### PR TITLE
Change zero-argument custom expression functions format with parens

### PR DESCRIPTION
**Pull request by calherries**
Changes zero-argument functions to read like `<function-name>()` instead of just `<function-name>` in the custom expression editor. The new format will still compile to the same MBQL data structure in JSON/EDN.

image

One side-effect of this is that all existing custom expressions that contain `count` without parentheses will now appear as `count()` to the user. Users can still write `count`, and when they close and open the custom expression editor again it will be rendered as `count()`.

[Slack thread](https://metaboat.slack.com/archives/C03SHMZ266R/p1668676917056199) for context on why we're making this change, which came from a discussion on [the now() function](https://github.com/metabase/metabase/pull/26548).

### CODE REVIEW

**Comment by calherries** [comment]
@nllho This PR requires some doc changes, namely adding `()` to the count and cumulativecount functions.

**Comment by ariya** [comment]
Here's another side-effect:

1. Type `2 * Count`
2. The autocomplete suggests two items, `Count(` and `CountIf(`
3. Press Enter to select the first one (default highlight)
4. Now we see the popup for the `Count` function, which is useful
5. But that also means the user has to either one the following to complete the expression:
a. type `)` to close the function
b. press Backspace to delete the `(`

Those extra clicks/keys were not necessary before.

I don't think this is the level of super-annoying but just be ready if we have incoming reports on such a similar issue.

**Review by nllho — APPROVED** [review]

**Comment by ariya** [comment]
@flamber Do you happen to recall the main reason to format any zero-arg function without the parentheses?

**Comment by calherries** [comment]
Closing for now, reasoning is in this [conversation](https://metaboat.slack.com/archives/C03SHMZ266R/p1669133407568439?thread_ts=1668676917.056199&cid=C03SHMZ266R)

from @ariya:
> The main reason is that the presence of (, and the autocomplete doesn't help by suggesting something, might lead the user to believe that they can do something like COUNT([SomeField]). See also this feature request for more details: https://github.com/metabase/metabase/issues/11558
To conclude, the most logical sequence IMHO is:
> 1) implement the feature requested in #11558
> 2) render Count (of a wildcard, no field) as COUNT() instead of COUNT

**Pull request closed without merging**
