### PR TITLE
[Epic PR] Make drill-through chiller (#26836)

### LINKED ISSUE #26836: [Epic] Make drill-through chiller
[Product doc](https://www.notion.so/metabase/Make-drill-through-chiller-0caf3f254da0463dbe7931f086f5ee28)

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/26836

### Description

Currently it's possible to "drill-through" data both in charts and tables by clicking on a data point/cell. The goal of this project is to simplify the menu with drill actions.

**Links**
- product doc 1: https://www.notion.so/metabase/Make-drill-through-chiller-0caf3f254da0463dbe7931f086f5ee28
- product doc 2: https://www.notion.so/metabase/Clean-up-and-add-view-details-action-to-drill-through-menus-on-unaggregated-rows-63cd958ec5884127a991b7af1d9435b3
- designs 1: https://www.figma.com/file/dlE39ZmU92l1dQcLi20fHH/Make-drill-through-chiller?node-id=101-2034&t=PVEI1hM6sWnCrqNE-0
- designs 2: https://www.figma.com/file/o2w0UgwuxNJKiSzPlaDElP/Add-view-details-action-to-drill-through-menus?node-id=0-1&t=YG238KaPfZh9CgG8-0

### Demo

https://github.com/metabase/metabase/assets/7983744/d14d0368-a643-4deb-aa38-a6111347d5f4

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30273)

### CODE REVIEW

**Review by cdeweyx — APPROVED** [review]
Looking good! No notes from me.

**Review by mazameli — CHANGES_REQUESTED** [review]
Found a bug: 
- Click on the View Details action
- Click outside the modal to close it
- Now you can't click on a table's column heading

Example: https://www.loom.com/share/66c4ed08c630492eb6cfeadc7607e4f9

**Comment by mazameli** [comment]
This could be a fault of my specs, but it would be great if we could fix the alignment here, moving "before, after, on, not on" to the left so that they left-align with the other text: 

image

**Comment by mazameli** [comment]
Gaps between icon and text look very slightly different here. We should standardize on 16px: 
image

**Comment by mazameli** [comment]
A tricky one here: the new alignment in this state is "correct" in that the sort button aligns to the left with the action icons below, but now optically looks off. The alignment that we have in `master` is preferred, as it looks correct optically. (This can happen when dealing with rounded containers/elements, like these rounded borders around the sort actions.)

image

**Review by mazameli — APPROVED** [review]
Nice!

**Pull request merged**
