### PR TITLE
Fix tooltips on dashboards

### LINKED ISSUE #846: sometimes tooltips don't show on dashboard cards
This is specific to dashboard cards.  Every time I've seen this happen if you click through to the QB the tooltips render there just fine.

### PR DESCRIPTION
**Pull request by tlrobinson**
Fixes #846

### CODE REVIEW

**Comment by agilliland** [comment]
This makes dashboards so much better!

I'm seeing one issue though.  Some of the tooltips for pie charts are ending up mispositioned ...

screen shot 2015-10-27 at 3 19 21 pm
screen shot 2015-10-27 at 3 18 50 pm

**Comment by tlrobinson** [comment]
Interesting, I'm not seeing this issue. Does it always happen?

**Comment by agilliland** [comment]
Yeah, I'm seeing it consistently.  Try putting lots of cards on the dashboards and/or include multiple pie charts.

**Comment by tlrobinson** [comment]
Looks like it only happens when the window is scrolled. Can you confirm that's the case for you too?

**Comment by agilliland** [comment]
Yep, that seems to be the case.

**Comment by tlrobinson** [comment]
Ok. It's also not a regression (just a lot more obvious, now that tooltips work consistently), but I can fix it as part of this PR if you like.

**Comment by agilliland** [comment]
cool.  yeah, i think we should fix that.

**Comment by tlrobinson** [comment]
Ok should be fixed.

**Pull request merged**
