### PR TITLE
Change query_cache.results column to correct blob type

### LINKED ISSUE #18815: Fix type of query_cache.results column in MySQL via new changeSet
In MySQL, The `query_cache.results` column in the app DB needs to be `LONGBLOB` in MySQL.  The #16095 change took care of fixing an old bug in the Liquibase configuration, for changeset ID 97 (which was many releases ago).

The trouble is that this will only take effect for new/blank MySQL app DB instances creates as of 0.42, and will not go back and fix any that are upgrading from older versions.  This issue is to fully close out the problem by creating a new changeset that will always change the column type to `${blob.type}` correctly, even on upgrade.

### PR DESCRIPTION
**Pull request by jeff303**
Add Liquibase changeSet to modifyDataType of query_cache.results to ${blob.type} (an idempotent operation on most DBs)

Add schema migrations test to confirm

### CODE REVIEW

**Comment by flamber** [comment]
It's running the migration, but it's changing to BLOB (huh?) instead of LONGBLOB. Tested `87715fd` on 10.5.8-MariaDB
```
...
		   169 Query	ALTER TABLE mb2.task_history MODIFY task_details LONGTEXT
		   169 Query	INSERT INTO mb2.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v42.00-062', 'jeff303', 'migrations/000_migrations.yaml', NOW(), 432, '8:fdab93c50c3432e2f5e58bedd9ac8a56', 'modifyDataType columnName=task_details, tableName=task_history', 'Added 0.42.0 - modify type of task_history.task_details from text to longtext on mysql,mariadb', 'EXECUTED', NULL, NULL, '3.6.3', '6051306090')
		   169 Query	COMMIT
		   169 Query	ALTER TABLE mb2.view_log MODIFY metadata LONGTEXT
		   169 Query	INSERT INTO mb2.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v42.00-063', 'jeff303', 'migrations/000_migrations.yaml', NOW(), 433, '8:b6b211459388818f7b5a738245c2ebc0', 'modifyDataType columnName=metadata, tableName=view_log', 'Added 0.42.0 - modify type of view_log.metadata from text to longtext on mysql,mariadb', 'EXECUTED', NULL, NULL, '3.6.3', '6051306090')
		   169 Query	COMMIT
		   169 Query	ALTER TABLE mb2.query_cache MODIFY results BLOB
211104 18:41:48	   169 Query	INSERT INTO mb2.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v42.00-064', 'jeff303', 'migrations/000_migrations.yaml', NOW(), 434, '8:d899883cca5c792dc632de90ac3af640', 'modifyDataType columnName=results, tableName=query_cache', 'Added 0.42.0 - fix type of query_cache.results on upgrade', 'EXECUTED', NULL, NULL, '3.6.3', '6051306090')
		   169 Query	COMMIT
		   169 Query	UPDATE mb2.DATABASECHANGELOGLOCK SET `LOCKED` = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
		   169 Query	COMMIT
...
```

**Comment by jeff303** [comment]
> It's running the migration, but it's changing to BLOB (huh?) instead of LONGBLOB. Tested `87715fd` on 10.5.8-MariaDB
> 
> ```
> ...
> 		   169 Query	ALTER TABLE mb2.task_history MODIFY task_details LONGTEXT
> 		   169 Query	INSERT INTO mb2.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v42.00-062', 'jeff303', 'migrations/000_migrations.yaml', NOW(), 432, '8:fdab93c50c3432e2f5e58bedd9ac8a56', 'modifyDataType columnName=task_details, tableName=task_history', 'Added 0.42.0 - modify type of task_history.task_details from text to longtext on mysql,mariadb', 'EXECUTED', NULL, NULL, '3.6.3', '6051306090')
> 		   169 Query	COMMIT
> 		   169 Query	ALTER TABLE mb2.view_log MODIFY metadata LONGTEXT
> 		   169 Query	INSERT INTO mb2.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v42.00-063', 'jeff303', 'migrations/000_migrations.yaml', NOW(), 433, '8:b6b211459388818f7b5a738245c2ebc0', 'modifyDataType columnName=metadata, tableName=view_log', 'Added 0.42.0 - modify type of view_log.metadata from text to longtext on mysql,mariadb', 'EXECUTED', NULL, NULL, '3.6.3', '6051306090')
> 		   169 Query	COMMIT
> 		   169 Query	ALTER TABLE mb2.query_cache MODIFY results BLOB
> 211104 18:41:48	   169 Query	INSERT INTO mb2.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v42.00-064', 'jeff303', 'migrations/000_migrations.yaml', NOW(), 434, '8:d899883cca5c792dc632de90ac3af640', 'modifyDataType columnName=results, tableName=query_cache', 'Added 0.42.0 - fix type of query_cache.results on upgrade', 'EXECUTED', NULL, NULL, '3.6.3', '6051306090')
> 		   169 Query	COMMIT
> 		   169 Query	UPDATE mb2.DATABASECHANGELOGLOCK SET `LOCKED` = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
> 		   169 Query	COMMIT
> ...
> ```

Blah, I forget that `${blob.type}` is NOT `LONGBLOB`, even for MariaDB/MySQL.  Hold on, I'll fix it (once I figure out why the test I added here passed, when it should have failed on MySQL).

**Comment by jeff303** [comment]
@flamber , ok, should be fixed now.

For the record, the reason the test erroneously passed was because the fix for #16095 actually _already did_ this (correctly) before my new migration ran.  So I updated the test to simulate the broken app DB (prior to #16095 being merged in) when it runs on MySQL.  A bit hacky but it should do what we need.

**Comment by flamber** [comment]
Booyah :tada: 
```
		   179 Query	ALTER TABLE mb2.view_log MODIFY metadata LONGTEXT
		   179 Query	INSERT INTO mb2.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v42.00-063', 'jeff303', 'migrations/000_migrations.yaml', NOW(), 433, '8:b6b211459388818f7b5a738245c2ebc0', 'modifyDataType columnName=metadata, tableName=view_log', 'Added 0.42.0 - modify type of view_log.metadata from text to longtext on mysql,mariadb', 'EXECUTED', NULL, NULL, '3.6.3', '6056766656')
		   179 Query	COMMIT
		   179 Query	ALTER TABLE mb2.query_cache MODIFY results LONGBLOB
		   179 Query	INSERT INTO mb2.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v42.00-064', 'jeff303', 'migrations/000_migrations.yaml', NOW(), 434, '8:9169e238663c5d036bd83428d2fa8e4b', 'modifyDataType columnName=results, tableName=query_cache', 'Added 0.42.0 - fix type of query_cache.results on upgrade (in case changeSet 97 was run before #16095)', 'EXECUTED', NULL, NULL, '3.6.3', '6056766656')
		   179 Query	COMMIT
```

**Review by dpsutton — APPROVED** [review]

**Review by camsaul — APPROVED** [review]

**Pull request merged**
