### PR TITLE
Fix z-order for all auth wrappers, so the boat animation doesn't overlay

### LINKED ISSUE #12658: Password reset doesn't work on low-resolution screens
**Describe the bug**
When trying to reset password on a low-resultion screen, the visual of the bridge overlays the password reset button and the button cannot be clicked.

**To Reproduce**
1. Have a screen with low resultion (1280x720)
2. Go to password reset link in Email when Admin resets password
3. Try clicking password reset button

**Expected behavior**

**Screenshots**
image

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome, but also with Edge
- Your operating system: Windows 10
- Metabase version: v0.35.3

**Severity**
Low

**Additional context**

### PR DESCRIPTION
**Pull request by flamber**
Fixes #12658

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
@flamber I have stumbled upon this exact issue while getting around Metabase for the very first time in the local dev environment. It seemed like a good issue for the first time contributor, so I wrote additional Cypress test in `frontend/test/metabase/scenarios/auth/signin.cy.spec.js`. No test was covering return from `/auth/forgot_password` back to `/auth/login`.

Will it be ok if I submit that test to the codebase?(I can also try to cover #12658)

If that is something you find useful, please just let me know should I open a separate PR or how to proceed?

Thanks in advance.

**Comment by flamber** [comment]
@nemanjaglumac That would be very welcomed :+1: Just open a new PR that also include the fix and then I'll close this PR.

**Comment by nemanjaglumac** [comment]
Will do :)
Thanks

**Comment by flamber** [comment]
Closed in favor of #12894

**Pull request closed without merging**
