### PR TITLE
Remove cache-related field from database creation form

### LINKED ISSUE #42741: The Admin / Performance page ignores the cache duration specified when creating a database
### Describe the bug

When you create a database, you're asked to set a cache invalidation policy. But the Admin / Performance page ignores this.

[Loom](https://www.loom.com/share/48d6459861054c58a48578e4e580e54c?sid=b7e7aacd-222b-4cd2-a4ab-fa480b1da6cb)

### To Reproduce

In Admin / Databases, create a new database and under advanced options specify a cache duration. Then go to Admin / Performance and look at the database.

Expected behavior: The database's cache invalidation policy in Admin / Performance should be set to Duration, with the specified number of hours.

Actual behavior: The database's cache invalidation policy in Admin / Performance is still "Use default".

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  }
}
```

### Severity

P1

### PR DESCRIPTION
**Pull request by rafpaf**
Removes the "Default cache duration" field from the database creation form.

Closes #42741

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#42808** <a href="https://app.graphite.dev/github/pr/metabase/metabase/42808?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by iethree — APPROVED** [review]
LGTM, make sure someone on the backend also gets a look at this before mergning 👍

**Comment by rafpaf** [comment]
### Merge activity

* **May 17, 8:30 AM EDT**: @rafpaf merged this pull request with [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/42808).

**Review by sansolovyov — COMMENTED** [review]
It's good, plus there are no backend changes, what can be better? 😁

**Pull request merged**
