### PR TITLE
Don’t enable Add Group button with string of white space as a group name

### LINKED ISSUE #22562: Frontend neither validates nor rejects empty string user group names
**Describe the bug**
Frontend neither validates nor rejects empty string user group names, but the backend explicitly asks for a non-blank string.

**Logs**
See the repro steps

**To Reproduce**
1. Go to Admin > People
2. Click on Groups tab
3. Click on "Create a group"
4. For the group name, enter just an empty space (or more empty spaces)
5. Notice that "Add" button becomes enabled
6. Click on "Add" button and observe the network tab in dev tools
7. `POST` request responds with `400` because backend asks for a non-blank string
```json
{"errors":{"name":"value must be a non-blank string."}}
```

**Expected behavior**
Frontend should have a validation for empty strings and not enable the "Add" button for empty strings

**Screenshots**
image

**Information about your Metabase Installation:**
local dev, `master`, c9de5ea342d15c8debee00e8c3a19af66d0ac1fb, H2, Sample Database

**Severity**
P3, because backend handles this correctly

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #22562

### How to test

1. Go to http://localhost:3000/admin/people/groups
2. Click on "Create a group"
3. For the group name, enter one or more empty spaces

"Add" button should not become enabled.

4. Add a group with a name surrounded by white spaces, such as "     mmmmm   ".

Saved group name should be trimmed, therefore be "mmmmm".

image

### CODE REVIEW

**Review by alxnddr — APPROVED** [review]

**Review by nemanjaglumac — APPROVED** [review]
Working nicely! :)
Thanks for fixing this so quickly.

**Review by nemanjaglumac — CHANGES_REQUESTED** [review]
Actually... wait.
Edit group name still doesn't handle empty spaces.

@gusaiani could you please fix that as well?

**Comment by gusaiani** [comment]
> Edit group name still doesn't handle empty spaces.

@nemanjaglumac, updated with that fix.

**Review by nemanjaglumac — APPROVED** [review]
@gusaiani thanks for addressing the extra comment. It does trim the whitespace, but there is only one final issue which is so minor that we can ignore it.

Let's say we already have to group "Foo", and you want to edit its name. If you add a bunch of empty spaces the "Add" button will be enabled.
image

but when you click on it will say that the group with that name already exists (which just confirms that the whitespace is trimmed)
image

Honestly, I'd just let this go but keep it in mind in case we run into this issue and someone complains about it.

**Pull request merged**
