### PR TITLE
Verify active database for `GET api/health`

### LINKED ISSUE #22500: Enhance health check endpoint (/api/health)
**Is your feature request related to a problem? Please describe.**
Currently our healthcheck endpoint acts like an init probe: the init process sets the initialization progress and then sets init-status/set-complete in the end to which the endpoint acts like a checker: if the process completed it will return 200 or if it hasn't it will return the init progress with a 503 status.

But what happens if Metabase is not healthy but it has finished initializing? e.g. the app database does not have enough connections, then we will respond with a 200 but the app won't be able to serve any requests

**Describe the solution you'd like**
Define a simple (performance-wise) but integral health checking process to enhance this endpoint

**Describe alternatives you've considered**
Otherwise we have to hit / along /api/health, to force the app to do something to know if it's healthy or not

**How important is this feature to you?**
Very important, and for any kind of deployment

**Additional context**
NA

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes https://github.com/metabase/metabase/issues/22500

Previously unconditionally responded with 200, status "ok" if we were
done initializing, even when we had 1500 stale db connections
somehow (:scream:).

Now attempt to connect to the database:

```shell
❯ http get localhost:3000/api/health -pb
{
    "status": "ok"
}

❯ http get localhost:3000/api/health
HTTP/1.1 503 Service Unavailable
...
{
    "status": "Error getting db connection"
}
```

and logging to the server (excuse quick error message used here)
```
2022-05-10 22:05:16,911 WARN server.routes :: Error in api/health database check
java.lang.ArithmeticException: Divide by zero
	at clojure.lang.Numbers.divide(Numbers.java:190)
	at clojure.lang.Numbers.divide(Numbers.java:3911)
	at metabase.server.routes$fn__122320.invokeStatic(routes.clj:51)
```

### CODE REVIEW

**Review by imrkd — APPROVED** [review]
LGTM 👍

**Comment by rlotun** [comment]
@dpsutton and @imrkd is this worth backporting? seems like an innocuous change and if we get it into the 43.1 release in time for a fleet upgrade it could help cloud out a lot (vs waiting 2 months for 44). wdyt?

**Comment by imrkd** [comment]
@rlotun 100%, my intention was to get this into 43.1 or 43.2 at the latest.

**Comment by rlotun** [comment]
feel free to add the `backport` label and add the linked issue to the 43.1 milestone. the `backport` label should still work even after a PR has been merged.

**Comment by dpsutton** [comment]
yes i thought i had added the `backport` label to this already. i did it on another PR and thought it was on this one as well

**Pull request merged**
