### PR TITLE
Handle absolute link for LinkCards on sub-path properly

### LINKED ISSUE #30893: Absolute links don't work on link cards when Metabase is on a sub-path
### Describe the bug

Entire repro is on https://github.com/metabase/metabase/issues/30891

### To Reproduce

1) set up Metabase on a sub-path with https://github.com/paoliniluis/metabase-subpath
2) create a dashboard and a link to an absolute URL
3) try to click that link it won't work

### Expected behavior

it should take the user to the absolute path

### Logs

_No response_

### Information about your Metabase installation

```JSON
1.46.2
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/30893

### Description

If you run the application on subpath (e.g. on localhost:9000/metabase, not just localhost:9000), the links to LinkCards which contain absolute links led to the host instead of correct path.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. clone https://github.com/paoliniluis/metabase-subpath
2. build metabase.jar using `./bin/build.sh` and copy it into `metabase-subpath/metabase`
3. update docker file in `metabase-subpath/metabase` (replace line 7 `ADD https://downloads.metabase.com/enterprise/latest/metabase.jar .` with `COPY metabase.jar /app/metabase.jar`)
4. run the subpath following the readme (update emdedding token and run `docker compose up`)
5. create a dashboard -> linkCard -> put there `https://google.com` and verify that after saving click on the link leads to the `google.com`

### Demo

https://www.loom.com/share/de82cf2ebd214c92860c4716f004a0cf

### Checklist

~- [ ] Tests have been added/updated to cover changes in this PR~

I talked to @nemanjaglumac and it looks like currently we can't create a e2e test for sub-path testing, but it's a crucial part of the testing, so we have to rely on manual testing instead

### CODE REVIEW

**Comment by uladzimirdev** [comment]
@iethree any suggestions on how to test this? 😄

**Review by WiNloSt — APPROVED** [review]
Works great for me. It's mind-boggling why `react-router` doesn't render this correctly in subpath. I checked that we passed correct `to` prop to `Link` but it still render the wrong one 🤔 

Also, approving despite not having test because 

>I talked to @nemanjaglumac and it looks like currently we can't create a e2e test for sub-path testing, but it's a crucial part of the testing, so we have to rely on manual testing instead

**Comment by uladzimirdev** [comment]
> Works great for me. It's mind-boggling why react-router doesn't render this correctly in subpath. I checked that we passed correct to prop to Link but it still render the wrong one 🤔

@WiNloSt yup, I spent a lot of time trying to understand it, maybe the reason is in not propertly handled basename parameter, as in react-router 3 which we use there is no such option.

**Review by iethree — APPROVED** [review]
this is an insane edge case. any ideas how to make sure others don't fall into this in the future?

**Comment by uladzimirdev** [comment]
> this is an insane edge case. any ideas how to make sure others don't fall into this in the future?

I'd bet on e2e, but it's not a case atm. So maybe upgrade to latest react-router would handle it properly @iethree

**Review by dragonsahead — APPROVED** [review]
works for me :)

**Pull request merged**
