### PR TITLE
Add parameters to GUI query builder & make permissionless title drilldown use parameters

### PR DESCRIPTION
**Pull request by daltojohnso**
https://github.com/metabase/metaboat/issues/144

This PR makes it so that when a user does not have underlying data permissions a click on the dashcard title will take the user to a query builder view of the dashcard with mapped parameters still visible and applied if values are present.

Quick run-through of behavior when a user has no data permissions:

https://user-images.githubusercontent.com/13057258/144541272-9b309aa0-e6dd-41c5-b5f7-f9c194716036.mov

Users with permissions should see the same behavior as before:

https://user-images.githubusercontent.com/13057258/144541328-4fda09b3-166b-43d0-b5e8-21a87bc75ece.mov

Here are a few details of the implementation:

- The GUI query builder gets a `<SyncedParametersList>` component that takes `parameters` from the question instance (passed via the card in the url) and `parameterValues` from the url’s query, stored in redux.

- In order for dashboard parameters to be used with a card, we need to run the query for the card using the new `/api/dashboard/:dashboardId/card/:cardId/query` endpoint, meaning I need access to a `dashboardId` in the query builder. For now, I’m setting it on the `card` object itself at `card.dashboardId` using the new `Question.prototype.setDashboardId` method. This mimics what we currently do for `parameters` and `parameterValues`. I don’t think this is ideal since none of these properties are actual properties on cards; instead, they are thrown on to make generating URLs easier. I think we probably need some new abstractions in metabase-lib to better handle cases where we need data on top of what is in a `card` (I’m afraid to say we need more classes that extend Question, but perhaps we can compose this data in a pleasant way without adding to the class hierarchy). I think it makes sense to revisit this topic in subsequent work.

- Most of the code change in this PR (besides unit tests & e2e tests) is to make our question URL generation properly carry parameters and parameter values to the query builder. I’ve killed the crufty, old function `questionUrlWithParameters` and am instead relying on a beefed up `Question.prototype.getUrlWithParameters` method call to generate the proper query builder url. There are three branches to this function: structured & editable queries have the parameters added to the question as additional filters; structured & uneditable queries have the parameters serialized with the rest of the card and the parameter values added as a url query; native queries have the parameter values remapped to the ids of the query’s template tags.

- There are a few tweaks to query builder initialization logic to ensure `parameters` on a serialized card are held onto and used.

- Click behavior code (`DashboardClickDrill.jsx`) is a bit weird in that you already have access to the parameter values in the correct format to send to the query builder, so the logic for building the URL is a bit different from dashcard title clicking. Ideally we'd make these two areas more similar.

### CODE REVIEW

**Comment by gusaiani** [comment]
> This PR makes it so that when a user does not have underlying data permissions…

@daltojohnso, how exactly do I set up permissions for a user to not have any data permissions as you mention above?

**Comment by daltojohnso** [comment]
@gusaiani -- sorry, I should've included that in the description!

As an admin...

1. On the Data permissions page (`/admin/permissions/data/group`), select the All Users option in the sidebar and then in the "Data access" column, select "No self-service".
2. Create a new user via the `/admin/people` route -- by default the user ought to be a "normal" user and not an admin
3. Create questions/dashboard using the admin and then open the saved question/dashboard links with the normal user -- I typically keep an incognito window open so that I can have both logged in at the same time.

**Review by kulyk — APPROVED** [review]
Nice!

**Comment by daltojohnso** [comment]
@flamber would you mind playing with this change to make sure there aren't any weird or undesirable states?

**Review by flamber — APPROVED** [review]
This seems to work well - and looks like it might fix other issues too (or at least lay most of the foundation) - #12720 and #15163
Though, this is just a really hard issue to test thoroughly. I've done my best. Two things:

----

If I revoke access to the original dashboard and refresh the question that I drill-through with a nodata-user (or just change the `dashboardId` in the query hash), then I get this, which is not very helpful (only the logs will give me a hint of the problem). Not blocking this PR, but would likely block the release.
image

----

Regarding #12720, it only works when the dashcard hasn't been modified (#13595) otherwise it will throw permission error.
And it will show different types of permission errors depending on if the user has nodata-accesss at all:
image
Or if I give access to another table (not related to the dashcard):
image

**Comment by daltojohnso** [comment]
Thanks for testing, @flamber. I'll go ahead and merge this PR and then follow it up with fixes for the first and third problems you noted. Those two shouldn't be too difficult. I know what's going wrong with the second problem regarding viz changes affecting the ability to run a card, but I'll need to dig into more to fully understand the problem.

**Comment by flamber** [comment]
@daltojohnso So I had a Product question, and then I gave access to People (basically any other table)
image

**Pull request merged**
