### PR TITLE
Dedupe and Minify CSS

### LINKED ISSUE #13219: CSS is included twice
@kdoh spotted that we're including styles twice:

image

This issue is happening in production builds and seems to include the same styles in both "app-main" and "styles".

### PR DESCRIPTION
**Pull request by iethree**
## Before
2 problems:
1. We were loading many (but not all) of our css styles twice (namely, those in the `css/core/` directory)
2. We were also not minifying our css

As you can see on the body class, the same styles are included in `app-main.css` and `styles.css`, and we load a total of 46kb of css

Screenshot from 2022-04-27 16-18-13
Screenshot from 2022-04-27 15-56-30

Both problems waste time and network resources, minorly impacting performance on production builds. As it turns out, problem no. 2 can be the solution to problem no. 1.

## Changes

1. Remove the largely duplicative `styles` bundle. This bundle included a build of all the css in our `css/` directory. Much of this was also included  in the `app-main` bundle because that bundle included all the css in the `css/core/` directory. The latter bundle also included component-specific css scattered throughout the repository.
2. Include the base css file in `app.js` ensuring that all styles are included int he production build.
4. Add css minification which, in addition to minifying our styles, also deduplicates all the duplciate styles from `css/core/`

By combining all the css into a single minified bundle, we can load a single 26kb css file, with no duplicate styles. Resolves https://github.com/metabase/metabase/issues/13219

Screenshot from 2022-04-27 15-56-59

Screenshot from 2022-04-27 16-33-00

## To Verify

- run `WEBPACK_BUILD="production" yarn build` on master and see the duplicate styles on the html body
- run the same build on this branch, and see the lack of duplicate styles.

## Side effects

- While minification seems like it would take longer, not building an extra bundle seems to shave about 10s off the production build time on my machine :grin: 
- Dev builds seem about ~1s faster, but it's hard to really tell.
- potentially better page load performance in the browser, because it's dealing with parsing half of the css. (not sure how to measure this)

### CODE REVIEW

**Comment by ariya** [comment]
This is great @iethree! Make sure you also test and verify that embedding still works properly.

**Comment by iethree** [comment]
I think i broke CI by adding a new dependency?

**Comment by ariya** [comment]
> I think i broke CI by adding a new dependency?

Your lockfile is out of sync. Try it by running: `yarn install --frozen-lockfile`.

**Comment by nemanjaglumac** [comment]
> > I think i broke CI by adding a new dependency?
> 
> Your lockfile is out of sync. Try it by running: `yarn install --frozen-lockfile`.

Or `yarn add css-minimizer-webpack-plugin` which will both add the dependency and update the `yarn.lock` file.

**Review by alxnddr — COMMENTED** [review]
Layout of some select components got broken:
Screenshot 2022-04-28 at 14 38 48

**Comment by alxnddr** [comment]
Publicly shared dashboards/questions looks fine

**Comment by iethree** [comment]
Ok this is pretty gnarly. The issue that @alxnddr  found is because the order of the css classes changing. In the case of that select, it can be fixed by moving the core css classes to the end of the imports (so `.flex` overrides  the `inline-block` property of `.AdminSelect`). BUT, that in turn messes up other things.

Fundamentally, an unknown number of elements in the application depend on a big chunk of css being imported twice, and it's probably more trouble than it's worth at this point to find and fix those (dozens? hundreds? thousands?) of cases. This will likely be easier to fix down the road once more of our css is isolated in styled components.

I think I'll close this PR unless anyone tells me its worthwhile to keep working on.

**Pull request closed without merging**
