### PR TITLE
Fix joined dimension default + smarter join aliases

### LINKED ISSUE #10441: Default granularity of time columns on joined tables not showing up
If you join to a table and then go to break it out by a time column, the default granularity (i.e. Day) is not showing up, either in the notebook or summarize sidebar. You can still click on that area on the right to select the granularity, but it's not obvious:

image

Screen Shot 2019-07-31 at 1 55 25 PM

### LINKED ISSUE #10548: We should improve default titles for columns in joined saved questions
Right now columns brought over from saved questions look like `table_card__57 → Created At: Week`. There's a challenge here because we probably don't want to include the full title in each joined column heading, but we should make it look a bit nicer than this.

image

Ideas:
1. Use the word "Question" plus the ID number, like: 
`Question 57 → Created At: Week` 
This option makes it easier to distinguish columns when joining from multiple saved questions, but doesn't really tell you what the saved question is. Visually, an improvement.

2. Use the first `n` characters of the saved question plus an elipses like:
 `Revenue in las… → Created At: Week`
A bit more human readable-ish, but would be annoying if you're joining "Revenue in last 30 days from Texas" and also "Revenue in last 30 days from California," since you wouldn't be able to distinguish them.

Option 1 seems like a simple enough enhancement.

### LINKED ISSUE #10550: Explicitly joined fields should be prefixed with join alias, which should be set to foreign key display_name by default
Similar to #10549

- [x] backend: columns from a `joined-field` should be prefixed with the join `alias` instead of the table name
- [x] frontend: join `alias` should be set to the foreign key field's `display_name` with trailing "id" removed 

Screen Shot 2019-08-09 at 4 42 53 PM

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #10441
Resolves #10550 (frontend)
Resolves #10548

Everything looks good

Implicit joins:

Screenshot 2019-08-12 17 30 56

Explicit joins:

Screenshot 2019-08-12 17 30 41

### CODE REVIEW

**Review by mazameli — APPROVED** [review]
UI looks right, and this does seem to fix #10441.

**Comment by mazameli** [comment]
@camsaul @paulrosenzweig Mind giving this a review when you get a minute please?

**Review by paulrosenzweig — APPROVED** [review]
I definitely don't understand all the relevant code involved here, but from what I see it makes sense 👍

**Comment by tlrobinson** [comment]
@paulrosenzweig Good enough for me :)

**Pull request merged**
