### PR TITLE
Remove unneeded URIs from content security policy header

### PR DESCRIPTION
**Pull request by gusaiani**
Here we remove URIs that we no longer use to load resources.

### CODE REVIEW

**Comment by gusaiani** [comment]
@alxnddr, a Loom here to make sure I'm reproducing it correctly:

https://www.loom.com/share/d71669a452a94a9abba0933efc112d66?from_recorder=1&focus_title=1

**Review by alxnddr — COMMENTED** [review]
@gusaiani seems like google identity library cannot access some resources:
Screenshot 2022-06-03 at 14 55 20

**Review by flamber — COMMENTED** [review]
It looks like the gstatic and googleapis were part of maps.google, which we moved away from several years ago (#3617) in favor of OSM.
https://developers.google.com/maps/documentation/javascript/content-security-policy

**Comment by gusaiani** [comment]
@alxnddr I've restored /accounts/, thanks for signaling it.

**Review by alxnddr — APPROVED** [review]

**Pull request merged**
