### PR TITLE
change from SVG cursors on dashboard card editing to normal css cursors.

### LINKED ISSUE #1729: Convert custom cursors from SVG to PNG so they work with Mac App
The cursor doesn't change to a resize icon when placed on the sides or corners of the card in a dashboard.

Resizing/dragging still works.

### PR DESCRIPTION
**Pull request by agilliland**
resolves #1729

### CODE REVIEW

**Comment by agilliland** [comment]
@kdoh @tlrobinson give this a quick double check when you get a chance and make sure i put this in the right place.

**Comment by kdoh** [comment]
If those assets aren't being used anymore we should probably ```git rm``` those as well.

**Comment by agilliland** [comment]
:+1:

**Comment by kdoh** [comment]
:shipit:

**Pull request merged**
