### PR TITLE
Fix table deactivation to be table-specific

### PR DESCRIPTION
**Pull request by asyncopation**
Hello,

I believe there is a Synchronization bug in the existing `retire-tables` functionality which currently deactivates all tables that share the same schema as the current table in the `old-tables` sequence.  Therefore, currently the tables that display in the log do not reflect all items being deactivated.

I believe this bug was never caught because the unintended deactivated tables would be found again upon the following Sync.  I believe this is related to existing issues like #6825.

This change adds the `table-name` filter which I believe was the original intention from line 117.

This is my first contribution to the project, so if I am missing some requirements, please forgive me and point me in the right direction.  I have signed the "Contributor License Agreement", but have not added any tests since this is a very small change.

### CODE REVIEW

**Comment by sbelak** [comment]
LGTM

**Comment by sbelak** [comment]
Thanks for the PR and welcome to the family. Would you mind adding a test for this (and which fails on existing version).

**Comment by camsaul** [comment]
Great catch. I'll add a test for this. We should definitely pull this into the next release.

**Comment by camsaul** [comment]
Thanks for this PR @asyncopation. I've went ahead and added a test for this and will merge it as part of PR #9638

**Comment by asyncopation** [comment]
Apologies for the wait!  I am new to Clojure and it was taking some time to get up to speed, so thanks for adding the test @camsaul.

**Pull request closed without merging**
