### PR TITLE
Bundle static viz charting code

### PR DESCRIPTION
**Pull request by ariya**
How to check? Run `yarn build-static-viz`.

The bundle should be created as `resources/frontend_client/app/dist/lib-static-viz.bundle.js`. This bundle.js is pretty self-contained. It exposes a global variable called `StaticViz`, which has the member function `RenderChart`.

There is no browser nor Node.js-specific calls in the bundle, it should run on a vanilla JavaScript interpreter (I tested with [GraalVM JS](https://github.com/oracle/graaljs), SpiderMonkey, etc.

You can e.g. quickly check this via Node.js REPL, too:
```
const vm = require('vm');
const fs = require('fs');
const BUNDLE = 'resources/frontend_client/app/dist/lib-static-viz.bundle.js';
vm.runInThisContext(fs.readFileSync(BUNDLE));
console.log(typeof StaticViz.RenderChart); // 'function'
```

### CODE REVIEW

**Comment by dpsutton** [comment]
@ariya love it but have some operational questions.

1. I see that the build will create this file. But presumably we need this for dev. Is that a separate task we will know we need to prep, or can that task be added to the normal `yarn build-hot` so that the file exists for dev automatically?
2. If this is something generated often, should the file be added to the `.gitignore` so that each local copy has the output and we don't mess about with committing and dealing with conflicts?
3. This file is currently checked in. Do we need to excise it or should this PR include an updated version of it built from this change?

**Comment by ariya** [comment]
> 1. I see that the build will create this file. But presumably we need this for dev. Is that a separate task we will know we need to prep, or can that task be added to the normal `yarn build-hot` so that the file exists for dev automatically?

I think so. Would love heard what workflow @kdoh has in mind for e.g. tweaking the charting code day-to-day from a browser? Making it part of _internal is a possibility, but I'm all ears.

> 2. If this is something generated often, should the file be added to the `.gitignore` so that each local copy has the output and we don't mess about with committing and dealing with conflicts?

`resources/frontend_client/app/dist` is already in  `.gitignore`. Am I missing something?

> 3. This file is currently checked in. Do we need to excise it or should this PR include an updated version of it built from this change?

Which file is "This file"?

**Comment by dpsutton** [comment]
@ariya I've been using the file located here: `https://github.com/metabase/metabase/tree/master/resources/frontend_shared` It's a sibling to `color_selector.js`. I got turned around since it is checked into the branch we've been using but I think that's just a convenience while we develop it.

**Comment by ariya** [comment]
> ... but I think that's just a convenience while we develop it.

Correct. That won't be needed anymore once this PR is merged.

**Review by dpsutton — APPROVED** [review]

**Review by kdoh — APPROVED** [review]

**Pull request merged**
