### PR TITLE
Data model flex fixes

### LINKED ISSUE #2464: Segments & Metrics forms not stretching full width of page
This is against 0.17.0-snapshot on Chrome.

screen shot 2016-04-28 at 2 45 23 pm

### PR DESCRIPTION
**Pull request by kdoh**
fixes #2464 #2313

### CODE REVIEW

**Comment by agilliland** [comment]
@kdoh on the creation screens the horizontal bar at the bottom of the page no longer extends the full width and the buttons look a little misaligned now.

**Comment by kdoh** [comment]
Ah. Looks like I'd only checked it on edit. Good catch.

**Comment by agilliland** [comment]
Everything else looks good though 👍

**Comment by agilliland** [comment]
cool.  lgtm now.

**Pull request merged**
