### PR TITLE
Fix combined series dashcard not showing correct column title in tooltip

### LINKED ISSUE #16249: Tooltip of combined dashboard cards does not show the correct column title
**Describe the bug**
When combining two cards on a dashboard, and changing the series name on the dashboard, then it shows the first series name in the tooltip for both series. When using CE, then it doesn't change the name for the second series.
Continuation of #11395, but for dashboard combined cards. Regression since 0.38.3.

Note for developers: Any reason why the tooltip is only showing values for a single question, when combined? Normally with multi-series, it would show all the series values, but perhaps this is a limitation, when combining.

**To Reproduce**
1. Create 4 questions - Custom question > Sample Dataset
   1. Orders - summarize CE `Sum(Total)` called `CE` group by CreatedAt:Year - save as "Q1"
   2. Orders - summarize CE `Average(Subtotal)` called `CE` group by CreatedAt:Year - save as "Q2"
   3. Orders - summarize "Sum of Total" group by CreatedAt:Year - save as "Q3"
   4. Products - summarize "Sum of Price" group by CreatedAt:Year - save as "Q4"
2. On a dashboard. CE-test:
   1. Add "Q1"
   2. Hover the "Q1" card and click "Add series" and add "Q2"
   3. Hover the combined Q1+Q2 card and click "Visualization options"
   4. Change the names of the series to something unique for each series
3. Hover the lines of the Q1+Q2 card
image
4. Do the same as step 2 again, but using Q3 and Q4 instead of Q1 and Q2
5. Hover the lines of the Q3+Q4 card
image

**Information about your Metabase Installation:**
Tested 0.38.2 thru 0.39.2 and commit `0401256` (almost 0.39.3) - regression since 0.38.3

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #16249 

I took @ranquild's original fix for this particular bug from https://github.com/metabase/metabase/pull/17946 but as you can see from the comments below there are a lot of very specific scenarios that needed handling. Gross stuff. To summarize:

1. #16249 seems to be specific to dashcards where we've added additional series. These additional series have odd viz settings keys to try to ensure they are unique.
2. When a single series is added to a dashcard, its viz settings key is USUALLY the card name.
3. When a multi series is added to a dashcard, its viz settings key is the card name combined with the column display name
4. Sometimes, the card name is not the card name but a column name -- see https://github.com/metabase/metabase/blob/a5d951b0a77ca85856fe1d651b6e98c480225746/frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx#L524 for where the card name is altered. I've added a prop to this "card" so that we can preserve the original card name in the object

The old regression #18210 was hitting the scenario where the card name is a column name. In this scenario we should be relying on the column name as the viz settings key. Confused yet?

In addition to the above changes to `apply_tooltip`, I needed to lace the `dashboard` object through to the `ChartSettings` component so that we have access to it when applying tooltips to Visualizations within the modal.

**Testing**
Follow the repro steps in #16249 to reproduce the original issue
Follow the repro steps in #18210 to make sure we are not re-regressing
If you can think of other ways to test this, go for it.

### CODE REVIEW

**Comment by daltojohnso** [comment]
https://github.com/metabase/metabase/pull/21267/commits/959a238013717a19c811f4bbf4dfb25e897b7616 handles one scenario, but it appears there are more. For example, a query like this won't show the correct tooltip titles:
Screen Shot 2022-03-28 at 2 11 32 PM

**Comment by daltojohnso** [comment]
Aaaaaand here's a scenario where we always need `card.name`...

create Q1
Screen Shot 2022-03-28 at 3 40 33 PM

Create Q2
Screen Shot 2022-03-28 at 3 40 49 PM

Add Q1 to dashboard and then add Q2 to it via the little "add series" button.

When you do this, altering column titles via the viz options on the dashcard stores the titles for BOTH cards using `card.name`, not `col.name`

**Review by flamber — COMMENTED** [review]
I'm still seeing the incorrect tooltip for the second question - no matter if I have single metrics or multiple in each question. These are Custom Expression metrics.

Multiple - 0:33-0:36

https://user-images.githubusercontent.com/1447303/161299742-a91296c5-6d4b-4c08-b9e1-ed57e06ad2cd.mp4

Single - 0:14

https://user-images.githubusercontent.com/1447303/161299967-fecc5095-b5d8-4418-9288-d839c59ab2b3.mp4

**Comment by daltojohnso** [comment]
@flamber -- thanks for testing. Apparently, we were never passing the `dashboard` object to this modal, so the code I added only worked once you looked at it on the dashboard. I think it should work now.

**Review by flamber — COMMENTED** [review]
It's still doing something strange on multi-series, while it seems to be working correctly on single-series.

Multi-series in both questions - uses incorrect references:

https://user-images.githubusercontent.com/1447303/161743601-2db98c17-8322-49e1-84ac-1f6a13d16ac9.mp4

Single series in both questions - seems to work correctly now:

https://user-images.githubusercontent.com/1447303/161744440-75924e66-cc04-4f1e-9350-b7bb667b2bcf.mp4

**Comment by daltojohnso** [comment]
This bug fix just gets worse and worse. Does this look right?

Uploading Screen Recording 2022-04-05 at 12.23.01 PM.mov…

**Review by flamber — APPROVED** [review]
Excellent! Given the amount of time that multiple people have spend on this, it would be wonderful to have a test, since I'm afraid of regressions in this area due to the complexity.
I guess the "Difficulty:Hard" label on the issue was spot on ;-)

PS - don't waste time backporting this.

https://user-images.githubusercontent.com/1447303/161840653-adc71b3e-ed98-4111-9600-17aad4f9d78d.mp4

**Comment by daltojohnso** [comment]
I agree -- I'll work on a batch of e2e tests for this fix. I think there are a few different scenarios worth testing.

**Review by ranquild — APPROVED** [review]

**Comment by daltojohnso** [comment]
@nemanjaglumac mind taking a look at the e2e tests I wrote for this?

**Review by nemanjaglumac — APPROVED** [review]
Great job with E2E tests.
Awesome abstractions!

Thank you

**Pull request merged**
