### PR TITLE
Cancel query button, and actually cancel the /api/dataset request

### LINKED ISSUE #1547: Allow refreshing query result even if the query hasn't changed
e.x. you'd like to see how changes you're making to the db are reflected in a query

### LINKED ISSUE #2181: Allow users to edit & re-run a query before the previous query finishes
I wrote a bad query- it took too long.  I had to wait a minute until I got the "Your question took too long" screen.  

I realized while it was running that it was poorly written and fixed it in the minute before it timed out

After that, there was no "retry" button.  If I make superficial changes to the query the retry button came back, but it seems to be comparing my query to the contents of the editor as of the last time the query timed out, not the actual query that ran

### LINKED ISSUE #2399: Allow users to cancel a query execution at the database
Mentioned by @agilliland in this [ticket](https://github.com/metabase/metabase/issues/2181) as a candidate for being split into a different feature request.

I was running a long running query. I realized after I hit run query that I forgot to filter the data. I then had to wait for it to complete. 

I wanted a cancel button.  Obviously I can just refresh the page to get this effect but a cancel button seems better/safer.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #2181 
Resolves #1547

### CODE REVIEW

**Comment by tlrobinson** [comment]
ire9822e7d

**Comment by agilliland** [comment]
@kdoh @tlrobinson where are we on this one?

**Comment by agilliland** [comment]
Are we g2g here?

**Comment by mukundvis** [comment]
@tlrobinson I used this feature, but this doesn't seem to kill the query in MySQL right? But shouldn't that also be done? Because as a user, I don't care about the response since I've clicked "Cancel". So, when the query is actually bad and takes a really long time, why should it still be running in the background? Hope I'm not missing something here?

**Comment by tlrobinson** [comment]
Ideally, yes. That's something we'd like to do but not currently implemented, and isn't possible or is "best effort" in many dbs (not sure about MySQL specifically). See #2399

**Pull request merged**
