### PR TITLE
Reduce boilerplate in permissions checks

### PR DESCRIPTION
**Pull request by crisptrutski**
### Description

This is a purely cosmetic change to reduce the repetition and density of some recently added permission checks.

Not sure if this is a good idea, but creating the PR was probably easier than explaining in a message 😄 

### How to verify

Run `metabase.api.search-test/indexed-entity-perm-test` and confirm that it still passes.

### CODE REVIEW

**Review by noahmoss — APPROVED** [review]
nice idea, thanks!

**Comment by crisptrutski** [comment]
A slightly more fancy idea would be to have a generic helper which takes strings like "/db/:model.database_id/", and generalizes to different lengths and patterns. Probably YAGNI 🙂

**Comment by crisptrutski** [comment]
@noahmoss do I need to get approval from anyone else, or free to merge?

**Comment by darksciencebase** [comment]
@crisptrutski free to merge

**Pull request merged**
