### PR TITLE
Zooming in on email attachment tables on pulse (attacks #18755)

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to #18755. Underlying problem is purported to be not being zoomed out enough. This one just zooms out. This won't work on FF but the underlying problem only occurs in mobile.

Trouble with using `transform: scale` is that the label divs don't zoom with it - this would turn a 1 liner fix into a 100 liner total change of CSS fix, unless you've got better ideas to execute that one

I saw reports that you used to be able to permanently enable scroll bars by setting `overflow-x: scroll` but I could not replicate being able to permanently enable scroll bars inside of emails.

There are purported methods of being able to do scrolling for overflow and zooming, but I can't find any way of doing it w/o JS. (for example: https://stackoverflow.com/questions/34196639/zooming-in-overflow-scroll)

### CODE REVIEW

**Comment by noahmoss** [comment]
Just tested it out locally. The data on mobile is definitely more readable than before, however the rows are very cramped and size of the text below the table has become oddly proportioned:

 
 
 In a (non-Firefox) browser the font size of the table is also extremely small and pretty hard to read:

image

Maybe a less aggressive zoom (0.8?) would be a decent compromise between these different issues? cc @kdoh for design input

**Review by kdoh — CHANGES_REQUESTED** [review]
I don't think we want to solve this via a CSS scale. I'd rather try and claw back more space by adjusting font-size margin and padding a little bit. Legibility gets weird in unexpected ways otherwise.

While I was testing this out I also noticed that it seems like the mobile css from #17825 isn't showing up when I viewed an email in Mail.app on the iPhone. (Although it did seem like it was in the screenshot added by the reporting user).  Here's what I saw which is definitely not enough content. 
IMG_1D9940A41925-1
 
So ultimately I think this might be a more involved CSS fix to get the right balance between being able to read actual values without having to zoom, and being able to see the overall context a bit more.

**Comment by alxnddr** [comment]
@kdoh we can show table outer borders so that the missing border on the right will mean that there are more columns to scroll to (but it looks worse in my opinion): 
Screenshot 2022-01-13 at 00 13 47

Besides that, I decreased padding a bit:

**Before**
Screenshot 2022-01-13 at 00 18 04

**After**
Screenshot 2022-01-13 at 00 16 40

What do you think?

**Comment by alxnddr** [comment]
Should we close this PR since https://github.com/metabase/metabase/pull/19654 is merged?

**Comment by howonlee** [comment]
SGTM

**Pull request closed without merging**
