### PR TITLE
Allow small number and markdown cards

### LINKED ISSUE #29417: Remove minimum size constraint for Markdown and Number dashboard cards
We are unnecessarily restrictive in what size we let users make certain dashboard cards. In the case that something you made works tiny and you really want it tiny, there shouldn’t be a hard constraint stopping you. The two most common examples of this are **Markdown** and **Number** cards which have a 3x1 and 3x3 min size respectively.

Let's drop both Markdown and Number cards to 1x1 min size and see how it feels. Note that this shouldn't affect the starting default size at all. Related issues: https://github.com/metabase/metabase/issues/8475 https://github.com/metabase/metabase/issues/5662

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/29417

### Description

This separates out dashcard `minSize` and `defaultSize` properties to allow scalar and text visualizations to get smaller than their default sizes.

Screen Shot 2023-03-24 at 1 18 46 PM

### How to verify

1. Add a markdown card to a dashboard
2. it should be 4x4
3. see that you can shrink it to 1x1
4. Add a question with a scalar visualization (e.g. `SELECT count(*) FROM ORDERS`) to a dashboard
5. see that it starts out at 3x3
6. see that you can shrink it to 1x1 if you want.

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29537)

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
Can you please tweak the scalar's font-size so it makes sense having them 1x1?
Screen Shot 2023-03-27 at 12 38 16 PM

**Comment by alxnddr** [comment]
Even a single digit with the question name do not look great:
Screen Shot 2023-03-27 at 12 41 28 PM

Wdyt about reducing the font size, rounding integers, and adding a tooltip to move the question name there?
cc @cdeweyx

**Comment by iethree** [comment]
@alxnddr @cdeweyx reducing the minimum number size was easy. What do you think about hiding the card title if height or width is 1 behind an ellipsis/tooltip?

elipsIfytName

**Review by alxnddr — APPROVED** [review]

**Comment by iethree** [comment]
> :) We just talked about this feature and we would love to make use of it, when wil this feature be released?

This will be released as part of the upcoming v.47.  Soon ™️

**Comment by johndaniels88** [comment]
I all! I am trying this on v56 and the minimum size of a simple number is still 2x2. What do I need to do to be able to shrink it to 1x1? Thanks for your help!!

**Pull request merged**
