### PR TITLE
[skip ci] this seems to clean things up

### PR DESCRIPTION
**Pull request by salsakran**
Fix the things that broke fixing #3302

### CODE REVIEW

**Comment by salsakran** [comment]
think this resolved things, @camsaul

**Comment by camsaul** [comment]
Did you look at this with jekyll? I think this is pretty close to what I had originally / I thought indenting code blocks like that broke formatting?

**Comment by salsakran** [comment]
Yup. It looks good on jekyll. There's a scroll bar in the code snippet, which looks like ass, but it renders properly.

**Comment by camsaul** [comment]
cool 👍

**Pull request merged**
