### PR TITLE
WIP: create vendor bundle

### LINKED ISSUE #4404: Development - vendor bundle
Split vendor js into vendor bundle. It might speed up development - webpack won't loose time combining big MB bundles each time code changes.

What do you think?

### PR DESCRIPTION
**Pull request by mariusz-jachimowicz-83**
Fix #4404 
vendor-bundle

### CODE REVIEW

**Comment by mariusz-jachimowicz-83** [comment]
vendor-bundle-2

**Comment by kdoh** [comment]
@mariusz-jachimowicz-83 Liking the progress on this 👍 . How much further are you planning on splitting stuff up?

**Comment by mariusz-jachimowicz-83** [comment]
At this stage it's enough, I think. It's hard to go further.

**Comment by mariusz-jachimowicz-83** [comment]
I have noticed in chrome tools that 

- loading 10MB main bundle takes 700ms
- loading reduced 6MB main bundle takes >700ms (while 4,5MB vendor bundle is loaded in parallel in 250ms)

Whole page loading time is roughly the same.

It's strange that I don't see loading time speed-up. This is why I consider leaving vendor bundle creation only for development. It will reduce rebuilding main bundle at least.

**Comment by salsakran** [comment]
@tlrobinson @attekei @mariusz-jachimowicz-83 

Do we still want to split this up if there's no real performance gain? Is there a perf gain in development?

**Comment by kdoh** [comment]
Closing this due to the fact that we've since migrated to Webpack 3 in #6147 and created a vendor bundle in #6159. Thanks for the initial effort @mariusz-jachimowicz-83.

**Pull request closed without merging**
