### PR TITLE
add new custom-stylesheet setting for public sharing

### PR DESCRIPTION
**Pull request by snarfed**
happy monday all! here's a [#YOLO JUST SUBMIT A PR](https://github.com/metabase/metabase/blob/master/docs/contributing.md#yolo-just-submit-a-pr). i'm starting to play with this internally. totally understand if you all don't want to merge, but i figured i'd let you know.

this optionally adds a user-defined CSS `<link>` to publicly shared dashboards and questions.

i originally added a `Access-Control-Allow-Origin: *` HTTP response header and tried to style into the iframe from JS in the outer HTML, but that didn't work. idk, i'm not a web developer, i just play one on TV.

related to:
https://discourse.metabase.com/t/is-it-possible-to-inject-a-custom-css-to-change-metabases-ui/1702
https://discourse.metabase.com/t/idiots-guide-to-modifying-visualisations/2771
https://discourse.metabase.com/t/ui-customization-in-dashboards/3278

-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [ ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by snarfed** [comment]
also this seems to be buggy as is. it's fully qualifying the local `<script>` URLs with `localhost:8080`, eg `<script type="text/javascript" src="http://localhost:8080/app/dist/vendor.hot.bundle.js?8c9f53bd2ea25f6c83bb">`, even though `MetabaseBootstrap` has the correct `site_url`. switching back to 0.29.0 release fixes that.

🤷‍♀️ i'll debug.

**Comment by atranel** [comment]
new version has issues with this edit. I cannot compile it unless I removed first edit to middleware.clj. They removed this file and made a folder Middleware. I tried to enter it into new /middleware/security.clj but compilation fails. Other edits are ok.

**Comment by snarfed** [comment]
thanks for the heads up!

**Comment by walterl** [comment]
Closed due to inactivity.

**Pull request closed without merging**
