### PR TITLE
validate current password when changing it

### LINKED ISSUE #23259: Changing account password to a non-complex password misleads the user with a success message even though the process fails
**Describe the bug**
Attempting to change account password to a common one will notify the user that password change has succeeded when in fact it hasn't due to lack of password complexity.

**Logs**
See Screenshots.

**To Reproduce**
1. Go to 'Account Settings'
2. Enter a common password to 'Create a Password' fields
3. Click 'Save'

**Expected behavior**
When password is too common, it should notify the user that the password is too common and the process has failed.

**Screenshots**
metabase-bug

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 101.0
- Your operating system: Ubuntu 20.04
- Metabase version: 0.43.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Not critical but it causes confusion when new users try to change their temporary password.

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/23259

## Changes
- Shows an error when the current is not correct
- Validates passwords for superusers too

## How to verify
- As an admin go to Account Settings
- Try change your password when entering invalid current password
- Ensure it shows an error
- Try the steps above as a regular user

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

**Comment by alxnddr** [comment]
@flamber @metabase/backend-developers why do we let admins change everyone's passwords, is this a requirement? I did not find any UI to perform this action. Also, it seems a bit wrong that we expire the current session when change password, should we fix it?

**Comment by flamber** [comment]
@alxnddr 
We let the admin set the user password (it's still called password reset), when you don't have email server configured, via Admin > People > ... > Reset password (it sends a PUT request to /api/user/:user_id/password with the password).

I'm guessing that we're dropping all user's sessions on password change, so you can ensure that no other devices are logged in. Related to #5063.

**Comment by alxnddr** [comment]
@flamber 
> We let the admin set the user password (it's still called password reset), when you don't have email server configured, via Admin > People > ... > Reset password (it sends a PUT request to /api/user/:user_id/password with the password).

Oh, thanks, I had an email server configured and did not see it. Well, the `old_password` field is being ignored for admins because they can change everyone's passwords. Is it okay if I just remove the field from the Account Settings?

**Comment by flamber** [comment]
@alxnddr So anyone could change their own password without inputting their current password? Sounds like something that needs to be thought through a bit more if so. It's a security precaution. Not a great one, but still. Not something that should land in a patch release.

**Comment by alxnddr** [comment]
@flamber not everyone but only admins since we ignore current password field value for them

**Comment by alxnddr** [comment]
@flamber I am speaking about this view: 
Screenshot 2022-06-13 at 20 44 16
 
When admins use it, backend ignores `old_password` because they should be able to change password anyway. So I'm suggesting removing "Current password" input from here

**Comment by flamber** [comment]
@alxnddr Ohh.... that seems like a mistake. I'm sure that it was meant to validate especially the admin password change.
If we want to remove the "current password" from Admins, then we might was well remove it from normal users too.

**Comment by alxnddr** [comment]
@flamber if we want to add admin password validation here it would be reasonable to validate it when resetting own password through the admin panel as well or maybe remove the reset button for a current user 🤔

**Comment by flamber** [comment]
@alxnddr 
If this PR solves the problem, where it would say "Success" no matter what the response code was, then great - merge it.
Then the product team can go through how the functionality works, when redoing the SSO and attributes in future versions.
It seems it's broken by design.

**Pull request merged**
