### PR TITLE
Issue #12203 - Sample Dataset data doesn't add up

### PR DESCRIPTION
**Pull request by jeff303**
Fixing total for all order records in sample data EDN file

Making same update in sample-dataset H2 file, via:

UPDATE ORDERS SET TOTAL=SUBTOTAL+TAX-IFNULL(DISCOUNT,0);

### CODE REVIEW

**Comment by jeff303** [comment]
This addresses #12203.

**Comment by camsaul** [comment]
13.6 MB is pretty big for the sample dataset H2 file given the amount of data in it... the old version you're replacing is only 1.6M. You can have H2 compress stuff by adding `DEFRAG_ALWAYS=TRUE` and maybe a few other things to the connection string. Maybe `COMPRESS=TRUE` is also appropriate. See https://www.h2database.com/javadoc/org/h2/engine/DbSettings.html for all the options

**Review by camsaul — CHANGES_REQUESTED** [review]
Old version of the sample dataset is only 1.6 MB... this PR makes it 13.6 MB. I definitely compressed the old sample dataset, I'll try to find the old code for generating it. 

You should compress your new DB file so it's not way too B I G

**Comment by camsaul** [comment]
oh yeah here's the old sample dataset code. I think I used literally every flag humanly possible there

https://github.com/TomSesselmann/metabase/blob/ee100c104c12353deac1d5d8938b730fa8c887be/lein-commands/sample-dataset/metabase/sample_dataset/generate.clj#L500-L502

**Comment by jeff303** [comment]
> oh yeah here's the old sample dataset code. I think I used literally every flag humanly possible there
> 
> https://github.com/TomSesselmann/metabase/blob/ee100c104c12353deac1d5d8938b730fa8c887be/lein-commands/sample-dataset/metabase/sample_dataset/generate.clj#L500-L502

Thanks, that indeed did the trick.  For posterity:

```alias h2shell='java -cp ~/.m2/repository/com/h2database/h2/1.4.197/h2*jar org.h2.tools.Shell'
h2shell
# for URL, enter
jdbc:h2:./resources/sample-dataset.db;UNDO_LOG=0;CACHE_SIZE=131072;QUERY_CACHE_SIZE=128;COMPRESS=TRUE;MULTI_THREADED=TRUE;MVCC=TRUE;DEFRAG_ALWAYS=TRUE;MAX_COMPACT_TIME=5000;ANALYZE_AUTO=100
# leave the rest of the options as default, then once connected, run the update statement mentioned in the commit msg```

**Review by camsaul — APPROVED** [review]

**Pull request merged**
