### PR TITLE
Handle unsupported formatting operators gracefully [WIP]

### LINKED ISSUE #9891: Pulses not loading anymore
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Security Disclosure

Security is very important to us. If discover any issue regarding security, please disclose the information responsibly by sending an email to security@metabase.com and not by creating a GitHub issue.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

### PR DESCRIPTION
**Pull request by walterl**
Fixes #9891

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
Works for me, to fix the lint errors you just need to run `yarn prettier` and it will reformat your code.

If you can, it would be nice to try to add a test for this

**Comment by walterl** [comment]
Thanks, @camsaul, but this isn't 100% working yet. I still need to port `metabase/lib/colors.js` to ES5, as explained [here](https://github.com/metabase/metabase/issues/9891#issuecomment-525570813).

I'll add a test too :+1:.

**Comment by walterl** [comment]
That moment when a new test shows undiscovered errors :stuck_out_tongue_closed_eyes:.

According to [the failing test](https://circleci.com/gh/metabase/metabase/146419), there is table formatter support missing for the `inside` and `between` operators.

Should those operators be supported in table formatting?

**Comment by mazameli** [comment]
Is this good to merge with your latest changes now @walterl?

**Pull request merged**
