### PR TITLE
Add snowflake driver

### PR DESCRIPTION
**Pull request by kenbier**
I figured I'd try #3355 since our company needs it. I was able to get it running locally and setup some sample questions. Simple things like date parsing, equations, table loading, column parsing etc. all seem to work.

I'm happy to write tests if you could point me in the right direction. Snowflake, like Redshift, is a hosted-only database solution. I am not sure of your team's strategy on testing hosted databases. 

###### TODO 
-  [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by kenbier** [comment]
Snowflake JDBC license can be found [here](https://github.com/snowflakedb/snowflake-jdbc])

**Comment by salsakran** [comment]
Thanks for the help!

As far as testing, does Snowflake have a free tier or a developer license?

**Comment by kenbier** [comment]
@salsakran They have a developer program. I can email the details.

Is there a metabase contact email?

**Comment by salsakran** [comment]
email my first name @metabase.com.

**Comment by katerinawait** [comment]
Hi, we would like to test this driver can  you please provide some info on installing it as we are new to metabase? We have couple snowflake dbs, so would we willing to aid development of this.

**Comment by kenbier** [comment]
@katerinawait https://github.com/metabase/metabase/blob/master/docs/developers-guide.md#install-prerequisites

**Comment by watthell234** [comment]
What is the progress on testing this amazing driver?

**Comment by salsakran** [comment]
@kenbier I've signed up for a snowflake account and am in the process of reviewing this.

You should be able to run the test suite by running 
`ENGINES=snowflake lein test`
if you need to pass account credentials, you can do so by passing them through env variables named
MB_SNOWFLAKE_TEST_<VariableNameInUppcer case>, 

eg for redshift, we specify 
```
MB_REDSHIFT_TEST_DB
MB_REDSHIFT_TEST_HOST
MB_REDSHIFT_TEST_PASSWORD
MB_REDSHIFT_TEST_USER
MB_REDSHIFT_USER
```

Can you run the test suite, linters and make sure they pass before we move forward? Eg, this PR failed linting when I tried.

**Review by salsakran — CHANGES_REQUESTED** [review]
Make sure linters pass, and the test suite as well.

**Comment by jjamesstark** [comment]
Any word on this? @kenbier @salsakran 

We're a couple weeks away from migrating to Snowflake and are piloting Metabase as well.

**Comment by michelzetun** [comment]
Hi @kenbier and @salsakran what is the status on this ? 
I really need this Snowflake support as in my current situation I would need to spend more money to use Metabase with other database instead of Snowflake. Due to this I am open to pay for the development and implementation in production level of this feature at the core product, in other words, simple setup as the other databases. 

Would you guys take this as a service or recommend someone to do it ?
Thanks.
Michel

**Comment by kenbier** [comment]
I've been pretty busy and tbh this fell down my priority list. Seems like
there is some interest so I'll try and pick

@michelzetun lets sync offline so I can understand your requirements. Would
you mind emailing me? me@kenbier.com

**Comment by kenbier** [comment]
Some things I still need to fix:

- Filter imported tables by the connection info
- Turn Number back to Int or other types based on precision (loses information when syncing schema with numbers based on the weird way snowflake stores numbers in schema table)
- Fix one bug with last sync timestamp

In the long term, it'd be nice to do queries across databases, which snowflake allows in the same connection. I will have to change the query planner and Table model to allow for this, and might include that in another PR to keep things simple.

**Comment by camsaul** [comment]
@kenbier I just realized `warehouse` isn't actually used as part of the connection spec

**Comment by kenbier** [comment]
@camsaul Looking good. Whats left? Just converting numbers columns (i.e. Integer) back to the proper column type?

**Pull request merged**
