### PR TITLE
Fix error when opening a public question with filters having default parameters

### LINKED ISSUE #17033: An error occurs when opening a public question with filters having default parameters
**Describe the bug**
When opening a public question that has filters with default values, the result is replaced with the "An error occurred while running the query" message in a couple of seconds.

**NOTE:** if you just refresh the page, it will work as expected

**To Reproduce**

1. Enable public sharing in admin
2. Ask a question > Native question > Sample Dataset
3. Enter `SELECT * FROM PEOPLE WHERE {{birthdate}} AND {{source}}`
4. Configure filters via the right sidebar:
    * `{{ birthdate }}` as a Field Filter mapped to People > BirthDate with a default of "Past 30 Years"
    * `{{ source }}` as a Field Filter mapped to  People > Source with default a of "Affiliate"
5. Save question
6. In the bottom right corner, click the "Sharing" icon (an arrow)
7. Open the share URL
8. You can see a table with results for a couple of seconds, but then it's replaced with the "An error occurred while running the query" message

**Demo**

https://user-images.githubusercontent.com/17258145/125569652-ef6b371c-8853-4eb5-9664-fd7d86bbeb36.mov

**Information about your Metabase Installation:**
Metabase 0.40.0

### PR DESCRIPTION
**Pull request by kulyk**
When opening a public question that has filters with default values, you see the results, but in a couple of seconds they're replaced with the "An error occurred while running the query" message. Fixes #17033

There is a race condition. Because of it, the results can be overwritten by a query without default parameters applied. Steps:

1. You open a URL like `/public/question/:guid`. There are no query parameters that are usually in sync with filters. So when the page mounts
2. [`PublicQuestion`](https://github.com/metabase/metabase/blob/v0.40.0/frontend/src/metabase/public/containers/PublicQuestion.jsx) mounts
3. The query run is triggered inside [`UNSAFE_componentWillMount`](https://github.com/metabase/metabase/blob/961caedc9983dfef7e25dfdfb0e18c9bde02dca4/frontend/src/metabase/public/containers/PublicQuestion.jsx#L119) _without_ parameters
4. `PublicQuestion` [renders `EmbedFrame`](https://github.com/metabase/metabase/blob/961caedc9983dfef7e25dfdfb0e18c9bde02dca4/frontend/src/metabase/public/containers/PublicQuestion.jsx#L197), `EmbedFrame` [renders `Parameters`](https://github.com/metabase/metabase/blob/v0.40.0/frontend/src/metabase/public/components/EmbedFrame.jsx)
5. `Parameters` [start syncing parameters with query parameters](https://github.com/metabase/metabase/blob/980518f2f488a7bf5d5c8637f57038708145d97c/frontend/src/metabase/parameters/components/Parameters/Parameters.jsx#L20). At the end, it should take parameters' default values and append them to the URL as query parameters
6. `Parameters` trigger the `setParameterValue` call, so the URL can be updated and we can run the query. `setParameterQuery` [triggers a new query run](https://github.com/metabase/metabase/blob/980518f2f488a7bf5d5c8637f57038708145d97c/frontend/src/metabase/public/containers/PublicQuestion.jsx#L134), now with default parameters applied
7. The trick is steps 3-6 happen simultaneously, and sometimes (however I can reproduce that every time), the result without filters is applied _later_, and you can see an error

Fixed by ensuring that the query with parameters is triggered only after the initial one from `componentWillMount`. Not the best solution out there, but it's the safest I guess. A better solution would be to move [`syncQueryParamsWithURL`](https://github.com/metabase/metabase/blob/980518f2f488a7bf5d5c8637f57038708145d97c/frontend/src/metabase/parameters/components/Parameters/Parameters.jsx#L20) from `Parameters` to the `PublicQuestion`, so the initial query would also contain default filter parameters.

Tried to add some e2e coverage here, but wasn't very successful. Tried intercepting and waiting for `GET /api/public/card/*/query`, but it catches only one request and I couldn't assert there is no error. Opened to ideas here 

### To Verify

1. Enable public sharing in admin
2. Ask a question > Native question > Sample Dataset
3. Enter `SELECT * FROM PEOPLE WHERE {{birthdate}} AND {{source}}`
4. Configure filters via the right sidebar:
    * `{{ birthdate }}` as a Field Filter mapped to People > BirthDate with a default of "Past 30 Years"
    * `{{ source }}` as a Field Filter mapped to  People > Source with default a of "Affiliate"
5. Save question
6. In the bottom right corner, click the "Sharing" icon (an arrow)
7. Open the share URL
8. You should see the results, without any error messages

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/125566975-27bae888-a512-43e4-880a-dcba8d9d1f2b.mov

**After**

https://user-images.githubusercontent.com/17258145/125567015-7d9eea71-b3df-43a2-81ba-eb6df34f43ff.mov

### CODE REVIEW

**Review by gusaiani — APPROVED** [review]
Awesome fix 👏

**Review by flamber — APPROVED** [review]
I cannot reproduce the race-condition you're seeing, but I'm quite sure we have some (example issue 13150).

I can however see the multiple requests on 0.40.0 (and previous versions):
```
2021-07-14 13:55:11,846 DEBUG middleware.log :: GET /api/public/card/e80508e2-edd2-4fac-a253-d03e99cb1e5c 200 9.1 ms (4 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (4 idle, 0 queued) (83 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 13:55:11,945 DEBUG middleware.log :: GET /api/session/properties 200 10.8 ms (0 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (4 idle, 0 queued) (83 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 13:55:12,030 DEBUG middleware.log :: GET /api/field/90 401 298.3 µs (0 DB calls) 
"Unauthenticated"

2021-07-14 13:55:12,045 DEBUG middleware.log :: GET /api/public/card/e80508e2-edd2-4fac-a253-d03e99cb1e5c/field/90/values 200 5.7 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (4 idle, 0 queued) (83 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 13:55:12,757 DEBUG middleware.log :: GET /api/public/card/e80508e2-edd2-4fac-a253-d03e99cb1e5c/query 202 [ASYNC: completed] 651.8 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (85 total active threads) Queries in flight: 1 (0 queued); h2 DB 4 connections: 0/2 (0 threads blocked)
2021-07-14 13:55:13,153 DEBUG middleware.log :: GET /api/public/card/e80508e2-edd2-4fac-a253-d03e99cb1e5c/query 202 [ASYNC: completed] 694.6 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 1/2 (0 threads blocked)
```
Which isn't there on this PR :tada: :
```
2021-07-14 14:07:32,178 DEBUG middleware.log :: GET /api/public/card/e80508e2-edd2-4fac-a253-d03e99cb1e5c 200 10.4 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 14:07:32,202 DEBUG middleware.log :: GET /api/session/properties 200 2.6 ms (0 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 14:07:32,614 DEBUG middleware.log :: GET /api/public/card/e80508e2-edd2-4fac-a253-d03e99cb1e5c/query 202 [ASYNC: completed] 188.9 ms (8 DB calls) App DB connections: 1/10 Jetty threads: 3/50 (3 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 0/2 (0 threads blocked)
2021-07-14 14:07:32,675 DEBUG middleware.log :: GET /api/field/90 401 367.8 µs (0 DB calls) 
"Unauthenticated"

2021-07-14 14:07:32,711 DEBUG middleware.log :: GET /api/public/card/e80508e2-edd2-4fac-a253-d03e99cb1e5c/field/90/values 200 7.3 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 14:07:33,154 DEBUG middleware.log :: GET /api/public/card/e80508e2-edd2-4fac-a253-d03e99cb1e5c/query 202 [ASYNC: completed] 175.0 ms (8 DB calls) App DB connections: 2/10 Jetty threads: 3/50 (3 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 0/2 (0 threads blocked)
```

But I'm still seeing this on Embedded questions, which I know you didn't wrote that you explicitly fixed that, but just wanted to note that it exists there too:
```
2021-07-14 14:04:14,468 DEBUG middleware.log :: GET /api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6NTY2fSwicGFyYW1zIjp7fSwiaWF0IjoxNjI2MjY0MjE2LCJfZW1iZWRkaW5nX3BhcmFtcyI6eyJiaXJ0aGRhdGUiOiJlbmFibGVkIiwic291cmNlIjoiZW5hYmxlZCJ9fQ.GXcsSYdX5bIo7wZ6GlOy1VvTK9t1g7p7-gKuEuh3xbo 200 19.6 ms (6 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 14:04:14,479 DEBUG middleware.log :: GET /api/session/properties 200 7.7 ms (0 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 14:04:15,161 DEBUG middleware.log :: GET /api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6NTY2fSwicGFyYW1zIjp7fSwiaWF0IjoxNjI2MjY0MjE2LCJfZW1iZWRkaW5nX3BhcmFtcyI6eyJiaXJ0aGRhdGUiOiJlbmFibGVkIiwic291cmNlIjoiZW5hYmxlZCJ9fQ.GXcsSYdX5bIo7wZ6GlOy1VvTK9t1g7p7-gKuEuh3xbo/query 202 [ASYNC: completed] 355.5 ms (10 DB calls) App DB connections: 1/10 Jetty threads: 3/50 (2 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 0/2 (0 threads blocked)
2021-07-14 14:04:15,302 DEBUG middleware.log :: GET /api/field/90 401 360.1 µs (0 DB calls) 
"Unauthenticated"

2021-07-14 14:04:15,361 DEBUG middleware.log :: GET /api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6NTY2fSwicGFyYW1zIjp7fSwiaWF0IjoxNjI2MjY0MjE2LCJfZW1iZWRkaW5nX3BhcmFtcyI6eyJiaXJ0aGRhdGUiOiJlbmFibGVkIiwic291cmNlIjoiZW5hYmxlZCJ9fQ.GXcsSYdX5bIo7wZ6GlOy1VvTK9t1g7p7-gKuEuh3xbo/field/90/values 200 73.6 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
2021-07-14 14:04:15,962 DEBUG middleware.log :: GET /api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6NTY2fSwicGFyYW1zIjp7fSwiaWF0IjoxNjI2MjY0MjE2LCJfZW1iZWRkaW5nX3BhcmFtcyI6eyJiaXJ0aGRhdGUiOiJlbmFibGVkIiwic291cmNlIjoiZW5hYmxlZCJ9fQ.GXcsSYdX5bIo7wZ6GlOy1VvTK9t1g7p7-gKuEuh3xbo/query 202 [ASYNC: completed] 309.6 ms (10 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (2 idle, 0 queued) (78 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 0/2 (0 threads blocked)
```

**Comment by kulyk** [comment]
> @kulyk Well, I'm still seeing two queries, not three, but could we get rid of the first, which would likely speed up performance by a lot (doesn't need to be part of this PR)

You're right, it would just require a bit more refactoring and it's probably going to be more risky, so should better be tackled separately. I'll file an issue ✏️

**Review by nemanjaglumac — APPROVED** [review]
🚀

**Comment by kulyk** [comment]
Huge thanks for the repro @nemanjaglumac !

**Comment by kulyk** [comment]
Hey @flamber, here is the issue about redundant query requests: #17061

**Pull request merged**
