### PR TITLE
Add tab-key navigation for metadata editor

### PR DESCRIPTION
**Pull request by kulyk**
Adds a custom "tab flow" for dataset metadata editor to make it easier to customize metadata for every column. It should be possible to navigate through every dataset field using the "Tab" key and go through each field's 'essential' properties (display name, description, special/semantic type, and real database column for native datasets).

### To Verify

_I recommend watching the demo video below. In the video, I go through and explain every change. Also, the keystrokes are highlighted there, so it can make it easier to test the change locally._

1. Open any dataset, click its name to open the details sidebar, and click "Customize metadata"
2. Ensure the first column is selected and you see its metadata in the right sidebar. Also, make sure the "Display name" input is focused with all the text selected
3. Hit the "Tab" key a few times. The flow should be: "Display name" > "Description" > "Database column this maps to" (only if you're on a native dataset, the field shouldn't be there for GUI ones) > "Special type" > Next column
4. Once you go through a list of essential fields for a single column and then hit "Tab" while the "Special type" picker is focused, the editor should switch to the next column and "Display name" should become focused
5. Go through a few columns in that way to ensure "tab navigation" works correctly
6. Try navigating backward using "Shift + Tab". You should be able to get back to the previous columns
7. Click on a random column and try using the "tab navigation" again, it shouldn't break
8. Click on the last column and. tab through essential fields. Once you hit "Tab" while being on the "Special type" picker, you should end up on the very first column

### Demo

https://user-images.githubusercontent.com/17258145/146763648-72bbc3b6-312e-42d5-8077-a3dccc21819c.mov

### CODE REVIEW

**Comment by mazameli** [comment]
Here are the couple things I noticed @kulyk: https://www.loom.com/share/3c20c0d43b5a4411afb2ba02a2b994d4

As I mentioned in the video, I think we're going to need a subtle transition animation when tabbing from one column to another to help make it clearer what's happening. I'm gonna go mock it up in Figma real quickly.

**Comment by mazameli** [comment]
@kulyk, here's [the transition animation that I'm envisioning](https://www.figma.com/proto/BS1y4OuRPagFUKEX0tHdr4/Allow-for-the-creation-and-usage-of-Models-aka-Datasets?page-id=437%3A3289&node-id=12449%3A17185&viewport=266%2C48%2C0.58&scaling=min-zoom&starting-point-node-id=12449%3A17185&show-proto-sidebar=1) for when the user tabs over from one column to the next. Hit your Tab key to see the transition, and hit shift+tab to go backwards.

We don't need this transition IMO when they use the mouse to click on another column heading to switch columns, but if it's _easier_ for you to implement it for both cases, that's okay.

**Comment by mazameli** [comment]
[Two tiny things I noticed here](https://www.loom.com/share/9467106fabec491db8724a53a5f80195), but this is looking and feeling great -- so if it's fast and easy to fix those two things, cool; otherwise I say let's merge it!

**Review by mazameli — APPROVED** [review]
So good!

**Review by daltojohnso — APPROVED** [review]
looks good. are there plans to make the accordion list keyboard friendly? 🙂

**Comment by kulyk** [comment]
> looks good. are there plans to make the accordion list keyboard friendly? 🙂

We should get there eventually. AccordionList could use a general refactoring too, it does way too much as I think

**Pull request merged**
