### PR TITLE
Hot fix for the some enterprise api docs

### PR DESCRIPTION
**Pull request by qnkhuat**
We have the command `api-documentation` to generate our [API docs](https://www.metabase.com/docs/latest/api-documentation.html). 

Currently, we have some mismatch in the endpoints we generate vs what it really is. So this PR is a hotfix to make sure our documents are consistent with the code.
- /api/ee/sandbox  -> /api/mt
- /api/ee/content-management -> /api/moderation-review
- /api/ee/sandbox/table -> /api/table
- /api/ee/sso/sso/ -> /auth/sso

Note that this is just a hotfix, the *right* way to fix this is to update the ee endpoint, see #22687

### CODE REVIEW

**Comment by qnkhuat** [comment]
@jeff-bruemmer do you think I should run the command and update the docs in this PR?

Also I tried to run and there are some unrelated changes in all the API docs. I'm not sure why this is not included in our current doc.
Screen Shot 2022-07-25 at 21 38 22

**Review by howonlee — APPROVED** [review]
There's tests for both things in the codebase, but usefulness of tests seems pretty marginal... your call on adding to the existing tests

**Comment by jeff-bruemmer** [comment]
@qnkhuat. Thanks for this hotfix; I wasn't aware these endpoints were off. I'll make a note on https://github.com/metabase/metabase/issues/22687 to follow up with this code if/when we get around to organizing the code the right way.

> do you think I should run the command and update the docs in this PR?

Great question. I will:

- Merge this PR as it is, and backport it to the release branch. And possibly even the 43 release branch; otherwise these changes won't be visible until after we release 44.
- Once backported, I'll run the command in each branch and commit the results. 
- Once the branches are updated, I'll run the scripts to update the docs on the website.

This approach is tedious, but avoids incorrectly documenting the API for each release.

> Also I tried to run and there are some unrelated changes in all the API docs. I'm not sure why this is not included in our current doc.

That's likely because the code has been updated, but since that last update, I've yet to re-run the command with the updated code on this branch.

**Comment by jeff-bruemmer** [comment]
@metabase-bot backport release-x.43.x

**Pull request merged**
