### PR TITLE
Migrate embedding SDK reducers to use redux toolkit's builder callback

### PR DESCRIPTION
**Pull request by heypoom**
### Description

The following warning regarding reducer object notation is shown in the console. This PR migrates the reducer to use the builder callback notion.

```bash
  console.warn
    The object notation for `createReducer` is deprecated, and will be removed in RTK 2.0. Please use the 'builder callback' notation instead: https://redux-toolkit.js.org/api/createReducer

      71 | };
      72 |
    > 73 | export const sdk = createReducer(initialState, {
         |                                 ^
      74 |   [refreshTokenAsync.pending.type]: state => {
      75 |     return {
      76 |       ...state,

      at createReducer (node_modules/@reduxjs/toolkit/src/createReducer.ts:228:17)
      at Object.<anonymous> (enterprise/frontend/src/embedding-sdk/store/reducer.ts:73:33)
      at Object.require (enterprise/frontend/src/embedding-sdk/store/index.ts:14:1)
      at Object.require (enterprise/frontend/src/embedding-sdk/hooks/public/use-question-search.ts:3:1)
      at Object.require (enterprise/frontend/src/embedding-sdk/hooks/public/index.ts:3:1)
      at Object.require (enterprise/frontend/src/embedding-sdk/hooks/index.ts:1:1)
      at Object.require (enterprise/frontend/src/embedding-sdk/components/private/AppInitializeController.tsx:8:1)
      at Object.require (frontend/test/__support__/ui.tsx:15:1)
      at Object.require (enterprise/frontend/src/embedding-sdk/components/private/PublicComponentWrapper/PublicComponentWrapper.unit.spec.tsx:1:1)
```

### How to verify

- Running tests such as `yarn jest PublicComponentWrapper` should no longer show the above error.

### CODE REVIEW

**Comment by oisincoveney** [comment]
Does this affect types in any way?

**Review by npretto — APPROVED** [review]

**Comment by heypoom** [comment]
> Does this affect types in any way?

@oisincoveney As I changed some of the `createAction` imports from `redux-actions` to `@reduxjs/toolkit`, I think the action creator type is changed slightly - but shouldn't affect the existing code.

Essentially, redux-actions uses a very generic action creator type `export type ActionFunctionAny<R> = (...args: any[]) => R;`, while redux toolkit injects the `type` metadata field and strictly defines the payload action structure.

**Comment by npretto** [comment]
> Does this affect types in any way?

AFAIR the builder pattern was made explicitly to have better type inference, as you can see with it you don't have to type the action as it infers them from the action creator

**Comment by oisincoveney** [comment]
> > Does this affect types in any way?
> 
> @oisincoveney As I changed some of the `createAction` imports from `redux-actions` to `@reduxjs/toolkit`, I think the action creator type is changed slightly - but shouldn't affect the existing code.
> 
> Essentially, redux-actions uses a very generic action creator type `export type ActionFunctionAny<R> = (...args: any[]) => R;`, while redux toolkit injects the `type` metadata field and strictly defines the payload action structure.

Sweet. Just wanted to make sure since I tried to shoehorn redux-actions with RTK. this is much nicer then 😄

**Review by oisincoveney — APPROVED** [review]
noice

**Comment by heypoom** [comment]
Getting some unrelated flaky tests, but I think https://github.com/metabase/metabase/pull/42046 will fix that 💪🏻

**Pull request merged**
