### PR TITLE
Add log4j dependency for custom json logging format

### PR DESCRIPTION
**Pull request by Onlinehead**
Related to https://github.com/metabase/metabase-ops/issues/667

### Description

Adding a log4j plugin for a [template json logging format](https://logging.apache.org/log4j/2.x/manual/layouts.html#json-template-layout) which is required for well-formatted logs. The default log4j template produce output which not really fit to our requirements. 
Also, it unlocks logging of an additional context in an easy-to-parse form which we will need in a near future. 

### Demo

Example of the custom output:

```
{"@timestamp":"2023-03-30T16:03:59.720+0200","level":"INFO","logger_name":"metabase.events","message":"Starting events listener: :metabase.events.last-login/LastLogin "}
{"@timestamp":"2023-03-30T16:03:59.720+0200","level":"INFO","logger_name":"metabase.events","message":"Starting events listener: :metabase.events.persisted-info/PersistedInfo "}
{"@timestamp":"2023-03-30T16:03:59.720+0200","level":"INFO","logger_name":"metabase.events","message":"Starting events listener: :metabase.events.sync-database/Sync "}
{"@timestamp":"2023-03-30T16:03:59.720+0200","level":"INFO","logger_name":"metabase.events","message":"Starting events listener: :metabase.events.driver-notifications/DriverNotifications "}
{"@timestamp":"2023-03-30T16:03:59.721+0200","level":"INFO","logger_name":"metabase.events","message":"Starting events listener: :metabase.events.revision/Revisions "}
{"@timestamp":"2023-03-30T16:03:59.721+0200","level":"INFO","logger_name":"metabase.events","message":"Starting events listener: :metabase.events.view-log/ViewLog "}
{"@timestamp":"2023-03-30T16:03:59.746+0200","level":"INFO","logger_name":"metabase.driver.impl","message":"Initializing driver :sql..."}
```

### Checks

No code added.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29686)

### CODE REVIEW

**Comment by dpsutton** [comment]
@Onlinehead can you help me understand this?

I'm running this branch and see no difference, which is good. I'm sure the devs don't want structured logging while developing. Can you give a sample config that does the structured logging?

Another thing i'm seeing is that your output doesn't allow the _message_ to be structured, just data about logging. The message is still an opaque text blob. Is this desired? Your output is

```javascript
{
  "@timestamp": "2023-03-30T16:03:59.720+0200",
  "level": "INFO",
  "logger_name": "metabase.events",
  "message": "Starting events listener: :metabase.events.last-login/LastLogin " // this is still opaque
}
```

One thing that is interesting to me, is that running metabase _without_ this change, I can still get this behavior:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
  <Appenders>
    <Console name="STDOUT" target="SYSTEM_OUT" follow="true">
      <JSONLayout compact="true" eventEol="true" properties="true" stacktraceAsString="true" includeTimeMillis="true"/>
    </Console>
  </Appenders>

  <Loggers>
    <Logger name="metabase" level="INFO"/>
    <Logger name="metabase-enterprise" level="INFO"/>
    <Logger name="metabase.plugins" level="DEBUG"/>
    <Logger name="metabase.server.middleware" level="DEBUG"/>
    <Logger name="metabase.query-processor.async" level="DEBUG"/>
    <Logger name="com.mchange" level="ERROR"/>
    <Logger name="org.quartz" level="INFO"/>
    <Logger name="liquibase" level="ERROR"/>
    <Logger name="net.snowflake.client.jdbc.SnowflakeConnectString" level="ERROR"/>

    <Root level="WARN">
      <AppenderRef ref="STDOUT"/>
    </Root>
  </Loggers>
</Configuration>
```

And 
```bash
❯ MB_JETTY_PORT=3006 java -Dlog4j2.configurationFile=log4j2.xml -jar 1.46.0.jar
{"timeMillis":1680188985147,"thread":"main","level":"INFO","loggerName":"metabase.util","message":"Maximum memory available to JVM: 8.0 GB","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","contextMap":{},"threadId":1,"threadPriority":5}
{"timeMillis":1680188986932,"thread":"main","level":"WARN","loggerName":"metabase.db.env","message":"\u001B[31mWARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html\u001B[0m","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","contextMap":{},"threadId":1,"threadPriority":5}
...
```

And the first log message from your output above:
```javascript
{"timeMillis":1680189004848,"thread":"main","level":"INFO","loggerName":"metabase.events","message":"Starting events listener: \u001B[34m:metabase.events.last-login/LastLogin\u001B[0m 👂","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","contextMap":{},"threadId":1,"threadPriority":5}

// pretty printed:
{
  "timeMillis": 1680189004848,
  "thread": "main",
  "level": "INFO",
  "loggerName": "metabase.events",
  "message": "Starting events listener: \u001b[34m:metabase.events.last-login/LastLogin\u001b[0m 👂",
  "endOfBatch": false,
  "loggerFqcn": "org.apache.logging.log4j.spi.AbstractLogger",
  "contextMap": {},
  "threadId": 1,
  "threadPriority": 5
}
```

So it seems that this is already possible? We've got some ansi escape codes that don't look great, but it seems like we have lots of information (possibly more? I see a context map and thread information).

**Comment by Onlinehead** [comment]
@dpsutton The idea is to use a custom formatting json which allow to structure the output different way (for example name `timestamp` as a timestamp and print it as a line in a full format and not as a pair of secodns + milliseconds etc.)
Escape codes are colors and emojies, we can disable them by env variables:
```
export MB_COLORIZE_LOGS=false
export MB_EMOJI_IN_LOGS=false
```

And here is an example of log4j config which I used to get the output from the example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Appenders>
        <Console name="STDOUT" target="SYSTEM_OUT">
            <JsonTemplateLayout eventTemplateUri="file:///tmp/metabase/layout.json"/>
        </Console>
  </Appenders>
    <Loggers>
      <Logger name="metabase" level="DEBUG"/>
      <Logger name="metabase-enterprise" level="INFO"/>
      <Logger name="metabase.plugins" level="DEBUG"/>
      <Logger name="metabase.server.middleware" level="DEBUG"/>
      <Logger name="metabase.query-processor.async" level="DEBUG"/>
      <Logger name="com.mchange" level="ERROR"/>
      <Logger name="org.quartz" level="INFO"/>
      <Logger name="liquibase" level="ERROR"/>
      <Logger name="net.snowflake.client.jdbc.SnowflakeConnectString" level="ERROR"/>

        <Root>
            <AppenderRef ref="STDOUT" level="All" />
        </Root>
    </Loggers>
</Configuration>
```
And the `layout.json`:
```json
{
  "@timestamp": {
    "$resolver": "timestamp"
  },
  "level": {
    "$resolver": "level",
    "field": "name"
  },
  "logger_name": {
    "$resolver": "logger",
    "field": "name"
  },
  "message": {
    "$resolver": "message",
    "stringified": true
  },
  "mdc": {
    "$resolver": "mdc"
  },
  "exception": {
    "exception_class": {
      "$resolver": "exception",
      "field": "className"
    },
    "exception_message": {
      "$resolver": "exception",
      "field": "message"
    },
    "stacktrace": {
      "$resolver": "exception",
      "field": "stackTrace",
      "stackTrace": {
        "stringified": true
      }
    }
  }
}
```

**Review by dpsutton — APPROVED** [review]

**Comment by dpsutton** [comment]
@Onlinehead you need to fix the CLA check. Either sign the google sheet or get added as a core dev. I think i just signed the form.

**Comment by dpsutton** [comment]
`git commit --allow-empty -m "empty to trigger CI"` should do it

**Pull request merged**
