### PR TITLE
Adding beforeUnload hook to Status Listing

### LINKED ISSUE #30229: show warning if the user tries to navigate away while uploading
our `react-use` library has a `useBeforeUnload` hook. let's use that.

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/30229

~🚧🚧WIP - Waiting for https://github.com/metabase/metabase/pull/30292 to merge and I'll update my test to use the `callMockEvent()` function~

### Description
Adds a browser alert if a user attempts to leave metabase while a CSV upload is happening

### How to verify
Try to reload the page while uploading a CSV

### Checklist
- [x] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30372)

### CODE REVIEW

**Review by oisincoveney — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30372)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @iethree and @npfitz)

___
*[`frontend/src/metabase/status/components/StatusListing/StatusListing.tsx` line 14 at r1](https://reviewable.io/reviews/metabase/metabase/30372#-NTwlVO70VUXujIGsNT-:-NTwlVO70VUXujIGsNT0:bczmuqf) ([raw file](https://github.com/metabase/metabase/blob/f7dec7d2d175a7191da0adc5b75ac2afab6c7786/frontend/src/metabase/status/components/StatusListing/StatusListing.tsx#L14)):*
> ```XML
> 
> const StatusListingView = () => {
>   const isLoggedIn = !!useSelector(getUser);
> ```

More of a newb question - why switch from using the state props to just selectors here?
___
*[`frontend/src/metabase/status/components/StatusListing/StatusListing.unit.spec.tsx` line 67 at r1](https://reviewable.io/reviews/metabase/metabase/30372#-NTwkpb19--8IipyTZ--:-NTwkpb19--8IipyTZ-0:btdg204) ([raw file](https://github.com/metabase/metabase/blob/f7dec7d2d175a7191da0adc5b75ac2afab6c7786/frontend/src/metabase/status/components/StatusListing/StatusListing.unit.spec.tsx#L67)):*
> ```XML
>   });
> 
>   it("should give an alert if a user navigates away from the page during an upload", () => {
> ```

This test looks good (and when you get my code in master it will be great!) - maybe we have a test like `should not give an alert if the user isn't uploading a CSV` as well. This is only because, at least from what I've seen so far) the condition can accidentally trigger while the page is loading or something, causing the popup to appear anyway. Might be more of a nit so feel free to ignore

**Comment by npfitz** [comment]
*[`frontend/src/metabase/status/components/StatusListing/StatusListing.unit.spec.tsx` line 67 at r1](https://reviewable.io/reviews/metabase/metabase/30372#-NTwkpb19--8IipyTZ--:-NU1nx6fDPim3rwcUgKZ:b-mq3fti) ([raw file](https://github.com/metabase/metabase/blob/f7dec7d2d175a7191da0adc5b75ac2afab6c7786/frontend/src/metabase/status/components/StatusListing/StatusListing.unit.spec.tsx#L67)):*
<details><summary><i>Previously, oisincoveney (Oisin Coveney) wrote…</i></summary><blockquote>

This test looks good (and when you get my code in master it will be great!) - maybe we have a test like `should not give an alert if the user isn't uploading a CSV` as well. This is only because, at least from what I've seen so far) the condition can accidentally trigger while the page is loading or something, causing the popup to appear anyway. Might be more of a nit so feel free to ignore
</blockquote></details>

No no, you're right. A quick test that only takes a couple minutes and is one more case we don't need to think about. I'll add it in

**Review by npfitz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30372)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @iethree and @oisincoveney)

___
*[`frontend/src/metabase/status/components/StatusListing/StatusListing.tsx` line 14 at r1](https://reviewable.io/reviews/metabase/metabase/30372#-NTwlVO70VUXujIGsNT-:-NU1nn4F9dKf-q0YDSg0:b-ws4hi7) ([raw file](https://github.com/metabase/metabase/blob/f7dec7d2d175a7191da0adc5b75ac2afab6c7786/frontend/src/metabase/status/components/StatusListing/StatusListing.tsx#L14)):*
<details><summary><i>Previously, oisincoveney (Oisin Coveney) wrote…</i></summary><blockquote>

More of a newb question - why switch from using the state props to just selectors here?
</blockquote></details>

No specific reason, other than trying to modernize things a bit.

**Comment by npfitz** [comment]
*[`frontend/src/metabase/status/components/StatusListing/StatusListing.unit.spec.tsx` line 67 at r1](https://reviewable.io/reviews/metabase/metabase/30372#-NTwkpb19--8IipyTZ--:-NUMTNHXCsXkYZ4G3YLQ:bqmjwcm) ([raw file](https://github.com/metabase/metabase/blob/f7dec7d2d175a7191da0adc5b75ac2afab6c7786/frontend/src/metabase/status/components/StatusListing/StatusListing.unit.spec.tsx#L67)):*
<details><summary><i>Previously, npfitz (Nick Fitzpatrick) wrote…</i></summary><blockquote>

No no, you're right. A quick test that only takes a couple minutes and is one more case we don't need to think about. I'll add it in
</blockquote></details>

Added!

**Review by EmmadUsmani — APPROVED** [review]
Looks good! There is a lint error regarding `useSelector` import that needs to be fixed before merging. Also I think https://github.com/metabase/metabase/pull/30292 hasn't merged to master yet, looks like it merged to another branch.

**Review by iethree — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30372)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @npfitz and @oisincoveney)

___
*[`frontend/src/metabase/redux/uploads.ts` line 40 at r4](https://reviewable.io/reviews/metabase/metabase/30372#-NUMsI7j9wdT4QiGY9P2:-NUMsI7j9wdT4QiGY9P3:be0530r) ([raw file](https://github.com/metabase/metabase/blob/6f081752544d1def38dc75a03af6f2c78e915324/frontend/src/metabase/redux/uploads.ts#L40)):*
> ```XML
> 
> export const hasActiveUploads = (state: State) =>
>   getAllUploads(state).some(upload => upload.status === "in-progress");
> ```

:grin: 



_Code quote:_
```XML
Uploads = (state: State) =>
```
___
*[`frontend/src/metabase/status/components/StatusListing/StatusListing.tsx` line 14 at r1](https://reviewable.io/reviews/metabase/metabase/30372#-NTwlVO70VUXujIGsNT-:-NUMsvjr8rL9hJ7UbUk2:bgc7vqv) ([raw file](https://github.com/metabase/metabase/blob/f7dec7d2d175a7191da0adc5b75ac2afab6c7786/frontend/src/metabase/status/components/StatusListing/StatusListing.tsx#L14)):*
<details><summary><i>Previously, npfitz (Nick Fitzpatrick) wrote…</i></summary><blockquote>

No specific reason, other than trying to modernize things a bit.
</blockquote></details>

:heart:

**Review by iethree — APPROVED** [review]
This rules
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30372#-:-NUMuMO04uj9oT-rZMH5:b-nlzb52)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @npfitz and @oisincoveney)

**Pull request merged**
