### PR TITLE
Guard every "target=_blank" link with rel="noreferrer"

### PR DESCRIPTION
**Pull request by ariya**
https://web.dev/external-anchors-use-rel-noopener/

### CODE REVIEW

**Review by kdoh — COMMENTED** [review]
@ariya Thanks for finding these. We also have an[ `ExternalLink`](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/ExternalLink.jsx) component that does something similar. I feel like maybe the thing to do here would be to try and use that to help propagate the pattern? Curious what you think.

**Comment by paulrosenzweig** [comment]
> The other page can access your window object with the window.opener property. This may allow the other page to redirect your page to a malicious URL.

TIL!

I think all of these are links are to pages we control (docs mostly). Though, it shouldn't hurt to include it. +1 to Kyle's suggestion of using `ExternalLink` instead which already has the attribute set.

Potentially malicious links in tables or custom dashboard click behavior use `open` in `lib/dom.js`. [It looks like](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/dom.js#L283) that passes `rel="noopener"`.

**Comment by ariya** [comment]
Good idea on using `ExternalLink` since it automatically takes care of this case! I'll look into that.

**Comment by ariya** [comment]
Closing this in favor of PR #14207.

**Pull request closed without merging**
