### PR TITLE
Fix checks for template tags

### LINKED ISSUE #10927: Variables pane/button doesn't show up in SQL editor on fresh install until page is refreshed
On `release-0.33.x` branch. Steps to repro:

*  Launch fresh instance of Metabase
*  Complete setup, go directly to "New Question" screen, create native query
*  Type a query with template params like `{{whatever}}`

Expected: Variables pane to pop up
Actual: Nothing. `X` (variables) button does not appear.

Refreshing the page causes the button to appear.

It sounds like this is related to the complex of issues where newly added databases don't have full information in the client until you completely refresh the page -- see #10330, #9517, #5129, etc. See also: #10524 

Marking as P1 [because this is related to Query Builder](https://github.com/metabase/metabase/wiki/Bug-Prioritization)

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/10927

The issue is cased by this check https://github.com/metabase/metabase/blob/5d5deac1da6aace93a09c017a3c213dcd8542399/frontend/src/metabase-lib/lib/queries/NativeQuery.ts#L419

Previously the database was loaded by the query builder only when there were snippets. It still worked in most cases because other UI components loaded databases, but there are edge cases when it doesn't work. That's why now we explicitly load the database when initializing the query builder.

How to test:
- Follow the steps https://github.com/metabase/metabase/issues/10927#issuecomment-815787298

### CODE REVIEW

**Review by kulyk — APPROVED** [review]
Nice!

**Review by flamber — COMMENTED** [review]
I don't think this is fixing the core issue - perhaps something related to snippets, but this issue was created before snippets existed.

I can still reproduce on commit `3556895`

https://user-images.githubusercontent.com/1447303/163843215-b2aa0783-e14b-4b1b-bab3-1168eb894336.mp4

**Comment by ranquild** [comment]
@flamber should work now, please have a look

**Review by flamber — COMMENTED** [review]
It's still causing the same problem - tested commit `1216a54`

https://user-images.githubusercontent.com/1447303/164084613-7b29d45a-f782-4483-b2ac-534c681e5d2d.mp4

**Comment by ranquild** [comment]
I'm closing this PR now since I'm not able to reproduce what Flamber is showing in the video. Spent 2 days trying to do so already.

**Pull request closed without merging**
