### PR TITLE
Run be tests on Java 21, and skip 19 altogether

### LINKED ISSUE #34469: Change the BE tests from Java 17, 19 to Java 21
I don´t think we should move to Java 17 or 19 at any point, but rather go to Java 21

We should switch all tests here https://github.com/metabase/metabase/blob/master/.github/workflows/backend.yml to Java 21

### PR DESCRIPTION
**Pull request by dragonsahead**
Testing Java 21 for tests. Fixes https://github.com/metabase/metabase/issues/34469

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
The CI is green and happy. :)
I'm even more happy that this means two jobs less in CI, but I'll leave the final decision to @camsaul and @metabase/core-backend-qp

**Review by metamben — CHANGES_REQUESTED** [review]
I vote for not dropping 17. It's a supported LTS version commonly used.

**Comment by paoliniluis** [comment]
> I vote for not dropping 17. It's a supported LTS version commonly used.

Although I agree, we (and our customers) run on 11 right now and I don't think we will run on 17 once we upgrade at some point in the future. Should we keep it? IMHO removing it makes more sense than keeping it @metamben

**Comment by metamben** [comment]
> > I vote for not dropping 17. It's a supported LTS version commonly used.
> 
> Although I agree, we (and our customers) run on 11 right now and I don't think we will run on 17 once we upgrade at some point in the future. Should we keep it?

According to https://stats.metabase.com/question/316-java-versions-in-the-wild, 17 is at the third place with a huge margin behind 11 and 1.8. (I expected more.) If removing 17 is a huge gain, I won't protest.

**Comment by paoliniluis** [comment]
@nemanjaglumac you decide

**Comment by nemanjaglumac** [comment]
We can run any/all versions on `master`, and choose only the currently supported/used one in PRs.

win-win

**Review by metamben — APPROVED** [review]

**Pull request merged**
