### PR TITLE
Quieter tests

### PR DESCRIPTION
**Pull request by camsaul**
We had a few tests that weren't working right, dumping a bunch of stacktraces in the test output. Fix those tests. Also add a new macro, `suppress-output`, to suppress stacktraces and error messages for tests that are suppose to throw Exceptions, which made it hard to notice when things actually went wrong (like the aforementioned bad tests)

### CODE REVIEW

**Comment by tlrobinson** [comment]
`yarn` typically takes less than a second if the dependencies are already up to date, so I'm not sure if checking our own checksum will do much.

**Comment by camsaul** [comment]
take a look at CI, it takes around 40 seconds most times. No idea why.

**Comment by camsaul** [comment]
maybe we're not caching whatever magic checksum yarn uses or something that yarn needs to install

**Comment by tlrobinson** [comment]
@camsaul As long as it caches the entire `node_modules` directory it should be fast. I think our `yarn.lock` might just need to be updated. If I do a fresh checkout right now it takes about 30 seconds to run `yarn` the first time, but that updates the `yarn.lock` then subsequent runs of `yarn` take less than a second.

Not a big deal either way, I'm mostly just curious. I might push a PR to see if just updating the lock file helps.

**Pull request merged**
