### PR TITLE
Increase MAX_SERIES from 20 to 200

### PR DESCRIPTION
**Pull request by dricket**
https://github.com/metabase/metabase/issues/3656

I'd personally use this immediately for visualizing more detailed datasets.  Thanks for reviewing!

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

---
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/5592)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by dricket** [comment]
FYI @tlrobinson

**Comment by jasrusable** [comment]
@dricket Any news on this?

**Comment by julienba** [comment]
@dricket same question

**Comment by mjalkio** [comment]
@tlrobinson is there any reason that this hasn't been merged? We're trying to make the move from another platform to Metabase and this is a blocker for us.

**Comment by satyadeepk** [comment]
At least 50 would be a good number. Please merge this.

Usecase:
We are grouping number of events in a mobile app by event name, which are higher than 20. One way to restrict is to set a SQL `having count > X` clause in the query. But since `having` is not supported in the query builder, increasing number of series makes sense.

**Comment by jaGarcia** [comment]
@tlrobinson Sorry to re-ping, but having this commit merged into trunk would be really great.  Thanks!

**Comment by clemzizer** [comment]
Any news?

**Comment by hermansc** [comment]
@senior @tlrobinson @kdoh @camsaul something for 0.30?

**Comment by clemzizer** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/metabase/metabase/5592)*

**Comment by mito** [comment]
admin configurable constants would be sweet

**Comment by adjenks** [comment]
> 
> 
> admin configurable constants would be sweet

@mito 
I second that. Maybe you should open a ticket.

**Comment by rfbird** [comment]
+1 for this getting merged into releases. Just ran into this issue for representing my data from different event timers

**Comment by camsaul** [comment]
@kdoh mind weighing in on this?

**Comment by kdoh** [comment]
https://github.com/metabase/metabase/issues/3656#issuecomment-512610895 is where my head is at on this as well.

**Comment by mazameli** [comment]
Going to go ahead and close this because as @kdoh mentioned, we plan on fixing this problem in a different way that allows for a bit more control and prevents the situation of folks accidentally doing something that could result in a really slow query: https://github.com/metabase/metabase/issues/3656#issuecomment-512610895

@dricket, thanks for opening this PR and for generating all the discussion and feedback.

**Pull request closed without merging**
