### PR TITLE
If actions are not supported, actions should be disabled for a database

### PR DESCRIPTION
**Pull request by calherries**
This PR tightens the logic for enabling actions on the BE to only database that support the actions feature.

Currently, it is possible for the actions to be "enabled" for a database even if actions were not supported. Even though the UI toggle doesn't appear in the admin page for those databases, the `database-actions-enabled` setting can be set via an API call like: `PUT /api/database/:id  { settings: { 'database-actions-enabled': true } ... }`

This meant that everywhere in the code we check if actions were enabled, we have to also check that actions are supported for the database. Our test coverage for this is very thin (only a couple of endpoints were tested).

To simplify things and make sure we don't forget to check in the future, this PR centralizes the constraint in one place: the `pre-update` function for Database. Note actions cannot be enabled on the insert of a database.

The logical constraint being maintained is: If actions aren't supported then actions are disabled.
Or the contrapositive: If actions are enabled then actions are supported.

Update: I've left in the check that the database supports actions whenever we check that actions are enabled as an extra safety measure.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28607)

### CODE REVIEW

**Comment by dpsutton** [comment]
I'm a fan of the addition: checking that actions are supported when enabling. I don't understand why the removal of the check in the actions enabled function. Is it performance related? It seemed a nice sanity check with no downside. Why remove it?

**Comment by calherries** [comment]
@dpsutton It's a code path that should never be hit. I generally like removing code that doesn't ever get run so we don't have to maintain or test it

**Comment by calherries** [comment]
I don't have strong opinions either way though so I've reverted the commit that removes the check. The important thing is this gets merged before the release

**Review by dpsutton — APPROVED** [review]

**Review by tsmacdonald — APPROVED** [review]
:boat:

**Review by kulyk — APPROVED** [review]

**Pull request merged**
