### PR TITLE
Add rollback migration for permissions

### PR DESCRIPTION
**Pull request by noahmoss**
Adds a rollback migration that sets paths in `permissions` based on the values in `data_permissions`. This should allow an instance to be upgraded to 48 and then rolled back to 47 while preserving any modifications to permissions that happened during the upgrade.

### CODE REVIEW

**Comment by noahmoss** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/metabase/metabase/38023?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #37473** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37473?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #38023** <a href="https://app.graphite.dev/github/pr/metabase/metabase/38023?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #38002** <a href="https://app.graphite.dev/github/pr/metabase/metabase/38002?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37934** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37934?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37932** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37932?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37930** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37930?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37837** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37837?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37671** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37671?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37549** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37549?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37426** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37426?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #37427** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37427?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37379** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37379?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #37619** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37619?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37377** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37377?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #37191** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37191?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #37378** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37378?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/38023?utm_source=stack-comment).

**Review by escherize — APPROVED** [review]
Usually we put the migration and rollback in the same changeSet.  Is this its own migration so we don't have to worry about invalidating liquibase checksums? Or could you speak to why it is it's own thing?

Also,

**Comment by noahmoss** [comment]
@escherize Good point. It was largely because I was originally thinking of this as a single SQL script that would rollback the perms all at once. But the way it turned out, it should be pretty easy to split up into separate rollbacks for each perm type so I'll do that.

I think you left out the second part of your comment?

**Comment by escherize** [comment]
Sorry about the cryptic `Also,`: I was just going to say that using `/schema/%` here: https://github.com/metabase/metabase/pull/38023/files#diff-69839413e40ccc70023121e6b2f78d6dae845d96c6d06e0624310b35c6f349f6R25 is a good catch.

**Pull request merged**
