### PR TITLE
Fix LDAP setting validation

### LINKED ISSUE #8222: Bug: 0.30 RC1 Admin LDAP Configuration Broke
There are a few issues with the Authentication > LDAP settings in 0.30 RC1 that don't happen in 0.29.3.

Issues:
1. An error shows up when trying to save that says "Looks like we ran into some problems". There is nothing in the server log or client log to indicate what that is for.
2. Typing in the group search base field does not seem to enable the save button
3. The group search base field is not persisting
4. Group membership mappings are not persisting

Steps to reproduce
1. Launch a fresh metabase and setup Authentication > LDAP.
2. Attempt to save after filling in ldap settings (without group settings). An error will pop up and say "Looks like we ran into some problems." Despite this it appears to persist.
3. Log out and back in. Add a Group Search Base string. Despite changing the field the save changes will not become enabled
4. Toggle something else to get the save button to enable and save. The error "Looks like we ran into some problems" will show up again but this time the group search base will not persist.
5. Attempt to add group membership mappings. The save button in the dialog does not work (clicking it does nothing).

Here are the settings I used in this test (works in 0.29.3):
> LDAP Host: adldap.foo.com
> LDAP Port: blank (default 389)
> LDAP username/password
> User Schema: DC=foo,DC=com
> User Filter: (&(uid={login})(objectClass=organizationalPerson))
> Email Attribute: userPrincipalName
> First Name Attribute: name

- Your browser and the version: Chrome 67
- Your operating system: Windows 7
- Your databases: N/A
- Metabase version: 0.30.RC1
- Metabase hosting environment: Local Windows 7
- Metabase internal database: H2

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #8222

### CODE REVIEW

**Review by senior — CHANGES_REQUESTED** [review]
It looks like this fixes the issue with saving the settings, but it still looks like we have an issue with the mappings.

Now if I click into the group mappings and add a new one, I can click save and it works. If I click `Edit Mappings` again, my new mapping is not there. If I hard refresh the page, the mapping is there. So it looks like it's saying it correctly, just some state isn't getting updated properly.

**Comment by tlrobinson** [comment]
@senior should be fixed now

**Comment by senior** [comment]
@tlrobinson Still looks to be broken. I add a new mapping, then save it. Click `Edit Mappings` again and the thing I added isn't there. I hard refresh the page and click `Edit Mappings` and it's there.

**Comment by tlrobinson** [comment]
@senior I just verified it again and it's working for me.

**Review by senior — APPROVED** [review]

**Comment by senior** [comment]
Not sure what was going on. I was definitely still seeing it this morning, but something must have been cached. Just ran `lein clean`, and tried it from a fresh browser and it was all good.

**Pull request merged**
