### PR TITLE
New question flow [WIP]

### PR DESCRIPTION
**Pull request by kdoh**
Work in progress version of a new approach to starting questions. It's currently very much a prototype so styling should be mostly ignored in favor of flow and other UX considerations.

TODOS:

behavior:
- [x] get pivot mode working
- [ ] metric mode should allow for a choice of breakout.
- [x] Should be able to select SQL mode
- [ ] If there is only one valid column for a given dimension type, don't make the user pick that, just pick it for them 
- [x] Should be able to select a table/segment
- [x] not currently correctly filtering out dimensions based on question type selection
- [x] can’t select a dimension yet
- [x] can’t use Back button yet
- [x] Back arrow on first state of new question screen doesn't do anything
- [ ] need to account for dbs with schemas in the new metric flow

### CODE REVIEW

**Comment by mazameli** [comment]
Not sure if all your latest changes are in yet, but I took a look this morning and took some notes:

- Start page
  - draws a lot of attention to metrics
- `A Metric`
  - If I don’t have any saved metrics, how can we improve the empty state?
  - I tried saving some new metrics in the admin panel and then hard refreshing, but my metrics aren’t showing up in any of the Existing Metrics lists
  - fresh metric: can’t select a database. getting a JS error:
```    
core.js?d2ec:55 Uncaught TypeError: Cannot read property 'type' of undefined
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:56971:30
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:57013:18
    at Array.forEach (native)
    at printBuffer (http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:56989:11)
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:56901:32
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:56016:13
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:55971:17
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:41566:13
    at onMouseLeave (http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:249873:33)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:24190:17)
```

- `a metric on a map`
  - visual design: I think the visual hierarchy should make the selection of the type of map most prominent, and the map itself way less prominent. Maybe even make each map type its own "card," in the same kind of style as each of the selection boxes on the first page of the new question flow.
  - If I can only select one kind of map, like US State, should we skip the selection step?
  - getting a JS error when arriving at this page, and every time I try to click `next`. seems to be the same one as above:

```
core.js?d2ec:55 Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:56971:30
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:57013:18
    at Array.forEach (native)
    at printBuffer (http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:56989:11)
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:56901:32
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:56016:13
    at http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:55971:17
    at dispatch (http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:41663:19)
    at _callee$ (http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:57956:34)
    at tryCatch (http://localhost:8080/app/dist/app-main.hot.bundle.js?10a2bf3b3721de39338d:17072:41)
```

- Clicking on the `SQL` button takes me to `/q` and shows me the query builder along with this error:
`Input to sql->params-snippets-info does not match schema: [(named (not ("Non-blank string" "")) sql)]`

**Comment by kdoh** [comment]
Wanted to add some of my thoughts on the process of building out the initial prototype for this so we can use my (surely numerous) mistakes to discuss some options for making things a bit easier in the future. This isn't comprehensive but maybe it can start the discussion for a couple key areas.

1. Query manipulation was harder than expected.
I had a bit of a hard time knowing which functions to use to manipulate the client side query dictionary in the "right way."  

I think my confusion at first was primarily due to the fact that there are both some query builder specific redux actions and the `lib/query.js` functions, and it's not necessarily clear which our preferred method is. It also looks like the redux actions use the query lib internally so that seems like it should be the preferred method but the QB itself doesn't always use them as far as I could tell.

It also took me a while to understand what some of the functions wanted as far as what `tableMetadata` is. I'm still not actually 100% sure if that's just a table object or not. This is a spot where going back and adding some flow types would be a big win I think.

In the end I ended up just writing new reducers to add relevant bits to a new query dict which is definitely capital W wrong but the code paths ended up being easier to grok that way for the purposes of just trying to get something up and running.


2. Getting associations between databases, tables, and fields wasn't as intuitive as I'd hoped.

In my ideal world, getting the current "right" metadata for a table or database would be somewhat like the following

```
// set a db as the thing we're focusing on
selectDatabase(id)

// get the tables for that thing, ideally not having to pass an arg cause the store knows I just told it what we're focusing on
getTablesForSelectedDatabase()

// same idea for a table
selectTable(tableId)
getFieldsForSelectedTable()

// so on and so forth
```

In my imagination those functions would either fetch the data if it's not around or return the proper stuff if we already have it. As far as I know I'd have to do that manually right now.

In general it feels like we often have a notion of a "currently focused" slice of the data in MB and it'd be great if I could get info about that without having to necessarily pass IDs around all the time. Maybe I don't have to?

3. Knowing which attributes to use on an object wasn't necessarily straightforward.
This is a bit of a follow on from #2. The most common culprit for this in my experience is the field object and the association for table. It has both `fields` and `fields_lookup', one of which just carries associations and one of which has the actual fields and some metadata. This threw me for a loop initially and led to a feeling of uncertainty around whether or not I was "doing it right." 

4. It's not easy to get fields of a certain type.
This is specific to this flow, but getting all the "time stuff" or location stuff from a table was less intuitive than I would have imagined. I'm sure we're going to be doing more and more of this as time goes on so it'd be great to have more utilities to help with this.

In my mind it'd be something like:

`getFieldsByCategory()` => return a map of fields to a category type. Maybe I can also specify a category to limit what comes back?

----

I think overall my main takeaway is that the FE code is large enough that it's hard to know what functions to use and when.

I think one way to solve this is to do a bit more documenting of what the "correct" core APIs should be for common stuff like metadata or query manipulation that is shared across parts of the app.

**Comment by mazameli** [comment]
Checked in with Kyle on some new designs this morning. Loving the direction overall 😍 . Here are some high-level questions I had that I want to keep track of:

- Is the pathway for creating a new custom expression clear and fast enough? Not sure that `Explore` feels like the right label for the mental mode where I know I want to create a new thing.
- Should `New custom expression` be one of the top-most items you see on the very first screen of this flow, e.g. next to SQL?
- The designs are using "number" to refer to metrics in most places, but occasionally using "metric," as in "new metric." We'll want to be careful about being consistent with our language.
- I think the DB/schema/table selection screens could use just a touch of visual differentiation since they look so much alike right now. E.g. putting a faded back large icon/illustration in the top-left to represent the kind of thing you're currently picking. It would be nice to add some transition animations to this flow too, like having the heading and illustration fade and move left as the next step's heading and illustration turn opaque and move in from right to left.
- I think the visual hierarchy of the custom expression screen needs a little dialing-in. The expression box itself looked too much to me like a note or info label for the selections below it. I also think it could be cool to have the expression box move down so that it's centered vertically after the user chooses one of the basic aggregations, and perhaps also after they give the box focus. Maybe it even grows in height/width slightly as it moves down.

**Comment by VikramTiwari** [comment]
@kdoh This seems interesting. Are there any work-in-progress screenshots you could post?

**Comment by attekei** [comment]
Closing this in favor of new PR #5790

**Pull request closed without merging**
