### PR TITLE
Fix new databases being not included in the permissions grid

### LINKED ISSUE #5619: When you add a new database permissions graph is broken until you refresh the page
If you add a new database and head straight to the permissions graph it will show "no permissions" for *everybody* for that new database until you refresh the page. I'm guessing this is another bug that arose from caching the database metadata.

### PR DESCRIPTION
**Pull request by attekei**
Fixes #5619

### CODE REVIEW

**Comment by camsaul** [comment]
we should probably merge into `release-0.26.0` just to be safe

**Comment by camsaul** [comment]
Also this will fix #4455 since they're duplicates

**Comment by attekei** [comment]
@camsaul could you validate that this solves the issue you described, then we could merge this

**Comment by attekei** [comment]
and just switched the base branch, thanks for pointing that out!

**Review by camsaul — APPROVED** [review]
yup just confirmed that this fixes it for me

**Pull request merged**
