### PR TITLE
Fix search in the app bar

### LINKED ISSUE #23609: It is not possible to view search results anymore
**Describe the bug**
Search results container is buried behind the home page and the app bar so it's not possible to view search results anymore.

**Logs**
N/A

**To Reproduce**
1. Go to '/` (home page)
2. Slick on the search box
3. You cannot see or access search results

https://user-images.githubusercontent.com/31325167/176484854-e52f5bb4-cb06-447e-9f94-eaaa4689391a.mov

**Expected behavior**
Search results should work and be visible as before.

**Screenshots**

**Information about your Metabase Installation:**
local dev, `master, a73b5a1cd6986231045d96217b3dc5db619cb82a

**Severity**
P2 or even P1?

**Additional context**
regression since 8b7022a5f76695717da58d5dbb43b041aa97b0a4 (https://github.com/metabase/metabase/pull/23595) cc @ranquild

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/23609
Regression since https://github.com/metabase/metabase/pull/23595

How to test:
- Make sure the top search works on small and large screens

Screenshot 2022-06-29 at 20 58 19
Screenshot 2022-06-29 at 20 59 57

### CODE REVIEW

**Review by npfitz — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac sure, go ahead

Actually, CI almost finished running tests in this PR. Please go ahead and merge it and I'll add that repro afterwards.
Sorry for confusion @ranquild

**Comment by nemanjaglumac** [comment]
Btw, not sure if this was the issue even before (I'm guessing it was), but when accessing Metabase in mobile view "Search" closes if you click on it. Is this an intended behavior?

**Comment by nemanjaglumac** [comment]
> Btw, not sure if this was the issue even before (I'm guessing it was), but when accessing Metabase in mobile view "Search" closes if you click on it. Is this an intended behavior?

Oh, just realized why it's happening.
It closes because Metabase logo below search is still clickable. See what I mean.

https://user-images.githubusercontent.com/31325167/176508667-6cfbb26f-1246-4f15-91a5-562a559351a7.mov

cc @ranquild

**Comment by ranquild** [comment]
@nemanjaglumac taking a look

**Comment by ranquild** [comment]
@nemanjaglumac Fixed

**Pull request merged**
