### PR TITLE
Skip loading Liquibase if not needed

### LINKED ISSUE #3715: Speed up access to liquibase changelog
Right now, when using signed jars, the slowest part of startup is checking for run migrations and running migrations.

On my dev laptop, each of these takes approximately 13s on a signed jar and <1s on an unsigned jar. 

I think the culprit is how we're accessing the changeset files. We're using liquibase.resource.ClassLoaderResourceAccessor as the ResourceAccessor

At https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L49 this code disables any caching of the signed jar, which causes the loader to do whatever magic verifying + accessing a signed jar invokes. (See http://stackoverflow.com/questions/27860598/netbeans-classloader-slow-on-resource-loading-with-signed-jar for a similar example)

Some options on how to improve this:

1. Remove old migrations files, and require people to upgrade through versions in order (eg, upgrading from 0.12 -> 0.21 would require you to upgrade to each version sequentially). This can be mitigated by keeping the last N versions worth of migrations and letting you migrate up to N versions up. To do this, we'd need to modify the migrations code to check for the previous version number, and bomb out if it's unsupported. I don't believe we're storing version numbers explicitly in the application database, but we probably should.

2. Package up all the changesets into a single changelog. That way we only pay for the verification once. This creates a single, unmanageable file, and makes merging feature branches potentially more annoying. 

3. Modify the liquibase code to cache the jar in question

4. Find a different way of shipping migrations for liquibase.

Thoughts @camsaul ?

### PR DESCRIPTION
**Pull request by camsaul**
This should be a big performance win.

Manually count the files in the `migrations` directory and only load & run Liquibase if the `databasechangelog` table doesn't exist or has less entries than the number files in the migrations dir.

### Running with migrations current

screen shot 2017-01-06 at 10 46 57 am

### Running with migrations needed

screen shot 2017-01-06 at 10 49 56 am

### Performance 

As you can see it shaves about 1 second off my launch time when running via `lein ring server`. I've seen similar savings when running via a JAR but I don't have the certs to sign the JAR on my computer so @salsakran can you give this a try and see if saves the 10 seconds we're expecting?

Fixes #3715

### CODE REVIEW

**Comment by camsaul** [comment]
I did a little more profiling in the REPL and it looks like it reduces DB setup time from about a second to just a few milliseconds:

screen shot 2017-01-06 at 11 09 13 am

so it seems like this will be a nice bonus not just for JAR launch time but also `lein ring server` launch time or for tests

**Comment by salsakran** [comment]
Hold off merging until I get a chance to play with this.

With a signed jar, as far as I could tell ~80% of the time was spent getting files out of a signed jar, so depending on how counting works, it might still have a pretty big performance hit just doing that.

**Comment by camsaul** [comment]
Yeah please build a signed JAR with these changes and let me know if the hypothesis is confirmed

**Comment by salsakran** [comment]
some numbers -
First run: 
unsigned : 9s from logging started to the http listener being up
signed: 30s from logging started to the http listener being up, 10s of which were checking for migrations, an additional 10s were running the migrations

Subsequent run:
signed: 5s all in
unsigned: 5s all in

Looks like this works.

However, the first startup time (which is crucial in making this a good experience for people just trying us out) could use some work.

**Comment by salsakran** [comment]
reviewing code now.

**Comment by camsaul** [comment]
Cool. A big chunk of the changes are just moving Liquibase-related code from `db.clj` into a new namespace so you probably don't need to worry about those functions

**Comment by camsaul** [comment]
I think short of not using Liquibase I don't know what we could do to fix the initial launch problem.


Here's an idea:

I've hand-rolled a basic migration framework for just running plain SQL migrations for some past Clojure projects, and we could probably do something like that here. We definitely have more code to work around Liquibase's problems than we would have for an entire set of barebones migration functions. I wouldn't mind writing migrations in plain SQL either and it's easier to figure out how to do something in SQL than to figure out how to do it in Liquibase anyway.

**Review by salsakran — CHANGES_REQUESTED** [review]
This looks reasonable for current production usage, but I think it's a bit fragile to rely on the number of migrations for two reasons -

1. this breaks development on two separate branches each with a single migration on dev.
2. It means we'll need to be really paranoid about removing migrations in the future

It looks like `JarFile$JarFileEntry.getName` should return the filename, and we can then compare those against what's in the table vs just comparing counts.

**Comment by camsaul** [comment]
fair points

**Comment by salsakran** [comment]
I think the most promising idea I had was to extend the build process to replace the migrations directory with a single xml file (or other format) that contains all the migrations for use inside of the jar. 
I think that would reduce the initial startup cost to the price of getting that file out of the jar twice vs two whole directory traversals as currently.

**Comment by camsaul** [comment]
unfortunately most of our early migrations were written in JSON and the newer ones in YAML so in order to concatenate those we would probably have to translate a bunch of the older ones

If we did that I think we could pretty feasibly concatenate all of them into a single YAML file, we could probably even do that as part of the launch process

**Comment by salsakran** [comment]
overall,  I'm 👍  this PR (with the changes mentioned)

I'd like to leave the tracking issue open and keep working on improving first time startup as well.

**Comment by camsaul** [comment]
@salsakran take another look at this. I tweaked the logic to just compare a set of migrations that have been ran with a set of migrations that exist. e.g.

```clojure
(not= #{"001_some_migration"} #{"001_some_other_migration"})
```

I've verified that it works for me but if you want to test it again it wouldn't hurt to have some extra eyes on this seeing how it's a critical code path

**Review by salsakran — APPROVED** [review]

**Comment by salsakran** [comment]
Looks good. mind merging this into a 0.22.1 branch? I dunno if we're going to be able to do enough testing on it this weekend.

**Comment by camsaul** [comment]
Are we still trying to merge this into 22.1?

**Pull request merged**
