### PR TITLE
Background color and layout fixes [WIP]

### PR DESCRIPTION
**Pull request by kdoh**
Trying to clean up a bit of our layout issues stemming from having `className="spread flex flex-column"` at the root of the app which was causing the suggestion sidebar in automatic dashboards to cut off prematurely and causing other persistent layout foibles.

This update will require fixing a couple existing parts of the app that rely on having that positioning and display context to do their own thing, but should hopefully make things saner going forward.

Note I'm basing this off of `autodash-style-polish` and I'm expecting to probably change the base to master after that merges.

### CODE REVIEW

**Comment by mazameli** [comment]
Here's one place that's looking a little funny; Groups as well. The sidebar seems fine in other parts of the admin panel, though.

screen shot 2018-03-23 at 10 49 38 am

**Comment by mazameli** [comment]
Data reference sidebar:

screen shot 2018-03-23 at 11 11 41 am

**Comment by mazameli** [comment]
New Question content is higher up than normal:

screen shot 2018-03-23 at 11 13 36 am

**Comment by mazameli** [comment]
Query builder and SQL placeholder text and Run button are hidden:

screen shot 2018-03-23 at 11 14 33 am

screen shot 2018-03-23 at 11 14 48 am

screen shot 2018-03-23 at 11 14 26 am

**Comment by mazameli** [comment]
I think you mentioned you're already aware of this one, but query results and visualizations aren't appearing.

**Comment by kdoh** [comment]
If you mean in the QB then yeah I'm already on that one.

**Comment by mazameli** [comment]
Cool, yep, that's what I meant. Dashboards seem fine.

**Comment by mazameli** [comment]
Data reference sidebar not showing up:

screen shot 2018-03-23 at 11 20 00 am

**Comment by kdoh** [comment]
Not thinking I want to try and shoehorn this big of a change into 0.29 and since some of the main layout stuff is going to be updated for 0.30 anyhow, I'm thinking it makes sense to hold off on this.

**Pull request closed without merging**
