### PR TITLE
Fix table rendering on the "Information We Collect" doc page

### PR DESCRIPTION
**Pull request by salsakran**
this has been broken for a while =(

### CODE REVIEW

**Comment by mazameli** [comment]
Just looking at the changed file with the View File tab in GH, this looks good. Our tests sure don't seem to like this PR though.

**Review by mazameli — APPROVED** [review]

**Comment by camsaul** [comment]
@mazameli Out tests didn't like this PR because @salsakran canceled the tests

Any objections to me merging this?

**Comment by flamber** [comment]
@camsaul 
It seems like something is still breaking the table, when viewing on website:
https://metabase.com/docs/v0.32.9/information-collection.html#server-side-analytics

**Comment by flamber** [comment]
Pinging @mbvictoria :smile:

**Pull request merged**
