### PR TITLE
Issue #12202 - Sample Dataset data doesn't add up

### PR DESCRIPTION
**Pull request by jeff303**
Fixing total for all order records in sample data

For some reason, I wasn't able to see these updates in the UI, even after deleting and then reloading the sample data via Admin (even when deleting and re-creating the uber-jar).

###### Before submitting the PR, please make sure you do the following
- [N/A] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.
### Tests
-  [N/A] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [X] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`
-  [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by camsaul** [comment]
The EDN file is only used for a few backend tests -- if you want it to show up in the UI you have to update the H2 database itself (`resources/sample-dataset.db`)

**Comment by camsaul** [comment]
How is this related to Issue #12202 ?

**Comment by jeff303** [comment]
Oops, that was supposed to say #12203. Will fix that soon, along with the H2 file.

**Comment by jeff303** [comment]
Closing in favor of #14513.

**Pull request closed without merging**
