### PR TITLE
fix combo stacking in static viz

### PR DESCRIPTION
**Pull request by EmmadUsmani**
Closes https://github.com/metabase/metabase/issues/38827

### Description

Fixes settings calculation, the `stack_type` setting should not be considered valid if it is non-null on a question where `card.display` is combo.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by EmmadUsmani** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/metabase/metabase/38988?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#38988** <a href="https://app.graphite.dev/github/pr/metabase/metabase/38988?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#38984** <a href="https://app.graphite.dev/github/pr/metabase/metabase/38984?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `echarts`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/38988?utm_source=stack-comment).

**Review by alxnddr — APPROVED** [review]
We can merge this for now since the behavior is different between static and dynamic viz, but we will need to change it the other way to support stacked series on combo charts

**Comment by EmmadUsmani** [comment]
@alxnddr Yup it should be a small change when the time comes

**Comment by EmmadUsmani** [comment]
### Merge activity

* **Feb 21, 3:00 PM EST**: @EmmadUsmani started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/38988).

**Pull request merged**
