### PR TITLE
Calculated columns tokenizer should not require spaces between operators and constants

### PR DESCRIPTION
**Pull request by MrMauricioLeite**
should solve #2629

### CODE REVIEW

**Comment by MrMauricioLeite** [comment]
Guys, I'm not sure if it solves the problem. That's because I'm unable to build a local copy on my Windows PC. If anyone can test it to make sure that it works.

I just hope it helps

**Comment by camsaul** [comment]
@MrMauricioLeite it looks like your fix works perfectly. There were some merge conflicts (e.g. `frontend/src/lib/expressions.js` was just moved to `frontend/src/metabase/lib/expressions.js`) so I went ahead and fixed those and opened a new PR #2686. Once that passes CI I'll merge it in.

Thanks for the contribution 👍 💯

**Comment by MrMauricioLeite** [comment]
Thanks man. I'm Happy that this simple trick solves.

Thanks for helping with the CI tests. I promise to better test my PRs in
the future.

**Comment by camsaul** [comment]
@MrMauricioLeite CI was fine we'd just renamed the file since you submitted the PR so that was the only thing I had to change 👍

**Comment by MrMauricioLeite** [comment]
Great! Thanks again.

**Pull request closed without merging**
