### PR TITLE
Permissions v1 [OLD PR]

### PR DESCRIPTION
**Pull request by camsaul**
WIP branch for permissions #1083, #3087
### Sexy :lock_with_ink_pen:

screen shot 2016-08-17 at 5 14 38 pm

screen shot 2016-08-17 at 5 15 17 pm

screen shot 2016-08-17 at 5 15 49 pm

screen shot 2016-08-17 at 5 35 55 pm

screen shot 2016-08-17 at 6 07 36 pm

screen shot 2016-08-17 at 5 41 51 pm

screen shot 2016-08-17 at 7 51 17 pm

screen shot 2016-08-17 at 7 40 39 pm

### CODE REVIEW

**Comment by mazameli** [comment]
I think you've already noted this in the to-dos, and not sure if this is a FE or BE thing, but there are some things like this in user-land:

Questions I don't have permission to see shouldn't be present in the list of Saved Questions:
screen shot 2016-08-18 at 1 26 02 pm

Beyond the visual design, cards on dashboards that I don't have permission to see shouldn't render their titles:
screen shot 2016-08-18 at 1 25 31 pm

**Comment by tlrobinson** [comment]
That (and in generally permissions checks) should probably be a backend thing so we don't leak card names etc to users who don't have permission to see them.

**Comment by MrMauricioLeite** [comment]
That leads me to think about what is going to happen on metabot, since we
don't have a signedin user to test his permissions against when listing
cards

[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-08-18 18:50 GMT-03:00 Tom Robinson <notifications@github.com>:

**Comment by camsaul** [comment]
FWIW I would vote that we *do* show the names of locked cards; it will be easier for Mr. Low-Level Employee to politely ask Sir Admin to grant them appropriate access for a data underlying a card if they know what that card is. I can see the conversation: "Sir Admin, I can't see a card on the sales dashboard." "Which one?" "I don't know which one. I can't even see the title."

**Comment by mazameli** [comment]
The counter example for that is the problem of sensitive card names, e.g. "Maz's top 10 HR violations." Sometimes the existence of a card is sensitive in its own right.

**Comment by camsaul** [comment]
Also FWIW I think making sure we don't "leak" the names of locked cards in the API is a make-work project for us that doesn't give us any real security benefit. We'd have to rework a dozen or so API endpoints to keep people from seeing info that doesn't need to be hidden in the first place.

**Comment by camsaul** [comment]
Is "Maz's top 10 HR violations" a real-world example?

**Comment by camsaul** [comment]
Superseded by #3376

**Comment by camsaul** [comment]
I'm going to go ahead and close this now that #3376 is the definitive Permissions PR

**Pull request closed without merging**
