### PR TITLE
emails to lowercase

### PR DESCRIPTION
**Pull request by VikramTiwari**
Fixes: https://github.com/metabase/metabase/issues/3047

### CODE REVIEW

**Comment by camsaul** [comment]
if we were to do this it would make sense to do it in the backend and enforce it as an invariant there

**Comment by VikramTiwari** [comment]
@camsaul Of-course we should use best solution. This is a quick and dirty attempt, but if we can do it better in backend, that is prefered. This is so much code repetition anyway.

**Comment by camsaul** [comment]
also this PR would break login anyone who set up an account with an non-lowercased email. Since their email would be lowercased automatically by the input forms they would never be able to login again

**Comment by VikramTiwari** [comment]
Oops! Yes. Didn't gave thought about currently deployed instances and their operability. Well, in that case, closing this PR, might raise another if I can figure out it from backend with interoperability with older versions. Also saw your message on issue. Let's discuss best way to approach on solving/not solving this issues there.

**Pull request closed without merging**
