### PR TITLE
remove unused dependencies

### PR DESCRIPTION
**Pull request by daltojohnso**
------ dependencies ------

**node-libs-browser** -- seems like this was a peer dependency of webpack at one point, in v1 perhaps.

**react-addons-shallow-compare** -- added over 5 years ago, superseded by `recompose`, `React.memo` and `React.PureComponent`

**redux-thunk** -- was surprised to see we didn't actually use this, but it appears we have our own custom implementation in `store.js` called `thunkWithDispatchAction`

**stack-source-map** -- added 5 years ago, no usage of it now. looks like it was added as part of a PR to add storybook to our codebase.

**webpack-dev-middleware** -- added 3 years ago, misplaced dev dependency added during an upgrade from webpack v1 to v3, but there's no usage of it as we use `webpack-dev-server`.

------ devDependencies ------

**color-diff** -- this was used in `bin/colopocalypse`, a tool that was actually removed just a few days ago https://github.com/metabase/metabase/commit/b413f2582ab4c33c42075a0f566745a455887dd7

**exports-loader and imports-loader** -- added here https://github.com/metabase/metabase/commit/7b845cd7d338d040dc5dd1176a95402b259c7a0b but I don't see any usage anywhere

**insightful** -- an amusing dependency https://github.com/kdoh/insightful that snuck in here: https://github.com/metabase/metabase/commit/7d178fd73f2fe881cdbc87c9da61a217eafedd80

**proxymise** -- was used in enzyme but no longer

**Verification**
`yarn build` and `yarn build-hot` work, the app compiles, and the app still works.

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]
Nice! Did you use a tool like [depcheck](https://github.com/depcheck/depcheck) for this or reading+grepping? Adding a linter for this would be great!

**Comment by daltojohnso** [comment]
Never heard of depcheck! But I used it and found more dead dependencies, so thanks!

**Review by paulrosenzweig — APPROVED** [review]
🎉

**Review by ariya — APPROVED** [review]

**Review by kdoh — APPROVED** [review]
Hah, forgot all about `insightful`

**Pull request merged**
