### PR TITLE
remove static viz import from pie chart option

### PR DESCRIPTION
**Pull request by EmmadUsmani**
Thread https://metaboat.slack.com/archives/C505ZNNH4/p1723203837352799?thread_ts=1723201440.582679&cid=C505ZNNH4

### Description

Importing `truncateText` from the static viz directory caused our bundle size to increase significantly. In this PR we remove that import, and replace it with an import for a similar function in the main app directory. We had to create a similar `truncateText` function from scratch since one didn't already exist.

### How to verify

Create a pie chart where dimension values have long names, or with a long prefix/suffix for the metric in column settings, add to a dashboard on a small dashcard, hover a slice or legend item and confirm truncation still works.

### Demo

Screenshot 2024-08-22 at 6 50 33 PM

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

Covered by existing storybook test for truncation.

### CODE REVIEW

**Comment by EmmadUsmani** [comment]
* **#47159** <a href="https://app.graphite.dev/github/pr/metabase/metabase/47159?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @EmmadUsmani and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alxnddr — COMMENTED** [review]
Looks good! Wdyt about moving specs of `truncateText` from "metabase/static-viz/lib/text" to the new implementation and replacing this old static truncateText with the new implementation to deduplicate this logic?

**Review by alxnddr — APPROVED** [review]
🙏

**Review by uladzimirdev — APPROVED** [review]
image

we're back, thanks!

**Pull request merged**
