### PR TITLE
Fingerprint numbers for possible unix timestamps

### PR DESCRIPTION
**Pull request by dpsutton**
Addresses https://github.com/metabase/metabase/issues/2074

Attempt to fingerprint number columns to see if those numbers are +- 20 years of now when interpreted as unix timestamps in seconds, millis, and microseconds.

Couple things i'm torn about and not sure if they are deal breakers, need to be addressed here, or just in the future and a new issue made:
1. Are these really fingerprints? The other values captured are min/max/q1/q3/std/avg. These are proper fingerprints describing the values. The values `percent-seconds` and their ilk are tabulations we accumulate in order to guess the data type but after that they aren't really fingerprints about the data. They don't describe the data shape or give any insight. This almost seems like transient data during sync that is either acted upon or discarded rather than being some metadata about the data that could aid the UI. And if this is true, is that also the case for `percent-email`, `-url`, `-state`, and `-json` that we do in the text fingerprinters?
2. If we decide that the special-type is indeed a unixtimestamp, the fingerprint is immediately worthless. Because if we decide its a date, then the standard deviation and average no longer make sense, and we would want to rerun the date fingerprint across them. This is currently a problem when changing these types manually (we don't schedule a refingerprint when we should). So its not clear if we should figure out how to schedule a new fingerprint with the new datetime special-type or let the mismatched fingerprint/field continue.

This change is pretty large but that's largely for an annoying reason that lots of tests have the fingerprints in them. The changeset is almost completely described by the following:

```clojure
(def twenty-years-ago (.. (LocalDateTime/now)
                          (minus 20 ChronoUnit/YEARS)
                          (toInstant ZoneOffset/UTC)
                          (getEpochSecond)))

(def twenty-years-from-now (.. (LocalDateTime/now)
                               (plus 20 ChronoUnit/YEARS)
                               (toInstant ZoneOffset/UTC)
                               (getEpochSecond)))

(defn between [l h]
  (fn [x]
    (<= l x h)))

(deffingerprinter :type/Number
  (redux/post-complete
    ((filter real-number?) (robust-fuse {:histogram            histogram
                                         :percent-seconds      (stats/proportion (between twenty-years-ago twenty-years-from-now))
                                         :percent-milliseconds (stats/proportion
                                                                 (between (* twenty-years-ago 1000)
                                                                          (* twenty-years-from-now 1000)))
                                         :percent-microseconds (stats/proportion
                                                                 (between (* twenty-years-ago 1000000)
                                                                          (* twenty-years-from-now 1000000)))}))
    (fn [{h :histogram :keys [percent-seconds percent-milliseconds percent-microseconds]}]
      (let [{q1 0.25 q3 0.75} (hist/percentiles h 0.25 0.75)]
        (robust-map
          :min (hist/minimum h)
          :max (hist/maximum h)
          :avg (hist/mean h)
          :sd  (some-> h hist/variance math/sqrt)
          :q1  q1
          :q3  q3
          :percent-seconds percent-seconds
          :percent-milliseconds percent-milliseconds
          :percent-microseconds percent-microseconds)))))
```

and making use of that in the classifier:

```clojure
(s/defn ^:private infer-special-type-for-number-fingerprint :- (s/maybe su/FieldType)
  [number-fingerprint :- i/NumberFingerprint]
  (let [percentages (select-keys number-fingerprint [:percent-seconds
                                                     :percent-milliseconds
                                                     :percent-microseconds])]
    (->> percentages
         (filter (fn [[k v]] (and (number? v) (>= v percent-valid-threshold))))
         ffirst
         (get {:percent-seconds      :type/UNIXTimestampSeconds
               :percent-milliseconds :type/UNIXTimestampMilliseconds
               :percent-microseconds :type/UNIXTimestampMicroseconds}))))

(defn infer-special-type* [base-type fingerprint]
  (match [base-type fingerprint]
    [(:isa? :type/Text) {:type {:type/Text text-fingerprint}}]
    (infer-special-type-for-text-fingerprint text-fingerprint)

    ;; use :type/Number instead of :type/Integer as Oracle maps to :type/Decimal for their biginteger type
    [(:isa? :type/Number) {:type {:type/Number number-fingerprint}}]
    (infer-special-type-for-number-fingerprint number-fingerprint)

    :else nil))
```

### CODE REVIEW

**Comment by sbelak** [comment]
re 1): I agree that the stuff that only helps classification and is never used afterwards should ideally be made transient.

re 2): Ideally we should refingerprint (we should in general be refingerprinting more often). To not get too many sync attempts (especially for folks with sync turned off/manual), we should at the very least nuke the fingerprint when it becomes invalid so that it gets redone on next sync.

With all this in mind, I'm not super stoked about this approach. I think this is one of the cases where if name-based classifiers don't work, it's good enough to fall back to manual intervention (@mazameli what do you reckon from the UX perspective?). If we do decide to have a specialised classifier, I'd just use what we already have from the number fingerprint, by checking if Q1 and Q3 are sane for a date (which is more or less what your approach does), plus a sanity check in max & min.

**Comment by dpsutton** [comment]
> we do decide to have a specialised classifier, I'd just use what we already have from the number fingerprint, by checking if Q1 and Q3 are sane for a date (which is more or less what your approach does), plus a sanity check in max & min.

I hadn't thought about this approach and it makes so much sense now.

I agree with your sentiment that this being too automatic might not be very good. Clever when it works but if it guesses wrong it will be completely crazy. Imagine if we interpret some serial numbers as dates and don't ever inform the user why that's the case, and all their charts have some nonsensical date data instead of serial numbers.

About refingerprinting, I added a refingerprinting step after the sync task if the sync didn't take too long to randomly resync up to 1,000 fields i think. It will hopefully work to keep the fields more up-to-date but i agree with you that there's a more systematic approach that needs to be taken.

**Comment by dpsutton** [comment]
Updated the logic to just check the quartiles. I wish i would have thought of that first. Nicely solves the transient state problem and removes a ton of noise from the diff that comes from updating lots of fingerprints in tests.

I'm very much on the fence if this change should be done and i think you raised a lot of good points @sbelak . 

Original ticket: https://github.com/metabase/metabase/issues/2074

**Comment by mazameli** [comment]
> To dream out loud, I would like if we could collect lots of intuitive guesses about what metabase thinks their data is with a way to easily toggle them on and accept them rather than just apply them outright. Either a full list or when they're browsing data some kind of pop-up "this looks like unix seconds, is that right?" and if they click accept or dismiss we transform them into dates or don't pester them again.

I think this is the way we'd have to play it if there is indeed a real possibility that we'll get it wrong, i.e., what you said here:

>  if it guesses wrong it will be completely crazy. Imagine if we interpret some serial numbers as dates and don't ever inform the user why that's the case, and all their charts have some nonsensical date data instead of serial numbers.

Figuring out the right UX for this would not be a quick thing, though. It's the kind of cool thing that we'd want to bookmark and keep top of mind that we _could_ do that would help inform e.g. a redesign of the Data Browser, Data Reference, or Data Model. Kyle and I were talking recently about potentially even _merging_ the Data Browser and Data Reference, and I could totally see these kinds of suggestions popping up there as well as in the Data Model.

But yeah, seems like a version 0.39 / 0.40 / v.later thing.

**Comment by dpsutton** [comment]
thanks for your thoughts @mazameli . I'm gonna close this draft PR and we can wait or possibly not do it. I don't know how many people this feature would help but i suspect its pretty low and pretty close to the number of people it might get wrong as well.

Without some kind of analysis explainer or some way to accept metabase's guesses, i'm a bit hesitant to do this one.

**Pull request closed without merging**
