### PR TITLE
Add databases to search results

### PR DESCRIPTION
**Pull request by tsmacdonald**
image

Wasn't sure what else to put in the result, @kdoh

### CODE REVIEW

**Comment by tsmacdonald** [comment]
Added a description:

image

**Comment by tsmacdonald** [comment]
And if we match on the description we get highlighting, as per usual:

image



(it probably makes sense to highlight search terms in the description at all times, but...that's a separate issue)

**Review by dpsutton — APPROVED** [review]

**Review by kdoh — APPROVED** [review]

**Comment by flamber** [comment]
@tsmacdonald This should probably have gone into `release-x.39.x` right?

**Comment by tsmacdonald** [comment]
@flamber it's a little green for 39.0, especially with how it handles DB descriptions. With a little more bake time I'm hoping to get it (and follow-up work) in either 39.1 or 40.

**Pull request merged**
