### PR TITLE
Trendlines mega branch

### PR DESCRIPTION
**Pull request by sbelak**
This combines #8691 and #8703. 

Note: the scale of X axis is changed to days.

I've made a very provisional fix for smart scalars to work with the new format (just take the first insight), but we need to think about how to handle multi-series there. cc @kdoh 

Frontend:
* [x] multiseries
* [x] non-linear
* [x] fix smart scalars

### CODE REVIEW

**Comment by tlrobinson** [comment]
@sbelak can we use underscores instead of dashes in all JSON responses?

**Comment by tlrobinson** [comment]
I've included the frontend for both multiseries and non-linear trendlines in this branch.

**Comment by tlrobinson** [comment]
screenshot 2018-10-17 12 57 16

**Comment by mazameli** [comment]
Turning the trend line on sometimes causes the lines/bars to jump upwards. It seems to be that the trend line is extending below the point where the series intersects the y-axis.

line-jumps

screen shot 2018-10-17 at 5 05 27 pm

bars-move

**Pull request merged**
