### PR TITLE
Expose additional string filter options in QB :yum: #1422

### PR DESCRIPTION
**Pull request by camsaul**
Expose [`starts-with`](https://github.com/metabase/metabase/wiki/Query-Language-'98#starts-with-filter), [`ends-with`](https://github.com/metabase/metabase/wiki/Query-Language-'98#ends-with-filter), and [`contains`](https://github.com/metabase/metabase/wiki/Query-Language-'98#contains-filter) string filters in the Query Builder.

Implements #1422

### CODE REVIEW

**Comment by camsaul** [comment]
screen shot 2016-01-26 at 6 26 42 pm

**Comment by agilliland** [comment]
Does this filter operator work on every driver that we have?

**Comment by kdoh** [comment]
Do we have the ability to do "does not contain?"

**Comment by camsaul** [comment]
@agilliand yes this has been part of MBQL for a long time now and is well tested for all the drivers

**Comment by camsaul** [comment]
@kdoh no but we could... That will require some extra work , mostly involving extra unit tests so if you want to open an issue and assign it to me I will do that separately

**Comment by kdoh** [comment]
@camsaul I definitely think if we're going to include contains and these other string filters folks are going to want the ability to exclude values as well. For example I want to filter such that none of the user emails have @metabase.com in the email field. What do you think @metabase/core-developers ?

**Comment by camsaul** [comment]
@kdoh FWIW all these filters used to be in the Query Builder, I added them in #839 and they were lost in a transition at some point. I agree that we should add "does not contain" but I don't think that should block re-enabling filters we already had

**Comment by agilliland** [comment]
I agree that having the complementary operation `does-not-contain` makes sense.  We should add that in for completeness.

**Comment by kdoh** [comment]
@camsaul Roger. I wouldn't block merging this for that but just want to make sure we're thinking of the whole set of use cases and we make sure we ship a coherent set of useful string filters this time.

I also think we'll want to examine which filters are promoted vs hidden under the more options for strings. If i had to guess "contains" and "does not contain" will probably be the among the most common uses for string filtering so we'll want to make sure they aren't always a second click away.

**Comment by agilliland** [comment]
If we feel that we want to tweak the positioning of these operators in the widget and we want to include does-not-contain in order to make this a more complete feature then let's do that in this PR.

**Comment by camsaul** [comment]
`does-not-contain` is a separate feature #1829 

@kdoh If I remember correctly when we originally added them they were part of the "advanced" filter options. Do you want to pull this PR and consider whether they should be moved to the not-advanced (?) filter options?

**Comment by kdoh** [comment]
@camsaul That's my main contention. I wouldn't consider ```contains``` or ```does not contain``` to be "advanced" for the intended GUI audience whereas maybe ```null```, ```not null``` and ```starts with``` and ```ends with``` are a bit more special case and should live below the "fold"

**Comment by camsaul** [comment]
@kdoh I'll move `contains`. What about `starts-with`/`ends-with` ?

**Comment by kdoh** [comment]
@camsaul I think we can leave them under more options unless someone else has a strong feeling that they should be one of the common defaults.

**Comment by agilliland** [comment]
I thought we were adding `does-not-contain`?

**Comment by camsaul** [comment]
I have a separate PR for that. I merged this in so I could rebase that branch off of it. Unfortunately that branch is just hanging out since GitHub is taking their time re-enabling PRs

**Pull request merged**
