### PR TITLE
Make sure resolved-joined-fields deduplicates :fields 

### LINKED ISSUE #14629: Sandboxing on tables with remapped FK (Display Values) causes query to fail
**Describe the bug**
When using column sandboxing on a table with remapped FK (Display Values), then the sandboxed query fails on 1.38.0-rc4.
This works in 1.37.8.

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Reviews > Product ID :gear: > Display Values = Use foreign key: `Products.Title`
image
2. Admin > People > create user "U1" and set attributes `user_id`=`1`
3. Admin > Permissions, revoke all collection and data permissions, and grant full access to Products, and sandbox to Reviews:
image
4. Login as user "U1" and go to Reviews table, which fails with `Value does not match schema: {:query {:fields (named (not ("distinct" a-clojure.lang.PersistentVector)) "Distinct, non-empty sequence of Field clauses")}}`
image
5. Same instance, just running 1.37.8 works:
image

<details><summary>Full stacktrace</summary>

```
2021-02-02 15:59:48,158 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 1,
 :started_at #t "2021-02-02T15:59:47.466413+01:00[Europe/Copenhagen]",
 :error_type :invalid-query,
 :json_query {:database 1, :query {:source-table 4}, :type "query", :parameters [], :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> util.schema$schema_core_validator$fn__17782.invoke(schema.clj:29)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals_STAR_.invokeStatic(wrap_value_literals.clj:137)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals_STAR_.invoke(wrap_value_literals.clj:133)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40651.invoke(wrap_value_literals.clj:147)"
  "query_processor.middleware.annotate$add_column_info$fn__40536.invoke(annotate.clj:578)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46234.invoke(permissions.clj:69)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47767.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46432.invoke(cumulative_aggregations.clj:60)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__49135.invoke(row_level_restrictions.clj:327)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48004.invoke(resolve_joined_fields.clj:35)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__48323.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44755.invoke(add_implicit_joins.clj:249)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47044.invoke(large_int_id.clj:44)"
  "query_processor.middleware.format_rows$format_rows$fn__47024.invoke(format_rows.clj:74)"
  "query_processor.middleware.desugar$desugar$fn__46498.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45516.invoke(binning.clj:225)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46034.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44303.invoke(add_dimension_projections.clj:315)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44506.invoke(add_implicit_clauses.clj:138)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__49135.invoke(row_level_restrictions.clj:327)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44904.invoke(add_source_metadata.clj:103)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__48737.invoke(column_level_perms_check.clj:25)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47964.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45104.invoke(auto_bucket_datetimes.clj:139)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46081.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__47749.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46133.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__46754.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44913.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48685.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47975$fn__47979.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47975.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46972.invoke(fetch_source_query.clj:264)"
  "query_processor.middleware.store$initialize_store$fn__48694$fn__48695.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:42)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__48694.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__48703.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47096.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44773.invoke(add_rows_truncated.clj:35)"
  "metabase_enterprise.audit.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__31273.invoke(handle_audit_queries.clj:162)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48670.invoke(results_metadata.clj:146)"
  "query_processor.reducible$async_qp$qp_STAR___33081$thunk__33082.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___33081.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___33090$fn__33093.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___33090.invoke(reducible.clj:134)"
  "query_processor$preprocess_query.invokeStatic(query_processor.clj:162)"
  "query_processor$preprocess_query.invoke(query_processor.clj:154)"
  "query_processor$query__GT_preprocessed.invokeStatic(query_processor.clj:168)"
  "query_processor$query__GT_preprocessed.invoke(query_processor.clj:164)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$fn__48947$preprocess_source_query__48952$fn__48953$fn__48954.invoke(row_level_restrictions.clj:135)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$fn__48947$preprocess_source_query__48952$fn__48953.invoke(row_level_restrictions.clj:134)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$fn__48947$preprocess_source_query__48952.invoke(row_level_restrictions.clj:129)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$fn__49051$gtap__GT_source__49056$fn__49060.invoke(row_level_restrictions.clj:207)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$fn__49051$gtap__GT_source__49056.invoke(row_level_restrictions.clj:195)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_gtap.invokeStatic(row_level_restrictions.clj:258)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_gtap.invoke(row_level_restrictions.clj:244)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_gtaps$replace_49108__49109.invoke(row_level_restrictions.clj:268)"
  "mbql.util.match$replace_in_collection$iter__19339__19343$fn__19344.invoke(match.clj:139)"
  "mbql.util.match$replace_in_collection.invokeStatic(match.clj:138)"
  "mbql.util.match$replace_in_collection.invoke(match.clj:133)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_gtaps$replace_49108__49109.invoke(row_level_restrictions.clj:268)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_gtaps.invokeStatic(row_level_restrictions.clj:268)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_gtaps.invoke(row_level_restrictions.clj:263)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$gtapped_query.invokeStatic(row_level_restrictions.clj:310)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$gtapped_query.invoke(row_level_restrictions.clj:307)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__49135.invoke(row_level_restrictions.clj:321)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44904.invoke(add_source_metadata.clj:103)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__48737.invoke(column_level_perms_check.clj:25)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47964.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45104.invoke(auto_bucket_datetimes.clj:139)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46081.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__47749.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46133.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__46754.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44913.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48685.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47975$fn__47979.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47975.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46972.invoke(fetch_source_query.clj:264)"
  "query_processor.middleware.store$initialize_store$fn__48694$fn__48695.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__48694.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__48703.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47096.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44773.invoke(add_rows_truncated.clj:35)"
  "metabase_enterprise.audit.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__31273.invoke(handle_audit_queries.clj:162)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48670.invoke(results_metadata.clj:146)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46375.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__47838.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46318.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___33081$thunk__33082.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___33081.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___33090$fn__33093.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___33090.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:235)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:231)"
  "query_processor$fn__49181$process_query_and_save_execution_BANG___49190$fn__49193.invoke(query_processor.clj:247)"
  "query_processor$fn__49181$process_query_and_save_execution_BANG___49190.invoke(query_processor.clj:239)"
  "query_processor$fn__49225$process_query_and_save_with_max_results_constraints_BANG___49234$fn__49237.invoke(query_processor.clj:259)"
  "query_processor$fn__49225$process_query_and_save_with_max_results_constraints_BANG___49234.invoke(query_processor.clj:252)"
  "api.dataset$fn__63122$fn__63125.invoke(dataset.clj:55)"
  "query_processor.streaming$streaming_response_STAR_$fn__63103$fn__63104.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__63103.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__17489.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error "Value does not match schema: {:query {:fields (named (not (\"distinct\" a-clojure.lang.PersistentVector)) \"Distinct, non-empty sequence of Field clauses\")}}",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data
 {:type :schema.core/error,
  :value
  {:database 1,
   :type :query,
   :query
   {:source-metadata
    [{:name "ID", :id 36, :table_id 4, :display_name "ID", :base_type :type/BigInteger, :special_type :type/PK, :fingerprint nil, :settings nil}
     {:name "PRODUCT_ID", :id 33, :table_id 4, :display_name "Product ID", :base_type :type/Integer, :special_type :type/FK, :fingerprint {:global {:distinct-count 176, :nil% 0.0}}, :settings nil}
     {:name "REVIEWER",
      :id 35,
      :table_id 4,
      :display_name "Reviewer",
      :base_type :type/Text,
      :special_type nil,
      :fingerprint
      {:global {:distinct-count 1076, :nil% 0.0},
       :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.001798561151079137, :average-length 9.972122302158274}}},
      :settings nil}
     {:name "RATING",
      :id 31,
      :table_id 4,
      :display_name "Rating",
      :base_type :type/Integer,
      :special_type :type/Score,
      :fingerprint {:global {:distinct-count 5, :nil% 0.0}, :type {:type/Number {:min 1.0, :q1 3.54744353181696, :q3 4.764807071650455, :max 5.0, :sd 1.0443899855660577, :avg 3.987410071942446}}},
      :settings nil}
     {:name "BODY",
      :id 32,
      :table_id 4,
      :display_name "Body",
      :base_type :type/Text,
      :special_type :type/Description,
      :fingerprint {:global {:distinct-count 1112, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 177.41996402877697}}},
      :settings nil}
     {:table_id 4,
      :special_type :type/CreationTimestamp,
      :unit :default,
      :name "CREATED_AT",
      :settings nil,
      :id 34,
      :display_name "Created At",
      :fingerprint {:global {:distinct-count 1112, :nil% 0.0}, :type {:type/DateTime {:earliest "2016-06-03T00:37:05.818Z", :latest "2020-04-19T14:15:25.677Z"}}},
      :base_type :type/DateTime}
     {:table_id 1,
      :special_type :type/Title,
      :name "TITLE",
      :settings nil,
      :id 5,
      :display_name "Product → Title",
      :fingerprint {:global {:distinct-count 199, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}},
      :base_type :type/Text,
      :source_alias "PRODUCTS__via__PRODUCT_ID"}],
    :fields
    [[:field-id 36]
     [:field-id 33]
     [:field-id 35]
     [:field-id 31]
     [:field-id 32]
     [:field-id 34]
     [:joined-field "PRODUCTS__via__PRODUCT_ID" [:field-id 5]]
     [:joined-field "PRODUCTS__via__PRODUCT_ID" [:field-id 5]]],
    :joins [{:strategy :left-join, :source-table 1, :alias "PRODUCTS__via__PRODUCT_ID", :fk-field-id 33, :condition [:= [:field-id 33] [:joined-field "PRODUCTS__via__PRODUCT_ID" [:field-id 8]]]}],
    :source-query
    {:source-table 4,
     :filter [:= [:field-id 33] [:value 1 {:base_type :type/Integer, :special_type :type/FK, :database_type "INTEGER", :name "PRODUCT_ID"}]],
     :fields [[:field-id 36] [:field-id 33] [:field-id 35] [:field-id 31] [:field-id 32] [:datetime-field [:field-id 34] :default] [:joined-field "PRODUCTS__via__PRODUCT_ID" [:field-id 5]]],
     :joins
     [{:strategy :left-join, :source-table 1, :alias "PRODUCTS__via__PRODUCT_ID", :fk-field-id 33, :condition [:= [:field-id 33] [:joined-field "PRODUCTS__via__PRODUCT_ID" [:field-id 8]]]}]}}},
  :error {:query {:fields (named (not ("distinct" a-clojure.lang.PersistentVector)) "Distinct, non-empty sequence of Field clauses")}}},
 :data {:rows [], :cols []}}
```

</details>

**Information about your Metabase Installation:**
Hash `6312927` ~1.38.0-rc4

**Additional context**
Related to https://github.com/metabase/metabase-enterprise/issues/405

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #14629

### CODE REVIEW

**Comment by sbelak** [comment]
I'm not sure this fixes the original issue. My understanding was that we get this error because `fields` is empty which is in term caused by results_metadata/source-metadata not being populated. The fix I was pursuing with #14660 tries to populate it if it's not.

**Comment by camsaul** [comment]
This PR fixes #14629 (Cypress repo test is now passing) but there might be other things to do for other bugs 🤷

**Comment by flamber** [comment]
From my testing, this seems to fix #14629.
And also partially fixes #13641, but only if there's FK remapping, otherwise it fails as before.
But I can still reproduce #10474.

**Comment by camsaul** [comment]
> From my testing, this seems to fix #14629.

That's what this PR is meant to fix

> And also partially fixes #13641, but only if there's FK remapping, otherwise it fails as before.

This PR is not for fixing 13641, we can address that separately

> But I can still reproduce #10474.

Why is this issue closed if it's not fixed yet? This PR is for fixing #14629, not #10474. We can fix that one in a follow-on PR as well

**Review by nemanjaglumac — APPROVED** [review]
Since we can't rely on Cypress at the moment, I did a manual reproduction and it seems to be working fine:
image

**Pull request merged**
