### PR TITLE
Relative datetime filters: Dashboards fixes

### LINKED ISSUE #21807: Bugs in the relative date/time dashboard filter widget
- [ ] The back button doesn't work
- [ ] If the user selects a specific date or relative date and then tries to access the widget again, it should display the last widget state with selected values (not the list with all possible date filters).
- [ ] There is no `Exclude dates...` button
- [ ] In relative dates, there is no `Starting from...` button

image

### PR DESCRIPTION
**Pull request by akiselev**
Fixes #21807

* Correctly sets `onBack={undefined}` for `DatePickerHeader` in dashboards
* Fix dashboard filter validation logic  (allow the field to be `null`)
* Add `Exclude` and `Starting from` serialization/deserialization

### CODE REVIEW

**Comment by akiselev** [comment]
@mazameli do these filter strings make sense?

* `past30days` + Starting from 3 years ago => `past30days~3years`
* `next3years` + Starting 5 months from now => `next3years~5months`
* Exclude Monday: `days~Mon`
* Exclude Tuesday, Wednesday, and Friday: `days~Tue-Wed-Fri`
* Exclude February `months~Feb`
* Exclude February, June, and December: `months~Feb-Jun-Dec`
* Exclude second quarter: `quarters~2`
* Exclude first and third quarters: `quarters~1-3`
* Exclude 12am (midnight): `hours~0`
* Exclude 12am and 11pm: `hours-0-23`
* ... and so on

**Comment by mazameli** [comment]
@akiselev The format you're using is tripping me up a bit here, so let me try rewriting this to answer what I think you're asking. I'll use a "Created At" column for example's sake.

The bits in double quotes are the user-facing strings I'm expecting in the UI. I believe I'm primarily confirming what you originally wrote.

---

`past30days~3years`: "Created At Past 30 days, starting from 3 years ago"
`next3years~5months`: "Created At Next 3 years, starting 5 months from now"

`days~Mon`: "Created At isn't Monday"
`days~Mon-Tue`: "Created At isn't Monday or Tuesday"
`days~Tue-Wed-Fri`: "Created At isn't 3 days" (i.e., any more than 2 selections, we should collapse down into "x days/weeks/months/etc")
`months~Feb`: "Created At isn't February"
`months~Feb-Mar`: "Created At isn't February or March"
`months~Feb-Jun-Dec`: "Created At isn't 3 months"

`quarters~2`: "Created At isn't Q2"
`quarters~1-3`: "Created At isn't Q1 or Q3"
`quarters~1-2-3`: "Created At isn't Q1, Q2, or Q3" (i.e., with quarters, since they're short to write, we should just always list out all of them and not collapse them like with days/months/etc."

`hours~0`: "Created At isn't 12 AM"
`hours-0-23`: "Created At isn't 12 AM or 11 PM"
`hours-0-13-23`: "Created At isn't 3 hours of the day" (saying "hours of the day" to disambiguate from like a duration of time, e.g. "isn't 3 hours" would sound like we might be saying "isn't 3 hours _long_")

**Comment by akiselev** [comment]
@mazameli that's correct.

@metamben mentioned that the format was confusing so I was wondering if you had any other ideas (the regex is easy to change)

**Comment by metamben** [comment]
> @metamben mentioned that the format was confusing 

In particular I can see potential problems because `~` is already used to choose between inclusive and exclusive intervals.

I could also imagine all kinds of combinations of relative datetimes: with and without inclusion and with offset forwards and backwards. Why can we shift the next 3 days into the future but not into the past? Even if we don't want to support all of these combinations, I would prefer a syntax that doesn't preclude adding them later.

**Comment by mazameli** [comment]
@akiselev Do you need anything else from me on this, or did our slack conversation unblock you sufficiently?

**Review by alxnddr — APPROVED** [review]

**Pull request merged**
