### PR TITLE
Match SparkSQL database-type case insensitive

### LINKED ISSUE #27466: SparkSQL driver doesn't work well with capital database-types
**Describe the bug**
Some implementations of the Hive Metastore that the SparkSQL connector will connect to return the `database_type` in capitals, e.g. `BIGINT`

**Expected behavior**
The driver shouldn't care about the casing

### PR DESCRIPTION
**Pull request by bjgbeelen**
Fix #27466

This is a small change. Some Hive metastores return the `database-type` in capitals (e.g. `INT` or `BIGINT`.
We don't care about how the type is written, so the easiest thing to do before the pattenr matching is making sure the `database-type` is written in lowercase.

I tried running the backend tests, but i get a compile error `Javascript resource not found: frontend_client/app/dist/lib-static-viz.bundle.js"`. I've tried and verified the correctness of this small fix in a separate driver build though

Please let me know if more is required

### Tests

- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27444)

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
Thank you for the contribution @bjgbeelen 
I've notified the backend team, but keep in mind it's the Holidays season so it may take a while until someone reviews this.

Two things:
- If there isn't already an open issue about this, it doesn't hurt to open it first and then resolve it with this PR
- You can build static-viz bundle with `yarn build-static-viz`

**Comment by bjgbeelen** [comment]
image

**Review by camsaul — CHANGES_REQUESTED** [review]
This will break if the system locale is Turkish -- the `(str/lower-case "TIME")` is `"tıme"` in that case. See https://github.com/metabase/metabase/issues/27250 for more information

**Comment by bjgbeelen** [comment]
Thanks @camsaul , didn't know about this. Made the change

**Review by camsaul — APPROVED** [review]

**Comment by camsaul** [comment]
It looks like we have a problem with our CI config for third party PRs

This should be good to merge tho, we can push this up as a separate branch to run CI to confirm

**Comment by lbrdnk** [comment]
I've manually verified that CLA was signed. Apart from automated CLA check all workflows have passed also in the CI mirror PR. I believe we are safe to merge this one :).

**Comment by lbrdnk** [comment]
@metabase-bot backport release-x.48.x

**Comment by lbrdnk** [comment]
`meteabase-bot` At least we tried :), I'll do that manually.

**Comment by lbrdnk** [comment]
@bjgbeelen, thank you for your contribution :)

**Pull request merged**
