### PR TITLE
Fix failed to start front-end development

### LINKED ISSUE #18522: Failed to start front-end development
**Describe the bug**
Unable to access /setup in front-end development

**Logs**
log from browser's console
```
Uncaught TypeError: tag is undefined
    docsUrl settings.js:137
    jsx AddDatabaseHelpCard.jsx:18
```

**To Reproduce**
1. Remove `resources/version.properties` or newly clone the repo
2. Build and start development

Start the server
```sh
clj -X:deps prep
clj -M:dev
```
inside repl
```clojure
(require 'dev)
(dev/start!)
```

Start the front-end
```sh
yarn build-hot
```
3. Goto http://localhost:3000
4. The site will fail to display the setup page

**Expected behavior**
- Able to visit setup page 
- the docurls will default to `latest` if `version` not found

- Your browser and the version: Firefox 93.0
- Your operating system: OSX: 12.0 Beta
- Metabase version: Current master 4107683e93f02c1359e96541a300e2b976be2e6a 
- Metabase hosting environment: local
- Metabase internal database: H2

**Severity**
Block me from development

**Additional context**
No

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #18522 

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### CODE REVIEW

**Review by kidd — APPROVED** [review]

**Comment by qnkhuat** [comment]
Hi @alxnddr,
This PR has conflicts bc [your PR](https://github.com/metabase/metabase/pull/18528) has modified `frontend/src/metabase/lib/settings.js`.
I'm trying to resolve the conflict but the prettifier yields an error about the `?` operator.

Screen Shot 2021-11-01 at 11 34 26

AFAIK from[ typescript@3.7](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/#optional-chaining) we have `?` operator supported, so could you take a look into this?

**Comment by alxnddr** [comment]
@qnkhuat in order not to be blocked, please use `// prettier-ignore` comment to disable it for the line. I'll upgrade prettier, format files, and remove it. Thanks for pointing it out!

**Comment by qnkhuat** [comment]
@alxnddr Am I doing this right ? 

Screen Shot 2021-11-01 at 20 38 55

**Comment by alxnddr** [comment]
@qnkhuat oh, sorry, it fails even before on the parsing stage. Then `tag && tag.match(...);` would work

**Comment by qnkhuat** [comment]
Cool! @alxnddr 

Would you mind taking another look? @kidd

**Review by alxnddr — APPROVED** [review]
@qnkhuat looks good! Thanks for your contribution

**Pull request merged**
