### PR TITLE
Add models educational modal to Admin > Data Model

### PR DESCRIPTION
**Pull request by kulyk**
Adds an educational modal telling more about Models to Admin > Data Model page.
~⚠️ Still need to add a URL to the Learn article~ ([done](https://github.com/metabase/metabase/pull/19832/commits/736633d443757971af49042fa1880326444ad400))

### To Verify

1. Sign in as admin
2. Open `/admin/datamodel`
3. Click "Simplify your schema with Models" at the top right
4. You should see an educational modal and should be able to close it

~Note: "Learn how" button is supposed to be a link to a Learn article which is still missing~ ([done](https://github.com/metabase/metabase/pull/19832/commits/736633d443757971af49042fa1880326444ad400))

### Screenshot

CleanShot 2022-01-21 at 14 36 00@2x

### CODE REVIEW

**Review by alxnddr — APPROVED** [review]
Works as expected

**Comment by nemanjaglumac** [comment]
Nit: Couldn't we render some dummy table and prevent clicking on it instead of including 2 png images for the user to have to download?

**Comment by kulyk** [comment]
> Nit: Couldn't we render some dummy table and prevent clicking on it instead of including 2 png images for the user to have to download?
> 
> The shown structure (from those PNGs) seems easy to replicate in an actual HTML.

I like the idea, but I'm not sure if it's worth the effort, the image is 20 KB

**Review by mazameli — CHANGES_REQUESTED** [review]
I'm just going to update the image asset before we merge this.

**Review by mazameli — APPROVED** [review]

**Pull request merged**
