### PR TITLE
Pinmap with colored pins and clustring

### PR DESCRIPTION
**Pull request by shahinism**
In this branch we've updated `Pinmap` data visualization component, to reflect our needs, and since the result is promising enough we though it's a good idea to share it with you here. 
## Changes:
1. Using [leafletjs](http://leafletjs.com) for maps. It has a reach set of helper plugins, which makes it easier to handle data on the map.
2. Using [OSM](wiki.openstreetmap.org/wiki/Tiles) map tiles instead of google map. It is also [possible to use other map tiles](https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#what-map-tiles-can-i-use-with-leaflet-is-it-limited-to-openstreetmap), but for now we are using OSM. Google map has [some known performance problem](https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#i-want-to-use-google-maps-api-tiles-with-leaflet-can-i-do-that).
3. Removed 2000 threshold for showing pins with popup data. Instead we are using pin clustering layer.
4. Settings map center to middle point of pins on the map.
5. Using SVG pins instead of images to make us able to change pin colors. (thanks to [leaflet.vector-marker](https://github.com/hiasinho/Leaflet.vector-markers))
6. Define pin colors based on `category` special type. So if a dataset, provides category type together with lat, lon fields, each pin will get a color related to it's category value. Colors for category values are calculated by [color hash](https://www.npmjs.com/package/color-hash) package. Also for category types with conventional green/red colors (like yes/no) it will use green or red instead of using `color-hash`.
7. Clustering markers when there are a lot of markers in a map view. (thanks to [prunecluster](https://github.com/SINTEF-9012/PruneCluster/))
8. Display the number of pins from each category with category's color, on cluster icon.
### Normal data with clustering (no category):

selection_150
### data with clustering and categories:

selection_152
### data with clustering and conventional (yes/no) category colors:

selection_151
## Possible issues

Two of the libraries we used here ([leaflet.vector-market](https://github.com/hiasinho/Leaflet.vector-markers) and [prunecluster](https://github.com/SINTEF-9012/PruneCluster/)) are not providing npm packages or serving this packages over a reliable CDN. Since we couldn't find any document on this subject in repository or any use case of such library in Metabase's code base, we are using [rawgit](http://rawgit.com) temporarily.

### CODE REVIEW

**Comment by salsakran** [comment]
Nice!

@kdoh does this play nicely with our color palate and the work  you're doing to unify it?

**Comment by salsakran** [comment]
@shahinism, before we'd be able to merge this into the project, we would need you to sign our Contributor License Agreement - https://docs.google.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform

We'll review it and see if we can get it in the 0.19 release if things look good. We're code freezing tomorrow for 0.18, and I think this will probably need a bit of bake-in time.

**Comment by salsakran** [comment]
This looks like it sidesteps our server-side tile generation - https://github.com/metabase/metabase/blob/master/src/metabase/api/tiles.clj

We had originally done that to speed up tile rendering. @shahinism how many points have you been able to render using the approach in this PR?

Also, many of our dataset endpoints are limited from returning more than 2k rows, so we should make sure this isn't broken by that limit.

**Comment by shahinism** [comment]
@salsakran I've already signed contributor license agreement. (Shahin Azad)

About the number of points, we in [Foundersbuddy](https://foundersbuddy.com) need a lot more than 2k of points, so I increased the threshold to 20k for test and it works with no problem as normal. On the other hand, [prune cluster](https://github.com/SINTEF-9012/PruneCluster/) have done some tests up to 1 million points on a map, which in my opinion has some good results.

**Comment by salsakran** [comment]
my read of https://github.com/metabase/metabase/blob/master/src/metabase/api/tiles.clj#L122 is that we are effectively capping any given tile by `absolute-max-results` defined at https://github.com/metabase/metabase/blob/master/src/metabase/query_processor.clj#L24 . Hence the tiles should be accurate for anyone not plotting 100s of millions of rows or more. 

If we do this, then the max result cap will directly affect the accuracy of these pin maps. So either we should have the pin marker end up being something like "2000+" instead of "2000". 

I think for the general case of "bare rows" anything past 2k isn't going to be navigated by a human anyway, but in the case of pin maps it's not unreasonable to be trying to create a map of your entire use base. Lots of companies using us have way more than 2k users in a single region (eg, NYC or SF).

Btw, @shahinism I'm a huge fan of this approach (and leafletjs), and think removing a dependency on a commercial api is a huge win for the project. Just trying to think through corner cases and make if we ship this no one else's usage breaks. Bear with our OCD tendancies =)

**Comment by MrMauricioLeite** [comment]
WOW.... Really, I'm amazed!
Great work @shahinism!!! You are doing an amazing job with that plugin.

Can't wait for this to be merged!! maybe in 0.19.0 milestone? =)

**Comment by agilliland** [comment]
I'd say that overall this looks like a sound approach.  The couple things I would tweak are ...

1. I would prefer not to see single letter aliases for 3rd party library imports.  It will ultimately make the code harder to read.  We allow a couple special cases if a library is used a lot (like underscore), but in this case I don't think leaflet should be `import L from "leaflet";` and instead would prefer to see a more natural name used such as `leaflet`.

2. We'll definitely want to find an alternative to using the CDN to get the libs and css.  Maybe @tlrobinson has some ideas on how to get this to integrate with our normal webpack build process?

Regarding the 2k limit on rows, that is definitely more of an issue now, but it's a bit orthogonal to this specific PR really.  It's not terribly difficult to come up with some other situations where a `:rows` type query would justifiably need to allow more than 2k rows to be returned (e.g. a pre-aggregated timeseries), so I'm not sure I would hold up the PR on that basis.  It is something that needs to be dealt with though.  It may make sense to add in the capability of picking specific fields from a table and simply not enforce the 2k limit in that situation.  That way you could do something like `select lat, long from geo_table` and it wouldn't be restricted to 2k rows the way that `select * from geo_table` would.

**Comment by shahinism** [comment]
I'm agree with @agilliland about single letter aliases for library imports. I've already tried to use `leaflet` as library import name. But those `leaflet` plugins (which I mentioned on CDN issue), are using `L` to access it (it's like an unwritten standard in leaflet community and most of the plugins out there are using the same approach).

**Comment by MrMauricioLeite** [comment]
I would love to see this merged

**Comment by tlrobinson** [comment]
As far as moving off the CDN, it looks like all of those packages are on NPM now (not sure if they're the right versions)

https://www.npmjs.com/package/leaflet
https://www.npmjs.com/package/Leaflet.vector-markers
https://www.npmjs.com/package/prunecluster

**Comment by salsakran** [comment]
@shahinism Sorry for the delay.

We've discussed this a bunch, and I think this should be merged after #612 

We'll have the same issue with the 2k limit in charting arbitrary columns in a raw result set, and we'll set up a way for the client to pull down all values for charted rows. This will remove the correctness issue (i.e. we can't expect admins to directly manage the max rows limit based on their data size).

Thanks for you patience, and hard work.

**Comment by shahinism** [comment]
@salsakran No problem ;)
@tlrobinson Thanks for packages links. I'm already using `leaflet` package from npm. The reason I didn't used `prunecluster` from npm is that this package is in beta version and as far as I tested it is unstable, so I used the latest stable version.

**Comment by tlrobinson** [comment]
@shahinism Makes sense. If the git repo has the package.json you can also just specify the repo URL and hash/branch. Could you try that? Otherwise we can either fork the repos and add the package.json or just vendor the files in `frontend/src/metabase/vendor/*`

**Comment by tlrobinson** [comment]
Regarding the 2k row limitation:

One possibility is adding an endpoint similar to the server-side tile generation endpoint, except it would returns a compact list of coordinates (and maybe entity id so we could link to an object detail page). It still wouldn't be as scalable as the server-rendered tiles since I don't think we want to send `absolute-max-results` rows to the client (1048576 * 2 floats = 8MB). The next step would be computer the clustering on the server, but that seems like overkill.

We could still offer the server-rendered tiles mode as a chart setting, but I think limiting to 10,000-100,000 rows and showing a warning would be fine. Remember that limit is the number of points *within your current viewport* (we filter by lat/lon bounds in the tile endpoint), so we can just tell the user to zoom in.

@salsakran Note that showing "2000+" on a cluster isn't sufficient since the 2000 rows may be split across more than one cluster. It would have to be a top-level warning like we have for tables.

**Comment by tlrobinson** [comment]
@shahinism  I've started merging this with our latest changes in #3133. Thanks for the great work! Let me know if you'd like to continue helping, otherwise I'm happy to finish it up.

**Comment by shahinism** [comment]
Thank you @tlrobinson for taking care of this. I was busy last couple weeks, and couldn't test suggested solutions.

**Comment by kdoh** [comment]
Hey @shahinism. Want to give you a big thank you for your work on this, it got us excited about maps  and charting improvements in general. Since there hasn't been any activity on this for a while I'm going to close this for the moment. If you feel like working more on it, we're more than happy to re-open it.

**Comment by bmckay959** [comment]
All, forgive my ignorance, but has this been implemented into Metabase? This is a key feature for my needs(Showing different colored pins for different categories) but am unsure how to implement? I am not seeing the ability within my deployment (Version 0.32.10)

**Comment by flamber** [comment]
@bmckay959 No, but go and upvote issue #5973 by clicking the :+1:

**Comment by bmckay959** [comment]
Thanks @flamber Will do now!

**Comment by loganbluecrew** [comment]
Leaving a note here that my team would also be very interested in this feature and has upvoted https://github.com/metabase/metabase/issues/5973 as well

**Pull request closed without merging**
