### PR TITLE
Fix revision history display

### LINKED ISSUE #20414: Cannot open Model sidebar in some cases
Hey, I wanted to try new Models, and I got stuck.

I created Model all right, but now I cannot edit it - see video.

https://user-images.githubusercontent.com/6343648/153385312-b70a1346-072e-493a-9265-fa97a1ff4235.mp4

Logs:
```
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:07+01:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 6.5 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 10/50 (12 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:07+01:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 14.6 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 9/50 (12 idle, 0 queued) (149 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:08+01:00 DEBUG metabase.server.middleware.log GET /api/database 200 7.7 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 10/50 (12 idle, 0 queued) (149 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:08+01:00 DEBUG metabase.server.middleware.log GET /api/card/1351 200 18.7 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 10/50 (12 idle, 0 queued) (149 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:08+01:00 DEBUG metabase.server.middleware.log GET /api/alert/question/1351 200 1.8 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (12 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:08+01:00 DEBUG metabase.server.middleware.log GET /api/table/card__1351/query_metadata 200 18.3 ms (7 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (12 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:09+01:00 INFO metabase.api.dataset Source query for this query is Card 1,351
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:09+01:00 INFO metabase.query-processor.middleware.fetch-source-query Trimming trailing comment from card with id 1,351
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:09+01:00 INFO metabase.query-processor.middleware.fetch-source-query Fetched source query from Card 1,351: 
 {:native
 "SELECT \n        U.id AS id,\n        U.name AS name,\n        U.surname AS surname,\n        U.year_of_birth AS year_of_birth,\n        U.street AS street,\n        U.street_no AS street_no,\n        U.zip_code AS zip_code,\n        U.city AS city,\n        U.last_login_date AS last_login_date,\n                U.created_at AS created_at,\n        U.updated_at AS updated_at,\n                U.e_mail AS e_mail,\n                                        U.phone_number AS phone_number,\n        U.phone_number2 AS phone_number2,\n        U.phone_number3 AS phone_number3,\n                        U.legal_entity_number AS legal_entity_number,\n        U.tax_entity_number AS tax_entity_number,\n        U.sap_id AS sap_id,\n        U.company_name AS company_name,\n        U.provisional_name AS provisional_name,\n                U.flags AS flags,\n                                U.web AS web,\n        U.occupation AS occupation,\n                                                U.admin_note AS admin_note,\n        U.average_service_rating AS average_service_rating,\n        U.average_quality_rating AS average_quality_rating,\n        U.average_value_rating AS average_value_rating,\n        U.description AS description,\n                                                                U.logo_id AS logo_id,\n        U.search_hide AS search_hide,\n                                        U.affiliate_id AS affiliate_id,\n                        U.skip_reminders_until AS skip_reminders_until,\n        U.vip_note AS vip_note,\n        U.legal_entity_state_id AS legal_entity_state_id,\n        U.eu_foreigner AS eu_foreigner,\n        U.quality_stamp AS quality_stamp,\n        U.review_count AS review_count,\n        U.admin_note_changed_at AS admin_note_changed_at,\n        U.suspicious AS suspicious,\n        U.fraud AS fraud,\n        U.knows_admin_note AS knows_admin_note,\n        U.knows_overdue AS knows_overdue,\n        U.knows_suspicious AS knows_suspicious,\n        U.knows_fraud AS knows_fraud,\n        U.impression_rating AS impression_rating,\n        U.impression_count AS impression_count,\n        U.current_balance AS current_balance,\n                        U.new_terms_agreed AS new_terms_agreed,\n                U.vat_payer AS vat_payer,\n                        U.source_id AS source_id,\n                U.salutation AS salutation,\n        U.scored_bids AS scored_bids,\n                U.admin_owner_id AS admin_owner_id,\n        U.provider_type_id AS provider_type_id,\n        U.company_created_at AS company_created_at,\n        U.registered_activities AS registered_activities,\n        U.birthday AS birthday,\n        U.motto AS motto,\n        U.anonymized_name AS anonymized_name,\n        U.provider_photo_id AS provider_photo_id,\n        U.background_photo_id AS background_photo_id,\n        U.contact_note AS contact_note,\n        U.opt_out_mail_group_flags AS opt_out_mail_group_flags,\n        U.dont_mail AS dont_mail,\n        U.credit_current_balance AS credit_current_balance,\n        U.credit_expiration AS credit_expiration,\n        U.average_user_rating AS average_user_rating,\n        U.provider_level AS provider_level,\n        U.provider_level_by_admin AS provider_level_by_admin,\n        U.kozel_seal_id AS kozel_seal_id,\n        U.cost_rate AS cost_rate,\n        U.last_opened_outgoing_mail_id AS last_opened_outgoing_mail_id,\n        U.last_opened_outgoing_mail_at AS last_opened_outgoing_mail_at,\n        (YEAR(NOW()) - IF(((U.year_of_birth < 1900)\n                OR (U.year_of_birth > YEAR(NOW()))),\n            NULL,\n            U.year_of_birth)) AS age_in_years,\n        TIMESTAMPDIFF(YEAR,\n            U.created_at,\n            CURDATE()) AS registered_in_years,\n        (CASE\n            WHEN (U.salutation LIKE 'pane%') THEN 'pane'\n            WHEN (U.salutation LIKE 'paní%') THEN 'paní'\n            WHEN (U.salutation IS NULL) THEN NULL\n            ELSE 'other'\n        END) AS gender_by_salutation,\n        (CASE\n            WHEN (U.legal_entity_state_id IN (0 , 4)) THEN 1\n            ELSE 0\n        END) AS is_verified,\n        (CASE\n            WHEN ((BOP.flags & 16) = 16) THEN 1\n            ELSE 0\n        END) AS is_frozen,\n        BOP.id AS bop_id,\n                                BL.name AS rfm_label_name,\n        IF(EXISTS( SELECT \n                    1\n                FROM\n                    provider_credits\n                WHERE\n                    ((provider_credits.user_id = U.id)\n                        AND (provider_credits.source_type = 'UserAchievement'))),\n            1,\n            0) AS has_achievements,\n        (CASE\n            WHEN ((U.flags & 256) = 256) THEN 1\n            ELSE 0\n        END) AS is_created_from_bop,\n        A.full_name AS admin_owner_full_name\n    FROM\n        users AS U\n        LEFT JOIN book_of_providers BOP ON\n            BOP.user_id = U.id\n                        LEFT JOIN bop_label_book_of_providers BOPBL ON\n            BOPBL.book_of_provider_id = BOP.id\n            AND BOPBL.bop_label_id IN (14 , 15, 16, 17, 18, 19, 20)\n        LEFT JOIN bop_labels BL ON\n            BL.id = BOPBL.bop_label_id\n        LEFT JOIN admin_users A ON\n            A.id = U.admin_owner_id\n    WHERE\n        U.type = 'User'\n        AND U.provider_switch = 1\n        AND U.flags & (274877906944 | 549755813888) = 0\n        AND U.flags & 8192 = 0\n        AND U.flags & 1024 = 0"}

[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:09+01:00 INFO metabase.query-processor.middleware.fetch-source-query Trimming trailing comment from card with id 1,351
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:09+01:00 INFO metabase.query-processor.middleware.fetch-source-query Fetched source query from Card 1,351: 
 {:native
 "SELECT \n        U.id AS id,\n        U.name AS name,\n        U.surname AS surname,\n        U.year_of_birth AS year_of_birth,\n        U.street AS street,\n        U.street_no AS street_no,\n        U.zip_code AS zip_code,\n        U.city AS city,\n        U.last_login_date AS last_login_date,\n                U.created_at AS created_at,\n        U.updated_at AS updated_at,\n                U.e_mail AS e_mail,\n                                        U.phone_number AS phone_number,\n        U.phone_number2 AS phone_number2,\n        U.phone_number3 AS phone_number3,\n                        U.legal_entity_number AS legal_entity_number,\n        U.tax_entity_number AS tax_entity_number,\n        U.sap_id AS sap_id,\n        U.company_name AS company_name,\n        U.provisional_name AS provisional_name,\n                U.flags AS flags,\n                                U.web AS web,\n        U.occupation AS occupation,\n                                                U.admin_note AS admin_note,\n        U.average_service_rating AS average_service_rating,\n        U.average_quality_rating AS average_quality_rating,\n        U.average_value_rating AS average_value_rating,\n        U.description AS description,\n                                                                U.logo_id AS logo_id,\n        U.search_hide AS search_hide,\n                                        U.affiliate_id AS affiliate_id,\n                        U.skip_reminders_until AS skip_reminders_until,\n        U.vip_note AS vip_note,\n        U.legal_entity_state_id AS legal_entity_state_id,\n        U.eu_foreigner AS eu_foreigner,\n        U.quality_stamp AS quality_stamp,\n        U.review_count AS review_count,\n        U.admin_note_changed_at AS admin_note_changed_at,\n        U.suspicious AS suspicious,\n        U.fraud AS fraud,\n        U.knows_admin_note AS knows_admin_note,\n        U.knows_overdue AS knows_overdue,\n        U.knows_suspicious AS knows_suspicious,\n        U.knows_fraud AS knows_fraud,\n        U.impression_rating AS impression_rating,\n        U.impression_count AS impression_count,\n        U.current_balance AS current_balance,\n                        U.new_terms_agreed AS new_terms_agreed,\n                U.vat_payer AS vat_payer,\n                        U.source_id AS source_id,\n                U.salutation AS salutation,\n        U.scored_bids AS scored_bids,\n                U.admin_owner_id AS admin_owner_id,\n        U.provider_type_id AS provider_type_id,\n        U.company_created_at AS company_created_at,\n        U.registered_activities AS registered_activities,\n        U.birthday AS birthday,\n        U.motto AS motto,\n        U.anonymized_name AS anonymized_name,\n        U.provider_photo_id AS provider_photo_id,\n        U.background_photo_id AS background_photo_id,\n        U.contact_note AS contact_note,\n        U.opt_out_mail_group_flags AS opt_out_mail_group_flags,\n        U.dont_mail AS dont_mail,\n        U.credit_current_balance AS credit_current_balance,\n        U.credit_expiration AS credit_expiration,\n        U.average_user_rating AS average_user_rating,\n        U.provider_level AS provider_level,\n        U.provider_level_by_admin AS provider_level_by_admin,\n        U.kozel_seal_id AS kozel_seal_id,\n        U.cost_rate AS cost_rate,\n        U.last_opened_outgoing_mail_id AS last_opened_outgoing_mail_id,\n        U.last_opened_outgoing_mail_at AS last_opened_outgoing_mail_at,\n        (YEAR(NOW()) - IF(((U.year_of_birth < 1900)\n                OR (U.year_of_birth > YEAR(NOW()))),\n            NULL,\n            U.year_of_birth)) AS age_in_years,\n        TIMESTAMPDIFF(YEAR,\n            U.created_at,\n            CURDATE()) AS registered_in_years,\n        (CASE\n            WHEN (U.salutation LIKE 'pane%') THEN 'pane'\n            WHEN (U.salutation LIKE 'paní%') THEN 'paní'\n            WHEN (U.salutation IS NULL) THEN NULL\n            ELSE 'other'\n        END) AS gender_by_salutation,\n        (CASE\n            WHEN (U.legal_entity_state_id IN (0 , 4)) THEN 1\n            ELSE 0\n        END) AS is_verified,\n        (CASE\n            WHEN ((BOP.flags & 16) = 16) THEN 1\n            ELSE 0\n        END) AS is_frozen,\n        BOP.id AS bop_id,\n                                BL.name AS rfm_label_name,\n        IF(EXISTS( SELECT \n                    1\n                FROM\n                    provider_credits\n                WHERE\n                    ((provider_credits.user_id = U.id)\n                        AND (provider_credits.source_type = 'UserAchievement'))),\n            1,\n            0) AS has_achievements,\n        (CASE\n            WHEN ((U.flags & 256) = 256) THEN 1\n            ELSE 0\n        END) AS is_created_from_bop,\n        A.full_name AS admin_owner_full_name\n    FROM\n        users AS U\n        LEFT JOIN book_of_providers BOP ON\n            BOP.user_id = U.id\n                        LEFT JOIN bop_label_book_of_providers BOPBL ON\n            BOPBL.book_of_provider_id = BOP.id\n            AND BOPBL.bop_label_id IN (14 , 15, 16, 17, 18, 19, 20)\n        LEFT JOIN bop_labels BL ON\n            BL.id = BOPBL.bop_label_id\n        LEFT JOIN admin_users A ON\n            A.id = U.admin_owner_id\n    WHERE\n        U.type = 'User'\n        AND U.provider_switch = 1\n        AND U.flags & (274877906944 | 549755813888) = 0\n        AND U.flags & 8192 = 0\n        AND U.flags & 1024 = 0"}

[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:11+01:00 DEBUG metabase.server.middleware.log GET /api/setting 200 16.1 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 9/50 (12 idle, 0 queued) (152 total active threads) Queries in flight: 1 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:11+01:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 13.5 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 9/50 (12 idle, 0 queued) (152 total active threads) Queries in flight: 1 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:11+01:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 18.1 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (12 idle, 0 queued) (152 total active threads) Queries in flight: 1 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:13+01:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 6.9 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 1 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:13+01:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 3.6 s (12 DB calls) App DB connections: 2/15 Jetty threads: 8/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued); mysql DB 2 connections: 0/1 (0 threads blocked)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:15+01:00 DEBUG metabase.server.middleware.log GET /api/task/info 200 11.2 ms (0 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:15+01:00 DEBUG metabase.server.middleware.log GET /api/task 200 161.8 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:52+01:00 DEBUG metabase.server.middleware.log GET /api/user 200 8.7 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 9/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:52+01:00 DEBUG metabase.server.middleware.log GET /api/revision 200 616.1 ms (16 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:53+01:00 DEBUG metabase.server.middleware.log GET /api/card/1351 200 10.8 ms (10 DB calls) App DB connections: 0/15 Jetty threads: 9/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:56+01:00 DEBUG metabase.server.middleware.log GET /api/alert/question/1351 200 1.2 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 9/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued)
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:56+01:00 INFO metabase.api.dataset Source query for this query is Card 1,351
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:56+01:00 INFO metabase.query-processor.middleware.fetch-source-query Trimming trailing comment from card with id 1,351
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:56+01:00 INFO metabase.query-processor.middleware.fetch-source-query Fetched source query from Card 1,351: 
 {:native
 "SELECT \n        U.id AS id,\n        U.name AS name,\n        U.surname AS surname,\n        U.year_of_birth AS year_of_birth,\n        U.street AS street,\n        U.street_no AS street_no,\n        U.zip_code AS zip_code,\n        U.city AS city,\n        U.last_login_date AS last_login_date,\n                U.created_at AS created_at,\n        U.updated_at AS updated_at,\n                U.e_mail AS e_mail,\n                                        U.phone_number AS phone_number,\n        U.phone_number2 AS phone_number2,\n        U.phone_number3 AS phone_number3,\n                        U.legal_entity_number AS legal_entity_number,\n        U.tax_entity_number AS tax_entity_number,\n        U.sap_id AS sap_id,\n        U.company_name AS company_name,\n        U.provisional_name AS provisional_name,\n                U.flags AS flags,\n                                U.web AS web,\n        U.occupation AS occupation,\n                                                U.admin_note AS admin_note,\n        U.average_service_rating AS average_service_rating,\n        U.average_quality_rating AS average_quality_rating,\n        U.average_value_rating AS average_value_rating,\n        U.description AS description,\n                                                                U.logo_id AS logo_id,\n        U.search_hide AS search_hide,\n                                        U.affiliate_id AS affiliate_id,\n                        U.skip_reminders_until AS skip_reminders_until,\n        U.vip_note AS vip_note,\n        U.legal_entity_state_id AS legal_entity_state_id,\n        U.eu_foreigner AS eu_foreigner,\n        U.quality_stamp AS quality_stamp,\n        U.review_count AS review_count,\n        U.admin_note_changed_at AS admin_note_changed_at,\n        U.suspicious AS suspicious,\n        U.fraud AS fraud,\n        U.knows_admin_note AS knows_admin_note,\n        U.knows_overdue AS knows_overdue,\n        U.knows_suspicious AS knows_suspicious,\n        U.knows_fraud AS knows_fraud,\n        U.impression_rating AS impression_rating,\n        U.impression_count AS impression_count,\n        U.current_balance AS current_balance,\n                        U.new_terms_agreed AS new_terms_agreed,\n                U.vat_payer AS vat_payer,\n                        U.source_id AS source_id,\n                U.salutation AS salutation,\n        U.scored_bids AS scored_bids,\n                U.admin_owner_id AS admin_owner_id,\n        U.provider_type_id AS provider_type_id,\n        U.company_created_at AS company_created_at,\n        U.registered_activities AS registered_activities,\n        U.birthday AS birthday,\n        U.motto AS motto,\n        U.anonymized_name AS anonymized_name,\n        U.provider_photo_id AS provider_photo_id,\n        U.background_photo_id AS background_photo_id,\n        U.contact_note AS contact_note,\n        U.opt_out_mail_group_flags AS opt_out_mail_group_flags,\n        U.dont_mail AS dont_mail,\n        U.credit_current_balance AS credit_current_balance,\n        U.credit_expiration AS credit_expiration,\n        U.average_user_rating AS average_user_rating,\n        U.provider_level AS provider_level,\n        U.provider_level_by_admin AS provider_level_by_admin,\n        U.kozel_seal_id AS kozel_seal_id,\n        U.cost_rate AS cost_rate,\n        U.last_opened_outgoing_mail_id AS last_opened_outgoing_mail_id,\n        U.last_opened_outgoing_mail_at AS last_opened_outgoing_mail_at,\n        (YEAR(NOW()) - IF(((U.year_of_birth < 1900)\n                OR (U.year_of_birth > YEAR(NOW()))),\n            NULL,\n            U.year_of_birth)) AS age_in_years,\n        TIMESTAMPDIFF(YEAR,\n            U.created_at,\n            CURDATE()) AS registered_in_years,\n        (CASE\n            WHEN (U.salutation LIKE 'pane%') THEN 'pane'\n            WHEN (U.salutation LIKE 'paní%') THEN 'paní'\n            WHEN (U.salutation IS NULL) THEN NULL\n            ELSE 'other'\n        END) AS gender_by_salutation,\n        (CASE\n            WHEN (U.legal_entity_state_id IN (0 , 4)) THEN 1\n            ELSE 0\n        END) AS is_verified,\n        (CASE\n            WHEN ((BOP.flags & 16) = 16) THEN 1\n            ELSE 0\n        END) AS is_frozen,\n        BOP.id AS bop_id,\n                                BL.name AS rfm_label_name,\n        IF(EXISTS( SELECT \n                    1\n                FROM\n                    provider_credits\n                WHERE\n                    ((provider_credits.user_id = U.id)\n                        AND (provider_credits.source_type = 'UserAchievement'))),\n            1,\n            0) AS has_achievements,\n        (CASE\n            WHEN ((U.flags & 256) = 256) THEN 1\n            ELSE 0\n        END) AS is_created_from_bop,\n        A.full_name AS admin_owner_full_name\n    FROM\n        users AS U\n        LEFT JOIN book_of_providers BOP ON\n            BOP.user_id = U.id\n                        LEFT JOIN bop_label_book_of_providers BOPBL ON\n            BOPBL.book_of_provider_id = BOP.id\n            AND BOPBL.bop_label_id IN (14 , 15, 16, 17, 18, 19, 20)\n        LEFT JOIN bop_labels BL ON\n            BL.id = BOPBL.bop_label_id\n        LEFT JOIN admin_users A ON\n            A.id = U.admin_owner_id\n    WHERE\n        U.type = 'User'\n        AND U.provider_switch = 1\n        AND U.flags & (274877906944 | 549755813888) = 0\n        AND U.flags & 8192 = 0\n        AND U.flags & 1024 = 0"}

[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:56+01:00 INFO metabase.query-processor.middleware.fetch-source-query Trimming trailing comment from card with id 1,351
[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:56+01:00 INFO metabase.query-processor.middleware.fetch-source-query Fetched source query from Card 1,351: 
 {:native
 "SELECT \n        U.id AS id,\n        U.name AS name,\n        U.surname AS surname,\n        U.year_of_birth AS year_of_birth,\n        U.street AS street,\n        U.street_no AS street_no,\n        U.zip_code AS zip_code,\n        U.city AS city,\n        U.last_login_date AS last_login_date,\n                U.created_at AS created_at,\n        U.updated_at AS updated_at,\n                U.e_mail AS e_mail,\n                                        U.phone_number AS phone_number,\n        U.phone_number2 AS phone_number2,\n        U.phone_number3 AS phone_number3,\n                        U.legal_entity_number AS legal_entity_number,\n        U.tax_entity_number AS tax_entity_number,\n        U.sap_id AS sap_id,\n        U.company_name AS company_name,\n        U.provisional_name AS provisional_name,\n                U.flags AS flags,\n                                U.web AS web,\n        U.occupation AS occupation,\n                                                U.admin_note AS admin_note,\n        U.average_service_rating AS average_service_rating,\n        U.average_quality_rating AS average_quality_rating,\n        U.average_value_rating AS average_value_rating,\n        U.description AS description,\n                                                                U.logo_id AS logo_id,\n        U.search_hide AS search_hide,\n                                        U.affiliate_id AS affiliate_id,\n                        U.skip_reminders_until AS skip_reminders_until,\n        U.vip_note AS vip_note,\n        U.legal_entity_state_id AS legal_entity_state_id,\n        U.eu_foreigner AS eu_foreigner,\n        U.quality_stamp AS quality_stamp,\n        U.review_count AS review_count,\n        U.admin_note_changed_at AS admin_note_changed_at,\n        U.suspicious AS suspicious,\n        U.fraud AS fraud,\n        U.knows_admin_note AS knows_admin_note,\n        U.knows_overdue AS knows_overdue,\n        U.knows_suspicious AS knows_suspicious,\n        U.knows_fraud AS knows_fraud,\n        U.impression_rating AS impression_rating,\n        U.impression_count AS impression_count,\n        U.current_balance AS current_balance,\n                        U.new_terms_agreed AS new_terms_agreed,\n                U.vat_payer AS vat_payer,\n                        U.source_id AS source_id,\n                U.salutation AS salutation,\n        U.scored_bids AS scored_bids,\n                U.admin_owner_id AS admin_owner_id,\n        U.provider_type_id AS provider_type_id,\n        U.company_created_at AS company_created_at,\n        U.registered_activities AS registered_activities,\n        U.birthday AS birthday,\n        U.motto AS motto,\n        U.anonymized_name AS anonymized_name,\n        U.provider_photo_id AS provider_photo_id,\n        U.background_photo_id AS background_photo_id,\n        U.contact_note AS contact_note,\n        U.opt_out_mail_group_flags AS opt_out_mail_group_flags,\n        U.dont_mail AS dont_mail,\n        U.credit_current_balance AS credit_current_balance,\n        U.credit_expiration AS credit_expiration,\n        U.average_user_rating AS average_user_rating,\n        U.provider_level AS provider_level,\n        U.provider_level_by_admin AS provider_level_by_admin,\n        U.kozel_seal_id AS kozel_seal_id,\n        U.cost_rate AS cost_rate,\n        U.last_opened_outgoing_mail_id AS last_opened_outgoing_mail_id,\n        U.last_opened_outgoing_mail_at AS last_opened_outgoing_mail_at,\n        (YEAR(NOW()) - IF(((U.year_of_birth < 1900)\n                OR (U.year_of_birth > YEAR(NOW()))),\n            NULL,\n            U.year_of_birth)) AS age_in_years,\n        TIMESTAMPDIFF(YEAR,\n            U.created_at,\n            CURDATE()) AS registered_in_years,\n        (CASE\n            WHEN (U.salutation LIKE 'pane%') THEN 'pane'\n            WHEN (U.salutation LIKE 'paní%') THEN 'paní'\n            WHEN (U.salutation IS NULL) THEN NULL\n            ELSE 'other'\n        END) AS gender_by_salutation,\n        (CASE\n            WHEN (U.legal_entity_state_id IN (0 , 4)) THEN 1\n            ELSE 0\n        END) AS is_verified,\n        (CASE\n            WHEN ((BOP.flags & 16) = 16) THEN 1\n            ELSE 0\n        END) AS is_frozen,\n        BOP.id AS bop_id,\n                                BL.name AS rfm_label_name,\n        IF(EXISTS( SELECT \n                    1\n                FROM\n                    provider_credits\n                WHERE\n                    ((provider_credits.user_id = U.id)\n                        AND (provider_credits.source_type = 'UserAchievement'))),\n            1,\n            0) AS has_achievements,\n        (CASE\n            WHEN ((U.flags & 256) = 256) THEN 1\n            ELSE 0\n        END) AS is_created_from_bop,\n        A.full_name AS admin_owner_full_name\n    FROM\n        users AS U\n        LEFT JOIN book_of_providers BOP ON\n            BOP.user_id = U.id\n                        LEFT JOIN bop_label_book_of_providers BOPBL ON\n            BOPBL.book_of_provider_id = BOP.id\n            AND BOPBL.bop_label_id IN (14 , 15, 16, 17, 18, 19, 20)\n        LEFT JOIN bop_labels BL ON\n            BL.id = BOPBL.bop_label_id\n        LEFT JOIN admin_users A ON\n            A.id = U.admin_owner_id\n    WHERE\n        U.type = 'User'\n        AND U.provider_switch = 1\n        AND U.flags & (274877906944 | 549755813888) = 0\n        AND U.flags & 8192 = 0\n        AND U.flags & 1024 = 0"}

[11cc21bf-569d-45ce-9e8f-483fc62411cc] 2022-02-10T11:11:59+01:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 3.5 s (12 DB calls) App DB connections: 1/15 Jetty threads: 7/50 (11 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued); mysql DB 2 connections: 0/1 (0 threads blocked)
```
Screenshot from 2022-02-10 11-12-36

Diagnostics:

{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.4.0-91-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.25"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-08",
      "tag": "v0.42.0",
      "branch": "release-x.42.x",
      "hash": "de1264e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

.

### PR DESCRIPTION
**Pull request by kulyk**
Fixes a weird bug with revision history rendering and one of its possible occurrences: #20414

If you want to understand the issue in full detail, I'd recommend going through #17858 PR description as it explains how revisions are rendered.

There are two ways we render the message:

1. In case only one property was changed, we just display something like "$USERNAME renamed this to ..."
2. In case there were > 1 properties changed in a single revision, the message is broken down into `title` ("$USERNAM edited this") and joined `description` ("Renamed this to ... and added description")

There is a special case when an item is moved to another collection. In this case, we display a link to the new collection using `jt'moved this to ${<CollectionLink />}'`. `jt` returns an array like `[ "moved this to", "", React.Element ]` and the component rendering a description capitalizes the "moved this to" part.

This was working fine because the current UI only lets you move items with a separate flow, so only the `collection_id` is changed on the UI (for some reason `collection_id` change is not tracked for dashboards 🤔). We started tracking `result_metadata` field changes for models as their metadata can be changed now. And looks like there is an edge-case when the table fingerprint gets updated at the same time you move a model to another collection 😵 So the description component receives nested `changes` array prop and crashes

Fixed by adding support to nested `changes` list, though it'd probably make sense to make revision rendering less magical. Also added a generic safety net: now if rendering a change description would fail, it'd fall back to the original ugly revision description.

There is no clear way how to reproduce this issue, you just have to catch it somehow, hopefully @flamber confirmed it works

### CODE REVIEW

**Review by flamber — APPROVED** [review]
:heart: 
Should we add a test, which makes sure that we cannot regress again? I still haven't figured out how to manually reproduce.

**Comment by kulyk** [comment]
Oh, so it did help @flamber? I wasn't completely sure. If that's it, I'll add some unit tests at least and a more common safety net for revision renderer. It's dump when it's impossible to open the sidebar at all when the something's off rendering a single revision message

**Comment by flamber** [comment]
Yup, I can open all my previous Datasets, so I'm fairly confident it will fix the reporter's issue as well, but don't really want to give them this build, since it's based on master.

**Comment by kulyk** [comment]
@flamber this should do it #20421

**Review by daltojohnso — APPROVED** [review]

**Pull request merged**
