### PR TITLE
upgrade ace from 1.2.9 to 1.4.7

### PR DESCRIPTION
**Pull request by paulrosenzweig**
@mazameli, this seems to fix the freezing bug you noticed. Though I still don't know what the root cause was since it seems that issue just started with the recent NativeQueryEditor changes.

The only issue I noticed with the upgrade was a spacing issue with the line numbers. I tweaked that so we can see the whole number, but let me know if it's too tight.

### CODE REVIEW

**Comment by mazameli** [comment]
> but let me know if it's too tight.

Yeah if you're talking about the column of line numbers, this does look too tight:
image

It should be 20px wide like this:
image

**Comment by mazameli** [comment]
Other than the line number column spacing, this PR seems to fix that weird typing bug! I tried writing a bunch of different queries with a few different DBs on this branch and could never repro the bug. Nice!

**Comment by paulrosenzweig** [comment]
I bumped the min line number width to 20px:

Kapture 2019-12-13 at 14 58 51


If you write a 100+ line query, the gutter width will increase very slightly:

Kapture 2019-12-13 at 14 57 34

**Comment by mazameli** [comment]
Line numbers should start at 1, not 0 (what are we, computer scientists?? 😉 ), but other than that, looks solid. 👍 

image

**Comment by paulrosenzweig** [comment]
ha! good catch

**Comment by mazameli** [comment]
Hmm, I'm now seeing a related but different bug in this branch, different from on master:

1. start a new sql question
2. write a query like `select * from orders` and run it either via the button or keyboard shortcut
3. you can't type type anything until you either first: 1) hit delete, 2) hit tab, 3) use the arrow keys to move the cursor around, or 4) click on the editor.

To add to the weirdness, I _think_ this only happens when the visualization is Table? Can you reproduce this @paulrosenzweig?

**Comment by paulrosenzweig** [comment]
I added a very ugly hack to avoid that error. After running a query we blur/refocus in the editor.

@mazameli, you were right that the issue only occurs for tables. The library we use for drag-n-drop columns disrupts Ace in some weird way. 

This blur/focus means that running a query will always focus in the editor. I think that's ok since the only other place you could be typing on that page is the search bar.

Other options I like even less:
* Blur/focus on every keystroke.
Surprisingly, this doesn't appear to affect typing at all, but it feels dangerous to do.
* Hook in to the table load rather than use a delay to guess when it's loaded.
This avoid the race between blur/focus and table load, but it spreads the hack into more files and creates awkward coupling.

**Review by mazameli — APPROVED** [review]
Seems like things work great now!

**Comment by mazameli** [comment]
I also pushed a small cosmetic tweak to the line number gutter that @kdoh and I had briefly chatted about yesterday that removes the line number border-right and aligns the sql with the db select and question title text:

image

**Review by kdoh — APPROVED** [review]

**Pull request merged**
