### PR TITLE
Switch to tools.deps

### PR DESCRIPTION
**Pull request by camsaul**
Requires Clojure CLI 1.10.3.905 or newer (use `clojure --help | grep Version` to check this and install a newer one by following steps in https://clojure.org/guides/getting_started if you need to)

Important! You have to "prep" our Java dependency (i.e., compile it) with

```sh
clojure -X:deps prep
```

before you do anything else. You just need to do this once. You should also do 

```sh
cd modules/drivers && clojure -X:deps prep
```

if you want to use the `:drivers` alias to include driver source paths in the classpath for local dev (Alex Miller said this should be fixed in the next week or so, see below)

- [x] Get the REPL & `:dev` alias working. REPL works although you will probably want to add the `:dev` alias e.g. `:dev:cider/nrepl` or `:dev:ee:ee:dev` for EE unless you don't want access to the test namespaces. Starts in ~5 seconds instead of ~1 minute. You can include drivers with `:drivers` `:drivers-test` respectively
- [x] Equivalent of `~/profiles.clj` `:env`. You can set `:jvm-opts` instead of `:env` and environ will still pick up on them. 
- [x] Rewrite build-drivers code. New build-drivers code is an order of magnitude faster; builds everything in ~35 seconds compared to the previous ~7 minutes (12x faster)
- [x] New test runner with pretty output & JUnit output. Tests run with `clojure -X:dev:test` or `clojure -X:ee:dev:ee-dev:test` (lol) (go upvote https://ask.clojure.org/index.php/10564/specify-an-alias-that-is-a-set-of-other-aliases?show=10564). Switches test runner to `eftest` (with some custom logic) -- tests or test namespaces explicitly marked `^:parallel` will now run in parallel. I marked a lot of our util and QP tests with this metadata. This cuts full test suite run time roughly in half for me. If you try to use `with-redefs` or stuff like inside a parallel test it will fail
- [x] Rework the build-uberjar stuff using tools.build -- should be pretty simple
- [x] Migrate linters
   - [x] ~~Merge #16726 so we can remove the docstring-checker linter (I'm not going to waste time porting this since clj-kondo can do it now) and use clj-kondo instead.~~ Alternative option: Just change `:missing-docstring` from `:warn` to `:warning` in the Kondo config file and call it a day, and worry about #16726 later
   - [x] Alias to run Eastwood -- `clojure -X:dev:ee:ee-dev:drivers:drivers-dev:eastwood`
      - [x] ~~We are now running Eastwood on test namespaces, and need to fix a bunch of warnings -- I fixed most of these but there are still a few left. Consider whether this should be done as part of a separate PR since it's not specific to deps.edn. Alternative option: just tell Eastwood not to run on test namespaces like we currently do and worry about fixing the rest of the lint errors/enabling Eastwood on test namespaces in a follow-on PR~~ Split this out into separate PR #17193
   - [x] Alias to run namespace-checker -- run with `clojure -X:dev:ee:ee-dev:drivers:drivers-dev:namespace-checker`
   - [x] Alias to run Bikeshed (or just remove Bikeshed entirely?)
   - [x] Update reflection warning script
- [x] Add Cloverage alias -- https://github.com/practicalli/clojure-deps-edn has an example for running Cloverage
- [x] Copy comments for dependencies
- [x] Copy convenience aliases for stuff like the H2 shell
- [x] Add alias that does the equivalent of `lein run`
- [x] Migrate CI config
   - [x] Create CI images that use newer version of Clojure CLI (@paoliniluis is working on this)
   - [x] switch CircleCI commands from `lein` to `clojure` equivalents
   - [x] switch GitHub actions from `lein` to `clojure` equivalents
- [x] Update DockerHub builder image (`./Dockerfile`) -- remove dep on Leiningen, update CLI version
- [x] Check whether we need to do anything special to get driver plugins working for local dev server/REPL (We don't have the equivalent of the init-plugins Lein `:injections` stuff anymore). Not sure if anything needs to be done
- [ ] There's currently no way to do `clojure -X:deps prep` for an alias (e.g. `:drivers`) -- I asked Alex Miller about this on 7/14/21 and he said there should be a fix next week. Workaround for now is to do `cd modules/drivers && clojure -X:deps prep`
- [x] Update developer documentation
   - [x] ~~Update 3rd-party driver building documentation, maybe the example sudoku driver as well.~~ Will do this as a follow-on
- [x] Migrate license generation code
- [x] ~~Add a `build.clj` `clean` command that removes generated Java and driver AOT classes (?) (Or should this be two separate commands for the core project, and for drivers?)~~ Will do this as a follow-on

### CODE REVIEW

**Comment by paoliniluis** [comment]
@camsaul Images ready at:
metabase/ci:circleci-java-8-clj-1.10.3.912-07-16-2021-node-browsers
metabase/ci:circleci-java-11-clj-1.10.3.912-07-16-2021-node-browsers
metabase/ci:circleci-java-16-clj-1.10.3.912-07-16-2021-node-browsers

3 images are with Node LTS and browsers so they can be reused across the pipeline (CircleCI base + 1 layer of Clojure CLI latest)

**Comment by camsaul** [comment]
This is now ready for review, the only thing left before merge is fixing a handful of failing Cypress tests -- still trying to work out why they're failing but they might be related to some test fixes related to our new test runner. `eftest`, our new test runner, runs tests in a different order than our old test runner; I had to fix a handful of tests so that they would clean up after themselves to avoid breaking other tests. In a few places, I tweaked the actual source code to facilitate test fixes (e.g. by adding support for `:limit` and `:offset` params to an endpoint so I could fetch more than the previously-hardcoded limit of items in a single request).

The namespace-checker linter now runs in more places, so fixes for incorrectly-sorted test namespaces are included in this PR as well. I split those fixes out into #17239 so once that lands I'll merge it in here which will reduce the size of the PR a little.

**Comment by camsaul** [comment]
Everything is green now ping @metabase/backend-developers can I get a review? Don't want this drifting again.

**Review by dpsutton — APPROVED** [review]
i see one failing test currently but seems sound to me

**Pull request merged**
