### PR TITLE
Math aggregations frontend

### LINKED ISSUE #3364: Allow multiple aggregations
Right now we allow a single aggregation (or raw rows) to be run per question.

We should use a similar UI idiom as the multiple breakout `+` to allow multiple aggregations. Each aggregation would be filtered via the filter clause, broken out by the breakout clause.

### LINKED ISSUE #3365: Expression aggregations
We should allow the equivalent of druid post aggregations to do things like divide a result by a constant or once #3364 is in place calculate things like averages.

### PR DESCRIPTION
**Pull request by tlrobinson**
Builds on #3722
Resolves #3364
Resolves #3365

TODO:

* [x] **In the admin panel, edits you make to existing metrics aren't saved**
* [x] Implement new QB bar UI changes
* [x] Long expressions overflow out of the UI 
* [x] Finalize new QB bar UI - @mazameli 
* [x] Fix minifier mangling Chevrotain token names
* [x] Ensure custom expression editor doesn't allow aggregations
* [x] Metrics support. Currently `MetricName()`
  * [x] Switch to identifiers (`metricname`) / string literals (`"Metric Name"`) like fields? - @salsakran 
* [x] Expressions support
* [x] Filter fields based on aggregation type
* [x] Filter aggregations based on db type
* [x] Syntax highlighting? - desirable if we switch metrics to be identifiers/quoted strings to distinguish from field names  - @salsakran 
* [x] Custom Expressions icon asset - @mazameli 
`3 27.4092639 4.98380736 31.8317715 27.8953593 32 27.9344945 26.6700596 10.8490353 26.5446093 19.1452597 17.087941 19.0659475 13.4863777 11.2489381 5.33008404 27.4312443 5.33008404 27.4312443 0 5.00337496 0 3.0793122 4.5090679 13.5268019 15.4100135`
* [x] Aggregation names
  * [x] Finalize UI - @mazameli 
* [x] Fix tests + add tests
* [ ] Fix error: when trying to use Cumulative Sum if I also have any kind of post-aggregation math: `No matching clause: :cumulative-sum`

~This is pretty barebones (no autocomplete, etc) but it works. There's a new "Custom Aggregation" aggregation at the end of the standard aggregations list.~

~It uses PEG.js for the grammer / parser (you'll need to run `pegjs frontend/src/metabase/lib/expressions/aggregation.pegjs` if you edit it), with some parts taken from the JavaScript PEG.js grammar (https://github.com/pegjs/pegjs/blob/master/examples/javascript.pegjs) for identifiers and string and number literals. Still need to figure out how to do autocomplete.~

Now uses Chevrotain and has very accurate autocomplete support

----

Added by Maz:
**UX to-dos and questions:**
* [x] If your cursor is in _front_ of a token, hitting `fn + delete` doesn't select the token and delete it as a whole the way it does when you're at the _end_ of a token and you hit `delete`.
* [x] Make error messages like this one nicer: `Expecting token of type --> RParen <-- but found --> " <--`
* [x] Standard keyboard shortcuts for input fields work weirdly in the expression box. Specifically, if you hit `cmnd + shift + rightArrow` I'd expect it to select all the text from the current cursor position to the end of the line, but it doesn't do that. You also can't hit `cmnd + left/rightArrow` to go to the start or end of the line.
* [x] Autocomplete menu feels like it gets in the way of error messages and of the submit button. I expect it to go away if I click outside of the input box.
*  [x] When I hit Tab I expect to go to `Aggregation name (optional)` input box; instead, it inserts the top item from the autocomplete.
*  [x] The way that backspacing makes a whole tokenized unit disappear is surprising/frustrating. I expected it to just behave like normal backspace.
*  [x] Shouldn’t be able to put a field in `Count()`
*  [x] Do we need to include operators and parens in the suggestion box?
*  [x] Because `esc` is needed right now to dismiss the autocomplete popover, it feels dangerous to have `esc` also dismiss the custom expression popover as well — it’s really easy to accidentally double-tap `esc`, losing all you typed.
*  [x] If I try to select a section of tokenized text, it’s really hard to see the highlighting. The tokenizer also seems to fight my cursor: it keeps repositioning it.
*  [x] When autocompleting a function, like Sum(), I don't know if it makes sense to add the closing paren. It means that you have to use the arrow key after typing the field(s) you want to Sum in order to skip over the paren if you're going to type more after it. My muscle memory keeps wanting to type the closing paren myself instead of using the arrow key.
* [x] What should the cutoff be for the number of fields we show in the autocomplete?
* [ ] If I type a space, the auto complete doesn’t know I’m still typing a field name
* [x] If I type double quotes to try referencing a field with multiple words, the tokenizer seems to barf
* [x] It feels weird how the autocomplete suggests something when i'm at the end of a valid complete expression, like `Sum(Subtotal)`. I'd expect it to not suggest anything new in this situation until I type a space.

**Styling:**
* [x] The autocomplete highlighting feels too subtle. It should probably be a blue background rather than blue text.
* [x] Max width of the expression popover feels too narrow.

### CODE REVIEW

**Comment by salsakran** [comment]
Played around with this branch  w/ @mazameli  and noticed the below issues.

*UX*
    * There’s no visual distinction between aggregations and groupings — they’re all green, and the only thing separating them is the “+” and the “bye"
    * No visual break between aggregations 
    * Is the “+” to the left or the right of “Add a grouping” the “active one”. 
        * Are they the same?
    * Custom aggregation feels hidden
    * I do something that seems like valid syntax, what happens?
        * Current error is "Expected ")" but "s" found."

*Code*
    * If I have two aggregations, and I switch the first one to “Raw Data”, it only shows the second aggregation now
    * Expressions w/ calculated column doesn’t show the column name
    * When I add an aggregation, I can still select “raw data”
    * I can’t use calculated columns in an expression

**Comment by mazameli** [comment]
So for the first 3 UX bullets, one idea would be to make aggregations blue, and leave groupings green, and filters purple. We could also add a vertical separator between aggregations and groupings, like the one between filters and aggregations.

That would look like this:

**Default view / raw data**
default

**Single aggregation**
single-aggregation-no-grouping

**Several aggregations**
(The plus button at the end of the aggregations butting up sort of near the plus button of the empty groupings area is a little weird, but this still felt like the best option of the several I tried. We could move the plus button to the right side of the empty state text for filters and groupings, but it just looks super weird to me.)

multiple-aggregations

**Several aggregations with a grouping**
multiple-metrics-and-grouping


As for the custom expression button feeling hidden, one thought I had was to move it to the same level as the "metabasics" and "common metrics" groupings, the only somewhat odd thing being that 
it's not an accordion like the other two:
custom-expression-at-bottom


As for the error messages, I don't know how aware the parser is of the context. E.g., if there's an aggregation inside of another aggregation, does the parser know that? The quality of the error messages will depend on this to some degree.

**Comment by tlrobinson** [comment]
Most of these shouldn't be any problem.

1. Regarding error messages

> "When I enter invalid expressions, the current error is "Expected ")" but "s" found.", can we get better errors?"

What do you have in mind?

This will change a bit when we switch to Chevrotain, but in general we can compose an error message based on the position of the error, the expected tokens, and the actual string that was found (or end of string).

Also, Chevrotain has a "fault tolerant" mode where it can try to fix minor syntax errors. That might be interesting to play around with. https://sap.github.io/chevrotain/playground/?example=tutorial%20fault%20tolerance

When do we want the error message to appear? Currently it's on blur.

2. Regarding suggestions / autocomplete

Another question is what do we want to show in the suggestions / autocomplete widget? It can be context sensitive and very detailed. e.x. type `1 +`  and we show field names, aggregations, operators, `(`, and suggestions like "a number literal". If you type `Sum(Foo + ` we'd show you everything except the aggregations, since you can't nest aggregations.

We can use similar logic for formatting errors, since we could just run the suggestion code on the input up to the point where the error was.

**Comment by mazameli** [comment]
For autocomplete, yeah, I was envisioning somewhat context aware suggestions.

So with a nearly blank field, you might see this (the "metrics" section is future-looking of course):
autocomplete-1

And if we know you're typing inside of an aggregation, we could exclude aggregations in suggestions:
autocomplete-2

One other idea I'd had that's probably overkill for now since our aggregation functions are pretty simple, is showing a function helper a la Excel:
autocomplete-3

**Comment by salsakran** [comment]
Would it make sense to place the "+" for groupings on the right? Or perhaps not show it for the first grouping?

screen shot 2016-12-08 at 5 13 09 pm

Looks kind of awkward.

**Comment by mazameli** [comment]
Yeah, I just thought it looked a little weird having it on the right; it's such a common pattern to have icon+link pairs with the icon on the left:
single-aggregation-no-grouping copy 2

This is with no plus button:
single-aggregation-no-grouping copy

Another idea is putting a border around the text to make it more clickable looking:
single-aggregation-no-grouping copy 3

The more I look at the first option (buttons on the right), the more I'm okay with it, though.

**Comment by mazameli** [comment]
One thing that got left off of Sameer's list was how to rename the automatic name given to custom expressions. My ideas on that were 1) put a pencil next to the column heading (but of course that only works in raw data / table view), or 2) let the user type "as" or "=" at the end followed by the string for the label, or 3) just be dumb and put another input box in the popover box below the expression field, like we do with the custom field UI.

**Comment by tlrobinson** [comment]
Metrics are aggregations so you wouldn't show them inside another aggregation.

That brings up another issue, how do metrics appear in the expression language?

A normal aggregation would look something like

`Average(Profit) / 100`

Would the `Sunday Profit Average` metric appear like

`SundayProfitAverage() / 100`

or

`"Sunday Profit Average" / 100`

or something else? The latter seems like it could be confusing since you couldn't distinguish between a field and a metric.

Another issue we may run into is collisions between metrics and fields with the same name. Fortunately expressions are persisted parsed into MBQL with actual field/metric IDs, so changing the names won't break them.

**Comment by tlrobinson** [comment]
Regarding splitting up aggregation and breakout, that's a possibility, though I kind of like how it currently reads like a sentence "Count of rows by Category" etc.

**Comment by salsakran** [comment]
yeah, I think it reads reasonably for existing questions, but it looks pretty hokey until you've got a fully spec'd question written.

also, if you don't have a breakout clause it looks really bad.

**Comment by salsakran** [comment]
Regarding syntax highlighting, the ideal behaviour would be to treat a metric, field or function as a "boxed" entity with a display_name or equivalent once it parsed cleanly. I.e. like email addresses in gmail and other email clients.

**Comment by mazameli** [comment]
Expression icon:
`3 27.4092639 4.98380736 31.8317715 27.8953593 32 27.9344945 26.6700596 10.8490353 26.5446093 19.1452597 17.087941 19.0659475 13.4863777 11.2489381 5.33008404 27.4312443 5.33008404 27.4312443 0 5.00337496 0 3.0793122 4.5090679 13.5268019 15.4100135`

**Comment by mazameli** [comment]
Couple small things I just noticed:
- Should `Count()` take any arguments (or suggest any autocomplete options other than `(` and `)`)? It just counts the rows in the table, so if you put anything inside parentheses it ignores it
- If I'm at the end of my expression and I type `enter`, I expected it to commit the aggregation rather than inserting an autocompleted `*`
- If you use the down arrow cursor to cycle through autocomplete options, it works great; after you get to the bottom, it cycles back up to the first option again. But the up arrow acts weird if you go all the way to the top: you have to like press it a few more times before the highlighted option shows up at the bottom again.

**Comment by mazameli** [comment]
I couldn't see on the Heroku branch where you'd put the ability to rename the field, but like I mentioned I think we could just do what we do with the custom field UI and have a second input field for this purpose:

screen shot 2016-12-10 at 3 49 25 pm

**Comment by tlrobinson** [comment]
@mazameli sorry I forgot to update the Heroku branch, it's very out of date. Should be deployed in ~10 minutes.

I was thinking the renaming ui should should be at a "higher level" than the expression editing pane, since you might want to rename a normal aggregation (e.x. "Sum of Total" as "Revenue" or something). Perhaps a small pencil icon or text that appears on hover of aggregation name in the qb bar, somewhere nearby:

screenshot 2016-12-10 16 53 38

Also, eventually we could allow renaming of breakouts (and additional fields, when #1445 is implemented) so it would be good to have it in a consistent place.

**Comment by tlrobinson** [comment]
@salsakran I should be able to do tokenized editor, but more details about he interaction and design would be helpful.

If you're after the closing paren of an aggregation does it delete the entire aggregation with expression, for example?

What does the tokenized aggregation look like?

I imagine fields will be blue, aggregations and metrics green?

**Comment by mazameli** [comment]
> I was thinking the renaming ui should should be at a "higher level" than the expression editing pane, since you might want to rename a normal aggregation (e.x. "Sum of Total" as "Revenue" or something). Perhaps a small pencil icon or text that appears on hover of aggregation name in the qb bar, somewhere nearby

Hmm, it's tough because I don't want to over-optimize for that scenario, but I do see the validity of your point. One possible other way to look at it is you could do a custom expression of `Sum of Total` (even though you could do this with the built-in expression), and give it a custom name. That's definitely a little janky, but the query builder already has so much going on in it that I'm just not in love with the idea of having on-hover actions introduced, especially if they're a little esoteric for everything other than custom fields.

**Comment by tlrobinson** [comment]
You can't do a custom expression with a simple aggregation because there's no difference in the query language between that and the simple aggregation you pick via the menus. You can see this by setting the expression to `Count()`.

I suppose we could use the `named` clause to distinguish them for now.

**Comment by salsakran** [comment]
Couple things I'm finding a bit jarring -

1. The presence of the left parenthesis as a valid option in the drop down list looks funky.
2. When I type 's', 'u', 'm' and then continue, it doesn't "autocomplete" to "Sum" and is case sensitive. The error message is a bit confusing.
3. When I copy+paste and entire `sum(tax * 2)` I get a somewhat cryptic error message 
```Expecting token of type --> RParen <-- but found --> 'tax' <--```

**Comment by tlrobinson** [comment]
Currently autocomplete is case insensitive but the actual parsing is not. Should we make everything case insensitive?

**Comment by camsaul** [comment]
I would vote we try to make things case-insensitive wherever possible, I could imagine that people would expect both `Sum(...)` and `sum(...)` to work.

MBQL '98 itself is case-insensitive so you might not even need to do anything to those on the frontend

**Comment by tlrobinson** [comment]
The expression language has more "friendly" aggregation names than the MBQL ones ("CumulativeSum", for example) so I will have to change some stuff, but shouldn't be hard.

**Comment by mazameli** [comment]
Okay, I polished up the tweaks to the QB UI to move the + buttons to the right, add a separator between the metric selector and the grouping selector, and to make the metric(s) blue.

screen shot 2016-12-19 at 11 59 49 am

**Comment by mazameli** [comment]
Okay, here's where I am right now with the restyling of the popout menu and the tokens. For reference, here's the current styling:

artboard copy 9

I had two main goals:
- increase the amount of horizontal real estate
- rein-in the colors of the tokens to make the aggregation formula easier to read

Here's the version I like the best right now. I widened the menu, decreased the font size down to 14px, and made the token colors a bit more pastel. I also made the input box borders chunkier, like the style of the Pulse creation form, because I think it looks more friendly and Metabase-y:

tokens
Here it is mocked up in a laptop-sized window:

tokens-in-place
It could be that the width will look weird when the fields are empty, so one avenue we could explore is letting the width expand out as the content increases, up to a max-width of x.

I had tried going a bit bigger with everything, but it looked goofy to me when revisiting it, not to mention it eats up more space both horizontally and vertically:

big-tokens

big-tokens-in-place


Feedback welcome!

**Comment by mokra** [comment]
I believe this could also solve #3043

**Pull request merged**
