### PR TITLE
Dashboard and question list filter with checkboxes

### PR DESCRIPTION
**Pull request by alxnddr**
[[Product doc]](https://www.notion.so/metabase/Use-checkboxes-for-category-filtering-c9e8ab5b34e6472fb326c2b829201995)

Change "List of values" filter for questions and dashboards to a list of checkboxes instead of a token field.

#### Column header
Screenshot 2021-12-23 at 02 01 45

#### Filter pill
Screenshot 2021-12-23 at 02 01 53

#### Filter sidebar
Screenshot 2021-12-23 at 02 00 18

### Dashboards
Screenshot 2021-12-23 at 02 02 12

#### Setup
- Go to Admin -> Data Model -> Sample Dataset -> Products
- For "Category" and "Title" change "Filtering on this field" to "A list of all values"
Screenshot 2021-12-23 at 02 13 08
- New question -> Sample dataset -> Products table

#### Cases

**Dashboards**
- Create a question based on the plain Products table without any groupings and filters and add it to a dashboard
- Open the dashboard in edit mode and add Filter -> Text or Category -> Dropdown;
- Connect the filter to the `Title` field and save the dashboard
    - Ensure the filter shows the list of titles with checkboxes
    - Ensure the search box allows filtering values
    - Ensure changing the filter updates the dashboard accordingly
    - Reopen filter and ensure selected values are moved to the top of the list
- Connect the filter to the `Category` field and save the dashboard
    - Ensure no search box is rendered because the list is less than 10 items in length
    - Ensure the filter shows the list of categories with checkboxes
    - Ensure changing the filter updates the dashboard accordingly
    - Reopen filter and ensure selected values are moved to the top of the list

**Questions**
- Simple question -> Sample Dataset -> Products
- Title field in column header and sidebar:
    - Ensure the filter shows the list of titles with checkboxes
    - Ensure the search box allows filtering values
    - Ensure changing the filter updates the table accordingly
    - Click on an added filter pill and ensure selected values are moved to the top of the list
- Category field in column header and sidebar:
    - Ensure the filter shows the list of categories with checkboxes
    - Ensure no search box is rendered because the list is less than 10 items in length
    - Ensure changing the filter updates the table accordingly
    - Click on an added filter pill and ensure selected values are moved to the top of the list

### CODE REVIEW

**Review by daltojohnso — COMMENTED** [review]
There's an unfortunate flash from the default `FieldValuesWidget` UI to the `ListField` UI because `hasList` depends on the existence of field value options which come from an endpoint call. I think this request can be pretty slow, and even worse, we don't cache it so the flash happens every time you open the popover. Maybe the `shouldList` method would work instead? (Wonderful naming conventions in this component 🙂)

https://user-images.githubusercontent.com/13057258/147176251-5309d30a-7adb-43ce-ba14-56caa79d64ea.mov

**Comment by flamber** [comment]
@daltojohnso That's #16103. Should be fairly quick, since the lookup is against the appdb, not the warehouse.
There are several other issues with dropdowns: https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+author%3Aflamber+dropdown+in%3Atitle

**Comment by alxnddr** [comment]
> Maybe the `shouldList` method would work instead?
Unfortunately, I initially used `shouldList` but it broke other cases. I'll try to make it look better

**Comment by alxnddr** [comment]
@daltojohnso good catch with flashing TokenField until the data is loaded. I fixed it by adding a loader

**Review by daltojohnso — APPROVED** [review]

**Pull request merged**
