### PR TITLE
Fix public dash rendering

### PR DESCRIPTION
**Pull request by kdoh**
Investigation into #6352. 

I decided to start by adding a test to create and visit a public dashboard. Strangely though, this is passing when I'd expect it to fail.

@attekei Could this be due to some difference between the Jest environment and the browser environment?

~~That aside, my gut says that a recent change in our webpack config has caused the public app to no longer be able to locate `iframe-resizer.` I'm wondering if the change in #6159 to create a vendor bundle is causing it to be excluded since it's dynamically required.~~

### CODE REVIEW

**Comment by kdoh** [comment]
So after a bit more digging it looks like I have to give some demerits to my gut. I reverted my change in #6159 and that didn't seem to make a difference with being able to locate that module. My new guess is the problem got introduced in the webpack upgrade in #6147 so I'm reading up a bit more to try and understand dynamic requires.

**Comment by kdoh** [comment]
So I have things back to working now having modified EmbedFrame and now public links, embeds, all that kinda stuff seems to work fine, including using `iFrameResizer` to auto size an embed.

I'm confused about a couple things still however.

1. We have a file at `resources/frontend_client/app/iframeResizer.js` that is I guess the file we serve to embeds that lets people use `onload="iFrameResizer({}, this)"` on their `<iframe>`s to have things auto size to the content?

How is that file generated? Is it just static and if so is there any sense of what version? 
If it's tied to our `package.json` how does it get generated?

2. I'm not sure [what this line even does](https://github.com/metabase/metabase/pull/6373/files#diff-1cedc2e8ee1434dd037ca56ade6b9a2cL61). If we're serving up `app/iframeResizer.js` why do we need to do this dynamic require at all? (Also see question 1 as I'm imagining that the require could cause issues if the required package and the served package differed?)

3. I'm still nervous that the tests were passing in the test env but the public links were broken.

@attekei / @tlrobinson If you're able to shed some light I'd feel much more comfortable about this "fix."

**Comment by salsakran** [comment]
this at least seems to empirically work.

**Review by salsakran — APPROVED** [review]
the code look innocuous enough, but I don't know enough about webpack or require to offer anything more substantive.

**Pull request merged**
