### PR TITLE
Fix for more common 24 hour time and Time only field formatting

### PR DESCRIPTION
**Pull request by poorlymac**
Fix for more commonly used 24 hour time https://github.com/metabase/metabase/issues/9538
Fix for Time only field formatting https://github.com/metabase/metabase/issues/9461

I hope these help, and feel free to redo changes any way you prefer.

### CODE REVIEW

**Comment by tlrobinson** [comment]
@poorlymac Thanks. Could you sign the CLA? Some tests would be nice too if you have a chance.

**Comment by poorlymac** [comment]
@tlrobinson, odd I'm certain I did sign the CLA, I will try it again :-) !

**Comment by poorlymac** [comment]
@tlrobinson I did it again

**Review by maltitco — COMMENTED** [review]
this solves the problem with incorrect display of hours after midnight

**Pull request closed without merging**
