### PR TITLE
Fix funnel appearance

### LINKED ISSUE #12042: Funnel graph cuts labels, when dashboard card is specific sizes (and/or smaller viewport)
**Describe the bug**
Funnel graph doesn't stay within card size when resizing card on dashboard or browser window.

**To Reproduce**
1. Native question with this query, change visualization to Funnel, save and add to dashboard
```
SELECT 'Registered' AS Step, 31159 AS Count UNION ALL 
SELECT 'Info_first' AS Step, 28372 AS Count UNION ALL 
SELECT 'Info_second' AS Step, 21494 AS Count UNION ALL 
SELECT 'DOI' AS Step, 19317 AS Count UNION ALL 
SELECT 'Verified' AS Step, 12284 AS Count UNION ALL 
SELECT 'Paid' AS Step, 1522 AS Count
```
2. Resize the card to 7x5:
image
3. Resize the card to 8x5 resize the browser window to ~900px
image

**Information about your Metabase Installation:**
Metabase 0.34.3, various backends and browsers.

**Additional context**
https://discourse.metabase.com/t/funnel-graph-breaks/9238
Related to #12175

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #12175: Funnel data value labels not visible in question visualization
**Describe the bug**
When having a short funnel (eg. 3 rows), the funnel is oversized and cannot view data value labels.

**To Reproduce**
1. Create a Native question and change visualization to Funnel.
```
SELECT 'Registered' AS Step, 31159 AS Count UNION ALL 
SELECT 'Info_first' AS Step, 28372 AS Count UNION ALL 
SELECT 'Info_second' AS Step, 21494 AS Count
```
2. Will look like this (Zooming out to 80% in the browsers seems to show the labels for this specific example):
image

**Information about your Metabase Installation:**
Metabase `master` (0.35-RC), 0.33.6 - various browsers and backends.

**Additional context**
Related to #12042

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #12854: Funnel graph has issues with Full Screen
**Describe the bug**
Funnel graph has a visual bug, cutting the results of each "step" when on full screen.

**Logs**
N/A

**To Reproduce**
1. Create a funnel chart with multiple steps.
2. Expand its "card" to cover at least 7 width x 6 height so that descriptions of 'stages' and results are showing
3. Change dashboard to Full-Screen.

**Expected behavior**
Absolute and percentual results should be shown without being truncated when on full-screen.
**Screenshots**
image

**Severity**
Not very severe. Slightly annoying as users have to hover over the funnel chart to see values.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.171-105.231.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/12042

When a funnel card is narrow I decreased font sizes, ellipsified info text, fixed the layout.

Before:
Screen Shot 2021-06-16 at 23 03 33

After:
Screen Shot 2021-06-16 at 17 14 27

### CODE REVIEW

**Review by gusaiani — APPROVED** [review]
More usable indeed 🚀

**Review by flamber — COMMENTED** [review]
This works great on square-ish cards :tada: 
39.4
image
This PR
image

But when you make them a little more rectangle, but the old problem pops back up:
image

----

It almost fixes three issues: #12042 #12175 #12854

**Comment by alxnddr** [comment]
@flamber thanks for pointing it out, fixed this case as well. Also, I removed excessive empty space in the first section.

Before:
Screen Shot 2021-06-18 at 14 27 21

After:
Screen Shot 2021-06-18 at 14 28 24

**Review by flamber — APPROVED** [review]
Ay ay captain, put all three scoundrels on the boat :ship: 
This looks great in every way I test it :tada:

**Pull request merged**
