### PR TITLE
Effective type in result cols

### PR DESCRIPTION
**Pull request by dpsutton**
This fixes an issue with analysis i ran into when trying to format the results of queries that have a datetime column with a unit.

```clojure
(-> (qp/process-query {:database 1
                       :type :query
                       :query {:aggregation ["count"]
                               :breakout [[:field 4 {:temporal-unit :month-of-year}]]
                               :source-table 2}})
    :data :cols first )

;; yields (with editing)
{:description "The date and time an order was submitted.",
 :unit :month-of-year,
 :name "CREATED_AT",
 :field_ref [:field 4 {:temporal-unit :month-of-year}],
 :effective_type :type/DateTime ;; this is bad!
 :base_type :type/Integer}

;; rows look like this
[[1 1826] [2 1686] [3 1801] [4 1555] [5 1371] [6 1277] [7 1468] [8 1479] [9 1455] [10 1564] [11 1606] [12 1672]]

;; where the integers are the months.
```

##### raw sql
```sql
SELECT month("PUBLIC"."ORDERS"."CREATED_AT") AS "CREATED_AT",
       count(*) AS "count"
FROM "PUBLIC"."ORDERS"
GROUP BY month("PUBLIC"."ORDERS"."CREATED_AT")
ORDER BY month("PUBLIC"."ORDERS"."CREATED_AT") ASC
```

##### graphical display
image

The effective_type was carried over from the field's effective type. This change makes the base_type of the results be the effective type of the column metadata. Effective_type is what you actually got, regardless of any of considerations. Usually this is set due to coercion strategies: you have an integer, coerce it to datetime as a unix epoch timestamp, and base_type is Integer, effective_type is DateTime. 

But when using units like this, you get back results for `month(timestamp)` which comes back as an integer. It doesn't make sense to have the effective_type of the column act as the effective_type of the result as they are quite different. This actually feels close to an expression or computed column. Not sure of the details on those in depth, but it is a result loosely based on a column, not just selecting a column.

### CODE REVIEW

**Comment by dpsutton** [comment]
I'll need to correct some drivers before this gets merged. But if you're here please audit the idea and tell me yea or nay

**Comment by camsaul** [comment]
👍 on adding effective type to the initial metadata we get back from the query...

Should we remove base type from the initial metadata as well? I think the main reason we ran into the bug is that base type we're return is misleading since it's actually the effective type. If we removed base type there it would fix the confusion.

We can have the `annotate` middleware add the actual base_type from the original Field (I think it should already be doing this if it's not already there), so that info would actually be correct

**Comment by dpsutton** [comment]
> Should we remove base type from the initial metadata as well? 
I think yes eventually but not quite yet. I'm also finding some pain points in that mongo doesn't return any type information just the column name so this fix isn't quite fully universal.

**Review by camsaul — APPROVED** [review]

**Comment by dpsutton** [comment]
#### Information about Frontend
This change affects a subtle and potentially far-reaching change. Consider the [following query on stats](https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjEsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiwyNSx7InRlbXBvcmFsLXVuaXQiOiJtb250aC1vZi15ZWFyIn1dXX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoiYmFyIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)

It is orders, grouped-be the month of the year aggregating on count:
image

This query sends back two columns: month and count. The difficulty comes in typing these columns: what is the type of the month column? Previous to this change we preserved the `:effective_type :type/DateTime` from the underlying column of `created_at`. But observe the actual query results (simplified for clarity here):

```clojure
(-> (qp/process-query {:database 1
                       :type :query
                       :query {:aggregation ["count"]
                               :breakout [[:field 4 {:temporal-unit :month-of-year}]]
                               :source-table 2
                               :limit 3}})
    ;;:data :rows
    :data
    (update :cols (fn [cols] (map #(select-keys % [:base_type :effective_type :unit :name]) cols)))
    (select-keys [:rows :cols])
    pprint
    )
{:rows [[1 1826] [2 1686] [3 1801]],
 :cols
 ({:base_type :type/Integer,
   :effective_type :type/Integer,
   :unit :month-of-year,
   :name "CREATED_AT"}
  {:base_type :type/BigInteger,
   :effective_type :type/BigInteger,
   :name "count"})}
```

The type of the `CREATED_AT` column is an _integer_; its values are `1, 2, 3` corresponding to those months. But the UI needs to know that these integers should be interpreted as months.

The change that is important for the frontend is removing this bug that allowed these columns to report as a `:type/DateTime`, and instead reporting as `:type/Integer`. For code that needs to be aware of them, have added a check that `isDate(column) || (column.unit && column.unit !== "default")`. I'm hoping that this is a valid check. How can we identify when an integer column is to be interpreted as months, or days, etc. Does anyone know of a situation where a column like this would have the unit `default`?

**Pull request merged**
