### PR TITLE
Use `Form` on login, user setup, and user password forms

### PR DESCRIPTION
**Pull request by kdoh**
Swaps out the custom form for our `Form` component with better validation and messaging.

- [x] Setup user (`metabase/setup/components/UserStep.jsx`)
- [x] Login email/password form (`metabase/auth/containers/LoginApp.jsx`)
- [x] Forgot password (`metabase/auth/containers/ForgotPasswordApp.jsx`)
- [x] Password reset (`metabase/auth/containers/PasswordResetApp.jsx`)
- [x] Save question (`metabase/containers/SaveQuestionModal.jsx`)
- [x] Database details (connection and schedule) (`metabase/frontend/src/metabase/components/DatabaseDetailsForm.jsx`)
  - [x] Setup
  - [x] Add
  - [x] Edit
- [ ] Settings
  - [ ] `metabase/admin/settings/components/SettingsSlackForm.jsx`
  - [ ] `metabase/admin/settings/components/SettingsBatchForm.jsx`
    - [ ] `metabase/admin/settings/components/SettingsEmailForm.jsx`
    - [ ] `metabase/admin/settings/components/SettingsLdapForm.jsx`
- [ ] Datamodel
  - [ ] `metabase/admin/datamodel/containers/MetricForm.jsx` (`redux-form`)
  - [ ] `metabase/admin/datamodel/containers/SegmentForm.jsx` (`redux-form`)
-  [ ] Data Reference
  - [ ] various (`redux-form`)

### CODE REVIEW

**Comment by tlrobinson** [comment]
FYI I've got a better implementation of `Form`/`CustomForm` in the enterprise fork we should upstream to this PR before merging.

**Comment by kdoh** [comment]
@tlrobinson Couple other things I found:

1. On login, if I use an incorrect password I get into a state like this with no feedback about what happened, which isn't ideal.
Screen Shot 2019-11-04 at 4 08 47 PM

2. On the updated save question modal, the save and cancel buttons should be on the right hand side of the modal footer.
Screen Shot 2019-11-04 at 4 09 46 PM

The other updated forms you I tried seemed to look and behave as expected.

**Comment by mazameli** [comment]
Were you guys intending to swap the modal buttons from the right to the left? This doesn't look right to me. I found three instances, but there could be more.

image

image

image


The right sidebar content is getting scrunched here:

image

image


We're gonna need some max-widths on these inputs:

image

**Comment by tlrobinson** [comment]
@kdoh 

> On login, if I use an incorrect password I get into a state like this with no feedback about what happened, which isn't ideal.

This only seems to happen after you enter the wrong password a second time, correct?

**Comment by mazameli** [comment]
Looks like the login form password error messages are now displaying correctly, and all the other items I mentioned in my comment have been fixed by @tlrobinson's recent commits.

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
Looks like there's just some lint and e2e snapshot items that need to be fixed in order to get this merged. Do we need a @paulrosenzweig assist, @kdoh?

**Comment by kdoh** [comment]
I was able to fix the merge conflicts here but there are some test failures in places where old forms were replaced by the new system and I think not all of our old test env form interaction stuff is working as it used to.

**Comment by tlrobinson** [comment]
Now depends on #11522 which replaces some of the same broken E2E tests

**Pull request merged**
