### PR TITLE
Distribution drill

### LINKED ISSUE #5666: Add `Distribution` action to number field headings once we have binning
Once we have binning (#5331) merged, it would be cool to add `Distribution` to the list of available actions for number fields, which would return a count of rows broken out by that number, binned with the auto/default strategy. This would let you easily see things like number of `Orders` in different `Subtotal` buckets.

screen shot 2017-08-02 at 12 50 23 pm

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #5666

* Currently it's enabled for all non-PK columns
* If it's a number it uses `["binning-strategy", ..., "default"]`
* If it's a datetime it uses `["datetime-field", ..., "month"]` because that seemed like a fairly safe default, until we have an automatic mode for `datetime-field` like we have for `binning-strategy`
* Otherwise it doesn't do any binning (strings, FKs, zip codes, etc)

I think this is a better version of the `Count by time` drill, which never really made sense to me anyway, so I'd say we should just remove that. Maybe it should be a top level action instead of per-column.

### CODE REVIEW

**Comment by tlrobinson** [comment]
Should we use a blacklist or whitelist for the types of fields allowed?

Here's approximately what I think each should be:

1. whitelist: datetimes, numbers but not all numeric things (basically anything that makes sense to do numeric aggregations on. not IDs, zip codes, etc. Do we have a type for that?), categories (does that include all string type fields we can group by?), FKs?
2. blacklist: PKs, descriptions, JSON, ...???

Honestly, I think our type system needs to be cleaned up / expanded / documented a bit better.

**Comment by tlrobinson** [comment]
Also the current sections don't really make a lot of sense to me. We have the "sum" section which includes "sum" and "sum by time" (and previously "count by time"), then we have the "averages" section with what looks more like a timeseries icon which includes various other aggregations (avg, min, max, distincts), plus now "distribution".

**Comment by tlrobinson** [comment]
@camsaul @sbelak Should `ZipCode` really derive from `Integer` which derives from `Number`?

`(derive :type/ZipCode :type/Integer)`

As I understood it the `Number` type is basically for things that you could do arithmetic/aggregations/binning/etc on, which doesn't include zip codes. Zip codes could be stored as numbers or strings but that's irrespective of their semantic types.

**Comment by salsakran** [comment]
:whatmazsaid:, I'd just add that imo distincts are useful for low ordinality numbers (eg, "what are the valid values for rating"), but I don't have high conviction on this.

**Comment by tlrobinson** [comment]
Currently it's using the same logic we use to show aggregations in the QB. I suppose we could special case it, or should we remove "Distincts" from non-low cardinality (category?) types?

**Comment by tlrobinson** [comment]
Oh I think @salsakran is talking about grouping a field without an aggregation in order to see the distinct values. The "Distincts" drill we were talking about is the "Number of distinct values of" aggregation.

**Comment by mazameli** [comment]
> eg, "what are the valid values for rating?"

Well, the current Distincts action wouldn't show you that: it would tell you how _many_ values of rating there are. A separate action that was like "show me all values for this field" (but pithier) would indeed be cool for categoric fields. But I maintain that knowing how _many_ distinct values of rating there are is pretty useless compared to seeing a histogram of its distribution.

**Comment by tlrobinson** [comment]
I think this is ready to be merged unless you want to remove the `Distincts` drill (easy to do in `frontend/src/metabase/qb/components/drill/SummarizeColumnDrill.js`)

**Comment by mazameli** [comment]
I'm seeing a pretty noticeable lag when doing a distribution on some fields. In this example, I would've expected to see the "doing science" loading state:

lag

**Comment by mazameli** [comment]
I'm guessing these actions didn't work before on nested questions, yeah? If I try a distribution action on a numeric field in a nested question, I get `(not (instance? metabase.query_processor.interface.FieldPlaceholder a-metabase.query_processor.interface.FieldLiteral))`. For non-numeric fields in nested questions, the distribution action doesn't show up at all (because we don't have type info?).

**Comment by mazameli** [comment]
Okay, some clarification. In this branch:
- The distribution action on numeric columns is the _only_ action in nested questions resulting in that error: `(not (instance? metabase.query_processor.interface.FieldPlaceholder a-metabase.query_processor.interface.FieldLiteral))`
- The distribution action _is_ appearing for category fields in nested questions, _except_ in nested questions generated from a saved x-ray (weird).

In master, actions on column headings of nested questions appear to be working fine. 😌

**Comment by tlrobinson** [comment]
Bleh. I think this is due to the qb switching the visualization before starting to re-run the query which results in it trying to show a bar chart for the raw data.

**Comment by mazameli** [comment]
Were you able to repro that lagging behavior? Think it's fixable?

**Comment by salsakran** [comment]
Re blacklist vs whitelist, I think it'd better to have a whitelist of the types of fields that a given drill supports. 

Downside: you'd have to make sure when adding a new type that it has the right drills set
Upside: you get less silly things slip through that result in crappy charts everytime someone tweaks the types.

**Comment by salsakran** [comment]
overall I'm a 👍 for the PR, but would prefer to not have distribution for description/json/etc as it tends to result in the browser choking on high cardinality fields on my machine.

**Comment by mazameli** [comment]
So is it easy or hard to hide the action for descriptions/json/etc., @tlrobinson? That and the lagging behavior appear to be the blockers on merging this.

**Comment by tlrobinson** [comment]
@mazameli I've pushed fixes for the delay and blacklisted PKs, Descriptions, Comments, and SerializedJSON. I can change it to a whitelist if you guys give me a list of types.

I think the nested question issue is a limitation of the backend. Do we want to fix binned columns in nested questions in the backend, or hide it on the frontend?

**Comment by salsakran** [comment]
fix it in the backend is my preference.

**Comment by tlrobinson** [comment]
@camsaul @senior what will it take to get `binning-strategy` to work on `field-literal`s?

**Comment by senior** [comment]
Doesn't seem like it would be a big deal. The ticket covering it is https://github.com/metabase/metabase/issues/5938 and it would also be useful for https://github.com/metabase/metabase/issues/7453.

**Comment by salsakran** [comment]
should we just merge this and fix #5938 quickly? I.e. I'd rather not have the user able to click on something reasonable and see a weird clojure stacktrace.

**Comment by tlrobinson** [comment]
I'm fine with that, if we think we'll get to #5938 ASAP, otherwise I can disable the drill for nested questions.

**Comment by salsakran** [comment]
ok, bumping #5938 to a P1, and we'll need to fix it for 0.30 and merging this.

**Pull request merged**
