### PR TITLE
Fix nested query controls for no-data users

### LINKED ISSUE #18977: When no-data user views a nested question, then "Ask question" and "Browse data" appears
**Describe the bug**
When no-data user views a nested question, then "Ask question" and "Browse data" appears in navbar.

**To Reproduce**
1. Simple question > Sample Dataset > Products - save as "Q1"
2. Simple question > Saved Questions > "Q1" - filter by Category="Doohickey" - save as "Q2"
3. Login as no-data user - the navbar correctly looks like this:
image
4. Visit "Q1", navbar still looks the same.
5. Visit "Q2", now the navbar changes to this:
image
6. It is not possible to do much, since most things will end in loading spinners to browser console errors, but the exposure is confusion.

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.41.2 - it is a regression, but probably dating back to 0.33

### LINKED ISSUE #18978: When no-data user views a nested question, then all editing options are exposed
**Describe the bug**
When no-data user views a nested question, then all editing options are exposed. And entering Notebook will cause frontend loop.

**To Reproduce**
1. Simple question > Sample Dataset > Products - filter by Category=`Doohickey, Gizmo` - save as "Q1"
2. Simple question > Saved Questions > "Q1" - filter by Category=`Doohickey` - save as "Q2"
3. Login as no-data user and visit "Q1" - it correctly does not expose anything, not even the filter:
image
5. Visit "Q2", now everything is exposed as-if it was a data-user:
image
6. Trying to make any changes will result in `Sorry, you don’t have permission to see that.` (frontend) / `You don't have permissions to do that.` (backend)
7. Clicking the Notebook editor will result in load spinner, but the frontend constantly reloads and hammering the server with requests (similar to #18818) - forgot to test, but guessing it's a regression since 0.41

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.41.2 - it is a regression, but probably dating back to 0.33

Very related to #18977 and a bit to #11914

### PR DESCRIPTION
**Pull request by kulyk**
Reproduces #18977, fixes #18977, reproduces #18978, fixes #18978

When a no-data user visits a nested query (a question with `source-table: "card__$ID"`), some UI controls allowing to modify the query are exposed. Any attempt to modify a query (filtering, aggregating, reordering columns, changing viz) ends up in "You don't have permission for that" error page.

### To Verify

1. Create a nested query (e.g. in the top navbar "+ Add" > "Question" "Saved Questions" > pick any question > Save)
2. Sign in as a no-data user and open that question
3. Make sure there are no controls to modify a query
    * no "Filter" button
    * no "Summarize" button
    * no "notebook" icon in the view header
    * no "Visualization" and "Settings" buttons in the view footer (@flamber this was not explicitly mentioned in the issues, but changing anything in there doesn't work for no-data users, so I removed them. Please LMK if I'm missing something)
    * no way to reorder table columns by dragging
    * no "Browse Data" link the top navbar
    * no "Question" option in "+ Add" menu in the top navbar
4. Make sure other questions look as before for no-data and normal users

NOTE: we still offer to use drill-throughs in this case (#11914), will fix that in the next PR

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/152987807-736413d2-696f-4c72-8408-ff7a75bdd925.mp4

**After**

https://user-images.githubusercontent.com/17258145/152987836-c3713412-dea3-4265-ba03-91fe7d0becdb.mp4

### CODE REVIEW

**Comment by kulyk** [comment]
@metabase-bot run visual tests

**Review by daltojohnso — APPROVED** [review]

**Comment by kulyk** [comment]
@flamber there was nothing in the tickets about hiding bottom left "Visualization" and "Settings" buttons, but no-data users can't actually do anything with them either. I wonder if they also should be removed? (note: they're removed on this branch)

**Comment by nemanjaglumac** [comment]
Not sure do you want to tackle this in this PR, but `nodata` user can still try to filter (and do all sorts of things) based on the column headers popovers that offer actions.

**Comment by kulyk** [comment]
@nemanjaglumac there is a subsequent PR that hides them, see #20320

**Review by nemanjaglumac — APPROVED** [review]

**Pull request merged**
