### PR TITLE
[WIP] Use Fetch instead of XHR

### LINKED ISSUE #29015: [Epic] Migrate XHR to fetch
[Product doc](https://www.notion.so/metabase/Tech-Migrate-XHR-to-fetch-aeeb15e8bad04e6092bc8283588cee5b)

### PR DESCRIPTION
**Pull request by iethree**
> [!Note]
> Testing to see how CI behaves

Closes https://github.com/metabase/metabase/issues/29015

### Description

giphy

We actually have an implementation of fetch that we only use in unit tests. Let's use it everywhere.

### CODE REVIEW

**Comment by paoliniluis** [comment]
@iethree resolved the simple conflict of the package.json based on the removal of the mysql package that you did a few days ago

**Comment by iethree** [comment]
This PR has a lot of potential to introduce flakes and failures to our CI workflows because it subtly changes request timings. We should probably not merge this until January when our CI situation settles down.

**Comment by iethree** [comment]
sometimes you have to admit defeat 🫡

**Comment by iethree** [comment]
sometimes you have to admit defeat 🫡

**Pull request closed without merging**
