### PR TITLE
Remove type-checking with Flow

### PR DESCRIPTION
**Pull request by ariya**
Normal development workflow should work (`yarn dev`, build process, etc).

Note that some type annotations are still left intact, since they are useful for informational purpose (we need to decide what to do with it at some point in the near future). These annotations are removed anyway during development/building.

<hr>

Basically what I have done:

1) `yarn add flow-remove-types`

2) Create `unflow.js` with the following content:

```js
const fs = require('fs');
const removeTypes = require('flow-remove-types');

function stripDirective(content) {
  const lines = content.split('\n').filter(line => {
    const trimmed = line.trim();
    const lineComment = trimmed.substr(0, 2) === '//';
    const blockComment = trimmed.match(/^\/\*/) && trimmed.match(/\*\/$/)
    const comment = lineComment || blockComment;
    const directive = trimmed.includes('@flow');
    const rule = trimmed.includes('eslint-disable') && trimmed.includes('flowtype');
    return !(comment && (directive || rule));
  });
  return lines.join('\n').trimLeft();
}

function unflow(content) {
  return removeTypes(stripDirective(content), { pretty: true });
}

let args = process.argv;
args.shift();
args.shift();

args.forEach(arg => {
  const content = fs.readFileSync(arg, 'utf-8');
  const modifiedContent = unflow(content);
  if (content != modifiedContent) {
    console.log(arg);
    fs.writeFileSync(arg, modifiedContent, 'utf-8');
  }
});
```

3) Run these commands:

```bash
find ./frontend/ -type f \( -name '*.js' -o -name '*.jsx' \) -print0 | xargs -0 -n1 node ./unflow.js
find ./enterprise/frontend/ -type f \( -name '*.js' -o -name '*.jsx' \) -print0 | xargs -0 -n1 node ./unflow.js
```

### CODE REVIEW

**Comment by rlotun** [comment]
linking to https://github.com/metabase/metabase/issues/14802

**Review by daltojohnso — APPROVED** [review]
Nice work!

Question -- how is `eslint` not barfing on the type definitions, `import type ...`, etc. without any relevant plugins?

**Comment by ariya** [comment]
> Question -- how is `eslint` not barfing on the type definitions, `import type ...`, etc. without any relevant plugins?

I believe it understands (likely via Babel) some "basic" type annotation syntax, although it doesn't do anything with it.

**Comment by camsaul** [comment]
Fixes #14802

**Pull request merged**
