### PR TITLE
don't pass dashcard viz settings to query builder

### PR DESCRIPTION
**Pull request by daltojohnso**
Related to #13595 

1. When drilling from dashboard --> question, use the original `card.visualization_settings` prop so that dashcard viz settings don't get sent to the query builder
2. When a user lacks self service data permissions, use the original `dashcard.card` object to avoid scenarios where our logic thinks the card is "dirty" and thus tries to run an ad hoc query

### CODE REVIEW

**Comment by daltojohnso** [comment]
@flamber -- is this what you want for #13595? When navigating dashboard --> question I'm now taking whatever viz settings are set on the original card. Also, I think I fixed the issue with users without data permissions being unable to title drill on cards with dashboard viz settings set.

**Review by flamber — APPROVED** [review]
So this definitely works from the perspective of not parsing dashcard settings into the card.
And would prevent a lot of those annoying permission problems.

I'm guessing that the queryhash is needed, as it has information about the parameter. Just makes bookmarking a link "less clean".

The only thing that I'm vary about is which unexpected behavior this might lead to.
If someone has created dashboards for different languages using the same questions, but have then made the "translation" via the dashcard, then those users would not be able to see those adjustments when drilling to the question.

Though, that feels like a P2 that we would have to deal with at some point, but currently not even allowing nodata-users to access questions (example, so they can export) or accidentally save dashcard settings (like Click Behavior) into the question, seems like much better problems, so I'm actually :+1: on doing this, but we probably need a few more eyes on this.

Bug:
When I as Admin does a drill, then the question is dirty (as expected)
image
But if I remove the filter (click X), then the URL changes to only `/question` (nothing else) and the UI looks like this, which seems like an inconsistent state (half clean, half dirty):
image

**Comment by daltojohnso** [comment]
Regarding that bug, apparently whenever you create an ad hoc question from a saved question and then return to the initial state of that saved question, it fails to mark the card as "dirty" so it gets into a bad url state. Adding an additional check on the existence of a card id fixes it. The code for determining the URL of the query builder is so messy, however, so pretty unsure about if this causes other problems. This "fix" keeps the URL hash and doesn't return the user to the original url -- that's a bit more complicated, but can work on it if desired.

Before

https://user-images.githubusercontent.com/13057258/145916194-7e6bbf6c-7053-48e0-8966-77d146fa868f.mov

After

https://user-images.githubusercontent.com/13057258/145916206-357a2b11-3c33-4881-a8c8-e2f4106d235c.mov

**Review by alxnddr — APPROVED** [review]

**Comment by flamber** [comment]
@daltojohnso Didn't even notice that this was the behavior currently. It seems like it might have been a regression from some time ago, I'll have to investigate that. We can merge this, but not sure if we should have more eyes on it.

**Comment by daltojohnso** [comment]
I'm going to go ahead and merge this. The line I added in https://github.com/metabase/metabase/pull/19329/commits/d8a979458a151de7d9c96fad7628dd21e9106a39 ought to get hit pretty frequently since that code is run on every change of the query builder URL.

**Pull request merged**
