### PR TITLE
sankey chart

### LINKED ISSUE #11888: Visualization: Sankey Diagram/User Flow Visualization
**Is your feature request related to a problem? Please describe.**
I would like to visualize how users are flowing through our app.

**Describe the solution you'd like**
A new type of visualization similar to this [User Flow](https://px6vg4ekvl21gtxs836x5jyx-wpengine.netdna-ssl.com/wp-content/uploads/2018/12/ezgif.com-video-to-gif-1.gif)

**Describe alternatives you've considered**
I have tried using line charts and scatter plots, but neither of them provides enough functionality.

**How important is this feature to you?**
This type of visualization would help us improve our UX by helping us better understand how people are navigating our app and where they are getting stuck. I imagine it would be beneficial to many others.

**Additional context**
None

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #29671: [Epic] Sankey Chart v52
Closes https://github.com/metabase/metabase/issues/11888

**Links**
- feature branch: `sankey-echarts`

**Implementation Plan**

### Milestone 1: Minimum shippable Sankey [1-2 weeks]
- [x] Implement data settings to support the [first suitable data shape](https://www.notion.so/metabase/Offer-new-viz-type-Sankey-chart-ebc7f49acbf740249115f65d017e8bf6?pvs=4#11269354c901806893e7ced80221a325)
- [x] Add all columns to the data transformation for tooltips and click behavior
- [x] Implement correct chart layout calculation to avoid overflows
- [x] Use our palette when assigning colors to segments
- [x] Handle errors when data shape is not correct
- [x] Add extensive visual specs coverage
- [x] Edge color selection
- [x] Right/Left/Justify align

#### Blockers / zero-effort work

This list contains blockers and near-zero effort polish tasks.

- [x] Update Sankey visualization icon [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524042369109)
- [n/a] ~Hovers are laggy~ [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523715459839) [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524562507779) — unrelated, caused by [Pooling database sync status triggers rerender that hides ECharts tooltips](https://github.com/metabase/metabase/issues/50309#top)
- [x] Handle labels collision better [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523875300039) [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523886446819) [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524089924339) [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524222339589)
- [x] Keep drills that only make sense for sankey [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523595974099)
- [x] Improve the error message when data has a circular dependency [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523657120589)
- [x] Improve the error message when selecting the same column as source and target at the same time [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523845921729)
- [x] Tweak font style for labels [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523794332379)
- [x] Add padding [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523961754569)
- [x] Change the default edge color to `source` [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524138661239)
- [x] Increase default sankey dashboard card size [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524182447699)
- [x] Fix tooltip values do not have formatting applied [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524495015619)
- [x] Handle longer node labels better [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524574427109)
- [x] Support compact numbers formatting [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524383195119)
- [x] Data labels configuration

#### Tests

- [x] Add dashboards E2E specs
- [-] Add BE static viz smoke test: https://github.com/metabase/metabase/pull/50793 (non-blocking)

### PR DESCRIPTION
**Pull request by alxnddr**
Epic https://github.com/metabase/metabase/issues/29671
Closes https://github.com/metabase/metabase/issues/29671
Closes https://github.com/metabase/metabase/issues/11888

PR with visual specs https://github.com/metabase/metabase/pull/49457

### Description

Implements a basic sankey chart.

### Demo

<video src="https://github.com/user-attachments/assets/7991ef19-7cc4-4d75-9bdf-d50fddfb1358" />

### CODE REVIEW

**Comment by deepfates** [comment]
Hi, curious when we might expect to see Sankey charts land in main. Any projections on this?

**Comment by alxnddr** [comment]
Hey @deepfates 👋 Unfortunately, it is unlikely we could prioritize this into the upcoming 51 release that should happen roughly in a week. We scheduled the Sankey for 52 which will get released in a couple of more months

**Review by cdeweyx — APPROVED** [review]

**Comment by kdoh** [comment]
I'm still seeing the bug where tool tips auto close after a few seconds without me moving my mouse. Running Firefox Developer (133.0b9).

Other than that, things are looking solid from my run through but I think that's a core blocking bug.

**Comment by alxnddr** [comment]
> I'm still seeing the bug where tool tips auto close after a few seconds without me moving my mouse. Running Firefox Developer (133.0b9).

I moved this into a separate issue since it is not related to Sankey chart — https://github.com/metabase/metabase/issues/50309

**Review by kulyk — APPROVED** [review]
🏆

**Pull request merged**
