### PR TITLE
[milestone 1] Prevent users from adding questions in personal collections to dashboards in public collections

### PR DESCRIPTION
**Pull request by WiNloSt**
> **Note**
> All PRs have been approved, this is just the milestone PR. But feel free to test everything again.

This is milestone 1 for Epic: https://github.com/metabase/metabase/issues/34733

_The testing plan below is copied from the epic_

#### Testing plan for milestone 1
Dashboards
1. Add a question to a dashboard in a public collection
    **expectation**: hides all personal collections
1. Add a question to a dashboard in a personal collection
    **expectation**: shows all collections
1. move a dashboard from a personal collection to a public collection and test 1)
    **expectation**: hides all personal collections
1. move a dashboard from a public collection to a personal collection and test 2)
    **expectation**: shows all collections

Query builder

Newly created question
1. Select a dashboard for a question in a public collection
    **expectation**: shows all collections
1. Select a dashboard for a question in a personal collection
    **expectation**: hides all public collections
1. Open public collection for a question in a public collection
    **expectation**:
        - shows `+ Create a new dashboard` option
        - shows dashboards
1. Open personal collection for a question in a public collection
    **expectation**:
        - shows `+ Create a new dashboard` option
        - shows dashboards
1. Open public collection for a question in a personal collection (this only happens for the root collection, as other public collections are already hidden)
    **expectation**:
        - hides `+ Create a new dashboard` option
        - hides dashboards
1. Open personal collection for a question in a personal collection
    **expectation**:
        - shows `+ Create a new dashboard` option
        - shows dashboards
1. When the question is in a public collection and the most recently viewed dashboard is in a public collection
    **expectation**:
        - shows the most recently viewed dashboard
1. When the question is in a public collection and the most recently viewed dashboard is in a personal collection
    **expectation**:
        - shows the most recently viewed dashboard
1. When the question is in a personal collection and the most recently viewed dashboard is in a public collection
    **expectation**:
        - shows the root collection instead
1. When the question is in a personal collection and the most recently viewed dashboard is in a personal collection
    **expectation**:
        - shows the most recently viewed dashboard

Existing question
1. Move a question from a personal collection to a public collection and test 1) from the **Newly created question** section
    **expectation**: shows all collections
1. Move a question from a public collection to a personal collection and test 2) from the **Newly created question** section
    **expectation**: hides all public collections
1. Test the rest of the scenarios from the **Newly created question** section

### CODE REVIEW

**Comment by WiNloSt** [comment]
Current dependencies on/for this PR:
* master
  * **PR #35135** <a href="https://app.graphite.dev/github/pr/metabase/metabase/35135" target="_blank">Graphite</a>  👈
    * **PR #35136** <a href="https://app.graphite.dev/github/pr/metabase/metabase/35136" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/35135?utm_source=stack-comment).

**Review by ranquild — APPROVED** [review]
@WiNloSt please ask @cdeweyx to review

**Comment by WiNloSt** [comment]
@ranquild does he need to review again? There's basically 0 behaviour change in milestone 1 [since his last review](https://github.com/metabase/metabase/pull/34833#pullrequestreview-1697665857).  But I mean it doesn't hurt to test again.

**Comment by ranquild** [comment]
@WiNloSt makes sense, feel free to merge

**Pull request merged**
