### PR TITLE
Change dashboard grid with to 24 units wide (experimental-ish)

### PR DESCRIPTION
**Pull request by mazameli**
This was proposed in https://github.com/metabase/metabase/issues/6218 (with a number of great reasons included there) and I wanted to try it out and see how it felt. It feels to me like this gives a lot more flexibility in dashboard layout, and as @vi-vsn pointed out, now you can have four equally-sized charts in the same row, like this:

screen shot 2018-05-01 at 5 07 50 pm

screen shot 2018-05-01 at 5 08 03 pm

**Questions/concerns**
- Does this feel more, or less friendly? It feels less restrictive to me.
- This allows for smaller cards, which seems like a plus to me, but we'll want to make sure none of these are too small now.

### CODE REVIEW

**Comment by edmarriner** [comment]
This seems like a good change to me. More flexibility is always welcome when you are trying to cater for many different situations or scenarios.

**Comment by vi-vsn** [comment]
That's great that you decided to pursue it. Even greater still that it can be done by changing a constant in a single file :+1:

**Comment by kdoh** [comment]
@metabase/core-developers Are there any issues that might effect existing dashboards here? If not, I'm thinking we should go ahead and move to this.

**Comment by tlrobinson** [comment]
One option is to just version dashboards and use the 18 for existing and 24 for new

**Comment by vi-vsn** [comment]
The way to convert between the grids - is to translate proportions and
round them to integer.

18/18 = 24/24
16/18 = 8/9 = 22/24 etc.

If you take this approach - it appears to me that things should work.

**Comment by MarkRx** [comment]
This would be great. It would help the fact that some of the single box types are too big at their smallest size (such as "Number")

**Comment by vi-vsn** [comment]
> most number of ways to divide cards in a grid (1, 2, 3, 4, 6, 12, 24).

Also 8.

**Comment by MarkRx** [comment]
@mazameli @tlrobinson here is a sample of what migrations would look like. As visualized below card sizes stay pretty close to their originals. It doesn't look bad at all... in fact most people probably wouldn't even notice. Since 18 and 24 are both divisible by 3 the most a card will differ on a single edge is 1/4 of the original grid block size.

resize_checker

As for the grid I'm not sure if you would also want to ensure square blocks and thus want to perform a vertical migration as well.

**Comment by MarkRx** [comment]
Migration Math Notes:
- New column start locations are old column * (24 / 18) rounded
- Every n % 3 = 1 increases the size of a card by 1

Given:
- C(n) is the new zero-based column
- C(p) is the old zero-based column 
- W(n) is the new width
- W(p) is the old width

```
C(n) = round(C(p) * 24 / 18)
W(n) = W(p) + (floor((C(p) + W(p) + 2) / 3) - floor((C(p) + 2) / 3))
```

**Explanation**
`round(C(p) * 24 / 18)` scales the column to the new coordinate system
`floor((C(p) + 2) / 3)` is the number of times the old start column intersected the set {1, 4, 7, 10, ...}
`floor((C(p) + W(p) + 2) / 3)` is the number of times the old end column intersected the set {1, 4, 7, 10, ...}
`floor((C(p) + W(p) + 2) / 3) - floor((C(p) + 2) / 3)` is the number of times we need to account for width growth due to a card using a grid column in the set {1, 4, 7, 10, ...}
`W(p) + (floor((C(p) + W(p) + 2) / 3) - floor((C(p) + 2) / 3))` is the scaled width onto the new coordinate system

I believe the migration sql will thus be:
```
update report_dashboardcard set col = round(col * 24.0 / 18.0);
update report_dashboardcard set sizeX = sizeX + floor((col + sizeX + 2) / 3) - floor((col + 2) / 3);
```

**Comment by mazameli** [comment]
Closing this for the time being since we haven't made movement on this in over a year, but we'll keep the branch and comments etc. around in case we want to revisit this and solve the migration problem.

**Comment by MarkRx** [comment]
I'm kind of disappointing this is being knocked out. I don't like the 18 wide grid at all. I believe my comment above solves the migration problem as it gives an algorithm to map coordinates with very little skew.

**Comment by RMMSecurity** [comment]
Any reason why this wouldn't be implemented? Since this was initially proposed there hasn't been any arguments against implementing it.  The issue around how to migrate existing dashboards was in my opinion solved by @MarkRx  's contributions. Add that to your migration steps and it's a great enhancement.

@mazameli as always came up with a great example to illustrate what you gain OOTB with the change. Given how restrictive the current system is you have to ask yourself if people would even *want* to be at 18 units wide given the choice. 

@tlrobinson did you ever get a change to review @MarkRx's solution? I think that covered it, but I'd be curious to hear your thoughts on the matter.


For reference I apply this change along with adjusting the minimum card size to 1x1 to our production branch of metabase and any dev branches I work on. Once you use it then going back to 18 feels stifling. **It's not a matter about squeezing more information into a dashboard, but helping the users/creators arrange their data into what makes the most sense for them.**   A use case for the 1x1 text cards is making them markdown cards and providing a better overview of the data, a better/clearer header, or separation between portions of your dashboard. (I can provide examples!)

**Comment by ni-ka** [comment]
As a new metabase user, I am trying to build symetrical and optically pleasing dashboards. I have researched if there is a way to adjust the grid setting and found this issue as well as https://github.com/metabase/metabase/issues/6218. I understand this may have implications for existing dashboards, but isn't it possible to implement configurable setting and eventually change the default value for new dashboards to 24?

**Pull request closed without merging**
