### PR TITLE
Fix raw HTML strings in QueryBuilderTutorial

### LINKED ISSUE #9566: Tutorial shows <strong> tag instead of making the text bold
- Your browser and the version: Firefox 65
- Your operating system: Windows 10
- Your databases: SQLite
- Metabase version: 0.31.2
- Metabase hosting environment: Local, Windows 10
- Metabase internal database: H2

- Steps to reproduce the issue: "Ask a Question" -> "Custom" or "Native query" -> "How do I use this thing?"-> Go to cards 4, 5, 6, or 7.

tags1

### PR DESCRIPTION
**Pull request by rohitpaulk**
Fixes #9566. 

Screenshots: 

2019-04-19-183346_501x463_scrot

2019-04-19-183328_478x382_scrot

2019-04-19-183314_473x321_scrot

2019-04-19-183302_477x421_scrot

 
### Tests

-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)

-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Note: Running `yarn test` locally failed for me (on master, not just this branch): 

```
 FAIL  frontend/test/metabase/visualizations/components/LineAreaBarRenderer.unit.spec.js (76.472s)
  ● LineAreaBarRenderer › should display hourly data (in Z timezone) in X axis and tooltip consistently

    expect(received).toEqual(expected)

    Expected value to equal:
      ["October 3, 2016, 8:00 PM", "October 3, 2016, 9:00 PM"]
    Received:
      ["October 3, 2016, 7:30 PM", "October 3, 2016, 8:30 PM", "October 3, 2016, 9:30 PM"]

    Difference:

    - Expected
    + Received

     Array [
    -  "October 3, 2016, 8:00 PM",
    -  "October 3, 2016, 9:00 PM",
    +  "October 3, 2016, 7:30 PM",
    +  "October 3, 2016, 8:30 PM",
    +  "October 3, 2016, 9:30 PM",
     ]
```

Looks like it has to do with the fact that I'm in a timezone that isn't rounded to the hour (`+5:30`).

**Comment by rohitpaulk** [comment]
Fixed a conflict - I'll rebase this soon.

**Comment by kdoh** [comment]
Hi @rohitpaulk. Thanks for this. Have you had a chance to rebase this yet?

As far as that test failure goes I haven't run into that locally. Updating to the latest master might help out.

**Comment by rohitpaulk** [comment]
Rebased! :slightly_smiling_face:

**Comment by tlrobinson** [comment]
Thank you @rohitpaulk

**Pull request merged**
