### PR TITLE
Use jvm flags for docker memory

### PR DESCRIPTION
**Pull request by wallies**
The JDK 8u131 has backported a nice feature in JDK 9, which is the ability of the JVM to detect how much memory is available when running inside a Docker container. https://blog.csanchez.org/2017/05/31/running-a-jvm-in-a-container-without-getting-killed/

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
didn't know about these flags. I don't see how adding them could hurt

**Comment by senior** [comment]
@wallies The blog post assumes you're specifying a memory limit for the docker container. What happens if you don't specify one? With the ` -XX:MaxRAMFraction=1`, would  that attempt to set the max heap to the amount of memory on the host system?

**Comment by wallies** [comment]
@senior I suppose it could. Although it would leave room for non-heap, as the JVM also accounts for other overhead, setting n=1 will configure a maximum heap size of slightly less than the amount of memory on the host system. Could add some instructions on how to run with docker, about setting a good limit, as this is good practice anyway. Could do same with kubernetes helm chart.

**Comment by senior** [comment]
I think that having this setting is a good idea and for docker users that are specifying the memory constraints for their docker containers out of habit, this will make Metabase behave memory-wise like they would expect. 

I'm primarily concerned about what the upgrade path looks like for existing users that are not specifying a container memory limit and are relying on the default behavior. Specifying the limit is a good practice, but breaking them on upgrade would be bad.

The other downside of this is users would no longer be able to run our docker container with no config arguments. Before the run the container they must decide how much memory to dedicate (or read our suggestions in docs) and specify it before launching.

I think having this setting is a good thing and using it would be a best practice for the admin, I just think we need to be careful about how we roll it out. If it was an opt-in sort of setting (i.e. MB_CONTAINER_DEFAULT_MEMORY=1) that seems like it might be better. Something like that where existing users could continue to work as-is and users wanting this behavior could just set that environment variable.

@camsaul @salsakran Have you got any thoughts on this change and it's impact on upgrades?

**Comment by salsakran** [comment]
strong 👎 on forcing a user to pass in memory config arguments to get things going.

I think it's a good additional knob for admins that know what they're doing to tweak things, but imo it breaks the zen of Metabase to make me think about how much memory to dedicate to a container.

**Review by senior — CHANGES_REQUESTED** [review]
:+1: on the idea, but it should be an opt-in setting so it doesn't force users to supply it and break users on upgrade.

**Comment by camsaul** [comment]
Thanks for this. We recently switched to Java 11 as our base image so these options to respect `ulimit`s are no longer experimental but enabled by default if I understand correctly, so going to go ahead and close this as no longer applicable

**Pull request closed without merging**
