### PR TITLE
Don't attempt to load card metadata if the card's table wasn't fetched

### LINKED ISSUE #11297: Collections View Permissions failing after upgrade to 0.33.5
Upgraded to 0.33.5 and now the ability to view Saved Questions is broken.  On the previous version, Users with View permissions on a Sub-collection previously could view the Question without access to the underlying data, but now they cannot.  If I give "Grant Unrestricted Access" to the group, then the user can run the saved question.  I believe that the new behavior is incorrect because it kind of defeats the point of saved collections.

Here's the javascript console of the error:
image

To be clear, the user can see the Subcollection and Question, but clicking on the question only provides the perpetual spinner with the error above.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #11297

This PR fixes the immediate cause of the bug but doesn't address the larger issues:

## 1. What's the right way to display the QB UI in this state?

* Should we hide the bottom bar that contains Visualzation and Settings?
* Should we allow tables headers to be filtered or reordered?
* Should we allow drill through? What about custom drill through in EE?

In v0.33.3, without data permissions we didn't show the "clicky chevrons" in table headers. That feels like the right behavior. However, as far as I can tell this was by accident. When getting the click actions an error occurred, which resulted in [visualizationIsClickable](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/components/Visualization.jsx#L282-L287) returning false.

## 2. How should we handle failed API calls

We should avoid making calls to endpoints that will 403. If we do get a 403, we probably shouldn't blow up the page. Even if we avoid all situations like that, these API calls still might fail. @camsaul suggested that we shouldn't break the question if auxiliary endpoints fail. 

I'm hesitant to just silence all API errors on secondary endpoints. If fetching table metadata fails, we can no longer display some essential UI for editing a question. Can we come up with a good, general way to gracefully degrade when we have most of the data? e.g. maybe we display an error to the user but never let the exception bubble up and break things.

## 3. We need some better tests

@camsaul pointed out that this looks very much like #10656. While the root cause was different, a few good e2e tests would have caught either situation.

I started implementing those in [this file](https://github.com/metabase/metabase/blob/master/frontend/test/metabase/scenarios/query_builder.e2e.spec.js), but it seemed like it was going to be a mess. Instead, I'm going to add them to #11302. That will be a good opportunity to to test out Cypress some more, but if we end up abandoning it, I'll need to port the tests.

### CODE REVIEW

**Review by kdoh — APPROVED** [review]
Code looks 👍. I'll probably need to think a bit more about the larger questions you raised in the description before I can say anything particularly cogent. Might also want to rope in @mazameli

**Comment by mazameli** [comment]
I still need to spin up this branch and verify the behavior is right, but let me address the questions in #1:

> Should we hide the bottom bar that contains Visualization and Settings?

Nope.

> Should we allow tables headers to be filtered or reordered?

Reordering would be a nice-to-have, but not critical. Should not be able to filter.

> Should we allow drill through? What about custom drill through in EE?

No drill-through, unless it's an enterprise custom drill through. Custom drill through was getting disabled previously, though, so I opened up a new EE issue to track the request for this change: https://github.com/metabase/metabase-enterprise/issues/339

> In v0.33.3, without data permissions we didn't show the "clicky chevrons" in table headers. That feels like the right behavior. However, as far as I can tell this was by accident. When getting the click actions an error occurred, which resulted in visualizationIsClickable returning false.

I agree that I think disabling the clickable column headings is the correct behavior in this situation. The column menus only contain actions that a restricted user wouldn't be able to do, with the exception of `Formatting` which is just a shortcut to the visualization `Settings` button.

Also, I don't know if this has come up but I believe I _should_ be able to use SQL filter widgets in this scenario. I'll double check what we used to do in 0.33.3 though.

**Comment by mazameli** [comment]
So it appears the behavior for SQL params for restricted users as of 0.33.3 was that we exposed filter widgets and allowed restricted users to input values, but we did not display the list of possible values. I'd propose we keep this behavior in this PR — if we want to change that behavior, I think I'd want to treat that as a separate PR because I'm not sure we'd want to expose values that might not be otherwise visible to restricted users.

Here's a screenshot from 0.33.3 — admin view on left, restricted user on right:

image

**Comment by mazameli** [comment]
Couple things:
- It would be great if we disabled drag-to-zoom on timeseries for restricted users: if they try to drag to zoom, they see a permissions error page.
- Looks like column heading actions are still enabled, but shouldn't be.
- Should also hide drill-through/filtering options when clicking on cells in a table. Not sure if this was correctly implemented in 0.33.3.
- I'm getting an endless loop when trying to view nested questions, even when I have collection access to both the nested and nesting saved questions. See this in the JS console:

```
Uncaught (in promise) TypeError: Cannot read property 'schemaNames' of null
    at Table.hasSchema (Table.js:39)
    at getDataSourceParts (QuestionDataSource.jsx:49)
    at Function.webpackJsonp../query_builder/components/view/QuestionDataSource.jsx.QuestionDataSource.shouldRender (QuestionDataSource.jsx:23)
    at ViewTitleHeader.render (ViewHeader.jsx:134)
    at ViewTitleHeader.<anonymous> (makeAssimilatePrototype.js:15)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:359)
hasSchema @ Table.js:39
getDataSourceParts @ QuestionDataSource.jsx:49
webpackJsonp../query_builder/components/view/QuestionDataSource.jsx.QuestionDataSource.shouldRender @ QuestionDataSource.jsx:23
render @ ViewHeader.jsx:134
(anonymous) @ makeAssimilatePrototype.js:15
(anonymous) @ ReactCompositeComponent.js:793
measureLifeCyclePerf @ ReactCompositeComponent.js:73
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:792
_renderValidatedComponent @ ReactCompositeComponent.js:819
performInitialMount @ ReactCompositeComponent.js:359
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createInitialChildren @ ReactDOMComponent.js:701
mountComponent @ ReactDOMComponent.js:520
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createInitialChildren @ ReactDOMComponent.js:701
mountComponent @ ReactDOMComponent.js:520
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createInitialChildren @ ReactDOMComponent.js:701
mountComponent @ ReactDOMComponent.js:520
mountComponent @ ReactReconciler.js:43
_updateRenderedComponent @ ReactCompositeComponent.js:762
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
performUpdateIfNecessary @ ReactCompositeComponent.js:558
performUpdateIfNecessary @ ReactReconciler.js:154
runBatchedUpdates @ ReactUpdates.js:148
perform @ Transaction.js:141
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:65
onStateChange @ connectAdvanced.js:202
(anonymous) @ makeAssimilatePrototype.js:15
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:17
dispatch @ applyMiddleware.js:35
action @ store.js:25
_callee3$ @ actions.js:466
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.<computed> @ runtime.js:114
step @ actions.js:77
(anonymous) @ actions.js:77
Promise.then (async)
step @ actions.js:77
(anonymous) @ actions.js:77
Promise.then (async)
step @ actions.js:77
(anonymous) @ actions.js:77
Promise.then (async)
step @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:497
(anonymous) @ store.js:19
(anonymous) @ bindActionCreators.js:3
componentWillMount @ QueryBuilder.jsx:174
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createInitialChildren @ ReactDOMComponent.js:701
mountComponent @ ReactDOMComponent.js:520
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
_updateRenderedComponent @ ReactCompositeComponent.js:762
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
performUpdateIfNecessary @ ReactCompositeComponent.js:558
performUpdateIfNecessary @ ReactReconciler.js:154
runBatchedUpdates @ ReactUpdates.js:148
perform @ Transaction.js:141
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
(anonymous) @ Router.js:103
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
done @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
getComponentsForRoute @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
mapAsync @ AsyncUtils.js:78
getComponents @ getComponents.js:29
finishEnterHooks @ createTransitionManager.js:77
next @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
wrappedNext @ TransitionUtils.js:110
_callee$ @ routes.jsx:170
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.<computed> @ runtime.js:114
step @ routes.jsx:94
(anonymous) @ routes.jsx:94
Promise.then (async)
step @ routes.jsx:94
(anonymous) @ routes.jsx:94
(anonymous) @ routes.jsx:94
(anonymous) @ routes.jsx:214
transitionHook @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
next @ AsyncUtils.js:34
loopAsync @ AsyncUtils.js:51
runTransitionHooks @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
runTransitionHooks @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
finishMatch @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
next @ AsyncUtils.js:41
loopAsync @ AsyncUtils.js:51
matchRoutes @ matchRoutes.js:231
match @ createTransitionManager.js:41
historyListener @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
Router_componentWillMount @ Router.js:96
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
_init @ app.js:67
(anonymous) @ app.js:106
Show 222 more frames
ReactCompositeComponent.js:742 Uncaught TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:742)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:721)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:642)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:544)
    at Object.receiveComponent (ReactReconciler.js:122)
    at Object.updateChildren (ReactChildReconciler.js:107)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:204)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:308)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:295)
    at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:944)
```

**Comment by flamber** [comment]
@mazameli 
Allowing filter options without data access sounds like #8472 (or #9270 fixed by #10799 on 0.33.3)
The nested question error is likely #11028.

**Comment by mazameli** [comment]
Okay, so maybe addressing the nested questions bug (#11028) is out of scope for this PR, @paulrosenzweig.

**Pull request merged**
