### PR TITLE
Smarter XRay comparisons pages

### PR DESCRIPTION
**Pull request by attekei**
- [x] Add tests for segment-by-segment comparison and segment-by-table comparison
- [x] Fix an issue with a missing feature value causing a page render error
- [x] Remove obsolete `/x-ray/compare/segments/:id/:id/field/:field` field data endpoints
- [x] Add "Compare with segment X" options to segment xray page
    - Requires the new “entities that can be compared to model X” endpoint that @sbelak is working on
- [x] Add table-by-table comparison pages
    - Unify the comparison logic so that there is just minimal duplication
- [x] Add comparison links enabled by the table-by-table comparison
- [x] In comparison pages, add dropdowns for switching the left/right compared model
- [x] Add test case for table-by-table comparison
- [x] Add test cases for comparison dropdowns (both on non-comparison and comparison pages)

### CODE REVIEW

**Comment by sbelak** [comment]
Added a new field :comparables to return of all /api/x-ray/model/:id responses. Format is as follows:
```[{:model :id}, ...] ```
eg.:
```"comparables":[{"id":1,"model":"table"},{"id":1,"model":"segment"},{"id":2,"model":"segment"},{"id":35,"model":"card"}```

What we currently consider for comparison:
* **Table**: all other tables with exactly the same fields -- "shards". For identity we consider the triplet :name, :base_type, :special_type; segments defined on any of these tables or the original table; cards showing raw data from any of these tables or the original table.
* **Segment**: same as for tables.
* **Cards**: same as for tables.
* **Fields**: all other fields of the same type in the same table.

### Discussion
* Would it be better to return the entire model object, rather than this paired down version?
* Should fields be comparable across table shards? My inclination is yes.
* Is exact type signature match for fields too restrictive? Would just matching :base_type be better?
* Should we follow FKs? My inclination is yes. If so, how many jumps/joins? Will too many options make the cumbersome?

**Comment by attekei** [comment]
> Would it be better to return the entire model object, rather than this paired down version?
Would be helpful if at least the names of models would be included for the comparison buttons. Currently I have to fetch lots of unnecessary metadata in order to show those.

If the overhead of including the returning the entire model object is small (in terms of the size of API response), then would be nice to include it as well.

**Comment by sbelak** [comment]
Changed so that a list of model objects with all the metadata is returned.

**Comment by attekei** [comment]
Ready for review!

**Comment by salsakran** [comment]
if there aren't segments we shouldn't show the comparison widget, eg I see this for many tables
screen shot 2017-10-19 at 11 45 17 am

**Comment by attekei** [comment]
Added support for arbitrary comparisons (now the model types of first and second compared entities aren't in a restricted order) and added support for comparing raw data questions with each other / with other kinds of models.

Still waiting tests to pass (there was a merge conflict once again) and will merge after that.

**Pull request merged**
