### PR TITLE
Optional symmetric encryption for DB details (AES256 CBC + HMAC SHA512)

### PR DESCRIPTION
**Pull request by camsaul**
This was easy to implement so I don't know why I waited so long to do it. Implements #865

Here's the basic idea:

### Part 1: Huh?

Pass `MB_ENCRYPTION_SECRET_KEY` env var to Metabase. This secret key can be whatever you want! 😻 

```bash
MB_ENCRYPTION_SECRET_KEY='WowILoveToucans' lein ring server
```

Then Metabase will log a sweet message letting you know encryption is g2g when you launch:

screen shot 2017-02-08 at 7 12 09 pm

And that's *all you have to do*. Wow.

DB details are completely transparent to application:

```clojure
(toucan.db/select-one-field :details 'Database :engine "postgres")
;; -> {:host "localhost", :port 5432, :dbname "test-data", :user "camsaul", :password nil, :ssl false}
```

But they're encrypted in the database:

```clojure
(jdbc/query (toucan.db/connection) 
  "SELECT details FROM metabase_database WHERE engine = 'postgres' LIMIT 1;")
;; -> ({:details "ae98856ee4b0e6210d8833678f931b4fa88dbef585b6d81266947f7eaff8440d0331d28dfbc542195c7bcdcace3cf18748cd871568f04c85e7c9df6abc96b11a8216dc04049c2c1cb16676200d680e9ad74804f6fb63d3fb354dd4980a4dc7a9a43b4ed3af920231f3fd5ea3180e7e099f1579e5f3421b092b628c78215655bda391141827795e22153870ebf9b3652189263d8b81a48f3f3969e04fea2b22c8"})
```

So if someone ever steals your Metabase DB, they won't know what's Gucci. #WOW 🙀 

### Part 2: How it all works?

1.  When Metabase launches, the secret key is hashed using ~~SHA-512~~ 100,000 iterations of PBKDF2+SHA-512

Using [Toucan](https://github.com/metabase/metabase/)'s powerful type system, whenever DB details are saved, we:

1.  generate an initialization vector (IV) of 16 cryptographically-secure random bytes
1.  serialize the DB details as a JSON string
1.  encrypt the string using IV + hashed secret key
1.  calculate a SHA-512 HMAC tag using IV, hashed secret key, and encrypted string
1.  encode (IV + encrypted string + tag) bytes as ~~hex~~ Base-64
1.  store in DB
1.  profit 💰 

When something is fetched from the DB:

1.  decode ~~hex~~ Base-64 -> bytes
1.  split into IV, encrypted message, and tag
1.  verify the tag using HMAC, secret key
1.  decrypt message w/ IV and secret key
1.  parse as JSON
1.  profit 💰 

This is backwards-compatible with unencrypted DB details, and includes some light TTL caching to prevent your computer from exploding by decrypting DB details (somewhat expensive) every time a query is ran. Nice 😎 

### Part 3: Next Steps

If we like this approach, we should do the following:

*  Add a few tests for this (should be pretty simple, we can have one of the test nodes use encryption)
*  Write some documentation about how to use this

### CODE REVIEW

**Comment by camsaul** [comment]
Other things could potentially be encrypted this way as well, such as SMTP settings (#1148)

**Comment by tlrobinson** [comment]
Cool. Should we use a KDF in case the admin chooses a not-very-secure key like "WowILoveToucans"?

**Comment by camsaul** [comment]
@tlrobinson see the description. We're hashing the secret key with SHA-512 to derive a longer key that is actually used to encrypt the data, so there's your KDF. But you are correct that "WowILoveToucans" is a bad secret key to begin with so our documentation should use a better example.

**Comment by tlrobinson** [comment]
@camsaul I meant a key stretching KDF like PBKDF2. But I'm fine just documenting a recommended way to generate a secret (`openssl rand -base64 32` or whatever)

**Comment by camsaul** [comment]
Yeah. It's probably not a bad idea to use something slow like `PBKDF2` to hash the OG secret key instead of `SHA-512`, I'll look into switching the impl

**Comment by VikramTiwari** [comment]
Inception case:

If I add my Metabase's database as a data source database in the UI, how will that work? Will I be able to see any data or will it all be encrypted?

Also, is this just for connection strings and such specifics or the complete database itself.

**Comment by camsaul** [comment]
@VikramTiwari this will not encrypt your database. Metabase doesn't do anything with your data except figure out what's there and give you ways to look at it. This is about encrypting the connection details for your database so someone wouldn't be able to see them if they got access to your Metabase DB. 

Inception! 🔮

**Comment by camsaul** [comment]
Ok, I've switched to using 100,000 iterations of  PBKDF2+SHA-512 as a KDF for the initial secret key. A single iteration takes about ~160ms on my laptop vs ~95 µs for plain SHA-512. I've also added a 16-character secret key minimum requirement. (Fortunately this hash only has to be done once at launch time)

So if you were to do something like `openssl rand -base64 16` to generate the secret key there would be 7.9e28 possible combinations, and if you were able generate hashes them with a setup a trillion times as fast as my laptop it would take ~400 million years to brute force the original secret key. But that assumes you have the hashed secret key in the first place, which you wouldn't have anyway, because we're not storing it. Bam! 😎

**Comment by amanoske** [comment]
Piping in as request from Sameer -- looks pretty good! Key things to think about though:

- What's the process for relaying this in transit to your DB? I see you're using openssl for the crypto heavy lifting, but are you also using it for the channel?

- Is it possible for you to zero out DB details in memory or do something similar? Crypto geeks are really going want this - i.e.: declaring the DB details as volatile + calling System/gc to force the garbage collector into action ASAP when you're done using them. Just like with Java there are potentially serious performance issues with this approach if it were done incorrectly.

**Comment by camsaul** [comment]
@amanoske 

*  Metabase can be configured to connect to its application DB with or without SSL. We primarily use non-SSL connections for development and of course heavily recommend SSL for production use, but ultimately it's up the admin that sets up a given Metabase instance.
*  I think zeroing out the memory would be a pretty tricky task. We're using C3P0 for DB connection pooling and I AFAIK it caches DB connection details in case it needs to open additional connections to a given DB, so we'd have to figure out how to deal with that, amongst other things. I think it makes sense to address that at some point in the future as a follow-on to this PR

**Comment by camsaul** [comment]
BTW @metabase/core-developers I switched this from storing the encrypted bytes as Base-64 instead of hex to save a little space and added a few unit tests as well. I've set up CI node 2 to use DB details encryption and looks like tests are passing there.

**Comment by camsaul** [comment]
So the only thing left I think is documentation

**Comment by salsakran** [comment]
What happens if I run it with encryption, and then forget to inject the key?

Can we store a (read-only) setting that the server has encrypted sensitive credentials and if it starts up again without a key, throw an error?

The failure mode here would be very confusing (all db calls would barf, but no error would reflect why)

**Comment by camsaul** [comment]
If you run it again without encryption the JSON parsing will fail and throw tons of exceptions (I've verified this)

There would be an error message, but it wouldn't be 100% clear, so I can do something like you're suggesting

**Comment by salsakran** [comment]
Question:
If I've done that (run in encrypted mode), forgot the password, should there be a way to recover the rest of the metadata? eg, start up, and allow the user to enter new credentials?

I.e. should this be an explicit error message or a barf + exit?

I dread the support load of the latter option.

**Comment by camsaul** [comment]
@salsakran that's the point of encrypting these details -- so you can't see them without the secret key. So we should try to make it clear to people that they should be careful not to lose the key.

That being said you should be able to go update the credentials in the admin panel and things should be back to normal if you switch the key.

**Comment by salsakran** [comment]
yup, the specific flow I had in mind in the former case was:

1. I've encrypted things and am a good tidy admin
2. I messed up chef env injection and lost the keys
3. Metabase helpfully lets me know that ThingsWentWrong
4. I can nuke the previously set credentials, and replace them with the actual database creds which being a tidy admin I have in a key manager or somesuch.

vs. the second "barf+exit" option where

3*. Metabase refuses to startup without keys
4*. I freak out and try to migrate everything but the keys to a new application database
4a*. I mess it up
4b*. I email every @metabase address I can find and plead for help
4c*. I run away to the countryside and raise alpacas instead.

**Comment by camsaul** [comment]
Yeah. I'll have it do the former. For (3) I'll just have it log some error messages about what went wrong

**Comment by salsakran** [comment]
Is it possible to use the admin checklist to surface critical "fix this now" errors like this? (separate PR, paging @kdoh)

**Comment by camsaul** [comment]
@salsakran I think that would be tricky to do since we won't know as soon until you try to use a DB that the details are encrypted in a bad way. We don't validate details for every DB at launch

**Comment by kdoh** [comment]
We certainly could. We'd want a critical flag or something similar so we could change the style and help people understand that certain conditions aren't a suggestion.

**Comment by salsakran** [comment]
so this PR is 👍 , but think that would be a really good touch of polish, and in general I think things like 
* you DW creds don't work
* your email cred don't work
* slack decided this is the week your api keys are weird and will error our
etc
 would be things to notify an administrator of. All of them could happen at instance startup (or really any time), and it would be cool to pipe them through.

**Comment by camsaul** [comment]
Polish like that would be nice, but I maybe it makes sense to address that whole set of desired errors to surface to the admin as a separate PR. Right now those things are just logged to the console and I don't want to drag unrelated things into this PR

**Comment by salsakran** [comment]
Yup, as I noted "this PR is 👍 "
Out of scope for this specific thing, and captured in #4350

**Comment by camsaul** [comment]
Ok. I have everything set up to give you a nice error message in the logs and confirmed I was able to go reset my DB details for encrypted DBs after changing the secret without breaking anything

**Comment by camsaul** [comment]
Should I add dox about this or is anyone else interested 😉 ⁉️

**Comment by camsaul** [comment]
I have also added the first Metabase test checks the output of the logs. 😎

**Pull request merged**
