### PR TITLE
Upgrade Cypress to v5.3.0

### LINKED ISSUE #13337: Upgrade Cypress to the latest version
**Is your feature request related to a problem? Please describe.**
We're currently using Cypress v3.8.2 (2 major versions behind the latest one).

**Describe the solution you'd like**
- upgrade Cypress to 5.3.0

_Additionally we should consider upgrading:_
    - `@testing-library/cypress` to the latest version (5.0.2 -> 7.0.1)
    - `@testing-library/jest-dom` to the latest version (4.0.0 -> 5.11.4)
    - `@cypress/webpack-preprocessor` to the latest version (4.1.0 -> 5.4.6)

NOTE: Cypress webpack preprocessor **already** has incorrect dependency
```bash
warning " > @cypress/webpack-preprocessor@4.1.0" has incorrect peer dependency "webpack@^4.18.1".
```
which means we should also upgrade webpack (currently v3.8.1). This will touch a lot of code, so I'd be extremely careful with that. 

**How important is this feature to you?**
We're missing out on some nice features in the latest release.
- [Test retries](https://docs.cypress.io/guides/guides/test-retries.html#Introduction) (which could help temporarily with some of the flakes)
- Firefox support is out of beta (5.3)
- full support for shadow DOM (5.2)
- [...more](https://docs.cypress.io/guides/references/changelog.html)

**Additional context**
- https://docs.cypress.io/guides/references/migration-guide.html
- https://github.com/testing-library/cypress-testing-library/releases

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
READY

### What does this PR accomplish?
- [x] upgrades Cypress to the latest version (v5.3.0)
- [x] closes #13337

### Additional notes:
- I'm opening this PR early on intentionally (it will help to see how CI reacts to the changes in each commit, does something break etc.)

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]
Looks good! Nice job working through the version conflicts 🎉

**Comment by nemanjaglumac** [comment]
@dacort - before we close it, I can eventually set up and include [test retries](https://docs.cypress.io/guides/guides/test-retries.html#Introduction) in this PR? Do we go for `2` or `3` retries in "run" mode? I'd leave `0` for "open" mode. What do you think?

```javascript
{
  "retries": {
    // Configure retry attempts for `cypress run`
    // Default is 0
    "runMode": 2,
    // Configure retry attempts for `cypress open`
    // Default is 0
    "openMode": 0
  }
}
```

**Comment by dacort** [comment]
> Do we go for `2` or `3` retries in "run" mode? I'd leave `0` for "open" mode. What do you think?

@nemanjaglumac Let's go for `2` and `0` is 👍 for "open" mode.

**Review by dacort — APPROVED** [review]
Looks good! Ran through the smoketests as well - while some failed in Firefox, all but one passed in Chrome. That one required a minor change that I'll open a new PR for.

**Pull request merged**
