### PR TITLE
X-ray copy tweaks

### PR DESCRIPTION
**Pull request by sbelak**
Makes cell copy much more sensible also slightly tweaks copy elsewhere.

Is there any point in the inline filter gadget if it's already part of the title?

### CODE REVIEW

**Comment by sbelak** [comment]
GenericTable is still crap: 
screenshot 2018-06-21 18 52 48

**Comment by sbelak** [comment]
Also segment titles are a bit of a mouthful. Can we shorten them to "such X" or some such?
screenshot 2018-06-21 19 01 36

**Comment by sbelak** [comment]
Fixed GenericTable and segments.

**Comment by mazameli** [comment]
Just pushed a commit with a bunch of small tweaks and fixes to the things that I was able to figure out how to change. Here are the other things I wasn't able to change:

1. The one contentious thing that remains: @salsakran seemed to feel pretty strongly that x-rays on cells of an aggregation (average of subtotal over time) should include the name of the aggregation in the title. So it's awesome that they now have the filter values in the title, and it's also awesome that the various _card_ titles are correctly name to communicate in cases where they're about the count of rows of the table rather than about the aggregation — but I think we still expect e.g. if I x-ray a cell in "the average of subtotal by created at" I'd see an x-ray with a title like "A look at the average of subtotal where Created At is January, 2018."
2. It used to be that for tables, we'd drop the word `table` when referencing them in titles of x-rays or cards. It seems like we stopped doing that specifically for special table types like UserTable and TransactionTable, resulting in undesirable titles like `New People table per month`. 
3. When x-raying a cell in an ad hoc aggregated question based on the People table, I'm seeing weird section and card titles like this: `New count of PEOPLE by Created At per month`. It seems like the `short-title` for this specific table type is wrong? I'm seeing this for the Orders table, too, e.g. when x-raying a whole saved question based on it: `Count of ORDERS metric over time`
4. Is there a way to make sub-section headings smaller than section headings? If you point me to where it's happening in the code, I can mess around with it. Example:

screen shot 2018-06-25 at 5 02 44 pm

- FYI, for cell x-rays, I changed the usage of "such" to "these," so it's like "How these Products are distributed," instead of "How such Products are distributed." It's less formal sounding now.

**Comment by sbelak** [comment]
1) I think there is a tension between two intentions when using cells. Sometimes you are focused on the metric (eg "I want to know more about _income_ from Texas"), other times on the dimension ("I want to know more about transactions in Texas"). Not sure if we can cover both of these with the same mechanism. But for the time being I changed the titles. I've also changed what is shown in a cell x-ray as too much context was lost if we continued to base them off table x-rays (I still thing "my" version reflects the contents better, but I do acknowledge that the contents is not yet ideal).

2) I think it only happened in Users as the attribute name was wrong there (short-title instead of short-name). Fixed

3) Users is same as 2). For the rest, what should it say? The metric is "count of Orders" so we say "count of orders metric". (ORDERS being all caps is wrong of course -- fixed)

4) This is an artefact of combining multiple dashboards into one so you can't change those sizes automatically. I've added a function that downsizes titles when merging dashboards. See if it looks ok to you.

*these/such*) on further reflection I think both are problematic as it will break in i18n in any language that has gendered prepositions (eg. German, any Slavic language, ...). I've dropped prepending "these" automatically and tweaked the heuristics a bit to minimize their usage.

**Comment by mazameli** [comment]
Things are looking much better to me now, and I think we should merge this after resolving one issue I found (and once tests are passing of course): if I x-ray an ad hoc scalar question, I get e.g. `Here's a closer look at your sum of Subtotal by null`

-----

**After** we merge this, I think we can address this question you asked: "Is there any point in the inline filter gadget if it's already part of the title?"

If we wanted to try getting rid of the filter gadget, we'd have to:
1. Make sure we're including _all_ filters in the title, which we're not currently doing. (This could be due to the issue I mentioned in Slack about how additional filters don't appear to be getting correctly applied to cell/drill-through x-rays.)
2. Currently the gadget is also showing the filters used to define a segment, so we would also have to come up with a better and clearer way of explaining the definition of segments, which we'd talked about doing anyway in the context of making segment vs. table comparisons more understandable.

I will explore #2 in the context of improving comparison x-rays, which I'm planning on looking at in depth this afternoon.

**Comment by sbelak** [comment]
The null thing should be fixed in 9e9744a. Can you confirm with the latest?

**Comment by mazameli** [comment]
1. Looks like that "null" issue for scalar x-rays is fixed 👌 

---

2. We already talked about this in Slack earlier today, but let's drop the word “metric” in cases where it’s just a basic sum of subtotal, count of table, etc. (e.g. just “A look at the average of Subtotal”), but to keep the word “metric” if I’m x-raying an _official_ metric (e.g. “A look at the Revenue metric”).

---

3. If I'm looking at an x-ray and I then do a subsequent cell x-ray on a chart in the first x-ray, the title doesn't include all the filters; only the last one that was added:

screen shot 2018-06-29 at 2 06 45 pm

---- 

4. When doing a cell x-ray on a chart broken out by date, if the granularity is anything other than "day," the title gets it wrong. 

screen shot 2018-06-29 at 1 58 35 pm

screen shot 2018-06-29 at 1 57 04 pm

screen shot 2018-06-29 at 12 48 32 pm

For these date filter titles, I would expect:
-- "…where Created At is 2018" for year
-- "…where Created At is Q2, 2018" for quarters
-- "…where Created At is April, 2018," for months
-- "…where Created At is April 22–28, 2018" for weeks (if that's not possible/easy, then "Created At is week 18, ")
-- Days are good
-- "…where Created At is 6 PM, January 5, 2019" for hours
-- "…where Created At is Monday, March 20, 2017 3:32 PM" for minutes

I might as well be really thorough:
-- "…where Created At is the 30th minute of the hour"
-- "…where Created At is 11 AM"
-- "…where Created at is on Thursdays"
-- "…where Created At is the 31st day of the month"
-- "…where Created at is the 169th day of the year"
-- "…where Created At is the 14th week of the year"
-- "…where Created At is June"
-- "…where Created At is during Q1"

**Comment by sbelak** [comment]
re 3: are we sure we want all the filters stuffed in there (I suppose this is related to the filter gadget question above)?

**Comment by mazameli** [comment]
> re 3: are we sure we want all the filters stuffed in there (I suppose this is related to the filter gadget question above)?

Let me spend maybe 30 minutes today playing with things and thinking through that, and then let's close this out.

**Comment by sbelak** [comment]
fixed 2

**Comment by mazameli** [comment]
Okay, so looking at it again, I think how we're treating filters right now makes a fair bit of sense, i.e.:
- the title includes the filter(s) generated from the "most recent" x-ray
- all of the applied filters are present below the title in the smaller labels

Yes, the filter labels can sometimes be redundant with the title, but I like that they're scannable and that when multiple filters are applied that the labels tell the complete story of what you're looking at. And yeah, trying to stuff _all_ the filters into just the title sounds heinous.

So from my perspective, all that's left is fixing the way we're treating date filters in titles.

**Comment by sbelak** [comment]
4 done

**Comment by mazameli** [comment]
When I try to x-ray a bar in a day-of-month chart, I get this error: `No matching clause: :day-of-month`

screen shot 2018-07-05 at 10 41 13 am

Server logs:

```
07-05 10:41:25 ERROR metabase.middleware :: GET /api/automagic-dashboards/adhoc/eyJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6MSwicXVlcnkiOnsic291cmNlX3RhYmxlIjoxLCJicmVha291dCI6W1siZGF0ZXRpbWUtZmllbGQiLFsiZmllbGQtaWQiLDddLCJkYXktb2YtbW9udGgiXV0sImFnZ3JlZ2F0aW9uIjpbWyJzdW0iLFsiZmllbGQtaWQiLDNdXV19fQ==/cell/WyI9IixbImRhdGV0aW1lLWZpZWxkIixbImZpZWxkLWlkIiw3XSwiYXMiLCJkYXktb2YtbW9udGgiXSwiMjAxNi0wMS0wM1QwMDowMDowMC0wODowMCJd 500 (82 ms) (53 DB calls).
{:message "No matching clause: :day-of-month",
 :type java.lang.IllegalArgumentException,
 :stacktrace
 ["automagic_dashboards.core$humanize_datetime.invokeStatic(core.clj:911)"
  "automagic_dashboards.core$humanize_datetime.invoke(core.clj:906)"
  "automagic_dashboards.core$eval54727$fn__54729.invoke(core.clj:962)"
  "automagic_dashboards.core$cell_title.invokeStatic(core.clj:985)"
  "automagic_dashboards.core$cell_title.invoke(core.clj:981)"
  "automagic_dashboards.core$eval54770$fn__54772.invoke(core.clj:1029)"
  "api.automagic_dashboards$fn__54858.invokeStatic(automagic_dashboards.clj:201)"
  "api.automagic_dashboards$fn__54858.invoke(automagic_dashboards.clj:190)"
  "middleware$enforce_authentication$fn__50021.invoke(middleware.clj:116)"
  "api.routes$fn__61831.invokeStatic(routes.clj:61)"
  "api.routes$fn__61831.invoke(routes.clj:61)"
  "routes$fn__61924$fn__61925.doInvoke(routes.clj:108)"
  "routes$fn__61924.invokeStatic(routes.clj:103)"
  "routes$fn__61924.invoke(routes.clj:103)"
  "middleware$catch_api_exceptions$fn__50163.invoke(middleware.clj:419)"
  "middleware$log_api_call$fn__50141$fn__50143.invoke(middleware.clj:350)"
  "middleware$log_api_call$fn__50141.invoke(middleware.clj:349)"
  "middleware$add_security_headers$fn__50075.invoke(middleware.clj:252)"
  "core$wrap_streamed_json_response$fn__62969.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__50026.invoke(middleware.clj:140)"
  "middleware$maybe_set_site_url$fn__50079.invoke(middleware.clj:276)"]}
```

**Comment by mazameli** [comment]
X-raying a bar in a per-day-of-the-week chart gives me `can't parse argument number:`

screen shot 2018-07-05 at 10 43 55 am


```
07-05 10:43:26 ERROR metabase.middleware :: GET /api/automagic-dashboards/adhoc/eyJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6MSwicXVlcnkiOnsic291cmNlX3RhYmxlIjoxLCJicmVha291dCI6W1siZGF0ZXRpbWUtZmllbGQiLFsiZmllbGQtaWQiLDddLCJkYXktb2Ytd2VlayJdXSwiYWdncmVnYXRpb24iOltbInN1bSIsWyJmaWVsZC1pZCIsM11dXX19/cell/WyI9IixbImRhdGV0aW1lLWZpZWxkIixbImZpZWxkLWlkIiw3XSwiYXMiLCJkYXktb2Ytd2VlayJdLCIyMDE4LTA3LTA2VDAwOjAwOjAwLTA3OjAwIl0= 500 (85 ms) (53 DB calls).
{:message "can't parse argument number: ",
 :type java.lang.IllegalArgumentException,
 :stacktrace
 ["automagic_dashboards.core$humanize_datetime.invokeStatic(core.clj:920)"
  "automagic_dashboards.core$humanize_datetime.invoke(core.clj:906)"
  "automagic_dashboards.core$eval54727$fn__54729.invoke(core.clj:962)"
  "automagic_dashboards.core$cell_title.invokeStatic(core.clj:985)"
  "automagic_dashboards.core$cell_title.invoke(core.clj:981)"
  "automagic_dashboards.core$eval54770$fn__54772.invoke(core.clj:1029)"
  "api.automagic_dashboards$fn__54858.invokeStatic(automagic_dashboards.clj:201)"
  "api.automagic_dashboards$fn__54858.invoke(automagic_dashboards.clj:190)"
  "middleware$enforce_authentication$fn__50021.invoke(middleware.clj:116)"
  "api.routes$fn__61831.invokeStatic(routes.clj:61)"
  "api.routes$fn__61831.invoke(routes.clj:61)"
  "routes$fn__61924$fn__61925.doInvoke(routes.clj:108)"
  "routes$fn__61924.invokeStatic(routes.clj:103)"
  "routes$fn__61924.invoke(routes.clj:103)"
  "middleware$catch_api_exceptions$fn__50163.invoke(middleware.clj:419)"
  "middleware$log_api_call$fn__50141$fn__50143.invoke(middleware.clj:350)"
  "middleware$log_api_call$fn__50141.invoke(middleware.clj:349)"
  "middleware$add_security_headers$fn__50075.invoke(middleware.clj:252)"
  "core$wrap_streamed_json_response$fn__62969.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__50026.invoke(middleware.clj:140)"
  "middleware$maybe_set_site_url$fn__50079.invoke(middleware.clj:276)"]}
```

**Comment by mazameli** [comment]
It would be great if the values of the filters in these titles could be humanized the way they are in the filter widget: `3 PM` instead of `22`, `June` instead of `6`, `Q1` instead of `1`.

screen shot 2018-07-05 at 10 46 13 am
screen shot 2018-07-05 at 10 44 57 am
screen shot 2018-07-05 at 10 42 28 am

**Comment by mazameli** [comment]
Double `of` here:

of of

**Comment by mazameli** [comment]
Looks like x-rays of time series with by-minute or by-hour granularity have the hour wrong (compare it to the value in the filter widgets).

screen shot 2018-07-05 at 11 31 25 am

screen shot 2018-07-05 at 11 32 37 am

**Comment by mazameli** [comment]
Similar to the day-of-the-week error I mentioned above, trying to x-ray a bar/dot in a time series with by-week granularity results in `No matching clause: :week`

screen shot 2018-07-05 at 11 43 13 am

**Comment by sbelak** [comment]
Fixed everything aside from the TZ issues.

**Comment by mazameli** [comment]
Hmm I'm still getting errors:
- `Assert failed: (or (not (string? coercible-to-ts)) (and (string? coercible-to-ts) (bound? (var *report-timezone*))))` when it's day-of-month
- `No matching clause: :day-of-year` when trying to x-ray a bar on a graph broken out by day-of-year.
- `Assert failed: (or (not (string? coercible-to-ts)) (and (string? coercible-to-ts) (bound? (var *report-timezone*))))` when it's broken out by week-of-year
- `Assert failed: (or (not (string? coercible-to-ts)) (and (string? coercible-to-ts) (bound? (var *report-timezone*))))` when it's quarter-of-year
- `Assert failed: (or (not (string? coercible-to-ts)) (and (string? coercible-to-ts) (bound? (var *report-timezone*))))` when it's by week
- `Assert failed: (or (not (string? coercible-to-ts)) (and (string? coercible-to-ts) (bound? (var *report-timezone*))))` when it's by quarter
- `Assert failed: (or (not (string? coercible-to-ts)) (and (string? coercible-to-ts) (bound? (var *report-timezone*))))` when it's minute-of-hour

**Comment by sbelak** [comment]
Sigh. Fixed + ample tests

**Comment by mazameli** [comment]
Nice. Everything looks right and fixed except `Day of year` is still broken: `No matching clause: :day-of-year`

Once that's fixed and this is passing tests let's get a code review and merge this today, yeah?

**Comment by sbelak** [comment]
Added

**Review by mazameli — APPROVED** [review]
This is good to go from my end.

**Comment by mazameli** [comment]
Have you reviewed this, @salsakran? I think it's ready to merge.

**Comment by salsakran** [comment]
the section headings are cool, but imo the "A look at" is overused

**Comment by salsakran** [comment]
screen shot 2018-07-09 at 5 29 25 pm

kinda verbose, and the number of preceding words is burying the lede in this screenshot

**Comment by salsakran** [comment]
`The top and bottom for the count of Orders` is a little vauge

**Comment by mazameli** [comment]
@salsakran, I pushed some changes:

`Number` instead of `Count` in titles and elsewhere:

screen shot 2018-07-10 at 10 29 40 am

Less verbose distribution titles:

screen shot 2018-07-10 at 10 29 34 am

I tried breaking up the top and bottom 5 into separate sections to make it easier to parse and describe:

screen shot 2018-07-10 at 10 42 50 am

**Pull request merged**
