### PR TITLE
support a more diverse set of timezones.

### PR DESCRIPTION
**Pull request by agilliland**
implements #1667

### CODE REVIEW

**Comment by maliayas** [comment]
Would you mind adding `Europe/Istanbul` as well please?

**Comment by agilliland** [comment]
Europe/Helsinki is the same timezone as Instanbul

**Comment by maliayas** [comment]
But there are special cases based on countries/cities one of which is DST. Hence the named timezones instead of numeric UTC offset.

**Comment by camsaul** [comment]
@maliayas DST is indeed a good reason to include `Europe/Istanbul` separately, if you want to submit a PR adding it I'll be happy to include it 👍

**Pull request merged**
