### PR TITLE
Rewrite TokenInput by deleting it 

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to #14878

WIP PR. Need to add:
1. Syntax highlighting DSL stuff
2. Style it so that it looks exactly like previous
3. Rewrite tests involved

but Ace will tokenize for us, even though it doesn't look that way at first

### CODE REVIEW

**Comment by ariya** [comment]
I can't seem to edit the expression (inside that Ace editor). Am I missing something?

**Comment by howonlee** [comment]
Should be drop in replacement. Can you give console output?

**Comment by ariya** [comment]
@howonlee Can you change the target PR to the [0.40-rewritten-expression-editor ](https://github.com/metabase/metabase/tree/0.40-rewritten-expression-editor) branch?

After that, and once there are few linter fixes, we should merge this first step.

**Comment by howonlee** [comment]
this force push is not agreeing with me because I merged master onto this one previously....

**Comment by ariya** [comment]
> this force push is not agreeing with me because I merged master onto this one previously....

Try to rebase it. Right now there's a bunch of other unrelated commits (and changes) in this PR.

**Comment by howonlee** [comment]
current things:
- breaks some cypress tests, down from "all tests" previously
- breaks syntax highlighting

all the other stuff, I think I fixed

**Comment by howonlee** [comment]
OK, so the root cause of the mode import being terrible is that, because ace has its own commonjs-style require thing, and its own entire implementation of oop and you need to inherit from ABC's to instantiate the mode, it really does have to be imported via commonjs-style imports. The trouble with this is that it mixes absolutely terribly with es6-style imports in the entire rest of the codebase.

Actually, after trawling through their source, it seems what they intend for you to do is to add new modes to a specific directory in their source. I am giving serious thought to literally doing that.

**Pull request merged**
