### PR TITLE
update prettier for Typescript

### PR DESCRIPTION
**Pull request by alxnddr**
We need to upgrade prettier to support Typescript optional chaining operator and more. To minimize changes, I upgraded to the next minor version `1.19.1`. It still emits some reformatting which is not configurable according to [docs](https://github.com/prettier/prettier/blob/95b8e54d1a6eeabebd81db37a4e088ea1de9197d/docs/options.md)

In order to keep automatic backports working I backported this PR to `release-x.41.x` branch [here](https://github.com/metabase/metabase/pull/19062)

### CODE REVIEW

**Comment by ariya** [comment]
> Upgrading to `1.19.1` emits a lot of changes in formatting, so I decided to upgrade to the latest version and to add [prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports) because I remember recently I saw PRs about it from @gusaiani.

So the reason to lump these two changes is because the PR is going to change so many files anyway?

**Comment by alxnddr** [comment]
> So the reason to lump these two changes is because the PR is going to change so many files anyway?
It was the reason to upgrade to the next major version which emits even more changes. I can split sorting imports in a separate PR

**Comment by kulyk** [comment]
@alxnddr what do you think if we update the prettier config here to match our current style guide, so the diff is not that huge? I'm worried it can break backporting. I'd vote for updating the imports in a separate PR too.

As a side note, should we maybe do major code style updates before major releases? Changes like this shouldn't be too risky. In this way, we can safely update the code style, roll out a release with updated code style and that later backport bug fixes without conflicts too

**Comment by alxnddr** [comment]
@kulyk, unfortunately, prettier is not that configurable, and I configured what was possible to match our current style guide, and it still emitted tons of changes.
I updated the branch to use just the next minor version `1.19.1`, which supports Typescript optional chaining. There is still a concern about breaking backports. 

Another thing I have on my mind is to disable prettier for `ts` files for now so that we can use its syntax and run the upgraded prettier right before the release, as you suggested. Wdyt @kulyk @ariya?

**Comment by ranquild** [comment]
> The only thing I'm afraid of is that it may lead to issues with automatic backports due to conflicts.

You can solve that by backporting these changes and manually resolving conflicts.

**Comment by kulyk** [comment]
> You can solve that by backporting formatting changes and manually resolving conflicts.

'm worried there is a big risk of accidentally breaking something on the release

**Review by ranquild — APPROVED** [review]
@alxnddr Looks good, please manually backport the changes. Probably the best way would be just to rerun prettier on the release branch.

**Pull request merged**
