### PR TITLE
Sync bin/start with metabase-deploy repo

### PR DESCRIPTION
**Pull request by tlrobinson**
We should keep these in sync.

### CODE REVIEW

**Comment by agilliland** [comment]
hmmm, i'm less certain about applying those settings here.  those settings feel like they are specific to Heroku but this bin/start script is used in a lot of scenarios outside of Heroku

**Comment by tlrobinson** [comment]
This repo is also deployable to Heroku.

**Comment by agilliland** [comment]
Yeah, I understand that, what I mean is that the logic in that script doesn't look like it will work properly on non-Heroku systems.  for example, on my MBP `ulimit -u` gives an output of 709 which would put it in the lowest class of memory in that script and that doesn't make a ton of sense.

i believe those memory values are specific to running on Heroku.

**Comment by tlrobinson** [comment]
Ok, we should be able to remove this code from both repos now that we're using the JVM buildbpack anyway, right?

**Comment by agilliland** [comment]
I'm fine with that.  We've never actually used this code in the main repo since we've always been using the clojure buildpack (which uses the jvm buildpack).  I'm not sure there have ever been any memory issues reported against that deployment setup.

In the `metabase-deploy` repo where we were using the null buildpack is where i believe we were getting the problems.  I'm happy to try removing this code and just relying on the jvm buildpack to establish sensible memory settings.

**Pull request merged**
