### PR TITLE
Add collection_preview field to report_card table

### PR DESCRIPTION
**Pull request by metamben**
This is the new Card field (`collection_preview`) part of the backend part of milestone 1 of #23222.

### CODE REVIEW

**Review by dpsutton — APPROVED** [review]
approving but with hope you'll strip off the property where it does not apply

**Comment by RubensRafael** [comment]
Hi @metamben, Can you help me?
I'm trying to create a new column in the core_users table, (it's a boolean), it's very similar to the changeSet of this PR, but I can't make these changes actually take effect, which command should I run to get it do that?

And I have another question, how do I find the #migrations channel from Metabase in Slack, so I can add the id correctly?

**Comment by metamben** [comment]
@RubensRafael Read the [docu about migrations](https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-migrations-manually.md) first. If you have to do something unusual, you can use `clojure -M:liquibase` to execute [the liquibase Main class](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/integration/commandline/Main.java), it's liquibase that's processing change sets.

I'm not sure if you can access the `#migrations` channel. @flamber How can people contribute changes with new migrations?

**Comment by flamber** [comment]
Our Slack is only for internal use. If someone creates a third-party PR, then when a Metabase member reviews it, they will claim migration numbers and provide those.

**Comment by RubensRafael** [comment]
> Our Slack is only for internal use. If someone creates a third-party PR, then when a Metabase member reviews it, they will claim migration numbers and provide those.

I don't know if this is relevant, but I contribute from GitStart fork. Does that make any difference?

**Comment by metamben** [comment]
> I don't know if this is relevant, but I contribute from GitStart fork. Does that make any difference?

I suppose it doesn't.

**Pull request merged**
