### PR TITLE
Fix 'Edit Settings' button in query builder

### PR DESCRIPTION
**Pull request by tlrobinson**
This fixes an error when clicking "Edit Settings" in the query builder for certain chart types, e.x. maps.

I thought there was an issue filed for it, but I can't find it.

### CODE REVIEW

**Comment by paulrosenzweig** [comment]
I opened a PR for this yesterday #10120. Sorry it's so cryptically titled!

Though, I think this fix is better, so I'll close mine.

**Review by paulrosenzweig — APPROVED** [review]

**Comment by paulrosenzweig** [comment]
I think it resolves this issue: https://github.com/metabase/metabase/issues/9346#issuecomment-458985874

Though the title doesn't really mention the general issue.

**Review by kdoh — COMMENTED** [review]
In general the `render` method of `ChartSettings` has a lot of conditional stuff going on that it'd be nice to have more test coverage on to prevent issues like this. Is there any easy test case we could add here to start to whittle away at that and prevent bugs like this or accidental regressions?

**Comment by tlrobinson** [comment]
@kdoh @paulrosenzweig Can you take a look at the tests I just added? I'm experimenting with `react-testing-library` which is an alternative to Enzyme etc that encourages not testing implementation details https://kentcdodds.com/blog/testing-implementation-details

**Comment by paulrosenzweig** [comment]
@tlrobinson I like the new tests! 

It's a great blog post too. This is a pretty sweet advantage of structuring tests this way:

> Oh, and React Hooks got you all excited? If you rewrite that accordion component to use React hooks, the enzyme test fails terribly, while the react-testing-library test continues to work.

**Comment by tlrobinson** [comment]
> @tlrobinson I like the new tests!
> 
> It's a great blog post too. This is a pretty sweet advantage of structuring tests this way:
> 
> > Oh, and React Hooks got you all excited? If you rewrite that accordion component to use React hooks, the enzyme test fails terribly, while the react-testing-library test continues to work.

Yeah, though we'll need to finally upgrade to React 16 to use hooks :)

**Pull request merged**
