### PR TITLE
Fix skinny time series bar charts

### LINKED ISSUE #1208: Bar charts show really skinny lines when the x-axis is a timeseries
Ran a query on the Orders table: Created At = last month, Sum of Subtotal by Created At: Week. Expected to see the sum of subtotals for each of the 4 weeks in the last month. 

I correctly saw this in the table and line/area views:
screen shot 2015-10-09 at 10 45 32 am

screen shot 2015-10-09 at 10 44 50 am

**But the bar chart only showed two of the weeks:** (I actually think it's rendering 3 — you can faintly see the first one abutting the y-axis — but you can't hover over it or really see it, making it useless)
screen shot 2015-10-09 at 10 45 26 am

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #1208

Works for everything except quarters, which D3 doesn't have support for.

Also, this might exacerbate #1257 since bars will now sometimes be too wide if the filter granularity is larger than the grouping granularity.

### CODE REVIEW

**Comment by salsakran** [comment]
:heart_eyes_cat:

**Comment by agilliland** [comment]
This is looking way better than all those silly skinny bars.  Seeing a few anomalies though ...

1. When I set a filter like "last month" i'm just getting a solid block of bars and something seems very out of place.

screen shot 2015-10-29 at 11 33 32 am

2. When doing weekly groupings for a single month the axis still feels a bit strange and the bars are fairly spread out.  Same issue is exacerbated more when there are fewer bars to display in the axis.  
Much better than before, but still not really what a user would expect ...

screen shot 2015-10-29 at 11 34 50 am

screen shot 2015-10-29 at 11 35 06 am

3. This starts to get more nit picky, but ideally the bars would center align over the ticks on the axis ...

screen shot 2015-10-29 at 11 35 44 am

**Comment by agilliland** [comment]
fixes #1406

**Comment by tlrobinson** [comment]
I believe the first 3 (any query with a date filter) are all due to #1257 which requires changes in the query processor, I assume.

**Comment by agilliland** [comment]
got it.  so we can leave those to be handled in a separate PR then.  how about #4, is it easy to tackle that now or should we file a separate issue?

**Comment by agilliland** [comment]
Just FYI, I'd like to resolve #1257 and test it out with this PR before merging.  In specific the first issue that i mentioned above which makes the chart look like a huge blue mess is pretty glaring, so I'd like to prevent that from happening.

**Comment by tlrobinson** [comment]
Ok I took a look at it awhile ago and I think it's a bit over my head, probably a job for @camsaul.

**Comment by agilliland** [comment]
@camsaul as Tom mentioned above it would be great if you could take a look at that issue and help us out with a fix.  I want to get that issue fixed before we merge this PR.

**Pull request merged**
