### PR TITLE
more generic color picker and collection colors

### PR DESCRIPTION
**Pull request by kdoh**
- provides a more diverse set of colors for collections and picks a random color from the set so that all collections won't end up being blue.

- allows a color set to be specified for the color picker component

### CODE REVIEW

**Comment by tlrobinson** [comment]
LGTM, any reason not to go ahead and use this in `ChartSettingColorPicker` as well?

**Comment by tlrobinson** [comment]
Also might be nice to add those colors to chart settings i.e. #3185

**Comment by kdoh** [comment]
@mazameli and I considered that. I think our main concern was that we haven't vetted this color set extensively enough to where we're confident it'll work in all charting contexts. I set things up so it'll be pretty easy to extend this to the defaults everywhere we have a color picker, but I'm not sure we want to pull the trigger on that just yet.

**Comment by tlrobinson** [comment]
Alright, but that doesn't prevent us from consolidating the color pickers, especially since `ColorPicker` defaults to the same colors as `ChartSettingColorPicker` now.

**Comment by kdoh** [comment]
Fair point. I can consolidate those as part of this.

**Comment by kdoh** [comment]
@tlrobinson If you want to give this another once over that'd be great.

**Review by tlrobinson — APPROVED** [review]

**Pull request merged**
