### PR TITLE
#6884 Repro: Dashboard revert fails for users with revert permissions

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Reproduces #6884

### How to test this manually?
- `yarn test-cypress-open --spec frontend/test/metabase/scenarios/collections/permissions.cy.spec.js`
- Replace `it.skip()` with `it.only()` to run the test in isolation
- The test should fail until the related issue is fixed

### Additional notes:
- Once the issue is fixed, please remove the `.skip` part (unskip the test completely)
- Make sure the test is passing and
- Merge it together with the fix

### Screenshots:
image

With the help of `onlyOn` function from `cypress-skip-test` library, we can now generate describe/context blocks, and tests conditionally while keeping everything neat and clean at the same time :)
- Please note that test wasn't even created for "view" and "no" access contexts":

image

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
@flamber I am planning on adding more tests to this file - both repros (such as https://github.com/metabase/metabase/issues/13229) and regular tests. I might even have an idea on how to create different contexts dynamically, but let's deal with this one first and then we'll build it up from here.

**Comment by flamber** [comment]
@nemanjaglumac Okay, so it's not ready for review? From what I can see, it's not testing how the dashboard can end up in a strange (partially corrupted) state, when reverting to some of the histories.

**Comment by nemanjaglumac** [comment]
I don't know what is corrupted state ofthe dashboard. What @mazameli was describing when the card gets really tiny seems correct to me - that happens in the step in which the card was added. Unfortunately, we add really tiny cards by default (something like 2x2). We can address that, but it is a separate issue.

What other "corruption" is there on the dashboard that I might have missed?

**Comment by flamber** [comment]
@nemanjaglumac You cannot have 2x2 charts. Minimum is 4x3. I have updated the issue with steps https://github.com/metabase/metabase/issues/6884#issuecomment-801943890

**Comment by nemanjaglumac** [comment]
@flamber thanks for an update. Really helpful 🙏

If you agree, I'd still treat this as two separate issues. One thing is that the revert button completely fails for some occasions, and the other/separate one is when you succeed to revert but then strange UI things happen.

I can open a separate issue for button that fails, just to keep track?

**Comment by flamber** [comment]
They are very much related, since it's likely caused by too many steps being recorded and saved, but not every step can be reverted, since it might not contain all the information it needs. But if you want to handle the "revert failed" in another issue, then you can open that. But then this PR should be for that issue.

**Comment by nemanjaglumac** [comment]
I'll open a new PR with a repro that follows updated repro steps.

**Pull request closed without merging**
