### PR TITLE
Fix LDAP Auth reflection warnings

### PR DESCRIPTION
**Pull request by willtrnr**
Fixes the reflection warnings introduced by #4340

### CODE REVIEW

**Review by camsaul — CHANGES_REQUESTED** [review]
Rewriting code to stop using `with-open` just to avoid reflection warnings is the wrong way of going about things. To fix this you need to `^Tag` things rather than write code in a convoluted way

**Comment by wwwiiilll** [comment]
I am however rewriting it like that to use `ldap/close` from the `clj-ldap` library instead of calling `.close` directly on the connection.

**Comment by camsaul** [comment]
I've went ahead and fixed this in #5374

**Comment by wwwiiilll** [comment]
Good, that's precisely what I had, was just waiting for the tests to complete locally.

**Pull request closed without merging**
