### PR TITLE
Support counting grouped on an aggregated field in BigQuery

### PR DESCRIPTION
**Pull request by jeff303**
Adding failing test to illustrate the problem.

### CODE REVIEW

**Comment by jeff303** [comment]
Fixes #15074

(hopefully, eventually)

I will need to work with @camsaul to figure out what's wrong here.  It seems clear that the `count` field **is** correctly qualified in the `SELECT` clause, just not in `GROUP BY`, so hopefully it's simple, but I'm not knowledgeable enough in MBQL to efficiently locate the problem.

**Comment by camsaul** [comment]
Not sure how to review this... The test LGTM. Maybe comment out the test? Since we don't have a "skip" equivalent like there is in the FE tests.

Maybe commit the test but instead of `(is ...)` do `(is (not ...))` and a comment saying this test should fail until that bug is fixed? Then maybe we accidentally fix the bug while working on something else, and notice the fix because the test starts failing

**Review by camsaul — APPROVED** [review]
Test looks fine but to merge it I'd change the `=` to `not=` or something like that and make a note that it's expected to fail until #15074 is fixed

**Comment by flamber** [comment]
@jeff303 This can be closed, right? I'm guessing that #17536 superseded this.

**Comment by jeff303** [comment]
This was done via #17536

**Pull request closed without merging**
