### PR TITLE
#15598: Data reference database list is unsorted

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Reproduces #15598 

### How to test this manually?
- `yarn test-cypress-open --spec frontend/test/metabase/scenarios/reference/databases.cy.spec.js`
- Replace `it.skip()` with `it.only()` to run the test in isolation
- The test should fail until the related issue is fixed

### Additional notes:
- Once the issue is fixed, please remove the `.skip` part (unskip the test completely)
- Make sure the test is passing and
- Merge it together with the fix

### Screenshots:
image

### CODE REVIEW

**Review by flamber — APPROVED** [review]
While creating these databases, it would be nice to check the `/browse` list, Simple question dropdown and Native query dropdown, since they are different from too.
I think the correct is the dropdown in "Simple/Custom question", whereas the one in Data Reference uses ID, and the one in Native is getting sorted by javascript, so it mixes up casing.

**Comment by nemanjaglumac** [comment]
Every single thing you mentioned displays the correct, sorted order.

**Comment by nemanjaglumac** [comment]
@flamber updated and expanded the test to cover all those scenarios. How do you like it now?

**Review by flamber — APPROVED** [review]
Excellent. Likely Browse/Simple/Custom should always be the same, since they're pulling data from the same place, but given the inconsistencies we've had over the years, I think it's good to test all of them like you do now.

**Pull request merged**
