### PR TITLE
Make AggregationPicker work better for metrics

### PR DESCRIPTION
**Pull request by ranquild**
Changes:
- Removes "Basic Metrics" and "Common Metrics" titles
- Combines both sections into one
- Adds "metric" icon to metric items

image

### CODE REVIEW

**Review by mazameli — CHANGES_REQUESTED** [review]
image



- It would be great if the `Custom expression…` item could look like this (note the font size and the green icon). I think the Metric ruler icon should be green, too.


image

- There are some left-alignment issues for both the Metric icons as well as the custom expression icon. Those icons should all left-align with the text for these basic aggregations.

**Comment by ranquild** [comment]
@mazameli please take a look 
Screenshot 2024-05-20 at 16 23 44
Screenshot 2024-05-20 at 16 23 56
Screenshot 2024-05-20 at 16 24 14

**Review by mazameli — CHANGES_REQUESTED** [review]
Thanks for those fixes, Alexander!

Sorry to be annoying, but I'm now just seeing some horizontal alignment issues with the icons relative to the text. Here's your screenshot on the left, with a zoomed-in mock of the desired alignment on the right — you can see that the icons are too high up currently:

image

**Comment by ranquild** [comment]
@mazameli also be fixed now 
Screenshot 2024-05-20 at 17 38 02

**Review by mazameli — APPROVED** [review]

**Review by kamilmielnik — COMMENTED** [review]
As someone who has many metrics defined (hopefully I'm in minority here) I'm not a big fan of this change since it results in a [very long dropdown menu](https://github.com/metabase/metabase/assets/6830683/87b18bf1-0bc5-4c91-9144-ce039eb5aa6d).

It also introduces some inconsistencies among notebook editor dropdowns (comments inline).

**Comment by mazameli** [comment]
I'm still in favor of merging this, but I've started a conversation with a more thorough explanation [in Slack](https://metaboat.slack.com/archives/C0645JP1W81/p1716415110330519).

**Pull request closed without merging**
