### PR TITLE
Fix display bug for large integers

### LINKED ISSUE #5816: Floating-point rounding errors in UI for very large integers (JS stores all numbers as 64-bit floats)
Our data has several primary / foreign key ID fields that are 8 byte BIGINT's.
So fairly large numbers, many above 256^7, are involved.

Metabase is unable to display the large numbers as answers, and appears to round them off when displaying them.

Among other issues, this creates problems with foreign key links.

The underlying data is correct - and downloading the answer as a CSV yields the correct numbers, without an apparent rounding error.

It is not possible to drill through the data, because Metabase appears to use the displayed number (rather than the actual query result as shown in the CSV download) to make the link / drill down. The result is an error screen when drilling down for linked foreign key records.

The following screen shots show the problem:

1. THE QUESTION RESULT DOWNLOADED AS A CSV, showing the correct large numbers:

image

2. THE QUESTION RESULT DISPLAYED ON SCREEN, showing the apparently rounded numbers:

image

3. And the normal error screen when attempting to drill down / click through on the rounded numbers:

image

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by kaplanmaxe**
Resolves #5816

Metabase does not properly display any integer larger than 2^53 due to that being the largest integer Javascript supports out of the box. A library was added to handle parsing large integers which stores them as `BigNumber`s.

I have not added tests as I'm not too familiar with the code base and not sure on the proper place to put them, however if you would like some added, any guidance you can give me would be appreciated :+1:

### CODE REVIEW

**Review by tlrobinson — APPROVED** [review]

**Comment by kaplanmaxe** [comment]
@tlrobinson thanks for the review. Love this project, has been super helpful. This has been the biggest issue for me. I noticed there are conflicts now due to the snapshot. How do you want to go about resolving it? Want me to rebase?

**Comment by camsaul** [comment]
Hey @kaplanmaxe, please go ahead rebase and ping me and I'll merge this.

Thanks!

**Comment by kaplanmaxe** [comment]
@camsaul good to go :+1:

**Comment by mazameli** [comment]
Thanks for the contribution, @kaplanmaxe!

**Pull request merged**
