### PR TITLE
Start Jetty earlier in process so Heroku boots don't fail

### PR DESCRIPTION
**Pull request by tlrobinson**

### CODE REVIEW

**Comment by tlrobinson** [comment]
Needs some designer love, but I added a progress bar:

progress

**Comment by mazameli** [comment]
@tlrobinson maybe we can use the same loader animation as we have in the mac app?

**Comment by tlrobinson** [comment]
Sure... but progress bar!

**Comment by tlrobinson** [comment]
@agilliland What else do we need to do to get this merged in? You mentioned some edge cases you were concerned about at one point?

**Comment by agilliland** [comment]
okay, i made one quick addition to resolve an issue that i saw in testing.  

the problem was that if a valid session id was set as a cookie when requesting the app during initialization our middleware code would attempt to validate that session and lookup the corresponding user, which requires a db connection that hadn't been initialized yet.

**Comment by agilliland** [comment]
at this point i think this is g2g.  the only thing that could possibly use some work is the loading indicator, which is functional but not exactly elegant.

what do we think about following Maz's suggestion and using the same basic loading assets from the Mac app?  i'm thinking instead of the spinning crescent we can just have a ring that fills in progressively?  and we should also add in a little bit of copy to confirm that it's a loading screen.

**Comment by agilliland** [comment]
i'm going to go ahead and merge this and create a separate issue for improving the loading page visuals, which is realistically fairly minor at this point.

**Pull request merged**
