### PR TITLE
Add editable column titles to LineAreaBar/Funnel/Pie charts

### LINKED ISSUE #14401: Blank screen when configuring unconfigurable chart axes
When configuring waterfall data, the axes dropdown is greyed-out since there's only one item to choose, but I can click the gear next to it which opens up a totally blank sidebar.

From here (`/question/:id`)

image

Click either of the gears and get:

### PR DESCRIPTION
**Pull request by daltojohnso**
Resolves #14401

### CODE REVIEW

**Comment by mazameli** [comment]
# Line/Area/Bar/etc. charts
I think that changing the x-axis column's name and having that update the tooltip and the x-axis label makes sense to me. 

One funky thing is that now that this exposes a Column Title input for y-axis columns (i.e., the series), the relationship between that input and the series label input that we have on the Display tab should probably follow the same logic that we're using for the way that the x-axis column's Column Title relates to the x-axis Label. Here's what I'm currently seeing if I only change the Column Title for my y-axis column; note that this series label input still says `Count`. If I haven't changed this series label manually yet, I think I would expect it to default to the Column Title (`Maz is great` in this example).

image

# Pie charts
This doesn't apear to be working yet for Pie charts. Is that expected? 
image

# Side note
Just to say this out loud: digging into this has really made me want to refactor the UX of this and ideally have one consistent and easy place for renaming columns, regardless of the chosen visualization. It's pretty gross how many different places this can happen now (and I'm probably largely to blame for the state this is in).

**Comment by daltojohnso** [comment]
Thanks @mazameli -- I've fixed both of those issues (I think)

**Comment by mazameli** [comment]
### 1. Pie charts look good! 👌🏼 

### 2. Series inputs still not right?
I'm not seeing the Line/Area/Bar series inputs getting updated to match my `Column Title` still. Here I'd expect `Count` to read `Total Orders` because that's what I changed that column's `Column Title` to.

image

### 3. Funnel charts not implemented yet?
If I change either my Step or Measure column's `Column title`, neither the y-axis label for the former nor the tooltip label for the latter seem to be affected:

image

image

**Comment by daltojohnso** [comment]
After spending some time writing a lot of e2e tests per a few different visualizations, I'm realizing there's a lot more complexity to this than I initially thought. I also realized this probably means there need to be changes in the static viz code as well? Also, I think there needs to be a more systematized approach to this work and perhaps a more formalized approach to the priority of column titles to series data labels and chart labels since it appears `column_title || something_else` is going to get sprinkled in a lot of places, not all very intuitively. I'm closing this PR and perhaps we can address this work in a larger Epic.

**Comment by flamber** [comment]
It definitely gets a lot more complex if we're taking all viz types into account, but then it would also solve 9312 and probably others

**Pull request closed without merging**
