### PR TITLE
Serdes: Hide `entity_id` from Serdes v1; it was causing errors

### LINKED ISSUE #26043: Load in serialization with --mode update fails on upserts
**Describe the bug**
When trying to update a card, seems like the load process thinks we're loading a new one

**Logs**
```
2022-10-20 17:37:56,179 ERROR serialization.upsert :: Error inserting metabase.models.card.CardInstance@6b213571 "AVERAGE QUANTITY PER MONTH": ERROR: duplicate key value violates unique constraint "report_card_entity_id_key"
  Detail: Key (entity_id)=(9wRLMMS6nmDUUAfXbRFVg) already exists.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "report_card_entity_id_key"
  Detail: Key (entity_id)=(9wRLMMS6nmDUUAfXbRFVg) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:149)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502)
	at clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__28481.invoke(jdbc.clj:979)
	at clojure.java.jdbc$db_do_execute_prepared_return_keys.invokeStatic(jdbc.clj:1007)
	at clojure.java.jdbc$db_do_execute_prepared_return_keys.invoke(jdbc.clj:963)
	at clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:1038)
	at clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:1015)
	at clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:1040)
	at clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:1015)
	at toucan.db$simple_insert_many_BANG_$iter__29238__29242$fn__29243$fn__29244.invoke(db.clj:607)
	at toucan.db$simple_insert_many_BANG_$iter__29238__29242$fn__29243.invoke(db.clj:605)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$dorun.invokeStatic(core.clj:3134)
	at clojure.core$doall.invokeStatic(core.clj:3149)
	at clojure.core$doall.invoke(core.clj:3149)
	at toucan.db$simple_insert_many_BANG_.invokeStatic(db.clj:604)
	at toucan.db$simple_insert_many_BANG_.invoke(db.clj:590)
	at toucan.db$simple_insert_BANG_.invokeStatic(db.clj:637)
	at toucan.db$simple_insert_BANG_.invoke(db.clj:626)
	at toucan.db$insert_BANG_.invokeStatic(db.clj:654)
	at toucan.db$insert_BANG_.invoke(db.clj:641)
	at metabase_enterprise.serialization.upsert$insert_many_individually_BANG_$iter__60614__60618$fn__60619$fn__60620$fn__60621.invoke(upsert.clj:85)
	at metabase_enterprise.serialization.upsert$insert_many_individually_BANG_$iter__60614__60618$fn__60619$fn__60620.invoke(upsert.clj:83)
	at metabase_enterprise.serialization.upsert$insert_many_individually_BANG_$iter__60614__60618$fn__60619.invoke(upsert.clj:80)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5935.invoke(core.clj:2763)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5939.invoke(core.clj:2774)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$concat$cat__5560$fn__5561.invoke(core.clj:736)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$sort.invokeStatic(core.clj:3114)
	at clojure.core$sort_by.invokeStatic(core.clj:3120)
	at clojure.core$sort_by.invokeStatic(core.clj:3120)
	at clojure.core$sort_by.invoke(core.clj:3120)
	at metabase_enterprise.serialization.upsert$maybe_upsert_many_BANG_.invokeStatic(upsert.clj:155)
	at metabase_enterprise.serialization.upsert$maybe_upsert_many_BANG_.invoke(upsert.clj:119)
	at metabase_enterprise.serialization.load$load_cards.invokeStatic(load.clj:657)
	at metabase_enterprise.serialization.load$load_cards.invoke(load.clj:637)
	at metabase_enterprise.serialization.load$fn__86224.invokeStatic(load.clj:678)
	at metabase_enterprise.serialization.load$fn__86224.invoke(load.clj:675)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase_enterprise.serialization.load$load_collections$iter__86270__86274$fn__86275$fn__86276.invoke(load.clj:751)
	at metabase_enterprise.serialization.load$load_collections$iter__86270__86274$fn__86275.invoke(load.clj:741)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$apply.invokeStatic(core.clj:662)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase_enterprise.serialization.load$load_collections.invokeStatic(load.clj:758)
	at metabase_enterprise.serialization.load$load_collections.invoke(load.clj:730)
	at metabase_enterprise.serialization.load$fn__86319.invokeStatic(load.clj:763)
	at metabase_enterprise.serialization.load$fn__86319.invoke(load.clj:761)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase_enterprise.serialization.load$load_collections$iter__86270__86274$fn__86275$fn__86276.invoke(load.clj:750)
	at metabase_enterprise.serialization.load$load_collections$iter__86270__86274$fn__86275.invoke(load.clj:741)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$apply.invokeStatic(core.clj:662)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase_enterprise.serialization.load$load_collections.invokeStatic(load.clj:758)
	at metabase_enterprise.serialization.load$load_collections.invoke(load.clj:730)
	at metabase_enterprise.serialization.load$fn__86319.invokeStatic(load.clj:763)
	at metabase_enterprise.serialization.load$fn__86319.invoke(load.clj:761)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase_enterprise.serialization.load$load_collections$iter__86270__86274$fn__86275$fn__86276.invoke(load.clj:750)
	at metabase_enterprise.serialization.load$load_collections$iter__86270__86274$fn__86275.invoke(load.clj:741)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$apply.invokeStatic(core.clj:662)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase_enterprise.serialization.load$load_collections.invokeStatic(load.clj:758)
	at metabase_enterprise.serialization.load$load_collections.invoke(load.clj:730)
	at metabase_enterprise.serialization.load$fn__86319.invokeStatic(load.clj:763)
	at metabase_enterprise.serialization.load$fn__86319.invoke(load.clj:761)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase_enterprise.serialization.cmd$fn__90588$v1_load__90593$fn__90594.invoke(cmd.clj:57)
	at metabase_enterprise.serialization.cmd$fn__90588$v1_load__90593.invoke(cmd.clj:43)
	at metabase_enterprise.serialization.cmd$load.invokeStatic(cmd.clj:84)
	at metabase_enterprise.serialization.cmd$load.invoke(cmd.clj:79)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.cmd$load.invokeStatic(cmd.clj:151)
	at metabase.cmd$load.doInvoke(cmd.clj:142)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__86554.invoke(cmd.clj:227)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:227)
	at metabase.cmd$run_cmd.invoke(cmd.clj:218)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:160)
	at metabase.core$run_cmd.invoke(core.clj:158)
	at metabase.core$_main.invokeStatic(core.clj:182)
	at metabase.core$_main.doInvoke(core.clj:177)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
```

**To Reproduce**
1) using https://github.com/paoliniluis/metabase-serialization (or setting up your own Metabase server to test serialization)
2) use the Orders X-RAY to create a set of questions and dashboards to have something to dump and load. Save the dashboard that is created
3) do the dump
4) access "/collections/root/collections/Automatically\ Generated\ Dashboards/collections/A\ look\ at\ your\ Orders\ table/cards/Average\ quantity\ per\ month/Average\ quantity\ per\ month.yaml" and replace "name: Average quantity per month" for "name: AVERAGE QUANTITY PER MONTH". Save the yaml
5) now load those files to a target instance with "--mode update"
6) see the error

**Expected behavior**
Shouldn't recognize that it is a different card, specially because there's no other card with the same entity_id

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your operating system: Alpine
- Your databases: Postgres 14
- Metabase version: 1.44.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
P2? Maybe P1 as it's making the feature non-usable

**Additional context**
NA

### PR DESCRIPTION
**Pull request by bshepherdson**
Fixes #26043.

### CODE REVIEW

**Review by camsaul — APPROVED** [review]

**Comment by flamber** [comment]
@bshepherdson Remember to add `backport` label to get it into 45 - and if this should get into a possible 44.6, then we can backport by doing something like this https://github.com/metabase/metabase/pull/25163#issuecomment-1234287544

**Comment by bshepherdson** [comment]
@metabase-bot backport release-x.44.x

**Comment by flamber** [comment]
@metabase-bot backport release-x.44.x

**Comment by bshepherdson** [comment]
@metabase-bot backport release-x.45.x

**Comment by bshepherdson** [comment]
@metabase-bot backport release-x.45.x

**Pull request merged**
