### PR TITLE
Auto-resizing embeds

### LINKED ISSUE #4591: There should be a way to auto-size dashboard embeds to fit the content
Dashboards have a fixed aspect ratio, so the default width/height of the iframe embed code is likely to cause scrolling or extra space at the bottom. It would be nice if there were a way to automatically size the iframe to fit the content.

This will probably entail a `postMessage` from the Metabase embed to the host page, and some Javascript running on host page to change the iframe size. We could probably use this: https://github.com/davidjbradshaw/iframe-resizer

Additionally, it would be nice if the width/height in the generated embed code were sized so this didn't happen, even if you don't include the iframe resizing snippet.

### LINKED ISSUE #4594: Embed codes use self-closing iframe tag, which isn't valid and may break things
Should be `<iframe ...></iframe>` not  `<iframe ... />`

### PR DESCRIPTION
**Pull request by tlrobinson**
Uses `iframe-resizer` to automatically set the height of the iframe so it doesn't scroll or have extra space.

You can use iframeResizer manually:

```html
<script src="node_modules/iframe-resizer/js/iframeResizer.js" charset="utf-8"></script>
<iframe
  src="http://localhost:3000/public/dashboard/69c861aa-0c7b-4630-ab4b-5bd5c001fc65" 
  frameborder="0" width="800" height="600" allowtransparency
  onload="iFrameResize({}, this)"></iframe>
```

Or I added a simple script that both loads the iframe, iframeResizer, and starts iframeResizer.

```html
<script src="http://localhost:3000/public/dashboard/69c861aa-0c7b-4630-ab4b-5bd5c001fc65.js"></script>
```

You can also pass options like `width` and `theme` in the script tag:

```html
<script src="..." data-width="800" data-theme-"night" data-bordered="false"></script>
```

Some other ideas for embedding APIs: https://runkit.com/docs/embed

Resolves #4591
Resolves #4594

TODO:

* [x] Decide which style APIs we want
* [x] Bundle iframeResizer in `resources/frontend_client/*`

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers Thoughts on this one?

The `embed_script` thing is optional, but lets the embed code with iframe resizing be a one-liner. Not as necessary since I figured out how to do it as a two-liner though.

**Comment by attekei** [comment]
Does the resizer script interfere if I for instance want to cover the full browser viewport with the embedded iframe? I think I like the two-liner version more as then I can remove the resizer functionality if I don't need it.

**Comment by tlrobinson** [comment]
@metabase/core-developers Ok I've removed the embed script thing for now.

Any opinions on whether we should serve `iframe-resizer` script for embedders to use, or just let them get it on their own from a CDN or bundle it in their app?

```html
<script src="mycompany-or-cdn-or-whatever.com/iframeResizer.js" charset="utf-8"></script>
<iframe
  src="http://metabase.mycompany.com/public/dashboard/ABCD"
  frameborder="0 width="800" height="600" allowtransparency
  onload="iFrameResize({}, this)"></iframe>
```

Or we could "white label" it with a little wrapper, which would provide a place for future enhancements (direct parameter access, etc):

```html
<script src="https://metabase.mycompany.com/app/metabase.js" charset="utf-8"></script>
<iframe
  src="https://metabase.mycompany.com/public/dashboard/ABCD"
  frameborder="0 width="800" height="600" allowtransparency
  onload="metabase.embed(this, { resize: true })"></iframe>
```

**Comment by salsakran** [comment]
I think we should serve it from the app. While it's not as scalable as a CDN, I'd rather not have YetAnotherStep in getting embedding working.

**Comment by tlrobinson** [comment]
Ok. Also, how do we expect people to discover this feature? Just via documentation, or a box they can check in the embed modal?  If the latter, that raises a whole bunch of questions.

**Comment by salsakran** [comment]
We definitely should note it in the documentation, and I think we should also have a separate embedding guide.

**Comment by tlrobinson** [comment]
@salsakran Ok how's this? 40b1284

**Review by attekei — APPROVED** [review]
Works as intended & code looks good 👍

**Pull request merged**
