### PR TITLE
Add a "See this dashboard" link for dashboard sub for slack

### PR DESCRIPTION
**Pull request by qnkhuat**
Screenshot 2024-07-30 at 10 14 55

[See it for real](https://metaboat.slack.com/archives/C04R9F5A29F/p1722309284843159)

[Context](https://metaboat.slack.com/archives/C01LQQ2UW03/p1719841214331139)

### CODE REVIEW

**Comment by cdeweyx** [comment]
On second thought: Let's just move the existing "Sent from XXX" to where "See this dashboard" is — Instead of linking to the dashboard twice, at the top and the bottom. 

cc: @kdoh in case you have other views

**Review by cdeweyx — CHANGES_REQUESTED** [review]
On second thought: Let's just move the existing "Sent from XXX" to where "See this dashboard" is — Instead of linking to the dashboard twice, at the top and the bottom. 

cc: @kdoh in case you have other views

**Comment by qnkhuat** [comment]
what about the text? is it "Sent from XXX" or "See this dashboard?"

**Comment by qnkhuat** [comment]
@cdeweyx updated, please see the description. 

wdyt if we combine sent from and sent by to one sentence tho? `Sent from Metabase by Conor`?

**Comment by luizarakaki** [comment]
@kdoh can you take a look? I think we can improve the copy to make this clearer and more concise.

As it isn't possible to link the dashboard name, I think it makes sense to consolidade both lines in a single message as Ngoc proposed:
`Sent from {{site_name}} by {{user_name}}`

**Comment by cdeweyx** [comment]
> @cdeweyx updated, please see the description.
> 
> wdyt if we combine sent from and sent by to one sentence tho? `Sent from Metabase by Conor`?

Yeah I agree that works here, let's go with that

**Review by cdeweyx — APPROVED** [review]

**Comment by qnkhuat** [comment]
Updated, see the change in the PR's description

**Pull request merged**
