### PR TITLE
List user collections for admins

### PR DESCRIPTION
**Pull request by kdoh**
Admin only route to browse user collections for admin-y purposes.

### CODE REVIEW

**Comment by mazameli** [comment]
Guess we could call this "Everyone's personal collections" since it shows mine too. The other option would be to the current user's.

screen shot 2018-06-12 at 3 21 50 pm

**Comment by mazameli** [comment]
Functionally, I think we can merge this. 

I did expect to see the breadcrumb path, like: `Saved items > Everyone's personal collections > Cam Saul's personal collection`, both for consistency as well as making it easier to navigate.

Visually, think the font size for the names is too big: I'd expect these cards to be like the same component as we're using for lists of tables, but with the icon swapped out. 

Otherwise everything seems to work as expected. I also verified that I can only see my own personal collection when logged in as a non-admin. 

(One funny thing was that I noticed that, as an admin, after I created another user I didn't see their personal collection until they logged in the first time. Doesn't bother me, but just thought I'd mention that in case anyone else was confused by it.)

**Comment by kdoh** [comment]
@mazameli Sounds good. The bread crumbing we'll need to make dependent on whether you're an admin or not since if you're just a normal user I wouldn't expect to see a breadcrumb path with `Everyone else's Collections` that I can't click and since it's in the top level list I'd expect it to not be 3 levels down when I click in. That shouldn't be terribly hard.

My vote is we should merge this as a functional base like you said and we can file a follow up issue with the other bits you brought up to smooth out a couple of the corners.

**Comment by mazameli** [comment]
👍

**Pull request merged**
