### PR TITLE
Introduce the non-admin Onboarding Checklist

### LINKED ISSUE #50576: Non-admin Onboarding Checklist
## Links
- [Product doc](https://www.notion.so/metabase/Better-Onboarding-pt-3-iterations-13469354c90180bebbdfe315a42552de?pvs=4#13469354c90181f695f4fd9bc7757ec2)
- [Figma](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6364-30904&t=jkz5hUBlbVM4A8Jw-1)

## The task
Create a non-admin version of the onboarding checklist.

```[tasklist]
- [x] Update the link visibility
- [x] Do not show CTAs for non-admins
- [x] Do not show the "setup" section to non-admins
```

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### What does this PR accomplish?
- It opens up an onboarding checklist for non-admins!
- It improves the route guards so that now even people who navigate directly to this route (`/gettting-started`) are redirected to the home page if they are not supposed to see the page (whitelabelled instances or embedding context)

Resolves #50576

> [!IMPORTANT]
> Other than opening this up to non-admins, all other conditions that determine whether or not to display the link to this page still apply.

### CODE REVIEW

**Comment by rafpaf** [comment]
Since my instance is older than 30 days, /getting-started shows me the error "Sorry, you don’t have permission to see that" when I log in as a non-admin user. I wonder if the page should display anyway when the instance is no longer new, even if the sidebar link won't display? After all, someone might open Onboarding in a tab on day 25, and then get confused a few days later when the tab gives them a permission error on refresh.

**Comment by rafpaf** [comment]
To see what the instance looks like when new, I deployed a preview environment for this PR, but the default user is an administrator, so I couldn't see how the page looked to non-admins. I also tried temporarily making [getIsNewInstance](https://github.com/metabase/metabase/blob/better-onboarding-pt3-non-admin/frontend/src/metabase/home/selectors.ts#L17-L21) always return true but `/getting-started` still redirected to `/unauthorized`.

I don't yet deeply understand our route guards but in case it's helpful, [this line of code](https://github.com/metabase/metabase/blob/better-onboarding-pt3-non-admin/frontend/src/metabase/routes.jsx#L134) might be worth giving a second look to. That makes me think e2e tests might be helpful for the non-admin case.

I admit this is a self-interested suggestion since I'm hoping to shadow you sometime as you wrangle Cypress!

**Review by rafpaf — CHANGES_REQUESTED** [review]
I've added some comments above and below

**Comment by nemanjaglumac** [comment]
> Since my instance is older than 30 days, /getting-started shows me the error "Sorry, you don’t have permission to see that" when I log in as a non-admin user. I wonder if the page should display anyway when the instance is no longer new, even if the sidebar link won't display? After all, someone might open Onboarding in a tab on day 25, and then get confused a few days later when the tab gives them a permission error on refresh.

This has nothing to do with the instance being old. It's way more embarrassing than that. I _simply_ forgot to remove the route guard 🤦‍♂️ 

Fixed in https://github.com/metabase/metabase/pull/50516/commits/542d431a6e600305cda7f7868f1ac4a8d17c19e3.
Will add E2E test for good measure.

Thank you so much for catching this!
It was a silly mistake on my part that could've introduced not so silly (read: BAD) user experience.

**Review by trinya — APPROVED** [review]

**Comment by rafpaf** [comment]
The "Set up" and "Slack" links don't look like links to me. Should they be in blue?

**Comment by rafpaf** [comment]
The bolded "filters" caught my eye. Should there be any other bolded text in the list? Perhaps a question for the design team.

**Comment by rafpaf** [comment]
For consistency, maybe use an em dash here since we use them below?

```
{jt`Filter and summarize data, add custom columns, join data from other tables, and more - ${(
                      <b key="no-sql">{t`all without SQL`}</b>
```

**Comment by nemanjaglumac** [comment]
> The bolded "filters" caught my eye. Should there be any other bolded text in the list? Perhaps a question for the design team.

Nope. This was the original design, and not really something that's in the scope of this PR.

**Review by rafpaf — APPROVED** [review]

**Review by rafpaf — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
@metabase-bot backport release-x.51.x

**Pull request merged**
