### PR TITLE
🥳 Miscellaneous Bugfixes 🥳

### PR DESCRIPTION
**Pull request by iethree**
Resolves: all open bugs

# Description

Let me know if you see any that I missed!

## How to test

- checkout branch
- `npm run start`
- click around to make sure there are no bugs anymore

### CODE REVIEW

**Comment by qnkhuat** [comment]
and improved startup time!

**Comment by nemanjaglumac** [comment]
Ship it!

**Comment by tsmacdonald** [comment]
Should improve performance in low-memory environments! :ship:

**Comment by kulyk** [comment]
Blazing fast! 🚢

**Comment by luizarakaki** [comment]
LGTM

**Review by alxnddr — COMMENTED** [review]
Looks great overall! Please add some e2e specs and angular

**Comment by iethree** [comment]
Hmm. Those merge conflicts are super intimidating. 😫  Gonna close this instead of dealing with that mess.

**Pull request closed without merging**
