### PR TITLE
Fixed driver installation description.

### PR DESCRIPTION
**Pull request by edenzik**
`MB_PLUGINS_DIR` has to be set for the Vertica driver to work.

###### TODO 
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by camsaul** [comment]
It doesn't need to be set if you're running locally or otherwise manually running the JAR. I guess you'd need to set it if you were using docker.

**Comment by edenzik** [comment]
So we should say that explicitly?

**Comment by salsakran** [comment]
@edenzik yes, it would be helpful to note that `if the default doesn't suit your needs` includes cases where one's needs include running it on docker =)

**Comment by salsakran** [comment]
happy to merge this if you elaborate a bit on when the defaults aren't sufficient.

**Pull request merged**
