### PR TITLE
Fix logic regression in sync tasks

### PR DESCRIPTION
**Pull request by camsaul**
While working on the sync refactor yesterday I realized that near the beginning of the 25 cycle I had mistakenly changed some of the logic that determined when which DBs were eligible for the so-called "full sync". I haven't seen bugs related to this specifically, but I'd rather be safe than sorry so reverting this code to what it was pre-25 for the time being. This should help provide a workaround for #5681 (making sure `is_full_sync` is always respected), although there may be other issues at play there causing more Fields than usual to be scanned for FieldValues. (Still investigating and making sure proper tests are in play to resolve that as part of the shiny new sync refactor.)

At any rate in the upcoming sync refactor PR I've already resolved this issue in a different way as well as added several dozen tests around sync scheduling, including ones that make sure the `is_full_sync` flag is respected. Previously, we had no such tests around this.

### CODE REVIEW

**Comment by doodlebro** [comment]
Can we just revert that commit you made and you can re open a PR? Seems like this is causing more problems than it's fixing by leaving this bug in the latest code.

**Comment by camsaul** [comment]
@doodlebro this commit is to revert a commit.

**Comment by doodlebro** [comment]
@camsaul: will a hotfix version be released as well?

Are we also writing a test to prevent this happening again?

**Comment by camsaul** [comment]
@doodlebro I talked about adding tests for this in the PR description.

> At any rate in the upcoming sync refactor PR I've [...] added several dozen tests around sync scheduling, including ones that make sure the `is_full_sync` flag is respected

Yes, we're planning on releasing a 0.25.2 release.

**Comment by doodlebro** [comment]
@camsaul why the long queue time for building in CI?

**Comment by camsaul** [comment]
@doodlebro because we have lots and lots of tests so sometimes CI takes a while to run.

**Comment by doodlebro** [comment]
It's a totally valid question given the state of latest :)

**Pull request merged**
