### PR TITLE
Use cljr-clean-ns to automatically sort all namespaces [proposal]

### PR DESCRIPTION
**Pull request by camsaul**
After talking with Arthur a bit it sounds like the standard hotness is just letting [cljr-refactor](https://github.com/clojure-emacs/clj-refactor.el) automatically keep your Clojure namespaces sorted for you. Since it has a different idea of how things are sorted I slapped together some Emacs Lisp and ran it over all over our Clojure files to get a sense for what things would look like

```emacs lisp
(require 'f)

(defun cam/clean-all-namespaces ()
  (interactive)
  (f-files "c:/Users/Cam/metabase/src"
           (lambda (filename)
             (when (string-match "\.clj$" filename)
               (with-temp-buffer
                 (find-file filename)
                 (call-interactively #'cljr-clean-ns)
                 (save-buffer)
                 (kill-buffer))))
           :recursive))
```

Since this is arguably a more standard way of sorting namespaces this PR is presented here so we can discuss whether it makes sense to switch over to this style. If so, I think we ought to switch over all our files at once so as to avoid confusing any potential contributors with a mix of different styles in different files

### CODE REVIEW

**Comment by camsaul** [comment]
So unfortunately `cljr-clean-ns` removes imports of nested Java classes, e.g. which are represented in Clojure like `DOMAnalyzer$Origin`. Unfortunately this breaks things and causes those namespaces to fail to compile. @thearthur do you know how to get `cljr-refactor` to behave the right way?

**Comment by camsaul** [comment]
actually I haven't updated `clj-refactor` in the better part of a year so let me upgrade the package and see if it behaves better, bug might already be fixed

**Comment by camsaul** [comment]
yeah latest version of `clj-refactor` still seems to have the same issue

**Comment by camsaul** [comment]
yeah looks like there's an open issue for this: https://github.com/clojure-emacs/clj-refactor.el/issues/332

**Comment by camsaul** [comment]
there's only a handful of namespaces this affects so we could probably manually fix them until the upstream bug is fixed

**Comment by camsaul** [comment]
but that sort of defeats the whole purpose of letting `clj-refactor` handle things for us automatically

**Comment by thearthur** [comment]
It's a manual review of an automatic process. 
That seems preferable to manual review of a manual process

we still have to review and test either way, this way we can spend less time explaining things to newbies (like me) and just say "do what emacs does"

**Comment by camsaul** [comment]
ok, spent a hour or so manually fixing all the namespaces this broke. It has trouble understanding `:require :all` forms, so I just replaced those with proper namespace aliases, which are preferable anyway.

**Comment by thearthur** [comment]
this should clean up any future problems with shadowing names as well.

**Comment by camsaul** [comment]
this is all passing now, it sounds like @thearthur and I are both in favor of it @metabase/core-developers any objections to us merging this?

**Comment by salsakran** [comment]
what about people that don't use emacs. How does that change the workflow?

**Comment by salsakran** [comment]
overall, I'm cool with this if it doesn't introduce friction for us peons on other editors.

**Comment by camsaul** [comment]
@salsakran this doesn't really change anything for non-Emacs users. The only thing that's changing here is the sorting rules so it's basically the same idea -- just make sure any new `:require`s you add are sorted properly. This should actually make things a little easier for new contributors with some past Clojure experience since these rules are a little more standard than what we've been using, and the rules themselves are a little simpler

**Comment by camsaul** [comment]
on another note: this really makes me wish I could just do something like

```emacs-lisp
(add-hook 'clojure-mode-hook
  (lambda ()
    ;; add hook to beginning of buffer-local before-save-hook (instead of adding to global hook)
    (add-hook 'before-save-hook #'cljr-clean-ns (not :append) :local)))
```

and have it run automatically on every save. If I get some free time I'll check out the bug and see if I can submit a PR for it

**Comment by camsaul** [comment]
Cool, going to go ahead and merge this now. @thearthur sorry if it causes a few merge conflicts with your SSH-tunnel branch but they should be pretty easy to resolve

**Comment by thearthur** [comment]
no problem, :ship: :it:

**Comment by benedekfazekas** [comment]
fyi i've fixed clojure-emacs/clj-refactor.el#332, should be available in latest snapshot of `refactor-nrepl` on clojars

**Comment by camsaul** [comment]
@benedekfazekas awesome, thanks!!

**Pull request merged**
