### PR TITLE
Add autocomplete to SelectPicker and CategoryWidget

### PR DESCRIPTION
**Pull request by tanzoniteblack**
This change adds filtering for filtering selections (both on questions and on dashboards) based off a search query.

- Expand the limit of distinct values of rows from 40 to 3000
I haven't seen any real performance reasons for the value of 40, only usability. Adding the type-in search filtering eliminates the usability reason. 3000 was kind of randomly picked based off our use case, but I'm open to better suggestions.

- Add a search box to `SelectPicker` and `CategoryWidget` which filters the values shown to the user based off a slightly fuzz search from their typed in input

# Category filtering on dashboard:
dashboard-filter-blank
dashboard-filter-filtered

# Category filtering on question:
question-filter-blank
question-filter-filtered

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by kdoh** [comment]
Thanks for this PR @tanzoniteblack! 

Based on an initial look I think we'll pant to do a couple things to move forward with this.

- Ensure the search box doesn't show up in cases where there are fewer than `N` values (your first category screenshot is a great example of what I mean). Search is useful, but in cases with a low number of options having search is just more UI chrome to parse that gets in the way of selecting an option. I'm inclined to say that it should only show up if there are more than 5 or 10 values or so. @mazameli / @salsakran I'd be curious to get your opinion on that number.

- As you mentioned, decide on what the limit of distinct values is. It should *definitely* be higher than 40, but we'll probably want to do a bit more digging on a sane default. 3000 seems a bit high to me but I don't fully know what a reasonable default is. Would you mind explaining a bit more about why 3000 seemed like the right number for you?

Overall this seems like a solid usability win so thanks so much for taking a stab at improving it!

**Comment by tanzoniteblack** [comment]
3000 wasn't really a well chosen number, so much as it fit the particular use case my company had and was still rather performant. 

The not having the box appear at all when the original selection list is less than 5 (10 seems high, since the box is useful at any point you have to scroll, in my opinion) is a good idea, and I'll implement that tomorrow.

**Comment by tlrobinson** [comment]
Regarding increasing the limit, I agree 40 is way too small.


3000 values probably isn't too large to store in the database. For reference, the max field value length is 100, so worst case 3000*100 = 300KB, but on average it will probably be much less.

But we should keep in mind currently in the query builder we load all the field values for all the fields in a table (and tables connected by foreign key). We could change that to load field values on demand.

**Comment by tlrobinson** [comment]
Also #2739 is related. We could essentially have an identical UI with low cardinality fields search on the client using saved field values, and higher cardinality search actually performing queries.

**Comment by tanzoniteblack** [comment]
Updated the code so that it only shows the search box if there's more than 5 values to choose from to begin with (on both question page & dashboard filter page)

**Comment by kdoh** [comment]
@salsakran / @camsaul Do either of you have opinions on the distinct values figure? If we're ok with 3000 then I think we just need to review the code and we should be ok to move forward with this.

**Comment by camsaul** [comment]
3000 values sounds kind of high, if someone has 10k fields that have FieldValues and each one takes 300KB (it could actually be more if any of the characters are multi-byte Unicode encodings) we're looking at theoretical double-digit gigabytes of stored field values. And keep in mind the entire set of field values for every field in a database is returned by the DB metadata endpoint which gets called all over the place in the frontend. We certainly don't want our API endpoints return responses that can get that large.

That might sound far-fetched but a lot of people have databases with hundreds of tables and tables with lots of columns. I am wary of raising the limit this high this fast; it seems dangerous.

**Comment by tanzoniteblack** [comment]
@camsaul that makes sense. Maybe better to start with a lower number, like 800, for the time being.   Honestly, I think that for much larger than that it makes sense to start querying the database for completion candidates, something like `select distinct(<field>) where <field> like '%<autocomplete>%' limit 1000;`

If you guys already have some thoughts about how something like that should be implemented, I'd be happy to take a stab at it.

**Comment by tlrobinson** [comment]
@camsaul Doesn't this line limit field values to 100 byes/characters:

```clojure
(def ^:private ^:const field-values-entry-max-length
  "The maximum character length for a stored `FieldValues` entry."
  100)
```

**Comment by camsaul** [comment]
@tlrobinson depends on how the string is counted. A string can have 100 characters but take 300 bytes to store if it's encoded in UTF-8 and all the characters are 3-byte encodings.

However it looks like `clojure.core/count` just counts the number of bytes in a string rather than the number of characters:

```clojure
(count "A😂😍") ; -> 5
```

So you are correct, the string would be limited to 100 bytes, and somewhere between 33-100 characters. But even so the size of the stored values could get pretty high if the limit is 3000 values

**Comment by salsakran** [comment]
👍 on the overall idea. 

At the risk of being OCD, could we not display this if it's 10 entries or more? The rationale being that the search bar is ~1-2 values worth of vertical real estate, and I'd only use it if I can't see the values in the window easily.

Regarding the limit (3k vs 800), I'll throw out that we have a number of instances in the wild with >100k fields  and dozens with >10k fields -- I'd like to tread carefully here. 

To look at this from a different angle -- do we need to keep field values around for all fields? For all fields in all tables? We identified "low cardinality dimensions" as being a candidate for this, what exactly are we saying when we raise the definition of "low cardinality" to 3k distinct values?

**Comment by mazameli** [comment]
> could we not display this if it's 10 entries or more?

@salsakran, I think you meant, "could we not display this **unless it's** 10 entries or more?"

**Comment by salsakran** [comment]
correct, updated my comment.

**Comment by tanzoniteblack** [comment]
Sure, I'll update the min value to 10 once the max number (i.e. the low cardinality number) has also been decided on.

Any other things that need to be updated in this code besides those two constants?

**Comment by moumny** [comment]
I suggest keep the top N most common values. (Here N should be the largest so that the stored values are not too big). For the rest query the database as @tanzoniteblack suggested. I've seen this working quite well in other similar projects.

**Comment by tanzoniteblack** [comment]
@salsakran I've updated the number of candidates needed before you see the type-ahead box from 5 to 10 like you've asked.

Also, I've changed the max completion limit from 3000 to 300 for the time being. It's still significantly more useful than 40 with no ability to query, though less useful than what I had originally intended. However, it should be conservative enough that it won't break anyone's system if they have a very large number of tables/columns for completions.

To achieve the use case that I needed, where we had 1k-2k candidates, I guess I'll have to work on doing the dynamic query for look ahead completions.

**Comment by salsakran** [comment]
Looks good to me! 

Revisiting how we deal with dimensions (and filters + values) is on our medium term radar and this PR makes a great step forward on that path =)

Thank you so much for all your work!

**Comment by tlrobinson** [comment]
@tanzoniteblack I merged your branch into our `master` and made a couple tweaks on the frontend. It's on the branch of the same name on our repo: https://github.com/metabase/metabase/tree/select-picker-autocomplete

Feel free to merge that into yours and then I think it will be ready to merge.

**Comment by tanzoniteblack** [comment]
@tlrobinson I believe that I gave permissions for metabase to alter my branch, so feel free to do that. If not, I'll get to this tomorrow morning

**Comment by tlrobinson** [comment]
@tanzoniteblack Indeed, thanks!

@metabase/core-developers Was there anything else or is this ready to merge?

**Review by tlrobinson — APPROVED** [review]

**Review by kdoh — APPROVED** [review]

**Comment by kdoh** [comment]
@tanzoniteblack Thanks for your work on this!

**Comment by camsaul** [comment]
@tlrobinson Something must be wrong with our CI setup, because this branch totally busted master. https://circleci.com/gh/metabase/metabase/9869

**Comment by camsaul** [comment]
nvm I guess some things changed on master that in the meantime since this was open. It's probably not a bad idea to merge master back into a branch and run tests again before merging

**Comment by dtheodor** [comment]
This doesn't seem to be working, I had to make this change https://github.com/dtheodor/metabase/pull/2/commits/8e61a80a682fb7d24d6eb876a6070dcba316eebe to get it to work.

**Comment by pedrokost** [comment]
May I ask about the status of this feature? I see lots of attempts to solve this problem, including https://github.com/metabase/metabase/pull/4241 and https://github.com/metabase/metabase/issues/2739 . The last one even had a milestone set (the last one being 0.21 before it was removed). 

This is a killer feature, which makes dashboard incredibly powerful. Unfortunately, it didn't make it to today's release 0.23. I hope to see it finished soon!

**Comment by tanzoniteblack** [comment]
@pedrokost This particular implementation of autocomplete seems to be working for me on the latest `0.23.0` release. Note: It will only work on text columns that have less than 300 entries. It's still not an ideal, killer feature with this limitation, but it's a lot better than the 40 that it was previously limited to.

In the native query builder, on a text column that has between 10 to 300 distinct items, do you not see a search box above the normal check list when trying to do a filter?

**Comment by pedrokost** [comment]
@tanzoniteblack  Sorry for the late reply... I couldn't find the issue on Github. 

My use case would require filtering 1000 values today. Basically, I've build a large dashboard for all our customer purchasing data and I wish to be able to search by user. Currently, I have to enter the customer_id, which is very difficult to explain & do for non-technical people (the sales guys & gals). 

This single feature would save me hours from building a custom frontend for reviewing customer purchases.

**Comment by tanzoniteblack** [comment]
@pedrokost if that's all that's holding you back from using metabase instead of building your own custom thing, here's some steps you can try to work around this until better searching is in place:

## If you really want people to use the built in query builder with pick list auto completion:

1.) Increase the limit of `300` saved entries to `3000`, by changing the variable [`low-cardinality-threshold`](https://github.com/metabase/metabase/blob/master/src/metabase/sync_database/analyze.clj#L21) and then the `bin/build` script to build your own jar to deploy (you might want to start with the git tag `v0.23.1` instead of `master` so you're running the latest stable with the only change being that limit

(Note: The above step is what I do for running this in production for my company, you can see in the discussion above why the number 3000 didn't get committed to master)

2.) At this point, you'll be able to autocomplete all 1000 of your strings...but they're still id's instead of names. What you can do at this point is create a [view](https://www.tutorialspoint.com/sql/sql-using-views.htm) in your database for your purchasing data...which surfaces the explicit user information that you want people to be able to filter by using the query builder. Metabase, at least for some? most? DB products, will treat a view identical to a table, so it will use your new `3000` string limit to cache the user names (since you say there are only 1000?)

## If you just want people to do a semi-natural language like search with custom names:

Write a custom sql query with [sql-parameters](http://www.metabase.com/docs/latest/users-guide/12-sql-parameters.html) that feed into sub-query like `where 1 = 1 AND [[user.last_name ilike '%' || {{last_name}} || '%'`]] AND [[user.first_name ilike '%' || {{first_name}} || '%']]` (or whatever syntax/operators are appropriate for your DB if you don't use postgres). 

Both of the above are semi-hacks that will hopefully be solved by a combination of https://github.com/metabase/metabase/issues/2739 and something to increase the number of completion candidates.

**Comment by sabino** [comment]
Hey @tanzoniteblack 
There is no search functionality when using the Category field on the dashboard.
Did I miss something?

search

**Comment by tanzoniteblack** [comment]
@sabino Hm...you're not missing anything, it's not there. It *was* there when this PR was merged, but appears to have gotten dropped. There were some merge conflicts right after this being merged that might've caused that to happen, I'll work on fixing that soon.

**Comment by attekei** [comment]
@tanzoniteblack Seems like a glitch in the original PR:
https://github.com/tanzoniteblack/metabase/blame/master/frontend/src/metabase/dashboard/components/parameters/widgets/CategoryWidget.jsx#L76

The search field in dashboard category filter is never shown because of the initial value of `regex` is null. I removed `&& regex` from the condition and after that the search field appeared and worked as intended!

**Comment by tanzoniteblack** [comment]
@attekei ... that looks wrong, good call. Don't suppose you want to throw together a PR with that fix?

**Comment by attekei** [comment]
@tanzoniteblack Will do, a good timing because I also have some other query filter fixes queued up! Just noticed that @dtheodor had suggested the same change one month ago.

**Pull request merged**
