### PR TITLE
Docs: Save 17M by compressing all PNG images *losslessly* with Zopfli [ci skip]

### PR DESCRIPTION
**Pull request by ariya**
Before: find ./docs -type f -iname '*.png' -exec du -ch {} + | tail -1
33M     total

After: find ./docs -type f -iname '*.png' -exec du -ch {} + | tail -1
16M     total

### CODE REVIEW

**Comment by ariya** [comment]
It might need to be part of CI at some point, but this'll do for now.

For some more references:
https://github.com/google/zopfli
https://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/
https://ariya.io/2016/06/using-zopfli-to-optimize-png-images

**Review by flamber — APPROVED** [review]
:rocket:

**Comment by salsakran** [comment]
Sweet!

Is there a way to do this automatically? otherwise as people submit new pngs for new docs and screenshots we'd need to do it again?

**Comment by ariya** [comment]
> Is there a way to do this automatically?

Certainly. We just need to think through the correct workflow.

**Pull request merged**
