### PR TITLE
Add BOM to the head of CSV file

### LINKED ISSUE #3271: CSV exports should include byte order mark
We're already exporting them as UTF-8 but apparently without including the BOM Excel can't open the files directly. It seems people having been working around this by either opening the files in LibreOffice or manually adding the BOM in a text editor.

See #1961 and http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom

### PR DESCRIPTION
**Pull request by kndt84**
###### Before submitting the PR, please make sure you do the following

- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### CODE REVIEW

**Comment by kndt84** [comment]
@flamber Thanks for linking to the issue. I've signed the CLA, so please approve to run workflows. As long as I tested to download a csv file, it works fine.

**Comment by kndt84** [comment]
It turns out that `\ufeff` is the BOM for UTF-16 BE, so we changed it to `\uefbbbf`, which is the BOM for UTF-8.

**Comment by noahmoss** [comment]
cc @camsaul -- I'm reading through the previous discussion about this and it seems inconclusive whether this is a good idea. What do you think?

**Comment by flamber** [comment]
Excel is silly. It requires BOM, and also semi-colons, to be able to automatically just open a CSV file correctly.
LibreOffice and friends will show an import dialog upon opening a CSV file, so you can change charset and delimiter etc.
My biggest concern would be if this messes up something for people who are expecting current style via the API. And we have an explicit XLSX export.

**Comment by noahmoss** [comment]
Yeah, I don't really understand why you would open a CSV file in Excel rather than just exporting as XLSX.

@kndt84 would you mind describing your use case that requires a BOM in the CSV export?

**Comment by kndt84** [comment]
> @kndt84 would you mind describing your use case that requires a BOM in the CSV export?

This is just our use case, but we assume that business users will download the data in CSV when they manually import the data from Metabase to other systems such as HubSpot. Since this is mainly done by business users, it would be helpful if it could be opened in Excel.

**Comment by camsaul** [comment]
Let me just leave this here [Falsehoods Programmers Believe About CSVs](https://donatstudios.com/Falsehoods-Programmers-Believe-About-CSVs) 

> Prepending a BOM is a good way to get Excel to read your encoding

**Comment by camsaul** [comment]
Lots of good discussion about this the last time this PR came up: #7029.

To build on what Tom was getting at back then, Excel might need the BOM but we don't have a good sense of whether adding it is going to break CSV usage for other use cases. As Tom pointed out Clojure's own CSV library says this:

> A byte order mark (BOM) is a byte sequence that appears as the first couple of bytes in some CSV files (and other text files). Data.csv will not automatically remove these extra bytes so they can accidentally be interpreted as part of the first cells characters. If you want to avoid this you can either try to manually detect it by looking at the first byte(s) and calling (.skip reader 1) before you pass the reader to read-csv.

https://github.com/clojure/data.csv#byte-order-mark

We really don't have a good sense of how many other libraries would behave the same way. At best we're just sorta busting CSV output for a handful of people. At worst we're busting it for everybody _except_ people who want to use it with Excel.

It seems a little kooky to add the BOM so make CSVs work better _for Excel_ when we already have XLSX export _for Excel_.

**Comment by camsaul** [comment]
I'm ok with adding an **option** to include the BOM when doing CSV export (I think an admin panel Setting would work here) so people who want it can turn it on, but I think turning it on for everybody is going to make people unhappy when it breaks their stuff when they upgrade.

**Review by camsaul — CHANGES_REQUESTED** [review]
This needs tests before we can even consider it.

Also, are you sure you ran the existing tests? I have trouble believing they actually passed with no changes given what the Clojure CSV library says about how it handles BOMs

**Comment by dpsutton** [comment]
image
from the unicode spec: https://www.unicode.org/versions/Unicode5.0.0/ch02.pdf#G19273

To me this means this has to be behind some setting. I'm wondering if this is something that even needs a setting override. Something like the following, where the arrow allowed to "Download with Bom" if the BOM wasn't default, and "Download without BOM" if the Bom was defaulted on the instance.
image



As it stands we'd probably much prefer to have the bytes behind some var with an appropriate name
```
(def BOM "\uefbbbf")
...

(.write writer BOM)
```

**Comment by camsaul** [comment]
+1 on what dan said RE putting it in a var as opposed to just using a magic string

**Pull request closed without merging**
