### PR TITLE
Series settings, combo charts, deterministic series colors

### LINKED ISSUE #3242: Allow the user control which series are split on the left and right axis
-  I am using the Google Chrome browser.
-  My computer's OS is macOS Sierra.
-  I'm running Metabase via Docker remotely and it is using the Postgres database.
-  My data is in a Postgres database.
-  My Metabase version is 0.19.3.

I have the following data (series names intentionally cut off, if they are relevant I can anonymize the data and post it like that):

If I select the Line viz type, the chart will look like this; the series with the sudden jump on the right is the first column from the table:

The tooltips seem to suggest that it's an issue with thousands separators:

### LINKED ISSUE #3330: Ability to combine different graph types on single graph
Certain graph types could conceivably be plotted on the same chart. For instance, this chart (which I have defined in Google Sheets) can not currently be constructed in Metabase:

screen shot 2016-09-08 at 1 12 15 pm

Obviously not any graph type can be arbitrarily combined, but at least Line, Bar, and Area charts could conceivably be rendered together.

### LINKED ISSUE #5910: Deterministic color selection
We do a lot of charts and dashboards. We have noticed that the color assignments are non-deterministic w/r/t the value represented. So for instance, a chart that includes a "foo" value might be blue on one chart, and on another chart which also uses "foo" as a value, it might be green.

I suggest that you use a deterministic approach to selecting color assignments based on the represented value, which will yield the following benefits:

 I feel this feature would drastically reduce the cognitive load of interpreting charts, especially when using dashboards.

- dashboards that have multiple widgets will have consistency of how colors are represented by default across widgets
- a chart's colors won't change when sort order is changed
- a chart's colors will be consistent even when values are missing (ie foo=green regardless of whether or not "bar" and "baz" appear in the chart)

The latter seems a bit harder, since you'll have to map colors independently (vs just indexing into a palette). I would certainly settle for nailing the first 2 by hashing values, sorting them, and using those as an index into the color lookup.

Please let me know if I can clarify this.

### LINKED ISSUE #5925: Bar chart colors shuffle when refreshing the chart in dashboard
I have created a dashboard with multiple charts. One of the charts is bar chart and when I refresh the dashboard with a new value each bar gets a random color as below:

screen shot 2017-09-10 at 4 00 42 pm
screen shot 2017-09-10 at 4 01 03 pm

It seems that there are not a setting to set color for each label. Is there any workaround for this? It is very confusing.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves (I think?) #2178 Multi series charts Y-Axis control and Colors of stacked bars
Resolves #3242 Allow the user control which series are split on the left and right axis
Resolves #3330 Ability to combine different graph types on single graph
Resolves #5925 Bar chart colors shuffle when refreshing the chart in dashboard
Resolves #5910 Deterministic color selection

* ~Fix: if you have an existing combo chart saved question with 2 metrics, 1 breakout and try adding another, the only visualization that will show the newly added metric is a table.~ Not a regression in this branch
* [x] Dial in relative thickness of line vs. thickness of bars
* ~If I switch my viz setting from `Line + Bar` to Line, Area, or Bar, I think all my series should be changed to lines, areas or bars.~
* [x] series settings
  * [x] color
  * [x] title
    * [x] propagate to axis titles?
  * [x] display (line, area, bar)
    * [x] need to move line/area charts on top of bars
    * [x] need to ensure lines and bars are aligned when using ordinal axis
  * [x] axis assignment
  * ~goal~
    * [x] add goal label instead of per series goals for now
  * [x] line settings
    * [x] line style
    * [x] show dots
    * [x] missing values
* [x] deal with "stacking" setting
* [x] add a combo chart option that uses both line and bar
  * how to decide which series gets which type?
  * [x] icon (@mazameli)
* [x] deterministic series colors
  * [x] implement deterministic series color assignment function
  * [x] have two tiers of colors, only use extra colors from harmony once main set is exhausted
  * [x] use for other chart types like pie

### CODE REVIEW

**Comment by tlrobinson** [comment]
screenshot 2018-09-17 15 03 24

**Comment by mazameli** [comment]
Looks like color settings and series labels are acting funny when adding data to a dashcard:

add-data-colors-change

**Comment by tlrobinson** [comment]
* dashcard multiseries: first question retain colors, subsequent change
* stacking
  * show stacking option if any are area/bar
  * if stacking enabled disable line/area/bar widget per series, add area/bar widget below
* single series color should key off of metric name?
* series settings broken for single series
* drill through
  * should preserve chart type
  * ~should preserve color~ difficult to know previous "key"
  * multiple metric "zoom" not working correctly

**Comment by MarkRx** [comment]
What do you mean by you are addressing #5910? Are you fixing https://github.com/metabase/metabase/issues/5910#issuecomment-375120530? Are color selections now persisted by value instead of relative order? If so how are you handling the breaking change?

**Comment by tlrobinson** [comment]
@MarkRx Yes, this fixes that issue by deterministically assigning colors based on the "series" name (i.e. the metric name like `Count` or a breakout value like `Success`). It even has logic to intelligently assign green to words like "success" and red to words like "failure" (currently just includes a set of hardcoded mappings but we may add a way to configure it in the future)

Regarding migration, we basically decided if you had changed the colors of a question we should continue to use those, but if you hadn't then we automatically use the new system. Does that seem reasonable to you?

**Comment by tlrobinson** [comment]
>  Fix: if you have an existing combo chart saved question with 2 metrics, 1 breakout and try adding another, the only visualization that will show the newly added metric is a table.

This actually isn't a regression, but it would be nice to fix at some point.

**Comment by MarkRx** [comment]
Yes that makes sense.

**Comment by tlrobinson** [comment]
Last remaining things:

* disable deterministic colors for pie chart for now
* add color mappings for common metrics
  - Count: blue
  - Sum: green
  - Average: purple
  - Distincts: red
* tweak orange color (@kdoh)

**Comment by MarkRx** [comment]
What's the reason for skipping pie charts? They work good for displaying % of status (success, failed, warning, etc) and thus benefit from color control.

**Comment by tlrobinson** [comment]
@MarkRx We think they don't look as good with the more randomly ordered colors, at least for results with lots of slices. I think there are a couple possible solutions:

1. allow the user to change the colors of individual slices to make it look better
2. switch from the deterministic colors to the existing sequential "harmony" above a certain number of slices

We'd like to get this PR merged ASAP which is why we're planning on disabling it for pie charts for now.

**Comment by tlrobinson** [comment]
For reference:

Old (sequential color harmony):

screenshot 2018-10-03 06 30 22

New (deterministic colors):

screenshot 2018-10-03 06 32 17

Old (deterministic colors):

screenshot 2018-10-03 06 30 34

New (deterministic colors):

screenshot 2018-10-03 06 31 48

**Comment by tlrobinson** [comment]
Wait... we do have a way to change the colors:

screenshot 2018-10-03 06 39 51

I guess I had forgotten I added that. @mazameli did you miss that too or was there another reason we wanted to disable it?

I think it might also be a good idea to switch from deterministic colors to sequential color harmony above a certain number of slices, though.

**Comment by MarkRx** [comment]
The pie chart is a special case as I could see colors being assigned by value or by rank / order. The color by order case looks better when you have arbitrary sets of data. That's how it works today. Assigning by value makes sense when data sets have specific semantical meanings. I think both are valid use cases.

Example (Pass/Warn/Fail):
image

**Comment by mazameli** [comment]
If we can fix the height of this input box to match the height of the other elements, and can get the text box to not be blank for single series, then I say let's merge this puppy.

single-series

**Review by kdoh — APPROVED** [review]
Looks good. Left a couple small questions about some comments but thats about it.

**Comment by m3l1k4** [comment]
Hi @MarkRx @tlrobinson I noticed while using metabase, that the color consistency for same categories across pie charts / bar graph still vary. I am guessing this was kept disabled for pie chart?

> What's the reason for skipping pie charts? They work good for displaying % of status (success, failed, warning, etc) and thus benefit from color control.



> @MarkRx We think they don't look as good with the more randomly ordered colors, at least for results with lots of slices. I think there are a couple possible solutions:
> 
> 1. allow the user to change the colors of individual slices to make it look better
> 2. switch from the deterministic colors to the existing sequential "harmony" above a certain number of slices
> 
> We'd like to get this PR merged ASAP which is why we're planning on disabling it for pie charts for now.

**Comment by adjenks** [comment]
@m3l1k4 If you look a few entries above your post, this ticket says that the feature was implemented then removed and then implemented again in pie charts:
https://github.com/metabase/metabase/issues/5857

**Pull request merged**
