### PR TITLE
Fixed the tips with "awhile" in Visualization by using ttag for multi-languages translation. 

### PR DESCRIPTION
**Pull request by AnonyV**
###### Before submitting the PR, please make sure you do the following
- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.
### Tests
-  [ ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by flamber** [comment]
Hi @AnonyV This was already fixed in PR #9659

**Comment by AnonyV** [comment]
> 
> 
> Hi @AnonyV This was already fixed in PR #9659

Hi flamber,
i think that PR #9659 caused the problems on other language's msgid to msgstr

**Comment by flamber** [comment]
@AnonyV Okay, so this PR is reverting that change? What problem is caused by #9659?

**Comment by AnonyV** [comment]
> 
> 
> @AnonyV Okay, so this PR is reverting that change? What problem is caused by #9659?

@flamber the tips in visualization must like this in chinese(the same as msgstr):
图片

but that caused the t`xxx` could not reflect msgid to the right msgstr with other languages , just like this:
图片

**Comment by mazameli** [comment]
The problem you're seeing is likely simply because the new string hasn't yet been translated and updated in [POEditor](https://poeditor.com/join/project/ynjQmwSsGh), the tool we use for community translations. Before version 0.33 comes out, we'll ask everyone to update the new and changed text throughout the product. The best way you could help this issue would be to join the POEditor project and help us keep the Chinese translation up-to-date!

 But I'm closing this PR because it would result in [incorrect grammar](https://www.quickanddirtytips.com/education/grammar/while-versus-awhile) for English. Thank you for your contribution.

**Comment by flamber** [comment]
@mazameli It seems like the POEditor is not updated with the new "a while" - can you take a look?
https://poeditor.com/projects/po_edit?order=&filter=&id=200535&id_language=31&search=but+seems+to+be+taking

**Comment by mazameli** [comment]
Yeah, it's likely that the "a while" fix got merged and then included in a point release, but we only tend to update POEditor and solicit updated translations from the community for major releases.

**Pull request closed without merging**
