### PR TITLE
User nicer modals for alerts

### LINKED ISSUE #3516: Improve the modal message when trying to add a group that already exists
Right now we're just showing a system modal, which is fugly. This is low priority, relatively speaking, though.

screen shot 2016-10-11 at 1 50 52 pm

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3516

### CODE REVIEW

**Comment by tlrobinson** [comment]
@mazameli Did you have a design in mind for this. Most of our modals have both a title and body text, but for alert we only need one. I had a little trouble getting it to look good.

**Comment by mazameli** [comment]
I think we could be a little fun and say in the title:
"There's already a group with that name"

And the body:
"It must be a really good name."

**Comment by mazameli** [comment]
If we're just looking for a generic, one-line alert style, I think we already have one:

add a group - filled in

Text css (just to give you an idea which already-existing class(es) to use):
```
font-family: Lato-Bold;
font-size: 22px;
color: #4C545B;
```

**Comment by tlrobinson** [comment]
Updated screenshot 2016-10-15 13 11 17

**Comment by tlrobinson** [comment]
@mazameli does this look ok?

**Comment by mazameli** [comment]
Yep, looks fine to me.

**Pull request merged**
