### PR TITLE
Save transient dashboard as a new (sub) collection

### PR DESCRIPTION
**Pull request by sbelak**
This:
1) changes the dashboard save API to:
`POST /api/dashboard/save/collection/:parent-collection-id`
2) creates a new collection with parent `:parent-collection-id` named the same as the dashboard
3) saves the [x-ray] dashboard and cards into it
4) pins the dashboard

If a collection with the same name already exists, a number is appended to the name (eg. `A look at your Orders table 2`). Should the names be globally unique or only within the parent collection?

Anyone with write permissions to `:parent-collection-id` can save a dashboard to it.

### CODE REVIEW

**Comment by sbelak** [comment]
Added back endpoint `POST /api/dashboard/save` which picks the parent collection based on the following logic:
Admins save dashboards into an "autogenerated" collection in the root folder,
Normal users save them into their personal folder

**Comment by salsakran** [comment]
couple of things -
1. I don't get a "save this" button as a non-admin in the FE, so that bit of logic should be removed
2. I see the folder with an autogenerated dashboard in the root folder, not a folder named "Automatically Generated Dashboards" (or something similar)

**Comment by sbelak** [comment]
Should the folder in both cases (admin and not) be placed in the intermediary "Automatically Generated Dashboards", or just if placed in root folder?

**Comment by salsakran** [comment]
for admins, place it in a `Automatically Generated Dashboards` folder, for normal users, put it in their personal collection?

**Comment by salsakran** [comment]
The backend is still returning a permissions error when a non-admin user hits  `/api/dashboard/save`

**Pull request merged**
