### PR TITLE
Hide column types and migrate JS functions working with them

### PR DESCRIPTION
**Pull request by metamben**
Part of #30054.

Effective and semantic type information are removed from display-info.
This forces the user of the API to use explicit type checks using the new function isa.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)

### CODE REVIEW

**Review by metamben — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @metamben)

___
*[`src/metabase/lib/metadata/calculation.cljc` line 406 at r1](https://reviewable.io/reviews/metabase/metabase/30146#-NTEugkW19Pl6JOJrAFp:-NTEugkW19Pl6JOJrAFq:b-nc5nck) ([raw file](https://github.com/metabase/metabase/blob/fc4b2ca9c1e91d34b1c81c59e14ff7c43f6d0d2f/src/metabase/lib/metadata/calculation.cljc#L406)):*
> ```Clojure
>   [{:keys [effective_type semantic_type] :as _column} type-kw]
>   (or (isa? effective_type type-kw)
>       (isa? semantic_type type-kw)))
> ```

Is this implementation overly simplistic?

**Review by bshepherdson — CHANGES_REQUESTED** [review]
Should add this new function to `lib.js` as well.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146#-:-NTFDCAF2S-sxN0YB-NK:bo94nsc)* status: all files reviewed, 2 unresolved discussions (waiting on @metamben)

___
*[`src/metabase/lib/core.cljc` line 159 at r2](https://reviewable.io/reviews/metabase/metabase/30146#-NTFCk8P29ys-zpiuY8N:-NTFCk8P29ys-zpiuY8O:b-kr0hg4) ([raw file](https://github.com/metabase/metabase/blob/3cf7fc712405cd2e9ffd559e9ed1082e25d04c47/src/metabase/lib/core.cljc#L159)):*
> ```Clojure
>    display-name
>    display-info
>    isa
> ```

`isa?` there's precedent for this spelling in both `clojure.core` and Metabase.
___
*[`src/metabase/lib/metadata/calculation.cljc` line 406 at r1](https://reviewable.io/reviews/metabase/metabase/30146#-NTEugkW19Pl6JOJrAFp:-NTFDMtp12JoLnqPxNA7:b-6gf7ei) ([raw file](https://github.com/metabase/metabase/blob/fc4b2ca9c1e91d34b1c81c59e14ff7c43f6d0d2f/src/metabase/lib/metadata/calculation.cljc#L406)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Is this implementation overly simplistic?
</blockquote></details>

I think it's fine to start with. We can expand it if we discover gaps.

**Review by metamben — COMMENTED** [review]
Where is that?

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146#-:-NTFI4TY2WLQ5sQQrrqr:bj5h08w)* status: all files reviewed, 2 unresolved discussions (waiting on @bshepherdson and @camsaul)

___
*[`src/metabase/lib/core.cljc` line 159 at r2](https://reviewable.io/reviews/metabase/metabase/30146#-NTFCk8P29ys-zpiuY8N:-NTFGD3TCjywFaCtEsmA:b-yhi0mm) ([raw file](https://github.com/metabase/metabase/blob/3cf7fc712405cd2e9ffd559e9ed1082e25d04c47/src/metabase/lib/core.cljc#L159)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

`isa?` there's precedent for this spelling in both `clojure.core` and Metabase.
</blockquote></details>

@camsaul suggested `isa`. I'm not quite sure what his reasons were. I don't think we like "special" characters in JS world (like `isa_QMARK_) and having different names in CLJ(S) and JS is not nice either.
___
*[`src/metabase/lib/metadata/calculation.cljc` line 406 at r1](https://reviewable.io/reviews/metabase/metabase/30146#-NTEugkW19Pl6JOJrAFp:-NTFIInRDYIidNGWtVWl:ba7gsu2) ([raw file](https://github.com/metabase/metabase/blob/fc4b2ca9c1e91d34b1c81c59e14ff7c43f6d0d2f/src/metabase/lib/metadata/calculation.cljc#L406)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

I think it's fine to start with. We can expand it if we discover gaps.
</blockquote></details>

Looking at `isa.js` I think it is overly simplistic. I wonder if this should be a kind of port of `isFieldType`

**Review by bshepherdson — CHANGES_REQUESTED** [review]
Sorry, I mean to `metabase.lib.js`, in `src/metabase/lib/js.cljs`.

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146#-:-NTFgCryBvINTRrFCoKM:b-ge7l1t)* status: all files reviewed, 2 unresolved discussions (waiting on @camsaul and @metamben)

___
*[`src/metabase/lib/core.cljc` line 159 at r2](https://reviewable.io/reviews/metabase/metabase/30146#-NTFCk8P29ys-zpiuY8N:-NTFgM8v-ySk4fwahrl_:bftsl7j) ([raw file](https://github.com/metabase/metabase/blob/3cf7fc712405cd2e9ffd559e9ed1082e25d04c47/src/metabase/lib/core.cljc#L159)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

@camsaul suggested `isa`. I'm not quite sure what his reasons were. I don't think we like "special" characters in JS world (like `isa_QMARK_) and having different names in CLJ(S) and JS is not nice either.
</blockquote></details>

The names we'll actually use in JS are determined by the wrapper functions, probably `isA()` in this case.

If it was `isa?` in `metabase.lib.metadata.calculation` and `metabase.lib.js`, and then in the TS wrapper it would be
```typescript
export function isA(typeName: string): boolean {
  return ML.isa_QMARK_(typeName);
}
```
which is acceptable to me. That's the only place the mangled name would appear. Then we have idiomatic names in both languages.
___
*[`src/metabase/lib/metadata/calculation.cljc` line 406 at r1](https://reviewable.io/reviews/metabase/metabase/30146#-NTEugkW19Pl6JOJrAFp:-NTFmVyNB7BTXoaI-BS_:b-r8jxt1) ([raw file](https://github.com/metabase/metabase/blob/fc4b2ca9c1e91d34b1c81c59e14ff7c43f6d0d2f/src/metabase/lib/metadata/calculation.cljc#L406)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Looking at `isa.js` I think it is overly simplistic. I wonder if this should be a kind of port of `isFieldType`
</blockquote></details>

Ah, I'd forgotten about that file. I think most of it is captured by the hierarchy in the Clojure code. I guess adapt the tests for that old file into new CLJC tests and make sure all the same cases are covered.

**Review by metamben — COMMENTED** [review]
Hmm. It should be there.

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146#-:-NTFndlT8AKpV3pZMmTh:bcjujga)* status: all files reviewed, 2 unresolved discussions (waiting on @bshepherdson and @camsaul)

___
*[`src/metabase/lib/core.cljc` line 159 at r2](https://reviewable.io/reviews/metabase/metabase/30146#-NTFCk8P29ys-zpiuY8N:-NTFnuDs98b2N4kM94gV:bf46hgm) ([raw file](https://github.com/metabase/metabase/blob/3cf7fc712405cd2e9ffd559e9ed1082e25d04c47/src/metabase/lib/core.cljc#L159)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

The names we'll actually use in JS are determined by the wrapper functions, probably `isA()` in this case.

If it was `isa?` in `metabase.lib.metadata.calculation` and `metabase.lib.js`, and then in the TS wrapper it would be
```typescript
export function isA(typeName: string): boolean {
  return ML.isa_QMARK_(typeName);
}
```
which is acceptable to me. That's the only place the mangled name would appear. Then we have idiomatic names in both languages.
</blockquote></details>

I'm not against that. I'm porting `isa.js` and it would look ugly in both worlds if we tried to stick to the same name.
___
*[`src/metabase/lib/metadata/calculation.cljc` line 406 at r1](https://reviewable.io/reviews/metabase/metabase/30146#-NTEugkW19Pl6JOJrAFp:-NTFoCaWEKD4rLtQUOrl:b-lup8mq) ([raw file](https://github.com/metabase/metabase/blob/fc4b2ca9c1e91d34b1c81c59e14ff7c43f6d0d2f/src/metabase/lib/metadata/calculation.cljc#L406)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Ah, I'd forgotten about that file. I think most of it is captured by the hierarchy in the Clojure code. I guess adapt the tests for that old file into new CLJC tests and make sure all the same cases are covered.
</blockquote></details>

Doing that right now. (Although `isa.js`, well, in fact `metabase-lib/types/constants.js` seems to define another type hierarchy too, along with some exotic (to my eyes) logic.)

**Review by bshepherdson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: all files reviewed, 1 unresolved discussion (waiting on @camsaul)

___
*[`src/metabase/lib/core.cljc` line 159 at r2](https://reviewable.io/reviews/metabase/metabase/30146#-NTFCk8P29ys-zpiuY8N:-NTKE35w5yvyNNWuKGHU:b-mvsn11) ([raw file](https://github.com/metabase/metabase/blob/3cf7fc712405cd2e9ffd559e9ed1082e25d04c47/src/metabase/lib/core.cljc#L159)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

I'm not against that. I'm porting `isa.js` and it would look ugly in both worlds if we tried to stick to the same name.
</blockquote></details>

Are you planning to make this change?

**Review by metamben — COMMENTED** [review]
I haven't added things to `src/metabase/lib/js.cljs`, since no conversions are needed. What advantage would it have adding them there?

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146#-:-NTPUb0e38dUG7MUt13V:bb87qw)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @bshepherdson and @camsaul)

___
*[`src/metabase/lib/types/constants.cljc` line 44 at r3](https://reviewable.io/reviews/metabase/metabase/30146#-NTPVVQwAT5bwNODmNwI:-NTPVVQwAT5bwNODmNwJ:b-9olvxm) ([raw file](https://github.com/metabase/metabase/blob/a7ae97b994f84cff15fab6919b2cea711c7d8bf2/src/metabase/lib/types/constants.cljc#L44)):*
> ```Clojure
>    COORDINATE  {:semantic_type [:type/Coordinate]}
>    LOCATION    {:semantic_type [:type/Address]}
>    ::entity    {:semantic_type [:type/FK :type/PK :type/Name]}
> ```

This was not exported by the JS source, so I keep it internal.
___
*[`src/metabase/lib/types/constants.cljc` line 55 at r3](https://reviewable.io/reviews/metabase/metabase/30146#-NTPVf6n02lJ4707NzEQ:-NTPVf6n02lJ4707NzER:b3uf0r3) ([raw file](https://github.com/metabase/metabase/blob/a7ae97b994f84cff15fab6919b2cea711c7d8bf2/src/metabase/lib/types/constants.cljc#L55)):*
> ```Clojure
>                 :include        [LOCATION]}
>    ;; NOTE: this is defunct right now.  see definition of metabase.lib.types.isa/dimension?.
>    ::dimension {:include [TEMPORAL CATEGORY ::entity]}})
> ```

This was not exported by JS either.
___
*[`src/metabase/lib/types/isa.cljc` line 14 at r3](https://reviewable.io/reviews/metabase/metabase/30146#-NTPY9cDAEdOUcFcVgz1:-NTPY9cDAEdOUcFcVgz2:bqubxcn) ([raw file](https://github.com/metabase/metabase/blob/a7ae97b994f84cff15fab6919b2cea711c7d8bf2/src/metabase/lib/types/isa.cljc#L14)):*
> ```Clojure
>   [{:keys [effective_type semantic_type] :as _column} type-kw]
>   (or (clojure.core/isa? effective_type type-kw)
>       (clojure.core/isa? semantic_type type-kw)))
> ```

I'm not sure how useful this logic is. The predicates below do worry about checking the right property and there is some overlap between `:type/*` and `:Semantic/*` types.
___
*[`src/metabase/lib/types/isa.cljc` line 247 at r3](https://reviewable.io/reviews/metabase/metabase/30146#-NTPWCaQ7rSlSLZ_COp6:-NTPWCaQ7rSlSLZ_COp7:behh4sh) ([raw file](https://github.com/metabase/metabase/blob/a7ae97b994f84cff15fab6919b2cea711c7d8bf2/src/metabase/lib/types/isa.cljc#L247)):*
> ```Clojure
>       ;; comment from isa.js:
>       ;; > FIXME: columns of nested questions at this moment miss table_id value
>       ;; > which makes it impossible to match them with their tables that are nested cards
> ```

Can we do better now?
___
*[`test/metabase/lib/types/isa_test.cljc` line 60 at r3](https://reviewable.io/reviews/metabase/metabase/30146#-NTPYqRY5T97c4lHedUf:-NTPYqRY5T97c4lHedUg:b-4kixz5) ([raw file](https://github.com/metabase/metabase/blob/a7ae97b994f84cff15fab6919b2cea711c7d8bf2/test/metabase/lib/types/isa_test.cljc#L60)):*
> ```Clojure
>                 (columns-of-type :Relation/*))))))
> 
> (deftest ^:parallel field-type-test
> ```

This is the only test in the JS version. It implicitly tests `field-type?` too.
___
*[`src/metabase/lib/core.cljc` line 159 at r2](https://reviewable.io/reviews/metabase/metabase/30146#-NTFCk8P29ys-zpiuY8N:-NTPV7M34SWENnGEX3Z9:bn0zigp) ([raw file](https://github.com/metabase/metabase/blob/3cf7fc712405cd2e9ffd559e9ed1082e25d04c47/src/metabase/lib/core.cljc#L159)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Are you planning to make this change?
</blockquote></details>

Here is is.

**Review by metamben — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @bshepherdson and @camsaul)

___
*[`src/metabase/lib/types/isa.cljc` line 1 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPr919CUxvhLD7rrDD:-NTPr919CUxvhLD7rrDE:bi8gyce) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/isa.cljc#L1)):*
> ```Clojure
> (ns metabase.lib.types.isa
> ```

`base_type` is not handled. My understanding is that this logic should not depend on it. (I think the JS code treated them interchangebly.)

**Review by bshepherdson — CHANGES_REQUESTED** [review]
Makes sense.

> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146#-:-NTPsC7w3BmRSWy1k8Up:b-dxcbts)* status: all files reviewed, 10 unresolved discussions (waiting on @metamben)

___
*[`src/metabase/lib/types/constants.cljc` line 12 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPvnzR5L0aLjwa8IoT:-NTPvnzR5L0aLjwa8IoU:b45h) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L12)):*
> ```Clojure
>      (reduce (fn [m typ] (doto m (gobj/set (name typ) typ)))
>              #js {}
>              (distinct (mapcat descendants [:type/* :Semantic/* :Relation/*])))))
> ```





_Suggestion:_
```Clojure
     (->> (mapcat descendants [:type/* :Semantic/* :Relation/*])
          distinct
          (m/index-by name)
          clj->js)))
```
___
*[`src/metabase/lib/types/constants.cljc` line 15 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPu89F3B1wPwnuiJtl:-NTPu89F3B1wPwnuiJtm:b-b8tyxp) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L15)):*
> ```Clojure
> 
> ;; primary field types used for picking operators, etc
> (def ^:export NUMBER "JS-friendly access for the number type" ::number)
> ```

I don't like seeing these JS-style constants in CLJC. We're striving to make the library idiomatic in both languages. 

So I think the Clojure code should use `::lib.types.constants/number` not `lib.types.constants/NUMBER`. The JS code should use 
```typescript
import { keyword } from "cljs/cljs.core";
export const NUMBER = keyword("metabase.lib.types.constants" "number");
```
if it needs these individual constants.

`TYPE` is needed, but I'd argue for a name like `types-by-name`. The TS wrapper can `export const TYPE = ML.types_by_name;` if needed.
___
*[`src/metabase/lib/types/isa.cljc` line 221 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPtP3PCCbMMepQEEOL:-NTPtP3PCCbMMepQEEOM:b-jx230o) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/isa.cljc#L221)):*
> ```Clojure
> 
> (defn ^:export email?
>   "Is `column` a comment?"
> ```

Wrong comment?
___
*[`src/metabase/lib/types/isa.cljc` line 231 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPtMrh7uKbeLF01UZw:-NTPtMrh7uKbeLF01UZx:b-jx230o) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/isa.cljc#L231)):*
> ```Clojure
> 
> (defn ^:export image-URL?
>   "Is `column` a comment?"
> ```

Wrong comment?

**Review by metamben — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: all files reviewed, 10 unresolved discussions (waiting on @bshepherdson and @metamben)

___
*[`src/metabase/lib/types/constants.cljc` line 12 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPvnzR5L0aLjwa8IoT:-NTQ7p2w9z04lq3Rw11j:b-yzrbul) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L12)):*
> ```Clojure
>      (reduce (fn [m typ] (doto m (gobj/set (name typ) typ)))
>              #js {}
>              (distinct (mapcat descendants [:type/* :Semantic/* :Relation/*])))))
> ```

I think `clj->js` is not what we want. We want to keep the values as keywords (i.e., opaque).
___
*[`src/metabase/lib/types/constants.cljc` line 15 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPu89F3B1wPwnuiJtl:-NTQ8hul7Q9bZGwoyJtK:b9zjrkn) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L15)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

I don't like seeing these JS-style constants in CLJC. We're striving to make the library idiomatic in both languages. 

So I think the Clojure code should use `::lib.types.constants/number` not `lib.types.constants/NUMBER`. The JS code should use 
```typescript
import { keyword } from "cljs/cljs.core";
export const NUMBER = keyword("metabase.lib.types.constants" "number");
```
if it needs these individual constants.

`TYPE` is needed, but I'd argue for a name like `types-by-name`. The TS wrapper can `export const TYPE = ML.types_by_name;` if needed.
</blockquote></details>

Wouldn't "advertising" `keyword` make these types less opaque? I don't like too much that the TS wrapper and the CLJC code have to agree on how these types are encoded. Also, in the case of this namespace, I don't worry too much about making it idiomatic in CLJ: I don't expect it to be really used. It's mostly here, so that we can change it if necessary.
___
*[`src/metabase/lib/types/isa.cljc` line 221 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPtP3PCCbMMepQEEOL:-NTQ9ahjBj_jARm6sJ9V:b-834n6i) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/isa.cljc#L221)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Wrong comment?
</blockquote></details>

Oops.
___
*[`src/metabase/lib/types/isa.cljc` line 231 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPtMrh7uKbeLF01UZw:-NTQ9gwA9WDamscjriA3:bxfg9b8) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/isa.cljc#L231)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Wrong comment?
</blockquote></details>

Oops.

**Review by bshepherdson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @metamben)

___
*[`src/metabase/lib/types/constants.cljc` line 12 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPvnzR5L0aLjwa8IoT:-NTUXp2z5LCtijRE_JEd:b-3ldsg3) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L12)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

I think `clj->js` is not what we want. We want to keep the values as keywords (i.e., opaque).
</blockquote></details>

Ah, good point. We should probably turn this into a helper, but it's fine to leave it here for now.
___
*[`src/metabase/lib/types/constants.cljc` line 15 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPu89F3B1wPwnuiJtl:-NTUY1g1CQFNqHYpR5AH:b-7y0hva) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L15)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Wouldn't "advertising" `keyword` make these types less opaque? I don't like too much that the TS wrapper and the CLJC code have to agree on how these types are encoded. Also, in the case of this namespace, I don't worry too much about making it idiomatic in CLJ: I don't expect it to be really used. It's mostly here, so that we can change it if necessary.
</blockquote></details>

I don't think there's a "good" option here, so I'm trying to pick the "least bad" option.

I'm standing firm on this point: in CLJC we should not be importing or using these `NUMBER` symbols; we should be using literal keywords. That includes in `type-hierarchies` below.

On the other point of using `keyword` from TS vs. exporting them from CLJC, I could be persuaded. I view `frontend/src/metabase-lib/` as a grey area with one foot in each world, so knowing about CLJS keywords is allowed. (It's already aware of the CLJC namespaces and vars, that the var names are different from the TS function names, and the name mangling.) On the other hand it makes them harder to search for in CLJC if you're trying to rename some keyword.

Perhaps this as a compromise:
```clojure
#?(:cljs
  (do
    (def ^:export key-string "JS-friendly access for the string type" ::string)
    ,,,))
```
then they're (a) CLJS only; (b) not used anywhere in the CLJC files; (c) have idiomatic Clojure names; (d) can be re-exported `export const STRING = ML.key_string;` in TS.

**Review by bshepherdson — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @metamben)

**Review by metamben — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @bshepherdson)

___
*[`src/metabase/lib/types/constants.cljc` line 15 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPu89F3B1wPwnuiJtl:-NTUqjiM2Y6D-3GKtH3L:b-plqbe6) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L15)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

I don't think there's a "good" option here, so I'm trying to pick the "least bad" option.

I'm standing firm on this point: in CLJC we should not be importing or using these `NUMBER` symbols; we should be using literal keywords. That includes in `type-hierarchies` below.

On the other point of using `keyword` from TS vs. exporting them from CLJC, I could be persuaded. I view `frontend/src/metabase-lib/` as a grey area with one foot in each world, so knowing about CLJS keywords is allowed. (It's already aware of the CLJC namespaces and vars, that the var names are different from the TS function names, and the name mangling.) On the other hand it makes them harder to search for in CLJC if you're trying to rename some keyword.

Perhaps this as a compromise:
```clojure
#?(:cljs
  (do
    (def ^:export key-string "JS-friendly access for the string type" ::string)
    ,,,))
```
then they're (a) CLJS only; (b) not used anywhere in the CLJC files; (c) have idiomatic Clojure names; (d) can be re-exported `export const STRING = ML.key_string;` in TS.
</blockquote></details>

Would we use these names (e.g., `key-string`) at all? I used the names defined in CLJC (instead of just using the keywords) to ensure consistency. If the names are not used everywhere, then why not make it JS friendly (i.e., `STRING`) right away?

**Review by metamben — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @bshepherdson)

___
*[`src/metabase/lib/types/constants.cljc` line 15 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPu89F3B1wPwnuiJtl:-NTUrzNm1J2DjCzv9XSP:bx88tso) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L15)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Would we use these names (e.g., `key-string`) at all? I used the names defined in CLJC (instead of just using the keywords) to ensure consistency. If the names are not used everywhere, then why not make it JS friendly (i.e., `STRING`) right away?
</blockquote></details>

What about the compromise
```clojure
#?(:cljs
  (do
    (def ^:export STRING "JS-friendly access for the string type" ::string)
    ,,,))
```
then they're (a) CLJS only; (b) not used anywhere in the CLJC files; (c) don't have idiomatic Clojure names; (d) don't have to be re-exported in TS.

**Review by metamben — COMMENTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: all files reviewed, 7 unresolved discussions (waiting on @bshepherdson)

**Review by bshepherdson — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30146)* status: all files reviewed, 6 unresolved discussions (waiting on @metamben)

___
*[`src/metabase/lib/types/constants.cljc` line 15 at r4](https://reviewable.io/reviews/metabase/metabase/30146#-NTPu89F3B1wPwnuiJtl:-NTVbg5P04RI__T62C54:b-vs1pr4) ([raw file](https://github.com/metabase/metabase/blob/b5db860a08101a8b07de0203e8e0ec5fd7bce801/src/metabase/lib/types/constants.cljc#L15)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

What about the compromise
```clojure
#?(:cljs
  (do
    (def ^:export STRING "JS-friendly access for the string type" ::string)
    ,,,))
```
then they're (a) CLJS only; (b) not used anywhere in the CLJC files; (c) don't have idiomatic Clojure names; (d) don't have to be re-exported in TS.
</blockquote></details>

Looks good.

**Pull request merged**
