### PR TITLE
Remove user id / query hash from SQL on BigQuery driver

### LINKED ISSUE #8539: Metabase is not using the BigQuery cache by question
The Metabase is not using the BigQuery cache by question, instead, it is used by the user / question.

BigQuery generates a hash for each SQL (including the comments), when Metabase injects the user id in a query, the hash changes and the BigQuery caches the SQL result per user/question.

This increases the expenses a lot, especially for the companies that have many active users.

[SQL user id injection](https://github.com/metabase/metabase/blob/master/src/metabase/driver/bigquery.clj#L539)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by berna-code**
Fixes: https://github.com/metabase/metabase/issues/8539

Remove sql comment (User id and Question hash) from BigQuery driver to guarantee that the cache will be by question.

### CODE REVIEW

**Comment by renanleme** [comment]
@bern4rdelli Vi o Pr, mas fiquei em dúvida, não tem test nos drivers?

**Comment by camsaul** [comment]
Sorry, did not mean to close this, GH did it automatically when I deleted a stale branch

We're still discussing whether we want to merge this, we do have some people who use the `userID` info in the comments (which was why we added it in the first place). I think we would want to make it configurable rather than removing it entirely.

**Review by camsaul — CHANGES_REQUESTED** [review]
We should make this configurable with an admin setting rather than removing entirely

**Comment by sabino** [comment]
@camsaul I've just made it as a configurable option

**Comment by sabino** [comment]
Can you review this @senior @camsaul ?

**Comment by shahzadbykea** [comment]
@camsaul @senior Can you please review this? This is a much needed feature in the next release.

**Comment by gabubellon** [comment]
@camsaul @senior  Please, Any expectation to review this ? This is a much needed feature too ! We are using a "custom" version to workaround this.

**Comment by sabino** [comment]
Hey @camsaul.

Is it possible to approve this? It is a simple change and the default value is enabled, so comments get added by default there should be no side effects.

Here is how it looks:
image

**Review by camsaul — CHANGES_REQUESTED** [review]
I think the basic functionality makes sense but we need to add a test to make sure this setting actually does what it says

**Review by mazameli — CHANGES_REQUESTED** [review]

**Comment by sabino** [comment]
@mazameli I've updated the texts as requested.

@camsaul Not sure if this test is enough, let me know what you think.

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
@camsaul Have you had a chance to review the test that was added to this?

**Comment by sabino** [comment]
Not sure why not all tests are running.
Can you check if everything is ok @camsaul?

Seems to be working as expected:
image

**Comment by sabino** [comment]
Well, this PR is 2 years old now.

**Review by camsaul — APPROVED** [review]
Overall this looks good to me. Tests against BigQuery don't normally run for 3rd-party PRs so I opened PR #13923 to run those tests and make a few minor tweaks to code style. If those tests pass, we can merge this.

**Comment by camsaul** [comment]
Merged as part of #13923

**Pull request closed without merging**
