### PR TITLE
Fix small typo in api doc

### PR DESCRIPTION
**Pull request by rodo**
Very small typo fixes

### CODE REVIEW

**Comment by salsakran** [comment]
@rodo Thanks for helping out! 

That file is autogenerated from our api endpoints, so if you wish to remove the umlat, you should change the source of that line in https://github.com/metabase/metabase/blob/master/src/metabase/api/user.clj#L47

I suspect @camsaul put that in there as a joke =)

**Comment by camsaul** [comment]
@salsakran that's a [diaeresis](https://en.wikipedia.org/wiki/Diaeresis), not an umlaut! It's there to tell you the word is pronounced re-act rather than rayct. Although I'm sure noöne is making that mistake so we don't really need it

**Comment by rodo** [comment]
Thanks @salsakran, just did it in f0ecb8e

**Comment by salsakran** [comment]
thanks @rodo !

**Pull request merged**
