### PR TITLE
fix dash height

### LINKED ISSUE #4952: Dashboards shouldn't have unnecessary padding
There is extra padding at the bottom of dashboards that doesn't need to be there. @attekei told me: "it’s basically because the QB and dashboard currently (unnecessarily) share the same styles and QB has some special requirements [I think for spacing visualizations]."

**Notice the scrollbar here:**

screen shot 2017-05-03 at 12 03 08 pm

**There should be padding below the last cards, but not this much. Should be more like how much margin/padding there is on the left and right:**

screen shot 2017-05-03 at 12 03 37 pm

### PR DESCRIPTION
**Pull request by kdoh**
fixes #4952

### CODE REVIEW

**Review by mazameli — COMMENTED** [review]
Fix works great. Only thing I noticed was I was getting an error on saved questions on dashboards, but that might not be due to your changes:

```
Syntax error in SQL statement "SELECT ""QUERY_CACHE"".""RESULTS"", ""QUERY_CACHE"".""UPDATED_AT"" FROM ( )[*] WHERE (""QUERY_HASH"" = ? AND ""UPDATED_AT"" >= ?) LIMIT 1"; expected "identifier"; SQL statement: SELECT "QUERY_CACHE"."RESULTS", "QUERY_CACHE"."UPDATED_AT" FROM ( ) WHERE ("QUERY_HASH" = ? AND "UPDATED_AT" >= ?) LIMIT 1 [42001-194]
```

**Comment by kdoh** [comment]
@mazameli I'm not seeing that error anywhere. Any more context for how / why it popped up? Nothing about changing CSS should create an issue like that.

**Comment by tlrobinson** [comment]
BTW changing the base doesn't automatically rebase your changes, so this PR now has some unrelated commits from `master`.

**Comment by kdoh** [comment]
@tlrobinson Whoops yeah missed that. Rebase incoming.

**Pull request merged**
