### PR TITLE
Collection sidebar: expand/collapse children when clicking on parent collection name

### LINKED ISSUE #17339: Collections aren't correctly expanding and collapsing in the sidebar on master
A collection is supposed to expand in the sidebar when it's clicked, revealing all of its immediate subcollections, and then should collapse when clicked again. I'm seeing this on master and on our Stats instance.

## Current behavior

no-expansion

## Expected (40.2)

collapsable

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #17339

## How to Test

1. Have nested collections.

2. Go to a collections page

3. Click on the title of a collection that has children.

The collection should reveal its children.

4. Click again on the title of the parent collection above.

The collection should hide its children.

### CODE REVIEW

**Comment by mazameli** [comment]
👀

**Comment by mazameli** [comment]
Only one thing I noticed: I think that if any sub-collections of a parent collection are expanded, when the parent collection is collapsed and then expanded again, all of its children should be _collapsed_, not expanded. That's the behavior of Notion, for example. 

This is how it's currently working for me in the branch:

https://share.getcloudapp.com/NQuYY8bj

**Comment by gusaiani** [comment]
> Only one thing I noticed: I think that if any sub-collections of a parent collection are expanded, when the parent collection is collapsed and then expanded again, all of its children should be collapsed, not expanded

Gotcha, looking into it.

**Comment by gusaiani** [comment]
For ease of review, I've started a different PR to solve what @mazameli asks for above: https://github.com/metabase/metabase/pull/17703

So this is reviewable in its own right.

**Review by mazameli — APPROVED** [review]
Looks good to me once https://github.com/metabase/metabase/pull/17703 is merged into this branch. 👍🏼

**Pull request merged**
