### PR TITLE
🍒 Remove db paging (#16990)

### PR DESCRIPTION
**Pull request by nemanjaglumac**
Cherry-picks 5096cef1853d7451998181eeb485fe15f14095ec (#16990) from the `release` branch to the `master`.

### CODE REVIEW

**Review by howonlee — COMMENTED** [review]
~~investigating failing tests, I can replicate on my machine~~

i get _different_ test failures, not the timeout

**Comment by nemanjaglumac** [comment]
> investigating failing tests, I can replicate on my machine

But you _could_ replicate some failures @howonlee ? Were they related to the fix?

**Comment by howonlee** [comment]
I think they're stemming from a misconfig of mysql on my box, actually. This may still be a flake

**Comment by nemanjaglumac** [comment]
If you figure out something might be weird with the change that was introduced in the original PR, does it make sense to revert it on `release` branch and issue a more polished version to the `master`?

If it's just an unrelated flake, then forget what I said.

**Review by howonlee — APPROVED** [review]
flake flake flake it did, it flaked

otherwise it looks same as on the release branch

**Pull request merged**
