### PR TITLE
"Delete this alert" button is not translated, and not centered in button

### LINKED ISSUE #24156: "Delete this alert" button is not translated, and not centered in button
**Describe the bug**
In the alert editing modal in the query builder, the section for deleting an alert looks a bit weird when the user language is German. The "Delete this Alert" text is not translated, and the button is stretched vertically but the text is not centered.

**To Reproduce**
1. Log in as an admin
2. Change your user language to German (I'm assuming this is an issue for other languages too but I haven't checked)
3. Create an alert for a question
4. Open the alert modal and scroll down to the "Danger Zone"

**Screenshots**
image

**Information about your Metabase Installation:**
Current master

**Severity**
Mild

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #24156 

###### Before submitting the PR, please make sure you do the following

- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### Demo
https://www.loom.com/share/18dbf14c9b734faba86b1b8a4e4d396b

### CODE REVIEW

**Comment by gitstart** [comment]
The translation for "Delete this Alert" does't exist thats why in German the text is still shown in english
But  translations for "Delete this alert" exists which fixes the issue of translation

**Comment by flamber** [comment]
Translations are handled via POEditor, but that string was not using the correct syntax (https://www.metabase.com/docs/latest/developers-guide/internationalization.html) until #24002, and since that went in after translations was updated, then that's why it's not translated currently.

But in this case, it's fine to accept this PR, since there's no reason to have the same sentence with different casings.

**Comment by gitstart** [comment]
While working on this, it was discovered that the button height increases to match paragraph text
Screen Shot 2022-07-25 at 5 06 53 PM
Maybe the button size should not increase based on paragraph height but based on just button text. If this is the case, should this be handled in this PR or create a different issue? cc: @flamber

**Comment by flamber** [comment]
I would guess it's just some flex-shrink that should be applied to the classes. In this PR is fine, since the issue is about both problems.

**Comment by gitstart** [comment]
@flamber PR has been updated with the fix for button as well.

**Pull request closed without merging**
