### PR TITLE
Ensure we use mbqlEq when comparing 'time-interval' MBQL clauses

### LINKED ISSUE #4231: Relative date filters not displayed correctly in query builder
Both on master and `release-0.22.1`, this is what I'm seeing when applying any relative filter to any GUI query, though the query and filter work correctly:

screen shot 2017-01-25 at 10 50 59 am

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #4231

More info in #4233

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers Review please. This should go in 0.22.1

**Review by kdoh — APPROVED** [review]
Looks good. Any thoughts on how we can try and minimize drift like this going forward?

**Review by salsakran — APPROVED** [review]
given that we're using mbEql elsewhere, this is 👍 
I'm with Kyle in thinking this seems error prone in general

**Comment by tlrobinson** [comment]
@kdoh Just don't use `===` when dealing with MBQL tokens. I also mentioned in #4233 we could alternatively parse/canonicalize the MBQL on the frontend like the backend does (it would be super nice if we could reuse some of the backend code as ClojureScript but that seems kind of unlikely)

**Pull request merged**
