### PR TITLE
Download functionality on embedded dashboards

### PR DESCRIPTION
**Pull request by goodfella1408**
###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by mazameli** [comment]
I accidentally left this comment on your repo, @goodfella1408, rather than ours, so I'm copy/pasting it here for context:

Hey, @goodfella1408. I spun this branch up locally and tried embedding a dashboard in a local HTML file and opening it up in Chrome, but I'm not seeing a new download button anywhere. Am I missing something? Here's a screenshot:

screen shot 2017-12-18 at 3 15 02 pm

**Comment by goodfella1408** [comment]
By embedded dashboards I meant -> https://metabase.com/docs/v0.23.0/administration-guide/13-embedding.html . It works when embedding the dashboard in a different webapp. Is embed in html same as above ?
Basically the download widget will come up only if the dashboardId is a JWT token .
This is the exact check in the code ->
const isEmbed = Utils.isJWT(dashboardId);

**Comment by mazameli** [comment]
Ah, gotcha. Could you attach a screenshot or two of how this impacts the UI? I'll try to make some time to test this out in an embedded web app, but it would be great to just get a quick sense of the changes via screenshots. Thanks!

**Comment by goodfella1408** [comment]
screen shot 2017-12-22 at 10 54 03 am
Sure PFA

**Comment by mazameli** [comment]
Thanks a bunch, goodfella. A couple of things:


1. I think this button should only appear when hovering on a dashboard card. It feels like too much visual noise to display it persistently on every card to me.
2. There's a different arrow icon you can use called `download`. I know you were intending to match the current download icon we're using on question pages, but we'll be swapping that icon out for the `download` one there as well in a separate issue.
3. This is more of a @metabase/core-developers point, but if we merge this PR, which is only for embedded dashboards, we're going to need to make sure we replicate this behavior on at least public and iframe dashboards, if not on all dashboards.

Here's a mockup of what I'm thinking:

**Download button appears on card hover**

hover-01

**Tooltip plus blue icon when hovering on the button itself**

hover-02

**Comment by goodfella1408** [comment]
@mazameli agreed with your comments.Please give me some time for fixing this - I am not a UI developer but the changes you called out should not be big .
It already works for iframes - I will add support for public links .

**Comment by mazameli** [comment]
Thanks a bunch, @goodfella1408, and happy new year!

**Comment by lexnat187** [comment]
@mazameli and @goodfella1408 how are these changes coming along? This is functionality is exactly what we need for our embedded dashboards.

**Comment by ejhayes** [comment]
I think this functionality would be very useful -- do you think it can make it into v0.28?!

**Comment by ssatoskar** [comment]
Team, When do we expect this feature to be released? I have an important client demo mid of February and they are very eager to see Metabase capabilities. Trying to convince them to go with Metabase for their banking analytics.

**Comment by hummerh2** [comment]
Any update on this? Need it for my Operations team. Thanks again for Metabase!

**Comment by woohoou** [comment]
this is totally cool, @goodfella1408 do you consider your fork is production ready?

**Comment by sranes** [comment]
Is this getting merged anytime soon? Eagerly waiting for it.

**Comment by gigincg** [comment]
Was this feature removed after merging? I'm unable to find an export/download icon in my dashboards

**Comment by flamber** [comment]
@gigincg This has been available since version 0.30 if I remember correctly. Note that it's specific to Embedded dashboards, not Public shared dashboards (upvote #6687 by clicking +1 on first post).
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Pull request merged**
