### PR TITLE
CI build: fix the cache key to include enterprise frontend

### PR DESCRIPTION
**Pull request by ariya**

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]
Nice catch!

**Review by camsaul — APPROVED** [review]
oops 😓

**Comment by camsaul** [comment]
In PR https://github.com/metabase/metabase/pull/13925 I changed it to consider *all* `.js` and `.jsx` files in the entire codebase:

```yaml
      # .FRONTEND-CHECKSUMS is every JavaScript source file as well as dependency files like yarn.lock
      - create-checksum-file:
          filename: .FRONTEND-CHECKSUMS
          find-args: ". -type f -name '*.js' -or -name '*.jsx' -or -name yarn.lock -or -name webpack.config.js -or -name package.json"
```

 so you actually might want to hold off on merging this in

**Review by camsaul — CHANGES_REQUESTED** [review]
I'm dumb. Thanks for catching this.

In PR https://github.com/metabase/metabase/pull/13925 I already changed it to consider *all* `.js` and `.jsx` files in the entire codebase:

```yaml
# .FRONTEND-CHECKSUMS is every JavaScript source file as well as dependency files like yarn.lock
- create-checksum-file:
    filename: .FRONTEND-CHECKSUMS
    find-args: ". -type f -name '*.js' -or -name '*.jsx' -or -name yarn.lock -or -name webpack.config.js -or -name package.json"
```

I'm hoping to merge that PR in today, so this won't be needed after #13925 is merged. If you do merge it I'll have to go in and fix merge conflicts which would just involve stomping over these changes 😓

**Comment by ariya** [comment]
> I'm hoping to merge that PR in today, so this won't be needed after #13925 is merged. If you do merge it I'll have to go in and fix merge conflicts which would just involve stomping over these changes

I think that's a good idea, just fold the change into your PR! I'm closing this for now.

**Pull request closed without merging**
