### PR TITLE
handle RecentViews for non-existant entites

### PR DESCRIPTION
**Pull request by escherize**
Due to the way we store recent views (ids happen to line up, but aren't fks) we can't easily use cascading deletes to delete RecentViews, so there are rare occurances of RecentView records that map to non-existant entites (e.g. a `dashboard`).

This tweak just doesn't show those RecentView records, instead of throwing (which breaks the api).

I considered deleting the RecentView records when this is detected, but the current bucket-filling pruning system will delete these entries on its own, so I don't think the added complexity is worth it.

### CODE REVIEW

**Review by noahmoss — APPROVED** [review]

**Comment by dpsutton** [comment]
This is built on an `N+1` architecture. Do you think it's possible to select all items in a few queries and then process them instead of for each item `(t2/select <model> :id (:id item))`?

**Comment by escherize** [comment]
It's possible to select everything in a few queries, I considered that, but is it worth it? Wince we select (at most) 100 items, I wasn't sure that sort of optimization was worth the tradeoff. I think it might be over optimization

**Comment by dpsutton** [comment]
I think it is worth it. Limiting this to at most 4 queries (cards/models, dash, table, collection) sounds much preferable than doing ~100 for this endpoint. Further, I think it would be easier to follow for the `ellide-archived` since that would be a simple little check for the few models and not have to do any io. And then `fill-recent-view-info` doesn't have to hit the db either and just does the current massaging.

**Comment by escherize** [comment]
Yeah that's fair, actually `fill-recent-view-info` already gets called with the entity row data tacked onto the map, for the `GET "activity/popular_items"` route. I'll make the change

**Pull request merged**
