### PR TITLE
Vertica Driver :tada:

### PR DESCRIPTION
**Pull request by camsaul**
Vertica driver from PR #3387 with documentation and other cleanup.

Implements #1337 

Still needs to be added to CI! 😢

### CODE REVIEW

**Comment by erp12** [comment]
I found a bug with this driver.
One our our data sources frequently uses the date `0001-12-30 BC`. The Vertica driver is not able to handle these dates when they are returned by a question/query.

The error message is:
`[Vertica][JDBC](10140) Error converting value to Timestamp.`
or
`[Vertica][JDBC](10140) Error converting value to Date.`

I am working on a fix, but any advice on where to start would be much appreciated.

**Comment by camsaul** [comment]
@erp12 do I dare ask why you're frequently using the date `0001-12-30 BC`? 😓 

Either way it sounds like the JDBC driver doesn't like dates like that. Maybe there's a JDBC connection string option we can pass?

**Comment by erp12** [comment]
@camsaul Its data coming from a separate data store in another part of our rather large organization. We aren't entirely sure why `0001-12-30 BC` is used, but its unfortunately not in our control.

I have confirmed that I can use the Vertica JDBC driver through R and it handles BC dates fine, although it promotes the date into a string. Could this be the same issue happening in metabase?

**Comment by camsaul** [comment]
@erp12 We ran into a somewhat similar issue, #1420, where MySQL didn't like dates that were `0000-00-00`. In #1495 I fixed that by adding an option to the JDBC connection string to allow "weird" dates.

If you can find a similar option for Vertica we can add that to the connection string. If not I don't realistically think it makes sense for us to rework big parts of our driver architecture to "promote dates into strings" at this point in time for an edge-case like this 😓

**Comment by erp12** [comment]
@camsaul Could you say a bit more about where the problem is? Sorry, I know very little about JDBC.

When I load some data with the BC dates into postgres, metabase can handles it fine ( although the date is slightly changed to `Thursday, December 28, 0000 4:59 AM` which is fine for our use case ).

When I use the Vertica jdbc driver outside of metabase, it returns the BC dates fine.

Given those two observations, do you still think it is hopeless to change the Vertica metabase driver so that it can handle these dates? 

Also, after looking through the vertica jdbc connection options, I don't see anything that seems relevant to this problem.

**Comment by camsaul** [comment]
Ok, finally got the CI situation figured out.

**Pull request merged**
