### PR TITLE
Fix fields from Amazon Athena Tables failing to sync if there is not an underscore in the Table Name

### LINKED ISSUE #43980: Fields from Amazon Athena Tables / S3 Buckets Fail to sync if there is not an Underscore in the Table Name
### Describe the bug

After connecting to Athena (S3 data source) the tables are all listed and they can all be queried from the native editor. However, when you attempt to access the table from the GUI editor you receive this error for some tables:

_No fields found for table "accounts"._

Can confirm there are no fields in the metabase_fields table. The pattern seems to be that tables WITH an underscore in the title sync just fine. Tables without underscores in the title do not. This behavior only seems to occur if the data catalog is defined explicitly in the connection settings from within Metabase.

### To Reproduce

1. Set up Metabase v49.xx
2. Set up Athena using an S3 bucket as the data source with some sample files ([this lab ](https://github.com/paoliniluis/metabase-athena-glue) works great)
3. Some folders in the bucket should have an underscore in the name; others should not
4. Connect to Athena from Metabase (explicitly include the catalog in the connection config)
5. Look at Table Metadata
6. Note that tables with an underscore in the name have fields to be manage. Tables without an underscore do not.

### Expected behavior

Fields from the table should sync into Metabase so the GUI builder is functional.

### Logs

2024-06-10 17:12:29 2024-06-10 22:12:29,190 INFO sync.util :: STARTING: Sync metadata for athena Database 3 ''Athena''
2024-06-10 17:12:30 2024-06-10 22:12:30,036 INFO sync.util :: STARTING: step ''sync-dbms-version'' for athena Database 3 ''Athena''
2024-06-10 17:12:30 2024-06-10 22:12:30,040 INFO sync.util :: FINISHED: step ''sync-dbms-version'' for athena Database 3 ''Athena'' (3.4 ms)
2024-06-10 17:12:30 2024-06-10 22:12:30,040 INFO sync.util :: STARTING: step ''sync-timezone'' for athena Database 3 ''Athena''
2024-06-10 17:12:30 2024-06-10 22:12:30,041 INFO sync-metadata.sync-timezone :: :athena database 3 default timezone is nil
2024-06-10 17:12:30 2024-06-10 22:12:30,041 INFO sync.util :: FINISHED: step ''sync-timezone'' for athena Database 3 ''Athena'' (1.2 ms)
2024-06-10 17:12:30 2024-06-10 22:12:30,041 INFO sync.util :: STARTING: step ''sync-tables'' for athena Database 3 ''Athena''
2024-06-10 17:12:30 2024-06-10 22:12:30,056 INFO sync-metadata.tables :: Found new tables: (Table  ''s3-data-source.accounttest'' Table  ''s3-data-source.account_testunderscore'')
2024-06-10 17:12:30 2024-06-10 22:12:30,121 INFO sync-metadata.tables :: Updating table metadata for Table 30 ''s3-data-source.reviews''
2024-06-10 17:12:30 2024-06-10 22:12:30,122 INFO sync-metadata.tables :: Updating table metadata for Table 32 ''s3-data-source.account_testunderscore''
2024-06-10 17:12:30 2024-06-10 22:12:30,122 INFO sync-metadata.tables :: Updating table metadata for Table 31 ''s3-data-source.accounttest''
2024-06-10 17:12:30 2024-06-10 22:12:30,122 INFO sync-metadata.tables :: Updating table metadata for Table 29 ''s3-data-source.feedback''
2024-06-10 17:12:30 2024-06-10 22:12:30,122 INFO sync-metadata.tables :: Updating table metadata for Table 26 ''s3-data-source.invoices''
2024-06-10 17:12:30 2024-06-10 22:12:30,122 INFO sync-metadata.tables :: Updating table metadata for Table 27 ''s3-data-source.analytic_events''
2024-06-10 17:12:30 2024-06-10 22:12:30,122 INFO sync-metadata.tables :: Updating table metadata for Table 28 ''s3-data-source.accounts''
2024-06-10 17:12:30 2024-06-10 22:12:30,227 INFO sync.util :: FINISHED: step ''sync-tables'' for athena Database 3 ''Athena'' (185.1 ms)
2024-06-10 17:12:30 2024-06-10 22:12:30,227 INFO sync.util :: STARTING: step ''sync-fields'' for athena Database 3 ''Athena''
2024-06-10 17:12:31 2024-06-10 22:12:31,037 INFO sync.util :: FINISHED: step ''sync-fields'' for athena Database 3 ''Athena'' (809.9 ms)
2024-06-10 17:12:31 2024-06-10 22:12:31,037 INFO sync.util :: STARTING: step ''sync-fks'' for athena Database 3 ''Athena''
2024-06-10 17:12:31 2024-06-10 22:12:31,076 INFO sync.util :: FINISHED: step ''sync-fks'' for athena Database 3 ''Athena'' (38.6 ms)
2024-06-10 17:12:31 2024-06-10 22:12:31,076 INFO sync.util :: STARTING: step ''sync-indexes'' for athena Database 3 ''Athena''
2024-06-10 17:12:31 2024-06-10 22:12:31,076 INFO sync.util :: FINISHED: step ''sync-indexes'' for athena Database 3 ''Athena'' (144.4 µs)
2024-06-10 17:12:31 2024-06-10 22:12:31,076 INFO sync.util :: STARTING: step ''sync-metabase-metadata'' for athena Database 3 ''Athena''
2024-06-10 17:12:31 2024-06-10 22:12:31,077 INFO sync.util :: FINISHED: step ''sync-metabase-metadata'' for athena Database 3 ''Athena'' (677.5 µs)
2024-06-10 17:12:31 2024-06-10 22:12:31,077 INFO sync.util :: STARTING: step ''sync-table-privileges'' for athena Database 3 ''Athena''
2024-06-10 17:12:31 2024-06-10 22:12:31,077 INFO sync.util :: FINISHED: step ''sync-table-privileges'' for athena Database 3 ''Athena'' (103.3 µs)
2024-06-10 17:12:31 2024-06-10 22:12:31,127 INFO sync.util :: FINISHED: Sync metadata for athena Database 3 ''Athena'' (1.9 s)
2024-06-10 17:12:31 2024-06-10 22:12:31,128 INFO sync.util :: STARTING: Analyze data for athena Database 3 ''Athena''
2024-06-10 17:12:31 2024-06-10 22:12:31,133 INFO sync.util :: STARTING: step ''fingerprint-fields'' for athena Database 3 ''Athena''
2024-06-10 17:12:31 2024-06-10 22:12:31,169 INFO analyze.fingerprint :: Fingerprinting 15 fields in table Table 32 ''s3-data-source.account_testunderscore''
2024-06-10 17:12:33 2024-06-10 22:12:33,905 INFO sync.analyze :: fingerprint-fields Analyzed [******············································] 😞   14% Table 29 ''s3-data-source.feedback''
2024-06-10 17:12:33 2024-06-10 22:12:33,914 INFO sync.analyze :: fingerprint-fields Analyzed [*************·····································] 😒   27% Table 26 ''s3-data-source.invoices''
2024-06-10 17:12:33 2024-06-10 22:12:33,918 INFO sync.util :: FINISHED: step ''fingerprint-fields'' for athena Database 3 ''Athena'' (2.8 s)
2024-06-10 17:12:33 2024-06-10 22:12:33,918 INFO sync.util :: STARTING: step ''classify-fields'' for athena Database 3 ''Athena''
2024-06-10 17:12:34 2024-06-10 22:12:34,007 INFO sync.analyze :: classify-fields Analyzed [********************······························] 😐   41% Table 31 ''s3-data-source.accounttest''
2024-06-10 17:12:34 2024-06-10 22:12:34,013 INFO sync.analyze :: classify-fields Analyzed [***************************·······················] 😌   55% Table 27 ''s3-data-source.analytic_events''
2024-06-10 17:12:34 2024-06-10 22:12:34,016 INFO sync.util :: FINISHED: step ''classify-fields'' for athena Database 3 ''Athena'' (97.4 ms)
2024-06-10 17:12:34 2024-06-10 22:12:34,016 INFO sync.util :: STARTING: step ''classify-tables'' for athena Database 3 ''Athena''
2024-06-10 17:12:34 2024-06-10 22:12:34,024 INFO sync.analyze :: classify-tables Analyzed [**********************************················] 😏   68% Table 32 ''s3-data-source.account_testunderscore''
2024-06-10 17:12:34 2024-06-10 22:12:34,033 INFO sync.analyze :: classify-tables Analyzed [****************************************··········] 😊   82% Table 30 ''s3-data-source.reviews''
2024-06-10 17:12:34 2024-06-10 22:12:34,034 INFO sync.analyze :: classify-tables Analyzed [***********************************************···] 😍   95% Table 28 ''s3-data-source.accounts''
2024-06-10 17:12:34 2024-06-10 22:12:34,034 INFO sync.util :: FINISHED: step ''classify-tables'' for athena Database 3 ''Athena'' (17.8 ms)
2024-06-10 17:12:34 2024-06-10 22:12:34,075 INFO sync.util :: FINISHED: Analyze data for athena Database 3 ''Athena'' (2.9 s)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-28",
      "tag": "v1.49.13",
      "hash": "de28e83"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Severe - there is a work around but it's not easy to diagnose

### Additional context

Note: I tested this with the above linked lab. I have not tried implementing this without using Glue.

Here is a walk through:
https://www.loom.com/share/af88c7ee1be74b2fa5151cf0b982c1f1

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/43980

The root cause of the problem is described here in [the issue](https://github.com/metabase/metabase/issues/43980#issuecomment-2166965880). The `java.sql.DatabaseMetadata` `getColumns` method returns an empty list in the scenario where the AWS user has no `GetTableMetadata` permissions. With this PR, in this scenario we will use a `DESCRIBE ...` query to get the column metadata, which doesn't suffer from the same bug but is slower.

Each `DESCRIBE` query takes about a second, so this has the potential to substantially slow down sync if there are many tables with such issues (~1 second per table). But I think we care more about fixing the bug than making athena sync that much slower. To make sync faster, we could implement something like step 4 in [this proposal](https://www.notion.so/metabase/Faster-sync-for-more-drivers-d5b657aba7354a19bf89d62f1038a8ff?pvs=4#01fed4c9f4c34b8199a481e82deb8b8a) but for nested fields, which would avoid the need to do a query per table.

To test this locally, make sure you've set the appropriate env variables for all the settings below. Use the credentials [here](https://start.1password.com/open/i?a=AEO4BXOSHNFCJLK26XA7AD522E&v=fbhwdxcon6hj77du2c5cc7wvaa&i=xhozcstrujjwm7n5thraqbvwl4&h=my.1password.com) and [here](https://start.1password.com/open/i?a=AEO4BXOSHNFCJLK26XA7AD522E&v=fbhwdxcon6hj77du2c5cc7wvaa&i=y3hco6kbtooqhdonm5p23vamwi&h=my.1password.com) to configure the athena test users to match CI. https://github.com/metabase/metabase/blob/6899f3cccb34a4c3cb8152e8bb3a3a60c677fa66/.github/workflows/drivers.yml#L40-L45
`MB_ATHENA_TEST_REGION` should be `us-east-1`

### CODE REVIEW

**Comment by calherries** [comment]
I can't reproduce the bug with the user we have for athena in CI. I'll wait for some help to create another user with the appropriate policies that we can use.

**Comment by calherries** [comment]
CI tests will fail until the secrets are added to github. See here: https://metaboat.slack.com/archives/C5XHN8GLW/p1718332009027499

**Review by crisptrutski — APPROVED** [review]
A truly bizarre bug. Good sleuthing!

**Comment by calherries** [comment]
@metabase-bot backport release-x.49.x

**Pull request merged**
