### PR TITLE
Don't run mapping logic that expects a `dataset_query` when there isn't one

### LINKED ISSUE #24530: Blank screen if user without permissions to view dashboard card tries to edit the dashboard filter
**Describe the bug**
This is a continuation of #20656, which was fixed by @daltojohnso in #20678. Everything works great now and the card shows the error without breaking the dashboard, **but** the moment the user without permissions to see dashcard tries to edit the dashboard filter, frontend breaks.

**Logs**
```
Visualization.jsx:109 Error caught in <Visualization> TypeError: Cannot read properties of undefined (reading 'type')
    at Function.isDatasetQueryType (InternalQuery.ts:14:1)
    at Question.query (Question.ts:225:1)
    at memoizeClass.ts:54:1
    at getWithFallback (memoizeClass.ts:11:1)
    at Question.value (memoizeClass.ts:54:1)
    at getParameterMappingOptions (mapping-options.js:67:1)
    at selectors.js:156:1
```
```
ExplicitSize.jsx:48 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at WrappedComponent._getElement (ExplicitSize.jsx:48:1)
    at WrappedComponent._updateResizeObserver (ExplicitSize.jsx:93:1)
    at WrappedComponent.componentDidUpdate (ExplicitSize.jsx:63:1)
    at commitLifeCycles (react-dom.development.js:19835:1)
    at commitLayoutEffects (react-dom.development.js:22803:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at commitRootImpl (react-dom.development.js:22541:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
```

**To Reproduce**
1. Follow all repro steps from https://github.com/metabase/metabase/issues/20656
image
2. Click on the pen icon to edit the dashboard
3. Click on the gear icon next to the filter in order to edit it
4. Frontend breaks, but it depends on your environment how will you see it (Cypress = fullscreen, dev = error in the container, production = blank screen)
image

**Expected behavior**
It should show a `key` icon without the ability to map filter to any fields from that card (like it properly does for `block` permissions, for example)
image

**Information about your Metabase Installation:**
local dev, `master`, f32550c66e41e529671737710d94b4021cbe0162, H2, Sample Database

**Severity**
We should never end up with the blank screen!

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #24530 
Reproduces #24530 

The fix is simple enough. Add another `if` statement to check for the existence of `card.dataset_query` before running logic that expects the existence of `dataset_query.`

`DashCardCardParameterMapper`, the component responsible for this error, runs the logic `new Question(card, metadata).query()` that expects the existence of `card.dataset_query`. We shouldn't ever let a `card` without a `dataset_query` get so far, but it's tough because we're doing things like `new Question(card, metadata).query()` all over the place without any consistency with respect to varying levels of user permissioning. `DashCardCardParameterMapper` probably knows too much about `cards` to begin with -- should only be involved with UI concerns, yet it inspects the `card` object in order to know what to do. 

Testing
Follow the steps described in #24530

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
I'm still seeing the error when testing locally.

**Comment by daltojohnso** [comment]
> I'm still seeing the error when testing locally.

Should be fixed now -- needed to add the `card.dataset_query` check to `getParameterMappingOptions`

**Comment by nemanjaglumac** [comment]
@daltojohnso do you mind if I add a repro directly to this PR?

**Comment by daltojohnso** [comment]
@nemanjaglumac go for it. Thanks!

**Comment by nemanjaglumac** [comment]
@daltojohnso pushed the repro. Sorry for two commits - I was on a stale branch when I tested originally. Hence the [commented out repro](https://github.com/metabase/metabase/pull/24536/commits/58838b40236186d2864f1f905411245e6a41dec9).

**Review by ranquild — APPROVED** [review]

**Pull request merged**
