### PR TITLE
Enable our custom SQLBehavior for SQL modes

### PR DESCRIPTION
**Pull request by tlrobinson**
Somehow this broke or was never working.

### CODE REVIEW

**Comment by salsakran** [comment]
seems to work for me in other branches? what's the symptom?

**Comment by tlrobinson** [comment]
Typing `{` doesn't insert a `}` like it does for `[` and `(`.

**Comment by tlrobinson** [comment]
I'm not exactly sure how it broke. It might have never worked, or a newer version of Ace broke it, but it's been bothering me for awhile since I know I at least attempted to enable it months ago.

**Comment by salsakran** [comment]
works for me 👍

**Pull request merged**
