### PR TITLE
Always show Popover footer regardless of Popover inner scroll

### LINKED ISSUE #14307: I shouldn't have to scroll to see the add-filter button in the notebook's add-filter popover
When trying to filter on a field where you can either select values from a list or via a search box, the add-filter popover seems to have a max-height that causes the add-filter button to get pushed down, requiring you to have to scroll to add the filter, which is annoying.

Dropdown list example:

have-to-scroll-again

Search box example:

add-filter-have-to-scroll

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #14307 

This PR is nearly identical to https://github.com/metabase/metabase/pull/16175, synced with and repointed to master branch.

<details><summary>Before/After gifs</summary>

<h3>After</h3>

<h3>Before</h3>

</details>

## How to Test

If doing manual exploration, please look for use cases not covered in this description, as popovers are used pervasively in our application and not yet 100% covered by tests. 

### Simple Question Column Headers

1. From home, click on `Ask a question`
2. Click on `Simple question`
3. Choose `Sample Dataset`
4. Choose any of the tables, for example `People`
5. Click on the top of the columns
6. Click on `Filter by this column`
7. Try the various filters.

<details><summary>Screenshot</summary>

</details>

### Custom Question Filter

1. From home, click on `Ask a question`
2. Click on `Custom question`
3. Choose `Sample Dataset`
4. Choose any of the tables, for example `People`
5. Click on `Add filters to narrow your answers`
6. Try all types of fields: text, location, datetime and so on. 

<details><summary>Screenshot</summary>

</details>

### Filter in a Saved Dashboard

<details><summary>Screen recording</summary>
<video src="https://user-images.githubusercontent.com/380816/119669010-0d7c4680-be0e-11eb-8f61-811739f0a131.mov" />
</details>

### Adding Number Parameter to Filter in a Saved Dashboard

See screen recording above and follow video below.

<details><summary>Screen recording</summary>
  <video src="https://user-images.githubusercontent.com/380816/119669675-9c895e80-be0e-11eb-9272-3c7323c68eb6.mov" />
</details>

### CODE REVIEW

**Review by kdoh — APPROVED** [review]
Looks good!

**Comment by nemanjaglumac** [comment]
This looks and works great, @gusaiani ! For "normal" (modern) screen sizes I still haven't been able to find any issues.
However, set the resolution to 1024x640 and the problem with footer overlapping the last (few) result(s) is back.

The last result `Zapata` is not visible in this screenshot.

image

**Comment by gusaiani** [comment]
@nemanjaglumac 

Hmm strange.

I can see Zapata in my local env.

Using Brave and setting resolution via dev tools.

Any more details on how to reproduce?

image

**Comment by gusaiani** [comment]
@nemanjaglumac I notice Zapata is at the beginning of a new batch of results.

Something to do with loading more results as we scroll in there.

So it may be related to that, and if you simply scroll again it shows.

**Review by nemanjaglumac — APPROVED** [review]
Seems to be working great!
Tested different screen sizes, filter in a sidebar (simple question), filter from the table header cell... everything is working.

One possible edge case is filter in a dashboard when you choose "dropdown" for a filter. It overflows the bottom of the screen. Maybe this can be a follow up PR. You make the call.

**Comment by gusaiani** [comment]
@nemanjaglumac Thank you very much for the manual testing, the feedback, and the partnership in getting this PR to this point.

@ariya Thank you for nudging me towards the better git branches and PR sizes.

@kdoh Thank you for the code review.

**Pull request merged**
