### PR TITLE
30 seconds refresh

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by salsakran** [comment]
hey @shargon -

what's the use case for this?

are your queries returning in seconds or?

**Comment by tlrobinson** [comment]
(Also note that you can set custom refresh rates by changing the value in the URL)

**Comment by shargon** [comment]
For my cases, are more useful a small refresh

**Comment by alirezastack** [comment]
For a live dashboard I think it is a must. 1 minute is so much that make metabase near to useless for live monitoring dashboards.

**Comment by kdoh** [comment]
Hey there @shargon. I want to really thank you for your work on this and bringing the issue to our attention but I think adding options of less than a minute to the refresh UI is going to be a no go for us until we get to a point where we support realtime or live dashboards in a true way.

For now I'd recommend using the URL solution @tlrobinson referenced above which will allow you to use whatever custom intervals you need.

**Pull request closed without merging**
