### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by Bonifacio2**

### CODE REVIEW

**Comment by Bonifacio2** [comment]
I have two questions:
- Are these broken tests legit?
- Signing the CLA is really required for this kind of PR?

**Comment by flamber** [comment]
@Bonifacio2
The driver tests are not available on external PRs, so they will fail. Other tests should pass, so not sure why those two e2e fails.
But CLA is always appreciated, but not strictly needed for typos.

**Review by noahmoss — APPROVED** [review]

**Comment by rlotun** [comment]
clone of this by @gusaiani - https://github.com/metabase/metabase/pull/16936 passes all tests so I'll merge this in. thanks for your contribution!

**Comment by gusaiani** [comment]
Thank you for your contribution, @Bonifacio2!

Should land in version 0.40, very soon.

**Pull request merged**
