### PR TITLE
Comma Separated Text In Text Field To Be Used With IN Operator

### PR DESCRIPTION
**Pull request by chenlingmin**
###### Comma Separated Text In Text Field To Be Used With IN Operator

```
(expect
  "SELECT * FROM USERS where id IN ('1', '2', '3')"
  (-> (qp/process-query
        {:database   (data/id)
         :type       "native"
         :native     {:query         "SELECT * FROM USERS [[where id IN ({{ids_list}})]]"
                      :template_tags {:ids_list {:name         "ids_list"
                                                 :display_name "Ids list"
                                                 :type         "text"}}}
         :parameters [{:type   "category"
                       :target ["variable" ["template-tag" "ids_list"]]
                       :value  "1,2,3"}]})
     :data :native_form :query))


```

### CODE REVIEW

**Comment by camsaul** [comment]
This is a big ol' SQL injection security risk

**Review by salsakran — CHANGES_REQUESTED** [review]
@chenlingmin Thank you so much for the work you've put into this PR!

We're interested in this feature, but for us to merge this PR we need to address the SQL injection attack matter.

Raw text can NOT be injected into our SQL templates. Doing so would allow users to inject things like `1;DROP TABLE core_users;` . This is contrived as we also have an added layer of protection in only allowing one sql statement per query. However, data exfiltration attacks could no doubt be done with a tiny bit of creativity within the one-statement constraint. 

For SQL template tags, all text that ends up in a generated SQL query needs to be typed and used as a JDBC connection parameter. 

Practically, this will likely mean counting the entries in the ParamValue, and putting an appropriate number of `?`'s in the generated SQL string and passing in the parameters to the driver all in some way.

I don't have the Query Processor middleware in my head, but perhaps @camsaul or @senior could offer advice on how best to interleave it?

**Comment by camsaul** [comment]
The various pieces of code that do param substitution just need to return the appropriate `:replacement-snippet` and a sequence of `:prepared-statement-args` so if you do that there's other code in place that makes sure the whole thing is put together and the args are passed. Look at what all the other code in that namespace is doing

**Comment by chenlingmin** [comment]
@salsakran I try it `1;DROP TABLE core_users;`, not happend SQL injection

**Comment by chenlingmin** [comment]
I just started learning Clojure, So I can't solve  SQL injection quickly. Can you fix it for me if there are any problems?

**Comment by camsaul** [comment]
@chenlingmin for the SQL injection to happen it would have to have a comma in the string so it would use the new code from this PR. Our normal single-string parameter code passes the string as a separate prepared statement argument to prevent such attacks

**Comment by chenlingmin** [comment]
look this, not happend SQL injection. can you give me example？
image

**Comment by camsaul** [comment]
@chenlingmin that is the textbook definition of SQL injection. Look at the query that gets sent to the DB (in green) below

**Comment by chenlingmin** [comment]
@camsaul  Yes, the generated SQL is indeed a textbook injection, But the query throws MySQLSyntaxErrorException, Error Code 1064, Why?

**Comment by camsaul** [comment]
@chenlingmin because the query you generated isn't valid SQL. But you still managed to inject SQL into a query using the parameters, which is *bad*. That means if you spent some time you could figure out a way to inject SQL that would not generate a bad query, and get access to something you're not supposed to.

**Comment by camsaul** [comment]
@chenlingmin, are you still working on this PR? If not, do you mind if we go ahead and close it?

**Comment by camsaul** [comment]
@chenlingmin, I'm going to go ahead and close this PR since it seems it's no longer being actively worked on. Please open a new PR if you have a fix for this one that avoids opening people up to SQL injection attacks. Thanks!

**Pull request closed without merging**
