### PR TITLE
Make sure resolve-joined-fields works on all levels (fixes #13642)

### LINKED ISSUE #13642: Drill-through not working on questions with joins, where target table is sandboxed, and target fields cannot be filtered
**Describe the bug**
Not possible for sandboxed user to drill-through to joined (implicit/explicit) target table, which is sandboxed. And it's not possible to filter any of the fields of the target table either.

If the origin table (Orders in this example) is not sandboxed, then the error is slightly different `Column "PUBLIC.PRODUCTS.CATEGORY" not found;`.

**To Reproduce**
1. Admin > People > create user "U1" with attribute `user_id=1` and `user_cat=Widget`
2. Admin > Permissions > Sample Dataset > revoke all, sandbox Orders on "User ID"=`user_id`, and sandbox Products on "Category"=`user_cat`
image
3. Custom question > Sample Dataset > Orders - join Products on ID=Orders.Product_ID - summarize Count by Category, save as "Q1"
image
4. Login as "U1" > open "Q1" > click Widget-bar to "View these Orders" - fails with `Column "source.CATEGORY" not found;`
image
<details><summary>Full stacktrace</summary>

```
2020-10-30 17:31:29,342 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 1,
 :started_at #t "2020-10-30T17:31:28.665807+01:00[Europe/Copenhagen]",
 :state "42S22",
 :json_query
 {:type "query",
  :query
  {:source-table 2, :joins [{:fields "all", :source-table 1, :condition ["=" ["field-id" 11] ["joined-field" "Product" ["field-id" 4]]], :alias "Product"}], :filter ["=" ["field-id" 6] "Widget"]},
  :database 1,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Comparison.optimize(Comparison.java:177)"
  "org.h2.command.dml.Select.prepare(Select.java:861)"
  "org.h2.command.Parser.prepareCommand(Parser.java:283)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1135)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)"
  "--> driver.sql_jdbc.execute$fn__44809.invokeStatic(execute.clj:239)"
  "driver.sql_jdbc.execute$fn__44809.invoke(execute.clj:237)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:257)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:254)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:390)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:386)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$fn__82086.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__82086.invoke(sql_jdbc.clj:47)"
  "driver.h2$fn__80898.invokeStatic(h2.clj:87)"
  "driver.h2$fn__80898.invoke(h2.clj:84)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49316.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__48591.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__49481.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__47392.invoke(auto_parse_filter_values.clj:44)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__43451.invoke(wrap_value_literals.clj:149)"
  "query_processor.middleware.annotate$add_column_info$fn__43314.invoke(annotate.clj:575)"
  "query_processor.middleware.permissions$check_query_permissions$fn__48466.invoke(permissions.clj:70)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__49999.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__48664.invoke(cumulative_aggregations.clj:61)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__51266.invoke(row_level_restrictions.clj:292)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__50236.invoke(resolve_joined_fields.clj:36)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__50555.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__46997.invoke(add_implicit_joins.clj:254)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__49277.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__49302.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__49257.invoke(format_rows.clj:84)"
  "query_processor.middleware.desugar$desugar$fn__48730.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__47751.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__48268.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__46545.invoke(add_dimension_projections.clj:318)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__46748.invoke(add_implicit_clauses.clj:141)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__51266.invoke(row_level_restrictions.clj:287)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47146.invoke(add_source_metadata.clj:105)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__50968.invoke(column_level_perms_check.clj:24)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50196.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__47339.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__48315.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__49981.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__48367.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__48986.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__47155.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50917.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50207$fn__50211.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50207.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49204.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__50926$fn__50927.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__50926.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__48244.invoke(cache.clj:214)"
  "query_processor.middleware.validate$validate_query$fn__50935.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__49329.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47015.invoke(add_rows_truncated.clj:36)"
  "metabase_enterprise.audit.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__31552.invoke(handle_audit_queries.clj:165)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__50902.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48607.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__50070.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__48550.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___40109$thunk__40110.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___40109.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___40118$fn__40121.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___40118.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
  "query_processor$fn__51311$process_query_and_save_execution_BANG___51320$fn__51323.invoke(query_processor.clj:249)"
  "query_processor$fn__51311$process_query_and_save_execution_BANG___51320.invoke(query_processor.clj:241)"
  "query_processor$fn__51355$process_query_and_save_with_max_results_constraints_BANG___51364$fn__51367.invoke(query_processor.clj:261)"
  "query_processor$fn__51355$process_query_and_save_with_max_results_constraints_BANG___51364.invoke(query_processor.clj:254)"
  "api.dataset$fn__62550$fn__62553.invoke(dataset.clj:59)"
  "query_processor.streaming$streaming_response_STAR_$fn__37118$fn__37119.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__37118.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__24642.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error
 "Column \"source.CATEGORY\" not found; SQL statement:\n-- Metabase:: userID: 2 queryType: MBQL queryHash: 0acf2ad499e2c9c3038de2d17e4011aa41af7931145f40dffdab1fe5f534a945\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"Product\".\"ID\" AS \"ID_2\", \"Product\".\"EAN\" AS \"EAN\", \"Product\".\"TITLE\" AS \"TITLE\", \"Product\".\"CATEGORY\" AS \"CATEGORY\", \"Product\".\"VENDOR\" AS \"VENDOR\", \"Product\".\"PRICE\" AS \"PRICE\", \"Product\".\"RATING\" AS \"RATING\", \"Product\".\"CREATED_AT\" AS \"CREATED_AT_2\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\" FROM \"PUBLIC\".\"ORDERS\" WHERE \"PUBLIC\".\"ORDERS\".\"USER_ID\" = 1) \"source\" LEFT JOIN (SELECT \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"PRODUCTS\".\"EAN\" AS \"EAN\", \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\", \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", \"PUBLIC\".\"PRODUCTS\".\"VENDOR\" AS \"VENDOR\", \"PUBLIC\".\"PRODUCTS\".\"PRICE\" AS \"PRICE\", \"PUBLIC\".\"PRODUCTS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"PRODUCTS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"PRODUCTS\" WHERE \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" = ?) \"Product\" ON \"source\".\"PRODUCT_ID\" = \"Product\".\"ID\" WHERE \"source\".\"CATEGORY\" = ? LIMIT 2000 [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:joins
   [{:strategy :left-join,
     :source-query
     {:source-table 1,
      :filter [:= [:field-id 6] [:value "Widget" {:base_type :type/Text, :special_type :type/Category, :database_type "VARCHAR", :name "CATEGORY"}]],
      :fields [[:field-id 4] [:field-id 1] [:field-id 5] [:field-id 6] [:field-id 8] [:field-id 3] [:field-id 2] [:datetime-field [:field-id 7] :default]],
      :gtap? true},
     :condition [:= [:field-id 11] [:joined-field "Product" [:field-id 4]]],
     :alias "Product",
     :source-metadata
     [{:name "ID", :id 4, :table_id 1, :display_name "ID", :base_type :type/BigInteger, :special_type :type/PK, :fingerprint nil, :settings nil}
      {:name "EAN",
       :id 1,
       :table_id 1,
       :display_name "Ean",
       :base_type :type/Text,
       :special_type nil,
       :fingerprint {:global {:distinct-count 200, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 13.0}}},
       :settings nil}
      {:name "TITLE",
       :id 5,
       :table_id 1,
       :display_name "Title",
       :base_type :type/Text,
       :special_type :type/Name,
       :fingerprint {:global {:distinct-count 199, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}},
       :settings nil}
      {:name "CATEGORY",
       :id 6,
       :table_id 1,
       :display_name "Category",
       :base_type :type/Text,
       :special_type :type/Category,
       :fingerprint {:global {:distinct-count 4, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
       :settings nil}
      {:name "VENDOR",
       :id 8,
       :table_id 1,
       :display_name "Vendor",
       :base_type :type/Text,
       :special_type :type/Company,
       :fingerprint {:global {:distinct-count 200, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}},
       :settings nil}
      {:name "PRICE",
       :id 3,
       :table_id 1,
       :display_name "Price",
       :base_type :type/Float,
       :special_type nil,
       :fingerprint
       {:global {:distinct-count 170, :nil% 0.0},
        :type {:type/Number {:min 15.691943673970439, :max 98.81933684368194, :avg 55.74639966792074, :sd 21.711481557852057, :q1 37.25154462926434, :q3 75.45898071609447}}},
       :settings nil}
      {:name "RATING",
       :id 2,
       :table_id 1,
       :display_name "Rating",
       :base_type :type/Float,
       :special_type :type/Score,
       :fingerprint {:global {:distinct-count 23, :nil% 0.0}, :type {:type/Number {:min 0.0, :max 5.0, :avg 3.4715, :sd 1.3605488657451452, :q1 3.5120465053408525, :q3 4.216124969497314}}},
       :settings nil}
      {:table_id 1,
       :special_type :type/CreationTimestamp,
       :unit :default,
       :name "CREATED_AT",
       :settings nil,
       :id 7,
       :display_name "Created At",
       :fingerprint {:global {:distinct-count 200, :nil% 0.0}, :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147", :latest "2019-04-15T13:34:19.931"}}},
       :base_type :type/DateTime}]}],
   :filter [:= [:field-id 6] [:value "Widget" {:base_type :type/Text, :special_type :type/Category, :database_type "VARCHAR", :name "CATEGORY"}]],
   :source-metadata
   [{:name "ID", :id 12, :table_id 2, :display_name "ID", :base_type :type/BigInteger, :special_type :type/PK, :fingerprint nil, :settings nil}
    {:name "USER_ID", :id 9, :table_id 2, :display_name "User ID", :base_type :type/Integer, :special_type :type/FK, :fingerprint {:global {:distinct-count 929, :nil% 0.0}}, :settings {}}
    {:name "PRODUCT_ID", :id 11, :table_id 2, :display_name "Product ID", :base_type :type/Integer, :special_type :type/FK, :fingerprint {:global {:distinct-count 200, :nil% 0.0}}, :settings {}}
    {:name "SUBTOTAL",
     :id 13,
     :table_id 2,
     :display_name "Subtotal",
     :base_type :type/Float,
     :special_type nil,
     :fingerprint
     {:global {:distinct-count 340, :nil% 0.0},
      :type {:type/Number {:min 15.691943673970439, :max 148.22900526552291, :avg 77.01295465356547, :sd 32.53705013056317, :q1 49.74894519060184, :q3 105.42965746993103}}},
     :settings nil}
    {:name "TAX",
     :id 16,
     :table_id 2,
     :display_name "Tax",
     :base_type :type/Float,
     :special_type nil,
     :fingerprint
     {:global {:distinct-count 797, :nil% 0.0}, :type {:type/Number {:min 0.0, :max 11.12, :avg 3.8722100000000004, :sd 2.3206651358900316, :q1 2.273340386603857, :q3 5.337275338216307}}},
     :settings nil}
    {:name "TOTAL",
     :id 17,
     :table_id 2,
     :display_name "Total",
     :base_type :type/Float,
     :special_type nil,
     :fingerprint
     {:global {:distinct-count 10000, :nil% 0.0},
      :type {:type/Number {:min 12.061602936923117, :max 238.32732001721533, :avg 82.96014815230805, :sd 38.35967664847571, :q1 52.006147617878135, :q3 109.55803018499738}}},
     :settings nil}
    {:name "DISCOUNT",
     :id 10,
     :table_id 2,
     :display_name "Discount",
     :base_type :type/Float,
     :special_type :type/Discount,
     :fingerprint
     {:global {:distinct-count 701, :nil% 0.898},
      :type {:type/Number {:min 0.17088996672584322, :max 61.69684269960571, :avg 5.161255547580326, :sd 3.053663125001991, :q1 2.9786226681458743, :q3 7.338187788658235}}},
     :settings nil}
    {:table_id 2,
     :special_type :type/CreationTimestamp,
     :unit :default,
     :name "CREATED_AT",
     :settings nil,
     :id 15,
     :display_name "Created At",
     :fingerprint {:global {:distinct-count 9998, :nil% 0.0}, :type {:type/DateTime {:earliest "2016-04-30T18:56:13.352", :latest "2020-04-19T14:07:15.657"}}},
     :base_type :type/DateTime}
    {:name "QUANTITY",
     :id 14,
     :table_id 2,
     :display_name "Quantity",
     :base_type :type/Integer,
     :special_type :type/Quantity,
     :fingerprint {:global {:distinct-count 62, :nil% 0.0}, :type {:type/Number {:min 0.0, :max 100.0, :avg 3.7015, :sd 4.214258386403798, :q1 1.755882607764982, :q3 4.882654507928044}}},
     :settings nil}],
   :fields
   [[:field-literal "ID" :type/BigInteger]
    [:field-literal "USER_ID" :type/Integer]
    [:field-literal "PRODUCT_ID" :type/Integer]
    [:field-literal "SUBTOTAL" :type/Float]
    [:field-literal "TAX" :type/Float]
    [:field-literal "TOTAL" :type/Float]
    [:field-literal "DISCOUNT" :type/Float]
    [:field-literal "CREATED_AT" :type/DateTime]
    [:field-literal "QUANTITY" :type/Integer]
    [:joined-field "Product" [:field-literal "ID" :type/BigInteger]]
    [:joined-field "Product" [:field-literal "EAN" :type/Text]]
    [:joined-field "Product" [:field-literal "TITLE" :type/Text]]
    [:joined-field "Product" [:field-literal "CATEGORY" :type/Text]]
    [:joined-field "Product" [:field-literal "VENDOR" :type/Text]]
    [:joined-field "Product" [:field-literal "PRICE" :type/Float]]
    [:joined-field "Product" [:field-literal "RATING" :type/Float]]
    [:joined-field "Product" [:field-literal "CREATED_AT" :type/DateTime]]],
   :limit 2000,
   :source-query
   {:source-table 2,
    :filter [:= [:field-id 9] [:value 1 {:base_type :type/Integer, :special_type :type/FK, :database_type "INTEGER", :name "USER_ID"}]],
    :fields [[:field-id 12] [:field-id 9] [:field-id 11] [:field-id 13] [:field-id 16] [:field-id 17] [:field-id 10] [:datetime-field [:field-id 15] :default] [:field-id 14]],
    :gtap? true}},
  :database 1,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 2,
   :context :ad-hoc,
   :nested? false,
   :query-hash [10, -49, 42, -44, -103, -30, -55, -61, 3, -115, -30, -47, 126, 64, 17, -86, 65, -81, 121, 49, 20, 95, 64, -33, -3, -85, 31, -27, -11, 52, -87, 69]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :gtap-perms #{"/db/1/schema/PUBLIC/table/2/query/" "/db/1/schema/PUBLIC/table/1/query/"}},
 :data {:rows [], :cols []}}

2020-10-30 17:31:29,347 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 684.4 ms (31 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (3 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
```

</details>

5. Removing the filter "Category is Widget" will show the table of the Orders+Products, but it's not possible to filter any of the fields/columns related to Products.
image

**Information about your Metabase Installation:**
Metabase 1.37.0.2

**Additional context**
Related to https://github.com/metabase/metabase-enterprise/issues/535 and #13641 and slightly to https://github.com/metabase/metabase-enterprise/issues/556 even though this is not using advanced sandboxes.

### PR DESCRIPTION
**Pull request by camsaul**
Follow-on to PR #14692, which is waiting on a review.

Fixes #13642

### CODE REVIEW

**Review by flamber — APPROVED** [review]
Tested `792c915`

This now works - I can now drill, sort and filter on the joined table columns :tada:

But if I have a FK remapping to the same table as I'm joining, then it fails with:
`Cannot resolve joined field due to ambiguous joins: table PRODUCTS (ID 6) joined multiple times. You need to wrap field references in explicit :joined-field clauses.`
So kinda the opposite of 13641

**Comment by camsaul** [comment]
@flamber is there a Cypress repro for that situation that you said is failing now? If not, @nemanjaglumac could you add one? I really want to make sure the fixes don't break anything new.

**Comment by nemanjaglumac** [comment]
@camsaul I'll add it asap. That's basically going to be the same logic (or to be precise, reverted) from what I did in https://github.com/metabase/metabase/pull/14710. We're just testing both `13641` and `13642` with AND without remapping.

**Comment by nemanjaglumac** [comment]
As of 79013a7df8bebdcbf2ce9789298de4c4f403bfb4 #13642 is still busted if display values are remapped. It works otherwise.

I've pushed the updated version of repro for #13642 UNSKIPPED in b504f2acae4dff088ac92de975b4d0be676bed80. It's going to run both "remapped" and the "default" version and it will fail on remapped until this is fixed.

The error:
```
Cannot resolve joined field due to ambiguous joins: table PRODUCTS (ID 4) joined multiple times. You need to wrap field references in explicit :joined-field clauses.
```

The state of the `sandboxes.cy.spec.js` at this moment looks like this (12 passing, 1 failing, 3 skipped)
image

**Pull request merged**
