### PR TITLE
Do not use absolute URLs in illustrations

### LINKED ISSUE #6704: Illustration images not found when run with non-root app context
Metabase version: 0.27.2

When running under a non-root app context (e.g. http://<hostname>:/metabase/) the following images are not found: questions_illustration.png, query_builder.png and sql_illustration.png.

The URL for these illustrations in the client are: `http://<hostname>/app/img/<illustration>.png `.

The should be of the form: `http://<hostname>/<context-path>/app/img/<illustration>.png`.

### PR DESCRIPTION
**Pull request by hjalves**
This fixes #6704.
Works in both non-root app context and root app contexts.

###### Before submitting the PR, please make sure you do the following 
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by tlrobinson** [comment]
Thanks for doing this. Looks like there's a few others if you feel like handling those, otherwise we can do another PR:

```
$ grep -r 'image="/' frontend
frontend/src/metabase/containers/EntitySearch.jsx:                  image="/app/img/empty_question"
frontend/src/metabase/dashboards/containers/Dashboards.jsx:              image="/app/img/dashboard_illustration"
frontend/src/metabase/dashboards/containers/Dashboards.jsx:                  image="/app/img/empty_dashboard"
frontend/src/metabase/dashboards/containers/DashboardsArchive.jsx:                  image="/app/img/empty_dashboard"
frontend/src/metabase/new_query/containers/MetricSearch.jsx:                  image="/app/img/metrics_illustration"
frontend/src/metabase/new_query/containers/NewQueryOptions.jsx:                    image="/app/img/questions_illustration"
frontend/src/metabase/new_query/containers/NewQueryOptions.jsx:                  image="/app/img/query_builder_illustration"
frontend/src/metabase/new_query/containers/NewQueryOptions.jsx:                    image="/app/img/sql_illustration"
frontend/src/metabase/questions/containers/QuestionIndex.jsx:      image="/app/img/questions_illustration"
```

**Review by tlrobinson — APPROVED** [review]

**Comment by hjalves** [comment]
Ok, I will update this MR with those changes after making some tests

**Comment by hjalves** [comment]
Tested every page where those illustrations appear. Both with non-root and root URL's.

**Review by kdoh — APPROVED** [review]
Thanks @hjalves!

**Pull request merged**
