### PR TITLE
Global and field formatting settings

### PR DESCRIPTION
**Pull request by tlrobinson**
Adds basic global and field level formatting settings UI.

Global / per-type:

screenshot 2018-10-02 22 00 30

Field:

screenshot 2018-10-02 22 05 26

Obviously needs some design love.

TODO:
* [x] a way to reset / unset settings, either individually or all? (@mazameli)
* [x] pick the settings we actually want to show (@mazameli)
* [x] Global settings layout (@mazameli)
* [x] Remove reset buttons from the global settings page @tlrobinson 
* [x] Resetting a setting to the default should make the reset icon go away @tlrobinson 
* [x] Field settings layout (change tabs to side menu) (@tlrobinson)
* [x] Field settings: empty state if there are not settings for a given field (fly coming out of inbox illustration) (@tlrobinson)
* [x] Remove `column title` from field settings (@tlrobinson )
* [x] `time_enabled` setting doesn't persist when clicked @tlrobinson 
* [x] Global date settings: add explicit `(month, day, year)` to ambiguous date options like `1/7/2018` @tlrobinson 
* [x] Date settings: add separator style if you've chosen a style like `2018/1/31` so you can do `2018-1-31` or `2018.1.31` @tlrobinson 
* [x] Currency: when updating the currency to e.g. Euros, it would be cool if the Currency Style options updated to display the selected currency type @tlrobinson 
* [x] Separator style shouldn't internationalize currency names
* [x] In the data model page, any field that's a currency type or subtype should have its currency unit set to the default by … uh default.
* [x] In field settings, Currency fields shouldn't have the `Style` option
* [x] make sure settings update for admin when they change them
* [x] make sure settings propagate from global to field correctly in UI
* [x] make sure we are correctly merging global settings for types that match both (i.e. Number + Currency). ensuring we don't have duplicate settings should be sufficient?
* [x] Would be cool if the global and chart-level unit-of-currency dropdown had a search box the way the one in the data modal does

### CODE REVIEW

**Comment by mazameli** [comment]
Should I expect global formatting settings for currency and separators to be reflected in tooltips yet?

screen shot 2018-10-08 at 1 51 20 pm

**Comment by mazameli** [comment]
We'll need to figure out a way to have these selects and inputs be a more reasonable width:

screen shot 2018-10-08 at 2 12 09 pm

**Comment by mazameli** [comment]
Added this to the to-do list, but it would be great if the global and chart-level unit of currency selects had a search box the way the data model one does. It's pretty rough trying to find e.g. Pounds otherwise.

screen shot 2018-10-08 at 2 36 24 pm

**Comment by mazameli** [comment]
Gonna stop playing with this branch now, but this is all feeling basically done to me, minus the to-dos and the few comments I just left. 👌

**Comment by mazameli** [comment]
Tooltips don't appear to be respecting formatting settings still:

screen shot 2018-10-09 at 10 34 00 am

**Comment by mazameli** [comment]
@tlrobinson Like we discussed a minute ago, we realized pulses aren't respected formatting options. In an effort to have fewer, smaller PRs we could take the approach of merging this one first, and then doing a follow-on to address that.

**Example**

Saved question:
screen shot 2018-10-09 at 10 41 28 am

Pulse preview:
screen shot 2018-10-09 at 10 40 39 am

**Comment by kdoh** [comment]
One thing we'll want to do is pin the currency select attachment so it doesn't jump around when you search.
currency_jump

**Comment by kdoh** [comment]
One strange thing I just noticed was that when I went to a table the date format I'd chosen was correct but it  was still showing time even though the `Show the time` global setting was set to off in the admin. Once I clicked "Off" again myself and went back to the table it was applied.

**Comment by mazameli** [comment]
Tooltips seem to work great now. The only place where they aren't is with region maps; legends aren't formatted there either:

map-tooltips

**Comment by tlrobinson** [comment]
> One strange thing I just noticed was that when I went to a table the date format I'd chosen was correct but it was still showing time even though the Show the time global setting was set to off in the admin. Once I clicked "Off" again myself and went back to the table it was applied.

I've fixed that, but I had forgotten I think @mazameli and I decided to disable that global setting, so I've also disabled it for global settings.

**Comment by tlrobinson** [comment]
@maz A couple visualizations like maps and funnels don't support column settings yet. I started a branch at #8663 to add those.

**Pull request merged**
