### PR TITLE
Enable grid heat maps

### LINKED ISSUE #7309: Pin maps now have weird "draw a circlemarker" UI element
Seems like maybe Leaflet changed some things? The draw-a-box UI is still there, but I'm not sure what this new UI is supposed to do. Doesn't appear to do anything, and it looks crummy. This is on master on Chrome.

leaflet

### PR DESCRIPTION
**Pull request by tlrobinson**
#3206

Only enables grid heat maps, not the blobby ones, until we figure out how to correctly compute options that make them look good.

Also resolves #7309

### CODE REVIEW

**Comment by mazameli** [comment]
Seems like this currently doesn't really work for the city-level granularity use case:

screen shot 2018-04-17 at 10 10 30 am

screen shot 2018-04-17 at 10 09 37 am

**Review by mazameli — CHANGES_REQUESTED** [review]
The lack of finer granularity when auto-binning lat+long doesn't appear to be a regression, but it is a bummer.

I would like to see the zoom behavior be made consistent before this gets merged though.

**Comment by tlrobinson** [comment]
I've updated the lat/lon bin widths to be 20, 10, 1, and 0.1, and fixed the zoom drill down.

**Comment by mazameli** [comment]
Rad, I'll check out the changes in a few minutes.

**Comment by mazameli** [comment]
When I do the zoom drill down, this is what I see:

zoom-in-table


The auto binning logic is oddly not picking the finest granularity (0.1) in this case where I only have points within the bounds of San Francisco:

screen shot 2018-04-18 at 3 55 09 pm

Manually choosing the 0.1 degree bins is definitely a step in the right direction, though in the future it would be cool if auto-binning could go to finer granularities than this:

screen shot 2018-04-18 at 3 55 54 pm

**Comment by tlrobinson** [comment]
I've made lat/lon zooming work to finer granularities. Now it always just divides by 10.

The auto binning happens in the backend, so should probably be addressed in a different PR.

**Pull request merged**
