### PR TITLE
Permissions groups (roles) v1 (Databases/Schemas/Tables) v2 [WIP]

### PR DESCRIPTION
**Pull request by camsaul**
Supersedes #3088 
Implements #3362, #1083, #2856

### CODE REVIEW

**Comment by camsaul** [comment]
@tom even though the "Save Changes" button looks disabled if you don't make any changes you can still click it 

screen shot 2016-09-26 at 4 05 25 pm

**Comment by camsaul** [comment]
@tom also I'm seeing weirdness if I switch my Data Access from ❌ to ✅  it says I will be denied access to one table

###### BEFORE (Mysteries Inc. has no access for Drew-id)

screen shot 2016-09-26 at 4 06 05 pm

###### AFTER (Mysteries Inc. has full access for Drew-id)

screen shot 2016-09-26 at 4 06 11 pm

**Comment by camsaul** [comment]
@tlrobinson even though the confirmation seems off it still seems to be doing the right thing as far as the API call is concerned.

**Comment by camsaul** [comment]
@tlrobinson I think the permissions confirmation box has add and revoke backwards because here I switched the perms for a DB to "none" and got a dialog saying all the things that are being revoked are being granted

screen shot 2016-09-26 at 4 30 16 pm

**Comment by camsaul** [comment]
@tlrobinson at least for schemas/tables. For native queries looks like we should tweak the copy when you switch to "none"

**Comment by mazameli** [comment]
So, here's some things I'm seeing that need addressing:

**Interactions**
- “Back” needs to be replaced with breadcrumbs. It's impossible to tell where you are in the stack currently. In the Sketch file, I depicted using the pattern we have currently for the admin panel databases section, though I'm not wedded to this:

screen shot 2016-09-28 at 10 59 08 am


- If I try to leave the page with dirty changes, I should be blocked by a modal. Title: You have unsaved changes. Body: Do you want to leave this page and discard your changes? Buttons: Yes No.
- I'm realizing it's unclear what the `Cancel` button at the bottom of the page should do. This is an example of where the top, blue editing bar pattern is superior, because with it, canceling would revert your changes and make the bar go away (i.e., you'd exit Edit mode). I suppose with the current design, the whole save bar could slide down if you hit `Cancel`. In any case, I think we're going to want a confirmation modal to make sure they want to discard their changes.
- I don't think the “Changing this DB to limited access” modal should appear when at the top level (DB) view; it's only useful when you're at the schema/table/column levels.
- At deeper levels, that modal has a typo: “Changing this DB to limited **limited** access"

**Cosmetic things and microcopy**
- The designs depict displaying the real/underlying schema name of each item above the row label. 

screen shot 2016-09-28 at 11 23 24 am

- I think the row headers should be text-align: left rather than center
- I think “Administrator” should be “Administrator**s**"
- dropdown menus needs `cursor: pointer`, because of course they do ;)
- I think the active state of the `Save Changes` button should be blue. (I know Sameer had proposed we use the top bar pattern that we use for dashboards, etc., but it's not currently used anywhere in the Admin Panel. I'm open to trying that route, though.)
- I find it a little hard to remember what each row represents when I'm switching between levels. I'm going to try mocking up what it looks like if each row's label has a corresponding icon next to it.
- I think we're all on the same page that the "buttons" that are in each cell need work. It's hard to tell they're clickable (as @camsaul would say, they lack visual affordance), and it's hard to tell that the Administrator ones aren't clickable. I also think they're too tall. I'll do some experimenting with the design.
- The “Raw queries” column label sounds ambiguous to me compared to the less-correct “SQL queries." I strongly feel like people are going to mistake this for the `Raw data` view (I think Kyle mentioned that in the Slack channel).
- Vertical rules between groups look too dark compared to the design.
- I'm wondering if we want to expand out the width of the table to 100% of the available space, even if there are only two columns. It just looks a little bare right now.

**Comment by mazameli** [comment]
Two thoughts on the Groups section:

- If I get removed from a group, it’s possible I will no longer have access to an artifact I created. Therefore, I should probably get an email notification just like I would if the permissions for a group I’m in have changed. The admin should also probably get a confirmation modal when clicking to remove a user from a group.
- Less importantly, in the next version, we might want to consider fleshing out group pages with things like: date the group was created, an audit history, date column for when users were added to the group, an optional description field for the group…

**Comment by salsakran** [comment]
Let's do emails in stage 2 given how group centric it's shaping up being. Things are already getting pretty heavy for stage 1. #shipit

**Comment by camsaul** [comment]
This PR is bigger than most of our releases 🙀 

image

**Pull request merged**
