### PR TITLE
Rotate the loading spinner in a non-linear fashion

### PR DESCRIPTION
**Pull request by ariya**
This adds some flair of "physics" to the spinner.

For more details, see https://ariya.io/2017/10/fun-with-single-element-css-spinner.

**Before:**

https://user-images.githubusercontent.com/7288/104876143-e8ca0c80-590b-11eb-9246-d57ee8e9cd0a.mp4

**After:**

https://user-images.githubusercontent.com/7288/104876148-ebc4fd00-590b-11eb-8659-f1456534b7b7.mp4

### CODE REVIEW

**Review by nemanjaglumac — APPROVED** [review]
Really nice improvement, @ariya . Thanks for taking care of this.

**Comment by mazameli** [comment]
Let me tweak the timing on the animation a bit before we merge this, please.

**Comment by nemanjaglumac** [comment]
Unrelated to this PR - could we raise the bar and use our own logo with some custom dots animation sometimes in the future?

**Comment by mazameli** [comment]
Just slowed it down by half a second and I think it looks classier now:

spinner

**Review by mazameli — APPROVED** [review]

**Pull request merged**
