### PR TITLE
Fix two issues with dashboard click behavior

### LINKED ISSUE #14473: Click Behavior with cross-filter sometimes does not list column options
**Describe the bug**
When doing cross filtering on the same dashboard, then it will sometimes not list the columns as available options, but allows updating one filter with another filter.

**To Reproduce**
1. Native question > Sample Dataset > `SELECT COUNT(*) FROM PRODUCTS` as Table viz, save to dashboard
2. Add 4 filters - 2 category, 2 id (doesn't matter if they are connected)
3. Hover card > Click Behavior > select column > "Update a dashboard filter"
4. Clicking "ID 1" option will correctly show the column as option, but also shows the other "ID" dashboard filter.
image
5. Clicking "Category" option will only show the other "Category 1" filter, but not the column.
image

**Expected behavior**
It should allow selecting a numeric column for a category filter.
I don't think you should be able to update the filters with another filter on the same dashboard - only on "Go to a custom destination".

**Information about your Metabase Installation:**
Tested 0.37.0 thru 0.37.7

**Additional context**
https://discourse.metabase.com/t/cross-filtering-not-working/13041

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #14473

This PR makes two changes to dashboard click behavior:
- It allows mapping numeric columns to dashboard category filters.
- It disallows using filters as sources for crossfiltering. 

Any issues with those changes, @mazameli?

### CODE REVIEW

**Review by daltojohnso — APPROVED** [review]
LGTM

**Review by mazameli — CHANGES_REQUESTED** [review]
This branch seemed to break custom click behavior for me, and would never show me the options for which filter I wanted to update. I tried the branch out with a new dashboard and new saved GUI question on both Safari and Chrome. After getting into this state, I couldn't get the click behavior sidebar to open any more until refreshing the browser.

broken-behavior

**Comment by paulrosenzweig** [comment]
@mazameli sorry about that! A typo was breaking everything. The Cypress tests were failing but our Cypress.io issues incorrectly marked them as passing.

**Comment by mazameli** [comment]
@paulrosenzweig No worries! Let me pull this down now and try again.

**Comment by mazameli** [comment]
Seems good now. When we originally shipped this, could you cross-filter by updating the value of filter X to the value of filter Y? Seems nonsensical, so it makes sense to me that this PR removes that as an option, but I'm just trying to think if there's a legitimate use case I'm not thinking of, like maybe having to do with hidden filters or something — but I'm pretty sure we're okay here.

**Review by mazameli — APPROVED** [review]

**Pull request merged**
