### PR TITLE
Fix exports for queries with aggregations

### LINKED ISSUE #18181: Export in 0.41.0-rc1 does not include aggregated columns
Hi,

I would like to report an issue with the newest released RC version.
The export function is not always working as intended.

The new export way doesn't always name the file in the new way.
Somtimes the naming starts with the title off the report, sometimes with Query_result....

I also have a specific report that is always exported as 'empty'. It only gives me the title column. All the data values are gone. CSV, XLSX, JSON they are all empty besides the title.

Schermafbeelding 2021-10-01 om 13 48 48
Schermafbeelding 2021-10-01 om 13 48 30

Diagnostic information:
```
{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "nl",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-09-29",
      "tag": "v0.41.0-RC1",
      "branch": "release-x.41.x",
      "hash": "6ff4eda"

    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by noahmoss**
Previously, to order viz settings & data for exports, I was using a map that associated column IDs and/or names with their position in the `cols` list. This code made an assumption that the `field_ref` for a column to have either an ID or name in the second position.
 
This approach worked fine for most fields, but did not work for aggregated fields which have the `field_ref` format `[:aggregation n]` where `n` is, I believe, unique for each aggregated field in the query. I've changed the key to use the first two entries in the field ref as the key instead (i.e. excluding metadata), which works for normal and aggregated fields. 

I needed to call `keyword` on the first entry in the key ref since it's a string in the viz settings (e.g. `["aggregation" 0]`), but a keyword in `cols` (e.g. `[:aggregation 0]`). I'm not sure where this discrepancy arises; if anyone knows, please enlighten me. 

Resolves #18181

### CODE REVIEW

**Review by flamber — APPROVED** [review]
This works, and tried several questions from 0.37, since there were dimension changes in 38 and 39.
But I simply don't understand the underlying problem.

**Comment by noahmoss** [comment]
Essentially the code was assuming that the `:field_ref` fields in the result metadata had a certain format, with the field ID or name in the second position. This didn't hold true for aggregations, causing them to be dropped from the column ordering used for exports.

**Comment by pawit-metabase** [comment]
> I was using a map that associated column IDs and/or names with their position in the cols list.

I haven't read the code so I don't know if it's handled already or not, but note that it is possible for a column ID to appear more than one time in result, for example, during a self-join, in which case you will want to differentiate them with the `:join-alias`.

**Comment by noahmoss** [comment]
@pawit-metabase Sigh...you're right, that's another edge case that is was breaking this. I've added handling for this as a special case.

It would be better if this could all be refactored so that we could correlated fields by the entire `field_ref` value. But since viz settings are passed in from the frontend for unsaved questions and parsed from JSON to Clojure, it doesn't exactly match the `field_ref` values in the query result metadata -- some values are strings when they should be keywords, etc.

**Pull request merged**
