### PR TITLE
#12600 Repro: Crash in ObjectDetail when parsing invalid JSON

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Reproduces #12600 

### How to test this manually?
- `yarn test-cypress-open`
- `frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js`
- All tests should pass

### Additional notes:
- The bug was fixed in #13633

### Screenshots:
image

### CODE REVIEW

**Review by flamber — APPROVED** [review]
Should the other test be removed?
https://github.com/metabase/metabase/pull/13633/files#diff-cf1c071510447a63b61d690f858cd466909442933e64ab950b58f4c9d98a4a88

**Comment by nemanjaglumac** [comment]
I don't think it hurts to have unit test as well. 
It has been updated since then:
```javascript
it("should not crash rendering invalid JSON", () => {
  render(
    <ObjectDetail
      data={invalidObjectDetailCard.data}
      series={invalidObjectDetailCard}
      loadObjectDetailFKReferences={() => ({})}
      settings={{ column: () => ({}) }}
    />,
  );

  screen.getByText(/i am not json/i);
});
```

@paulrosenzweig what do you think? Keep both tests or just one (which one)?

**Comment by paulrosenzweig** [comment]
I don't have strong feelings, but I think only using the unit test is better. Both tests are already written so aside from a second of runtime and possible maintenance down the line, it doesn't hurt to have both.

In general if a unit test provides sufficient coverage, I think we should stick with that since it's faster. Here, the bug logic is straightforward and confined to one (unconnected) component. Running the test inside a full app with Cypress doesn't really change things.

**Comment by nemanjaglumac** [comment]
Thank you for detailed answer.
I thought we're getting a bit more coverage with e2e, but that's probably not directly related to this issue. A weird example would be if you can't even click ID to "arrive" at the object detail page. That's probably very unlikely to happen, so I get your point and I agree.
Besides, even if something weird like that happens, some other test should catch it.

To avoid duplicates in the future, it would be awesome if we start marking unit tests that are repros with the same notation as we do for Cypress.

`test-name(metabase#XXXX)`

**Comment by paulrosenzweig** [comment]
> To avoid duplicates in the future, it would be awesome if we start marking unit tests that are repros with the same notation as we do for Cypress.

👍 I like it!

**Comment by nemanjaglumac** [comment]
I'll close this. Sorry for the confusion.

**Pull request closed without merging**
