### PR TITLE
Remove whitelabel navigation bar color option in Admin settings

### PR DESCRIPTION
**Pull request by gusaiani**
The "navigation bar color" seems to
1. control the background color for the sidebar
2. have a white background color by default

however, the current label says something different.

### How to check changes.

Go to http://localhost:3000/admin/settings/whitelabel and see the text following "Navigation bar color".

### After

image

### Before

image

### CODE REVIEW

**Comment by flamber** [comment]
This would close out #22221

**Comment by mazameli** [comment]
Hm, I need to look at this more closely but I think the conversations had been more about getting rid of this option entirely, as I don't know that we want to allow folks to set the sidebar to different colors. I'll take a look and check in with Conor.

**Comment by mazameli** [comment]
So to circle back, as per https://github.com/metabase/metabase/issues/22221, I think this setting should be **cut**. @kdoh [agreed](https://metaboat.slack.com/archives/C01MS7DQKR6/p1651232871644519?thread_ts=1651181848.005029&cid=C01MS7DQKR6), and I'll take @cdeweyx's 👌🏼 on that thread as at least acquiescence. ;) 

---

By way of example, this is how I think we're envisioning the app looking when people change the UI colors:

image

The new nav wasn't designed with the intent of people doing this, by contrast:

image

**Comment by cdeweyx** [comment]
@mazameli I'm on board with that

**Comment by cdeweyx** [comment]
> So to circle back, as per #22221, I think this setting should be **cut**. @kdoh [agreed](https://metaboat.slack.com/archives/C01MS7DQKR6/p1651232871644519?thread_ts=1651181848.005029&cid=C01MS7DQKR6), and I'll take @cdeweyx's 👌🏼 on that thread as at least acquiescence. ;)
> 
> By way of example, this is how I think we're envisioning the app looking when people change the UI colors:
> 
> image
> 
> The new nav wasn't designed with the intent of people doing this, by contrast:
> 
> image

@mazameli I'm on board with that

**Review by mazameli — CHANGES_REQUESTED** [review]
Just marking this as "changes requested" so my GH bot will stop bugging me for a review. [Feedback here](https://github.com/metabase/metabase/pull/22406#issuecomment-1118062679)

**Comment by gusaiani** [comment]
@mazameli, I've removed the option to choose the nav color.

If ok and merged, we should probably clean up the backend, and also the place in the frontend where the color is defined so it doesn't check for a user set color.

First, I'd like to be sure you think we should go forward with it at this time.

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
@gusaiani Yep, this looks right to me. Can we be sure that if someone had previously set a value for this setting that we're resetting their sidebar back to the default/correct color, so that they don't e.g. get stuck with a bright purple sidebar or something? 😄

**Comment by gusaiani** [comment]
> Yep, this looks right to me. Can we be sure that if someone had previously set a value for this setting that we're resetting their sidebar back to the default/correct color, so that they don't e.g. get stuck with a bright purple sidebar or something? 😄

@mazameli  Yup :) Will follow up on this.

**Pull request merged**
