### PR TITLE
Funnel visualization

### PR DESCRIPTION
**Pull request by mavimo**
Implements funnel visualization. This is only a first draft, use CSS3 property to draw funnel instead of JS lib, actually don't work on IE.
###### DEMO

Using:

```
CREATE TABLE `demo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `proprieta` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `demo` VALUES (1,'first'),(2,'first'),(3,'first'),(4,'first'),(5,'first'),(6,'first'),(7,'first'),(8,'first'),(9,'first'),(10,'first'),(11,'first'),(12,'first'),(13,'first'),(14,'first'),(15,'first'),(16,'first'),(17,'first'),(18,'first'),(19,'first'),(20,'first'),(21,'first'),(22,'second'),(23,'second'),(24,'second'),(25,'second'),(26,'second'),(27,'second'),(28,'second'),(29,'second'),(30,'second'),(31,'second'),(32,'second'),(33,'second'),(34,'second'),(35,'third'),(36,'third'),(37,'third'),(38,'third'),(39,'third'),(40,'third'),(41,'third'),(42,'third'),(43,'third'),(44,'fourth'),(45,'fourth'),(46,'fourth'),(47,'fourth'),(48,'fourth'),(49,'fourth'),(50,'fifth'),(51,'fifth'),(52,'fifth'),(53,'fifth');
```

And the config:

screen shot 2016-08-06 at 21 21 46

We are able to generate the funnel visualization:
- screen shot 2016-08-06 at 21 11 57
- screen shot 2016-08-06 at 21 13 14

(two draft, the first one i think is more appropriate, but i prefer the second version)
###### TODO
- [x] Create graph using to D3 (already included in Metabase)
- [ ] `componentDidUpdate`
- [x] Configuration area
- [ ] Split component in react sub-component (FunnelVertical)
- [ ] Split component in react sub-component (FunnelHorizontal)
- [ ] Tests
- [ ] Storybook
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform).

### CODE REVIEW

**Comment by mavimo** [comment]
@camsaul @tlrobinson can you have a check, and give me some feedback/suggestion/indication if it can be useful also for other ppl?

**Comment by jacopoch** [comment]
This will be extremely useful for us for example. We're building our analytics around Metabase and funnels are something that not many tools are good at visualising!
I hope it makes its way to one of the future releases!

**Comment by tlrobinson** [comment]
@mavimo Nice work! We're actually working on some new visualizations for the next release so this is good timing.

@mazameli How does this fit in with your ideas for a funnel visualization?

**Comment by mavimo** [comment]
@jacopoch ciao :) Can you share your "requirements" for the funnel visualization? I'm exploring some idea about information to display, eg:
 - The funnel need to match exactly the start/end size or can be only indicative?
 - What happen for long funnel (15-20 steps)?
 - What happen for funnel with big drop rate after some steps (eg: drop 80/99/99.5/99.7/99.9)?
 - We need to show drop rate step-by-step, and total drop rate?
 - Color need to approximate some kind of information or can just be "random"?

@tlrobinson I'm also working on gauge and to extend the map visualization to include some european country (not only US + Word, but also Italy, France, Germany, ...) There is a large dataset already available on http://code.highcharts.com/mapdata/1.0.0/ (based on information from NaturaEarthData that are free for use in external tools, see http://www.naturalearthdata.com/about/terms-of-use/), WIP will be available I some week.. if you are already working on it let me know so I can help/stop to work on the same type of widget :)

**Comment by tlrobinson** [comment]
@mavimo Cool, gauges and the ability to upload custom GeoJSONs are also on the roadmap, but I haven't started working on either. @mazameli will also have things to say about the UX for those.

Regarding choropleths/GeoJSONs, we're planning on switching our map visualizations to Leaflet, and that might include choropleths. So far we just have PR #3133 for pin maps (originally @shahinism's #2737) but not choropleths (e.x. http://leafletjs.com/examples/choropleth.html)

**Comment by mazameli** [comment]
I'll be looking over this thoroughly today, but looks really promising!

**Comment by jacopoch** [comment]
@mavimo to answer your questions:

#### What happen for long funnel (15-20 steps)?
In this case we'd want to draw a vertical funnel, I'd love not to limit the length in height of a widget of this kind, however I think very seldom 20 steps funnels are useful (IMHO).
 
#### What happen for funnel with big drop rate after some steps (eg: drop 80/99/99.5/99.7/99.9)?
The viz should support showing these situations and the chart should accommodate for it, I guess placement of the numbers can be figured out for these edge cases.

#### We need to show drop rate step-by-step, and total drop rate?
Yes, I'd say both.

#### Color need to approximate some kind of information or can just be "random"?
I'd make possible to define a gradient and make it reversible (beginning lighter, end of the funner darker).

One additional important thing would be to allow grouping or mosaics in the funnel, by adding another dimension like a segment, you should be able to produce something like (excuse the drawing):

screen shot 2016-08-08 at 23 45 49

**Comment by jacopoch** [comment]
And to clarify the "mosaic" funnel above, the need we have is mainly to follow A/B tests or groups of objects as they move towards conversion.
Funnels are usually good but it's hard to compare between funnels unless you can "stitch them together" 👍

**Comment by mazameli** [comment]
So, some initial thoughts:

- Overall, this looks really great
- We'll want to make sure this visualization respects our nice looking labels for things like times/dates:
make time labels nice
- We'll have to figure out a design for funnels to look nice on dashboard cards at various sizes:
make them work on dashboards
- For cases where there are lots of steps (~20), vertical is one possibility, but would break our convention with all other charts, which is to have them all fit inside of the browser window. I'd propose instead that we do some responsive restyling, like making the count values rotate 90 degrees and putting the percentage drop values into tooltips, etc. Whatever we do in this situation is very likely exactly what we'll have to do with small dashboard cards. I'll work on some mockups.

**Comment by salsakran** [comment]
This looks awesome @mavimo !

Re 15-20 step funnels. Honestly at that point, YourDoingItWrong, and it's not clear that a funnel really is the best way to display this. I think it's ok to start dropping information at smaller card sizes as needed and let hover states display the #'s and %'s.

Re color, I definitely like the single gradient!

**Comment by mavimo** [comment]
@mazameli yeap, small card ([Min size is 4x5](https://github.com/mavimo/metabase/blob/feature/funnel-visualization/frontend/src/metabase/visualizations/Funnel.jsx#L16-L17), are you able to make it smaller?) with a lot of steps are broken, will be improved in the next iterations.

@mazameli chose label/value columns will be done in the funnel configuration, I'll start to investigate how to do it this night ;)

@jacopoch introduce "mosaics" in funnel for A/B testing should be a nice idea, maybe can be done in the next iteration (need to change how to design funnel steps), but absolutely 👍 

@salsakran I know, 20 steps are not "the best approach" but sometime funnel are used to identify the main drop motivation, on long process we can also have 20+ steps, maybe we can drop this kind of edge-case on the first iteration?

@jacopoch do you think single color, single gradient can be fine at the begin? I prefer to limit config/feature on the first release, and I agree with @salsakran, colors "are not important"...

**Comment by mavimo** [comment]
## Data
```sql

CREATE TABLE `demo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `channel` varchar(100) DEFAULT NULL,
  `metric_a` int(11) DEFAULT '0',
  `metric_b` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
);

SELECT * FROM metabase_funnel.demo;
INSERT INTO `metabase_funnel`.`demo`
(`channel`, `metric_a`, `metric_b`)
VALUES
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('first', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('second', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('second', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('second', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('second', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('second', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('second', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('second', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('second', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('third', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('third', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('third', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('third', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('third', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('fiurth', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('fiurth', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('fiurth', FLOOR(RAND()*10), FLOOR(RAND()*10)),
('fiurth', FLOOR(RAND()*10), FLOOR(RAND()*10));
```

## Question

```sql
SELECT
    `demo`.`channel` AS `channel`,
    sum(`demo`.`metric_a`) AS `Metric A`,
    sum(`demo`.`metric_b`) AS `Metric B`
FROM `demo`
GROUP BY `demo`.`channel`
ORDER BY `Metric A` DESC,
         `demo`.`channel` ASC
```

## Preview

screen shot 2016-08-09 at 21 43 17

**Comment by mavimo** [comment]
@mazameli 
> We'll want to make sure this visualization respects our nice looking labels for things like times/dates

I'm not sure the component should change the data representation, if you need to format maybe you can change the original query?

PS: fake dataset have a typo, sorry `fiurth` => `fourth`

**Comment by mavimo** [comment]
@mazameli 
> For cases where there are lots of steps (~20), vertical is one possibility, but would break our convention with all other charts

As I can understand vertical funnel should be "not allowed"?

**Comment by mazameli** [comment]
> I'm not sure the component should change the data representation, if you need to format maybe you can change the original query?

I'm sure this is a matter of just hooking up the step labels to our display logic or something. All of our other chart types make time stamps look nicer.

>> For cases where there are lots of steps (~20), vertical is one possibility, but would break our convention with all other charts

> As I can understand vertical funnel should be "not allowed"?

Yeah, that's my current opinion. I really don't think we want to introduce vertical scrolling in order to see all of a visualization. A funnel with tons of steps should be treated as an edge case that we can handle gracefully, but not optimize for.

**Comment by mavimo** [comment]
@jacopoch you can find a firstr draft of funnel mosaics on branch [feature/funnel-visualization-mosaics](https://github.com/mavimo/metabase/tree/feature/funnel-visualization-mosaics).

Since I switch to a full SVG representation there are some feature missing and design need to be re-worked. @mazameli do you have some design guideline/suggestion?

### TODO:

- [ ] Introduce single step values
- [ ] Introduce legen
- [ ] Improve styling
- [ ] Check visualization on low resolution

### Preview: 
screen shot 2016-08-13 at 15 10 53

### Configuration:
screen shot 2016-08-13 at 15 11 03

screen shot 2016-08-13 at 15 10 57

**Comment by mavimo** [comment]
@jacopoch I see also your mosaics use "horizontal" line to separate A/B metrics, I prefer to have it matching the exact behavior on the user side, eg:

screen shot 2016-08-13 at 15 19 47
screen shot 2016-08-13 at 15 18 42

**Comment by jacopoch** [comment]
@mavimo looking good!

**Comment by mazameli** [comment]
This is great stuff, mavimo. In this new segmented view, I think some simple enhancements would be:

- [ ] apply the same gradient effect on each step to gradually fade out the colors as you're doing in the single metric/segment version
- [ ] display the initial value for each metric by its label (e.g., "Metric A: 1,745")
- [ ] I don't know if there's room to display the percent changes for every metric at every step, but that would be something to try
- [ ] @kdoh or I can help out with the font styling for the step and metric labels
- [ ] the width of the visualization should fill up 100% of its container's space
- [ ] there should be a bit more margin at the bottom of the chart

Maybe @kdoh and @tlrobinson will have some thoughts on next steps to get this merged. It would probably make sense for kdoh to help with implementing some of the style tweaks I've mentioned. He's also working on some styling for the funnel at small sizes, etc.

We're excited about this feature! 💯  😍

**Comment by mavimo** [comment]
@mazameli some suggestion are already implemented on https://github.com/mavimo/metabase/tree/feature/funnel-visualization-mosaics

- [x] apply the same gradient effect on each step to gradually fade out the colors as you're doing in the single metric/segment version (see https://github.com/mavimo/metabase/commit/17a787c0d8aa6a7971a7986106fb557c51694724#diff-ad4a249e6706a5c0d6b92ab867bc0ca3R87 )
- [x] the width of the visualization should fill up 100% of its container's space (see https://github.com/mavimo/metabase/commit/3f127c8e2e11677e75175ac21e90da9b820d563e#diff-ad4a249e6706a5c0d6b92ab867bc0ca3R120 )
- [x] there should be a bit more margin at the bottom of the chart (see https://github.com/mavimo/metabase/commit/3f127c8e2e11677e75175ac21e90da9b820d563e#diff-ad4a249e6706a5c0d6b92ab867bc0ca3R56 )

About:

 - [ ] display the initial value for each metric by its label (e.g., "Metric A: 1,745")
 - [ ] I don't know if there's room to display the percent changes for every metric at every step, but that would be something to try

I agree but I'm not sure how can display all this information in the funnel without "overload" user with data; we need to show information (initial step value, end step value, % lost) for each "metric" and for the "total" value, for each step... I think can be too complex to display on small graph, so i'm going to investigate how to display tooltips to display details and show only a basic information in the grap.

I'm going to fix some conflict after branch rebase, after I'll sent the screenshot of the current status ;)

@mazameli @kdoh any help on text formatting is really appreciated :)

@jacopoch thx! :)

**Comment by mavimo** [comment]
screen shot 2016-08-15 at 19 30 46

screen shot 2016-08-15 at 19 31 46

**Comment by mavimo** [comment]
Counter for initial value:

screen shot 2016-08-15 at 20 31 09

**Comment by mavimo** [comment]
Merged funnel visualization (with mosaics feature) in the initial funnel visualization feature, I rewrite a bit the git history to have consistence on messages, and rebased on master to be sure to make it easy to CR & merge.

@kdoh @tlrobinson any suggestion how to move to make this feature mergeable (and allow other people help me to improve it :) )?

**Comment by mavimo** [comment]
@mazameli added step values (only for total) and over effect on series.

@jacopoch I'm not sure if we need to display step % remaining or the % of the lost value, do you know if there is some "standard" about it?

screen shot 2016-08-16 at 23 36 02
screen shot 2016-08-16 at 23 35 57

**Comment by mavimo** [comment]
Introduce funnel step information using tooltip.

There is some issue on tooltips for single serie value (are this information required?) and on multiseries where the tooltip is limited to SVG area).

@jacopoch @mazameli @tlrobinson any suggestion? This is my first React component, so I suppose there are some main issue (eg, I'm not sure about `key` value and how to reference items using key, so I used `class` attribute 👎 ).

## Demo
screen shot 2016-08-21 at 13 07 06
screen shot 2016-08-21 at 13 07 02
screen shot 2016-08-21 at 13 07 09

**Comment by tlrobinson** [comment]
@mavimo You should use the functionality we already have for tooltips. Look for `onHoverChange` in some of the other visualizations.

**Comment by mavimo** [comment]
@tlrobinson I see the ToolTip class but is implemented using HTML (`<div>`, ..) , actually I' using SVG element (since it's into `<svg>` element), I'll try to move it outside the grap.

**Comment by tlrobinson** [comment]
@mavimo You don't need to render the Tooltip yourself, you just call the `onHoverChange` prop and the parent component will display the tooltip for you.

**Comment by tlrobinson** [comment]
Oh area you trying to render multiple tooltips at the same time as you have in the screenshot?

@mazameli How is this looking design-wise?

**Comment by mavimo** [comment]
@tlrobinson yes, when user move mouse over a single serie all tooltips are visible (se you can see all required information for this "pipe"). I'm not sure is the best idea, but this make possibile view all require information without move the mouse around each step/pipe (that can be hard at the end of the funnel where the pipe size is really small).

**Comment by mazameli** [comment]
@mavimo I don't think the multiple tooltip approach is working. I'm spending some time this morning finishing up some designs to help finish this off — stay tuned. 👍

**Comment by mazameli** [comment]
So here are some updated thoughts:

1. We'd like to simplify this first version, specifically by removing the the multi-segment option from this PR and saving that for a future PR. There are some bigger questions we have about that specific functionality that we'd like to sort out separately.
2. I think we can provide enough information to users with the real estate we have without including any tooltips at all, so let's remove the tooltip functionality entirely, except for at small dashboard card sizes, when we need it.
3. After discussing with @salsakran, I think the information we should provide on screen is: 

- The initial total value of the metric
- The metric value at each step 
- The name of each step
- The **percent retained** at each step (not the drop off). (The thinking is that in most use cases, you're asking yourself what percent of customers converted, or what percent of users went from step 1 to step 2 — not how many _didn't_. And It's usually simpler arithmetic to mentally calculate the dropoff percentage than the opposite.)

Here's a mockup of the large version on the main question page:

funnel

And here's a large dashboard card:

larger dashboard card


And a small dashboard card, with accompanying hover state:
small dashboard card


Here is a zip with all the font sizes, spacing, colors, etc.
[funnel design specs.zip](https://github.com/metabase/metabase/files/438285/funnel.design.specs.zip)

@metabase/core-developers, let me know if you have feedback on the visual design. 
@mavimo, let me know if all this makes sense. Again, we tremendously appreciate your contributions to the project!

**Comment by salsakran** [comment]
One random thought, for long lived funnels, it would probably be useful to name the steps via visualization settings. This will typically correspond to the specific stage in a funnel better than whatever the breakout value is.

**Comment by mavimo** [comment]
@mazameli thanks for your work on design! I'll try to implement your version ASAP; at this point, maybe I can go back to HTML approach instead of SVG approach.

After a short discussion with biz on company I'm working seems that have "funnel channel" for A/B testing is really appreciate (and relevant) for the BIZ dept. I'll go to remove from the current version, but it make sense to introduce it ASAP, can I propose to continue to have it without "per channel" tooltip information but only in the graph? It make sense for you?

**Comment by mazameli** [comment]
I understand that the funnel-with-channels visualization is something that people in your business department might find really useful, but I think it would be better to wait and do that in a thought-out way rather than trying to cram it into the tooltip. I'm having a hard time envisioning an elegant way of doing that, particularly when considering that there could be a large number of potential channels. We're eager to get the simplest and best first version of this merged so that it can be stress-tested before we start adding in other enhancements. Thanks for your understanding!

**Comment by MrMauricioLeite** [comment]
Completely Agree here guys, even thgough splitting the funnel by two colors
whould be awesome for AB testing. Maybe even 3 splits are awesome. But I'm
sure that in the future we can find a better way to design that.

Anyway, this is just an amazing feature and you are incredible for adding
that to the product.
Maybe later we can look at funnels on d3 for inspiration, and further tests.

Congrats guys, love to Watch your Repo. Metabase is great thanks to you.

[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-08-26 14:22 GMT-03:00 Maz Ameli <notifications@github.com>:

**Comment by mavimo** [comment]
@mazameli 👍

**Comment by mavimo** [comment]
@mazameli current WIP (create with the same date from your sample, but it look a bit different ;) )

screen shot 2016-08-27 at 12 55 13

There are some small change in:
 - Date formatting (I used the default behavior on `import { formatValue } from "metabase/lib/formatting";`, I think using the default behavior should be better instead of custom visualization).

I need to work on the "small size" version, but I have also a small issue on the desktop version.

The date (when there are no enough space) should display ellipse + tooltip. In the initial implementation I do it work, but when I moved to CSS flex model to optimize the funnel steps visualization some problem appear, see:

screen shot 2016-08-27 at 12 59 01

After some investigation seems a problem related to `text-overflow: ellipsis;` with `flex` model. I think this is a separate issue that need to be fixed in `<Ellipsified>` component. I can't find issue related to it but I can't also find any `Ellipsified` usage in flexmodel, do you know if is an already know issue or is not a required behavior? There are some workaround (see https://css-tricks.com/flexbox-truncated-text/ ).

PS: I'm also working in a complete new branch, I'm not sure if the best solution is to open a new PR or just override this branch).

**Comment by mavimo** [comment]
Wip for the "small version".

screen shot 2016-08-27 at 15 24 45

**Comment by arnaudbouffard** [comment]
hey @mavimo  impressive work! i was just studying dumping Mixpanel (we're only planning to use it for user progress funnel visualisation) where metabase (we recently set it up and are so excited, looks really promising!) to offer funnels.

I read in [metabase documentation](http://www.metabase.com/docs/v0.23.0/users-guide/08-multi-series-charting.html) funnels can already somehow be built, but I wonder if/when your work will show up in the official Metabase.

I see a check failed upon merge, any news since early Feb?

**Comment by kdoh** [comment]
Hey there @arnaudbouffard! We ended up moving @movimo's excellent work from this over to #3275 and merged funnel support in that PR. Looks like we left this open accidentally.

If you look at [this documentation](http://www.metabase.com/docs/latest/users-guide/04-visualizing-results.html#funnel) it has some info on how to create funnels in Metabase.

**Comment by sabino** [comment]
@kdoh @tlrobinson @camsaul @salsakran @mazameli 
Hey guys, the mosaic feature was left out right? I was wondering because that would be a really nice feature.

**Pull request closed without merging**
