### PR TITLE
Pivot tables: Include fewer subtotal queries, switch to bitmap grouping representation

### PR DESCRIPTION
**Pull request by robdaemon**
Switch to using an index to separate the resultsets

 Reduce the powerset to what's actually requested

This will now generate a different set of breakouts, where the
first is always the breakouts requested by the original query,
the next are the powerset of `pivot_rows` (including the [] set)
This greatly reduces the response to something more manageable and
traversable in the front end, but exposes that we are not saving the
pivot_rows / pivot_cols values in the card, therefore the card and
embed endpoints now return the wrong data.

### CODE REVIEW

**Comment by robdaemon** [comment]
@paulrosenzweig this fixes some things and breaks another - hopefully the commit message explains. Looks like we definitely need to persist `pivot_rows` and `pivot_cols` in the database so that we can generate the right thing for `/card` endpoints

**Comment by paulrosenzweig** [comment]
I think I'm passing pivot_rows/pivot_cols to the card endpoint. I might have missed some cases there though, so let me know where you don't see the params coming through. 

However, we can't pass the params for public/embedded since we don't send down the query to the client. I think falling back to the powerset when the params aren't passed makes sense to cover that case.

**Comment by paulrosenzweig** [comment]
> This will now generate a different set of breakouts, where the first is always the breakouts requested by the original query, the next are the powerset of pivot_rows (including the [] set)

I don't think that's quite the right subset. For example to show the "grand totals" on the bottom, we need to group by just the pivot_cols.

Currently, the visualization doesn't gracefully handle missing subtotals. Sorry if that makes debugging difficult!

**Comment by robdaemon** [comment]
Yep, the call to `/api/advanced_computation/pivot/card/:card-id/query` has the `pivot_rows` and `pivot_cols` - so that's good.

For public/embed, yeah, we don't have a way to pass those in. Maybe if they were in the `visualization_options`? What I see in there now is in a format that makes sense for the front-end, but not for the backend. For now, I can just do the full powerset. That definitely means I need to do a bitmask and not just an index of which breakout it is. I think I came up with an idea for that last night.

**Comment by robdaemon** [comment]
okay whew I think this gets it, @paulrosenzweig - what tests out to be a proper bitmask, limited return sets when `pivot-cols` and `pivot-rows` are specified, full powerset of breakouts when it is not.

**Comment by robdaemon** [comment]
@paulrosenzweig Okay I added the missing subtotals you mentioned earlier - I'll get to the other endpoints tomorrow (Friday)!

**Comment by paulrosenzweig** [comment]
The frontend is working with the backend on this branch now.

**Comment by robdaemon** [comment]
okay I got the missing endpoints added to `api/advanced_computation/public.clj` but I didn't get all of their tests done. That last commit can be reverted or whatever if necessary if that blocks anyone.

**Review by paulrosenzweig — APPROVED** [review]
Backend code looks good. I reverted the last commit, but I'll open a new PR with it and the associated frontend changes.

**Pull request merged**
