### PR TITLE
Change admin UI: navbar and premium embedding widget

### PR DESCRIPTION
**Pull request by alxnddr**
[Product doc](https://www.notion.so/metabase/Clean-up-settings-navigation-a85a0aff236d419c8681a03e6dbcaec2)

## Scope
1) Navbar
- App navbar 
    - removed "Manage Metabase Cloud" menu item
    - renamed "Admin" -> "Admin settings"
- Admin navbar
    - replaced admin menu with exit button
    - added a metabase logo

Screen Shot 2021-12-10 at 03 32 29

2) Premium embedding
- replaced the premium embedding section with a new informational section about paid plans
 
Before
Screen Shot 2021-12-13 at 18 38 40

After
Screen Shot 2021-12-13 at 23 58 51

(Changing the Enterprise page which is in the product doc is extracted in a separate PR because it is blocked now https://github.com/metabase/metabase/pull/19343)

### CODE REVIEW

**Comment by agnes-pinhanelli** [comment]
@alxnddr looks good! Just want to make sure that [self-hosted, OSS instances still have the basket icon](https://www.figma.com/file/A5ouuvqtMkNXy78wrvuicQ/Clean-up-settings-navigation?node-id=58%3A4020) (to explore paid features) on the header, like shown in Figma. We won't show this icon for Cloud, Starter; Pro or Enterprise tho. I also just wanted to make sure [we are using the same style for hovers as shown in Figma](https://www.figma.com/file/A5ouuvqtMkNXy78wrvuicQ/Clean-up-settings-navigation?node-id=58%3A3954), can I see like a screen recording of that interaction or something like that please?

Premium Embedding looks good, but we won't have the box around the embedding secret key input & button, [you can see it here](https://www.figma.com/file/A5ouuvqtMkNXy78wrvuicQ/Clean-up-settings-navigation?node-id=226%3A3969).

**Comment by alxnddr** [comment]
> (https://www.figma.com/file/A5ouuvqtMkNXy78wrvuicQ/Clean-up-settings-navigation?node-id=58%3A3954), can I see like a screen recording of that interaction or something like that please?

Sure thing, here is a short video:
https://share.getcloudapp.com/E0uKDqDO

> Premium Embedding looks good, but we won't have the box around the embedding secret key input & button, [you can see it here](https://www.figma.com/file/A5ouuvqtMkNXy78wrvuicQ/Clean-up-settings-navigation?node-id=226%3A3969). And then I think there's a few tweaks needed for the spacing and size of inputs and texts, as shown on the link above.
Good catch, thanks! Will fix

**Comment by alxnddr** [comment]
@agnes-pinhanelli I've updated the branch and the screenshots, please have a look

**Review by daltojohnso — APPROVED** [review]

**Comment by agnes-pinhanelli** [comment]
@alxnddr looks good! :) thank you so much

**Pull request merged**
