### PR TITLE
Remove old type components

### PR DESCRIPTION
**Pull request by kdoh**
We had some name overlap that was understandably confusing in #13954. This switches over instances that used the old `Text` and `Subhead` components to the new ones and removes the old components themselves as well.

### CODE REVIEW

**Comment by mazameli** [comment]
Looks like the download popover got a bit funky:

### Before

image

### After

image

**Review by mazameli — CHANGES_REQUESTED** [review]
ICYMI, it looked to me that the change to `DownloadButton` caused some layout problems. Did `Text` (vs `/type/Text`) include vertical padding or margin?

**Comment by kdoh** [comment]
@mazameli Yup I saw. Going to dig into that this afternoon.

**Comment by kdoh** [comment]
@mazameli Fixed it up
image

**Review by mazameli — APPROVED** [review]

**Pull request merged**
