### PR TITLE
Show "Learn about your data" info on fresh model page

### PR DESCRIPTION
**Pull request by gusaiani**
### How to Test

1. `+New`
2. `Model`
3. `Native query`
4. Click on `book icon`

Sidebar should now show options of models, instead of the page erroring.

### CODE REVIEW

**Review by ranquild — CHANGES_REQUESTED** [review]
I debuged this and the underlying issue is that the `model` created by New -> Model isn't a correct model (or `dataset`, using metabase-lib terms). We should never get a question where `isDataset()` is true but `isStructured` is false. When creating a dataset from a question, we are using `composeDataset` method which returns a question with a structured query referencing the underlying query (either structured or native).

It seems to me that when we click on New -> Model we are creating the `Question` instance in a wrong way, and we should fix that instead of fixing symptoms.

**Comment by gusaiani** [comment]
@ranquild Got it, let me get to the instantiation then.

**Comment by gusaiani** [comment]
@ranquild @daltojohnso, adding `isSaved()` to the checks solves the issue.

I also experimented with running `composeMetadata` on the question when creating the new model hash, as per Alex's suggestion. That by itself did not solve the issue. I notice that for the context of a fresh model, `composeMetadata` will return `this`, that is, what it got in the first place. Changing this first `if` block in `composeMetadata` does not change the behavior and breaks the query one step down.

**Review by ranquild — APPROVED** [review]
It seems like `Learn about your data` works as expected now.

**Pull request merged**
