### PR TITLE
Scroll viewport if dragged item goes out of bound

### PR DESCRIPTION
**Pull request by maxzheng**
This will allow users to move a question to anywhere on the dashboard that may be outside of the viewport.

Testing: I have done some manual tests by dragging questions around and it works as expected. As for unit test, I am not really sure how to test this kind of change, but let me know if you want one and knows how.

### CODE REVIEW

**Comment by flamber** [comment]
Hi @maxzheng :wave: hopefully your first PR for many :wink: 
Is this a fix for #5333? When I test your code on Firefox, then it doesn't seem to trigger a scroll.
Maybe it's easier to update `react-draggable` to `^3.3.2`, and test with some more browsers?

**Comment by maxzheng** [comment]
@flamber yes. upgraded to latest 3.x version as that's compatible with React 15 used by this project. Latest 4.x is not compatible. Tested change in Chrome/Firefox/Safari and it works.

**Comment by maxzheng** [comment]
@flamber Looks like all tests passed except yarn flow. I am not familiar with that check so I am not sure why it is failing for the new version of react-draggable (not a frontend developer). Can you provide some guidance on what needs to be done? Thx.

**Comment by flamber** [comment]
@maxzheng I'm not sure why it's failing the test. Hopefully one of the frontend developers can spot it.

**Comment by mazameli** [comment]
I tried this out in Brave, Chrome, Safari, and Firefox and it worked for me. This is definitely a nice enhancement when editing tall dashboards. @paulrosenzweig or @kdoh, any guidance you can provide Max with re: those flow errors?

**Comment by kdoh** [comment]
My guess is this is flow not liking something in the type definitions of the new package. We have some 3rd party flow definitions in `frontend/interfaces` so we could add one for `react-draggable` there similar to the others. It's possible upgrading `flow` itself could help with these but it might produce other errors so I'm not sure we want to go down that road here.

We also already ignore a lot of packages in our `.flowconfig` so adding `.*/node_modules/react-draggable/.*` to that file is another option to suppress the error. Either of those approaches would be ok with me until we get a more robust flow type setup going using `flow-typed` or some such.

**Comment by maxzheng** [comment]
@kdoh Thanks for the tip. I tried to upgrade flow, but that started to bring in other peer dependencies, and it became a bigger change that I didn't feel comfortable making, so opting to ignore.

**Review by kdoh — APPROVED** [review]

**Comment by kdoh** [comment]
Thanks @maxzheng

**Pull request merged**
