### PR TITLE
Add ellipsified for table header and rows

### PR DESCRIPTION
**Pull request by tlrobinson**
Continuation of #4383 by @joannekoong

### CODE REVIEW

**Comment by tlrobinson** [comment]
@mazameli @kdoh we should verify this doesn't cause performance issues. There's a comment in the existing code `using formatValue instead of <Value> here for performance. The later wraps in an extra <span>`. It looks like Tooltip doesn't add new DOM elements but it does add 4 event listeners.

**Review by kdoh — COMMENTED** [review]
I am seeing a noticeable bit of lag scrolling the `Orders` table with remapped fields to show product and user names etc with those columns small enough to have their values ellipsified. If there's a stretch of rows with short names then things are normal and performant so I think it can probably be attributed to the tooltip addition.

**Comment by tlrobinson** [comment]
I'm guessing that's due to the `setState({ isTruncated: ... })` and subsequent re-render happening on ellipsified, but not non-ellipsified cells.

Not sure if there's an easy way to optimize that.

Maybe we should only enable this for headers?

**Comment by kdoh** [comment]
I went ahead and changed this so that we're only adding tooltips to headers to fix the performance issue. I think that strikes the right balance of usability improvement so you can get a hint at what a particularly long column is named without resizing. Going to go ahead and merge it after CI runs to (finally) close this out unless anyone objects.

**Pull request merged**
