### PR TITLE
Saved question picker fixes

### LINKED ISSUE #14287: Cannot select saved questions from collections that have colon in their name in the query builder
**Describe the bug**
The table picker says "No tables found in this database." for every collection that has a colon in its name. The reason is that the frontend sends malformed API requests (cuts the collection name right before the colon), and so it gets a 404 from the API.

**Logs**
Server:
```
[7876f9e5-776b-4a94-ba6b-469dc229e21e] 2021-01-06T20:53:31+01:00 WARN metabase.middleware.log GET /api/database/-1337/schema/ScanForm 404 1.1 ms (1 DB calls) 
"Not found."
```

Frontend:
```
[Error] Request entities,schemas,-1337:ScanForm: TK,fetch failed: – {status: 404, data: "Not found.", isCancelled: false}
	(anonymous function) (app-main.bundle.js:5:62011)
	l (vendor.bundle.js:98:125993)
	(anonymous function) (vendor.bundle.js:98:125778)
	r (app-main.bundle.js:5:57724)
	(anonymous function) (app-main.bundle.js:5:57844)
	promiseReactionJob
```

Note that the frontend thinks it's requesting schemas from `ScanForm: TK`, but the server log shows `ScanForm` only. 

**To Reproduce**
1. Create a collection with `:` in its name
2. Create a question, save it in that collection
3. Open query builder, select "Saved Questions" in the picker, then the collection you've created in step 1.

**Expected behavior**
Saved questions show up, just like for collections that don't have `:` in their name.

**Screenshots**
Screenshot 2021-01-06 at 20 57 55

**Information about your Metabase Installation:**

- Your browser and the version: Safari Technology Preview `Release 117 (Safari 14.1, WebKit 15611.1.7.2)`, Chrome `87.0.4280.88 (Official Build) (x86_64)`
- Your operating system: macOS 10.15.7 `(19H114)`
- Your databases: PostgreSQL, sqlite3
- Metabase version: `v0.37.4`
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Low-ish

**Additional context**
Manually making a request to `/api/database/-1337/schema/ScanForm:%20TK` instead of `/api/database/-1337/schema/ScanForm` succeeds.

### LINKED ISSUE #16899: Updated saved question data picker - styling improvements
There are a couple small tweaks we should make to the picker to make it a bit nicer to use.

1. The current width of 480 or so pixels makes the two columns of the picker about even which makes it feel more cramped and intense with a large number of collections and questions. Given we have the space, I'd increase the width to about 620px or so so there's less of a 1:1 relationship between the sidebar and the content.

2. There's no border separating the fixed search input from the rest of the picker. I'd add a `border-bottom` class or the equivalent in styled-components to create a cleaner separation between that fixed element and the scroll-able areas. 
Screen Shot 2021-07-06 at 10 33 47 AM

I went ahead and mocked up what these changes would look like using the web inspector to give an example. Screen Shot 2021-07-06 at 10 42 49 AM

### PR DESCRIPTION
**Pull request by alxnddr**
### Description

1) Adds 1px border below the search input
2) Makes the saved question picker wider
3) Fixes selecting collections with `:` in their names

Screen Shot 2021-07-06 at 21 27 56

Closes https://github.com/metabase/metabase/issues/16899
Closes https://github.com/metabase/metabase/issues/14287

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
Nice colon fix - and much better width, though it doesn't play nice on mobile. It was bad before, but more difficult now.
image

**Review by kdoh — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
Don't forget to unskip repro for 14287, please.

**Comment by alxnddr** [comment]
@flamber @kdoh what do you think about this quick fix for mobile devices?
Screen Shot 2021-07-07 at 20 21 34

**Comment by kdoh** [comment]
Better than before. At some point we'll want to do a version that's more usable, but I'm ok with this for now since we're not really expecting (nor do we see much evidence of) people trying to start brand new questions on mobile.

**Review by flamber — APPROVED** [review]
Looks great! :+1:

**Pull request merged**
