### PR TITLE
Additional tooltip metrics for waterfall and scatter charts

### LINKED ISSUE #4748: Tooltips shouldn't include `description` fields
description

### LINKED ISSUE #5176: Tooltips shouldn't display every single column in the result when visualizing raw/unaggregated data
This is a bit of an edge case, but tables with lots of columns can result in tooltips like this one:

screen shot 2017-05-22 at 4 57 33 pm

Since this is a pretty goofy situation, I think it would be okay to just show the first n columns, and then say `and x more…`. (It also might make sense in cases where the user is visualizing raw data, like a pin/heat map or a scatterplot, to have the table settings' show/hide columns selections affect which fields show up in a data point's tooltip.

For an example of when and why we might want max-width, look no further than https://github.com/metabase/metabase/issues/4748

### PR DESCRIPTION
**Pull request by kulyk**
Followup on #47700
Closes #5176, closes #4748

Adds an ability to include other dataset columns in tooltips for waterfall and scatter charts (in addition to cartesian ones).
Done primarily by switching waterfall and scatter's tooltip type to "series_comparison". Waterfall charts also needed [some preparation](https://github.com/metabase/metabase/commit/12a7da1c2a3f179cd818b36b65865b7df164643e) as they had a hard limit on a number of dataset metrics. The PR reworks them so instead of showing an error, we'd invalidate `graph.metrics` on a need and use `defaultMetrics.slice(0, 1)` by default (it's possible to change the metric column in viz settings)

### To verify

**Scatter**

1. New > Question > Orders > Visualize > Change display to "scatter"
2. Open viz settings, change "Subtotal" for x-axis and "Tax" for y-axis
3. Hover any bubble and ensure the tooltip only shows subtotal and tax info
4. Open the "Display" tab in viz settings and add more columns via "Additional tooltip metrics" setting
5. Hover any bubble again and ensure you can see selected metrics

**Waterfall**

<details>
<summary>SQL query for testing</summary>

```sql
select 'Apples' as product, 200 as metric, 10 as profit
union all
select 'Bananas' as product, 110 as metric, -4 as profit
union all
select 'Oranges' as product, 140 as metric, 15 as profit
union all
select 'Peaches' as product, 80 as metric, -7 as profit
union all
select 'Mangos' as product, 120 as metric, 2 as profit
```

</details>

1. New > SQL query > Paste the SQL above > Run > Change display to "waterfall"
2. Hover any segment and ensure the tooltip only shows info for two columns
4. Open the "Display" tab in viz settings and add more columns via "Additional tooltip metrics" setting
5. Hover any segment again and ensure you can see selected metrics

### Demo

scatter

waterfall

### CODE REVIEW

**Review by cdeweyx — APPROVED** [review]
Looks good ✅

**Comment by cdeweyx** [comment]
Can close https://github.com/metabase/metabase/issues/5176 and https://github.com/metabase/metabase/issues/4748 once we merge this

**Review by EmmadUsmani — COMMENTED** [review]
Screenshot 2024-09-24 at 3 19 55 PM

Looks great for the most part! I think the circle color inside the tooltip should match the bar color of the waterfall chart

**Comment by kulyk** [comment]
> Looks great for the most part! I think the circle color inside the tooltip should match the bar color of the waterfall chart

Thanks @EmmadUsmani! Please take another look, should be done in [`514efd7`](https://github.com/metabase/metabase/pull/48088/commits/514efd7afa4ff77bafb4752fd1126c7b2b29acda)

**Review by EmmadUsmani — APPROVED** [review]

**Pull request merged**
