### PR TITLE
Handle composite pk filters

### LINKED ISSUE #7599: Date or time in composite primary key break filtering
We have a use case where a primary key is made up of two columns, one of them being a date or timestamp, such as in this example for Postgres:
 
```
CREATE TABLE test
(
person_id integer NOT NULL,
created date NOT NULL,
PRIMARY KEY(created, person_id)
);

INSERT INTO test VALUES 
(1, '2018-05-01'), (2, '2018-05-01'),
(3, '2018-05-02'), (4, '2018-05-02'), (5, '2018-05-02'),
(6, '2018-05-03'), (7, '2018-05-03'), (8, '2018-05-03'), (9, '2018-05-03');
```

When exploring this table in MetaBase using "New Question -> Custom" and then setting a filter to e.g. "ON  2018-05-03, then the result does not show a list of 4 entries. Instead, the first individual entry is shown and there's a right arrow on the right of the screen to show the next entry. Clicking that arrow results in an error `Invalid value '2018-05-031': expected a DateTime.`

The same bug happens when the column uses a timestamp instead of a date type.

Expected behaviour:
The filter should show a table with 4 entries (for 2018-05-03).
```
6, 2018-05-03
7, 2018-05-03
8, 2018-05-03
9, 2018-05-03
```

A similar bug happens when grouping by day. The result is a list of 3 days, which is correct. But when clicking one of the days, an individual entry is shown instead of a list of values.

It appears that MetaBase gets tripped up by the column being part of the primary key. When the date or timestamp columns are not part of the primary key, the behaviour is as expected.

-  Your browser and the version: reproduced with Chrome Version 65.0.3325.181, Firefox 59.0.2
-  Your operating system: macOS 10.13
-  Your databases: reproducable with Postgres 10
-  Metabase version: v0.29.0
-  Metabase hosting environment: Mac app
-  Metabase internal database: H2

### LINKED ISSUE #13717: Only show Object Detail when there is 1 row - otherwise always show Table
**Describe the bug**
When filtering on a field type "Entity Key", but the result might contain more than 1 row (eg. because of composite keys #3475), then an Object View is shown, which leads to incorrect representation of the results.

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Orders
2. Change "ID" field type to "No special type", and "Quantity" to "Entity Key"
3. Simple question > Sample Dataset > Orders - click any row of Quantity, which then shows Object Detail visualization even though the request result returns more than 1 row (2000 in this case).
image

**Expected behavior**
Only show Object Detail, when the result is 1 row - otherwise always show a table.
This will protect against accidental incorrect Field Type, or when the data somehow deviates from expectations.

**Information about your Metabase Installation:**
Metabase 0.34.3 thru 0.37.0.2 - probably always been the behavior.

**Additional context**
Related to #7599 and #9447 and #11503

### PR DESCRIPTION
**Pull request by alxnddr**
Fixes https://github.com/metabase/metabase/issues/7599
Fixes https://github.com/metabase/metabase/issues/13717

### Description

When tables had non-unique PKs, filtering by the PK column showed only one record (https://github.com/metabase/metabase/issues/13717). The same happened with composite keys (https://github.com/metabase/metabase/issues/7599)

#### Composite keys
- Go to the Data Model settings `/admin/datamodel/database/1`
- Select the Orders table and make the `Quantity` column type = `Entity Key` in addition to the ID column
- Simple question -> Orders
- Ensure clicking on `Quantity` table values shows all records with the quantity
- Ensure clicking on `ID` table values shows the only record in the table
- Manually add `equals` filter for both `Quantity` and `ID` with one value for each
- Ensure it shows Object Details view instead of the table view

#### Non-unique PK
- Go to the Data Model settings again `/admin/datamodel/database/1`
- Select the Orders table and make the `ID` column type = `No semantic type`
- Simple question -> Orders
- Ensure clicking on `Quantity` table values shows all records with the quantity

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Review by kulyk — APPROVED** [review]
Nice! Code looks good and works as described

**Review by flamber — APPROVED** [review]
It seems like it's doing some weird stuff - it's really not different from currently, which doesn't work great, but just thought you might be able to spot what is happening.
Either way, this is a much improvement in correctness.

https://user-images.githubusercontent.com/1447303/134515844-a388d8e8-a940-4f6b-9574-e5f36b7b9085.mp4

**Comment by alxnddr** [comment]
@flamber I investigated a bit and I think I found what needs to be done. I'll do it in a separate PR

**Pull request merged**
