### PR TITLE
Enable saving to subcollection when access to parent is revoked (#14052)

### LINKED ISSUE #14052: Cannot save to sub-collection, where parent collection is revoked access
**Describe the bug**
When you create a collection ("Parent") in "Our analytics" and Revoke access, and then create a sub-collection inside of that ("Child") with Curate access, then it's not possible for the users to save anything new to the Child collection - but they can edit and view existing objects.

**To Reproduce**
1. Create a hierarchy of collections like this:
```
- Our analytics (Revoke)
- - Parent collection (Revoke)
- - - Child collection (Curate)
```
2. Login as user - viewing "Our analytics" will show "Child", but not "Parent" - as expected:
image
3. Trying to save (or move) a question, the "Child" collection is not an option in the collection selector of the modal:
image
4. But it's possible to use the search :mag: in the collection selector to find the hidden "Child" collection, which then allows you to save to the collection:
image

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.37.3

**Additional context**
Related to #11605 and perhaps #8198

### PR DESCRIPTION
**Pull request by cjwooo**
###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### CODE REVIEW

**Comment by alxnddr** [comment]
@cjwooo thanks for your contribution, looks great! CI is green https://github.com/metabase/metabase/pull/22663 I'm wondering if you can add `lodash` dependency (with types) to package json, so we can merge it. Or I can do it myself and merge the branch I created to run our CI

**Comment by paoliniluis** [comment]
Just tested the branch in metabase/metabase-dev:external_19581 but didn't work, the subcollections don't appear

**Comment by alxnddr** [comment]
@paoliniluis was the exact case you tried different from what is described in the issue? I'm asking because it did work for me locally and the Cypress spec passes

**Comment by paoliniluis** [comment]
@alxnddr just did the test again, I might have been some stranded caching, it works now

**Comment by alxnddr** [comment]
Merged as a part of https://github.com/metabase/metabase/pull/22663

**Pull request closed without merging**
