### PR TITLE
Fix unneeded query nesting when removing all expressions

### LINKED ISSUE #19745: Orphaned Notebook section settings can cause dashboard filters to be unavailable
**Describe the bug**
When removing a Custom Column after aggregation, then some settings (`fields`) are orphaned, which causes problems for connecting filters on dashboards.
I think this might just be a frontend bug, which doesn't do proper cleanup.

**Workaround** After removing the Custom Column, then re-select the grouping field, which will cleanup the orphaned settings.

**To Reproduce**
1. Custom question > Sample Dataset > Products
2. Summarize Count, Sum of Price, Sum of Rating - grouped by Category - add Custom Column `1 + 1`
image
3. Visualize, change to Table viz and in the Visualization Settings remove the column "Count"
image
4. Save question - do a browser refresh
5. Go to Notebook and remove the Custom Column. Save question.
6. Add to dashboard, add Time filter and try to connect to card - it will say `No valid fields` on the card.
image
7. Go back to the question's Notebook and re-select the grouped "Category", Visualize and save question. Now step 6 is possible.

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.41.6

**Additional context**
Very related to #19744

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/19745
Reproduces https://github.com/metabase/metabase/issues/19745

How to test:
- Follow the steps from the issue

When editing columns for a nested query we set the `fields` clause. When removing all other clauses on the top-level query, we currently don't do anything with the `fields` clause. This breaks `cleanNesting` functionality and makes the query to be always nested. This PR tries to solve it by dropping the `fields` clause on the top-level query when there are no other clauses.

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
I can still reproduce the problem on `3b7a442`, and it doesn't look like the test is following the exact steps in the issue.

**Comment by ranquild** [comment]
@flamber it should work now but I'm not 100% sure the fix won't cause any unwanted side-effects.

**Review by flamber — COMMENTED** [review]
Tested `346a544` - and I'm still able to reproduce the problem.

Let's have @nemanjaglumac create the reproduction, then it might be easier to try to fix the issue. Seems like step 3 is missing from the reproduction.

**Comment by ranquild** [comment]
@flamber I've recorded a video where I'm following the steps from the original issue exactly and it works as expected https://www.loom.com/share/bc5f97a543fb4f17a2dd4b5600d2522d. Please let me know if there is something else I should do.

@flamber @nemanjaglumac as for the step, it's a simplified version of the original repro steps to make the test run faster. It tests the root cause.

**Comment by ranquild** [comment]
@flamber I believe I finally got it. We do different things when:
- removing the last custom expression
- removing all custom expressions by removing the whole step

I've fixed both these cases and added a repro for each of them. I would appreciate it a lot if you take a look again (hopefully the last time now).

**Review by nemanjaglumac — APPROVED** [review]
Tested multiple times following the original repro steps and everything seems to be working.

Regarding the simplified test steps - I don't have enough context to understand why step 3. (removing "Count" from the table viz settings) was important for this but like I said, after multiple rounds of manual tests everything works.

One thing to note:
If you saved the question **prior to these changes**, it would still not be possible to connect the filter after the "upgrade", but I think it's understandable because the query was wrong when it was saved.

**Pull request merged**
