### PR TITLE
Generated style guide + snapshot tests [prototype]

### PR DESCRIPTION
**Pull request by tlrobinson**
A quick prototype of the ideas @attekei and @kdoh and I discussed for generating a component style guide and snapshot tests:

Here's the component style guide (it obviously needs a little design love):

screenshot 2017-04-11 15 06 05

Here's `Button.info.js`, the only thing needed to add a component to the style guide, and generate (3 in this case) snapshot tests:

```javascript
import React from "react";
import Button from "metabase/components/Button";

export const component = Button;

export const description = `
Metabase's main button component.
`;

export const examples = {
    "": <Button>Clickity click</Button>,
    "primary": <Button primary>Clickity click</Button>,
    "with an icon": <Button icon='star'>Clickity click</Button>
};
```

### CODE REVIEW

**Comment by kdoh** [comment]
YESSSS!! 👍

**Review by kdoh — APPROVED** [review]
This seems like a big win.

**Comment by tlrobinson** [comment]
@kdoh do we want to polish the ui or just merge it?

**Comment by kdoh** [comment]
I wouldn't block merging this on that. I think we can chip away at improvements as we go.

**Review by attekei — APPROVED** [review]
Looks good! Let's merge and see how this fits to our design/dev process and improve later based on our experiences.

**Pull request merged**
