### PR TITLE
Add new Accounts and Invoices tables to Sample database

### PR DESCRIPTION
**Pull request by ranquild**
Epic https://github.com/metabase/metabase/issues/24807
SQL https://gist.github.com/ranquild/4828bed6985da461db657a961c8e4e7f

The new tables are hidden by default for all users. I used the same SQL types for similar fields from the old sample db.

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
Can we please, please, please, super please NOT use the actual domains and use the reserved `.test` or `.example` domains instead?

https://www.thepicky.com/website/list-of-reserved-top-level-domains/

**Comment by dpsutton** [comment]
I'm not fully caught up here but looking over have the following thoughts:
- fighting over the name "sample dataset" sounds like a recipe for disaster. I'd just embrace that this is a different dataset. Even `sample2` or something similar
- Is this aimed primarily at serving as a new dataset for tests or for people to play with when first starting up a new instance?

**Comment by ranquild** [comment]
> Can we please, please, please, super please NOT use the actual domains and use the reserved `.test` or `.example` domains instead?
> 
> https://www.thepicky.com/website/list-of-reserved-top-level-domains/

Fixed

**Review by alxnddr — APPROVED** [review]
Works as described. I did not get what is the final decision on renaming but it can be tweaked later if needed

**Pull request merged**
