### PR TITLE
Add a reminder note to pick either backport or no-backport label

### PR DESCRIPTION
**Pull request by perivamsi**

### CODE REVIEW

**Comment by noahmoss** [comment]
Should there be some brief explanation of when you'd want to backport a PR, or a link to a doc that explains it? This might be confusing for external contributors who aren't aware of our workflow

**Comment by nemanjaglumac** [comment]
@noahmoss The CI doesn't run for external contributors anyway.

**Review by tsmacdonald — APPROVED** [review]
Works for me, though it's unfortunate we can't have separate templates for employees and third-party contributors

**Comment by npretto** [comment]
@nemanjaglumac but they would still see it and not understand it which is not super friendly
Not sure how many external PRs we have but the first would read is an important message that they don't have the full context of.

I usually delete all top part of the template with CLA warning out of habit anyway, so I'd probably not even read it, should we add it to the checklist at the bottom instead? Even if we don't add the label we'd get reminded by the failing label anyway

**Comment by tsmacdonald** [comment]
> I usually delete all top part of the template with CLA warning out of habit anyway, so I'd probably not even read it, should we add it to the checklist at the bottom instead? Even if we don't add the label we'd get reminded by the failing label anyway

I figure that anyone new to the company will probably read the PR template stuff the first time out of curiosity, and anyone already at the company just needs to get burned by not having a `no-backport` label once to remember to do it.

This PR isn't a perfect solution, but it feels like an improvement and the entire situation is pretty low-stakes.

**Pull request merged**
