### PR TITLE
Serdes for dashboardtab

### PR DESCRIPTION
**Pull request by qnkhuat**
Serdes for dashboard_tab which was added in https://github.com/metabase/metabase/pull/29802.

A dashboard can either have or do not have a tab. And a tab is just a container of cards so this is somewhat similar to DashboardCard in the way it's not explicitly exported but inlined within Dashboard.

This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30249)

### CODE REVIEW

**Review by bshepherdson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30249)* status: all files reviewed, 5 unresolved discussions (waiting on @john-metabase and @qnkhuat)

___
*[`enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj` line 651 at r2](https://reviewable.io/reviews/metabase/metabase/30249#-NU26c-40MBZXS4kCRPf:-NU26c-40MBZXS4kCRPg:b-issf5x) ([raw file](https://github.com/metabase/metabase/blob/22ac860d09a60b88cb39fb1faaa7ffa49c4c1b56/enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj#L651)):*
> ```Clojure
>             DashboardCard       _                          {:dashboard_id     dashboard-id
>                                                                              :card_id          card-id-1
>                                                                              :dashboard_tab_id tab-id-1}
> ```

nit: wonky indentation.



_Code quote:_
```Clojure
            DashboardCard       _                          {:dashboard_id     dashboard-id
                                                                             :card_id          card-id-1
                                                                             :dashboard_tab_id tab-id-1}
```
___
*[`src/metabase/models/dashboard.clj` line 476 at r2](https://reviewable.io/reviews/metabase/metabase/30249#-NU28YdBEPFzUMk5iw1-:-NU28YdBEPFzUMk5iw10:b-4b2q7s) ([raw file](https://github.com/metabase/metabase/blob/22ac860d09a60b88cb39fb1faaa7ffa49c4c1b56/src/metabase/models/dashboard.clj#L476)):*
> ```Clojure
>     (-> (serdes/extract-one-basics "Dashboard" dash)
>         (update :ordered_cards     #(mapv extract-dashcard %))
>         (update :ordered_tabs      #(mapv (fn [tab] (dissoc tab :id :dashboard_id :updated_at)) %))
> ```

Even though this inner logic is pretty trivial, can we extract it to an `export-dashtab` helper?
___
*[`src/metabase/models/dashboard.clj` line 498 at r2](https://reviewable.io/reviews/metabase/metabase/30249#-NU26kx4DIYf58aYWv84:-NU26kx4DIYf58aYWv85:bhzq18f) ([raw file](https://github.com/metabase/metabase/blob/22ac860d09a60b88cb39fb1faaa7ffa49c4c1b56/src/metabase/models/dashboard.clj#L498)):*
> ```Clojure
>                               [{:model "Dashboard"     :id (:entity_id dashboard)}
>                                (when (:dashboard_tab_id dashcard)
>                                  {:model "DashboardTab" :id (:entity_id dashcard)})
> ```

This is using the dashcard's ID for the middle segment, not the `DashboardTab`'s ID. That seems wrong to me, and doesn't match the path constructed in `dashtab-for`.
___
*[`src/metabase/models/dashboard.clj` line 507 at r2](https://reviewable.io/reviews/metabase/metabase/30249#-NU276J_5sRYzCUD_Mnr:-NU276J_5sRYzCUD_Mns:b-hdzd1j) ([raw file](https://github.com/metabase/metabase/blob/22ac860d09a60b88cb39fb1faaa7ffa49c4c1b56/src/metabase/models/dashboard.clj#L507)):*
> ```Clojure
>          :serdes/meta (remove nil?
>                               [{:model "Dashboard"    :id (:entity_id dashboard)}
>                                {:model "DashboardTab" :id (:entity_id tab)}])))
> ```

This could call `generate-path` but doesn't need to. `generate-path` only receives the entity (the tab) as input and would have to look up its parent dashboard to get its `entity_id`s as well.

Since in `load-one!` below we already have the parent dashboard handy, it's easier to generate the paths directly. `dashcard-for` does the same (even though `generate-path` is defined for `DashboardCard`; that might be dead code?)

Also: no need for `(remove nil? ...)` when there's no `when` conditional parts.



_Code quote:_
```Clojure
         ;; should this call to generate-path?
         :serdes/meta (remove nil?
                              [{:model "Dashboard"    :id (:entity_id dashboard)}
                               {:model "DashboardTab" :id (:entity_id tab)}])))
```
___
*[`src/metabase/models/dashboard_card.clj` line 360 at r2](https://reviewable.io/reviews/metabase/metabase/30249#-NU295K29D1FGs-byAnr:-NU295K39W_1UcUGCR8k:b-k1jjmp) ([raw file](https://github.com/metabase/metabase/blob/22ac860d09a60b88cb39fb1faaa7ffa49c4c1b56/src/metabase/models/dashboard_card.clj#L360)):*
> ```Clojure
> ;;; ----------------------------------------------- SERIALIZATION ----------------------------------------------------
> ;; DashboardCards are not serialized as their own, separate entities. They are inlined onto their parent Dashboards.
> ;; And if the parent dashboard has tabs, it'll be inlined inside DashboardTab.
> ```

From reading the code I can understand what this comment means, but it doesn't seem very clear at first.



_Suggestion:_
```Clojure
;; If the parent dashboard has tabs, the dashcards are inlined under each DashboardTab, which are inlined on the Dashboard.
```

**Comment by qnkhuat** [comment]
*[`src/metabase/models/dashboard.clj` line 476 at r2](https://reviewable.io/reviews/metabase/metabase/30249#-NU28YdBEPFzUMk5iw1-:-NU59NqpEkwMUk0tWggl:b-5bvh1i) ([raw file](https://github.com/metabase/metabase/blob/22ac860d09a60b88cb39fb1faaa7ffa49c4c1b56/src/metabase/models/dashboard.clj#L476)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Even though this inner logic is pretty trivial, can we extract it to an `export-dashtab` helper?
</blockquote></details>

updated in https://github.com/metabase/metabase/pull/30249/commits/7d6e1e777f615889b3e68b9c56b2592e3506fddc

**Comment by qnkhuat** [comment]
*[`src/metabase/models/dashboard.clj` line 498 at r2](https://reviewable.io/reviews/metabase/metabase/30249#-NU26kx4DIYf58aYWv84:-NU6gLy25Tekq7j-TOFk:blq21u6) ([raw file](https://github.com/metabase/metabase/blob/22ac860d09a60b88cb39fb1faaa7ffa49c4c1b56/src/metabase/models/dashboard.clj#L498)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

This is using the dashcard's ID for the middle segment, not the `DashboardTab`'s ID. That seems wrong to me, and doesn't match the path constructed in `dashtab-for`.
</blockquote></details>

my bad, fixed in https://github.com/metabase/metabase/pull/30249/commits/7d6e1e777f615889b3e68b9c56b2592e3506fddc

**Comment by qnkhuat** [comment]
*[`src/metabase/models/dashboard_card.clj` line 360 at r2](https://reviewable.io/reviews/metabase/metabase/30249#-NU295K29D1FGs-byAnr:-NU6gT2Y-CWFay3Yy-wI:b5315ke) ([raw file](https://github.com/metabase/metabase/blob/22ac860d09a60b88cb39fb1faaa7ffa49c4c1b56/src/metabase/models/dashboard_card.clj#L360)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

From reading the code I can understand what this comment means, but it doesn't seem very clear at first.
</blockquote></details>

https://github.com/metabase/metabase/pull/30249/commits/7d6e1e777f615889b3e68b9c56b2592e3506fddc

**Review by qnkhuat — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30249)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @bshepherdson and @john-metabase)

**Review by bshepherdson — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @john-metabase)

**Pull request merged**
