### PR TITLE
Limit channels.list to only a few channels

### PR DESCRIPTION
**Pull request by jrdalpra**
Just list the first 10 channels to avoid read_timeout errors while listing huge number of channels

###### Before submitting the PR, please make sure you do the following
- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.
### Tests
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by jrdalpra** [comment]
@camsaul 

This is a simple change to enable us to list channels when we have tons of channels available.

Somehow, it is failing on a frontend test, but I just changed a simple request parameter to list the slack channels.

Can you re-trigger the step?

Thanks.

**Comment by jrdalpra** [comment]
@tlrobinson @camsaul @agilliland @kdoh can you please look at this PR?
We want to start using the slack integration but the way we care listing channels is causing a timeout and prevent us to create the settings.
Thanks.

**Review by salsakran — CHANGES_REQUESTED** [review]
Hard 👎 on this PR. This prevents anyone from ever sending a pulse to any channel that is not in the first 10 returned. 

If we wish to make this process more scalable we should paginate the results. 

This will require 
- modifying the UI widget to scroll/paginate
- updating the frontend fetching to be page aware
- extending the api to return a specific page.

**Comment by kdoh** [comment]
I went ahead and opened #11735 to provide a place for more discussion on this and to track the problem specified here.

@jrdalpra if you want to take on work involved in the above items let me know and I'll reopen this and assign it to you, just don't want to leave this open and assume that those changes would be coming without your consent since it's a bit more involved than what you have here.

**Pull request closed without merging**
