### PR TITLE
Fix #11974 -- Respond with 200 code on public csv export

### LINKED ISSUE #11974: Status code to prevent G Sheet to load csv data
**Describe the bug**

If I am to include data into Google Sheets from metabase via the [card-export API](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apicardcard-idqueryexport-format) via the [IMPORTDATA](https://support.google.com/docs/answer/3093335) function, I get a `Could not fetch URL: ...` error. However, on my server I see the request and the expected 202 response.

It works fine on 0.34.1.

**Logs**

The proxy logs a 202 Accepted on the requested URL. I can not share the exact log, this it reveals a public URL.

**To Reproduce**
1. Go to any card.
2. Share it publicly.
3. Go to Google Sheets
4. Paste the `IMPORTDATA("YOUR_PUBLIC_CSV_URL")` into a cell.

**Expected behavior**

It should simply work, as described in #3772 

**Screenshots**

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "de",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1062-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6 (Ubuntu 11.6-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.2",
      "date": "2020-02-04",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**

 It isn't severe, but annoying for me. I am happy to help however I can.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by codingjoe**
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

Resolves #11974

### CODE REVIEW

**Review by salsakran — CHANGES_REQUESTED** [review]
This isn't mergeable as-is. 

We stream results and replying with a 200 touches on browser and load balancer behavior. @camsaul can give a deeper review.

We spent a _lot_ of time getting to our current setup to prevent memory consumption from going off the rails, and we're not going to arbitrary change the status codes for all of these end-points without a clear story around how it'll work with streaming.

**Comment by codingjoe** [comment]
@salsakran that is an interesting concern. I to make sure we can find a proper solution that does not introduce even more regression, I'd love if you could share a little more detail how those would be affected.

My current understanding is that we do respond with a 202-response on data export API that should respond with 200. After all,  they serve a RESTful receive GET-request and do include a full response body.  A 202-respons is expected for requests that trigger server internal process and do not require a response body. However, a body or header indicating the status should be provided.

I am currently not aware of any behavior variations of any browser in respect to 200 responses. Would you specify your concern here?

Regarding your load balancer concern, this seems to be something tied to a specific setup. Maybe you could tell me the name of the load balancer in question for me to conduct further research of possible problems.

A little side note:
This does not alter streaming responses. They still work as before. All that is altered is the response code. Furthermore, a 202-response-code is not related to streaming or non-streaming responses. If a response is streamed, or rather chunked, is indicated by the `Content-Encoding` header and the missing `Content-Length` header.
The intended purpose of 202-response-code is to provide feedback, whether a request is accepted for processing. E.g. a machine to machine  request to start a long-running ETL process. The 202 codes indicates successful authentication and that the request was not malformed (400-reponse), yet the process could still error during its execution. Preferably a `Location` header is provided as well to request further updates of the running process.
IMHO this is not the right response code for an export API unless it creates downloadable ZIP-files that are downloaded from another location.

**Comment by camsaul** [comment]
For CSV/XLSX/JSON export I think we should change it back to 200.

The only reason we do 202 for query responses in the first place is because we don’t know the actual status code of the response right away (because the query is still running) because the response is streamed. The 202 tells the frontend to look for a `_status` key (IIRC) in the API response with the actual status code. Since CSV/XLSX/JSON exports don't go to thru the frontend client (and there's no `_status` key anyway) there's no benefit to using 202

**Comment by robdaemon** [comment]
Rebased into #13500 - thank you for the contribution!!

**Pull request closed without merging**
