### PR TITLE
fix: pivot table disappear

### LINKED ISSUE #43129: Pivot table dissapears when going to the notebook editor and return to the viz
### Describe the bug

The FE will clean the rendering when going to the notebook editor and return to the viz

### To Reproduce

1) make a question like
image

2) use a pivot table to visualize it
3) then go to the notebook editor again
4) then click again on the same place to go back to the viz

the table is empty

### Expected behavior

It should show you the viz

### Logs

NA

### Information about your Metabase installation

```JSON
v50
brave
```

### Severity

P2

### Additional context

Peek 2024-05-24 13-13

### PR DESCRIPTION
**Pull request by elton-okawa**
Closes https://github.com/metabase/metabase/issues/43129

### Description

**Problem:**
`react-virtualized` [AutoSizer](https://github.com/bvaughn/react-virtualized/blob/e78651c3d844c6f639347d1fb796072783c175d2/source/AutoSizer/AutoSizer.js#L170) depends on `parentNode`'s size after mounted in order to calculate the correct `width` and `height` but [ExplicitSize](https://github.com/metabase/metabase/blob/bdf67dbe3f50af70e8aa64dd5b6bec4685dae573/frontend/src/metabase/components/ExplicitSize.tsx#L213) that wraps `DebouncedFrame` initially pass `null` and them real values. In the end when `AutoSizer` is mounted, its parent (DebouncedFrame) does not have a `height` set resulting in table rows being hidden in a tiny container.

I didn't investigate further why it works when you just arrived at the page because I have the following questions about `DebouncedFrame` and `ExplicitSize`

**Why DebouncedFrame and ExplicitSize?**
From the component comments:
> This component prevents children elements from being rerendered while it's being resized...

I understand the idea here, especially when using together with `ExplicitSize` that it modifies its state whenever you resize the browser window that results in re-render.

I didn't understand the reason why we need to keep track of the component size in a React state and not let the DOM do its job, because doing this, we end up triggering re-render every time the window is resized and also re-rendering the same component twice on mount (first render, set state with actual size, render again).

**Solution**
Remove `DebouncedFrame`
By removing it we also lose the greyed out table while resizing, maybe it's important to keep it 🤔 

I'm opening this a draft pull requests because I'd like to hear feedbacks about this approach.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Create a new question
2. Choose pivot table visualization
3. Open notebook
4. Go back to visualization

### Demo

https://www.loom.com/share/2ef979d755e744da826c25d12b36d992?sid=a91217bc-bf42-4ee1-a12d-c9993b6d0292

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
Hi @elton-okawa ,
Thank you for the contribution.

This problem doesn't exist on the `master` branch. It's currently affecting only the v50 release.
I'm adding the E2E reproduction for it that should confirm this.

Stay tuned.

**Comment by nemanjaglumac** [comment]
@elton-okawa it seems that the issue doesn't exist in the latest v0.50.10 anymore.
https://github.com/metabase/metabase/issues/39504#issuecomment-2209421588

**Comment by elton-okawa** [comment]
@nemanjaglumac Thanks for the response! It seems it's been fixed by other changes.
I'll close this PR for now, if possible we should also close the issue.

**Comment by nemanjaglumac** [comment]
> if possible we should also close the issue

We tend to never close an issue without adding a test for it first.
Once https://github.com/metabase/metabase/pull/45143 gets merged to `master` and then backported to the release branch, I'll close the issue.

**Pull request closed without merging**
