### PR TITLE
Remove chart rendering throttle with the app sidebar animation

### LINKED ISSUE #24291: UI performance regression between 42.4 and 43.4
**Describe the bug**
Some customers reported feeling 43 slower than 42 so I did a few tests and here's what I found:
1) 43.4 does not keep the spinners till the moment it renders the charts, it renders a white frame for a few ms and then it renders the chart. 42.4 kept the spinner till the moment before the rendering.
2) 43.4 renders one chart after another, while 42.4 did this faster (2 charts after another)
3) 42.4 rendered the first chart faster (around 1000ms after everything started, while 43.4 made it 1500ms after everything started)

Note: 44.0-RC1 is a little bit slower, but not much than 43.4

**Logs**
Unfortunately uploading Chromium profiling info is limited (cannot upload >25MB)

**To Reproduce**
1) New->question->Orders. Summarize: sum of total, average of quantity, sum of tax. Group by Product->vendor and Product->category. Save the question
2) Create a new dashboard
3) Add the newly created question 20 times to the dashboard
4) Profile it

**Expected behavior**
Keep Metabase smooth

**Screenshots**
One example, a frame with all charts with a white background since the spinner is not there but the chart has not yet rendered
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-OS 22.04
- Your databases: Postgres 14.3
- Metabase version: 42.4, 43.4, 44.0-RC1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.3

**Severity**
P2'ish

**Additional context**
Reported by 2 customers

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/24291

## Changes

It is controversial, but this PR reverts chart rendering throttle because it slowed down overall speed of rendering and customers want to have faster rendering. Unfortunately, rewriting of line/area/bar/combo charts to properly deal with performance issues is not a feasible task to do at the moment, that is why I simply revert the throttle.

In addition to that, I'm also removing the collections sidebar animation.
- it causes multiple rerenders of charts when resizing not instantly
- all other sidebars do not have any animation

## How to verify

- create and open a dashboard with multiple linea/area/bar/combo charts
- ensure it does not flash white cards between showing a loader and a chart

### CODE REVIEW

**Comment by alxnddr** [comment]
@mazameli @cdeweyx hey, what do you think about removing the sidebar animation? It affects the FE app performance and all other sidebars don't have any animation

**Review by ranquild — APPROVED** [review]
Works as described. Should we also remove dashcard resizing animation?

**Review by mazameli — APPROVED** [review]
The removal of the animation is a small bummer, but I'm cool with it in the name of performance.

**Comment by alxnddr** [comment]
> Works as described. Should we also remove dashcard resizing animation?

I removed the initial animation only because the subsequent resize animation feels nice

**Review by flamber — APPROVED** [review]
This looks good to me, but having difficulties understanding the consequences - simple little dashboard test

0.44.0

https://user-images.githubusercontent.com/1447303/184858129-5ea84aef-6490-4c1e-8463-e587cacba832.mp4

This PR commit `2251440`

https://user-images.githubusercontent.com/1447303/184858257-2a9af09b-da4b-4121-be59-07a305e47f72.mp4

**Pull request merged**
