### PR TITLE
Fix negative value on loading dashboard title

### LINKED ISSUE #33692: Negative number is shown in browser tab during loading cards
### Describe the bug

I can see negative numbers of completed requests during loading the dashboard cards

### To Reproduce

- Go to the dashboard, e.g. on stats open `/dashboard/1907-metabase-business`
- reload the page, check browser tab, notice `-11/15` loaded

https://www.loom.com/share/306315680105409ca6bc9abcc36b7b07

### Expected behavior

Number of cards in loading state should always >= 0

### Logs

_No response_

### Information about your Metabase installation

```JSON
Google chrome 116

metabase 0.47.1
7bacd2fa79dbe2c7635768ac5fddd24e4fe10c06
```

### Severity

P3

### Additional context

_No response_

### LINKED ISSUE #34767: Negative number of cards loaded in page title
I was clicking around Metabase today, not sure how I triggered it but the page title is "-9/11 loaded" which I'm reading as "negative nine out of 11 [cards] loaded"... seems like a bug...

image

### PR DESCRIPTION
**Pull request by ibedwi**
Closes https://github.com/metabase/metabase/issues/34767
Closes https://github.com/metabase/metabase/issues/33692

### Description

In the `updateLoadingTitle` action, the `loadingDashCards.loadingIds` initial size is greater than the `totalCards` size. Hence the calculation result is negative.

#### Root cause

In the `fetchCardData` action, `FETCH_CARD_DATA_PENDING` [dispatched](https://github.com/ibedwi/metabase/blob/b2fb7b356058c60ffcde03f9c424a6a6fd8ccf61/frontend/src/metabase/dashboard/actions/data-fetching.js#L268).  

```js
dispatch({
  type: FETCH_CARD_DATA_PENDING,
  payload: {
    dashcard_id: dashcard.id,
    card_id: card.id,
  },
});
```

In the `reducers`, the passed `dashcard_id` is added to the `loadingIds` regardless it's already there or not:

```
[FETCH_CARD_DATA_PENDING]: {
  next: (state, { payload: { dashcard_id } }) => {
    const loadingIds = state.loadingIds.concat(dashcard_id);
    return {
      ...state,
      loadingIds,
    };
  },
},
```

Therefore, the size of `loadingIds` might be doubled the size of the dashboard's cards.

#### How this fixed

In this PR, the `dashcard_id` would be added if the `loadingIds` array doesn't have it yet. 

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Go to the dashboard with cards
2. Reload the page, check the browser's tab and see the title "`.../... loaded`"

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

Sometimes, the title isn't updated. So to check this issue, I log the returned value of `updateLoadingTitle` action

#### Before

CleanShot 2023-11-11 at 20 38 03@2x

#### After
CleanShot 2023-11-11 at 20 34 20@2x

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

**Review by WiNloSt — APPROVED** [review]
Works great! Thank you for your contribution.

**Comment by WiNloSt** [comment]
@ranquild why shouldn't we backport this PR? It looks like a simple fix that could be easily backported.

**Comment by nemanjaglumac** [comment]
Hi @ibedwi ,
thank you so much for the contribution to Metabase! You've already received approvals and @WiNloSt ran CI from within the organization to make sure everything works. We can merge it immediately, but if you'd like to help us a tiny bit more - would you please rebase this PR on top of the latest master so that it includes b547eb7eb447c89cb357651d28db1b5b209f82e4?

We're preparing the CI environment for the external contributors, which means that we can most likely run the CI directly for your branch. Even if we figure out there are some things left to polish and the CI fails, don't worry - I'll merge this PR for you anyway.

If this is too much of a hassle, please do let me know and I'll merge it immediately.
Really appreciate what you've done so far.

**Comment by ibedwi** [comment]
> Hi @nemanjaglumac , yes I would love to help! Let me rebase this branch

@nemanjaglumac I've rebased this branch. I think https://github.com/metabase/metabase/pull/35643 is included now. Please let me know if I miss something. Thanks for your explanation and guidance!

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac I've rebased this branch. I think #35643 is included now. Please let me know if I miss something. Thanks for your explanation and guidance!

@ibedwi hm, something seems off. There are now 32 commits.

Can you please try the following.
1. Sync your fork with the Metabase repo using GitHub UI (if that's easier)
2. (then locally in your fork) `git checkout master` and `git pull`
3. `git checkout fix/negative-value-on-loading-dashboard-title`
4. `git rebase -i master` (then get rid of all commits that are not yours)
5. finally, `git push --force`

**Pull request merged**
