### PR TITLE
Language settings

### LINKED ISSUE #8384: Option to change language
With the new multilanguage version, the language is selected by metabase and not by the user. While this makes sense as a default option, I'd like to suggest to have the option for the user to change the language back to english.

The option to change the language might be there, but I have not found it.

In our case, we're based in Spain but inside the company we work in English as we have people from different nationalities. Right now, we're all seeing Metabase in Spanish.

My proposal is that the user can change on an individual basis his preferred language.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by kdoh**
Closes #8384

1. Adds instance language selection to the setup flow.
2. Adds the option for users to override the instance language with their own preference in the account settings.
3. Moves the instance language in the admin settings to `Localization` section (formerly Formatting) instead of `General`

### TODOs

- [x] FE stuff:
     - [x] available languages should come from backend
     - [x] update the setup flow to add step to pick default language
     - [x] add an option in the "My Account" page to change User language.
     - [x] Add UI for the "default language" Setting (this should be pretty easy)
     - [x] Use `site-locale` Setting and `User.locale` for rendering stuff

- [x] Backend stuff:
     - [x] Add a new "default language" Setting
          - [x] Setup API endpoint needs to set this value. Should validate it as well.
     - [x] Add a `language` column to User to record User's language Setting. Default = `NULL` which means use default language.
          - [x] Edit user API endpoint needs to be able to validate/set this value
     - [x] Need to rework how i18n works -- probably by removing the PuppetLabs i18n library entirely and using our new logic that relies on the "default language" Setting for `trs` and User `language` for `tru`
          - [x] Any log messages that happen *before* DB is initialized (i.e., before Settings are available) should probably just fall back to English

### CODE REVIEW

**Comment by mazameli** [comment]
@camsaul, I gave the branch a perusal. I'm sure you've got changes in flight for much or all of what I've found, but I figured I'd list what I'm seeing anyway just in case:

### Setup
* I had my browser's language set to Spanish, but the language for my new fresh instance was not initially set to Spanish.
* The list of languages should ideally display the language names in that language. (e.g. Español)
* Spanish was missing from the language list, as well as a bunch of other languages. (There should currently be 17 languages that are at 100% translated, if you include English.)
Screen Shot 2020-05-18 at 2 12 39 PM
* I tried setting my language to Persian and clicking Next, but nothing happened to the UI.
* The “1” step is listed twice:
Screen Shot 2020-05-18 at 2 14 02 PM

### Admin Panel
* The language I'd selected in the setup flow wasn't selected in the Admin Panel language setting.
* In the admin select, there are languages that shouldn’t be listed, because they’re below 100% translated: Ukranian, Norwegian Bokmal, Vietnamese.
* The language list in the admin doesn’t appear to be in any kind of discernible order. I'd expect alphabetical.
* As with the setup flow, ideally the language names should appear in that language in the dropdown.
* Changing the language in admin doesn’t appear to do anything, and the selection doesn’t persist if I navigate away from the page and back again.

### Personal account settings
* I can change my language in my account settings but it doesn’t do anything, and the selection gets cleared out after I click Update.

**Comment by camsaul** [comment]
@mazameli it's not finished yet

**Comment by camsaul** [comment]
Ok, this is all done now. The only weird thing is that you have to refresh the page for language changes to take effect. I added a note to this effect in the admin page but we should add it elsewhere as well? Or make significant changes to the way we do i18n so we can hotload different language bundles.

Also #12560 is annoying but I opened a separate bug

**Comment by mazameli** [comment]
@camsaul, as you mentioned the necessity of reloading is the main problem with the state of this PR. I'm pretty sure this isn't going to feel right until the language selection takes effect right away unfortunately.

### Setup
* I had my browser's language set to Persian, but the language for my new fresh instance was not initially set to Persian. The idea in the spec was to set the default language for new instances to the installer's browser language if possible.
* My language selection correctly persisted, but the language didn't change in the second step, which made me think the feature was broken. I can't hard refresh the page in the setup flow without losing my changes, and it feels bad that I'd need to do that.
* The list of languages should ideally display the language names in that language, like this:
image

* Even after finishing the setup and getting to the home page, my language selection still didn't seem to take effect. Hard refreshing did get it to work, but that doesn't feel ideal.

### Admin Panel
* I ran into an odd bug where selected some languages didn't work correctly, and would sometimes result in `en` being selected instead:

language-selection-bug

* As with the setup flow, ideally the language names should appear in that language in the dropdown.

### Personal account settings
* Changing my language didn't do anything even after saving and navigating away until I hard refreshed. I suspect users are going to think something's busted.
* I also ran into an error when trying to select Persian.

**Comment by camsaul** [comment]
@mazameli the issue with dropdowns displaying the code e.g. `en` instead of `English` is an FE regression in `master` that's not specific to language settings -- see #12560 which I opened to track this

I think we should definitely change the language stuff so it doesn't require a hard refresh. I want to go ahead and merge this PR now and do that as a follow-on PR. I made tons of unrelated improvements to backend test running in this PR and want to get it merged so I can use that stuff in other PRs.

**Comment by camsaul** [comment]
I'm going to go ahead and merge this now because I've implemented a ton of backend test improvements and do another follow-on PR with changes for updating language during setup

**Pull request merged**
