### PR TITLE
Unskip tests for 13642

### PR DESCRIPTION
**Pull request by camsaul**
Unskip tests for #13642 -- @sbelak mentioned this should be fixed now (fixed in #14014)

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
Which PR/commit fixed this? It's important to keep track of such relationships.
Ideally, we should always merge unskipped repro together with the fix.

**Comment by flamber** [comment]
I don't know how the tests are passing, but I can still reproduce on commit `73a260b`, though slightly different error:
```
Column "source.Products__CATEGORY" not found; SQL statement: -- Metabase:: userID: 2 queryType: MBQL queryHash: 00cc4ca78b223deae8ec307f20159c0b723630b6fb3dd6c2f43a520452d3b8ae SELECT "source"."ID" AS "ID", "source"."USER_ID" AS "USER_ID", "source"."PRODUCT_ID" AS "PRODUCT_ID", "source"."SUBTOTAL" AS "SUBTOTAL", "source"."TAX" AS "TAX", "source"."TOTAL" AS "TOTAL", "source"."DISCOUNT" AS "DISCOUNT", "source"."CREATED_AT" AS "CREATED_AT", "source"."QUANTITY" AS "QUANTITY", "Products"."ID" AS "Products__ID", "Products"."EAN" AS "Products__EAN", "Products"."TITLE" AS "Products__TITLE", "Products"."CATEGORY" AS "Products__CATEGORY", "Products"."VENDOR" AS "Products__VENDOR", "Products"."PRICE" AS "Products__PRICE", "Products"."RATING" AS "Products__RATING", "Products"."CREATED_AT" AS "Products__CREATED_AT" FROM (SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY" FROM "PUBLIC"."ORDERS" WHERE "PUBLIC"."ORDERS"."USER_ID" = 1) "source" LEFT JOIN (SELECT "PUBLIC"."PRODUCTS"."ID" AS "ID", "PUBLIC"."PRODUCTS"."EAN" AS "EAN", "PUBLIC"."PRODUCTS"."TITLE" AS "TITLE", "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", "PUBLIC"."PRODUCTS"."VENDOR" AS "VENDOR", "PUBLIC"."PRODUCTS"."PRICE" AS "PRICE", "PUBLIC"."PRODUCTS"."RATING" AS "RATING", "PUBLIC"."PRODUCTS"."CREATED_AT" AS "CREATED_AT" FROM "PUBLIC"."PRODUCTS" WHERE "PUBLIC"."PRODUCTS"."CATEGORY" = ?) "Products" ON "source"."PRODUCT_ID" = "Products"."ID" WHERE "source"."Products__CATEGORY" = ? LIMIT 2000 [42122-197]
```

**Comment by nemanjaglumac** [comment]
My local Cypress run is also failing:
image

**Comment by camsaul** [comment]
I didn't actually check that this test passed. I just noticed @sbelak mentioned that it was fixed in the comment https://github.com/metabase/metabase/issues/13642#issuecomment-773470788...

I guess tests might have passed initially on this PR because of the Cypress.io fiasco. I'll close the PR since it doesn't actually seem fixed

**Pull request closed without merging**
