### PR TITLE
Put images in loading/init screen

### PR DESCRIPTION
**Pull request by mazameli**
Partially addresses https://github.com/metabase/metabase/issues/4697

Decided to go with static images instead of GIFs (too twitchy to cycle through looping GIFs, and determined the static images we have are better at more immediately communicating the "wow" of the feature we're highlighting).

- [ ] Make things more fluid/responsive
- [x] Finalize the set of images
- [x] Encode the images inline in the HTML
- [x] Get the carousel working
- [X] ~How often should we cycle through these GIFs?~
- [X] ~Should the GIFs loop? They do currently.~
- [X] ~Should we serve them up randomly rather than sequentially?~
- [X] ~Need to clean up the actual GIFs and their sizing a tad.~

### CODE REVIEW

**Comment by mazameli** [comment]
@kdoh or @attekei, I could use your eyes on this if you have a second. I'm a little stuck on getting the JS for the carousel working exactly right.

The approach I'm using is to swap out the `background-image` for a div (since the images are encoded) by changing its class every 5 seconds using `setInterval()`. The problem I'm having is that I'm trying to do the fade effect by using a CSS opacity transition by adding a `transparent` class to the image and heading divs, waiting a fraction of a second with `setTimeout()` (so it won't loop) and then replacing the `transparent` class with `opaque`. It works fine the first time, but I think I'm missing something about the interplay between setInterval and setTimeout, because on subsequent iterations of the loop, the fade out isn't happening.

This also might be a bonkers stupid approach in the first place. 😆 I tried some copypasta of a pure JS fade in/out but it was weird and I couldn't get it to work right.

**Comment by attekei** [comment]
@mazameli Actually nothing wrong with setInterval and setTimeout there – the reason for fade out not happening is that you have both `opaque` and `transparent` in the class at the same time. For instance this (a little hacky) one-line change fixes the problem:
```
featureImage.className = featureImage.className.replace(" opaque", "") + " transparent";
```

I think that the current approach is fine. I might have tried a css-only approach (using CSS keyframes) but it doesn't make a big difference 🙂

**Comment by mazameli** [comment]
Ah whoops! Thanks Atte!

**Comment by mazameli** [comment]
Fixed the fading effect and added in the rest of the images if anyone wants to check this out. I think the layout could stand to be more fluid/responsive, but otherwise this is pretty close to what I was thinking.

**Comment by kdoh** [comment]
I'm not sure the transition is working as intended. It looks like it's happening too fast to where the actual transition effect is lost.

Once we get that figured out we should also use a custom timing function instead of `ease-in-out.`

**Pull request merged**
