### PR TITLE
Support query cancellation in new BigQuery driver

### LINKED ISSUE #7013: Cancel timed out queries to BigQuery
When querying BigQuery, if the query passes the timeout threshold, a timed out response is returned. Even though the query has timed out, it continues to run in the background. The results are then available later via a different endpoint.

We don't currently have any logic to follow up a timed out query with polling the other endpoint for the results. Since we're not interested in the results after a time out, we should cancel the query. The timed out query will include it's query id which is all we need to be able to cancel the query and stop waisting BigQuery cycles.

### PR DESCRIPTION
**Pull request by jeff303**
Remove now unused 60 second timeout

Remove a bunch of unneeded code (`with-finished-response`) from the legacy driver

Add support for canceling query, which stops pagination of results

Add test to confirm pagination stops upon cancellation

Add test to confirm that max rows enforcement via middleware prevents unnecessary pages from being fetched

### CODE REVIEW

**Comment by jeff303** [comment]
I investigated the possibility of being able to use the `BigQuery` client to cancel a job, when even the **first** page of results is taking a long time to come back.  But I don't think it's really feasible, unfortunately.

Fundamentally, for this approach to be feasible, we would need to get a reference to the generated job _before_ `.getQueryResults` is called on it.  The current `queryRpc` method [here](https://github.com/googleapis/java-bigquery/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java#L1274) does both of those at once.  We could reimplement this entire method, in order to capture the internal `jobId` before invoking `.getQueryResults`, but that involves too much reflection for comfort (many of those internal calls are to package private methods, which would get very ugly).

Given this reality, and the fact that the current BigQuery driver code also doesn't support in-flight cancellation, we could tackle this in the future.   If Google were to tackle googleapis/java-bigquery#1592 then it would be more feasible.

**Comment by flamber** [comment]
@jeff303 This seems to fix 7013 and partially fix 12003 - if I understand the code correctly. I haven't tested, since I'm not sure how

**Comment by jeff303** [comment]
> @jeff303 This seems to fix 7013 and partially fix 12003 - if I understand the code correctly. I haven't tested, since I'm not sure how

Yes, I will link to #7013.  And #12003 is fixed, at least w.r.t. BigQuery, with this change (perhaps we should move Druid out to its own issue to track that?)

**Review by camsaul — APPROVED** [review]
Cool. WFM 👍

**Pull request merged**
