### PR TITLE
fix click behavior on pin maps

### LINKED ISSUE #13597: "Click behavior" not working on pin maps
**Describe the bug**
"Click behavior" not working on pin maps. It does not send the column data.

**To Reproduce**
1. Custom question > Sample Dataset > People - limit 2
image
2. Change visualization to Map (pins), save question and add to dashboard
3. Add filter ID and connect to card
4. Hover dashboard card > click "Click behavior" > select "Update a dashboard filter" > select filter "ID" = column "ID" - save dashboard
image
5. Click any of the pins - no value is added to the dashboard filter, no errors in the browser console - but it seems like it's refreshing the map on click.

**Information about your Metabase Installation:**
Metabase 0.37.0.1

**Additional context**
https://discourse.metabase.com/t/try-out-the-new-0-37-release/12048/14?u=flamber

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/13597

LeafletMarkerPinMap visualization did not pass data about the row clicked. This PR fixes it. 
Please check the original issue for repro steps.

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
While it works for QB questions that returns a field with the type "Entity Key" (PK), it does not work otherwise - and does not work for SQL questions.

I'm not completely sure I understand the logic behind the pkIndex, but I'm guessing that the map requires some unique identifier and PK was used for that, but that seem fragile and something that will get us into more problems at some point.

And I guess all tests that looks at the URL would need an update, since we now include object name in the URL, which is likely the reason for it failing.

**Comment by alxnddr** [comment]
@flamber thanks for pointing it out! It seems like it looks for PK for the default clicking behavior like opening a card entity. However, when we manually specify click behavior even for questions without PK or SQL questions, it is better to be working, so I fixed it

**Review by flamber — APPROVED** [review]
Awesome! I cannot break it in any way, and while the code looks good, you probably want another eye on it.

**Review by daltojohnso — APPROVED** [review]
LGTM

**Pull request merged**
