### PR TITLE
Fix Radio component in Audit section with new syntax

### LINKED ISSUE #17102: Tabs in the Audit section look broken
Here's how they look when I spin up the EE locally:

image

Our Birdly Birdbase instance has the correct tabs still (ignore the color):

image

### PR DESCRIPTION
**Pull request by mazameli**
Fixes #17102 

**Before**

image

**After**

image

### CODE REVIEW

**Comment by mazameli** [comment]
No idea why that `be-tests-mariadb-latest-ee` test is failing. Tried to rerun it once, but will try again.

**Comment by nemanjaglumac** [comment]
> No idea why that `be-tests-mariadb-latest-ee` test is failing. Tried to rerun it once, but will try again.

It's something we tried to debug today. No luck yet. But no point in rerunning it, either. It fails on every single commit for everyone, starting with 3311b6211977b35e60802e615ece5767947fdc68.

**Review by kulyk — APPROVED** [review]
Thanks @mazameli

**Comment by mazameli** [comment]
@metabase/core-developers I can't merge this 'cause of the erroneous failing test, FYI.

**Comment by kulyk** [comment]
@mazameli the fix for maria DB is on master already. You can rebase your branch and the test should pass

**Pull request merged**
