### PR TITLE
fix percent change e2e flakes and failures

### PR DESCRIPTION
**Pull request by EmmadUsmani**
### Description

Two types of tests were flaking in this file for different reasons, possibly due to differences in behavior post-React 18 upgrade. Note that I'm backporting this PR to the 50 release branch because I have another backport that is blocked by these flaky tests.

1. Bar series

Unlike line series, we need to pass the `index = 1` parameter when calling `showTooltipForBarInSeries` to hover the datum and show its tooltip. 

The underlying selectors are different, `path[d="${CIRCLE_PATH}"][stroke="${color}"]` for line series, and `path[fill="${color}"]` for bars, so maybe that's the root cause of the difference, but for now manually providing the index of 1 instead of 0 for bars suffices to fix the flakes.

2. Daylight savings related tests

Some of these would hover over 4 datum in a series, and for some reason the tooltip selector method would flake frequently when trying to select the fourth. I've fixed the flakiness by modifying the questions and selecting only 3 datum instead. This works consistently locally, and hopefully in CI as well.

Additionally, to help reduce flakiness we now hover the settings menu after each datum. For some reason hovering multiple datums consecutively causes the tooltips to flake.

### How to verify

Run tests locally and in CI multiple times

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by EmmadUsmani** [comment]
* **#43621** <a href="https://app.graphite.dev/github/pr/metabase/metabase/43621?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @EmmadUsmani and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by iethree — DISMISSED** [review]
LGTM, can you run a stress test before merging?

**Comment by iethree** [comment]
looks like theres till some flakes on `should show percent change in tooltip for timeseries axis`


https://github.com/metabase/metabase/actions/runs/9374658490/job/25811192141

**Comment by EmmadUsmani** [comment]
Closing in favor of https://github.com/metabase/metabase/pull/43761, which will add these tests to the flaky job instead

**Pull request closed without merging**
