### PR TITLE
Fix areas render under bars in combo charts

### LINKED ISSUE #40209: [dc.js migration] areas render under bars in combo charts
Screenshot 2024-03-15 at 4 38 02 PM

http://localhost:3000/question/281-combo-40209-areas-render-under-bars-in-combo-charts

The fix is to set the `z` property of the line/area series to always be greater than the `z` of the bar series.

### PR DESCRIPTION
**Pull request by kulyk**
Closes #40209

### Before

before

### After

after

### CODE REVIEW

**Comment by EmmadUsmani** [comment]
@kulyk Looks good! Can you add a visual test snapshot before merging? You can see examples in `frontend/src/metabase/static-viz/components/ComboChart/stories-data`, and here's a small PR of mine that adds one: https://github.com/metabase/metabase/pull/40264. To get the `rawSeries` object that we put in the json file, just open your browser console when you open the question in the QB view, it should be logged there. Then once you update the PR add the `loki update` label and it will automatically update snapshots.

**Review by JesseSDevaney — COMMENTED** [review]
LGTM! Just check out Emmad's comment above about adding a visual test snapshot before merging :arrow_up:

**Comment by alxnddr** [comment]
In addition to what Emmad mentioned, I found it convenient to update snapshots locally using `yarn test-visual:loki-update` when I want to check whether my changes broke anything or not. If the diff is valid, you can push all the updated screenshots and you won't need to use `loki update`. To update snapshots locally you also need to run Docker daemon since we use dockerized chromium for avoiding flakes on different platforms.

The fix looks good!

**Comment by kulyk** [comment]
Thanks for your advice @EmmadUsmani @alxnddr 🙏 
I've added a new JSON with raw series in [this commit](https://github.com/metabase/metabase/pull/40314/commits/3cd9ab8a57f9d6ebba0b6cef8768182dde197df9), and [here](https://github.com/metabase/metabase/blob/40209-fix-combo-chart-z-indexes/.loki/reference/chrome_laptop_static_viz_ComboChart_Combo_Histogram.png) is the new screenshot

**Comment by EmmadUsmani** [comment]
@kulyk Thanks! I'll approve for now but before merging there's just one more thing to add. In `ComboChart.stories.tsx` you should import the json object for the story and render a story component for it. You should just be able to copy any of the other stories and just change the `rawSeries` arg to `data.areaOverBar` as well as the component name of course.

**Review by EmmadUsmani — APPROVED** [review]

**Review by alxnddr — APPROVED** [review]

**Pull request merged**
