### PR TITLE
Chart Improvements 2

### LINKED ISSUE #645: scatter plot chart option

### LINKED ISSUE #646: bubble chart option

### LINKED ISSUE #745: New visualization type: Progress Bar
Basically a replacement for simple "scalar" display, where the user can set a maximum number, and the scalar value is displayed as a progress bar towards that max.

Could be great for live dashboards, especially quotas).

### LINKED ISSUE #896: Ensure that time series breakouts have continuous grouping values
*User Story*: as a user performing queries that are grouped by a time granularity/extract (day, month, day-of-week, etc) I want to ensure that all possible groupings are reflected in my query result so that I don't misinterpret the data or chart the wrong trend.

This applies specifically to time based groupings, either by time granularity (hour, day, week, month) or by time extract (day-of-week, hour-of-day).  In all of these groupings there is an expectation that the result of the query will include a value for each of the continuous grouping values.

For example, if grouping by day for the last 30 days it would be expected that the query would result in 30 rows of data, one for each of the days.  If it turns out that the underlying data does not have values for a given grouping we should correct for that and supply an empty value.  The same is true for time extract groupings such as day-of-week where it would be strange to run a query grouped by day-of-week and only get back 4 rows of data for (Tuesday, Wednesday, Friday, Sunday).

### LINKED ISSUE #1918: Line/Bar/Area charts should support linear X axis scale
We support time and ordinal scales on the X axis, but not linear. Showing an ordinal scale for a numeric dimension can be misleading.

The simplest logic would be to use a linear scale if the dimension is numeric. However, if the results are sparse enough it may be better to use an ordinal scale.

### LINKED ISSUE #1920: Offer "exotic" chart axis scaling options like logarithmic
Presumably as visualization options. We might also consider doing quadratic, exponential, major, minor, pentatonic, and other exotic scales. 

As discussed in #1918

### LINKED ISSUE #2771: stacked area charts plots 0 for missing values
This is not an error per say, but more an formatting question/discussion

lets assume I have chart (sample below) and one of the categories is missing, then suddenly shows up (see green), it shows zero value for the whole history, I would assume this category would be missing and would show from the time it actually exists.

image

### LINKED ISSUE #2861: Pie Graph Visual enhancements/improvements
Hi Metabase Team,

Although it's easy to create charts and pull data from databases and play with data but we have no options when it comes to chart options like colors, labels etc.

I have some recommendations from Pie charts:

Please take a look at the Pie chart below. There are two Percentage fields, one create from my Query and one created automatically from Metabase. Although I can see that it's handful to have it being created automatically sometimes it's not so convenient and I will explain my self.

So let's say I have 8 fields on a table and I want to report only on the top 3 and return the relevant percentage of them from the table and not from the Pie chart it self. So lets say I have the following:

AAA - 25%
BBB - 20%
CCC - 15%
DDD - 10%
EEE - 10%
FFF - 10%
GGG - 5%
HHH - 5%

If I report on the top 3 the automatically created percentage will show something less than the real percentages but I want to return the real percentage which is 25% , 20% and 15%.

pie_issue

The second one is on the hover if the returned text is lengthy it will be overlapped by the pie chart itself. Maybe you should bring the label in front?

pie_issue_2

### PR DESCRIPTION
**Pull request by tlrobinson**
- [x] ~~Gauge #2989 and~~ Progress #745 charts
  - [x] fix: when a progress bar card is on a dashboard, clicking on it goes to the scalar visualization for the question instead of the progress bar.
  - [x] fix: when resizing the browser window and redrawing the chart, the label for the current value lags behind awkwardly
  - [x] rules for scaling down
  - ~~more scaling tweaks (@kdoh)~~
- [x] Scatter #645 and Bubble #646 charts
- Pie Chart enhancements
  - [x] "other" threshold setting
  - [x] hide "perecent" in tooltip (sometimes) #2861
  - [ ] better formatting of long labels inside the donut
- [x] Log/Power X and Y axis scales: #1920
- [x] Linear X axis scales: #1918
- [x] Timeseries continuous grouping values: #896 
- [x] Control over missing values #2771
- [x] Line/Area/Bar goals
  - [x] Label
- [x] In settings modal, dropdowns with no valid selections should be disabled and have placeholder text, e.g. "No valid fields" (added by Maz)
- [x] In settings modal, dropdowns with only one valid possible selection should have that option selected, and the dropdown should be disabled (added by Maz)
- [x] scatter/bubble tooltips
- [x] scatter/bubble hover effects (both for single and multi-series)
- ~~clicking on a specific bubble/dot should bring it to the top of the stack~~
- [x] Dial in how we're determining relative bubble sizes

Resolves #2771
Resolves #745
Resolves #646
Resolves #645 
Resolves #2861
Resolves #1920
Resolves #1918
Resolves #896
Resolves #2771

To be implemented in separate PRs:
- [ ] Leaflet Pinmaps #2737 and #3133
- [ ] Leaflet Choropleths + GeoJSON uploads: #2740
- [ ] Funnel chart #3144 + #2926

### CODE REVIEW

**Comment by mazameli** [comment]
I did some treatments for a simple gauge and then one that has optional good/okay/bad ranges (which would be a stretch or future enhancement). I think we can just use this and not introduce a thermometer. @kdoh (or anyone else), let me know if you have visual design feedback.

Large version:
simple gauge large

Small dashcard version:
simple gauge on dashboard

Large fancy version:
good okay bad gauge large

Dashcard version:
good okay bad gauge

**Comment by mazameli** [comment]
Realizing the fancy version should have tick marks at the color transitions probably.

**Comment by salsakran** [comment]
hmm.... that feels very ... bottom heavy. Not sure how it would look in a dashboard.

**Comment by mazameli** [comment]
I think I know what you mean — that the text is low down — but that's mostly to make sure there's room horizontally for longer numbers. Maybe I could trim down the thickness of the gauge? In a dashboard, it could look like this:

gauge in dashboard

**Comment by kdoh** [comment]
A couple thoughts:

- I think the curve of the "gauge" itself and the size of the scalar info are making it feel a bit claustrophobic, especially in the dash card variant. More space between them might help.
- In the version with ranges (which is a rad feature) the indicator gets pretty lost.
- I think in both cases the fact that it's almost a traditional car dashboard like gauge but isn't quite makes them feel a little awkward. The non range default visualization is also kinda walking the uncanny valley between thermometer, progress bar, and gauge as well.
-  I think in both variants I don't get an immediate read on the top and bottom ends of the range.
- Something about the overall shape of the gauge itself doesn't feel quite right.

I think it'd be worth exploring a few more variants.

**Comment by salsakran** [comment]
And fwiw, I wayyyy prefer a progress bar for this sort of visualization.

**Comment by rNianios** [comment]
Any change to add Issue [2969](https://github.com/metabase/metabase/issues/2696) as well on the improvements?

**Comment by mariosergioti** [comment]
+1 vote for a gauge or progress bar chart!

**Comment by esuus** [comment]
Rrreally looking forward to scatter plots. Would you, beyond the visual representation, also show values on correlation (Pearson correlation coefficient) and statistical significance on/next to the scatterplot?

**Comment by salsakran** [comment]
Looks pretty good overall.

I have a couple details:
1. The bare input for goals feels weird. I think the pattern we have for auto-axis should be used here. A toggle for whether the user wants to add a goal, and if so, an input for the goal itself.
2. With the addition of all the various options in the line chart `display` tab, it's no longer obvious that the color select is a color select. We should add a label, such as "Line Colors" above it
3. The X + Y axis labels behave strangely. The input label is `Y-axis label` but it's empty. After playing with it, it's obviously an input for an override of the default label but that's not obvious. I think we should add a `default` value to the input form field. 

With these points taken care of I'm a 👍 

Didn't look at the code too closely, @kdoh any comments on this PR?

**Comment by kdoh** [comment]
Agree with all the UX points above.

I took a look at the code and nothing stood out to me as wonky. @tlrobinson Is there anything in particular you'd like reviewed?

**Comment by tlrobinson** [comment]
1 and 2 are now fixed. 3 will be easier to do as part of #3361.

**Comment by salsakran** [comment]
awesome. merge away.

**Comment by coussej** [comment]
Hi @tlrobinson , @mazameli : 

I know this is an older PR, but I was looking for a gauge chart option for metabase, which brought me here. I see some considerable work has already been done for the gauge chart, but I see it has not made it's way to the product yet. Can I conclude that the option for such a chart has been discarded? That would be a shame, as in my work experience a gauge option like the one below is one of the most requested visualisation types! 

Thanks in advance for you answer!

image

**Comment by mnlbox** [comment]
@tlrobinson Are you any plan to add gauge chart?

**Pull request merged**
