### PR TITLE
Fix include today not working for past/next date filters on SQL queries

### PR DESCRIPTION
**Pull request by MarkRx**
Two fixes (#7339):

- Fix next not supporting "include-today" for SQL queries
- Fix past/next not actually including today for SQL queries

###### Before submitting the PR, please make sure you do the following 
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [x] Run the frontend and integration tests with  `yarn && yarn run prettier && yarn run lint && yarn run flow && ./bin/build version uberjar && yarn run test`)
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) - Signed by company. Let us know if we need one per user/github account.

@cgopalan

### CODE REVIEW

**Comment by cgopalan** [comment]
@salsakran do you need anything else for this to be reviewed and merged?

**Comment by cgopalan** [comment]
@camsaul do you need anything else for this to be reviewed and merged?

**Review by salsakran — APPROVED** [review]
verified that it fixes the reported issue. @camsaul mind looking over the code?

**Review by camsaul — APPROVED** [review]
~This works for me if you remove the unnecessary `(boolean)` calls~

EDIT: meant to mark this as Changed Requested

**Review by camsaul — CHANGES_REQUESTED** [review]
This works for me once you remove the unnecessary `(boolean)` calls

**Comment by cgopalan** [comment]
@camsaul Removed the unnecessary boolean cast. Please review.

**Review by camsaul — APPROVED** [review]

**Comment by gunjansriv86** [comment]
Is this fixed? I got this issue while deploying a report 

Today is 2nd of November and i am working in IST timezone.

I found above issue to be in Native query questions. Following is what i have faced while deploying a client's report

1.  **Custom query Builder**. - when we do a filter on date field here  and select day as "Today", it perfectly displays all transactions of 2nd November
custom query-date filter is correct

2. **Native query builder** - I wrote an SQL and applied dynamic filters on date. when i select day as "Today", it displays all transactions of 1st November.

native query question-date filter off 1 day


Not sure what is causing this issue? If timezone was the issue, shouldn't it have occured in both the approach

Any suggestions to fix this issue?

Thanks
Gunjan

**Comment by MarkRx** [comment]
It was partially fixed. There is another PR to fix the rest of it here: #8274. It's been sitting there for months though.

**Pull request merged**
