### PR TITLE
Fix Data Model page blank if database doesn't exist

### LINKED ISSUE #14652: Data Model page busted if you visit a database that doesn't exist
Probably an edge case, but we should make sure pages don't look insane if there isn't anything to display. It seems like it's not handling 404 (or other error) responses from the backend correctly. 

image

Steps to repro 

1. Visit data model page in admin panel
2. Delete the database from the REPL or another tab
3. Hit refresh on data model page
4. B R O K E N

### PR DESCRIPTION
**Pull request by kulyk**
When you try to open a database that doesn't exist on the Data Model page, it crashes and just shows a blank screen.

Reproduces #14652, fixes #14652

### To Verify

1. Sign in as admin
2. Go to `/admin/datamodel/database/:db-id-that-does-not-exist`
3. You should see a page saying "The page you asked for couldn't be found." and a database selector in the top left

### Screenshot

Screenshot 2021-06-21 at 17 26 38

### CODE REVIEW

**Review by gusaiani — COMMENTED** [review]
@kulyk, I don't quite see the expected message at the center of the page.

Here's what I currently see when going to http://localhost:3000/admin/datamodel/database/db-id-that-does-not-exist

image

**Comment by gusaiani** [comment]
Also for http://localhost:3000/admin/datamodel/database/db-id-that-does-not-exist,
important to note that the backend log shows an infinite loop,

**Comment by kulyk** [comment]
> @kulyk, I don't quite see the expected message at the center of the page.
> 
> 
> 
> Here's what I currently see when going to http://localhost:3000/admin/datamodel/database/db-id-that-does-not-exist
> 
> 
> 
> image
> 
> 

Sorry, I didn't make the repron steps clear enough.`/:db-id-that-does-not-exist` is a named parameter, it should be an integer like in the "after" state screenshot

Still it's a good catch and probably worth a fix

**Review by gusaiani — APPROVED** [review]
👍

Might be nice to consider non-integers being passed as url params in this very PR, but up to you.

**Pull request merged**
