### PR TITLE
fix lint errors due to duplicate c-3po imports

### PR DESCRIPTION
**Pull request by salsakran**
These got introduced when resolving merge conflicts in the i18n PRs.

### CODE REVIEW

**Comment by salsakran** [comment]
Ok, I'm a bit confused.

@kdoh + @tlrobinson -- how does the `jt` tag work here? It seems weird that the `Link` component is inside a translate string. Am I correct in assuming that the lint error being thrown is indicative of a mistake?

**Comment by kdoh** [comment]
@salsakran Yeah basically there were a couple spots where `jt` was used but it was used improperly so the inline link was just being treated as text, so the Link was never used, therefore the `no-unused-vars` lint rule was getting hit.

**Comment by tlrobinson** [comment]
As I understand it, `jt` should be used when the format string might includeReact elements. It returns an array rather than string concatenation. e.x.

```
const foo = <em>foo</em>
return <div>{jt`hello ${foo}`}</div>
```

...does `[“hello “, <em>foo</em>]` which works in React, rather than `“hello “ + <em>foo</em>` which is nonsensical.

**Comment by tlrobinson** [comment]
@salsakran did you mean to include `resources/dev-log4j.properties` in this PR?

**Comment by tlrobinson** [comment]
It looks like people have been internationalizing JSX incorrectly.

Here's one example I've fixed: https://github.com/metabase/metabase/pull/6665/files

Here's an example from this PR: 

screenshot 2018-01-10 14 29 28

`jt` does *not* parse strings into JSX, it just interpolates into an array rather than a string, which preserves the React elements rather than casting to a useless `[Object object]` string.

Here's a little demo: https://jsfiddle.net/tlrobinson/r4sond89/1/

**Comment by tlrobinson** [comment]
Oh, it looks like that's the same issue @kdoh was referring to. I've fixed a couple more instances.

**Comment by bpinaya** [comment]
Hi there, I've just pulled from the master branch to get the text features but it seems that the build is broken, this is my error log after running `yarn run build-hot`:
```
WARNING in ./frontend/src/metabase/admin/people/containers/PeopleListingApp.jsx             
                                                                                            
/home/bpinaya/Documents/metabase/frontend/src/metabase/admin/people/containers/PeopleListingApp.jsx                                                                                
  4:10  warning  'Link' is defined but never used  no-unused-vars                           
                                                                                            
✖ 1 problem (0 errors, 1 warning)                                                           
                                                                                            
 @ ./frontend/src/metabase/routes.jsx 301:24-88                                             
 @ ./frontend/src/metabase/app-main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js

ERROR in ./frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx

/home/bpinaya/Documents/metabase/frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx
  3:19  warning  '/home/bpinaya/Documents/metabase/node_modules/c-3po/dist/index.js' imported multiple times  import/no-duplicates
  6:10  error    't' is already defined                                                                             no-redeclare
  6:23  warning  '/home/bpinaya/Documents/metabase/node_modules/c-3po/dist/index.js' imported multiple times  import/no-duplicates

✖ 3 problems (1 error, 2 warnings)

 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 89:32-85
 @ ./frontend/src/metabase/routes.jsx
 @ ./frontend/src/metabase/app-main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js

ERROR in ./frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx

/home/bpinaya/Documents/metabase/frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx
   3:19  warning  '/home/bpinaya/Documents/metabase/node_modules/c-3po/dist/index.js' imported multiple times  import/no-duplicates
  14:10  error    't' is already defined                                                                             no-redeclare
  14:23  warning  '/home/bpinaya/Documents/metabase/node_modules/c-3po/dist/index.js' imported multiple times  import/no-duplicates

✖ 3 problems (1 error, 2 warnings)

 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 111:17-40                                                                                                     
 @ ./frontend/src/metabase/routes.jsx                                                                                                                                                    
 @ ./frontend/src/metabase/app-main.js                                                                                                                                                   
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js                                                                                          
                                                                                                                                                                                         
ERROR in ./frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx                                                                                                         
Module build failed: Duplicate declaration "t"                                                                                                                                           
                                                                                                                                                                                         
  12 | import cx from "classnames";                                                                                                                                                      
  13 | import _ from "underscore";                                                                                                                                                       
> 14 | import { t, jt } from "c-3po";                                                                                                                                                    
     |          ^                                                                                                                                                                        
  15 |                                                                                                                                                                                   
  16 | export default class SettingsSlackForm extends Component {                                                                                                                        
  17 |                                                                                                                                                                                   
                                                                                                                                                                                         
 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 73:25-71                                                                                                      
 @ ./frontend/src/metabase/routes.jsx                                                                                                                                                    
 @ ./frontend/src/metabase/app-main.js                                                                                                                                                   
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js                                                                                          
                                                                                                                                                                                         
ERROR in ./frontend/src/metabase/admin/settings/selectors.js                                                                                                                             
Module build failed: Duplicate declaration "t"                                                                                                                                           
                                                                                                                                                                                         
  17 |                                                                                                                                                                                   
  18 | import { UtilApi } from "metabase/services";                                         
> 19 | import { t } from "c-3po";             
     |          ^                             
  20 |                                        
  21 | const SECTIONS = [                     
  22 |     {

 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 111:17-40
 @ ./frontend/src/metabase/routes.jsx
 @ ./frontend/src/metabase/app-main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js

ERROR in ./frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx     
Module build failed: Duplicate declaration "t"                                              

  4 | import cx from "classnames";            
  5 | import _ from "underscore";             
> 6 | import { t, jt } from "c-3po";          
    |          ^       
  7 |                  
  8 | import Breadcrumbs from "metabase/components/Breadcrumbs.jsx";                        
  9 | import Input from "metabase/components/Input.jsx";                                    

 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 89:32-85         
 @ ./frontend/src/metabase/routes.jsx         
 @ ./frontend/src/metabase/app-main.js        
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js
Child html-webpack-plugin for "../../index.html":                                           
     1 asset           
    [../../../node_modules/html-webpack-plugin/lib/loader.js!../../../resources/frontend_client/index_template.html] ./node_modules/html-webpack-plugin/lib/loader.js!./resources/frontend_client/index_template.html 4.39 kB {0} [built]
    [../../../node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [../../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
    [../../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
Child html-webpack-plugin for "../../public.html":                                          
     1 asset           
    [../../../node_modules/html-webpack-plugin/lib/loader.js!../../../resources/frontend_client/index_template.html] ./node_modules/html-webpack-plugin/lib/loader.js!./resources/frontend_client/index_template.html 4.39 kB {0} [built]
    [../../../node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [../../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
    [../../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
Child html-webpack-plugin for "../../embed.html":                                           
     1 asset           
    [../../../node_modules/html-webpack-plugin/lib/loader.js!../../../resources/frontend_client/index_template.html] ./node_modules/html-webpack-plugin/lib/loader.js!./resources/frontend_client/index_template.html 4.39 kB {0} [built]
    [../../../node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [../../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
    [../../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
webpack: Failed to compile.
```

**Pull request merged**
