### PR TITLE
fix #3105 #3106 #3107: doc fixes

### LINKED ISSUE #3105: #User Guide in start page in dox
think we're missing a space.

screen shot 2016-08-02 at 11 35 11 am
oc

### PR DESCRIPTION
**Pull request by mavimo**
fix #3105 #3106 #3107

See:
- https://github.com/metabase/metabase/pull/3121
- https://github.com/metabase/metabase/pull/3122
- https://github.com/metabase/metabase/pull/3123
-  [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
  (unless it's a tiny documentation change).

cc/ @camsaul

### CODE REVIEW

**Comment by camsaul** [comment]
@mavimo This LGTM. Thanks for your contribution.

**Comment by camsaul** [comment]
Just so no one gets mixed up here this fixed #3105, #3106, and #3107, I think the numbers got jumbled in the title

**Comment by mavimo** [comment]
@camsaul my fault, fixed.

**Comment by camsaul** [comment]
No worries @mavimo. Thanks again for your contributions 👍

**Pull request merged**
