### PR TITLE
Bigquery numeric support

### PR DESCRIPTION
**Pull request by lmatsuura**
Implements https://github.com/metabase/metabase/issues/8855

### CODE REVIEW

**Comment by camsaul** [comment]
works for me but we'll need to pull this into another PR and run the tests for it

**Comment by leonardomatsuura** [comment]
Can you point me into the right direction? Is this something that i should do on my end?

**Comment by camsaul** [comment]
Hey @leonardomatsuura, you can run tests locally like this:

```bash
MB_BIGQUERY_TEST_ACCESS_TOKEN=<token> \
MB_BIGQUERY_TEST_CLIENT_ID=<token> \
MB_BIGQUERY_TEST_CLIENT_SECRET=<secret> \
MB_BIGQUERY_TEST_PROJECT_ID=<project-id> \
MB_BIGQUERY_TEST_REFRESH_TOKEN=<refresh-token> \
DRIVERS=h2,bigquery lein test
```

The easiest way to get the values for these is to connect Metabase to your BigQuery project and then look at the values it stores for these in the application database (in the `metabase_database.details` field)

It would definitely save us a lot of time if you can check and make sure tests are still passing after the changes -- I have a feeling a few things will need to be updated. Let me know when you get tests passing locally.

One last thing. Could you rebase this on `master`? It shouldn't be too difficult -- BigQuery and other drivers were moved into new directories, and several of the functions were renamed as part of my [modular drivers project](https://github.com/metabase/metabase/pull/9087) -- but the underlying logic powering the drivers is still the same. Im' really sorry to have pulled the rug out from under this PR; I try to change the driver interface as little as possible, but this big refactor was long a time in the making and will really help make Metabase more extensible by third parties. I don't expect things to move around too much more in the future, so you shouldn't have to do it again after that!

**Comment by camsaul** [comment]
Works for me

**Pull request merged**
