### PR TITLE
use email input type to validate email

### LINKED ISSUE #6717: Login should provide feedback if email address is invalid
When using native authentication without LDAP configured if you attempt to login with an invalid email address (such as simply using a username) the UI fails to give any sort of feedback that there is an issue.

### Steps
Attempt to sign in as foo with an invalid password. Hit sign-in. Nothing happens. Contrast this with the case below:

Attempt to sign in with foo@foo.com with an invalid password. Hit sign-in. The UI says: "Password: did not match stored password"

### Expected Behaviour
The UI should provide some sort of feedback that the login was invalid if an email address is not entered properly

### Actual Behaviour
The UI provides no user feedback if an email address is not entered properly

Browser: Chrome 62.0.3202.94
OS: Windows 7
Databases: Oracle 11g
Version: You're on version v0.27.2
Host Env: Windows 7
Internal Database: H2

### PR DESCRIPTION
**Pull request by kdoh**
Fixes #6717 

Doing a simple version of email validation here by changing the input email type from "text" to "email" so we get email validation in modern browsers for free.

Only thing I'm slightly unsure of here is whether it's possible for the username value to be a string other than an email? If so then this approach wouldn't work. I'm 95% sure that's not possible after taking a quick look at `models/user.clj`, but @camsaul can I get a gut check on that from you?

### CODE REVIEW

**Comment by camsaul** [comment]
Yeah `user.email` has to be a valid email address, we validate that on the backend.

**Review by mazameli — COMMENTED** [review]
This is an overall improvement, though there are still some edge cases where we don't provide any feedback:

email-validation

**Comment by kdoh** [comment]
@jornh Thanks for chiming in. I went ahead and tweaked this so that if LDAP is enabled everything behaves just as it has since we introduced LDAP, but if its not then we set the input type to email which gets us the built in validation for email addresses out of the box in cases where the username must be an email.

https://github.com/metabase/metabase/pull/6932/commits/5ae6e34c6020281dfb967295e9018f2b9b1f8488#diff-bf4737af6509a161955611831bb0d020R153

**Review by tlrobinson — APPROVED** [review]
LGTM

**Comment by tlrobinson** [comment]
@kdoh Although do we know why the form had `noValidate` to begin with?

**Comment by kdoh** [comment]
@tlrobinson I was wondering that myself. I did a bit of digging in the git history and I believe it's been around since the angular days which makes me think it was due to some usage there that's no longer relevant. Either way since we weren't running our own client side validation here it wasn't really helping out.

**Pull request merged**
