### PR TITLE
Migrate notebook aggregations to MLv2 — Disable MLv1 validation (4)

### PR DESCRIPTION
**Pull request by kulyk**
Part of #31001

The fourth step in the notebook editor's `AggregateStep` migration. That one excludes aggregations and breakouts from the MLv1 query "clean" phase.

MLv1 query clean is used to ensure that the columns we use in different clauses are actually available. Imagine we're joining tables A and B, sorting results by a column from B, and remove the join. MLv1's clean phase would detect that the sort clause uses a no longer available column and remove it.

This mechanism doesn't make sense for MLv2 — MLv2 guarantees query validity at any given stage, and it'll automatically clean up invalid clauses when e.g. `removeClause` is called. MLv2 also has minor differences in how field references look like. Because of these differences, MLv1 could treat MLv2's field references as invalid even tho they're fine. So far, it makes more sense to disable validation for these clauses, because only the notebook editor could produce "invalid" aggregations and breakouts

### To Verify

CI should be green 🟢

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
I'm only starting to ramp up my knowledge here and I noticed that it makes impossible to change the the aggregated dimension on previous stages now but I assume it should be working, right?

<video src="https://github.com/metabase/metabase/assets/14301985/6421802b-d7dc-4902-838b-6393b13015fa" />

**Review by ranquild — COMMENTED** [review]
What Sasha said. The change looks good but doesn't seem to be working correctly now

**Comment by kulyk** [comment]
Appreciate the bug report; it seems to be a BE problem, I've opened the issue to track it — #31858

**Comment by kulyk** [comment]
@alxnddr @ranquild please take another look — #31959 should have fixed the issue with editing aggregations from previous stages

**Review by ranquild — APPROVED** [review]

**Pull request merged**
