### PR TITLE
Pivot table improvements

### LINKED ISSUE #2618: Transpose or Swap Axes of Table Visualization
When I group and sum some 2D data, Metabase seems to choose the x and y axes for me. How do I swap the table orientation? Even when swapping the two grouping keys, it still chooses for me.

*  I am using the latest Chrome browser.
*  My computer's OS is OSX.
*  I'm running Metabase locally from the JAR
*  My database is Postgres.
*  My Metabase version is v0.17.

### LINKED ISSUE #4027: Unable to order pivoted tables descending in query builder
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome 55
- Your operating system: Ubuntu 16.10
- Your databases: Postgres, Redshift
- Metabase version: 0.21.1
- Metabase hosting environment: Ubuntu 16.04
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
1) Create a query in query builder
2) Use an aggregation
3) Group by 2 columns
--> You have a nice pivoted table
4) Order by the column that is the first column in the pivoted result table Descending: Order stays ascending :( 

image

### LINKED ISSUE #4210: Inconsistent Pivoting
- Your browser and the version: Chrome 55
- Your operating system: OS X 10.12
- Your databases: BigQuery
- Metabase version: 0.21

I have a dashboard with a bunch of cards - all of which are custom SQL. A couple of those cards have a table visualization, with pivot enabled. The dashboard also has a text filter which affects all the cards (account filter). 

Once I apply a filter value, the pivoted tables are refreshed. However, the structure of the pivot changes (columns and rows are switched).

Before Filter:
image

After Filter:
image

I think the better solution (which might require a separate issue?) would be to enable control of the pivoted data (what goes where).

### LINKED ISSUE #6419: Pivot Table: Sometimes the axis changes
In questions that has a pivot table, I think that has a bug that changes the order os axis, columns become rows and rows become columns. In an auto-refresh sometimes has this change.

### LINKED ISSUE #8053: Pivot Table Column Ordering
Hi, this is a feature request/question on how to do something specific, namely order columns in a pivot table. 

I set up Metabase on our company's MySQL database. The table we're hitting a minor issue with is normalized time series data. We are using Metabase's pivot table feature to convert the normalized data into columns, with Dates as the Y axis and Titles as the X axis. 

The issue is we cannot seem to reorder the order the columns appear in in a pivot table. Columns always seem to be alphabetic. For my team members who are used to being able to reorder columns in regular tables with Metabase, this has been confusing. 

Is re-ordering of pivot tables a planned feature? I searched through the PR's and issues but did not find a reference to it.

Thank you very much!

### LINKED ISSUE #8687: Simple pivot tables don't like color range conditional formatting
Was trying to create a single metric, dual dimension table with gradient conditional formatting on master in chrome, and got this behavior:

conditional-formatting-pivot-table

Only relevant JS error I saw:

`ColorRangePicker.jsx:35 Uncaught TypeError: Cannot read property 'map' of undefined
    at ColorRangePicker.jsx:35
    at _class.render (Triggerable.jsx:135)
    at _class.<anonymous> (makeAssimilatePrototype.js:15)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:359)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)`

### LINKED ISSUE #8720: Pivot table headers incorrect
In master pivot table column headers are incorrect due to the way column settings work.

### PR DESCRIPTION
**Pull request by tlrobinson**
Long overdue...

Resolves #8053 Pivot Table Column Ordering
Resolves #6419 Pivot Table: Sometimes the axis changes
Resolves #4027 Unable to order pivoted tables descending in query builder 
Resolves #4210 Inconsistent Pivoting 
Resolves #2618 Transpose or Swap Axes of Pivoted Table Visualization
Resolves #8720 Pivot table headers incorrect
Resolves #8687 Simple pivot tables don't like color range conditional formatting

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers thoughts on these changes and whether we should try to get it in 0.31? The main things are:

1. preserve order of the results, don't automatically sort them (see below for caveat)
2. ability to pick which columns appear in the header and cells

Regarding 1, I realized this is currently not quite correct if the results are sparse, e.x. in this case the results are sorted by the first and second columns, but `a y`  is missing:

```
a x 1
a z 2
b x 3
b y 4
b z 5
```

you'll end up with

```
  x z y
a 1 2
b 3 4 5
```

note the headers are out of order, `x z y` instead of `x y z`

I'll have to think about how to best handle this, preferably by just looking at the results and not the query so it works with SQL as well.

**Comment by MarkRx** [comment]
So long as people are able to change the x and y column order that's what matters.

As for default ordering it depends... you could get fancy to do better guessing but it would fall short in edge cases.

In the above example from the 'a' dataset you know:
> x < z

From the 'b' dataset you know:
> x < y
> y < z

You can thus deduce the order x < y < z. This falls apart should people have sparse enough datasets where there isn't enough information to make a conclusion. For example:

> a x 1
> a z 2
> b x 3
> b y 4

It isn't possible to determine which comes first - y or z. In the most extreme case two datasets could be mutually exclusive and thus incomparable. In that case maybe fall back to the result set order coming back from the database?

At the end of the day a person can reorder the columns as needed. As to if this is the right approach (complexity, intuitiveness to end user) vs the order of the result set... I don't know.

**Comment by mazameli** [comment]
This PR does indeed solve the issues. I feel like we could get rid of the `Data` tab in viz settings for pivot tables, though, and just put the stuff in it into the `Columns` tab. Then if pivoting is turned on, the `Pivot column` dropdown could just appear below it. And if pivoting is off, we'd hide that dropdown and show the `Visible fields` section instead. WDYT @tlrobinson?

**Comment by tlrobinson** [comment]
@mazameli @MarkRx I implemented a solution to the sorting problem that I think is reasonable. It detects if a column is sorted within a "group" but not globally and sorts the columns/rows accordingly. Please try it out and let me know what you think. Relevant code is in `data_grid.js`

**Review by kdoh — APPROVED** [review]

**Comment by mazameli** [comment]
LGTM

**Comment by gajus** [comment]
When is this planned to be released?

**Comment by mazameli** [comment]
@gajus In version 0.31, for which we're currently working on a release candidate.

**Pull request merged**
