### PR TITLE
Separate MBQL schema for time vs date/datetime literals

### PR DESCRIPTION
**Pull request by calherries**
This PR creates separate MBQL schema for time literals vs date or datetime literals.

This enables tighter constraints on MBQL clauses that can take date or datetime literals as arguments, but not time literals. The upcoming `convert-timezone`, and `datetime-diff` clauses are examples.

Note it is only possible to differentiate between time and date/datetime literal strings in Clojure and not ClojureScript, as we don't have functions to parse date vs datetime vs time ClojureScript.

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
Excellent change. This is great. LGTM

**Review by qnkhuat — APPROVED** [review]
Would be great if we can run those tests on cljs too but I guess it's not the scope of this PR.

**Comment by nemanjaglumac** [comment]
@calherries is this going to be included in the 45 release or we let it bake until 46?

**Comment by calherries** [comment]
Should have backported it, thanks for asking

**Pull request merged**
