### PR TITLE
Improve latitude 'inside' filter

### PR DESCRIPTION
**Pull request by tlrobinson**
* adds a way to set formatting options for filter arguments, so we can format latitude/longitude correctly
* add compact formatting for lat/lon for "inside" filter
* if there's only one option for the longitude field just default to it and don't show the widget. this is probably the common case, no point in confusing users by asking them to select the longitude field

screenshot 2018-02-23 14 20 08

### CODE REVIEW

**Comment by tlrobinson** [comment]
@salsakran @mazameli @kdoh Thoughts on this?

**Comment by kdoh** [comment]
Seems good to me. Could we use the formatting options system
> adds a way to set formatting options for filter arguments, so we can format latitude/longitude correctly

to help fix the `mailto:` issue in #7273?

**Comment by tlrobinson** [comment]
@kdoh Yeah, something like that. We'd probably add a `link` formatting option. Not sure if it would be best to default it to `true` (and pass `false` in a few places, maybe have a global default formatting options for FilterWidget / FieldValuesWidgert) or `false` (then pass `link={true}` to `Value` in Table/ObjectDetail)

**Comment by kdoh** [comment]
@tlrobinson Yeah as far as defaults are concerned my gut with `mailto:` says it's better to be precise and have to enable it where you want it, and maybe miss a few places, than have links popping up email clients in spots you didn't intend.

**Pull request merged**
