### PR TITLE
Relax restriction that sandboxes cannot add columns (ignore additional columns instead)

### LINKED ISSUE #14612: Advanced Sandboxing using questions that return more/other columns than the sandboxed table is not possible anymore, but the errors are not helpful
**Describe the bug**
Advanced Sandboxing using questions that return more/other columns than the sandboxed table is not possible anymore (1.38.0), since it caused an cascade of other problems.
This issue is only about providing helpful errors to admin - not to allow extra columns.

**To Reproduce**
This provides no feedback to the admin, why they cannot select a crazy QB question with extra columns - nothing in the log either.
image

Trying to edit a question that is used for sandboxing from
`SELECT ORDERS.* FROM ORDERS WHERE USER_ID={{sandbox}}`
to
`SELECT ORDERS.*, 'x' AS "EXTRACOL" FROM ORDERS WHERE USER_ID={{sandbox}}`
will now not be possible, since the question metadata is checked before saving.
image

And it's possible to change a QB question and save - in Notebook without ever seen any errors:
image

And if something like this is setup, when upgrading to 1.38.0 there will be errors when users just tries to access tables.
Example: `Output of gtap->source does not match schema: {:source-metadata [nil nil nil nil nil nil (not (map? nil))]}`
image

**Information about your Metabase Installation:**
Commit `6312927` (~0.38.0-rc4)

**Additional context**
Continuation of https://github.com/metabase/metabase-enterprise/issues/524

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #14612

@nemanjaglumac I could use some help updating the sandboxing test that checks that errors are shown, since as I mentioned the other day we were always going to have to change it once that restriction it tested was removed. I don't think I did it right

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
Tested `180952a`

I'm getting much better errors as a sandboxed user if there's some weird sandbox-card connected, which returns crazy columns:
`Sandbox Questions can't return columns that have different types than the Table they are sandboxing.`

But now I'm not seeing any error messages for the Admin at all.
- I can still select the crazy sandbox-card, which the user will get an error message with, without any messages to the admin.
- I can add columns to existing connected sandbox-card SQL and save - the user will never see the extra column, it's silently ignored.
- I can select any sandbox-card - example Orders sandboxed with SQL/QB card that returns Reviews-table, which then only displays the columns they have in common (ID, Product_ID, Created_At).

Note: If someone was using advanced sandboxing and extra columns etc, then downgrading might cause some problems until they manually re-run some of the sandboxed cards.

**Comment by flamber** [comment]
I have no idea what's going on. Went for a walk, came back and was switching around on all the permissions, and now I'm getting error as the admin, but only in some cases.
I was working on an instance upgraded from 1.37.8 with all the silliness done to sandbox-cards as I could imagine.

I can set the crazy sandbox-card for People table without any errors, but if I try setting it for Reviews, then it displays an error.
image

This is the crazy sandbox-card:
image

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac I could use some help updating the sandboxing test that checks that errors are shown, since as I mentioned the other day we were always going to have to change it once that restriction it tested was removed. I don't think I did it right

No worries. Let's sync offline.

**Comment by camsaul** [comment]
Ignoring the extra columns is intentional. It's the behavior that we proposed switching to (as opposed to showing an error)

**Comment by camsaul** [comment]
Errors might not show up in admin if it's a SQL question that you've never ran before, that's still an issue. I think we should consider that a separate smaller issue

**Comment by flamber** [comment]
Okay, ignoring the SQL question run-save vs just-save, it's not always showing errors to the admin with QB questions. I guess it has something to do with some matching columns between the table and the sandbox-card, which it then accepts sometimes.
It's better now that what it was, and it feels like fringe cases with crazy QB questions, but I don't know - I'm testing blind.

**Comment by nemanjaglumac** [comment]
@camsaul the test is now updated to cover differently-typed columns.

[20/20](https://github.com/nemanjaglumac/metabase-tests/actions/runs/558525589) green tests at GitHub actions. ✅

**Pull request merged**
