### PR TITLE
WIP | Data Apps Feature Branch

### PR DESCRIPTION
**Pull request by kulyk**

### CODE REVIEW

**Comment by TurkerTunali** [comment]
"Data Apss" sounds interesting.

**Comment by iethree** [comment]
@kulyk you think we can close this puppy now?

**Comment by kulyk** [comment]
@iethree well, I'm not sure to be honest. I'm pretty sure we won't need app containers, but the list viz is still there. What do you think?

**Comment by iethree** [comment]
> @iethree well, I'm not sure to be honest. I'm pretty sure we won't need app containers, but the list viz is still there. What do you think?

@kulyk I don't think list viz is happening any time soon, and if we ever get back to it, we can dig it out of this PR

**Pull request closed without merging**
