### PR TITLE
add renovate config

### PR DESCRIPTION
**Pull request by alxnddr**
This PR adds [Renovate](https://github.com/marketplace/renovate) config, which is a tool that helps to keep our dependencies up to date. Compared to [dependabot](https://github.com/dependabot), it is way more flexible and allows group changes together.

Since we have a lot of major outdated dependencies upgrading, which will require a significant amount of work, I enabled the bot only for minor and patch dependencies. It is scheduled to create PRs `every month on the first day of the month`.

Please share what do you think about this approach.

### How to verify
- Fork Metabase and merge this config into `master`
- Install [Renovate](https://github.com/marketplace/renovate) and give it access to the Metabase repo

It will create a PR: [Update all non-major dependencies](https://github.com/alxnddr/metabase/pull/57)
Also, it provides an issue with a [Dependency Dashboard](https://github.com/alxnddr/metabase/issues/39) where you can trigger the bot to run again.

### CODE REVIEW

**Review by daltojohnso — APPROVED** [review]
I'm unfamiliar with this tool, but this seems fine?

**Comment by alxnddr** [comment]
@daltojohnso this tool is quite popular https://github.com/renovatebot/renovate#who-uses-renovate worth giving it a shoot

**Review by kulyk — APPROVED** [review]
Cool! Nice work 👏

**Review by rlotun — APPROVED** [review]
i installed the renovate bot. thanks for doing this.

**Pull request merged**
