### PR TITLE
Rename X-Ray "fingerprints" to Thumbprints

### PR DESCRIPTION
**Pull request by camsaul**
Fixes naming from #5316

### CODE REVIEW

**Comment by salsakran** [comment]
Sweet.

So some things to consider -
* We should probably just refer to them as "X-Rays" throughout the frontend codebase, and the api layer

* re: Internal namespacing, I'm fairly indifferent to, since the eventual idea is to take a subset of the current sampled field x-ray and call that a "field fingerprint". This would serve as the "cached" or lowest compute cost version of an x-ray. I don't mind the idea the thing calculated by the analysis "fingerprinting" remaining a fingerprint, and the api endpoints calling functions for "thumbprints" as they'll often be bigger.
 
* Not really sure what the lowest level of functions , eg "metabase.fingerprinting.core" should be called.

**Comment by sbelak** [comment]
Agreed on 1).

As for "thumbprints" I'd then rather use a completely different name. This just seems confusing to someone new coming to the codebase and while it does establish a difference, the naming (thumbprint being a subset of fingerprint) does not properly convey their relationship.

**Comment by sbelak** [comment]
After some more though I'd rather us going for the ultra dry but descriptive feature-extraction and variants for fingerprinting, but keep x-ray for the user-facing part.

**Comment by camsaul** [comment]
Cool, when you come up with a better name than "thumbprints" this PR will probably still be a good starting-off point to get the rename in. I changed some of the stuff to "xray", for example the API endpoints, which sounds like a change we want to keep.

**Comment by kdoh** [comment]
I moved over the frontend stuff to use the term "Xray" and also made some structural changes so now XRays have their own part of the redux store, which should be useful as we add more features, like the comparison work we're doing.

@camsaul / @sbelak let me know when you land on names for things so I can update some of the selectors to use the proper key name from the API response.

**Comment by sbelak** [comment]
@salsakran, @camsaul if you are both fine, I'd like to rename fingerprint* to feature-extraction + x-ray so that we aren't dragging @kdoh down.

**Comment by camsaul** [comment]
I'm good with any name

**Comment by sbelak** [comment]
Closing this and moving work to branch feat-x-ray

**Comment by salsakran** [comment]
I'm cool with anything you two are good with, as this is all internally facing nomenclature. "X-Rays" will be the word we use externally, and I think it's good to decouple that from the specific details inside the box.

**Pull request closed without merging**
