### PR TITLE
Collections project bulk actions

### PR DESCRIPTION
**Pull request by kdoh**
- [x] Move modal button
- [ ] Make sure things don't stay selected on move
- [ ] Entity menu clipped (we need to switch to popovers to autodetect the window)
- [ ] Pinned item anatomy

### CODE REVIEW

**Comment by mazameli** [comment]
Bulk archiving could really use a toast notification with an Undo. It also feels to me like Move should be the first action. I accidentally hit Archive when I meant to hit Move.

**Comment by mazameli** [comment]
I know @kdoh's already on this 'cause we talked about it last week, but I think this will look nicer once these buttons are left-aligned with the entity lists, the way they already are in collections without sub-collections.

alignment

**Comment by kdoh** [comment]
@mazameli Most of the things you ran into should be fixed as of 1bf0279. Toasts are definitely part of the plan for both archiving and moving, @tlrobinson and I talked a little on Friday about the best way to make triggering those easier regardless of the situation so its just a matter of putting that plan into action I think.

**Comment by mazameli** [comment]
When I select items and then move them, when I go to their new destination they remain selected, which they shouldn't.

remain-selected

**Comment by mazameli** [comment]
This entity item menu gets clipped off toward the bottom of lists:

screen shot 2018-06-12 at 11 04 34 am

**Comment by mazameli** [comment]
Are we tackling the selection and favoriting of pinned items in this pr? I'd expect this item to have a checkbox, a star, and a `…` menu like the other un-pinned items:

screen shot 2018-06-12 at 11 06 30 am

**Comment by mazameli** [comment]
Couple small things about the move modal:

This default state feels odd because it appears that it's selected the "Saved items" collection, but the move button is disabled. I'd expect the current collection the item(s) is in to be highlighted.

screen shot 2018-06-12 at 11 10 11 am

Feels odd that I can "move" items to the collection it's already in:

screen shot 2018-06-12 at 11 10 20 am

I believe I'm the dunce who suggested repeating the name of the collection in the main move button, but this looks really goofy. I think this should just be a simple `Move` button, and I don't think we even need the icon. **I'm happy to make this change.**

screen shot 2018-06-12 at 11 10 30 am

**Comment by mazameli** [comment]
@tlrobinson I *love* this new simple permissions modal for collections. 

The only functional things that seem missing are on the _full_ permissions grid: 
- an X button to get out of it
- breadcrumbs to go up a collection level
- When editing the full permissions grid, if I cancel I'm taken back to the simple modal; I'd expect to just close all the modals.

In a separate future PR, we can also bring the full collections permissions grid to the Admin Panel Permissions tab.

**Pull request merged**
