### PR TITLE
Typo in Portuguese Translation

### PR DESCRIPTION
**Pull request by brunocavalcante**
Typo fix: "Encontratmos um erro..." should be "Encontramos um erro..."

### CODE REVIEW

**Comment by thalesmello** [comment]
Why does the diff change 9276 lines? Shouldn't it have been just a single one?

**Comment by iGitScor** [comment]
Clearly a whitespace issue (https://github.com/metabase/metabase/pull/8426/files?w=1) for this huge diff

**Comment by tlrobinson** [comment]
@brunocavalcante We've switched to using POEditor to more easily manage translations: https://poeditor.com/join/project/ynjQmwSsGh Could you please make the same change there.

**Comment by brunocavalcante** [comment]
Sure can! Already did. :)

**Pull request closed without merging**
