### PR TITLE
Support distinct by two or more columns in druid

### PR DESCRIPTION
**Pull request by anoopk19**
Druid driver will fail if custom aggregation expression is defined that should return a distinct count of two or more dimension columns. 

This code change will allow such aggregation expression

### CODE REVIEW

**Comment by anoopk19** [comment]
@camsaul , Can you review this pr?

**Review by camsaul — COMMENTED** [review]
This looks good so far. I will have to fork it to run tests against Druid, I will do that right now

**Comment by camsaul** [comment]
Ok, tests are running in this branch https://github.com/metabase/metabase/tree/anoopk19-master

**Comment by camsaul** [comment]
Ok, so the tests did pass for this, but I accidentally merged a different @anoopk19 PR. I'll run the tests again with all PRs merged and see if things work as expected

**Comment by camsaul** [comment]
@anoopk19 is there a GitHub issue that corresponds to this?

**Comment by camsaul** [comment]
Merged as part of #10752 which includes test fixes

**Pull request closed without merging**
