### PR TITLE
Funnel visualization single channel

### PR DESCRIPTION
**Pull request by tlrobinson**
I've merged @mavimo's PR #3275 with master, and merged our existing bar chart funnel visualization into the Funnel visualization.

It's currently defaulting multiseries to the old style bar funnel, and single series (multiple rows) to the new style funnel.

### CODE REVIEW

**Comment by mazameli** [comment]
Neat! Played around with it a bit, and seems like it's generally working pretty great. One thing I did notice is that it won't open up the chart options or work at all really if you're trying to use an unaggregated table, unless that table is already in the form that the funnel viz wants. Ideally, you'd be able to just pick any column to use for the metric and dimension/steps (incidentally, in the chart options for funnels, we might want to change the label from "dimension" to "steps" or something like that).

**Comment by mavimo** [comment]
@mazameli @tlrobinson whaaa, I suppose to lost this PR in my OS contribution, I'm really sorry -.-" 

There is something i can do to help on "funnel visualization" ?

**Comment by tlrobinson** [comment]
@mavimo No worries, thank you for doing most of the work! Give it a try and let me know if you find any issues.

@mazameli I fixed the issues you mentioned, please give it another try.

**Review by kdoh — APPROVED** [review]

**Comment by tlrobinson** [comment]
@mazameli Did you want to give this another try before I merge it?

**Pull request merged**
