### PR TITLE
Cherry pick be data apps

### PR DESCRIPTION
**Pull request by dpsutton**
EDIT:
this is also missing the migrations from https://github.com/metabase/metabase/pull/26717 and d9896f0656b4674c938f62af17fb4ba0a4566456 and e19050cbd95cc31289f3dfb823aa6c61edfd277e.

The two shas are easily mergeable. The problem is the first PR has lots of FE code mixed together. If i can send it all into master should be ok, otherwise would need @kulyk to merge it and deal with any conflicts.

#### Cherry picking data apps

Starting from https://github.com/metabase/metabase/pull/26013 which is branch `data-apps-main`, I got all of the commits in that branch as patches:

`git format-patch master..data-apps-main`

I copied these over into a directory and used `[org.eclipse.jgit/org.eclipse.jgit "6.4.0.202211300538-r"]` to parse the patch files for which ones touch the backend

```clojure
(ns patch
  (:require
   [clojure.java.io :as io]
   clojure.repl
   [clojure.string :as str])
  (:import
   org.eclipse.jgit.diff.DiffEntry
   org.eclipse.jgit.patch.Patch))

(def patch-files (remove #(.isDirectory %) (file-seq (io/file "patches")))) ;; copy patch files to patches dir

;; javadoc
;; https://download.eclipse.org/jgit/site/6.4.0.202211300538-r/apidocs/org/eclipse/jgit/patch/Patch.html#getFiles()
;; https://download.eclipse.org/jgit/site/6.4.0.202211300538-r/apidocs/org/eclipse/jgit/patch/FileHeader.html
(defn touches? [^DiffEntry de]
  (or (some-> de (.getNewPath) (str/ends-with? ".clj"))
      (some-> de (.getOldPath) (str/ends-with? ".clj"))))

(defn accumulate [patch-files]
  (reduce (fn [touching-be patch-file]
            (try (with-open [is (io/input-stream patch-file)]
                   (let [p (Patch.)]
                     (.parse p is)
                     (let [file-headers (.getFiles p)]
                       (if (some touches? file-headers)
                         (conj touching-be patch-file)
                         touching-be))))
                 (catch Exception e
                   (clojure.repl/pst e 10)
                   touching-be)))
          []
          patch-files))

(comment
  (def patches (accumulate patch-files))
  (count patches)
  (doseq [p (accumulate patch-files)]
    (io/copy p (io/file (str "keep/" (.getName p)))))
  )
```

This gives me a list of the following patches:
```
❯ for file in ./keep/* ; print $file
./keep/0002-Revert-Apps-Disable-data-apps-prior-to-release-25982.patch
./keep/0007-Apps-Implicit-action-pre-fetch-values-25940.patch
./keep/0008-Revert-Remove-data-app-permission-code-26016.patch
./keep/0010-Remove-unused-imports.patch
./keep/0018-Don-t-require-the-table_id-on-result_metadata-elemen.patch
./keep/0022-Support-filtering-cards-by-used-model-26088.patch
./keep/0034-Support-filtering-apps-using-a-given-model-26124.patch
./keep/0040-Apps-Handle-type-errors-more-cleanly-26120.patch
./keep/0045-Apps-Accept-model-ids-for-scaffolding-apps-26139.patch
./keep/0053-Apps-Add-required-to-action-parameters-26296.patch
./keep/0054-Apps-Cleanup-scaffolded-back-button-26317.patch
./keep/0076-Forward-action-execution-error-messages-to-the-front.patch
./keep/0084-Apps-Actions-for-public-pages-26554.patch
./keep/0085-Run-publicly-shared-actions-with-full-permissions-26.patch
./keep/0092-Support-actions-with-MySQL-and-MariaDB-26573.patch
./keep/0093-Check-permissions-for-implicit-actions-26652.patch
./keep/0101-WIP-Unify-action-representation-26717.patch
```

All of these are applied except the last one. That patch is based on 

```
From 06adc4d46fabb7ce98170bc818ef9530ecb10120 Mon Sep 17 00:00:00 2001
From: metamben <103100869+metamben@users.noreply.github.com>
Date: Wed, 30 Nov 2022 15:52:37 +0300
Subject: [PATCH 101/115] WIP: Unify action representation (#26717)
```
which is pr #26717 . This PR has the data-apps-main merged (not rebased) into it, so lots of FE changes came through. Hopefully @kulyk can get the branch to a state where that PR can be merged.

### CODE REVIEW

**Comment by snoe** [comment]
@dpsutton the migration yml file seems to have been missed, and I can't say for certain if there were `.cljc` changes.

**Comment by dpsutton** [comment]
> @dpsutton the migration yml file seems to have been missed, and I can't say for certain if there were `.cljc` changes.

ahh good point. I'll add that in. I checked and saw no `cljc` files involved but only after the fact :)

**Comment by camsaul** [comment]
We want to merge #27413 first, right? Once that's in, do we still need this PR?

**Comment by dpsutton** [comment]
closed in favor of tamas's https://github.com/metabase/metabase/pull/27413

**Pull request closed without merging**
