### PR TITLE
Remove all remaining E2E and frontend bits from CCI

### PR DESCRIPTION
**Pull request by nemanjaglumac**
This is the first successful run of our whole E2E test suite using GitHub Actions 🎉 
https://github.com/metabase/metabase/actions/runs/2565316800

And this is how CircleCI looks now :)
https://app.circleci.com/pipelines/github/metabase/metabase/38785/workflows/0997b29e-4144-42e1-bbfe-995673baa797
image

## Note for reviewers:
- Please check `config.yml` carefully and make sure t here are no leftovers related to frontend/e2e
- Also, as a sanity check make sure nothing that was removed is still needed (probably not because CI would catch it)

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
FYI, I was triggering the CI runs in order to see how often will `admin-ee` group fail due to the H2 connection failures during the `restore`.

**Review by flamber — APPROVED** [review]
I would have preferred adding the GHA in one PR and then removing CCI in a different PR a few days later, but I guess we're this close to the finish line, so might as well rip the :adhesive_bandage:

**Comment by nemanjaglumac** [comment]
> I would have preferred adding the GHA in one PR and then removing CCI in a different PR a few days later, but I guess we're this close to the finish line, so might as well rip the 🩹

Agreed in general, but there is no turning back now.
Whatever starts happening when we move these last two groups to GitHub Actions, we'll have to deal with it immediately.

**Review by kulyk — APPROVED** [review]
👏 👏 👏

**Comment by diogormendes** [comment]
@nemanjaglumac , it will need a manual backport

**Comment by nemanjaglumac** [comment]
Yup.
I'm aware, thank you.

The merge conflict is a bit nasty because we're using java 8 on a release branch and java 11 on master. I'll tag you once I prepare a manual backport.

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac , it will need a manual backport

Here it is.
#23573

**Pull request merged**
