### PR TITLE
Enable lots of additional security headers for Metabase.

### PR DESCRIPTION
**Pull request by camsaul**
Seeing how Security is Important (™) I've added a lot of best-practice HTTP headers to `index.html` responses to help prevent clickjacking, MITM, XSS, and other nasties.
-  Added the `Cache-Contol`, `Expires`, `Strict-Transport-Security`, `Content-Security-Policy`, `X-Frame-Options`, `X-XSS-Protection`, `X-Permitted-Cross-Domain-Policies`, and `X-Content-Type-Options` headers to requests that serve `index.html`. 
-  Added `Strict-Transport-Security` to API responses as well. 
-  Added new `Setting` to specify SSL cert public key. which, when set, will include `Public-Key-Pins` header with `index.html` and API responses as well.

If you're unfamiliar with any of these headers and would like to understand them better [this page](https://www.veracode.com/blog/2014/03/guidelines-for-setting-security-headers) is a good starting point.

Configuring `Content-Security-Policy` was a little tricky, so if people can help test things out with these new branch, and make sure no weirdness occurs, that would be :+1:

### CODE REVIEW

**Comment by camsaul** [comment]
BUMP

**Comment by camsaul** [comment]
BUMP

**Comment by salsakran** [comment]
+1 on the bump.

**Comment by agilliland** [comment]
Last time we talked about this the next steps were to add these headers to a few of our own internal instances so that we can validate them in use before we merge them.  I'm not going to merge this PR without first seeing how the app behaves when we run these headers in a real deployment.

**Comment by camsaul** [comment]
Cool, but that was a month and a half ago

**Comment by salsakran** [comment]
@agilliland so let's do that. deploy a branch of this on proto or something similar. 

I would really like to close this off and get in the habit of shipping security improvements in as tight a timeframe as possible. 

A PR like this shouldn't language for a month+

**Pull request merged**
