### PR TITLE
Always create new items in the current collection

### PR DESCRIPTION
**Pull request by ranquild**
Product doc https://www.notion.so/metabase/Make-Metabase-realize-I-m-trying-to-do-work-and-help-me-out-51ada72df7f94da483a0cc8c30cc173f?d=31d8a44a318a4322b184f8e4560cde2d#a02efa1d6a7640d8b42b61aebf7f5e5d

How to test:
- Open a non-root collection
- Click `New` -> `Collection`
- Make sure the suggested collection is the opened one

Screenshot 2022-08-25 at 14 18 33

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
Users with no access to "Our Analytics" have their personal collection pre-selected instead of the current one:
Screen Shot 2022-08-25 at 3 32 14 PM

**Review by kulyk — APPROVED** [review]
This is amazing 🎉 Noticed it doesn't work for "+ New > Question", but it doesn't work on `master` as well. That's odd given we were setting new question's `collectionId` in `Urls.newQuestion` 🤔

**Review by kulyk — APPROVED** [review]
This is amazing 🎉 Noticed it doesn't work for "+ New > Question", but it doesn't work on `master` as well. That's odd given we were setting new question's `collectionId` in `Urls.newQuestion` 🤔

**Comment by ranquild** [comment]
@alxnddr I can't reproduce it. Does your non-admin user has `curate` access to the current collection? If not, that would explain it. 

Screenshot 2022-08-25 at 15 00 52
Screenshot 2022-08-25 at 15 01 00
Screenshot 2022-08-25 at 15 01 08

**Review by alxnddr — APPROVED** [review]
@ranquild sorry, you're right, the user did not have `curate` permission on the collection

**Pull request merged**
