### PR TITLE
Drop full screen mode text size modifications

### LINKED ISSUE #9615: Fullscreen mode causes changes to font sizes which skews intended layout
I have a layout which looks great but when put into fullscreen mode, the text either gets hidden or if in a text card suddenly becomes too big. For example
great
notsogreat
expected
distorted

It seems like this is a feature though? If so, is there anyway to get night mode without having to go fullscreen? Thanks.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/9615

### Description

Drop full screen mode font size modifications

### How to verify

1. go to dashboard, create text card, put some text that fills almost all space of the card
2. go to full screen mode (... -> enter full screen mode)
3. verify that font size in dashcards is not changed  

### Demo

https://www.loom.com/share/b8b8661e5cd44361999c89eee89b5f71

### Checklist

~- [ ] Tests have been added/updated to cover changes in this PR~

### CODE REVIEW

**Comment by uladzimirdev** [comment]
we're waiting for feedback from design team regarding full screen mode

**Review by kdoh — COMMENTED** [review]
Fascinating that this results in a positive diff. I would have just deleted [these lines](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/css/dashboard.css#L252-L285) altogether but is there some context I don't have about why adding a new rule is required?

**Comment by uladzimirdev** [comment]
@kdoh this PR was created before the decision to drop all styles 😄 I'll rework it

**Review by kamilmielnik — APPROVED** [review]
:+1:

**Pull request merged**
