### PR TITLE
repro/Dash w text box cards

### PR DESCRIPTION
**Pull request by Opalevanescence**
Cypress repro of Issue #12873 
Test will pass when issue is solved

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]
LGTM. I added a commit to remove a `skip` from the first `it`. I'm pretty sure that was fixed early today in #12891

**Comment by paulrosenzweig** [comment]
Whoops the test still failed. I was thinking of #11358, which isn't quite merged yet.

**Comment by Opalevanescence** [comment]
Ah, okay, I'll add the `skip()` back in for now

**Comment by paulrosenzweig** [comment]
Now that #11358 has been merged, I re-un-skipped the test, confirmed it worked, and pushed that change here. 😆  sorry for toggling that back and forth.

**Pull request merged**
