### PR TITLE
Metadata/refs overhaul. RIP `field_ref`

### LINKED ISSUE #29701: [MLv2] You should be able to add `:expression`s as order-bys
`lib/order-by` currently errors if you try to use it with an expression reference.

### LINKED ISSUE #29702: [MLv2] [Bug] `orderable-columns` should work if query contains two columns with the same name from different tables
```clj
(-> (lib/query-for-table-name meta/metadata-provider "VENUES")
    (lib/join (-> (lib/join-clause
                    (meta/table-metadata :categories)
                    (lib/=
                      (lib/field "VENUES" "CATEGORY_ID")
                      (lib/field "CATEGORIES" "ID")))
                  (lib/with-join-fields :all)))
    (lib/fields [(lib/field "VENUES" "ID")  (lib/field "CATEGORIES" "ID")])
    (lib/append-stage)
    (lib/orderable-columns))
```

Results in `Column :names must be distinct!`

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #29701
Fixes #29702

Some work towards #29704
Some work towards #29707 

This PR overhauls `:field_ref` calculation. Instead of including `:field_ref`s in all calculated metadata, field refs are now calculated on demand when you need them. Ignore existing `:field_ref`s in metadata. This serves two important purposes:

1. `field_ref`s tend to be wrong all the time; we can't really trust saved field refs. It's safer to recalculate them. They're a never-ending source of bugs, see https://github.com/metabase/metabase/search?q=field_ref&state=open&type=issues. 👋 field refs
2. When referring to the same Field more than once in a query in different places, we need to use unique UUIDs anyway (see #28722 and #29696), so we need to regenerate that part of the Field ref _anyway_
3. Generating a bunch of random UUIDs we never end up using is wasteful and will make our tests slow in low-entropy cloud runners; only generate them when we need them.
4. Field refs need to be different depending on where you use them -- see https://github.com/metabase/metabase/issues/27735
5. Not having reified `field_refs` in the metadata will discourage people from using them for dumb purposes in the future, such as keys in viz settings

This PR removes `metabase.lib.field/->field` and `metabase.lib.field/field` and replaces them with more general multimethods `metabase.lib.ref/ref`. These work with other things that can be referenced too, like expressions.

The new idea is you generate references on demand when you're adding something to a query.

Calculated metadata from `metabase.lib.metadata.calculation/metadata` is now guaranteed to include `:lib/source` information telling you where a field ref comes from, e.g. `:source/expressions` or `:source/previous-stage`, so we can generate CORRECT field references 100% of the time.

While I was at it I also fixed order by stuff not working with expression references and a few other things

This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29711)

### CODE REVIEW

**Review by camsaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29711)* status: 0 of 31 files reviewed, 14 unresolved discussions

___
*[`src/metabase/lib/aggregation.cljc` line 52 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpTjqfCK_G_xk8tjEr:-NRpTjqfCK_G_xk8tjEs:bxm1erd) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/aggregation.cljc#L52)):*
> ```Clojure
>      (when (:base-type opts)
>        {:base_type (:base-type opts)})
>      (when (:effective-type opts)
> ```

See #29707 ([MLv2] Uh, aren't we supposed to be using `:effective-type` everywhere, not `:base-type`?)  
___
*[`src/metabase/lib/field.cljc` line 147 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpU28P6rcjF8fMzrQh:-NRpU28P6rcjF8fMzrQi:b-9fh6gk) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/field.cljc#L147)):*
> ```Clojure
>   (::temporal-unit metadata))
> 
> (defmethod lib.temporal-bucket/temporal-bucket-method :field
> ```

Since field refs are now generated from `:metadata/field`s its important that the temporal unit is stored in an agreed-upon key by the ref generation code, and for resolving a ref back to metadata. I changed this up a bit so current temporal unit and changing the temporal unit is opaque even to other parts of MLv2 and is done thru methods.

This is some work towards #29704 ([MLv2] Finish implementing temporal bucketing) 
___
*[`src/metabase/lib/field.cljc` line 171 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpUcmM1c1pULsQCx3U:-NRpUcmM1c1pULsQCx3V:bxjse5s) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/field.cljc#L171)):*
> ```Clojure
>     [:field (dissoc opts :join-alias) id-or-name]))
> 
> (defmethod lib.join/with-join-alias-method :metadata/field
> ```

Same idea for joins.
___
*[`src/metabase/lib/join.cljc` line 16 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpUk-MEMfMV0pyqXbI:-NRpUk-MEMfMV0pyqXbJ:b6c90je) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/join.cljc#L16)):*
> ```Clojure
>    [metabase.util.malli :as mu]))
> 
> (defmulti with-join-alias-method
> ```

I moved this stuff so we could keep the `defmulti`s at the top of the namespace. Added `current-join-alias-method` and `current-join-alias` because we'll want those at some point (that point is now, in this PR)
___
*[`src/metabase/lib/metadata.cljc` line 78 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpUxevCJ5wroXxAEkC:-NRpUxevCJ5wroXxAEkD:bjidj77) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/metadata.cljc#L78)):*
> ```Clojure
>    ;; `fk_field_id` would be `VENUES.CATEGORY_ID`. In a `:field` reference this is saved in the options map as
>    ;; `:source-field`.
>    [:fk_field_id    {:optional true} [:maybe ::lib.schema.id/field]]
> ```

filled out this schema a little more so it's easier to remember what the normal keys you might expect to see in here are and what they mean. These keys match the existing metadata format so do not complain to me about dumb names.
___
*[`src/metabase/lib/normalize.cljc` line 40 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpV8dg5FZiqnVavy4N:-NRpV8dg5FZiqnVavy4O:b1fw4qj) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/normalize.cljc#L40)):*
> ```Clojure
>    ;; we can calculate `:field_ref` now using [[metabase.lib.ref/ref]]; `:field_ref` is wrong half of the time anyway,
>    ;; so ignore it.
>    :field_ref   (constantly ::do-not-use-me)
> ```

strip out field refs any time we encounter them when normalizing metadata or the like. Don't use them! 
___
*[`src/metabase/lib/stage.cljc` line 33 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpVKZC5zfBCXaVsN6p:-NRpVKZC5zfBCXaVsN6q:b25tvbk) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/stage.cljc#L33)):*
> ```Clojure
>     :filter      lib.normalize/normalize}))
> 
> (mu/defn ^:private ensure-previous-stages-have-metadata :- ::lib.schema/query
> ```

the changes in this namespace are almost all breaking out large functions into smaller ones and other small refactors, no significant changes to how this stuff actually works other than including the new `:lib/source` keys
___
*[`src/metabase/lib/temporal_bucket.cljc` line 39 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpVWIg4gFy94YzbMQ3:-NRpVWIg4gFy94YzbMQ4:bpgt8oa) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/temporal_bucket.cljc#L39)):*
> ```Clojure
>       (i18n/tru "last {0} {1}" (pr-str (abs n)) (unit->i18n (abs n) unit)))))
> 
> (defmulti temporal-bucket-method
> ```

renamed for consistency with everything else
___
*[`src/metabase/lib/temporal_bucket.cljc` line 64 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpVYr5DLAl77Kmp9tf:-NRpVYr5DLAl77Kmp9tg:b-8zmbn6) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/temporal_bucket.cljc#L64)):*
> ```Clojure
>   (temporal-bucket-method x unit))
> 
> (defmulti current-temporal-bucket-method
> ```

Work towards #29704, another thing on the TODO list to cross off.
___
*[`src/metabase/lib/temporal_bucket.cljc` line 78 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpVda3A0bTMbW-kT9L:-NRpVda3A0bTMbW-kT9M:biy27wi) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/temporal_bucket.cljc#L78)):*
> ```Clojure
>   (current-temporal-bucket-method x))
> 
> (defmulti available-temporal-buckets-method
> ```

Not yet fully implemented, will finish this up in the PR for #29704 ([MLv2] Finish implementing temporal bucketing) 
___
*[`src/metabase/lib/metadata/calculation.cljc` line 118 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpVmTi89uT9lgHn1-y:-NRpVmTi89uT9lgHn1-z:b-nsmvjk) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/metadata/calculation.cljc#L118)):*
> ```Clojure
>     (lib.dispatch/dispatch-value x)))
> 
> (defmethod metadata-method :default
> ```

Made `metadata` a wrapper, and the multimethod is now `metadata-method`, so we can have nice arities and use `mu/defn` to validate the results
___
*[`src/metabase/lib/schema/ref.cljc` line 53 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpVve88wMd4A27teE9:-NRpVve88wMd4A27teEA:bpotoq3) ([raw file](https://github.com/metabase/metabase/blob/8c45fb6ac41ce7e962a8b6636ccf005fa1898394/src/metabase/lib/schema/ref.cljc#L53)):*
> ```Clojure
> (defmethod expression/type-of* :field
>   [[_tag opts _id-or-name]]
>   (or ((some-fn :effective-type :base-type) opts)
> ```

Work towards #29707 ([MLv2] Uh, aren't we supposed to be using `:effective-type` everywhere, not `:base-type`?) 
___
*[`test/metabase/lib/dev_test.cljc` line 23 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpW4bw4nR8i9gA_o66:-NRpW4bw4nR8i9gA_o67:b-da80ys) ([raw file](https://github.com/metabase/metabase/blob/a817ed8aff5ef4c0048c747caaecaeed5c143a31/test/metabase/lib/dev_test.cljc#L23)):*
> ```Clojure
>             (f {:lib/type :mbql/query, :lib/metadata meta/metadata-provider} -1)))))
> 
> (deftest ^:parallel field-from-results-metadata-test
> ```

Moved this into `metabase.lib.field-test` since there is nothing dev-specific about this test
___
*[`test/metabase/lib/order_by_test.cljc` line 125 at r2](https://reviewable.io/reviews/metabase/metabase/29711#-NRpWGOaE31ndgXmFNCq:-NRpWGOaE31ndgXmFNCr:b-br2dc5) ([raw file](https://github.com/metabase/metabase/blob/a817ed8aff5ef4c0048c747caaecaeed5c143a31/test/metabase/lib/order_by_test.cljc#L125)):*
> ```Clojure
>            (describe-legacy-query-order-by query)))))
> 
> (deftest ^:parallel describe-order-by-expression-reference-test
> ```

I finally implemented this test, but it's part of the new test at the bottom of the file now, so see below

**Review by bshepherdson — CHANGES_REQUESTED** [review]
> Reviewed 25 of 31 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29711)* status: all files reviewed, 15 unresolved discussions (waiting on @camsaul)

___
*[`src/metabase/lib/metadata.cljc` line 32 at r3](https://reviewable.io/reviews/metabase/metabase/29711#-NRsymTq1aX8-_C0rZXt:-NRsymTq1aX8-_C0rZXu:bhnyns1) ([raw file](https://github.com/metabase/metabase/blob/e2cdcd175bba525ff078ffc09ec8c2548d48ba4d/src/metabase/lib/metadata.cljc#L32)):*
> ```Clojure
> ;;; away dealing with Dimensions in the future so the FE QB GUI doesn't need to special case them.
> 
> (mr/def ::column-source
> ```

These are inconsistently pluralized. `:source/aggregation` is singular, but `:source/expressions` is not. I think singular makes more sense: `aggregation`, `expression`, `previous-stage`, `card`, `native`, etc.

**Review by camsaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29711)* status: all files reviewed, 15 unresolved discussions (waiting on @bshepherdson)

___
*[`src/metabase/lib/metadata.cljc` line 32 at r3](https://reviewable.io/reviews/metabase/metabase/29711#-NRsymTq1aX8-_C0rZXt:-NRtEAk33u4z-gkjEjND:b-qpzptc) ([raw file](https://github.com/metabase/metabase/blob/e2cdcd175bba525ff078ffc09ec8c2548d48ba4d/src/metabase/lib/metadata.cljc#L32)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

These are inconsistently pluralized. `:source/aggregation` is singular, but `:source/expressions` is not. I think singular makes more sense: `aggregation`, `expression`, `previous-stage`, `card`, `native`, etc.
</blockquote></details>

This is intentional. `:lib/source` is supposed to correspond to the part of the query stage where something came from; a query indeed can have multiple `expressions` but only one `previous-stage`. RE `aggregations` and `breakouts`: the keys are currently singular, but in reality they correspond to something plural; I think in the near term future we're going to rename these keys anyway -- https://github.com/metabase/metabase/issues/29736 is on our TODO list -- so I gave them plural names to reflect reality and avoid making more work for us when we tackle https://github.com/metabase/metabase/issues/29736.

**Comment by snoe** [comment]
I wonder if we should make `lib.dev/field` smarter so that things that are not sourced from the current stage are passed through `ref` or if malli can enforce the use of refs over ids.

In this example, it would be nice if the `order-by` used `[:field {...} "ID"]`. It seems that with this change referring to it by `field-id` would go against the purpose.



_Code snippet:_
```
(-> (lib/query-for-table-name meta/metadata-provider "VENUES")
    (lib/fields [(lib/field "VENUES" "ID")])
    (lib/append-stage)
    (lib/order-by (lib/field "VENUES" "ID")))
```

**Review by bshepherdson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29711)* status: all files reviewed, 15 unresolved discussions (waiting on @camsaul and @snoe)

___
*[`src/metabase/lib/metadata.cljc` line 32 at r3](https://reviewable.io/reviews/metabase/metabase/29711#-NRsymTq1aX8-_C0rZXt:-NRts3BE05cN0SJ3ryoX:b-dxcbts) ([raw file](https://github.com/metabase/metabase/blob/e2cdcd175bba525ff078ffc09ec8c2548d48ba4d/src/metabase/lib/metadata.cljc#L32)):*
<details><summary><i>Previously, camsaul (Cam Saul) wrote…</i></summary><blockquote>

This is intentional. `:lib/source` is supposed to correspond to the part of the query stage where something came from; a query indeed can have multiple `expressions` but only one `previous-stage`. RE `aggregations` and `breakouts`: the keys are currently singular, but in reality they correspond to something plural; I think in the near term future we're going to rename these keys anyway -- https://github.com/metabase/metabase/issues/29736 is on our TODO list -- so I gave them plural names to reflect reality and avoid making more work for us once we tackle https://github.com/metabase/metabase/issues/29736.  
</blockquote></details>

Makes sense.

**Pull request merged**
