### PR TITLE
make sure QP "annotate" returns the correct version of a field (fixes #1257)

### LINKED ISSUE #1257: Filter and group same field by different granularities results in wrong "unit" result column.
```
{
  source_table: 12,
  filter: ["TIME_INTERVAL", 45, "current", "year"],
  aggregation: ["count"],
  breakout: [["datetime_field", 45, "as", "quarter"]]
}
```

Expected: `data.cols[0].unit  == "quarter"`
Actual: `data.cols[0].unit  == "year"`

### PR DESCRIPTION
**Pull request by camsaul**
@tlrobinson @agilliland I can't reproduce #1257. Here are some tests to prove it is working

### CODE REVIEW

**Comment by agilliland** [comment]
Not sure about the unit tests, but this is definitely still happening.  Here's a couple screenshots illustrating the issue.

Query using the sample dataset has a filter with the granularity set to "year" and a breakout with the granularity set to "week", but the query is returning the results as unit = year when it should be unit = week.  Keep in mind that it's the same exact column.

screen shot 2015-11-10 at 3 08 18 pm

This is the exact JSON response from the api which shows unit = year instead of unit = week like expected.
screen shot 2015-11-10 at 3 08 25 pm

**Comment by camsaul** [comment]
@agilliland can you give me the query dict that's getting passed to the API for that query

**Comment by agilliland** [comment]
```
{:database 1,
 :type "query",
 :query
 {:source_table 1,
  :aggregation ["count"],
  :breakout [["datetime_field" 25 "as" "week"]],
  :filter ["AND" ["TIME_INTERVAL" 25 "current" "year"]]}}
```

**Comment by camsaul** [comment]
@agilliland @tlrobinson this fixes #1257

**Comment by agilliland** [comment]
perfect.  just gave this a try and it's working for me!

**Comment by agilliland** [comment]
FYI, merge from master to get a couple fixes which were affecting unit tests on CircleCi.

**Comment by agilliland** [comment]
nice.  :+1:

**Pull request merged**
