### PR TITLE
tighten up some stray debug logging.

### LINKED ISSUE #2796: disable debug logging on api call paths
Doesn't seem all that useful to have logs full of things like this ...

screen shot 2016-06-17 at 12 13 19 pm

### PR DESCRIPTION
**Pull request by agilliland**
Resolves #2796

### CODE REVIEW

**Comment by camsaul** [comment]
Logging API calls has helped us solve a few bugs in the past. Instead of removing it entirely it makes a lot more sense just to skip logging the noisy calls like `health` and `logs`.

**Comment by agilliland** [comment]
Personally I would vote for leaving those messages out of the logs because 99% of the time they are just going to be noise for end users and should only be of relevance to developers.  Again, any logging that is really meant to be in the logs all the time should not be logged at DEBUG level.

Either way, if you feel you have a better approach then I'll let you make those changes.

**Comment by salsakran** [comment]
Clear +1 on the client side console logging.

Can we just add a system wide setting for this? Most other software out there has a log verbosity option for this very reason (namely that there are reasonable differences of opinion on when to spit out debug logs).

**Comment by tlrobinson** [comment]
JavaScript's `console.log` and friends don't have a standard way to set the desired log level. In some browsers like Chrome it's a UI setting in the dev tools.

We could hack it by doing something like `console.log = function() {}` though. Or use a more full-featured logging package, and enforce no `console.log` in ESLint.

**Pull request merged**
