### PR TITLE
Disable CSV uploads for sandboxed users

### LINKED ISSUE #32263: Don't allow CSV uploads when sandboxing is enabled
## Context
Sandboxed users shouldn't be able to upload CSVs. [More context here](https://metaboat.slack.com/archives/C04S696LRUM/p1688502771309619).

### PR DESCRIPTION
**Pull request by tsmacdonald**
[Fixes #32263]

Hoping that @npfitz does it on the FE as a separate PR.

### CODE REVIEW

**Comment by tsmacdonald** [comment]
@noahmoss I don't quite understand the…relationship here. I thought that sandboxing was a per-table thing, so I would've thought that I'd have to check the user perms against the uploads DB, not that there was a global "is this user sandboxed? yes or no" thing.

This might all be a moot point after I do #32265 though?

**Comment by noahmoss** [comment]
@tsmacdonald That is how sandboxing works, but we also treat "sandboxed users" (i.e. users who have _any_ sandboxing enabled) as a general class of users who have certain features disabled. For example, we disable editing SQL snippets for sandboxed users, and we also hide all the other users on an instance from them when they create subscriptions. So there's precedent for this sort of thing.

**Comment by tsmacdonald** [comment]
@noahmoss Cool, sounds great, thanks. So I stand behind this PR as…doing that.

**Review by noahmoss — APPROVED** [review]
Looks good, although I wonder if uploads should also be restricted for users using connection impersonation. I've asked on Slack; if the answer is yes you should be able to just change the check to use `sandboxed-or-impersonated-user?`

**Pull request merged**
