### PR TITLE
New dashboard grid size [WIP]

### LINKED ISSUE #1024: Order of dashboard cards on a small screen should be same order as on a large screen
Presently, the order of cards on a customized dashboard when viewed on a large screen are one way, and then the order changes in an unexpected way when you resize your window down to tablet/mobile size. Instead of presenting the cards stacked vertically in the expected order (i.e., top-left card first, the one to the right of it second, and so on), the cards are presented *in the order in which they were created*. This is unexpected.

Cards arranged how I want them. **Card E was created first.**
screen shot 2015-09-23 at 2 18 27 pm

Cards all willy nilly:
screen shot 2015-09-23 at 2 18 46 pm

### LINKED ISSUE #2055: Lots of empty space at the bottom of my dashboard
If this is a bug report, please fill in the blanks:

*  I am using the OSX app
*  My Metabase version is `0.15.0`

Here's a screenshot of `0.14.1` (left) side-by-side with `0.15.0` (right), both scrolled all the way to the bottom of the same dashboard. `0.14.1` stops where the last card stops but `0.15.0` lets me keep scrolling well past the end of the board.

screen shot 2016-02-29 at 3 51 37 pm

FWIW I've tried this in the `0.12.1` and `0.13.3` releases of the OS X app as well. Those behave like `0.14.1` (no extra whitespace)

### PR DESCRIPTION
**Pull request by tlrobinson**
- [x] Show grid when editing
- [x] Change grid width from 6 to 12 cells wide
- [x] Change grid aspect ratio from 1:1 to 4:3
- [ ] Migrate/version legacy dashcards (need to multiply `col` and `sizeX` by 2, `row` and `sizeY` by 2 to maintain approximate existing size and aspect ratio)
- [x] Don't expand grid rows beyond bottom card unless editing (resolves #2055)
- [x] Display dashcards in same order in 1D mobile layout as 2D grid layout (resolves #1024)

### CODE REVIEW

**Comment by tlrobinson** [comment]
@agilliland how should we go about migrating existing dashcards? @kdoh and I figured out how we need to scale them to maintain their existing size in the new grid, assuming 18 cells wide, fixed 4:3 aspect ratio (previous was 6 cells wide, 1:1 aspect ratio). One time migration, or version dashcards and migrate-on-write?

**Comment by camsaul** [comment]
use the data migration stuff I added a while back

**Comment by tlrobinson** [comment]
The cells themselves would have a 4:3 aspect ratio (in pixels). Cards can have varying aspect ratios (cell, and thus pixel). You'd need to make a card 3x4 cells to get it to be square, assuming cells have 4:3 aspect ratios.

Playing with it I think @kdoh and I decided a width of 12 cells feels better than 18. However then I don't think we can scale the height of existing cards correctly to maintain their aspect ratios.

I actually like square cells. It feels more symmetric to me.

**Comment by agilliland** [comment]
frontend isn't building for me right now ```ERROR in ./frontend/src/visualizations/components/Visualization.jsx
Module not found: Error: Cannot resolve module 'icepick' in /Users/agilliland/workspace/metabase/metabase/frontend/src/visualizations/components
 @ ./frontend/src/visualizations/components/Visualization.jsx 27:15-33```

**Comment by agilliland** [comment]
@tlrobinson let me know if you are ready to take this for a test drive.

**Comment by agilliland** [comment]
@tlrobinson one really crappy thing I just realized is that with the new grid system change all of the old dashboard revisions are going to be messed up.  so realistically when we upgrade we should deal with that somehow otherwise users could upgrade then revert to a previous revision which will be using the wrong grid system.

**Comment by tlrobinson** [comment]
I'm just going to close this in favor of #2103 since we really need to evaluate the new grid in conjunction with the new scalable visualizations.

**Pull request closed without merging**
