### PR TITLE
Show inactive tables in database & table pickers in the query builder

### PR DESCRIPTION
**Pull request by ranquild**
Epic: https://github.com/metabase/metabase/issues/18675

1. For databases - if the initial sync for all tables hasn't finished
2. For tables - if the initial sync for this table hasn't finished

DatabaseSchemaPicker:
Screen Shot 2021-10-27 at 10 28 06 pm

TablePicker:
Screen Shot 2021-10-27 at 10 31 42 pm

How to test:
As the BE for this PR is not ready we would need to rely on mocked data:
1. Set `initial_sync` to false https://github.com/metabase/metabase/blob/c0b5c697d1c5c814ec35a50ed2696617ea172d4a/frontend/src/metabase/schema.js#L19
2. Set `initial_sync` to false https://github.com/metabase/metabase/blob/c0b5c697d1c5c814ec35a50ed2696617ea172d4a/frontend/src/metabase/schema.js#L53
3. Add a question -> Simple question. 
4. If your instance has only one database, click on the back icon to navigate to Database picker.
5. Check that databases have spinners but it's possible to select them.
6. Check that tables are disabled and it's not possible to select them.
7. Revert `initial_sync` changes and check that everything works as usual.

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
Should we also update items state in the data picker search?
Screen Shot 2021-11-15 at 14 11 56

When a db has schemas, the loader is centered:
Screen Shot 2021-11-15 at 14 11 29

**Comment by ranquild** [comment]
@alxnddr All the issues are fixed atm

**Comment by alxnddr** [comment]
@ranquild one last bit:
Without changing `initial_sync` "Raw Data" has a loader
Screen Shot 2021-11-15 at 20 16 02

**Comment by ranquild** [comment]
@alxnddr Great catch! Fixed

**Review by alxnddr — APPROVED** [review]

**Pull request merged**
