### PR TITLE
Fix clicking on a legend item in the query builder on unsaved question

### LINKED ISSUE #12439: Clicking on legend in native question breaks the UI
**Describe the bug**

**Logs**
```
app-main.bundle.js?1580a7cbc7eacd7d4885:5 Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at Function.value (app-main.bundle.js?1580a7cbc7eacd7d4885:5)
    at e.value (app-main.bundle.js?1580a7cbc7eacd7d4885:5)
    at app-main.bundle.js?1580a7cbc7eacd7d4885:5
    at i (app-main.bundle.js?1580a7cbc7eacd7d4885:5)
    at e.n.value (app-main.bundle.js?1580a7cbc7eacd7d4885:5)
    at app-main.bundle.js?1580a7cbc7eacd7d4885:5
    at vendor.bundle.js?1580a7cbc7eacd7d4885:1
    at vendor.bundle.js?1580a7cbc7eacd7d4885:1
    at vendor.bundle.js?1580a7cbc7eacd7d4885:1
    at vendor.bundle.js?1580a7cbc7eacd7d4885:1
```

**To Reproduce**
1. Create a new native question
2. Use this SQL:
```sql
SELECT "PRODUCTS__via__PRODUCT_ID"."CATEGORY" AS "CATEGORY", parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') AS "CREATED_AT", count(*) AS "count"
FROM "PUBLIC"."ORDERS"
LEFT JOIN "PUBLIC"."PRODUCTS" "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
GROUP BY "PRODUCTS__via__PRODUCT_ID"."CATEGORY", parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM')
ORDER BY "PRODUCTS__via__PRODUCT_ID"."CATEGORY" ASC, parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') ASC
```
3. Click "Visualization" and select "Line Chart"
4. Click on any of the legends
5. Note that we get the above error in the console
6. Try to click other buttons in the UI and notice it has become unresponsive

**Expected behavior**
That clicking on the legend does nothing.

**Screenshots**
n/a

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.171-105.231.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "mysql",
      "redshift",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-28",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "e72d28e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Annoying, but can workaround it by not clicking on the legend.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/12439

Steps to reproduce:

- Ask a native question with `SELECT "PRODUCTS__via__PRODUCT_ID"."CATEGORY" AS "CATEGORY", parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') AS "CREATED_AT", count(*) AS "count"
FROM "PUBLIC"."ORDERS"
LEFT JOIN "PUBLIC"."PRODUCTS" "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
GROUP BY "PRODUCTS__via__PRODUCT_ID"."CATEGORY", parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM')
ORDER BY "PRODUCTS__via__PRODUCT_ID"."CATEGORY" ASC, parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM`
- Click on a legend item
- The question should **not** be reloaded
- Important - do not save the question!

### CODE REVIEW

**Review by daltojohnso — APPROVED** [review]
Works as described. I'm confused about why a legend click should trigger a rerun of the query, though.

**Review by flamber — CHANGES_REQUESTED** [review]
I think we should just not present the legend as clickable here.

This PR causes /api/dataset request (which requires permissions), but it also modifies the question title.
When I'm on `/question/788-sql-multiple-series` and click the Gizmo legend, then the URL changes to the following:
`/question/788-gizmo#eyJuYW1lIjoiR2l6bW8iLCJkZXNjcmlwdGlvbiI6bnVsbCwiZGF0YXNldF9xdWVyeSI6eyJ0eXBlIjoibmF0aXZlIiwibmF0aXZlIjp7InF1ZXJ5IjoiU0VMRUNUIFwiUFJPRFVDVFNfX3ZpYV9fUFJPRFVDVF9JRFwiLlwiQ0FURUdPUllcIiBBUyBcIkNBVEVHT1JZXCIsIHBhcnNlZGF0ZXRpbWUoZm9ybWF0ZGF0ZXRpbWUoXCJQVUJMSUNcIi5cIk9SREVSU1wiLlwiQ1JFQVRFRF9BVFwiLCAneXl5eU1NJyksICd5eXl5TU0nKSBBUyBcIkNSRUFURURfQVRcIiwgY291bnQoKikgQVMgXCJjb3VudFwiXG5GUk9NIFwiUFVCTElDXCIuXCJPUkRFUlNcIlxuTEVGVCBKT0lOIFwiUFVCTElDXCIuXCJQUk9EVUNUU1wiIFwiUFJPRFVDVFNfX3ZpYV9fUFJPRFVDVF9JRFwiIE9OIFwiUFVCTElDXCIuXCJPUkRFUlNcIi5cIlBST0RVQ1RfSURcIiA9IFwiUFJPRFVDVFNfX3ZpYV9fUFJPRFVDVF9JRFwiLlwiSURcIlxuR1JPVVAgQlkgXCJQUk9EVUNUU19fdmlhX19QUk9EVUNUX0lEXCIuXCJDQVRFR09SWVwiLCBwYXJzZWRhdGV0aW1lKGZvcm1hdGRhdGV0aW1lKFwiUFVCTElDXCIuXCJPUkRFUlNcIi5cIkNSRUFURURfQVRcIiwgJ3l5eXlNTScpLCAneXl5eU1NJylcbk9SREVSIEJZIFwiUFJPRFVDVFNfX3ZpYV9fUFJPRFVDVF9JRFwiLlwiQ0FURUdPUllcIiBBU0MsIHBhcnNlZGF0ZXRpbWUoZm9ybWF0ZGF0ZXRpbWUoXCJQVUJMSUNcIi5cIk9SREVSU1wiLlwiQ1JFQVRFRF9BVFwiLCAneXl5eU1NJyksICd5eXl5TU0nKSBBU0MiLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sImRhdGFiYXNlIjo0fSwiZGlzcGxheSI6ImxpbmUiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsiZ3JhcGguZGltZW5zaW9ucyI6WyJDUkVBVEVEX0FUIiwiQ0FURUdPUlkiXSwiZ3JhcGgubWV0cmljcyI6WyJjb3VudCJdfSwib3JpZ2luYWxfY2FyZF9pZCI6Nzg4fQ==`

**Comment by ranquild** [comment]
@flamber please have a look at the updated fix. Legend items are still clickable but a click won't do anything.

**Review by flamber — COMMENTED** [review]
@ranquild It doesn't create a dirty question anymore, but it's sending two requests on every click, which can change the visualization type and causes the question to get into a semi-dirty state where it shows the "Save" button, but the URL is still `/question/123`

Can we somehow just not do anything on click if it is not easily possible to remove the link?

https://user-images.githubusercontent.com/1447303/140918409-96b57817-2331-4c2b-8b59-eac7bda1fb02.mp4

**Comment by ranquild** [comment]
> Can we somehow just not do anything on click if it is not easily possible to remove the link?
@flamber Changed it to work exactly like this, please have a look.

**Review by flamber — APPROVED** [review]
Awesome!

**Comment by ranquild** [comment]
@metabase-bot backport release-x.41.x

**Pull request merged**
