### PR TITLE
BigQuery driver: make #standardsql flag case-insenitive to match actual

### PR DESCRIPTION
**Pull request by tlrobinson**
Include in 0.23.0

### CODE REVIEW

**Comment by camsaul** [comment]
I fixed that failing test already in master and the release branch so this LGTM

**Comment by tlrobinson** [comment]
If you fixed it in the release branch shouldn't this pass?

**Comment by camsaul** [comment]
The last CI run of the release branch passed https://circleci.com/gh/metabase/metabase/10294

**Comment by camsaul** [comment]
what commit did you branch off of

**Comment by tlrobinson** [comment]
Oh derp, nevermind, it doesn't get merged before CI runs it.

**Pull request merged**
