### PR TITLE
Remove -Xverify:none since it has no effect anymore with Java >= 13

### PR DESCRIPTION
**Pull request by ariya**
https://bugs.openjdk.java.net/browse/JDK-8214731

### CODE REVIEW

**Comment by ariya** [comment]
Hmm, looks like there are numerious execution failures (see [be-linter-cloverage failure](https://app.circleci.com/pipelines/github/metabase/metabase/11187/workflows/562ae42b-5419-46c4-832a-57f0ac8e9e34/jobs/404138), among others) which may indicate an actual Java bytecode verification error:

```
Syntax error (VerifyError) compiling new at (********/task/sync_databases_test.clj:143:1).
Operand stack underflow
Exception Details:
  Location:
    ********/task/sync_databases_test/MockJobExecutionContext.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; @8: areturn
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @8
    flags: { }
    locals: { '********/task/sync_databases_test/MockJobExecutionContext', 'java/lang/Object', 'java/lang/Object' }
    stack: { }
  Bytecode:
    0x0000000: 2a2b 2cb9 017b 0300 b0 
```

(Not sure what's going on here)

**Comment by dpsutton** [comment]
>  Running with these options enables execution of Java programs that violate the Java Virtual Machine Specification.

> Syntax error (VerifyError) compiling new at

**Comment by dpsutton** [comment]
https://ask.clojure.org/index.php/9943/defrecord-can-emit-invalid-bytecode

**Comment by dpsutton** [comment]
@ariya good job on thinking forward about this change and congratulations on finding your first compiler bug

**Comment by ariya** [comment]
> @ariya good job on thinking forward about this change and congratulations on finding your first compiler bug

Thanks for the super-speedy solution to this problem!

**Review by camsaul — APPROVED** [review]
awesome

**Pull request merged**
