### PR TITLE
round very small values to zero on the y axis

### LINKED ISSUE #9986: Float significant digits in auto y-axis range
Metabase: v0.32.5

When using auto y-axis value for float type, zero value is shown as: `-0.00000000018` as show in picture. 

It should be either 0 or a smaller number of digits.

Screen Shot 2019-05-16 at 10 53 37 AM

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #9986 

This PR fixes the issue by checking if a number is _very_ close to zero and if so replacing it with zero. I used [`Number.EPSILON`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON) as the cutoff.

Is there ever a time when we want to show values between `Number.EPSILON` and zero? If not, I'll just move this logic to `formatValue` where it could catch more cases and be tested more easily.

# Before

Screen Shot 2019-06-13 at 11 17 18 AM

# After

Screen Shot 2019-06-13 at 11 12 01 AM

### CODE REVIEW

**Comment by tlrobinson** [comment]
@salsakran @camsaul How do we feel about always rounding numbers between -2^-52 and 2^-52 to 0?

**Comment by camsaul** [comment]
I think for purposes of the y-axis formatting code it makes sense as log as the scale of the y-axis isn't microscopic.

I could see some legitimate cases where you're dealing with very small numbers (maybe some sort of sciencey stuff) so if the entire axis ranges from `±0.00000001` for example I don't think you'd want to be rounding stuff there to 0.

**Comment by tlrobinson** [comment]
Yeah, perhaps the epsilon should just be a function of the Y-axis range?

**Comment by paulrosenzweig** [comment]
Even if we pulled this into `formatValue`, the chart would use the unrounded value. However, I think with an axis range from ±0.00000001 (1E-8) you'd be unable to see `Number.EPSILON` (~2E-16) as distinct from zero.

Even if it can't be visualized, maybe it could be useful to keep the unrounded values just for display in tables? Though, if you're dealing with numbers this small, you're running up against the limits of floats. I feel like other things would break?

**Comment by paulrosenzweig** [comment]
> Yeah, perhaps the epsilon should just be a function of the Y-axis range?

👍 Definitely safest to keep it there for now, we can always move it to a more general place if the need arrises.

**Comment by tlrobinson** [comment]
@paulrosenzweig I meant maybe the epsilon we use should be derived from the min and max values of the Y axis rather than using `Number.EPSILON` directly. But I haven't really thought that through, and I think you're right about this being moot due to the limits of floating point numbers.

**Comment by paulrosenzweig** [comment]
Ah sorry I see what you were saying.

Yeah I'm not super clear on exactly what limits would be hit. Clearly there are some numbers represented in IEEE754 smaller than `Number.EPSILON`, but if there are _many_ numbers smaller than it, then maybe it's useful to be able to represent those on a y axis?

**Comment by paulrosenzweig** [comment]
I stand corrected! There can be totally legit charts where all the values are tiny. This PR as is breaks the y-axis labels. I'll make epsilon a function of the y-range as you suggest.

image

I think there's still some danger here since if the y values each had 1 added to them, they'd suddenly become equal to eachother. That potential issue doesn't really affect this though, and we can deal with other small number issues as they arise rather than just prevent small numbers from being graphable.

**Review by tlrobinson — APPROVED** [review]

**Pull request merged**
