### PR TITLE
Update devcontainer Dockerile

### PR DESCRIPTION
**Pull request by Somtom**
### Description

While running VSCode dev containers locally, I realized that it is actually broken. 
When comparing against the root Dockerfile, I saw that the versions are different.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Open the repo in VSCode and start a devcontainer
2. Run the Task: Run Build Task command

### Checklist

~~- [ ] Tests have been added/updated to cover changes in this PR~~

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
> I realized that it is actually broken.

Broken as in "doesn't even start"?

**Comment by Somtom** [comment]
>Broken as in "doesn't even start"?

Yes exactly.
Last messages before it breaks was a complain about 
`css-loader@1.0.1" has incorrect peer dependency "webpack@^4.0.0".`

**Comment by nemanjaglumac** [comment]
> Yes exactly. Last messages before it breaks was a complain about `css-loader@1.0.1" has incorrect peer dependency "webpack@^4.0.0".`

That particular error has nothing to do with this being broken. We're seeing it on every local build. Unfortunately, that's just the wonderful world of JavaScript dependencies, and us being locked in extremely old version of one package.

**Comment by Somtom** [comment]
Ah sorry I actually should have provided the other logs as well. I first read its an error but it was actually a warning 🤦 . 
I quickly reran things on the old master. Here is the trace:

```
[cljs] Error building classpath. Failed to read artifact descriptor for org.opensaml:opensaml-saml-api:jar:4.2.0
[cljs] org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.opensaml:opensaml-saml-api:jar:4.2.0
[cljs]  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:306)
[cljs]  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
[cljs]  at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
[cljs]  at clojure.tools.deps.alpha.extensions.maven$read_descriptor.invokeStatic(maven.clj:115)
[cljs]  at clojure.tools.deps.alpha.extensions.maven$fn__1128.invokeStatic(maven.clj:143)
[cljs]  at clojure.tools.deps.alpha.extensions.maven$fn__1128.invoke(maven.clj:143)
[cljs]  at clojure.lang.MultiFn.invoke(MultiFn.java:244)
[cljs]  at clojure.tools.deps.alpha$expand_deps$children_task__771$fn__773$fn__774.invoke(alpha.clj:405)
[cljs]  at clojure.tools.deps.alpha.util.concurrent$submit_task$task__479.invoke(concurrent.clj:35)
[cljs]  at clojure.lang.AFn.call(AFn.java:18)
[cljs]  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[cljs]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[cljs]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[cljs]  at java.base/java.lang.Thread.run(Thread.java:829)
[cljs] Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact io.dropwizard.metrics:metrics-parent:pom:4.2.9 from/to central (https://repo1.maven.org/maven2): /home/vscode/.m2/repository/io/dropwizard/metrics/metrics-parent/4.2.9/metrics-parent-4.2.9.pom.part (No such file or directory)
[cljs]  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:176)
[cljs]  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:222)
[cljs]  at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1077)
[cljs]  at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:853)
[cljs]  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:344)
[cljs]  at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:1306)
[cljs]  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:481)
[cljs]  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:437)
[cljs]  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:252)
[cljs]  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:297)
[cljs]  ... 13 more
[cljs] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.dropwizard.metrics:metrics-parent:pom:4.2.9 from/to central (https://repo1.maven.org/maven2): /home/vscode/.m2/repository/io/dropwizard/metrics/metrics-parent/4.2.9/metrics-parent-4.2.9.pom.part (No such file or directory)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:425)
[cljs]  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
[cljs]  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
[cljs]  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:172)
[cljs]  ... 22 more
[cljs] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.dropwizard.metrics:metrics-parent:pom:4.2.9 from/to central (https://repo1.maven.org/maven2): /home/vscode/.m2/repository/io/dropwizard/metrics/metrics-parent/4.2.9/metrics-parent-4.2.9.pom.part (No such file or directory)
[cljs]  at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
[cljs]  at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
[cljs]  at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:628)
[cljs]  at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
[cljs]  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514)
[cljs]  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
[cljs]  ... 25 more
[cljs] Caused by: java.io.FileNotFoundException: /home/vscode/.m2/repository/io/dropwizard/metrics/metrics-parent/4.2.9/metrics-parent-4.2.9.pom.part (No such file or directory)
[cljs]  at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
[cljs]  at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[cljs]  at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:163)
[cljs]  at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:151)
[cljs]  at org.eclipse.aether.internal.impl.DefaultFileProcessor.move(DefaultFileProcessor.java:252)
[cljs]  at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:482)
[cljs]  at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
[cljs]  ... 30 more
error Command failed with exit code 1.
```

**Review by dragonsahead — APPROVED** [review]

**Pull request merged**
