### PR TITLE
exception for none and block

### LINKED ISSUE #24380: False warning that `No self-service` means higher access than `Block` permissions
**Describe the bug**
In our **current permissions model**, `Block` permissions override `No Self-service`. However, the UI will warn you if you try to block a certain user group that also has "No Self-service" permissions set elsewhere.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
_You will need an EE version for this_
1. As an admin create a new group "Test"
2. Set data access to `No Self-service` for "All Users"
3. Go to the data permissions for the Test group and set their permissions to `Block`
4. You will see an exclamation mark icon. If you hover it, it will warn you that "All Users" group has higher access, which is not true **in the current permissions model**
image

**Expected behavior**
Remove the warning as long as permissions work in a non-linear and non-additive fashion. Meaning that "No self-service" cannot trump "Block" permissions.

**Severity**
Misleading and can set wrong expectations.

**Additional context**
[We're updating docs in order to underline how things currently work](https://github.com/metabase/metabase/pull/24277).

### PR DESCRIPTION
**Pull request by jeff-bruemmer**
Fixes https://github.com/metabase/metabase/issues/24380

image

Adds a conditional to `hasGreaterPermissions` function to account for a scenario where the logic of the `PERM_LEVELS` ordering fails. With this fix, the warning shown above will NOT appear when the all users default group permission is set to "No self-service" (`"none"`), and the value being set is `"block"`.

### CODE REVIEW

**Review by howonlee — APPROVED** [review]
this one is actually probably better, I think, just copy-paste the test I wrote on the other PR

**Comment by nemanjaglumac** [comment]
@jeff-bruemmer 
Does `block` overrule the download permissions?

In this case, "All users" has "No self-service" and "1 million rows" set for download.
image

**Review by nemanjaglumac — APPROVED** [review]
👌

**Comment by jeff-bruemmer** [comment]
Just noting for the future; the code here will need to be refactored to handle the situation @nemanjaglumac mentioned above. For each download permission check, we'll need to check if the current group's data permission is set to block. We can tackle this fix in a future PR.

**Pull request merged**
