### PR TITLE
Update SAML link

### PR DESCRIPTION
**Pull request by mkopinsky**

### CODE REVIEW

**Comment by mazameli** [comment]
Thanks for the contribution! Would you mind [signing our CLA](https://docs.google.com/a/metabase.com/forms/d/e/1FAIpQLSfc9GWyJ3F9U_4NzHLeTblgtog1FKtG3CjLshE4FAAKSdvNoQ/viewform) please so we can merge this?

**Comment by mkopinsky** [comment]
The MR template said the CLA wasn't necessary for minor documentation things, which is why I didn't sign initially.

I'm checking with my boss on whether I'm allowed to sign a CLA for things I do on company time. Sigh.

**Comment by mkopinsky** [comment]
Signed

**Review by mazameli — APPROVED** [review]
Thanks, Michael! The CLA bot is complaining, but I verified your signature is in our records.

**Pull request merged**
