### PR TITLE
Mongo native queries [WIP]

### PR DESCRIPTION
**Pull request by camsaul**
Since everybody polled prefered the Mongo Aggregation Pipeline as the native option here it is.

Implements #2072.

(Supercedes #2534)

### CODE REVIEW

**Comment by camsaul** [comment]
Actually I need to make a UI change for this. Mongo Aggregation Pipeline queries have to be ran against a certain collection. So we need to adjust the dropdown for Mongo native queries to select DB + Collection instead of just DB. 

😢

**Comment by camsaul** [comment]
@tlrobinson if you get a chance it would be cool if you could help me figure out how to make the Table selection code less wonky for MongoDB native queries. I have everything wired up & working but the Table picker is just a `DataSelector` that I've faked out by passing an it array of Tables and pretending they're DBs.

screen shot 2016-05-04 at 7 35 42 pm

**Comment by tlrobinson** [comment]
Ok I pushed a less hacky version. If we want to merge them into a single widget like we have in the gui query builder that would be possible but a bit more work.

**Comment by camsaul** [comment]
@tlrobinson Thanks 👍

**Comment by toszter** [comment]
Loving this!  I thought it was abandoned in #2072.  Phew! Glad it's not. :)

**Pull request merged**
