### PR TITLE
More Instrumentation

### PR DESCRIPTION
**Pull request by agilliland**
implements #1591 , implements #1592 , implements #1593 , implements #1594 , implements #1595 , implements #1596

### CODE REVIEW

**Comment by agilliland** [comment]
@tlrobinson @kdoh check this out for the instrumentation updates.

it seemed that the only reasonably scalable way to go forward with adding tracking in a lot of the places we wanted was to overload the anchor tag so that we could attach an analytics event to it.  i'm not super stoked about overloading such a low level and critical html tag, but its working fine for me and seems simple enough.

**Comment by tlrobinson** [comment]
Seems reasonable, though instead of a special `functions` prop I'd probably just use the standard `onClick` so the API is identical to the `<a>` tag, and I don't think we need to support an array of functions.

Also is there a reason you're using the old school Component API rather than an ES6 class?

**Comment by agilliland** [comment]
sure, that makes sense.  i'll tweak it back to use `onClick` instead of `functions`.  i'll fix it to use the ES6 class, it's just because i grabbed the first component i saw and copied it to start the new component, so it just happened to be an old component.

**Comment by kdoh** [comment]
My 2 cents is that this seems a bit confusing to look at. Seems like a more extensible way to handle this would be to wrap elements we want analytics on with a higher order component rather than use our own special A tag.

```
<Track event='event-name'>
  <a href="/some-path" onClick="handleModalClose">Derp Close the modal</a>
</Track>
```


<Track pseudo code to come - finding a link>

**Comment by agilliland** [comment]
The problem with that is we need the event to fire on a specific trigger, such as a click or something.  There is no easy way to do that in the structure you've given because there is nothing that connects the `<Track>` component with the click on a child element such as a button or a link.

**Comment by kdoh** [comment]
I think we should be able to hijack the click via that wrapping component, fire our analytics event and then have it do whatever it was gonna do. It would essentially involve creating a higher order component and cloning the child. https://facebook.github.io/react/docs/clone-with-props.html

**Comment by kdoh** [comment]
If that's too much or wouldn't work I'd maybe consider using the name ```<TrackedAction>``` or something more clear. My concern is the diff between an uppercase A and lower is small enough it'd be easy to forget which is which or accidentally switch them (also would help us in finding them later).

**Comment by tlrobinson** [comment]
I do agree with @kdoh that something like that would be nicer (and would work for any sort of clickable element, not just `<a>`)

It would be easy to do if we're ok with adding another DOM element, since both the child and parent receive the DOM events (use `onClickCapture` to ensure the child component can't `stopPropagation` before you get it), but adding another element isn't ideal (should it be `block` or `inline`, etc?)

There might be some other magic that would work though. I'll think about it.

**Comment by tlrobinson** [comment]
Another idea is just having a `click` event listener on the `<body>` that looks for a special property like `data-metabase-event`.

```
document.body.addEventListener("click", function(e) {
    var node = e.target;
    // check the target and all parent elements
    while (node && node.dataset) {
        if (node.dataset.metabaseEvent) {
            console.log("EVENT", node.dataset.metabaseEvent)
        }
        node = node.parentNode;
    }
}, true);
```

then do `<a href="..." data-metabase-event="whatever-event">whatever</a>`

**Comment by agilliland** [comment]
I suppose that makes things fairly simple, but then we have a function which would get called on every single click.  Probably simpler though because we don't need to mess with our anchor tags or create any new react components.

@tlrobinson , can you see any downsides to this approach?

**Comment by tlrobinson** [comment]
The only downsides I see:

1. As you mention, the function is called on every click, which I don't think is a big deal, since clicks are relatively infrequent, and the work done in it is fairly minimal.
2. Providing a `data-metabase-event` prop to a custom React component won't work unless that component passes it on to it's child HTML element, but usually we'll be using it with simple `<a>` or `<button>` or whatever.

**Comment by agilliland** [comment]
okay, this is g2g now if you want to take another peak at it.  I went with Tom's recommendation of using a click event listener when we wanted to add tracking on anchors and buttons.

**Comment by tlrobinson** [comment]
LGTM.

Minor enhancement: you could do something like `const parts = node.dataset.metabaseEvent.split(";").map(p => p.trim());` to make it less sensitive to whitespace.

**Pull request merged**
