### PR TITLE
fix #3105: Title in User guide page

### LINKED ISSUE #3105: #User Guide in start page in dox
think we're missing a space.

screen shot 2016-08-02 at 11 35 11 am
oc

### PR DESCRIPTION
**Pull request by mavimo**
Fix #3105
-  [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
  (unless it's a tiny documentation change).

### CODE REVIEW

**Comment by camsaul** [comment]
@metabase/core-developers This PR and #3106 / #3107 all look good to me, I've double-checked the HTML and they're all fixed as expected. Unfortunately since [GitHub doesn't let you change the target branch of a Pull request](https://github.com/isaacs/github/issues/18) if we accept these that means we'll have to wait for 0.20 before the fixes go live

**Comment by mavimo** [comment]
@camsaul I can change PRs target branch, what's the expected destination branch?

**Comment by salsakran** [comment]
@mavimo 
https://github.com/metabase/metabase/tree/release-0.19.1 is (hopefully) going out today

**Comment by camsaul** [comment]
@mavimo `release-0.19.1`. Since you'll have to open a new PR it might be faster just to combine this along with the two into a single PR and open that

**Comment by mavimo** [comment]
@camsaul ok, I'm doing it.

**Comment by mavimo** [comment]
https://github.com/metabase/metabase/pull/3124

**Pull request closed without merging**
