### PR TITLE
Cleanup archive page

### PR DESCRIPTION
**Pull request by tlrobinson**
* [x] hide "Unarchive" button for entities that don't have a `setArchived` action
* [x] fix Metric entity icon
* [x] add missing `setArchived` actions
  * [x] metric (need backend support?)
  * [x] segment (need backend support?)
* [ ] add missing `DELETE` endpoints
  * [ ] segment
  * [ ] metric
  * [ ] collection

before:

screenshot 2019-02-19 17 04 38

after:

screenshot 2019-02-19 17 04 19

### CODE REVIEW

**Comment by kdoh** [comment]
@tlrobinson https://github.com/metabase/metabase/pull/8820 might also be of interest to you.

**Comment by tlrobinson** [comment]
It looks like we're missing `DELETE` endpoints for collections, segments, and metrics. Do we want to add those before merging this?

**Comment by kdoh** [comment]
@tlrobinson one question I'd have with segments and metrics being deleted is since questions based on them currently still work when the segment / metric is "retired" is there a danger of old questions being broken if someone then goes in and does an actual `DELETE` on one of those?

If things don't break and it's not particularly involved it'd be preferable if the same, archive ->  can delete once archived behavior was the same for all non collection items before we merge.

Collections are a little funnier because right now we keep associations between a collection and its items so if you archive a collection the items get archived too, and if you unarchive it, everything goes back. So if you delete a collection do all its child items get deleted as well? I would say that makes sense but we probably want a little more confirmation on that (some indication of which things belonged to which collection would also be nice). So I think adding it for collections needs more thought and I wouldn't necessarily hold up the rest of this for that. 

I also happened to just find a bug / UX bugbear where you can unarchive a specific question that shows up in the archive having been part of an archived collection, and now it's back in business but you can't find it except by searching. And if you do go to it and click on the collection in the header, you go to the archived collection and there's no indication that anything is archived.

**Comment by tlrobinson** [comment]
@kdoh Deleting segments/metrics will break questions based on them, so we probably shouldn't allow that.

I think as is this branch is improvement over the existing state so I'd be inclined to merge and follow up with solutions for segments/metrics/collections in another PR if necessary, since neither will be trivial.

**Comment by kdoh** [comment]
That works for me. 👍

**Pull request merged**
