### PR TITLE
[SQL filters coverage] Group reproductions

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING CI && PENDING REVIEW

### What does this PR accomplish?
- Groups SQL filter related reproductions under one folder
- Separates each of the repros into individual files (1 file per repro)
    - This makes it much easier to grep/find and to read/review

### Questions:
- Some of these repros are now covered by the SQL filters test matrix. Do we still want to keep the individual repros, anyway?

### CODE REVIEW

**Review by flamber — APPROVED** [review]
I'm guessing this is just reordering. If the new matrix covers some issues, then specific tests for those issues can be removed, since matrix is preferred because it covers more.
But removal of tests should be done in separate PR.

**Review by gusaiani — COMMENTED** [review]
+1000 to breaking up test files that were over 700 loc.

Even knowing this is how Cypress has been naming their repro files and describes recently, I would suggest we keep doing it our current way.

Github issue numbers, by themselves, tell us next to nothing about what we are trying to reproduce.

If we keep naming our files and describe functions according to what they are about (feature and so on), this should be a lot easier to understand at a glance.

Then, by keeping the `(metabase#githubIssueNumber)` pattern as appendicces to `describe` or `it` descriptions , if we want to learn more about the issue, we can go there.

**Comment by nemanjaglumac** [comment]
@gusaiani not sure I follow?

Do you mean not to break repros into separate files?
Or you want to say that we should add some short description to each of the file names?

**Comment by gusaiani** [comment]
@nemanjaglumac 

> Do you mean not to break repros into separate files?

Many 👍 to breaking up repros into separate files.

> Or you want to say that we should add some short description to each of the file names?

Yes, I believe we should add short descriptions to each of the file names.
And not use Github issue numbers in file names.

Also not name describes solely with Github issue numbers.
Instead, just name them like we've been doing.

**Comment by nemanjaglumac** [comment]
> Yes, I believe we should add short descriptions to each of the file names.
> And not use Github issue numbers in file names.

Issue numbers are convenient because they are unique.
 
> Also not name describes solely with Github issue numbers.

Test name itself contains all the info you need.

> Instead, just name them like we've been doing.

It was easy to name files before when we had only up to 10 files in a single folder/group. I cannot imagine having to come up with a unique short description for every single repro, and then having to think of (something?) for a describe block, only to then have a nice fill description of the issue in the test name.

Using issue numbers seems convenient for many reasons:
1. removes cognitive overload
2. improves grepping -> makes it extremely easy to find a file you need
3. makes it even more easy to find the issue by its number in GitHub (try to find some old issue using keywords)

Even if some repro fails in the CI, you will immediately see the issue number, and Ci also prints the name of the test where you'll have a full description of an issue.

In the end, as we improve our overall test matrix (coverage), the number of issues/reproductions will surely go down.
At some point, we will most likely start running (at least) two large sets of Cypress e2e tests:

1. smoke tests (test matrices, extended coverage using UI flow)
    - most likely as a nightly job
    - run them before merge in protected branches (`on:pull_request`)
2. reproductions (much faster as they use API in most of the cases)
    - run them on every single commit to receive a fast feedback (`on: push`)

**Comment by nemanjaglumac** [comment]
Not to mention how easy it is to find a specific repro from a Cypress GUI.

**Comment by gusaiani** [comment]
@nemanjaglumac 

🤔 And then the file names stay Github issue numbers forever?

Or when the issue is fixed, would we change the name of the e2e test file?

—

Dialectic:

From this logic, we name our feature files Github issues as well. They are unique and require no thinking to choose a name.
So we have component file 123456.jsx

Also, a bit of a stretch though:

We will be coupled with Github. 
Say Github falls in disgrace somehow.
We have to move our repo somewhere else.

———

Again, these are just my 2c here. I have no problem with trying it!

**Comment by nemanjaglumac** [comment]
> 🤔 And then the file names stay Github issue numbers forever?
> 
> Or when the issue is fixed, would we change the name of the e2e test file?

I don't see an issue of them staying GitHub issue numbers forever.

> 
> Dialectic:
> 
> From this logic, we name our feature files Github issues as well. They are unique and require no thinking to choose a name.
> So we have component file 123456.jsx

Not even remotely comparable, imo.
Repros **should represent** some highly specific edge cases, not to be confused with the regular test files (named as we did all along).
Also, reproductions represent the "reactive" approach of writing tests. We failed to cover something proactively and then we have to cover for that by writing a repro.

Ideally, our coverage should be so good that there are very few repros ever needed. The "main" test network covers and catches the regressions early on.

Let me reiterate that **every single reproduction** has very detailed test name.
I'd completely agree with your concern if we had to rely on an issue number only. But we don't so I don't see an issue here.

> Also, a bit of a stretch though:
> 
> We will be coupled with Github.
> Say Github falls in disgrace somehow.
> We have to move our repo somewhere else.

Valid, but extremely unlikely.
If that happens, we have some much bigger issues to worry about.

Also, the way to mitigate that apocalyptic scenario is to start using different nomenclature. Let's say we have to migrate to GitLab. I'd name new issues reproductions as `gitlab_12345.cy.spec.js`.

> Again, these are just my 2c here. I have no problem with trying it!

Same here. I have no problem with trying and sticking with whatever we as a team agree on. Let's take this offline.

These are all perfectly valid concerns.
Thank you for being vigilant, as always :)

**Pull request merged**
