### PR TITLE
Bump Redshift driver to 2.1.0.12

### PR DESCRIPTION
**Pull request by dragonsahead**
Seems there were a few fixes in the latest version

### CODE REVIEW

**Comment by paoliniluis** [comment]
There's something that changed here clearly: 

```
expected: [{:base_type :type/Decimal,
            :database_type "numeric",
            :name "case_when_numeric_inc_nulls"}
           {:base_type :type/Text, :database_type "varchar", :name "raw_null"}
           {:base_type :type/Text, :database_type "varchar", :name "raw_var"}]
  actual: ({:base_type :type/Decimal,
            :database_type "numeric",
            :name "case_when_numeric_inc_nulls"}
           {:base_type :type/Text, :database_type "varchar", :name "raw_null"}
           {:base_type :type/Text,
            :database_type "character varying(5)",
            :name "raw_var"})
    diff: - [nil nil {:database_type "varchar"}]
          + [nil nil {:database_type "character varying(5)"}]
```

**Comment by john-metabase** [comment]
@paoliniluis sorry, I dropped this review. Do you want me to look at the errors?

**Comment by paoliniluis** [comment]
@john-metabase if you want to continue this PR, feel free to do so, as the error clearly shows that something has changed from the Redshift side and returns something that we're not expecting

**Comment by paoliniluis** [comment]
Hey @markbastian, leaving this PR to you

**Pull request closed without merging**
