### PR TITLE
Redux QB

### PR DESCRIPTION
**Pull request by agilliland**
Convert QB over to redux.

The goal here was to make the conversion with as few changes to the actual React components as possible, so there will definitely still be another round of updates needed.

I looked into doing this via ReduxRouter but there were complications with all the custom url updating and history management that was rather icky when trying to keep it in sync between Angular and Redux, so in the end I think it's easiest to hold off that bit until we actually make ReduxRouter the route handler for the app.

TODO:
- [x] visualization not updating on window resize
- [x] visualization not updating on data ref toggle
- [x] native editor mode seems to lag behind the most recent db choice
- [x] native editor is a bit laggy on update (tries to update query on every keystroke 😞 )

### CODE REVIEW

**Comment by agilliland** [comment]
@tlrobinson take a look at this whenever you have some time and we can talk through what's here.  i'm not wedded to anything here, it's just what was easiest for me as I was working on this.

**Comment by tlrobinson** [comment]
The main thing is I'd like to have this use the global Redux store and React router.

- Put the Query Builder reducer here: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/app.js#L88
- Angular routes here (this will eventually go away): https://github.com/metabase/metabase/blob/master/frontend/src/metabase/app.js#L123
- React routes here: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/Routes.jsx#L17

Ideally we'd start using the same Metadata store we're using in the dashboard filters branch but we need to merge that branch first.

**Comment by agilliland** [comment]
Yeah, so I started out using the global redux store but found that it created a number of complications so I backed off a little bit and decided on this approach which I consider as an in between step.  

The main problem I kept running into is that currently we are using Angular as the true authority on the app and its routes and then we have redux jerry rigged to sit on top of Angular with some code which bridges between the two.  With the QB there is a fair amount of code related to manual route manipulation and custom history tracking which was consistently causing issues when trying to keep it consistent between angular and redux router, so rather than keep trying to force that issue I am skipping over it, which I think makes the most sense.

My actual preference for the overall Angular -> Redux migration would be that we 1) finish moving any code that still uses an Angular controller over to using its own Redux store (the QB is the majority of this work remaining), then 2) remove Angular as the core of the app and make Redux + ReduxRouter the actual core, and finally 3) consolidate all of the individual Redux stores together into a global store and remove any redundancies.

With the QB migrated to its own redux store the remaining work to move angular to redux is pretty minimal.  Probably only a couple of days of work.

**Comment by agilliland** [comment]
@tlrobinson let me know if you want to do anything else on this branch.  i think everything is functional and ready to merge.  

i figure that in terms of the best way to organize our Redux code that it's probably easiest to tweak that once angular is completely gone and we are using a global redux store for all of the app.

**Comment by tlrobinson** [comment]
LGTM.

**Pull request merged**
