### PR TITLE
Update path to deployment file

### PR DESCRIPTION
**Pull request by marketingnerds**

### CODE REVIEW

**Comment by camsaul** [comment]
@salsakran are these pages automatically updated by the script that builds the documentation? Otherwise we should add this to the release checklist 💔

**Comment by salsakran** [comment]
these are NOT automatically updated =(

similar to the raw tags in SQL template docs, we should choose between having the docs read well on https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-metabase-on-elastic-beanstalk.md vs metabase.com/docs.

I *think* we should point people to mb.com/docs and replace explicit version numbers with {{version}} which is the jekyll tag that will emit he correct version number.

**Comment by camsaul** [comment]
Cool, I was digging through PRs and it seems we get these regularly (#3022 was essentially the same thing) so we should definitely consider an approach that will keep things up-to-date.

**Comment by camsaul** [comment]
@salsakran Should we go ahead and merge this and then open an issue to have the change the docs or script so we don't run into this problem in the future?

**Comment by salsakran** [comment]
👍

**Comment by camsaul** [comment]
I'm going to go ahead and merge this and then open an issue to have the change the docs or script so we don't run into this problem in the future

**Comment by camsaul** [comment]
@marketingnerds thanks for your contribution!

**Pull request merged**
