### PR TITLE
Static hourglass indicator when reduced motion is preferred

### LINKED ISSUE #18191: Improve loading spinner visual when under `reduce-motion`
Currently the loading spinner, when `prefers-reduce-motion` is enabled, is the spinner, but frozen.

Users can be confused by that visual.

An alternative that's been mentioned is using an hourglass icon.

### PR DESCRIPTION
**Pull request by ariya**
The rotating spinner is replaced by a static hourglass icon.

How to verify:

1. Make sure to enable [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences)
2. Do something that takes time, e.g. ask a question, click on X-ray etc

**Before this PR**

The loading is still an arc (supposed to be spinning, as the visual cue).

**After this PR**

The loading indicator is a static hourglass icon.

image

### CODE REVIEW

**Review by flamber — APPROVED** [review]
:hourglass: :tada:

**Review by mazameli — APPROVED** [review]
I like it!

**Review by alxnddr — APPROVED** [review]
👍

**Comment by ariya** [comment]
> I like it!

Thank you @mazameli for the SVG icon!

**Pull request merged**
