### PR TITLE
Fix: Create api token modal now shows error from backend 

### LINKED ISSUE #47552: Generating API token with same name gives an empty input
### Describe the bug

In admin interface, if you try to generate an API token with the same name as an already existing one, you will get an empty input field (instead of expected token or error saying "name already exists" or similar). See video.

https://github.com/user-attachments/assets/4ef02ef1-0b9d-420a-b5a5-faf7a0e6d952

### To Reproduce

1. Go to 'Admin settings > Authentication'.
2. Click on 'Manage' under 'API Keys' section.
3. Click on 'Create API key' and fill in a name and pick a user group. Create the token.
4. Again, click on 'Create API key' and fill in the same name and pick a user group. Create the token.
4. The input field will not contain token, but instead just be empty.

### Expected behavior

Show user an error saying that the name of the token already exists and can therefore not be created.

### Logs

Network response:

```
POST: 400 Bad Request
errors : {name: "An API key with this name already exists."}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-08-29",
      "tag": "v0.50.23",
      "hash": "7040ff1"
    },
    "settings": {
      "report-timezone": "Europe/Stockholm"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5 (Debian 15.5-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.10.0-linuxkit",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}
```

### Severity

low - bad user experience

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by antonhedstrom**
For example if name is taken. 

Closes https://github.com/metabase/metabase/issues/47552

### Description

The modal for creating an API token didn't take into consideration whether the request was successful or not. If we got an error from backend, the next step (showing the API token) was shown (independent of if a token was generated or not).

This change now renders the error message coming from backend, if any. Giving the user a chance to change the name and try again. 

Remaning issue: The submit button still says "Success" (with green background) for a few seconds, even if there was an error. 

I also took the opportunity to disable the submit button if the request is in the air (i.e. `response.isLoading`)

### How to verify

1. Go to 'Admin settings -> Authentication'
2. Click "Manage" button in the 'API token' section.
3. Click "Create API Key" and generate a token with name "Foo".
4. Again, click "Create API Key" and generate another token with the same name, "Foo".
5. The error message should now show up next to the Submit button saying: "An API key with this name already exists."  

### Demo

image

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by rafpaf** [comment]
Thank you, @antonhedstrom. I've moved your code along with a tweak from me into this PR: https://github.com/metabase/metabase/pull/51395

**Comment by rafpaf** [comment]
Closing this in favor of #51395. @antonhedstrom, thank you for your perceptiveness. And your hard work on this. When this merges, your name will be on the commit. I'll be a co-author, to facilitate `git blame`'ing.

**Comment by rafpaf** [comment]
I regret having to stamp this with a red badge. It's not stoplight red - it's a bullfighter red. It means go. We'll be using your code.

**Comment by antonhedstrom** [comment]
> Closing this in favor of #51395. @antonhedstrom, thank you for your perceptiveness. And your hard work on this. When this merges, your name will be on the commit. I'll be a co-author, to facilitate `git blame`'ing.

Hehe that is not a big deal for me, the UX is more important :) I noticed that there was a request for a test or two, but that will be handled in the new PR then I guess? Do you want me to take a look on that?

**Pull request closed without merging**
