### PR TITLE
add jest for front-end component testing

### PR DESCRIPTION
**Pull request by kdoh**
I've been wanting to do a better job of testing our front-end components outside of our e2e tests which are nice but expensive, so I spent a little time this afternoon poking at a possible solution.

I'm interested in trying out [Jest](https://facebook.github.io/jest/) for a couple reasons:

1. the [snapshot testing](https://facebook.github.io/jest/blog/2016/07/27/jest-14.html) feature could help us get to a reasonably large amount of test coverage with relatively low effort and should hopefully help us cut down on the number of bugs produced due to changes in things like classNames or other more presentational aspects without having to write more expensive e2e tests and look at screenshot diffs and trace something back to a component.

2. it's got a really nice almost 0 setup dev experience for a pretty powerful test environment regardless of snapshotting which means we can also use tools like [enzyme](https://github.com/airbnb/enzyme) to do more robust testing if appropriate without having to fire up a full browser environment like we do currently.

There's a really nice post on the pros and cons of snapshot testing [here](http://benmccormick.org/2016/09/19/testing-with-jest-snapshots-first-impressions/).

I did a real quick set of tests for our `<Button>` component as examples. 

The tests ensure that a button:
- should have text in it.
- better damn well have an icon if you tell it to have one 
- adds the right button class if you say its a primary button

consider this more of a discussion than a PR that I intend to merge as-is. I'm open to moving where things live (I like specs next to components but that's just me), doing or not doing snapshots, or any combination of things, but I definitely would love to make it easier to add tests to our front-end code.

### CODE REVIEW

**Comment by tlrobinson** [comment]
👍 

I tried migrating our Karma tests to Jest awhile ago but there are bunch that seem to require a better DOM implementation than Jest provides. I'd definitely like to revisit that rather than adding a 3rd set of frontend tests.

I'm also +1 on moving specs next to implementation. Having them in a totally separate tree leads to a sort of "out of sight out of mind" situation.

**Comment by kdoh** [comment]
@tlrobinson Yeah I'd messed with Jest about a year ago but it was in a pretty funky state at the time. I don't know when you last tried but now that they include jsdom, default automocking to off, and changed the setup experience it seems much better now than it was (at least at first blush).

I'm mostly curious to get your thoughts on the idea of snapshot testing. I like it in principle but I could see the potential for it to cause some headaches.

**Comment by tlrobinson** [comment]
Fairly recently. JSDOM doesn't support SVG, so anything that tests dc.js visualizations is out.

Snapshot testing seems reasonable for small-ish components. I think it's worth trying.

**Comment by kdoh** [comment]
@tlrobinson / @salsakran Any thoughts on if / how we should move forward with this?

**Comment by TuckerWhitehouse** [comment]
You may want to take a look at https://github.com/storybooks/storyshots, uses your storybook stories for jest snapshot testing.

**Comment by kdoh** [comment]
I'd love to figure out a way forward with this or go ahead and close it in favor of some other approach if we can.

**Comment by tlrobinson** [comment]
I don't see any harm in merging it. I'm definitely interested in migrating to Jest.

Unfortunately I don't think we'll be able to migrate all of our Karma tests due to the lack of a full DOM, but maybe some of those tests can be re-written or done as E2E tests.

Can you fix the merge conflicts and add it to `/bin/ci` (basically copy the `run_step yarn run test` line)

**Comment by kdoh** [comment]
@tlrobinson Sounds like a plan!

**Pull request merged**
