### PR TITLE
[MLv2] Add `metabase.lib.binning` and add binning support for fields

### LINKED ISSUE #29705: [MLv2] Implement binning
Need the following:

- A way to set the `:binning` options for a `:field` ref or `:metadata/field` field metadata. For metadata I think it should be saved as a namespaced key like `::binning` or something that is never accessed outside of that namespace, see what we do for `:metadata/field` (column metadata) for join aliases and temporal bucketing in `metabase.lib.field` for example.
- Need a way to get the current binning options applied to a Field. Should this come back in `displayInfo()`?
- Need a way to remove binning options
- Need a way to see if a Field is allowed to be binned/info about what the allowed options are (figure out what the UI will need)
- `display-name` (for both `:field` refs and `:metadata/field`s) should include the fact that a column is binned (see screenshot below)
- When generating a ref with `lib.ref/ref`, make sure `:binning` options are included if present in the `:field/metadata`
- Binning should NOT be propagated to metadata/refs for the next stage of a query.

image

### PR DESCRIPTION
**Pull request by bshepherdson**
No `metabase.lib.js` wrapping yet. Fixes #29705.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30299)

### CODE REVIEW

**Review by snoe — APPROVED** [review]

**Review by metamben — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30299)* status: all files reviewed, 12 unresolved discussions (waiting on @bshepherdson)

*[a discussion](https://reviewable.io/reviews/metabase/metabase/30299#-NTk3sxpAhfJoqn4zx8j:-NTk3sxpAhfJoqn4zx8k:b-ojv1fy) (no related file):*
Will expressions binning be implemented in a separate PR?

___
___
*[`src/metabase/lib/binning.cljc` line 90 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjt0pO89f5gf9sxbZX:-NTjt0pO89f5gf9sxbZY:b-zfqvt2) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L90)):*
> ```Clojure
> 
> (def ^:private *numeric-binning-strategies
>   (delay (mapv with-binning-option-type
> ```

Why do we `delay`? Can't we compute this eagerly and use the value without wrapping it into a function?
___
*[`src/metabase/lib/binning.cljc` line 103 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjtFtJ0BkWaow47m-I:-NTjtFtJ0BkWaow47m-J:bwx3wxo) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L103)):*
> ```Clojure
> 
> (def ^:private *coordinate-binning-strategies
>   (delay
> ```

Why do we `delay`?
___
*[`src/metabase/lib/binning.cljc` line 113 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjtW8E7MNyxVjQXoHR:-NTjtW8FAuOVLsbMDlRm:bgrgh24) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L113)):*
> ```Clojure
> 
> (defn coordinate-binning-strategies
>   "List of binning options for coordinate fields (ie. latitude and longitude). These split the data into N ranges each a
> ```

I think mentioning "N" is confusing.



_Suggestion:_
```Clojure
 "List of binning options for coordinate fields (ie. latitude and longitude). These split the data into ranges, each a
```
___
*[`src/metabase/lib/binning.cljc` line 129 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjv1r367GuXxdCzPqp:-NTjv1r367GuXxdCzPqq:b-b1wxes) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L129)):*
> ```Clojure
>     (case strategy
>       :num-bins  (i18n/trun "{0} bin" "{0} bins" num-bins)
>       :bin-width (str bin-width (when (isa? (:semantic_type field-metadata) :type/Coordinate)
> ```

Now I wonder if and how we should make sure this is consistent with the type `:metabase.lib.types.constants/coordinate`.
___
*[`src/metabase/lib/field.cljc` line 308 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjyyO18sRK7XClUs7v:-NTjyyO18sRK7XClUs7w:b-gx0lw1) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/field.cljc#L308)):*
> ```Clojure
>      (assoc options :binning binning)
>      (dissoc options :binning))
>    id-or-name])
> ```

I suppose this should be done by `update-options`. (I wonder if we should change `update-option` so that it removes the key instead of associng `nil` with it.)
___
*[`src/metabase/lib/field.cljc` line 314 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjz_bwAc7k1eGVT9kD:-NTjz_bwAc7k1eGVT9kE:b-o7hxd5) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/field.cljc#L314)):*
> ```Clojure
>   (if binning
>     (assoc  metadata ::binning binning)
>     (dissoc metadata ::binning)))
> ```

This could be handled by `update-options` too, and then the implementations for `:field` and `:metadata/field` would be the same.
___
*[`src/metabase/lib/field.cljc` line 325 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk-ILL5Y2XPNc6MLP1:-NTk-ILL5Y2XPNc6MLP2:b8b5lw5) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/field.cljc#L325)):*
> ```Clojure
>         {min-value :min max-value :max} (get-in fingerprint [:type :type/Number])]
>     (cond
>       ;; TODO: Include the time and date binning strategies too; see metabase.api.table/assoc-field-dimension-options.
> ```

Is there a separate GH issue for this?
___
*[`src/metabase/lib/schema/binning.cljc` line 18 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk0oc80Q7ZQINYBGOj:-NTk0oc80Q7ZQINYBGOk:bll4bus) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/schema/binning.cljc#L18)):*
> ```Clojure
>    [:map
>     [:strategy  [:ref ::binning-strategies]]
>     [:bin-width {:optional true} number?]
> ```

Do negative and zero widths make sense?
___
*[`src/metabase/lib/schema/binning.cljc` line 20 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk1wMuEI9TYn-lFjNq:-NTk1wMuEI9TYn-lFjNr:bk9x4q4) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/schema/binning.cljc#L20)):*
> ```Clojure
>     [:bin-width {:optional true} number?]
>     [:num-bins  {:optional true} ::lib.schema.common/int-greater-than-zero]]
>    [:fn {:error/message ":bin-width or :num-bins must be provided, matching the :strategy"}
> ```

For completeness this should mention `:default` too.
___
*[`src/metabase/lib/schema/binning.cljc` line 29 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk300eE_Mumzw-KwaW:-NTk300eE_Mumzw-KwaX:bemtod3) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/schema/binning.cljc#L29)):*
> ```Clojure
>    [:lib/type [:= :metabase.lib.binning/binning-option]]
>    [:display_name :string]
>    [:mbql [:maybe [:map [:binning ::binning]]]]
> ```

In what situations can `:mbql` be missing?
___
*[`test/metabase/lib/field_test.cljc` line 252 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk5PGW1BYbzw80BXQV:-NTk5PGW1BYbzw80BXQW:bvuool3) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/test/metabase/lib/field_test.cljc#L252)):*
> ```Clojure
>           :let                  [field-metadata (lib.metadata/field meta/metadata-provider "PUBLIC" "ORDERS" "SUBTOTAL")]
>           [what x]              {"column metadata" field-metadata
>                                  "field ref"       (lib/ref field-metadata)}
> ```

Why are these in the loop?



_Code quote:_
```Clojure
          :let                  [field-metadata (lib.metadata/field meta/metadata-provider "PUBLIC" "ORDERS" "SUBTOTAL")]
          [what x]              {"column metadata" field-metadata
                                 "field ref"       (lib/ref field-metadata)}
```

**Review by bshepherdson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30299)* status: all files reviewed, 9 unresolved discussions (waiting on @metamben)

*[a discussion](https://reviewable.io/reviews/metabase/metabase/30299#-NTk3sxpAhfJoqn4zx8j:-NU3QkGl59xfQZJ3muCn:b-hkmc1l) (no related file):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Will expressions binning be implemented in a separate PR?
</blockquote></details>

Is that a thing? I was cribbing from temporal bucketing, and that doesn't apply there. But if you can bin an expression (within the same stage where it's defined) that'll need fixing. It actually doesn't seem to work correctly on Stats right now, though the UI is mostly there.

___
___
*[`src/metabase/lib/binning.cljc` line 90 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjt0pO89f5gf9sxbZX:-NU2AlWx-gVM6d7NrTNI:bkqtpja) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L90)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Why do we `delay`? Can't we compute this eagerly and use the value without wrapping it into a function?
</blockquote></details>

There's no `i18n/deferred-tru` in the CLJC i18n lib, so the CLJS tests fail at compilation time. That's probably a solvable infrastructure issue but that's out of scope here.
___
*[`src/metabase/lib/binning.cljc` line 103 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjtFtJ0BkWaow47m-I:-NU2B6u0CKeOgf_7SJN9:b-q64pkt) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L103)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Why do we `delay`?
</blockquote></details>

See above.
___
*[`src/metabase/lib/binning.cljc` line 113 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjtW8E7MNyxVjQXoHR:-NU2BakNEXkDUwTwEoXK:b-896fix) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L113)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

I think mentioning "N" is confusing.
</blockquote></details>

Done.
___
*[`src/metabase/lib/binning.cljc` line 129 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjv1r367GuXxdCzPqp:-NU2D9zp5oWxYnJNH-Ev:be3nxs1) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L129)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Now I wonder if and how we should make sure this is consistent with the type `:metabase.lib.types.constants/coordinate`.
</blockquote></details>

Isn't it consistent? `::coordinate` maps to `{:semantic-type [:type/Coordinate]}`, which tracks with this.

If you mean "how do we keep them in sync", I'm not sure about that.
___
*[`src/metabase/lib/field.cljc` line 308 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjyyO18sRK7XClUs7v:-NU2NkZZ9ZFSau2YN5aG:blyo0ln) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/field.cljc#L308)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

I suppose this should be done by `update-options`. (I wonder if we should change `update-option` so that it removes the key instead of associng `nil` with it.)
</blockquote></details>

Done by adding `u/assoc-dissoc`, and now this is `(lib.options/update-options field-clause u/assoc-dissoc :binning binning)` etc.
___
*[`src/metabase/lib/field.cljc` line 325 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk-ILL5Y2XPNc6MLP1:-NU3P3On1X9qSQW6UPF0:b77dmf3) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/field.cljc#L325)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Is there a separate GH issue for this?
</blockquote></details>

No, and I'm also not sure whether this really applies, since the temporal bucketing was already handled in another PR.
___
*[`src/metabase/lib/schema/binning.cljc` line 18 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk0oc80Q7ZQINYBGOj:-NU3PnSd4mClPBWfMIdV:b-hdsm88) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/schema/binning.cljc#L18)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Do negative and zero widths make sense?
</blockquote></details>

No they don't. Done. 
___
*[`src/metabase/lib/schema/binning.cljc` line 20 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk1wMuEI9TYn-lFjNq:-NU3PlxP1OxUB54D0Qu1:b-896fix) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/schema/binning.cljc#L20)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

For completeness this should mention `:default` too.
</blockquote></details>

Done.
___
*[`src/metabase/lib/schema/binning.cljc` line 29 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk300eE_Mumzw-KwaW:-NU3PyvVA9ri-hitdkp9:busjq8x) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/schema/binning.cljc#L29)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

In what situations can `:mbql` be missing?
</blockquote></details>

If this option is `Don't bin`. That's a `::binning-option` too.
___
*[`test/metabase/lib/field_test.cljc` line 252 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk5PGW1BYbzw80BXQV:-NU3QBBi-7VZJDz_1jwJ:b8x9wge) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/test/metabase/lib/field_test.cljc#L252)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Why are these in the loop?
</blockquote></details>

Because we want to check that it works for both `column metadata` directly, and for `lib/ref`s to the field. The RHS is written as a map, but it's really a seq of pairs.

**Review by metamben — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30299)* status: all files reviewed, 6 unresolved discussions (waiting on @bshepherdson)

*[a discussion](https://reviewable.io/reviews/metabase/metabase/30299#-NTk3sxpAhfJoqn4zx8j:-NU3Xm7821p-H4hP8E-2:be4s6vh) (no related file):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Is that a thing? I was cribbing from temporal bucketing, and that doesn't apply there. But if you can bin an expression (within the same stage where it's defined) that'll need fixing. It actually doesn't seem to work correctly on Stats right now, though the UI is mostly there.
</blockquote></details>

I guess it should work. I'm not saying it should be implemented in this PR.

___
___
*[`src/metabase/lib/binning.cljc` line 90 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjt0pO89f5gf9sxbZX:-NU3Y6AIDc7YWCtW_2Vf:boqqvxh) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L90)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

There's no `i18n/deferred-tru` in the CLJC i18n lib, so the CLJS tests fail at compilation time. That's probably a solvable infrastructure issue but that's out of scope here.
</blockquote></details>

When working on temporal bucketing, I implemented the display name calculation in the `display-name-method`.
___
*[`src/metabase/lib/binning.cljc` line 129 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjv1r367GuXxdCzPqp:-NU3YgeI4wjWtPNLnhSy:bscxq2w) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/binning.cljc#L129)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Isn't it consistent? `::coordinate` maps to `{:semantic-type [:type/Coordinate]}`, which tracks with this.

If you mean "how do we keep them in sync", I'm not sure about that.
</blockquote></details>

If we wanted to keep them consistent (in sync), we should probably use the functions defined in `metabase.lib.types.isa`.
___
*[`src/metabase/lib/field.cljc` line 308 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTjyyO18sRK7XClUs7v:-NU3Z9So6abWyJCIyP1M:b-8fx2u7) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/field.cljc#L308)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Done by adding `u/assoc-dissoc`, and now this is `(lib.options/update-options field-clause u/assoc-dissoc :binning binning)` etc.
</blockquote></details>

:+1: 
___
*[`src/metabase/lib/field.cljc` line 325 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk-ILL5Y2XPNc6MLP1:-NU3ZTEU0bJdpjXky5pj:bwv8yd7) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/src/metabase/lib/field.cljc#L325)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

No, and I'm also not sure whether this really applies, since the temporal bucketing was already handled in another PR.
</blockquote></details>

Hmm. I'm a bit confused. I'm not sure if binning and bucketing should be merged.
___
*[`test/metabase/lib/field_test.cljc` line 252 at r2](https://reviewable.io/reviews/metabase/metabase/30299#-NTk5PGW1BYbzw80BXQV:-NU3_XfP3eCNU3hyEuAP:b-2w11ti) ([raw file](https://github.com/metabase/metabase/blob/1d9c8a52f0e6f5f785af8a5db297383b7e70f216/test/metabase/lib/field_test.cljc#L252)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

Because we want to check that it works for both `column metadata` directly, and for `lib/ref`s to the field. The RHS is written as a map, but it's really a seq of pairs.
</blockquote></details>

I still can't see why that `:let` couldn't be a `let` outside of the `doseq`.

**Review by metamben — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30299)* status: all files reviewed, 7 unresolved discussions (waiting on @bshepherdson)

*[a discussion](https://reviewable.io/reviews/metabase/metabase/30299#-NU7n9XzBP6vnYD2u4mo:-NU7n9XzBP6vnYD2u4mp:bfz7rvo) (no related file):*
Since @camsaul's camelCase, kebab-case PR has been merged, this PR has to be updated.

___

**Review by metamben — COMMENTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30299)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @bshepherdson)

**Pull request merged**
