### PR TITLE
Add search to popovers in the data model

### LINKED ISSUE #2805: Add a search box for foreign key target dropdown in Data Model
When mapping Foreign Keys in the schema editor the user is presented with a list of tables which can be very long in some cases. I propose to make a simple change and add a filtering option or at least a way to jump to a certain alphabetic group by using the keyboard. See an example of the problem:

### PR DESCRIPTION
**Pull request by mazameli**
WIP PR to add search to currency, FK mapping, and special type popovers.

Fixes #2805.

### CODE REVIEW

**Comment by mazameli** [comment]
@kdoh, since you asked, it looks like the current status of this is that it adds search to the foreign key mapping dropdown, but not to the special type dropdown. IIRC, @tlrobinson had run into a problem when trying to implement this real quick where it was only able to do one or the other for some reason.

image

image

I don't believe this PR _adds_ search for currencies on the data model page, but does fix an annoying bug where opening that dropdown scrolls you to the top of the page:

image

**Comment by tlrobinson** [comment]
I took a look at this, the main issue with adding search to the special type picker is that that uses the `LegacySelect` component (takes `options` prop) rather than newer `BrowserSelect` (uses children `Option` elements), which is the only one that supports search currently. It would be easy enough to switch the special type picker to use `BrowserSelect`, except that doesn't support sections.

We should really consolidate those. I think it would also make sense to use `AccordianList` which support, sections, searching, and virtualized list, so we wouldn't have to duplicate all that in `Select`.

**Comment by RMMSecurity** [comment]
@mazameli I can't even begin to thank you. This solves a major pain point I had since I am dealing with literally thousands of FKs.  

Ctrl+F will pick up some of the names on the left side so it was really a messy problem this resolves nicely. Can't wait to see this PR merged!   🙂

**Comment by RMMSecurity** [comment]
Any traction on this?

I noticed some formatting problems with text wrapping as shown here:

image

**Comment by flamber** [comment]
@RMMSecurity I think once #11522 has landed, then it would be very easy to enable search on dropdowns that needs it.

**Comment by RMMSecurity** [comment]
Another thing to note is Field Type:

image

I'd expect that to reflect the currently selected FK

**Comment by mazameli** [comment]
Closing this PR in favor of https://github.com/metabase/metabase/pull/11522, which will indeed allow for search in the data model popover menus.

**Comment by RMMSecurity** [comment]
@mazameli Just want to add that #11522 did not add in search to data model popover menus unless I'm missing something just FYI. At least not from a clean checkout of master

**Comment by mazameli** [comment]
@RMMSecurity yeah, thanks for the ping — I was just realizing this yesterday. #11522 was a refactor of our `<Select>` component, which _allows_ for search in those popovers, but which didn't actually implement them in those popovers. I'll see if I can whip a PR together.

**Comment by mazameli** [comment]
This is being implemented over here now instead: https://github.com/metabase/metabase/pull/11912

**Pull request closed without merging**
