### PR TITLE
add a very short delay to throttle test to try and avoid intermittent failures

### LINKED ISSUE #1352: fix throttle unit test, which fails intermittently
not happening super often, but the unit test in `metabase.api.common.throttle-test` fails randomly

### PR DESCRIPTION
**Pull request by agilliland**
resolves #1352

### CODE REVIEW

**Comment by camsaul** [comment]
The throttle stuff has stayed pretty stable since we wrote it. This might be a good candidate for spinning off into a separate library. Deploying stuff on [Clojars](https://clojars.org/) is super easy, I think this could be spun of as its own project in an hour or so.

###### Pros

*  Faster CI times & more focused codebase
*  Cool potential blog post
*  Other people might use the lib and contribute fixes 

###### Cons

*  Overhead of maintaining another project. For this since it basically hasn't changed since we wrote it that overhead is pretty small

**Comment by camsaul** [comment]
like seriously no more intermittent test failures

**Comment by camsaul** [comment]
if this beezy was a separate lib. I can make it one in 20 mins #kanye

**Comment by agilliland** [comment]
lets do it! :+1:

**Pull request merged**
