### PR TITLE
Fix QB error image paths

### LINKED ISSUE #9405: Images specified in CSS files aren't rendering correctly
Images specified in our CSS such as the "No Results" illustration are currently not rendering. Changing ` background-image: url("../app/assets/img/no_results.svg");` to `background-image: url("../assets/img/no_results.svg");` appears to fix this, but it's currently unclear why this broke.

**Example:**

image

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #9405

### CODE REVIEW

**Review by mazameli — CHANGES_REQUESTED** [review]
Hmm I'm still not seeing the No Results image. 

screen shot 2019-02-11 at 3 14 40 pm

screen shot 2019-02-11 at 3 14 49 pm

**Comment by RMMSecurity** [comment]
> Hmm I'm still not seeing the No Results image.

Works for me? Also on 1a1832f

image

**Comment by kdoh** [comment]
Odd. Spinning up the branch with and going to a no results query also gets me to a missing image like @mazameli.

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
I found that running this branch with `yarn run build` instead of `yarn run build-hot` got the image to show up correctly.

**Comment by tlrobinson** [comment]
Ah, so I think what happened is we fixed it for the "build-hot" awhile ago, which broke normal builds That's also probably why we didn't notice for so long. We should investigate more and try to fix for both.

**Comment by tlrobinson** [comment]
Doesn't seem like there's an easy way to fix this in both cases. We could move them out of the CSS though.

**Pull request merged**
