### PR TITLE
Erroring question page nits

### PR DESCRIPTION
**Pull request by howonlee**
These are the nits which Maz picked out with respect to the erroring question page, or at least the ones that haven't been whacked yet
1. Indicates to end user what the current running state is. Given the many orders of magnitude in DB query run times I think something robust and non-ephemeral is necessary here (looking at some sort of expanded QE model) but Maz suggested expedient method and I took it
2. No more left nav on the table page
3. Page heading for table page
4. Independent scroll-x behavior on the table
5. Styling for the error section on the table page
6. Select-all component. Note that the interaction behavior with pagination is fiddly.
7. Coalescing default behavior for Our Analytics collection (default collection) and null number of dashboards
8. Rename `error name` to `error content` search

### CODE REVIEW

**Comment by alxnddr** [comment]
@howonlee rerun all question works duplicates questions:
<video src="https://user-images.githubusercontent.com/14301985/136105543-05b3fb5c-7f1f-4f1b-8691-908f46fcfaa7.mov" />

**Comment by alxnddr** [comment]
searching "Our analytics" collection does not work:
<video src="https://user-images.githubusercontent.com/14301985/136105844-b54f2181-bbe6-4f52-bae9-a98ef0b4bb63.mov" />

**Comment by howonlee** [comment]
> @howonlee rerun all question works duplicates questions:
> 
>  Screen.Recording.2021-10-06.at.00.30.35.mov

I ripped out the previous rerunning questions functionality and thought I put the previous one back in because of a ridiculous action-at-a-distance bug: apparently not. willfix

**Comment by howonlee** [comment]
> When I select only one question, select all checkbox becomes selected: Screen Shot 2021-10-06 at 00 38 21

I thought this was intended behavior? click on it to deselect everything

**Comment by alxnddr** [comment]
> I thought this was intended behavior? click on it to deselect everything

Usually, in interfaces, it keeps being unchecked until you select all items manually. If users want to deselect everything, they can click twice. I think this is a minor issue

**Comment by alxnddr** [comment]
I manually changed the page size in the code to test the pagination here. 
<video src="https://user-images.githubusercontent.com/14301985/136107577-407801f9-29da-430e-aa5e-74fd5517e256.mov" />

Selected rows are stored by indices in `rowChecked` which does not work well with pagination. Are rows unique by a question id? It would be better to use unique ids. For instance, we can pass a prop `selectedKeyColumn` to find the column and use its values as unique ids

**Review by alxnddr — COMMENTED** [review]
Nice fixes, looks way better for users! I left a couple of comments and suggestions about issues I found. Please tell if you need any help with that

**Comment by mazameli** [comment]
I'm not sure why, but I'm periodically not seeing any results in the list when I should, even after multiple refreshes:
https://share.getcloudapp.com/P8uGn4gY

**Comment by mazameli** [comment]
> I thought this was intended behavior? click on it to deselect everything

I agree with @howonlee here. The current select-all/none behavior feels right to me (and matches gmail's behavior fwiw).

**Comment by howonlee** [comment]
> > I thought this was intended behavior? click on it to deselect everything
> 
> I agree with @howonlee here. The current select-all/none behavior feels right to me (and matches gmail's behavior fwiw).

gmail's exact behavior, there is also a faded indicator for partial selections

**Comment by mazameli** [comment]
@howonlee I took care of some additional styling here if you want to merge it into this branch: https://github.com/metabase/metabase/pull/18272

**Review by alxnddr — APPROVED** [review]
Good job 👍

**Pull request merged**
