### PR TITLE
🤖 backported "Much better collection permission performance"

### PR DESCRIPTION
**Pull request by github-automation-metabase**
#46942

This was a painful backport, because some
previous very relevant changes hadn't been backported. So there are some
changes from the original, non-backported, commit:

- removed all support for getting the trash collection, getting things
that were `archived_directly`, or getting collections by
`archive_operation_id`. None of these exist in this branch.

- in this branch, functions like
`permissions-set->visible-collection-ids` did not check for archived
status or anything other than permissions. On `master`, they do. So, the
new function that replaced them,
`collection/visible-collection-filter-clause`, also checks for archived
status as well as permissions. To resolve this, I chose to just default
`collection/visible-collection-filter-clause` to ignore archived status
and return both archived and unarchived collections.

  > [!IMPORTANT]
  > Manual conflict resolution is required.
  Checkout the branch and run `./backport.sh` script. Force push your changes after cherry-picking.

### CODE REVIEW

**Review by johnswanson — CHANGES_REQUESTED** [review]
Note to self: need to include https://github.com/metabase/metabase/pull/47324 before merging.

**Review by johnswanson — APPROVED** [review]

**Comment by johnswanson** [comment]
@noahmoss would you be able to take a quick pass on this and let me know if my changes from the original commit make sense?

Specifically, I:
- removed all support for the trash collection, `archived_directly`, and `archive_operation_id` (they don't exist in this branch), and
- default to returning all collections, whether archived or not, since that's what `permissions-set->visible-collection-ids` did in this branch

**Review by noahmoss — APPROVED** [review]
A little hard to tell which parts exactly are different from the version in master... but I skimmed through and nothing major jumped out at me so 👍

**Comment by qnkhuat** [comment]
We shouldn't have v51 migrations in a v50. Same reasons I commented [here](https://github.com/metabase/metabase/pull/47367#pullrequestreview-2267519967)

**Pull request merged**
