### PR TITLE
Reenable posting Slack subscriptions to private slack channels

### LINKED ISSUE #20867: New Slack App does not allow selecting private channels for pulses
**Is your feature request related to a problem? Please describe.**
With the old Slack bot integration it used to be possible to select a private channel for pulses in Slack. This option is now gone with the introduction of the new Slack App.

**Describe the solution you'd like**
We would like for it to, once again, be possible to select private channels when setting up a Slack pulse. 

**Describe alternatives you've considered**
A workaround was suggested in #2694 [here](https://github.com/metabase/metabase/issues/2694#issuecomment-653202849), but it seems a bit too bad, as this was possible with the old integration.

It has also been suggested to just make the text field free form, so private channels can be added directly by name (and then might just not exist). This solution would also work, but the UX of having them available in the dropdown as before seems nicer.

**How important is this feature to you?**
We do not use pulses for anything *but* posting to private channels, as it is only select people who needs the info. Right now we did the manual DB edit as in the workaround. It was historically also a very popular addition in #2694, so it seems like a lot of people will miss this option.

**Additional context**
I found that the decision to remove list of `private_channel` was made [here](https://github.com/metabase/metabase/pull/19499#discussion_r779060637). It was done to reduce the need of the scope `groups:read`, which is a bit too bad. I would like to note that this scope still only gives the app read access to private channels it has been added to. I verified this using the `conversations.list` endpoint. So the scope does not give excessive access to lots of unneeded information.

-----
Just thought I would raise this as its own issue, to show that we would very much like this option to still be available.

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #20867 

### How to test

<ol>
  <li>Go to http://localhost:3000/admin/settings/slack</li>
  <li>Click on "Create Slack app"</li>
  <li>Follow onscreen instructions until you get the OAuth Bot string</li>
  <li>Paste the OAuth Bot string in the Slack config page inside Metabase, select a channel to post to</li>
  <li>
    ⚠️ This is a temporary workaround for a separate issue Noah is looking at: in Slack, visit the channel or channels you wish to send Slack Subscriptions to.
  </li>
  <ol type="a">
    <li>In Slack, go to each channel you wish to post subscriptions to.</li>
    <li>Type `/add` until you see "Add Apps to this channel", and add the Metabase app to each channel
  </ol>
  <li>Visit a dashboard</li>
  <li>Click on the "Subscriptions" icon on the top right. It looks like an ✉️</li>
  <li>Click on "a private channel"</li>
  <li>Fill out the private channel name below the radio button</li>
  <li>Click on "Send to Slack now"</li>
  <li>Check your Slack channel. It should have gotten an update</li>
  <li>Set a subscription, say using "hourly". It should work for private channels.</li>
</ol>

#### Other things in this PR

Broke down a large file, was > 500 loc.
Fixed a couple of propTypes.

### CODE REVIEW

**Review by alxnddr — APPROVED** [review]
Codewise looks good, works as expected

**Comment by safvanplp** [comment]
Apologize for the lack of knowledge. Is this released already to the current version or it will be part of the next release? If it is released to the current version itself, how can I fix this? Should I download the executable again?

**Comment by flamber** [comment]
@safvanplp Follow the issue #20867, which gets a milestone attached, when closed - in this case 0.43.3 https://github.com/metabase/metabase/releases/tag/v0.43.3

**Comment by abhishek-superk** [comment]
Works great for dashboards, but don't see any change in setting alerts for a question. 
Sending dashboard subscriptions and question alerts should work the same, right?

**Comment by safvanplp** [comment]
Highlighting the same point that Abhishek has mentioned. Works perfectly for Dashboard Subscriptions, but not for Question Alerts. Please add this fix to alerts also.

**Pull request merged**
