### PR TITLE
Let people use comma-separated numbers in SQL num param inputs

### LINKED ISSUE #5457: Comma Separated Numbers In Number Field To Be Used With IN Operator
- Your browser and the version: Chrome 59
- Your operating system: OS X 10.12
- Your databases: Redshift
- Metabase version: 0.24.2
- Metabase hosting environment: Ubuntu
- Metabase internal database: Postgres

Recently upgraded from v0.22.2 to v0.24.2 bug is in 0.24.2. 

Previously user was able to enter a comma separated list of numbers into the ids_list field (variable type of number). Now, when entering a comma separated list of numbers only the first number shows in the results of the query.

 [[id IN ({{ids_list}})]]

e.g. If a user enters 10, 11 in the ids_list field the query will only return result for id 10. In v0.22.2 query would return aggregated results for id 10 and 11.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #5457
Includes test

### CODE REVIEW

**Comment by chenlingmin** [comment]
If I want separated str. How to do?

``` select * from T where str in ('a','b')```

**Comment by camsaul** [comment]
@chenlingmin we currently don't support doing comma-separated text like that but it's something we might add in the future

**Comment by camsaul** [comment]
#4728 is the relevant issue for tracking that

**Comment by ProgrammerFu** [comment]
@camsaul Is it supported now?

select * from T where str in ('a','b')

**Pull request merged**
