### PR TITLE
Conditional table formatting

### LINKED ISSUE #4121: Color table based on cell value - Feature request
It would be great to be able to somehow color the cells / rows of a table based on the values in the cell / row. 

Coloring of cells would be great for example to illustrate customer retention, like in the appended file. Coloring of rows, based on the value of one or more of the cells would be great to draw special attention to some of the rows, might this be best / worst performer in a set of coworkers / products.

Cell coloring should probably be a gradient between two values, or max / min in the set. Row colors could probably use the same gradient, or just a color if above / below a certain value.

This functionality is similar to conditional formatting in excel.

table1b

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves: #4121
Implements: #7122

TODO:

- [x] pivot table support
- [x] multiple column support
- [x] reorder rules
- [x] dial in single colors and color ranges (@mazameli)
- [x] finish tweaking settings panel reorganization
- [x] replace "back" button

This is looking great so far. Besides the overall coolness of the feature, I'm also loving the new section tabs for the modal, and the reordering of the rules feels great. I'm scheming already of ways to use some of these ideas to improve field reordering as well as showing/hiding fields, and bringing in fields from other tables.

Here's what I've found:

**Issues**
* [x] If I overwrite a question’s formatting via settings on a dash-card, the formatting rule doesn’t take effect. 
* [x] Weirdly, the collection picker is all screwed up in the save question modal

**The formatting itself**
* [x] The darkest colors still feel a little too dark, making the cell a bit rough to read. I think the darkest we want to go is maybe ~65% of the full stock colors.
* [x] Row highlight feels a bit too dark too. Let's knock that back to 20% of the full stock colors.

**Rules list panel**
* [x] I think new rules should go to the top of the stack rather than the bottom so that it’s not confusing why they’re not showing up
* [x] I don’t think my design choice to have the gradient/color behind the column name(s) for each rule box is working; it’s making things illegible. Can we do this instead?

**New rule settings**
* [x] The "Which columns should be affected?" dropdown should open right away when creating a new rule (not when editing an existing rule), to save you a click.
* [x] Let’s put some placeholder text in the column selector dropdown for when it’s empty so that its height doesn’t jump around: “Choose a column"
* [x] Below the “Rules will be applied in this order” heading let’s add a help sentence: “Click and drag to reorder"
* [x] There should be a cancel button when I'm creating or editing a rule.
* [x] “Smallest/largest value in the table” — two things on this: 1) it should say "column" rather than "table" (I forgot to update that in the designs). 2) The way you have it implemented currently, it looks at the smallest/largest value in all of the columns included in the rule. I feel like that should be a separate radio option that only appears if more than one column is selected, and that the default should be the smallest/largest value in each column. So the options would be, "Smallest/Largest value in each/this column," "Smallest/Largest value in all of these columns" (only available if more than one column is selected", and "Custom value."

**Gradient rules**
* [x] The selections in the gradients palette popover should have `cursor: pointer`
* [x] Color gradient palette should close after I make a selection
* [x] In other products, I've seen them provide two selections for each gradient type: one going from white to the color, the other going from the color to white. I'd like to add that for each of the colors we currently have. This could alternatively be handled by a toggle that says "flip color direction" or something, but I think that requires more thinking that just selecting the direction you want visually from a list. I've also added in a red-to-green/green-to-red option, and a red-yellow-green/green-yellow-red one; I think those will be common for good/bad status indicators.

**The modal itself**
* [x] The placement of the buttons for chart settings is something I’ve flip-flopped on a bit over the years, but I think they belong in the bottom-right. I was inconsistent in the designs on purpose originally, because I was concerned the "add rule" button wasn't going to be obvious enough. But I think it's okay if we do something like this (I've also changed the treatment of the reset to defaults button so it's not so bold and heinous):
* [x] Right now the whole modal scrolls. I would expect for only the left panel to scroll. This should be cleaner once the buttons are all clustered in the bottom-right, I hope.

### CODE REVIEW

**Comment by tlrobinson** [comment]
@mazameli there's a few bits remaining but feel free to start playing with this

**Comment by mazameli** [comment]
This is looking great so far. Besides the overall coolness of the feature, I'm also loving the new section tabs for the modal, and the reordering of the rules feels great. I'm scheming already of ways to use some of these ideas to improve field reordering as well as showing/hiding fields, and bringing in fields from other tables.

Here's what I've found:

**Issues**
* If I overwrite a question’s formatting via settings on a dash-card, the formatting rule doesn’t take effect. 

screen shot 2018-05-18 at 12 12 46 pm

* Weirdly, the collection picker is all screwed up in the save question modal:
screen shot 2018-05-18 at 12 35 13 pm

**The formatting itself**
* The darkest colors still feel a little too dark, making the cell a bit rough to read. I think the darkest we want to go is maybe ~65% of the full stock colors.
* Row highlight feels a bit too dark too. Let's knock that back to 20% of the full stock colors.

**Rules list panel**
* I think new rules should go to the top of the stack rather than the bottom so that it’s not confusing why they’re not showing up
* I don’t think my design choice to have the gradient/color behind the column name(s) for each rule box is working; it’s making things illegible. Can we do this instead?

screen shot 2018-05-18 at 2 48 20 pm

**New rule settings**
* The "Which columns should be affected?" dropdown should open right away when creating a new rule (not when editing an existing rule), to save you a click.
* Let’s put some placeholder text in the column selector dropdown for when it’s empty so that its height doesn’t jump around: “Choose a column"
* Below the “Rules will be applied in this order” heading let’s add a help sentence: “Click and drag to reorder"
* There should be a cancel button when I'm creating or editing a rule.
* “Smallest/largest value in the table” — two things on this: 1) it should say "column" rather than "table" (I forgot to update that in the designs). 2) The way you have it implemented currently, it looks at the smallest/largest value in all of the columns included in the rule. I feel like that should be a separate radio option that only appears if more than one column is selected, and that the default should be the smallest/largest value in each column. So the options would be, "Smallest/Largest value in each/this column," "Smallest/Largest value in all of these columns" (only available if more than one column is selected", and "Custom value."

**Gradient rules**
* The selections in the gradients palette popover should have `cursor: pointer`
* Color gradient palette should close after I make a selection
* In other products, I've seen them provide two selections for each gradient type: one going from white to the color, the other going from the color to white. I'd like to add that for each of the colors we currently have. This could alternatively be handled by a toggle that says "flip color direction" or something, but I think that requires more thinking that just selecting the direction you want visually from a list. I've also added in a red-to-green/green-to-red option, and a red-yellow-green/green-yellow-red one; I think those will be common for good/bad status indicators.

gradient palette


**The modal itself**
* The placement of the buttons for chart settings is something I’ve flip-flopped on a bit over the years, but I think they belong in the bottom-right. I was inconsistent in the designs on purpose originally, because I was concerned the "add rule" button wasn't going to be obvious enough. But I think it's okay if we do something like this (I've also changed the treatment of the reset to defaults button so it's not so bold and heinous):

color range
rules list

* Right now the whole modal scrolls. I would expect for only the left panel to scroll. This should be cleaner once the buttons are all clustered in the bottom-right, I hope.

**Comment by mazameli** [comment]
This looks great! The dash-card setting issue seems to be fixed, so I checked that off in the to-do list.

I am however still seeing this weirdness with the collection picker for newly saved questions:

screen shot 2018-05-25 at 4 53 55 pm

**Comment by salsakran** [comment]
@mazameli is that just in this branch or is it a general regression?

**Review by kdoh — APPROVED** [review]

**Comment by mazameli** [comment]
Not sure if this helps @tlrobinson, but I just ran the FE tests locally on this branch and got this:

screen shot 2018-05-30 at 1 39 17 pm

**Comment by mazameli** [comment]
@tlrobinson We should merge this puppy! (Once tests pass, that is… 😁 )

**Pull request merged**
