### PR TITLE
Enable and fix broken "edit history metadata" E2E tests

### PR DESCRIPTION
**Pull request by calherries**
I noticed an e2e test file that had the `.` in the wrong place.

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
Oh... that means these tests (added almost two years ago) NEVER ran! :(
And now they are failing.

Thanks for catching this @calherries 

I'll add @kulyk and @iethree who were working on this file

**Comment by kulyk** [comment]
😱 Great catch @calherries! I'll take a look at why the tests are failing

**Comment by kulyk** [comment]
@nemanjaglumac, the last commit should fix the tests; mind looking at this once again, please? Seems like the tests were written when we had modal forms for editing questions and dashboards title/description. I rewrote the test to use current flows for editing stuff

**Comment by iethree** [comment]
> 

(FYI, i'm only on git blame because I updated prettier)

**Comment by nemanjaglumac** [comment]
I can confirm tests are now fixed and are working as expected.
However, do we really need this to be E2E? Seems excessive and I'm inclined to remove the whole spec.

Especially since this FE unit spec exists that covers the same functionality:
https://github.com/metabase/metabase/blob/master/frontend/test/metabase/components/LastEditInfoLabel.unit.spec.js

**Review by nemanjaglumac — APPROVED** [review]
We can revisit the usefulness of this file separately (see [this comment](https://github.com/metabase/metabase/pull/27889#issuecomment-1416468037)).

**Pull request merged**
