### PR TITLE
Drill polish

### LINKED ISSUE #4667: Drill-Through Part 2 -- Polish
Splitting off polish + minor bugs off #4496 so we can merge + experiment with this. 

This will be the main tracking issue, and should include anything that is intended to happen by version 0.24

Sherpa: @salsakran 

### Feature To-dos
- [ ] Enable for visualizations on dashboards 
- [x] Replace Summarize for Raw Tables with 
   - common metrics (flattened, and limited to 5?)
   - count of TableName(plural) by time
   - sum of columns -> column picker???
- [ ] Visual design for drill-through options
- [x] Clicking on column header should let you get
    - min/max/avg of this column (if numeric)
    - sum of this column (if numeric)
    - sum of this column by time (if numeric)
    - distinct values of this column (if numeric)
    - count of rows pivoted by this column

 
### Bugs
- [ ] Click-through popover not working for maps on mobile

### Polish
- [ ] When clicking on a funnel, the target should be the line and not the bar

### Open-ended To-dos
- [ ] Decide on ordering of options 

### Open Questions
- How does this work in the context of permissions?
- How does this work wrt public links?

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #4667

Sherpa: @salsakran 

### Feature To-dos
- [ ] Replace Summarize for Raw Tables with 
   - [x] common metrics (flattened, and limited to 5?)
   - [x] count of TableName(plural) by time
   - [ ] sum of columns -> column picker???
- [x] Visual design for drill-through options
- [x] Clicking on column header should let you get
    - [x] min/max/avg of this column (if numeric)
    - [x] sum of this column (if numeric)
    - [x] sum of this column by time (if numeric)
    - [x] distinct values of this column (if numeric)
    - [x] count of rows pivoted by this column

 
### Bugs
- [ ] Click-through popover not working for maps on mobile

### Polish
- [ ] When clicking on a funnel, the target should be the line and not the bar

### Open-ended To-dos
- [x] Decide on ordering of options 

### Open Questions
- Can we make it more clear what the footer does? Currently there are no labels, and the addition of filters next to granularity makes what was simple (the connection of granularity to the time axis) confusing.
- How does this work in the context of permissions?
- How does this work wrt public links?

### CODE REVIEW

**Comment by salsakran** [comment]
@tlrobinson for some reason the column header doesn't come up when I click on a time column. eg the "created at" column of the orders table in the sample dataset.

**Comment by moumny** [comment]
May i suggest #3689 :)

**Comment by tlrobinson** [comment]
@salsakran How should `When clicking on a funnel, the target should be the line and not the bar` work?

Obviously the lines are 1px wide, thus hard to click. Should there just be a wider click target on top of the line (how wide? N pixels? 50%?), and have the popover be located on the line at the top of the funnel sections?

Should tooltips also be updated to use the same click/hover targets?

**Comment by mazameli** [comment]
Could the target be the _label_ for the step rather than the line?

**Comment by tlrobinson** [comment]
That's certainly possible, though I feel like the tooltips and click targets should probably match.

**Comment by mazameli** [comment]
Here's the latest on what we're thinking for the drill-through menu visual design. First, we'll table the right-click behavior (thanks for prototyping that, Tom). 

Here's the general pattern: every item that can be clicked on to drill through has 1–n rows of action groups, containing 1 or more actions, laid out horizontally. Each action group has an icon representing it, and every action is written out in text. The action menu should appear oriented such that the icon for the first action group is directly under the location of the mouse click. Action group rows have a hover effect, where the text is darker (I also have it bolder in the designs, but toggling boldness might make the text shimmy around). Hovering over the text of an action should turn it blue.

google menu copy 42

Here's what it would look like if you hovered off the card:

google menu copy 43

Hovering over a different row of actions:

google menu copy 41

Blue action item hover effect:

google menu copy 40

google menu copy 39

If the user selects a pivot action that requires the selection of a field, it would be great if we could present a limited initial list that could be expanded. Once we have the ability to prioritize dimensions for metrics, this menu should presumably have those first. Until then, this could be something dumb, like the first n location/time/category fields in the table, or something smarter like the most often used dimensions.

google menu copy 34

Expanded dimension menu:

google menu copy 33

Here are a couple more examples. Here's a table field heading. Note that the list of actions are slightly different from the list we've been working off of; @salsakran and I riffed on these last week.

column heading copy

Here's a primary key cell in a raw table. The last row of actions lets the user select from a list of dashboards or questions that can use this field+value as a filter parameter. Clicking on that dashboard/question in the list takes you to that item, filtered by the cell's value. (Is there ever a case where this would be ambiguous?)

raw table cell - pk copy 2

List of dashboards:

column heading v1 copy 18

**Comment by mazameli** [comment]
Random thought: have we figured out what to do if the user clicks on a multi-line chart on a point where the lines overlap? I.e., which series are they interacting with in that situation?

**Comment by tlrobinson** [comment]
Currently it will be whichever is on top (the last series, probably?), same as tooltips.

**Comment by mazameli** [comment]
Hmm, maybe this is overcomplicating things, but I wonder if in that scenario we'd want to let them pick the series they want to interact with first from a list. I can imagine users finding the current behavior being frustrating and arbitrary.

**Comment by salsakran** [comment]
I think it's overcomplicating things. Let's ship this and see if people actually run into this.

**Comment by mazameli** [comment]
Yeah, I'm with ya. Just seemed a little goofy.

**Comment by tlrobinson** [comment]
> The last row of actions lets the user select from a list of dashboards or questions that can use this field+value as a filter parameter. Clicking on that dashboard/question in the list takes you to that item, filtered by the cell's value. (Is there ever a case where this would be ambiguous?)

This isn't going to be trivial. Currently I think the only way to get the list of cards/dashboards filterable by a particular field is to load every card and dashboard and look at the all the parameters and queries.

**Comment by salsakran** [comment]
```
This isn't going to be trivial. Currently I think the only way to get the list of cards/dashboards filterable by a particular field is to load every card and dashboard and look at the all the parameters and queries.
```
this should probably be a backend api call, or at least hidden behind a lib clientside. 
We can punt if it's truly nasty. However, this is the sort of thing we want to be able to (easily) do.

**Comment by tlrobinson** [comment]
Paging @camsaul

**Comment by salsakran** [comment]
let's get everything but that wrapped up..

in general the drill-through menu should be thought of as extensible and malleable.

**Comment by salsakran** [comment]
Is the sort icon supposed to be on a diagonal? (on chrome, mac)

screen shot 2017-04-26 at 6 42 09 pm

**Comment by salsakran** [comment]
Can we return to "view <TableName>" instead of "View Rows"?  It feels a little more sterile and disconnected as "rows".

**Comment by mazameli** [comment]
- The margin-right on each action item in a row in the menu should be more like 30px. Right now it looks like 18px. Here's a detail from the designs:
screen shot 2017-04-26 at 10 06 15 pm


- Looks like we're not displaying dots on line charts broken out by quarter? Seems like we should; makes it easier to see that you can click on the point.

screen shot 2017-04-26 at 9 36 22 pm

- In Chrome, there's a funny twitching that happens when hovering on the drill through menu:
twitching-menu

- This breaks convention, but ideally I'd love to have the drill through menu open up directly on top of the clicked point (without the little triangle pointer emanating from the menu) rather than appearing above/below it. I think that would make it feel faster to click on the primary action. (Incidentally, I'm scheming to propose restyling all/most of our popup menus to not have the triangle pointer, and just appear on top of the originating item.)
- On a related note, we'll want to refine where the dimension/field picker appears; it current is pretty annoying how the most likely click (the first field in the list) ends up being far away from your last click. It would be great if it could also not have the pointer and originate from the location of the last click.
dimension-picker

- Should we show the menu at all when there's only one option, or just automatically do that action right away? I tend toward the latter.
screen shot 2017-04-26 at 10 01 56 pm

- When clicking to view the unaggregated rows on a cumulative count of rows, it feels like you'd expected to see all the rows accumulated up to that point rather than just the rows added on that date. It's weird to click on a y-axis point that's at like 237 and then click to see the rows and there are only 4 of them.

- This is about the granularity dropdowns rather than the action menu, but it's still weird to me that I can't select `All time` again after I make a selection on the time range.

- This pie sure places lots of orders.
screen shot 2017-04-26 at 10 03 24 pm

**Comment by mazameli** [comment]
> Is the sort icon supposed to be on a diagonal?

No, I'm assuming that's a placeholder. A new icon was supplied for this.

**Comment by tlrobinson** [comment]
Responding to your comments in a minute, but one thing I noticed was "Count of rows by COLUMN" for column headers was replaced with "Count by time" in the mockups. Count doesn't need a column as an argument, so I'm not sure it really makes sense to "count this column by time", but it does make sense to "count all rows by this column". What that intentional?

**Comment by tlrobinson** [comment]
> Is the sort icon supposed to be on a diagonal? (on chrome, mac)

fixed.

> Can we return to "view " instead of "View Rows"? It feels a little more sterile and disconnected as "rows".

I think previously it was "View this/these DISPLAY_NAMEs". "View" seems a little too ambiguous to me, but I can do whatever you prefer.

> The margin-right on each action item in a row in the menu should be more like 30px. Right now it looks like 18px

done

> Looks like we're not displaying dots on line charts broken out by quarter?

I'm pretty sure this is due to the logic we've had for at least a year that automatically hides the dots when they're too dense / too many are overlapping. Try setting the row limit to 10, for example. If you still think it's broken could we address it as a separate issue?

> In Chrome, there's a funny twitching that happens when hovering on the drill through menu:

Hmm, seems like that's due to the dots only showing when they're hovered. I could force the dot to be visible as long as the drill menu is showing for that particular dot, which I think would be nice anyway.

> This breaks convention, but ideally I'd love to have the drill through menu open up directly on top of the clicked point (without the little triangle pointer emanating from the menu) rather than appearing above/below it.

Personally I prefer having the triangle point at the target, especially in the case of click actions, since it's pointing to the actual "object" the action will apply to (except in some cases where the object may be large, like bars or area charts, then it uses the mouse event location).

The other big issue is what happens if the click is near the bottom or right edge of the screen, and forcing the top left as the anchor would clip it? Currently it prioritizes the top left, but if it won't fit it will flip it, which I think is a pretty good compromise.

> On a related note, we'll want to refine where the dimension/field picker appears; it current is pretty annoying how the most likely click (the first field in the list) ends up being far away from your last click. It would be great if it could also not have the pointer and originate from the location of the last click.

Yeah, that's annoying. I'm not sure what the correct solution is. We should probably use the same direction as long as the popover is open rather than jumping around based on the content and available size, but then if the click is near the bottom you'll have a very small popover showing a potentially long list.

Currently the popover picks the highest priority direction that fits the content, but instead we could have it pick the direction with more space regardless of content size. But that would defeat the purpose of the top-left priority I mentioned in the previous question.

> Should we show the menu at all when there's only one option, or just automatically do that action right away? I tend toward the latter.

That was implemented but I took it out while working on the new design, and I actually prefer the consistency of knowing a click will open a popover rather than possibly perform some action. If there were some visual indication that a click will immediately perform an action vs open the popover then I think we could do that though.

> When clicking to view the unaggregated rows on a cumulative count of rows, it feels like you'd expected to see all the rows accumulated up to that point rather than just the rows added on that date.

Hmm, yeah. I can add a special case for cumulative count/sum that does a `BEFORE` instead of `ON`. Actually, it would need to be an "on or before", since currently we're doing an `ON` of a bucketed field rather than a `BETWEEN` of two points in time. Blarggg.

> This is about the granularity dropdowns rather than the action menu, but it's still weird to me that I can't select All time again after I make a selection on the time range.

Would "all time" just be another operator, alongside "previous", "current", etc?

> This pie sure places lots of orders.

What do you suggest? Technically the pie does have orders, in database terms.

I think sometimes the current scheme makes sense ("View this User's Orders") and sometimes it doesn't ("View this Product's Orders" would be better as "View Orders with this Product" or something), but we need something that works for both cases.

**Comment by tlrobinson** [comment]
@salsakran or @mazameli, whoever wants to sherpa this, could you distill your feedback and my responses into concrete TODOs, please?

**Comment by mazameli** [comment]
> > This pie sure places lots of orders.

> What do you suggest? Technically the pie does have orders, in database terms.
 I think sometimes the current scheme makes sense ("View this User's Orders") and sometimes it doesn't ("View this Product's Orders" would be better as "View Orders with this Product" or something), but we need something that works for both cases.

Haha, yeah, I was mostly just joking around about how sometimes the arrangement leads to funny sentences like that one. I don't know if I can think of something better yet.

**Comment by mazameli** [comment]
> I think previously it was "View this/these DISPLAY_NAMEs". "View" seems a little too ambiguous to me, but I can do whatever you prefer.

Yeah, we've gone back and forth on this one a bit, but I agree with Tom that "View/See these `display_names`" is clearer than just "View" by itself.

> I'm pretty sure this is due to the logic we've had for at least a year that automatically hides the dots when they're too dense / too many are overlapping. Try setting the row limit to 10, for example. If you still think it's broken could we address it as a separate issue?

Yeah, I'll break this out (or slice and dice it? :trollface:) into a separate issue. On further inspection I think it's a bug having to do with broken out series.

> Hmm, seems like that's due to the dots only showing when they're hovered. I could force the dot to be visible as long as the drill menu is showing for that particular dot, which I think would be nice anyway.

If we decide to maintain the behavior where the menu appears below the click instead of on top of it, then I'd be in favor of what you suggest here. If we cover the point, it's a moot… point. 😎 

> Personally I prefer having the triangle point at the target, especially in the case of click actions, since it's pointing to the actual "object" the action will apply to (except in some cases where the object may be large, like bars or area charts, then it uses the mouse event location). The other big issue is what happens if the click is near the bottom or right edge of the screen, and forcing the top left as the anchor would clip it? Currently it prioritizes the top left, but if it won't fit it will flip it, which I think is a pretty good compromise.

IDK, I think the menu originating on top of the click is just as clear (think Android style menus), and more convenient in terms of click targets. As for the positioning problem, I guess I don't see that as a big deal: we'd just try to get the menu as close to the click target as possible, and if that would clip it we just move it back into the viewport with like 30px of margin from the edge of the window.

> We should probably use the same direction as long as the popover is open rather than jumping around based on the content and available size, but then if the click is near the bottom you'll have a very small popover showing a potentially long list.

Yeah you raise a good point re: cases when it's near the bottom. I think we'll need reasonable min/max heights for the dimension list, and in the exceptions where the proximity of the menu to the edge causes a problem, we just suck it up and scoot the menu upwards. Then the majority of cases work more preferably but we still fallback gracefully. I think that's preferable to a super tiny scrolling menu — even one that's idealistically placed.

> Should we show the menu at all when there's only one option, or just automatically do that action right away? I tend toward the latter.

I can't think of every possible situation where there's only a single action, but for the positive cases like an ID click-through to the detail, I think that the blue hover effect to communicate that _something_ will happen might be natural enough. 

>> When clicking to view the unaggregated rows on a cumulative count of rows, it feels like you'd expected to see all the rows accumulated up to that point rather than just the rows added on that date.

> Hmm, yeah. I can add a special case for cumulative count/sum that does a BEFORE instead of ON. Actually, it would need to be an "on or before", since currently we're doing an ON of a bucketed field rather than a BETWEEN of two points in time. Blarggg.

Paging @salsakran to weigh in on how important this is.

> Would "all time" just be another operator, alongside "previous", "current", etc?

Yeah, that seems the most obvious option to me.


> > This pie sure places lots of orders.

> What do you suggest? Technically the pie does have orders, in database terms.
 I think sometimes the current scheme makes sense ("View this User's Orders") and sometimes it doesn't ("View this Product's Orders" would be better as "View Orders with this Product" or something), but we need something that works for both cases.

Haha, yeah, I was mostly just joking around about how sometimes the arrangement leads to funny sentences like that one. I don't know if I can think of something better yet.

**Comment by mazameli** [comment]
And to my understanding, @salsakran remains the head sherpa on this.

**Comment by salsakran** [comment]
`I think previously it was "View this/these DISPLAY_NAMEs".`
I liked this version. Not sure why we changed it.

**Comment by salsakran** [comment]
`Would "all time" just be another operator, alongside "previous", "current", etc?`

"All time" would set the filter to null (and be displayed if there's no time filter on that dimension)

**Comment by salsakran** [comment]
Imo the above two issues are clear minor fixes that make things feel nicer.

The other main flow breaking step is the dimension selector design + the click path to get to the top. 

Everything else is valid, but I'd rather clean these three issues and see how things feel. My hunch is that it'd be quite nice/shippable at that point.

**Comment by salsakran** [comment]
The next big bucket of smoothing will be actions + making sure that you end up in a usable state. Eg, I've often done a pivot action and ended up on a "select fields" prompt which is pretty lame.

**Comment by tlrobinson** [comment]
Alright, I've

1. Change the "underlying records" title back to "View this/these TABLE NAME"
2. Added an "All Time" option for the timeseries menu
3. Set the popover to use the initial attachment (usually top left) and not jump around.

Anything else important?

**Review by salsakran — APPROVED** [review]
#MergeIT

**Comment by salsakran** [comment]
any further polish items will be cataloged separately

**Pull request merged**
