### PR TITLE
Fix:Native question filter widget reordering doesn't work #9357

### LINKED ISSUE #9357: Native question filter widget reordering doesn't work
Hi all,

In the latest version,

Raw question filters have handles, but they do not work: 
you can move the filter, but when dropped, it comes back to its first place.

Is it intended behaviour ?

Best regards,

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by sunui**
A spelling mistake ? #9357

### CODE REVIEW

**Comment by flamber** [comment]
Hi @sunui 
Nice catch! :clap: It fixes the reordering.
Do you how to add a [Cypress test](https://github.com/metabase/metabase/wiki/E2E-Tests-with-Cypress) to [native.cy.spec.js](https://github.com/metabase/metabase/blob/master/frontend/test/metabase/scenarios/question/native.cy.spec.js), so this issue doesn't return?

**Comment by sunui** [comment]
@flamber Done

**Comment by Nathlmt** [comment]
Any news on this?

**Comment by nemanjaglumac** [comment]
Hi @sunui, thank you so much for your contribution! ❤️
I know it's long overdue but can I please ask you to rebase this branch on `release-x.38.x`? A lot has changed since May 2020 so let's make sure this still works. I can help with Cypress if needed.

**Comment by nemanjaglumac** [comment]
Closing in favor of https://github.com/metabase/metabase/pull/14952.

- Rebased on `release-x.38.x`
- Solved merge conflict
- Updated repro

**Pull request closed without merging**
