### PR TITLE
Separate positive / negative stacked charts

### LINKED ISSUE #5763: Separate positive / negative stacked bar charts
I'm trying to achieve a specific kind of stacked bar chart for an active user graph separated out by retained, created, resurrected (positive) and lost (negative) like:

image

The way Metabase works is that it kind of draws the negative over the positive bars. It makes mathematical sense, but I don't really see why you would ever want that.

Is there a way to make Metabase draw a graph like the above?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/5763

**What**
Customizes DC stack behaviour by providing a custom D3-like `stack` layout, which can position tracks separately. Unfortunately the original D3 `stack` cannot be customized without copying and modifying `stack` function.

**Alternatives**
This behavior is supported out of the box with "d3": "^4.9"`. We can:
1. Merge this PR and do not upgrade `dc` and `d3`
2. Merge this PR, upgrade the libs and remove the custom `stack`
3. Close this PR without merging, upgrade the libs and enable native `stackOffsetDiverging`.

**How to test**
Follow the steps from the cypress test. You should be able to see negative bars stacked separately below `0`, and not on top of positive ones.

Screen Shot 2021-09-23 at 2 20 18 pm

### CODE REVIEW

**Comment by ranquild** [comment]
@mazameli Could you have a look? This PR modifies stacking behaviour across our charts to support negative values.

**Comment by mazameli** [comment]
@ranquild yep! I'll give it a look.

**Review by mazameli — CHANGES_REQUESTED** [review]
1. I am seeing negative values incorrectly getting tucked under positive ones in a weird way. See this recording: https://share.getcloudapp.com/7KuEr1X5
2. I really think for any chart that has values that go below 0, we need to make sure the 0 axis line stands out. It's really hard to read in its current form. Here's a screenshot of the current state followed by a mockup of a desired state. The significant differences in the mockup are that the 0-axis is dark, and on top of the visualization, and there is no dark bottom x-axis line, but instead a normal dashed, lighter axis line (at the -150 mark in the case of this example mockup).

### Screenshot

image

### Desired

image

3. I'm seeing the value labels for negative bars showing up weirdly in the middle of the bar. I'd expect them to show up at the bottom of the bar. Here's what I'm currently seeing:

image

**Comment by ranquild** [comment]
1st one is fixed, working on the 3rd bullet point

**Review by mazameli — CHANGES_REQUESTED** [review]
This is looking very good and almost there. Two detail polish items:

1. Can we please have the color of the restyled 0-axis line in this scenario be `#B9BBC2` (which is the color of the "normal" 0 x-axis line).
2. In the state where there are negative values, can the bottom line of the chart be _dashed_ and the light gray color, instead of being dark gray?

See this mockup based on your screenshot to see how I'd prefer it to appear:

image

**Comment by ranquild** [comment]
@mazameli 

1. The stroke color of the normal X axis should be currently the same as for `0` line:
Screen Shot 2021-09-24 at 9 59 04 pm

2. Changed the color of the axis for stacked charts, should be the same as you described, please have a look

**Review by mazameli — APPROVED** [review]
I'm seeing one last thing, but I think it can be fixed as a follow-on unless it's quick. So I'm going to approve this, 'cause I don't think what I'm seeing is blocking; it's pretty subtle.

But the issue is that there appears to be a missing x-axis line for the second-to-last mark now:

image

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Comment by alxnddr** [comment]
@ranquild we have just a couple of visual tests of visualizations, and it would be so great if you could add a test for this feature 🙏

**Review by alxnddr — APPROVED** [review]
This is great 🙌

**Pull request merged**
