### PR TITLE
Ensure we are paginating resultsets

### LINKED ISSUE #18455: Exporting large amount of data with PostgreSQL result in OutOfMemory
**Describe the bug**
When exporting a large amount of data with PostgresSQL, the export fails because the JVM ran out of memory.

**Logs**
```
2021-10-14 07:57:51,724 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 33,
 :started_at #t "2021-10-14T07:57:31.810839Z[UTC]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__80178.invoke(execute.clj:480)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:477)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:472)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
    "driver.sql_jdbc$eval82150$fn__82151.invoke(sql_jdbc.clj:54)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__58611.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__57638.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__58590.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__57025.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__58897.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__61001.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__56085.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__51786.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__51619.invoke(annotate.clj:615)"
    "query_processor.middleware.permissions$check_query_permissions$fn__57495.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__59812.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__57727.invoke(cumulative_aggregations.clj:60)"
    "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__61961.invoke(row_level_restrictions.clj:338)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__61219.invoke(visualization_settings.clj:62)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__60153.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__60474.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__55625.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__58546.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__58519.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__54895.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__57799.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__56480.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__57280.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__55258.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__55495.invoke(add_implicit_clauses.clj:147)"
    "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__61961.invoke(row_level_restrictions.clj:338)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__60928.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__55802.invoke(add_source_metadata.clj:123)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__61446.invoke(column_level_perms_check.clj:30)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__60014.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__56024.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__57335.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__59788.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__57389.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__58191.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__55817.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__60867.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__60031$fn__60035.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__60031.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__58439.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__60884$fn__60885.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__60884.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__60943.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__58630.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__55651.invoke(add_rows_truncated.clj:35)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__61413.invoke(handle_audit_queries.clj:130)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__60846.invoke(results_metadata.clj:143)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__57662.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__59901.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__57588.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___47934$thunk__47935.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___47934$fn__47937.invoke(reducible.clj:108)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: fc6f2a49feb1217824f25bc88e9287b0358eb698449745a45879c96dd1703333\nSELECT \"public\".\"large_table\".\"id\" AS \"id\", \"public\".\"large_table\".\"large_text\" AS \"large_text\" FROM \"public\".\"large_table\" LIMIT 1048575",
    :params nil,
    :type :invalid-query}}],
 :error_type :invalid-query,
 :json_query
 {:database 33,
  :query {:source-table 6475},
  :type "query",
  :middleware {:process-viz-settings? true, :skip-results-metadata? true, :format-rows? false},
  :async? true,
  :viz-settings
  {:table.pivot false,
   :table.pivot_column "large_text",
   :table.cell_column "id",
   :table.column_formatting [],
   :metabase.shared.models.visualization-settings/column-settings {},
   :metabase.shared.models.visualization-settings/table-columns
   [{:metabase.shared.models.visualization-settings/table-column-name "id",
     :metabase.shared.models.visualization-settings/table-column-field-ref ["field" 2928 nil],
     :metabase.shared.models.visualization-settings/table-column-enabled true}
    {:metabase.shared.models.visualization-settings/table-column-name "large_text",
     :metabase.shared.models.visualization-settings/table-column-field-ref ["field" 2929 nil],
     :metabase.shared.models.visualization-settings/table-column-enabled true}]}},
 :native
 {:query
  "SELECT \"public\".\"large_table\".\"id\" AS \"id\", \"public\".\"large_table\".\"large_text\" AS \"large_text\" FROM \"public\".\"large_table\" LIMIT 1048575",
  :params nil},
 :status :failed,
 :class java.lang.OutOfMemoryError,
 :stacktrace [nil],
 :card_id nil,
 :context :csv-download,
 :error "Java heap space",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 33,
  :query {:source-table 6475, :fields [[:field 2928 nil] [:field 2929 nil]], :limit 1048575},
  :type :query,
  :middleware {:process-viz-settings? true, :skip-results-metadata? true, :format-rows? false},
  :async? true,
  :info
  {:executed-by 1,
   :context :csv-download,
   :nested? false,
   :query-hash
   [-4, 111, 42, 73, -2, -79, 33, 120, 36, -14, 91, -56, -114, -110, -121, -80, 53, -114, -74, -104, 68, -105, 69, -92,
    88, 121, -55, 109, -47, 112, 51, 51]}},
 :data {:rows [], :cols []}}
```

**To Reproduce**
1. Create the test data larger than it would fit into memory (4 KB text * 500k rows = 2 GB)
```
create table large_table
(
    id         serial primary key,
    large_text text
);

insert into large_table (large_text)
select repeat('Z', 4000)
from generate_series(1, 500000)
```
2. Run Metabase with limited ram (e.g. `-Xmx1g`)
3. Ask a question -> Simple question -> Select the table we've created
4. Export as csv

**Expected behavior**
Exporting large amount of data should work by default without extra configuration

**Screenshots**

**Information about your Metabase Installation:**
Happens on`1.40.5` and `master`

**Severity**
Reported by cloud customer, prevents export of large data. No known workaround.

**Additional context**
This is due to 2 issues:
1) There is no default fetch size set for PostgreSQL and the default behavior is to fetch all rows into memory (similar to #11878) - this can be worked around by setting `defaultRowFetchSize` in additional options
2) If auto commit is `true`, [PostgreSQL will fetch the entire result set anyway](https://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor). This cannot be worked around.

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes https://github.com/metabase/metabase/issues/18455

Large query results can OOM the server, even though we are streaming results. Its because the ResultSet can have a lot of rows in memory and we need to limit them.

##### Setup
Made big tables in both pg and mysql

##### pg
```sql
create table large_table
(
    id         serial primary key,
    large_text text
);

insert into large_table (large_text)
select repeat('Z', 4000)
from generate_series(1, 500000)
```

##### In mysql use the repl:
```clojure
;; 5 is my mysql db id. Use your own
  (jdbc/execute! (sql-jdbc.conn/db->pooled-connection-spec 5)
                 ["CREATE TABLE large_table (id int NOT NULL PRIMARY KEY AUTO_INCREMENT, foo text);"])

  (do
    (jdbc/insert-multi! (sql-jdbc.conn/db->pooled-connection-spec 5)
                        :large_table
                        (repeat 50000 {:foo (apply str (repeat 5000 "Z"))}))
    :done)

  (jdbc/execute! (sql-jdbc.conn/db->pooled-connection-spec 5)
                 ["ALTER TABLE large_table add column properties json default null"])

  (jdbc/execute! (sql-jdbc.conn/db->pooled-connection-spec 5)
                 ["update large_table set properties = '{\"data\":{\"cols\":null,\"native_form\":{\"query\":\"SELECT
                 `large_table`.`id` AS `id`, `large_table`.`foo` AS `foo` FROM `large_table` LIMIT
                 1\",\"params\":null},\"results_timezone\":\"UTC\",\"results_metadata\":{\"checksum\":\"0MnSKb8145UERWn18F5Uiw==\",\"columns\":[{\"semantic_type\":\"type/PK\",\"coercion_strategy\":null,\"name\":\"id\",\"field_ref\":[\"field\",200,null],\"effective_type\":\"type/Integer\",\"id\":200,\"display_name\":\"ID\",\"fingerprint\":null,\"base_type\":\"type/Integer\"},{\"semantic_type\":null,\"coercion_strategy\":null,\"name\":\"foo\",\"field_ref\":[\"field\",201,null],\"effective_type\":\"type/Text\",\"id\":201,\"display_name\":\"Foo\",\"fingerprint\":{\"global\":{\"distinct-count\":1,\"nil%\":0.0},\"type\":{\"type/Text\":{\"percent-json\":0.0,\"percent-url\":0.0,\"percent-email\":0.0,\"percent-state\":0.0,\"average-length\":500.0}}},\"base_type\":\"type/Text\"}]},\"insights\":null,\"count\":1}}'"])

```

and then from the terminal client repeat this until we have 800,000 rows:
```sql
insert into large_table (foo, properties) select foo, properties from large_table;
```

##### Exercise from repl
Then can exercise from code with the following:

```clojure
(-> (qp/process-query {:database 5 ; use appropriate db and tables here
                        :query {:source-table 42
                                ;; :limit 1000000
                                },
                        :type :query}
                        ;; don't retain any rows, purely just counting
                        ;; so resultset is what retains too many rows
                       {:rff (fn [metadata]
                               (let [c (volatile! 0)]
                                 (fn count-rff
                                   ([]
                                    {:data metadata})
                                   ([result]
                                    (assoc-in result [:data :count] @c))
                                   ([result _row]
                                    (vswap! c inc)
                                    result))))
                        })
     :data :count)
```

PG was far easier to blow up. Mysql took quite a bit of data.

Then we just set a fetch size on the result set so that we (hopefully)
only have than many rows in memory in the resultset at once. The
streaming will write to the download stream as it goes.

PG has one other complication in that the fetch size can only be honored
if autoCommit is false. The reasoning seems to be that each statement is
in a transaction and commits and to commit it has to close resultsets
and therefore it has to realize the entire resultset otherwise you would
only get the initial page if any.

If anyone has a good idea of how to test this I'm all ears. But I believe it would require setting memory limits and having a large testing db available. So gonna pass on that for now

### FetchSize Profiling

```
;; Long queries on gcloud pg
;; limit 10,000
;; fetch size | t1   | t2   | t3
;; -------------------------------
;; 100        | 6030 | 8804 | 5986
;; 500        | 1537 | 1535 | 1494
;; 1000       | 1714 | 1802 | 1611
;; 3000       | 1644 | 1595 | 2044

;; limit 30,000
;; fetch size | t1    | t2    | t3
;; -------------------------------
;; 100        | 17341 | 15991 | 16061
;; 500        | 4112  | 4182  | 4851
;; 1000       | 5075  | 4546  | 4284
;; 3000       | 5405  | 5055  | 4745
```

Based on this 500 sounds like a good first attempt at a global setting. Thanks for the pointers to check non-local.

### CODE REVIEW

**Comment by paoliniluis** [comment]
We can raise an executor with a very very small amount of RAM and test there :)

**Review by pawit-metabase — COMMENTED** [review]
1) For RedShift, we override the default fetch size with `redshift-fetch-size`. Now that we have a global default, we should remove that options (and related tests). Any Adminstrator that want to override the fetch size on RedShift should just set `defaultRowFetchSize` additional property instead.

2) For MySQL ([doc - see "ResultSet"](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html)) - We should set the fetch size to ` Integer.MIN_VALUE` instead which causes MySQL to stream the result (based on TCP flow control) instead of relying on a specific fetch size value. Actually, any other value will not take effect without `useCursorFetch=true` anyway.

EDIT: Interestingly, setting a fetch size does prevent OOM on MySQL despite what the documentation says 🤔

**Comment by dpsutton** [comment]
> > If anyone has a good idea of how to test this I'm all ears. But I believe it would require setting memory limits and having a large testing db available. So gonna pass on that for now
> 
> The former is easy, e.g. Docker with its [--memory option](https://docs.docker.com/config/containers/resource_constraints/).

I think it will be a bit more than this. The queries can take a bit of time to complete (like 23-27 seconds). Presumably we'd only want to run this test in a special test harness and not in a regular dev test. So we need a way to mark long running tests and exclude them from the other test runner. And it would seem wasteful to just run a single test with all of this. But I do like the idea of starting some long running tests that can check for these types of things. But I think it will be more complicated than just a bit of yaml.

**Review by pawit-metabase — APPROVED** [review]
LGTM

**Pull request merged**
