### PR TITLE
Metabase-lib

### PR DESCRIPTION
**Pull request by attekei**
### Regressions found in the bug bash on 6/23/17

**metric/segment regression cluster**
- [x] When you hover on the segment info icon it doesn't show the filters that create that segment
- [x] When you hover on the metric info icon it doesn't show the info modal if the metric has filters
- [x] if you click on a segment/metric you made from its activity feed item then it doesn't properly load the table and you get an error 500
- [x] write tests for all three

**data reference sidebar regression cluster**
- [x] trying to click on the metric formula in the data reference returns a JS error
- [x] in data reference sidebar it says "Choose an aggregation" for a metric aggregation
- [x] creating a new question from a table when in data reference sidebar fails
- [x] If you open the data reference, navigate to a table with a metric, try to add the metric, and then close the data reference it doesn't show the metric properly as the aggregation in the bar

**misc QB regressions**
- [x] when using “is empty” the timeseries mode filter is empty. Sometimes you also get `Uncaught TypeError: Invalid attempt to destructure non-iterable instance`
- [x] Query failure isn't properly reflected in QB UI – it just renders the last successful query
- [x] Error illustrations are missing in query builder error states
- [x] Field filters in SQL queries don't work properly *(pending test stub added)*
- [x] When viewing a time series, grouped by year, as a table, using the zoom in action on a cell seems to filter by the wrong value *(pending test stub added)*
- [ ] This query produces an error: *(Atte wasn't able reproduce)*
screen shot 2017-06-23 at 16 31 53

**others**
- [x] When you click “Pick a segment or table” in getting started guide, it scrolls you abruptly to top of the page _(solved but will logically be part of a separate PR)_

### Create separate issues
- [ ] If I click on a scalar count of rows, I’d expect to be able to See these X
- [ ] Using drag to filter when breaking out by month of year, hour of day, etc. doesn't work properly *(the dimension is interpreted in `dimensionIsTimeseries` and `dimensionIsNumeric` as number although it is timeseries)*
- [ ] When embedding a dashboard with 3 cards added to a dashboard ID parameter, one of the cards is greyed out even though its being filtered

### Nested query bugs found in the bug bash on 6/23/17:
- Trying to download the csv/xls/json of a nested query for both saved and dirty questions leads to an API error
- When doing a quick-filter on a nested query (total = 54.8 in this case), the field name isn’t shown in the filter clause
- When trying to group by a nested query dictionary field names are also gone
- When you click “Pick a segment or table” in getting started guide, it includes saved questions to the list too
- The nested query is a segment of the People table, aggregated to a count of rows by birthdate:month, but it seems like the dashboard filter doesn’t recognize the month column as a date field.
- Not sure if these were bugs but listing for the sake of completeness: custom expression option not showing up for nested queries, custom field option not showing up on nested queries

### Questions discussed with Tom:
- Docstring needed for Aggregation.js 
**action point: should add docstring**
- Adding also wrapper classes for Breakout and Filter and enforcing those + Aggregation as a default interface instead of plain objects; this is mostly just a question of prioritization and time use 
**action point: yes, those wrapper classes should be added, but not yet for 0.25 necessarily**
- Having the drill-through actions in Question vs. in query classes
**action point: let's keep them in question but move some heavy lifting to respective query classes**

### Ideas:
- Use generics for defining the query type for a question

### CODE REVIEW

**Comment by attekei** [comment]
Proto is ready for testing, no support for multiple tables yet so you have to define multiple metrics for one table (those will appear to the metrics list when adding metrics). A screenshot of the metrics adding view:

screen shot 2017-05-19 at 10 36 41

**Comment by mazameli** [comment]
I know this is still a WIP, so you might already be aware of some of these issues, but I wanted to make sure I mentioned a few things that I noticed:

- [ ] It seems I can't add a second breakout to new questions
- [ ] I can't seem to add saved metrics: if I click on a checkbox in the add modal, nothing appears
- [ ] If I change my visualization from Line to Area, it incorrectly becomes a stacked area chart. This doesn't happen on the Stats instance. (I haven't checked this again recently, and I can't verify it today because of the above issue)

**Comment by attekei** [comment]
The proto is now migrated to metabase-lib. I added some accessor methods (name, datasetQuery, display, displayName, id, isSaved, publicUUID) to `Question.js` and `equalsToMetric` method to `StructuredQuery.js`. Not sure should those changes be simply merged to the current metabase-lib branch.

**Comment by mazameli** [comment]
Breaking out a scalar by a category with the drill-through action doesn't work; the clicks don't do anything in this state:

screen shot 2017-06-14 at 2 32 53 pm

JS error:

```
actions.js?c5eb:342 Uncaught TypeError: Cannot assign to read only property 'query' of object '#<Object>'
    at pivot (actions.js?c5eb:342)
    at Question.pivot (Question.js?a5ff:268)
    at onCommitBreakout (PivotByAction.jsx?929b:76)
    at Object.onFieldChange (BreakoutPopover.jsx?6b94:38)
    at onChangeDimension (FieldList.jsx?f44d:133)
    at onClick (FieldList.jsx?f44d:214)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js?47d4:73)
    at executeDispatch (EventPluginUtils.js?65c4:89)
    at Object.executeDispatchesInOrder (EventPluginUtils.js?65c4:112)
    at executeDispatchesAndRelease (EventPluginHub.js?fed9:47)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js?fed9:58)
```

**Comment by mazameli** [comment]
Granularity dropdown at bottom of screen is missing on time series:

screen shot 2017-06-14 at 2 44 00 pm

**Comment by mazameli** [comment]
I can't add a second grouping:

screen shot 2017-06-14 at 2 45 26 pm

**Comment by mazameli** [comment]
Selecting an aggregation from a table heading, like `Distincts`, weirdly drops off the word `ID` from the field name in the aggregation label (this should read `Product ID`):

screen shot 2017-06-14 at 2 59 12 pm

**Comment by mazameli** [comment]
I'm not sure if this is a regression, but it drives me nuts that you can't use numeric custom fields in aggregations. (Notice the `Rating times 10` field)

screen shot 2017-06-14 at 3 02 28 pm

screen shot 2017-06-14 at 3 02 52 pm

**Comment by mazameli** [comment]
Table/segment summarization doesn't work:

screen shot 2017-06-14 at 3 07 16 pm

**Comment by mazameli** [comment]
Drag-to-filter not working:

screen shot 2017-06-14 at 3 52 56 pm

**Comment by mazameli** [comment]
Saving a saved question you're editing doesn't work, nor does forking it and replacing the original. With the former, there's a JS error; with the latter, no error but the save button doesn't do anything.

screen shot 2017-06-14 at 4 33 14 pm

screen shot 2017-06-14 at 4 33 41 pm

**Comment by mazameli** [comment]
Not sure if this is pertinent, but I keep seeing this introspection error in the logs:

screen shot 2017-06-14 at 4 52 05 pm

**Comment by mazameli** [comment]
SQL variables not seeming to work:

screen shot 2017-06-14 at 4 57 13 pm

screen shot 2017-06-14 at 4 58 02 pm

**Comment by mazameli** [comment]
Not sure if this is a regression, but a dashboard with a dropdown category filter shared via public link has its filter turn into an input box:

screen shot 2017-06-14 at 5 08 18 pm

**Comment by mazameli** [comment]
Clicking on the title of a card on a public dashboard mistakenly tries to go to that card detail (I did confirm that this is a regression, or at least it's fixed on master):

screen shot 2017-06-14 at 5 10 42 pm

**Comment by salsakran** [comment]
I think some of what's happening is that the code at `metabase/qb/lib/actions.js` doesn't actually treat `dataset_query` as read-only. Eg in 
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/qb/lib/actions.js#L317
unless I'm missing something we're copying an array reference rather than a deep copy. Then in https://github.com/metabase/metabase/blob/master/frontend/src/metabase/qb/lib/actions.js#L327 we're writing to it.

Think the answer to this is fleshing out `metabase-lib/lib/Question.spec.js` to cover drill-through, actions, etc.

**Comment by salsakran** [comment]
Not sure what's going on, but this is what I see when I spin up this branch locally and hit "new question"


screen shot 2017-06-21 at 10 12 53 pm

**Comment by attekei** [comment]
@salsakran Was caused by a mistake when I extracted `Mode` to its own class. I fixed it and added an integrated test `QueryBuilder.integ.spec.js` for checking that QB renders on page load without errors for both new and saved questions.

**Comment by salsakran** [comment]
Also, one thing to note is that all the "pendings" are causing the build to fail linting ;)

**Comment by salsakran** [comment]
Found a bug where a question converted from GUI->SQL is missing filter parameters 

original gui question
screen shot 2017-06-22 at 10 26 30 am

converted result
screen shot 2017-06-22 at 10 26 04 am

**Pull request merged**
