### PR TITLE
Fix day aggregation in Druid driver preventing display of multiple time-series

### PR DESCRIPTION
**Pull request by Digma**
Fixed an issue with day aggregation in druid driver, preventing time-series in multiple aggregation to display properly.

Only happens when displaying time-series or barchart with multiple time-series aggregated per day:
screen shot 2018-11-27 at 16 13 30

Other aggregations are not impacted (for example hourly):
screen shot 2018-11-27 at 16 13 53

Not sure this is the ultimate fix but seems to work. Probably requires some regression test but that is beyond my Clojure capacity

###### Before submitting the PR, please make sure you do the following 
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by mazameli** [comment]
Can you give us an update on the status of this PR? It appears that the tests haven't been run. Do you need help with that? Thanks!

**Review by salsakran — CHANGES_REQUESTED** [review]
Any change to the query processor must include a test for the specific fix you are trying to make.

**Comment by lkm** [comment]
Is PR dead in the water? It's still an issue in 0.32.8 and is quite crippling for Druid queries

**Comment by lkm** [comment]
@salsakran This is an omission in the first place since the other query processors return data in the format corrected in this MR. Just to be clear this means that he first impression with doing any date-based aggregation in Metabase with Druid is an error (day is default). I really think this is such a small fix with quite substantial UX benefits.

**Comment by salsakran** [comment]
@lkm thanks for the context on the severity of the issue. However, we don't take PRs that don't have any tests.

@Digma This seems to be a fairly serious issue and we'd love to merge your PR. Can you please add a test for this?

**Comment by lkm** [comment]
Thanks for understanding @salsakran. The problem seems to be that [moment](https://momentjs.com/) can't parse dates with timezone but no time, e.g. `2019-05-09+01:00` vs `2019-06-26T00:00:00+01:00`. I'm not a Clojure dev either, but since this is actually happening in javascript I'd be happy to write a jest test to prove this

**Comment by Digma** [comment]
I moved to a different company, took some holidays and so never got the time to make a test. @salsakran I'll try to have a look but I honestly have no clue about clojure and not much time to learn much. I'll see if I can do some copy pasting and manage to make a test

**Comment by Digma** [comment]
Just had a look tonight and I think adding a test is beyond my abilities in Clojure. I will probably close the PR then and leave somebody else take care of the issue

**Comment by Digma** [comment]
Sorry, Won't have time to do it. Closing

**Pull request closed without merging**
