### PR TITLE
Add apple touch icons

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes https://github.com/metabase/metabase/issues/9210

---

I've not looked into how I can run Metabase locally to see if this works yet, so I apologise in advance if I've messed something up.

---

Generating the icons: _I use Sketch_.

1. Take the latest [logo](https://metabase.com/images/logo.svg) and drop it into a Sketch art board at 128x128 (or whatever Apple supports at the largest resolution).
2. Resize the SVG into the art board so that it's "squared off":
    image
    _There may be a better way of doing this._
3. Export the PNG file at 1x size.
4. Upload to https://realfavicongenerator.net/ and generate the icons.
5. Update the files.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
I might change this a little based on https://stackoverflow.com/a/48969053

**Comment by jbrooksuk** [comment]
Changed!

**Review by kdoh — APPROVED** [review]
Thanks for this @jbrooksuk! I don't have a full device library to test things like the windows icons but in my local testing on iOS it seems like everything works as expected. If you wouldn't mind fixing the merge conflict we'll get this in once it's green.

For extra credit, if you have the time, would you mind quickly commenting with an overview of how you exported the assets in this case so if we need to make changes in the future we can make sure we're hitting all the same targets easily?

**Comment by kdoh** [comment]
I'll actually go ahead and fix the conflict since it's easy.

**Comment by jbrooksuk** [comment]
Thanks @kdoh! No worries, I’ll write this up tonight. Fairly straightforward with Sketch.

**Comment by jbrooksuk** [comment]
@kdoh I've updated the PR with some directions. Let me know if you'd like more info.

**Pull request merged**
