### PR TITLE
Fix for upstream issue 5648

### PR DESCRIPTION
**Pull request by joshuashort**
Simple fix for [issue #5648](https://github.com/metabase/metabase/issues/5648).

Instead of looking for the first primary key in the destination table, this looks for the column which matches the relationship specified by the foreign key; as far as I can tell, this is more robust and allows for a situation which wasn't explicitly disallowed, but wasn't actually supported completely before -- accurate relationship counting and drill-through on tables with more than one entity key.

Since the target column id is known, it makes sense to use that to match a column instead of grabbing the first thing that is a primary key.

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by joshuashort** [comment]
It seems that a Metabase `Entity Key` isn't *exactly* a primary key -- it's more like something that enables a `Foreign Key` to link to some corresponding entr(ies|y) in a different table. That said, it might be nice to have the ability for linking tables in a more generic way. I guess it's similar to joins and subqueries, but it seems powerful to be able to drill through different relationship defined between columns in different tables..

This pull request at least allows different tables to use a foreign key to point to different primary keys on a given table. Maybe it even makes sense to allow something to be both a foreign and an entity key?

**Comment by salsakran** [comment]
By inspection, it looks like what you're doing is more correct than the original behaviour.

Do you mind writing a test to make expected behaviour explicit?

**Comment by joshuashort** [comment]
I don't mind, but I'm not familiar with how testing works yet.. it'll take some extra time, but it's a good learning opportunity.

**Comment by joshuashort** [comment]
@salsakran, do you have any pointers for how to approach this? I'm looking through the existing frontend tests..

I *think* the requested test would go in `query_builder/actions.integ.spec.js` since that's the file being updated, but it doesn't look like much is actually tested there.

And I'd have to make sure there's something defined in `__support__/sample_dataset_fixture.js` that is defined with multiple entity keys, right?

**Comment by salsakran** [comment]
Both of those conclusions are correct. If you really get stuck, I'can help with the data scaffolding part.

**Comment by joshuashort** [comment]
It was an easy fix at the time.. but I didn't have enough time/familiarity with the stack to do tests 😢

**Comment by joshuashort** [comment]
I cleaned up the silly extra commits that were attached to this and rebased off of the current master.

I think it's still valid (unless some properties changed).

**Comment by joshuashort** [comment]
Looks like the `isPK` function was only used once, so it's failing on the linter. I'll remove the import so everything passes CI 👼

**Comment by joshuashort** [comment]
Admittedly, this might not be seen as a major issue, but it seems like something that is unnecessarily broken (with a clear resolution). The old/current way of doing things is unbelievably naive and breaks (unnecessarily).

I came across this issue (probably like @ryan-tangocard) when using a table that is used as a 'hub' to link two (previously-implicitly-related) databases while consolidating into a single warehouse. There are legitimately 2 columns which can be marked as `Entity Key`, as each are Unique on the table, and each serve as the destination of a foreign key in different domains.

This PR breaks nothing (given the current paradigm of a single key), and it further enables 'unofficial' structures. I'll post some screenshots of what's broken to further drive the point..

**Comment by joshuashort** [comment]
As promised, here are some screen shots..

This one, where `CustID` and `CustNum` are both "Entity Key", as they mean different things internally/externally: screen shot 2019-01-04 at 4 03 40 pm

As displayed in the 'connected to' region (to the right), there should be 1 entry.. but here's what happens:

screen shot 2019-01-04 at 4 04 04 pm

In the previous image, it can be seen that `CustomerID` was incorrectly populated with the value from `CustNum` (as opposed to the other key, `CustID`).

Scrolling a little further down, there's another relationship (`vista_ShipHead` (setting aside the 'smart' behavior of mangling names based on cardinality)):

screen shot 2019-01-04 at 4 04 35 pm

Clicking one this relationship (since it's the one arbitrarily selected by the current `isPK` loop), produces the correct results:

screen shot 2019-01-04 at 4 06 55 pm

**Comment by joshuashort** [comment]
A more concise example (though I now see that counts were incorrect):

screen shot 2019-01-04 at 4 44 22 pm

Clicking the `sdb_Hospitals` link (there should be 1 entry):

screen shot 2019-01-04 at 4 44 36 pm

Clicking the `vista_ShipHead`s link (there should be 15, but there are 55.. the filter seems right, but the count seems wrong):

screen shot 2019-01-04 at 4 44 53 pm

**Comment by mazameli** [comment]
@tlrobinson Mind giving this a look?

**Comment by devurandom** [comment]
> @tlrobinson Mind giving this a look?

@camsaul, @mazameli Can anything be done to advance this and get it merged?

**Comment by paulrosenzweig** [comment]
Replaced by #15779

**Pull request closed without merging**
