### PR TITLE
[metabase-lib] Dev experience and CLJC infra improvements

### PR DESCRIPTION
**Pull request by bshepherdson**
## Dev experience:

- CLJS now has source maps
- Devtools extension renders CLJS data in Chrome (et al) Devtools
- Use a debug build of CLJS in the tests

## CLJC infra overhaul

This drops `cljs-bean`, and does real conversion between JS and CLJS data.

The idea here is that the TS wrapper classes hold an opaque CLJS map as an
`_inner` field, and pass that to the CLJC functions.

Rather than magic `de/defn` with autoconversion, `de/defn` is just a wrapper
for `mu/defn` (since it doesn't work nicely in CLJS right now).

Many of the methods in the TS wrapper classes are getters and setters for
nested fields; the new `de/define-getters-and-setters` generates those from a
list of names and `get-in`-style paths.

It generates three things in CLJ and five in CLJS:

```clojure
(def InnerSchema [:map '...])
(def MainSchema [:map [:some [:map [:field InnerSchema]]]])

(de/def-getters-and-setters MainSchema
  some-field [:some :field])

;; generates:

(mu/defn ^:export some-field :- InnerSchema
  [x :- MainSchema]
  (get-in x [:some :field]))

(def ^:private ->some-field
  #?(:cljs (converters/incoming InnerSchema)
     :clj  identity))

(mu/defn ^:export with-some-field :- MainSchema
  [x :- MainSchema new-value :- InnerSchema]
  (assoc-in x [:some :field] (->some-field new-value)))

;; CLJS-only below here:
(def ^:private some-field->
  (converters/outgoing InnerSchema))

(mu/defn ^:export some-field-js :- :any
  [x :- MainSchema]
  (some-field-> (some-field x)))
```

The `some-field-js` flavour supports methods that want to return a vanilla JS
object.

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
backend stuff works for me. Can't really give a qualified opinion about the JS tooling changes

**Review by ranquild — CHANGES_REQUESTED** [review]
Most likely a false alarm but I can't get build working locally with this branch. I get this with `yarn build:cljs`:

```
shadow-cljs - config: /Users/alex/Work/metabase/shadow-cljs.edn
shadow-cljs - connected to server
[:app] Compiling ...
error Command failed with exit code 1.
```

Could you double check it works for you locally? If it does, what you do to work around this issue?

**Comment by bshepherdson** [comment]
Not actually a false alarm, that broke most of the builds/tests that failed too. I forgot to remove the `metabase.domain-entities.question` from the list of exported namespaces, even though I've dropped that file from this PR.

It should work now @ranquild

**Review by ranquild — COMMENTED** [review]
@bshepherdson I still get the same error for some reason

**Review by ranquild — APPROVED** [review]
Build works now, source maps are available in the dev tools. Still not sure if it would be possible to debug cljs in the browser using this approach.

**Pull request merged**
