### PR TITLE
Ignore cruft fields

### PR DESCRIPTION
**Pull request by sbelak**
This slightly reworks the logic when we mark a field as `:preview_display:=false`:
* the (existing) length criteria is applied only to fields with `special_type` nil or JSON. Reason being that if the field has some domain meaning (and hence a special type), you probably want to see it.
* if the field's name starts with _ it's very likely some sort of cruft and can safely be ignored.

Also makes x-rays ignore fields with `:preview_display = false`.

### CODE REVIEW

**Comment by camsaul** [comment]
I think applying the length criteria only to those special types makes sense. 👍 

I think that Fields starting with `_` are cruft would be a reasonable assumption in most cases, my big worry is for the 1% of people who for some reason named some or all of their non-crufty Fields wacky names that begin with underscores. They'll have a really confusing time when they sync their DB and nothing shows up. It might be a reasonable assumption for 99% of people but I would put money on bugs coming in about Fields not syncing from the other 1%.

Maybe I am just being paranoid about trying not to break things more than necessary. I would be interested to hear @salsakran's thoughts on this

**Comment by sbelak** [comment]
In retrospective this has a nasty behaviour in that each time it will overwrite the value for preview_display even if manually overwritten.

**Comment by sbelak** [comment]
Reviving this with just the uncontroversial parts (& tests)

**Review by camsaul — APPROVED** [review]
looks good

**Pull request merged**
