### PR TITLE
#13024 Repro: Data model "Column order" should respect selected sorting

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING CI && PENDING REVIEW

### What does this PR accomplish?
- Reproduces #13024 

### How to test this manually?
- `yarn test-cypress-open`
- `frontend/test/metabase/scenarios/admin/datamodel/table.cy.spec.js`
- All tests should pass

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
@flamber two questions:
1. Is code self-explanatory enough without additional comments or should I add them?
2. Does this reproduce the issue or is that issue specific to upgrading from one Metabase version to another?

**Comment by flamber** [comment]
This issue is a lot more complicated. I'm not sure I understand what the test is trying to do.

**Comment by nemanjaglumac** [comment]
> I'm not sure I understand what the test is trying to do.

It asserts that the selected (database) order is respected in UI.
I understood that it rendered alphabetically, although "Column order: Database" was selected.

**Comment by flamber** [comment]
This is not a frontend issue - it's a backend issue, where the new default since 0.36 is not correctly done.

**Comment by nemanjaglumac** [comment]
Closing, since this would possibly require testing version upgrade which we can't test right now.

**Pull request closed without merging**
