### PR TITLE
embedded dashboards: send message to parent HTML doc when params change

### PR DESCRIPTION
**Pull request by snarfed**
embedded dashboards: send message to parent HTML doc when params change

for #7811. this lets HTML pages that embed Metabase dashboards detect and handle when the user changes parameter values.

as an example, with this PR, you can add this JS to the outer HTML page to propagate parameter values in and out of the dashboard iframe, so you can share URLs to specific queries:

```js
<script type="text/javascript">
function receiveMessage(event) {
  if (event.origin == "http://localhost:3000" &&
      event.data.source == "Metabase" &&
      event.data.name == "dashboard-parameters") {
    window.location.hash = event.data.value.slice(1);  // strip leading ? char
  }
}
window.addEventListener("message", receiveMessage, false);

if (window.location.hash) {
  document.getElementById("metabase").src += "?" +
      window.location.hash.slice(1);  // strip leading # char
}
</script>
```

you can see this in action on https://data.color.com/v1/ . the browser url fragment updates dynamically as you change filter values. if you then open that url in a new tab, it automatically sets the same filter values.

-  [ ] No backend changes afaict. (If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`)
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by snarfed** [comment]
to elaborate a bit, the example JS above propagates the filters in the URL query string into the top-level URL's fragment, eg `#foo=1&bar=z`. i then followed https://www.simoahava.com/gtm-tips/track-url-fragments-as-pageviews/ to get those fragments into Google Analytics, which gets us nice tracking and reporting of the exact queries people are doing in the embedded dashboard. woot!

**Comment by MarcGJA** [comment]
If I understand this proposal correctly, were Metabase to adopt this approach with embeds into one's own apps there would be something to latch onto to detect filter selections and pass them up to the parent page or send some from the parent page back to the iframe.  

Definitely!  This would be a welcome feature for app embeds!  To track yes, and to allow app end users to save off their own default filter selections to a table within the app itself for a Metabase iframe embed to pick up on demand!  Especially with highly dimensional data such an ability would be a big plus!  That way rather than refreshing a page or iframe to a blank slate of filter selections or resource specific defaults each app end user could save off their own defaults or favorite selections!  Brilliant!

Having read <a href="https://github.com/metabase/metabase/issues/6604">@salsakran's response to #6604</a> -- "We're definitely not going to default an iframe rendered dashboard to the last state of its filters as that does not make sense for the usual in-application embedding case." -- it was looking rather glum for such a feature ever to come about.  

But with this approach there's hope!  And the sooner the better!  Speaking for myself I could put this to use today were it available!

**Comment by snarfed** [comment]
you can see this in action right now on https://data.color.com/v1/ . the browser url fragment updates dynamically as you change filter values. if you then open that url in a new tab, it automatically sets the same filter values.

**Comment by RossKinsella** [comment]
Would love to see this feature. Anything I can do to push it along?

**Comment by MarcGJA** [comment]
@snarfed Thanks for providing the link, I didn't realize this was something actually in action right now!

**Comment by tlrobinson** [comment]
FYI here's the `postMessage` API we're thinking about adding to question/dashboard embedding as well (basically just sending back and forth `window.location`): https://github.com/metabase/metabase/pull/9832/files#diff-a03c5401b41cd857491e4ccbcc632658R29

Does that seem sufficient for your use cases? Since parameters are mirrored in the URL I think it should work?

**Comment by snarfed** [comment]
@tlrobinson sounds great. exciting!

**Comment by mazameli** [comment]
@tlrobinson Per [your comment](https://github.com/metabase/metabase/pull/7817#issuecomment-488137456), should we close this PR without merge since it sounds like we've resolved this another way?

**Comment by petrusgomes** [comment]
@mazameli the postMessage documentation is enterprise only. Is this available for regular Metabase builds?

**Comment by tlrobinson** [comment]
We have another implementation of this in the enterprise edition which we will be pulling into this repo. We can leave this open for now or move it the discussion back to #7811

**Comment by kdoh** [comment]
Let's have any more discussion take place in #7811 just to reflect that this PR won't be the place that happens.

**Pull request closed without merging**
