### PR TITLE
Fix filtering by fk fields via table headers :notes:

### PR DESCRIPTION
**Pull request by camsaul**
Here's a better error message for #2738 so this should be easier to debug if it happens again in the future

screen shot 2016-06-13 at 4 50 50 pm

### CODE REVIEW

**Comment by tlrobinson** [comment]
👍

**Comment by camsaul** [comment]
@tlrobinson I have a fix for this too I need to tweak a couple tests I'll open the pr tomorrow morning

**Comment by camsaul** [comment]
@tlrobinson I went ahead and added the fix for filtering to this PR as well if you want to take a look at that too

**Comment by tlrobinson** [comment]
LGTM

**Pull request merged**
