### PR TITLE
fix long pulse name rendering

### LINKED ISSUE #6821: Entering a pulse name longer than 70 characters causes the edit button to disappear
Entering a pulse name longer than 70 characters causes the edit button to disappear, was testing to see if there was a maximum pulse name

- Your browser and the version: Firefox 58.0.1
- Your operating system: Windows 10
- Your databases: postgress
- Metabase version: 0.27.2
- Metabase hosting environment: ubuntu
- Metabase internal database: default

### Bug
*Repeatable steps to reproduce the issue*
- Create a new Pulse
- Give it a name that's longer than 70 characters

### PR DESCRIPTION
**Pull request by kdoh**
Fixes #6821

### CODE REVIEW

**Review by mazameli — CHANGES_REQUESTED** [review]
I'd expect to see an error message below the name input box, or next to the buttons, otherwise it's unclear what the problem is.

screen shot 2018-02-12 at 10 47 16 am

**Comment by kdoh** [comment]
@mazameli So there are two things happening here. The one you mentioned is the one that I initially thought was being reported, but isn't actually the more pressing UX issue. 

Basically as is you can enter a pulse name that's pretty gnarly and if you do, it looks like this on the listing which pushes the edit button over and makes it impossible to edit.

screen shot 2018-02-12 at 10 57 01 am

This particular PR updates the listing so that long pulse names will always wrap
screen shot 2018-02-12 at 10 58 32 am

I'm thinking we should probably set some sort of max length on the input itself but I'd want to do a bit of thinking on how long that should be.

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
Oh, gotcha. In that case, yes, this PR works as advertised. 👍

**Comment by mazameli** [comment]
> I'm thinking we should probably set some sort of max length on the input itself but I'd want to do a bit of thinking on how long that should be.

To clarify, there actually is an existing max length: that's why I was getting into that state in the screenshot. It's just not enforced/highlighted via FE form input validation. Not sure what the exact character count is, but I input something close to 800 characters (lorem ipsum paragraph).

**Comment by kdoh** [comment]
Yeah I think the max length is enforced on the backend, probably whatever the column max length is for the MB Db schema for pulse name. We should follow up with a PR that shows and does validation based on that.

**Comment by mazameli** [comment]
Cool, yeah. In any case I think we can merge this PR.

**Pull request merged**
