### PR TITLE
filter possible native question mapping options by parameter operator

### LINKED ISSUE #16181: Dashboard Contains filter doesn't remain when clicking on Question title
**Describe the bug**
On the new dashboard string filters options,  when using "contains", when clicking on a Question title (at least for SQL questions) on the dashboard to open it, the filter doesn't remain a "contains" one and switch to "equal" as you can see on this recording, which will lead to different results (or literally no result).

**Logs**
No log

**To Reproduce**
1. Add a String "contains" filter on a dashboard
2. Add a SQL Question as a tile of this dashboard and make it listen to the "contains" filter
3. Add a value to this filter (the tile/Question values will change based on it)
4. Click on the title of the SQL Question from the dashboard
5. You will see that the SQL Question opens with the filter value being an "equal"

**Expected behavior**
The Question should open and the filter should be a "contains"

**Screenshots**
Screen+Recording+2021-05-18+at+11 26 28+AM

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1",
    "os.name": "Linux",
    "os.version": "5.4.0-1045-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "redshift",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-07",
      "tag": "v0.38.3-SNAPSHOT",
      "branch": "?",
      "hash": "c70590d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Very annoying: Preventing users from drilling down from a dashboard

### PR DESCRIPTION
**Pull request by daltojohnso**
Resolves #16181 
Reproduces #16181 

If your native question has a `string` tag and your dashboard has a `string/contains` parameter, you should not be to map the parameter to the tag. Currently, you're able to. This PR fixes that by adding an additional filter based on the parsed operator name of the tag and the parameter.

Recording of the fix:

https://user-images.githubusercontent.com/13057258/123175334-7fa87100-d436-11eb-95fd-e63dd04dd263.mov

### CODE REVIEW

**Comment by daltojohnso** [comment]
JK this is in progress -- I'm going to write a new e2e test for this scenario

**Comment by flamber** [comment]
This seems like a possible fix to avoid getting into a correctness issue, but it also makes it much harder to understand how to connect filters, which is already hard enough currently #15438.
While we can probably include this, I think we need some more helpers to guide people.

**Comment by daltojohnso** [comment]
Screen Shot 2021-06-25 at 10 00 18 AM

@flamber would a warning message like this work for you? Feel free alternative phrasing

**Comment by flamber** [comment]
@daltojohnso You probably want someone who's native English to copy that, but it would be impossible for someone who doesn't have write access to SQL to know which filter type is selected in the question.
I think we need to change how filters are connected fundamentally, but that shouldn't block this PR, which just prevent people from selecting something that can lead to incorrect results.

**Review by alxnddr — APPROVED** [review]
LGTM 👍

**Pull request merged**
