### PR TITLE
change the driver's nice name to "MySQL / MariaDB"

### LINKED ISSUE #2581: MariaDB Support (note: this is already supported, just use "MySQL")
Is there any chance that you will add support for MariaDB? As we know MariaDB is a cousin if not sister RDB to MySQL, so I don't believe it would be so much of a work to add it. From the other hand I don't know your backend so my previous statement may be wrong. 

Anyway is there any chance to add it?

Google and other big companies have moved to MariaDB as well.

http://www.theregister.co.uk/2013/09/12/google_mariadb_mysql_migration/

Thanks for your time,

Romanos

### PR DESCRIPTION
**Pull request by MrMauricioLeite**
Resolves #2581

### CODE REVIEW

**Comment by salsakran** [comment]
Before merging, we need to make a concrete decision to do this.

Does anyone have adoption numbers for MariaDB? I still think there might be some value in having a separate entry.

**Comment by camsaul** [comment]
According to the [DB-Engines ranking](http://db-engines.com/en/ranking) MariaDB is the 20th most popular DB (compare to MySQL at #2). It's ahead of other things we support like Redshift (#35) but it's moving up in popularity.

**Comment by camsaul** [comment]
MySQL's score is 40x that of MariaDB. Not sure how closely that reflects actual market share but it's a pretty good indication that MySQL is still an order of magnitude more popular

**Comment by camsaul** [comment]
@metabase/core-developers this PR has been open for 3 months now, I think we should either merge this PR if we're ok with this approach, or close it if we want to do it a different way

**Comment by camsaul** [comment]
@salsakran @metabase/core-developers this PR has been open for 8 months now. Do we want to merge this? If not, we should close it instead of leaving it open forever.

**Comment by mazameli** [comment]
I'm way more in favor of having MariaDB be its own selection.

**Comment by camsaul** [comment]
Cool. Thank @MrMauricioLeite for opening this but I'm going to go ahead and close this PR because we've decided to take a different approach.

**Pull request closed without merging**
