### PR TITLE
do not show restore sample database button to non-admins

### LINKED ISSUE #22504: Non-admin user with DB detail permissions always is shown "Bring the sample database back" link
**Describe the bug**
A non-admin user with DB detail editing permissions for at least one database is shown the button to restore the Sample DB, even if a Sample Database already exists (and even if they have permission to edit it). Clicking on the button returns a 403 in all cases.

**Expected behavior**
This button should be hidden for all users who are not full admins.

**Screenshots**
image

**Information about your Metabase Installation:**
Current master

**Severity**
Minor

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/22504

## Changes
When the sample database is deleted, non-admin users with any "manage database" permission should not see the restore sample database button

## How to verify
Check the original issue repro steps

### CODE REVIEW

**Review by nemanjaglumac — CHANGES_REQUESTED** [review]
This works for the non-admin user, but if admin removes the "Sample Database" and then clicks on "Bring the sample database back" link, that link stays and can be clicked infinite times even if the Sample Database was restored.

As admin:
1. Go to Databases
2. Remove "Sample Database"
3. Click on `Bring the sample database back`
4. Notice the "Sample Database" is back but the link is still there
5. Click on the link again and see that the `POST /api/database/sample_database` goes through and has a `200` response

image


### Note:
This seems to be the bug that existed prior to this change, but since you are already working on refactoring the `DatabaseList`, it doesn't hurt to fix this as well.

@alxnddr if you'd rather do it in a separate (follow up) PR, please let me know and I'll approve this one.

**Comment by alxnddr** [comment]
@nemanjaglumac thanks for pointing out, I fixed that

**Review by ranquild — APPROVED** [review]

**Review by gusaiani — APPROVED** [review]
Nice refactor too.

**Review by nemanjaglumac — APPROVED** [review]
Works like a charm this time.
Thanks for taking the time to address the comments.

**Pull request merged**
