### PR TITLE
Heat maps v2 [WIP]

### PR DESCRIPTION
**Pull request by tlrobinson**

### CODE REVIEW

**Comment by mazameli** [comment]
Do we think we need to dial down the opacity of the blobs? It's pretty hard to discern the borders of regions in this example, though of course it's using #fakedata, so I'm not sure how common it's going to be for users to have this hard of a time understanding the map.

screen shot 2017-07-18 at 4 07 18 pm

Editing the size of a heatmap card is kind of tricky because of how the Leaflet watermarking pops up when you have your cursor in the bottom right corner. Not sure if we can do anything about this. 
screen shot 2017-07-18 at 5 01 00 pm

Resizing a heatmap dashboard card seems to have trouble re-rendering:
screen shot 2017-07-18 at 5 02 34 pm

**Comment by mazameli** [comment]
I think I found a bug:
1. create a heatmap (mine is the raw data of the People table, filtered down to USA using the drag-to-filter on the map) and save it
2. Add it to an empty dashboard and save the dashboard
3. Navigate away to a different section and then back to the dashboard
4. Notice that your card is missing (it does seem to show up if you hard refresh, but you have to do that every time you view the dashboard) **Note:** if you close the browser window and then open up your instance again and navigate back to the dashboard, the card does show up. But then navigating to a different part of MB and back to the dashboard again results in the same problem: no card on the dashboard.
5. If you edit the dashboard, the card is still not visible
6. Then, if you add another card to the dashboard (I just added the same one again), the card reappears, but with an error on it: `Cannot read property "setOptions" of undefined`

screen shot 2017-07-18 at 5 04 38 pm

screen shot 2017-07-18 at 5 05 31 pm

screen shot 2017-07-18 at 5 05 47 pm

**Comment by mazameli** [comment]
Trying to figure out _how_ to make a grid map was kind of hard. I think a few things would help:

1. If I've grouped a metric or a raw data query by lat+long and selected Grid Map, shouldn't we just bin lat+long automatically for the user instead of giving them an error/warning?
2. Adding a label to the binning options arrow/button next to binnable fields would be good. I think I mentioned some possible options in the binning PR and/or in Slack maybe?

Additionally, I have no idea what `quantized` means, but I figured out that changing those options changes the size of my grids. This is probably a future enhancement, but it feels like we could consider adding a bottom-screen widget to provide the option to "change grid size: small, medium, large, XL," or an action menu item to "increase/decrease grid size."

**Comment by tlrobinson** [comment]
> Do we think we need to dial down the opacity of the blobs?

I left the "blobby" heat map in for now but I think we might end up removing it. I've mentioned this problem before: I think the ideal heat map parameters depend on the density of the points (which depends on the number of points, their metric value, if any, the size of the map, the zoom level, etc). I've exposed all the relevant heat map parameters in the settings (radius, blur, min opacity, max zoom) so if you want to fiddle with them feel free, but we'll need to come up with some formula, and possibly expose some of those settings in the final version (maybe with sliders instead of number inputs).

Alternatively, there are other Leaflet heatmap libraries that might do a better job of automatically setting these parameters.

> Editing the size of a heatmap card is kind of tricky because of how the Leaflet watermarking pops up 

> Resizing a heatmap dashboard card seems to have trouble re-rendering:

I don't think these two are regressions (they apply to pin maps as well), but I've fixed them in this branch.

> I think I found a bug

Fixed.

> If I've grouped a metric or a raw data query by lat+long and selected Grid Map, shouldn't we just bin lat+long automatically for the user instead of giving them an error/warning?

Perhaps, but so far there's no precedent for changing (and re-running) the query itself when visualization settings are changed.

Normally there's no reason to do a continuous breakout of lat/lon. I think just changing the default breakout for lat/lon to be binned (30 degrees?) should be sufficient. That will start working once @senior implements `default_dimension_option` which I talked to him about yesterday.

> Adding a label to the binning options arrow/button next to binnable fields would be good. I think I mentioned some possible options in the binning PR and/or in Slack maybe?

Once the default thing mentioned above is implemented it will show the default option, like this:

screen shot 2017-07-19 at 9 40 14 am

**Comment by mazameli** [comment]
Thanks for the updates, Tom. I'm continuing to poke at the branch.

Any reason why the grid doesn't repeat/wrap around if I zoom the map out like this?

screen shot 2017-07-19 at 10 43 21 am

**Comment by mazameli** [comment]
I just pulled a minute ago, and when I open up a saved heatmap, I'm getting that `Cannot read property 'setOptions' of undefined` error, even if it's not in a dashboard. Hard refreshing the browser doesn't fix it, but using the refresh button in Metabase _does_ fix it.

screen shot 2017-07-19 at 1 20 25 pm

**Comment by mazameli** [comment]
With a publicly shared grid map card/dashcard, because drillthrough is disabled (I think), clicking anywhere on the map results in a stuck tooltip that you can't dismiss. This does not happen with heat maps.

screen shot 2017-07-19 at 1 26 38 pm

**Pull request merged**
