### PR TITLE
#13187 Repro: FE should respect (BE) settings for `auto_run_queries`

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
READY

### What does this PR accomplish?
- Reproduces #13187

### How to test this manually?
- `yarn test-cypress-open`
- `frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js`
- Replace `it.skip()` with `it.only()` to test this in isolation
- The test should fail until the related issue is fixed

### Additional notes:
- Once the issue is fixed, please remove the `.skip` part (unskip the test completely)
- Make sure the test is passing and
- Merge it together with the fix

### Screenshots
Example of a failing test:
image

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
I'm unsure where you are finding the class `selected` - I don't see such class.

**Comment by nemanjaglumac** [comment]
Check the screenshot.
There is a class `.Toggle__selected___3MRMF`. I'm asserting that the whole css doesn't **include** the string "selected".

**Review by flamber — APPROVED** [review]
If it works Cypress, that's fine. Not seeing that in Firefox.

**Comment by nemanjaglumac** [comment]
> If it works Cypress, that's fine. Not seeing that in Firefox.

Huh, that's weird. Here's the screenshot from Firefox 83 (within Cypress)
image

---

And from within Firefox itself:

image

**Pull request merged**
