### PR TITLE
Move model cache section back to OSS

### PR DESCRIPTION
**Pull request by kulyk**
In #22892 we moved the model cache section to the enterprise folder making it go away completely in free plans. We actually want this in OSS too, so this PR moves it back to OSS closer to the question info sidebar when it's going to be used.

### To Verify

1. Run Metabase OSS
2. Go to `/admin/settings/caching` and enable model persistence
3. Spin up a sample PostgreSQL DB from [metabase/metabase-qa](https://github.com/metabase/metabase-qa) in Docker
4. Go to `/admin/databases`, connect the new PSQL DB and enable model persistence for the DB (click the "Enable model persistence" button on the DB page's sidebar)
5. Create a question using PSQL data, turn it into a model
6. Open the info sidebar (click the "info" icon at the top right)
7. You should see the caching info in the sidebar

### Demo

CleanShot 2022-06-22 at 16 16 54@2x

### CODE REVIEW

**Review by WiNloSt — COMMENTED** [review]
1. This might not be related to the change but I couldn't find a way to force creating model cache after I've enabled model cache and created models. My models are stuck in this state
image
2. The OSS and EE model menu version isn't the same there's no menu to persist/unpersist menu on the OSS. With this change I expect it to be there as well
    #### OSS
    image

    #### EE
    image
3. One way to force model cache that I found is to unpersist the model, then persist it again. This will create a `persist-refresh` task instantly, but what I expect is that when the model is first created with model cache enabled the model cache should also be created. Likewise, if we created models before enabling the model cache, I'd expect those models to have model cache created as well.
    image

**Comment by kulyk** [comment]
Thanks for your feedback @WiNloSt 

Regarding 1 and 3: it's on purpose. Metabase is going to pick up caching on a schedule. I agree it'd be much nicer if models would get cached instantly once you enable caching or when you create a model from a DB with caching enabled, but there is a risk that it can put too much load on the app and make the experience worse. I've raised that question already, you can read a little bit more about it [on Slack](https://metaboat.slack.com/archives/C03E7PBDQJH/p1653414932538509)

Re 2: model-level caching controls are supposed to be a paid feature, so they shouldn't appear in OSS. Originally, I thought we won't show the caching info section in the sidebar too, but it should be available in OSS actually, so this PR fixes it. But enable/disable cache control for models is a paid feature

**Comment by WiNloSt** [comment]
@kulyk Thanks for the explanation. Everything works as expected then.

**Review by WiNloSt — APPROVED** [review]
Since everything works as expected 🎉

**Review by npfitz — APPROVED** [review]
Looks good!

**Pull request merged**
