### PR TITLE
Binned dimension: fix redundant temporal sub-dimensions

### LINKED ISSUE #16327: Double binning menu for date fields when using Saved Question (Native)
**Describe the bug**
This is a reprise of #15446, but specific to when base is a Native question.

**To Reproduce**
1. Native query > Sample Dataset > `select * from products` - save as "Q1"
2. Custom question > Saved Questions > "Q1"
3. Summarize Count by CreatedAt - click the binning menu, notice all options are duplicated (upper and lower).
Selecting any of the options in the upper-part will be dropped when clicking Visualize (similar to #15725)
Had to zoom out a bit to completely show all options.
image
4. Select one of the options from the lower-part and click Visualize
image
5. On Simple view, it does not mark which option is selected, but also here only the lower-part of options should be used.
Selecting any of the options in the upper-part will cause the same problem as #15397/#15725
image

**Information about your Metabase Installation:**
Tested 0.38.4 thru 0.39.3 - regression since 0.39.0

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by ariya**
This fixes #16327.

Steps to verify (from the said bug, copied here for convenience):
1. Ask a question, Native question
2. Type `select * from products` and save it as Q1
3. Ask a question, Custom question
4. Choose Saved Questions, Q1
5. Summarize: _Count_, by _CREATED_AT_ (click on the binning menu)

**Before**

The pop-up list shows too many items, with duplicated ones.

image

**After**

image

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
I think it's the wrong set of options that is available.

On 0.39.3, when I just click the CreatedAt (not binning), and then click the field again and open the binning, then it marks one of the options as selected:
image

This PR, doing the same thing, does not mark any as selected:
image

And manually selecting any of the options will drop the field on Visualize, or create error in Simple-mode.

**Comment by ariya** [comment]
> This PR, doing the same thing, does not mark any as selected:

Spot on @flamber, thanks! Apparently this test revealed another missing change in the previous refactoring (from time ago): preserving the type in the subdimensions. I've slightly tweaked it and now the selection should be correct. Please take another look, thanks!

**Review by gusaiani — APPROVED** [review]
Fixes duplication of options 👍

Interesting to note that the summaries generated don't seem to ever change by the time slicing. But that's another story.

**Review by flamber — CHANGES_REQUESTED** [review]
Tested 422411b
It now works for SQL, but breaks for QB (which works on 39.3). I really wish we had a full test-matrix before trying to fix these, since it seems like the code is inter-connected in a way that just makes it difficult to fix without causing regressions.
image

**Comment by nemanjaglumac** [comment]
> I really wish we had a full test-matrix before trying to fix these

Working on it. Maybe we should wait a bit more with the fixes before extensive e2e coverage is finished?

**Comment by ariya** [comment]
> since it seems like the code is inter-connected in a way that just makes it difficult to fix without causing regressions.

Fortunately it's not as worse as I imagine. It turns out that the selected binning wasn't picked up because of the search by an exact MBQL comparison. Apparently, the subdimensions aren't consistent, e.g. when they are coming from native SQL, a type option ("base-type") exists which then failed that MBQL exact match.
I don't think we have the time to enforce strict consistency everywhere in our metabase-lib code, but I added a workaround (should be a safe hack, consider this is not different than what's in v38) to search for the selected binning again using a loose comparison (ignoring the base-type, which should be in the parent dimension anyway), if the exact comparison fails to find one.

**Comment by flamber** [comment]
Tested `29c3d34`
It now works for QB, but fails for SQL - feels like Sisyphus is hiding in this code.
But now it shows the option selected in Notebook :+1:

Reproduce:
1. Native query > Sample Dataset > `select * from products` - run, save as "Q1"
2. Custom question > Saved Questions > "Q1"
   1. Summarize Count by CreatedAt (without selecting binning, just let it auto) - this works
   2. Summarize Count by CreatedAt:Year (or any binning manually selected) - column is dropped in Notebook, and in Sidebar it will create query error. Selecting Column-header Distribution works, since it's basically doing auto-binning.

Sidebar error:
`Value does not match schema: {:query {:breakout [(named (not (":field clauses using a string field name must specify :base-type." a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :expression, :field")]}}`

<details><summary>Full stacktrace</summary>

```
2021-06-12 11:53:33,444 INFO api.dataset :: Source query for this query is Card 272
2021-06-12 11:53:33,573 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2021-06-12T11:53:33.451464+02:00[Europe/Copenhagen]",
 :error_type :invalid-query,
 :json_query
 {:database 4,
  :query
  {:source-table "card__272", :aggregation [["count"]], :breakout [["field" "CREATED_AT" {:temporal-unit "year"}]]},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> util.schema$schema_core_validator$fn__16373.invoke(schema.clj:29)"
  "query_processor.middleware.validate$validate_query$fn__49796.invoke(validate.clj:9)"
  "query_processor.middleware.normalize_query$normalize$fn__47677.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44943.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49727.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46794.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48839.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46734.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38051.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___38060$fn__38063.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___38060.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
  "query_processor$fn__49886$process_query_and_save_execution_BANG___49895$fn__49898.invoke(query_processor.clj:253)"
  "query_processor$fn__49886$process_query_and_save_execution_BANG___49895.invoke(query_processor.clj:245)"
  "query_processor$fn__49930$process_query_and_save_with_max_results_constraints_BANG___49939$fn__49942.invoke(query_processor.clj:265)"
  "query_processor$fn__49930$process_query_and_save_with_max_results_constraints_BANG___49939.invoke(query_processor.clj:258)"
  "api.dataset$run_query_async$fn__56143.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__56122$fn__56123.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__56122.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error
 "Value does not match schema: {:query {:breakout [(named (not (\":field clauses using a string field name must specify :base-type.\" a-clojure.lang.PersistentVector)) \"Must be a valid instance of one of these clauses: :expression, :field\")]}}",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data
 {:type :schema.core/error,
  :value
  {:database 4,
   :query
   {:source-table "card__272", :aggregation [[:count]], :breakout [[:field "CREATED_AT" {:temporal-unit :year}]]},
   :type :query,
   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
   :info
   {:executed-by 1,
    :context :ad-hoc,
    :card-id 272,
    :nested? true,
    :query-hash
    [48, 119, -125, -1, -91, -75, 39, -61, 15, -3, 112, 126, 23, 50, -99, -108, 104, 100, 63, 17, 25, 31, 80, -90, 112,
     88, 14, 75, 29, 105, 95, 74]},
   :constraints {:max-results 10000, :max-results-bare-rows 2000}},
  :error
  {:query
   {:breakout
    [(named (not (":field clauses using a string field name must specify :base-type." a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :expression, :field")]}}},
 :data {:rows [], :cols []}}

2021-06-12 11:53:33,578 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 142.3 ms (4 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (3 idle, 0 queued) (79 total active threads) Queries in flight: 1 (0 queued)
```

</details>

**Comment by ariya** [comment]
> Sidebar error:
> `Value does not match schema: {:query {:breakout [(named (not (":field clauses using a string field name must specify :base-type." a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :expression, :field")]}}`

Yeah, this one is #16379, isn't it? It happens regardless of the redundant subdimensions in the list (which this PR is trying to fix).

**Comment by flamber** [comment]
@ariya Then I prefer leaving the double-binning, since since that's currently the workaround for using binning.

**Comment by flamber** [comment]
@ariya Allllmost there! This works great for nested SQL, but for nested QB and simple QB (plain table) it drops the column in Notebook when doing manual-bin, and doing it in Sidebar works, but it doesn't show the field as selected.
Even though I don't see this making release, do you want to continue on this branch or change to master?
Here's a video showing first nested SQL, then nested QB, and last is just a simple QB:

https://user-images.githubusercontent.com/1447303/122119765-dbb53900-ce29-11eb-9038-12ae2a1bc042.mp4

**Comment by ariya** [comment]
> Even though I don't see this making release, do you want to continue on this branch or change to master?

I'll likely continue in the master branch instead, now that the test matrix from @nemanjaglumac starts to look really good.
Beside, we keep uncovering new binning bugs which have little to do with just duplicated subdimensions.

**Pull request closed without merging**
