### PR TITLE
fix inability to filter by a field of a joined table

### PR DESCRIPTION
**Pull request by alxnddr**
### Description

Filtering by fields of joined tables did not work because `join-alias` of the dimension that was used for filtering had been missing.

After:
Screen Shot 2021-04-14 at 00 30 40

Fixes https://github.com/metabase/metabase/issues/15570

### CODE REVIEW

**Review by ariya — APPROVED** [review]
LGTM :+1:

**Comment by ariya** [comment]
@paulrosenzweig might want to take a look at this as well?

**Comment by alxnddr** [comment]
@ariya thanks for the review! I slightly changed the PR to fix the simple question mode as well, could you take a look?

**Review by ariya — APPROVED** [review]
LGTM :+1:

**Pull request merged**
