### PR TITLE
Allow setting MB_HEAP_SIZE variable in Docker run script

### PR DESCRIPTION
**Pull request by jakubkulhan**
Set JVM `-Xms` and `-Xmx` options.

### CODE REVIEW

**Comment by camsaul** [comment]
maybe it's more useful if we just expose a general way to set additional JVM options. @salsakran , thoughts?

**Comment by salsakran** [comment]
@jakubkulhan are these things you're setting all the time?

Unless we're planning on doing something smart w/ HEAD_SIZE in the script (like autosetting it for certain instance types in aws, etc), I'd also say it might be best to just pass through JVM args

**Comment by camsaul** [comment]
Also, it's not always desirable to set minimum heap size to the same as max. If we have some really huge amount of RAM we're gonna introduce unnecessary startup lag. e.g. if someone is running on a `t2.large` and giving MB 7 gigs of RAM it's a waste of time to allocate all 7 gigs on launch.

**Comment by jakubkulhan** [comment]
I got inspired by [Elasticsearch and its `ES_HEAP_SIZE`](https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html) as a) it's simple (user don't have to think what should be minimum memory, what should be maximum); b) sooner or later JVM consumes most of `-Xmx` memory anyway.

**Comment by kdoh** [comment]
Hey @jakubkulhan. Thanks for your work on this. Since it's been a while without any activity on this PR I'm going to close it for the moment. If you'd like to continue working on this please just reply and we're happy to re-open it.

**Pull request closed without merging**
