### PR TITLE
Create pt-br.po

### PR DESCRIPTION
**Pull request by marcus2703**
Portuguese-BR translations for metabase package.

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by abmj1979** [comment]
Pulses not could be translate to "Pulsos" or "Notificações"?

**Comment by fernandosjp** [comment]
@abmj1979 Acho que notficações seria a melhor palavra mesmo. 

@marcus2703 tem um typo em "Metabase está fucionando" >> "Metabase está funcionando"

**Comment by jornh** [comment]
@keyboard99 @lucasloami looks like a pt-br Pull Request to me 🎉

**Comment by keyboard99** [comment]
Great hehe

**Comment by valtlfelipe** [comment]
The last update from the [metabase.pot](https://github.com/metabase/metabase/blob/master/locales/metabase.pot) was 13 days ago, this PR is from January. The translations need to be updated!

Wouldn't be better we use a service where everyone could help translate like https://translate.zanata.org ?

**Comment by mauricio-sonegatti** [comment]
I don't know any translator tools, does anyone else have more suggestions like @valtlfelipe ?

**Comment by lucasloami** [comment]
Any updates on merging this PR?

**Comment by mauricio-sonegatti** [comment]
I did some speed translation and using google on the spanish translation from @joebordes at PR #7065 .
Strangely some phrases weren't translated, but I think it's a start.
I did not made a new PR because my company proxy does not like git sometimes, so I uploaded the file as txt on the following. Warning - I didn't tested it yet.
[pt-br.txt](https://github.com/metabase/metabase/files/1900109/pt-br.txt)

**Comment by mauricio-sonegatti** [comment]
Using pt-br.po as my file is not working, the build can't continue because it generates a java class with "-" on the name and throws an error. Right now I'm trying going with pt.po and see where it goes.

**Comment by joebordes** [comment]
as far as I can see they did not take make comments into consideration, you will have to do pt only
I suppose they will revisit this issue again in the future
At least we have a good start.

**Comment by mauricio-sonegatti** [comment]
I don't know why, but right I have only a problem:
The /admin/settings/setup  , /admin/settings/authentication and /admin/settings/authentication/ldap are unavailable, they show only the background instead of content.
For now, this is the pt-br translation I have, using pt.po as the archive
[pt.zip](https://github.com/metabase/metabase/files/1921913/pt.zip)

I thought it was strange, while building for the first time, it created some #~ lines at the end of the file, I took care of them, but still have the issues
metabase-pt-br
metabase-pt-br1
metabase-pt-br2

**Comment by joebordes** [comment]
That isn't due to your translation, it is something that needs fixing. [They know and are on it](https://github.com/metabase/metabase/issues/6674)

**Comment by mauricio-sonegatti** [comment]
Thanks @joebordes , I'll subscribe to that issue, for now I'm gonna let my users try the translation as it is, to see if any other issue rises.

**Comment by fernandosjp** [comment]
Guys, I'm a bit confused on where we are at the pt-br translation. @mauricio-sonegatti Is the file you linked on comment above in another PR? It seems that @marcus2703 just did the first commit but is not updating it anymore. Am I right? @mauricio-sonegatti Since you are the most advanced here with pt translation, how do you suggest we should proceed?

**Comment by mauricio-sonegatti** [comment]
@fernandosjp I created a new PR, #7396 . My company proxy finally let me push to github.
For now this is the file I'm testing on my deploy. As already known everywhere, there's a lot of strings that stay on the backend, @joebordes posted here some of the issues that are being looked and that we need fixed to fully translate.
As I said before, thanks for @joebordes for the insight and work on the ES translation that helped me get to this point. A lot of things can get better translated, but it's a start.

**Comment by tlrobinson** [comment]
@marcus2703 @mauricio-sonegatti @fernandosjp @valtlfelipe @lucasloami @killboard @abmj1979  We're going to try out using POEditor to manage translations. Here's the project: https://poeditor.com/join/project/ynjQmwSsGh I've imported this PR so I'm going to close it. Thanks!

**Comment by mauricio-sonegatti** [comment]
@tlrobinson I just pushed my PR #7396 to the project on POEditor too. You can close that one too.

**Comment by mauricio-sonegatti** [comment]
Also @tlrobinson we finished translating all strings to POEditor. The community is already contributing, and I think it can be shipped.

**Comment by valtlfelipe** [comment]
@mauricio-sonegatti I would wait one or two days, so that I can review all translated strings. Some strings are confusing, or translated wrong, maybe a translator has been used and messed up somethings.

I will updated here as soon I finish.

**Comment by valtlfelipe** [comment]
Now it looks good to me, of course, there are a lot of strings, I may have not fixed all.

I can say, we can release it! @tlrobinson

**Comment by mazameli** [comment]
Thanks for your work, everyone! We've [released the PT-BR translation](https://metabase.com/blog/Metabase-in-Portuguese/index.html) in version 0.30.1 yesterday.

**Pull request closed without merging**
