### PR TITLE
Merge events by pixel coordinates

### PR DESCRIPTION
**Pull request by ranquild**
Epic: https://github.com/metabase/metabase/issues/20289

How to test:
- Create events that close to each other. The ones on the screenshot are Jan 1 and Jan 24.
- Resize the chart and make them group / ungroup with each other
- Note that the position of the event line & icon is the average of events within the group

Screenshot 2022-03-28 at 18 21 55
Screenshot 2022-03-28 at 18 22 11
Screenshot 2022-03-28 at 18 22 22

### CODE REVIEW

**Comment by mazameli** [comment]
This behavior in principle looks right to me, but I ran into at least one case where I had an event on March 1, 2019, but the line for the event on the chart appeared to be somewhere in between Feb 27 and Feb 28: https://www.loom.com/share/92449578abb54efe8601151433e7201d

**Comment by ranquild** [comment]
@mazameli I was able to reproduce the issue, thanks! Trying to figure out what's wrong

**Comment by ranquild** [comment]
@mazameli I've fixed the issue, please take a look

**Review by mazameli — APPROVED** [review]
Looks perfect!

**Pull request merged**
