### PR TITLE
patch-v0.13.1

### LINKED ISSUE #1637: Pulse test endpoint requires admin but is displayed to non-admins
Clicking the button results in "Sorry, you are not authorized to view the specified page."

Is it safe to allow normal users to send arbitrary pulses?

### LINKED ISSUE #1641: Can't sort on grouping field
When I create "group and count" table I can sort it on the count field but not on the group variable field. (Specifically this is grouping on a timestamp by week, not sure if it's true for all group bys). Thanks!

### PR DESCRIPTION
**Pull request by tlrobinson**
- [x] Pulse test endpoint requires admin but is displayed to non-admins #1637
- [x] Can't sort on grouping field #1641

Resolves #1637
Resolves #1641

### CODE REVIEW

**Comment by tlrobinson** [comment]
This mostly resolves the sort issue #1641, which arose when we added `fk->` and `datetime_field` fields types but continued using simple equality operator to match fields.

However, I don't know what the best solution to fix setting the sort when clicking table column headers for `fk->` fields is, since we currently just get the field id from the `cols` object returned by the dataset API, which doesn't tell us anything about the original `fk->` field.

@agilliland @camsaul Perhaps the query processor should return more information about the source of every column (like we started doing with `:unit` on `datetime_field`). This would also allow us to show the full origin of a column in places like the table headers and chart axis.

This little hack is related: https://github.com/metabase/metabase/blob/master/frontend/src/query_builder/QueryVisualizationTable.jsx#L246-L247

**Comment by agilliland** [comment]
Cool.  This at least gets us to a functional state again.  @tlrobinson I noticed that this still doesn't quite work in the case where I group by DateTime : Week and then try to click the column header in the table view.  Is it possible to resolve that use case fairly easily?

There are no joins in that case, so I'm assuming you have the metadata needed.

**Comment by tlrobinson** [comment]
Ok this latest commit actually sort of fixes the foreign key thing, except possibly in the case where you happen to breakout the same field twice through two different foreign keys, but that seems pretty rare.

Interestingly the query processor seems to be able to handle

`{ ..., breakout: [["fk->", 3, 27]], order_by: [[27, "ascending"]] }`

but not

`{ ..., breakout: [["datetime_field", 27, "by", "week"]], order_by: [[27, "ascending"]] }`

which is a little surprising because the former could be ambiguous (e.x. `breakout: [["fk->", 3, 27], ["fk->", 4, 27]]`) but the latter is not

**Comment by camsaul** [comment]
If `27` is in a different Table you should *always* use the `fk->` form to refer to it, so both of those forms are wrong

**Comment by agilliland** [comment]
So what is the expected form of the `order_by` clause in these cases?
1. ordering by a datetime field at a specific granularity
2. ordering by a field which is from a different table
3. ordering by a datetime field from a different table

There's nothing in the docs right now that cover these use cases, https://github.com/metabase/metabase/wiki/Query-Language-Overview

**Comment by camsaul** [comment]
`:order_by [[["fk->" 3 27] "ascending"]]`

make sense?

**Comment by camsaul** [comment]
this is in the documentation BTW:

screen shot 2015-12-07 at 4 52 39 pm

**Comment by agilliland** [comment]
so if the field is being broken out as a datetime weekly should the order_by clause be ...

 `:order_by [[["datetime_field", 27, "by", "week"] "descending"]]`

and if that field is an FK in another table it should be ...

 `:order_by [[["datetime_field",["fk->", 3, 27], "by", "week"] "descending"]]`

??

**Comment by camsaul** [comment]
@agilliland yes sir

**Comment by agilliland** [comment]
so @tlrobinson do we have the necessary information to make that happen?  i want to make sure we are forming proper queries.

**Comment by tlrobinson** [comment]
There's not enough information in the table view columns to get the sort clause right 100% of the time (no `fk->` info, `column.unit` is populated on date/time columns regardless of whether it was in the query), so in addition to doing my best to pick the sort correctly, in `cleanQuery` I'm now also matching sort clause target field IDs against the breakout (if a breakout is present) and replacing it with the actual breakout to ensure it's correct.

This seems to work for regular fields, `datetime_field`s, `fk->` fields, and any combination thereof. The only edge case I'm aware of is if you have two breakouts with the same target field, which is only possible if a table has 2 foreign keys to the same table and you breakout the same field in that table.

**Comment by agilliland** [comment]
thanks Tom!  this is looking good now.  I'll cut the patch release artifacts and then merge this.

**Comment by camsaul** [comment]
did-you-forget-about-deleting-this-branch

**Pull request merged**
