### PR TITLE
Getting Started Guide Backend :information_source: [WIP]

### PR DESCRIPTION
**Pull request by camsaul**
This should be enough for a few days. (@lewisl9029) Still pending tests, some more API work, and other changes as needed. I recommend anyone who checks out this branch make a backup copy of your DB as the migration is subject to change.
###### Models:
-  Added `points_of_interest` text column to `Database`, `Table`, `Field`, `Dashboard`, `Metric`, and `Segment`.
-  Added `caveats` text column to `Database`, `Table`, `Field`, `Dashboard`, and `Segment`.
-  Added `how_is_this_calculated` text column to `Metric`.
-  Added `show_in_getting_started` boolean column to `Dashboard`, `Table`, and `Segment`.
-  Created new intersection table `MetricImportantField` for the most important `Fields` for a `Metric`.
-  Added new `Settings`: `getting-started-things-to-know`, `getting-started-contact-name`, `getting-started-contact-email`
###### API Endpoints:
-  Added `GET /api/getting_started/` which returns the various things that need to be displayed in the front page of the Getting Started Guide.
-  Added `PUT /api/metric/:id/important_fields` which can be used to set the IDs of `Fields` that are important for `Metric` with `:id`
-  Existing endpoint `PUT /api/setting/:key` can be used to update `Settings`, e.g. `PUT /api/setting/getting-started-things-to-know`
-  Existing endpoints like `PUT /api/dashboard/:id` (etc.) can be used to change values of new columns`points_of_interest`, `caveats`, `how_is_this_calculated`, and `show_in_getting_started`
### Outstanding TODOs:
-  [ ] Return "Important Fields" for Metrics from `GET /api/getting_started/` (@lewisl9029 I'll add this when you're ready to wire it up, let me know)

### CODE REVIEW

**Comment by lewisl9029** [comment]
RE: Added caveats text column to Database, Table, Field, Dashboard, and Segment.

We're going to need to add `caveats` to `Metric` as well.

**Comment by lewisl9029** [comment]
Also noticing just now that databases don't seem to have a description column yet.

We'll need this for data-reference too.

**Comment by camsaul** [comment]
Databases already have descriptions, the endpoint where you got the DB probably just isn't fetching it so we just need to add that in

**Comment by camsaul** [comment]
@lewisl9029 what API endpoint are you getting the DBs from

**Comment by camsaul** [comment]
@lewisl9029 added `caveats` for Metric. You'll need to re-migrate from your for it to take effect (use the backup of your DB or just wipe it and create a new one). Here's my outstanding TODOS:

-  [ ] Return `:description` with Databases from the appropriate API endpoint
-  [ ] Return "Important Fields" for Metrics from `GET /api/getting_started/`

**Comment by lewisl9029** [comment]
For fetching I'm using both `db_list` and `db_metadata`:
```
        db_list: {
            url: '/api/database/',
            method: 'GET',
            isArray: true
        },
        db_metadata: {
            url: '/api/database/:dbId/metadata',
            method: 'GET',
            params: {
                dbId: '@dbId'
            }
        },
```

For updating I'm using `db_update`:
```
        db_update: {
            url: '/api/database/:dbId',
            method: 'PUT',
            params: {
                dbId: '@id'
            }
        },
```

**Comment by camsaul** [comment]
@lewisl9029 `description` comes back with both those endpoints. Put them in your browser and see for yourself :wink:

**Comment by lewisl9029** [comment]
@camsaul Sorry I should have been a bit more specific, the problem I ran into was actually with the `db_update` endpoint. 

When I send a PUT with updated name & description, it returns a db with the updated name but `null` description (i.e. the description isn't getting updated). Further GETs at the endpoint also return the updated name with null description. 

So it's probably just the `db_update` endpoint that's not handling description correctly.

**Comment by camsaul** [comment]
@lewisl9029 yeah that's pretty different from "databases not having a description column". Try the latest commit I enabled editing description for `PUT /api/database/:id`.

**Comment by lewisl9029** [comment]
@camsaul Awesome. I'll try it out asap. =)

**Comment by camsaul** [comment]
@lewisl9029 feel free to close this once you merge it into the main data reference branch

**Comment by lewisl9029** [comment]
Sure. It's already been merged so I'll close it now. =)

**Pull request closed without merging**
