### PR TITLE
Drop BE defaults for dashcard's size_x, size_y, row, and col

### PR DESCRIPTION
**Pull request by calherries**
Database defaults for some `DashboardCard` fields are now redundant since https://github.com/metabase/metabase/pull/27708#top, which changes the FE to always create dashcards with these fields.

Before we were creating dashcards without these fields, and updating the fields later for historical reasons.

This PR offers two improvements:
1. It tightens the requirements at the database level, so there are no defaults for size_x, size_y, row, and col. They are all still required to be not NULL.
2. It tightens up the requirements at the API endpoints, so now `POST /api/dashboard/:dashboard-id/cards` and `PUT /api/dashboard/:dashboard-id/cards` require these fields to be not null in the request body.

The changes themselves are small, and limited to these three files:
image

I would recommend starting the review there, and then moving to the tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27750)

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
@calherries will this prevent downgrading to the previous versions if needed?

**Comment by calherries** [comment]
@nemanjaglumac No, these columns are already required to be not NULL.

**Comment by qnkhuat** [comment]
we just recently changed the default value in https://github.com/metabase/metabase/pull/27572, maybe @tsmacdonald could chime in on the decision of dropping these default values?

**Comment by calherries** [comment]
Yes, we talked about this in [this](https://metaboat.slack.com/archives/C04DAKKDMFT/p1673959017983529) conversation.

From Tim:

> I seem to recall that they already have default card dimensions for other reasons, and that I was annoyed that we have to keep 4×4 in sync between the FE, BE, and DB defaults (as observed by [Nemanja here](https://github.com/metabase/metabase/pull/27572#issuecomment-1375779523)).
> So, with that in mind, pulling it all into the FE and making it required for the POST would simplify things across the board.

**Review by qnkhuat — APPROVED** [review]
LGTM!

**Pull request merged**
