### PR TITLE
Remove `MetabaseSettings.docsUrl()`

### PR DESCRIPTION
**Pull request by iethree**
Prep for https://github.com/metabase/metabase/issues/41189

### Description

MetabaseSettings has been deprecated for a *long* time. This removes one major use of it `MetabaseSettings.docsUrl()` and replaces it with a more developer-friendly hook: `useDocsUrl`. 

Before
```ts
import MetabaseSettings from "metabse/lib/settings";
import { useSelector } from "metabase/lib/settings"
import { getShowMetabaseLinks } from "metabase/selectors/whitelabel";
...
const showMetabaseLinks = useSelector(getShowMetabaseLinks);
const url = MetabaseSettings.docsUrl("dashboards/actions");
```

After
```ts
import { useDocsUrl } from "metabase/common/hooks";
...
const { url, showMetabaseLinks } = useDocsUrl("dashboards/actions");
```

One other item of note is that we had to update a lint rule: `no-unconditional-metabase-links-render` to remind users that they need to destructure the `showMetabaseLinks` property out of this hook and use it to conditionally render metabase links to account for whitelabel settings.

Now, when the lint rule reminds you to do the conditional check, you don't need a new import, you just need to destructure the value out of the same hook. 😁 

### How to verify

No functional changes, just less deprecated code in use. ☺️ 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by npfitz — APPROVED** [review]
Looks good!

**Comment by npfitz** [comment]
Actually, since this morning, there is another docs url in `frontend/src/metabase/admin/settings/notifications/WebhookForm.tsx` that should also be converted

**Comment by iethree** [comment]
> Actually, since this morning, there is another docs url in `frontend/src/metabase/admin/settings/notifications/WebhookForm.tsx` that should also be converted

😱  thanks. I'll kill that one too. Also gotta update some tests

**Comment by iethree** [comment]
> Actually, since this morning, there is another docs url in `frontend/src/metabase/admin/settings/notifications/WebhookForm.tsx` that should also be converted

actually that one is fine, it's using the selector already which is still fine 👍

**Pull request merged**
