### PR TITLE
Update H2

### PR DESCRIPTION
**Pull request by salsakran**
1.4.198 finally has window functions!

### CODE REVIEW

**Comment by salsakran** [comment]
Oof. 
Quartzite is still on quartz version 2.1.7 https://github.com/michaelklishin/quartzite/blob/master/project.clj#L6 ,
which still has trailing commas. This version bump of H2 dropped support for them. 

Probably other issues as well. 

Investigating

**Comment by salsakran** [comment]
Also, it looks like the primary build error is from the liquibase generated statement
```CREATE TABLE PUBLIC.METABASE_FIELDVALUES (ID INT AUTO_INCREMENT NOT NULL, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL, VALUES[*] CLOB, HUMAN_READABLE_VALUES CLOB, FIELD_ID INT NOT NULL, CONSTRAINT PK_METABASE_FIELDVALUES PRIMARY KEY (ID), CONSTRAINT FK_FIELDVALUES_REF_FIELD_ID FOREIGN KEY (FIELD_ID) REFERENCES PUBLIC.METABASE_FIELD(ID))
```

**Comment by camsaul** [comment]
I'm guessing `VALUES[*]` is a marker for the part of the query where the error is and it's the identifier `VALUES` that it specifically doesn't like. Maybe in old versions of H2 you could use that as an identifier without quoting it but in new versions you can't do it any more? 

IIRC Liquibase only quotes identifiers that it thinks need quoting -- maybe updating to the latest version of Liquibase will fix the issue. If not there should be some way we can force Liquibase to do quoting there

**Comment by paoliniluis** [comment]
why not 1.4.200?

**Comment by devurandom** [comment]
> I'm guessing `VALUES[*]` is a marker for the part of the query where the error is and it's the identifier `VALUES` that it specifically doesn't like. Maybe in old versions of H2 you could use that as an identifier without quoting it but in new versions you can't do it any more?
> 
> IIRC Liquibase only quotes identifiers that it thinks need quoting -- maybe updating to the latest version of Liquibase will fix the issue. If not there should be some way we can force Liquibase to do quoting there

Indeed, Liquibase 4.3.5 changes this and quotes "values" (see the commits in #16086 for the problems this causes and how to potentially prevent them in the future).

**Pull request closed without merging**
