### PR TITLE
Add cumulative count aggregation type

### PR DESCRIPTION
**Pull request by camsaul**
The original BASIC need for all users. Implements #647

### CODE REVIEW

**Comment by agilliland** [comment]
This isn't working correctly on the frontend yet.  A cumulative count doesn't require the selection of a field to operate.

**Comment by camsaul** [comment]
@agilliland I'm already working on adjusting that

**Comment by agilliland** [comment]
cool.  also, it looks like we aren't summing properly when there are 2 breakouts in the query.  it's just summing each individual tuple instead of doing the summing within the appropriate breakout.

**Comment by camsaul** [comment]
@agilliland are you talking about cumulative sum?

**Comment by agilliland** [comment]
i'm talking about both.  it doesn't feel right that the cumulative summing just continues across the multiple dimensions because the values don't make much sense then.

e.g. this feels wrong
month, category, count/sum, cumulative count/sum
april cat1 100 100
april cat2 150 250
may cat1 100 350
may cat2 150 500

i'm not certain what is is best, but this feels more natural because the values within the categories are actually accurate.
month, category, count/sum, cumulative count/sum
april cat1 100 100
april cat2 150 150
may cat1 100 200
may cat2 150 300

maybe poke around a little on the internet and see how some databases treat this?

**Comment by camsaul** [comment]
ok now this is making america great again 
up and to the right, folks

screen shot 2016-05-03 at 4 53 45 pm

**Comment by camsaul** [comment]
@agilliland databases don't treat it, it's not a real DB thing... Want to open a separate issue for that?

**Comment by agilliland** [comment]
lets take a little time and figure out how we want to progress as part of this PR.

**Comment by camsaul** [comment]
@agilliland ? I'm not sure I follow. If you found a bug with a different aggregation that should be opened as a separate issue. If this PR disappeared of the face of the earth this second we'd still want to address that issue.

**Comment by agilliland** [comment]
This is not a different aggregation, this is specifically to do with cumulative count which you are adding in this PR, so it's relevant.

**Comment by camsaul** [comment]
But if it has to do with cumulative sum...

**Comment by camsaul** [comment]
@agilliland I can't address the issue because I'm not sure what exactly you're talking about. Since it affects an existing aggregation type can you please open that as an issue and explain in more detail what you're seeing and how you think the results should be different?

**Comment by agilliland** [comment]
It doesn't affect a different aggregation, it affects the work in THIS pr.  The question is very simply to ensure that we are properly handling the way cumulative counting works when there are 2 breakouts in the query.

**Comment by camsaul** [comment]
So it doesn't affect cumulative sum at all? I thought you said it affects both?

**Comment by camsaul** [comment]
I haven't heard anything else about objections to the way multiple breakouts are handled. Since it's not specific to this aggregation we can address that in a separate issue if it is still desired. If there are no further objections I'm going to go ahead and merge this

**Comment by Poggen** [comment]
When grouping on two columns this does not produce the result I expected. The values I'm getting are:

month, category, count, cumulative count
april cat1 4 4
april cat2 6 10
may cat1 13 23
may cat2  6 29

It would, in my opinion, be more a more logical approach to pivot on both breakouts, i.e doing two separate cumulative counts – one per category:

month, category, count, cumulative count
april cat1 100 100
april cat2 200 200
may cat1 150 250
may cat2  250 450

Is this multiple breakouts with cumulative counts/sum really working as intended?

**Comment by tlrobinson** [comment]
@Poggen You're right, that seems broken to me.

Note that it's not always obvious which breakout to do the "accumulation" over. I think it will usually be the time dimension, if there is one, or maybe we could look at sort order?

A possible workaround, if you have a small number of categories, would be to create a card for each category, and combine them on a single dashboard card using the "add series" functionality.

**Comment by camsaul** [comment]
It's working as intended.

100 + 200 = 300
300 + 150 = 450
450 + 250 = 700

All cumulative count does is cumulate the values of your count column, and your count column is broken out by two categories, `month + category`.

**Comment by tlrobinson** [comment]
@Poggen I filed an issue for this here: #4266

**Comment by salsakran** [comment]
@camsaul the issue here is whether the intended behaviour makes any sense.

**Pull request merged**
