### PR TITLE
time filter improvements

### PR DESCRIPTION
**Pull request by kdoh**
addresses #3199

Remaining Todos:
- [x] misc styling tweaks
- [x] granularity choices should collapse.
- [x] include time in filter descriptions
- [x] modal jumping when switching to between.

### CODE REVIEW

**Comment by salsakran** [comment]
When I move from a `between` filter to a `current`, the granularity selector gets stuck.

See attached.

screen shot 2016-11-14 at 5 18 12 pm

**Comment by salsakran** [comment]
The drop down selector (the triangle) feels a little too close to the choices, and it's not all that obvious to me that it's clickable. There doesn't seem to be enough visual differentiation between that and normal text.

**Comment by salsakran** [comment]
overall, liking the new categories a lot in terms of functionality/

**Comment by tlrobinson** [comment]
@kdoh You should use the `autoFocus` attribute on `input` instead of `findDOMNode(this.refs.input).focus()`. I replaced most of them but it looked like I missed the one causing @salsakran's error.

**Comment by mazameli** [comment]
This is a long comment, but let me start by saying I think this is a great improvement to our current filters!

- The biggest problem I have with this implementation is that I found it really confusing and cumbersome to try and select a specific month (besides this/last/next month). I was expecting to be able to click open the calendar that appears in the initial `On` popup and just select two dates to create a range (maybe `On` would change to `Between` automatically). Or, when I figured out that I needed to select `Between`, I was confused why there were two calendars instead of just one. It felt odd that, if I've opened up a calendar, that Metabase didn't intuit I wanted to choose _both_ the start and end date via the calendar, and it made it hard to visualize the range. It also surprised me that the `add a time` button moved down below the calendar. I think in the `Between` view we should just always show a single calendar below the two date range boxes (which might necessitate putting the `add a time` buttons into the boxes. I could maybe envision them being redone without the icon, in blue, and smaller, inside the boxes).
- Actually, for `Before`, `After`, `On`, and `Between`, does it make sense to just _always_ show the calendar below the input box? I guess the counterpoint is that hiding it makes it feel less heavy? I think that the calendar is helpful to have visible, even if I'm typing in the date, because it gives me context and confirms that the day/range I'm typing in is in fact the day of the week etc. that I think it is. [Kayak](https://www.kayak.com/) does this well, as an example.
- In the `Between` view, I think there could be an N-dash (–) (or the word `and`) between the two input fields to reinforce that it's saying "this through that."
- In `Previous`, `Next`, and `Current`, I can't seem to open the `day` dropdown
- I keep accidentally clicking the link that goes back to the field selector when I'm meaning to change the time filter type. Maybe that's just me being a spaz, or maybe the hierarchy is off?
- I really wish hitting `enter` committed the filter, especially for cases when I'm typing a value into a box
- Doesn't seem like there's an validation or error states on date input fields
- Nice enhancement would be some kind of [input masking](http://robinherbots.github.io/Inputmask/) for dates, so that you'd know the format we're looking for, or at least so you wouldn't have to bother typing slashes
- When switching to one of the options that uses an input field (like `Previous`, `After`, etc.), I wish the field got focused so I wouldn't have to click into it before I start typing. Same thing when clicking `add a time`: wish it would focus on the first of the two input boxes.
- Any reason why the `add a time` option defaults to `PM` instead of `AM`? AM is listed first.
- The way the popover menu has to resize every time I want to change the filter type (like from `On` to `Previous`) is a bit jarring. I know it's a little funny to have a dropdown float over a popover, but I feel like it might make things feel less twitchy.
- The left-alignment of the date inputs relative to the text of the filter type dropdown is off. For `Before` `After` and `On`, the box is too far left; and for `Between` it's indented too far to the right.
- The `Previous` selection is a little wonky with the way it does or doesn't pluralize `day(s)`: it pluralizes it when you've input 1, but the other types (e.g. 'Next') don't do that.
- Super minor detail, but when a filter is added that includes a specific hour, there should be a comma after the year, before the time. And we should be consistent about our treatment of `AM` and `PM` — it's capitalized in the popover menus, but lowercased in the filter. (Getting _really_ granular, I've also always been taught it should be either `AM` or `a.m.`, but never `am`)

**Comment by kdoh** [comment]
@metabase/core-developers Would be great to get a code review on this again given some of the updates.

**Comment by tlrobinson** [comment]
Looking pretty good.

Did you decide not to integrate the date formatting thingy you were showing me? I think it would be good to at least have a placeholder text (todays date in the correct format, maybe?)

I feel like the sub menus should have a little more distinctive style, it's hard to distinguish them in cases like this:

screenshot 2016-11-28 18 16 39

Or just use another popover? I know popovers in popovers are lame, but we do it in a couple places and it doesn't bother me too much. It would cut down on the jumpy popover resizing too.

I'm also not wild about the vertical layout. It's easier to comprehend

```
Next 1 Day
```

than 

```
Next
1
Day
```

**Comment by tlrobinson** [comment]
Code LGTM

**Comment by LukeAbell** [comment]
I'm testing out the latest version and it looks like the ability to filter by "Current Week" is missing now? Was that intentional? It's something we use regularly.

**Comment by kdoh** [comment]
@LukeAbell Heya. Good eyes, that was an oversight that got messed up in the shuffle. We're working on adding it back in and I'll update you here once it's merged (it'll definitely be in 0.21). Thanks for the feedback. Would love to hear any other thoughts on the new widget if you have them.

**Comment by kdoh** [comment]
@LukeAbell https://github.com/metabase/metabase/pull/3856 adds that back in. Thanks for poking at the new stuff.

**Comment by LukeAbell** [comment]
Thanks @kdoh! Just deployed a new jar and it's working great!

**Pull request merged**
