### PR TITLE
xrays: add table name to title for fields from joined tables

### PR DESCRIPTION
**Pull request by sbelak**
Adds table name to fields we pull from other tables.

Before:
Screenshot 2019-08-27 16 53 53
After:
Screenshot 2019-08-27 16 53 44

I'm not sure why the frontend changes the axis name to singular.  This should probably be unified before we ship it. cc @mazameli 

Implements #9696

### CODE REVIEW

**Comment by sbelak** [comment]
Updated to use the same algorithm as the FE

**Review by camsaul — APPROVED** [review]

**Comment by mazameli** [comment]
Tried this on the `Orders` table — shouldn't I be seeing `Sales per Product -> Title` in this card's title?

image

**Comment by sbelak** [comment]
@mazameli that title is hardcoded/hand crafted. Shall we move away from those in favour of generated ones?

**Comment by sbelak** [comment]
p.s. to view it in action, x-ray `Reviews`

**Review by mazameli — APPROVED** [review]
Looks good

**Pull request merged**
