### PR TITLE
Browsing | Improve mobile sidebar

### PR DESCRIPTION
**Pull request by kulyk**
The navigation sidebar doesn't look and feel good on the mobile in its current state, so this PR should make it better ✨ 

* for desktop/tablet the sidebar should work without any noticeable changes
* for mobile the sidebar will now overlap page content instead of pushing it like on the desktop
* the mobile sidebar will now take more horizontal space (`90vw`)
* the search input in the top app bar will become smaller for mobile to free up some space
* clicking on a bookmark/collection/link in the mobile sidebar will also close the sidebar
* clicking on the homepage link in the navbar or focusing the search input will close the sidebar
* added a basic in-out transition (width + opacity), need a look from the design team though

### To Verify

Ensure the bullet points below are actually true 😄 

### Demo

**Before**

sidebar-before

**After**

sidebar-after

### CODE REVIEW

**Comment by mazameli** [comment]
This was likely busted before, but it would be cool to fix how dashboard headings look. I'd expect:
- The title on one line
- Then the collection name and the last edited date on the next line
- Then the actions on a third line

image

**Comment by kulyk** [comment]
> This was likely busted before, but it would be cool to fix how dashboard headings look. I'd expect:
> 
> * The title on one line
> * Then the collection name and the last edited date on the next line
> * Then the actions on a third line
> 

@mazameli it's actually done in #21349, please take a look

**Comment by mazameli** [comment]
@kulyk awesome!

**Review by mazameli — APPROVED** [review]
Looks great. I saw one thing with tooltips acting sticky, but I suspect it's because I was using Chrome's web inspector so simulate a mobile device: https://www.loom.com/share/673c64d4c62c4534b68b1a12bcbdcd0b

**Review by kdoh — APPROVED** [review]

**Pull request merged**
