### PR TITLE
Restrict adding card of project with non null value

### PR DESCRIPTION
**Pull request by ghost**
###### Before submitting the PR, please make sure you do the following

- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### description

If you `POST api/dashboards/DashId/cards` with null card_id, you'll see the blank card like below. This is definitely unexpected behavior because it cannot be deleted in the GUI, and it's not that the card doesn't have permissions in the first place, it's just that it doesn't exist.

ss 4
ss 5

So I fixed by removing `s/maybe` here.

I also fix `;; TODO - param should be `card_id`, not `cardId` (fix here + on frontend at the same time)` as well.

### CODE REVIEW

**Comment by ulwlu** [comment]
> First-time contributors need a maintainer to approve running workflows

I wait for this approval.

**Comment by noahmoss** [comment]
> I wait for this approval.

Approved :)

Thanks for your contribution! Seems sensible to me, though it seems a few e2e tests are failing. (Ignore the driver tests, those are expected to fail on external PRs)

**Comment by ulwlu** [comment]
@noahmoss @camsaul 

Hi, thank you for commenting. 
While I look into the errors, I came to think that we shouldn't replace the name "cardId" into "card_id".

In my guess, This ToDo is made because database column name is `card_id`. However, As I look into the code like below,

https://github.com/metabase/metabase/blob/648996f69a88f7b71f1e8c11d8f1db7152628654/frontend/src/metabase/dashboard/components/DashboardHeader.jsx#L51

all the front-end code is unified to camel case, so it seems strange to fix only this part. Besides, this change is disruptive, and people who have been using it with `cardId` will be forced to modify their code.

My suggestion would be to just delete the ToDo comment and revert all this rename work, what do you think?

**Comment by ulwlu** [comment]
@noahmoss 

Hi, shall I add look into case or ignore this?
I believe this is not an error from code.

```
  Running:  databases/add.cy.spec.js                                                       (4 of 27)
07-21 21:53:40 ERROR driver.util :: Database connection error
org.postgresql.util.PSQLException: Connection to :5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

**Review by flamber — CHANGES_REQUESTED** [review]
Blocking, since this would prevent creating Textbox cards on a dashboard, which are nulls.

There's an issue open about `cardId` vs `card_id` - issue 16337

Version 0.40.0 allows you to remove cards like that:
image

Everything is slightly complex, as you have probably noticed. You should have a lot of failed Cypress tests regarding dashboards.
The Cypress error about `databases/add.cy.spec.js` are for some specific database tests, and would require having those databases available (https://github.com/metabase/metabase-qa)

I think we should close this PR - do you agree @ulwlu ?

**Comment by ulwlu** [comment]
@flamber 

> Version 0.40.0 allows you to remove cards like that:

If we can remove, then yes I agree with that.

**Pull request closed without merging**
