### PR TITLE
Chart setting fixes

### LINKED ISSUE #8755: Clicking on `choose fields` should open the `Data` tab
Ever since we changed the default tab for charts to the `Display` one, clicking on the `choose fields` button incorrectly opens the `Display` tab instead of the `Data` tab:

data-tab

### LINKED ISSUE #8784: Pie charts are broken in master, FE issues (flow?)
- Chrome 70
- Windows 10 1803
- PostgreSQL 10.5
- 0.31.0 (master)
- Ubuntu 18.04
- Internal DB is PostgreSQL 10.5 too

- *Repeatable steps to reproduce the issue*

Well, I'm not sure about the easy steps to reproduce, but every time i try to make a pie chart it hangs up at `TypeError: Cannot read property 'getHostNode' of null`, either in Developer Console of Chrome when question is already saved or creating the new one. Fully Frontend error. Also, if i try to change conditions and measures of Pie chart in settings, well... I can't get in settings, i get `TypeError: Cannot read property 'undefined' of undefined`. The full errors are:
```
ReactReconciler.js:60 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:60)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:381)
    at Object.getHostNode (ReactReconciler.js:60)
    at Object.updateChildren (ReactChildReconciler.js:111)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:209)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:308)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:295)
    at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:944)
    at ReactDOMComponent.updateComponent (ReactDOMComponent.js:758)
    at ReactDOMComponent.receiveComponent (ReactDOMComponent.js:720)
```

```
ChartSettingColorsPicker.jsx:25 Uncaught TypeError: Cannot read property 'undefined' of undefined
    at ChartSettingColorsPicker.jsx:25
    at Array.map (<anonymous>)
    at ChartSettingColorsPicker.render (ChartSettingColorsPicker.jsx:14)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:359)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:234)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:701)
-------
```

### LINKED ISSUE #8788: Can't display a pie chart with a binned numeric dimension
Just pulled master to make sure this hasn't been fixed recently. The error reads `Cannot read property ``getHostNode`` of null`. Breaking out by a binned date seems to work fine, and the problem seems to only be with Pie charts.

binned-pie

### PR DESCRIPTION
**Pull request by tlrobinson**
* [x] Resolves #8784 "Pie charts are broken in master"
* [x]  Resolves #8788 Can't display a pie chart with a binned numeric dimension
* [x] Resolves #8755 "Clicking on `choose fields` should open the `Data` tab"

### CODE REVIEW

**Comment by mazameli** [comment]
Looks good. Only funny thing I saw is that if I have 1 metric but 2 dimensions, I can now choose which field to use for the dimension in the pie chart (cool), but it looks like it's adding another secondary breakout with my other field. That's interesting but unexpected. 

Query:

screen shot 2018-10-26 at 3 44 27 pm

Result, with extra pie slices for each source per product category:

screen shot 2018-10-26 at 3 44 38 pm

**Comment by tlrobinson** [comment]
Yeah, the solution is to not use two breakouts for a visualization that doesn't support it.

**Comment by tlrobinson** [comment]
Or #8563

**Review by kdoh — APPROVED** [review]

**Comment by mazameli** [comment]
> Yeah, the solution is to not use two breakouts for a visualization that doesn't support it.

Sure. Not a blocker, just pointing it out because it feels as a user like you're fixing the problem by selecting a dimension, but then it selects both dimensions instead.

**Review by mazameli — APPROVED** [review]

**Comment by tlrobinson** [comment]
BTW this isn't a regression, it's just more obvious now because previously each slice was given a different color, whereas now all slices with the same dimension value get the same color. See the screenshot in #8563.

**Comment by mazameli** [comment]
Yeah, I figured as much. 👌

**Pull request merged**
