### PR TITLE
Operations guide breakout

### PR DESCRIPTION
**Pull request by victoriaspek**
All this does is break the operations guide into separate pages and add a little text to the Operations table of contents. No real content changes.

### CODE REVIEW

**Comment by mazameli** [comment]
I think breaking this up into separate pages makes sense.

Just wanted to call out that there are places were we're using the existing anchor links (e.g. on a lot of our [past release posts](https://metabase.com/blog/metabase-0.29/index.html) we have a link to the upgrading instructions). If we "break" those anchor links, users will just end up on the `Start` page. Do we need to do anything about this?

**Comment by salsakran** [comment]
so long as old posts don't 404, that's fine.

new deep links should go to the appropriate section though

**Review by mazameli — CHANGES_REQUESTED** [review]
Unless this is intended to be a multi-page guide, with links at the bottom of each page to the next page, I think that including numeric prefixes on doc file names is an anti-pattern. It makes it annoying and confusing if we ever decide to rearrange the TOC order or insert a new page anywhere other than at the end of the list. (I know we have them on doc pages in other, older guides, but that's from an earlier era where those actually were meant to be briefer multi-page guides rather than the more lengthy, exhaustive docs they've become.)

**Review by mazameli — APPROVED** [review]
Thanks for humoring my OCD. :D

**Pull request merged**
