### PR TITLE
Fix #11974 -- Respond with 200 code on public csv export

### LINKED ISSUE #11974: Status code to prevent G Sheet to load csv data
**Describe the bug**

If I am to include data into Google Sheets from metabase via the [card-export API](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apicardcard-idqueryexport-format) via the [IMPORTDATA](https://support.google.com/docs/answer/3093335) function, I get a `Could not fetch URL: ...` error. However, on my server I see the request and the expected 202 response.

It works fine on 0.34.1.

**Logs**

The proxy logs a 202 Accepted on the requested URL. I can not share the exact log, this it reveals a public URL.

**To Reproduce**
1. Go to any card.
2. Share it publicly.
3. Go to Google Sheets
4. Paste the `IMPORTDATA("YOUR_PUBLIC_CSV_URL")` into a cell.

**Expected behavior**

It should simply work, as described in #3772 

**Screenshots**

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "de",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1062-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6 (Ubuntu 11.6-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.2",
      "date": "2020-02-04",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**

 It isn't severe, but annoying for me. I am happy to help however I can.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #11984: Download in Excel not working in Edge (legacy)
**Describe the bug**
I try to download the query data in Edge on Windows, but nothing seems to happen.

**Logs**
Frontend (not sure if relevant):
`3SCRIPT5022: SCRIPT5022: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vendor.bundle.js (1,285943)
8TypeError: Unable to get property 'displayName' of undefined or null reference
column Naam joined-field,Gebruikers,field-id,250
new joined-field,Gebruikers,field-id,250
old field-id,250
`

Backend:
`x.x.x.x - - [25/Feb/2020:20:29:31 +0000] "POST /api/card/2/query/xlsx HTTP/1.1" 202 4554 "https://x.x.x/question/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362"`

**To Reproduce**
1. Go to any question.
2. Click on the download icon and choose Excel (maybe any other one).
3. Observe nothings happens.

**Expected behavior**
The file should download.

**Information about your Metabase Installation:**
Browser info below is my dev browser. The Edge version in question is above in the backend log.
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
Pretty bad, as we have to tell our clients not to use IE 11, but now also not Edge.

**Additional context**
I suspect a regression, as I think it used to work in a previous minor version. Edge on Mac does work. Chrome on Windows and Mac do, too.

### PR DESCRIPTION
**Pull request by robdaemon**
This replaces #12577 with an updated rebase and a target of `release-0.36.x`

Thank you, @codingjoe!

Resolves #11974

### CODE REVIEW

**Review by camsaul — CHANGES_REQUESTED** [review]
Just so we don't forget,

we need to tweak this to only change CSV/XLSX/JSON downloads to 200 but leave the normal stuff that goes thru the frontend client as 202s

**Comment by codingjoe** [comment]
Thanks @robdaemon, I am happy to see that frequent contributor has picked this up. If there is anything I can do from my side, please feel free to reach out.

**Review by camsaul — APPROVED** [review]
This LGTM... would it be easy to increase the test coverage around some of the stuff here? So we can have better than 50% coverage on this part of the code

**Comment by robdaemon** [comment]
> This LGTM... would it be easy to increase the test coverage around some of the stuff here? So we can have better than 50% coverage on this part of the code

I'll see what I can do - I'm going to finish up another PR first, and the come back to increasing this test coverage

**Pull request merged**
