### PR TITLE
Root Collection Permissions [WIP]

### PR DESCRIPTION
**Pull request by camsaul**
Stage 3 of "Spaces". Follow-on to #7451 

Basically "Root Collection Read Perms" just means you have read perms for things with no `collection_id`. I think this excludes Collections with no parent Collection because Collection perms are separate

###### Backend:

- [x] Finish removing references in code to `/db/id/native/read` permissions. Native read permissions are deprecated, predictably, because data access permissions no longer control existing Cards
- [x] There are literally hundreds of tests to update/rework
    - [x]  1  failure in `metabase.models.collection-test`
    - [x]  3  failures in `metabase.api.collection-test`
    - [x]  3  failures in `metabase.models.card-test`
    - [x] 25  failures in `metabase.models.permissions-test`
    - [x] 31  failures in `metabase.api.card-test`
    - [x] 10  failures in `metabase.api.dashboard-test`
    - [x]  1  failure in `metabase.api.field-test`
    - [x]  8  failures in `metabase.api.pulse-test`
    - [x] 45  failures in `metabase.permissions-test`
    - [x] 16  failures in `metabase.api.alert-test`
    - [x]  1  failure in `metabase.api.activity-test`
    - [x]  1  failure in `metabase.query-processor.middleware.results-metadata-test`
    - [x]  1  failure in `metabase.sync-database.analyze-test`
    - [x]  2  failures in `metabase.query-processor-test.nested-queries-test`
    - [x]  4  failures in `metabase.api.dataset-test`
    - [x]  9  failures in `metabase.api.x-ray-test`
- [x] I'm pretty sure we need to rework `GET /api/collection/root` to use `effective_location`s rather than `collection_id = nil`
- [x] API needs to let you grant/modify Root Collection permissions

##### Frontend:

- [x] Need UI for granting/revoking ROOT COLLECTION read permissions
- [x] Need to remove "Native Read Permissions" from the data access permissions grid
- [x] Other updates as appropriate for data access perms to make sure it doesn't imply they affect Cards anymore
- [x] Need to update some integration tests that no longer make sense that are failing with messages like 
    ```
    Alerts › alert list for a question › as a non-admin / normal user › should let you see also other alerts where you are a recipient
    ```

### CODE REVIEW

**Comment by salsakran** [comment]
@mazameli wrt to `Alerts › alert list for a question › as a non-admin / normal user › should let you see also other alerts where you are a recipient`
should a user who is signed up for an alert be able to see that question if they don't have collection permissions to see it? does that even make sense?

**Comment by mazameli** [comment]
@salsakran No, if you're signed up for an alert on a question you don't have View access for, you shouldn't magically be given View access to that question. But my reading of that line is that, provided you do have view access to that question, if you click on the alerts button, you should see all alerts you have set up on that question yourself as well as any alerts an admin has added you to.

**Comment by camsaul** [comment]
@metabase/core-developers any objections to me merging this

**Comment by mazameli** [comment]
The root-level permissions themselves seem to be working correctly. Nice job, Cam.

Only funny things I see are:
1. I don't think we should be showing the Edit This Collection action for the root-level collection (doesn't really make sense to change its name or description IMO)
2. We definitely shouldn't be showing the archive action for the root-level collection (clicking the action doesn't do anything thankfully).

screen shot 2018-06-06 at 10 18 35 am

screen shot 2018-06-06 at 10 18 30 am

**Pull request merged**
