### PR TITLE
Add `-Dclojure.main.report=stderr` to `:dev` alias

### PR DESCRIPTION
**Pull request by camsaul**
Sometimes Clojure fails with errors like

```
Syntax error (ClassNotFoundException) compiling at (********/driver/sqlite_test.clj:230:16).
sql.qp-test-util

Full report at:
/tmp/clojure-12125931956503910528.edn

Exited with code exit status 1
CircleCI received exit code 1
```

Not very easy to debug in CI. This PR sets an option so this error log is printed to standard error instead

### CODE REVIEW

**Comment by camsaul** [comment]
Ok, verified that it works. See https://app.circleci.com/pipelines/github/metabase/metabase/33351/workflows/e9ccdb8f-e1f4-47d3-a2f0-aaa113acfa45/jobs/1719468/artifacts

**Comment by dpsutton** [comment]
Oh this is a nice solution. I would have set `"clojure.main.report"` to be `"stderr"` and just had it inline here. Wouldn't have thought to upload it.

**Review by dragonsahead — APPROVED** [review]
```
luis@luis-Legion-S7-15ACH6:~/Documents/metabase$ git checkout store-test-failure-reports
Switched to branch 'store-test-failure-reports'
Your branch is up to date with 'origin/store-test-failure-reports'.
luis@luis-Legion-S7-15ACH6:~/Documents/metabase$ circleci config validate
Config file at .circleci/config.yml is valid.
```
Seems like this won't break anything, so I'm giving the green light

**Comment by dpsutton** [comment]
And just for reference, it can be specified as so:

```clojure
/tmp
❯ clojure -M -e "(+ 1"
Execution error at clojure.main/main (main.java:40).
EOF while reading, starting at line 1

Full report at:
/var/folders/1d/3ns5s1gs7xjgb09bh1yb6wpc0000gn/T/clojure-8298587731156933895.edn

/tmp
❯ clojure -J-Dclojure.main.report=stderr -M -e "(+ 1"
{:clojure.main/message
 "Execution error at clojure.main/main (main.java:40).\nEOF while reading, starting at line 1\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.RuntimeException,
  :clojure.error/line 40,
  :clojure.error/cause "EOF while reading, starting at line 1",
  :clojure.error/symbol clojure.main/main,
  :clojure.error/source "main.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.LispReader$ReaderException,
    :message
    "java.lang.RuntimeException: EOF while reading, starting at line 1",
    :data {:clojure.error/line 2, :clojure.error/column 1},
    :at [clojure.lang.LispReader read "LispReader.java" 314]}
   {:type java.lang.RuntimeException,
    :message "EOF while reading, starting at line 1",
    :at [clojure.lang.Util runtimeException "Util.java" 221]}],
  :trace
  [[clojure.lang.Util runtimeException "Util.java" 221]
   [clojure.lang.LispReader readDelimitedList "LispReader.java" 1405]
   [clojure.lang.LispReader$ListReader invoke "LispReader.java" 1243]
   [clojure.lang.LispReader read "LispReader.java" 285]
   [clojure.lang.LispReader read "LispReader.java" 216]
   [clojure.lang.LispReader read "LispReader.java" 210]
   [clojure.core$read invokeStatic "core.clj" 3767]
   [clojure.core$read invokeStatic "core.clj" 3742]
   [clojure.main$eval_opt$fn__9220 invoke "main.clj" 487]
   [clojure.main$eval_opt invokeStatic "main.clj" 487]
   [clojure.main$eval_opt invoke "main.clj" 482]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "EOF while reading, starting at line 1"}}

Execution error at clojure.main/main (main.java:40).
EOF while reading, starting at line 1



/tmp
❯ clojure -M --report stderr -e "(+ 1"
{:clojure.main/message
 "Execution error at clojure.main/main (main.java:40).\nEOF while reading, starting at line 1\n",
 :clojure.main/triage
...
```

**Comment by camsaul** [comment]
@dpsutton I changed this to set a Java option instead, please 👀

**Review by dpsutton — APPROVED** [review]

**Pull request merged**
