### PR TITLE
WIP - BigQuery JDBC Driver

### PR DESCRIPTION
**Pull request by sabino**
This is a WIP

I am currently having some trouble with the execute-query part. Tried forcing the autocommit parameter, but I am either setting it wrong or the driver is not working as expected.

Looked for documentation for the Simba BigQuery driver but there is no mention about autocommit.
I don't know if this will get merged (and I know there are no tests written right now) but I hope someone can help making this work.

Currently it is listing all the schemas, its tables and the fields.
The problem is when you run a query.

Got the driver [here](https://cloud.google.com/bigquery/partners/simba-drivers/)

https://github.com/metabase/metabase/issues/4432

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)

### CODE REVIEW

**Comment by sabino** [comment]
Btw I've tried adding the Additional Projects parameter (no documentation for JDBC - only [ODBC](https://www.simba.com/products/BigQuery/doc/ODBC_InstallGuide/mac/content/odbc/bq/options/ui/additionalprojects.htm) - but it works for JDBC as well) , but since Metabase expects a single "database" it doesn't work. Maybe if added multidatabase support it could work. As a workaround the project could be injected to the schema (very ugly tho)

**Comment by sabino** [comment]
I had no success trying to query using the JDBC so I've merged with the current Driver, that uses the API. It's kinda wierd since you have to specify the login info like the current driver AND the service account with the JSON file, but it's working so far.

I will leave this here, so if someone want to take a look and try to fix it to use only the JDBC will be great.

My next step is to customize the database-describe so it can fetch for more than one database.

**Review by robertoduessmann — APPROVED** [review]

**Comment by satyadeepk** [comment]
Hi @sabino, I am facing couple of issues:
1. When querying "Raw data" under view section in query builder, I get this error.
```
Assert failed: (or field index (and (seq schema-name) (seq field-name) (seq table-name)) (log/error "Don't know how to alias: " this))
```
2. I mapped Foreign Key on a table in Data model and trying to filter on a field from the foreign key table - it gives error: `Column name id is ambiguous at [2:118]` due to the `ON` clause.



This is the SQL query that was generated. 
```
SELECT  COUNT(*) AS `count`
FROM  `mysql.user_post`
LEFT JOIN `mysql.users` `mysql.users__via__users_id`
ON  users_id = id
WHERE  `users__via__users_id.first_name` = 'Example user'
```

How can I fix the `ON` clause to have qualified field names like ?
```
ON  `mysql.user_post`.`users_id` = `users__via__users_id`.`id`
```

This is my first time with Clojure. If you can give me pointers on how to fix the driver, I can try.

**Comment by sabino** [comment]
Hey @satyadeepk thanks for the info. Turns out that this branch was not up to date.

Would you mind testing it again?

**Comment by satyadeepk** [comment]
Hey @sabino, thanks for the commit!
1. A different issue is now occurring with "Raw data" on tables with foreign keys.
```
Error: Column name id is ambiguous at [2:262]
```

This is the generated query:
```
SELECT
  description AS description,
  hash_tag AS hash_tag,
  id AS id,
  title AS title,
  users_id AS users_id,
  users__via__users_id.first_name AS first_name
FROM
  mysql.user_post
LEFT JOIN
  mysql.users users__via__users_id
ON
  users_id = users__via__users_id.id
```

2. Issue 2 above is fixed now! Aggregations (count, sum etc) are working fine on tables with foreign key 😄 
This is the generated query which works.
```
SELECT
  COUNT(DISTINCT users__via__User_Id.id) AS count,
  Is_New_User AS Is_New_User
FROM
  mixpanel.event
LEFT JOIN
  mysql.users users__via__User_Id
ON
  User_Id = users__via__User_Id.id
GROUP BY
  Is_New_User
```

**Comment by tlrobinson** [comment]
Hey all,

Thank you for this PR and apologies for the long delay responding. We've recently done some work to support drivers as plugins in Metabase and as of the next release (v0.32) we will be asking driver developers to first publish new drivers in their own repositories (typically named `metabase-*-driver`). If the driver fully passes the driver tests we will link to it from our documentation, and if a driver gains significant usage we will consider merging it into Metabase itself.

Here is some documentation about publishing a driver as a plugin in a separate repository: https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#drivers-shipped-as-3rd-party-plugins

Here are two example drivers: https://github.com/metabase/sudoku-driver https://github.com/metabase/crate-driver

We still have some work to do on the documentation. You can follow progress and provide feedback on that here: https://github.com/metabase/metabase/issues/9348

Thank you.

**Comment by allan-simon** [comment]
@tlrobinson  does this mean this PR should be re-created as a dedicated plugin repository ?

**Pull request closed without merging**
