### PR TITLE
FE - Make editing table metadata not rely on the full database metadata

### PR DESCRIPTION
**Pull request by ranquild**
Epic https://github.com/metabase/metabase/issues/30190

Changes:
- Uses endpoints that fetch data by schema/table instead of fetching full db metadata
- Removes special data model entities and uses `metabase-lib`
- Adds `getMetadataUnfiltered` for `getObjectUnfiltered` selectors in the entities framework to get the full graph of entities without removing hidden tables/fields etc
- Adds jest tests
- Unskips and fixes e2e tests

Markup is not changed, however data flow in the component tree is different. Here is the mapping between the new components and the old ones:

- `FieldVisibilityPicker` from `ColumnItem`
- `MetadataBackButton` from `FieldApp`
- `MetadataEditor` from `MetadataEditorApp`
- `MetadataHeader` from `MetadataHeader`
- `MetadataSchemaList` from `MetadataSchemaList`
- `MetadataSection`, `MetadataSectionHeader` from `Section`
- `MetadataTable` from `MetadataTable`
- `MetadataTableList` from `MetadataTableList`
- `MetadataTablePicker` from `MetadataTablePicker`
- `MetadataTableSchema` from `MetadataSchema`
- `MetadataTableSettings` from `TableSettingsApp`
- `MetadataTableSyncWarning` from `TableSyncWarning`
- `SemanticTypeAndTargetPicker` from `ColumnItem`

How to verify:
- Make sure updated data model pages never load all tables with their fields at once
- Hiding tables, changing fields, data model permissions (EE) should still work

Please note that the field settings page (with value remapping etc) is not yet changed.

Screenshot 2023-04-20 at 23 51 12

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30204)

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
@ranquild I found one issue with schemas, can you please have a look and cover this case with a spec too:
<video src="https://user-images.githubusercontent.com/14301985/234397205-28c3d418-b99f-4fa1-a08f-b3f45dfd19e5.mov" />

**Review by alxnddr — COMMENTED** [review]
> Reviewed 55 of 78 files at r1, 31 of 31 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30204)* status: all files reviewed, 1 unresolved discussion (waiting on @ranquild)

___
*[`frontend/src/metabase/admin/datamodel/metadata/components/MetadataBackButton/MetadataBackButton.styled.tsx` line 10 at r2](https://reviewable.io/reviews/metabase/metabase/30204#-NTu2rfU9fU4tL5TDTp3:-NTu2rfU9fU4tL5TDTp4:b3brdxt) ([raw file](https://github.com/metabase/metabase/blob/30eff442f4b3f1fbcfa576e3c5bffb55d2e030b4/frontend/src/metabase/admin/datamodel/metadata/components/MetadataBackButton/MetadataBackButton.styled.tsx#L10)):*
> ```XML
>   align-items: center;
>   padding: 1rem;
>   border-radius: 99px;
> ```

`border-radius: 50%;`

**Comment by calherries** [comment]
@alxnddr I can't reproduce the permissions issue locally, even following your instructions. Do you know what I could be doing differently? Here's my setup

All users:
image

And my "Managers" group permissions for sample database:
image

If I login as a user in the managers group, it's works fine. There's even a test on the backend that tests this endpoint works correctly, so I'm stumped. There must be something different about your local permissions state I'm not seeing 

https://github.com/metabase/metabase/blob/30eff442f4b3f1fbcfa576e3c5bffb55d2e030b4/enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj#L354-L369

**Comment by ranquild** [comment]
@calherries you can run `data-model-permissions.cy.spec.js` and see the spec failing for the data model case

**Comment by ranquild** [comment]
@alxnddr I've added a spec for the case with all tables hidden in a schema (currently fails in this PR because the BE needs to be changed). As for the second issue with data model permissions there is also a e2e spec that fails. Wdyt about merging this FE PR to the integration branch? We would merge BE fixes to the integration branch and merge it to master when all tests are green.

**Comment by alxnddr** [comment]
@calherries AFAIR I did not allow All Users to have any access to this db:
<video src="
https://user-images.githubusercontent.com/14301985/234699509-e26037c2-d703-44c2-a883-74dc0ed19aff.mov
" />

**Review by alxnddr — APPROVED** [review]
FE looks good, tests will be unskipped

**Comment by calherries** [comment]
@alxnddr I found that bug yesterday, the fix is merged into [30190-data-model-performance](https://github.com/metabase/metabase/tree/30190-data-model-performance).

**Pull request merged**
