### PR TITLE
🍒  Manual Backport (#33066)

### PR DESCRIPTION
**Pull request by iethree**
trying to add the whole spec in 🤞 

backport: #33066

### CODE REVIEW

**Comment by iethree** [comment]
interesting. The click-outside-the-popover issue is still broken in the release branch, but working in master. Looking into what I can backport to get it good in the release branch

**Review by ranquild — APPROVED** [review]

**Review by JesseSDevaney — COMMENTED** [review]
@iethree Are you waiting to merge this until you get that 

> click-outside-the-popover issue

fixed in the release branch and the tests un-skipped?

**Comment by JesseSDevaney** [comment]
@iethree @nemanjaglumac This PR did introduce some skipped tests into the release branch. Are we planning to fix the issue that caused these tests to be skipped and un-skip them in a future PR, or are we going to leave the skipped tests in there?

**Comment by iethree** [comment]
I think it's fine to leave them there. if we figure out what to backport to fix the popover thing we can un-skip it

**Pull request merged**
