### PR TITLE
Static multi-series Line/Area/Bar chart

### LINKED ISSUE #18688: Implement combo static viz chart front-end
Add combo chart static viz renderer so that the back end will be able to use it

### LINKED ISSUE #18783: Support multiple series for line/bar/area
All line/bar/area static viz renderers should support multiple series provided by the following BE task https://github.com/metabase/metabase/issues/18782

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/18783
Closes https://github.com/metabase/metabase/issues/18688

Configurable generic static line/area/bar chart that aims to replace existing static visualizations. 
Key differences from the existing line/area/bar static visualizations:
- Supports multiple series of any visualization type
- Shows legend
- Supports negative values for bars and areas
- Shows goal line

Screen Shot 2021-11-26 at 20 48 28

### How to verify
- There is a demo on [the internal page](http://localhost:3000/_internal/static-viz)

CI is red because of prettier. After https://github.com/metabase/metabase/pull/19062 gets approved, I will merge it with https://github.com/metabase/metabase/pull/18778 and rebase this PR.

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Review by ranquild — CHANGES_REQUESTED** [review]
1. Doesn't work correctly when bars have identical series names. Bars are collapsed.
2. There are issues with displaying series with both positive and negative values
Screen Shot 2021-11-24 at 2 58 58 pm

3. A question about the API. Would it make sense to accept `rows` in the same format as in `/api/card/:id/query` and `visualization_settings` from `api/card/:id`?

**Review by kdoh — COMMENTED** [review]
The internal preview looks like I'd expect. 👍  Just looks like there are some edge cases to take account of, and we'll want to put this through it's paces in the RC / bug bash process to see if there are any others we find.

**Comment by alxnddr** [comment]
@ranquild, 
> 1. Doesn't work correctly when bars have identical series names. Bars are collapsed.
Fixed, thanks!

> 2. There are issues with displaying series with both positive and negative values
I initially synchronized zeros on both Y axes but then reverted because it got a bit more complicated when I wanted to make "nice" ticks values. I decided to put aside it for now since it required more time and it is not a regression compared to our non-static visualizations:
Screen Shot 2021-11-24 at 19 03 30

> 3. A question about the API. Would it make sense to accept `rows` in the same format as in `/api/card/:id/query` and `visualization_settings` from `api/card/:id`?
The idea was to make a truly declarative XYChart that does not transform data. Some of our `visualization_settings`, such as having more than > dimensions or interpolating missing values with zero, are actually data transformations. I wanted to implement settings/data transformation in `LineAreaBarChart` that uses `XYChart`, but @howonlee told me that he is already close to providing data in the suitable format for `XYChart`. However, if it does not work for some reason, I'd write data transformations inside the `LineAreaBarChart` chart.

**Comment by ranquild** [comment]
> The idea was to make a truly declarative XYChart that does not transform data. Some of our `visualization_settings`, such as having more than > dimensions or interpolating missing values with zero, are actually data transformations. I wanted to implement settings/data transformation in `LineAreaBarChart` that uses `XYChart`, but @howonlee told me that he is already close to providing data in the suitable format for `XYChart`. However, if it does not work for some reason, I'd write data transformations inside the `LineAreaBarChart` chart.

Got it, makes sense. Given the time we have left until the release, I'd stick with a safer option atm.

**Review by ranquild — APPROVED** [review]

**Pull request merged**
