### PR TITLE
Fix 'TypeError: _this2._input.focus is not a function' error

### PR DESCRIPTION
**Pull request by tlrobinson**
Fix for `ListSearchField` not focusing correctly, and throwing an error in the JS logs.

### CODE REVIEW

**Review by kdoh — COMMENTED** [review]
We might want to try and have this be a little more self documenting by changing the component name to `BlurInput` or something. It wouldn't naturally occur to me that using our `Input` component might cause an issue like the one this solves.

**Comment by tlrobinson** [comment]
Yeah, though the bug isn't really specific to this component. Wrapper components like this don't automatically proxy their props or methods (e.x. `blur`) to their wrapped components so you can't assume all the features of `button` are exposed in `Button` either, for example.

**Comment by tlrobinson** [comment]
Also this `Input` component was written a long time ago before I fully understood controlled vs. uncontrolled React components. If we want to have a `<Input>` component like we have for `<Button>` it should probably be re-written, and automatically add our default input classes, etc.

**Comment by kdoh** [comment]
Gotcha. Yeah I think that'd be ideal.

**Pull request merged**
