### PR TITLE
Finish consolidating column to field ref functions

### LINKED ISSUE #12073: [0.35 blocker] `coalesce` function doesn't work correctly in the notebook
I'm either misunderstanding `coalesce` or it's broken. Here I'm using it to try and create a custom column called "Habits Column" and I'm expecting it to return for each row either the value of `Uses Drugs?`, `Diet`, `Drinks?`, or the string "No answer" if all the others are empty. 

The main oddity is that the resulting column is named "Uses Drugs?" instead of the expected "Habits Column". The second problem is that I'm still seeing empty cells in this new column, but I'm guessing that's because one of the columns (maybe the first one) actually contains whitespace instead of null, so it's technically not empty?

image

### PR DESCRIPTION
**Pull request by tlrobinson**
We started consolidating column to field ref functions when we added `field_ref` to columns. This completes that.

Resolves #12073

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]
LGTM. Is there any way this could break saved viz settings? e.g. if something was saved under a field-id previously?

**Comment by tlrobinson** [comment]
> LGTM. Is there any way this could break saved viz settings? e.g. if something was saved under a field-id previously?

I don't *think* so but maybe I'll try testing against all our saved questions on stats.

**Comment by tlrobinson** [comment]
I tested the old and new versions of `keyForColumn` and the only difference is `joined-field` columns were incorrectly using `field-id` instead of `joined-field`. So this would break column settings on joined fields, which would be unfortunate. I'm not sure how to best handle that.

Ultimately I think we need a way to migrate these. Related to #11829.

**Comment by paulrosenzweig** [comment]
I'm not sure how many hurdles it's worth jumping to avoid that, but we could "migrate on update", right? i.e. keep `fieldRefForColumnWithLegacyFallback `, and when reading check that key as a fallback. We'd always save under the new (`fieldRefForColumn`) key. That does add some confusing code that we can never remove though...

Yeah a real settings migration system would be huge. Could that be hacked together in the short-term using db migrations? The migration wouldn't touch columns but instead parse the JSON, update, and re-serialize it. It would just be a way to have something run once.

**Comment by tlrobinson** [comment]
@paulrosenzweig I think one problem is we can't migrate to the new column key without the column's `field_ref`, which I think requires running the query. Or maybe we don't actually need to run the query, just the query processor.

**Review by mazameli — APPROVED** [review]
Seems like it fixes the behavior. 👍

**Comment by tlrobinson** [comment]
Changing this to WIP until we figure out how to handle `joined-field` column settings migration.

**Comment by tlrobinson** [comment]
@paulrosenzweig I decided to kick the can down the road a bit longer and just add a special case for the differing case. I also added some tests and validated them against the previous version, so we at least have that written down.

**Comment by paulrosenzweig** [comment]
👍 makes sense to me!

**Pull request merged**
