### PR TITLE
Allow specifying the server cert chain for MongoDB

### LINKED ISSUE #3877: Connect MongoDB with SSL and self-signed certificate
Still cannot use metabase with mongodb hosted on compose.io.

Reason:

Compose.IO uses self-signed SSL certificates for each deployment.

Therefore need a way to supply a custom pem file for this.

Without it I get this error:

```
12-06 17:50:48 ERROR metabase.driver :: Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=aws-eu-west-1-portal.X.dblayer.com:XXXXX, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}}] 
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or :+1: comment

### PR DESCRIPTION
**Pull request by robdaemon**
This will allow the user to specify the server's certificate chain (the
public CA certs) or the server's private key if it's a self-signed cert
with no CA.

Resolves #3877

[ci mongo]

### CODE REVIEW

**Comment by robdaemon** [comment]
Tested locally against MongoDB in a container with certificates generated by `cfssl` - this still needs an integration test.

**Comment by robdaemon** [comment]
One thing you may see when testing locally is that the SSL test for the mongo driver will fail if you don't update your mongo launch script to match what the CI config has now.

**Comment by mazameli** [comment]
Is the `Server SSL certificate chain` input box necessary or relevant if `Use a secure connection (SSL)?` is turned off? If not, we should only show it if that toggle is turned on. 

image

For reference, that's how the `Use an SSH-tunnel for database connections` setting works: it reveals additional settings when turned on.

**Review by camsaul — APPROVED** [review]
LGTM

**Comment by robdaemon** [comment]
> Is the `Server SSL certificate chain` input box necessary or relevant if `Use a secure connection (SSL)?` is turned off? If not, we should only show it if that toggle is turned on.

Yep, you're right, let me fix that

**Comment by robdaemon** [comment]
@mazameli - okay, that UI bug is fixed!

**Comment by mazameli** [comment]
@robdaemon Sweet, seems good to me. 👍

**Comment by robdaemon** [comment]
```Testing expectations
Total old-style expectations tests: 1907
Total namespaces still using old-style expectations tests: 125
Who has the most? ********.models.collection-test with 175 old-style tests

FAIL in (no-new-expectations-style-tests-test) (expectations.clj:134)
Don't write any new tests using expect!
expected: (<= total-expect-forms 1889)
  actual: (not (<= 1907 1889))

FAIL in (no-new-expectations-style-tests-test) (expectations.clj:135)
Don't write any new tests using expect!
expected: (<= total-namespaces-using-expect 124)
  actual: (not (<= 125 124))```

I didn't add any new `expect` tests?

**Comment by camsaul** [comment]
@robdaemon that's weird. I only have 1889 `expect` tests locally. Let me try your branch

**Comment by camsaul** [comment]
@robdaemon oh I figured it out. That number is not taking driver tests in to account. I'll fix

**Comment by camsaul** [comment]
So the test coverage stuff only counts coverage when running without any drivers. So it would be good to add some tests for things like `socket-factory-for-cert` that aren't tested anywhere except indirectly in the Mongo tests

**Comment by robdaemon** [comment]
There's not a ton that can be tested in `socket-factory-for-cert` because of the visibility of things inside `SSLSocketFactoryImpl`, but I did add a test that it doesn't fail and returns an `SSLSocketFactory` as expected.

**Pull request merged**
