### PR TITLE
refactor app mount point to remove flex context by default

### PR DESCRIPTION
**Pull request by kdoh**
setting a global display context of flex seems a bit aggro for an app as big as metabase. this PR removes that context by default and is also meant to clean up and refactor any views that may have relied on this context to set their own context. context. context. context.
#### views needing refactor after removing the context
- [x] query builder
- [x] object detail 
- [x] logged out auth
- [x] admin panel views with sidebar elements
- [x] setup flow?

### CODE REVIEW

**Comment by agilliland** [comment]
I haven't seen anything major and the setup flow works fine for me, but I am seeing several of our sidebars not really stretching to their expected height.

For example, on the homepage ...

screen shot 2016-03-07 at 2 58 11 pm

I'm seeing the same thing in some of the data model pages where the sidebar is growing/shrinking based on the # of tables, or when you search for a table the sidebar shrinks.  So we should look at that stuff and make sure it's working as desired.

**Comment by kdoh** [comment]
Interesting. I'll look into that. Haven't noticed that behavior in the screenshot locally but maybe I'm running into a cache issue. Seeing the admin sidebar problem now though.

**Comment by agilliland** [comment]
The problem with the homepage will only manifest itself is the main activity feed has nothing in it.  So the screenshot i did was right after a fresh install.  After adding a couple cards things stretched out and looked normal.

**Comment by agilliland** [comment]
K, this is looking really close.  the admin section looks pretty solid now, I'm just seeing a few other small items.

* The sidebar on the homepage doesn't extend beyond the starting page height.
* On Safari the QB is somehow missing some padding/margin at the top and is noticeably closer to the navbar.
* The sidebar in the Data Model section doesn't contain all the content properly.
screen shot 2016-03-08 at 6 09 47 pm

**Comment by agilliland** [comment]
Note that last one existed in the last release, so it isn't cause by this PR

**Comment by kdoh** [comment]
@agilliland double check my work here but I think it should be g2g now.

**Comment by agilliland** [comment]
something isn't right with the saved questions page, but everything else looks good.

**Comment by agilliland** [comment]
this looks good now.  merging.

**Pull request merged**
