### PR TITLE
Fix image width on Text Cards to use max-width

### LINKED ISSUE #15356: Dashboard Textbox images are 100% width
**Describe the bug**
Dashboard Textbox with markdown images are 100% width

**To Reproduce**
1. Go to dashboard and add a textbox, make it full width and input the following in the textbox:
``
2. Enjoy the 120x120 image in all it's glory:
image

**Expected behavior**
Instead of `width: 100%;` it should just be `max-width: 100%;`

**Information about your Metabase Installation:**
Tested 0.36.8 thru 0.38.2

**Additional context**
Seems like it might have been a regression, since #10857 talks about having problems with making the images scale.

### PR DESCRIPTION
**Pull request by nat-casey**
This fixes the bug identified in https://github.com/metabase/metabase/issues/15356 

### Before
Screen Shot 2021-04-15 at 4 51 25 PM

### After
Screen Shot 2021-04-15 at 4 38 45 PM

### CODE REVIEW

**Comment by nat-casey** [comment]
@flamber @camsaul here is a small fix for the css bug in #15356, let me know if there is anything else I can do to get this change pushed through. Thanks!

**Review by alxnddr — APPROVED** [review]
@nat-casey thanks for taking care of it!

**Comment by alxnddr** [comment]
@nat-casey could you please sign the [Individual Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSfc9GWyJ3F9U_4NzHLeTblgtog1FKtG3CjLshE4FAAKSdvNoQ/viewform)?

**Comment by nat-casey** [comment]
@alxnddr done!

**Comment by nat-casey** [comment]
Once this goes through, is there an ETA on when we will be able to see this change? (We're using Metabase Enterprise)

**Comment by alxnddr** [comment]
@nat-casey, the change will be included in the next release 0.39, which is likely to happen on Monday.

Thank you for your contribution!

**Comment by alxnddr** [comment]
Merged as a part of https://github.com/metabase/metabase/pull/15653

**Pull request closed without merging**
