### PR TITLE
Fix drill-through popover look for native models

### PR DESCRIPTION
**Pull request by kulyk**
### To Verify

1. Open a native dataset
2. Click any column header in the results table
3. Ensure the "sort" action buttons don't look weird
4. Open a saved native question (not a dataset)
5. Click any column header in the results table
6. Ensure you can see a single "Column formatting" action, not only a gear icon as in (#14027)

### Demo

**Before**
CleanShot 2021-11-30 at 18 12 22@2x

**After** 
CleanShot 2021-11-30 at 18 21 44@2x

### CODE REVIEW

**Comment by mazameli** [comment]
A nice touch would be to give these column headings `cursor: grab;` to show you can reorder them.

image

**Comment by mazameli** [comment]
Hmm, here's an odd thing: with this SQL-based dataset, before I use the sort action I get a different set of available actions than after I sort.

image

image

**Comment by mazameli** [comment]
The above seems to be the case with all the columns in that dataset. If this is an existing bug, then I'm cool with merging this PR just for the visual fixes, which look great.

**Comment by kulyk** [comment]
@mazameli great catch. I have an idea for the fix, but I'll need to slightly how we turn questions into datasets and vice-versa. Moving this to draft for now

**Comment by kulyk** [comment]
@mazameli this should be now fixed

**Comment by mazameli** [comment]
Nice! I'll give it a look shortly.

**Review by mazameli — APPROVED** [review]
🎉

**Review by alxnddr — APPROVED** [review]

**Pull request merged**
