### PR TITLE
Custom expression editor: use lexical-based highlighting

### PR DESCRIPTION
**Pull request by ariya**
This reduces the memory pressure since the spans (for the contentEditable) will be flat (before, they construct a tree).

It doesn't completely solve #16094, but it does provide some noticeable performance improvements. Moreover, this offers another step towards eliminating the dependency on the syntax tree (and hence, the parser) on the UI-side of custom expression.

To experiment with it, follow the steps in #16094:

**To Reproduce**
1. Ask a question, Custom question
2. Sample Dataset, Reviews table
3. Filter, Custom Expression
4. Type (or better: copy + paste) `contains([Product → Vendor], "Lorem ipsum dolor sit amet") OR` repeatedly

image

**Another illustration**
1. Ask a question, Custom question
2. Sample Dataset, Products table
3. Custom Column, and type `case([Category] = "test", 1, 2)`
4. Open DevTools and select the custom expression with the element Inspector

_Before this PR:_

The tokens in the expression are represented by a number of `<span>` in a tree (which can be quite deep):

image

_After this PR:_

The tokens in the expression are represented by a number of `<span>` in a flat list:

image

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
It seems like it's doing something to the color formatting, where functions used to be black:
image

I can feel it's faster now, but still somewhat slow when the CE gets big.

Is it the same performance problem as this, where there's a slowdown after typing the comma?:
`coalesce([Category]` type the comma
`coalesce([Category], [Category]` type the comma

**Comment by ariya** [comment]
> It seems like it's doing something to the color formatting, where functions used to be black: image

Yup, don't worry as I'm not completely done with the colorization of different tokens.

> I can feel it's faster now, but still somewhat slow when the CE gets big.
> Is it the same performance problem as this, where there's a slowdown after typing the comma?: `coalesce([Category]` type the comma `coalesce([Category], [Category]` type the comma

The remaining source of that slow-down is custom expression trying to do extensive validation (still quadratic to the length of the expression), subject to some follow-up performance tweak/rewrite.

**Comment by ariya** [comment]
@metabase-bot run visual tests

**Review by flamber — APPROVED** [review]
Looks great. Not seeing any problems - besides the known ones ;-)
And since there's more work ahead, then let's move on.

**Review by alxnddr — APPROVED** [review]
LGTM 👍

**Pull request merged**
