### PR TITLE
Proposal: move semantic types into separate `:Semantic/` type hierarchy

### PR DESCRIPTION
**Pull request by camsaul**
Investigation towards a small refactor that will let us do a little more validation in the API layer and sync process and prevent Metabase from getting into weird/invalid states where things break. Related to the overall #14054 project.

This PR moves our semantic types (e.g. `:type/Income`) into their own hierarchy (e.g. `:Semantic/Income`), separate from the data type (base type/effective type) hierarchy. See the docstring I added in `metabase.types` for a longer explanation. I also moved Relation types `:type/PK` and `:type/FK` into their own `:Relation/` hierarchy since they are neither a data type nor a semantic type

While auditing our type hierarchy I tried to fix a few little weird things I came across in a way that shouldn't break anything. Examples:
- it became clear that some of our types were defined multiple times (with different abstract parents).
- Some base types derived from `:type/Category` (a semantic type), but this information was not used anywhere. E.g. `:type/Boolean` (data) derived from `:type/Category` (semantic). I believe the original intention was that `BOOLEAN` and other base type `:type/Category` columns should be marked as "category" columns during sync (i.e., get their FieldValues cached) -- this makes sense, except the code didn't actually do this, so having this weird inversion didn't make sense. 
- Some of the semantic time types like `UpdatedTime` derived from `:type/Date` instead of `:type/Time` -- fixed these inconsistencies
- I reorganized a few things so the overall order of the file is more logical.
- Added tests to enforce the rules for the various type hierarchies.
- I didn't create separate frontend exports to split up `TYPE` -- `TYPE` still has everything at this point. It didn't seem necessary to split it up at this point in time, but we could do that as a follow-on.

#### TODO 

- [x] Fix automagic dashboards/x-ray tests
- [ ] fix a few FE tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/15956)

### CODE REVIEW

**Comment by camsaul** [comment]
@dpsutton do you think this project is still worth pursuing? There are lots of merge conflicts now, not sure whether it's even worth fixing them, or just closing this

**Comment by dpsutton** [comment]
I had forgotten about this. I think this is a lot of churn in 138 files right now for little gain but possibly nasty bugs. I think it's worth doing again in the future. Maybe we can focus on it right after a release and get it merged in after max 3 days?

**Comment by camsaul** [comment]
@dpsutton, yeah it's a little late in the 40 cycle to be doing big changes like this. Maybe at the start of the 41 cycle will give things time to shake out.

At that point doing a new search-and-replace in the whole project would be faster than fixing a bunch of merge conflicts... we can keep some of the changes here tho like the deduplicating types and new tests

**Comment by tsmacdonald** [comment]
@camsaul sounds like it's okay to close this PR?

**Comment by camsaul** [comment]
closing since I don't feel like pursuing this further at this time

**Pull request closed without merging**
