### PR TITLE
Drill-thru actions more click-friendly

### LINKED ISSUE #10625: Pop-up clickability unclear
**Describe the bug**

When I hover over a column's pop-up, there are a couple things that make the clickability unclear:

* Hovering over a row changes the row's color, which initially made me think the entire row would be clickable
* The clickboxes are pretty small. It seems like in most cases only the text is clickable. With `Zoom`, for example, this clickable area is pretty small.

**To Reproduce**

1. Open the sample dataset
2. Click on "Reviews"
3. Click on a column in "Reviews by Rating"
4. Hover over the "zoom" row, but not over the "zoom" text
5. Hover over the "zoom" text

**Expected behavior**

I expected the entire row to be clickable

**Screenshots**

Screen Shot 2019-08-19 at 3 36 58 PM

**Information about your Metabase Installation:**

- Dockerized MB, `docker run -p 3000:3000 --name mb1 metabase/metabase`
- Version 0.32.10

**Severity**

Annoying

### PR DESCRIPTION
**Pull request by flamber**
Fixes #10625

### CODE REVIEW

**Review by kdoh — CHANGES_REQUESTED** [review]
@flamber I'm not sure this particularly addresses the underlying issue described in #10625. The text-hover change helps reduce the confusion reported which is 👍 , but the overall clickable area doesn't  increase much.

I think part of the reason why this cropped up in the first place was that certain rows can have more than one item and so the hover and click is set to be really local to that item, but especially in cases where there's just the one (like zoom) ideally we'd make the whole row clickable no matter where you're hovering.

**Comment by flamber** [comment]
@kdoh Are you hinting at doing some flex auto, so it fills the row no matter if there's one or multiple?
But when you say the whole row, do you also mean the icon? That would be a little confusing with rows that has multiple links - would the icon then be part of the first link (I don't like that idea)?

**Comment by kdoh** [comment]
@flamber I think we'd probably want to do some conditional styling based on the number of items in the row vs doing anything like that and I don't really trust flex for that purpose. To your point if there are multiple items we want those to be clear targets. I might take a quick crack at this tomorrow locally myself so I can give you better feedback.

**Comment by flamber** [comment]
@kdoh 
Hi Kyle. I had this running at a place for a few months, upgraded to a release, and had forgotten about this addition and they instantly complained how difficult it was to select drills :wink: 
Feel free to close this PR, if you don't feel like that's the direction you wanna go.
Screencast 2019-12-03 21 41 53 Screencast 2019-12-03 21 41 54

**Review by kdoh — APPROVED** [review]
Don't want to let the perfect the enemy of the good here so going to go ahead and approve this.

**Pull request merged**
