### PR TITLE
Fix add series modal freezes the entire app

### LINKED ISSUE #13100: Adding data series to dashboard widget lags then sometimes hangs the UI
**Describe the bug**
Adding a data series to an existing widget can lag and hang the UI. After clicking the "Add data" or "Edit data" button on the widget the modal can take a very long time to populate the list of questions. Sometimes populating this list seems to stop and I end up with an incomplete list of questions.

If the list completes populating, the search function can take a few seconds to respond to key presses and execute searches.

Overall this dialog feels clunky and hard to use. Depending on where in this process it is at, if I got to a different browser tab and come back the Metabase screen is blank and needs to be refreshed to get it working again.

**Logs**
No Server logs or console errors. But the Network tab shows lots of ```query_metadata``` requests when the dialog is opened, lots of them are "Pending", sometimes it appears to hang in that state.

**To Reproduce**
1. Edit a dashbord with a widget
2.  click the "Add data" or "Edit data" button
3. Modal dialog is presented and lagging starts

**Expected behavior**
I'd expect a more responsive dialog, with a better search function, maybe organising the questions using the collection structure that we get in other search dialogs.

**Screenshots**
image

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.2",
      "date": "2020-07-31",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```
**Severity**
Makes the Add/Edit data function very hard to use. It's unpredictable, sometimes it will work sometimes it won't. Frustration mostly.

**Additional context**
We've got quite a few questions but I imagine no more than a "normal" sort of install. It would be great if this function used the same search dialog as other question search functions (like the "Add a question" button on at the top of the dashboard edit screen).

### PR DESCRIPTION
**Pull request by alxnddr**
Fixes https://github.com/metabase/metabase/issues/13100

### Description

In order to address the performance issues, I added virtualization to the question list implemented loading questions metadata in batches by "Load more" button. When the button is clicked, it loads metadata for the next 15 questions. However, if there are 100 more questions that use exactly the same underlying tables, all of them will be appended to the list.

This should just help as a quick fix, however, we definitely need to add server-side pagination there for even better performance.

### Screenshots
Screen Shot 2021-10-06 at 22 49 57

### How to verify
- Run an instance with a decent number of saved questions
- Create a dashboard with a line/area/bar chart and open edit mode
- Click add series
- Ensure "Load more" button fetches metadata next questions and appends them to the list
- Ensure the search box works fast

### CODE REVIEW

**Review by daltojohnso — APPROVED** [review]
nice, glad there ended up being a relatively simple fix for this

**Review by flamber — COMMENTED** [review]
I really hoped it would solve the problem, but it doesn't :cry: 
I have made much mental coffee while debugging issues involving combining on dashboards.
Think we both need to do something about the excessive requests, but it's the freezing that is the most painful.

Hope this explains how severe the problem is for some with a lot of questions. Sorry for the long videos, but not much is happening besides freezing for a long time.

This PR:

https://user-images.githubusercontent.com/1447303/131035158-82c224e7-d329-4cc2-94f3-d36d8af58258.mp4

0.40.3:

https://user-images.githubusercontent.com/1447303/131035714-205c9544-dfee-4614-b89b-eeb93e9d4abb.mp4

**Comment by alxnddr** [comment]
@flamber could you please try the updated branch on an instance with tons of questions?
The solution is far from perfect, but this is what I could do on the client-side only. The FE still fetches all questions, but then it loads metadata in chunks and shows users the `Load more` button for the next chunk.

I assume the list of question names that can contain 10k entries is not usable anyway, and because of that, users probably use search to find a specific question they have in mind and we just need to make the modal unfrozen. What are your thoughts?

**Review by flamber — APPROVED** [review]
Wauw!!! And I'm even using the search and adding a question!
There's plenty of optimizations that could be done, but those would be their own P2/P3 issues.

https://user-images.githubusercontent.com/1447303/135601497-282dda57-34f7-451d-9608-d8cc9eb50e26.mp4

**Comment by alxnddr** [comment]
@nemanjaglumac thank you 🙏 It worked

**Review by mazameli — APPROVED** [review]
Seems pretty snappy to me! https://share.getcloudapp.com/BluD712D

**Review by daltojohnso — APPROVED** [review]
nice!

**Pull request merged**
