### PR TITLE
[RFC] Add mocks for sample database (database, tables, fields)

### PR DESCRIPTION
**Pull request by ranquild**
RFC: https://www.notion.so/metabase/47-Deprecate-withSampleDatabase-in-renderWithProviders-786fa0043de1486da511384685318964
Epic https://github.com/metabase/metabase/issues/26960

Adds helpers like `createSampleDatabase`, `createOrdersTable` etc which return API data matching our sample database (fixture). I've corrected types and IDs to match what we have in the real sample database to make it easier to debug and create mock questions based on it.

Example usage:
```
import { createSampleDatabase } from "metabase-types/api/mocks/presets";
import { setupDatabaseEndpoints } from "__support__/server-mocks";

const setup  = () => {
  const database = createSampleDatabase();
  setupDatabaseEndpoints([database]);
   ...
};
```

Possible next steps:
- Add a `createMetadata` helper to create a `Metadata` instance based on the provided database, including its tables and fields

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28794)

### CODE REVIEW

**Comment by kulyk** [comment]
@ranquild this is simply _awesome_, thank you! 🎉 My two cents:

1. What do you think about extracting database and table IDs into constants? Now they're hardcoded, but they could be useful if we want to reference a table ID in tests
2. What do you think about making `presets` a directory and moving whatever there is now into something like `presets/sample_database`? I can see an immediate value in more presets (multi-schema database, empty database, etc.). It can become hard to maintain them if they all live in the same file

**Comment by ranquild** [comment]
@kulyk agree with both points, I'll make the changes accordingly

**Comment by kulyk** [comment]
Think we can also link this to the #26960 epic

**Comment by ranquild** [comment]
@kulyk added ids using the same names we have in cypress, and modified a test to use the new helper

**Review by kulyk — APPROVED** [review]
🏆

**Pull request merged**
