### PR TITLE
Add bracket/paren/braces matching to SQL editor

### PR DESCRIPTION
**Pull request by tlrobinson**
This enhances the SQL editor to automatically insert a closing bracket/brace/paren when you  insert an opening bracket/brace/paren, and delete the corresponding matching brace when deleting one.

### CODE REVIEW

**Comment by tlrobinson** [comment]
Anyone have any objections to this? It's especially nice with template tags, since you can just hit `{{` then a tag name, and the closing brackets are automatically inserted.

**Comment by salsakran** [comment]
sounds + looks awesome.

let me play with it a bit

**Comment by tlrobinson** [comment]
@salsakran Any additional thoughts on this?

**Comment by salsakran** [comment]
Seems to work, and haven't gotten into any weird states with it. 

👍

**Pull request merged**
