### PR TITLE
Ignore clj-kondo files

### PR DESCRIPTION
**Pull request by walterl**
[clj-kondo](https://github.com/borkdude/clj-kondo/) is a great linter.

### CODE REVIEW

**Comment by camsaul** [comment]
Are you using clj-kondo locally? How is it working for you?

I tried it with Metabase a few years ago but didn't add it to the project because of false positives or warnings that couldn't be disabled or something like that

**Comment by walterl** [comment]
clj-kondo is working really well for me. That said, I admittedly haven't spent a lot of time in this repo, so can't speak as to false positives. Not sure what it was like a few years ago, but it's still very actively developed and [very configurable](https://github.com/borkdude/clj-kondo/blob/master/doc/config.md).

Given all that, I'll rather back this PR out for now, until I can be more certain about its usefulness, and maybe add an appropriate/useful `.clj-kondo/config.edn`, rather than just ignoring the whole directory.

**Comment by robdaemon** [comment]
I use `clj-kondo` myself locally, but I do ignore some of what it says. I haven't put any effort into adjusting it.

I have `.clj-kondo` in my global `.gitignore` for now.

**Comment by camsaul** [comment]
If it's useful and we can get it passing by disabling some warnings then I'm all for adding it as a linter and adding it to CI

**Comment by borkdude** [comment]
> I tried it with Metabase a few years ago

Clj-kondo has only been around since the spring of 2019.

It's pretty easy to ignore warnings you don't like, either by [disabling a rule completely](https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#enabling-and-disabling) or ignoring warnings [locally](https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#ignore-warnings-in-an-expression). 

[This](https://github.com/borkdude/clj-kondo/blob/master/doc/linters.md) is the complete list of linters that it currently has.

For macros that clj-kondo doesn't recognize, you can write custom [hooks](https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#hooks) to get proper linting for those.

On top of the clj-kondo [analysis output](https://github.com/borkdude/clj-kondo/blob/master/analysis/README.md) you can build additional linters and tools.

Clj-kondo can also be used as a JVM library or [babashka pod](https://github.com/borkdude/clj-kondo#babashka-pod) so you can post-process its output to your likings.

We also have a page with [CI integration](https://github.com/borkdude/clj-kondo/blob/master/doc/ci-integration.md) tips and tricks.

If you need any help with setting up clj-kondo, let me know.

**Pull request closed without merging**
