### PR TITLE
MLv2: use kebab-case keys in Clojure & camelCase in JS

### LINKED ISSUE #30044: [MLv2] `displayInfo` should return `camelCase` keys for JS
As discussed here https://metaboat.slack.com/archives/C04DN5VRQM6/p1681320907511569

Neither Clojure(Script) nor JavaScript loves `snake_case` keys, so what's the point of using them? For JS-friendliness, let's return `camelCase` keys for JS. I think we can have our cake and eat it too: we can return `kebab-case` for Clj(s), and use [CSK](https://github.com/clj-commons/camel-snake-kebab) (which we already have as a dependency) to convert them to `camelCase` at the Cljs => js boundary automatically.

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #30044

Updates Metabase Lib v2 so all metadata and display info (in and out) uses `kebab-case` keys. Metadata is automatically normalized to kebab-case when it comes in. `display-info` is kebab-case in Clojure-land and gets converted to `camelCase` for the JS version.

Since MLv2 exists independently of the notion of an application database it seems weird to continue to tie ourselves into using icky `snake_case` keys that are gross in both Clojure and JavaScript. Since we already have to do a bit of conversion at the boundaries anyway (-> pMBQL shape conversion, adding `:lib/type` keys, etc.) we might as well also do key conversion and have nice keys going forward rather than icky ones.

Seems like quite a big overhaul but most of this PR is just updating the keys in the captured metadata in `metabase.lib.test-metadata`, it seemed like a better and more performant approach long term vs converting those keys on the fly in every test.

I would have used [CSK ](https://github.com/clj-commons/camel-snake-kebab) for this directly, but I wanted to avoid "Turkish system locale" problems, so I created a few wrapper versions in `metabase.util` that use `u/lower-case-en` and the like. I cleaned up some competing patterns for doing stuff like that in `metabase.util` while I was at it.

**I know this PR is going to cause trouble and conflicts when it lands, I apologize for that, but I think it will be worth it in the long-term**

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30248)

### CODE REVIEW

**Review by camsaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30248)* status: 0 of 52 files reviewed, all discussions resolved

___
*[`.clj-kondo/config.edn` line 164 at r1](https://reviewable.io/reviews/metabase/metabase/30248#-NTR1JkG-nfIiUTvAZ-M:-NTR1JkG-nfIiUTvAZ-N:bfa0udc) ([raw file](https://github.com/metabase/metabase/blob/cb0aa8b6c5f60040b9454ed3a7333b64a4424777/.clj-kondo/config.edn#L164)):*
> ```edn
> 
>   :discouraged-namespace
>   {camel-snake-kebab.core {:message "CSK is not Turkish-safe, use the versions in metabase.util instead."}
> ```

Not really needed for this PR, but we should probably be careful not to use this directly, unless we like things breaking in Turkish, so I added this to the Kondo config and fixed a few places it came up
___
*[`.clj-kondo/config.edn` line 727 at r1](https://reviewable.io/reviews/metabase/metabase/30248#-NTR1XJKDv8DzPO2ctXQ:-NTR1XJKDv8DzPO2ctXR:bshsjdr) ([raw file](https://github.com/metabase/metabase/blob/cb0aa8b6c5f60040b9454ed3a7333b64a4424777/.clj-kondo/config.edn#L727)):*
> ```edn
>     :discouraged-var
>     {medley.core/map-keys {:message "Use clojure.core/update-keys"}
>      medley.core/map-vals {:message "Use clojure.core/update-vals"}}}}}}
> ```

Also not really needed, but this is something that should have been a rule already. Use the Clojure 11 stuff now that it exists



_Code quote:_
```edn
    {medley.core/map-keys {:message "Use clojure.core/update-keys"}
     medley.core/map-vals {:message "Use clojure.core/update-vals"}}}}}}
```
___
*[`frontend/src/metabase-lib/metadata.ts` line 26 at r1](https://reviewable.io/reviews/metabase/metabase/30248#-NTR1frm4CAGiVcjC2_e:-NTR1frm4CAGiVcjC2_f:b2nhsto) ([raw file](https://github.com/metabase/metabase/blob/cb0aa8b6c5f60040b9454ed3a7333b64a4424777/frontend/src/metabase-lib/metadata.ts#L26)):*
> ```XML
> 
> export type DisplayInfo = {
>   displayName: string;
> ```

Yay
___
*[`src/metabase/util.cljc` line 128 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTR2PqY7ORmGRU39gc3:-NTR2PqY7ORmGRU39gc4:b8hni4f) ([raw file](https://github.com/metabase/metabase/blob/539fae62e95b646afadcb362751c430f4a8ed253/src/metabase/util.cljc#L128)):*
> ```Clojure
>   (m/filter-vals some? m))
> 
> (defn normalize-map
> ```

moved this down so it could use the new `->kebab-case-en` fn
___
*[`src/metabase/analytics/snowplow.clj` line 175 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTR2b_RDLmbvnkYo2bj:-NTR2b_RDLmbvnkYo2bk:baohqnp) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/analytics/snowplow.clj#L175)):*
> ```Clojure
> (defn- normalize-kw
>   [kw]
>   (-> kw name (str/replace #"-" "_")))
> ```

I removed `u/snake-key` in favor of `u/->snake_case_en`, unfortunately that doesn't seem to be what we actually wanted HERE, because `:h2` becomes `"h_2"`. This seems to be what we ACTUALLY wanted. 
___
*[`src/metabase/lib/card.cljc` line 22 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTR2yxuEGP49xkYeiW-:-NTR2yxuEGP49xkYeiW0:b-wcwkd1) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/lib/card.cljc#L22)):*
> ```Clojure
> 
> (mu/defn ^:private infer-results-metadata
>   [metadata-providerable :- lib.metadata/MetadataProviderable
> ```

It seemed sort of important to differentiate from these functions actually needing a `query` vs just needing something that can be used to get a`metadata-provider`... I have coined the phrase *metadata providerable* to signify this sort of thing. It rhymes with *connectable* in `next.jdbc` or Toucan 2, *modelable* in Toucan 2, etc.
___
*[`src/metabase/lib/metadata.cljc` line 149 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTR3aWh2uJj5xImGQaz:-NTR3aWi9RL5vHKjuBH_:bgvfda2) ([raw file](https://github.com/metabase/metabase/blob/539fae62e95b646afadcb362751c430f4a8ed253/src/metabase/lib/metadata.cljc#L149)):*
> ```Clojure
>   :hierarchy lib.hierarchy/hierarchy)
> 
> (defmethod ->metadata-provider* :default
> ```

I changed this multimethod to a plain function because there is only one implementation of it, and I don't forsee us adding more, so it's a bit silly to have it. 
___
*[`src/metabase/lib/metadata.cljc` line 163 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTR3u763yYetSnMjFQr:-NTR3u763yYetSnMjFQs:b-hj48hl) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/lib/metadata.cljc#L163)):*
> ```Clojure
>   [metadata-providerable :- MetadataProviderable]
>   (if (lib.metadata.protocols/metadata-provider? metadata-providerable)
>     metadata-providerable
> ```

I changed the argument names for a bunch of these to make it clear that they actually accept a metadata providerable, not like you'd probably be passing in a query to the functions to construct empty queries, but technically you could. And now we have `MetadataProviderable` to enforce this where before there was no schema for this notion

**Review by metamben — APPROVED** [review]
> Reviewed 51 of 52 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30248)* status: all files reviewed, 7 unresolved discussions (waiting on @camsaul)

___
*[`src/metabase/util.cljc` line 169 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTs40y-ndPrxV9ZS-_:-NTTs40y-ndPrxV9ZS-a:bn6aesj) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L169)):*
> ```Clojure
> 
> (defn capitalize-en
>   "Locale-agnostic version of [[clojure.string/capitalize]]."
> ```

Plus this version returns `""` on `nil`, as opposed to throwing an NPE. This is also different from how `upper-case-en` (NPE) and the wrapped conversion fns (return `nil`) work.
___
*[`src/metabase/util.cljc` line 202 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTtIOM9lXrHX4lZA4p:-NTTtIOM9lXrHX4lZA4q:b-7co3hn) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L202)):*
> ```Clojure
> (def ^{:arglists '([x])} ->kebab-case-en
>   "Like [[camel-snake-kebab.core/->kebab-case]], but always uses English for lower-casing, and also supports keywords
>   with namespaces, and `nil`."
> ```

It's not unambiguous what "supports `nil`" means.
___
*[`src/metabase/util.cljc` line 211 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTtcq-4ngF-KWowXMh:-NTTtcq-4ngF-KWowXMi:undefined) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L211)):*
> ```Clojure
> 
> (def ^{:arglists '([x])} ->camelCaseEn
>   "Like [[camel-snake-kebab.core/->camelCaseEn]], but always uses English for upper- and lower-casing, and also supports
> ```





_Suggestion:_
```Clojure
->camelCase
```
___
*[`src/metabase/util.cljc` line 230 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTu-1kDmlp9yiPX5xv:-NTTu-1kDmlp9yiPX5xw:undefined) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L230)):*
> ```Clojure
> 
> (defn snake-keys
>   "Convert the keys in a map from `lisp-case` to `snake_case`."
> ```





_Suggestion:_
```Clojure
kebab-case
```
___
*[`src/metabase/util.cljc` line 240 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTuBtP0im2KubniCdP:-NTTuBtP0im2KubniCdQ:bm1fun9) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L240)):*
> ```Clojure
>   - JS object (with string keys)
>   The keys are converted to `kebab-case` from `camelCase` or `snake_case` as necessary, and turned into keywords.
>   Namespaces keywords are rejected with an exception.
> ```

Where is that exception thrown?



_Suggestion:_
```Clojure
Namespaced
```
___
*[`src/metabase/lib/table.cljc` line 48 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTUC6ky-ly6hiXksF2x:-NTUC6ky-ly6hiXksF2y:undefined) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/lib/table.cljc#L48)):*
> ```Clojure
>   See [[metabase.query-processor.middleware.add-implicit-clauses/table->sorted-fields*]]."
>   [field-metadatas]
>   (remove (fn [{visibility-type :visibility-type, active? :active, :as _field-metadata}]
> ```





_Suggestion:_
```Clojure
:keys [visibility-type]
```
___
*[`test/metabase/util_test.cljc` line 254 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTUKIEDDIfOFOcWUPyH:-NTUKIEDDIfOFOcWUPyI:borluhw) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/test/metabase/util_test.cljc#L254)):*
> ```Clojure
>                    (u/capitalize-en "ibis")
>                    (u/capitalize-en "IBIS")
>                    (u/capitalize-en "Ibis"))))))
> ```

What about testing these functions with "exotic" data like `nil`, `""`, a map, etc.?

**Review by camsaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30248)* status: 34 of 58 files reviewed, all discussions resolved (waiting on @metamben)

___
*[`src/metabase/util.cljc` line 169 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTs40y-ndPrxV9ZS-_:-NTtbX6JB_q8hyWwdXSo:b-7ql1td) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L169)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Plus this version returns `""` on `nil`, as opposed to throwing an NPE. This is also different from how `upper-case-en` (NPE) and the wrapped conversion fns (return `nil`) work.
</blockquote></details>

fixed
___
*[`src/metabase/util.cljc` line 202 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTtIOM9lXrHX4lZA4p:-NTtbYQDAiccsK_UD0W3:b-7ql1td) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L202)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

It's not unambiguous what "supports `nil`" means.
</blockquote></details>

fixed
___
*[`src/metabase/util.cljc` line 211 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTtcq-4ngF-KWowXMh:-NTtbZdo5arqJWY6DMZO:b-7ql1td) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L211)):*
> ```Clojure
> 
> (def ^{:arglists '([x])} ->camelCaseEn
>   "Like [[camel-snake-kebab.core/->camelCaseEn]], but always uses English for upper- and lower-casing, and also supports
> ```

fixed
___
*[`src/metabase/util.cljc` line 230 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTu-1kDmlp9yiPX5xv:-NTtb_xpEh5JHDdAO_99:b-7ql1td) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L230)):*
> ```Clojure
> 
> (defn snake-keys
>   "Convert the keys in a map from `lisp-case` to `snake_case`."
> ```

fixed
___
*[`src/metabase/util.cljc` line 240 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTTuBtP0im2KubniCdP:-NTtbbSZ2-HSV5WHjGZQ:b-cxz67f) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/util.cljc#L240)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Where is that exception thrown?
</blockquote></details>

You're right, I removed this part of the docstring now.
___
*[`src/metabase/lib/table.cljc` line 48 at r2](https://reviewable.io/reviews/metabase/metabase/30248#-NTUC6ky-ly6hiXksF2x:-NTtbhTy4yRj1W2CKHbz:bb7f2mf) ([raw file](https://github.com/metabase/metabase/blob/1d3ebc75c8ec6986bc1e545415c0bfa9835ade95/src/metabase/lib/table.cljc#L48)):*
> ```Clojure
>   See [[metabase.query-processor.middleware.add-implicit-clauses/table->sorted-fields*]]."
>   [field-metadatas]
>   (remove (fn [{visibility-type :visibility-type, active? :active, :as _field-metadata}]
> ```

done

**Review by metamben — APPROVED** [review]
> Reviewed 27 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30248)* status: all files reviewed, 1 unresolved discussion (waiting on @camsaul)

___
*[`test/metabase/util_test.cljc` line 263 at r3](https://reviewable.io/reviews/metabase/metabase/30248#-NTu_oIc6AnFJlSAXl9O:-NTu_oIc6AnFJlSAXl9P:b6rboh6) ([raw file](https://github.com/metabase/metabase/blob/08359ecc609408acc8a3772814621533d70eac11/test/metabase/util_test.cljc#L263)):*
> ```Clojure
>     ;; incorrect usage, hence the `:clj-kondo/ignore` comments below.
>     #_:clj-kondo/ignore 1  "1"
>     #_:clj-kondo/ignore {} "{}"))
> ```

Why do we verify unintended behavior? I suggest deleting these test cases along with the comment.

**Review by camsaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @camsaul)

___
*[`test/metabase/util_test.cljc` line 263 at r3](https://reviewable.io/reviews/metabase/metabase/30248#-NTu_oIc6AnFJlSAXl9O:-NTuqIx-3e_ddsA3RxJU:b-3wwmee) ([raw file](https://github.com/metabase/metabase/blob/08359ecc609408acc8a3772814621533d70eac11/test/metabase/util_test.cljc#L263)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Why do we verify unintended behavior? I suggest deleting these test cases along with the comment.
</blockquote></details>

that's kind of what I thought too, but I thought that was what you were suggesting in your previous comment, so I went ahead and added it anyway. I'll remove it

**Pull request merged**
