### PR TITLE
Modify expression dimension to support subdimensions

### PR DESCRIPTION
**Pull request by ariya**
This is necessary so that custom columns can have binning (strategy), temporal unit, etc.

**Note**: This PR only addressed the front-end aspect. If you click Visualize in the repro below, the query result is still not correct. For that, we need to wait for @camsaul's tweak on the QP. 

<hr>

How to try:

1. New, Question
2. Sample Database, Products table
3. Custom Column, type `[Price] / 2` and name it `HalfPrice`
4. Custom Column, type `[Created At]` and name it `Product Date`

5. Summarize, `Count`, by `Price`. Here you can choose various binning for the breakout:

image

6. Summarize, `Count`, by `Created At`. Here you can choose various temporal units for the breakout:

image

7. Instead of `Price`, change the breakout to `HalfPrice` instead.
8. Instead of `Created At`, change the breakout to `Product Date` instead.

**Before**

In step 7, no binning is available for this custom column `HalfPrice`. This is confusing since choosing the original column, `Price`, gives the choice of various bins.

image

In step 8, no choice of temporal unit is available for `Product Date`, despite the original column `Created At` actually has many choices.

image

**After**

`HalfPrice` offers the same binning options. The chosen binning will be persistent (i.e. choose one, select it again, and the previous chosen binning is highlighted).

image

The same goes for `Product Date`:

image

### CODE REVIEW

**Review by flamber — APPROVED** [review]
Is it supposed to not have default binning, or is that a backend thing that isn't available yet?

And if I manually select a binning for a number, then I'm able to go back to "Don't bin", but I'm not able to do this for dates (which is basically what Cam is looking for in #19684, and would be a general good thing to have to avoid multiple casting, but also useful of joins, where you want to match to exact datetimes).

image

**Comment by ariya** [comment]
> Is it supposed to not have default binning, or is that a backend thing that isn't available yet?

Correct. I want to see first how `:nil` options is handled in the backend, and potentially make the right adjustment on the frontend.

> And if I manually select a binning for a number, then I'm able to go back to "Don't bin", but I'm not able to do this for dates (which is basically what Cam is looking for in #19684, and would be a general good thing to have to avoid multiple casting, but also useful of joins, where you want to match to exact datetimes).

Isn't this a general issue anyway with date/time field, even for a non custom-column? I can choose a breakout on `Created At`, pick a unit, but then there's no way for me to have unbinned `Created At`?

**Comment by flamber** [comment]
@ariya Yes, it's general, but is required if we want to implement binning in the metric for some types. For joins too https://github.com/metabase/metabase/pull/17883#pullrequestreview-754287000

**Comment by ariya** [comment]
> @ariya Yes, it's general, but is required if we want to implement binning in the metric for some types. For joins too [#17883 (review)](https://github.com/metabase/metabase/pull/17883#pullrequestreview-754287000)

Acknowledged. I'll add it to the backlog so I can tackle it in some follow-up (probably also requires some back-end tweaks).

**Pull request merged**
