### PR TITLE
Add dox about changing session expiration [ci skip]

### PR DESCRIPTION
**Pull request by camsaul**

### CODE REVIEW

**Comment by flamber** [comment]
Fixes #9495
We don't use/mention "Java system property" elsewhere. Should we start doing that or might it just cause confusion?

**Comment by camsaul** [comment]
I am leaning towards starting to do it elsewhere. `export` doesn't work in Windows whereas Java system properties work the same way on any platform. So if you're running locally on Windows it might save you a bit of confusion.

**Comment by camsaul** [comment]
It's easier than telling people three different ways to set an Env var e.g.

```cmd
:: cmd
setx MAX_SESSION_AGE "1440"
java -jar metabase.jar
```

```powershell
# powershell
$env:MAX_SESSION_AGE='1440'
java -jar metabase.jar
```

**Comment by flamber** [comment]
But I use `java -DMAX_SESSION_AGE=1440 -jar metabase.jar` without any problems. Is that a specific problem on Windows that doesn't allow `MAX_SESSION_AGE` but only `max.session.age`?

Having only a single variable name makes it a lot easier to search for instead of two writing types.

**Comment by camsaul** [comment]
Good point. I forgot that you could set it as Java system property like `-DMAX_SESSION_AGE`. But I guess they'd both be normalized to the same thing.

I think in this case we should include examples with `java -D<variable>=<value>` as well as `<variable>=<value> java` because the syntax for setting environment variables is different in Windows or PowerShell

**Comment by flamber** [comment]
Totally. It seems like PowerShell is getting more traction these days, so we need to adjust for that.
I've tried to include some of the different ways in #12182, but need PS too.

**Pull request merged**
