### PR TITLE
#14302 Repro: Native question with filter - dirty state without changes

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Reproduces #14302

### How to test this manually?
- `yarn test-cypress-open`
- `frontend/test/metabase/scenarios/question/native.cy.spec.js`
- Replace `it.skip()` with `it.only()` to test this in isolation
- The test should fail until the related issue is fixed

### Additional notes:
- Once the issue is fixed, please remove the `.skip` part (unskip the test completely)
- Make sure the test is passing and
- Merge it together with the fix

### Screenshots
image

### CODE REVIEW

**Review by flamber — APPROVED** [review]
I don't think there will be a race-condition, but perhaps instead of waiting for "14302", it should wait for `/question/${QUESTION_ID}?PRICE=10` ?

**Comment by nemanjaglumac** [comment]
@flamber It can also wait on `cardQuery` as in many other test cases, but it felt unnecessary here because "Save" is visible quite early on. Even before the question loads.

**Comment by nemanjaglumac** [comment]
> I don't think there will be a race-condition, but perhaps instead of waiting for "14302", it should wait for `/question/${QUESTION_ID}?PRICE=10` ?

What's even worse, asserting on link leads to race condition:
image

**Comment by flamber** [comment]
Well, that's fun. I think I have an issue open about that. If it currently works, then LGTM.

**Pull request merged**
