### PR TITLE
Create models from CSV uploads

### LINKED ISSUE #29963: Create models from CSV uploads

### PR DESCRIPTION
**Pull request by calherries**
Resolves https://github.com/metabase/metabase/issues/29963

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29966)

### CODE REVIEW

**Comment by tsmacdonald** [comment]
*[`frontend/src/metabase/services.js` line 94 at r3](https://reviewable.io/reviews/metabase/metabase/29966#-NSjEeoA6hGsnSDgnxBb:-NSjEeoA6hGsnSDgnxBc:bp8iz1y) ([raw file](https://github.com/metabase/metabase/blob/fbebd6431111509dabd34267b9f744e8c27bdcaf/frontend/src/metabase/services.js#L94)):*
> ```JavaScript
>   uploadCSV: POST("/api/card/from-csv", {
>     formData: true,
>     fetch: true,
> ```

as discussed on the huddle I don't need these FE changes locally :thinking:

**Comment by tsmacdonald** [comment]
*[`frontend/src/metabase/lib/api.js` line 90 at r3](https://reviewable.io/reviews/metabase/metabase/29966#-NSjEodL5cwUj8MmSBa7:-NSjEodL5cwUj8MmSBa8:bf0mie8) ([raw file](https://github.com/metabase/metabase/blob/fbebd6431111509dabd34267b9f744e8c27bdcaf/frontend/src/metabase/lib/api.js#L90)):*
> ```JavaScript
>         if (options.formData && options.fetch) {
>           delete headers["Content-Type"];
>         }
> ```

(same)

**Review by calherries — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29966)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @tsmacdonald)

___
*[`frontend/src/metabase/services.js` line 94 at r3](https://reviewable.io/reviews/metabase/metabase/29966#-NSjEeoA6hGsnSDgnxBb:-NSjIYHKDKbQOJvovUzk:bwvyox4) ([raw file](https://github.com/metabase/metabase/blob/fbebd6431111509dabd34267b9f744e8c27bdcaf/frontend/src/metabase/services.js#L94)):*
<details><summary><i>Previously, tsmacdonald (Tim Macdonald) wrote…</i></summary><blockquote>

as discussed on the huddle I don't need these FE changes locally :thinking: 
</blockquote></details>

Reverted
___
*[`frontend/src/metabase/lib/api.js` line 90 at r3](https://reviewable.io/reviews/metabase/metabase/29966#-NSjEodL5cwUj8MmSBa7:-NSjIJLWBhEq1o1luEN5:bwvyox4) ([raw file](https://github.com/metabase/metabase/blob/fbebd6431111509dabd34267b9f744e8c27bdcaf/frontend/src/metabase/lib/api.js#L90)):*
<details><summary><i>Previously, tsmacdonald (Tim Macdonald) wrote…</i></summary><blockquote>

(same)
</blockquote></details>

Reverted

**Review by tsmacdonald — CHANGES_REQUESTED** [review]
BE changes look good. FE needs to be investigated, but let's get this merged without them since we're still not sure what the culprit is and I don't want the BE changes to be held up

> Reviewed 2 of 4 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29966#-:-NSjIajk2PQ49Ha3iCBl:bp3gqxv)* status: 0 of 6 files reviewed, 2 unresolved discussions

**Review by tsmacdonald — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29966#-:-NSjItBL2leIVWNnvv_G:bnfp4nl)* status: 0 of 6 files reviewed, 2 unresolved discussions

**Pull request merged**
