### PR TITLE
Add option to propagate permissions to sub collections

### LINKED ISSUE #8205: Canceling changes in full collections permissions grid goes back instead of canceling
This is on master.

- Go to the collections permissions grid
- Make some changes at several different levels of collections and sub-collections
- When you click Cancel, you just go back a page until you get to the start, at which point the button will actually cancel changes.

permissions-grid-cancel

### PR DESCRIPTION
**Pull request by tlrobinson**
screenshot 2018-08-06 16 31 28

Also resolves #8205

### CODE REVIEW

**Comment by mazameli** [comment]
Ideally I wouldn't see this toggle when dealing with a collection that doesn't have any subcollections.

screen shot 2018-08-06 at 4 54 47 pm

**Comment by mazameli** [comment]
Here are the visual tweaks I made to the popover:

screen shot 2018-08-06 at 5 08 11 pm

**Comment by tlrobinson** [comment]
> Ideally I wouldn't see this toggle when dealing with a collection that doesn't have any subcollections.

Good point, fixed.

**Review by mazameli — APPROVED** [review]

**Review by salsakran — APPROVED** [review]
seems to work well from my manual testing of it

I can live with the toggle, though it does not fill me with aesthetic glee.

**Review by kdoh — COMMENTED** [review]
👍 for the propagation itself.

Not sure I'm loving the overall flow of the interaction for this though. The mixture of select items that immediately close the select and set your choice and then a toggle below just feels a little messy. For lack of a better term it feels like I could use more of a moment of pause to understand what going on if I'm potentially going to affect a bunch of items I can't see here (especially since we're defaulting to on).

Also curious if there's a reason why we went for a toggle vs a checkbox here. Small distinction but to me the toggle has more of a global implication whereas a checkbox feels possibly more appropriate on a per "instance" setting like this.

**Comment by mazameli** [comment]
Cool, thanks for the feedback. 

I could go either way with a checkbox vs. a toggle.

The reason that I opted for this defaulting on and it being handled by a toggle instead of a separate confirmation was:
- the unanimous user feedback was that the expected default behavior would be for the setting to propagate down
- because of that, I thought it would feel really clicky to have to confirm that expected behavior each time.

I.e., would you want to have to click this every time?

screen shot 2018-08-07 at 10 42 54 am

**Comment by kdoh** [comment]
I think my reaction to it was more about the context in which things are happening than the defaulting to on (which makes sense). Just feels like the put these options in a popover strategy is starting to get a little messy. Anyhoo, as reflected by the fact this is merged I think it's an overall net win.

**Pull request merged**
