### PR TITLE
Trendline frontend

### PR DESCRIPTION
**Pull request by tlrobinson**
Basically working, probably needs some visual design tweaks. Maybe settings to change the line style and/or extend to the future?

screenshot 2018-10-03 11 59 44

### CODE REVIEW

**Comment by tlrobinson** [comment]
We discussed changing the color to be a 60% shade of the line color. The `series-settings` changes a bunch of things about how colors are chosen so I'd like to wait for that to be merged before doing this.

**Comment by mazameli** [comment]
As we tweak the visuals for trend lines one thing to keep in mind is how they might look next to goal lines.

**Comment by mazameli** [comment]
@tlrobinson I went ahead and brought over the color and lightening changes from the multi-series pr as we discussed. Provided CI passes, I say we go ahead and merge this PR. I played with it again and didn't run into any problems.

**Comment by rayterrill** [comment]
I just tested it in 0.31 RC1, and while the trendline shows in edit mode and when I view the dashboard when authenticated, it doesn't show up on our public dashboard.

**Pull request merged**
