### PR TITLE
trim unused code

### PR DESCRIPTION
**Pull request by salsakran**
Remove old deployment code. Could I get a sanity check @tlrobinson or @camsaul ?

I've inspected the release script, and checklist, and created a test build and it all seems to work. Would appreciate a last lookover.

### CODE REVIEW

**Comment by camsaul** [comment]
✂️  💇  snip snip

**Comment by salsakran** [comment]
that a 👍 ?

**Comment by camsaul** [comment]
✂️ ➕ 👍 ➡️ 💀 

scissors and thumbs don't mix @salsakran 😹

**Comment by camsaul** [comment]
but yeah 👍

**Comment by salsakran** [comment]
I'm going to start doing my code reviews via interpretive dance. 

Be on the lookout for uploaded videos.

**Pull request merged**
