### PR TITLE
Postgres foreign data wrapper support

### LINKED ISSUE #1468: support postgresql foreign data wrappers
specifically, foreign tables. these are provided by extensions like `postgres_fdw` to allow querying remote databases and other data sources. docs: http://www.postgresql.org/docs/9.3/static/postgres-fdw.html

only medium priority for us. we're currently working around it with hand-defined views, which metabase does support. (yay.) this would still be nice though!

### PR DESCRIPTION
**Pull request by tlrobinson**
This may or may not be the best solution but I want to see if it passes CI.

Resolves #1468

### CODE REVIEW

**Comment by orlando** [comment]
🚀

**Comment by tlrobinson** [comment]
This seems to work, and passes CI.

I don't think there's an easy way to add a test for this since it would require the Postgres installation have a foreign data wrapper extension installed.

@camsaul any reason not to just merge this since I've verified it works manually and doesn't break any tests?

**Comment by camsaul** [comment]
@tlrobinson Most Postgres installations ship with common extensions available so you just need to enable them. For example this works out of the box on my computer:

```sql
CREATE EXTENSION IF NOT EXISTS postgres_fdw;
```

I've done the same thing to enable `postgis` on Postgres on CircleCI in the past on a different project. I would imagine `postgres_fdw` is available on Circle as well.

**Comment by tlrobinson** [comment]
@camsaul Cool, I added a test case for this in the latest commit.

**Comment by camsaul** [comment]
WFM

**Pull request merged**
