### PR TITLE
Speed up permissions migrations (round 2)

### LINKED ISSUE #46497: v50 data permissions migrations are slow
The data migrations are slow and can take up to several hours in their current form.

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes #46497 

* Rewrites permission migrations with the goal of improving performance
* Precomputes the permission paths for each table in a CTE
* Adds `ANALYZE data_permissions` calls before any heavy insertion jobs
  * (I've added a good number of these...they help substantially, but unsure which of these are helpful and which are redundant)

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#46393** <a href="https://app.graphite.dev/github/pr/metabase/metabase/46393?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by johnswanson — APPROVED** [review]
This looks good. I've been testing performance locally using a script that populates the DB with real-world permission data. The worst performing case took ~160 seconds to complete all migrations on my machine. That was with 18 groups and 265k tables (noting that groups + tables aren't the only variable here, as the migrations are especially slow with lots of _granular_ permissions, whereas permissions set at the db-level are relatively fast).

Reducing the amount of memory available to 3GB did not have any appreciable effect on migration performance.

**Review by escherize — APPROVED** [review]

**Comment by johnswanson** [comment]
Looking at this more today, I found that the performance suffers pretty rapidly with large numbers of permissions groups:

```
table_count  group_count  resulting_data_permission_count  migration_ms
152560       2            459437                           34368.227958
162560       2            489497                           27559.583167
222560       2            959492                           32182.925167
262560       2            790097                           68536.443166
302560       2            910337                           80100.077625
342560       2            1030577                          86583.370042
442560       2            1331177                          80407.519208
542560       2            1631777                          186439.729541
642560       2            1932377                          228435.363834
742560       2            2232977                          284153.462583
842560       2            2533577                          347160.588417
4021         100          510039                           48658.427416
4021         200          1013039                          95913.10925
4021         300          1516039                          145751.82875
```

My migration timed out at 6 minutes with 4021 tables and 400 permissions groups.

One important thing to note here: the very high costs here compared to when I was testing on real-world data are, I think, due to the fact that in these tests, *every* permissions group has granular permissions set on *every* database. In the real world, this seems unlikely.

The number of interest here is effectively the total number of [group-id, table] pairs such that the permissions group has *granular* permissions on the table's database. If that number is very high, the migration will be slow.

One other note: I didn't include the old version in the table above for the simple reason that it began timing out with only 200,000 tables - so we're looking at at least an OOM improvement in speed here.

**Comment by dpsutton** [comment]
**table-count**|**group-count**|**resulting-data-permission-count**|**migration-ms**
:-----:|:-----:|:-----:|:-----:
152,560|2|459,437|34 s
162,560|2|489,497|27 s
222,560|2|959,492|32 s
262,560|2|790,097|68 s
302,560|2|910,337|80 s
342,560|2|1,030,577|86 s
442,560|2|1,331,177|80 s
542,560|2|1,631,777|186 s (3 min)
642,560|2|1,932,377|228 (3.8 min)
742,560|2|2,232,977|284 (4.7 min)
842,560|2|2,533,577|347 (5.7 min)
4021|100|510,039|48 s
4021|200|1,013,039|95 s
4021|300|1,516,039|145 s (2.4 min)

**Pull request merged**
