### PR TITLE
shorten the TTL on the sql driver connection pools from 3 hours down to 1 hour.

### PR DESCRIPTION
**Pull request by agilliland**
This is meant to provide some relief for #1702 by reducing the likelihood that connections sit in the connection pool for several hours.  I think we can consider reducing this further, but for now 1 hour is fine.

### CODE REVIEW

**Comment by agilliland** [comment]
Sure, that makes sense.  The downside to having it so low is that really we won't have much of a pool going, so when the connections are actually needed there is an increased likelihood that they'll need to be created.

I don't feel strongly about it though, so I'll change the min-pool size back to 1.

**Comment by camsaul** [comment]
If we keep the minimum pool size of 3 those won't get recycled, right? It might actually make more sense to deal with the initial overhead because it will save us from having to recreate those all the time now that they are recycled much more aggressively

**Comment by camsaul** [comment]
or is there a setting where we can have it keep 3 but still lazily create 2 & 3?

**Comment by agilliland** [comment]
Correct, the pool will always maintain 3 open connections in that case.  

I don't believe there is any way to lazily create the connections like that.  In fact, I'm not sure that c3p0 was doing that anyways.  It attempts to acquire connections in batches because it considers that a more efficient way to scale the pool, so even though the min was 1 I'm pretty sure it was still creating 3 at a time.

**Comment by camsaul** [comment]
oh then in that case we might as well keep 3 as the minimum

**Pull request merged**
