### PR TITLE
[M1] Metabase illustration settings

### PR DESCRIPTION
**Pull request by WiNloSt**
Milestone 1 branch of #39246
[Product doc](https://www.notion.so/metabase/Let-white-labeling-customers-customize-illustrations-24e120498d5f414aaf52ddd0de9e20fc)
[Figma design](https://www.figma.com/file/yOksAHQ5ih6ospZd6f3RVc/Let-white-labeling-customers-customize-illustrations?type=design&node-id=1486-122158&mode=design&t=sKXiTjXPk4lqncYe-0)

This integration PR contains 5 other PRs for milestone 1 which are all approved and merged to this branch.

There are some merge conflict fixes that are introduced directly to this branch, but they're mostly global CSS migration conflicts.

### How to verify
We add 4 new illustration settings here.
1. Login and unsubscribe pages
    - Test login page with different illustration options
    - Test unsubscribe page with different illustration options. You can access the unsubscribe page here http://localhost:3000/unsubscribe?hash=hash&email=email&pulse-id=pulse-id
1. Landing page (aka home page)
    - Test home page with different illustration options
1. When calculations return no results. This is for query results.
    - Question that returns no results
    - A card in a dashboard that returns no results.
1. When no objects can be found. This is for anything that's not query results e.g. any entity that couldn't be found
    - Search app
    - Collection picker -> Search
    - Collection picker -> select an empty collection

### CODE REVIEW

**Comment by WiNloSt** [comment]
* **#40139** <a href="https://app.graphite.dev/github/pr/metabase/metabase/40139?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#40219** <a href="https://app.graphite.dev/github/pr/metabase/metabase/40219?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @WiNloSt and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by mazameli — CHANGES_REQUESTED** [review]
- Custom Login and landing page images: this seems to be scaling the image even if I choose a really wide one, which is different behavior from how the lighthouse default illustration works. In general for these large images I don't think we want to be scaling images, since it'll make a small image look bad, and defeat the purpose of a large image that overflows the viewport. Example: this image of mine is much taller than this: 

image

- Nit: when changing the no-results images to a custom one or to no-image, I found I had to hard refresh to see that take effect. Must've been cached.

**Review by mazameli — APPROVED** [review]
Removing my change request because I misunderstood what @vbenedetti had intended here. I think the image behavior in the branch is neither right nor wrong — it could be exactly what our users want. It's just different from the default image's behavior.

**Comment by WiNloSt** [comment]
> Nit: when changing the no-results images to a custom one or to no-image, I found I had to hard refresh to see that take effect. Must've been cached.

I couldn't reproduce this after updating the branch with the latest `master`.

I've tried both no calculation results and no object results and made sure I click exit admin, so the page won't reload and I could still see those image settings reflect on the app.

**Pull request merged**
