### PR TITLE
Popover movement #15502

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to #15502. It was mutating the maxHeight after tethering, but we want semantics of before.

### CODE REVIEW

**Comment by howonlee** [comment]
I can't repro the cypress failure, which seems to be an overlapping of the button according to the video, on my machine

**Comment by nemanjaglumac** [comment]
> I can't repro the cypress failure, which seems to be an overlapping of the button according to the video, on my machine. investigating...

Try setting the window height to 720px.

**Comment by howonlee** [comment]
note on repro of overlap bug: I was not able to repro at:
- 1000px height,
- 700px height set by window manager
- 400px height set by window manager,
 
but I was able to repro at:
- 700px height set by chrome's window size simulator
- but not 400px height set by chrome's window size simulator

**Review by daltojohnso — APPROVED** [review]
looks good! sorry for the late review

**Comment by flamber** [comment]
This causes other weirdness

----

The data-selector is really small - clicking multiple times will sometimes show full size, but it then overflows the viewport.
image

----

Breakout options is not contained within viewport (neither is CE dropdown, but cannot screenshot that)
image

**Comment by nemanjaglumac** [comment]
If you have to do every click with `{ force: true }`, something is probably off and worth investigating. Especially if it's worked before.

**Comment by howonlee** [comment]
Fix for the dropdown issue has to be bundled with fix for #15445 so it's coming in the fix for #15445. As far as I can tell I could repro the data-selector being really small and repro a fix within this branch.

**Pull request merged**
