### PR TITLE
Add schemas to data reference sidebar

### LINKED ISSUE #10520: The Data Reference sidebar should organize tables by schema when applicable
Right now when looking at the contents of a DB that has its tables organized in schemas in the data reference sidebar panel, the tables are shown as a flat list. We should really show the list of schemas, with the ability to click in to see a schema's contents. It's hard or impossible right now to know which table is which if there's more than one with the same name in multiple schemas.

Somewhat related to https://github.com/metabase/metabase/issues/7926

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10520 

@mazameli any updates on the styling? (I'm guessing yes.)

image

Also, I noticed that we're using tables' `name` rather than `display_name` here. In the full data reference we use `display_name`. Is that intentional because we want to use the string that a SQL-writer needs to know? If it's an oversight I can fix it here.

### CODE REVIEW

**Review by mazameli — DISMISSED** [review]
Instead of just grouping the list of tables by schema, I think we're going to want a distinct step or pane to list the schemas themselves (if there are any besides the primary `public` one), since there could potentially be lots of them. 

This is what I'm picturing: list the schemas, then click on one to see the tables inside of it:

image

On the schema list, in the top-right, I've also depicted a count of the schemas, like how we have a count of the total tables on the table list pane.

Regarding the table names, yes, showing the `name` instead of the `display_name` was an intentional choice in order to help folks as they're writing SQL.

**Comment by paulrosenzweig** [comment]
@mazameli how's this?
dataref

**Review by mazameli — COMMENTED** [review]
Seems great. Only funny thing I noticed was the sort order of the schemas. It all seemed alphabetical except I'm not sure why `public` isn't showing up at the top, and why `schema_71` is at the bottom here. (For reference, I'm looking at our redshift CI DB locally.)

image

**Review by tlrobinson — APPROVED** [review]
LGTM!

**Pull request merged**
