### PR TITLE
Database schemas UI

### LINKED ISSUE #1706: Better UI support for Postgres/Redshift Schemas
I've connected Metabase to my Redshift cluster and can see my database, however the metabase UI lists ALL the tables in ALL the schemas in one long list. In my case, I have almost 1000 so that's a very long list. It would be great if the interface could actually support the Schema object in Redshift/PostgreSQL to aid in finding and selecting the desired tables.

Repro steps:
1. Create Redshift cluster with multiple schemas and multiple tables per schema.
2. Connect Metabase to Redshift cluster with user authorized to all schemas and all tables in each schema.
3. In Metabase, Create New Question.
4. In "Data" drop down observe the Database is connected and all tables are listed, but the "Schema" concept is completely missing.

Expected Result:
The Schema object is represented and you can navigate to the desire Table by Schema.

Actual Result:
The Schema object is missing entirely. Instead, all the tables are listed alphabetically with no schema information at all.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #1706
- [x] Data picker
- [x] Metadata table picker
- [x] Fix native query data picker
- [x] Update QB tutorial to match UI changes

### CODE REVIEW

**Comment by tlrobinson** [comment]
This is far enough along that it's worth trying out (minus the QB tutorial update and native data picker)

**Comment by agilliland** [comment]
I'm getting errors in my JS console

screen shot 2016-01-20 at 7 13 05 pm

**Comment by tlrobinson** [comment]
I'm guessing it's not safe to assume table.schema is present? I've only tested with h2 and Postgres so far, which both had a default schema.

**Comment by agilliland** [comment]
correct.  table.schema is allowed to be null

**Comment by tlrobinson** [comment]
Ok should be ready to go. Fixed the case where schema is not present.

Also fixed the native query data selector and query builder tutorial.

**Comment by agilliland** [comment]
I'm seeing a few issues ...

1) On the QB, when i go back to the Database listing in the dropdown after having chosen a database w/out any schemas, it leaves my previous selection highlighted blue when it should be grey.

screen shot 2016-01-21 at 5 10 31 pm

2) The data reference is completely broken for me.  It doesn't indicate any schema info in the table listings, and when i do click on a table everything goes blank.

screen shot 2016-01-21 at 5 13 42 pm

3) The QB tutorial doesn't launch after a click on `how does this thing work?` any more.  Oddly, if i click the link and then click something else then it comes up.

**Comment by agilliland** [comment]
@tlrobinson , specifically regarding the code, as we go forward I think we should be trying as hard as possible to avoid using local state in our React components.  

I don't think it's worth changing right now, but the way the schema list is built and maintained in a React component state seems more problematic than doing that same work when the api returns the data and then passing it in as props.  So ideally that work would be done in a Redux action or some other helper function completely outside the rendering logic itself.

**Comment by tlrobinson** [comment]
@agilliland 

1. Fixed
2. This branch doesn't touch the data reference, and it looks like this is broken on master as well. I'm not sure when that happened, I'll take a look.
3. I'm not able to reproduce this. Are there any error messages or anything?

**Comment by tlrobinson** [comment]
Ok, data reference is fixed. It may have been broken by some refactoring in the segments branch :-/

**Comment by agilliland** [comment]
Cool, #1 is good.  I did notice one other thing that can be confusing though.  because the Database/Table selector is stateful, if you pick a table (and the selector closes), then you open it up and click on the back button to get to the database list, then click outside the list (again closing the selector), when you click on the table name again it opens the selector to the database list instead of to the table listing for your chosen database.

The data reference is better, but if you click on any of the buttons/choices on the field section of the data reference (e.g. the `potentially useful questions`) they don't do anything.  so those are still broken.

I'm still getting an issue with the QB Tutorial launching.  I see this error in my js console ..

screen shot 2016-01-21 at 5 59 51 pm

**Comment by tlrobinson** [comment]
@agilliland Oops, same problem with the data ref field. Fixed. Sometimes I wish we had static typing...

Hmm that error seems to indicate it couldn't find the "Sample Dataset" database. Did you remove it? I'll add a check for that.

**Comment by agilliland** [comment]
correct.  i don't have it in my databases list right now, which brings up a very relevant issue of whether or not we should even show the QB tutorial in that case.  seems best that if the sample dataset doesn't exist then we should just disable the QB tutorial stuff.  @mazameli @salsakran any thoughts?

**Comment by tlrobinson** [comment]
Ok, but it's not related to this branch, should we do that on a separate issue/PR? Perhaps we shouldn't entirely remove the Sample Dataset when an admin removes it, but hide it unless the tutorial is running?

**Comment by agilliland** [comment]
Yeah, you're right.  I'll create a new issue for that and we can discuss there.

**Pull request merged**
