### PR TITLE
Add h2-with-db task to easily get a H2 REPL to your metabase.db

### PR DESCRIPTION
**Pull request by tlrobinson**

### CODE REVIEW

**Comment by tlrobinson** [comment]
@agilliland or @camsaul this is pretty simple, ready to merge

**Comment by camsaul** [comment]
is there any advantage to having the old command as well? Or would it make sense just to replace it with this one

**Comment by agilliland** [comment]
I agree with Cam, if we don't really need both commands then we should just settle on one or the other.  What would be the intended reason for running the `h2` command without it pointing to the Metabase db?

**Comment by tlrobinson** [comment]
Yeah that's fine, I'm not sure why I didn't do this more useful command in the first place. I'll get rid of the other one.

**Comment by tlrobinson** [comment]
Ok, done.

**Comment by camsaul** [comment]
👍

**Pull request merged**
