### PR TITLE
Add FirebirdSQL driver [ci drivers]

### PR DESCRIPTION
**Pull request by Nikos410**
So here we go.

First of all I want to thank the whole metabase team for providing this great tool as open-source software - and especially Cam, who has been a great help while developing this driver and setting up tests.

This PR adds a module for a FirebirdSQL driver to Metabase. 

I have developed and tested this driver against one of our Firebird3 databases; the driver *should* work for older versions as well, but I did not test that. The tests however have to run against a Firebird 3 database, because the tests extensions use some things that were only added in Firebird 3. (E.g. Boolean datatype, Identity columns)

### CODE REVIEW

**Comment by camsaul** [comment]
*  Nikos410 HAS NOT signed the CLA

**Comment by camsaul** [comment]
@Nikos410 it looks like you signed the CLA as `Niko410` which is why my bot is getting mixed up

**Comment by Nikos410** [comment]
Well... should I sign it again or is it fine as it is? After all no one stops anyone from changing their username after signing...

**Comment by tlrobinson** [comment]
Hey all,

Thank you for this PR and apologies for the long delay responding. We've recently done some work to support drivers as plugins in Metabase and as of the next release (v0.32) we will be asking driver developers to first publish new drivers in their own repositories (typically named `metabase-*-driver`). If the driver fully passes the driver tests we will link to it from our documentation, and if a driver gains significant usage we will consider merging it into Metabase itself.

Here is some documentation about publishing a driver as a plugin in a separate repository: https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#drivers-shipped-as-3rd-party-plugins

Here are two example drivers: https://github.com/metabase/sudoku-driver https://github.com/metabase/crate-driver

We still have some work to do on the documentation. You can follow progress and provide feedback on that here: https://github.com/metabase/metabase/issues/9348

Thank you.

**Comment by Nikos410** [comment]
Alright, I have moved the driver into a [standalone repository](https://github.com/evosec/metabase-firebird-driver). :+1:

**Pull request closed without merging**
