### PR TITLE
fix cut-off info popover text in Safari

### PR DESCRIPTION
**Pull request by daltojohnso**
Just needs a bit of added line-height, I think.

Screen Shot 2022-01-24 at 11 15 30 AM

### CODE REVIEW

**Comment by ariya** [comment]
Any reason to target the 42 branch directly?

**Comment by kulyk** [comment]
The lowercase "g" is still slightly cut-off

CleanShot 2022-01-25 at 12 52 49@2x

**Comment by daltojohnso** [comment]
thanks for catching that @ariya. it's been a while since I used `backport` so I got it twisted around 🙂

**Comment by daltojohnso** [comment]
sorry about that @kulyk, I actually fixed it this time around:

Screen Shot 2022-01-25 at 10 01 14 AM

**Review by kulyk — APPROVED** [review]

**Pull request merged**
