### PR TITLE
Ga aggregation fix

### PR DESCRIPTION
**Pull request by kristynrb**
**Bug Fix**
This is a bug fix for the following issues: [5756](https://github.com/metabase/metabase/issues/5756) and [4894](https://github.com/metabase/metabase/issues/4894). This allows a user to select multiple aggregations for GA and see the results displayed in a column. 

The problem was the structured query was not formatted correctly to send to GA, so only the first aggregation was being sent.  

**New bug**
However, another issue has arisen. You can now use multiple aggregations, but you cannot remove the aggregation one-by-one. The aggregations can be (all) deleted if you select to delete the first aggregation selection. 

The problem is that the aggregation value that is being used when the `x` is clicked is the aggregation that was reformatted for the GA request. Any help that you can suggest for me to fix this new bug would be greatly appreciated!

google_analytics_broken_agg

###### TODO 
-  [x ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by salsakran** [comment]
I've verified that this fixes #4894

**Comment by salsakran** [comment]
@attekei or @tlrobinson mind chiming in with regards to the issue with 'x'ing out aggregations?

**Comment by tlrobinson** [comment]
@kristynrb Thanks for taking a shot at this. However, I think it's better handled on the backend in the GA driver. MBQL already supports multiple aggregations so we just need to make sure the GA query processor handles more than just the first one.

Here's the code: https://github.com/metabase/metabase/blame/master/src/metabase/driver/googleanalytics/query_processor.clj#L250-L256

It looks like we only take the `first-aggregation` whereas we should probably `map` over all the aggregations to get the metric name then `join` them all with a comma.

The `order-by` clause should also be updated to use the correct aggregation: https://github.com/metabase/metabase/blob/master/src/metabase/driver/googleanalytics/query_processor.clj#L173

@camsaul does that sound right?

**Review by tlrobinson — COMMENTED** [review]
Comments in the PR

**Review by tlrobinson — CHANGES_REQUESTED** [review]
Comments in the PR

**Comment by tlrobinson** [comment]
@kristynrb I've gone ahead and implemented that approach in this PR: #6822, please give it a try. Thanks!

**Comment by kristynrb** [comment]
Thanks @tlrobinson! I noticed that tests were failing with the PR #6822. Should I wait for any fixes / tests to pass or should I go ahead and implement this into my code?

**Comment by salsakran** [comment]
fixed in #6822

**Pull request closed without merging**
