### PR TITLE
i18n(es_ES) initial version

### PR DESCRIPTION
**Pull request by joebordes**
I know it is early for this but I thought it may be useful for you to be able to change to another language and I wanted to ask about the language file name.

I looked through the c3po documentation but couldn't see where it defines the language codes to use for the translation. From what I get we could use any letters.

I just want to make sure there is defined support for the different language regions. For example, ES Spain (which is the file in this PR), ES Argentina or ES Mexico, just to name a few. The same issue can appear in German, with de_DE and de_AT, among others.

I think the correct way to go is to use the [ISO 3166 3 letter code](https://www.iso.org/iso-3166-country-codes.html)

https://www.iso.org/obp/ui

### CODE REVIEW

**Comment by kdoh** [comment]
Thanks a bunch for working on this @joebordes. Just want to loop in @tlrobinson to have him take a quick look and make sure everything here so far will be compatible with the work going on in #5803 and the general flow we're establishing for i18n.

**Comment by LionelBino** [comment]
Hey there, i want t help with this

**Comment by joebordes** [comment]
H @LionelBino

Until they upload the file to the main branch I would suggest that you make a PR against my fork or send me the modified file and I will upload it.

I am overbooked right now but plan to get back to this in 10 days or so

Note, that the current state of this file is missing many of the new strings in 0.29, you should update my file with the new strings

**Comment by joebordes** [comment]
@LionelBino, I just updated the ES translation on PR #7065 which is where the correct version is.
I am going to close this PR as the other one is the correct version.
We can start talking there.

**Pull request closed without merging**
