### PR TITLE
Load initial Docker Metabase db from provided H2 dump

### PR DESCRIPTION
**Pull request by walterl**
Related to @ogeagla's DB migration work.

### CODE REVIEW

**Comment by walterl** [comment]
I added a check to `load-from-h2` to test if the target db is already initialized. If it is, bail before triggering some nastier duplicate PK errors.

**Review by ogeagla — CHANGES_REQUESTED** [review]
I would add the Dockerfile we will use for EB, which attempts to restore the dump from the EB asset zip then starts Metabase normally.

**Comment by walterl** [comment]
> I would add the Dockerfile we will use for EB, which attempts to restore the dump from the EB asset zip then starts Metabase normally.

:heavy_check_mark:

**Review by ogeagla — APPROVED** [review]

**Comment by ogeagla** [comment]
LGTM

**Pull request merged**
