### PR TITLE
Update AWS Elastic Beanstalk deployment script

### PR DESCRIPTION
**Pull request by russelldavies**
Fixes the issue where environment variables were not being read. Environment variables are passed to the Docker instance but not the host EC2 instance so had no effect.

Also cleaned up script and updated Papertrail configuration.

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by salsakran** [comment]
Thanks! I personally don't know enough to determine whether this is a good or bad idea. Anyone on  @metabase/core-developers feels like they do?

**Comment by mazameli** [comment]
@camsaul or @ogeagla, this PR is from two years ago. Is this still relevant / something that would be a good idea?

**Comment by ogeagla** [comment]
What was the issue with setting env vars that this was supposed to address?  I'd like to get more either comments here or in the code explaining the changes also as I don't really follow most of them.

**Comment by russelldavies** [comment]
I can't remember the all the reason for the commits but I think it was to fix the issue with nginx not reading variables for HTTP to HTTPS redirect. Considering that Elastic Beanstalk is hardly used these days it might just be better to close this issue.

**Comment by kdoh** [comment]
Closing per @russelldavies comment on EB usage.

**Pull request closed without merging**
