### PR TITLE
Parameter reordering [WIP]

### LINKED ISSUE #3238: Suggestion: Allow reordering of dashboard level field filters and SQL parameter widgets
I suggest a drag and drop method, but it doesn't matter too much

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3238 (part of #5934)

### CODE REVIEW

**Comment by tlrobinson** [comment]
(only implemented in dashboards so far)

**Comment by mazameli** [comment]
@tlrobinson Gonna try and not overthink this. Basically, I think dashboard filter widgets should be reorderable when you're in Edit mode, and SQL filter widgets should be reorderable any time  (otherwise I think it would be too hard to tell when you can/can't reorder them; happy to tweak this once it's implemented if we think it feels wrong).

For dashboard filters in edit mode, we can add a small grabber icon and a white background like this:

dashboard_reorder

For SQL filters we'd show the grabber icon whenever you hover, regardless of whether the filter is active or not:

sql_reorder

The little grabber icon should fit into the available left margin; it shouldn't move the content of the filter widgets around.

Here's the path for the grabber icon:

`M9.692 7.385a3.692 3.692 0 1 1 0-7.385 3.692 3.692 0 0 1 0 7.385zm0 12.307a3.692 3.692 0 1 1 0-7.384 3.692 3.692 0 0 1 0 7.384zM22 7.385A3.692 3.692 0 1 1 22 0a3.692 3.692 0 0 1 0 7.385zm0 12.307a3.692 3.692 0 1 1 0-7.384 3.692 3.692 0 0 1 0 7.384zM9.692 32a3.692 3.692 0 1 1 0-7.385 3.692 3.692 0 0 1 0 7.385zM22 32a3.692 3.692 0 1 1 0-7.385A3.692 3.692 0 0 1 22 32z`

**Comment by tlrobinson** [comment]
Ok i've added the grabber on both dashboards and SQL params (still need to actually implement the function for reordering SQL params but you can at least try the dragging behavior).

Should dragging only happen if you hit the grabber, or should you be able to drag anywhere after a certain distance/delay? See the `distance` and `pressDelay` props here https://github.com/clauderic/react-sortable-hoc#sortablecontainer-hoc

**Comment by mazameli** [comment]
Nice, just played with it real quick. I think making the whole filter a drag target (instead of just the grabber) is the way to go, particularly if we add the `distance` property you suggested. If you tell me where how to put that prop, I can try messing around with the exact values until it feels right.

**Comment by mazameli** [comment]
Pushed a couple minuscule changes. If I'm being picky, it would be cool if the whole parameter widget was a click target, because right now I can make it so that on hover the whole parameter widget gains cursor:pointer, but unless you're over the center of the widget clicking doesn't do anything, so the pointer is a miscue.

Other than that, I think we can merge this now.

**Pull request merged**
