### PR TITLE
Improve exported csv filename

### PR DESCRIPTION
**Pull request by maliayas**
Now it's more meaningful and shorter IMHO.

### CODE REVIEW

**Comment by salsakran** [comment]
Hey, @maliayas , thanks for taking a crack at this. We picked that super early on, and it's probably not the best name.

`data_` is a little too vague. I think `metabase_result_` is probably the most clear prefix. do you mind updating to that?

**Comment by tlrobinson** [comment]
Would it make sense to include the table name (if it's not a SQL question)

**Comment by maliayas** [comment]
Hmm, that makes sense. My current vote would be for `dbname-tablename-timezone.csv`. When those are added, `query`, `result`, `data`, `metabase` would be unnecessary IMHO. Because CSV extension already indicates it's a _data_. Also maybe we should remove the zone part from the timezone to be shorter? Because most of the time consumers of the file will be in the same timezone. `2016-11-10 22:56` might be enough maybe?

**Comment by looric** [comment]
query_result_2018-04-09T01_45_49.954Z.xlsx

suggest the time part to be the metabase.core :: System timezone. other than the UTC time

**Comment by camsaul** [comment]
Closing since we never got CLA on this

**Comment by maliayas** [comment]
Sorry, I wasn't notified about the CLA request. Is the CLA about license? How do I do that? I couldn't find a documentation about it.

**Comment by maliayas** [comment]
Oh, I see there is a Google doc for that. I prefer not to use Google apps and I release this really tiny PR under public domain. You can use/merge/modify it however you want. I hope stating this is enough for your procedure.

Regards,

**Comment by camsaul** [comment]
@maliayas it’s in the template when you open a pull request

**Comment by maliayas** [comment]
@camsaul

> it’s in the template when you open a pull request for Metabase

Please see my later comment.

**Pull request closed without merging**
