### PR TITLE
Delete appropriate GTAPs when permissions change

### LINKED ISSUE #16190: Revoking access to users in multiple groups does not correctly cleanup GTAP
**Describe the bug**
Revoking access to users in multiple groups does not correctly cleanup GTAP

**To Reproduce**
1. Admin > People > Groups > create two groups, TestGroup1, TestGroup2
2. Admin > People > create TestUser1, and assign the two groups. Also add attribute to user, ex: `user_id` : `1`
3. Admin > Permissions > Sample Dataset > Orders > TestGroup1 > Grant sandboxed access > "User ID" = `user_id`
4. See metadata table `group_table_access_policy` now contains the permission
5. Now, revoke access again for TestGroup1
6. `group_table_access_policy` still contains the permission
7. Repeat step 3, but for TestGroup2
8. `group_table_access_policy` now contains two permissions
9. Login as TestUser1 and try to access Sample Dataset > Orders, results in error:
`Found more than one group table access policy for user 'test1@test.test'`

Current workaround is to manually delete the old policy from `group_table_access_policy`

Example of query that will remove all orphaned GTAPs - make sure to backup before running!
<details>

Written for Postgres - run the query inside of the checker-comment to see what will be remove before running the full delete query.
```sql
DELETE
FROM
  group_table_access_policy
WHERE
  id IN (
    -- checker:begin
    SELECT
      GTAP.id
    FROM
      group_table_access_policy AS GTAP
    WHERE
      0 = (
        SELECT
          count(*)
        FROM
          permissions AS p
        WHERE
          p.group_id = GTAP.group_id
          AND p."object" LIKE concat('%/', GTAP.table_id, '/query/segmented/')
      )
    -- checker:end
  )
```

</details>

**Information about your Metabase Installation:**
Tested 1.34.4 thru 1.39.2

Originally EE249 - https://github.com/metabase/metabase-enterprise/issues/249

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #16190

Fixed by adding EE-specific `revoke-perms-delete-sandboxes-if-needed!` and `grant-perms-delete-sandboxes-if-needed!` hook methods into underlying perms functions for deleting and granting permissions.

This PR is like 80% tests, 10% EE-impl boilerplate and maybe like 10% actual new code.

1. GRANT full DB perms = delete all sandboxes for Tables in that DB.
2. REVOKE all DBs perms = delete all sandboxes for Tables in that DB.
3. GRANT full schema perms = delete all sandboxes for Tables with that schema.
4. REVOKE all schema perms = delete all sandboxes for Tables with that schema.
5. GRANT full table perms = delete all sandboxes for that Table.
6. REVOKE all table perms = delete all sandboxes for that Table.
7. changing Table READ perms shouldn't affect anything.
8.  GRANT Table query perms => remove sandbox for that Table
9. REVOKE Table query perms => shouldn't affect anything
10. GRANT Table segmented perms = don't touch GTAPs.
11. REVOKE Table segmented perms = delete associated GTAPs.

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
There's something really strange going on in the frontend. Took me a while to figure it out.

1. Admin > Permissions > Sample Dataset > People > sandbox - select column `ID` = attribute `user_id`
image
2. When clicking "Save" in the modal, then it send a `POST /api/mt/gtap` and adds a row in `group_table_access_policy`
3. Then when clicking "Save Changes" on the permissions page, then it sends a `PUT /api/permissions/graph`, which adds two rows to `permissions` table, but now the `group_table_access_policy` row has been removed.
4. Now edit the sandbox again and redo it - ID=user_id and click "Save", which sends a `POST /api/mt/gtap`
Only now everything works as expected.

The funky thing is that this is how the frontend also works in 0.39.2, so I guess this PR is cleaning up GTAP before adding to the `permissions` table, which then causes it to lose parts of the permissions.

It seems wrong to actually save parts of permission changes, when clicking "Save" in the modal, but I guess it might have been implemented like that to handle OSS/EE conflicts.
But that part isn't new, but it's blocking this PR.

**Comment by camsaul** [comment]
Thanks for digging in to that @flamber, I've been trying to figure out what's going on with the failing Cypress tests in this PR. The `group_table_access_policy ` inexplicably getting deleted when you save the graph would explain things. I'll figure out what's going on and fix it.

**Comment by camsaul** [comment]
Ok @flamber, take another look at this. I reworked things to fix the issue you caught. Previously it was deleting the GTAP because full perms were being revoked, even tho sandboxed perms were being granted at the same time. The updated code considers overall graph change when deciding what to delete, so changing full perms to sandboxed perms will no longer erroneously delete the GTAP.

**Review by dpsutton — APPROVED** [review]

**Review by flamber — APPROVED** [review]
:beach_umbrella: :black_square_button: :broom: 

Okay, it's much saner now. But it doesn't cleanup this scenario. It doesn't seem to cause any problems, but I'm thinking that you probably don't want to leave left-overs.

1. Admin > Permissions > revoke all access to Sample Dataset
2. Go to table Orders > "Grant SANDBOXED access" with User ID=user_id and Save and Save Changes, so it creates a row in `gtap` and two in `permissions`
3. Now change Orders to "Grant UNRESTRICTED access". It correctly removes the `gtap`, but it leaves two rows in `permissions` and adds another.

Approving, since this now fixes the issue and the final cleanup doesn't seem to cause any problems.

**Comment by camsaul** [comment]
@flamber the old rows in `permissions` not being cleaned up is a separate lower-priority issue, I'll open a new GH issue to tackle that separately

**Pull request merged**
