### PR TITLE
Additional fields [prototype]

### PR DESCRIPTION
**Pull request by tlrobinson**
Add additional fields to queries in the chart settings modal, e.x. when grouping by a fk you want to see the fk's entity name instead of id.

http://recordit.co/dyEbbhtxZ2

#1445

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by danielfaulknor** [comment]
Any update on this? It's the only feature missing for us

**Comment by edobry** [comment]
Any idea when this will be released?

**Comment by mazameli** [comment]
Any reason why we never merged this? I don't know if I'd change much based on your screen recording (having trouble running this locally, probably due to migrations or somesuch). I think I'd only pretty up the add link, and I'm also not sure I'd automatically pivot the table after adding the new field as it seems it's doing in the recording.

Prettier link and left-aligned checkboxes:

artboard copy

**Comment by mazameli** [comment]
Any thoughts on this one, @salsakran?

**Comment by kjohannessen** [comment]
This is the main outstanding feature for us to be able to use this product without having to create custom SQL Queries all the time. The same GUI feature in Filters that allows you to reference foreign key fields should be available in the "Customize this table" part of the Query Definition.

**Comment by mazameli** [comment]
Been thinking about this PR a little and started to think that the current implementation of adding each additional field one-by-one via the contextual menu might be cumbersome. This is an ugly sketch of how we might be able to minimally alter the UI to make it easier to add/remove multiple fields more quickly:

add-fields

**Comment by abcfyk** [comment]
Really looking forward to these features! @mazameli

**Comment by mokra** [comment]
Any chance this will be continued?

**Comment by MarkRx** [comment]
Dear PR,

Please get merged.

Thanks,
MarkRx

**Comment by tlrobinson** [comment]
Closing in favor of #8004

**Pull request closed without merging**
