### PR TITLE
Alternative fix for pie chart hanging

### PR DESCRIPTION
**Pull request by tlrobinson**
Alternative to @cmann50's #4035, which doesn't rerender correctly when the size or number of items changes (e.x. when you change the query)

This (mostly) resizes correctly in Chrome but in Safari it doesn't resize when making the window smaller.

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers Please review. Try out a variety of situations with the pie chart visualization, in particular one with enough slices that the legend is truncated. Also try resizing from large to small and vice versa.

**Comment by tlrobinson** [comment]
@metabase/core-developers Bump. I'd like to get this in 0.22 since it appears to be broken on all browsers not just Safari. Please give it a try.

**Comment by mazameli** [comment]
Tried in Chrome, Safari, and Firefox. Didn't see any hanging on any of them with a count of rows broken out into 30 slices. Firefox doesn't seem to resize the chart, though, nor does it collapse down the legend into `n more` like Safari and Chrome do.

**Comment by tlrobinson** [comment]
Did anyone want to review this any further?

**Pull request merged**
