### PR TITLE
[MLv2] Add card-or-table-id

### LINKED ISSUE #35257: [MLv2] BE — Add `card-or-table-id` method
The FE needs a way to get a `ColumnMetadata's` card or table ID to workaround field values fetching
Here's a possible signature:

```ts
function cardOrTableId(
  query: Query,
  stageIndex: number,
  column: ColumnMetadata,
): string | number {}
```

### PR DESCRIPTION
**Pull request by snoe**
Fixes #35257

### CODE REVIEW

**Comment by ranquild** [comment]
Please don't do anything and don't merge until we finish discussing this https://metaboat.slack.com/archives/C04CYTEL9N2/p1698765990489889

**Review by ranquild — COMMENTED** [review]
The function returns `["card", 5]` instead of `card__5`. And for columns from tables I'd expect an integer value. cc @kulyk

**Comment by snoe** [comment]
> The function returns `["card", 5]` instead of `card__5`. And for columns from tables I'd expect an integer value. cc @kulyk

Changed the return value, renamed to `legacy-card-or-table-id` to better capture these deprecated "ids"

**Review by ranquild — APPROVED** [review]

**Review by metamben — APPROVED** [review]
LGTM

**Pull request merged**
