### PR TITLE
Fix popover scrolling

### LINKED ISSUE #8316: Group selection menu not scrollable anymore (in v0.30)
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

Chrome Version 67.0.3396.99 (Official Build) (64-bit)

- Your operating system: (e.x. OS X 10, Windows XP, etc)

Mac OS X Sierra (10.12.6)

- Metabase version: (e.x. 0.19.3)

v 0.30

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)

Docker

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

Postgres

- *Repeatable steps to reproduce the issue*

1. Have many groups of users such they don't fit on the screen
2. Click the group selection for a particular user
3. The list is not scrollable anymore

Gifs:

### PR DESCRIPTION
**Pull request by kdoh**
Fixes #8316, #8281, #8377

### CODE REVIEW

**Review by tlrobinson — COMMENTED** [review]
`AccordianList` is virtualized so I feel like adding `overflow: scroll` probably isn't the right thing. Which issues does that change address?

Also, does this fix all of the individual issues listed in #8377? If so you should list them here so they all get closed. If not we shouldn't close #8377.

**Review by mazameli — APPROVED** [review]
This PR fixes all the issues in the description, and also fixes all the issues in that "master issue" as far as I can tell. The only issue number not called out in this PR from the master issue is #8370.

**Comment by mazameli** [comment]
The table/db/schema select scrolls a little funky in Firefox, fyi:

double-scroll-ff

**Comment by mazameli** [comment]
Yeah, I think you're right. 

- So, this PR fixes #8316 and #8281 in Chrome, FF, and Safari.
- It _technically_ fixes #8370, in that you can now scroll to the bottom of the table/db/scheme selector in FF. I suppose the odd [double scrollbar behavior](https://github.com/metabase/metabase/pull/9046#issuecomment-443292299) could be called a separate issue.
- And then #8656 is its own issue, which this PR doesn't claim to address.

So I guess that leaves me with still being a 👍 on merging.

**Comment by tlrobinson** [comment]
> I'd imagine if react-virtualized's List component accepts style props it can handle it without breaking virtualization but maybe I'm mistaken.

I don't think that's a safe assumption, and it actually might be the cause of the double scrollbar issue in the data selector.

But I guess double scrollbars are better than not being being able to scroll at all.

**Comment by kdoh** [comment]
I'm starting to think this is maybe a problem with the Popover component itself These lines https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/Popover.jsx#L368 (which because of being tied to sizeToFit are only currently applying to the DataSelector) don't actually do anything in cases where there's a ton of content because `Popover--withBackground` has `overflow-hidden;` I think that might be the offender here actually. @tlrobinson remind me what `sizeToFit` is supposed to do? It seems like all of our popovers are sizing to fit behaviorally but that prop defaults to false.

**Comment by tlrobinson** [comment]
@kdoh `sizeToFix` should probably be called `constrainToScreen`. It changes the height of the popover so that's it's not clipped.

**Review by tlrobinson — APPROVED** [review]

**Pull request merged**
