### PR TITLE
Fix broken links in README

### PR DESCRIPTION
**Pull request by dleve123**
- Remove `www` subdomain as it's no longer needed
- Add `.html` suffixes to broken links

###### TODO 
~~-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).~~
  - I think this counts as a tiny documentation change

### CODE REVIEW

**Comment by dleve123** [comment]
cc @attekei on this small doc patch that I ran into when investigating metabase. I also recommend updating your doc server so that legacy links redirect appropriately FWIW.

**Review by attekei — APPROVED** [review]

**Review by camsaul — APPROVED** [review]
👍

**Comment by dleve123** [comment]
Cool, LMK if any other actions are needed to get this merged.

**Comment by salsakran** [comment]
This is a bandaid, but thanks for caring enough, @dleve123 !

We recently migrated off of github pages to S3 and the way jekyll and s3 work isn't always the same as github pages.

**Pull request merged**
