### PR TITLE
Multiseries Charts V1

### LINKED ISSUE #590: Timeseries spanning dozens of years or more show too many ticks

### LINKED ISSUE #656: Allow multiple series on a line chart

### LINKED ISSUE #855: Line/Area/Bar charts incorrectly displayed as a timeseries with certain data
We are missing a concrete data set to reproduce this, but I did see it for sure.  A user created a query that was a count grouped by a column which was alphanumeric (ex: `scanner005`) and when you tried to chart the results using a bar chart the x-axis was indicating time series, which was clearly wrong.  no actual bars showed up on the graph.

### LINKED ISSUE #926: tooltips should respect the authoritiah of the browser window
like some of our other popovers, etc the tooltips aren't aware of the browser edge and as such content is getting clipped

screen shot 2015-08-31 at 11 16 46 am

### LINKED ISSUE #1222: IE - Dashboard resizing and re-arranging do not work

### LINKED ISSUE #1731: TypeError: Cannot read property 'tagName' of null
I am getting cannot read property 'tagname' of null exception while visualizing as bar chart if data contains '-' . Pie chart works fine .

It works just fine if i replace '-' from data .

Please refer attached screenshots .
screen shot 2016-01-13 at 9 38 59 pm
screen shot 2016-01-13 at 9 40 02 pm

Can someone please look into this ?

### LINKED ISSUE #1783: Tooltips on bar charts in firefox
I'm experiencing this problem in firefox:
screen shot 2016-01-22 at 5 40 44 pm
screen shot 2016-01-22 at 5 40 39 pm

Tooltip is misplaced for bar charts. It keeps appearing in the same place when i move the widget. In chrome it works well.

### LINKED ISSUE #1895: Bar graph truncating last value when grouping by date
Metabase: 0.14.1

Here's a sample table in Postgres:
```sql
CREATE TABLE test (
  value INT,
  date DATE
  );
  
INSERT INTO test (value, date) VALUES
  (10, '2015-12-01'),
  (20, '2016-01-01'),
  (30, '2016-02-01')
  ;
```

Here is the query in Metabase displayed as a table:
screenshot 2016-02-06 08 36 48

Here's the bar graph visualization with February data not showing:
screenshot 2016-02-06 08 41 08

### LINKED ISSUE #1896: Skinny bar graphs when using SQL editor
Metabase: 0.14.1

Issue: Unlike the bar graphs generated when constructing a query using the Metabase query editor, the SQL editor bar graphs are skinny and not representing all of the values. 
```sql
CREATE TABLE test (
  value INT,
  date DATE
  );
  
INSERT INTO test (value, date) VALUES
  (10, '2015-12-01'),
  (20, '2016-01-01'),
  (30, '2016-02-01')
  ;
```

Query using SQL editor and bar graph visualization:
screenshot 2016-02-06 08 50 34

### LINKED ISSUE #1901: years sometimes being shown as comma separated integers on x axis of charts
Not sure how best to prevent this but in this case we have a column named year being used for a breakout and marked as a category in the data model. The result is that the year 2002 is being shown as 2,002

screen shot 2016-02-08 at 11 19 38 am

### LINKED ISSUE #1942: Date format incorrect on dashboard
I group by month in the query builder, and within the query builder everything looks fine:
image

However when I add the question to a dashboard the date is a truncated timestamp:
image

This is on a Postgres server and metabase v0.14.1

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #656 (multiple series)
Resolves #590 (tick density in timeseries spanning many years)
Resolves #855 (incorrect detection of timeseries)
Resolves #926 (tooltips overflowing window)
Resolves #1222 (dashboard dragging/resizing broken in IE)
Resolves #1731 (`Cannot read property 'tagName' of null`) -- need confirmation
Resolves #1783 (tooltips broken in Firefox)
Resolves #1895 (truncated bar charts)
Resolves #1896 (skinny bars with SQL editor)
Resolves #1901 (years/zips being formatted with commas)
Resolves #1942 (dashboard table not formatting cells same as qb table)

TODO/bugs:

**multiseries**
- [x] Logic for only showing suitable cards in "add data" modal
- [x] Legend header causing "add data" modal to expand horizontally
- [x] improved split axis calculation
- [x] merging 2 timeseries with different granularities inserting 0 values
- [x] wait until all series have loaded before rendering
- [x] disable opacity transition on charts
- [x] Unable to save dashboard after deleting a multiseries card (but removing the multiseries first then deleting works) (@agilliland?)

**dash repositioning/resizing**
- [x] Resizing broken
- [x] scrolling while dragging
- [x] stretching a card horizontally forever when trying to resize it

**charting**
- [x] Disable line chart dots at high density?
- [x] Disable card header outside of dashboard
- [x] we are showing the axis labels on every card on dashboards, which wasn't happening before.  is there a rule about when to show axis labels?
- [x] Disable tooltips if title not ellipsified or hidden
- [x] Tooltips should format dates correctly for SQL queries
- ~~Certain cards losing their color setting (https://proto.metabase.com/card/24)~~

**misc**
- [x] Merge `dashboard_test.clj` (@agilliland)
- [x] Fix failing CI tests

### CODE REVIEW

**Comment by mazameli** [comment]
These chart titles shouldn't be present on the Question pages: 

title-bug

**Comment by agilliland** [comment]
I added in a variety of things that I had left out in my first pass over the backend/api code including some updates to the way dashboard revisions work so that we properly capture and account for the new DashboardSeries.

I also fixed the problem you mentioned @tlrobinson about the DashboardCard not deleting properly when it has some additional series attached to it, so that should be g2g now.

**Comment by agilliland** [comment]
@tlrobinson we ready to merge this now?  seems like everything is in good shape and whatever other tweaks we want to do we can tackle in a separate branch/PR if needed.

**Comment by tlrobinson** [comment]
Sounds good!

**Comment by bnetter** [comment]
:+1: great news! Can't wait to try it. When is the next release?

**Comment by agilliland** [comment]
The next release is scheduled to come out next week on Feb 29th.

**Comment by coussej** [comment]
Awesome ! :+1: Great to see so much effort being put into this project :smile:

**Pull request merged**
