### PR TITLE
CI: Migrate frontend and backend linters to GitHub Actions

### PR DESCRIPTION
**Pull request by ariya**
This reduces the burden of CircleCI.

### CODE REVIEW

**Comment by ariya** [comment]
As the added bonus, linter errors (such as the one by ESLint demonstrated here) are recognized by GitHub Actions and there's a convenient link to jump straight to the offending place.

image

**Comment by ariya** [comment]
As for the backend linter errors, demonstrated here by the output of Eastwood (Clojure linter), there is a script that parses the output and convert/upload it to the annotations format understood by GitHub.

(This is just temporary BTW, as @camsaul suggested to upstream the annotation formatter to the Eastwood project itself. Once that happens, we can just the new formatter output as is).

image

**Comment by nemanjaglumac** [comment]
So, CircleCI doesn't depend on the successful GitHub checks in any way?

Btw, both Frontend and Backend linters seem to be running twice (both for `push` and for `pull_request`). Was that intentional?

**Comment by ariya** [comment]
> So, CircleCI doesn't depend on the successful GitHub checks in any way?

It does, but IIRC checks are only for success vs fail (boolean), whereas annotations give the details (which is not supported out-of-the-box with CircleCI).

> Btw, both Frontend and Backend linters seem to be running twice (both for `push` and for `pull_request`). Was that intentional?

Good catch! Let me try to restrict `push` only for master, feature, and release branches.

**Comment by nemanjaglumac** [comment]
> > So, CircleCI doesn't depend on the successful GitHub checks in any way?
> 
> It does, but IIRC checks are only for success vs fail (boolean), whereas annotations give the details (which is not supported out-of-the-box with CircleCI).

I meant: CircleCi job will start immediately (in parallel with GitHub), right? So even if some file is misconfigured we rely on GH to catch that and fail. When that happens will it cancel the CircleCI run or will it let it finish? Sorry for potentially ignorant questions - I am trying to understand how things are wired together.

One more thing: will `[ci skip]` flag have an effect on GitHub CI as well?

**Comment by ariya** [comment]
> I meant: CircleCi job will start immediately (in parallel with GitHub), right? So even if some file is misconfigured we rely on GH to catch that and fail. When that happens will it cancel the CircleCI run or will it let it finish? Sorry for potentially ignorant questions - I am trying to understand how things are wired together.

That is the case, CircleCI will continue to run regardless the success/failure status of GitHub Actions runs.

> One more thing: will `[ci skip]` flag have an effect on GitHub CI as well?

I wasn't sure to implement this, since the linter runs should be fast anyway.
But I guess you're spot on: for consistency, GitHub Actions should also honor `[ci skip]` (I'll tweak it soon).

**Comment by ariya** [comment]
I found the cause of the problem: this is the current limitation of GitHub. The [secret GitHub token](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret), uniquely generated for each job and expires when the job is done, is not available for a GitHub Actions workflow that gets triggered by a pull request (this is understandable, since such a token can be used to gain access to the repository by anyone creating a pull request). Once the pull request is accepted and the branch is merged, the secret token is properly available for the workflow.

Unfortunately this limitation means that we can not have the full experience of integrated annotations (as converted from the linter output) in the pull request itself.

I will close this for now while searching for a potential workaround.

**Pull request closed without merging**
