### PR TITLE
Update tooltip copy

### PR DESCRIPTION
**Pull request by gusaiani**
Per Michael's request

image

### CODE REVIEW

**Review by salsakran — CHANGES_REQUESTED** [review]
We should update the final "edition" to "editions" for grammatical reasons 🤓

I also think we should have a name for paid editions vs referring to pro and enterprise.

**Comment by gusaiani** [comment]
@salsakran 

Thanks, string updated.

I've redirected your thought on naming to https://metaboat.slack.com/archives/C013LQ0MEQL/p1643746716782839

**Review by brunobergher — APPROVED** [review]
lgtm

**Review by salsakran — COMMENTED** [review]
works for me

**Review by salsakran — APPROVED** [review]

**Pull request merged**
