### PR TITLE
Add instructions for Render deployment

### PR DESCRIPTION
**Pull request by anurag**
This PR adds documentation for running Metabase on [Render](https://render.com). 

We also have a Metabase install guide up on https://render.com/docs/deploy-metabase.

### CODE REVIEW

**Comment by salsakran** [comment]
Hello @anurag -

Appreciate you putting this together! Unfortunately, we tend to move very conservatively regarding which third party hosting options we recommend. None of us have used render yet, and I don't think we would take the step of effectively recommending it until we see a number of our users finding success there over time, especially with regard to upgrades and stability. Additionally, by virtue of this being in official docs, we'd be on the hook for supporting this and fielding questions if things  change or don't work. We can't do that at this point in time.

Closing for now, but we'll keep an eye out.

**Comment by anurag** [comment]
Hi @salsakran, this presents a chicken and egg situation. It's hard to get users to use Render for Metabase unless they see it *somewhere* in Metabase docs. I posted on https://discourse.metabase.com, and we've seen a few new users from it. Would it make sense to add this guide as a 'community-maintained' option like [Cloud66](https://metabase.com/docs/latest/operations-guide/running-metabase-on-cloud66.html)?

FWIW, we've been running our own Metabase instance on Render for months, and just upgraded to the latest version by simply changing a line in the Dockerfile:

https://github.com/render-examples/metabase/commit/3e652b287fdd483713a72fe4e2d0f6bb5a535d9f

**Comment by salsakran** [comment]
@anurag The Cloud66 inclusion is, in retrospect, a mistake. I've removed it in #10236 

We're re-examining our recommendations regarding hosting and how we present them, and will keep render in mind.

**Comment by anurag** [comment]
Thanks!

**Pull request closed without merging**
