### PR TITLE
Improve time-interval datetime comparison performance

### PR DESCRIPTION
**Pull request by on99**
1. where created_at >= '2020-08-07 00:00:00' and created_at < '2020-08-08 00:00:00'
2. where date(created_at) >= '2020-08-07 00:00:00' and date(created_at) < '2020-08-08 00:00:00'

performance of 1 is better than 2 because of index, most of the
databases including mysql/postgres will do a full scan on table if there are
functions performed on table columns

###### Before submitting the PR, please make sure you do the following
- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.
### Tests
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by on99** [comment]
The code is run in our production for a year and it works pretty well. We have 4 billion rows in a table, full table scan is very slow, that's why I made this modification.

Can someone please take a look? @flamber @camsaul

**Comment by flamber** [comment]
Hi @on99 Thank you for the PR. I'll leave the review to Cam or one of the other Clojure developers.
I guess this is trying to fix #11502 - and perhaps some of the issues referenced in #11837 too?

**Comment by on99** [comment]
@flamber Thanks for your information. 

I think my pull request can fix some issues referenced in #11837 since `time-interval` is only applied to `previous` `current` `next`. I cannot come up with easy fix for `before` `after` `on` `between` for now.

**Review by sbelak — CHANGES_REQUESTED** [review]
Thank you for the PR. Making MB run faster is always greatly appreciated. I'm trying to understand why the existing optimizations from https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/optimize_datetime_filters.clj (for more context & rationale, see #11837 which introduced it) don't get applied in your case. After a quick glance I'm guessing due to time unit miss match. If so, that raises the question are the limitations set in optimize_datetime_filters.clj to narrow? Either way, I'd rather see the work concentrate on improving the optimizer, than applying low-level (ish) optimizations when de-sugaring (which in a pedantic way stops being sugar in the first place, as you can't really get to MBQL generated otherwise).

**Comment by on99** [comment]
@sbelak That's great! I find https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/optimize_datetime_filters.clj is applied to `before` `after` `on` `between`, but not `previous` `current` `next`(`time-interval`).

I'll try to improve this optimizer, though I am not sure if it's possible.

**Comment by on99** [comment]
After digging into the [source code](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/optimize_datetime_filters.clj#L33-L34), I found filter-clause only matches `:absolute-datetime`, however, `previous current next` generates `:relative-datetime`. 

For example, the filter-clauses generated are
* Between: `[:between [:datetime-field [:field-id 269] :day] [:absolute-datetime #t "2020-08-01T00:00Z[UTC]" :day] [:absolute-datetime #t "2020-08-09T00:00Z[UTC]" :day]]`
* Previous: `[:between [:datetime-field [:field-id 269] :day] [:relative-datetime -30 :day] [:relative-datetime -1 :day]]`
* Next: `[:between [:datetime-field [:field-id 269] :day] [:relative-datetime 0 :day] [:relative-datetime 2 :day]]`
* Current: `[:= [:datetime-field [:field-id 269] :day] [:relative-datetime 0 :day]]`

I am not so familiar with clojure, can you help fix the optimizer? @sbelak

**Comment by on99** [comment]
@sbelak Is the current optimizer is designed for `:absolute-datetime` only? Can we just optimize `:relative-datetime` in mbql? I think my pull request is simple enough to fix the performance issue, what do you think?

**Comment by pranas** [comment]
We made a custom build out of this and it solved our perf issues. @on99 thanks for the PR.

**Comment by camsaul** [comment]
Hi @on99, thanks for this PR. This is definitely a step in the right direction, but we want to optimize more than just usage of `:time-interval` -- we'd like to optimize filters like `[:> [:datetime-field [:field-id 1] :month] [:relative-datetime -1 :month]]` as well. I'm working on a PR that optimizes everything.

Thanks again!

**Comment by camsaul** [comment]
New PR: #14835

**Comment by on99** [comment]
This is great, thanks for your work! @camsaul

**Pull request closed without merging**
