### PR TITLE
Disable auditing when `site-uuid` nonces are initialized

### LINKED ISSUE #38009: Initializing MB from a config file is broken
### Describe the bug

If you start up a new instance of Metabase with `MB_CONFIG_FILE_PATH` set, and `MB_PREMIUM_EMBEDDING_TOKEN` set to a token that provides the `config-text-file` feature, it will nevertheless error with:
```
Execution error (ExceptionInfo) at metabase-enterprise.advanced-config.file/initialize! (file.clj:261).
Metabase config files require a Premium token with the :config-text-file feature.
`````

### To Reproduce

1. Set `MB_CONFIG_FILE_PATH` as described [here](https://www.metabase.com/docs/latest/configuring-metabase/config-file)
2. Set `MB_PREMIUM_EMBEDDING_TOKEN` to a token with full features
3. Start up Metabase with a fresh app DB

### Expected behavior

Should not error

### Logs

_No response_

### Information about your Metabase installation

```JSON
Current master
```

### Severity

unsure, feature might be totally busted

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crisptrutski**
Fixes https://github.com/metabase/metabase/issues/38009

### Description

With the [ntroduction of the [init mechanism](https://github.com/metabase/metabase/pull/37849/files) for app settings, we introduced a subtle change - the initialization of `site-uuid` settings is now audited.

Unfortunately this change broke the loading of the Enterprise feature flags when first populating the app database, due to a concurrency bug in the auditing code. This resulted in the app silently falling back to a "no feature flags" state. In the case where we are using a config file this issue is then exposure by an immediate crash during startup.

The details of the concurrency bug are quite detailed - see [this comment](https://github.com/metabase/metabase/issues/38009#issuecomment-1906910158) on the parent issue.

This PR simply reverts to the previous behavior - no auditing. 

### How to verify

1. Drop all tables in the app database.
2. Set `MB_CONFIG_FILE_PATH` to point to a config file. A placeholder is fine, it won't be loaded.
3. Set a `MB_PREMIUM_EMBEDDING_TOKEN`. It must have the right format, but won't be used.
4. Start the server.
5.  🌈 

Without this change you should get the following instead:

```
2024-01-23 06:02:29,724 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Metabase config files require a Premium token with the 
  :config-text-file feature. {}
```

### CODE REVIEW

**Review by qnkhuat — COMMENTED** [review]
are you sure we don't want to audit all the initialized values? It's a set so it feels like we should.

wdyt if we fix this by making `site-uuid-for-premium-features-token-checks` to never audit?
that should fix the deadlock issue.

**Comment by qnkhuat** [comment]
And sorry that I didn't review the earlier PR that you introduced, `:init,` but reviewing this PR got me to read about them, and I think it'd really help if we have a bit more document. especially for the `:init` option for `defsetting` and `bypass-read-only?` option for the `set!` function.

**Comment by crisptrutski** [comment]
> are you sure we don't want to audit all the initialized values? It's a set so it feels like we should.
> 
> wdyt if we fix this by making `site-uuid-for-premium-features-token-checks` to never audit? that should fix the deadlock issue.

Right now the UUIDs are the only settings using `:init`, and in the old implementation they use the same non-audited setters to init as in this PR. I wanted to be as conservative as possible and just go back to the old semantics for now, to unblock the next `0.48` release.

I'd like to get more input about whether we should enable or explicitly opt-out of audit for these uuids, and prefer not to pick a side in the codebase yet. We don't audit "default" so I think it's also OK if you think of init just as a "per site" default.

As far as the deadlock goes, there's an [independent fix](https://github.com/metabase/metabase/pull/38029) for that which allows us to keep auditing if we want, I'm hoping to merge both.

**Comment by crisptrutski** [comment]
> And sorry that I didn't review the earlier PR that you introduced `:init,` but reviewing this PR got me to read about them, and I think it'd really help if we have a bit more document. especially for the `:init` option for `defsetting` and `bypass-read-only?` option for the `set!` function.

Thanks for pointing out those spots. I plan to do a small clean up PR which also tightens up the schema, so I can update those docstrings at the same time.

**Comment by qnkhuat** [comment]
I think there is a subtle difference between init and default is that `init` will write to DB.
And I think audit_log is meant to track these writes, I'm not sure how important it is if it's the first write tho. Worth checking with @luizarakaki or @noahmoss

**Comment by crisptrutski** [comment]
After discussing with @luizarakaki I've changed this PR to explicitly . Since the race condition has been fixed in [another PR](https://github.com/metabase/metabase/pull/38029), I have re-enabled auditing for any future usage of `:init`.

**Comment by crisptrutski** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #38027** <a href="https://app.graphite.dev/github/pr/metabase/metabase/38027?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #37863** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37863?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #37870** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37870?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/38027?utm_source=stack-comment).

**Review by qnkhuat — APPROVED** [review]
Cool, LGTM!

**Pull request merged**
