### PR TITLE
Docker H2 to Postgres migration documentation

### PR DESCRIPTION
**Pull request by joshuashort**
Some documentation on migrating from H2 to Postgres with a Docker container. Let me know if it needs some work.

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by camsaul** [comment]
This makes sense to me. Thoughts @metabase/core-developers @salsakran ?

**Comment by joshuashort** [comment]
I'm not sure what the convention is for spacing between a new section and the end of an indented block, but I've updated this branch to only include the new content and not mess with existing formatting.

**Comment by camsaul** [comment]
@joshuashort it doesn't look like all the stuff you've added is correctly formatted markdown. Take a look at how the docs render at https://github.com/joshuashort/metabase/blob/docker-h2-migration-instructions/docs/operations-guide/running-metabase-on-docker.md

and you'll see what I mean

**Comment by joshuashort** [comment]
Thanks @camsaul! That's a bit embarrassing -- I was incorrectly copying how things were done in the section "Using Postgres as the Metabase application database". Is there a preference on using indentation vs. back-ticks for making code blocks? It's done both ways in this document.

**Comment by joshuashort** [comment]
Fixed the indentation..

**Comment by camsaul** [comment]
It doesn't really matter which one you use although the places that do both (triple-backtick *and* four-space indentation) look wrong to me so don't copy those 😉

**Comment by camsaul** [comment]
@salsakran this looks good to me. Can we merge this?

**Pull request merged**
