### PR TITLE
Drag on line/area/bar chart to filter

### PR DESCRIPTION
**Pull request by tlrobinson**
* [x] basically working
* [x] handle dates
* [x] handle numbers
* [x] disable for
  * [x] ordinal axis
  * [x] SQL questions
  * [x] dashboard multiseries
  * [x] ?
* [x] disable tooltips when dragging
* [x] UX / styling
- [x] Seems to prevent action menu from opening on line charts. I can't click on the points anymore. (This only seems to happen if the granularity is such that we're not displaying actual dots.) I can click on bars and bubble chart bubbles, but if I try to click on any of the actions I get a JS error and nothing happens:
-  ~~Re the above, if I click on `view these [x]`, I get taken to the result view but get a Metabase error: `Input to field-id does not match schema: [0;33m [(named (not (integer? nil)) id)] [0m`~~ - fixed I think?
- [x] I get this JS error if I try it on a dashcard timeseries, and nothing happens
- ~~doesn't appear to work on Postgres at all: I'm getting a blank chart if I try using it with our Pie dataset~~ unable to reproduce
- [x] feels weird to me that the resultant filters include hours and minutes in them
- [x] It feels like this should automatically change the granularity for me if I zoom on a segment that's smaller than the current granularity, otherwise I can get into a state where nothing is displayed even though something could be (like April 19–21 by Month should automatically switch to By Day)
- [x] once you're mid-drag, you can't cancel it out by hitting `esc` or something
- [x] if you drag off the browser window, the bounding box gets kind of weird
- [x] I can live with the little grippers, but would love to see if we could change them to something more Metabase-y

njhfr7buhs

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers if we want to squeeze this in 0.24 it would go nicely with the other "direct manipulation" additions (drill through / click actions, draw rect to filter map)

**Comment by salsakran** [comment]
it looks very sweet. @mazameli can you sherpa this? would love to include it in 0.24

**Comment by mazameli** [comment]
Yep I'll take a look right now.

**Comment by mazameli** [comment]
How hard would it be to customize the appearance of the grippers if we wanted to?

**Comment by mazameli** [comment]
This PR is still quite buggy:

- Seems to prevent action menu from opening on line charts. I can't click on the points anymore. (This only seems to happen if the granularity is such that we're not displaying actual dots.) I can click on bars and bubble chart bubbles, but if I try to click on any of the actions I get a JS error and nothing happens:

screen shot 2017-05-05 at 12 10 37 pm

- Re the above, if I click on `view these [x]`, I get taken to the result view but get a Metabase error: `Input to field-id does not match schema: [0;33m [(named (not (integer? nil)) id)] [0m`

- I get this JS error if I try it on a dashcard timeseries, and nothing happens:

screen shot 2017-05-05 at 12 13 38 pm

- doesn't appear to work on Postgres at all: I'm getting a blank chart if I try using it with our Pie dataset:
screen shot 2017-05-05 at 12 00 54 pm

- feels weird to me that the resultant filters include hours and minutes in them
screen shot 2017-05-05 at 12 00 25 pm

- It feels like this should automatically change the granularity for me if I zoom on a segment that's smaller than the current granularity, otherwise I can get into a state where nothing is displayed even though something could be (like April 19–21 by Month should automatically switch to By Day)
- once you're mid-drag, you can't cancel it out by hitting `esc` or something
- if you drag off the browser window, the bounding box gets kind of weird
- I can live with the little grippers, but would love to see if we could change them to something more Metabase-y

**Comment by tlrobinson** [comment]
Yeah, definitely a 1:00am work-in-progress PR :)

Modifying the grippers shouldn't be hard, if you want to come up with something for them.

**Comment by tlrobinson** [comment]
Ugggggh dc.js https://groups.google.com/forum/#!searchin/dc-js-user-group/brush$20dots%7Csort:relevance/dc-js-user-group/S9ICz0fGeoQ/mKiR49o-CgAJ

> Can I render data points in a line chart and keep the Brush on?

> Sorry, it doesn't look like there is any support for this currently.  The line chart's drawDots function explicitly drops out if the brush is on.  Feel free to open a feature request, or you could always just comment that out in your own copy. ;-)

**Comment by tlrobinson** [comment]
@mazameli I can easily change the handles to another SVG path (and change the stroke and fill colors). Here are the existing paths, it would be best if you could just modify them:

Left:

```
M-0.5,76.69275A6,6 0 0 0 -6.5,82.69275V147.3855A6,6 0 0 0 -0.5,153.3855ZM-2.5,84.69275V145.3855M-4.5,84.69275V145.3855
```

Right:

```
M0.5,76.69275A6,6 0 0 1 6.5,82.69275V147.3855A6,6 0 0 1 0.5,153.3855ZM2.5,84.69275V145.3855M4.5,84.69275V145.3855
```

**Comment by mazameli** [comment]
Cool, I'll take a look at modifying them.

**Comment by tlrobinson** [comment]
Although now that I think about it, arguably the handles aren't really necessary since you can't adjust it once you mouseup, unlike in the "normal" dc.js usage where it applies a filter to all the other charts on the page and you can adjust it.

**Comment by mazameli** [comment]
Yeah maybe let's just see how it looks without them?

**Comment by tlrobinson** [comment]
@mazameli Alright I think I've fixed all the issues you found.

It's feeling pretty good, IMHO.

**Comment by attekei** [comment]
My notes of the UX (didn't do a code review yet):

### Problems with filtering in line/area/bar charts

Sometimes the drag filtering work intuitively, sometimes it doesn't. The biggest grip for me is that the change in granularity depends unsystematically on the size of dragged area and whether there are data points inside that area or not. 

#### Examples of situations where the filtering works as I would expect:

- When I drag an area which contains a single data point in chart with yearly/month/week granularity, I very logically jump to a chart with the next, more precise granularity 
(yearly->monthly, monthly->weekly, weekly->daily).

#### Examples of situations where I'm surprised of the result:

- When I have a year-by-year chart and I drag an area that doesn't contain data points at all, then it results in a strange time range with the smallest possible granularity:
screen shot 2017-05-11 at 11 04 50

- In day-by-day chart it's hard to predict what the hour range will be in the filter after dragging. For instance, doing dragging like this doesn't filter until midnight as I would expect:
value1
screen shot 2017-05-11 at 11 12 09

#### Possible solutions

- It would make sense for me if the filters would be based solely on the data points contained in the dragged area. If no data points are inside the area, then any filtering would not happen. IMHO the change in granularity should be always be standard (year->month, quarter->week?, month->week, week->day, day->hour, hour->minute). 

- Would be logical if the data points inside the hovered area are highlighted.

### Drill-through/lineage

- Click actions for bar charts don't seem to work.

- Should line/area graph data points have `cursor: pointer` when hovering them? Currently the cursor doesn't change (this also applies to 0.24, not only to this branch).

- The "started from" lineage is broken for both drill-through and drag filtering in this branch. Oftentimes even the "New Question" title disappears and the title header is left completely empty.

**Review by mazameli — CHANGES_REQUESTED** [review]
- If I click "back to last run" after getting no results, I arrive at the same no results screen; pushing "back to last run" a second time works, though. It seems I also have to click Back twice if I'm on a filtered view of a chart, too.

> I get this JS error if I try it on a dashcard timeseries, and nothing happens

- This at first was not fixed for me, but then it started working weirdly after a bit. I'll keep my eye on this.

- When filtering on bar charts, the interaction is a little unclear in terms of how much of the first/last bar I need to encompass with my dragged box to include it. I.e., in a by-week time series bar chart, if I only drag over half of a bar at the right edge of my box, that week isn't included. I think I'd expect it to include a bar as long as it's partially included in the dragged area.

- I see you've noted a to-do item to disable this for dashcard multiseries, and that makes sense for now (until we possibly change the way multi-series questions are constructed).
- It's pretty hard to use with area charts, because if you start the drag in the middle of a shaded area, the drag doesn't initiate, because presumably it's listening for the click to open the drill-through menu. 
- Incidentally, that menu is not showing up when clicking on the shaded part of an area chart like it should. Same with bar charts: not seeing the drill through menu when clicking on a bar.
- 2D charts, like count of orders over time broken out by product category, don't seem to be rendering at all.
- Love the ability to cancel the drag with esc
- When clicking "view these orders" on a scatterplot broken out by time I'm getting this error: `Input to field-id does not match schema: [0;33m [(named (not (integer? nil)) id)] [0m`

**Comment by tlrobinson** [comment]
That's pretty much the behavior I was going for, and I'm not sure anything about it is currently technically wrong, just slightly weird UX. When going from day to hour it does 12am to 11pm, bucketed by *by hour*, which results in the full day (it includes the full 11pm hour).

That was done in response to @mazameli's observation that the ranges included times when they didn't need to, so now it just rounds to the same unit as a the granularity. We could use some different logic for formatting the date filter (always by date unless granularity is <= hour, then use date+hour+minute?) 

If you believe it's behaving incorrectly, and not just displaying the filter strangely, can you show me a case on a `count`/`sum` graph where you drag over some points, and the points on the filtered graph don't add up to the same as what you dragged over?

As far as the granularity progression, it seemed better to pick the granularity with at least some minimum number of points, currently 5, which effectively just skips the `quarter` granularity, which I felt was a too sparse when zooming on a single year.

> Should line/area graph data points have cursor: pointer when hovering them? Currently the cursor doesn't change (this also applies to 0.24, not only to this branch).

#5056

> The "started from" lineage is broken for both drill-through and drag filtering in this branch. Oftentimes even the "New Question" title disappears and the title header is left completely empty.

#5088

**Comment by tlrobinson** [comment]
> When filtering on bar charts, the interaction is a little unclear in terms of how much of the first/last bar I need to encompass with my dragged box to include it. I.e., in a by-week time series bar chart, if I only drag over half of a bar at the right edge of my box, that week isn't included. I think I'd expect it to include a bar as long as it's partially included in the dragged area.

I've changed it to fade out the unselected bars, which should help this. I can change the style if to something other than the default, if you like.

I think it will be difficult to adjust where exactly the bar becomes selected (currently the center), though I can probably get the snapping behavior as seen on the bar chart here: https://dc-js.github.io/dc.js/

dc.js doesn't have fading of unselected dots/lines built in, but I could probably add it, if desired, though it's probably not as critical for lines though since it's more obvious when a point will be selected.

**Comment by mazameli** [comment]
Cool, I'll check out the fading; I imagine that'll help.

Also, I'm seeing that if my granularity is set to Week, using the draggable filters causes the filter dropdown to use the old "5th week, 23rd week" etc. style.

screen shot 2017-05-11 at 1 46 48 pm

**Comment by tlrobinson** [comment]
@attekei Ok I've improved the logic for generating the filters to something I think will resolve your concerns. The filters are equivalent to what I had before, but they use the existing granularity rather than the new granularity, which makes more sense.

It also collapses `BETWEEN` to `=` if the start and end are the same. If you select one day you now get "Created At: Day is January 1, 2017" instead of "Created At: Hour between 12AM January 1 and 11PM January 1".

**Comment by attekei** [comment]
@tlrobinson Cool, a huge improvement to the earlier experience!

I encountered just a few issues that should be easy to fix:

- This still applies in the latest version (and also to other granularities than year): 
> When I have a year-by-year chart and I drag an area that doesn't contain data points at all, then it results in a strange time range with the smallest possible granularity 

screen shot 2017-05-12 at 10 50 20

- Seems that there is a duplicate entry in browser history, which makes returning to the previous chart a little inconvenient (edit: just noticed that Maz had encountered the same issue too)

- I would (still) like to see the data points inside the dragged area being highlighted

**Comment by tlrobinson** [comment]
> Also, I'm seeing that if my granularity is set to Week, using the draggable filters causes the filter dropdown to use the old "5th week, 23rd week" etc. style.

We didn't update the default formatting. I'm not sure if we decided on a default formatting. I think that's primarily used there and in the filter values, if you happen to filter by weeks (currently the only way is via this feature or drill through)

If you can tell me what the new default should be and I do another PR for that.

**Comment by tlrobinson** [comment]
> When I have a year-by-year chart and I drag an area that doesn't contain data points at all, then it results in a strange time range with the smallest possible granularity

What do we think the desirable behavior is? Don't apply the filter at all?

> I would (still) like to see the data points inside the dragged area being highlighted

We have that for bars. Are you talking about the dots on line charts?

**Comment by mazameli** [comment]
> We didn't update the default formatting. I'm not sure if we decided on a default formatting. I think that's primarily used there and in the filter values, if you happen to filter by weeks (currently the only way is via this feature or drill through). If you can tell me what the new default should be and I do another PR for that.

Cool, I'll file that as a separate issue.

**Comment by mazameli** [comment]
Is draggable filtering supposed to be disabled for _all_ dashcards, or only multi-series ones? Seems like it makes sense to disable it on multi-series, but less sense on single series dashcards. In any case, if it's disabled it would be cool if the dragging animation/box didn't display.

**Comment by mazameli** [comment]
Drill-through menu still not appearing on area or bar charts, with the exception of 2D area charts (weird). Not seeing any JS errors.

**Comment by mazameli** [comment]
Still getting that error when clicking `view these orders` on scatterplot broken out by time.

Scatterplot chart:

screen shot 2017-05-12 at 12 30 48 pm

After clicking `view these orders` on one of the dots. Note the weird `field 1480` filter, which I think corresponds to what the `count` was at that point:

screen shot 2017-05-12 at 12 30 56 pm

**Comment by mazameli** [comment]
One thing that's made a little tricky by this is clicking outside of the drillthrough menu to close it, because a single click event on a chart seems to get eaten by the drag-filter listener. It would be nice if a single click on a chart would just close the drill through menu if it's open.

**Comment by mazameli** [comment]
Everything else is great besides the 4 comments I left above. 👏

**Comment by salsakran** [comment]
I feel like it's a little too easy to get into filtering mode for some reason. And once I've filtered, and I *really* want to be able to pan around.

**Comment by tlrobinson** [comment]
> I feel like it's a little too easy to get into filtering mode for some reason.

@salsakran What do you suggest?

I might be able to tweak it so it doesn't activate unless you mouse down for a minimum period, or drag a minimum number of pixels.

> And once I've filtered, and I really want to be able to pan around.

Panning is a fairly different feature, at least implementation-wise.

I'm not sure how the interactions would work either. I feel like it would be weird to sometimes have dragging filter/zoom and sometimes have it pan.

Perhaps in timeseries mode we could "remember" the unzoomed query results (either client-side or in the cache?) and show a small context scrubber thingy at the bottom (until you modify the aggregation/breakout/etc).

image

I think I'd prefer to do that as a follow on though.

**Review by attekei — COMMENTED** [review]
I love the highlighting of data points inside the dragged area for line/area points! Also in general the interactions feel pretty solid in all visualization types. I found two issues:

1. Trying to apply the row chart visualization results in an error:
screen shot 2017-05-22 at 13 24 07

2. In area charts, you are not able to drag if your mouse is inside some of the areas that have a fill color. 

I think that (1) is blocking but (2) could be addressed in a follow-on PR.

**Pull request merged**
