### PR TITLE
Change "Data Model" to "Table Metadata"

### PR DESCRIPTION
**Pull request by mazameli**
Changes the string in the nav bar, the reducer, and docs. @jeff-bruemmer, the thing I'm uncertain about in the docs are the permissions bits: I can't recall the full scope of the "data modeling" permissions and whether it only encompasses the "Data Model" section or if it also affects Models.

image

### CODE REVIEW

**Comment by jeff-bruemmer** [comment]
We should also change the data permissions "manage data model" option:

image

**Comment by brunobergher** [comment]
FYI @luizarakaki on the permission name change

**Comment by mazameli** [comment]
@jeff-bruemmer, good call. Pushed a commit. Could I please ask for a full review now? 🙏🏼

**Review by jeff-bruemmer — COMMENTED** [review]
This is probably too picky, but I want to hold off on approval so we can discuss one aspect of this change that's kind of goofy.

image

The current Data Model tab houses three sub-tabs:

- Data
- Segments
- Metrics

The "Data Model" name fits this setup, whereas "Table Metadata" only fits the Data sub-tab. 

I know we're working on Metrics 2.0, but I don't know where metrics will end up in the product, and I don't want to accidently "hide" segments and metrics behind semantic imprecision. Just want to raise this case so we're deliberate about the decision, not overlooking it.

**Comment by mazameli** [comment]
@jeff-bruemmer I hear you, but I don't think we care much about the old metrics 1.0 or segments 1.0 features. And in a way, given that they're currently inextricably tied to tables, they kinda _are_ table metadata.

**Review by jeff-bruemmer — APPROVED** [review]

**Pull request merged**
