### PR TITLE
Virtual tables v1

### PR DESCRIPTION
**Pull request by agilliland**

### CODE REVIEW

**Comment by soilforlifeforms** [comment]
Any news on when this will be merged?

**Comment by that0n3guy** [comment]
does this relate to: https://github.com/metabase/metabase/issues/1822?

**Comment by aguynamedben** [comment]
Thanks for the hard work on this!

**Comment by shrav** [comment]
@agilliland, this feature would be very valuable to my team. Is there anything I can do to help drive this to completion?

**Comment by agilliland** [comment]
There is still quite a bit of work to be done on this feature and unfortunately I'm not able to dedicate the time to it, so it's on pause for the moment unless someone else wants to pick it up.

**Comment by shrav** [comment]
@agilliland I might be able to help, can you tell me what's left?

**Comment by agilliland** [comment]
There is honestly a lot of work remaining, so it would not be a small task.  The frontend is subbed out and largely functional in this PR, but the backend requires a great deal of work and there are large implications across the entire app to introduce this feature.

**Comment by salsakran** [comment]
closing this in favor of the approach in #1822

**Pull request closed without merging**
