### PR TITLE
Make DataSelector load metadata on demand

### PR DESCRIPTION
**Pull request by tlrobinson**
This refactors `DataSelector` to load metadata on demand as databases/schemas/tables are clicked.

Frontend TODO:

1. Manually validate all uses of `DataSelector` work as expected:
     - [x] `DatabaseSchemaAndTableDataSelector`
          - [x] `DataStep` and `JoinStep` (notebook mode)
          - [x] `QuestionDataSelector` (chill mode)
          - ~`GuiQueryEditor` (segment/metric editor in data model)~
     - [x] `DatabaseDataSelector`
          - [x] `NativeQueryEditor` (native query builder)
     - [x] `SchemaAndTableDataSelector`
          - [x] `NativeQueryEditor` (native query builder)
     - [x] `SchemaTableAndFieldDataSelector`
          - [x] `TagEditorParam` (native query template tag editor)
2. Add automated tests
      - ideally integration tests which exercise the Redux and Metadata code? We have `frontend/test/metabase/query_builder/components/DataSelector.integ.spec.js`. 
There's not much there yet but maybe a good starting point.
3. I believe the data reference (in native query builder, not `/reference`) will also need to load data on demand now since we can't assume it's already loaded up front?

Backend TODO:

1. [x] we need an endpoint to get a single databases' tables but **not** fields, which currently `GET /api/database/:dbId/metadata` currently does.
    - Along the lines of #10035, I think it would be nice if we had a generic `includes` argument to specify which nested objects are included, e.x. `/api/database/:id?include=tables` and  `/api/database/:id?include=tables.fields`
    - But `GET /api/database/:dbId/tables` would be fine for now too
2. **If** we're keeping the "Saved Questions" database in the `DataSelector` as it current is (I'm not sure we should), where all collections (even nested ones) are in a flat list of fake "schemas", then (`-1337` is the fake "Saved Questions" database ID)
    - [x] `GET /api/database/-1337/schemas` should work
    - [x] `GET /api/database/-1337/schema/:schemaName` should work
    - [x] `GET /api/database`'s `include_cards` flag should be replaced with something like `?saved` which should cause the "Saved Questions" database but **not** the cards themselves to be included. If `include_tables` (or `include=tables` as in # 1) is also provided then **both** real tables and saved question "tables" should be included under their respective databases. It never really makes sense for the frontend to request `include_cards` without `include_tables` (ideally that should be covered by `GET /api/database/-1337?include=tables` or whatever)

### CODE REVIEW

**Comment by tlrobinson** [comment]
@salsakran regarding blocking rendering on the new question page, we definitely don’t need to block on the `include_tables`/`include_cards` API calls, but we do load the list of databases in order to know whether you have data access (gui or native) so we can show the appropriate buttons. Is that ok?

**Comment by salsakran** [comment]
That's a good reason to load databases (sans tables or cards) =)
I forgot that the list isn't 100% static.

**Comment by salsakran** [comment]
@tlrobinson would all this be simpler if we had a GET schemas endpoint?

**Comment by tlrobinson** [comment]
> @tlrobinson would all this be simpler if we had a GET schemas endpoint?

Not really in this case. There's functionality to load data when changing steps https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/DataSelector.jsx#L304-L308 but DataSelector has database+schema as the same "step": https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/DataSelector.jsx#L24

**Comment by tlrobinson** [comment]
In fact, we already have ` GET /api/database/:id/schema`.

**Comment by salsakran** [comment]
Does it make sense to have those two be in the same step? If that were unwound, would scalability here be much simpler?

**Comment by tlrobinson** [comment]
I've attempted to do basically that twice now, and honestly, `DataSelector` is a bit of a mess.

**Comment by tlrobinson** [comment]
I'm tempted to just rewrite it. These are the versions of DataSelector currently used (and where they're used):

```
DatabaseSchemaAndTableDataSelector
    GuiQueryEditor
    DataStep
    JoinStep
    QuestionDataSelector

SchemaTableAndFieldDataSelector
    TagEditorParam

DatabaseDataSelector
    NativeQuerySelector

SchemaAndTableDataSelector
    NativeQuerySelector
```

They're all some subset of the `Database`, `Schema`, `Table`, and `Field` steps

```
Database Schema Table       DataSelector
         Schema Table Field DataSelector
Database                    DataSelector
         Schema Table       DataSelector
```

I think it could be simplified a lot.

**Comment by paulrosenzweig** [comment]
👍 on killing the unused getting started thing. Maybe we can merge that as its own PR if this is going to be bigger and involve a rewrite of the data selector?

---

Rewriting `DataSelector` makes sense to me. I've only had to change stuff in there once, but I remember being pretty confused. 

An alternate half-way solution: If you don't think it's worth a rewrite yet, maybe we leave the giant db+tables load call in one piece but move it into `DataSelector` on open. That wouldn't fix the problem but would delay the lag until it's going to be displayed. Also, people who open the QB just to view a question don't need to load it.

**Review by paulrosenzweig — APPROVED** [review]

**Pull request merged**
