### PR TITLE
[Manual backport] Show "Starting from" filters only when expressions are supported

### PR DESCRIPTION
**Pull request by ranquild**
Backports https://github.com/metabase/metabase/pull/24487

### CODE REVIEW

**Review by WiNloSt — COMMENTED** [review]
I see the one line that caused the backport conflict is from https://github.com/metabase/metabase/pull/24218. Do you think that PR should be backported too since [this line was in the original PR](https://github.com/metabase/metabase/pull/24487/files#diff-60689b6635fb875459527c1f9090bf6d4342bd363e671085170819b3ca85df8cL160)?

**Comment by ranquild** [comment]
@WiNloSt I think not. The PRs are unrelated

**Comment by WiNloSt** [comment]
@ranquild The one line that was introduced in #24218 is
https://github.com/metabase/metabase/pull/24218/files#diff-60689b6635fb875459527c1f9090bf6d4342bd363e671085170819b3ca85df8cR158

Which was removed by the original PR of this backport
https://github.com/metabase/metabase/pull/24487/files#diff-60689b6635fb875459527c1f9090bf6d4342bd363e671085170819b3ca85df8cL160

I mean, if the original PR doesn't contain that one line, the automatic backport should have worked. So, I'm not sure that **not** including that one line would make the release branch work as intended. Because if #24218 is backported after this backport PR is merged, there won't be [this change](https://github.com/metabase/metabase/pull/24487/files#diff-60689b6635fb875459527c1f9090bf6d4342bd363e671085170819b3ca85df8cL160) on the `release-x` branch i.e. the `reverseIconDirection` prop that is removed in this PR will still exist https://github.com/metabase/metabase/blob/fc5dc37686980f129f2710307a8bbd60da0413b9/frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.tsx#L158

However, if we don't backport #24218 then this PR should be good to go.

I hope I got my point across. Other than that single line, this backport looks exactly like the original PR, which is supposed to work since it's already merged.

**Comment by ranquild** [comment]
@WiNloSt thanks for the detailed explanation. I believe the release will be in a few hours and we are not going to backport the referenced PR.

**Review by alxnddr — APPROVED** [review]

**Pull request merged**
