### PR TITLE
Remove delete button from archive app

### LINKED ISSUE #18372: Delete button appears on archived collection
**Describe the bug**
A collection can't be deleted, but when we select an archived collection, the Delete button appears but it does nothing

**Logs**
No logs at all

**To Reproduce**
1) create a collection
2) archive it
3) go to the archiving section
4) select a collection with the icon
5) click on delete button

**Expected behavior**
The delete button should not appear

**Screenshots**
image

Very related to #2783

### PR DESCRIPTION
**Pull request by gusaiani**
Closes #18372 

⚠️ This is conceptually wrong - for now. 
See discussions below.

### How to test

1. Create a collection
2. Archive it
3. Go to http://localhost:3000/archive
4. Select a collection by clicking on the checkbox to the left of the collection name

You should see a bar at the bottom of the window.
It should include an `Unarchive` button.
It should no longer include a `Delete` button.

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
It should not remove the Delete button.
The Delete button should be available for elements that can be deleted (questions, dashboards, etc).

**Comment by gusaiani** [comment]
@flamber Hmm thanks, now I think I get it.

**Comment by flamber** [comment]
There's no endpoint for it #2783 - guess it might have been because it can be difficult to understand the consequences from deleting a collection (since it would delete everything within the collection and sub-collections). And we're not presenting archived collections well either (#4013).

**Comment by gusaiani** [comment]
@flamber, thank you very much for explaining.

Let me bring in @mazameli and @kdoh to see if they have a point of view on this.

The way this works now is indeed inconsistent.

The delete button is displayed if we select any archived item.

We could do a mix of the following (among others I'm sure):

<ol>
<li>print a warning that collections won't be deleted (at least users won't be confused when deleting and collections stay there)</li>
<li>not render the delete button if the selected items happen to only be collections</li>
<li>implement deleting collections
  <ol type="a">
    <li>Deleting all items within a collection, which is probably way too destructive</li>
    <li>Preserving all items within a collection, which to me makes sense. Items may live independently, continue to live in other collections and so on.</li>
  </ol>
</li>

This would need to pass the prioritization funnel too, so please let us know what you think.

**Comment by gusaiani** [comment]
Will come back to it in the future, as design is unclear.

**Comment by yasergsi** [comment]
I would like to have this feature as well since when I archive a collection and create a new one with the same name it adds a sequential serial number as a suffix to the collection name which looks VERY BAD when clients view it on our website which has full app embedding in Enterprise version.

**Pull request closed without merging**
