### PR TITLE
Add `updated` special type for timestamps

### PR DESCRIPTION
**Pull request by dpsutton**
keyed off of column names that include "update" which are date, time,
or datetime columns.

addresses https://github.com/metabase/metabase/issues/12386

### CODE REVIEW

**Comment by dpsutton** [comment]
Questions:
- do i need a tag to run frontend tests?
- i added the new type to the few spots i thought was needed on the frontend but not sure if i got them all
- is there any X-Ray stuff I need to do? As far as i can tell this doesn't do anything at all really, just adds a new tag that nothing really cares about. What needs to happen to hook this up somewhere useful?

**Review by sbelak — APPROVED** [review]

**Review by kdoh — APPROVED** [review]
Nothing about this seems off, but I'll be the first to say I don't fully know how the BE / FE types collide. This particular case seems like a good use for `.cljs`

**Comment by dpsutton** [comment]
Adding cljs seems like a pretty big step. I think we serialize some information for settings into json and that approach seems like it would benefit here as well. Adding cljs to the frontend will necessarily add a large bundle for the clojurescript runtime, a penaly we may not want to pay if we just need a type hierarchy.

**Review by paulrosenzweig — APPROVED** [review]
LGTM! I think the frontend gets the type hierarchy tree from the server, so this should be all that's needed.

> do i need a tag to run frontend tests?

Nope they run by default

**Pull request merged**
