### PR TITLE
boilerplate for including plugins in elastic beanstalk

### PR DESCRIPTION
**Pull request by ericcj**
Adds configuration so that beanstalk users can simply add plugin jars to .ebextensions/metabase_plugins and re-zip metabase-aws-eb.zip instead of everyone having to write the configs themselves as per 

https://discourse.metabase.com/t/installing-plugins-oracle-driver-on-an-aws-eb-instance/5539
https://discourse.metabase.com/t/metabase-plugin-and-aws-elastic-beanstalk/15300
https://discourse.metabase.com/t/metabase-elasticbeanstalk-athena/11320

- [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/26318)

### CODE REVIEW

**Comment by ericcj** [comment]
Failing tests don't seem related to these changes

**Comment by ericcj** [comment]
@paoliniluis could I get a review of this?  I merged upstream to ensure tests pass

**Comment by ericcj** [comment]
@jeff-bruemmer could i get a review of this one?  thanks!

**Comment by paoliniluis** [comment]
@ericcj we're no longer recommending beanstalk. I really don't think that this will ever be merged. In fact, I think that we will deprecate beanstalk artifacts altogether at some point in the near future

**Comment by ericcj** [comment]
oh bummer.  there's a few moving pieces to actually run metabase in production and although beanstalk is kinda janky it at least fills them all in instead of having to roll them yourself, and doesn't seem to be going anywhere per https://github.com/aws/elastic-beanstalk-roadmap/projects/1  Seems simplest to just keep that but if it must go then have you considered another way to template it like cloudformation with App Runner or ECS?

**Comment by paoliniluis** [comment]
@ericcj things might go that way, yes. We know that AWS won’t deprecate it, but let’s face it: it became one of the least supported services in their stack

**Comment by ericcj** [comment]
ya i'm no fan of beanstalk, but it's worked generally ok for us for a few years now.  i AM a big fan of open source metabase so i'm hoping that doesn't become prohibitively complicated for others to run

**Comment by ericcj** [comment]
closing since metabase no longer recommends beanstalk https://discourse.metabase.com/t/elastic-beanstalk-no-longer-recommended/31708 but gave this branch another update for posterity to recommend a bigger instance type and setting Xmx per https://www.metabase.com/docs/latest/troubleshooting-guide/running#metabase-fails-to-start-due-to-heap-space-outofmemoryerrors because of https://github.com/metabase/metabase/issues/34754#issuecomment-1767271789

**Pull request closed without merging**
