### PR TITLE
Visualization: Bar chart not showing 0 values unlike line and area chart

### LINKED ISSUE #22442: Visualization: Bar chart not showing 0 values unlike line and area chart
This is the only option when choosing bar chart.

image

Whilst below images are for Line and Area chart.

image
image

This is the same as for previous metabase version that I was on around v0.3+

However, there was a workaround (just switch to line/area chart then select **"Replace missing values" with Zero** then revert to bar chart, missing values would then be replaced with 0 value) that I did back then that is now not working on my current version.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1077-azure",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #22442

###### Before submitting the PR, please make sure you do the following

- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### Demo
https://www.loom.com/share/416b312bcda74fdaa1cd3ab3fcb541d9

### CODE REVIEW

**Comment by flamber** [comment]
I'm guessing this is trying to address #22442?

**Comment by gitstart** [comment]
@flamber yes! sorry for missing the tag

**Comment by gitstart** [comment]
@alxnddr Thank you for the review, PR has been updated now. Could you please review again?

**Review by alxnddr — APPROVED** [review]
Work as expected, thank you for your contribution!

**Pull request merged**
