### PR TITLE
Close Stale PRs after a year of inactivity

### PR DESCRIPTION
**Pull request by iethree**
This marks PRs as stale after 1 year of inactivity, and automatically closes them if they are inactive for 1 week after being marked stale. It also removes an unused config from a prior stale-archiving workflow.

for context, here are how many PRs are stale for a few different time periods

time | stale PRs | link
--- | --- | ---
1 year | 20 | https://github.com/metabase/metabase/pulls?q=updated%3A%3C%3D2021-10-17+is%3Aopen+
6 months | 40 | https://github.com/metabase/metabase/pulls?q=updated%3A%3C%3D2022-04-17+is%3Aopen+
3 months | 75 | https://github.com/metabase/metabase/pulls?q=updated%3A%3C%3D2022-07-17+is%3Aopen+

### CODE REVIEW

**Comment by flamber** [comment]
I completely disagree with automation. We have already tried this once before and removed it #11740.
We should either completely say that we're not interested in PRs or make an active effort to get them across the merge line, and of course actively close PRs that we won't accept instead of just have them linger (and be auto-closed).

**Comment by camsaul** [comment]
> We shouldn't ever be in a position that we have X months old open PRs in the first place.

Well... we are in that position, so the bot is there to help catch ones that fall thru the cracks. I'm a big fan of having automation do stuff for us to free up our time to do actually important stuff. Getting the number of open PRs down to something more manageable will mean less things fall thru the cracks going forward. Right now it's sort of overwhelming with how much stuff is in there, and at least half of our open PRs are ones that are stale and probably never going to get merged 

And it's not like you can't easily reopen a PR anyway if it gets closed but we didn't want it closed.

**Review by camsaul — APPROVED** [review]
Well, I am strongly in favor of this. It sounds like the rest of the eng team is as well. But we should try to convince Flamber and Nemanja so we're not merging this over their objections

**Comment by iethree** [comment]
Lets' give it a try. We can always revert!

**Pull request merged**
