### PR TITLE
Fix multiseries chart without data in the first series

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resovles #9893

The core problem was that when a series is empty, the column types are returned as `type/*`. If the _first_ series had no rows returned, the saved metrics and dimensions would be invalid. This would lead to the confusing error message "What fields do you want to use for the X and Y axes?"

Why just the first series? When checking for validity we destructured the first series, but ignored any others.

The fix I made here was to change the two relevant `isValid` functions to check if **any** series is valid.

old:
```js
isValid: ([{ card, data }], vizSettings) => stuff
```

new:
```js
isValid: (series, vizSettings) => series.some(({ card, data }) => stuff
```

Is this the right change? It definitely seems wrong to only look a the first series to check validity, but without seeing this bug, I would have guessed the right answer is to use `every` here rather than `some`.

As an alternative, is it possible to have results with no rows still return the type of the columns? That would let us use `every` every even when results have no rows.

If we _do_ want to keep this change, should I update the other settings defs beyond, `graph.metrics` and `graph.dimensions`? There are a handful of others that similarly destructure the first series.

### CODE REVIEW

**Review by tlrobinson — COMMENTED** [review]
I think ideally the backend would return the correct column metadata even if there are no rows, but I'm not sure if that's possible for SQL queries. @camsaul?

If that's not possible, I think this is a fine solution. As far as doing the same for other settings, I that might make sense for ones where `useRawSeries` is `true`.

Separately we probably shouldn't be showing messages like `Which fields do you want to use...` on dashboards at all (a generic error message would be better) but that can be handled separately.

**Comment by camsaul** [comment]
It's not really possible for SQL the way things work now. It might be possible by querying the JDBC resultsetmetadata but it still wouldn't work for Druid or Mongo unfortunately.

**Comment by paulrosenzweig** [comment]
> As far as doing the same for other settings, I that might make sense for ones where `useRawSeries` is `true`.

I started implementing this logic in a [more general place](https://github.com/metabase/metabase/blob/fix-9893/frontend/src/metabase/visualizations/lib/settings.js#L141) with the intention of having `isValid` always expect a single series and the `.some` being applied whenever `useRawSeries: true`. I ended up tossing that out and just doing it in the `isValid` function itself because there was only one more place that needed it.

Is it worth implementing it in a more general place? The `.some` logic still feels weird to me, so maybe it's better to keep it localized to each `isValid`.

**Comment by tlrobinson** [comment]
My main question with this is if we apply the `.some` thing to `isValid` don't we also need to apply similar logic to `getDefault`? `getDefaultColumns` only looks at the first series entry.

**Review by tlrobinson — COMMENTED** [review]
My main question with this is if we apply the `.some` thing to `isValid` don't we also need to apply similar logic to `getDefault`? `getDefaultColumns` only looks at the first `series` entry.

**Comment by paulrosenzweig** [comment]
> don't we also need to apply similar logic to `getDefault`?

I _think_ for this bug, we don't. Here the `graph.dimensions` setting is already set but then new data with no rows was breaking things.

It seems like we'd want `getDefault` if users were configuring the chart when one series was empty. Is that right? Still not sure that means `getDefault` shouldn't look at all the series.

**Review by tlrobinson — APPROVED** [review]

**Pull request merged**
