### PR TITLE
Split Chinese i18n into zh, zh-HK, and zh-TW variants

### PR DESCRIPTION
**Pull request by paulrosenzweig**
After updating `zh-Hant` to `zh-HK` in PO editor, the import script should be run with the new variants to download them:

`./bin/i18n/import-po-from-poeditor zh zh-TW zh-HK`

### CODE REVIEW

**Comment by mazameli** [comment]
@paulrosenzweig, I've pushed up the three Chinese .po files. One note is that the Hong Kong file was lowercase in PoEditor, `zh-hk`, so I left its filename like that; let me know if I should change that.

**Comment by mazameli** [comment]
@paulrosenzweig, I also just went ahead and updated the rest of our added languages for 0.35, and have removed Turkish (85%) and Vietnamese (87%).

This PR will now fix https://github.com/metabase/metabase/issues/12187.

**Comment by mazameli** [comment]
Looks like there are some delightful newline errors in some of the translations. Fixing now…

**Comment by paulrosenzweig** [comment]
OK I think I fixed the issues around casing and `_` vs `-`. Here's the way it works now:
* Country codes are upcased while downloading the .po files.
* Hyphens are convert to underscores when generating the JSON and java class files.

**Comment by mazameli** [comment]
Could @tlrobinson or @camsaul give this a review por favor?

**Comment by camsaul** [comment]
I took a look but I think Tom is a better person to review this.

**Review by tlrobinson — APPROVED** [review]

**Pull request merged**
