### PR TITLE
Adjusting style of Column Title label in Table Viz

### PR DESCRIPTION
**Pull request by npfitz**
[Notion Doc](https://www.notion.so/metabase/Maz-notes-on-viz-settings-67aed0e4ddcc4d4a83028992c4301820#30166395d0814c83bba503dc8474c612)

Adding `form-field` variant to Column Title setting in Table Viz.

After:
image

### CODE REVIEW

**Review by WiNloSt — APPROVED** [review]

**Review by alxnddr — COMMENTED** [review]
We should increase the label font-size according to [mockups](https://www.figma.com/file/5FVngMnCsuapn6wWzOFOYQ/viz-fixes?node-id=4%3A916&t=invoPEaFNdsIZqvz-0). It is too small so it is not good for a11y.

Also, can you please update it for other elements?
Screen Shot 2022-11-28 at 2 24 48 PM

On the data model page labels look more consistent:
Screen Shot 2022-11-28 at 2 25 53 PM

I believe we should have just one variant

**Comment by npfitz** [comment]
Yeah, we can adjust that. I think we have a few different screenshots floating around and some might be out of date. We do say [here](https://www.notion.so/metabase/Viz-fixes-d667bd245a0047b180da43f708f54a9d#4fe3b8cf72f0461db5e7c59b3186d7ee) though that font size of labels in the popup should be 12px. (we also say the color should be `text-dark`)

**Comment by naatz-co** [comment]
On header settings, we should stick to text-dark and 14px

On popover settings, I agree with Sasha, the font could be bigger, so changing to 14px would be good. I tried to add the medium text input field to clean things, but it doesn't work in all cases, so it's better to stick in a single pattern and use text-dark (`#4C5773`) + 14px on popovers too. 

Sorry for the confusion, guys.

**Comment by npfitz** [comment]
No problem! I'll take care of that in the morning 👍

**Comment by npfitz** [comment]
I removed all instances of `label: "form-field"`. This should force all labels in the popups to be `font-size: 14px; color: 'text-dark'`.

**Pull request merged**
