### PR TITLE
Update dep: react-redux

### PR DESCRIPTION
**Pull request by gusaiani**
⚠️ Checking CI

### CODE REVIEW

**Comment by ariya** [comment]
Please note for major dependency update like this (not for bug fixing), we shall do it in the master branch to minimize the regression risks.

**Comment by gusaiani** [comment]
Noted @ariya, thank you

**Comment by gusaiani** [comment]
CI e2e fails happening here and in a clean `release-x.39.x` branch when I run it. 
Couldn't ascertain if it's feasible to simply update the dep this time around.

May come back to this soon from `master` branch.

**Comment by ariya** [comment]
> CI e2e fails happening here and in a clean `release-x.39.x` branch when I run it.

Could be. Please check also the commit status at https://github.com/metabase/metabase/commits/release-x.39.x (might be useful to rebase/target the one that is green).

**Pull request closed without merging**
