### PR TITLE
clean up UX on SSO login

### LINKED ISSUE #10009: Sign In With Google screen is confusing to users without accounts
We use Sign in With Google to give everyone in our organization access to Metabase.  I keep getting requests from new employees asking for access, and have to explain that they already have access if they just click "Sign in with Google".

This screen would be a lot clearer if there was text indicating that the Sign in With Google button can be used to create an account.

Alternatively, if there was a setting in admin to change the "Sign in to Metabase" title or add a paragraph underneath it describing how to sign up that would help too.

image

### PR DESCRIPTION
**Pull request by kdoh**
resolves #10009 

Present folks with a clearer choice of SSO vs email / password when SSO is enabled. 

if SSO is set up the user gets two options
Screen Shot 2019-05-22 at 12 36 55 PM

if the user clicks "Sign in with Metabase" they're taken to our usual email / password form.
Screen Shot 2019-05-22 at 12 37 13 PM

(also adds tests to make sure the login form is behaving in either case)

I'm definitely open to feedback on the verbiage of "Sign in with Metabase." if people have feelings on that.

I'm hoping that this is enough to help folks out without having to add instructional text but we might also want to add a note that you can use your "@domain" email here. A back button from the email form also might be a good idea.

### CODE REVIEW

**Comment by mazameli** [comment]
I think we talked about this PR several days ago, but to summarize what I think I'd said — I think this is an improvement. I think I'd prefer `Sign in with email` over `Sign in with Metabase`; the latter sounds too much like `Sign in to Metabase` (i.e. the page's heading), and I'm unsure what it would mean if I clicked on that.

**Comment by camsaul** [comment]
@kdoh @mazameli is there anything else we need to do to get this merged?

**Comment by kdoh** [comment]
@camsaul Some reasonable tests were my blocker. I wasn't sure how to do those given our current framework. Maybe @paulrosenzweig has some ideas?

**Comment by paulrosenzweig** [comment]
@kdoh the tests you've added already make sense to me. What tests are still needed?

**Review by paulrosenzweig — APPROVED** [review]

**Pull request merged**
