### PR TITLE
WIP: render search filter results inline

### LINKED ISSUE #49992: Render multi-value search filter results inline in the filter popover instead of in a second popover.
**Is your feature request related to a problem? Please describe.**

We introduced the multi autocomplete component for filters in v51, but are getting some complaints that the double popover is distracting and hard to work with. We should render the results inline instead.

Image

**Describe the solution you'd like**
Render the results inline. The rest of the functionality should remain the same.

Image

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/49992

WIP

### Demo

https://github.com/user-attachments/assets/f4302c59-858e-4d8a-bc02-f0ca384130e6

### CODE REVIEW

**Review by ranquild — CHANGES_REQUESTED** [review]
I think there that there are too many fragile hacks for this to get merged. I suggest we revert `FieldValuesWidget` changes back to the point where it rendered options inline by itself.

**Comment by ranquild** [comment]
@romeovs search field values with remapping is broken. Compare with v50:
Screenshot 2024-12-10 at 10 00 20
Screenshot 2024-12-10 at 10 01 37

this PR:
Screenshot 2024-12-10 at 10 39 22

**Comment by ranquild** [comment]
@romeovs also when there are lot of values the UI becomes very slow. Try making `User.Email` as `list of values` and see how the component works in this case.

**Comment by romeovs** [comment]
Closing in favor of #51183

**Pull request closed without merging**
