### PR TITLE
Upgrade to Babel v7 [wip]

### PR DESCRIPTION
**Pull request by tlrobinson**
* [ ] upgrade jest / fix tests

### CODE REVIEW

**Comment by camsaul** [comment]
*  tlrobinson HAS NOT signed the CLA

**Comment by camsaul** [comment]
*  tlrobinson HAS NOT signed the CLA

**Comment by camsaul** [comment]
@paulrosenzweig do we still want this?

**Comment by paulrosenzweig** [comment]
I think this is old enough that we should start from scratch instead.

**Pull request closed without merging**
