### PR TITLE
Links in new tab/window

### LINKED ISSUE #12366: Regression with URL links
**Describe the bug**
Previously when URLs were rendered in results the default behaviour on clicking was to open in a new window / tab.

When we updated to the latest metabase version we find that URLs are visited in the same tab.

**Logs**
N/a

**To Reproduce**
Click a URL in query results

**Expected behavior**
To open in a new tab / window

**Screenshots**
N/a

**Information about your Metabase Installation:**
N/a

**Severity**
Minor

**Additional context**

Previously this line https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/ExternalLink.jsx#L15 used to be  `target="_blank"`, in this new change it looks like this is now delegated to PLUGIN_FORMATTING_HELPERS

The previous target value is not present in the PLUGIN_FORMATTING_HELPERS https://github.com/metabase/metabase/blob/master/frontend/src/metabase/plugins/index.js#L52-L56

I'd be happy to submit a PR if this is something that is welcome.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by howonlee**
Resolves #12366 

The issue frames it as a regression-qua-regression, but it seems to be more of a "we want the previous behavior it was good" more producty opinion. Nevertheless, here it is.

### CODE REVIEW

**Comment by salsakran** [comment]
do we have opinions on how this should work when embedded @kdoh @mazameli ?

I _think_ this change means that embedded/iframed links would open in a new tab, which I'm not sure is desirable.

**Comment by howonlee** [comment]
> do we have opinions on how this should work when embedded @kdoh @mazameli ?
> 
> I _think_ this change means that embedded/iframed links would open in a new tab, which I'm not sure is desirable.

previous behavior was that embedded/iframed links had the behavior that if they were in same domain, they would stay in the iframe, else they would go to a new page in same tab.

new behavior is such that, if embedded/iframed and same domain, stay in iframe, else a new page in new tab/window.

it actually does seem to be a producty question. one of the previous tickets in the trail of tickets leading to this one wanted a config option, which can also be done

**Comment by flamber** [comment]
The regression was even more involved than just embedding, since it also caused external links (like auth links during GA database setup on Admin > Databases, or in-app docs links) not to be opened in new tab - this fixes that too:
https://github.com/metabase/metabase/blob/2a0683bc3dcf1b3e11e41d073c84bac71b3ddce5/frontend/src/metabase/components/ExternalLink.jsx#L7

But perhaps it will have some unintended consequences for someone embedding that expects the current behavior, which has been around since for a year (0.35.0).
I know several EE have requested opening in new tab the past year.

**Comment by kdoh** [comment]
> new behavior is such that, if embedded/iframed and same domain, stay in iframe, else a new page in new tab/window.
I think this sounds like a sensible default to me.

**Review by paulrosenzweig — APPROVED** [review]
Looks good to me.

> But perhaps it will have some unintended consequences for someone embedding that expects the current behavior, which has been around since for a year (0.35.0).

That's a good point, @flamber. Given that you know people are asking for this change. It probably makes sense to make this change and add a setting if we hear from those suffering unintended consequences.

**Pull request merged**
