### PR TITLE
Prototype measure-text fn

### PR DESCRIPTION
**Pull request by adam-james-v**
Related: https://github.com/metabase/metabase/issues/24672

This is a prototype measure-text fn which takes a string and a map which gets converted into inline CSS on a span
element. This element is then rendered with a graphics context (the same one used for the final render of a static-viz
png), where the width and height can be found.

There's a REPL-ready fn that can be used to actually render the string, and can be viewed in a CIDER REPL that has
`(setq cider-repl-use-content-types t)` (inside emacs).

Here's a screenshot of my REPL:
image

## Next Steps
- fix `register-fonts!` to work properly with our newer fonts. They're .woff2 files in our resources folder, and they fail at the moment. I think the font registration should work, but will have to investigate this further
- determine the best way to allow the frontend to actually use this fn, and build that interface (is it an API endpoint?)
- get some eyes on the implementation to see if there are important things overlooked (eg. is this actually a good idea, to perform lots of small renders like this?)

### CODE REVIEW

**Comment by alxnddr** [comment]
Hey Adam, looks promising! 

> * determine the best way to allow the frontend to actually use this fn, and build that interface (is it an API endpoint?)

The current architecture of static viz: Clojure code invokes JS code which renders SVGs, then clojure code converts it to PNGs and composes email. Network communication is not involved. Can you please provide invokable function to the JS code so that it can measure text while rendering?

**Comment by alxnddr** [comment]
Also, I'm not sure about the JVM and BE in general if there are more lightweight solutions. I assume that rendering html and measuring the result might be more heavy-weight compared to rendering texts using graphic libs(?) if any. I just don't have enough expertise there but I would check for the most lightweight option. It is important, because while rendering, JS code can invoke this function like ~100 times or so

**Comment by adam-james-v** [comment]
> Hey Adam, looks promising!
> 
> > * determine the best way to allow the frontend to actually use this fn, and build that interface (is it an API endpoint?)
> 
> The current architecture of static viz: Clojure code invokes JS code which renders SVGs, then clojure code converts it to PNGs and composes email. Network communication is not involved. Can you please provide invokable function to the JS code so that it can measure text while rendering?

I think I can do that. I think that you mentioned somewhere (Notion or Slack, not sure...) that there is already some rough approximation for getting dimensions? If so, could you say where I can find that code? I think it might be a helpful starting point for me.

**Comment by alxnddr** [comment]
> I think I can do that. I think that you mentioned somewhere (Notion or Slack, not sure...) that there is already some rough approximation for getting dimensions? If so, could you say where I can find that code? I think it might be a helpful starting point for me.

@adam-james-v the existing rought approximation is simply terrible 😬 Check `measureText` function in `frontend/src/metabase/static-viz/lib/text.ts`. So we need to have a valid function that provides correct text dimensions that we can invoke in the GraalVM JS environment

**Pull request closed without merging**
