### PR TITLE
Allow JDBC additional-options in Redshift plugin

### PR DESCRIPTION
**Pull request by jmccarthy**
This PR introduces JDBC additional options to the Redshift plugin. Discussed in #9695

### Tests
-  [X] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [X] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

-  [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by camsaul** [comment]
I think the Amazon people deleted our old redshift JDBC dep so this will have to be rebased on master for tests to be green

**Comment by walterl** [comment]
Closing due to inactivity.

**Review by camsaul — APPROVED** [review]
This works for me if you rebase it on master.

**Comment by jmccarthy** [comment]
Thanks, will do this week!

**Comment by pawit-metabase** [comment]
This PR got quite stale now. I've took the commit, merged master into it and created a new PR at #18111.

**Pull request closed without merging**
