### PR TITLE
Presto test fixes

### PR DESCRIPTION
**Pull request by jeff303**
Point CircleCI presto test to the tagged older version (0.186)

### CODE REVIEW

**Comment by jeff303** [comment]
This should theoretically make the current Presto driver tests pass, even on the newer Presto server version

**Comment by jeff303** [comment]
The Docker image this is running against has manually be pushed to Docker hub (`latest` tag), built from metabase/presto-mb-ci#8

**Comment by dpsutton** [comment]
Can you explain what problem you are solving here? I see this pinned to a version but that makes me a bit antsy. Should we have two presto images, one with https and one http only? Or is this solely just different versions that matters?

**Comment by jeff303** [comment]
> Can you explain what problem you are solving here? I see this pinned to a version but that makes me a bit antsy. Should we have two presto images, one with https and one http only? Or is this solely just different versions that matters?

Sure, I will provide full details on what's going on.

On the newer Presto server version (0.254), the `INSERT` statements that the legacy Presto driver runs to populate test data, are failing.  These same statements are not failing on 0.186 (the old version).  All of this is being run through the Presto HTTP API (which is what the current driver uses).

We have to update the Presto server version, at least for the JDBC driver, because of bugs in the JDBC driver that only manifest against the older server version.

I already spent a couple days debugging nothing but this problem, which is only one tiny part of a much larger (and ballooning) set of tasks that are needed in order to get Presto JDBC, then Kerberized version of that, ready to go.  So this is about just getting things to work without burning even more time than has already been spent.  This can be justified as follows:

- Eventually, the "legacy" Presto driver (the one that uses the HTTP API) will be retired and only the JDBC version will remain, at which point we can simply get rid of the Docker image for the older Presto server version
- This problem is only occurring on data load (for the test data sets), which is not on the normal production code path that users exercise

Given all of these considerations, I feel this is the best way to deal with the problem.

**Review by dpsutton — APPROVED** [review]

**Comment by dpsutton** [comment]
Awesome. thanks jeff. Knowing that the old driver is going away makes this make a lot of sense.

**Pull request merged**
