### PR TITLE
Running CI for external contribution #35973

### PR DESCRIPTION
**Pull request by snoe**
Running CI for external contribution #35973

### CODE REVIEW

**Comment by kienstra** [comment]
Thanks for opening this, I'm fixing failed tests now.

**Comment by kienstra** [comment]
Hi @snoe,
Thanks a lot for opening this to run CI.

When you can, cherry-picking in https://github.com/metabase/metabase/pull/35973/commits/4c14a82af0aac64e307590053245094466a78502 and https://github.com/metabase/metabase/pull/35973/commits/d68bfa01ee7235d4623b2128b85306ed43846808 from https://github.com/metabase/metabase/pull/35973 will fix most of the failed tests.

I probably can't fix the [Athena tests](https://github.com/metabase/metabase/actions/runs/6963167183/job/18948279463?pr=36064). As Cam mentioned in https://github.com/metabase/metabase/issues/29573, that "…will have to be done manually from a REPL."

Thanks so much for running this, and have a great holiday.

**Comment by kienstra** [comment]
Sorry, just pushed https://github.com/metabase/metabase/pull/35973/commits/aedc632291ad4463d0af9d9d433fc8e0dde38ce1 to https://github.com/metabase/metabase/pull/35973 in order to fix the failed tests here. 

Thanks for your patience.

**Comment by kienstra** [comment]
Also pushed https://github.com/metabase/metabase/pull/35973/commits/14afbcf1de1ba09a8a5c07a84b7c7e7875f5afd0 to fix the Postgres tests.

**Comment by snoe** [comment]
@kienstra I've loaded the combined test-data to athena. If you can apply this patch to your branch you should be able to access it, and we get that test passing here.

```
--- a/modules/drivers/athena/test/metabase/test/data/athena.clj
+++ b/modules/drivers/athena/test/metabase/test/data/athena.clj
@@ -31,7 +31,10 @@
 ;; names.
 (defmethod ddl.i/format-name :athena
   [driver database-or-table-or-field-name]
-  ((get-method ddl.i/format-name :sql-jdbc) driver (str/replace database-or-table-or-field-name #"-" "_")))
+  (let [name' ((get-method ddl.i/format-name :sql-jdbc) driver (str/replace database-or-table-or-field-name #"-" "_"))]
+    (if (= name' "test_data")
+      "v2_test_data"
+      name')))
```

**Comment by kienstra** [comment]
Hi @snoe,
Just pushed https://github.com/metabase/metabase/pull/35973/commits/05753442fa3b6aaaac9e1f0ba81097438b5389f9 to https://github.com/metabase/metabase/pull/35973, with your [patch](https://github.com/metabase/metabase/pull/36064#issuecomment-1824837705).

Thanks a lot for loading the new `test-data` to athena.

**Comment by kienstra** [comment]
Hi @snoe,
Thanks for cherry-picking so many of my commits here.

Do you have any ideas for the [failed Athena test](https://github.com/metabase/metabase/actions/runs/6983326361/job/19004262397#step:3:454)? 

Thanks for all of your help here.

**Comment by kienstra** [comment]
Thanks a lot for looking at it. Interesting about the `venues` table.

**Comment by kienstra** [comment]
Hi Case,
Sorry to keep asking you to cherry-pick commits.

When you can, could you please cherry-pick the latest from https://github.com/metabase/metabase/pull/35973/?

**Comment by kienstra** [comment]
Thanks so much for your patience!

**Comment by snoe** [comment]
> Thanks so much for your patience!

No worries, we'll get there, appreciate you.

**Comment by kienstra** [comment]
Thanks so much! 

Looks like the `security/snyk` GitHub action is hanging.

The [failed driver tests](https://github.com/metabase/metabase/actions/runs/7093582583/job/19341388458?pr=36064) in this PR for are actually [from my fork's](https://github.com/kienstra/metabase/actions/runs/7093521700/job/19341000931?pr=14) https://github.com/kienstra/metabase/pull/14 commit https://github.com/kienstra/metabase/pull/14/commits/2a287c4f1de0d85e1d36a12f6afc02f3e59cb5ba.


Screenshot 2023-12-05 at 12 57 45 PM

Both of those GitHub actions have the same run ID: `7093582583`

https://github.com/metabase/metabase/actions/runs/7093582583/job/19341388458?pr=36064
https://github.com/kienstra/metabase/actions/runs/7093521700/job/19341000931?pr=14

…though there could still be more Athena errors that I'lll need to fix even when GitHub actions run on this PR 😄

**Comment by kienstra** [comment]
Maybe GitHub action didn't run here because there were merge conflicts.

In that case, I just pushed https://github.com/metabase/metabase/pull/35973/commits/8f9fbe7548399426451c3f61dee37cae23a40db7 to https://github.com/metabase/metabase/pull/35973.

**Comment by kienstra** [comment]
Thanks a lot for cherry-picking that.

Hm, [Athena failed again](https://github.com/metabase/metabase/actions/runs/7120808552/job/19388845720?pr=36064#step:3:698) with `No Table "venues" found for :athena Database `

**Comment by kienstra** [comment]
Do you think cherry-picking in https://github.com/metabase/metabase/pull/35973/commits/d4c8f129461f7f2f5a06d3706648909abc013391 from https://github.com/metabase/metabase/pull/35973 would help?

The [failed Athena test](https://github.com/metabase/metabase/actions/runs/7120808552/job/19388845720?pr=36064#step:3:440) mentioned that:

```sh
[CLI-agent-send-off-pool-2] FATAL metabase.test.data.athena - Athena database creation is disabled: not creating database "v2_test_data". 
Tests will likely fail.
See metabase.test.data.athena/*allow-database-creation* for more info.
```

Though you already created the database in Athena. So maybe it's not needed, and it could break something else.

**Comment by snoe** [comment]
> Do you think cherry-picking in [d4c8f12](https://github.com/metabase/metabase/commit/d4c8f129461f7f2f5a06d3706648909abc013391) from #35973 would help?
> 
> The [failed Athena test](https://github.com/metabase/metabase/actions/runs/7120808552/job/19388845720?pr=36064#step:3:440) mentioned that:
> 
> ```shell
> [CLI-agent-send-off-pool-2] FATAL metabase.test.data.athena - Athena database creation is disabled: not creating database "v2_test_data". 
> Tests will likely fail.
> See metabase.test.data.athena/*allow-database-creation* for more info.
> ```
> 
> Though you already created the database in Athena. So maybe it's not needed, and maybe it would break something else.

No, that only exists to create the db from the REPL. We explicitly don't want that to be possible from CI. 
This run shows that the aws secrets are present. When I run locally against these creds the test pass.

**Comment by kienstra** [comment]
Thanks, that makes sense that we shouldn't run it in CI.

**Comment by kienstra** [comment]
Maybe the latest commits from #35973 will help. Thanks for being so patient!

**Comment by kienstra** [comment]
Thanks a lot for cherry-picking those commits in. 

I didn't fix the Athena error, it looks like.

**Comment by kienstra** [comment]
Wow, thanks a lot for re-running CI/CD!

**Comment by snoe** [comment]
It turns out our internal Athena credentials were mixed up and the v2_test_data was, in fact, created somewhere CI couldn't see it. I'm sorry it took so long to track down. 

I prefer the recent change to keep `mt/dataset test-data` though, it helps keep the diff way down.

**Comment by kienstra** [comment]
Oh all good, thanks a lot for fixing the Athena tests.

>I prefer the recent change to keep mt/dataset test-data though, it helps keep the diff way down.

Definitely, it keeps the scope of this PR much smaller.

**Comment by snoe** [comment]
PR https://github.com/metabase/metabase/pull/35973 merged to master.

**Comment by kienstra** [comment]
Thanks for your enormous amount of patience, Case!

**Pull request closed without merging**
