### PR TITLE
Binning strategies frontend [WIP]

### PR DESCRIPTION
**Pull request by salsakran**
Frontend for #5331

Ideally, #5331 can be merged into master without breaking anything, and this can be tacked on independently. 

TODO:

* [x] QB support (show strategies in breakout picker)
* [x] Formatting ranges
  * [ ] Is it ok the formatting doesn't indicate the min is inclusive and max is exclusive?
* [x] Drill through support
* [x] Bug: ranges starting with 0 are blank
* [x] Bug: axis are off
  * should we just use ordinal axis and fill missing bins?

### CODE REVIEW

**Comment by senior** [comment]
Below is a description of backend/UI interaction for binning.

The *query_metadata* response now contains 2 new attributes, a top-level *dimension_options* which is a map, that has all of the possible dimensions for all of the fields.
```
{
  "0" : {
    "name" : "Minute",
    "mbql" : [ "datetime-field", null, "minute" ]
  },
  "1" : {
    "name" : "Minute of Hour",
    "mbql" : [ "datetime-field", null, "minute-of-hour" ]
  },
...
"15" : {
    "name" : "Quantized by the default binning strategy for the field",
    "mbql" : [ "binning-strategy", null, "default" ]
  },
  "16" : {
    "name" : "Quantized by the 10 equally sized bins",
    "mbql" : [ "binning-strategy", null, "num-bins", 10 ]
  }
}
```
The above *mbql* is a query clause where the `null` can be replaced by a field. Each field now has a *dimension_options* key that has zero or more references to keys in that top-level *dimension_options* map. These indexes are in numerical order:
```
{ ... field data ...
  "dimension_options": ["15", "16", "17", "18"]
}
```
This cuts down on the size of the message as the dimension strategies only appear once.

When a query is issued with a binning strategy, the column metadata now includes *"binning_info"* in the *"cols"* key of the response.
```
{
... column metadata ...
  "min_value" : 10.0646,
  "max_value" : 40.7794,
  "binning_info" : {
    "binning_strategy" : "num-bins",
    "bin_width" : 10.2383,
    "num_bins" : 3,
    "min_value" : 10.0646,
    "max_value" : 40.7794
  }
}
```
The *min_value* and *max_value* in the column is the global min/max value that the database sync code found. *binning_info* also contains a min and max value that is the min/max used for this binning strategy. Including query criteria that constrains the min/max values, such as drilling into a bin will cause the min/max in *binning_info* to be different from the global min/max. The user (or the drill into process) can use >, >=, <, <= with normal query filters to change that min/max. If multiple are specified (maybe an MB supplied one for drilling and the user specified one), the greatest min value and the smallest max value is chosen. The *bin_width* and *num_bins* attributes can be use to determine how many bins to show.

**Comment by tlrobinson** [comment]
Known issues:

* bins beginning at 0 aren't formatted in tooltips correctly:
screenshot 2017-06-16 23 33 48

* axis ticks don't align with actual bars. Should we use ordinal axis and fill missing bins?
screenshot 2017-06-16 23 33 59

**Comment by tlrobinson** [comment]
Merged with #5331

**Comment by sbelak** [comment]
Tick layout I like is where the ticks are left align and the bars touch (so the middle ticks play double duty as ends/strats) and we definitely should fill missing bars, else you can't distinguish
```
*
*           *
* _ _ _ _ _ * *
```
and
```
*
* *
* * * 
```
even though they are completely different distributions.

**Comment by salsakran** [comment]
@sbelak I'm still getting non-rounded bins
screen shot 2017-07-19 at 4 49 38 pm

**Pull request merged**
