### PR TITLE
Simplify Slack setup

### LINKED ISSUE #20050: Simplify the Slack setup
Add the manifest to step 1 URL, which simplifies step 2 by a lot:
https://api.slack.com/reference/manifests#sharing_manifests

```
https://api.slack.com/apps?new_app=1&manifest_yaml=_metadata%3A%0A%20%20major_version%3A%201%0A%20%20minor_version%3A%201%0Adisplay_information%3A%0A%20%20name%3A%20Metabase%0A%20%20description%3A%20Bringing%20the%20power%20of%20Metabase%20to%20your%20Slack%20%23channels%21%0A%20%20background_color%3A%20%22%23509EE3%22%0Afeatures%3A%0A%20%20bot_user%3A%0A%20%20%20%20display_name%3A%20Metabase%0Aoauth_config%3A%0A%20%20scopes%3A%0A%20%20%20%20bot%3A%0A%20%20%20%20%20%20-%20users%3Aread%0A%20%20%20%20%20%20-%20channels%3Aread%0A%20%20%20%20%20%20-%20channels%3Ajoin%0A%20%20%20%20%20%20-%20files%3Awrite%0A%20%20%20%20%20%20-%20chat%3Awrite%0A%20%20%20%20%20%20-%20chat%3Awrite.customize%0A%20%20%20%20%20%20-%20chat%3Awrite.public%0A
```

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/20050

Removes the manifest step and inlines the manifest into the URL.

How to test:
- Go to Admin > Slack
- Make sure it is possible to setup a Slack app using the steps on this page.

### CODE REVIEW

**Comment by gusaiani** [comment]
@ranquild,

I'm unclear on how do test this one, here's a Loom with my questions.

https://www.loom.com/share/a67a6c1bf45047fd8a08f14b8a67e5d1

**Comment by ranquild** [comment]
> @ranquild,
> 
> I'm unclear on how to test this one, here's a Loom with my questions.
> 
> https://www.loom.com/share/a67a6c1bf45047fd8a08f14b8a67e5d1

@gusaiani Thanks for the video! Indeed, there was a bug with the manifest in the URL, it should be working now.

**Review by gusaiani — APPROVED** [review]
Very nice improvement 👍

**Comment by ranquild** [comment]
@metabase-bot backport release-x.42.x

**Pull request merged**
