### PR TITLE
Personal Collections [WIP]

### PR DESCRIPTION
**Pull request by camsaul**
WIP PR

###### Backend:
- [x] Need some more tests, as always (!)
   - [x] tests to make sure slugs aren't unique any more
   - [x] tests making sure you can only see your own personal collection
   - [x] Even though the Collections permissions graph doesn't return personal collections, we should add tests to make sure it throws Exceptions if you try to change perms for personal collections
   - [x] tests to make sure you're not allowed to archive, move, etc. personal collections
- [x] What should we name the Collections? (right now, based on username; if two people have same name, this will be *broken* since Collections currently cannot have the same name)
- [x] add a flag to mark the personal collection of a user (or perhaps have it be a separate key? @tlrobinson any opinions?)
- [x] Place personal collections under a collection for admin view 
- [x] Remove  `GET /api/card?collection=slug` endpoint optional param

###### Frontend:
- [ ] UI for Personal Collections as appropriate
- [ ] Tests for new UI

### CODE REVIEW

**Comment by mazameli** [comment]
Trying to edit a pulse to put it my personal collection results in a save error for the pulse.

JS console:
```
Failed to load resource: the server responded with a status of 400 (Bad Request)
app-main.hot.bundle.js:31717 Objectdata: {errors: {…}}isCancelled: falsestatus: 400__proto__: Object
(anonymous) @ app-main.hot.bundle.js:31717
```

Server logs:
```
06-07 17:41:12 DEBUG metabase.middleware :: PUT /api/pulse/1 400 (3 ms) (0 DB calls).
{:errors {:cards "value may be nil, or if non-nil, value must be an array. Each value must be a map with the keys `id`, `include_csv`, and `include_xls`. The array cannot be empty."}}
```

**Comment by kdoh** [comment]
@mazameli Sounds like #7789. I don't think that's specific to this branch.

**Comment by mazameli** [comment]
It would be rad if in the UI a user always saw their own personal collection labeled as "My personal collection" instead of e.g. "Maz Ameli's personal collection."

**Comment by kdoh** [comment]
Yeah agreed. @camsaul / @tlrobinson should that be done on the front end or the back end?

**Comment by mazameli** [comment]
We're going to want to hide personal collections from the permissions grid:

screen shot 2018-06-07 at 5 47 29 pm

**Comment by mazameli** [comment]
Looks like I'm unable to save a pulse in my personal collection:

Here's the pulse I tried to save:

screen shot 2018-06-08 at 10 39 22 am

And here's where it actually ended up when I saved it:

screen shot 2018-06-08 at 10 39 46 am

**Comment by mazameli** [comment]
From my admin account, I'm oddly seeing the personal collection for the first non-admin user I created in addition to my own personal collection. (Expected behavior is mocked up in https://github.com/metabase/metabase/issues/7816)

screen shot 2018-06-08 at 10 55 03 am


people

**Comment by camsaul** [comment]
@mazameli the special "Other People's Personal Collections" folder for admins isn't implemented yet

**Comment by mazameli** [comment]
@camsaul For sure. Also, I commented just now in the doc, but just to over-communicate I'll mention that [Sameer made a good point ](https://www.google.com/url?q=https://github.com/metabase/metabase/issues/7816%23issuecomment-395211259&sa=D&ust=1528484846429000&usg=AFQjCNEghSwGgzjmpeGxh4ou6t0OCll_yA) that the "Everyone else's personal collections" item doesn't necessarily need to be implemented as a specialized collection; it can just be a link to a page with a list of each user, which takes you to their personal collection when clicked, [like this](https://github.com/metabase/metabase/issues/7816#issuecomment-395214412).

**Pull request merged**
