### PR TITLE
Cypress E2E postgres snapshot

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
As a part of an ongoing effort, documented in https://github.com/metabase/metabase/issues/18118, this PR is taking a first real step towards the unification of `metabase-db` e2e tests and the rest of e2e tests.

More precisely:
- Creates a Postgres snapshot that we can use in ANY test by writing `restore('postgres-12')`
    - this snapshot includes H2 Sample Dataset as the first database, and also includes connection to the Postgres database, as the second one
- Uses that snapshot in tests
- Moves all tests and repros from the `metabase-db/postgres` directory to their logical places within the `scenarios` folder
- Tweaks the config and the cypress runner, because postgres is no longer a part of them
- Reduces the number of the total E2E CI groups by two (`e2e-postgres-12-oss`, and `e2e-postgres-12-ee`)

### Note:
When you run these tests locally, be sure to have Postgres [QA DB Docker image](https://github.com/metabase/metabase-qa) running.

```bash
docker run --rm -p 5432:5432 --name meta-postgres12-sample metabase/qa-databases:postgres-sample-12
```

### CODE REVIEW

**Review by ariya — APPROVED** [review]
Ship it :rocket:

**Review by flamber — APPROVED** [review]
Looks great - hopefully this will make it easier for you to make DB-specific tests, or even do matrix tests across multiple DBs (that will likely be a lot harder because of ID and casing differences).

**Comment by nemanjaglumac** [comment]
@metabase-bot backport release-x.41.x

**Comment by nemanjaglumac** [comment]
> Looks great - hopefully this will make it easier for you to make DB-specific tests, or even do matrix tests across multiple DBs (that will likely be a lot harder because of ID and casing differences).

@flamber 
It'll be much much easier to do a matrix-style testing with this. For UI 100%. API will require some tweaking and some helper functions.

**Pull request merged**
