### PR TITLE
Allow . separator in expression identifiers

### LINKED ISSUE #12076: Ability to refer to fk-linked columns using a dot instead of an arrow
In notebook expressions, I should be able to refer to linked columns like this: `Product.Category` instead of having to type `Product → Category`

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #12076

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]
LGTM. The only thing I can think of is that the regex is a bit permissive (e.g. `...` is an identifier). I don't see what issues that would cause though.

**Review by mazameli — CHANGES_REQUESTED** [review]
This only appears to work for showing me autocomplete suggestions. If I manually type out e.g. `Product.Category` I get errors.

Screen Shot 2020-03-17 at 12 24 20 PM

Screen Shot 2020-03-17 at 12 25 11 PM

Screen Shot 2020-03-17 at 12 25 51 PM

**Comment by tlrobinson** [comment]
@mazameli I've fixed that and made this configurable like I did for quotes, at the top of config.js, feel free to tweak:

```js
export const EDITOR_FK_SYMBOLS = {
  symbols: [".", " → "],
  default: " → ",
};
```

`symbols` are the ones that are allowed, `default` is the canonical one.

**Comment by tlrobinson** [comment]
e.x.

Screenshot 2020-03-17 16 27 13
Screenshot 2020-03-17 16 27 43

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
WFM 👍

**Pull request merged**
