### PR TITLE
Fix calculation in `ttl-hierarchy`

### LINKED ISSUE #18458: Caching on 0.41.0 caches results for very long time (does not respect settings defined)
**Describe the bug**
Caching on 0.41.0 caches results for very long time (does not respect settings defined)

Currently the only workaround is to disable caching.

**To Reproduce**
1. Admin > Settings > Caching > Duration=`4`, Multiplier=`2`
2. Native query > `select current_timestamp, pg_sleep(5)` - run query, save as "Q1" and add to dashboard
3. On dashboard, refresh a couple of times (issue #13262), until the card loads instantly
4. Now wait 10 seconds and refresh the dashboard, where new results are expected. But the cache is still displayed.
5. Looking at the `POST /api/card/123/query`, it contains a `cache_ttl: 36000` (10 hours).

**Information about your Metabase Installation:**
Tested 0.41.0 and master with EE features.

### PR DESCRIPTION
**Pull request by jeff303**
The `ttl-hierarchy` function falls back to `query-magic-ttl` if no stored (card, dashboard, database) cache settings are available.  But that function returns its TTL value in milliseconds, while the model level, granular TTLs are stored in hours.  Convert those to seconds before returning, so that `ttl-hierarchy` is always returning in seconds

Add backend test for this scenario (no stored model ttls, but an average query execution time is available, and hence the `query-magic-ttl` should be used)

Unskip Cypress repro

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
My quick scramble through OSS and EE, this seems to have fixed the problem with the few tests that I did :trophy: 

I'm expecting questions that explicitly define to 1 hour to be cached for this duration, but it seems like the execution time still has to be above "Minimum Query Duration" defined in Admin > Settings > Caching.
Perhaps that was a design choice, I don't know. Just feels odd.

**Review by camsaul — APPROVED** [review]

**Comment by camsaul** [comment]
it would still be good to get a 👍 from @flamber as well

**Review by dpsutton — APPROVED** [review]
Looks good. Took me much longer to approve because there's almost no information what the unit of the cache_ttl is. Took a while to track down that it is actually hours. The comments in the db schema say seconds so this should be documented somewhere. Not a responsibility of this PR but would be nice for some future work. It is quite ambiguous.

**Comment by flamber** [comment]
We have always been using `cache_ttl` with seconds. While it was never exposed, it was very much used by some of our advanced users. #4664 #5144 #13396

If we have suddenly decided it should be hours in 0.41, then fair enough, but currently several people internally have been confused. I'm sure this will lead to more problems in the future.

Anyways, it seems to have nothing to do with this PR, but the implementation. I have no idea if we should open an issue it, since unless we fix it right now, then it will never be fixed.

**Pull request merged**
