### PR TITLE
Use hyperUnique aggregator for Druid distinct queries

### LINKED ISSUE #5223: Druid HyperUnique aggregator in View dropdown
### Feature requests and proposals

Hi guys!

I am trying to generate a query that involves a Druid HyperUnique aggregator. Currently I am able to do so via native query.

It would be great if this was available in the View dropdown. Currently "Number of distinct values of..." returns 1 for yyperUnique type columns.

Did you already have a look at this feature? If not, could you point me in the right direction so I can try to implement it?

Thank you.

### PR DESCRIPTION
**Pull request by psalaberria002**
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
- [x] Add :type/DruidHyperUnique
- [x] Use hyperUnique aggregator for :type/DruidHyperUnique fields
- [x] Get DruidHyperUnique type from Druid when syncing.

This PR fixes #5223 

This is a first draft of a working example. I don't know the codebase well enough, so please let me know if there is a better way to implement this.

### CODE REVIEW

**Comment by moumny** [comment]
Awesome ! I tried it and it works.
Would be great though if the hyperunique value only show up in the "distinct number of ..." because sum of  create an error and is confusing for users.

**Comment by psalaberria002** [comment]
That would be a nice feature indeed. Show :type/DruidHyperUnique fields only in "distinct number of ...".

Is there any existing functionality in Metabase for handling that?

**Comment by psalaberria002** [comment]
Any update on this issue?

**Comment by Digma** [comment]
That PR would be very helpful for us. Any decisions regarding some next step or blockers to merge it?

**Comment by camsaul** [comment]
I think I missed this PR when it was first opened. I'll take a look at it today and see if we can merge it into our upcoming release

**Comment by jonatasfreitasv** [comment]
When i find this option?

I search in View menu and in Native Query, but not find DruidHyperUnique feature.

v 0.28.1

**Pull request merged**
