### PR TITLE
Collections backend 📇 

### PR DESCRIPTION
**Pull request by camsaul**
Backend for Collections.

Updated API dox are available [here](https://github.com/metabase/metabase/blob/collections-backend-wip/docs/api-documentation.md); new endpoints include various `/api/collection/` endpoints and new `?f=no-collection` and `?collection=<slug>` filter options for `GET /api/card`.

### CODE REVIEW

**Comment by tlrobinson** [comment]
First things I've noticed:

We need to be able to filter by both "no-collection" and the existing filters like "fav" at the same time, i.e. favorited questions that are not in a collection. We could either make the `collection` parameter take a special `no-collection` value, or maybe empty string.

Also, if it's not too difficult it would be nice if we could do server-side search / filtering of the card name. It would be slightly easier on the frontend, and a bit more bandwidth efficient for large instances, since we'll no longer load every card up front as we previously did.

A `?q=SEARCH_TERMS` parameter that does a case-insensitive substring match of the card name would match the existing client-side search behavior.

**Comment by tlrobinson** [comment]
Also getting `"Attempted to return a boolean as an API response. This is not allowed!"` on `PUT /api/collection/ID` body `{color: "#72AFE5", name: "foo"}`

**Comment by camsaul** [comment]
@tlrobinson let me see what I can do

**Comment by tlrobinson** [comment]
For the first one this was my workaround:

```diff
diff --git a/src/metabase/api/card.clj b/src/metabase/api/card.clj
index 016554f..068697a 100644
--- a/src/metabase/api/card.clj
+++ b/src/metabase/api/card.clj
@@ -140,7 +140,7 @@
                   hydrate-favorites)]
     ;; Since labels and collections are hydrated in Clojure-land we need to wait until this point to apply label/collection filtering if applicable
     (filter (cond
-              (seq collection) (let [collection-id (check-404 (db/select-one-id Collection :slug collection))]
+              (seq collection) (let [collection-id (if (= collection "") nil (check-404 (db/select-one-id Collection :slug collection)))]
                                  (comp (partial = collection-id) :collection_id))
               (seq label)      (partial card-has-label? label)
               :else            identity)
@@ -166,7 +166,7 @@
    *  LABEL and COLLECTION params are mutually exclusive; if both are specified, LABEL will be ignored and Cards will only be filtered by their `Collection`.
    *  If no `Collection` exists with the slug COLLECTION, this endpoint will return a 404."
   [f model_id label collection]
-  {f (s/maybe CardFilterOption), model_id (s/maybe su/IntGreaterThanZero), label (s/maybe su/NonBlankString), collection (s/maybe su/NonBlankString)}
+  {f (s/maybe CardFilterOption), model_id (s/maybe su/IntGreaterThanZero), label (s/maybe su/NonBlankString), collection (s/maybe s/Str)}
   (let [f (keyword f)]
     (when (contains? #{:database :table} f)
       (checkp (integer? model_id) "id" (format "id is required parameter when filter mode is '%s'" (name f)))
```

**Comment by camsaul** [comment]
@tlrobinson Did you get that workaround working? It doesn't look like it would because `(seq "")` returns `nil`, which is falsy, so you wouldn't be able to trigger the no collection filter with an empty string.

**Comment by camsaul** [comment]
Either way that basic approach works for me so I'll build on it

**Comment by tlrobinson** [comment]
Oh, I thought it was but maybe not.

**Comment by camsaul** [comment]
ok @tlrobinson I made the change to `GET /api/card` so you can filter by no collection by using an empty string. Has tests and everything so that's g2g

Same for the fix for `PUT /api/collection/:id`.

RE adding a query string param for `GET /api/card`: I think just continuing to do the filtering on the frontend for card names for now is fine. It's probably a little faster anyway because you don't need to wait for a network round-trip to reload results every time the search term changes, which can get kind of laggy (assuming the search results are supposed to update instantly). 

We could certainly change it in the future but to do it right I'll want to rewrite the functions that handle various filter options to generate partial queries (rather than the entire query) so the name filter clause can be merged in. It's not a super-trivial change so I'll tackle it some point in the future outside of this PR.

**Comment by camsaul** [comment]
Closing in favor of #3920

**Pull request closed without merging**
