### PR TITLE
GET /api/database/form_input shouldn't require auth

### LINKED ISSUE #1421: List of available databases is empty in setup process
When I try to select a database type to add in the setup process I get an empty list.

screen shot 2015-11-01 at 10 26 44 pm

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #1421.

### CODE REVIEW

**Comment by tlrobinson** [comment]
This doesn't resolve #1421 yet, needs more frontend work. I'll do it.

**Comment by tlrobinson** [comment]
Ok should be good now.

**Comment by agilliland** [comment]
After looking at this again I think we are actually better off just putting `:engines   @driver/available-drivers` inside the `public-settings` in the metabase.models.settings namespace and avoiding the need to have a `database/form_input` endpoint at all.

The data for the engines is non-sensitive and static anyways, so this just puts it somewhere that's easier to access and doesn't require another api call.  To get it on the frontend you'd just import the `MetabaseSettings` module and call `get('engines')`

**Comment by agilliland** [comment]
@tlrobinson @camsaul I tweaked this based on my last comment.  I think this is a simpler approach than having an endpoint for /api/databases/form_input .  Let me know if you have any final thoughts before I merge.

**Pull request merged**
