### PR TITLE
Sparkline nits in static viz email

### LINKED ISSUE #18678: Tune static viz email template
[Product doc](https://www.notion.so/metabase/Email-template-visual-improvements-2fc546d30fee409f895f4884947bd868)

- [ ] Decrease the space between titles and descriptions
- [ ] Decrease the text size of scalar timeseries callouts
- [ ] Decrease the spacing between scalar callouts and their labels
- [ ] Decrease the font size of scalar callout labels
- [ ] Make sure to scale the legend accordingly

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to the nits from #18676 - I can't find the legend scaling problem in the product docs or anywhere, though, this may be a problem

### CODE REVIEW

**Comment by alxnddr** [comment]
@howonlee could you please describe what the changes are exactly? Having screenshots would be useful

**Comment by howonlee** [comment]
> @howonlee could you please describe what the changes are exactly? Having screenshots would be useful.
> 
> Is it #18678 ?

Yes, it's supposed to be the contents of 18678. Screenshots forthcoming in a bit

**Comment by howonlee** [comment]
Attached are the two screenshots, old and new respectively. Don't mind the broken waterfall, fix for that's up in another PR (#19563)

old-email
new-email

So:
- Title description space decreased
- Scalar timeseries callout size decreased
- Spacing for said callout decreased
- Font size of said callout decreased

**Review by alxnddr — APPROVED** [review]
Looks good!
https://github.com/metabase/metabase/issues/18678 also contains a point about scaling legends, can you please fix it too?
Screenshot 2022-01-07 at 23 40 12

**Comment by howonlee** [comment]
Pursuant to the nits from #18678 and #18676

**Pull request merged**
