### PR TITLE
permissions fixes

### PR DESCRIPTION
**Pull request by alxnddr**
## Description

Set of Permissions fixes from the latest bug bash and from Bruno:

**Disable native query permission when a data access permission is `Block`**
Screen Shot 2021-09-04 at 01 12 18

**Sort databases/schemas/tables in the sidebar**
Screen Shot 2021-09-04 at 01 11 54

**When database permission is `Block` it is still possible to change schema/table permission with a warning about changing the database level permission to Granular**
Screen Shot 2021-09-04 at 01 11 22

**Block permission is available only in EE**
No screenshot is needed here 

**Tooltips are aligned with icons**
Screen Shot 2021-09-04 at 01 10 12

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Comment by brunobergher** [comment]
UX/UI-wise this looks great.
I wonder if #17763 should be bundled with this PR though.

**Comment by nemanjaglumac** [comment]
@alxnddr  Please rebase on `master` to get the latest changes and the related repros.

Will it be too much of a hassle to break this down into a different PRs for every individual fix? It'd be much easier to review and track later on.



> UX/UI-wise this looks great.

Clicking on the "granular" still defaults to "Block" permissions on a tabular level, which is wrong. It should be "No self-service".
dasdas

**Comment by alxnddr** [comment]
> Clicking on the "granular" still defaults to "Block" permissions on a tabular level, which is wrong. It should be "No self-service". 

I'm not sure if it should be "No self-service" on tables when users click granular on a database. After clicking they have the ability to specify a custom level for any table they want but previously they did not (#17763)

**Comment by brunobergher** [comment]
I see your point, maybe we're talking about the same thing in subtly different ways. It depends on what the Admin is switching away _from_.

So:
- If the DB is set to `Block`
- Then the Admin picks `Granular`
- The app will drill down to the table view
- And the default there should indeed be `No self-service`, since it’s the most conservative, in case someone changes away from block by mistake.

This does make it that, out-of-sight, the app switches the DB to `No self-service`, but the expectation is that the Admin will then change specific tables to `Unrestricted`, thus making it `Granular`, out-of-sight, at the DB level.

But:
- If the DB is set to `Block`
- Then the Admin picks `Unrestricted`
- The tables in that DB should also go to `Unrestricted`, and the app won't drill down into the table view automatically

Does this compute for you?

**Comment by alxnddr** [comment]
@brunobergher 
> * And the default there should indeed be `No self-service`, since it’s the most conservative, in case someone changes away from block by mistake.
I totally agree with the rest but I was not sure about this specific case: if someone changed the DB permission from `block` by mistake we have already changed the DB level. But if we keep table level (and database) permissions `Block` instead of `No self-service` it is not a problem. And it won't be different to change table permission from `Block` to `Unrestricted`, so that's why I wondered if we really want to change table permissions to `No self-service` in this case

**Comment by brunobergher** [comment]
> But if we keep table level (and database) permissions Block instead of No self-service it is not a problem

But there's no such thing as "table-level block permission", right?

**Review by daltojohnso — APPROVED** [review]
Code looks good 👍 I'll go ahead and approve this in case the discussion you're having results in no other action

**Comment by alxnddr** [comment]
> > But if we keep table level (and database) permissions Block instead of No self-service it is not a problem
> 
> But there's no such thing as "table-level block permission", right?

We do show `Block` on table level and I was thinking to make it not disabled so that users can switch from `Block` on the table/schema level to any other permission but not back
Screen Shot 2021-09-13 at 10 45 57

Maybe it would not be that clear for users why they can't switch back, so I'll change it to `No self-service` as you and Nemanja proposed

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Pull request merged**
