### PR TITLE
Faster mac app launch time :racing_car:

### PR DESCRIPTION
**Pull request by camsaul**
Skip Java's bytecode verification when launching the Mac App because the JAR is already known to be good and the app is signed preventing shady kittens from modifying the JAR. Shaves off a second or so of launch time.

### CODE REVIEW

**Comment by salsakran** [comment]
you have any sense of how many seconds are shaved?

**Comment by camsaul** [comment]
@salsakran a second at best. But I think every little bit helps in this case

**Comment by camsaul** [comment]
I added a new command called `lein profile` that profiles the time it takes to launch Metabase.
After extensive profiling I can confirm that adding this options shaves about an average of 1 second from the Metabase launch time. That's a performance improvement I think we can all enjoy 😍  👍

**Comment by salsakran** [comment]
Can I modify the jar within the app without violating the overall app signature?

**Comment by camsaul** [comment]
I think it only checks the signature the first time you launch the app so if you launch first you should be allowed to do it.

**Comment by salsakran** [comment]
ugh.

**Comment by salsakran** [comment]
though I guess not any more ugh than just replacing the app with an unverified jar since we're not checking that the jar is signed/verified anyway.

**Comment by camsaul** [comment]
All the JVM `Xverify` does is make sure the bytecode inside is valid. i.e. the JAR file isn't corrupted. 

Either way right now someone can replace the Metabase JAR inside the app with their own JAR. They wouldn't be able to pass that modified `Metabase.app` onto other people though because the codesigning would fail.

**Pull request merged**
