### PR TITLE
Change BigQuery driver to accept documented dataset name

### LINKED ISSUE #9388: Error when running query with BigQuery dataset whose name starts with a number
We are using Metabase to connect to multiple BigQuery datasets. The names of the datasets are auto-generated by a service. We are able to connect to all of our datasets and view the tables/views in each dataset. However we have just discovered that when we ask a Question against a dataset with a long name (32 characters) that the operation fails with the following error message:

Assert failed: (valid-bigquery-identifier? %)

With some engineering effort we can re-create the offending datasets with shorter names, but we are concerned that this problem may re-occur, especially given the way metabase constructs the sql (every column in the sql statement selected is qualified by dataset and table name).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by masu-mi**
## Overview
This changes are aimed to close #9388 .

According to the specification, BigQuery's dataset and table are acceptable,
if their name are satisfying following conditions.

* Include only `a-z`, `A-Z`, underscore(`_`) or numbers(`0-9`).
* Contain up to 1024 chars.

Ref.

* https://cloud.google.com/bigquery/docs/datasets?hl=en
* https://cloud.google.com/bigquery/docs/tables?hl=en

[ci all]

### CODE REVIEW

**Comment by flamber** [comment]
Guessing that it would also fix #9204. I have a feeling that it might cause problems with the length of some of the metadata columns, which are [limited to 254](https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml#L348) characters.

**Comment by masu-mi** [comment]
Ah. I'll make this PR's scope smaller, add commit to keep identifier's max length on 128.

**Review by camsaul — APPROVED** [review]
This makes sense to me. I'll have to push this branch again to trigger CI

**Comment by camsaul** [comment]
BigQuery and some of the other tests don't normally run for PRs from people outside the core team so we have to trigger them manually.

Running this branch in CI here:

https://app.circleci.com/pipelines/github/metabase/metabase?branch=masu-mi-fix-9388

**Review by camsaul — CHANGES_REQUESTED** [review]
Looks like there are test failures in the new tests

https://app.circleci.com/pipelines/github/metabase/metabase/11275/workflows/3e605825-63c2-4334-bff5-ccb8b2e7e0a7/jobs/408597/tests

**Comment by masu-mi** [comment]
@camsaul Thank you for your comments. I've fixed test code and check this change work well with following cmd.
My apologies for pushing borken tests.

```sh
$ DRIVERS=h2,bigquery lein with-profile +ci,+junit test \
    :only metabase.driver.bigquery.query-processor-test/acceptable-dataset-test
```

**Comment by flamber** [comment]
Thank you for the PR @masu-mi. Sorry for the delayed review.
This was incorporated into #16746 which will be part of 0.41.0

**Pull request closed without merging**
