### PR TITLE
Docs fixes and clarification of versions and Field Filters

### PR DESCRIPTION
**Pull request by flamber**
Okay, it's probably not a minor docs change anymore - sorry :crying_cat_face:
And I should probably have run the `prettier` as a separate commit, so it was easier to see changes

- some broken links
- ~~no images on audit doc~~ (fixed by #11229 in the meantime)
- minimum MySQL version to 5.5.3 (from 4.1) [ref](https://mariadb.com/kb/en/library/about-mariadb-connector-j/#server-compatibility)
- note about minimum recommended version of MySQL/MariaDB and `utf8mb4` (https://github.com/metabase/metabase/issues/10691#issuecomment-560870392)
- only Java 8 and 11 (not sure if this should be extended a bit, see https://github.com/metabase/metabase/pull/10194#issuecomment-504515326)
- Field Filter note about comment syntax not always `#` on Complex Default Value (common problem on the forum)
- Field Filter note about some databases requires schema in the FROM-clause like `FROM "schema"."table"` and for BigQuery it needs enclosed in backticks like ``FROM `dataset_name.table` `` (common on the forum and #6611 #6409 #6310 #8404 - not sure if a documentation clarification counts as a fix for the open issues?)
- link to `../troubleshooting-guide/timezones.md` in bottom of `/docs/operations-guide/handling-timezones.md`
- ~~`/docs/faq.md` replaced with "This page has been moved [here]" (fixes partially #11413)~~ Skipped for another PR, as per Maz [comment](https://github.com/metabase/metabase/pull/11117#discussion_r353435162)
- and the edited docs got `prettier` too
- try one more time (#8191 #9168 #10613) to fix [Server-side Analytics](https://www.metabase.com/docs/latest/information-collection.html#server-side-analytics) table by running it through `prettier`

### CODE REVIEW

**Comment by flamber** [comment]
Hi @mazameli 
I know this has turned into a CF, but it's really not as bad as all the horrible merges makes it look like. But sorry for the `prettier`, which makes my changes less visible.
If you want, I can redo everything better in a new PR?

**Comment by mazameli** [comment]
@flamber Nah, that's on us for not reviewing this sooner. Let me take a look at the diff today.

**Review by mazameli — CHANGES_REQUESTED** [review]
This is great stuff. Just a few copy suggestions, and a request to leave the old FAQ page in until we can extract some content out of it and then kill it in a separate PR.

**Comment by flamber** [comment]
@mazameli Can this be merged, so I don't have to continue fixing conflicts? :wink:

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
Sorry! 🤦‍♂

**Pull request merged**
