### PR TITLE
Fix and reproduce #20499: The term "SQL query" used in DBs that don't support SQL

### LINKED ISSUE #20499: "SQL Query" in UI for MongoDB/Druid/GA native queries
There's a reason the old UI used "Native query" and not "SQL query".

image

We don't support SQL for MongoDB (etc.) and not every native query is a SQL query.

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Fixes #20499 
- Reproduces #20499 
- Updates all tests that were using the term "SQL query"

### How to test?
_Make sure you have Mongo DB connected (or GA, or Druid)_
1. Visit a home page
2. Click on the "New"
3. Popover should display "Native query" instead of "SQL query"

_For the sample database and every other DB that supports SQL_
1. Visit a home page
2. Click on the "New"
3. Popover should display "SQL query"

### CODE REVIEW

**Review by camsaul — APPROVED** [review]

**Review by mazameli — CHANGES_REQUESTED** [review]
See discussion here: https://github.com/metabase/metabase/issues/20499#issuecomment-1048065512

**Review by diogormendes — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
@mazameli when you find some time, please check this again. @daltojohnso was so kind to jump in and help.

If someone has at lease one DB that doesn't support SQL connected, they will see "Native query". Otherwise, it will show "SQL query" (which is the default for everyone else).

**Comment by mazameli** [comment]
@nemanjaglumac will do!

**Review by mazameli — APPROVED** [review]

**Review by ariya — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
@ariya I've backported this (still not merged), but on a second thought - do we want this in 42 or 43?

**Comment by flamber** [comment]
@nemanjaglumac Does this influence translations? If yes, then 43. If no, then it can be backported.

**Comment by nemanjaglumac** [comment]
Just checked `.po` files. Both terms "Native query" and "SQL query" were already there (already translated) from before.
In other words, this shouldn't affect translations.

**Pull request merged**
