### PR TITLE
Collections project curate permissions UI

### LINKED ISSUE #7698: Only user with curate permissions should be able to see the edit icon or pin a dashboard to a collection
If I have the curate/edit bit for a collection, I should be able to pin a dashboard to the collection.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #7698

- [x] Need backend to include `can_write` in `GET /api/collection/:id`
- [x] Need backend to include `can_write` in `GET /api/collection/root`
- [x] Only show pins to users with `can_write`
- [x] Hide + and pencil icons?

### CODE REVIEW

**Comment by camsaul** [comment]
Went ahead and added `can_write` in the `nested-collections` branch.

**Comment by mazameli** [comment]
Yes, the `+` and pencil icons should be hidden if the user only has View permission for the current collection.

**Comment by tlrobinson** [comment]
> This branch seems to be preventing admins from pinning things in the root collection (no pin icon on hover)

This is because `GET /api/collection/:id` doesn't include `can_write`. Are we planning on merging `nested-collections` into `collections-project` soon, or do we need to pull @camsaul's fix in?

**Comment by salsakran** [comment]
confirmed that this works on my local machine

**Pull request merged**
