### PR TITLE
Fixing `format-sql` to work with Metabase SQL Parameters

### PR DESCRIPTION
**Pull request by markbastian**
`format-sql` will expand double-curly brace expressions (e.g. {{FOO}} becomes { { FOO } }). This fixes that.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30008)

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
Have you looked into having the SQL formatter itself not output brackets like this? Seems like it would be better if we could have it format things the way we want directly rather than taking the formatted output and then re-formatting it again

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30008#-:-NSmCsk0CSB0Rvgr_yuO:b-13lom3)* status: all files reviewed, 2 unresolved discussions (waiting on @markbastian)

___
*[`src/metabase/db/query.clj` line 62 at r1](https://reviewable.io/reviews/metabase/metabase/30008#-NSmAYy4ACB_xll5RdTk:-NSmAYy50LG-D2_5lVuX:b-dy98gf) ([raw file](https://github.com/metabase/metabase/blob/327b97579c944a35286ef351bd2e46cc71f72c0e/src/metabase/db/query.clj#L62)):*
> ```Clojure
>   [sql]
>   (when sql
>     (let [rgx #"\{\s*\{\s*[^\}]+\s*\}\s*\}"]
> ```

Should these be `\s+` instead of `\s*`? Not need to replace anything if there is no whitespace to replace. Also, I'm wondering whether this would be a little easier if you just used a capture group.

```clj
(str/replace s #"\{\s+\{\s+([^}]+)\s+\}\s+\}" "{{$1}}")

(str/replace "SELECT\n  A\nFROM\n  { { # 1234 } }\nWHERE\n  { { STATE } }" #"\{\s+\{\s+([^}]+)\s+\}\s+\}" "{{$1}}")
;; =>
"SELECT\n  A\nFROM\n  {{# 1234}}\nWHERE\n  {{STATE}}"
```

Or maybe separate lookahead and lookbehind patterns

```clj
(-> s
    (str/replace #"\{\s+\{\s+(?=.*\}\s*\})" "{{")
    (str/replace #"(?<=\{\{.*)\s+\}\s+\}" "}}"))
```
___
*[`test/metabase/db/query_test.clj` line 98 at r1](https://reviewable.io/reviews/metabase/metabase/30008#-NSmAJ6u6wz2_ZNbtT9R:-NSmAJ6u6wz2_ZNbtT9S:b-dbzkov) ([raw file](https://github.com/metabase/metabase/blob/327b97579c944a35286ef351bd2e46cc71f72c0e/test/metabase/db/query_test.clj#L98)):*
> ```Clojure
>                  (json/parse-string weird-formatted-query))))))))
> 
> (deftest format-sql-with-params-test
> ```

Pure function test, you should make it `^:parallel`



_Code quote (i):_
```Clojure
(deftest format-sql-with-params-test
```



_Code snippet (ii):_
```Clojure
(deftest ^:parallel format-sql-with-params-test
```

**Review by metamben — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30008)* status: all files reviewed, 5 unresolved discussions (waiting on @markbastian)

___
*[`src/metabase/db/query.clj` line 62 at r1](https://reviewable.io/reviews/metabase/metabase/30008#-NSmC9EbAodUHWVLjy0_:-NSmC9EbAodUHWVLjy0a:b-k33c7n) ([raw file](https://github.com/metabase/metabase/blob/327b97579c944a35286ef351bd2e46cc71f72c0e/src/metabase/db/query.clj#L62)):*
> ```Clojure
>   [sql]
>   (when sql
>     (let [rgx #"\{\s*\{\s*[^\}]+\s*\}\s*\}"]
> ```

The second last `\s*` will ever only match the empty string, so it can be removed.
___
*[`src/metabase/db/query.clj` line 63 at r1](https://reviewable.io/reviews/metabase/metabase/30008#-NSmCYzl8MDLhnEwmLgL:-NSmCYzl8MDLhnEwmLgM:b-zhs1l7) ([raw file](https://github.com/metabase/metabase/blob/327b97579c944a35286ef351bd2e46cc71f72c0e/src/metabase/db/query.clj#L63)):*
> ```Clojure
>   (when sql
>     (let [rgx #"\{\s*\{\s*[^\}]+\s*\}\s*\}"]
>       (str/replace sql rgx (fn [match] (str/replace match #"\s*" ""))))))
> ```

`\s*` -> `\s+`
___
*[`test/metabase/db/query_test.clj` line 102 at r1](https://reviewable.io/reviews/metabase/metabase/30008#-NSmCpJR4dlnbfBL3TOd:-NSmCpJR4dlnbfBL3TOe:bl01hky) ([raw file](https://github.com/metabase/metabase/blob/327b97579c944a35286ef351bd2e46cc71f72c0e/test/metabase/db/query_test.clj#L102)):*
> ```Clojure
>     ;; Baseline demonstrating what we don't want.
>     (is (= "SELECT\n  *\nFROM\n  { { # 1234 } }"
>            (#'mdb.query/format-sql* "SELECT * FROM {{#1234}}")))
> ```

I think the comment in the code is enough, I don't care much maintaining this property.

**Review by metamben — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30008)* status: all files reviewed, 5 unresolved discussions (waiting on @markbastian)

**Review by markbastian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30008)* status: 0 of 21 files reviewed, 5 unresolved discussions (waiting on @camsaul and @metamben)

___
*[`src/metabase/db/query.clj` line 62 at r1](https://reviewable.io/reviews/metabase/metabase/30008#-NSmAYy4ACB_xll5RdTk:-NSmcjje0Ij0WWTq-3zo:b-614zrp) ([raw file](https://github.com/metabase/metabase/blob/327b97579c944a35286ef351bd2e46cc71f72c0e/src/metabase/db/query.clj#L62)):*
<details><summary><i>Previously, camsaul (Cam Saul) wrote…</i></summary><blockquote>

Should these be `\s+` instead of `\s*`? Not need to replace anything if there is no whitespace to replace. Also, I'm wondering whether this would be a little easier if you just used a capture group.

```clj
(str/replace s #"\{\s+\{\s+([^}]+)\s+\}\s+\}" "{{$1}}")

(str/replace "SELECT\n  A\nFROM\n  { { # 1234 } }\nWHERE\n  { { STATE } }" #"\{\s+\{\s+([^}]+)\s+\}\s+\}" "{{$1}}")
;; =>
"SELECT\n  A\nFROM\n  {{# 1234}}\nWHERE\n  {{STATE}}"
```

Or maybe separate lookahead and lookbehind patterns

```clj
(-> s
    (str/replace #"\{\s+\{\s+(?=.*\}\s*\})" "{{")
    (str/replace #"(?<=\{\{.*)\s+\}\s+\}" "}}"))
```


</blockquote></details>

I was able to configure the SqlFormatter library as suggested.

**Pull request merged**
