### PR TITLE
Update filter modal tab metrics

### PR DESCRIPTION
**Pull request by iethree**
## Description

- change "metrics" tab name to "summaries" [(notion link)](https://www.notion.so/metabase/Change-Metrics-tab-name-to-Summaries-or-Summarizations-afdab449d595402b80053bf6fd049438)
- put "summaries" tab at the end of the tabs [(notion link)](https://www.notion.so/metabase/Dimensions-should-come-before-metrics-in-filter-modal-1daf9954df304e808c715f30009dd47e)
- always show tab icons

## Screenshots

Screen Shot 2022-06-07 at 2 29 42 PM

This also affects the name and order of options in the filter sidebar

Screen Shot 2022-06-07 at 2 29 57 PM

## Testing Steps

- open any table (like orders)
- apply any summary from the summary sidebar (like count by order id)
- open the bulk filter modal, and see the summaries tab appears at the end, with an icon

### CODE REVIEW

**Review by WiNloSt — APPROVED** [review]
Works as expected. I don't really understand the structured query, but the change itself is pretty easy to reason about.

**Comment by koconder** [comment]
Also agree with @WiNloSt

**Review by kdoh — APPROVED** [review]
I'm finding it a bit deflating to end up on the summary tab for the most common case of a single aggregation. It feels heavier than I'd ideally want. I'm starting to wonder if a separate tab for the aggregation(s) will ultimately be the way to go or not. Might need a bit more design.

Regardless, I'd go ahead and merge this change since it's relatively simple and improves what we already have.

**Comment by kdoh** [comment]
@WiNloSt / @koconder When you say you don't understand the structured query do you mean you're confused by something about the UX of the new filter modal, or is that more of a reference to something about the code? Would love to hear more about that if it's the former.

**Comment by WiNloSt** [comment]
@kdoh I was specifically referring to the code itself. The change was in `frontend/src/metabase-lib/lib/queries/StructuredQuery.ts`, I tried to look around the file, but still didn't get the whole picture of how everything is working together yet.

**Pull request merged**
