### PR TITLE
Dashboard fullscreen / auto-refresh [Experimental]

### LINKED ISSUE #1349: Dashboard fullscreen / auto-refresh ability
Currently the width is limited and the widgets are centered, which doesn't allow to take advantage of bigger resolutions.

It could be nice to have an option to display the dashboard full screen and also auto-refreshing the metrics, typically to set up a dashboard on a TV. 
 
(from http://discourse.metabase.com/t/dashboard-on-tv/51)

### PR DESCRIPTION
**Pull request by tlrobinson**
Will resolve #1349 but needs more work on full screen card layout.

Currently refreshes on a fixed 5 minute interval.

screenshot 2015-10-28 13 22 39 2

### CODE REVIEW

**Comment by styts** [comment]
Any idea when this will get merged? We need it :smiley:

**Comment by mbseid** [comment]
+1 on this. I would love this. Was about to implement it ourselves.

**Comment by zackliscio** [comment]
+1

**Comment by kdoh** [comment]
Hey all. Thanks for the +1's, as always they help us a ton with understanding your needs so keep 'em coming.

Just wanted to pop in and let you know we hear you and we've been working on redesigning dashboards more generally.  One of the requirements of the updates is making sure dashboards look great on widescreen monitors and as part of that we want to give you the option to make sure things stay up to date. The plan also includes updating the look and feel of the visualizations to make sure your data is more legible and better looking.

I can't give an exact sense of when exactly we'll be shipping it just yet but should be within the next couple of releases.

**Comment by MartinArens** [comment]
+1

**Comment by tlrobinson** [comment]
Closing this. New version implemented in #2136

**Pull request closed without merging**
