### PR TITLE
[MLv2] Append and drop final stage

### PR DESCRIPTION
**Pull request by snoe**
Functions to append or drop the final stage of a query.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29625)

### CODE REVIEW

**Review by camsaul — CHANGES_REQUESTED** [review]
Overall this LGTM but I think we should explicitly error in `drop-stage` for queries with only one stage, and that test for `append-stage` could be slightly better

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29625#-:-NRe4r3mDW9hyKgdDc6Q:bx4dwfa)* status: all files reviewed, 2 unresolved discussions (waiting on @snoe)

___
*[`src/metabase/lib/stage.cljc` line 258 at r1](https://reviewable.io/reviews/metabase/metabase/29625#-NRe4HieDW80FAK-LUJa:-NRe4HieDW80FAK-LUJb:b-bkdlrp) ([raw file](https://github.com/metabase/metabase/blob/3cc83a27f1e6a739f96fd790f09c4bf9159f7ba9/src/metabase/lib/stage.cljc#L258)):*
> ```Clojure
>   (update query :stages conj (lib.options/ensure-uuid {:lib/type :mbql.stage/mbql})))
> 
> (mu/defn drop-stage :- ::lib.schema/query
> ```

What should this do if the query only has one stage? It should probably throw an Exception, right? 

Keep in mind the `mu/defn` instrumentation checks don't currently run in JS 



_Code quote:_
```Clojure
(mu/defn drop-stage :- ::lib.schema/query
  "Drops the final stage in the pipeline"
  [query]
  (update query :stages (comp vec butlast)))
```
___
*[`test/metabase/lib/stage_test.cljc` line 72 at r1](https://reviewable.io/reviews/metabase/metabase/29625#-NRe4ZmOETSvUvb_EPAv:-NRe4ZmOETSvUvb_EPAw:b-lxj9zf) ([raw file](https://github.com/metabase/metabase/blob/3cc83a27f1e6a739f96fd790f09c4bf9159f7ba9/test/metabase/lib/stage_test.cljc#L72)):*
> ```Clojure
>     (is (not= query
>               (-> query
>                   (lib/append-stage)
> ```

TBH this isn't really a great test, `lib/append-stage` could just be implemented as `(assoc query :x true)` and this would still pass. Actually checking that the shape looks like what we expected would be nice



_Code quote:_
```Clojure
    (is (not= query
              (-> query
                  (lib/append-stage)
                  (lib/filter 1 (lib/= 1 (lib/field "VENUES" "NAME"))))))
```

**Comment by snoe** [comment]
*[`test/metabase/lib/stage_test.cljc` line 72 at r1](https://reviewable.io/reviews/metabase/metabase/29625#-NRe4ZmOETSvUvb_EPAv:-NRe5eD88r7GwySpZ8BX:bvdlsek) ([raw file](https://github.com/metabase/metabase/blob/3cc83a27f1e6a739f96fd790f09c4bf9159f7ba9/test/metabase/lib/stage_test.cljc#L72)):*
<details><summary><i>Previously, camsaul (Cam Saul) wrote…</i></summary><blockquote>

TBH this isn't really a great test, `lib/append-stage` could just be implemented as `(assoc query :x true)` and this would still pass. Actually checking that the shape looks like what we expected would be nice
</blockquote></details>

The schema instrumentation and adding the filter to the new stage both help to ensure that the stage was properly added (it errors with "Stage 1 does not exist" otherwise).

**Comment by camsaul** [comment]
*[`test/metabase/lib/stage_test.cljc` line 72 at r1](https://reviewable.io/reviews/metabase/metabase/29625#-NRe4ZmOETSvUvb_EPAv:-NRe8OUKB9mKHYmfSM_z:b-4gor3b) ([raw file](https://github.com/metabase/metabase/blob/3cc83a27f1e6a739f96fd790f09c4bf9159f7ba9/test/metabase/lib/stage_test.cljc#L72)):*
<details><summary><i>Previously, snoe (Case Nelson) wrote…</i></summary><blockquote>

The schema instrumentation and adding the filter to the new stage both help to ensure that the stage was properly added (it errors with "Stage 1 does not exist" otherwise).
</blockquote></details>

Gotcha.

**Comment by snoe** [comment]
*[`src/metabase/lib/stage.cljc` line 258 at r1](https://reviewable.io/reviews/metabase/metabase/29625#-NRe4HieDW80FAK-LUJa:-NReBIDYBr5uNYl-eWLp:b-896fix) ([raw file](https://github.com/metabase/metabase/blob/3cc83a27f1e6a739f96fd790f09c4bf9159f7ba9/src/metabase/lib/stage.cljc#L258)):*
<details><summary><i>Previously, camsaul (Cam Saul) wrote…</i></summary><blockquote>

What should this do if the query only has one stage? It should probably throw an Exception, right? 

Keep in mind the `mu/defn` instrumentation checks don't currently run in JS 
</blockquote></details>

Done.

**Comment by snoe** [comment]
*[`test/metabase/lib/stage_test.cljc` line 72 at r1](https://reviewable.io/reviews/metabase/metabase/29625#-NRe4ZmOETSvUvb_EPAv:-NReBs402gAInNpiLmT0:bu80rcz) ([raw file](https://github.com/metabase/metabase/blob/3cc83a27f1e6a739f96fd790f09c4bf9159f7ba9/test/metabase/lib/stage_test.cljc#L72)):*
<details><summary><i>Previously, camsaul (Cam Saul) wrote…</i></summary><blockquote>

Gotcha.
</blockquote></details>

Updated to be a bit more explicit.

**Review by camsaul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29625#-:-NReQ2co81l--Kxe4Nth:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoe)

**Comment by camsaul** [comment]
Hitting merge on this because I want to use it for something

**Pull request merged**
