### PR TITLE
Fix new questions don't appear in the Saved Questions picker

### LINKED ISSUE #9027: New questions do not appear in 'Source Questions' until you refresh the browser
Save a new question, then go to the QB and it doesn't appear as a source until you refresh the browser. Seems to be an issue on all versions I've tested (up to 0.31.1)

### PR DESCRIPTION
**Pull request by kulyk**
**EDIT:** the solution changed from a simple reload to adding custom reducers to schema and table entities

Fixes #9027: new questions don't appear in the Saved Questions picker until you refresh the browser. The fix is very straightforward: it makes the picker refresh the list of selected collection questions any time we select a collection

### To Verify

1. (in a new window) Custom question > Saved Questions - wait for the list of "Our analytics" to load
2. Native query > Sample Dataset > `select 0` run and save as "0-test" in "Our analytics"
3. Custom question > Saved Questions > you should see "0-test" inside "Our analytics" immediately

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
This seems like a "hammer" method, which means less caching, but more requests.
It's kinda a central issue throughout Metabase - see https://github.com/metabase/metabase/issues/10330#issuecomment-610900593 - it would be great if we could find a more graceful approach.

First time it will show a loading spinner, but any time after that it will make the request and then show the selector (which takes ~700ms on my setup with a few hundred questions).
If it would show the selector loader, then I would probably be okay with approving this, since doing a browser refresh (or re-login) is a pretty bad user experience and it's currently much more difficult to share anything in a team.

**Review by ranquild — COMMENTED** [review]
@kulyk There is a way to invalidate entities cache, please look for `actionShouldInvalidateLists` and `INVALIDATE_LISTS_ACTION`. Another approach would be providing a `reducer` for an entity to add an entry directly without a BE request, `Users` entity does that.

**Comment by kulyk** [comment]
@flamber @ranquild thanks for your feedback 🙏  And @ranquild thank you for the implementation tip.

I went with the reducers approach, `actionShouldInvalidateLists` is a pretty brutal solution as it would invalidate all the schemas and tables caches each time a question is created or updated. Also, this PR makes the picker handle cases when questions are archived and unarchived (as they also should be removed from / added to the picker)

**Review by ranquild — APPROVED** [review]
Tested it and seems to be working correctly, great work!

**Comment by flamber** [comment]
@kulyk Maybe I'm doing something wrong, but it's not working on `edfaaa4`. Tested Firefox and Chrome.

**Comment by kulyk** [comment]
@flamber that's strange. I'm following the repro steps you mentioned in the issue + archive/unarchive scenario and "it works on my machine"™ (see the attached video). Could you please double-check as @ranquild also confirmed it works? Or maybe there is some uncovered edge case you face?

https://user-images.githubusercontent.com/17258145/135494607-59f6bdec-4f2f-47ab-8953-fe23aec1080e.mov

**Review by flamber — APPROVED** [review]
Your video looks soooooo cool - wish my fairly large test setups was similar, though a blank instance works almost similar to your video.

I'm good with putting this into master if it would help to get more testing (stats etc), but should we hold off on backport just for a day or two?

https://user-images.githubusercontent.com/1447303/135518849-73a8f4e6-c63a-44aa-a113-43a87154627b.mp4

https://user-images.githubusercontent.com/1447303/135520082-20c1603b-4800-4587-954f-2db385c5ce4b.mp4

**Pull request merged**
