### PR TITLE
Fixes Elastic Beanstalk timeouts on AL1 platform

### PR DESCRIPTION
**Pull request by ghost**
A prior PR moved the nginx conf setup into .platform
which is used by the AL2 platform, but not AL1. This
adds back the nginx setup in .ebextensions, which fixes
timeouts on long queries (>60 seconds).

###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/19387)

### CODE REVIEW

**Comment by paoliniluis** [comment]
Hi @aguerard, thanks for the contribution. Amazon Linux 1 is now EoL (https://aws.amazon.com/amazon-linux-ami/faqs/) with only maintenance support from AWS. We have strongly suggested our users to move away from AL1 due to this and other reasons, so I'm concerned that adding more complexity into our deployment bundles to support an EoL'd platform will be an issue. Why can't you move away from AL1? thanks

**Comment by aguerard** [comment]
> Hi @aguerard, thanks for the contribution. Amazon Linux 1 is now EoL (https://aws.amazon.com/amazon-linux-ami/faqs/) with only maintenance support from AWS. We have strongly suggested our users to move away from AL1 due to this and other reasons, so I'm concerned that adding more complexity into our deployment bundles to support an EoL'd platform will be an issue. Why can't you move away from AL1? thanks

I'm only adding to the directories used by the AL1 platform; if this was touching shared/AL2 files I'd otherwise agree with you. If you don't want users to use AL1, you should rm that entire ebextensions directory and add that info to the official docs for setting up metabase on EB. In our case, i was just trying to update to fix the log4j issue; decoupling the DB, doing a blue-green deploy, etc. seemed like a lot more work (and i assume AL1 was still supported given those file are still there).

Given I'm only adding complexity to the EoL platform files, does it really matter if it will fix those who are still on AL1 w/o affecting anyone else?

**Comment by aguerard** [comment]
Thanks for the quickly reply, BTW! Wasn't expecting such short turnaround

**Comment by aguerard** [comment]
>We recommend using platform hooks to run custom code on your environment instances. You can still use commands and container commands in .ebextensions configuration files, but they aren't as easy to work with. For example, writing command scripts inside a YAML file can be cumbersome and difficult to test.

source: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.migration-al.html

I was wrong; these configuration files are still used. I'll have to modify this PR to check the platform and only run the nginx command if it's AL1.

I bet there are a few folks like me who now have (effectively) broken AL1 EB stacks. I still think it's best for the community to merge it in given most folks don't have a choice but to update in light of the log4j vuln (if this were solely an optional/feature upgrade then that's a different story). If going from AL1->2 was a button press it'd be one thing, but it's a bit of a procedure.

**Comment by paoliniluis** [comment]
closing as we no longer recommend beanstalk for deployment

**Pull request closed without merging**
