### PR TITLE
Custom styling for file picker button

### LINKED ISSUE #12728: Service account JSON file picker needs visual polish
Screen Shot 2020-06-16 at 2 33 41 PM

### PR DESCRIPTION
**Pull request by mazameli**
Fixes #12728

## Before

image

## After

image

## File selected

image

### CODE REVIEW

**Review by kdoh — COMMENTED** [review]
Looks good. Only thing I might consider is changing the text color to a darker shade when there's a file that's been selected. The initial state and selected look a bit similar.

**Comment by mazameli** [comment]
@paulrosenzweig, do you know if there's a way where I could conditionally add/change css classes in `/components/form/widgets/FormTextFileWidget.jsx` when a file's been selected? I'm not really following the handler code in there.

**Comment by paulrosenzweig** [comment]
@mazameli I think you could add the class when the `value` prop is falsey. e.g.

`className={cx({"Form-file-input--has-value": value}, "Form-file-input")}`

With `cx` provided by ` import cx from "classnames"` .

**Comment by mazameli** [comment]
Sweet, that did the trick! @kdoh could I get an approval if this looks good to you?

conditional-styling

**Review by kdoh — APPROVED** [review]

**Pull request merged**
