### PR TITLE
Fix embed downloads for 'non-root context'

### LINKED ISSUE #8848: Report Embed Export Failed
https://github.com/metabase/metabase/pull/8629

This issue is regarding pull request Fix public/embed downloads when mounted at non-root context #8629

I have verified this issue in Metabase 0.31 RC1 and the exports for dashboard embedding works super fine but when the report is embedded the export fails. 

@tlrobinson @senior @camsaul , could you please look into this issue?

Thank you

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #8848

### CODE REVIEW

**Comment by Siddarth434** [comment]
I do not have Dev level setup. I can definitely try if you give me a metabase jar.

**Comment by tlrobinson** [comment]
@Siddarth434 https://www.dropbox.com/s/z142lltdp3rbpkw/metabase-fix-non-root-embed-downloads.jar

**Comment by Siddarth434** [comment]
@tlrobinson,

I will let you know by tomorrow.

**Review by Siddarth434 — APPROVED** [review]
I have verified the changes and it is working Perfectly.

**Pull request merged**
