### PR TITLE
simple chart colors expansion.

### PR DESCRIPTION
**Pull request by kdoh**
Simpler implementation of #4125 that just uses our existing colors to expand the range of series colors for line and bar charts.

Should satisfy #3185 and a range of other color limit related issues.

### CODE REVIEW

**Review by tlrobinson — APPROVED** [review]
LGTM, I think.

Just to confirm, the initial 5 or whatever colors are the same, so people's existing charts won't change?

**Comment by kdoh** [comment]
@tlrobinson Yup. This just adds to the initial set.

**Comment by formariz** [comment]
It's avaliable only in enterprise plan?

**Comment by flamber** [comment]
@formariz It's been available since 0.23 (in the open source edition): https://github.com/metabase/metabase/issues/3185#issuecomment-277321470
But you're likely looking for #6300

**Pull request merged**
