### PR TITLE
Fix exclude days of week filter formatting

### LINKED ISSUE #21979: Filtering "Exclude" shows wrong weekday
**Describe the bug**
Filtering "Exclude" shows wrong weekend - though, the actual query is correct - took me a while to understand what was going on.

**To Reproduce**
1. Question > Sample > Products
2. Filter CreatedAt > Exclude > "Days of the week" > uncheck Monday - Add filter
3. Incorrectly shows the wrong day - it is filtering correctly in the query
image
4. Edit the filter and select Monday again, now it's not possible the save the filter changes (Update filter)
image

**Expected behavior**
While I'm fine with the order of the weekdays, then in a perfect world, it should order depending on Admin > Settings > Localization > First day of the week

**Information about your Metabase Installation:**
0.43.0-rc1 and master `b9cedcc`

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/21979
Reproduces https://github.com/metabase/metabase/issues/21979

How to test:
- Follow the steps from issue
- There is also new unit tests for this case

Please note that technically the change for `hour-of-day` is not needed because the `value` already contains timezone information and `moment.utc` would give the same result as `moment(value).utc()`. However I believe it would be great to parse the value in the same way as for `day-of-week` for consistency.

### CODE REVIEW

**Comment by ranquild** [comment]
@nemanjaglumac Could you fix merge conflicts in https://github.com/metabase/metabase/pull/21998/files? I would merge it afterwards

**Comment by nemanjaglumac** [comment]
@ranquild will it be ok if I push that repro directly to this branch rather than waiting for the CI after I solve merge conflict and then you'd have to wait for the CI again after you merge it?

**Comment by ranquild** [comment]
@nemanjaglumac sure, push it here

**Comment by nemanjaglumac** [comment]
@ranquild it seems that at least one part of that issue was not fixed.
image

The string in the test needs to be updated to `Update filter` but the button itself is disabled, which is incorrect behavior.

**Comment by ranquild** [comment]
@nemanjaglumac I don't think it's a bug. You cannot exclude nothing when using exclude filter.

**Comment by ranquild** [comment]
I've updated the test to match the filter behavior.

**Review by akiselev — APPROVED** [review]

**Pull request merged**
