### PR TITLE
Feature/map

### PR DESCRIPTION
**Pull request by ChakshuGautam**
###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### CODE REVIEW

**Comment by flamber** [comment]
Hi @ChakshuGautam 
I don't know what this PR is trying to address, so please update description and would need to be rebased to master.
Closing for now.

**Comment by ChakshuGautam** [comment]
Hey sorry this was done by mistake. Please delete this PR. I was just playing with the code. Thanks.

**Comment by flamber** [comment]
@ChakshuGautam That's not how Github works. You cannot delete PRs, only close them.

**Comment by ChakshuGautam** [comment]
Yes. Sorry, poor choice of words. I meant close only. Sorry for the inconvenience.

**Pull request closed without merging**
