### PR TITLE
Partial fix for #24727: reduce number of linting false positives in test

### PR DESCRIPTION
**Pull request by borkdude**
#24727

cc @dpsutton @camsaul

### CODE REVIEW

**Comment by borkdude** [comment]
@dpsutton @camsaul 

I spent 5 hours on this and got the count down from:

linting took 8888ms, errors: 710, warnings: 721

to:

linting took 9324ms, errors: 113, warnings: 103

I can do part 2 after my vacation in a couple of weeks.
One thing that's not accounted for in the hooks is that `mbql-query` can have fully qualified symbols with causes two warnings: one for an unresolved namespace and one for an invalid binding. This is the major TODO, the rest is more of the same that's in this PR.

**Comment by dpsutton** [comment]
@borkdude this looks outstanding. 

I like your judicious use of ns-group, individual namespace config, metadata in the namespace. Thanks so much.

Looks like our other namespace linter is complaining about `ns` vs `[ns]`. I think we have plans to retire that one.

**Comment by borkdude** [comment]
@dpsutton I see that I accidentally introduced a bunch of whitespace changes. Do you want me to revert those?

**Comment by dpsutton** [comment]
@borkdude if its easy to undo that would be nice. Although its not unheard of that we have incorrectly indented forms. But probably better to either not fix them in this or certainly not indent them in a way we don't like.

**Comment by camsaul** [comment]
Nice! I'll try to figure out how to merge this with the work I did on this yesterday: https://github.com/metabase/metabase/pull/24736

I fixed the `mbql-query` hook and some of the other issues you mentioned there already in that PR

**Comment by borkdude** [comment]
@camsaul Feel free to cherry-pick anything you want from this PR and then close it.

**Comment by camsaul** [comment]
I pulled some of this stuff into #24748 and other follow-on PRs, and those have been merged in now. Going to go ahead and close this out

**Pull request closed without merging**
