### PR TITLE
Add more logging information for serialization

### PR DESCRIPTION
**Pull request by jeff303**
Include causes when logging

### CODE REVIEW

**Review by flamber — APPROVED** [review]
Is this included in the new Serialization PRs? Otherwise just rebase, so it'll be part of those.

**Comment by jeff303** [comment]
> Is this included in the new Serialization PRs? Otherwise just rebase, so it'll be part of those.

Is this change actually useful to you?  I had the impression that we still needed a friendlier "I am trying to do X" line for everything.  But in any case, I can lump this into the master changes in #15756 tomorrow.

**Comment by flamber** [comment]
I would love if there were smarter errors, which gave a clear understanding of the problem - and the full stack could be included with debug parameter.
But the current state is just a black box, which is why I would prefer adding full stacktraces to errors until my test setup does a `dump`, `load` and `load --mode update` without any (vague) errors.

**Comment by jeff303** [comment]
These changes (and more logging improvements) will be moved into #15858.

**Pull request closed without merging**
