### PR TITLE
fix implicit date parsing from numbers

### LINKED ISSUE #19118: Wrong label display in Chart
**Describe the bug**
I have "Fiscal Year" and the labels should display "2020","2021" and "2022" respectively. But it's showing differently. Below are screenshots of my data presented in tabular and graphical forms. Fiscal Year is defined as a "Category"
image

**To Reproduce**
My Native Query
select 2020 as fiscalyear, 200 as Quantity union
select 2021 as fiscalyear, 100 as Quantity union
select 2022 as fiscalyear, 150 as Quantity 

1. Summarize by Calculating the summary of Quantity
2. Grouped by Fiscal Year
3. Change visualization to Bar Graph 

**Expected behavior**
The label should reflect the correct value 

**Screenshots**
image
image

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.1+9",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.1+9",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.1.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.8-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Our end-user might deemed our report erroneous because of the inaccurate label being displayed and would also make our report unreliable.

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/19118

## Changes

When we render Line/Area/Bar/Scatter charts we try to infer x-axis data type from numbers/strings when x-axis type is not manually specified by user. The function `dimensionIsTimeseries` from `frontend/src/metabase/visualizations/lib/timeseries.js` is used to detect if x-axis values contain implicit date time by trying to parse the value using moment `moment(rows[0] && rows[0][i], moment.ISO_8601).isValid()`. The important detail is that we use `moment.ISO_8601` format here. However, we did not specify the format later when we parse actual x-axis values to render them.

## How to verify

- New -> Native query
```
select 2020 as fiscalyear, 200 as Quantity union
select 2021 as fiscalyear, 100 as Quantity union
select 2022 as fiscalyear, 150 as Quantity
```

- Visualize as Line
- Set x-axis `fiscalyear`
- Set y-axis `quantity`
- Ensure X-ticks show correct values

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual-tests

**Comment by alxnddr** [comment]
@metabase-bot run visual-tests

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Review by ranquild — COMMENTED** [review]
While the fix works, I don't know if it breaks something. We use this function literally everywhere to parse dates. WDYT about using this format only for numbers?

**Review by ranquild — CHANGES_REQUESTED** [review]
I believe we should use this format only when the value is a number. Check the value by a regexp as we do for timezones?

**Comment by alxnddr** [comment]
@ranquild we don't need to check by regex because strings like '2015' worked before and the issue was only with numbers. I added type check for safety in order not to break anything unexpectedly

**Review by ranquild — APPROVED** [review]

**Review by ariya — APPROVED** [review]

**Review by akiselev — APPROVED** [review]

**Pull request merged**
