### PR TITLE
Metrics segments fixes

### LINKED ISSUE #3492: Metric and Segment creation weirdness
On rc-0.20, when attempting to create a Metric, I'm incorrectly shown `raw data` as a possible selection for my aggregation type (and it's unclickable). 

More importantly, I also can't seem to make a selection for **any aggregation type**. If it's a one-step aggregation type, like `count of rows`, it's unclickable; if it's a two-step selection, like `Sum of…`, then the column is unclickable.

This is also happening with Segment creation: select any kind of filter, then try clicking `Add filter` and observe that nothing happens. You also cannot close the popover menu.

screen shot 2016-10-10 at 11 55 31 am

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3492

### CODE REVIEW

**Comment by kdoh** [comment]
LGTM

**Comment by salsakran** [comment]
looks reasonable codewise, but out of curiosity why didn't this get picked up before ?

**Comment by salsakran** [comment]
👍  verified that I can create metrics/segments

**Comment by tlrobinson** [comment]
I introduced the crashyness bug this weekend and noticed it and thought I fixed it but I guess it slipped by. Need more test cases :-/

It looks like the raw data option has been appearing for a long time, if not forever.

**Pull request merged**
