### PR TITLE
Release 0.21.0

### PR DESCRIPTION
**Pull request by salsakran**
Booooosh!

### CODE REVIEW

**Comment by kdoh** [comment]
🎉

**Comment by anki-code** [comment]
Guys, 

1. Could you add the metric name to the tooltip in the stacked area 

image

or replace "Count" label to metric name:
image

Color markers really confused me when I work with many stacked charts with different colors.

2. Could  you add the alphabet sort in dashboards dropdown?

3. Could you add more colors in palette:
image)

I have charts with more than 5 blocks in stack area and it's the hell to analyze it: you have two blocks with the same colors and the same tooltip (see point 1 in this list)

Thank you for great product!

**Comment by tlrobinson** [comment]
@anki-code Could you file # 1 and # 2 as separate issues? # 3 is already filed in #3185

**Comment by anki-code** [comment]
@tlrobinson, Yep! 1 - #3899, 2 - #3900

**Comment by salsakran** [comment]
closing as the version number was updated separately and there were no additions to 0.21 since branching off master.

**Pull request closed without merging**
