### PR TITLE
Improve dashboard performance

### PR DESCRIPTION
**Pull request by attekei**
This addresses #4929 and I've done the following changes:
- got rid of super slow `updateIn` in getMappingsByParameter
- got rid of `shouldComponentUpdate` in DashboardGrid because it just slowed things down and the count of renders is so slow that I think that we don't really need it
- removed `HACK_parseTimestamp`; because of garbage collection it actually just slowed things down
- recalculate the dashboard header height only when mounting header and preparing for showing the header modal

### CODE REVIEW

**Comment by attekei** [comment]
Ready for code review, feel free to chime in if you think that some of the optimizations I did are not good!

**Comment by tlrobinson** [comment]
Can you explain what was going on with `HACK_parseTimestamp`? We added that specifically to fix performance issues so I'm surprised it was slowing things down.

**Comment by attekei** [comment]
In my quick benchmarking the normal `parseTimestamp` was actually around 30% faster, maybe due to reduced garbage collecting explained in #4929. But I'm not totally confident about it and it has a minor (~10-20ms delay) impact to interactions so I could also revert that specific change.

**Comment by tlrobinson** [comment]
Are you saying `parseTimestamp` is 30% faster than `HACK_parseTimestamp`, or the overall render is 30% faster with `parseTimestamp` instead of `HACK_parseTimestamp`?

**Comment by attekei** [comment]
Just the method itself, with large datasets there was a difference of ~5-10ms per a run of `makeIndexMap`. I don't know why the GC is triggered in `HACK_parseTimestamp`. But because you likely had good reasons for adding it, I will revert that change and merge this PR after that.

**Comment by tlrobinson** [comment]
I'm guessing you weren't noticing the slow down when changing `HACK_parseTimestamp` because it only really helps when you have a very large number of time points, and I think most of these optimizations help with more "average" cards. 5-10ms is obviously a worthwhile tradeoff if it saves hundreds of ms later. If you're not sure why code is there it doesn't hurt to ask.

I suspect the only performance regression in 0.24 was due to the new "fully connected" metadata object being injected in `DashCard`s, and the `shouldComponentUpdate` which did a deep equality check, thus comparing ALL the metadata rather than one table's metadata (and I suspect when I wrote that `shouldComponentUpdate` I may have thought `_.isEqual` was a shallow comparison...)

I think removing `shouldComponentUpdate` entirely might actually be a regression compared to 0.23, in cases where rendering is slower than doing a deep equality check of all the props (including the entire `data` objects)

It would be good if we wrote a better thought out `shouldComponentUpdate` in `Visualization` to avoid unnecessary re-renders in all situations, not just `DashCards`.

**Pull request merged**
