### PR TITLE
Allow using models in native queries and dashboards

### LINKED ISSUE #19449: Variable sidebar in native editor should include datasets
**Is your feature request related to a problem? Please describe.**
It's not clear that you can reference datasets when writing a SQL query.

image

**Describe the solution you'd like**
It should be obvious that you can incorporate datasets in your SQL queries.

**How important is this feature to you?**
This ticket just identifies an opportunity for dataset completeness, as datasets are still in development at the time of this writing.

**Additional context**
We may want to do more in the variable sidebar, or create a different section, to make it clear that you can reference saved questions and datasets. Right now it's kind of a "hidden" feature.

### PR DESCRIPTION
**Pull request by kulyk**
Resolves #19449

This PR makes it possible to use models in native queries (like `select * from {{ #MODEL_ID }}`) and add them to dashboards. Models are still saved questions under the hood, but they're excluded from question listing APIs that are used by the pickers

### To Verify

1. Create a model
2. Create/open an existing dashboard
3. Go to editing mode and open the sidebar for adding questions ("pencil" icon > "add" / "plus" icon)
4. Ensure you can see your model in the list of questions. Click it, so it gets added to the dashboard
5. Click "Save" and make sure the model is displayed correctly
6. Create a new native query ("add" / "plus" icon in the main navbar > "SQL query")
7. Type `select * from {{#}}`
8. The tag editor sidebar should appear on the right. Click "Pick a saved question"
9. Ensure you can see your model in the list of questions. Click it and make sure the query has changed to `select * from {{ #MODEL_ID }}`
10. Run the query (CMD + Enter / click the "Run" button)
11. Ensure you see regular model data in the results

### Demo

<details>
<summary>Adding model to dashboard</summary>

https://user-images.githubusercontent.com/17258145/149953972-3912e36c-140d-413e-8fcf-d19186852d9d.mov

</details>

<details>
<summary>Using model in a native query</summary>

https://user-images.githubusercontent.com/17258145/149953995-da638381-3dbc-4546-8290-fe357741d4bc.mov

</details>

### CODE REVIEW

**Review by alxnddr — APPROVED** [review]
It looks and works well!

Should we say "Model" instead of "Question" here?
Tiny and unrelated bit only if it is easy to do right away — it would be great to center the text:
Screenshot 2022-01-18 at 17 06 16

**Comment by kulyk** [comment]
Good call @alxnddr 🙌  It also makes me wonder which copy should we use for listings like that. We used to say "Pick a question", but the options now include models too, so should we now say something like "Pick a question or a model" to be more accurate? 🤔 @mazameli what do you think?

**Comment by dpsutton** [comment]
Some options are using a more generic phrase:
- "Pick a starting source"
- "Pick a source"

**Review by mazameli — APPROVED** [review]
Nice!

**Pull request merged**
