### PR TITLE
MB_JETTY_HOST default value for Docker

### PR DESCRIPTION
**Pull request by joshuashort**
It seems like binding to `0.0.0.0` might be a better choice than binding to `$HOSTNAME`.. I found that I couldn't run Metabase on multiple Docker networks, and when I tried to switch networks the Metabase container needed to be restarted.

Binding to `0.0.0.0` seems to allow Docker networks to function appropriately. I've been able to work around this by specifying `MB_JETTY_HOST` in my compose file, but I don't see why this shouldn't be the default.

This came about when I was trying to use nginx to proxy to a Metabase container.

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by salsakran** [comment]
Thanks! I personally don't know enough to determine whether this is a good or bad idea. Anyone on  @metabase/core-developers feels like they do?

**Comment by senior** [comment]
This seems like a good change, binding to 0.0.0.0 binds to all network cards (and hostnames). Seems like a good default and users can still change it if they want to bind to a specific host (i.e. for SSL reasons or something similar)

**Review by senior — APPROVED** [review]
👍

**Comment by joshuashort** [comment]
Updated the comment line with a more accurate description -- from @senior's explanation

**Comment by salsakran** [comment]
Sweet, thanks @senior and @joshuashort !

**Pull request merged**
