### PR TITLE
Update outdated libs

### PR DESCRIPTION
**Pull request by ranquild**
- `fast-xml-parser@4.1.2`
- `lodash-es@4.17.21`
- `decode-uri-component@0.2.2`
- `tmpl@1.0.5`
- `trim@0.0.3`
- `ua-parser-js@0.7.23`
- `y18n@4.0.1`
- `qs@6.10.3`
- `unset-value@2.0.1`

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28533)

### CODE REVIEW

**Review by alxnddr — APPROVED** [review]
Should we backport this to 45 and release 45.4 (or 45.3.1)?

**Comment by nemanjaglumac** [comment]
`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.`

**Comment by nemanjaglumac** [comment]
@alxnddr We have `Snyk` vulnerability scanning enabled in Docker.
No vulnerabilities have been found in `x.45.3`

**Comment by alxnddr** [comment]
> `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.`
> 
> @ranquild what was the process for updating these dependencies? We had to use `resolutions` previously. Now there's only `yarn.lock` alone.

seems like he removed outdated entries from yarn lock and then reran `yarn` which is valid

**Comment by ranquild** [comment]
@nemanjaglumac when dependabot fixes issues it also updates `yarn.lock` only

**Comment by alxnddr** [comment]
> @alxnddr We have `Snyk` vulnerability scanning enabled in Docker. No vulnerabilities have been found in `x.45.3`

I asked that because of [this](https://metaboat.slack.com/archives/C97M2U8M6/p1677076336856519?thread_ts=1676044024.318969&cid=C97M2U8M6)

**Review by dragonsahead — APPROVED** [review]
🚀🚀🚀

**Pull request merged**
