### PR TITLE
Add insights for number vs. number queries

### PR DESCRIPTION
**Pull request by sbelak**
Returns linear trendline, best fit trendline, and correlation coefficient using the same format as timeseries insights.

There are some presentation questions though. Should we continue using the term trendline, or the more precise "best fit line". What you are often interested in when looking at number vs. number is correlation. How should we display it? Does it get added with the trendline or is it a separate setting? 

Also while the settings pick up the presence of a trendline it does not get rendered.

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
A test would be nice but besides that LGTM

**Comment by mazameli** [comment]
Here's what I'm thinking for options and presentation:

New toggle added to scatterplot display options. These should appear when the x-axis is numeric, and I assume only when there is a single variable on the y-axis?

best_fit_off

Line of best fit toggled on:

best fit on

Hovering on the best fit line could show the correlation coefficient:

hover

**Comment by sbelak** [comment]
I like this, can we slot the FE work into 35?

**Comment by rlotun** [comment]
closing due to age.

**Pull request closed without merging**
