### PR TITLE
we had unlimited xrays since 2018 and it is time to end this madness

### LINKED ISSUE #43258: Generating an x-ray on a line chart on big tables will generate a massive x-ray that will lock up the browser
### Describe the bug

A customer has a very big table, which they use to generate a simple line chart. They found that when they use an x-ray on a data point the x-ray generated is massive

### To Reproduce

1) set up Metabase with a postgres db
2) load this massive dataset https://drive.google.com/file/d/1rbp2or3Kdoc6Fy-9j1m2HCA4NvOEa2A9/view?usp=sharing
3) do a very simple question like
image

4) then click on any data point ->automatic insights- >x-rays
image

you'll get an ultra massive dashboard that locks up the browser and probably the server as well

### Expected behavior

we need product on this

### Logs

NA

### Information about your Metabase installation

```JSON
since the very beginning
```

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by sansolovyov**
Fixes #43258

Back in 2018, we've [set `:show` to be `:all`](https://github.com/metabase/metabase/commit/77500ca6e9fa7df55e3a439fa5fc05411665cba3) for x-ray dashboard, and so our card limit was not respected. We've agreed to limit this to 30 cards per x-ray dashboard.

I'm having hard time to understand what to test, since this seems more like a configuration (and this option is supplied all over the tests, so it's tested well), rather than a behavior change.

### CODE REVIEW

**Review by crisptrutski — APPROVED** [review]

**Comment by paoliniluis** [comment]
I would love this to be discussed with one of our customers who're really keen on using x-rays cc @ignacio-mb

**Comment by luizarakaki** [comment]
@paoliniluis what would be discussed, we don't recommend and don't support dashboards with more than 30 cards. X-rays are a best-effort type of thing. If we want to support x-raying huge tables, we can do it, but it would be a feature request.

**Comment by kamilmielnik** [comment]
> I'm having hard time to understand what to test

@piranha Please add a test reproducing the issue this PR fixes, i.e. a test which verifies that huge, multi-card dashboards won't be generated anymore.

**Comment by piranha** [comment]
@kamilmielnik this makes sense at the first glance, but the problem is that all tests right now pass this option explicitly - so it's tests quite thoroughly, but was an override at the top. And writing a big test just to test that override is no longer there?.. Feels excessive.

**Comment by kamilmielnik** [comment]
@piranha we need a test to ensure the issue won't come back in the future. It should probably be an e2e test.

**Comment by paoliniluis** [comment]
@luizarakaki I would just ask what are their expectations. I agree 100% with you, but just want to know what they're expecting from this feature

**Pull request merged**
