### PR TITLE
Automagic dashboards improvements 

### PR DESCRIPTION
**Pull request by sbelak**
Follow-up to #7048

Backend TODO:

- [ ] load yaml in a safe manner
- [x] if inferring filters to show, only use those that apply to all cards.
- [ ] limit number of filters
- [x] field analysis
- [ ] overloadable field and metric analysis
- [ ] coloring

Frontend TODO:

- [ ] fix parameters
- [ ] drill throughs

### CODE REVIEW

**Comment by salsakran** [comment]
Can we also limit the number of filters added? Anything that ends up spanning more than a single row is unsightly, imo

**Comment by mazameli** [comment]
If I mark a field as `do not include` in the data model, we're still trying to break out by it, but the card displays with an error.

screen shot 2018-03-15 at 11 34 14 am

**Comment by salsakran** [comment]
If there are a lot of tables in a DB, `/ready` doesn't render properly



screen shot 2018-03-15 at 12 10 37 pm

**Comment by salsakran** [comment]
merging this, and copying incomplete tasks to #7136

**Pull request merged**
