### PR TITLE
MetaBot tweaks for multiple instances

### PR DESCRIPTION
**Pull request by camsaul**
tweaks to make sure only one Metabase instance runs MetaBot at a time, and for other instances to "assume the role" when needed

### CODE REVIEW

**Review by senior — COMMENTED** [review]
If I'm reading the code correctly and have the various levels of caching in my head, I have a concern about the leader election code as it is. These things are really tough to diagnose and troubleshoot and are generally way more likely to happen than it seems in distributed systems. Let me know if I'm misundestanding your algorithm, but here's an example of a bad scenario.

We have three MB instances: M1, M2, M3. M1 is the metabot, M2 and M3 are not but are still checking, someone unplugs M1.

Now let's say that we're unlucky enough that M2 and M3 are checking settings at the same time. Both check the last update time (we're past 2 minutes) both update themselves as the metabot by updating their instance id. M2 first, then M3. M2 and M3 now both have a cached `am-i-metabot?` boolean. They both update the last checkin, basically the same time but M3 was last.

We now have M2 and M3 as metabot for a minute, then M2 gets the settings cache invalidation signal and will update, realizing it's no longer the metabot. Again the timers are aligned so at the second minute M2 checks last update. 2 minutes have gone by, M3 updates it's last update time (M2 hasn't seen it yet) and now we're back to M2 and M3 both being metabot for a minute. This time M3 has it's cache invalidated after a minute and we have the issue again.

I think having two metabots for a minute isn't ideal, but it isn't really that bad either. What I think is a bigger deal is that we could be in a situation where it would repeatedly happen and we'd have 2 metabots every even minute and 1 metabot every odd minute.

**Comment by camsaul** [comment]
@senior your point about multiple simultaneous MetaBots is a good one, I went ahead and changed the timeout from 2 minutes to 3 which should fix the issue by giving M2 enough time to realize for sure it's definitely no longer the MetaBot (via Settings cache invalidation) and stop trying to become it. Either way if we have 2 MetaBots for a minute or too I'm not concerned about that as long as they sort themselves out after that.

**Comment by salsakran** [comment]
Would adding a bit of jitter in where on the minute a given nodes updates settings reduce the probability further?

Eg have the node check every minute on the `uuid()%60` second mark rather than at the top of the minute?

**Comment by camsaul** [comment]
@salsakran Now that I bumped the timeout up to 3 minutes I think the probability is basically zero so not sure a few seconds of jitter would really make a huge difference anyway

**Comment by salsakran** [comment]
think the jitter would reduce the chance of an initial class

**Comment by camsaul** [comment]
ok. should be less of a chance of an initial class now (?). Added some MetaJitter to the MetaBot.

**Pull request merged**
