### PR TITLE
Fix login redirect

### LINKED ISSUE #2971: login doesn't redirect to original location
If someone sends me a link to something like `https://metabase.my-website.com/dash/22` and I'm not logged in, clicking the link will take me to the login page. After I log in it takes me to the activity feed instead of redirecting to `/dash/22` as I would expect.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #2971

### CODE REVIEW

**Comment by salsakran** [comment]
is there a way to test this?

**Comment by tlrobinson** [comment]
I think it would be best tested as an end-to-end test. I can give that a try using #3091 but it won't be run on CI yet

**Comment by salsakran** [comment]
cool. that makes sense.

**Comment by tlrobinson** [comment]
@salsakran I've merged the e2e branch into this one and wrote a test: https://github.com/metabase/metabase/pull/3137/files#diff-18c54606df51c9088ba2c2dfacb87e45R50

**Comment by salsakran** [comment]
@tlrobinson I'm a 👍  if this is ready to merge.

**Comment by tlrobinson** [comment]
@salsakran  I'm thinking we should get this fix in 0.20 but not sure if we're going to merge the e2e stuff yet, so I can open a separate PR with the fix but not the test stuff. Does that sound ok?

**Comment by salsakran** [comment]
let's merge the e2e branch? Is there any reason not to?

**Comment by tlrobinson** [comment]
Superseded by #3476

**Pull request closed without merging**
