### PR TITLE
Repro for #12899

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### What does this PR accomplish?
- reproduces the issue #12899 
- checks for the existence of section `Custom Expression` within Custom question > Orders Popover

### Where should the reviewer start?
1. `yarn test-cypress-open`
2. click on `/scenarios/question/new.cy.specs.js`

### How should this be manually tested?
- go to `/`
- Ask a question > Custom Question > Sample Dataset > Orders > Summarize > Pick the metric you want to see
- Popover should contain `Custom Expression` section

### Screenshots
N/A

### Notes/Questions
- I was using `cy.visit("/question/new?database=1&table=2&mode=notebook");` to go directly to orders, as per [this](https://github.com/metabase/metabase/wiki/E2E-Tests-with-Cypress#increase-viewport-size-to-avoid-scrolling) recommendation.
    - navigating like this opens the page with closed "Filter, Summarize, Join Data..."
- manual navigation to the same page, on the other hand, shows `Filter` and `Summarize` expanded by default
- my guess is that this is desired behaviour; documenting it just in case...
- test should pass when the underlying issue is solved

### CODE REVIEW

**Comment by salsakran** [comment]
@nemanjaglumac thanks for putting this together!

**Comment by salsakran** [comment]
@paulrosenzweig mind taking a look and merging if it looks good?

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac thanks for putting this together!

@salsakran you're welcome. I'm glad I was able to help.

**Review by paulrosenzweig — APPROVED** [review]
I'd skip the test for now and add `(Issue #12899)`. Once the test passes, I'm 👍 to merge!

I think it's probably worth expanding this test to actually use the custom expression option rather than just checking it's present. That's a tricky test to write when the feature is broken though, so it shouldn't be part of this PR.

**Comment by nemanjaglumac** [comment]
@paulrosenzweig - I was actually thinking about the option to include both "Basic Metrics" and "Custom Expression" in a `const METRICS = [...]` and to test for each case. However, hard coding it probably wouldn't be a good idea. There's probably an option to get that data from the store (in @flamber 's screenshot there's also "Common Metrics").

Anyway, I'll update the test with your suggestions. Thanks.

**Pull request merged**
