### PR TITLE
Release Without Github

### PR DESCRIPTION
**Pull request by iethree**
### Description

Allows us to release to s3 and dockerhub if github goes down completely.

Screen Shot 2023-11-17 at 5 18 26 PM

### CODE REVIEW

**Comment by paoliniluis** [comment]
Love it, we can even dockerize this so we ensure absolute immutability and anyone can release with the correct credentials

**Comment by iethree** [comment]
@iethree Thanks for your contribution! ❤️  We'll try to review it as soon as we can.


  Reviewers, make sure to check out our [External PR Review Guide](https://www.notion.so/metabase/Third-Party-PRs-External-contributions-5954061854424c1ea6391d98746646e0) when reviewing.

**Comment by iethree** [comment]
@iethree Thanks for your contribution! ❤️  We'll try to review it as soon as we can.


  Reviewers, make sure to check out our [External PR Review Guide](https://www.notion.so/metabase/Third-Party-PRs-External-contributions-5954061854424c1ea6391d98746646e0) when reviewing.

**Review by perivamsi — APPROVED** [review]

**Review by nemanjaglumac — APPROVED** [review]
Elegant! <3

**Pull request merged**
