### PR TITLE
Add snowplow tracking

### PR DESCRIPTION
**Pull request by ranquild**
Epic https://github.com/metabase/metabase/issues/18291

This PR adds snowplow tracking in a similar way to google analytics. This means that:
- Snowplow tracker is only enabled when the user has enabled anonymous tracking
- It tracks only existing pageview events
- `CSP` header allows requests to `sp.metabase.com` only when anonymous tracking is enabled

How to test:
- Change `isProduction` to true
- Open the home page
- Navigate to other page
- Check that a request to `sp.metabase.com` has been fired, it contains data, and it is successful

### CODE REVIEW

**Comment by ranquild** [comment]
@alxnddr It may seem like a lot of changes, but actually it's just `analytics.js` + renaming from `trackEvent` to `trackStructEvent`

**Comment by ranquild** [comment]
> Should it work in dev mode? I am getting 404 Screen Shot 2021-10-13 at 00 26 50

Should be no longer an issue

**Review by alxnddr — APPROVED** [review]
🚀

**Comment by ranquild** [comment]
@metabase-bot backport release-x.41.x

**Pull request merged**
