### PR TITLE
split up webpack config based on env [WIP]

### PR DESCRIPTION
**Pull request by kdoh**
While working on #6242 I started to get a little annoyed by our one massive webpack config file. Proposing we do [what they recommend in the guide](https://webpack.js.org/guides/production/) and split up our config so that it's a little clearer to understand what config modifications apply in what environments.

I think this might also help us feel more comfortable tweaking the config for dev to help speed things up because it'll help us know we're not accidentally busting things in the prod build, etc.

Wanted to get this up even though it's not finished so that I could get feedback from @attekei and others on the idea so that I don't bother finishing migrating this if we don't like the concept.

Questions:
- Do we like this?
- If we like it, how do we want to handle 'dev'? I'm pretty sure most of us consider the hot env "dev" these days so is it worth having a `webpack.hot.js` or just continue calling it 'dev'

ToDos
- [ ] get feedback on the approach
- [ ] finish splitting up the config

### CODE REVIEW

**Comment by attekei** [comment]
Makes sense, hopefully lets us to get rid of those `if (NODE_ENV !== "production") { ... }` conditions which make the current webpack config files hard to read. `webpack.dev.js` works for me!

**Comment by kdoh** [comment]
@attekei Yeah that's exactly the idea. Cool in that case I'll try and make a little progress on this this week. Do you have any preferences on the question I had around whether we should just make "hot" the default dev env? My preference would be yes.

**Comment by attekei** [comment]
I think we could. Currently `yarn run build-hot` works also on Windows (I confirmed that a few weeks ago) so I think that it should be the default for development if I understood your question correctly.

**Comment by kdoh** [comment]
Closing this for now since I haven't had time to work on it in a while and it's fairly low priority.

**Pull request closed without merging**
