### PR TITLE
13455 column order after removal

### LINKED ISSUE #13455: Changing column order/visibility via visualization Settings sidebar is inconsistent
**Describe the bug**
When using the visualization Settings sidebar to reorder column and removing columns, causes some inconsistency. Reordering works, but removing columns will reset the order. And every change will show Play-button instead of just doing the change.

**To Reproduce**
1. Custom question > Sample Dataset > Orders - join table Products
image
2. Click visualization Settings sidebar > drag "Product -> Category" column to beginning of table - it actually moves the column, when looking underneath the overlay, but still shows Play-button (the old "Get answers"):
image
3. Click the Play-button and now remove the column "Subtotal", which will then seem to do it correctly underneath the overlay:
image
4. But after clicking the Play-button, then "Subtotal" is removed, but any column ordering has reverted to default:
image

**Information about your Metabase Installation:**
Metabase 0.35.4, 0.36.7, 0.37.0-rc2

**Additional context**
Related to #12395. And a little to #12044.
This is not a regression, but it's basically some of the same problems as #10466

### LINKED ISSUE #29140: removing the last column in a table visualization resets all columns
**Describe the bug**
When removing the last column from a table visualization, if the column is a joined column, then after removing it all columns will reappear.

**Logs**
```
[backend] 2023-03-10 12:13:56,016 WARN api.common :: Unexpected parameters at [:post "/"]: [:type :database :query :parameters]
[backend] Please add them to the schema or remove them from the API client
[backend] 2023-03-10 12:13:56,100 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 84.1 ms (25 DB calls) App DB connections: 1/4 Jetty threads: 4/50 (1 idle, 0 queued) (86 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/2 (0 threads blocked)
```

**To Reproduce**
1. Open a table visualization (from model, table, or question).
2. Add a joined column (can do this from visualization settings sidebar).
3. Remove all other columns (click eye icon in sidebar), then remove the joined column.
4. All original columns from the table will reappear in the visualization.

**Expected behavior**
Columns should not reappear, table should be empty.

**Screenshots/videos**

https://user-images.githubusercontent.com/37751258/224420162-341980c7-df8d-42e4-b0ce-21c8b1772e5c.mov

**Information about your Metabase Installation:**
`master` branch commit `b2a822cb2b`

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.6+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.6+10",
    "os.name": "Mac OS X",
    "os.version": "13.0",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-03-08",
      "src_hash": "5b2936dc350df411dc567059489c9ff8ef59f0f3",
      "tag": "v0.46.0-SNAPSHOT",
      "branch": "master",
      "hash": "4e30153"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Minor annoyance, not very severe.

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/13455

### Description
2 main adjusts here is:
- `table.columns` is valid check only cares about enabled columns now. This makes sense as disabled columns won't come back in `data.cols`
- Another adjustment to `ChartSettingOrderedColumns` to apply original indexes *before* filtering out any settings that don't have a matching column.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> Orders + Products
2. Move Products -> Category up above Total
3. Hide Total
4. Products -> Category should still be in it's original position

### Demo
chrome_hlGp7z8Y1x

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by npfitz** [comment]
It looks like this also closes #29140 as it had the same `isValid` check returning false to revert back to default situation. I'll put a 
e2e test together for it as well

**Review by iethree — CHANGES_REQUESTED** [review]
So this seems to fix the case where it resets column position, but when it's preserved, reordering it further seems to not work properly

demo:

https://www.loom.com/share/52a8eb2885964a2a8096640a200c8bf5

**Comment by npfitz** [comment]
Oh geez... yeah, all my work was in the sidebar component, not the table header. I'll need to see if I can apply the same changes there

**Review by iethree — APPROVED** [review]
❤️‍🔥

**Pull request merged**
