### PR TITLE
add withUndos option to renderWithProviders to render Undos during …

### PR DESCRIPTION
**Pull request by npretto**
### Description

This will allow us to test toast/undos easily in jest tests.

I added it behind a flag to not render the component when we don't need it, even though it's a small component we have a lot of tests

### How to verify

[This test](https://github.com/metabase/metabase/pull/41575/files#diff-bfaa39e7d0397935ebf6b7a70dad5261af7438cd0a8e2ec185094e537f4e05efR211-R213) in a PR with this code should pass

### CODE REVIEW

**Review by WiNloSt — COMMENTED** [review]
I like the approach, but I just have a thought that maybe we should not do anything more with `undos` until we extract `toast`/`notification` out of `undos`. Now in a lot of E2E tests, we call `undoToast()` while what we're actually testing is testing the toast notification.

I mean it is technically correct since we `dispatch(addUndo(xxx))` when we want to show the notification. It just feels wrong extending this notion of `undo`s that mostly are toast notifications.

In a perfect world, I'd expect `toast` or `notification` or whatever we're gonna call it behave similar to undo, but doesn't allow the ability to undo things since that's not what it's made for.

**Review by iethree — APPROVED** [review]

**Comment by npretto** [comment]
@iethree since you approved, would you be ok with the change from `withUndos` to `withNotifications` as suggested above?

**Comment by iethree** [comment]
> @iethree since you approved, would you be ok with the change from `withUndos` to `withNotifications` as suggested above?

either one sounds fine to me. either way we'll want to make some changes when we make notifications more sane down the road (https://github.com/metabase/metabase/issues/38832)

**Comment by npretto** [comment]
I'll leave it with the current name then just to make sure I'm not adding an abstraction which can be wrong soon, we can decide when we do that change if we want to merge the two into one flag or not (it will probably depend if we plan on migrating everything or not, and how)

**Pull request merged**
