### PR TITLE
Bump jsrsasign package version

### PR DESCRIPTION
**Pull request by dragonsahead**
Bumping package version

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]

**Comment by ariya** [comment]
@paoliniluis probably need to rebase it against the latest master, to fix the test failures.

**Comment by paoliniluis** [comment]
I think this (https://github.com/kjur/jsrsasign/commit/f28fe3b1803b1d684c1badef4577b77eab9d96ff) is the method for the signatures, which is 5 years old. I know that you were worried about the systemic impact of this bump @ariya (which I fully agree).

**Comment by ariya** [comment]
@paulrosenzweig Can you elaborate on the easiest way to verify this? That way, we know how to do it again next time we need to bump the version.

**Comment by paulrosenzweig** [comment]
@ariya currently, we only use jsrsasign to generate embed tokens. That token is used in the embed preview iframe src. When I tested this I just made sure that preview loaded.

Also, I did see [a test](https://github.com/metabase/metabase/blob/6987567cf6c64e3d1863cf150d026c908ab65525/frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js#L657) that should cover this too.

For any future readers though, it's probably worth checking again that there aren't more uses of jsrsasign. Right now I have a [PR that's on hold](https://github.com/metabase/metabase/pull/15584) which would add another use.

**Comment by ukritw** [comment]
@paoliniluis @ariya 
A [PR for snowplow in-product tracking](https://github.com/metabase/metabase/pull/15584) was put on hold because of this. 
Unfortunately, I don't fully understand the technical reasons behind it but is there any concern to merge the PR as is?

**Comment by paoliniluis** [comment]
Just checked Paul's comment: when I did this PR we were concerned that the bump in the version would do something weird on the embedding but did not happen (as the main function which generates the token was not changed). In the case of Snowplow I would just test that it works if it does, then we don't need to to do anything else. I believe that Paul forgot to merge the PR after I merged this one (I merged on May 10 and Paul made the comment on the Star Wars day)

**Pull request merged**
