### PR TITLE
Add recent views list

### PR DESCRIPTION
**Pull request by alxnddr**
Continuing Kyle's work https://github.com/metabase/metabase/pull/16324

This PR adds showing Recently Viewed items list when users click on search bar:
Screen Shot 2021-08-24 at 23 28 21

In this PR I also addressed comments provided by @daltojohnso and @mazameli in the original PR.

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Review by gusaiani — COMMENTED** [review]
I couldn't really see a "recent viewed list" in my search xD

Any tips?

Some inlined comments.

**Review by gusaiani — APPROVED** [review]
Pretty awesome. CLJ Linter, counting on it being trivial :)

**Review by dpsutton — APPROVED** [review]

**Review by kdoh — APPROVED** [review]
Looks good to me! Thanks for helping get this across the finish line.

**Pull request merged**
