### PR TITLE
Add RTK to the project, configure the store

### PR DESCRIPTION
**Pull request by alxnddr**
Epic: https://github.com/metabase/metabase/issues/29637

## Description

Initial setup of our store with Redux Toolkit.
The state mutation check is disabled for now, I will enable it in the next PRs. The serializable check will require decent refactoring in our app because it stores non-serializable values in some areas.

## How to verify

- Check the app runs
- CI is green
- Redux dev tools work

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27695)

### CODE REVIEW

**Review by EmmadUsmani — COMMENTED** [review]
@alxnddr We still have one import `from "redux"` in `reducers-public.js`, can you update it?

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/27695#-:-NRiLQAj5zFG0tymBJlo:b-f3p0do)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ranquild)

**Comment by alxnddr** [comment]
@EmmadUsmani good catch, thanks! I replaced it

**Review by EmmadUsmani — APPROVED** [review]
Looks good!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/27695#-:-NRiPVb572md_VnFXgz5:b-vs1prh)* status: all files reviewed, 1 unresolved discussion (waiting on @alxnddr and @ranquild)

___
*[`package.json` line 91 at r1](https://reviewable.io/reviews/metabase/metabase/27695#-NRiPQVJ0t-mG43atcmp:-NRiPQVJ0t-mG43atcmq:b44uc2) ([raw file](https://github.com/metabase/metabase/blob/eef5e440ced3fb80d854a13bc02d598b8ac633e5/package.json#L91)):*
> ```JSON
>     "react-use": "^17.4.0",
>     "react-virtualized": "^9.22.3",
>     "redux": "^4.2.0",
> ```

🎉

**Review by alxnddr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/27695)* status: all files reviewed, 1 unresolved discussion (waiting on @EmmadUsmani and @ranquild)

___
*[`package.json` line 91 at r1](https://reviewable.io/reviews/metabase/metabase/27695#-NRiPQVJ0t-mG43atcmp:-NRj05Ki6gqDUsMyjHfL:b-896fix) ([raw file](https://github.com/metabase/metabase/blob/eef5e440ced3fb80d854a13bc02d598b8ac633e5/package.json#L91)):*
<details><summary><i>Previously, EmmadUsmani (Emmad Usmani) wrote…</i></summary><blockquote>

🎉
</blockquote></details>

Done.

**Pull request merged**
