### PR TITLE
Public cards and dashboards [OLD PR]

### LINKED ISSUE #3680: Provide a public sharable link for a question
As per designs in #2683, allow a user to share a given card to users without a Metabase login.

This should have an instance wide admin toggle, and should use a generated, secure UUID for the public facing link

### PR DESCRIPTION
**Pull request by camsaul**
Wow! Progress on this is moving faster than Charlie Sheen can say winning after 3 lines of coke.

The only thing left here is all the frontend stuff :joy:

WIP. Resolves #3680 and #3681

### TODO Backend:

* [ ] `/api/card/:id` should return the uuid, if any is set.
  * proposal: `public_uuid`
* [ ] need a way to get the card data
  * proposal: `GET /api/public/card/:uuid` (should probably return minimum necessary info, only `display`, `name`, `visualization_settings` are necessary)
* [ ] rename `POST /api/public/card/:uuid` to `POST /api/public/card/:uuid/query` for consistency with non-public API
* [x] need public csv and json endpoints (cards only, not dashboard, I assume)
  * ideally these would be the same as the public card URLs (not the API endpoints) but with the filename extension, e.x. `/share/card/:uuid.csv` (not sure if we've come up with a URL structure yet)

### TODO Frontend:

* [x] add `enable-public-sharing` setting to frontend
* [x] share widget on dashboards
* [x] share widget on query builder
* [ ] pick URL format
  * `/share/question/:uuid`
  * `/share/question/:uuid.csv`
  * `/share/question/:uuid.json`
  * `/share/dashboard/:uuid`
* [ ] public question page
* [ ] public dashboard page
* [ ] make public pages lightweight by moving to separate webpack entrypoint

### New setting: 

*  `enable-public-sharing`
    This is returned as part of the public settings info; must be enabled to create or execute public Cards & Dashboards

### New endpoints:

*  `POST /api/card/:id/public_link`
    Create a public link for a Card. Must be admin and public sharing must be enabled. Returns UUID
*  `DELETE /api/card/:id/public_link`
    Unshare a public Card. Must be admin.
*  `POST /api/dashboard/:id/public_link`
    Create a public link for a Dashboard. Must be admin and public sharing must be enabled. Returns UUID
*  `DELETE /api/dashboard/:id/public_link`
    Unshare a public Dashboard. Must be admin.
*  `POST /api/public/card/:uuid` 
    Fetch the results for a publically shared Card. Does not require auth credentials. Public sharing must be enabled. Optional accepts *URL* params `parameters` and `format`, which may be either `json` or `csv`.
*   `GET /api/public/dashboard/:uuid`
    Fetch a publically shared Dashboard. Does not require auth credentials. Public sharing must be enabled. This includes information about the Cards belonging to this Dashboard, but not their results; fetch those asynchronously using the endpoint below.
*   `GET /api/public/dashboard/:uuid/card/:card-id`
    Fetch the results for a Card in publically shared Dashboard. Optionally accepts *URL* param `parameters`. Does not require auth credentials. Public sharing must be enabled. This is intended for use in asynchronously populating the Cards of a Dashboard once it has been fetched.

Updated auto-generated API dox are also available [here](https://github.com/metabase/metabase/blob/public-cards-and-dashboards/docs/api-documentation.md).

I think these should cover everything but please let me know if anything needs tweaks.

### CODE REVIEW

**Comment by camsaul** [comment]
Ok so the endpoint for fetching a public Card is all done, only thing left to do is endpoint for a public Dashboard and then tests & cleanup. I think at this point someone can probably get started on frontend stuff ⭐️

**Comment by camsaul** [comment]
Ok Dashboard endpoints are live too, backend stuff is all finished minus cleanup and tests.

**Comment by camsaul** [comment]
Ok, backend is all finished including 36 new tests. Let me know what tweaks you guys want if any.

**Comment by salsakran** [comment]
Overall, looks 👍 
One thing that occurs to me is that we'll probably want to be able to GET a public link for a given card or dashboard. It seems strange to have to POST an id in that situation. Eg, how do we know if a given card/dashboard has a public url?

**Comment by tlrobinson** [comment]
I think it makes sense to use `POST` for creating the public link, but once it's created I assume we want to see it immediately any time someone opens the public link widget, so it would be easiest if the UUID were returned in the `GET /api/card/:id` and `GET /api/dash/:id` responses.

**Comment by tlrobinson** [comment]
@camsaul I added some TODOs with tweaks needed. let me know if you have any questions

**Comment by camsaul** [comment]
The `POST` endpoint will just return the existing UUID if you call it again so my thinking was that whenever the widget was opened hit the endpoint and use it to populate the text fields. I didn't see any designs for indicating that a Card or Dashboard is shared but if we want to show that I can make some tweaks.

**Comment by camsaul** [comment]
@tlrobinson for JSON and CSV just specify the `?format=` param, the API isn't set up to work with extensions in the URLs

**Comment by camsaul** [comment]
Oops I totally broke this PR so I'm going to go ahead and close it now.

Closing in favor of #4123

**Pull request closed without merging**
