### PR TITLE
Improvements to E2E testing workflow

### PR DESCRIPTION
**Pull request by attekei**
The results of my weekend experiments:

- I found it distracting that every time I run new E2E tests, a new browser is created (and destroyed if the test was successful). The new `yarn run test-e2e-dev` creates a browser session that is reused for each new test run, making the development experience more pleasant.

- Finding good CSS selectors for tests E2E has been strenuous. I created a modified version of https://github.com/zalando/ui-automation-chrome-extension that is included to the browser session when you run `yarn run test-e2e-dev`. It lets you see the optimal CSS selectors of clicked items. Including it in the test browser session lets you write your tests incrementally: after you've written a part of the test, you can rerun it, and continue picking the CSS selectors where the test was left for subsequent test interactions 

Probably this won't be merged as is but at least is a good starting point for discussing how could we improve our conventions/workflow of frontend testing.

### CODE REVIEW

**Comment by attekei** [comment]
Additional ideas regarding E2E tests / frontend testing in general:

 * Currently individual tests are long and monolithic, and at least for me it's hard to decipher by just looking at code what is happening there. Maybe partitioning them to multiple steps would be useful for self-documentary purposes. Additionally, step-by-step execution of those steps could be possible if it is considered useful.

* We briefly talked with @kdoh whether we want to prioritize E2E tests in advance because their heaviness and fragility, and do more snapshot testing with Jest. I don't have a strong opinion on this, and last weekend I focused solely on E2E just because it was something I could study in two days :-)

**Comment by attekei** [comment]
Also defining which test to run from command line would be convenient because I consistently forget to remove `frescribe` and `fit` blocks from commits.

**Review by tlrobinson — APPROVED** [review]
Seems to work well.

Eventually it would be great if we could figure out how to automatically reset the database to the required state when running a persistent server (i.e. using `E2E_PORT`), and maybe automatically start the persistent server.

**Review by kdoh — APPROVED** [review]
Looks good. Would be nice to add some documentation about the process as well.

**Comment by attekei** [comment]
Added simple instructions to developer's guide. Merging now to master.

**Pull request merged**
