### PR TITLE
Add Slovak and update translations for 0.33.5

### LINKED ISSUE #11177: Add Slovak translation
Slovak has gotten to [100% translated](https://poeditor.com/projects/view?order=trans_desc&id=200535), so this is a reminder to myself to create a PR to add it in.

### PR DESCRIPTION
**Pull request by mazameli**
Adds Slovak and updates all our already-included languages. 

Fixes #11177

### CODE REVIEW

**Comment by camsaul** [comment]
before we merge this we should run it against the new i18n validation step we added to `master`. Just pushed a commit to add it to `release-0.33.x` as well

**Comment by mazameli** [comment]
Nice, I didn't know we added that to master. 👌

**Comment by camsaul** [comment]
Ok we have to go in and fix some of these files 

```
locales/it.po:13078: 'msgid' and 'msgstr' entries do not both end with '\n'
locales/it.po:13115: 'msgid' and 'msgstr' entries do not both end with '\n'
```

It's really fussy and doesn't like if people add newlines to translations of strings that didn't have them 🤷‍♂ 

You can run this command 

```
./bin/i18n/build-translation-resources
```

locally to get a faster feedback loop.

We added this to CI because otherwise when we want to do a release I have to spend 20 minutes fixing all the translation files first which is annoying, better to do them before the last second

**Comment by mazameli** [comment]
Rad

**Comment by mazameli** [comment]
K, I pushed a commit to fix that `it.po` file, @camsaul.

**Review by camsaul — DISMISSED** [review]
We should get this in once those files are fixed

**Comment by mazameli** [comment]
Not sure why the CI `verify-i18n-files` check is failing on this branch; `./bin/i18n/build-translation-resources` runs just fine locally without error. Looks like it's a problem with `gettext`? Any suggestions @camsaul?

**Review by tlrobinson — CHANGES_REQUESTED** [review]
Why does this PR modify `.circleci/config.yml `? That might be why it's failing. I'd `git checkout release-0.33.x -- .circleci/config.yml` (and commit that) and see if that fixes it.

**Comment by mazameli** [comment]
Cool, will do. I might've messed up when merging in upstream changes.

**Comment by mazameli** [comment]
That did the trick, Tom.

**Review by tlrobinson — APPROVED** [review]

**Pull request merged**
