### PR TITLE
Pass correct default colours to the static-viz waterfall chart

### LINKED ISSUE #20621: Static waterfall default colors are invalid
**Describe the bug**
Default colors of the static waterfall chart are invalid.

**To Reproduce**
1. Create a waterfall chart without explicitly specifying colors 
2. Add it on a dashboard and send a subscription

**Screenshots**
Screenshot 2022-02-18 at 11 44 25

**Information about your Metabase Installation:**

Latest `master`

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes #20621

The waterfall chart implementation in js already has default colours hardcoded, so instead of passing the wrong colors
from the backend, rely on the chart's colors.

### Before
Incorrect colours are used for static waterfall charts. This is because the list of colors [here](https://github.com/metabase/metabase/blob/047a336b6b489985f2ef8457acf479174cff4405/src/metabase/pulse/render/body.clj#L362-L366) in the backend is just hardcoded, and seems to be out of date compared to colours hard-coded as defaults in the [Waterfall chart static viz code ](https://github.com/metabase/metabase/blob/f6085da31e4649069a9cbff63d4fdc12f5f3ce4b/frontend/src/metabase/static-viz/components/CategoricalWaterfallChart/CategoricalWaterfallChart.jsx#L57-L64).

To find out where those colour values came from, I compared the static waterfall chart code to the [waterfall chart code we use on the frontend](https://github.com/metabase/metabase/blob/7f1b701aaa3c53dd38ae6a877b6ae666723bfa6f/frontend/src/metabase/visualizations/visualizations/WaterfallChart.jsx#L22-L53), and noticed that:

```
"waterfall.increase_color": { ... getDefault: () => color("accent1") ... }
"waterfall.decrease_color": { ... getDefault: () => color("accent3") ... }
"waterfall.total_color": { ... getDefault: () => color("text-dark") ... }
```

Those colors are defined [here](https://github.com/metabase/metabase/blob/9eaf9c9b8f41003e067c6598d76c6401547bc849/frontend/src/metabase/lib/colors/palette.ts).

Duplicating these colour values in multiple places seems like a bit of an issue, and may also be confusing when a user has altered the colour palette in the Admin panel (Appearance tab).

Since I don't know the best place to put these changes, and have a few open questions: 
 - should the backend always assume sane and correct defaults on the js side?
 - should the backend always look for colors in `public-settings`? and respect them, falling back to defaults if there's nothing there
 - where should we put the defaults? (frontend, backend, hardcoded in static viz components?)

Before having all of these answered, I think it might be useful to merge this PR, as it's a simple change and moves us past the bug, at least.

### After
Colours are correct for static waterfall charts:
image
(left is static-viz renders, right is the same card in the browsers)

Colors work when explicitly set in visualization settings:
image

Colors work when the palette is adjusted in 'Appearance' tab of the Admin Panel (Enterprise):
image

### CODE REVIEW

**Comment by WiNloSt** [comment]
> - should the backend always assume sane and correct defaults on the js side?

I believed so, since there are quite a lot of work on FE on generating colors already e.g. each accent from 1 to 7 has 2 extra variants, 1 lighter and 1 darker. Since these color are generated at run time, it isn't saved anywhere and for BE to duplicate these colors it needs to also duplicate the color logic https://github.com/metabase/metabase/blob/512d07d9cfca8faf709aac5ceab25769d0381564/frontend/src/metabase/lib/colors/palette.ts#L64-L80
> - should the backend always look for colors in public-settings? and respect them, falling back to defaults if there's nothing there

TBH, I'm not totally sure how colors work in the BE at the moment. Since `public-settings. application-colors` seem to only store changed colors, if BE need access to the whole color palette, it needs to have combine the color settings with the default, which I'm not sure if we should duplicate to the BE, or if it's even already duplicate

> - where should we put the defaults? (frontend, backend, hardcoded in static viz components?)

As I've explained that there are colors that are generated at runtime on FE, I thought the only sane place that should calculate the colors should be only FE, but @ranquild  would be a better person to answer that since he's worked on the new colors palette.

**Comment by WiNloSt** [comment]
Regardless of the comment above, the PR looks good to be merged as you've suggested.

**Review by alxnddr — COMMENTED** [review]
The defaults are correct now but when I explicitly change waterfall colors they are not being applied:

Screen Shot 2022-08-16 at 12 20 17 PM

Screen Shot 2022-08-16 at 12 20 25 PM

**Comment by alxnddr** [comment]
> Duplicating these colour values in multiple places seems like a bit of an issue, and may also be confusing when a user has altered the colour palette in the Admin panel (Appearance tab).

We cannot import these colors from the front-end code because they can be redefined by [Appearance settings](https://www.metabase.com/learn/embedding/brand) and these colors are stored on the BE side.

> should the backend always assume sane and correct defaults on the js side?
In the static viz javascript code plays the role of a thin rendering layer and some of defaults are in hands of the BE if it is defined somewhere in settings, etc, where the javascript code don't have the access to.

> should the backend always look for colors in public-settings? and respect them, falling back to defaults if there's nothing there
Yes, it is necessary to match non-static charts

> where should we put the defaults? (frontend, backend, hardcoded in static viz components?)
These defaults are based on the settings so the only way to have them is BE reading the settings and providing to the JS code

**Comment by adam-james-v** [comment]
This is superceded by work here: https://github.com/metabase/metabase/pull/24852

**Pull request closed without merging**
