### PR TITLE
Relax schema for columns returned by the DB

### PR DESCRIPTION
**Pull request by sbelak**
Squashes a schema error on sync for MS SQL.

### CODE REVIEW

**Comment by flamber** [comment]
@sbelak I remember seeing that a lot on some MSSQL, but it seems like it's also on SQLite.
Would this fix #10681 or only squash part of that issue?

**Comment by sbelak** [comment]
@flamber that's a different error point, but I'll add fix for that as well into this PR. Tnx for the heads-up

**Comment by sbelak** [comment]
Turns out it was different enough to warrant itss own PR: #11358

**Review by camsaul — APPROVED** [review]
WFM

would it be hard to write a test for this ?

**Pull request merged**
