### PR TITLE
Fix dashcard button regression

### LINKED ISSUE #3169: After upgrading to 0.19.2 the card buttons have disappeared from LineAreaBarChart
When editing a dashboard the "Add series" and "Remove" buttons have disappeared from the LineAreaBarChart cards.

This seems to be related to #3154 and the logic for LegendHeader.

*  I am using the Mozilla Firefox 47.0 browser.
*  My computer's OS is Ubuntu 14.04.4 LTS.
*  I'm running Metabase locally from the JAR and it is using the Postgres database.
*  My data is in a Postgres database.
*  My Metabase version is 0.19.2.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3169

### CODE REVIEW

**Comment by salsakran** [comment]
seems to fix #3169 for me.

is there anything this might effect that I should test?

**Comment by salsakran** [comment]
LooksGoodToMerge

**Comment by tlrobinson** [comment]
In the QB there should be no headers except for a card-level multiseries (i.e. 2nd breakout or multiple metrics)

In dashboards:

If it's not multiseries the top (and only) legend should just show the card title and link to the card.

If it's a dash-level multiseries the top (and only) legend should show each series with the colored dots, and link to each card.

If it's a card-level multiseries the top legend should show the card title and link to the card, the second legend should show each series (the 2nd breakout values or metric names) with the colored dots. The second legend shouldn't link anywhere.

**Comment by salsakran** [comment]
all those cases pass for me locally.

**Pull request merged**
