### PR TITLE
Hide drills for no-data users

### LINKED ISSUE #11914: Drill-through without data permission - should that be possible?
**Describe the bug**
Users without data permission and trying to drill-through a dashboard question, just sees a spinner and there's an error in the log.

**To Reproduce 1**
1. Create user with no-data permission, view-only collection.
2. Create a Simple question of Sample Dataset > Orders, and save to dashboard
3. Login with no-data user, access dashboard, try to drill-through the question (i.e. Quantity = 2)
4. Shows `Sorry, you don’t have permission to see that.` (frontend) / `You don't have permissions to do that.` (backend)
image

**To Reproduce 2**
1. Login as no-data user and go to the question created previously in Repro1.Step2
2. Try reordering the columns, or sorting one of the columns
3. Similar error as Repro1.Step4

**Information about your Metabase Installation:**
Tested 0.34.2 thru 0.41.2

**Additional context**
https://discourse.metabase.com/t/drilldown-option-without-data-permission/8708

I'm not sure if drill-through should even be possible, when user doesn't have data permission.
Tested 0.32.10 and in that version the drill-through are disabled, so something changed in 0.33+

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by kulyk**
Reproduces #11914, fixes #11914

No-data users could click on column headers and cells to trigger drills, but they just fail without data permissions. This PR is based on #20317 work and hides the drills

### To Verify

1. Create a nested query (e.g. in the top navbar "+ Add" > "Question" "Saved Questions" > pick any question > Save)
2. Sign in as a no-data user and open that question
3. Click on a table column header, a cell, and on any PK/FK cell. You shouldn't trigger any drills

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/152996934-fe3c15c6-4421-4e39-b626-6fe98bdf3fff.mp4

**After**

https://user-images.githubusercontent.com/17258145/152996947-a93c5907-17d7-4ebc-9d32-0419fa9ca795.mp4

### CODE REVIEW

**Review by daltojohnso — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
@kulyk please take a look at this video. Resizing columns is making a question dirty and it's possible to override the original question and to save a new one.
https://www.loom.com/share/28ead68b47414c4581693b8036d16263

**Review by flamber — APPROVED** [review]
This seems quite good, but I would probably not backport this (at least not yet).

Some minor things:

1. When I go to a Model based on SQL, then I see `This question is written in SQL.` with no-data, which is not even shown for full-data users:
image
2. When I hover points, then it shows mouse pointer (my screenshot tool does not capture my cursor)
image
3. It's still possible to drag-to-drill
image

**Comment by nemanjaglumac** [comment]
Now we're stuck a little.
Apparently, there was an issue created way before where we expected a `nodata` user to be able to resize columns:
https://github.com/metabase/metabase/issues/9772

And the repro for that is failing:
image

@flamber does it make sense for the `readonly` user to be able to resize columns? By doing so, they create a dirty state which leads to the prompt to save the question.

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac no-data users should not be able to put a question in dirty state. That's basically what this PR and the previous tries to avoid as much as possible. I'm fine with allowing the change column width and do whatever they want as long it doesn't cause dirty state with all the problems it entails.

Understood.
In that case I see two options to resolve this:
1. @kulyk should check if it's possible to prevent getting the question dirty but still let the `nodata` user resize columns or
2. @brunobergher could help us by approving to change the logic in #9772 and actually completely disable `nodata` user to resize columns (in which case, we should be explicit about it in the documentation and the user feedback)

Maybe there's some other solution, but I don't see it currently.

**Comment by brunobergher** [comment]
> @brunobergher could help us by approving to change the logic in https://github.com/metabase/metabase/issues/9772 and actually completely disable nodata user to resize columns

Well, I agree with @flamber in that

> I'm fine with allowing the change column width and do whatever they want as long it doesn't cause dirty state with all the problems it entails.

since this is about tweaking how to look at something, even if temporarily. I wouldn't want to remove that ability in order to prevent drill-downs. The actual solution would be to not allow that change to be saved.

**Comment by flamber** [comment]
Just reviving this again, since it seems like Models causes even more problems (I can create issue for it if you want it separate)

**Example 1**
1. Create a SQL and convert to Model
2. View the Model as Admin:
image
3. Login with no-data user and view the Model
image

----

**Example 2**
1. Create a question and convert to Model
2. Login with no-data user and view the Model
3. Try to order by one of the columns
image
4. Shows Run-overlay because there's a stacktrace within the response data - errors with ``` `database` is required for all queries whose type is not `internal`.```
image
<details><summary>Full stacktrace</summary>

```
2022-04-20 13:15:55,924 DEBUG middleware.log :: POST /api/dataset 400 4.3 ms (0 DB calls) 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "`database` is required for all queries whose type is not `internal`.",
   :data
   {:status-code 400,
    :query
    {:type "query",
     :database nil,
     :query {:source-table "card__789", :order-by [["desc" ["field" 103 nil]]]},
     :parameters [],
     :middleware {:js-int-to-string? true}}},
   :at [metabase.api.dataset$run_query_async invokeStatic "dataset.clj" 50]}],
 :trace
 [[metabase.api.dataset$run_query_async invokeStatic "dataset.clj" 50]
  [metabase.api.dataset$run_query_async doInvoke "dataset.clj" 41]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [metabase.api.dataset$fn__65331 invokeStatic "dataset.clj" 75]
  [metabase.api.dataset$fn__65331 invoke "dataset.clj" 71]
  [compojure.core$wrap_response$fn__32284 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__32268 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__32273 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 151]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__65391 invoke "auth.clj" 14]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32324 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 299]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [metabase.api.routes$fn__76516$fn__76519 invoke "routes.clj" 56]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__76661$fn__76662 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32324 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 299]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [metabase.server.routes$fn__76649$fn__76651 invoke "routes.clj" 41]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73644 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__73641 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__77130$fn__77131$fn__77132 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__77130$fn__77131 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__77130 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80483 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__55251 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__79638 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__79656 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__55275 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__80750 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__80766 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__34391 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__45744$fn__45745 invoke "session.clj" 262]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 243]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 235]
  [metabase.server.middleware.session$bind_current_user$fn__45744 invoke "session.clj" 261]
  [metabase.server.middleware.session$wrap_current_user_info$fn__45731 invoke "session.clj" 221]
  [metabase.server.middleware.session$wrap_session_id$fn__45717 invoke "session.clj" 167]
  [metabase.server.middleware.auth$wrap_api_key$fn__65399 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__80670 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__34374 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__34399 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__80712 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__34402 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80499 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__76903 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 388]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 633]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 380]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 386]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run "Thread.java" 829]],
 :cause "`database` is required for all queries whose type is not `internal`.",
 :data
 {:status-code 400,
  :query
  {:type "query",
   :database nil,
   :query {:source-table "card__789", :order-by [["desc" ["field" 103 nil]]]},
   :parameters [],
   :middleware {:js-int-to-string? true}}},
 :message "`database` is required for all queries whose type is not `internal`.",
 :query
 {:type "query",
  :database nil,
  :query {:source-table "card__789", :order-by [["desc" ["field" 103 nil]]]},
  :parameters [],
  :middleware {:js-int-to-string? true}}}
```

</details>

----

**Example 3**
1. Create a question and convert to Model
2. Create a question from the Model
3. Login with no-data user and view the question
4. Try to order by one of the columns
image
5. Shows typical `Sorry, you don’t have permission to see that.`
image
Backend log
```
2022-04-20 13:21:22,933 WARN middleware.log :: POST /api/dataset 403 2.6 ms (3 DB calls) 
"You don't have permissions to do that."
2022-04-20 13:21:23,096 WARN middleware.log :: GET /api/database/4/schemas 403 9.3 ms (3 DB calls) 
"You don't have permissions to do that."
```

**Comment by kulyk** [comment]
@flamber I'd appreciate another look at this PR in combo with:

* #21819
* #21823

The first one should get rid of the "This question is written in SQL" thing for native models. The second one will allow no-data users to change visualization type/settings locally (reorder/resize columns, change viz type and settings) without being able to save the changes. Please LMK if that fits your expectations

**Comment by flamber** [comment]
@kulyk This PR is better than current state, so I'm good with merging, then we can do followups, but please have a look in video, since I'm unsure if it is this PR or changes to navbar, but the permission error is hiding the navbar (which is really bad UX) and slightly offset permission error.

Note that allowing column resize means this this will **not** be fixing #16836, but it likely needs it's own PR.

https://user-images.githubusercontent.com/1447303/164719530-34e2c907-1644-4c09-94ec-4cf4e5844560.mp4

**Comment by kulyk** [comment]
> @kulyk This PR is better than current state, so I'm good with merging, then we can do followups, but please have a look in video, since I'm unsure if it is this PR or changes to navbar, but the permission error is hiding the navbar (which is really bad UX) and slightly offset permission error.
> 
> Note that allowing column resize means this this will **not** be fixing #16836, but it likely needs it's own PR.

@flamber oh right, that's caused by the navbar changes, I'll create another PR, thank you. I'll merge that one soon then, thanks!

**Comment by kulyk** [comment]
@flamber #21947 should fix the error UI thing

**Pull request merged**
