### PR TITLE
Gauge visualization

### LINKED ISSUE #2989: Gauge chart?
Could I ask for you to add, if possible a gauge chart option?

Gauge charts are quite useful especially when you know a limit and they are being used in many dashboard systems.

Eg. I have 400 used licenses out of 600 usable. 

I know you could work around with pie charts and others as well but cauge I believe is the best representation.

### LINKED ISSUE #4500: Progress vs Gauge Use cases
I was wondering if the implementation of a gauge visualisation is still on the roadmap? I get the impression that a progress visualisation is being pushed to fill this use case, but I believe the uses are quite different.

I see there have been a couple of issues raised around this topic, and I see that there has even been done some work around them (#3149) by @mazameli ? 

image

A gauge is, after a normal line chart, the most used visualisation type for the type of end-user I work with, and in 90% of the cases exactly like displayed in the image above!

Thanks for the update, and keep up the good work! Metabase is brilliant :-)

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #2989
Resolves #4500 

- [x] The `Done` and `Cancel` buttons in the viz settings modal are broken
- [x] I think the maximum diameter for a gauge should be 500px; any larger and it starts to look goofy
- [x] The labels for the start/end of ranges in the chart seem to be disappearing sooner than they need to: on a window set to 1440x880, if a gauge is in a dashcard, it needs to be 6w x 8h grid units before they appear.
- [x] I wish the indicator didn't reanimate when I open up the viz settings modal
- [x] I think the minimum dashcard size for gauges should be the same as for pie charts, 4x4, with the bottom padding the same, ~20px.
- [x] If the optional range labels don't fit, could those be put into a tooltip when hovering on the range? Seems like they're getting truncated frequently.
- [x] When adding a new range, the color its assigned should be the next unused color in the palette, starting from the beginning, rather than gray.
- [x] I shouldn't be able to delete a range if it's there's only one of them
- [x] Polish: the color palette swatch button should be the same height as the input boxes that they're next to.
- [x] Dont barf if range is missing min or max

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Can we see a screenshot?

**Comment by mnlbox** [comment]
@tlrobinson any news about this?

**Comment by MitchSaad** [comment]
Very keen to see this happen!

**Comment by tlrobinson** [comment]
Still a work in progress, but here's what we've got:

screenshot 2018-08-08 17 29 48

screenshot 2018-08-08 17 29 53

@mazameli It's probably ready for some additional design guidance.

**Comment by mnlbox** [comment]
@tlrobinson wooooooooooow I love it man. It's so beautiful :heart:

**Comment by mazameli** [comment]
So, some next steps. We still need to do some visual explorations on the chart itself (found some old ones @kdoh had done as well as my old file), but I think we can make some nice small improvements to behavior and settings:

1. I love that the chart defaults to three segments, but I think the color order is backwards. Red-yellow-green is more of an expected default IMO.
2. Our `constant` green/yellow/red color values should probably be selectable from the color palette so that you can choose those even in situations where the color palette has been changed.
3. I think it might be neat, but probably unnecessary, if the default max value was the next power of ten up from the scalar's value, and the other two segments were at the 1/3 points (so if the query result was 378, the ticks would be at 0, 333, 666, and 1,000). Not sure how that would work with negative values.

As for the settings themselves, this is my current best idea, which is probably not at all something we can do with the current visualization constraints, but feels really intuitive to me. Let's talk it through in person if you want, @tlrobinson.

screen shot 2018-08-16 at 5 21 58 pm

**Comment by lwqcz** [comment]
@mazameli great progress a really like that. What about to have default setting for all graphs in admin panel? Maybe like graph templates? And I have a question - how these gause graphs will work in case of overflow? I mean when configured maximum is 1000 and the result from question will get 1200? I would prefer to have option to configure behaviour when default configured range is breached, like the segment over 1000 will be that color... I and can also imagine that there could be color fade configured for given increment or so. But what me and other will love is even the first gauge feature iteration 😉

**Comment by tlrobinson** [comment]
1. That's fine with me. I guess I was thinking of a use case where larger numbers are bad. Like your factory is about to blow up or something.
2. Were you thinking we show both the accents and the success/warn/error colors, or remove the redundant (but slightly different) accents, or ...?
3. This might be a little tricky. At what point in the question creation flow would you want the default max setting be "fixed"? The way settings currently work is defaults are computed from the current state of the query, so if the scalar value changed then the max would change. However, we do have a way to mark settings defaults as persisted (`persistDefault`) when the question is saved, so if it's ok that it's "fixed" on save then it should be easy. The one weird thing is if you bookmarked an ad-hoc question the max would automatically update to always be 10x the value. Maybe not a big deal if we expect most people to save the question and/or manually set the max?
4. I think that chart setting layout is doable with flexbox. The end color wells are just 1.5x times the size of the middle ones, I think?

**Comment by mazameli** [comment]
**Visual design update:**

We went through a bunch of iterations and we think we should move forward with this mock, though I think we're going to want to play with details of it once it's in the branch. E.g., I suspect the indicator isn't quite bold/contrasty enough to be read quickly still.

green

For the settings, I think we probably want to go with something more immediately obvious like this:

settings

This also would allow users to make gauges with discontinuous colored ranges, like this:

discontinuous

If two ranges overlap due to user input we can just decide on a layer order and put one range on top of the other.

------

**Stretch idea: range labels**
One idea @kdoh had was to give users the option to put labels on ranges to convey their semantic meaning, like this:

chart with labels

If we did that, the settings could look like this:

settings with labels

**Comment by mazameli** [comment]
@tlrobinson, to respond to the numbered questions/comments you wrote:

> That's fine with me. I guess I was thinking of a use case where larger numbers are bad. Like your factory is about to blow up or something.

Sure, that's a valid case; I just think e.g. the sales target scenario is a more common default, with more being good.

> Were you thinking we show both the accents and the success/warn/error colors, or remove the redundant (but slightly different) accents, or ...?

To step back and rethink this, is there a way to only show those colors in the palette if the palette has been altered via white labeling? That's the main situation in which you'd need to be able to grab a red/yellow/green.

> This might be a little tricky. At what point in the question creation flow would you want the default max setting be "fixed"? The way settings currently work is defaults are computed from the current state of the query, so if the scalar value changed then the max would change. However, we do have a way to mark settings defaults as persisted (persistDefault) when the question is saved, so if it's ok that it's "fixed" on save then it should be easy. The one weird thing is if you bookmarked an ad-hoc question the max would automatically update to always be 10x the value. Maybe not a big deal if we expect most people to save the question and/or manually set the max?

Yeah, this was a half-baked idea that's sounding like it might get wacky. Let's not stress about this.

> I think that chart setting layout is doable with flexbox. The end color wells are just 1.5x times the size of the middle ones, I think?

Cool, that's good to know in case we decide to do that layout instead of the more traditional one I posted above a minute ago. Thanks.

**Comment by jbrooksuk** [comment]
Could there be an option to toggle the indicator?

**Comment by mazameli** [comment]
@jbrooksuk Toggle the indicator how exactly? On/off, or…?

**Comment by jbrooksuk** [comment]
Correct @mazameli. IMHO, the indicator proposed is very large and off putting.

Have you seen how Grafana handles their gauges?

**Comment by mazameli** [comment]
@tlrobinson I updated the description of this PR with what I think are the last to-dos before we merge this (some small polish to-dos might have snuck in that list too… 😁 )

**Comment by tlrobinson** [comment]
@mazameli I can't reproduce this:

> The Done and Cancel buttons in the viz settings modal are broken

**Comment by mazameli** [comment]
@tlrobinson hmm, I restarted my server and I'm still seeing this:

done-cancel

**Comment by mazameli** [comment]
Just noticed that things get a little funky if you clear out one of the range value input boxes. Ideally we could fail gracefully so that there's always the shape of the gauge present and that the arrow doesn't float around like this.

funky-gauge

**Comment by tlrobinson** [comment]
@mazameli I think I've fixed most of these issues, please give it another try.

How much do you care about not animating when opening the settings? It's not a ton of work, maybe 15 minutes worth.

**Comment by mazameli** [comment]
> How much do you care about not animating when opening the settings? It's not a ton of work, maybe 15 minutes worth.

Feels worth it if it's 15 minutes, if you don't mind.

**Comment by tlrobinson** [comment]
@mazameli I've fixed the funkiness you mentioned and disabled the animation in settings.

**Comment by mazameli** [comment]
Only two remaining things I can find:
1. If I clear out the "global" min or max, the chart disappears. And I probably shouldn't be able to click Done if there isn't a global min and max.
2. I can't enter negative numbers like `-100` in any of the input boxes.

**Review by kdoh — APPROVED** [review]

**Review by mazameli — COMMENTED** [review]
Only thing I saw was that clicking on `Reset to defaults` resets the chart preview, but the values in the range input boxes don’t get changed. Other than that I say ship this puppy.

**Comment by mnlbox** [comment]
Thanks guys. You done a great work. :wink:

**Comment by veve90** [comment]
Thank you guys!!!

**Comment by veve90** [comment]
Hello,

I just downloaded the docker metabase image.. and I don't have the Gauge.. is this normal?

Thank you!!

**Comment by mazameli** [comment]
Hi, @veve90. This feature will be included in version 0.31 of Metabase, which will be released this October.

**Comment by veve90** [comment]
In Metabase 0.31 can we add min/max values for the gauge that come from a table (sql query)?

**Comment by veve90** [comment]
In 0.34 I can't manage to see the gauge (?) Is this still available?

**Comment by mazameli** [comment]
@veve90 The latest version of Metabase is 0.30.4. Version 0.31.0 will have the gauge visualization in it (along with _lots_ of other new features!). We'll hopefully be putting out a release candidate build next week so folks can test things out before the official release, so I'll ping you then if you'd like to try out the gauge chart early.

In answer to your other question about dynamic min/max values, no that won't initially be possible. We have gotten a fair number of requests, however, to be able to use the results of saved questions as values for variables, so that might be something we look at doing for version 0.32.

**Pull request merged**
