### PR TITLE
Improve color documentation in the style guide

### PR DESCRIPTION
**Pull request by kdoh**
Add better color representation to the internal style guide, including the normal, and saturated JS palettes, and the colors used in our visualizations. You can also click on any of them and it'll copy the hex value to your clipboard.

If you have your local dev env spun up, check out [the colors page](http://localhost:3000/_internal/colors).

Otherwise, here's a screen shot.

screen shot 2018-03-26 at 10 03 48 pm

### CODE REVIEW

**Comment by tlrobinson** [comment]
To make the text visible on black or other dark components you could use the `color` package's `Color(...).isDark()` method

I think you'd need to upgrade the `color` package. I did in the visualized question list branch but you can do it here and it should be easily merged. `yarn add color` should do it.

**Comment by kdoh** [comment]
Nice. That's something I'd thought about last night but forgot to put in a ToDo.

Do you have any ideas why this is failing the flow check on CI? Looks like it's looking at some of the stuff in `/node_modules/`?

**Comment by tlrobinson** [comment]
Yeah probably a dependency of `rebass`.  You can add an entry to the `[ignore]` section of `.flowconfig`.

Do we really want to add `rebass` as a dependency? Is it something we want to start using in the main app, or will it end up as another hipster-js-tree-ring ;) I'm not opposed to either, but if it's the latter we should make sure it's not ending up in our `vendor` bundle. The `_internal` routes are code split but I don't know how that interacts with `vendor` bundle / `CommonsChunkPlugin`.

**Comment by kdoh** [comment]
My idea was to use rebass for most of the work I'm doing on the `spaces-ui` and `entity-pages` branches since both of those are going to be replacing a bunch of code (this branch is actually cherry-picked from over there). In general it's a pretty light weight library and does a lot of the same kind of thing I'd done in our css library more elegantly through props and components so I'd like to start heading that way. 

For this branch I can definitely just use some of our existing stuff and not add the dep and then we can use that stuff if and when we're using that library having shipped real features with it in the app.

**Review by mazameli — COMMENTED** [review]
- The color swatches are quite large; I think they could be closer to 150px square so you could see more at a glance.
- Nitpicky, but some kind of hover state or a list cursor:pointer on the swatches would be a nicety to make it clear they're clickable.
- It would be helpful if there was some way of indicating which CSS classes used which of the colors, e.g., below or on top of the first blue swatch, listing `text-brand`, `text-brand-hover`, `bg-brand`, and `bg-brand-hover`. 
- Might be cool to add a click-to-copy on the class names, too.

**Comment by kdoh** [comment]
@mazameli Made a couple of the tweaks you suggested, primarily smaller swatches and the copy indicator. 

I'll look into trying to get a better since of which things overlap between the CSS and JS colors in a follow up, although one of the things I want to do is improve the structure of some of our components going forward to where needing to apply colors yourself is an increasingly infrequent activity. Ideally over time most of the need for those classes goes away.

Right now I'm treating this as more of a reference for `what is Metabase blue?` and an overview of our pallete and am keeping the CSS color list around as a reminder of things to clean up.

**Pull request merged**
