### PR TITLE
Clean up collection icon stragglers

### PR DESCRIPTION
**Pull request by kdoh**
Noticed a few places where the ghosts of icons past are still hanging around.

Dashboard move toast - Before
Screen Shot 2023-01-27 at 12 57 27 PM
After
Screen Shot 2023-01-27 at 12 57 40 PM

Question move toast - Before
Screen Shot 2023-01-27 at 3 57 41 PM
After
Screen Shot 2023-01-27 at 3 57 23 PM

Data reference sidebar - Before
Screen Shot 2023-01-27 at 3 48 54 PM

After
Screen Shot 2023-01-27 at 3 46 34 PM

I went with the approach of aliasing `collection` to be the same as `folder` since I think expected and convenient names are likely to help make sure we're closer to the intended result than using just one un-intuitive name consistently.

### CODE REVIEW

**Review by mazameli — APPROVED** [review]
Thanks!

**Comment by mazameli** [comment]
While you're in there, do you think the toast confirmations still need two icons on the left?

**Review by iethree — APPROVED** [review]

**Comment by iethree** [comment]
> While you're in there, do you think the toast confirmations still need two icons on the left?

➕ I agree with @mazameli , 3 would be better

**Comment by kdoh** [comment]
@mazameli Yeah that's goofy as heck. They sure don't, but I think I want to consider that separately.

**Pull request merged**
