### PR TITLE
Remove unused public_perms columns :closed_lock_with_key:

### PR DESCRIPTION
**Pull request by camsaul**
Remove the last remnants of the old public permissions system. 

Implements #3408

### CODE REVIEW

**Comment by camsaul** [comment]
@metabase/core-developers any objections to me merging this?

**Comment by tlrobinson** [comment]
Wasn't there something on the frontend that needed to be removed? I think it was in the qb or dashboard header.

**Comment by salsakran** [comment]
looks fine from the code perspective.

**Comment by camsaul** [comment]
@tlrobinson I already did that as part of the permissions branch. In that branch we removed all the places that used these columns but I didn't remove the columns themselves because that would make switching in and out of that branch a PITA

**Comment by tlrobinson** [comment]
👍

**Pull request merged**
