### PR TITLE
Show/hide all fields toggle in table options

### LINKED ISSUE #3951: Add show/hide all fields toggle in table options
I'm trying to only see several fields in a table that has a ton of fields, and it's a pain to have to uncheck them all.

screen shot 2016-12-14 at 10 34 14 am

### PR DESCRIPTION
**Pull request by mariusz-jachimowicz-83**
Fix #3951

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by mariusz-jachimowicz-83** [comment]
I have just started to learn components structure.

**Comment by mariusz-jachimowicz-83** [comment]
select-all
unselect-all
unselect-all-2

**Comment by mariusz-jachimowicz-83** [comment]
Please review

**Comment by salsakran** [comment]
@mariusz-jachimowicz-83 given that @mazameli opened that issue (and is one of our designers), he should ok any visual changes in a PR. 

@mazameli, thoughts?

**Comment by mazameli** [comment]
Sorry for the delay in reviewing this! I'm getting some errors when trying to build this locally, so here's some small feedback just based on the screenshots.

I think it's a little confusing to have the toggle appear as one of the items in the list itself. I'd much prefer if we could reuse the select all component we already have when selecting multiple questions from the questions lists in collections, in this manner:

artboard

artboard copy

artboard copy 2

**Comment by mariusz-jachimowicz-83** [comment]
Proposition looks nice. Is there svg icon for this select all checkbox? I didn't saw this before.

**Comment by mazameli** [comment]
Sorry for the much delayed reply. @kdoh, would you be able to point him in the right direction to find that select-all component?

**Comment by mazameli** [comment]
I'd love to merge this once the visual/UI changes above get implemented. Not sure if @mariusz-jachimowicz-83 is still able to work on this, but maybe @attekei or @kdoh have a few spare cycles?

**Comment by mazameli** [comment]
I pulled this branch locally and tried implementing the suggested changes myself, but hit a few snags:
1. Maybe most importantly, the logic for selecting all the items works, but takes a long time, even on a small table. The logic for _un_-selected items works great. Not sure what's up with it.
2. Trying to move the checkbox up to the right of the "fields to include" label doesn't seem easy, because that label gets changed via a property passed to ChartSettings.jsx. So I'm not sure how to get the stacked checkbox on that same line short of putting its markup into ChartSettings.jsx, which I don't think we want to do. 
3. I imported StackedCheckBox and swapped out CheckBox for it in the render method. When I open up the modal, I can see the stacked checkbox momentarily, but then it abruptly vanishes. When I close the modal, it appears again for a moment before the modal closes.

If we can fix #1, I think at this point I'd just say merge it unless the rearranging is easier than it seems to be to me.

**Comment by mariusz-jachimowicz-83** [comment]
@mazameli I don't know why selecting might be slow but even though it should be faster then toggle dozen of  fields :smile: I think. For people it's important to just have some ability. It doesn't need to be. Points 1-3 might be resolved after merge separately.

**Comment by salsakran** [comment]
closing in favor of #6339

**Pull request closed without merging**
