### PR TITLE
Revert Cypress upgrade (v5.3.0. -> v3.8.2)

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
IN REVIEW

### What does this PR accomplish?
- reverts Cypress upgrade from v5.3.0 to v.3.8.2

### Additional context:
Since we [merged the upgrade](https://github.com/metabase/metabase/commit/d9eb1b01b689fd12d4d5d703cadcb3618d1e7d17), Cypress tests started timing out randomly in CircleCI with the following message:
`Too long with no output (exceeded 5m0s): context deadline exceeded`

- Even when we increased `no_output_timeout` to 10m, it continued to happen. 
- Next try was to [remove test retries](https://github.com/metabase/metabase/commit/3594c6ca68bddc07e02a3b3e04b3bca6d28a9a90), but that didn't help either.

### CODE REVIEW

**Comment by dacort** [comment]
Do we also need to revert the `cy.url` --> `cy.location("pathname")` changes from the original upgrade?

**Comment by nemanjaglumac** [comment]
> Do we also need to revert the `cy.url` --> `cy.location("pathname")` changes from the original upgrade?

No. That was plain wrong, but "old" Cypress didn't complain. I intentionally didn't revert that part.

**Review by dacort — APPROVED** [review]
I didn't go through `yarn.lock` line by line, but assuming it represents the state of what it was before the upgrade.

**Comment by nemanjaglumac** [comment]
> I didn't go through `yarn.lock` line by line, but assuming it represents the state of what it was before the upgrade.

Hm... I can diff those two. The state of `package.json` **is** the same. I assumed `yarn.lock` should be as well.

**Comment by paulrosenzweig** [comment]
I wouldn't be surprised if some yarn.lock versions changed. Many of our package.json versions are too loose, so there's probably some flexibility when cypress is upgraded and then downgraded. If no tests are failing that's probably OK.

Earlier this week, I saw a few things fail with minor version changes during a merge. (e.g. dc.js went from 2.1.9 to 2.2.2 and broke two tests) Ideally, things wouldn't break when versions change, but if they will we shouldn't specify a range in package.json.

**Comment by nemanjaglumac** [comment]
@dacort here's the diff (before upgrade and after reverting it, respectively)

## 1
```
ajv@^6.5.5:
  version "6.10.2"
  resolved "https://registry.yarnpkg.com/ajv/-/ajv-6.10.2.tgz#d3cea04d6b017b2894ad69040fec8b623eb4bd52"
  integrity sha512-TXtUUEYHuaTEbLZWIKUr5pmBuhDLy+8KYtPYdcV8qC+pOZL+NKqYwvWSRrVXHn+ZmRRAu8vJTAznH7Oag6RVRw==
  dependencies:
    fast-deep-equal "^2.0.1"
    fast-json-stable-stringify "^2.0.0"
    json-schema-traverse "^0.4.1"
    uri-js "^4.2.2"
```
```
ajv@^6.12.3:
  version "6.12.5"
  resolved "https://registry.yarnpkg.com/ajv/-/ajv-6.12.5.tgz#19b0e8bae8f476e5ba666300387775fb1a00a4da"
  integrity sha512-lRF8RORchjpKG50/WFf8xmg7sgCLFiYNNnqdKflk63whMQcWR5ngGjiSXkL9bjxy6B2npOK2HSMN49jEBMSkag==
  dependencies:
    fast-deep-equal "^3.1.1"
    fast-json-stable-stringify "^2.0.0"
    json-schema-traverse "^0.4.1"
    uri-js "^4.2.2"
```
## 2
```
fast-deep-equal@^2.0.1:
  version "2.0.1"
  resolved "https://registry.yarnpkg.com/fast-deep-equal/-/fast-deep-equal-2.0.1.tgz#7b05218ddf9667bf7f370bf7fdb2cb15fdd0aa49"
  integrity sha1-ewUhjd+WZ79/Nwv3/bLLFf3Qqkk=
```
```
fast-deep-equal@^3.1.1:
  version "3.1.3"
  resolved "https://registry.yarnpkg.com/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz#3a7d56b559d6cbc3eb512325244e619a65c6c525"
  integrity sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==
```
## 3
```
har-validator@~5.1.0:
  version "5.1.3"
  resolved "https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.3.tgz#1ef89ebd3e4996557675eed9893110dc350fa080"
  integrity sha512-sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==
  dependencies:
    ajv "^6.5.5"
    har-schema "^2.0.0"
```
```
har-validator@~5.1.0:
  version "5.1.5"
  resolved "https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.5.tgz#1f0803b9f8cb20c0fa13822df1ecddb36bde1efd"
  integrity sha512-nmT2T0lljbxdQZfspsno9hgrG3Uir6Ks5afism62poxqBM6sDnMEuPmzTq8XN0OEwqKLLdh1jQI3qyE66Nzb3w==
  dependencies:
    ajv "^6.12.3"
    har-schema "^2.0.0"
```
## 4
```
psl@^1.1.24:
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/psl/-/psl-1.4.0.tgz#5dd26156cdb69fa1fdb8ab1991667d3f80ced7c2"
  integrity sha512-HZzqCGPecFLyoRj5HLfuDSKYTJkAfB5thKBIkRHtGjWwY7p1dAyveIbXIq4tO0KYfDF2tHqPUgY9SDnGm00uFw==
```
```
psl@^1.1.24:
  version "1.8.0"
  resolved "https://registry.yarnpkg.com/psl/-/psl-1.8.0.tgz#9326f8bcfb013adcc005fdff056acce020e51c24"
  integrity sha512-RIdOzyoavK+hA18OGGWDqUTsCLhtA7IcZ/6NCs4fFJaHBDab+pDDmDIByWFRQJq2Cd7r1OoQxBGKOaztq+hjIQ==
```

**Comment by dacort** [comment]
Except for `fast-deep-equal` those all look relatively harmless. And for `fast-deep-equal`, the breaking changes I see in the 3.0 [release notes](https://github.com/epoberezkin/fast-deep-equal/releases/tag/v3.0.0-beta.0) don't seem like they would impact us.

**Comment by nemanjaglumac** [comment]
Thank you for digging into this @dacort 

[THIS](https://app.circleci.com/pipelines/github/metabase/metabase/9384/workflows/73dc364e-a961-4cb4-9f3a-ab8439b41105/jobs/327703) is one of the newer flakes. It's failing consistently - 4 times in a row. I'll try to fix it (although there is simply no logic behind the fail). If even that doesn't work, I'll skip it temporarily with a todo note to get back to it asap. The priority is to merge this into master and stop Cypress timeouts in CI.

**Pull request merged**
