### PR TITLE
Improve line-height in data ref paragraphs [ci skip]

### PR DESCRIPTION
**Pull request by mazameli**
Another Trivial PR™. This one makes the line-height of long paragraphs be more friendly and legible. Incidentally, this whole css file uses `px` throughout, so I used that in my change, but I'm not sure if we want to switch everything in the file to `rems`. In conclusion, let's make line-height great again!

Before:
screen shot 2016-08-15 at 3 08 45 pm

After:
screen shot 2016-08-15 at 3 08 33 pm

### CODE REVIEW

**Comment by kdoh** [comment]
I'm definitely not against merging this because better line height is definitely 👍, but it seems like we should have a better abstraction to ensure proper body text size and proper leading. This is one of those places where I wonder "why doesn't this just look right out of the box?"

**Comment by mazameli** [comment]
Yeah, good call. Would you suggest putting this on the `.text-body, :local(.text-body)` selectors in `metabase/frontend/src/metabase/css/core/text.css`?

**Comment by lewisl9029** [comment]
RE: the use of `px` everywhere. I'd usually prefer to use `rem` as well, but I remember looking through a lot of the existing component-specific CSS files in the codebase and only seeing `px` values for font-sizes, so that's what I ended up following. 

If we do prefer `rem` and want to make the switch, we should probably do a sweep across all the `font-size` values in the codebase to make things consistent.

**Comment by mazameli** [comment]
Ended up creating a new `text-reading` class in `text.css` and including that in the data reference detail's class composition. 

I'd intended on also removing the `font-size: 16px` rule from the `detailSubtitle` class, since `text-reading` specifies `font-size: 1em`, but that wasn't resulting in the expected font size, probably due to some shenanigans with our root font size not having global scope or something that I don't understand.

**Comment by camsaul** [comment]
Does `text-reading` imply that other text is not intended for reading?

**Comment by mazameli** [comment]
Haha, it's probably not the best class name. `lengthy-text`?

**Comment by kdoh** [comment]
I'd ideally like to keep the `.text` prefix so something in that land would be my preference. Let's make that change with whatever you think makes sense (`.text-paragraph`?) and then call this a day. I feel like what we should really do here to improve this down the road is have a `<Text>` component that just handles this all internally and obscures the need to remember to do anything to make text have the proper line length and line height.

**Comment by camsaul** [comment]
LGTM 👍

**Pull request merged**
