### PR TITLE
remove sync events from the activity feed because it's overly verbose

### PR DESCRIPTION
**Pull request by agilliland**

### CODE REVIEW

**Comment by agilliland** [comment]
@kdoh @mazameli what should we do with existing feed entries about database syncs?  any reason we'd want to actively remove those from the feed on upgrade?

**Comment by tlrobinson** [comment]
In the future perhaps we should just collapse multiple identical events in a row into a single event? Could even be done purely in the frontend.

**Comment by agilliland** [comment]
Yeah, that's definitely a possibility as well.  After talking this over with Kyle there were a couple other reasons we felt it was preferential to remove this from the main homepage activity feed, but I agree that being able to condense the feed items where appropriate would be great.

There are definitely times when someone works on a Dashboard or a Question and creates multiple feed items in a row which could be condensed.

**Comment by mazameli** [comment]
My take is we should just remove all the items. I can't why you'd want them in there for historical purposes, and if you leave them in there but then stop providing new updates, people will wonder if the syncing is broken ("looks like the last time it got the latest data was over a week ago…").

**Comment by kdoh** [comment]
+1 to what @mazameli said. One of the main reasons to remove it aside from frequency and visual noise is the fact that it incorrectly insinuates that Metabase has to get a copy of your data when in reality this is activity item is speaking about the metadata and model of the schema being up to date. I'd be worried that folks would think "ingestion" stopped working by leaving some in from the past.

**Comment by agilliland** [comment]
k ... i'll go ahead and purge the old feed entries as part of this update then.

**Pull request merged**
