### PR TITLE
Add marginBottom to SelectPicker

### LINKED ISSUE #16658: Boolean filter Popovers show visually chopped `True` and `False`
Related to: #16655

## To reproduce:

1. Ask a question, Native question
2. In the SQL editor, type the following:
```
select 0::integer as "integer", true::boolean AS "boolean"
union all
select 1::integer as "integer", false::boolean AS "boolean"
union all
select null as "integer", true::boolean AS "boolean"
union all
select -1::integer as "integer", null AS "boolean"
```
3. Save question.
4. Click _Explore results_ button (top right)
5. Click on the _boolean_ column, choose Filter by this Column

Note that `True` and `False` get cut off at the bottom.

image

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #16658

## How to Test

1. Ask a question, Native question
2. In the SQL editor, type the following:
```
select 0::integer as "integer", true::boolean AS "boolean"
union all
select 1::integer as "integer", false::boolean AS "boolean"
union all
select null as "integer", true::boolean AS "boolean"
union all
select -1::integer as "integer", null AS "boolean"
```
3. Save question.
4. Click _Explore results_ button (top right)
5. Click on the _boolean_ column, choose Filter by this Column

### CODE REVIEW

**Comment by ariya** [comment]
@gusaiani Does this also solve the popover cutoff in #16679?

**Review by kulyk — APPROVED** [review]
LGTM 👏

**Comment by kulyk** [comment]
> @gusaiani Does this also solve the popover cutoff in #16679?

I can still reproduce the issue with the longitude filter

**Comment by gusaiani** [comment]
Will tackle the longitude filter next. Thanks guys.

**Comment by kulyk** [comment]
@gusaiani Ariya is already working on that at #16728

**Comment by gusaiani** [comment]
@ariya, #16679 seems to now be fixed on `master`, correct?

cc @kulyk

**Comment by ariya** [comment]
> @ariya, #16679 seems to now be fixed on `master`, correct?

No it's not.

**Pull request merged**
