### PR TITLE
Vertical legend fixes for LineAreaBarChart

### PR DESCRIPTION
**Pull request by ranquild**
Fixes issues found during bugbash:
1. Fixes trimming in horizontal mode
2. Aligns the LineAreaBarChart in a special way in the Query Builder
3. Fixes vertical legend calculations for fullscreen mode
4. Fixes legends text color in night mode in dashboards

How to test 1:
- Add a line chart to a dashboard
- Edit dashboard -> hover over card -> Add series -> Add several other line charts
- When series names overflow the width of the card, they should be truncated

How to test 2:
- See @mazameli comment. It should be aligned correctly for both horizontal and vertical modes

How to test 3:
- Create a line chart with breakout by category, e.g. by User -> State
- Add this line chart to a dashboard
- Enter fullscreen mode
- You should be able to see "And X more" button, which should allow you to select series in the popover

How to test 4:
- Same as 3
- Enter night mode
- Legend labels should change their color

### CODE REVIEW

**Comment by mazameli** [comment]
It also appears that the spacing/padding on question pages looks a bit off for _horizontal_ legends, too:

image

Adding `margin-top: 10px;` and `margin-left: 15px;` looks more correct to me:

image

**Comment by ranquild** [comment]
> It also appears that the spacing/padding on question pages looks a bit off for _horizontal_ legends, too:
> 
> image
> 
> Adding `margin-top: 10px;` and `margin-left: 15px;` looks more correct to me:
> 
> image

The spacing for both horizontal and vertical legends in the query editor should be fixed in this PR, please have a look.

**Comment by gusaiani** [comment]
@ranquild Steps to test would be very helpful for me to test and review.

I don't really know how to produce these charts in Metabase, believe it or not.

**Comment by ranquild** [comment]
@mazameli Added a fix for that case, please have a look

**Comment by mazameli** [comment]
Sweet, will do.

**Comment by mazameli** [comment]
@ranquild Looking good to me!

**Review by alxnddr — APPROVED** [review]
👍

**Pull request merged**
