### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by rlotun**
Do a rough first pass at a security.md file.

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
WFM... we should add this to the https://github.com/metabase/metabase/saml20-clj repo too

**Review by salsakran — COMMENTED** [review]
This seems reasonable. We might want to remove the security portion of the readme or link to this from there? 

Also, I'm not sure that we should support the last 3 versions, but don't feel strongly about where the line should be.

**Review by flamber — APPROVED** [review]
Would it be possible to just write supported versions more generic, so we don't have to keep this updated on every major release?

**Comment by camsaul** [comment]
> Also, I'm not sure that we should support the last 3 versions, but don't feel strongly about where the line should be.

Maybe for Enterprise we should do extended support but for the free edition not promise the same level of commitment?

**Comment by ariya** [comment]
> We might want to remove the security portion of the readme or link to this from there?

Yup, otherwise duplicated information (esp. if it's not exact) can be confusing.

**Review by ariya — APPROVED** [review]

**Pull request merged**
