### PR TITLE
Prepend info about query execution to SQL :information_desk_person: :…

### PR DESCRIPTION
**Pull request by camsaul**
Prepend some general information about query being ran as a comment to the beginning of queries for SQL DBs (I couldn't figure out how to do this for Mongo or Druid).

e.g.

``` sql
-- Metabase:: userID: 2 executionID: 170cbab5-090b-4be5-b286-1168f9439b5a queryType: MBQL queryHash: 1005045833
SELECT "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", [...]
FROM "PUBLIC"."ORDERS" 
LIMIT 1
```

Implements #2386

### CODE REVIEW

**Comment by agilliland** [comment]
I would recommend a different solution here which doesn't involve changing the driver protocol and provides more flexibility.

1. Rather than add an argument to the `mbql->native` function (or any other function) you can simply place there relevant data on the query object itself.  The query is `the` description of what's being executed so it makes sense to put the information there.

2. I wouldn't apply this code as part of the `mbql->native` function at all because that functions only purpose is to transpile our custom query definitions into native queries and presumably can be called without a query execution ever taking place, plus doing so would prevent this information from being available on native query executions.  Instead I think it makes more sense to apply this in the `execute-query` function so it's used on all query executions.

3. Rather than forcing the formatting of this information into a string I think it makes more sense to simply add a dictionary of this information to the query and let the drivers utilize it how they like.  This allows for cases where a string comment may not be the best way to log this information for a given database.  To avoid requiring every driver to write its own `query->remark` function I still think it makes sense to provide a generic form of that function which drivers can easily use if that approach is all they need.

With those tweaks I believe you'll likely end up with fewer new lines of code introduced, no changes to our driver protocol, and in the long run there will be the option for drivers to customize how a remark is captured if that's necessary.  The only code you should end up needing would be 1) a few lines in the `dataset-query` function which will `assoc` the appropriate information onto the query before it's passed to the `process-query` function, 2) a generic implementation of `query->remark` same as you have right now, and 3) a couple lines in the generic-sql `execute-query` function which calls `query->remark` and prepends the output to the SQL that will be executed (same for bigquery and any other drivers).

**Comment by salsakran** [comment]
👍  on @agilliland thoughts.

This is potentially something we'd generalize over time. I'd prefer a relatively loose context dictionary that contains information that a driver could potentially use for other nefarious purposes rather than a tightly specific remark string.

**Comment by agilliland** [comment]
@camsaul I guess you decided not to take all of my recommendations provided above.  There are a couple of drawbacks to the code that you merged ..

1. We are not applying the remark to native queries, which for many Metabase instances may be over half of the queries being executed.

2. Since you prepend the remark to the SQL in the `mbql->native` function it is now included in the SQL that is given to users when they decide to look at the query and possibly change it into a native card, which is a little hokey.

screen shot 2016-06-07 at 5 19 59 pm

**Comment by salsakran** [comment]
@camsaul let's rework this so that native queries are covered and the mbql->native isn't borked. 

I'm adding another 👍 on allen's comments in the original code review.

**Comment by salsakran** [comment]
Additionally, there should be tests on both the mbql->native as well as the prepended comment. 

This PR shouldn't have passed CI.

**Pull request merged**
