### PR TITLE
#14604 Repro: Custom columns break pivot tables

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Reproduces #14604

### How to test this manually?
- `yarn test-cypress-open`
- `frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js`
- Replace `it.skip()` with `it.only()` to run the test in isolation
- The test should fail until the related issue is fixed

### Additional notes:
- Once the issue is fixed, please remove the `.skip` part (unskip the test completely)
- Make sure the test is passing and
- Merge it together with the fix

### Screenshots:
image

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
@paulrosenzweig I didn't know what exactly to assert on. Custom column name was a logical thing to do, but we can assert on so many other UI elements. Either let me know if you'd like me to add some more assertions, or please feel free to update the test as you see fit.

One more thing to note:
Obviously, I couldn't use API to write the full test (because wrong XHR is in the root of this). So, I first created a a "normal" question with custom column prepared, and then used UI to add it as an aggregation.

**Comment by paulrosenzweig** [comment]
> I couldn't use API to write the full test (because wrong query being constructed is in the root of this).

As far as I know, the query constructed by the notebook editor is correct. The issue is that the pivot endpoint doesn't return the correct data. Given that, I opted to use `visitQuestionAdhoc` and directly open up a pivot table rather than building the query in the UI.

I also split out two separate tests. The first checks that you can aggregate a custom column. The second checks that you can breakout with a custom column. Both fail currently due to #14604.

**Review by paulrosenzweig — APPROVED** [review]
It's a bit unfair for me to approve since I edited them 🤷 

@nemanjaglumac feel free to merge if you think they look alright.

**Comment by nemanjaglumac** [comment]
I'd like @flamber 's eyes on this before we merge it.

Btw, @paulrosenzweig it's unfair for this to even mention me because you really did all the work! 💪

**Comment by flamber** [comment]
I would like to have a test where you create a Custom Column, but actually don't use it in the summarize, and then it shouldn't show up in the Pivot Table.

**Pull request merged**
