### PR TITLE
Move click behavior to metabase-lib

### PR DESCRIPTION
**Pull request by ranquild**
Epic https://github.com/metabase/metabase/issues/25618

### CODE REVIEW

**Comment by kulyk** [comment]
Not sure if everything from `click-behavior` belongs to `metabase-lib`. A lot of utilities there are dashboard's internal matters. E.g. `getClickBehaviorDescription` ([here](https://github.com/metabase/metabase/blob/18774a5df8fc1400d6289622451b869ced4f9bcb/frontend/src/metabase-lib/lib/parameters/utils/click-behavior.js#L201)) or `clickBehaviorIsValid` ([here](https://github.com/metabase/metabase/blob/18774a5df8fc1400d6289622451b869ced4f9bcb/frontend/src/metabase-lib/lib/parameters/utils/click-behavior.js#L236)). Agreeing that utils figuring out suitable mapping target/source pairs would probably belong here

**Comment by ranquild** [comment]
@kulyk I believe that complicated business logic should go to `metabase-lib`. It's definitely not UI only. We're moving parameters logic to metabase-lib and this is mostly about parameters, too.

**Comment by daltojohnso** [comment]
I'm in agreement with @kulyk here -- I think code in `metabase-lib` should be limited to query transformation logic and related metadata. I include a subset of parameters code in that category, mainly the bits relating to its `type` and conversion to mbql) as `parameters` can be a property on the body of query POST requests. Click behavior logic seems like it might be a step or two outside of that limit. The feature is certainly tied closely to parameters and I see a lot of logic that should be in parameters utility functions, but I don't think we should put all of it there, as "click behavior" is its own feature that mainly has to do with updating URLs -- sometimes that just means a direct link to a question URL without any parameters.

**Comment by ranquild** [comment]
I don't agree with you. Posting functions from `click-behavior` here - that's definitely not "UI" logic

`getDataFromClicked`:

```
export function getDataFromClicked({
  extraData: { dashboard, parameterValuesBySlug, userAttributes } = {},
  dimensions = [],
  data = [],
}) {
  const column = [
    ...dimensions,
    ...data.map(d => ({
      column: d.col,
      // When the data is changed to a display value for use in tooltips, we can set clickBehaviorValue to the raw value for filtering.
      value: d.clickBehaviorValue || d.value,
    })),
  ]
    .filter(d => d.column != null)
    .reduce(
      (acc, { column, value }) =>
        acc[name] === undefined
          ? { ...acc, [column.name.toLowerCase()]: { value, column } }
          : acc,
      {},
    );

  const parameterByName =
    dashboard == null
      ? {}
      : _.chain(dashboard.parameters)
          .filter(p => parameterValuesBySlug[p.slug] != null)
          .map(p => [
            p.name.toLowerCase(),
            { value: parameterValuesBySlug[p.slug] },
          ])
          .object()
          .value();

  const parameterBySlug = _.mapObject(parameterValuesBySlug, value => ({
    value,
  }));

  const parameter =
    dashboard == null
      ? {}
      : _.chain(dashboard.parameters)
          .filter(p => parameterValuesBySlug[p.slug] != null)
          .map(p => [p.id, { value: parameterValuesBySlug[p.slug] }])
          .object()
          .value();

  const userAttribute = _.mapObject(userAttributes, value => ({ value }));

  return { column, parameter, parameterByName, parameterBySlug, userAttribute };
}
```

2. `getTargetsForQuestion`:

```
function getTargetsForQuestion(question, metadata) {
  const query = new Question(question, metadata).query();
  return query
    .dimensionOptions()
    .all()
    .concat(query.variables())
    .map(o => {
      let id, target;
      if (
        o instanceof TemplateTagVariable ||
        o instanceof TemplateTagDimension
      ) {
        let name;
        ({ id, name } = o.tag());
        target = { type: "variable", id: name };
      } else {
        const dimension = ["dimension", o.mbql()];
        id = JSON.stringify(dimension);
        target = { type: "dimension", id, dimension };
      }
      let parentType;
      let parameterSourceFilter = () => true;
      const columnSourceFilter = c => isa(c.base_type, parentType);
      if (o instanceof TemplateTagVariable) {
        parentType = { text: Text, number: Number, date: Temporal }[
          o.tag().type
        ];
        parameterSourceFilter = parameter =>
          variableFilterForParameter(parameter)(o);
      } else if (o.field() != null) {
        const { base_type } = o.field();
        parentType =
          [Temporal, Number, Text].find(t => isa(base_type, t)) || base_type;
        parameterSourceFilter = parameter =>
          dimensionFilterForParameter(parameter)(o);
      }

      return {
        id,
        target,
        name: o.displayName({ includeTable: true }),
        sourceFilters: {
          column: columnSourceFilter,
          parameter: parameterSourceFilter,
          userAttribute: () => parentType === Text,
        },
      };
    });
}
```

**Comment by kulyk** [comment]
@ranquild yeah, for these two I agree that `metabase-lib` can be a better place to leave at least in the spirit of business logic consolidation vs. spreading across a bunch of layers. Maybe it makes sense to move the entire function, and maybe it'd feel more "right" to extract a part of it that touches dimensions and query internals but keep the facade in the core app directory. I think the point is that a lot of code from click behavior is a 100% app/UI matter (like [`getClickBehaviorDescription`](https://github.com/metabase/metabase/blob/18774a5df8fc1400d6289622451b869ced4f9bcb/frontend/src/metabase-lib/lib/parameters/utils/click-behavior.js#L201) which is only used in UI)

**Review by daltojohnso — APPROVED** [review]
I definitely agree that a huge chunk of this logic should be in `metabase-lib`, especially everything related to columns and types and most things related to parameters. My "bad abstractions" senses tingle when I see words like click, extraData, userAttribute, linkType, however, and I think there's a coupling of the specific action (a click on a dashcard by a user) with the responsibilities of metabase-lib that we should at some point revisit and address.

**Pull request merged**
