### PR TITLE
migration to backfill QueryField for native cards

### PR DESCRIPTION
**Pull request by sansolovyov**
resolves #39998

### CODE REVIEW

**Review by tsmacdonald — APPROVED** [review]
LGTM. I'm wondering if we should wait for the `{{variable}}` stuff to get merged so that those cards get backfilled too

**Comment by piranha** [comment]
> I'm wondering if we should wait for the {{variable}} stuff to get merged so that those cards get backfilled too

makes sense!

**Review by tsmacdonald — CHANGES_REQUESTED** [review]
just for the archived bit, which I'd forgotten about but is in the original ticket

**Comment by tsmacdonald** [comment]
(And the {{variable}} stuff is merged, so this should be good to go once you add the archived clause)

**Comment by piranha** [comment]
@tsmacdonald omg, yes! done.

**Review by tsmacdonald — APPROVED** [review]
awesome. turned on auto-merge

**Comment by tsmacdonald** [comment]
```
                    java.lang.Exception: Cyclic load dependency: [ /metabase/driver ]->/metabase/query_processor/compile->/metabase/native_query_analyzer/parameter_substitution->/metabase/native_query_analyzer->/metabase/db/custom_migrations->/metabase/db/setup->/metabase/db->/metabase/models/serialization->/metabase/models/setting->[ /metabase/driver ]->/metabase/driver/oracle
```

ah shoot, sorry dude :stuck_out_tongue:

**Pull request merged**
