### PR TITLE
MLv2 schema: validate references

### LINKED ISSUE #30084: [MLv2] We need to validate that references you're adding to a query are actually valid for that stage
See also: #30083

Right now pMBQL is pretty forgiving and lets you add almost any sort of reference to a query as long as the type information is correct; You can do something like 

```clj
{:lib/type :mbql/query
 :stages [{:source-table 1, :filter [:= {...} [:field {..., :join-alias "X"} 2] 3]}]}
```

even tho there is no join `X`, or use a `[:field {...} <string-name>]` reference in the first stage of a query, or use `[:aggregation {...} 0]` in a query with no aggregations, etc. 

We should disallow as much of these things as we can in the stage schemas themselves. Some more advanced validation will require a metadata provider, but I suppose we should be able to do those checks against the query as a whole if it has `:lib/metadata`, right? If it's not feasible to do these checks in the actual schemas then maybe we can do them in some other way. 

Maybe some sort of general `(valid-reference-for-stage? query stage-number reference)` function would make sense for implementing this. TBD

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #30084

- Make sure `:aggregation` references refer to a valid aggregation index
- Make sure `:expression` references refer to a valid expression name
- Make sure `:field` references with `:join-alias` refer to a join in the current stage of the query, or a previous stage, or a join inside a join in any of those stages. I know this is completely insane, but apparently we intentionally allow this: https://github.com/metabase/metabase/blob/e587a20cbee9b4046b97938e5bd4a04a6ccb1881/test/metabase/driver/sql/query_processor_test.clj#L948-L1008
  
  In hindsight, if we have MLv2 in place all along, we probably never would have generated queries so foul in the first place, I think theoretically you **should** be using `[:field <opts> <string>]` to refer to a column from a previous stage regardless of whether it comes from a join or not, but we were luckily if MLv1 output anything syntactically valid let alone logically valid, so the QP tries very hard to guess what you meant and work anyway. So we'll just have to allow this for now until some point in the future where maybe we can fix those queries or something.

Unfortunately this cannot validate join aliases when using a Card source query, since we don't know what sorts of joins the Card source query might introduce; if we did full-query validation **with** a metadata provider we could probably infer this information, but that is probably outside the scope of this PR. I'll open a follow-on issue to implement it in the future tho.

I considered adding additional validation rules: 

* requiring people to use `[:field <opts> <integer-id>]` clauses in the initial stage for fields that didn't come from joins
* Doing whole-query validation when the metadata provider is present:
  * make sure Fields exist, and belong to the `:source-table`
  * make sure the `:source-table` and joined tables exist and belongs to the `:database`
  * make sure referenced Metrics and Segments exist
  * make sure source-table (when it is a Card) exists and is against the same `:database`
  
but I decided these would make more sense in follow-on PRs. The stuff here is what is immediately valuable in combination with @snoe 's PR https://github.com/metabase/metabase/pull/30096

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30098)

### CODE REVIEW

**Review by snoe — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30098)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @camsaul)

**Review by metamben — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30098)* status: all files reviewed, 1 unresolved discussion (waiting on @camsaul)

___
*[`src/metabase/lib/schema.cljc` line 176 at r3](https://reviewable.io/reviews/metabase/metabase/30098#-NT06mqDAR6bhBjbKdgO:-NT06mqDAR6bhBjbKdgP:b3jrzfr) ([raw file](https://github.com/metabase/metabase/blob/762f009046a47766f342563498c93f8a3bbd48b7/src/metabase/lib/schema.cljc#L176)):*
> ```Clojure
>   previous stages."
>   ;; this is redundant now but I'm leaving it open so we can add more stuff in the future as we validate more things.
>   (some-fn join-ref-error-for-stages))
> ```

`some-fn` looks superfluous.

**Review by camsaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30098)* status: all files reviewed, 1 unresolved discussion (waiting on @metamben)

___
*[`src/metabase/lib/schema.cljc` line 176 at r3](https://reviewable.io/reviews/metabase/metabase/30098#-NT06mqDAR6bhBjbKdgO:-NT1Qto_1ZImxIfEBubw:b-7ql1td) ([raw file](https://github.com/metabase/metabase/blob/762f009046a47766f342563498c93f8a3bbd48b7/src/metabase/lib/schema.cljc#L176)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

`some-fn` looks superfluous.
</blockquote></details>

fixed

**Review by snoe — COMMENTED** [review]
[Discussion here](https://metaboat.slack.com/archives/C04DN5VRQM6/p1681749871658869)

At first look it seems there's a problem with converted queries validating aggregation references.

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30098#-:-NTF9nwvBRgZwruh_CoI:byu32g2)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @metamben)

**Review by metamben — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30098)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @camsaul)

**Pull request merged**
