### PR TITLE
Add Locale configuration setting and Postgres date trunc correction

### PR DESCRIPTION
**Pull request by atharvai**
# Overview
This PR adds a configurable Locale setting to Metabase. This is used only to configure the locale for `moment.js` and does not affect language and number formatting. The default is kept as `en` (US) locale but allows changing based on any locale listed [here](https://github.com/moment/moment/tree/master/locale).

The second change is that for Postgres data source _only_ the date trunc transformation for week is now an unmodified implementation. This follows postgres' standard of defining week boundaries instead of Metabase deciding the week boundary. 

Locale Setting UI:
image

Locale Setting effect (default):
image

Locale Setting using `en_gb` locale:
image

Locale Setting using `ja` locale:
image

One thing to be mindful of is the language is still English so other than the symbols defined in locale files, everything will be in English. 

# Related Issues
- https://github.com/metabase/metabase/issues/4910
- https://github.com/metabase/metabase/issues/1779
- https://github.com/metabase/metabase/issues/2517

# Comments/Questions
- Should the locale setting be a drop down list similar to timezone setting?
- Verify other areas of Metabase which might need modification. 
  - Other data sources (not applicable to Hudl).
- What other changes need to be made related to this?

###### TODO 
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by atharvai** [comment]
Other than license agreement what else is needed to get this PR ready to merge?

**Comment by alagu** [comment]
Is this happening?

**Review by mazameli — CHANGES_REQUESTED** [review]
Hey, @atharvai. Apologies this PR hasn't been resolved for so long. My thoughts:

If this setting for now just changes what the first day of the week is, I think the setting should just be a dropdown that lets you pick the first day of the week, regardless of how that's actually being implemented with moment.js behind the scenes. Doesn't really make sense to me to ask the user to input a locale code to change what the first day of the week is.

**Comment by atharvai** [comment]
Hey this is now over 2 years old and I'm not sure the branch even works. I'm also no longer working with Metabase codebase so I'm unlikely to pick this up.  Feel free to pick up.
Yea drop down makes sense.

**Pull request closed without merging**
