### PR TITLE
Remove `QuestionDataSelector`

### LINKED ISSUE #42559: Remove `QuestionDataSelector`

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #42559

### Description

It took me a while to track down how `QuestionDataSelector` was used.
It was being rendered when `isNewQuestion && queryBuilderMode === "view"` but I could never achieve this condition in the current Metabase version - it's not possible for `isNewQuestion` to be `true` when `queryBuilderMode === "view"`. 

It was possible in the past though - Metabase 0.35 had a ["Simple question" mode](https://github.com/metabase/metabase/assets/6830683/ce6a8888-26a1-4197-8c3b-4ac3ead747ac) where this condition evaluated to `true`  (see [video of how things used to looked like](https://github.com/metabase/metabase/assets/6830683/29981531-1628-49be-997f-f38bb6752591)) and there was no trigger button for the data source picker. Since this mode no longer exists, I think it's safe to get rid of this code.

I also created a temporary PR (#42561) to run CI for this change against `master` (the `data-picker` feature branch has almost a hundred failing test right now) and [everything was green](https://github.com/metabase/metabase/pull/42561#issuecomment-2107372586) ([run in replay.io](https://app.replay.io/team/dzoyNTM4ZjRmOC05YmFlLTRiYjYtYjljYi1jOGYzOWUyMjRhZWY=/runs?testRunId=f85ead63-085e-445b-9d92-d294f596265e&testId=)).

### CODE REVIEW

**Review by uladzimirdev — APPROVED** [review]
I'd not merge it before @ranquild's review

**Comment by ranquild** [comment]
@kamilmielnik it should be used. I think when opening a ad-hoc question from url

**Review by ranquild — COMMENTED** [review]
I would leave it until CI is fixed

**Comment by kamilmielnik** [comment]
> I think when opening a ad-hoc question from url

That's not it - in that case `isNewQuestion` will be `false` and `QuestionDataSelector` won't be used.

`isNewQuestion` will be `true` only if source table has not been selected.
Only once source table has been selected `queryBuilderMode` can change to `"view"`.
So it looks like this condition will never be satisfied.

I also tried a case with ad-hoc question when user does not have access to source table.

> I would leave it until CI is fixed

I tested this change against `master` (see last paragraph in PR description) and everything was green.

> @kamilmielnik it should be used.

If that's true - we can prove it.
I failed to do so though.

@ranquild are you sure this is needed?

**Review by ranquild — APPROVED** [review]
@kamilmielnik not, I'm not sure. I can approve this now but we might need to revert this later on.

**Comment by kamilmielnik** [comment]
> @kamilmielnik not, I'm not sure. I can approve this now but we might need to revert this later on.

I [asked in Slack](https://metaboat.slack.com/archives/C505ZNNH4/p1715612493095239). I'll merge this PR tomorrow if there are no objections.

**Pull request merged**
