### PR TITLE
Vim & Emacs keybindings

### LINKED ISSUE #16419: Vim and Emacs modes for native query editor
We could provide vim/emacs modes for the native query editor using the `setKeyboardHandler` method on [Ace](https://ace.c9.io/#nav=api&api=editor).

### PR DESCRIPTION
**Pull request by noahmoss**
Closes https://github.com/metabase/metabase/issues/16419

Adds a new `keybindings` user-local setting which controls the keybindings each user uses in the SQL editor (options are `vim`, `emacs` and `nil` (default))

Adds a new `SQL Editor Keybindings` section to account settings.

### CODE REVIEW

**Comment by noahmoss** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #38364** <a href="https://app.graphite.dev/github/pr/metabase/metabase/38364?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/38364?utm_source=stack-comment).

**Review by camsaul — APPROVED** [review]
👍 on the code itself, but honestly I'm not really convinced that this change is a good one to add, and I'm saying this as a biased Emacs user. One of the selling points of Metabase is ease of use, and every knob we add makes it more confusing and less user-friendly... think In 'N' Out Burger menu vs Jack-in-the-Box. A prominent VIM or Emacs editor keybindings option seems very engineery... are our power users (data analysists who breathe SQL) likely to use this feature? 

Let's get input from @brunobergher or someone else on product before merging this in

**Comment by noahmoss** [comment]
Yeah this was a quick experiment from our offsite hackathon, but it works pretty well. Definitely wasn't planning on merging without product feedback though.

I wonder if there's somewhere more hidden we could stick the option? @luizarakaki suggested maybe an "advanced options" toggle like we have on DB config pages

**Comment by camsaul** [comment]
Haha I just asked about this on the `#ama-product` Slack channel and I literally said the same thing, I would feel more comfortable with this being in an advanced options toggle

**Comment by noahmoss** [comment]
Closing per discussion with product

**Pull request closed without merging**
