### PR TITLE
recent_views stored in user local setting

### PR DESCRIPTION
**Pull request by adam-james-v**
Related: #27216

This modifies the view log event handler to write a user's views to their local settings map (stored as json in the appdb).

In order to do this, a new setting is defined in `metabase.events.view-log`: `user-recent-views` of type :json.

It stores the 10 most recent views. This is done because the endpoint `/api/activity/recent_views` filters out any archived items, but if an archived item somehow is viewed, it will still show up in recent_views. It's also probably useful just in case we want to show more than 5 recent views. But we don't want to stuff _tons_ of items into a user setting.

This will only modify the setting when the three 'read' events occur `#{:card-read :dashboard-read :table-read}`. I've pasted some notes at the end of this PR related to the other events that cause the view-log to update, I think double counts actually occur which should be fixed.

The `/api/activity/recent_views` endpoint is modified now to first check if the user has any views in their local settings. If they do, just use that. If they do not, we will run the old recent_views query (improved by #[29259](https://github.com/metabase/metabase/pull/29259)) to populate their views list.

This should be a better way to store recent_views as it will not require heavy queries to be run constantly. Once a user views anything, their setting will update, and so the endpoint will, in almost all cases, just do a quick fetch of a single setting value for that user.

Some additional changes:
- recent_views ‘backfilling’ (with the slow query) happens in the view_log namespace, so that any other users of the setting don’t have to know about it at all
- small change in a query processor middleware that passes :context on to the view events metadata. 
- the :card_read event that would trigger a recent_views change is now :card_query. This is because I need :context to see if a card is viewed in a collection (pinned, therefore not meant to count as a view) or :dashboard (also not meant to count as a view of the card).

---

some notes on what causes a view

:card-query
 - occurs when collection with pinned cards/models is opened. maybe shouldn't count as a view

:card-read
 - happens when you view a card, like, load it in the UI and are looking at it

:card-read AND :card-query
 - happens when you view a model, like, load it in the UI and are looking at it

:dashboard-read
 - happens when you view a dashboard

:card-create
 - when you save a card
 - this will probably cause double counts because it will save and then trigger a :card-read right away too

:table-read
 - when viewing a table.
 - when selecting a db/table in dropdowns in the Question editor

I think we need the view log topics to be much smaller: #{:card-read :dashboard-read :table-read}

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29631)

### CODE REVIEW

**Review by noahmoss — APPROVED** [review]
Nice, I think this is definitely an improvement over doing the full table query for recent views.

This is intentionally ignoring whether things are bookmarked, right? Would it make sense (and be possible) to not add bookmarked items to the list in the first place? Obviously there's still the edge case of something being un-bookmarked after being viewed but that doesn't seem too big of a deal

**Review by adam-james-v — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29631)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @noahmoss)

___
*[`src/metabase/api/activity.clj` line 262 at r1](https://reviewable.io/reviews/metabase/metabase/29631#gh-1166937859:-NTFKeAuCRKL9o-ybddr:bgcz7af) ([raw file](https://github.com/metabase/metabase/blob/b920d9d39dd8d94f4fa940608dea09644133f2d5/src/metabase/api/activity.clj#L262)):*
<details><summary><i>Previously, noahmoss (Noah Moss) wrote…</i></summary><blockquote>

nit: alignment
</blockquote></details>

This alignment is caused by the `model->id->items` binding further down in the let. I don't love it, but it's what my editor did, and I thought it was roughly what Metabase's formatting is. I can change it of course.

**Review by adam-james-v — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29631)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @noahmoss)

___
*[`src/metabase/api/activity.clj` line 266 at r1](https://reviewable.io/reviews/metabase/metabase/29631#gh-1166945005:-NTZTixG-6rpjp4L6nMd:b-896fix) ([raw file](https://github.com/metabase/metabase/blob/b920d9d39dd8d94f4fa940608dea09644133f2d5/src/metabase/api/activity.clj#L266)):*
<details><summary><i>Previously, noahmoss (Noah Moss) wrote…</i></summary><blockquote>

Not a big deal, but could this be done in a custom getter for the setting rather than the API handler? Would probably be better encapsulation in case anyone else uses this setting, they wouldn't have to think about the backfilling process
</blockquote></details>

Done.

**Review by noahmoss — APPROVED** [review]

**Comment by noahmoss** [comment]
@paoliniluis Should be fine to backport, but I'm not sure when we'll do a 44 release next (unless this is severe enough to warrant one on its own). What's preventing them from updating?

**Comment by paoliniluis** [comment]
@noahmoss driver issue, check the shared starburst channel :( 

is this the only PR we should backport? or there's another one?

**Pull request merged**
