### PR TITLE
Allow Metabase to use MySQL for the application db

### LINKED ISSUE #1332: Allow Metabase to use MySQL as the application database
Right now [the documentation](https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-the-metabase-jar-file.md#the-metabase-application-database) reads:

    The default settings use an H2 database, but other options are available.

H2 and Postgresql examples are given, but what about other RDMS vendors? The documentation should one of:

* Metabase only supports H2 and Postgresql, and nothing else

* Metabase supports H2 and Postgresql, but we haven't tested other providers.

* Metabase should support most common RDMS vendors. H2 and Postgresql have been tested.

### PR DESCRIPTION
**Pull request by agilliland**
resolves #1332

### CODE REVIEW

**Comment by agilliland** [comment]
@camsaul @tlrobinson care to give this a shot and verify that it's working?

**Comment by tlrobinson** [comment]
Seems to work fine for me. I was able to point it to a local MySQL database and go through the setup process, and add the same MySQL database as a database in Metabase, view all the tables, etc.

**Comment by caske33** [comment]
I'd really like to use this PR already inside docker. Does that mean that I have to build the image myself as the dockerhub image isn't updated yet?

**Comment by agilliland** [comment]
If you want to use an official Metabase build then yes, you'll have to wait a little longer until we release the final 0.13.0 build.  We are aiming for before Thanksgiving here in the US.

If you just want to test this out or are willing to be on our HEAD of development, which is beta code and not officially supported :wink:, then we have a dockerhub repo for that https://hub.docker.com/r/metabase/metabase-head/

We use the metabase-head image for Continuous Deployment of our internal staging system, so it's getting used on a regular basis.  Just know that it takes several minutes to start up because it has to pull dependencies for things like jar files and npm projects, plus it has to actually build all the code.

```
docker run -d -p 3000:3000 --name metabase-head metabase/metabase-head
```

Just use the instructions for running on Postgres in the current documentation http://www.metabase.com/docs/v0.12.1/operations-guide/running-metabase-on-docker.html and swap the values so that they apply to mysql

**Pull request merged**
