### PR TITLE
Pass dashboardId and dashcardId in QueryDownloadWidget in ViewFooter

### LINKED ISSUE #20868: Users with "No self-service" data access can't download report with filters
**Describe the bug**
Error happens when "no self-service" user tries to export question in csv/excel/json. Error only appears when the question is part of a dashboard with connected filter and user clicks on a question title.
Export works normally when opening the question directly from the collection.
For users with unrestricted data access, there's no error in any case.

**Logs**
```
{"via":[{"type":"clojure.lang.ExceptionInfo","message":"Invalid parameter: Card 1 does not have a template tag named nil.","data":{"type":"invalid-parameter","invalid-parameter":{"type":"date/all-options","value":"2018-03-05~2022-03-05","target":["dimension",["field",34,null]],"id":"f6dd6d27"},"allowed-parameters":null},"at":["metabase.query_processor.card$fn__68401$validate_card_parameters__68406$fn__68407","invoke","card.clj",160]}],"trace":[["metabase.query_processor.card$fn__68401$validate_card_parameters__68406$fn__68407","invoke","card.clj",160],["metabase.query_processor.card$fn__68401$validate_card_parameters__68406","invoke","card.clj",151],["metabase.query_processor.card$run_query_for_card_async","invokeStatic","card.clj",208],["metabase.query_processor.card$run_query_for_card_async","doInvoke","card.clj",169],["clojure.lang.RestFn","invoke","RestFn.java",826],["metabase.api.card$fn__71249","invokeStatic","card.clj",686],["metabase.api.card$fn__71249","invoke","card.clj",678],["compojure.core$wrap_response$fn__32273","invoke","core.clj",160],["compojure.core$wrap_route_middleware$fn__32257","invoke","core.clj",132],["compojure.core$wrap_route_info$fn__32262","invoke","core.clj",139],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",151],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",152],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",152],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",152],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",152],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",152],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",152],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285","invoke","core.clj",200],["metabase.server.middleware.auth$enforce_authentication$fn__65369","invoke","auth.clj",14],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285","invoke","core.clj",200],["compojure.core$make_context$handler__32313","invoke","core.clj",289],["compojure.core$make_context$fn__32317","invoke","core.clj",299],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$make_context$fn__32317","invoke","core.clj",300],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$make_context$fn__32317","invoke","core.clj",300],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$make_context$fn__32317","invoke","core.clj",300],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["metabase.api.routes$fn__76493$fn__76496","invoke","routes.clj",56],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285","invoke","core.clj",200],["clojure.lang.AFn","applyToHelper","AFn.java",160],["clojure.lang.AFn","applyTo","AFn.java",144],["clojure.core$apply","invokeStatic","core.clj",667],["clojure.core$apply","invoke","core.clj",662],["metabase.server.routes$fn__76638$fn__76639","doInvoke","routes.clj",57],["clojure.lang.RestFn","invoke","RestFn.java",436],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285","invoke","core.clj",200],["compojure.core$make_context$handler__32313","invoke","core.clj",289],["compojure.core$make_context$fn__32317","invoke","core.clj",299],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__32266","invoke","core.clj",153],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287","invoke","core.clj",197],["metabase.server.routes$fn__76626$fn__76628","invoke","routes.clj",41],["compojure.core$routes$fn__32285$f__32286","invoke","core.clj",198],["compojure.core$routes$fn__32285","invoke","core.clj",200],["metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73621","invoke","exceptions.clj",98],["metabase.server.middleware.exceptions$catch_api_exceptions$fn__73618","invoke","exceptions.clj",86],["metabase.server.middleware.log$log_api_call$fn__77104$fn__77105$fn__77106","invoke","log.clj",209],["metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info","invokeStatic","diagnostic.clj",15],["metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info","invoke","diagnostic.clj",9],["metabase.server.middleware.log$log_api_call$fn__77104$fn__77105","invoke","log.clj",201],["toucan.db$_do_with_call_counting","invokeStatic","db.clj",216],["toucan.db$_do_with_call_counting","invoke","db.clj",209],["metabase.server.middleware.log$log_api_call$fn__77104","invoke","log.clj",200],["metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80457","invoke","browser_cookie.clj",38],["metabase.server.middleware.security$add_security_headers$fn__55229","invoke","security.clj",148],["metabase.server.middleware.json$wrap_json_body$fn__79612","invoke","json.clj",64],["metabase.server.middleware.json$wrap_streamed_json_response$fn__79630","invoke","json.clj",98],["metabase.server.middleware.offset_paging$handle_paging$fn__55253","invoke","offset_paging.clj",42],["ring.middleware.keyword_params$wrap_keyword_params$fn__80724","invoke","keyword_params.clj",55],["ring.middleware.params$wrap_params$fn__80740","invoke","params.clj",69],["metabase.server.middleware.misc$maybe_set_site_url$fn__34379","invoke","misc.clj",59],["metabase.server.middleware.session$bind_current_user$fn__45722$fn__45723","invoke","session.clj",262],["metabase.server.middleware.session$do_with_current_user","invokeStatic","session.clj",243],["metabase.server.middleware.session$do_with_current_user","invoke","session.clj",235],["metabase.server.middleware.session$bind_current_user$fn__45722","invoke","session.clj",261],["metabase.server.middleware.session$wrap_current_user_info$fn__45709","invoke","session.clj",221],["metabase.server.middleware.session$wrap_session_id$fn__45695","invoke","session.clj",167],["metabase.server.middleware.auth$wrap_api_key$fn__65377","invoke","auth.clj",27],["ring.middleware.cookies$wrap_cookies$fn__80644","invoke","cookies.clj",216],["metabase.server.middleware.misc$add_content_type$fn__34362","invoke","misc.clj",27],["metabase.server.middleware.misc$disable_streaming_buffering$fn__34387","invoke","misc.clj",76],["ring.middleware.gzip$wrap_gzip$fn__80686","invoke","gzip.clj",86],["metabase.server.middleware.misc$bind_request$fn__34390","invoke","misc.clj",93],["metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80473","invoke","ssl.clj",38],["metabase.server$async_proxy_handler$fn__76877","invoke","server.clj",73],["metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a","handle",null,-1],["org.eclipse.jetty.server.handler.HandlerWrapper","handle","HandlerWrapper.java",127],["org.eclipse.jetty.server.Server","handle","Server.java",516],["org.eclipse.jetty.server.HttpChannel","lambda$handle$1","HttpChannel.java",388],["org.eclipse.jetty.server.HttpChannel","dispatch","HttpChannel.java",633],["org.eclipse.jetty.server.HttpChannel","handle","HttpChannel.java",380],["org.eclipse.jetty.server.HttpConnection","onFillable","HttpConnection.java",277],["org.eclipse.jetty.io.AbstractConnection$ReadCallback","succeeded","AbstractConnection.java",311],["org.eclipse.jetty.io.FillInterest","fillable","FillInterest.java",105],["org.eclipse.jetty.io.ChannelEndPoint$1","run","ChannelEndPoint.java",104],["org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","runTask","EatWhatYouKill.java",338],["org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","doProduce","EatWhatYouKill.java",315],["org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","tryProduce","EatWhatYouKill.java",173],["org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","run","EatWhatYouKill.java",131],["org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread","run","ReservedThreadExecutor.java",386],["org.eclipse.jetty.util.thread.QueuedThreadPool","runJob","QueuedThreadPool.java",883],["org.eclipse.jetty.util.thread.QueuedThreadPool$Runner","run","QueuedThreadPool.java",1034],["java.lang.Thread","run","Thread.java",829]],"cause":"Invalid parameter: Card 1 does not have a template tag named nil.","data":{"type":"invalid-parameter","invalid-parameter":{"type":"date/all-options","value":"2018-03-05~2022-03-05","target":["dimension",["field",34,null]],"id":"f6dd6d27"},"allowed-parameters":null},"message":"Invalid parameter: Card 1 does not have a template tag named nil.","invalid-parameter":{"type":"date/all-options","value":"2018-03-05~2022-03-05","target":["dimension",["field",34,null]],"id":"f6dd6d27"},"allowed-parameters":null}
```

**To Reproduce**
On sample database H2:
1. Create a simple question
2. Create a dashboard and add question from above
3. Add a filter to the dashboard and connect it to question
4. Create a new user with "no self service" data access; and view only access to the collection
5. With that user open dashboard and click on a title of the question
6. Export the data
7. Open the exported data. There will be a stack trace of an error instead of correct data inside.

**Expected behavior**
I expected to download a csv file. Got error instead

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.13.0-27-generic",
    "user.language": "en",
    "user.timezone": "Europe/Ljubljana"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Relatively high. External users can't download reports directly from the dashboard. So we need to prepare exports from our side. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by kanobi**
Closes #20868

### Description
There was a bug for sandboxed users. They couldn't export the data if they viewed a filtered question from a dashboard.

I saw that dashcardId and dashboardId were not being passed for QueryDownloadWidget in the ViewFooter.jsx
Because those two fields were null, the getDownloadButtonParams function in frontend/src/metabase/query_builder/components/QueryDownloadWidget/utils.ts didn't work correctly. It wrongly assumed that the question was of type isSavedQuery instead of isDashboard

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Create a new dashboard with 1 question and a filter which is connected to the question
2. Create a new sandboxed user with no data access
3. Login with this new user and access the dashboard 
4. Use a filter and then click on the question
5. In the question viewer export the dataset
6. Check that the exported data includes correct results (previously it contained a stack trace of the error)

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29896)

### CODE REVIEW

**Comment by kanobi** [comment]
I'm not that familiar with testing, so maybe somebody can complete this with a frontend test

**Comment by nachimehta** [comment]
@kanobi is there a recommended fast fix in the mean time? we're experience downtime in production because of this

**Comment by kanobi** [comment]
@nachimehta The fix in this PR worked when I opened it. It's just adding a few missing parameters in the template for the download button. I haven't checked in the latest build.

**Comment by alxnddr** [comment]
@kanobi thanks for your contribution! I cherry-picked your commits into a separate branch https://github.com/metabase/metabase/pull/33317 and we will merge it if CI is green. The fix should be included in the next maintenance release x.47.1

**Pull request closed without merging**
