### PR TITLE
Make sure GET /api/collection/tree works regardless of Collection order

### LINKED ISSUE #14280: Moved collections not being correctly included in `api/collection/tree` API response
**Describe the bug**
While trying to do some organization on our stats instance I was moving around a bunch of collections that had "Test" data we've made into a new parent "Test" folder to clean up our sidebar a bit.  After moving a few, I noticed collections I'd moved weren't reflecting in the new sidebar (they do reflect properly in the move modal). Strangely this is only happening with a few. Another couple I'd moved are showing up exactly as expected.

**Logs**
JS console
```Uncaught TypeError: can't access property "length", n.name is undefined```

That error makes more sense after inspecting the API response. Somehow there's a child node with no info wrapping one of the moved collections. I'm not entirely sure what could cause the API to generate a response like this. I also moved 3 collections, so I'm not sure why the other ones aren't showing up.

```
  {
    "description": "If you're testing things out, try and put things here.",
    "archived": false,
    "children": [
      {
        "children": [
          {
            "description": "Automatically generated cards.",
            "archived": false,
            "slug": "questions_for__a_look_at_your_people_table_",
            "color": "#509EE3",
            "name": "Questions for \"A look at your People table\"",
            "personal_owner_id": null,
            "id": 115,
            "location": "/179/18/",
            "namespace": null
          }
        ]
      }
    ],
    "slug": "testing",
    "color": "#509EE3",
    "name": "Testing",
    "personal_owner_id": null,
    "id": 179,
    "location": "/",
    "namespace": null
  },
```

**To Reproduce**
I haven't found a consistent reproduction yet, but this is what initially happened.

1. Create a new collection
2. Navigate to an existing collection.
2. Use the "Edit collection" action to open up the collection details modal and select a new parent collection from the dropdown.
3. Move the existing collection to the new collection.
4. Navigate to the new "parent" collection and no content is visible.

**Expected behavior**
The moved collection is visible under its new parent immediately.

**Information about your Metabase Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: Windows
- Metabase version: 0.38-rc1
- Metabase hosting environment:
- Metabase internal database: Postgres

**Severity**
Severe, can result in items becoming inaccessible.

### PR DESCRIPTION
**Pull request by camsaul**
I think the issue is already fixed... I just wrote an extra test and enabled the cypress test and it seems to be passing.

Fixes #14280

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
FYI: [this Cypress failure](https://app.circleci.com/pipelines/github/metabase/metabase/11872/workflows/173648f5-9799-4926-a9fa-008ff38f708e/jobs/437844) is now fixed on `master` (bbc49e682a423b016deb58d1c72ea0945af7d5a8). Feel free to rebase and run the tests again.

[This one](https://app.circleci.com/pipelines/github/metabase/metabase/11872/workflows/173648f5-9799-4926-a9fa-008ff38f708e/jobs/437847), OTOH, feels related to the changes.

**Comment by mazameli** [comment]
Who needs to review this, @camsaul?

**Comment by nemanjaglumac** [comment]
### The bug
Cypress keeps failing because the "New collection" is not open by default and doesn't even have a chevron icon next to it. 

image

Also, note that when you enter a "New collection", the UI doesn't show its children:
image

I managed to repro this behavior manually in local dev environment and also using metabase-head.

### GIf recordings
_Note that it is still possible to see "First collection" and "Second collection" as "New collection"'s descendants in a modal, but depending on where you save some random collection "Foo", the UI is different:

1. If "Foo" is saved in any of the descendants, the chevron shows up but you can't open "New collection" and you can't see Foo inside (neither as sub-folder, nor in UI)


2. If "Foo" is saved directly in a "New collection", you can see it as a sub-folder, but not in the UI:


Hope this helps 🤨

**Review by robdaemon — APPROVED** [review]

**Review by nemanjaglumac — APPROVED** [review]
I can confirm that the underlying issue is now fixed.
Children collections are moved inside a new parent and are accessible within it.
image


There is another part of the issue that is not covered by this fix. The parent should be immediately open after we move collection(s) inside of it, and this doesn't happen.
I'll open a follow up issue for that.

**Pull request merged**
