### PR TITLE
Fix syncing sample dataset :disappointed:

### LINKED ISSUE #2706: error getting metadata for sample database
This is on Metabase `master`

I'm seeing this stacktrace come up when the sample dataset is synced

```
06-06 15:50:16 ERROR events.sync-database :: Error syncing Database: 1 #error {
 :cause Column "PUBLIC._METABASE_METADATA.ID" not found; SQL statement:
SELECT * FROM "PUBLIC"."_METABASE_METADATA" ORDER BY "PUBLIC"."_METABASE_METADATA"."ID" ASC [42122-191]
 :via
 [{:type org.h2.jdbc.JdbcSQLException
   :message Column "PUBLIC._METABASE_METADATA.ID" not found; SQL statement:
SELECT * FROM "PUBLIC"."_METABASE_METADATA" ORDER BY "PUBLIC"."_METABASE_METADATA"."ID" ASC [42122-191]
   :at [org.h2.message.DbException getJdbcSQLException DbException.java 345]}]
 :trace
 [[org.h2.message.DbException getJdbcSQLException DbException.java 345]
  [org.h2.message.DbException get DbException.java 179]
  [org.h2.message.DbException get DbException.java 155]
  [org.h2.expression.ExpressionColumn optimize ExpressionColumn.java 147]
  [org.h2.command.dml.Select prepare Select.java 852]
  [org.h2.command.Parser prepareCommand Parser.java 257]
  [org.h2.engine.Session prepareLocal Session.java 560]
  [org.h2.engine.Session prepareCommand Session.java 501]
  [org.h2.jdbc.JdbcConnection prepareCommand JdbcConnection.java 1188]
  [org.h2.jdbc.JdbcPreparedStatement <init> JdbcPreparedStatement.java 73]
  [org.h2.jdbc.JdbcConnection prepareStatement JdbcConnection.java 276]
  [com.mchange.v2.c3p0.impl.NewProxyConnection prepareStatement NewProxyConnection.java 213]
  [clojure.java.jdbc$prepare_statement invokeStatic jdbc.clj 468]
  [clojure.java.jdbc$prepare_statement doInvoke jdbc.clj 432]
  [clojure.lang.RestFn invoke RestFn.java 425]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.RestFn applyTo RestFn.java 132]
  [clojure.core$apply invokeStatic core.clj 650]
  [clojure.core$apply invoke core.clj 641]
  [clojure.java.jdbc$db_query_with_resultset invokeStatic jdbc.clj 833]
  [clojure.java.jdbc$db_query_with_resultset invoke jdbc.clj 790]
  [clojure.java.jdbc$query invokeStatic jdbc.clj 866]
  [clojure.java.jdbc$query doInvoke jdbc.clj 838]
  [clojure.lang.RestFn invoke RestFn.java 425]
  [metabase.driver.generic_sql$query invokeStatic generic_sql.clj 198]
  [metabase.driver.generic_sql$query invoke generic_sql.clj 195]
  [metabase.driver.generic_sql$query invokeStatic generic_sql.clj 201]
  [metabase.driver.generic_sql$query invoke generic_sql.clj 195]
  [metabase.driver.generic_sql$table_rows_seq invokeStatic generic_sql.clj 237]
  [metabase.driver.generic_sql$table_rows_seq invoke generic_sql.clj 235]
  [metabase.driver$eval17049$fn__17143$G__17034__17152 invoke driver.clj 41]
  [metabase.sync_database.sync$sync_metabase_metadata_table_BANG_ invokeStatic sync.clj 46]
  [metabase.sync_database.sync$sync_metabase_metadata_table_BANG_ invoke sync.clj 30]
  [metabase.sync_database.sync$maybe_sync_metabase_metadata_table_BANG_ invokeStatic sync.clj 201]
  [metabase.sync_database.sync$maybe_sync_metabase_metadata_table_BANG_ invoke sync.clj 196]
  [metabase.sync_database.sync$update_data_models_from_raw_tables_BANG_ invokeStatic sync.clj 220]
  [metabase.sync_database.sync$update_data_models_from_raw_tables_BANG_ invoke sync.clj 203]
  [metabase.sync_database$sync_database_with_tracking_BANG_$fn__34402 invoke sync_database.clj 82]
  [metabase.sync_database$sync_database_with_tracking_BANG_ invokeStatic sync_database.clj 74]
  [metabase.sync_database$sync_database_with_tracking_BANG_ invoke sync_database.clj 68]
  [clojure.core$partial$fn__4763 invoke core.clj 2528]
  [metabase.driver$fn__17279 invokeStatic driver.clj 236]
  [metabase.driver$fn__17279 invoke driver.clj 236]
  [metabase.driver$eval17049$fn__17225$G__17016__17234 invoke driver.clj 41]
  [metabase.sync_database$sync_database_BANG_ invokeStatic sync_database.clj 43]
  [metabase.sync_database$sync_database_BANG_ doInvoke sync_database.clj 24]
  [clojure.lang.RestFn invoke RestFn.java 410]
  [metabase.events.sync_database$process_sync_database_event$fn__45280 invoke sync_database.clj 32]
  [clojure.core$binding_conveyor_fn$fn__4676 invoke core.clj 1938]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}
```

If you remove the order-by condition then this seems to work just fine, but I'm not sure exactly why ...

```clojure
(merge {:select   [:*]}
  (when pk-field
    {:order-by [[(qualify+escape table pk-field) :asc]]}))
```

Previously this function used to just do this, so I'm not sure if we need that order-by clause ...

```clojure
(k/select (korma-entity database table))
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #2706.

This was ultimately caused by `metabase.driver/table-rows-seq` expecting a `Table` but getting passed a `RawTable`; it was fetching a primary key `Field` whose `table_id` was the `id` of the aforementioned **`RawTable`** (:scream:). This wasn't caught in tests because in some cases their IDs matched (e.g. `RawTable 4 <-> Table 4`); when syncing the sample dataset, this wasn't the case, exposing the bug.

Added additional checks and reworked code to work as intended.

### CODE REVIEW

**Comment by agilliland** [comment]
As I mentioned in the original issue that was filed, removing that condition to order the results by the PK field of the table was all that was needed to resolve this problem and it looks like you did that and changed the code to just `{:select [:*]}`, but I'm not clear why you changed the driver interface at all.

In specific, I see no real reason to change the interface such that you force `table-rows-seq` to work off of a `RawTableInstance`.  That seems like a less ideal way for the interface to be defined.  The previous version of the function expected a MAP which represented a table and only need to have a `:name` and `:schema` to work properly.  I would recommend sticking with that approach.  With the changes you propose here I think you are making that function overly specific for no reason.

**Comment by camsaul** [comment]
The problem wasn't that we were ordering by PK so much as it was that the method signature wasn't clear and we were attempting to order by a PK that didn't exist because of it.

`table-rows-seq` was getting passed a `RawTableInstance`, so it was *extremely* misleading to have a `Table`-esque object coming in. I mistook it for a `Table` which lead to the confusion in the first place. So all I did was clarify that what gets passed is a `RawTable`, not a `Table`.

Consider if the same code was written in Java:

```java
public static Object tableRowsSeq(Map table) { ...}
```

vs.
```java
public static List<TableRow> tableRowsSeq(RawTable table) { ... }
```

You'd use the second (more-specific) method signature. I'd rather error on the side of being overly-strict with types than let issues like this creep in.

**Comment by agilliland** [comment]
The fact that you accidentally misinterpreted the function argument and applied some code which was never going to work is not really a reason to change the protocol and force a more strict function signature.  There was nothing wrong with the function definition.

In general, there is no reason for the driver code to be coupled to Metabase's internal entity models such `Table` or `RawTable`.  Having a more generic function signature that simply accepts a MAP ensures that fewer changes are needed on the driver protocol over time and removes any misconceptions that drivers should be expecting specific entity models.

The only change that was needed was to remove the offending code in the driver `(field/Field (table/pk-field-id table))` which attempted to reach out into the rest of the Metabase system and lookup things that it shouldn't have needed.  And if you wanted to update some comments to clarify the function arguments.

**Comment by camsaul** [comment]
`ad absurdum` a method signature that didn't specify any type information at all would be even more resistant to changes in the future. But I absolutely think it's important that we make it as hard as possible for people writing code to do the wrong thing. When things are ambiguous, it's easy to shoot yourself in the foot; when they're specific, it's much harder to do so. 

We can always make the method more flexible if the need arises in the future; but until a valid reason to do so comes up we should error on the side of safety, specificity, and rigidity.

**Comment by agilliland** [comment]
There are other ways to remove ambiguity that don't require changing what are meant to be well defined interfaces such as the IDriver protocol.

When it's all said and done, the ultimate problem you are creating here is that you are asking drivers to import classes such as `metabase.models.raw_table.RawTableInstance` and that's what should be avoided.  There is absolutely no reason for a driver implementation to even know that class exists.

By doing that you are subverting the design goals of ensuring the drivers are well encapsulated and fully decoupled from the rest of the Metabase system and you are creating a situation where changes to model classes like RawTableInstance can end up requiring changes to driver implementations, which is exactly what we don't want.

**Comment by camsaul** [comment]
No one needs to import any classes. It's merely done for the sake of clarity.

**Comment by agilliland** [comment]
You've added code in the generic-sql driver which is clearly importing and referencing the RawTableInstance class which is what I consider a bad idea.  Again, the driver code should not know about that class nor have any dependency on it.

**Comment by camsaul** [comment]
@agilliland ok changed this to remove the extra type information and safety-checks.

**Comment by agilliland** [comment]
cool.  lgtm 👍

**Pull request merged**
