### PR TITLE
Move data for OG Test Database to EDN File :yum:

### LINKED ISSUE #671: Convert default test dataset to EDN format
Cleaner. Instead of generating it in code when loading the unit tests.

### PR DESCRIPTION
**Pull request by camsaul**
Minor refactor. This was bugging me. We have a big ~1500 line Clojure file that contained all the static data for the OG "Test Database" test dataset. All of the other datasets like `sad-toucan-incidents` live in EDN files. 

Resolves #671

### CODE REVIEW

**Comment by salsakran** [comment]
My $0.02 - if we're going to have a serialization format for test data, I'd prefer to have the same format be used for the demo dataset. And ideally this should be a format that is easy to generate from postgresql, sqllite or other source databases. 

EDN is a dead end.

**Comment by agilliland** [comment]
haha.  @camsaul always getting "itchy".  i don't spend as much time on the test dataset code as you do and this was bugging me as well, so :+1:

**Comment by camsaul** [comment]
@salsakran The demo dataset is generated programmatically and saved as an H2 file. These are clojure data definitions that are used to create temporary databases during unit testing for everything from Mongo to SQL Server.

**Comment by salsakran** [comment]
I'm strictly in single digit cents land in terms of caring. My general bias in things like this is to use serialization formats uniformly across various pieces of the greater overall system (which in this case typically involves ingestion + transformation upstream of the DB) rather than have formats tied to a given stack/language. 

Inflation has turned my $0.02 into $0.019999945 since the last comment.

**Comment by camsaul** [comment]
What are you suggesting then? That data used by the *Clojure unit tests* should be saved as H2 files? And we should write a whole extra later to load the schemas and data from those files so we can translate them to other databases like Mongo or SQL Server?

**Comment by salsakran** [comment]
JSON.

$0.0145343

**Comment by camsaul** [comment]
JSON doesn't have timestamp literals. `-$55.00`

**Comment by agilliland** [comment]
You guys are wasting time now.  And filling up my inbox.

I think EDN is fine.  JSON could be cool, but we definitely don't need to do that right now.

`$1,483,299,857.32`

**Pull request merged**
