### PR TITLE
Put bulk actions above popovers in collections

### PR DESCRIPTION
**Pull request by rafpaf**
With the collection table now inside a `@container`, popovers were being created above the bulk actions toast (z-axis-wise). This branch fixes this by changing which element serves as the container (we'll use `CollectionTable`, not `CollectionRoot` - both are equally good), and moving the bulk actions toast just outside this container.

Now the toast appears above popovers:

This branch also restores the margin-left adjustment that is needed to correct the position of the bulk actions toast when the sidebar is open. This adjustment was recently removed because the @container query fixes this problem, but now that the toast is not inside the @container, we need to restore that solution.

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#42512** <a href="https://app.graphite.dev/github/pr/metabase/metabase/42512?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by iethree — APPROVED** [review]
nice! an elegant, simple solution.

**Comment by rafpaf** [comment]
### Merge activity

* **May 10, 11:57 AM EDT**: @rafpaf merged this pull request with [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/42512).

**Comment by rafpaf** [comment]
lol, I'm so sorry for tagging you, @container! I'm of course referring to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries

**Pull request merged**
