### PR TITLE
Wipe stacktrace to users during SAML/JWT login

### LINKED ISSUE #14820: Don't show stacktrace to users during SAML/JWT login
**Describe the bug**
When there's a misconfiguration or error of SAML, then a pretty-error is shown to the users - including an support email.
This leads to confusion about where the problem is - many thinking it's something wrong with Metabase.
Do not show stacktrace or support email address.

**Reproduce: SAML**
1. Setup Metabase with SAML - I just tried with Google SAML, but other IdP's probably behavior similar
2. Verify login works in incognito-window.
3. Admin > Settings > General > change the Site URL from https to http
3. In incognito-window, try logging in again - Metabase will throw the following error screen and stop the login process:
image

**Reproduce: JWT**
1. Setup Metabase with JWT (just needs to be enabled, JWT endpoint is not required)
2. In incognito-window go to `http://localhost:3000/auth/sso?jwt=test` - errors with non-pretty JSON stacktrace to end-user:
```
{"cause":"Message seems corrupt or manipulated.","via":[{"type":"clojure.lang.ExceptionInfo","message":"Message seems corrupt or manipulated.","data":{"type":"validation","cause":"header"},"at":["buddy.sign.jws$parse_header","invokeStatic","jws.clj",88]}],"trace":[["buddy.sign.jws$parse_header","invokeStatic","jws.clj",88],["buddy.sign.jws$parse_header","invoke","jws.clj",77],["buddy.sign.jws$unsign","invokeStatic","jws.clj",153],["buddy.sign.jws$unsign","invoke","jws.clj",147],["buddy.sign.jwt$unsign","invokeStatic","jwt.clj",111],["buddy.sign.jwt$unsign","invoke","jwt.clj",107],["metabase_enterprise.sso.integrations.jwt$login_jwt_user","invokeStatic","jwt.clj",56],["metabase_enterprise.sso.integrations.jwt$login_jwt_user","invoke","jwt.clj",54],["metabase_enterprise.sso.integrations.jwt$fn__61588","invokeStatic","jwt.clj",76],["metabase_enterprise.sso.integrations.jwt$fn__61588","invoke","jwt.clj",72],["clojure.lang.MultiFn","invoke","MultiFn.java",229],["metabase_enterprise.sso.api.sso$fn__58202$fn__58204","invoke","sso.clj",63],["metabase_enterprise.sso.api.sso$fn__58202","invokeStatic","sso.clj",62],["metabase_enterprise.sso.api.sso$fn__58202","invoke","sso.clj",58],["compojure.core$wrap_response$fn__11944","invoke","core.clj",160],["compojure.core$wrap_route_middleware$fn__11928","invoke","core.clj",132],["compojure.core$wrap_route_info$fn__11933","invoke","core.clj",139],["compojure.core$wrap_route_matches$fn__11937","invoke","core.clj",151],["compojure.core$routes$fn__11956$f__11957","invoke","core.clj",198],["compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__11937","invoke","core.clj",153],["compojure.core$routes$fn__11956$f__11957","invoke","core.clj",198],["compojure.core$routes$fn__11956","invoke","core.clj",200],["compojure.core$routes$fn__11956$f__11957","invoke","core.clj",198],["compojure.core$routes$fn__11956","invoke","core.clj",200],["compojure.core$make_context$handler__11984","invoke","core.clj",287],["compojure.core$make_context$fn__11986","invoke","core.clj",296],["compojure.core$routes$fn__11956$f__11957","invoke","core.clj",198],["compojure.core$routes$fn__11956","invoke","core.clj",200],["compojure.core$routes$fn__11956$f__11957","invoke","core.clj",198],["compojure.core$routes$fn__11956","invoke","core.clj",200],["compojure.core$make_context$handler__11984","invoke","core.clj",287],["compojure.core$make_context$fn__11986","invoke","core.clj",296],["compojure.core$routes$fn__11956$f__11957","invoke","core.clj",198],["compojure.core$routes$fn__11956","invoke","core.clj",200],["compojure.core$routes$fn__11956$f__11957","invoke","core.clj",198],["compojure.core$routes$fn__11956","invoke","core.clj",200],["metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__79024","invoke","exceptions.clj",96],["metabase.server.middleware.exceptions$catch_api_exceptions$fn__79021","invoke","exceptions.clj",84],["metabase.server.middleware.log$log_api_call$fn__80862","invoke","log.clj",187],["metabase.server.middleware.security$add_security_headers$fn__78987","invoke","security.clj",142],["metabase.server.middleware.json$wrap_json_body$fn__80643","invoke","json.clj",64],["metabase.server.middleware.json$wrap_streamed_json_response$fn__80661","invoke","json.clj",98],["ring.middleware.keyword_params$wrap_keyword_params$fn__81203","invoke","keyword_params.clj",55],["ring.middleware.params$wrap_params$fn__81219","invoke","params.clj",69],["metabase.server.middleware.misc$maybe_set_site_url$fn__35106","invoke","misc.clj",58],["metabase.server.middleware.session$bind_current_user$fn__42732$fn__42733","invoke","session.clj",277],["metabase.server.middleware.session$do_with_current_user","invokeStatic","session.clj",258],["metabase.server.middleware.session$do_with_current_user","invoke","session.clj",250],["metabase.server.middleware.session$bind_current_user$fn__42732","invoke","session.clj",276],["metabase.server.middleware.session$wrap_current_user_info$fn__42719","invoke","session.clj",236],["metabase.server.middleware.session$wrap_session_id$fn__42705","invoke","session.clj",182],["metabase.server.middleware.auth$wrap_api_key$fn__55051","invoke","auth.clj",27],["ring.middleware.cookies$wrap_cookies$fn__81123","invoke","cookies.clj",216],["metabase.server.middleware.misc$add_content_type$fn__35089","invoke","misc.clj",27],["metabase.server.middleware.misc$disable_streaming_buffering$fn__35114","invoke","misc.clj",75],["ring.middleware.gzip$wrap_gzip$fn__81165","invoke","gzip.clj",86],["metabase.server.middleware.misc$bind_request$fn__35117","invoke","misc.clj",92],["metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80879","invoke","ssl.clj",38],["metabase.server$async_proxy_handler$fn__80476","invoke","server.clj",71],["metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a","handle",null,-1],["org.eclipse.jetty.server.handler.HandlerWrapper","handle","HandlerWrapper.java",127],["org.eclipse.jetty.server.Server","handle","Server.java",516],["org.eclipse.jetty.server.HttpChannel","lambda$handle$1","HttpChannel.java",383],["org.eclipse.jetty.server.HttpChannel","dispatch","HttpChannel.java",556],["org.eclipse.jetty.server.HttpChannel","handle","HttpChannel.java",375],["org.eclipse.jetty.server.HttpConnection","onFillable","HttpConnection.java",273],["org.eclipse.jetty.io.AbstractConnection$ReadCallback","succeeded","AbstractConnection.java",311],["org.eclipse.jetty.io.FillInterest","fillable","FillInterest.java",105],["org.eclipse.jetty.io.ChannelEndPoint$1","run","ChannelEndPoint.java",104],["org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","runTask","EatWhatYouKill.java",336],["org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","doProduce","EatWhatYouKill.java",313],["org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","tryProduce","EatWhatYouKill.java",171],["org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","run","EatWhatYouKill.java",129],["org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread","run","ReservedThreadExecutor.java",375],["org.eclipse.jetty.util.thread.QueuedThreadPool","runJob","QueuedThreadPool.java",773],["org.eclipse.jetty.util.thread.QueuedThreadPool$Runner","run","QueuedThreadPool.java",905],["java.lang.Thread","run","Thread.java",834]],"data":{"type":"validation","cause":"header"},"message":"Message seems corrupt or manipulated.","type":"class clojure.lang.ExceptionInfo"}
```
But there's nothing in the log console besides: `2021-03-28 13:11:19,068 ERROR api.sso :: Error returning SSO entry point`

**Expected behavior**
- Do not show email support email address, since is not for end-users.
- Do not show stacktrace, since it's not the full stacktrace anyway (it seems).
- If possible, make the error message easier for admins and users to understand that it's a configuration problem and need an admin of the instance and/or IdP to fix it.
- And include a link back to login page

**Severity**
This might also be noted as a "security risk" in internal security audits, even though it does not show any sensitive information that isn't available by looking at the source code.

**Information about your Metabase Installation:**
Tested 1.36.11 and 1.37.9

**Additional context**
Related to #14819

### PR DESCRIPTION
**Pull request by dragonsahead**
Simplify the messages and point to the instance administrator

Should fix https://github.com/metabase/metabase/issues/14820

### CODE REVIEW

**Comment by brunobergher** [comment]
Thanks for taking this on! Mind sharing a screenshot? I don't have an environment set up for dev.

**Comment by paoliniluis** [comment]
sure, I just removed HTML code, but can tune it as you wish as the html template for any SSO error is here: https://github.com/metabase/metabase/blob/master/enterprise/backend/src/metabase_enterprise/sandbox/api/error_page.mustache
image

**Comment by brunobergher** [comment]
Thanks for sharing. It could be prettier, but this is plenty. Thank you for taking it on, from a product perspective this is good to go.

**Review by camsaul — APPROVED** [review]
works for me

**Pull request merged**
