### PR TITLE
Detect if file is blank or bad for SQLite DB connection

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to #16199
Problem
- If you put in a filename for a nonexistent file in the SQLite filename connection, MB will happily eat it up until you try to issue queries, whereupon which it will explode

Solution
- Don't let user do that. Check if db file exists straight up and if it's a proper SQLite file

### CODE REVIEW

**Comment by noahmoss** [comment]
My one nitpick about this is that `can-connect?` doesn't cover all possible cases where a DB connection might fail if it's just checking for the existence of the file. If the SQLite file is locked by another application, `can-connect?` would pass but an exception is still thrown on the backend when a connection is attempted. (I've been running into this situation in the wild.)

The docstring for the `can-connect?` multimethod also says: 

> Check whether we can connect to a `Database` with `details-map` and perform a simple query. For example, a SQL
>   3   database might try running a query like `SELECT 1;`. 

Would it be worth changing `can-connect?` to match this description? Maybe that doesn't need to be in this PR in which case I'm happy to stamp this and file a follow-up issue.

**Comment by howonlee** [comment]
> My one nitpick about this is that `can-connect?` doesn't cover all possible cases where a DB connection might fail if it's just checking for the existence of the file. If the SQLite file is locked by another application, `can-connect?` would pass but an exception is still thrown on the backend when a connection is attempted. (I've been running into this situation in the wild.)
> 
> The docstring for the `can-connect?` multimethod also says:
> 
> > Check whether we can connect to a `Database` with `details-map` and perform a simple query. For example, a SQL
> > database might try running a query like `SELECT 1;`.
> 
> Would it be worth changing `can-connect?` to match this description? Maybe that doesn't need to be in this PR in which case I'm happy to stamp this and file a follow-up issue.

SQLite has concurrent reads on files and a total lock on writes in non-WAL mode which would prevent the file open from MB in the first place but I'll shove in a null query anyhow.

**Comment by noahmoss** [comment]
@howonlee that's what I mean, if another app has an exclusive lock, MB can't do any reads but `can-connect?` returns `true`. The UI in that case is that MB appears to add the DB successfully but it doesn't contain any data, so we probably want to fail fast with an error message

**Comment by howonlee** [comment]
> @howonlee that's what I mean, if another app has an exclusive lock, MB can't do any reads but `can-connect?` returns `true`. The UI in that case is that MB appears to add the DB successfully but it doesn't contain any data, so we probably want to fail fast with an error message instead

But we open the file when looking at it for `can-connect`, so it'll block on the exclusive lock, unless you're talking about the problems nfs has with advisory locking?

Anyways, moot point

**Comment by noahmoss** [comment]
> But we open the file when looking at it for `can-connect`, so it'll block on the exclusive lock, unless you're talking about the problems nfs has with advisory locking?

Hmm...I tried running this branch locally and I see the error message when I give it a non-existent file, but when I give it a file being actively used by another app it lets me add the DB with no error, but I subsequently see this in the logs when I try to view an x-ray:

```
2021-06-08 00:13:49,733 WARN sync.util :: Error syncing _metabase_metadata table for sqlite Database 3 'Test'
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
```

**Comment by noahmoss** [comment]
Huh, I played around with it more and it seems that `SELECT 1` still succeeds when SQLite is locked, but `SELECT 1 from table_name` returns an error. Maybe this is an error that should just be surfaced better elsewhere in the app. I'll file a separate issue.

**Review by noahmoss — APPROVED** [review]

**Pull request merged**
