### PR TITLE
Add Basic Authentication to Druid

### LINKED ISSUE #18808: Add Basic Authentication to Druid Queries
Problem description:
When defining a database from type "Druid", there is no option to set a secure connection via "Basic Authentication".
Hence, it basically eliminates the possibility to use a security option that is supported by the Druid backend and by Druid's native UI, since if we will enable this option, Metabase will not be able to get results, due to missing authentication.

Proposed solution:
On Metabase, in Druid DB settings (Admin panel), add an option (toggle) for "Basic Authentication" . If enabled, it will allow the admin user to add the token. Also, once enabled, all the calls to druid will use the token as a basic authentication header.

**How important is this feature to you?**
Feature is important, as without it, it expose security risk in Druid.

**Additional context**
druid_ui (1)

The development of this feature will be sponsored by Mobitech.io :
https://www.upwork.com/ab/applicants/1455154266814951424/job-details

### PR DESCRIPTION
**Pull request by nbotelhodev**
### Objective 
This PR allows using of basic header authentication only in Druid Database connection, files modified are exclusive of Druid code. 

### Feature 
It's a simple adjustment, I added three fields in additional options UI and receive the values in Druid driver core to put in the basic header option of `clj-http`.

### Tests
- [X] My tests check if the basic header option is in clj-http request options or not.
- [X] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [X] If there are changes to the backend codebase, run the backend tests with `Clojure -X:dev:test`
- [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/20412)

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
Cool, this LGTM.

I had to approve this to run on CI so when that's done we can merge. Some of the jobs should fail since we don't inject credentials into third-party PRs but we can still merge anyway if Druid tests and linters pass

**Comment by gpodevijn** [comment]
Thanks again for the work, it'll be very useful for us. 
Is there any chance that this PR will be merged in the next release?

**Comment by gpodevijn** [comment]
I just realised that the token's box is not a "password" box which makes the token visible from the UI (and probably not encrypted in the DB). 

We're using Imply's Druid API pass as the token value to be able to connect to Druid. Would it be possible to hide and encrypt the token value?

Thank you!

image

**Comment by flamber** [comment]
@gpodevijn Encryption is handled for everything in `metabase_database.details` https://www.metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html

And change `type: string` to `type: password` or `type: secret`, that should automatically prevent it from being included in responses.

**Review by camsaul — DISMISSED** [review]
- Fix merge conflicts 
- Fix plaintext passwords

Then request another review 💪

**Comment by Ray33** [comment]
@flamber @camsaul  Can you please update about the status of this PR ?

**Comment by flamber** [comment]
@Ray33 It's written right above your comment.

**Comment by Ray33** [comment]
@flamber Changes were done . Please check.

**Comment by flamber** [comment]
@Ray33 And @nbotelhodev has already requested a review from Cam a few hours ago, so you'll have to wait until there's a review.

**Comment by Ray33** [comment]
@kulyk Can you please update if there are further fixes that need to be done here?
(if not, what the merge status is?)

**Comment by kulyk** [comment]
@Ray33 apologies, I've mentioned this PR by accident; I'm not the right person to look at those changes. Cam is currently out of the office and should be able to review the change once he gets back. Thank you!

**Comment by nbotelhodev** [comment]
Hi @camsaul, 
Could you help me to close this PR, please? I need to finish this adjustment with @Ray33. 
Thank you!

**Comment by Ray33** [comment]
Hi @camsaul,
Could you help to merge this PR, please?

**Comment by nbotelhodev** [comment]
Hey guys @camsaul @gpodevijn @flamber 
Help me merge this MR, please!

**Comment by Ray33** [comment]
@flamber can you please help with merge and rollout ?

**Comment by camsaul** [comment]
@metabase/core-backend-qp let's see if we can get this over the line for the next cycle

**Comment by carstenkadmos** [comment]
having this would help us a great deal as well! Thanks

**Review by metamben — APPROVED** [review]
LGTM

**Pull request merged**
