### PR TITLE
Question based filter params

### PR DESCRIPTION
**Pull request by joneath**
Addresses #6820

### CODE REVIEW

**Comment by joneath** [comment]
@mazameli I have the initial UI in place expect for the preview/placeholder in the card picker select but that should be very easy to add. I do have a couple questions though:

1. What should we do with the "required" toggle? Toggling it on gives the user a text box to input a default value. Can this work when the user has selected a question's results for the filter values? If so how would this work?
2. In using the CardPicker from Pulses there is a boolean flag called `attachmentsEnabled` which is required to be true otherwise I get the error message `Raw data cannot be included in pulses` for my cards. What are attachments and can I just go with this hack or should I rework the component?

Here's where i'm at:
screen shot 2018-02-25 at 13 43 40

**Comment by salsakran** [comment]
We're only going to allow questions that have a result with a single column.
@camsaul I think this should be a specialized endpoint so that the query builder native editor component doesn't need to be aware of the internals of how results are represented. 
In theory it could also be a frontend utility function but that seems to spread out a lot of complicated state for no real performance benefit.

**Comment by mazameli** [comment]
- For the required toggle, it would be great if, when a question is being used to populate results, the input box for the Required section turned into a dropdown populated with the question results, so the user could just select one of the available options.
- Not entirely sure what you're referring to by, "except for the preview/placeholder in the card picker select."
- As for the rest, I'm seeing a show-stopper problem with the variables panel, so I can't currently assess the rest of the feature:

vars

Here's the JS errors I'm seeing when I try to invoke the panel:

screen shot 2018-02-26 at 9 05 43 pm

**Comment by joneath** [comment]
@mazameli looks like a one of your cards doesn't have `result_metadata` which is how I was determining which questions have a single results column. I've added temporary support for null `result_metadata` until we have a dedicated API/query param from @camsaul to return only these cards.

**Comment by joneath** [comment]
Hey guys, I'm alive! So I'm jumping back into this PR and my two open questions are:

1. Will we be able to save the selected question to be used in the filter using the current `TemplateTag` modeling? It doesn't currently look possible by inspecting what is saved for a native query card with template tags.
2. Once I get saving of the referenced questions then I'll need to actually start querying for row data. I believe Cam finished an API for this recently? I'll save this question for him.

**Comment by marvec** [comment]
Hello, is there any progress on it? We are considering to deploy metabase and this is the only thing missing in the puzzle...

**Comment by mazameli** [comment]
Assigning this to you @tlrobinson since I don't think @joneath will be wrapping this up. I think it's definitely something we should finish and merge.

**Comment by nitzien** [comment]
Do we know if this will be available in 0.35.0?

**Comment by salsakran** [comment]
Hey @paulrosenzweig -
Can you take a quick look at this and see if things have diverged enough that we should close this PR or if it's close enough to done that we should keep it? #6820 is still something we very much want to do, and there's a design for it.

**Comment by paulrosenzweig** [comment]
Enough adjacent code has changed since this PR was opened I think we should start from scratch. 

Also, I wonder if it's worth revisiting the designs to allow the feature on dashboards as well as native questions.

**Pull request closed without merging**
