### PR TITLE
Make Field Filter usage more clear, when used with Optional Clauses

### PR DESCRIPTION
**Pull request by flamber**
There are so many posts, where people are getting Field Filter syntax wrong, when used in combination with Optional Clauses. This will hopefully clear some of the confusion.

For some reason, the Field Filter without clauses didn't have the "Try it" button, so I added that too.

@mbvictoria Can you spell check or suggest other text, since I'm not fluent in English?

### CODE REVIEW

**Comment by mbvictoria** [comment]
Thanks for doing this! My wording suggestion: When using a field filter, the column name should not be included in the SQL. Instead, the variable should be mapped to a field in the side panel.

**Comment by flamber** [comment]
@mbvictoria I'm not sure if we should also add a note to the [top](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type) Field Filter section about the limitation of using aliases. That's a common mistake too.

**Comment by mbvictoria** [comment]
@flamber That's a good idea - can you draft something based on the points of confusion you've seen there? Thanks!

**Comment by flamber** [comment]
@mbvictoria 
It's funny, I can write stuff, but when I know it's going into a documentation and needs to be very understandable/translatable, then my English is out-the-window.
But this is a question that is being answered every week. #3324
```
**Note:** Field filters generates SQL based on the mapped field, so table aliases are not supported.
```

**Comment by mbvictoria** [comment]
It looks good to me!! Maybe it makes sense to flip it so that people see that aliases are not supported first?
 
**Note:** Table aliases are not supported. This is because field filters generate SQL based on the mapped field.

**Comment by flamber** [comment]
@mbvictoria I've added your (much better) wording to the docs - skipped the side panel help, since it's already getting very long. But CI is failing on something unrelated.

**Review by victoriaspek — APPROVED** [review]
Looks good!

**Review by mazameli — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
