### PR TITLE
Removes :fingerprint from serialized Fields and Cards in v2 export

### LINKED ISSUE #31669: [Serdes] Remove fingerprint from content and data model
**Context**
Fingerprints from questions and fields change often.
They are directly related to the underlying data.
We shouldn't serialize fingerprints. Reasons:
- There is no guarantee the source and target instances are querying the same underlying data source. So in many case the fingerprints are wrong.
- It polutes the diffs. As it is possible to see in [this commit](https://github.com/metabase/metabase/commit/896ee707a048edfba3a08e9b4f9a06adc718e283#diff-8b4ff9437199c196cbdca36c248e6503b7f1a2b7716d1b55112885af20bad752). All files are modified because of changes in fingerprints
- It may contain sensitive data. If we decide to add them to serdes, it should be an optional flag.

```[tasklist]
### Fields to remove
- [ ] In datamodel/fields: `fingerprint_version`
- [ ] In datamodel/fields: `last_analyzed`
- [ ] In datamodel/fields: `fingerprint` and nested keys
- [ ] In collection/cards: `fingerprint` and nested keys 
- [ ] Anywhere else we serialize fingerprints
```

### PR DESCRIPTION
**Pull request by john-metabase**
To reduce noise and clashes with version control, we now omit fingerprint-related keys from Fields, and from the `:result_metadata` of Cards.

Resolves #31669

### CODE REVIEW

**Review by bshepherdson — CHANGES_REQUESTED** [review]
So I originally skipped `:result_metadata` in building serdes, believing that since it's bulky and synthesized from the uesr's data anyway, we could skip it and let the importing end rebuild it.

However, we discovered some issues. Most notably with models, hence the specific test. The querying logic for a single card will populate its own `result_metadata`, but not that of any cards it depends on.

It's implicitly assumed to exist - after all you can't create a card A that depends on a model B without running that model and populating its `:result_metadata` previously. Importing A and B without `:result_metadata` breaks that assumption and causes errors.

See https://github.com/metabase/metabase/pull/26154

Which isn't to say we can't exclude these values from serdes! But we'll want to make sure the `:result_metadata` is recursively computed, not just for the first level.

**Comment by john-metabase** [comment]
@bshepherdson to make sure I understand: the problem seems to be that _imported_ cards based on models won't work until the cards that the models are based on are run in the destination instance?

I think we could address this by forcing population of `:results_metadata` on dataset cards in the `import` side of things.

**Comment by bshepherdson** [comment]
Yes, you have understood the issue correctly. I think that fix will work. Hopefully we can arrange a good unit test for this case.

**Comment by john-metabase** [comment]
Looking back at the original issue... I don't know where I got the idea `:result_metadata` needed to be removed at this point. @luizarakaki had asked for it before, but not in this specific issue. I am going to re-do this but leave `:result_metadata` until I hear from Luiz.

I'm honestly not sure what I was thinking when removing it... I think I went to look at `card.clj` and didn't see anything about `:fingerprint` and got confused.

**Comment by john-metabase** [comment]
Oh, right, because `:result_metadata` entries (fields) may contains `:fingerprint`

**Review by bshepherdson — APPROVED** [review]

**Pull request merged**
