### PR TITLE
Automagic dashboards improvements - round 2

### PR DESCRIPTION
**Pull request by tlrobinson**
* [x] Group headings shouldn't be huge in "mobile" view
* [x] Error page should have actual error contents (like how we do it on QB error pages)
* [x] Histogram labels should be better
* [x] Time filter labels should display humanized timestamps
* [x] The `Show More` button should be in main content area
* [x] Filter labels should have icons
* [x] When going from one x-ray to another, view should be scrolled back to top
* [ ] All cards should be x-rayable

### CODE REVIEW

**Comment by sbelak** [comment]
Bug: if I do a group by day of week (or similar), the cell drill-through generates the wrong `cell-query`.

**Comment by sbelak** [comment]
I did the datetime humanization server side. Not sure if it's the right call. Thoughts @salsakran @tlrobinson? 

If we go down this path, cell queries should to be slightly smarter and use the minimal needed resolution for the datetime string, instead of full ISO like now, to keep the display as compact as possible.

**Comment by tlrobinson** [comment]
@sbelak If the backend is formatting the date then it needs to take into account the `unit`, e.x. `month`, and then it doesn't really matter what resolution the FE includes in the filter. Even if I change `["=",["datetime-field",["field-id",43],"as","month"],"2015-01-01T08:00:00.000Z"]` to `["=",["datetime-field",["field-id",43],"as","month"],"2015-01"]` the backend currently formats it as `January 1, 2015` which isn't correct, it should be `January 2015`.

There are a few options:

1. the backend can look at the `datetime-field`'s `unit` and format based on that. I'm not sure if the backend has code for that already. Ideally we wouldn't have to duplicate logic the frontend already has
2. the backend could include a `column` object (similar to `/api/dataset`'s `data.cols`) alongside the `value` and the frontend could format it using that (something like `formatValue(filter.value, { column: filter.column })`)
3. the backend could just return the raw filter clauses along with relevant field metadata (similar to what we do with `param_values` for public questions/dashboards since FieldValuesWidget needs those) and the frontend can format the full filter (including field names)

The advantage of 2 and 3 is we can reuse all the formatting logic the frontend already has, including other types like latitude/longitude.

**Comment by sbelak** [comment]
Re 3: any specific request/needs how the response should look like? The filter, a map {field-id -> Field}, anything else?

**Comment by tlrobinson** [comment]
@sbelak maybe exactly like we do with `param_fields` on public dashboards:

```javascript
{
  // ...normal dashboard stuff"
  param_fields: {
    286: {
      id: 286,
      table_id: 16,
      display_name: "Created Date",
      base_type: "type/Date",
      // …
  }
}
```

Make sure to include both the fk and target field for `fk->` fields.

**Comment by mazameli** [comment]
I don't think we should show users the `Save this` button at all if they don't have Curate permissions for the `Automatically Generated Questions` collection. I.e., I shouldn't be able to write to that collection.

Right now if I'm not an admin, I can save x-rays even if I don't have Curate permissions, but if I try to go view the x-ray I've just saved I hit a permissions error (unless the admin has explicitly changed the default and given me View permissions).

non-admin-x-ray

**Comment by mazameli** [comment]
Legacy x-rays are still accessible from the Data Reference. IIRC, the last time @metabase/core-developers discussed this, we decided we were going to remove these.

screen shot 2018-04-19 at 10 07 15 am

**Comment by mazameli** [comment]
Here's an updated design for the `See more` button per yesterday's feedback:

see_more_about_this

**Comment by tlrobinson** [comment]
Ok I've fixed all the issues I'm aware of except. I don't know what "All cards should be x-rayable" means, but I'm guessing it's a backend thing?

**Comment by mazameli** [comment]
Some small details about the way we're adding filters to saved x-ray descriptions:

- If a x-ray has filters applied, we should probably _replace_ the dashboard description with the filters instead of just concatenating them at the end. 
- The current filter descriptions are missing a comma plus space between each one.

E.g. this current dashboard description:
`
An overview of your Profiles table and how it's distributed across time, place, and categories.Filtered by:Height is between 74 and 76Drinks is sociallyIncome is between -200000 and 0
`

should be more like this:

`
Filtered by: Height is between 74 and 76, Drinks is socially, Income is between -200000 and 0
`

**Comment by mazameli** [comment]
Dashboards saved from x-rays don't seem to work correctly when trying to create new dashboard filters. The expected behavior is that the cards would display a dropdown to show the fields that can be mapped to a new filter, or a filter currently being edited. Instead, they continue to show their visualization.

If I add a automatically generated card to a new dashboard, however, it does appear to work correctly.

[dashboard editing.mp4.zip](https://github.com/metabase/metabase/files/1932968/dashboard.editing.mp4.zip)

**Comment by mazameli** [comment]
When I click through on x-ray cards, I don't see a query builder bar unless I hard refresh the page.

no-qb

**Comment by mazameli** [comment]
When looking at a filtered x-ray for an orders/transactions table (e.g. where People->State is TX), trying to hit one of the deeper x-rays like `ByCountry.yaml` or `Seasonality.yaml` results in a 404 (if this is an error, it's not correctly showing the error page):

transactions-in-depth

**Comment by mazameli** [comment]
Numeric filters are rendering their values as crazy looking real numbers. We should display these in a friendly fashion.

screen shot 2018-04-20 at 10 35 48 am

**Comment by mazameli** [comment]
Um, it looks like we're incorrectly saving… a lot of metrics and segments. I think this happened after I connected a to a Google Analytics DB:

metrics segments

**Comment by sbelak** [comment]
- [ ] wrong title when saving cell xray
- [ ] humanize numeric filters
- [ ] ensure unique collection names
- [ ] drilldown is broken when applying filters
- [ ] card clickthrough doesn't show query builder

**Comment by sbelak** [comment]
Save for GA dashboard is broken due to #7399

**Comment by sbelak** [comment]
@tlrobinson here's a branch (off this one) that just passes the query filter to the FE #7404

**Pull request merged**
