### PR TITLE
[tech debt] Stop using ms/BooleanString and only use ms/BooleanValue

### LINKED ISSUE #39740: [tech debt] Stop using ms/BooleanString and only use ms/BooleanValue
`ms/BooleanString` will coerce to a string, and we should probably get rid of it and only ever use `ms/BooleanValue` which will always coerce to a boolean

We want the coercion layer to give us values that are helpful, and true is more helpful than "true". So we should remove `ms/BooleanString` and calls to parseBoolean

### PR DESCRIPTION
**Pull request by puchka**
Closes https://github.com/metabase/metabase/issues/39740

### Description

Solves #39740 ~~apart from the one in `src/metabase/api/native_query_snippet.clj`~~
The tests in `metabe.api.native-query-snippet-test` are ending with an error as reported in #41389

### CODE REVIEW

**Review by escherize — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution.

The changes you've sent up look good, but I think we can make them even better by removing `BooleanString` entirely. And it won't take many more changes, either:

- [ ] delete [this bit of this test](https://github.com/puchka/metabase/blob//test/metabase/util/malli/schema_test.clj#L60-L62)
- [ ] remove [this last non-test usage](https://github.com/puchka/metabase/blob//src/metabase/api/native_query_snippet.clj#L24-L31) of ms/BooleanString
- [ ] remove the [BooleanString schema def](https://github.com/puchka/metabase/blob//src/metabase/util/malli/schema.clj#L230-L235), since it will be unused then.

**Comment by puchka** [comment]
> Hi, thanks for your contribution.
> 
> The changes you've sent up look good, but I think we can make them even better by removing `BooleanString` entirely. And it won't take many more changes, either:
> 
>     * [x]  delete [this bit of this test](https://github.com/puchka/metabase/blob//test/metabase/util/malli/schema_test.clj#L60-L62)
> 
>     * [x]  remove [this last non-test usage](https://github.com/puchka/metabase/blob//src/metabase/api/native_query_snippet.clj#L24-L31) of ms/BooleanString
> 
>     * [x]  remove the [BooleanString schema def](https://github.com/puchka/metabase/blob//src/metabase/util/malli/schema.clj#L230-L235), since it will be unused then.

Hi, thank you for your review. I applied the requested changes.

**Review by escherize — APPROVED** [review]

**Comment by escherize** [comment]
I've merged your change. Thank you @puchka!

**Comment by puchka** [comment]
Thank you for the review @escherize 🙏

**Pull request merged**
