### PR TITLE
Avoid native editor autocomplete suggestions flicker

### LINKED ISSUE #34596: Suggestions unexpectedly change in the SQL query editor
### Describe the bug

:warning: In prod build (stats instance) it blinks twice and comes back to the initial list of suggestions on the 2nd blink.

`master`, locally, dev build, **blinks once**:
https://github.com/metabase/metabase/assets/6830683/d902fad7-d4aa-4cd3-9fdb-c25d87a97e66

stats instance, prod build, **blinks twice**:
https://github.com/metabase/metabase/assets/6830683/ff1c53d2-82a6-425f-93b0-341fdeb63805

### To Reproduce

1. Create new SQL question
2. Hit <kbd>p</kbd>

Suggestions are displayed and the list shortly changes to a different list.

### Expected behavior

Suggestions are displayed and don't change

### Information about your Metabase installation

`master` & stats instance

### Severity

P2

### Additional context

Found when reviewing #34534

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/34596
Reduces the cases where https://github.com/metabase/metabase/issues/48712 is relevant

### Description

ACE editor is bit weird: it only updates the autocompletion results when the callback is called. This causes some flicker when the autocompletion API is bit slow (as the linked issue describes).

This PR solves that by splitting the completion into two phases:
1. just takes the existing completions and filters out items that do not match the current prefix. Trigger the autocompletion again (but tell it to go into phase 2).
2. Call the actual autocomplete and talk to the API

This two-phase approach was necessary because we want to update suggestions instantly when typing to remove stale suggestions, but still want to be able to debounce the actual API requests.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> SQL query
2. Type `PE`, wait for the completions to settle
4. Type `O`, the non-matching completions should dissapear instantly

### Demo

https://github.com/metabase/metabase/assets/1250185/7eac6265-411e-4dec-b6ae-709305367ef3

### CODE REVIEW

**Review by ranquild — COMMENTED** [review]
We shouldn't bring such complexity to the FE to solve a UI bug. We need to find another solution instead.

**Comment by romeovs** [comment]
Closing due to [comment](https://github.com/metabase/metabase/pull/45136#pullrequestreview-2159479955).

**Comment by romeovs** [comment]
This PR seems to also resolve https://github.com/metabase/metabase/issues/48712.

@ranquild: maybe we could reconsider whether or not the changes are too complex, since it solves two issues? I personally don't think these changes are more complex then what the current code does. 

Alternatively I think we should move away from ACE, but doing that will be more work.

**Comment by ranquild** [comment]
@romeovs I'm fine with merging a fix like this but I can't verify if it solves the issue. E.g. here https://github.com/metabase/metabase/issues/34596 the new behavior matches exactly the old one when locally it flickers once. Also recorded a loom with this https://www.loom.com/share/8cd58775001347249a1039814984980e. Could you explain/record when the new implementation works better than the old one?

**Review by ranquild — COMMENTED** [review]
Commented

**Comment by romeovs** [comment]
@ranquild What this fixes is not the fact that some completions come in faster than others (due to some of the completions being sync vs some of them being async).

This PR makes sure that unrelated results from previous async completions do not linger while we're waiting for the new results.

### Before
This is how things worked before this PR

1. We type `PE`
  - this triggers a call to `/autocomplete_suggestions?substring=PE`
  - at the same time it triggers the editor to show "sync" completions which come from the SQL grammar (like `type`, etc), they are displayed immediately, the results look like this:
  ```
  type
  escape
  update
  tablesample
  ```
2. After a while the results from the call to `/autocomplete_suggestions`, they now get mixed in with the sync results:
  ```
  PEOPLE
  EXPECTED_INVOICE
  type
  escape
  RATING_MAPPED
  update
  tablesample
  ```
3. We type `O` (so the text in the editor is `PEO`)
  - An async call to `/autocomplete_suggestions?substring=PEO` gets made
  - Immediately, the current suggestions are filtered by the new search text (`PEO`), this also includes results from the previous async call. This includes `EXPECTED_INVOICE`
  ```
  PEOPLE
  EXPECTED_INVOICE
  ```
4. After a while the async results for the second call come in and replace the async results from the first call, they do not include `EXPECTED_INVOICE` so the results now correctly show
  ```
  PEOPLE
  ```

This means there is a _flicker_ between step 3. and 4. where some results are shown and then dissappear (without the user doing anything).

##### Video
https://github.com/user-attachments/assets/81665175-2cc1-41c3-a7ae-fb69051c1151

### After

1. We type `PE`
  - this triggers a call to `/autocomplete_suggestions?substring=PE`
  - at the same time it triggers the editor to show "sync" completions which come from the SQL grammar (like `type`, etc), they are displayed immediately, the results look like this:
  ```
  type
  escape
  update
  tablesample
  ```
2. After a while the results from the call to `/autocomplete_suggestions`, they now get mixed in with the sync results:
  ```
  PEOPLE
  EXPECTED_INVOICE
  type
  escape
  RATING_MAPPED
  update
  tablesample
  ```
3. We type `O` (so the text in the editor is `PEO`)
  - An async call to `/autocomplete_suggestions?substring=PEO` gets made
  - Immediately, the current suggestions are filtered by the new search text (`PEO`), but we correctly filter out the unwanted entries too:
  ```
  PEOPLE
  ```
4. After a while the async results for the second call come in and replace the async results from the first call, they do not include `EXPECTED_INVOICE` so the results now correctly show
  ```
  PEOPLE
  ```


##### Video

https://github.com/user-attachments/assets/feabd208-d63d-4870-9b9e-c1c230c142cf

This means there is no flicker between the user typing and the async results coming in. 

This also means the results don't change as much so it reduces the impact of https://github.com/metabase/metabase/issues/48712. I don't think it completely removes all the cases where it happens, but it makes it more of an edge-case than it already is. #48712 still happens when in this scenario:
1. type `PEO` and wait for the results to come in
2. Remove the `O` and immediately use the arrow keys to select a suggestion
3. When the async call comes in the suggestion list (and your selection) is reset.

Whether or not we want to wait with showing "sync" results is kind of unrelated. It might further reduce the impact of these edge-cases, but I don't think it will fully solve them either. Happy to include that in this PR though!

**Review by ranquild — APPROVED** [review]
Got it, makes sense. We might want to keep the flicker issue open (unsure about that). I see that it makes it better than before.

**Pull request merged**
