### PR TITLE
Resolve pivot tables in serialization

### LINKED ISSUE #30130: Resizing columns in pivot tables in serialization breaks the card on load
**Describe the bug**
Seems like the new column width in the pivot table card breaks the metadata on the load with
"Error: Invalid metadata returned for cell 2:
        x:255, y:0, width:NaN, height:30"

**Logs**
Frontend error
Error: Invalid metadata returned for cell 2:
        x:255, y:0, width:NaN, height:30

**To Reproduce**
Using https://github.com/paoliniluis/metabase-serialization as the base
1) create a pivot table on the origin
2) resize one column
3) dump and load
4) see the card breaking on destination

**Expected behavior**
We shouldn't break the cards :(

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.46.1

**Severity**
P1

**Additional context**
NA

### PR DESCRIPTION
**Pull request by qwef**
Closes https://github.com/metabase/metabase/issues/30130

### CODE REVIEW

**Review by noahmoss — CHANGES_REQUESTED** [review]
Fix looks good and I confirmed that this fixes the issue locally. However the test doesn't seem to repro the issue properly—when I comment out the call to `resolve-pivot-table-settings` the test still passes.

Not 100% sure why it doesn't repro but I'd guess that the Card you're creating is slightly different from what's actually being loaded for pivot tables? Lmk if you get stuck and I can help dig deeper into it.

**Review by noahmoss — APPROVED** [review]

**Comment by noahmoss** [comment]
@qwef backport?

**Comment by metamben** [comment]
@qwef Since the milestone is 0.46.7, We need a backport to `release-x.46.x` too.

**Review by metamben — COMMENTED** [review]
LGTM

**Pull request merged**
