### PR TITLE
Remove card id from questions updated by drills

### LINKED ISSUE #11557: Bug: Filter not applied when downloading data.
**Describe the bug**
When adding a filte to a saved Question and then downloading the result, the additional filter ist not applied to the downloaded data set.

**Logs**
not applicable

**To Reproduce**
0. open the sample dataset and filter the People table to: birthdate - past 20 years. 
1. save this as a new Question "PEOPLE, Filtern nach BIRTH_DATE"
3. open a saved Question
4. click on a value in the table and use it as a filter (SOURCE = "Twitter")
5. refresh the data (the dataset is now filtred)
6. download the data set to EXCEL
7. realize the the additional filter (step 2) is NOT applied to the downloaded data

**Expected behavior**
I expected the downloaded dataset to be equal to the dataset shown in the browser

**Screenshots**
Step3
Step4
Step5
Step6
Step7

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_222",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.222-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-1099-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.4",
      "date": "2019-10-07",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Because of this bug our users may download and process incorrect data sets.
It is a medium bug since it can be avoided by adding the filter from the filter menu and not directly from the table.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #11557

~When a saved card is updated, it still keeps has its ID so we know what card to save to. The `SavedQueryButton` issues a request for a given card ID without using the current state of the card. This PR makes sure to only use the `SavedQueryButton` if it's both saved and unedited (`!isDirty`).~ reverted in favor of more general fix

Previously, adding the filter in the sidebar and adding it from the table heading had different results. I considered totally unifying the codepaths (different redux actions in the QB), but that felt like too big of a change for a point release. Instead, I updated the visualization card update code to remove the card id. That triggers the dirty state correctly.

### CODE REVIEW

**Review by flamber — APPROVED** [review]
This works as expected for the download, but I'm noticing the UI is still behaving slightly different other places. Not sure if that should be spun off into it's own issue.

When using the column to filter from, notice it doesn't fully dirty the UI, so it doesn't display "Started from ..."
image

When filtering via Filter-sidebar:
image

**Comment by mazameli** [comment]
@paulrosenzweig I saw you wanted my eyes on this, so I've been playing around with it for 10 or 15 minutes now, and I haven't noticed anything that feels odd or wrong when modifying a saved question. Is there anything I should specifically look at or that you'd want to talk out?

**Comment by paulrosenzweig** [comment]
@mazameli thanks for looking! I think the main question was whether this maintains question lineage when it shouldn't. e.g. drilling into a bar to see rows or visualizing the distribution of a table columns.

If it feels good to you, I'm happy to merge as-is. It's more of a hassle to split out specific drill actions that maintain or discard lineage, and this fixes at least one bug. We can follow on with any refinements.

**Comment by mazameli** [comment]
Yeah, it's feeling right to me. 👍

**Pull request merged**
