### PR TITLE
fix(frontend): Filter technical/cruft table types

### LINKED ISSUE #9759: Hidden tables show in "our data" page when it is marked as technical/cruft
Browser: Firefox Quantum (66.0.1)
OS: Linux Manjaro
Databases: Postgres 11.2
Metabase version: 31.2
Metabase hosting env: Ubuntu 18.04.1 LTS
Internal db: H2

### Steps to reproduce
1. Change visibility of a table to hidden of a data model under admin.
2. It won't appear under "Our Data" page now.
3. Change "Why hide" to technical/cruft.
4. Now, it appears in "Our Data" page.

https://github.com/metabase/metabase/pull/8831 should respect technical/cruft visibility type.

### PR DESCRIPTION
**Pull request by joeirimpan**
Fixes #9759

### CODE REVIEW

**Review by jbrooksuk — APPROVED** [review]

**Comment by joeirimpan** [comment]
@jbrooksuk is there anything pending on this?

**Comment by jbrooksuk** [comment]
@joeirimpan I don't think so, but I'm unable to merge it as I'm not part of the metabase team. Ping @tlrobinson @camsaul

**Comment by joeirimpan** [comment]
@tlrobinson Can you take a look?

**Comment by tlrobinson** [comment]
Thanks @joeirimpan

**Pull request merged**
