### PR TITLE
Frontend cleanup

### PR DESCRIPTION
**Pull request by tlrobinson**
- Add / cleanup some Flow types
- Move `query_builder/*.jsx` components into `query_builder/components` like the rest of the app.

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers needs review

**Comment by camsaul** [comment]
Is this part of #927 👴 ?

**Comment by kdoh** [comment]
Looks pretty good to me.  One question I had was for the Flow types for some of the libraries like Underscore, Icepick etc are those our defs or community ones? 

If they're our custom ones we might want to consider trying to use the underscore ones at https://github.com/flowtype/flow-typed/ since I'm imagining those are a bit more vetted.

**Comment by tlrobinson** [comment]
Yeah some of them are based on the flowtype ones, it was just easiest to copy them over manually. Using their CLI tool is something to look into though.

**Pull request merged**
