### PR TITLE
Add fonts in Dockerfile to fix pulses

### LINKED ISSUE #2342: Support unicode (emoji, Chinese characters, etc.) in pulses
The pulse rendering engine doesn't handle emoji. It should.

screenshot 2016-04-08 13 06 41

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by dragonsahead**
Adding Noto fonts, it fixes #2342

I just tested with the current build and we get
image

while with the noto fonts, we get
image

### CODE REVIEW

**Comment by paoliniluis** [comment]
Will this have any licensing issue? https://fonts.google.com/noto

**Comment by paoliniluis** [comment]
Adding @kdoh and @mazameli as this will have an impact on fonts and also on the size of the container. Should we delete dejavu?

**Comment by mazameli** [comment]
> Adding @kdoh and @mazameli as this will have an impact on fonts and also on the size of the container. Should we delete dejavu?

@paoliniluis Thanks for the ping! Adding support for Chinese etc. seems like a great reason to merge this to me. If you're not concerned about the size increase, then neither am I. I assume dejavu is a font, but can you tell me what we're currently using it for?

**Review by mazameli — COMMENTED** [review]
Left some general comments, but I don't think I can truly review this PR.

**Review by camsaul — APPROVED** [review]

**Comment by camsaul** [comment]
Container size difference doesn't worry me, unless this is adding like an extra 100 MB, but somehow I seriously doubt that.

**Comment by paoliniluis** [comment]
Ok, it seems we added ttf-dejavu A LOOONG time ago https://github.com/metabase/metabase/pull/2431 and there doesn't seem to be anything specific about the why. I would say that we remove that package and go full noto maybe?

**Comment by paoliniluis** [comment]
New container size 477MB from 346MB (37% increase). Some screenshots
image
image
image
image

**Review by camsaul — APPROVED** [review]
~works for me~

**Comment by mazameli** [comment]
No concerns here from the screenshots I'm seeing, but I can't really approve this PR since I can't really review it.

**Comment by camsaul** [comment]
Wait a second... how big is this font? It's 130 MB (or more since you're removing the other font?) That's insane. Are you sure that's right? That seems questionable

**Comment by paoliniluis** [comment]
> Wait a second... how big is this font? It's 130 MB (or more since you're removing the other font?) That's insane. Are you sure that's right? That seems questionable

yup, the new noto fonts are B.I.G.

**Review by camsaul — APPROVED** [review]
I read in to this a little more and I guess noto and the CJK stuff really are just gigantic packages. I'm not sure what the implications are of adding another 130MB to the Docker image size. I guess it should mostly be fine other than taking longer to download.

I would be interested in seeing if this slows down CI significantly. We should also loop in cloud and make sure it's not going to make things too much slower when spinning up new instances

**Comment by mazameli** [comment]
@paoliniluis @camsaul what are we gonna do about this PR? It's been 3 weeks since Cam's last comment.

**Comment by paoliniluis** [comment]
@Onlinehead what do you think about this PR?

**Comment by Onlinehead** [comment]
@paoliniluis Don't see any problems here.

**Pull request merged**
