### PR TITLE
Check dependency licenses in CI

### PR DESCRIPTION
**Pull request by tlrobinson**

### CODE REVIEW

**Comment by camsaul** [comment]
A better way to do this (at least for Clojure) would be to make a Leinigen license checker plugin. Could fork `https://github.com/technomancy/lein-licenses` as a starting point and the only difference would be instead of outputting the licenses it could normalize the names and then check them there

**Comment by tlrobinson** [comment]
> A better way to do this (at least for Clojure) would be to make a Leinigen license checker plugin. 

Maybe, but this is already pretty much done.

**Comment by salsakran** [comment]
👍 to having a unified program that does this check vs one in FE land and one in BE land.

**Comment by tlrobinson** [comment]
@salsakran should we resurrect this?

**Review by salsakran — APPROVED** [review]
Done is better than perfect. This works and is something we should be doing. 

I think we should merge and rewrite if it's worth the effort at a later time.

Any thoughts @rlotun @ariya ?

**Comment by rlotun** [comment]
+1 If this works and solves a problem let's merge this in and figure out how to make it better later.

**Comment by paulrosenzweig** [comment]
I'm not sure why Cypress keeps failing here, but given the changes, it's definitely unrelated.

**Pull request merged**
