### PR TITLE
only show NQF SQL option if the user has permission to at least one db

### LINKED ISSUE #5838: We shouldn't show the SQL option in the new question window if a user doesn't have permission to write raw queries
Right now if a user doesn't have permission to do so, and they click on the SQL option, they'll see the SQL editor but won't be able to interact with it:

screen shot 2017-08-29 at 5 03 56 pm

### PR DESCRIPTION
**Pull request by kdoh**
Fixes #5838 and #5839

### CODE REVIEW

**Comment by mazameli** [comment]
Everything looks right except for the case where I have SQL editing access to one DB but not others.

Here are the admin panel settings:

screen shot 2017-09-06 at 11 38 15 am

The database I do have access to isn't selected or selectable in the UI:

screen shot 2017-09-06 at 11 39 01 am

If I go to the query builder, though, and then switch to SQL from there, things work as expected:

screen shot 2017-09-06 at 11 41 12 am

**Review by mazameli — CHANGES_REQUESTED** [review]
See above comment.

**Comment by kdoh** [comment]
I fixed the issue @mazameli ran into and this branch also now adds the redirect behavior if someone only has the GUI option.

I still need to add some tests. Getting a multi user environment in the full integration test env is a bit of a hassle right now based on how shared login sessions work, so I might just try and do some quick unit tests on the component in the meantime to provide a bit of safety until that gets more robust.

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
Nicely done — everything seems to be working right. 👌

**Pull request merged**
