### PR TITLE
Add option to disable animation in organization

### LINKED ISSUE #19085: Add option to disable animation in organization
For users that use Metabase on daily basis and specially those that author questions, user interface animations are distracting and time consuming (specially Question Editor drawer animation). In comparison professional software packages like Excel, PowerBI, Tableau, IDEs etc, don't add use animations. It would be great to be able to disable animations in the admin panel.

### PR DESCRIPTION
**Pull request by gitstart**
###### Before submitting the PR, please make sure you do the following

- [X] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

Fixes #19085

### Demo
https://www.loom.com/share/d0b93bc4ae9247129d14afe27e882768

### CODE REVIEW

**Comment by noahmoss** [comment]
@alxnddr Isn't this somewhat covered by the recent work to respect `prefers-reduced-motion`? I wonder if this actually needs to be a dedicated setting in the product as well.

@gitstart Regarding the backend changes, this would be a great use case for user-local settings, which are a relatively new mechanism in the code base. I'd prefer if we don't add new boolean flags to the user table at the top level. Instead, a new setting can be added to `metabase.public-settings` using the `defsetting` macro, with the option `:user-local :only`, which will cause it to store a distinct value for each user rather than a global value for all users. It can then be fetched and set by the frontend using `/api/setting` APIs.

**Review by camsaul — CHANGES_REQUESTED** [review]
Agree with with @noahmoss said about seeing if we can leverage `prefers-reduced-motion` here.

If we can't, this is 100% something that belongs in a [User-local Setting](https://github.com/metabase/metabase/pull/20456) instead of adding a new column to the User table.

**Review by ranquild — CHANGES_REQUESTED** [review]
This PR doesn't reference an epic or a product doc. I haven't seen this feature in our (pod) tracker anywhere. Is this change intended? We already leverage `prefers-reduced-motion` in our components, maybe the referenced issue can be already closed?

This solution won't work for `animation`, i.e. not `transition`. We also have a dedicated components for global styles https://github.com/metabase/metabase/blob/1aa9565c451fb2c92c4cab46c45dde7a0adab174/frontend/src/metabase/styled-components/components/GlobalStyles/GlobalStyles.tsx#L10.

Agree with @camsaul , this is definitely a regular user-local setting and not a new `User` field if we want it to be triggered manually.

**Comment by alxnddr** [comment]
A new user-local does not make a lot of sense because on a user level it can be configured through `prefers-reduced-motion` setting. The original issue mentions an instance level setting which might be useful in embedding cases. Anyway, it requires clarification

**Pull request closed without merging**
