### PR TITLE
Fix filter updates in filter pill popover

### LINKED ISSUE #24994: Can't change filters via 'Show filters'
**Describe the bug**

In a saved question, when I clicked on "Show filters" and try to change any of the filters (date, is empty, etc), the Update filter button grays out immediately. 

**Logs**
None

**To Reproduce**
1. Go to any saved question with filters
2. Click on "Show filters"
3. Try to change any filter's value (is empty to not empty, date to another date, etc)
4. Update filter button grays out immediately

**Expected behavior**
Update filter button shouldn't gray out, so the new filter can be applied. 

**Screenshots**

n/a as it's pretty simple / screenshot won't provide much value

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version:  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",

- Your operating system: MacIntel
- Your databases: Redshift
- Metabase version: master / 1fca705
- Metabase hosting environment: Metabase Cloud
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It's a bit inconvenient as I need to go to the question's editor page to make changes instead. 

**Additional context**
None

### PR DESCRIPTION
**Pull request by akiselev**
Resolves #24994
Reproduces #24994

Reproduce:

Reproduce:
1. Question > Sample > Products
2. Filter Category=(select all) and CreatedAt=past 30 years
3. Count grouped by Category
4. Filter Count > 0
image
5. Try making any changes to the Category filter pill - the "Update filter" button should work and should update the filter

### CODE REVIEW

**Review by ranquild — APPROVED** [review]
Works as described. Could you add a repro in cypress for this issue?

**Review by nemanjaglumac — CHANGES_REQUESTED** [review]
Before you merge, I found something that seems off.
Will update in a minute.

EDIT:
@akiselev I hope this video helps
https://www.loom.com/share/77fbb7f33642467dbdaeee6af8a2fafb

EDIT 2:
Sorry, my bad.
Post-aggregation filter dropping is not the focus of this PR. #25066 takes care of that.

**Review by nemanjaglumac — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
There are some things that seem weird to me, but are not necessarily part of this PR:

- Category has the button "Update filter" while Created at has the button "Add filter"
- Why are buttons enabled by default even if there are no changes to filters?

**Review by ranquild — CHANGES_REQUESTED** [review]
Seems like an invalid fix - it drops other filters for nested queries.

**Pull request closed without merging**
