### PR TITLE
Changed is-url? to url? and is-email? to email? and changed all the f…

### PR DESCRIPTION
**Pull request by codingkarthik**
…unction

calls accordingly

###### TODO 
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Review by camsaul — CHANGES_REQUESTED** [review]
Looks like we still need to change all the tests to use the new function names. `test/metabase/util_test.clj` is a good place to start.

**Comment by codingkarthik** [comment]
I have made the changes and pushed it. Please
review it.

**Review by senior — APPROVED** [review]
👍

**Comment by camsaul** [comment]
@codingkarthik, can you please sign our [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)?

**Comment by codingkarthik** [comment]
I have signed the CLA,

**Review by camsaul — APPROVED** [review]
LGTM

**Pull request merged**
