### PR TITLE
Dynamically space x axis ticks

### LINKED ISSUE #5743: Feature Request: Formatting Axis Labels
I'm running into an issue with charts where x-axis labels are consistently overlapping due. Most commonly with dates in line and area charts, as seen below:

image

It would be great if there were a date format option or if the cards were responsive enough to automatically scale such that labels along the axis would disappear rather than overlap. Vertical ticks to mark data points would also help with clarity. 
-------
Version 60.0.3112.90 (Official Build) (64-bit)
Encountered with data from MSSQL, Oracle and PostGres with QueryBuilder and SQL questions.

### PR DESCRIPTION
**Pull request by camsaul**
Big sexy win of the day.

Dynamically space x-axis ticks based on the widths of the ticks themselves. Wow!

Fixes #5743 

### Before

before

### After

after

### Maz

@mazameli can you try to repro it the same way you did in #5743? I tried to repro it and this is what I saw:

timeseries

I'm not convinced the code I changed fixed timeseries charts (I'm certain it fixed non-timeseries ones) so if you could confirm/deny that would be 💯

### CODE REVIEW

**Comment by mazameli** [comment]
Rad. I'll check this out this afternoon. 👍

**Review by kdoh — APPROVED** [review]
Code looks like a solid improvement. Would be nice to unit test some of these functions.

**Review by mazameli — APPROVED** [review]
Looks good to me. Definitely an improvement. I did confirm that the scenario from #5743 is fixed by this PR.

Not regressions, but:
- feels weird to have intermittent x-axis ticks on ordinal groupings, like product titles, but I guess the only alternative in a high cardinality case like this would be diagonal labels, which could get gnarly.
- the re-rendering chugs a ton when grouping with a ton of x-axis points, like `created at by minute`

**Comment by salsakran** [comment]
@mazameli was it always slow on `created_at by minute`or did it get worse?

**Comment by camsaul** [comment]
@mazameli I noticed the chugging as well and am hoping at some point I can figure out how to speed things up

**Comment by mazameli** [comment]
"Not regressions, but…" ;)

**Pull request merged**
