### PR TITLE
Revert to using _.sortBy which actually sorts numbers correctly ಠ_ಠ

### LINKED ISSUE #2819: Hour-of-day line charts ordered incorrectly
*  I am using the Google Chrome (v51.0.2704 - x86-64) browser.
*  My computer's OS is Mac OS X 10.11.5.
*  I'm running Metabase locally from the JAR.
*  My database is H2.
*  My Metabase version is 0.18.0.

I'm trying to plot simple 'count by hour' data, but it seems that 2AM is being inserted in between 7PM and 8PM resulting in some strange looking charts. Please let me know if you require more information :)

screenshot at jun 23 16-49-46
screenshot at jun 23 16-50-01
screenshot at jun 23 16-50-19

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #2819

Unit test forthcoming

### CODE REVIEW

**Comment by camsaul** [comment]
wait so `sort()` doesn't sort correctly? 🙀

**Comment by MrMauricioLeite** [comment]
Hi @tlrobinson, sorry to barge in but have you considered changing the comment that says to use javascript sort function instead of _.sortby ?

The comment says X and the code does Y

**Comment by tlrobinson** [comment]
@camsaul Not for numbers, it casts them to strings: https://tonicdev.com/tlrobinson/bad-javascript-sort-bad

Though actually we should just use the JavaScript `sort` and provide the comparator function `.sort((a,b) => a - b)` (or is it `b - a`? I can never remember)

@MrMauricioLeite Good point, thanks.

**Comment by salsakran** [comment]
Fixes the example for me on the sample dataset.

**Comment by tlrobinson** [comment]
@salsakran Can you take a look at the unit tests and let me know if they're sufficient. Basically each row like this https://github.com/metabase/metabase/pull/2830/files#diff-52cfec8ceffcd684e6829c4b03557dc9R47 is a single series (with the Y values left out since they're not used by `getXValues`)

**Comment by salsakran** [comment]
looks good! 👍

**Pull request merged**
