### PR TITLE
Use FormProvider in SaveQuestionModal

### PR DESCRIPTION
**Pull request by uladzimirdev**
separated from https://github.com/metabase/metabase/pull/30224
related to https://github.com/metabase/metabase/issues/26178

### Description

Refactoring of the SaveQuestionModal form with the FormProvided way instead of current, which is deprecated.
This refactoring allows to bypass problems with types in https://github.com/metabase/metabase/pull/30224

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Edit a question and try to save it, you'll have a modal which provides you two ways of saving the question: as a new question or to replace existing one.

### Demo

https://www.loom.com/share/e24376da04824a608152ad3a2ae46920

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30418)

### CODE REVIEW

**Review by deniskaber — COMMENTED** [review]
Looks good! Thanks!

**Review by ranquild — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30418)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @deniskaber, @kulyk, and @uladzimirdev)

___
*[`frontend/src/metabase/containers/SaveQuestionModal.jsx` line 142 at r1](https://reviewable.io/reviews/metabase/metabase/30418#-NU6Yl391yDGS41pnm47:-NU6Yl391yDGS41pnm48:b-6q7hpk) ([raw file](https://github.com/metabase/metabase/blob/ce85bf9b7816c45f05e8886a672491038d2b47ee/frontend/src/metabase/containers/SaveQuestionModal.jsx#L142)):*
> ```JavaScript
>           {({ values, isValid }) => (
>             <Form>
>               {!!showSaveType && (
> ```

Why not just `{showSaveType && (`? If there are issues `showSaveType` we can modify it to be the actual boolean value
___
*[`frontend/src/metabase/containers/SaveQuestionModal.jsx` line 191 at r1](https://reviewable.io/reviews/metabase/metabase/30418#-NU6YbGIBHbvwP3SOsGe:-NU6YbGJBBbknLV9SasX:b-lqt6tn) ([raw file](https://github.com/metabase/metabase/blob/ce85bf9b7816c45f05e8886a672491038d2b47ee/frontend/src/metabase/containers/SaveQuestionModal.jsx#L191)):*
> ```JavaScript
>                   onClick={this.props.onClose}
>                 >{t`Cancel`}</Button>
>                 <FormSubmitButton title={t`Save`} disabled={!isValid} primary />
> ```

It should be automatically disabled when not valid, could you double check that?

**Comment by uladzimirdev** [comment]
*[`frontend/src/metabase/containers/SaveQuestionModal.jsx` line 191 at r1](https://reviewable.io/reviews/metabase/metabase/30418#-NU6YbGIBHbvwP3SOsGe:-NU70gg_EUrCraMP4iXI:b-sct9bt) ([raw file](https://github.com/metabase/metabase/blob/ce85bf9b7816c45f05e8886a672491038d2b47ee/frontend/src/metabase/containers/SaveQuestionModal.jsx#L191)):*
<details><summary><i>Previously, ranquild (Alexander Polyankin) wrote…</i></summary><blockquote>

It should be automatically disabled when not valid, could you double check that?
</blockquote></details>

there are tests to check it. Also on the video attached I showed it as well. could you please clarify exactly should I check?

**Comment by uladzimirdev** [comment]
*[`frontend/src/metabase/containers/SaveQuestionModal.jsx` line 142 at r1](https://reviewable.io/reviews/metabase/metabase/30418#-NU6Yl391yDGS41pnm47:-NU70uBj9Gj6c7mfL4AW:b-e8513l) ([raw file](https://github.com/metabase/metabase/blob/ce85bf9b7816c45f05e8886a672491038d2b47ee/frontend/src/metabase/containers/SaveQuestionModal.jsx#L142)):*
<details><summary><i>Previously, ranquild (Alexander Polyankin) wrote…</i></summary><blockquote>

Why not just `{showSaveType && (`? If there are issues `showSaveType` we can modify it to be the actual boolean value
</blockquote></details>

good point!

**Comment by uladzimirdev** [comment]
*[`frontend/src/metabase/containers/SaveQuestionModal.jsx` line 191 at r1](https://reviewable.io/reviews/metabase/metabase/30418#-NU6YbGIBHbvwP3SOsGe:-NU719kp-COvLFhpyokI:bbmww78) ([raw file](https://github.com/metabase/metabase/blob/ce85bf9b7816c45f05e8886a672491038d2b47ee/frontend/src/metabase/containers/SaveQuestionModal.jsx#L191)):*
<details><summary><i>Previously, uladzimirdev (Uladzimir Havenchyk) wrote…</i></summary><blockquote>

there are tests to check it. Also on the video attached I showed it as well. could you please clarify exactly should I check?
</blockquote></details>

previous implementation included other checks for disabled state 

do you mean to check that?



_Code quote:_
```JavaScript
submitTitle
```

**Review by kulyk — APPROVED** [review]
Looking good! Could we please link it to #26178 as well?

**Review by ranquild — APPROVED** [review]

**Pull request merged**
