### PR TITLE
Static viz colors harmonization with dynamic viz colors

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to #18676. Previously colors were all willy-nilly, but now for LAB series colors we will have the same function that determines the harmonized dynamic visualization colors determine the static viz colors using basically the same method. It rotates in hue-space but I didn't really feel like reimplementing those matrix multiplications in clojure so it gets late-bound to the FE bit instead.

Caveats
1. Category pie charts still use the old way
~~2. This doesn't work at all with dashboard cards and cards visualization settings both set at once.~~

~~Will fix number 2 before undrafting~~

It looks like bad compatibility with dashcards is actually a general static viz problem so it's going to get fixed in another PR

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Comment by howonlee** [comment]
Wait, does it work without the CI finishing beforehand?

**Comment by alxnddr** [comment]
It seems like colors are different:

Screenshot 2022-02-10 at 12 45 10

Screenshot 2022-02-10 at 12 45 37

**Pull request closed without merging**
