### PR TITLE
[backport] Fix 33971: CSV uploads aren't possible when native query editing is disabled

### PR DESCRIPTION
**Pull request by calherries**
Backports https://github.com/metabase/metabase/pull/33990

Also backports fixes:
#34073
#34083

### CODE REVIEW

**Review by noahmoss — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
@calherries can you add https://github.com/metabase/metabase/pull/34073 directly to this PR, please?

**Comment by calherries** [comment]
@nemanjaglumac added

**Comment by calherries** [comment]
Also added https://github.com/metabase/metabase/pull/34083

**Comment by calherries** [comment]
@npfitz can you please investigate why the unit tests are failing?

**Pull request merged**
