### PR TITLE
Generate field_ids by index

### PR DESCRIPTION
**Pull request by metamben**

### CODE REVIEW

**Review by johnswanson — APPROVED** [review]
I think this is reasonable but tbh the complexity here is kind of breaking my brain.

I was playing around locally with another approach that I think _might_ be simpler?

- in the "full" history, provide each field with an "internal ID" (the complex prefixed value we use to actually resolve the field), plus another ID that is just a nano-id
- when generating the history we send to the LLM, remove the internal ID and just send the nano-ID
- when resolving a field ID given to us by the LLM, just look through the history to find the field with that ID, then get its "internal ID" and resolve that

The more I play around, the more I like your idea of having an internal history and an explicit transformation step where we take that history and process it into a format fit for the LLM. In other words, have a completely separate `envelope/full-history` function and `envelope/history-for-llm` function, where the latter takes the output of the former and does all the processing we need.

**Comment by metamben** [comment]
> I think this is reasonable but tbh the complexity here is kind of breaking my brain.

What complexity do you mean?

> The more I play around, the more I like your idea of having an internal history and an explicit transformation step where we take that history and process it into a format fit for the LLM. In other words, have a completely separate `envelope/full-history` function and `envelope/history-for-llm` function, where the latter takes the output of the former and does all the processing we need.

I think we should eventually produce a schema about the expected too output just like we have a schema about the tool input as it seems important for maintaining agent stability. Given such a schema, we could use Malli's `mt/strip-extra-keys-transformer` to make sure the agent only sees data it is supposed to. I looked around to see if JSON schemas can be transformed to Malli schemas, but it doesn't exist yet: https://github.com/metosin/malli/issues/54. However, we might still be able to do compile _our_ JSON schemas to Malli.

**Comment by johnswanson** [comment]
> > I think this is reasonable but tbh the complexity here is kind of breaking my brain.
> 
> What complexity do you mean?

I guess I have a couple concerns, and to be clear this more saying that the current complexity is confusing, not that your PR is adding confusing complexity.

Right now I guess we only actually interpret these non-opaque identifiers in one place, which seems safe enough, but I have some fear that we'll end up parsing them out elsewhere? I guess it also feels like there's a lot of "stuff" required to generate a result-column, and a lot of it is pretty confusing. I need to pass in a `field-id-prefix`, but how do I figure out what `field-id-prefix` is the right one for a given column of a given entity? It feels like the caller of `->result-column` needs to understand a lot about the whole system.

**Comment by metamben** [comment]
I'll merge this and think about the abstraction issue you mentioned.

**Comment by metamben** [comment]
> Right now I guess we only actually interpret these non-opaque identifiers in one place, which seems safe enough, but I have some fear that we'll end up parsing them out elsewhere?

Currently, they are not parsed anywhere, but prefixes get generated both on the producer and the consumer side.

> I guess it also feels like there's a lot of "stuff" required to generate a result-column, and a lot of it is pretty confusing. I need to pass in a field-id-prefix, but how do I figure out what field-id-prefix is the right one for a given column of a given entity? It feels like the caller of ->result-column needs to understand a lot about the whole system.

Would it be less confusing if instead of the (rather obscure) prefix, both producers and consumers provided the type and the ID of the entity the columns (are expected to) belong to?

**Pull request merged**
