### PR TITLE
Collections project overworld empty state

### PR DESCRIPTION
**Pull request by kdoh**
Adds metabot explore recommendations to the overworld in cases where no dashboards have been pinned.

Implements #7714

### CODE REVIEW

**Comment by salsakran** [comment]
we should probably have a bit of copy to let the user know what they're seeing in the recommended x-rays.

**Comment by kdoh** [comment]
@salsakran Yup! @mazameli and I talked about that this morning.

**Comment by mazameli** [comment]
Like Kyle already said, I think this is a fine starting place to play with this, and then we'll want to tweak the appearance of the cards just slightly so that they match the other cards (black text instead of blue, icon sizing etc.). 

I've also been playing around with a place to put a link to get to /explore at the end of the databases list, so that after you've added pinned dashboards you can still get to it. (Putting a secondary link on each database card to x-ray it felt funky to me, but it's also my expectation that we'll be able to add an x-ray button on each db's detail page so you'd be able to do that there as well.)

screen shot 2018-06-11 at 1 38 35 pm

**Review by tlrobinson — APPROVED** [review]
LGTM, though I think it would make sense to skip /explore after initial setup and go straight to overworld since it has the same content.

**Pull request merged**
