### PR TITLE
Update the running metabase on debian guide

### PR DESCRIPTION
**Pull request by omegadeep10**
Switch from using `etc/init.d` scripts to `systemd` configuration files for better support and simpler user experience

-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by camsaul** [comment]
Similar PRs: #9037 #7858

I want to merge one of these but with 3 PRs for the same thing, which one should we merge? 😖

**Comment by omegadeep10** [comment]
#9037 seems to be pretty much the same, except it adds instructions on setting up an unprivileged user for Metabase. This is definitely very useful. It also has instructions on setting up a `syslog` conf, which  I think is to redirect messages to `/var/log/metabase.log` if I'm not mistaken? I'm not sure about the advantages or disadvantages of this approach.

#7858 is also the same.


I'd be happy to do some research and go over wording on all three versions. I'll then integrate it into my PR so we have a single unified doc. Working on it today, should be ready by tomorrow; I'll tag you when ready.

**Comment by omegadeep10** [comment]
I've centralized the changes from the other similar PRs. Specifically, I've integrated the instructions on creating an unprivileged user and the `rsyslog` conf. 

@camsaul

**Comment by walterl** [comment]
Closed due to inactivity, overlap with merged #9037.

**Pull request closed without merging**
