### PR TITLE
Remove the `field-filter-operators-enabled?` feature flag

### PR DESCRIPTION
**Pull request by daltojohnso**
https://github.com/metabase/metaboat/issues/144

This PR exposes the operator-based parameter filters to everyone by removing the associated feature flag.

I've also included a small bug fix in https://github.com/metabase/metabase/pull/19378/commits/a3f5e0290af6326cb174d10522e078b2e55ed567. Template tags with widget types of `"category"` and `"location/..."` weren't populating the widget type dropdown in the variables sidebar of the native query editor.

**Testing**
1. Create a native question with template `select * from PRODUCTS where {{category}}` and set the filter type to "field filter" and the widget type to "String". The parameter widget should behave as it would've before if set to a "Category" widget type. The "category" should no longer show up.
2. Create a native question with template `select * from PEOPLE where {{state}}` and set the filter type to "field filter" and the widget type to "Location". Sub location types should no longer be available. Instead, the types should mirror the various string operator types.
3. Create a GUI question (something simple like the Products table) and add it to a dashboard. Create a "Text or Category" > "Dropdown" filter and map it to the Category field of the Products table. Play around with it and make sure it shows field values and filters correctly.
4. Add a Number filter and map it to Products.Rating and make sure it works/filters/etc.
5. Checkout `master` and connect a question on a dashboard to a Category filter. Check this branch out and make sure it still works.
6. Checkout `master` and create a native question with a Category filter and make sure it works after checking this branch back out.
7. Checkout `master` and create a native question with a Location/State filter and make sure it works after checking this branch back out.

### CODE REVIEW

**Review by camsaul — APPROVED** [review]
Backend changes LGTM.

**Review by flamber — COMMENTED** [review]
There are 3 of these, which I'm quite sure was left on purpose if I remember correctly.
`mockSessionProperty("field-filter-operators-enabled?", false);`

But perhaps there has been so much revamp that it's completely not needed anymore? Then I would guess that those tests are not needed anymore either.

Or are we completely blocking the old style? If so, then I need a lot of time to test this with many different upgrade scenarios.

Though, I'm almost at a point where I would prefer this merged as-is, since then I wouldn't be the only one testing and then it'll have a month baking time in master, which would give it a greater chance to flush out everything.

**Comment by daltojohnso** [comment]
@flamber -- my assumption is we are completely removing the old UI so that, for everyone, it'll be like `field-filter-operators-enabled?` is enabled.

I replaced `old-parameters.cy.spec.js` with tests that verify that parameters like `category` and `location/city` still work, and I also added `dashboard-filters-sql-text-category.cy.spec.js` to check old category widget-type template tags in the native query editor. I'm happy to add more tests around this transition to make sure we're not breaking anything in the switch.

**Comment by flamber** [comment]
@daltojohnso Perfect. I expected that too, but the tests explicit tests with the `false` was done as upgrade tests. It sounds like you've already covered most of that, so those three tests can likely be removed.
It's getting a little late, so I'll continue hammering on this in the morning, but I've already found a few things.
But I would still be good with merging this and picking up any stray cats in other PRs.

**Comment by alxnddr** [comment]
It must be closing https://github.com/metabase/metabase/issues/3035

**Review by alxnddr — APPROVED** [review]
Works as expected, looks good 👍

**Comment by flamber** [comment]
@alxnddr It's closing a handful of issues, but I'll be going through those as I test.

**Pull request merged**
