### PR TITLE
specific version numbers and replace with the latest version in the w…

### PR DESCRIPTION
**Pull request by salsakran**
…ebsite

Manually updating these is obviously not working. Replaced any version other than `latest` with the jekyll site variable for the version the documentation site is on.

### CODE REVIEW

**Comment by tlrobinson** [comment]
Does that mean older versions of the docs will have the latest version number, or is it set up in such a way that they will get their own version?

**Comment by salsakran** [comment]
ugh. Good point.

**Comment by salsakran** [comment]
So with this setup, all docs will always point to the latest version of an artifact.

**Comment by salsakran** [comment]
though on further thought I'm not sure we'd ever want people to land someplace and launch an old version.

**Comment by tlrobinson** [comment]
I could go either way. It seems a little weird to have the old docs change when a new version is added, but it's still preferable to forgetting to update the version to the latest.

**Comment by salsakran** [comment]
yeah, I think in our case, given that we don't support older versions (practically), if someone ends up on this page, I'd want them to install the latest one. I can deal with a bit of weirdness.

**Pull request merged**
