### PR TITLE
Fix 'additional fields' functionality

### LINKED ISSUE #9144: Can't add linked columns to a table
This is on master on our stats instance. The expected behavior is that I click the plus and the column gets added to my list of visible columns in the modal, and gets added to the far right of my table. Instead, nothing happens. Not seeing any JS console errors, and the logs don't seem to have anything to say on the matter either.

fk-cols

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #9144

I'm not exactly sure how this broke, but the underlying problem is `fieldRefForColumn` [and similar functions](https://github.com/metabase/metabase/issues/8859) return non-normalized MBQL like `["fk->", 1, 2]` but should be returning `["fk->", ["field-id", 1], ["field-id", 2]]`.

Until we have some way to migrate/normalize `visualization_settings` we'll have to just make sure to normalize `fieldRef` in functions like `findColumnIndexForColumnSetting`.

### CODE REVIEW

**Comment by tlrobinson** [comment]
FYI I've also fixed this in `notebook-mode`

**Comment by RMMSecurity** [comment]
OMG @tlrobinson I'm going to test this now!!

**Comment by ejhayes** [comment]
@tlrobinson any idea if this will be merged at some point? The linked columns feature is pretty much unusable with this bug.

**Comment by tlrobinson** [comment]
@ejhayes Yes it will be.

**Comment by mazameli** [comment]
@tlrobinson looks like this just needs lint/FE unit tests to pass and a code review from @paulrosenzweig or @kdoh, yeah?

**Comment by paulrosenzweig** [comment]
I pulled these changes into #10358, which also changes the `ForeignFieldReference` type.

**Pull request closed without merging**
