### PR TITLE
Fix Padding on Single Database Names

### LINKED ISSUE #21276: Incorrect padding on native query page with single database (on master)
**Describe the bug**
Incorrect padding on native query page with single database on `master`. See screenshot for more information

**Logs**
N/A

**To Reproduce**
1. Start a new Metabase instance and do not add any data source
2. Go to New -> Native query

**Expected behavior**
There is sufficient padding around the Metabase name

**Screenshots**
On 0.42.0
Metabase 0 42 0

On master
Metabase master 2351795

**Information about your Metabase Installation:**
Chrome 99.0.4844.84
Metabase master (2351795) on H2

**Severity**
Looks bad

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by iethree**
## Before

- https://github.com/metabase/metabase/pull/21189 removed a fixed min-height style property, and introduced a regression where single-database names wouldn't have appropriate padding
Screenshot from 2022-03-28 09-34-06

## Changes

- updates single database name component and placeholder components to use block-level HTML elements so that their padding is correctly applied
- update single db component name to more accurately reflect what it does
- resolves #21276 

##  After

- Single and multiple databases names have appropriate padding

Screenshot from 2022-03-28 09-36-44 Screenshot from 2022-03-28 09-36-26

### CODE REVIEW

**Comment by flamber** [comment]
@iethree This wasn't backported, so is backport of this PR needed?

**Review by alxnddr — APPROVED** [review]

**Comment by iethree** [comment]
> @iethree This wasn't backported, so is backport of this PR needed?

@flamber I'll create a single backport for this PR and https://github.com/metabase/metabase/pull/21189, thanks for bearing with me as I get the hang of the backport process

**Comment by flamber** [comment]
@iethree I would recommend just leaving everything for 43 instead of spending more time trying to get them backported to 42.

**Comment by iethree** [comment]
> @iethree I would recommend just leaving everything for 43 instead of spending more time trying to get them backported to 42.

Sorry, I didnt see this until I opened https://github.com/metabase/metabase/pull/21296 This was actually some helpful education for me on the backporting process and considerations.

**Pull request merged**
