### PR TITLE
Implement waterfall static visualization

### PR DESCRIPTION
**Pull request by alxnddr**
Epic: https://github.com/metabase/metabase/issues/18676

Add waterfall static visualization renderers. The charts created following an already defined approach which results in some code duplication and limitations. It will be addressed further in static viz development.

Screen Shot 2021-11-09 at 02 21 39

### How to verify
- Run Metabase locally and go to http://localhost:3000/_internal/static-viz
- Ensure the waterfall static visualizations render charts correctly

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Review by ranquild — APPROVED** [review]
Works correctly. There is a small issue when there are mostly negative values, which might exist in other chart types:

Screen Shot 2021-11-09 at 2 43 46 pm

There is also an issue when labels are positioned vertically, compare the distance between labels and ticks in other charts:

Screen Shot 2021-11-09 at 2 45 19 pm

**Comment by alxnddr** [comment]
@ranquild thanks, fixed these

**Review by kdoh — APPROVED** [review]
Looking good!

**Pull request merged**
