### PR TITLE
Add Big Query Log Processor for HoneySql

### LINKED ISSUE #31153: log() - logarithm function calculates wrong result in BigQuery because parameters backwards
### Describe the bug

- Using the Metabase `log()` function with BigQuery calculates the wrong result because Metabase mixes up the parameters
- As per [these BigQuery docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#log), `log()` should be used like `log(x, base)`, but Metabase is sending `log(base, x)` to BigQuery resulting in incorrect results.

### To Reproduce

1. Create a Question on a BigQuery table
2. Add a custom expression called log10 - `log(10)`
3. Add a custom expression called log100 - `log(100)`
4. Add a custom expression called log1000 - `log(1000)`
5. Click Visualize to see the results of the custom expressions
image

Values:
  - log10 should be 1
  - log100 should be 2
  - log1000 should be 3

6. Click View SQL and see that x and base are reversed:
```
SELECT `zendesk_16700.datesAndAmounts`.`date` AS `date`, `zendesk_16700.datesAndAmounts`.`amount` AS `amount`, log(10, 10) AS `log10`, log(10, 100) AS `log100`, log(10, 1000) AS `log1000` FROM `zendesk_16700.datesAndAmounts`
```

### Expected behavior

- Should use BigQuery `log()` function like `log(x, base)` instead of `log(base, x)`

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Metabase version: v1.46.4
```

### Severity

P1 - producing incorrect result with no error or warning

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mayankagarwals**
Fixes https://github.com/metabase/metabase/issues/31153

### CODE REVIEW

**Comment by mayankagarwals** [comment]
A first version of the solution @likeshumidity

Seem to be facing some issue with setting up metabase locally, can only see these three databases to connect to. 
image


I'll figure this out and get back

CC @qnkhuat

**Comment by mayankagarwals** [comment]
@qnkhuat I'm blocked on the testing part, any idea why the above issue might happen?

**Comment by qnkhuat** [comment]
Try starting the repl with `DRIVERS=bigquery-cloud-sdk clj -M:dev:ee:ee-dev:drivers:drivers-dev`

**Comment by mayankagarwals** [comment]
Yep, that worked. Thanks @qnkhuat! 

In my opinion, I've fixed the problem of Metabase SQL -> honeysql. The honeysql for `log(2)` is `[:log10 2]` which is correct according to [this](https://john.shaffe.rs/honeysql/?q=%5B%3Alog10%202%5D&opt=%7B%3Achecking%20%3Astrict%0A%20%3Aparams%20%7B%3Aparam1%20%22gabba%22%2C%20%3Aparam2%202%7D%0A%20%3Apretty%20true%7D) evaluator 
```
(defmethod sql.qp/->honeysql [:bigquery-cloud-sdk :log]
   [driver [_ field]]
   [:log10 (sql.qp/->honeysql driver field)])

```

But the output sql is 
```
  "SELECT `source`.`string_field_0` AS `string_field_0`, `source`.`string_field_1` AS `string_field_1`, `source`.`string_field_2` AS `string_field_2`, `source`.`string_field_3` AS `string_field_3`, `source`.`string_field_4` AS `string_field_4`, `source`.`int64_field_5` AS `int64_field_5`, `source`.`log2` AS `log2` FROM (SELECT `test2.test`.`string_field_0` AS `string_field_0`, `test2.test`.`string_field_1` AS `string_field_1`, `test2.test`.`string_field_2` AS `string_field_2`, `test2.test`.`string_field_3` AS `string_field_3`, `test2.test`.`string_field_4` AS `string_field_4`, `test2.test`.`int64_field_5` AS `int64_field_5`, `log10` AS 2 AS `log2` FROM `test2.test`) `source` LIMIT 1048575",
```

Focus on the native query  `log10 AS 2 AS log2` which should be `log10(2) AS log2`

My hunch is there is something that needs to be fixed in honeysql->native conversion also here

**Comment by willbryant** [comment]
@mayankagarwals I think you are using the HoneySQL 2 syntax but the bigquery driver is still on HoneySQL 1 (see https://www.metabase.com/docs/master/developers-guide/driver-changelog#honey-sql-2). Try using `hsql/call`?

**Comment by piranha** [comment]
Merged in #34609. Thanks, @mayankagarwals!

**Pull request closed without merging**
