### PR TITLE
Fix sent pulse to Private Channels

### PR DESCRIPTION
**Pull request by wagnerads**
The slack list private groups at another end point. **https://api.slack.com/methods/groups.list**
Issue https://github.com/metabase/metabase/issues/2694
###### TODO
-  [x] Sign our [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)

### CODE REVIEW

**Comment by tlrobinson** [comment]
I haven't tested this, but does it only return groups that the user who created the token are in?

**Comment by wagnerads** [comment]
Yes, as described in the documentation Slack. 

> This method returns a list of private channels in the team that the caller is in and archived groups that the caller was in. The list of (non-deactivated) members in each private channel is also returned.

**Comment by mvlbarcelos** [comment]
+1

**Comment by wagnerads** [comment]
CLA signed.

**Comment by salsakran** [comment]
Quick couple of questions before moving forward with this --

By my read, this takes the private channels of the person hooking up MB with Slack and publishes them to anyone creating a Pulse. I.e. I'm an analyst, I connect slack to Metabase once, and at *every* point in the future anyone in the company who can create a pulse can see my list of private channels. 

Imo, the right thing to do here is to allow users to Login Via Slack (similar to our #1008 ) and then get a list of the current user's private channels. That way in the above scenario, I get *my* list of private channels when I create a Pulse, not the poor embarrassed analyst's.

Thoughts?

**Comment by diegonetto** [comment]
@salsakran @wagnerads any plans on moving forward with this?

More and more people are asking for this at my startup, happy to help if needed.

**Comment by cdruxerman** [comment]
@salsakran just wanted to see if there is an update, definitely interested in this feature

**Comment by salsakran** [comment]
closing this PR since there hasn't been a change in approach. As noted above this PR solves #2694 but introduces a bigger issue. 

@wagnerads by all means re-open if you change approaches, but going to close this particular PR

**Pull request closed without merging**
