### PR TITLE
Add database syncing status

### PR DESCRIPTION
**Pull request by ranquild**
Epic: https://github.com/metabase/metabase/issues/18675

A different approach to add a database syncing indicator that doesn't overlap with other elements.

Screen Shot 2021-12-13 at 9 35 15 am

Screen Shot 2021-12-13 at 9 35 02 am

How to test:
- Go to Admin > Database > New database
- Add a new H2 database (you can copy connection details from Sample Dataset)
- You should see the indicator in the bottom right corner
- It should be visible in other parts of the app

### CODE REVIEW

**Comment by ranquild** [comment]
@mazameli could you please have a look? I also need help with tooltip copy.

**Review by alxnddr — APPROVED** [review]
Nice 👏  It does not conflict with sidebars anymore

**Review by mazameli — CHANGES_REQUESTED** [review]
My understanding that I confirmed with @cdeweyx was that this little circle+spinner was supposed to be the new collapsed state of the larger "snackbar" status indicator. I can't see any way in this branch to see or toggle the component to the expanded snackbar state, which I assumed would be its default state.

**Comment by mazameli** [comment]
I found something that's related but I'm unsure if it was added in this PR or not: the message about exploring the Sample Database shows up _every time_ I go to the homepage while a database is syncing. I'd expect it to just show up one time. Here's a recording: https://www.loom.com/share/d3e343e6ce45442183a6d80808ac9767

**Comment by mazameli** [comment]
@cdeweyx, I'm not sure what the intended behavior is here, but one thing I'm seeing is that when I'm logged in as a non-admin, I don't see any indication that tables aren't ready yet. 

Non-admin on the left here; admin on the right:

image

image

image

**Review by mazameli — APPROVED** [review]
It seems the issues I found aren't reproducible. 🤷🏼‍♂️

**Pull request merged**
