### PR TITLE
Add approved domains FE validation

### LINKED ISSUE #18235: Dashboard Subscription test email button does not show error messages
If sending the email fails for one reason or another (such as the email domain being disallowed) the `Send email now` button changes to `Sending failed` but the sidebar does not show the error message returned by the REST API.

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/18235

How to test:
- Run Metabase EE
- Go to Admin > General and set approved email domain
- Go to a dashboard, open the subscription sidebar and enter an email recipient with another domain
- Click Send now button
- You should see an error message that this domain is not allowed

Dashboard subscriptions:
Screen Shot 2021-10-08 at 5 48 59 pm

Alerts:
Screen Shot 2021-10-08 at 6 21 01 pm

Audit app:
Screen Shot 2021-10-11 at 4 25 02 pm

### CODE REVIEW

**Review by nemanjaglumac — DISMISSED** [review]
After clicking "Send now" button, there is not "Sending failed" state any more. It shows "Email sent".



... which is why this related e2e test failed
image

**Comment by mazameli** [comment]
## Ideal

My ideal would be that we do some email validation _before_ that button is pushed or before saving the subscription, like once the entered email address or recipient is tokenized. I don't like how this restriction is invisible to the user until the very last moment, and would prefer if we could let them know what they're allowed to do sooner.

**Typing in email address**

image

**Then if we detect any malformed or disallowed addresses, we can display a corresponding error message, and keep the `Send Email Now` and `Done` buttons disabled until the offending addresses are removed:**

image

**Here would be the state after removing the bad address(es):**

image

---

## Alternative solution

If we can't do front-end validation, then here's what I'd suggest:

- We have a button that has a built in `Success` or `Failed` state that we use for example on the `/admin/settings/email` page for the "send email now" button there. We can use that button here to show if the sending failed.
- If it failed we should display the error message below the "send email now" button until they click the "send email now" button again and have a successful send.

**Bad email entered here**

image

**After clicking the Send Email Now button**

image

**That Success/Failed button component I mentioned automatically reverts back to its default state after a few seconds, so it would look like this:**

image

**Even after correcting the email address(es), the error message stays there until the Send Email Now button is clicked again**

image

The error finally disappears after clicking "Send Email Now" and having it send successfully:

image

**Review by mazameli — DISMISSED** [review]
Amazing! Just one small string correction, and then I think it should be merged. 👏🏼

**Comment by ranquild** [comment]
@nemanjaglumac Added missing tests for approved domains validation for the audit app, please have a look.

**Review by daltojohnso — APPROVED** [review]
looks good!

**Pull request merged**
