### PR TITLE
Visual repro #20552: Static viz Y-axis values are rounded, which are confusing for low values

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Creates a visual repro for #20552
- Creates a visual repro for #20554

### How to test this manually?
- `yarn test-visual-open`
- `frontend/test/metabase-visual/static-visualizations/reproductions/20552-static-viz-rounding-y-axis-values.cy.spec.js`
- Observe the Cypress GUI and notice the rounding for the Y-axis values (see the screenshot)
- Also, from that same screenshot it is clear that data point values (#20554) are not being rendered

### Additional notes:
- Once the issue is fixed, please remove the `.skip` part (unskip the test completely)
- Visually inspect and make sure the values are not rounded anymore
- Merge the test together with the fix

### Screenshots:
image

How the graph (properly) looks like in the dashboard before sending it as a subscription:
image

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Comment by nemanjaglumac** [comment]
@flamber and @alxnddr - It made sense to unify repros for #20552 and #20554 in this one. Please let me know if this works for you?

**Comment by nemanjaglumac** [comment]
> I don't know how we're doing it, so someone else has to approve if it makes sense.

Unlike the regular reproductions that have explicit assertions, writing tests for visual regressions makes sense only when something is already working, because it has to start from a valid point.

However, I still believe there is a benefit in writing these visual regressions tests up front. The only "catch" is that they **have to** be skipped until the issue is fully fixed or a feature is implemented.

Then, after a visual inspection, we can enable the visual regression test and merge it together with the fix. From that point on, it will catch regressions.

**Comment by alxnddr** [comment]
In my opinion, with visual tests, it makes sense to create tests that cover more than one thing because we will pay for each snapshot

**Comment by dpsutton** [comment]
We have some prior art for parsing and interpreting values in the resulting svg forms. This allows a bit more structured testing than just visual tests. For example, in `metabase.pulse.render.js-svg-test`

```clojure
      (testing "The svg string has formatted axes"
        (let [spec (s/cat :y-axis-labels (s/+ (s/tuple
                                               #{"#text"}
                                               #(and (string? %)
                                                     ;; ["#text" "prefix0.00"]
                                                     (re-matches #"prefix\d+\.\d{2}" %))))
                          :x-axis-labels (s/+ (s/tuple
                                               #{"#text"}
                                               #(and (string? %)
                                                     ;; ["#text" "1/1/2020"]
                                                     (re-matches #"\d+/\d+/\d{4}" %)))))
              text-nodes (->> svg-hiccup (tree-seq vector? rest) (filter text-node?))]
          (is (= true (s/valid? spec text-nodes))
              text-nodes)))
```

This parses the svg and selects all text nodes and ensures that the formatting is applied to both dates and numbers.

**Pull request closed without merging**
