### PR TITLE
Audit docs

### PR DESCRIPTION
**Pull request by victoriaspek**
Let me know if there's anything else I should include!

### CODE REVIEW

**Comment by salsakran** [comment]
what are we trying to do with these docs? Eg, is it simply to inform people that certain things are possible?

This seems very sparse and enumerating the screens vs actually serving as either a guide or a reference.

@mazameli are there things that are counter intuitive we should call out? Anything that people have been confused by?

**Comment by mazameli** [comment]
Off the top of my head, some things I recall people asking:
- When clicking on a query in the log of previously run queries, do I see a snapshot of the query at the time it was run, or as it is now? (It's the former for ad hoc, and I believe the latter for saved questions.)
- Confusion around whether SQL queries are counted in audit logs of queries run against specific tables. (They're not, since we only know what _database_ a SQL query is run against.)
- Is the "new users over time" chart when new users are _created_ or when they first _log in_?
- Can I download/export these logs? (Not yet.)
- I'd call attention to the charts on the Dashboard and Questions overviews that show the most popular items and their relative slowness, which help highlight areas where performance could be optimized.

**Comment by mbvictoria** [comment]
@salsakran @mazameli, new commit has tons of changes.

**Review by camsaul — APPROVED** [review]
read thru it. Sounds good to me

**Pull request merged**
