### PR TITLE
Allow metabase container to be started as non-root

### LINKED ISSUE #9861: Docker image can not run as non-root
This is in relation to #4734 - it seems like the container can not run as non-root which is an issue in some kubernetes configurations. 

Switching to UID 2000 or user 'metabase' leads to issues starting up:
grafik

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #13147: Run metabase helm chart on a kubernetes cluster which has pod security policy
**Is your feature request related to a problem? Please describe.**
If a k8s cluster enabled pod security policy, the Metabase deployment cannot be scaled up since the limitation of the cluster is runAsNonRoot, but Metabase not.

**Describe the solution you'd like**
Able to configure securityContext runAsUser runAsGroup

**Describe alternatives you've considered**
Able to configure serviceAccount for Metabase

**How important is this feature to you?**
Since the implementation of my company's requirement is urgent, I will push a modified helm chart into my company's helm repository, just make it can use a serviceAccount claim the permission to run as root.

**Additional context**
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
https://kubernetes.io/docs/concepts/policy/pod-security-policy/

### PR DESCRIPTION
**Pull request by michael-todorovic**
Fixes: #9861
Closes: #13147 

This PR aims to fix #9861, root-cause of #13147.

The principle is very simple: the image itself is able to run as non-root. The `run_metabase.sh` embeds code to migrate permissions local h2 database from root to user to ease people life. However, it requires the container to be run as root.

If you run H2: as long as your permissions are fixed with the correct user, the container can be run as non-root.
If you don't run H2 (rds, pgsql, mysql, etc), you don't need to start the container as root at all as there are no permissions to fix so we can start the server immediately.

How to test?

```
cd bin/docker/ &&  bash ./build_image.sh release v0.36.4 # build metabase/metabase:v0.36.4 with this PR
docker run -u 1234:1234 -p 3000:3000 --rm --name metabase -e MB_DB_CONNECTION_URI="postgres://<pgsqlServer>:5432/<pgsqlDatabase>?user=<pgsqlUser>&password=<pgsqlPassword>" metabase/metabase:v0.36.4
```

### CODE REVIEW

**Comment by Tijmen34** [comment]
@michael-todorovic Do you need some assistance on this PR? I really need this feature :)

**Comment by Andrioshe** [comment]
I also need this PR and would like to assistance.

**Comment by michael-todorovic** [comment]
I'll take some time today to review why the pipeline fails. (I totally forgot the PR 😅 sorry about that)

**Comment by michael-todorovic** [comment]
So I refreshed the branch from master as it was failing but it's still failing on some unrelated tests. If a maintainer can have a look, it could help :)

**Comment by Tijmen34** [comment]
@flamber, @nemanjaglumac I reckon you are both maintainers, can you take a look at this please?

**Comment by Tijmen34** [comment]
@camsaul Any chance you got some time to review this PR? :)

**Comment by camsaul** [comment]
@michael-todorovic, is there a reason for all of the seemingly unrelated changes in this PR (e.g. things like moving around lines that set env vars)? We're wary to make any changes to the Metabase run script without an extremely careful review, but it's a lot harder to review this with all of these unrelated changes

**Review by camsaul — CHANGES_REQUESTED** [review]
There are merge conflicts in `run_metabase.sh`

I think once those are fixed we should be able to merge this.

**Review by camsaul — APPROVED** [review]
ok, I fixed the merge conflicts. This looks good to me now.

**Comment by zheileman** [comment]
Hello @michael-todorovic,

First of all thank you for your work and for taking time to try to solve this long standing issue.

We have a kubernetes deployment in a cluster that forbids use of root in containers.

We've tested the latest version of metabase `v0.37.3` which includes your tweaks and despite that it continues failing to run in a non-root container.
We are using image `metabase/metabase:v0.37.3` in our deployment.yml

Example logs:
```Pulling image "metabase/metabase:latest"
0s    Normal    Pulled    pod/xyz-metabase-deployment-547c96c597-5wmdf    Successfully pulled image "metabase/metabase:latest"
0s    Warning   Failed    pod/xyz-metabase-deployment-547c96c597-5wmdf    Error: container has runAsNonRoot and image will run as root
```

We think this is because some of the scripts that the `Dockerfile` use, or the entrypoint itself, requires root to either do initialisation/setup or to create the `metabase` (2000) user/group that is used later on to spawn the process (this one, running as non-root so that's good):

```bash
> ps
PID   USER     TIME  COMMAND
1   metabase   1:02   java -XX:+IgnoreUnrecognizedVMOptions -Dfile.encoding=UTF-8 -Dlogfile.path=target/log -XX:+ExitOnOutOfMemoryError -server -jar /app/metabase.jar
```

Are we missing something here? Is there perhaps another image that can run as non-root as per your example, and if so, is that other image pushed to docker hub?

Worth also noting that I can't get it to work following your instructions but I can't rule out this might be an issue with my local system:

```bash
➜  docker git:(master) ./build_image.sh release v0.37.3
Building Docker image metabase/:v0.37.3 from official Metabase release v0.37.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 404 
```

Thanks again!

**Comment by michael-todorovic** [comment]
Hello @zheileman, thanks for trying :) 
From what I see, the [fixes](https://github.com/metabase/metabase/pull/13214/files#diff-40207310251e432def3ac05509f9eb8ee6073ae0fc1e5bfa0ac57121db4332f5R42-R46) are not in [0.37.3](https://github.com/metabase/metabase/blob/v0.37.3/bin/docker/run_metabase.sh) yet (see [history](https://github.com/metabase/metabase/commits/v0.37.3/bin/docker/run_metabase.sh)).

@camsaul do you have an idea which metabase release would have this MR in it?

**Comment by flamber** [comment]
@michael-todorovic `master` is the next upcoming major release, so in this case, that would be 0.38. And the issue(s) a PR closes gets a milestone tag applied too.

**Comment by zheileman** [comment]
Oh wow, I guess we were extremely excited to get this up and running as this is a big blocker for us.

I read the PR a few days ago, and this morning got the alert of a new release so just assumed these fixes were included as part of the new release.

Any idea why the `build_image.sh` is failing to curl some file?

**Comment by zheileman** [comment]
Hello, I can see the work in this PR is now merged to the master branch, and I've been trying to use it in a kubernetes cluster.

However I'm in what I believe is a catch-22 situation.

If I define in my deployment file a specific user, then it will not run as root, this is fine, but also it will bypass the creation of the users and setup of permissions in script `run_metabase.sh` ([line 42](https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh#L42)).

If I run it as root, then it will work, but the container will run as root, despite the metabase process itself not running as root. 

Am I missing something here?

Thank you in advance.

**Comment by flamber** [comment]
@zheileman 
But how should the creation of users be done with non-root?
The permission stuff is mostly for H2, which you most definitely should not be using on k8s, so you can ignore that.
And then there's a build-protection by making the JAR world readable (#10510), but that caused the image to almost double in size (#11416). We should probably find a way to protect against this, while not doubling the image.

What do you propose instead? You're welcome to submit a PR. It would probably be easier to understand if you provided examples.

**Comment by zheileman** [comment]
@flamber usually, with the docker images we control, the users/groups are created as part of the Dockerfile. So for example when using an alpine image, we add some users/groups and then we use that user, something like:

```sh
# add non-root user and group
RUN addgroup -g 1000 -S appgroup && \
    adduser -u 1000 -S appuser -G appgroup

# change some permissions
RUN chown -R appuser:appgroup foobar

# run container as user
USER 1000
```

Not sure if something like this could be done with metabase. Maybe with an intermediate Dockerfile we control. I can try.

**Comment by JFryy** [comment]
This is an old issue, and I am sure anyone interested has already done so in this thread, but to confirm on what @zheileman said this does indeed work with the intermediate Dockerfile from what I have tried with configuring with DB Envars:

Note we just need the username and group, this has issues working without specifying a DB.
```
from metabase/metabase:v0.45.1

# add non-root user and group
RUN addgroup -g 1000 -S metabase-nonroot && \
    adduser -u 1000 -S metabase-nonroot -G metabase-nonroot

# run container as user
USER metabase-nonroot

ENTRYPOINT ["/app/run_metabase.sh"]
```

Start postgres container on same docker network and connect (after making a table name)
```
docker run -p 5432:5432 -e POSTGRES_PASSWORD=test --network=bridge postgres & 
docker build . -t metatest
docker run -e MB_DB_TYPE="postgres" -e MB_DB_DBNAME='metabase' -e MB_DB_PORT='5432' -e MB_DB_USER='postgres' -e MB_DB_PASS='test' -e MB_DB_HOST='172.17.0.2' --network=bridge -p 3000:3000 metatest
```

**Pull request merged**
