### PR TITLE
Draggable table columns

### PR DESCRIPTION
**Pull request by tlrobinson**
Drag table columns to reorder them

TODO:
- [x] fix drill throughs

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers thoughts on merging this?

**Comment by tlrobinson** [comment]
@metabase/core-developers revisiting this since we've released 0.29. Can I get some reviews?

**Comment by mazameli** [comment]
Trying to pin down exactly what causes this, but sometimes when I reorder columns with a pivoted table, I get the "every field is hidden" message and the below JS error:

pivot-table-columns-error

```
settings.js:217 Error getting setting table.columns TypeError: Cannot read property 'name' of null
    at Table.jsx:76
    at Array.map (<anonymous>)
    at Object.isValid (Table.jsx:76)
    at getSetting (settings.js:202)
    at getSettings (settings.js:256)
    at Visualization.render (Visualization.jsx:350)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
```

**Comment by mazameli** [comment]
There are also cases with pivot tables where it won't let me reorder at all:

can t-reorder

```
warning.js:33 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Draggable component.
printWarning @ warning.js:33
warning @ warning.js:57
getInternalInstanceReadyForUpdate @ ReactUpdateQueue.js:46
enqueueSetState @ ReactUpdateQueue.js:207
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
Draggable._this.onDragStop @ react-draggable.js:236
DraggableCore._this.handleDragStop @ react-draggable.js:2052
settings.js:217 Error getting setting table.columns TypeError: Cannot read property 'name' of null
    at Table.jsx:76
    at Array.map (<anonymous>)
    at Object.isValid (Table.jsx:76)
    at getSetting (settings.js:202)
    at getSettings (settings.js:256)
    at selectors.js:253
    at index.js:76
    at index.js:36
    at index.js:90
    at index.js:36
getSetting @ settings.js:217
getSettings @ settings.js:256
(anonymous) @ selectors.js:253
(anonymous) @ index.js:76
(anonymous) @ index.js:36
(anonymous) @ index.js:90
(anonymous) @ index.js:36
mapStateToProps @ QueryHeader.jsx:44
mapToPropsProxy @ wrapMapToProps.js:43
handleNewPropsAndNewState @ selectorFactory.js:34
handleSubsequentCalls @ selectorFactory.js:67
pureFinalPropsSelector @ selectorFactory.js:74
runComponentSelector @ connectAdvanced.js:26
componentWillReceiveProps @ connectAdvanced.js:150
(anonymous) @ makeAssimilatePrototype.js:15
(anonymous) @ ReactCompositeComponent.js:608
measureLifeCyclePerf @ ReactCompositeComponent.js:73
updateComponent @ ReactCompositeComponent.js:607
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
updateChildren @ ReactChildReconciler.js:107
_reconcilerUpdateChildren @ ReactMultiChild.js:204
_updateChildren @ ReactMultiChild.js:308
updateChildren @ ReactMultiChild.js:295
_updateDOMChildren @ ReactDOMComponent.js:944
updateComponent @ ReactDOMComponent.js:758
receiveComponent @ ReactDOMComponent.js:720
receiveComponent @ ReactReconciler.js:122
updateChildren @ ReactChildReconciler.js:107
_reconcilerUpdateChildren @ ReactMultiChild.js:204
_updateChildren @ ReactMultiChild.js:308
updateChildren @ ReactMultiChild.js:295
_updateDOMChildren @ ReactDOMComponent.js:944
updateComponent @ ReactDOMComponent.js:758
receiveComponent @ ReactDOMComponent.js:720
receiveComponent @ ReactReconciler.js:122
updateChildren @ ReactChildReconciler.js:107
_reconcilerUpdateChildren @ ReactMultiChild.js:204
_updateChildren @ ReactMultiChild.js:308
updateChildren @ ReactMultiChild.js:295
_updateDOMChildren @ ReactDOMComponent.js:944
updateComponent @ ReactDOMComponent.js:758
receiveComponent @ ReactDOMComponent.js:720
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
updateChildren @ ReactChildReconciler.js:107
_reconcilerUpdateChildren @ ReactMultiChild.js:204
_updateChildren @ ReactMultiChild.js:308
updateChildren @ ReactMultiChild.js:295
_updateDOMChildren @ ReactDOMComponent.js:944
updateComponent @ ReactDOMComponent.js:758
receiveComponent @ ReactDOMComponent.js:720
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
performUpdateIfNecessary @ ReactCompositeComponent.js:558
performUpdateIfNecessary @ ReactReconciler.js:154
runBatchedUpdates @ ReactUpdates.js:148
perform @ Transaction.js:141
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:65
onStateChange @ connectAdvanced.js:202
(anonymous) @ makeAssimilatePrototype.js:15
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:71
(anonymous) @ store.js:18
dispatch @ applyMiddleware.js:35
_callee$ @ redux.js:16
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.(anonymous function) @ runtime.js:117
step @ redux.js:13
(anonymous) @ redux.js:13
Promise.then (async)
step @ redux.js:13
(anonymous) @ redux.js:13
(anonymous) @ redux.js:13
(anonymous) @ redux.js:29
(anonymous) @ store.js:17
(anonymous) @ bindActionCreators.js:3
onColumnReorder @ TableInteractive.jsx:268
onStop @ TableInteractive.jsx:462
Draggable._this.onDragStop @ react-draggable.js:213
DraggableCore._this.handleDragStop @ react-draggable.js:2052
settings.js:217 Error getting setting table.columns TypeError: Cannot read property 'name' of null
    at Table.jsx:76
    at Array.map (<anonymous>)
    at Object.isValid (Table.jsx:76)
    at getSetting (settings.js:202)
    at getSettings (settings.js:256)
    at Visualization.render (Visualization.jsx:350)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
```

**Comment by mazameli** [comment]
If I group a raw or aggregated query by a field or two, and then reorder the result columns, if I then try to add more grouping fields and rerun the query, the new fields don't show up. This does not happen if I do not reorder the columns.

reordering-raw-table

```
warning.js:33 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Popover component.
printWarning @ warning.js:33
warning @ warning.js:57
getInternalInstanceReadyForUpdate @ ReactUpdateQueue.js:46
enqueueSetState @ ReactUpdateQueue.js:207
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
(anonymous) @ Popover.jsx:86
setInterval (async)
_getPopoverElement @ Popover.jsx:81
(anonymous) @ makeAssimilatePrototype.js:15
_renderPopover @ Popover.jsx:278
(anonymous) @ makeAssimilatePrototype.js:15
componentDidMount @ Popover.jsx:94
(anonymous) @ makeAssimilatePrototype.js:15
(anonymous) @ ReactCompositeComponent.js:262
measureLifeCyclePerf @ ReactCompositeComponent.js:73
(anonymous) @ ReactCompositeComponent.js:261
notifyAll @ CallbackQueue.js:74
close @ ReactReconcileTransaction.js:78
closeAll @ Transaction.js:207
perform @ Transaction.js:154
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145
ListSearchField.jsx:31 Uncaught TypeError: _this2._input.focus is not a function
    at ListSearchField.jsx:31
```

**Review by mazameli — CHANGES_REQUESTED** [review]
There are some issues that need fixing which I mentioned, but I really like this functionality. 

A few additional things I observed, but which aren't hard blockers imho:
- There isn't _great_ affordance for this, but I'm not really sure how/if we'd want to play that up more without it taking too much prominence. I.e., we don't want to overemphasize this feature and consequently overshadow the fact that the can click on the heading to access the actions menu. (And I don't really want to put move actions in the heading actions menu.)
- It would be nice if the window would scroll as I'm dragging a column in situations where I have a really wide table.
- There's definitely a bit of a lag when trying to drag columns on tables with lots of rows.

**Comment by mazameli** [comment]
1. Got it. Seems like something you should be able to do, but sounds like a separate issue.
2. Ah, you're right. Never noticed that before.
3. For sure. Doesn't seem like a deal-breaker.

**Comment by tlrobinson** [comment]
1. I think the actual correct thing is to respect the sort order, which we're not currently doing

**Comment by mazameli** [comment]
Hmm, looks like the most recent commits have broken table heading actions. I'm getting this when clicking on a heading:

```
warning.js:33 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Draggable component.
```

**Comment by tlrobinson** [comment]
Fixed.

I also added a slight CSS transition to the columns when dragging. Let me know what you think.

**Review by mazameli — APPROVED** [review]

**Comment by mazameli** [comment]
Looks good to me. Would be great to fix that (non-regression) issue with additional columns not appearing after reordering, because I suspect this PR cause/enable people to reorder columns more often, making them potentially run into that issue more.

**Pull request merged**
