### PR TITLE
Track new question creation

### PR DESCRIPTION
**Pull request by ranquild**
Epic: https://github.com/metabase/metabase/issues/18291

How to test:
- Install Snowplow Debugger browser extension
- Build docker image `docker build -t test .`
- Run Metabase `docker run -it --rm test` and complete the setup with tracking enabled
- Create new questions of all types (simple, complex, native) with the extension recording events
- Verify that the data, e.g. the `type`, `source`, was set correctly

### CODE REVIEW

**Comment by gusaiani** [comment]
@ranquild, is there any Docker log in I need to do? 🤔

I ran `docker build -t test .` and it fails after a long time.

Then doing `docker run -it --rm test` fails because it doesn't find an image.

**Review by alxnddr — COMMENTED** [review]
I created a native question, then clicked explore results, and instantly saved the new question.
It was recorded with `source : from_scratch` but probably should be `existing_question`. The same happens when I create a simple question based on a saved question.

Should we not send events when we duplicate a dataset? The button says "duplicate" question yet, but it would be great to either have separate events or a flag `is_dataset`. 
cc @kulyk

Besides that works great

**Comment by ranquild** [comment]
> is there any Docker log in I need to do? 🤔

@gusaiani Not you don't. For some reason, sometimes `docker build` fails sometimes for me too.

**Comment by ranquild** [comment]
> I created a native question, then clicked explore results, and instantly saved the new question. It was recorded with `source : from_scratch` but probably should be `existing_question`. The same happens when I create a simple question based on a saved question.

@alxnddr I've made a fix, please have a look. It follows the logic from here https://github.com/metabase/metabase/blob/88cc45c4e7527363aa694744fa057c66868ca971/frontend/src/metabase/query_builder/components/view/QuestionDataSource.jsx#L133. Basically if your new question is based on data from a saved question, it will send `source: "existing_question"`.

**Review by alxnddr — APPROVED** [review]

**Pull request merged**
