### PR TITLE
Fix a regression in getting subdimensions

### PR DESCRIPTION
**Pull request by ariya**
This is basically the next logical step after PR #16140, the fix is very similar.

To verify (copied from `scenarios/binning/sql.cy.spec.js` for convenience);

1. Ask a question, Native question
2. Type the following and saved as _SQL for binning_
```sql
SELECT ORDERS.CREATED_AT, ORDERS.TOTAL, PEOPLE.LONGITUDE
FROM ORDERS
JOIN PEOPLE ON orders.user_id = people.id
```
3. Ask a question, Simple question
4. Choose _SQL for binning_ from Saved Questions
5. Summarize, Group by TOTAL, 10 bins

**Before this PR**

Failed with an error: `Value does not match schema: {:query {:breakout [(named (not (":field clauses using a string field name must specify :base-type." a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :expression, :field")]}}`

image

**After this PR**

The query is successful:

image

### CODE REVIEW

**Review by alxnddr — APPROVED** [review]
LGTM 👍

**Comment by nemanjaglumac** [comment]
This is most probably out of scope of this fix (repro), but still worth mentioning.
Although there are no errors now and the chart finally renders, binning is far too granular. I thought the problem is just the 100 bins option, but then I changed it to 50 and got very similar (and equally incorrect) result. Please see the screenshots below.

100 bins (4939 bars)
image


50 bins (3976 bars)
image

FYI, the number of distinct values of `TOTAL` is 6313.

**Comment by ariya** [comment]
> What worries me is that what I'm seeing does not match the screenshot in the description cc @ariya.

Which is weird, since manually running the steps seem to produce the correct (expected) output.

In the Cypress tests, it seems that `openPopoverFromDefaultBucketSize` already triggers a call to `/dataset`. However, the query is wrong since it doesn't have any aggregation.

image

After that, there is the proper call to `/dataset`:

image

Maybe the presence of the second to last query messed up something?

**Comment by nemanjaglumac** [comment]
@ariya it's not just Cypress. I was getting the same results locally as well. Even restarted the instance to make sure your fix gets picked properly, but let me do it again to make absolutely sure I'm not seeing/doing something wrong here.

**Comment by nemanjaglumac** [comment]
Aaaaaaaaargh, found it!
It really depends on whether you run the SQL query before saving it or not 😵‍💫

image

image

**Comment by ariya** [comment]
> It really depends on whether you run the SQL query before saving it or not 😵‍💫

Looks like it's the same issue as https://github.com/metabase/metabase/issues/16671#issuecomment-864015639

**Comment by nemanjaglumac** [comment]
> > It really depends on whether you run the SQL query before saving it or not 😵‍💫
> 
> Looks like it's the same issue as [#16671 (comment)](https://github.com/metabase/metabase/issues/16671#issuecomment-864015639)

@ariya good call. I'll have to find a way to execute the query and possibly even to expand the tests with this (@flamber , does that seem like a reasonable thing to do?), but there doesn't seem to be a reason to block your fix any longer.

I'd say go ahead and merge it.

**Comment by nemanjaglumac** [comment]
@ariya I've updated the test, and now the SQL query waits for the `result_metadata` to be loaded first. That results in much closer to the real world scenario and now the resulting visualization (binning) is also correct. 🎉

Good news:
It seems you're just one step away from fixing the binning options being rendered two times. Compared to the previous fix attempt where @flamber noticed it's important which set of options (upper/lower) you chose from matters, now it works for both. It is still incorrect in that it renders the options two times, but:
1. the result is correct
2. selected binning option (bucket) is highlighted, albeit two times

**Comment by nemanjaglumac** [comment]
After a bit more digging, this is where we're at:
image

I could've even ignored the double binning options for time series (because [they now work](https://github.com/metabase/metabase/pull/16707#issuecomment-866739442)), but given the amount of problems around it, decided to leave them skipped. Do you agree with this @flamber ?

**Review by nemanjaglumac — APPROVED** [review]

**Comment by flamber** [comment]
@nemanjaglumac I don't understand. We do not want skipped tests if something is fixed. But there's too many PRs going on right now, so I don't know what is fixed in which PR. But if something isn't fixed in a specific PR, then of course, the test should be kept skipped.

**Comment by nemanjaglumac** [comment]
@flamber Ariya's fix works for time series, although it still displays the double binning options. My hunch was to leave it skipped until that double binning gets fixed.

**Pull request merged**
