### PR TITLE
Athena driver

### PR DESCRIPTION
**Pull request by thslopes**
###### Before submitting the PR, please make sure you do the following 
-  [ :heavy_check_mark:  ] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [ :heavy_check_mark: ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [ :innocent:  ] Sign the [Contri/butor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by thslopes** [comment]
#3960

**Comment by salsakran** [comment]
@camsaul this got clobbered after the QP refactor. Any advice on how to get the merge conflicts resolved?

**Comment by ricardoekm** [comment]
Hi @camsaul !
Can you lend us a hand in this PR? We've successfully merged with 0.31 however we've noticed significant changes in the 0.32 and thus many conflicts arised.

**Comment by romanych** [comment]
Do you plan to merge this PR in foreseeable future?

**Comment by ilyakamens** [comment]
god this would be glorious if it was merged and released

**Comment by camsaul** [comment]
Sorry I don't think I saw the original comments. Driver methods have been moved around and renamed a bit but are mostly the same. Take a look at some of the other drivers to get a sense of updated names. Shouldn't be too hard to update everything. 

Going forward we're moving towards a community-supported 3rd-party driver module so things like this aren't held up by us merging drivers. You can look at a sample 3rd-party driver here https://github.com/metabase/sudoku-driver, or one that's actually in use here: https://github.com/metabase/crate-driver

You won't have to worry about making tests work if you publish the driver as a separate repo.

**Comment by camsaul** [comment]
At any rate any drivers whose DBs we can't run and test against locally with Docker aren't ones we're likely to merge into the core project as they're a nightmare for us to test and maintain. So for your case I recommend publishing the driver as a Metabase plugin. Our upcoming 0.32.0 release features full plugin support.

**Comment by ilyakamens** [comment]
@thslopes @ricardoekm what are your thoughts on the above? i'd love to help in some way but don't know closure and am completely unfamiliar with the internals of metabase.

**Comment by ricardoekm** [comment]
Maybe we did it wrong, but I'm afraid we've changed internals of Metabase (query processor) to support features such as nested fields. From the merge conflicts, it seems some of those classes have changed.

I wonder if we'll be able to move such changes to plugin.

**Comment by camsaul** [comment]
@ricardoekm you shouldn't need to change any Metabase internals to support nested Fields. Our MongoDB driver supports nested Fields using just the normal driver methods

**Comment by ricardoekm** [comment]
Yep, MongoDB support was a start. But it didn't work in scenarios such as inner joins (using a nested field to perform inner join), where there's no equivalent in MongoDB.

For this we had to modify generic sql, query processor. e.g.:
https://github.com/metabase/metabase/pull/8577/commits/33fee4a2539aef90973ca7239f32f838cfe23bad

**Comment by ilyakamens** [comment]
so where does this leave us @camsaul? my team is begging me for this and i am woefully unqualified to implement it.

**Comment by tlrobinson** [comment]
Hey all,

Thank you for this PR and apologies for the long delay responding. We've recently done some work to support drivers as plugins in Metabase and as of the next release (v0.32) we will be asking driver developers to first publish new drivers in their own repositories (typically named `metabase-*-driver`). If the driver fully passes the driver tests we will link to it from our documentation, and if a driver gains significant usage we will consider merging it into Metabase itself.

Here is some documentation about publishing a driver as a plugin in a separate repository: https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#drivers-shipped-as-3rd-party-plugins

Here are two example drivers: https://github.com/metabase/sudoku-driver https://github.com/metabase/crate-driver

We still have some work to do on the documentation. You can follow progress and provide feedback on that here: https://github.com/metabase/metabase/issues/9348

Thank you.

**Comment by tlrobinson** [comment]
By the way, I noticed there were 3 Athena drivers: #5439 #8577 #8637 You all may want to consider consolidating efforts.

**Comment by camsaul** [comment]
Hey, as you might have noticed we refactored our query processor 3 or 4 months ago to improve performance and make it easier to implement custom behavior for individual drivers. I’d be interested in seeing if the changes eliminate or reduce the amount of things you needed to change to get this driver working. Please ping me if you migrate it over to support the refactored code shipped with Metabase 31+ and we can proceed from there

**Comment by dacort** [comment]
(AWS employee here) I made an initial version of the Athena driver using the new plugin system. It went well and I'm able to execute raw SQL queries but more work is necessary to make the driver fully compatible. I'll likely continue work on it in the coming weeks and will create a new repo for it soon.

**Comment by dacort** [comment]
@ricardoekm Will do - there were a couple tricky things to get it to work so will try to post the current version as soon as I can. Specifically “EXTERNAL_TABLE” had to get added to some of the existing driver code that reads the tables from the JDBC driver.

**Comment by Webysther** [comment]
Hey @dacort are you working on some branch of this feature?

**Comment by dacort** [comment]
@Webysther I am, was trying to figure out how to get it to a non-hacky state, but I can share where it is now. I'm not too familiar with lein so it involves downloading the Athena driver manually.

**Comment by Webysther** [comment]
@dacort share please, will be awsome.

**Comment by dacort** [comment]
Take a look at https://github.com/dacort/metabase-athena-driver - it is still _very_ early and only supports raw SQL queries at the moment.

**Comment by ricardoekm** [comment]
@dacort we've made a pull request: https://github.com/dacort/metabase-athena-driver/pull/10

With this PR it seems the driver is finished. There're a few refactorings to do, we're gonna do it after merge.

**Pull request closed without merging**
