### PR TITLE
Add Telegram Messenger integration for Pulse

### PR DESCRIPTION
**Pull request by derekstavis**
This is a work in progress patch. (That's why it's in a single commit)

### Motivation

I maintain an open source game called [TeleMMO](https://github.com/telemmo/telemmo), which is a Telegram-based RPG game. I have been using Metabase to create the game stats dashboard, it's been an awesome experience, since it's a beautiful tool and gives me the power to write manual Mongo aggregations.

As game's user base is entirely Telegram-based, it was desired that Metabase was able to send Pulses to Telegram as well, so we could create a channel, add the Telegram bot there and have it updates the channel with leaderboard from time to time.

### Summary

This PR is the first step on full Telegram integration as seen on Slack. As I had a specific need and wanted to prove if I could handle implementing it, this PR features only Pulse integration for Telegram, letting Metabot for a second iteration.

The intention with this initial PR is to warm the discussion on this integration, grab feedback and improve it together until it's merge-able.

### Results

screen shot 2017-02-28 at 20 06 09

screen shot 2017-02-28 at 20 06 56

screen shot 2017-02-28 at 20 07 13

### Disclaimer

I never had prior experience with Clojure. I just started tinkering with Metabase code, and really, it was an awesome experience, because code is very well organized and well named. With this in mind, I'd like to ask for reviews and possible improvements in backend code. Although I'm a React developer, feel free to review frontend too :)

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by camsaul** [comment]
What's Telegram?

**Comment by salsakran** [comment]
Thanks for the help @derekstavis !

Before going too much further, can you please sign our CLA? We can't accept a PR without that.

As we start adding places for pulses to go, I think we should treat this as an excuse to try to modularize pulse targets. I'd rather not add a general settings tab *and* another row in the pulse create/edit view for each potential target.

@kdoh @mazameli can you chime in? I'd like a UX review before merging this as well.

**Comment by derekstavis** [comment]
Signed the CLA. Thanks.

**Comment by derekstavis** [comment]
Hey, sorry for bumping... Any update on this?

**Comment by kdoh** [comment]
@derekstavis Don't be sorry at all. Sorry we let it go a bit without taking a closer look, lots of stuff in the works here at Metabase HQ.

I think like @salsakran said the main concern here is that while this is probably fine in terms of just adding Telegram support, the inevitable question is "what happens when we get another PR for something like Hipchat". I'm really torn on accepting this as is since we haven't gotten that many actual submissions of new pulse destinations in the year + of the feature so it's not really a "problem" yet, but I know deep down it's going to be an issue.

It also runs contrary to the design ethos of Metabase to just append things to the bottom of lists without a bit more thought.

I'd be curious to get your thoughts on how it was to develop the support for Telegram, specifically what was hard, what was easy, and how much UI wrangling it took etc, and see if maybe we could come up with something light weight enough that would future proof things without requiring too much reworking on your part or a big undertaking on the core team's part.

@salsakran / @mazameli Curious to get your feelings as well. In the meantime I'll take a look at the actual implementation here and see how it feels and if I can contribute more to the conversation based on that.

**Comment by derekstavis** [comment]
>Don't be sorry at all. Sorry we let it go a bit without taking a closer look, lots of stuff in the works here at Metabase HQ.

I understand. No problem :)

>It also runs contrary to the design ethos of Metabase to just append things to the bottom of lists without a bit more thought.

Perfect. I completely agree.

>I'd be curious to get your thoughts on how it was to develop the support for Telegram, specifically what was hard, what was easy, and how much UI wrangling it took etc

I went full pathfinder with the will to implement Telegram support. Metabase code is very well architected. It feels consistent, so I believe that's the main reason I found pretty easy, even with myself knowing 0% about Clojure. Also, developer documentation worked like a charm, so I had no curve to to start developing <3

One thing that I really felt while working on this PR is that I was cheating, because there were lots of copy-pasta code that could have turned into shared code but I haven't done to keep the flow state.

>and see if maybe we could come up with something light weight enough that would future proof things (...)

In React, I can clearly see and do the refactors needed to get code sane, but in server I believe I'm not the best person to do it, but well, why not try? 😛 

I appreciate Metabase a lot and I will certainly continue tweaking this PR. Don't feel like I'm rushing or anything, but also feel free to give any directions!

I have recently worked on properly deploying Metabase for [TeleMMO dashboard](https://metabase.telemmo.stavis.me/public/dashboard/2fc95b6d-f2c0-4b9d-b873-650275586cda).

And also set up Telegram integration for the leaderboard:

screen shot 2017-03-16 at 01 23 32

I really wish to continue working in this PR to give a better user experience for Telegram (and probably implement Metabot too), but this will come in some months, because now we need to finish more game features. This is actually good because it will probably demand more from both Telegram integration and Metabase itself.

Thanks for the thoughts!

**Comment by kdoh** [comment]
Going to close this as we don't have any plans to merge this and I feel bad letting it continue to linger open as it has.

**Comment by ohld** [comment]
Hi! Any thoughts about Telegram integration for Pulse? It would be really awesome to have it.

**Pull request closed without merging**
