### PR TITLE
Fix :max aggregations for Druid :lightning:

### LINKED ISSUE #2602: Metabase not recognizing timestamp field
Metabase isn't recognizing a field as a timestamp field making it difficult to group data over time.

The data is currently being pulled in via RJMetrics from a Segment.io warehouse and loaded into our Redshift cluster.

Screenshot of query builder: https://www.evernote.com/l/AOzaW-zl8DFL6YxSRVHvNtqhL87CqKuiX6A
Screenshot of schema: https://www.evernote.com/l/AOwJaZ2IaQhCUoTQfqlgMeeF4kQRBxb0UR8

As an additional test, I have Segment.io loading the same data warehouse (without RJMetrics) to another database inside of the same Redshift cluster and Metabase recognizes it as a DateTime field.

Screenshot of query builder: https://www.evernote.com/l/AOx17gf7jNJLB43vsUA5KtcCScj5T55ttFI
Screenshot of schema: https://www.evernote.com/l/AOyobhZmOR9IJ4gCAPbBDojfCH3FXxaSTUs

Is there a way to change the schema manually?

*  I am using the Chrome browser.
*  My computer's OS is OSX 10.11.4.
*  I'm running Metabase on AWS.
*  My database is Redshift.
*  My Metabase version is v0.17.0 built on 2016-05-02.

Possibly related to #1576

### LINKED ISSUE #2606: Return minimum value when query maximum value in druid
*  My database is druid.
*  My Metabase version is 1.17.1.

It always return minimum value when query maximum value in druid. I think it's a bug can be fixed as follows:

```
--- a/src/metabase/driver/druid/query_processor.clj
+++ b/src/metabase/driver/druid/query_processor.clj
@@ -111,11 +111,11 @@

 (defn- ag:doubleMax [field]
   (case (dimension-or-metric? field)
-    :metric    {:type      :doubleMin
-                :name      :min
+    :metric    {:type      :doubleMax
+                :name      :max
                 :fieldName (->rvalue field)}
     :dimension {:type        :javascript
-                :name        :min
+                :name        :max
                 :fieldNames  [(->rvalue field)]
                 :fnReset     "function() { return Number.MIN_VALUE ; }"
                 :fnAggregate "function(current, x) { return Math.max(current, (parseFloat(x) || Number.MIN_VALUE)); }"
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #2606.

### CODE REVIEW

**Comment by salsakran** [comment]
*cough* test? *cough*

**Comment by camsaul** [comment]
We're already testing Druid `min`/`max` aggregations when the columns are dimensions. But not metrics. Oops 😓

**Comment by salsakran** [comment]
let's add tests for metrics before we merge this

**Comment by camsaul** [comment]
added tests

**Pull request merged**
