### PR TITLE
Allow only one action menu popover to be open at once

### LINKED ISSUE #44910: Multiple menus can be opened simultaneously in Trash
### Describe the bug

image

### To Reproduce

1. Delete a few entities
2. Go to trash
3. Click on "..." button for every item, starting from the last one

### Information about your Metabase installation

master, da0c9cb645

### Severity

P3

### LINKED ISSUE #45141: Make collection table navigable by pressing Tab
Currently, if you try to tab through a collection table, the focus cursor will stop at the first action menu you reach.

### PR DESCRIPTION
**Pull request by rafpaf**
On master, when you open an action menu in a collection, other open action menus remain open:

On this branch, when you open an action menu, it closes any other open action menus:

Closes #44910
Closes #45141

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#45619** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45619?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by npfitz — CHANGES_REQUESTED** [review]
Looks like a nice little fix for #44910 . Can we unskip the e2e repro in `trash.cy.spec.js`? And expand on it if necessary?

**Comment by rafpaf** [comment]
@npfitz I've unskipped that test, which now passes 🎉

**Review by npfitz — APPROVED** [review]
Looks good! Thanks for updating this 👍

**Comment by rafpaf** [comment]
### Merge activity

* **Jul 17, 9:42 AM EDT**: @rafpaf merged this pull request with [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/45619).

**Pull request merged**
