### PR TITLE
Make sure icon.attrs is defined before trying to get icon.attrs.className

### LINKED ISSUE #4919: Pulses list is broken
Pulse list is broken on master, chrome on mac os x

screen shot 2017-05-01 at 12 39 09 pm

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #4919. Apparently the Slack icon doesn't have an `attrs` property, it's just

```javascript
{img: "/app/img/slack.png"}
```

no idea what's going on here but this does fix it

### CODE REVIEW

**Comment by camsaul** [comment]
@attekei it looks like you were the last one to touch this file so if you could take a look and let me know if this fix makes sense that would be 👍

**Review by attekei — CHANGES_REQUESTED** [review]
Uh, the Slack icon seems to be the only icon in the whole app that isn't in svg format... and seems `loadIcon` in `icon_paths.js` returns the value early in that case without adding a class name.

I think that checking the existence of icon.attrs is a good safeguard but would be nice to apply the `Icon Icon-iconname` classes in `loadIcon` also to the slack icon for consistency

**Comment by camsaul** [comment]
@attekei is this the right syntax

```javascript
if (def.img) {
    return { className: 'Icon Icon-' + name, ...def };
}
```

**Comment by camsaul** [comment]
Ok @attekei made the suggested changes so take another look.

**Review by attekei — APPROVED** [review]

**Pull request merged**
