### PR TITLE
Add Cypress custom command `button`

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING CI && PENDING REVIEW

### What does this PR accomplish?
- Abstracts away Cypress Testing Library syntax `cy.findByRole("button", { "Foo" });` and uses shorter and easier to type (and remember) `cy.button("Foo");`
- Replaces all valid instances of such command in all tests
- Forces using `cy.button("Visualize");` instead of `cy.findByText("Visualize");` in all tests

### How to verify this still works?
- All tests should pass
- If you want to try it locally, this command should work both with the string and also with regex as an argument
    - `cy.button("Save");` should works just as same as `cy.button(/save/i);`

### Why do this?
It's cumbersome to type the long form of the original custom command, so many people avoid it and use `cy.findByText()`. Cypress testing library has really nice intent behind it that helps enforce (and test) good a11y practices in an application. This change will hopefully simplify and encourage the use of the proper command.

## WARNING!
This selector will not work on buttons with the nested structure! Good example is "Summarize" that you can see in "Simple question" GUI.
```html
<button
  ml="1"
  data-metabase-event="View Mode; Open Summary Widget"
  class="Button hide sm-show ViewButton-sc-1bti87e-0 bOvfhB Button-ygn2tx-0 cANzZu flex-no-shrink Button--medium"
>
  <div class="flex layout-centered">
    <svg
      class="Icon Icon-insight Icon-sc-1x67v3y-1 hFNRPZ"
      viewBox="0 0 32 32"
      width="14"
      height="14"
      fill="currentcolor"
      role="img"
      aria-label="insight icon"
    >
      <path
        d="M12.6325203 19.3674797 0 16 12.6325203 12.6325203 16 0 19.3674797 12.6325203 32 16 19.3674797 19.3674797 16 32z"
      ></path>
    </svg>
    <div class="ml1 hide sm-show">Summarize</div>
  </div>
</button>
```

For this I'd use:
```javascript
// Please note that we have to use findAll selector here!
// Cypress first finds ALL buttons, then picks the one that contains "Summarize"
cy.findAllByRole("button").contains("Summmarize");
```

### CODE REVIEW

**Review by gusaiani — APPROVED** [review]
> Forces using cy.button("Visualize"); instead of cy.findByText("Visualize"); in all tests

I didn't quite find where in the diff the above is implemented.

To my eyes this is a nice helper function, makes things cleaner and more declarative like the icon command. 👍

**Comment by nemanjaglumac** [comment]
Thanks for the review, Gus.

The diff is basically this whole commit:
https://github.com/metabase/metabase/commit/b1e11dcb39f8f979cc912fc030286a56afb694e2

**Comment by gusaiani** [comment]
@nemanjaglumac I think I understood now. 

Somehow I got the expectation that a linting rule would be introduced to actually beep if we queried for a button using findBy* when we could use the command.  

Onwards as far as I'm concerned 🙂

**Review by alxnddr — APPROVED** [review]
That's handy, thanks!

**Comment by nemanjaglumac** [comment]
> Somehow I got the expectation that a linting rule would be introduced to actually beep if we queried for a button using findBy* when we could use the command.

Oh, my bad! Sorry.
I should've chosen some other word instead of "enforce". Usually people look at the existing tests and copy some parts of the code, at least in the beginning. So, if there are no instances of findByText "Visualize", it's far more likely everyone will just use cy.button. :)

**Pull request merged**
