### PR TITLE
Let JSON array be filtered with `contains` and all the other string filters

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to #21933. Change in the FE typesystem (only) was by far the least disruptive.

Currently `Type/Array` in backend translates to `UNKNOWN` type in FE, although of course it isn't unknown to us. Just coerces the filter types to be ARRAY and for ARRAY to be stringly typed.

### CODE REVIEW

**Comment by iethree** [comment]
Is the backend for this implemented?

I have a json field with an array and it doesn't come in as `type/Array` from the backend

```json
{
  "description": null,
  "database_type": "json",
  "semantic_type": "type/SerializedJSON",
  "table_id": 5,
  "coercion_strategy": null,
  "name": "auctions",
  "fingerprint_version": 0,
  "has_field_values": "search",
  "settings": null,
  "caveats": null,
  "fk_target_field_id": null,
  "dimensions": [],
  "dimension_options": [],
  "updated_at": "2022-03-21T13:36:05.87",
  "custom_position": 0,
  "effective_type": "type/Structured",
  "active": true,
  "nfc_path": null,
  "parent_id": null,
  "id": 38,
  "last_analyzed": null,
  "position": 4,
  "visibility_type": "normal",
  "default_dimension_option": null,
  "target": null,
  "preview_display": true,
  "display_name": "Auctions",
  "database_position": 4,
  "fingerprint": null,
  "created_at": "2022-03-21T13:36:05.87",
  "base_type": "type/Structured",
  "points_of_interest": null
}
```

similarly, with a postgres array field, it's not recognized as an array

```json
{
    "description": null,
    "database_type": "_int4",
    "semantic_type": "type/Category",
    "table_id": 12,
    "coercion_strategy": null,
    "name": "id_list",
    "fingerprint_version": 5,
    "has_field_values": "list",
    "settings": null,
    "caveats": null,
    "fk_target_field_id": null,
    "dimensions": [],
    "dimension_options": [],
    "updated_at": "2022-07-07T08:07:49.415",
    "custom_position": 0,
    "effective_type": "type/*",
    "active": true,
    "nfc_path": null,
    "parent_id": null,
    "id": 284,
    "last_analyzed": "2022-07-07T08:07:49.418",
    "position": 5,
    "visibility_type": "normal",
    "default_dimension_option": null,
    "target": null,
    "preview_display": true,
    "display_name": "ID List",
    "database_position": 5,
    "fingerprint": {
        "global": {
            "distinct-count": 3,
            "nil%": 0.6666666666666667
        }
    },
    "created_at": "2022-07-07T08:07:49.37",
    "base_type": "type/*",
    "points_of_interest": null
}
```

applying a contains filter doesn't parse as a string, and still errors

Screen Shot 2022-07-07 at 8 09 17 AM

for arrays:
```
 "ERROR: function lower(character varying[]) does not exist\n  Hint: No function matches the given name and argument types. You might need to add explicit type casts.\n  Position: 378",
```

for json: 
```
 "ERROR: operator does not exist: json ~~ character varying\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 462",
```

**Comment by howonlee** [comment]
Overall vision (in [private notion link](https://www.notion.so/metabase/Add-support-to-arrays-of-records-in-JSON-fields-eebf02da462146a79c7344de4c103601#94cf54f089de4b4cb2640192ee6cd655) here) entails new `metabase_table` creations, and isn't "just stringly typed" - I was imagining this as first step in a gigantic cavalcade of stuff. Notably, this type trick only works on top-level array because, indeed, none of the backend is done for that array stuff.

21933 is not quite an epic but not just one piecemeal task, I guess. maybe solution is to just grossly expand this PR to the 100-200 sloc that the whole impl would entail

**Comment by iethree** [comment]
> 21933 is not quite an epic (or at least not a large epic) but not just one piecemeal task, is the takeaway, I suppose. maybe solution is to just grossly expand this PR to the 100-200 sloc that the whole impl would entail

I'm not sure what the best overall solution is for implementing real array support, but from a UX + frontend standpoint, I think I'd rather disable filters on array or json fields from the UI to avoid tricking people into thinking they can filter when they cannot.

**Comment by iethree** [comment]
Updated the UI to not trick users into thinking they can filter on json arrays: https://github.com/metabase/metabase/pull/22063

**Comment by howonlee** [comment]
this isn't the fix

**Pull request closed without merging**
