### PR TITLE
docs: add greptimedb community driver plugin

### PR DESCRIPTION
**Pull request by sunng87**
### Description

Add [GreptimeDB](https://github.com/GreptimeTeam/greptimedb-metabase-driver) to community driver.

### CODE REVIEW

**Comment by sunng87** [comment]
@camsaul I assume I don't need to sign the CLA for this small change. Let me know if there is anything to add to get this merged. Thank you!

**Comment by sunng87** [comment]
Looks like the ci failures are not related to this change.

**Comment by perivamsi** [comment]
This is merged through https://github.com/metabase/metabase/pull/48214

**Comment by sunng87** [comment]
@perivamsi Thank you!

**Pull request closed without merging**
