### PR TITLE
Fix LDAP branch reflection warnings and a few other style issues

### PR DESCRIPTION
**Pull request by camsaul**
Fixes the reflection warnings introduced by #4340

### CODE REVIEW

**Comment by camsaul** [comment]
It turns out the LDAP branch (#4340) introduced both reflection warnings and flow errors so going to go ahead and merge this fix for the former and then we'll do a follow-on for the flow errors 😱

**Comment by wwwiiilll** [comment]
Yeah saw that, should I work on fixing the flow errors? I completely forgot to run frontend lints (we also forgot to run the PR on CI as well).

**Comment by salsakran** [comment]
@wwwiiilll yes please!

**Comment by wwwiiilll** [comment]
Here it is #5375

**Pull request merged**
