### PR TITLE
Nested queries

### PR DESCRIPTION
**Pull request by camsaul**
Implements #1822, some subset of functionality for #2214

### TODO - @camsaul

- [x] Allow nested-nested queries? If so, consider adding even more extra tests. If not, remove from Saved Questions virtual DB
- [x] Get Saved Questions virtual database working in the Data Reference
- [x] Add some new tests for queries coming back with / Cards validating (or fetching) metadata 🙀 
- [x] Make sure running nested query from API doesn't overwrite Card metadata cols if different
- [x] Fix warning: Table 'null' has no Fields associated with it. (in `add-implicit-clauses`)
- [x] Duplicate columns issues 😒 
- [x] Drill-through not working
- [x] filter and grouping fields are showing up all-caps and with underscores instead of the “friendly” styling
- [x] some of the column header drill-through options aren’t setting correct columns for viz. eg, a “count by time” on an integer results in `Which fields do you want to use for the X and Y axes?`
   > This is due to the columns being in a different order than normal
- [x] Nested queries with SQL params not working
- [x] Don't allow datetime breakout by year source column
- [x] Don't allow cumulative-count/cumlative-sum source queries
- [x] using a `past 30 days` filter is giving me this: `(not (instance? metabase.query_processor.interface.ValuePlaceholder a-metabase.query_processor.interface.Value))`
    the source table is a sql query
-  [x] zoom not working: 

      1. Start a new question based on a saved question that has at least one numeric field and one datetime field.
   2. Select an aggregation and break it out by the datetime field (breakout granularity doesn't matter), and select line, area, or bar for your visualization. 
   3. Click on a bar or point and select `zoom in`
   4. Notice that a filter is correctly applied to filter on the selected bar/dot, but instead of the time granularity being increased from e.g. quarter to month, the QB is incorrectly getting a second, additional breakout with the correct granularity.

### TODO - Frontend Help (@tlrobinson and/or @attekei)

- [x] breakouts missing when you click the compass button thing
- [x] a few options missing, eg, “distribution” is missing from a integer column
- [ ] Add "Is your question missing" link to Saved Questions selector "accordian" [sic] list

### Maybe TODO (?) - @mazameli  Cosmetic Polish Suggestions

- [ ] Maybe we want to give "Saved Questions" a distinct icon in the QP DBs dropdown
- [ ] Might be nice to use the Collections' colors and icon in this list like we do elsewhere instead of the folder/schema icon
- [ ] Not a lot of room in this popover for "Saved Questions" and the name of the collection

### CODE REVIEW

**Comment by salsakran** [comment]
Some (open) questions:
1) Would we want to limit `source-query`'s to just saved questions? (Bias: why not leave it open)
2) Wouldn't we want to allow `source-query` to point to a saved question? More specifically, if I were to save a query A that uses query B under the hood, and query B changes, I'd expect query A to use the new Query B as a starting point. The approach in this PR seems to have to "unwrap" query B
3) Do we want to enforce a max-depth of 2 (as is implicit? in this PR), or should we have the QL accept a deeper nesting, and separately enforce a sanity limit in the front end?

**Comment by camsaul** [comment]
currently the QP can handle any depth, so if we do enforce a max depth we could do it on the frontend and leave the backend capable of doing arbitrary depth

**Comment by camsaul** [comment]
I can tweak `source-query` to accept a card ID as a 3rd option that should be doable

**Comment by salsakran** [comment]
Another question -
would it be possible to use CTE's instead of subselects?
If we then allowed 1 or more CTE's we would have a pretty clear path to joins, etc in a pretty chill way. The overall generated sql would also be more understandable.

**Comment by salsakran** [comment]
not suggesting we do joins in this PR, but would rather not to rework this if/when we get around to query composition.

**Comment by salsakran** [comment]
ie. where this could get bonkers is if you could eventually do something like
`{"IN", fieldID, {subquery-results}}`

**Comment by camsaul** [comment]
@salsakran we could definitely use CTEs instead of subselects, it doesn't really make much of a difference from an implementation standpoint. I'll play around with it

**Comment by mazameli** [comment]
I know this is still a WIP, so some of these items might be known issues, but I just wanted to make note of a few things I noticed as I played with this today so they don't get lost:

- Saved question columns don’t seem to have a field type, so I can't seem to use aggregations on any fields
- There's going to be some permissions weirdness: if saved question A's source table is another saved question, B, if a user has permission to A's collection but not B's collection, they can still view question A. This makes some amount of sense, but what if question A is just a raw data query of question B?
- If a saved nested query can't be used _itself_ as a source table, how will we communicate that visually and otherwise to end users? How many levels of Inception would we theoretically allow before we'd be letting a user shoot themselves in the foot?
- though "Saved Questions" does appear in the Data Reference as a DB, I'm not seeing any saved questions appear within its list of "tables"

Some cosmetic things:
- Saved question table column headings are all caps, and not friendlified.
- Maybe we want to give "Saved Questions" a distinct icon here:

screen shot 2017-06-05 at 2 37 20 pm

- Might be nice to use the Collections' colors and icon in this list like we do elsewhere instead of the folder/schema icon:

screen shot 2017-06-05 at 2 37 35 pm

- Not a lot of room in this popover for "Saved Questions" and the name of then collection:

screen shot 2017-06-05 at 2 37 45 pm

**Comment by camsaul** [comment]
> There's going to be some permissions weirdness: if saved question A's source table is another saved question, B, if a user has permission to A's collection but not B's collection, they can still view question A. This makes some amount of sense, but what if question A is just a raw data query of question B?

@mazameli the idea of Collections in the first place was that you could add cards to them so people would be allowed to see Cards they otherwise wouldn't be able to see (for example, you could let someone see a specific SQL Card but not give them general SQL permissions.)

So in your example I think someone adding the card to Collection A (to allow people to view it) isn't much different than doing the same thing with a SQL Card.

**Comment by camsaul** [comment]
> though "Saved Questions" does appear in the Data Reference as a DB, I'm not seeing any saved questions appear within its list of "tables"

that's a bug, i need to tweak the frontend to not ask for the saved questions DB in the data reference. I don't think it should be popping up there

**Comment by camsaul** [comment]
@mazameli RE 

> Saved question columns don’t seem to have a field type, so I can't seem to use aggregations on any fields

This is working fine for me

screen shot 2017-06-05 at 3 59 04 pm

what database are you using?

**Comment by mazameli** [comment]
> what database are you using?

Sample Dataset. The saved question I'm trying to use as a source table is just a raw data one on the People table with a `between` time filter on the Birthday field.

I tried to save a new question to debug what's up with mine, but I'm getting this now when trying to save a question (count of rows with one or two breakouts):

screen shot 2017-06-05 at 4 04 23 pm

**Comment by mazameli** [comment]
I'm getting this error if I try to add a breakout to an aggregation with a nested query:

`(not (instance? metabase.query_processor.interface.FieldPlaceholder a-metabase.query_processor.interface.FieldLiteral))`

screen shot 2017-06-06 at 11 10 28 am

**Comment by camsaul** [comment]
@maz have you restarted the server since pulling the latest? Also did you make sure to do a `git pull --force` since I've force-pushed

**Comment by mazameli** [comment]
`git pull --force` seems to have fixed it! Thanks.

**Comment by sabino** [comment]
Hey @camsaul 

I was testing here and if I save a question like this:
```sql
SELECT *
FROM ORDERS O
LEFT JOIN PEOPLE P ON O.USER_ID = P.ID
LIMIT 10
```
Then try to create another question from it, metabase will internally run:
```sql
SELECT * FROM (SELECT *
FROM ORDERS O
LEFT JOIN PEOPLE P ON O.USER_ID = P.ID
LIMIT 10)
```
But this will raise an error:
metabase_error

Any way to prevent this without specifying the fields?

**Comment by camsaul** [comment]
@sabino this PR is still a work in progress. We haven't sorted out all the issues 😉

**Pull request merged**
