### PR TITLE
Wrap `tru` and `trs` macro results in `str`

### PR DESCRIPTION
**Pull request by walterl**
Automatically call `str` on translated strings. But not during compilation, because translations are not yet loaded at that point. In that case `deferred-tru` can be used, which is the old `tru`, renamed. That is it returns a `UserLocalizedString`.

All use cases of `(str (tru ...))` has been replaced with `(tru ...)`. `deferred-tru` is used in all cases where `str` is applied anyway (usually when joined with other strings), so as to avoid unnecessary extra calls to `str`.

All of the above goes for `trs` and `deferred-trs` too.

### CODE REVIEW

**Comment by walterl** [comment]
_Finally_! :stuck_out_tongue_closed_eyes:

The fact that `lein uberjar` picked up the compile time `trs`/`tru` usages makes me a lot more comfortable that this won't cause further regressions.

**Comment by walterl** [comment]
Fixes #10473

**Comment by flamber** [comment]
@walterl I guess it fixes #10347 too, but it's been really difficult to debug. Most cases in the forum seemed to be fixed, when people double-checked the credentials.

**Comment by walterl** [comment]
@flamber It's quite possible, yes. This change started out as just trying to fix the error messages, so that #10347 would be easier to investigate and fix.

**Review by camsaul — APPROVED** [review]
Awesome 👍

**Comment by walterl** [comment]
Ironically, that last commit (f5e5a6f) was my original fix for this issue, before we went for updating the `tr*` macros :stuck_out_tongue:. It illustrates that the general i18n fix may still leave instances where we'll need to wrap translated string values in `str`. That said, it is still an improvement.

**Pull request merged**
