### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by mazameli**
### Description

Updates icons in the entire product.

Screen Shot 2023-05-31 at 6 52 15 PM

Screen Shot 2023-05-31 at 6 52 45 PM

Screen Shot 2023-05-31 at 6 56 19 PM

### Tech details

While updating icons timeline events got broken because they relied on icons in `icon_paths` that are defined as the string value of `d` attribute of `path` or as an object that has the `d` value. Also, there was one `png` icon. This PR also introduces `svgr` loader for Webpack which allows importing svg icons as components and lets us store icons as previewable files.

#### Most important

- New Icon component `frontend/src/metabase/core/components/Icon`
- Webpack config changes https://github.com/metabase/metabase/pull/31096/files#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166f
- Rendering icons in timeline events https://github.com/metabase/metabase/pull/31096/files#diff-78ba030f0a294a79e9d84130cd5c109d939c235e56db7cef48d4d4b3d39e2db1

The rest is mechanical import updates, specs updates, adding aria-labels for some specs, fixing specs, and updating jest and storybook configs.

### How to verify

**App**
- Ensure icons are shown correctly everywhere in the app  

**Storybook**
- Run `yarn storybook`
- Go to the [Icons](http://localhost:6006/?path=/story/components-icon--default)
- Ensure they look good

### Checklist

- [n/a] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by mazameli** [comment]
@alxnddr, I'm wondering if you or someone else with viz or Event timeline knowledge could please help me out with this question: https://www.loom.com/share/aa29ffd51ef54c9c967da0aaef4b8b99

**Comment by alxnddr** [comment]
@mazameli can you please fix `arrow_split` icon file? 

Screen Shot 2023-05-30 at 10 50 59 PM

**Comment by mazameli** [comment]
@alxnddr, good catch. I think it's used for the breakout action in the drill-through menu, yeah?

**Comment by mazameli** [comment]
>In the meantime, I'll fix the CI and resolve conflicts

@alxnddr Thanks a ton! I've fixed the arrow_split icon, and also fixed up the sizing of the icons in the drill-through menu.

**Review by ranquild — APPROVED** [review]

**Review by kdoh — APPROVED** [review]
👍

**Comment by mazameli** [comment]
@alxnddr thanks for the test fixes!

**Pull request merged**
