### PR TITLE
Put New Tests in Flake Jail + Parole Well Behaved Tests

### PR DESCRIPTION
**Pull request by iethree**
### Description

After a meeting of the flaky test parole board, we decided to let several tests out of the flaky test job for good behavior. This made room for a new batch of newly-flaky tests to pay their debts to society in the flaky test job. We'll review their records in the near future to see if they deserve to re-join the general testing public.

see: [replay io dashboard](https://app.replay.io/team/dzoyNTM4ZjRmOC05YmFlLTRiYjYtYjljYi1jOGYzOWUyMjRhZWY=/tests) and [stats](https://stats.metabase.com/question/18032-10-flakiest-tests) for the most wanted list

### CODE REVIEW

**Comment by uladzimirdev** [comment]
@iethree great initiative, I'd love to see a stress test run for every test we want to remove from `flaky` group with at least 30 runs

**Comment by iethree** [comment]
> @iethree great initiative, I'd love to see a stress test run for every test we want to remove from `flaky` group with at least 30 runs

Good idea!
- https://github.com/metabase/metabase/actions/runs/9383152897
- https://github.com/metabase/metabase/actions/runs/9383157779
- https://github.com/metabase/metabase/actions/runs/9383165588
- https://github.com/metabase/metabase/actions/runs/9383169128
- https://github.com/metabase/metabase/actions/runs/9383174681
- https://github.com/metabase/metabase/actions/runs/9383177978
- https://github.com/metabase/metabase/actions/runs/9383183137
- https://github.com/metabase/metabase/actions/runs/9383189231

**Comment by iethree** [comment]
> > @iethree great initiative, I'd love to see a stress test run for every test we want to remove from `flaky` group with at least 30 runs
> 
> Good idea!
> 
> * [metabase/metabase/actions/runs/9383152897](https://github.com/metabase/metabase/actions/runs/9383152897)
> * [metabase/metabase/actions/runs/9383157779](https://github.com/metabase/metabase/actions/runs/9383157779)
> * [metabase/metabase/actions/runs/9383165588](https://github.com/metabase/metabase/actions/runs/9383165588)
> * [metabase/metabase/actions/runs/9383169128](https://github.com/metabase/metabase/actions/runs/9383169128)
> * [metabase/metabase/actions/runs/9383174681](https://github.com/metabase/metabase/actions/runs/9383174681)
> * [metabase/metabase/actions/runs/9383177978](https://github.com/metabase/metabase/actions/runs/9383177978)
> * [metabase/metabase/actions/runs/9383183137](https://github.com/metabase/metabase/actions/runs/9383183137)
> * [metabase/metabase/actions/runs/9383189231](https://github.com/metabase/metabase/actions/runs/9383189231)

@uladzimirdev everything passed except sandboxes, which has been sent back to jail

**Review by uladzimirdev — APPROVED** [review]
:shipit:

**Pull request merged**
