### PR TITLE
Allow the Administrators group to sync

### LINKED ISSUE #13820: Cannot map users to Admin group
**Describe the bug**
In the UI for group mappings for SAML/JWT/LDAP SSO authentication:
> Membership to the Admin group can be granted through mappings, but will not be automatically removed as a failsafe measure.

But when selecting the Admin group, then it has no effect during the login process, so the user never gets Admin access, only the regular groups are correctly assigned to the user.
image

**Expected behavior**
Should have the ability to map users to the Admin group.

**Information about your Metabase Installation:**
Metabase x.37.2
Reference: https://github.com/metabase/metabase-enterprise/issues/445 EE445

### PR DESCRIPTION
**Pull request by robdaemon**
Allows the Administrators group to sync from LDAP or SAML providers.
This was previously not allowed to avoid a user accidentally locking
themselves out of the admin group.

#13820

### CODE REVIEW

**Review by rlotun — COMMENTED** [review]
Code LGTM. I'm just asking @mazameli to check in with a few enterprise customers to see that this matches what they expect.

**Review by camsaul — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
@robdaemon [the same comment](https://github.com/metabase/metabase/pull/13797#issuecomment-730649160) for Cypress test goes here as well. They were fixed in 71c38b2035e98f14b39645080ff76b7f209d4f6e and 5a4b484b2dda2b14cece5fe17f29b00d8217da81.

You can safely ignore them :)

**Comment by salsakran** [comment]
I propose we enable a toggle for this in Enterprise and leave the OSS behavior as-is so it doesn't disrupt anyone.

**Comment by robdaemon** [comment]
That was my plan. The toggle will default to OFF for existing EE customers with LDAP enabled, and default to ON for new LDAP integrations.

**Pull request closed without merging**
