### PR TITLE
Tidy up metabot logging

### PR DESCRIPTION
**Pull request by agilliland**

### CODE REVIEW

**Comment by camsaul** [comment]
Most of those things are printlns because they're in there for debugging with the intention of removing them once the metabot feature set stabilizes

**Comment by agilliland** [comment]
Got it.  I suppose that's understandable, but I still think we should use the logger instead.

We should start using the logger more effectively really.  The way I've always used it in the past is to set the default log level to INFO and expect that any messages at that level are always meant to be in the output.  Then feel free to put lots of messages at the DEBUG level throughout the code which you then turn on/off as needed when you are working on that part of the code.

e.g. if you are working on metabot then you'd have a log config like this ...
```
# customizations to logging by package
log4j.logger.metabase=INFO
log4j.logger.metabase.metabot=DEBUG
```

**Comment by camsaul** [comment]
Right. `println` is a lot more useful for me for something under development because it pops up in my REPL vs a separate buffer when I'm working on the code. Most of these `printlns` are overly noisy so I think we can just leave them in until we wrap up the metabot features and then remove them entirely.

**Comment by agilliland** [comment]
k ... sorry about that.  i can revert this if you prefer the printlns.

**Pull request merged**
