### PR TITLE
Keep filter and fields clauses in trivial nested queries

### LINKED ISSUE #21688: Pivot Table query optimization
@luizarakaki comment:

We should improve the Pivot Table query in two ways:

- [ ] Move filtering clauses to the inner query (so it actually use indexes).
- [ ] Select only relevant fields in the inner query. If the table has more fields than used for breakouts, we should get only the necessary to build the pivot.

---
_Original issue_
Hello metabase team,

I'm playing with pivot table and found them extremely slow. 

After some digging, I'm not alone : 
- https://discourse.metabase.com/t/pivot-tables-extremely-slow/13694
- https://discourse.metabase.com/t/how-to-improve-performance-in-data-present-in-pivod-table/16350/8
- https://discourse.metabase.com/t/pivot-table-is-just-running/16602

I did some research on how table are pivoted looking at queries generated on my database and I probably found an optimization with filters. 

**Example source query :** 

 ```
SELECT `REQUEST`.`REQ_ID` AS `REQ_ID`,
 		`REQUEST`.`REQ_DATETIME` AS `REQ_DATETIME`,
          `Agence`.`AG_NOM` AS `Agence__AG_NOM`,
          `Marque`.`LIBELLE` AS `Marque__LIBELLE`,
          `Status`.`STA_NAME` AS `Status__STA_NAME`
   FROM `REQUEST`
   LEFT JOIN `AGENCE` `Agence` ON `REQUEST`.`AG_ID` = `Agence`.`AG_ID`
   LEFT JOIN `REF_SOCIETE` `Marque` ON `Agence`.`SOC_ID` = `Marque`.`SOC_ID`
   LEFT JOIN `STATUS` `Status` ON `REQUEST`.`REQ_LAST_STATUS` = `Status`.`STA_ID`
   LEFT JOIN `AGENCE` `AGENCE__via__AG_ID` ON `REQUEST`.`AG_ID` = `AGENCE__via__AG_ID`.`AG_ID`
   WHERE (`REQUEST`.`REQ_DATETIME` >= date(now(6))
       AND `REQUEST`.`REQ_DATETIME` < date(date_add(now(6), INTERVAL 1 DAY)))
```

Result : 145 row(s) fetched - 39ms (4ms fetch), on avr. 15, 09:39:30

**Pivoted one :** 

```
SELECT `source`.`Marque__LIBELLE` AS `Marque__LIBELLE`,
       `source`.`Agence__AG_NOM` AS `Agence__AG_NOM`,
       `source`.`Status__STA_NAME` AS `Status__STA_NAME`,
       `source`.`pivot-grouping` AS `pivot-grouping`,
       count(DISTINCT `source`.`REQ_ID`) AS `count`
FROM
  (SELECT `REQUEST`.`REQ_ID` AS `REQ_ID`,
  		   `REQUEST`.`REQ_DATETIME` AS `REQ_DATETIME`,
          abs(0) AS `pivot-grouping`,
          `Agence`.`AG_NOM` AS `Agence__AG_NOM`,
          `Marque`.`LIBELLE` AS `Marque__LIBELLE`,
          `Status`.`STA_NAME` AS `Status__STA_NAME`
   FROM `REQUEST`
   LEFT JOIN `AGENCE` `Agence` ON `REQUEST`.`AG_ID` = `Agence`.`AG_ID`
   LEFT JOIN `REF_SOCIETE` `Marque` ON `Agence`.`SOC_ID` = `Marque`.`SOC_ID`
   LEFT JOIN `STATUS` `Status` ON `REQUEST`.`REQ_LAST_STATUS` = `Status`.`STA_ID`
   LEFT JOIN `AGENCE` `AGENCE__via__AG_ID` ON `REQUEST`.`AG_ID` = `AGENCE__via__AG_ID`.`AG_ID`) `source`
WHERE (`source`.`REQ_DATETIME` >= date(now(6))
       AND `source`.`REQ_DATETIME` < date(date_add(now(6), INTERVAL 1 DAY)))
GROUP BY `source`.`Marque__LIBELLE`,
         `source`.`Agence__AG_NOM`,
         `source`.`Status__STA_NAME`,
         `source`.`pivot-grouping`
ORDER BY `source`.`Marque__LIBELLE` ASC,
         `source`.`Agence__AG_NOM` ASC,
         `source`.`Status__STA_NAME` ASC,
         `source`.`pivot-grouping` ASC
```

Result : 16 row(s) fetched - 10.524s (1ms fetch), on avr. 15, 09:45:33

Problem : the "source" sub query is not filtered as asked in initial query, only the pivot is filtered. 

**Optimized pivot** (where clause on source, not on pivot) : 

```
SELECT `source`.`Marque__LIBELLE` AS `Marque__LIBELLE`,
       `source`.`Agence__AG_NOM` AS `Agence__AG_NOM`,
       `source`.`Status__STA_NAME` AS `Status__STA_NAME`,
       `source`.`pivot-grouping` AS `pivot-grouping`,
       count(DISTINCT `source`.`REQ_ID`) AS `count`
FROM
  (SELECT `REQUEST`.`REQ_ID` AS `REQ_ID`,
  		   `REQUEST`.`REQ_DATETIME` AS `REQ_DATETIME`,
          abs(0) AS `pivot-grouping`,
          `Agence`.`AG_NOM` AS `Agence__AG_NOM`,
          `Marque`.`LIBELLE` AS `Marque__LIBELLE`,
          `Status`.`STA_NAME` AS `Status__STA_NAME`
   FROM `REQUEST`
   LEFT JOIN `AGENCE` `Agence` ON `REQUEST`.`AG_ID` = `Agence`.`AG_ID`
   LEFT JOIN `REF_SOCIETE` `Marque` ON `Agence`.`SOC_ID` = `Marque`.`SOC_ID`
   LEFT JOIN `STATUS` `Status` ON `REQUEST`.`REQ_LAST_STATUS` = `Status`.`STA_ID`
   LEFT JOIN `AGENCE` `AGENCE__via__AG_ID` ON `REQUEST`.`AG_ID` = `AGENCE__via__AG_ID`.`AG_ID`
   WHERE (`REQUEST`.`REQ_DATETIME` >= date(now(6))
       AND `REQUEST`.`REQ_DATETIME` < date(date_add(now(6), INTERVAL 1 DAY))) ) `source`
GROUP BY `source`.`Marque__LIBELLE`,
         `source`.`Agence__AG_NOM`,
         `source`.`Status__STA_NAME`,
         `source`.`pivot-grouping`
ORDER BY `source`.`Marque__LIBELLE` ASC,
         `source`.`Agence__AG_NOM` ASC,
         `source`.`Status__STA_NAME` ASC,
         `source`.`pivot-grouping` ASC
```

16 row(s) fetched - 20ms, on avr. 15, 09:47:26

From 10.524s to 20ms, it's 99.8% better. 

Do you think this can be implemented ? 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by metamben**
Fixes #21688 for trivial cases. (I'm not sure this PR is enough to close the issue.)

The fundamental problem is that whenever we process a query with expression, we nest it in a subquery. (I assume we do this to make sure that expressions are calculated once.) The expectation is that the DB engine optimizes this subquery away, but it seems this is unfortunately not the case for some of the DBMSs.  My understanding is that referring to fields that are not used can still lead to those fields being loaded and filtering outside the nested query can lead to loading rows that are then thrown away.

This PR tries to optimize queries when this is trivially doable:
1. it makes sure we refer only fields that are referenced in the nested query instead of referring all of them, and
2. if the filter clause contains no expression, it is kept in the nested query and not pulled up to the outer query.

### CODE REVIEW

**Comment by camsaul** [comment]
RE 

>I assume we do this to make sure that expressions are calculated once.

It's been so long since we implemented expressions I don't remember exactly why I did it, but I think the main reason for pushing the expressions down into a nested query was that if the expression compiled to parameterized SQL like `something(some_field, ?)` then it would blow up if you tried to put it in both `GROUP BY` and `ORDER BY`, since the DB can't verify that those two expressions are the same thing. It wasn't to prevent the expression from being calculated multiple times

**Review by camsaul — APPROVED** [review]
I think this approach makes sense. Do you think it's feasible to build on this and be able optimize the pivot stuff more generally as a follow-on? I'm happy either way, this is still a net win. Just thinking in terms of whether we might want to schedule time to work towards a more general fix during the 47 cycle

**Comment by metamben** [comment]
> Do you think it's feasible to build on this and be able optimize the pivot stuff more generally as a follow-on?

@camsaul As per your explanation, the nesting is important and will have to stay. A more general solution would probably require partial interpretation of the filter to see which parts of it can be left in the nested query. This is doable, but of course much more complicated than what I did here and therefore more error prone.  I would only embark on doing this if we have some concrete cases where we clearly see they are worth the effort.
If we can get rid of the nesting, that would solve problem at its root, but seems like a risky change.

TBH, #21688 is very generic and I could not check if my change really fixes the OP's problem. I _assume_ that the kinds of problems that are reported there occur in column oriented DBs with a lot of data.

**Comment by prigal** [comment]
Hello, I'm the OP, I will run the same test again when it will be released, I don't have any expressions in my query (only pure sql), it should work.

I will just wait for 0.46.1 as long as we never update before .1. 

Thanks for your work on this.

**Pull request merged**
