### PR TITLE
Search widget polish

### LINKED ISSUE #6995: Follow-up polish for filter search widget
Follow-up items for https://github.com/metabase/metabase/pull/4241

**Quriks**
- [ ] If an existing query builder category filter uses an operator other than `Is`, the operators list should be expanded by default when clicking on the filter to modify it.
- [ ] The operators being hidden under Options was only intended to be the behavior for categoric fields, not numeric ones. The filter popover for numeric fields should be unchanged.
- [x] If I've clicked on Options to show the logical operators, but then I click to go back to the list of fields and select a different field to filter on, the options have stayed opened, which I did not expect.
- [ ] Finite lists of options incorrectly display `Including every option in your filter probably won’t do much…` if you enter in a search parameter that doesn't match any value in the list.
- [ ] In the case of FK fields where I can search by an entity name _or_ enter an ID, if I start typing an ID I get the "no matching results found" message. This is correct in that it's trying to search the list of entity names, but it makes me feel like I'm typing in an incorrect ID. My current dumb idea for a solution would be to change the no-results message in this case to include the entity name, like, "No matching Last Names found," to clarify a little that it's searching on the entity name, and that the ID you're typing isn't wrong.

**Visuals**
- [ ] Get a max-width in place so that the popovers don't change in size as more options are selected and added to the token box
- [ ] Implement the design for the default state for search widgets, with the magnifying glass
- [ ] After `Options` is clicked, it should either go away or change to `Hide options`
- [ ] The `Options` button can get really close to long field names. This will be fixed somewhat by the width of the popover getting extended and fixed, but the Options link itself also needs some extra padding-left.
- [ ] Dashboard category filters widgets are missing `cursor-pointer`, as is our hallowed tradition. Not talking about the popover, but the filter widget itself, both when the filter is inactive as well as active.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #6995

Follow-up items for https://github.com/metabase/metabase/pull/4241

**Quriks**
- ~If an existing query builder category filter uses an operator other than `Is`, the operators list should be expanded by default when clicking on the filter to modify it.~
- ~The operators being hidden under Options was only intended to be the behavior for categoric fields, not numeric ones. The filter popover for numeric fields should be unchanged.~
- [x] If I've clicked on Options to show the logical operators, but then I click to go back to the list of fields and select a different field to filter on, the options have stayed opened, which I did not expect.
- [x] Finite lists of options incorrectly display `Including every option in your filter probably won’t do much…` if you enter in a search parameter that doesn't match any value in the list.
- [x] In the case of FK fields where I can search by an entity name _or_ enter an ID, if I start typing an ID I get the "no matching results found" message. This is correct in that it's trying to search the list of entity names, but it makes me feel like I'm typing in an incorrect ID. My current dumb idea for a solution would be to change the no-results message in this case to include the entity name, like, "No matching Last Names found," to clarify a little that it's searching on the entity name, and that the ID you're typing isn't wrong.
- [ ] The fixed width of the popover is causing it to get clipped on the right side of the browser
- [x] There's also a weird behavior now where if I have a filter with a long-ish label, when I click on it, it gets shrunken down to the width of the popover
- [x] In search widgets, selecting the only item that matches a search term causes text to show up that says that no matches have been found. In this case, maybe the best behavior would be to go back to the empty state for the search results area, i.e. display the magnifying glass.
- [x] This is a foreign key field, Product ID, that I've remapped to the product title, and renamed to "Product:" But Metabase seems to think it's a number, so I'm getting numeric operators, and it's causing some weird states:
- [x] We'll want to make sure we add some margin-bottom to the dropdown in the Empty and Not Empty operator states

**Visuals**
- [x] Get a max-width in place so that the popovers don't change in size as more options are selected and added to the token box
- [x] Implement the design for the default state for search widgets, with the magnifying glass
- [x] After `Options` is clicked, it should either go away or change to `Hide options`
- [x] The `Options` button can get really close to long field names. This will be fixed somewhat by the width of the popover getting extended and fixed, but the Options link itself also needs some extra padding-left.
- [x] Dashboard category filters widgets are missing `cursor-pointer`, as is our hallowed tradition. Not talking about the popover, but the filter widget itself, both when the filter is inactive as well as active.

### CODE REVIEW

**Comment by tlrobinson** [comment]
> Get a max-width in place so that the popovers don't change in size as more options are selected and added to the token box

@mazameli  IMO for parameters the widget should initially be the same size as the un-opened parameter, so I've implemented an auto-expanding behavior, where as soon as the widget expands beyond the initial size due to the user entering or clicking a option it expands to a larger fixed fixed, so it only changes size once. I feel like this is an acceptable tradeoff, but let me know what you think.

**Comment by tlrobinson** [comment]
> The operators being hidden under Options was only intended to be the behavior for categoric fields, not numeric ones. The filter popover for numeric fields should be unchanged.

@mazameli as I mentioned in Slack I think it would be good if we could unify the operator selector behavior so we don't have both "Options" and "More Options". If we remove "More Options" then the operator selector takes up a lot of real estate, which is bad if the operators are visible by default.

I think it would be better if we somehow showed the operator name in the header and make the operator picker more of a transient thing. Perhaps we could show it by default for new filters, but hide it otherwise.

I've implemented some of these ideas in this branch.

**Comment by mazameli** [comment]
@tlrobinson I think the simplest thing for operators, which will also match the way we're treating Date filters now, would be to go with a dropdown. (You were right after all, @salsakran.) 

I'd wanted to see if we could avoid always taking up that space with the `Is` operator for category filters, since it's very often the case that `Is` is what you want, but I do think after all that this is going to make for the most consistent experience across all filter types in the query builder.

operators

**Comment by tlrobinson** [comment]
Cool, +1 for filter reunification. Though I agree the small “Is” looks out of place.

Adding the custom layouts for numeric filters and reunifying the date filters with everything else is a slightly non trivial project so I might do that as a a separate PR. I’ll implement the top row of your designs for both string and number filters as part of this PR

**Comment by mazameli** [comment]
> IMO for parameters the widget should initially be the same size as the un-opened parameter, so I've implemented an auto-expanding behavior, where as soon as the widget expands beyond the initial size due to the user entering or clicking a option it expands to a larger fixed fixed, so it only changes size once. I feel like this is an acceptable tradeoff, but let me know what you think.

This doesn't offend me horribly, but just looks a little cramped to me in some cases, like this one below. But I can probably just bump up the margin outside the search box a bit:

screen shot 2018-02-23 at 4 24 33 pm

There's also a weird behavior now where if I have a filter with a long-ish label, when I click on it, it gets shrunken down to the width of the popover:

screen shot 2018-02-23 at 4 31 19 pm

screen shot 2018-02-23 at 4 31 26 pm

**Comment by mazameli** [comment]
All the filter buttons have gotten tiny!

Here's how they are on Stats.mb, and how they used to be up until today:

screen shot 2018-02-23 at 4 23 54 pm

Here's how they're looking currently:

screen shot 2018-02-23 at 4 24 08 pm

**Comment by mazameli** [comment]
The fixed width of the popover is causing it to get clipped on the right side of the browser:

screen shot 2018-02-23 at 4 29 38 pm

**Comment by tlrobinson** [comment]
> All the filter buttons have gotten tiny

@mazameli oops, I adjusted the padding on the footer from p2 to p1 so it matched the rest of the widget, and the button felt too large so I dropped it down to medium sized. I forgot our button sizes have screen width breakpoints and I guess my screen was big. I’ll switch the buttons back to full sized.

**Comment by mazameli** [comment]
This is a foreign key field, Product ID, that I've remapped to the product title, and renamed to "Product:"

screen shot 2018-02-27 at 5 05 56 pm

But Metabase seems to think it's a number, so I'm getting numeric operators, and it's causing some weird states:

screen shot 2018-02-27 at 5 04 18 pm

screen shot 2018-02-27 at 5 04 45 pm

What could be greater than Awesome Wooden Pants, though, really?

screen shot 2018-02-27 at 5 05 09 pm

**Comment by mazameli** [comment]
We'll want to make sure we add some margin-bottom to the dropdown in the Empty and Not Empty operator states:

screen shot 2018-02-27 at 5 20 42 pm

**Comment by tlrobinson** [comment]
> This is a foreign key field, Product ID, that I've remapped to the product title, and renamed to "Product:"
> 
> But Metabase seems to think it's a number, so I'm getting numeric operators, and it's causing some weird states:

We've always allowed the numeric operators on numeric ID fields (and string operators on string ID fields). It seems reasonable to want to do BETWEEN two IDs.

I agree showing the search icon under both is wrong. I've changed it so it only shows it under the currently focused one.

**Comment by mazameli** [comment]
What makes it feel particularly weird is that this is a _remapped_ FK field, so the fact that it's an ID "under the hood" is obscured. The fact that I'm able to search on the entity name exacerbates the feeling that this should act more like a category field than a number field. I'm not against the "Between" operator, but it just feels funny that the default operator is "Equals" instead of "Is."

**Comment by mazameli** [comment]
With dashboard or SQL filters, if I make a number of selections but don't hit the Done button, I can get into a weird state where the widget says I've made selections, but the filter doesn't get applied. To make this consistent with the query builder, we should discard the selections unless the Done button is pressed.

unapplied-filter

**Comment by mazameli** [comment]
Remapped FK fields don't seem to be filtering properly in SQL filters. [Here's a video that shows the behavior.](https://github.com/metabase/metabase/files/1768541/remapped-fks.mp4.zip)

screen shot 2018-02-28 at 11 26 40 am





**These same filters are getting applied correctly both in the query builder and in dashboards:**
 
screen shot 2018-02-28 at 11 21 20 am

screen shot 2018-02-28 at 11 19 39 am

screen shot 2018-02-28 at 11 18 14 am


**Remapped _primary keys_ are also working _correctly_ in SQL:**

screen shot 2018-02-28 at 11 24 34 am

**So are basic category filters:**

screen shot 2018-02-28 at 11 17 42 am

**Comment by mazameli** [comment]
@salsakran and I took a look at this, and once the FK fields in SQL, and the selected-but-not-applied issues I mentioned above are fixed, this is ready to merge from a product perspective. 🎉

**Comment by tlrobinson** [comment]
> Remapped FK fields don't seem to be filtering properly in SQL filters.

@mazameli This is because you have the optional clause double brackets (`[[...]]`) around the whole `WHERE` clause and you're not providing a value for `z`, so it's stripping the whole thing off.

If you change it to `select * from orders where {{x}} AND {{y}} [[AND subtotal = {{z}}]]` it should work.

It wasn't a problem in your other examples because you only used field filter tags, and they're replaced with `1 = 1` so the optional clause doesn't need to be stripped off.

We should probably have better validation to warn if you provide a value for a template tag but it's removed because another template template is unset, but this isn't a regression and should be addressed separately.


screenshot 2018-03-01 15 01 21

**Comment by tlrobinson** [comment]
@mazameli  I believe I've fixed the other issues you mentioned.

**Comment by mazameli** [comment]
> This is because you have the optional clause double brackets ([[...]]) around the whole WHERE clause and you're not providing a value for z, so it's stripping the whole thing off.

Ahhh, gotcha. Sorry for the false alarm!

> We should probably have better validation to warn if you provide a value for a template tag but it's removed because another template template is unset, but this isn't a regression and should be addressed separately.

Agreed. I'll file this as its own thing.

**Comment by mazameli** [comment]
This looks ready to go once tests are green. 🎉

**Pull request merged**
