### PR TITLE
fix: Use an indicator-agnostic testid

### LINKED ISSUE #44271: Use a loading indicator-agnostic testid

### PR DESCRIPTION
**Pull request by rafpaf**
Changes the `"loading-spinner"` testid to `"loading-indicator"`.

Closes #44271

### CODE REVIEW

**Comment by rafpaf** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/metabase/metabase/44265?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#44265** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44265?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#44010** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44010?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#44008** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44008?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#43979](https://github.com/metabase/metabase/pull/43979) <a href="https://app.graphite.dev/github/pr/metabase/metabase/43979?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#44139](https://github.com/metabase/metabase/pull/44139) <a href="https://app.graphite.dev/github/pr/metabase/metabase/44139?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#43970** <a href="https://app.graphite.dev/github/pr/metabase/metabase/43970?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sloansparger — APPROVED** [review]
apologies, looks like my delayed review has resulted in some merge conflicts

**Comment by rafpaf** [comment]
### Merge activity

* **Jun 19, 8:32 PM EDT**: @rafpaf merged this pull request with [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/44265).

**Comment by iethree** [comment]
I know this PR relates to adding support for skeletons, but it would be very helpful if that was discernible from the PR or the issue 🙏

**Pull request merged**
