### PR TITLE
Don't show links in table cells for aggregations

### PR DESCRIPTION
**Pull request by tlrobinson**
#803

This only prevents the linkification, not selecting senseless aggregations. Perhaps changing the `SUMMABLE` type to exclude `fk` and `id` `special_type`s would be sufficient? https://github.com/metabase/metabase/blob/master/frontend/src/lib/schema_metadata.js#L48

### CODE REVIEW

**Comment by agilliland** [comment]
cool.  I agree that we should update the definition of summable to exclude ID and FK special_types.  can you add that to this PR?  then this is g2g :+1:

**Comment by tlrobinson** [comment]
Sounds good. While I'm at it there are a bunch of other types we could exclude from `SUMMABLE`. `COORDINATE`, `LOCATION`, `DATE_TIME` seem like obvious choices, maybe even `CATEGORY`?

**Comment by agilliland** [comment]
makes sense to me.

**Comment by tlrobinson** [comment]
On second thought you may want to average a category, e.x. rating. But I think the others are ok to exclude.

**Comment by salsakran** [comment]
Coordinate and category were summable to allow things to be averaged. If we
nix them we should expand the allowed list for averages.

**Comment by tlrobinson** [comment]
Ok, only included ENTITY, LOCATION, and DATE_TIME for now (can times be averaged though?)

**Pull request merged**
