### PR TITLE
🤖 backported "convert embed.ts to ts and to use createSlice from rtk"

### PR DESCRIPTION
**Pull request by github-automation-metabase**
Backport of #44496

Without the fix in the second commit it failed because on master we don't store the font on redux anymore and I removed the parsing of the hash parameters

@deniskaber I asked your review as you did the related changes

### CODE REVIEW

**Review by deniskaber — APPROVED** [review]

**Review by deniskaber — COMMENTED** [review]
Sorry, I approved this initially, but after a second thought - removing possibility to pass parameters using hash is a breaking change. We should not introduce this in a patch.

Could you please remove parameters validation for `50.x`?

**Comment by npretto** [comment]
> Sorry, I approved this initially, but after a second thought - removing possibility to pass parameters using hash is a breaking change. We should not introduce this in a patch.
> 
> Could you please remove parameters validation for `50.x`?

Sure, should all of the parameters be allowed both in search and in hash?

**Comment by npretto** [comment]
> > Sorry, I approved this initially, but after a second thought - removing possibility to pass parameters using hash is a breaking change. We should not introduce this in a patch.
> > Could you please remove parameters validation for `50.x`?
> 
> Sure, should all of the parameters be allowed both in search and in hash?

Changed it to what it was before in v50, so spreading both search and hash parameters in 96d5b0daaf47017c9f7d33490a3eca73538a5d1a.
I also changed a test to make sure we don't backport other breaking changes

**Review by deniskaber — APPROVED** [review]
Nice! Thank you, @npretto !

**Pull request merged**
