### PR TITLE
Summary table [WIP]

### PR DESCRIPTION
**Pull request by r-kot**
This new visualization type automatically groups fields in the order they appear in the query results by default, but this grouping can be reordered. This visualization also displays totals and the grand total by default, but this can be turned toggled per grouping field in the options.

obraz

obraz

TODO:
- [ ] improve description
- [ ] from https://github.com/metabase/metabase/pull/8427#issuecomment-417503638
  -  [x] 1. change the default settings
  -  [x] 2. change the default sort order
  -  [ ] 3. add support for nested pivot
  -  [x] 4. fix sorting from header
  -  [x] 5. fix strange state
  -  [x] 6. fix settings behaviour
  -  [x] 7. fix disappearing header for a pivot table
  -  [x] 8. fix header for pivot 
  -  [x] 9. fix the size of labels for totals

- [x] fix drill-through
- [ ] fix flow
- [x] refactor code
- [x] add tests
- [ ] add comments

-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by mazameli** [comment]
This seems to be coming along nicely! I'll have to do another review of the finer details, such as visuals and microcopy, but I spent a while playing with this and noting some of the larger behavioral bugs and quirks I've come across in the branch so far:

1. With a query builder question with two metrics (count of rows, and sum of Total), only my Sum column automatically showed up in the Table Values section of the pivot table settings. Expected: all aggregations/metrics should default to being in the Table Values section.

2. All of the Table Rows fields seemed to default to Descending instead of Ascending. I expected the default sort to be Ascending.

3. It doesn't appear as though I can use more than one field for columns. I would expect to have the columns be nested/grouped, e.g. each Source listed per each Category in this example:
multiple-fields-for-columns

4. There seems to be both a bug or performance issue as well as a visual issue when trying to sort the table using the dashboard-card table heading actions. When using the table heading sort actions from within the question detail page, I don't experience the same freezing behavior, but it appears the visualization sort settings are overriding the query sort settings (i.e. the sorting is happening in the front end only). I recall us discussing this months ago, but I don't recall the conclusion we arrived at WRT where the sorting should happen. I'd like @tlrobinson to weigh in on that.
table-sort

5. When you don't include some of the fields returned by the query, you can get into some strange states, like this one, where it is showing multiple blank rows for some reason:
screen shot 2018-08-30 at 4 18 44 pm

Removing the unused fields from the query results in an expected table:

screen shot 2018-08-30 at 4 20 59 pm

6. When I have an existing summary table (in this example with 2 metrics and 1 group-by to start) and I add a new group-by (`Product.Category` in this example) and re-run the query, nothing appears to change:

screen shot 2018-08-30 at 4 23 29 pm

I expected the new group-by to be used in the Rows for the table by default, like this:

screen shot 2018-08-30 at 4 23 49 pm

7. Sometimes when moving a field from being used as Rows to being used as Columns instead, the column headings don't appear after closing the visualization settings. Refreshing the entire page (not just re-running the query) does bring the headings back, however.

field-as-rows-to-columns

8. When using a binned numeric field (like Age ranges) for Columns, the column heading only shows one number in the range instead of the full range, e.g. only `18` instead of `0 – 18`. However, the full range label correctly appears when using the field as Rows.

9. It would be nice if these "totals" cells were wide enough by default so that you don't have to expand the width of them:

totals-label

**Comment by salsakran** [comment]
@r-kot Let us know when this should get re-reviewed. Thank you for all the work you're doing here!

**Comment by dannyeuu** [comment]
This will be a really improvement to get insights from data, congrats !

**Comment by r-kot** [comment]
@mazameli  Could we move the implementation of nested pivot (point no 3 from your post) into the next version of the summary table?
I want to decrease scope to end this task it faster.

**Comment by mazameli** [comment]
@r-kot Yes, I think that's fine for the first version of this feature.

**Comment by mazameli** [comment]
This is looking quite close, @r-kot. Here's what I'm seeing:

**Performance**
* Summary Tables seem to take 2–3 seconds sometimes to render or to re-render when a change has been made, such as when changing the sort order or pivoting the table.

**Issues**
* When my query result is raw data, if I select a Summary Table it doesn't render.
* If my query result is raw data and I open the chart options, I can't exit out of the modal.
* Totals and Subtotals seem to always be summing Values columns, even if the metric is e.g. an average. For example in this screenshot, I would expect to see the _average_ for the values [3,4,4,3] rather than the sum of them:

screen shot 2018-10-08 at 12 37 35 pm

**Polish**
* There are a number of smaller visual/UX polish items that I think the core team should handle after this PR is merged. 

**Next steps:**
I believe @tlrobinson will give this a code review later this week.

**Comment by r-kot** [comment]
@mazameli 
Thanks for the feedback.
 > - When my query result is raw data, if I select a Summary Table it doesn't render.
 >  - If my query result is raw data and I open the chart options, I can't exit out of the modal.

Could you give me more details to reproduce these bugs?
Could you test it on the latest version?

 > - Totals and Subtotals seem to always be summing Values columns, even if the metric is e.g. an average. For example in this screenshot, I would expect to see the average for the values [3,4,4,3] rather than the sum of them

It is easy to fix, I will do it tomorrow.

**Comment by mazameli** [comment]
For the raw data issue, here's what I'm observing:

raw-data

Here's the server error I'm seeing:

```
10-09 13:55:29 WARN metabase.query-processor :: {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error
 "Input to auto-bucket-datetime-breakouts* does not match schema: \n\n\t   [(named {:query {:breakout [nil nil nil nil nil nil nil nil (named [nil nil (named (not (\"Valid field type\" nil)) \"field-type\")] \"Must be a valid instance of one of these clauses: :field-id, :field-literal, :fk->, :datetime-field, :expression, :binning-strategy\") nil]}} arg0)]  \n\n",
 :stacktrace
 ["query_processor.middleware.auto_bucket_datetime_breakouts$eval44285$auto_bucket_datetime_breakouts_STAR___44290.invoke(auto_bucket_datetime_breakouts.clj:40)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__43784.invoke(add_row_count_and_status.clj:15)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__46462.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__49650.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__44324$fn__44325.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:85)"
  "util.date$call_with_effective_timezone.invoke(date.clj:74)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__44324.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__51628$fn__51629.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:32)"
  "query_processor.store$do_with_store.invoke(store.clj:28)"
  "query_processor.middleware.store$initialize_store$fn__51628.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__44778.invoke(cache.clj:150)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46349.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:149)"
  "query_processor$process_query.invoke(query_processor.clj:145)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:265)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:259)"
  "query_processor$eval51673$process_query_and_save_execution_BANG___51678$fn__51679.invoke(query_processor.clj:289)"
  "query_processor$eval51673$process_query_and_save_execution_BANG___51678.invoke(query_processor.clj:275)"
  "query_processor$eval51697$process_query_and_save_with_max_BANG___51702$fn__51703.invoke(query_processor.clj:310)"
  "query_processor$eval51697$process_query_and_save_with_max_BANG___51702.invoke(query_processor.clj:306)"
  "api.dataset$download_dataset$fn__54782.invoke(dataset.clj:44)"
  "api.common$eval25377$invoke_thunk_with_keepalive__25382$fn__25383$fn__25384.invoke(common.clj:435)"],
 :query
 {:type "query",
  :query {:source-table 1},
  :parameters [],
  :super-query
  {:aggregation [],
   :breakout
   [["field-literal" "DISCOUNT" "type/Float"]
    ["field-literal" "SUBTOTAL" "type/Float"]
    ["field-literal" "TOTAL" "type/Float"]
    ["field-literal" "CREATED_AT" "type/DateTime"]
    ["field-literal" "QUANTITY" "type/Integer"]
    ["field-literal" "PRODUCT_ID" "type/Integer"]
    ["field-literal" "TAX" "type/Float"]
    ["field-literal" "USER_ID" "type/Integer"]
    ["field-literal" "TITLE" nil]
    ["field-literal" "ID" "type/BigInteger"]]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 2,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [-81, -97, 82, -22, -103, -59, -98, -4, -33, -106, 51, -98, 125, -128, 56, -102, 7, -96, 29, 119, 3, 95, -20, -106, 78, -124, -79, 96, -85, -31, 106, 114],
   :query-type "MBQL"}},
 :expanded-query nil,
 :ex-data
 {:type :schema.core/error,
  :value
  [{:database 1,
    :type :query,
    :query
    {:breakout
     [[:field-literal "DISCOUNT" :type/Float]
      [:field-literal "SUBTOTAL" :type/Float]
      [:field-literal "TOTAL" :type/Float]
      [:field-literal "CREATED_AT" :type/DateTime]
      [:field-literal "QUANTITY" :type/Integer]
      [:field-literal "PRODUCT_ID" :type/Integer]
      [:field-literal "TAX" :type/Float]
      [:field-literal "USER_ID" :type/Integer]
      [:field-literal "TITLE" nil]
      [:field-literal "ID" :type/BigInteger]],
     :source-query {:source-table 1}},
    :constraints {:max-results 10000, :max-results-bare-rows 2000},
    :info
    {:executed-by 2,
     :context :ad-hoc,
     :nested? true,
     :query-hash [-81, -97, 82, -22, -103, -59, -98, -4, -33, -106, 51, -98, 125, -128, 56, -102, 7, -96, 29, 119, 3, 95, -20, -106, 78, -124, -79, 96, -85, -31, 106, 114],
     :query-type "MBQL"},
    :driver {},
    :settings {},
    :nested? true}],
  :error
  [(named {:query {:breakout [nil nil nil nil nil nil nil nil (named [nil nil (named (not ("Valid field type" nil)) "field-type")] "Must be a valid instance of one of these clauses: :field-id, :field-literal, :fk->, :datetime-field, :expression, :binning-strategy") nil]}} arg0)]}}

10-09 13:55:29 WARN metabase.query-processor :: Query failure: Input to auto-bucket-datetime-breakouts* does not match schema:

           [(named {:query {:breakout [nil nil nil nil nil nil nil nil (named [nil nil (named (not ("Valid field type" nil)) "field-type")] "Must be a valid instance of one of these clauses: :field-id, :field-literal, :fk->, :datetime-field, :expression, :binning-strategy") nil]}} arg0)]


["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:233)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:226)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:266)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:259)"
 "query_processor$eval51673$process_query_and_save_execution_BANG___51678$fn__51679.invoke(query_processor.clj:289)"
 "query_processor$eval51673$process_query_and_save_execution_BANG___51678.invoke(query_processor.clj:275)"
 "query_processor$eval51697$process_query_and_save_with_max_BANG___51702$fn__51703.invoke(query_processor.clj:310)"
 "query_processor$eval51697$process_query_and_save_with_max_BANG___51702.invoke(query_processor.clj:306)"
 "api.dataset$download_dataset$fn__54782.invoke(dataset.clj:44)"
 "api.common$eval25377$invoke_thunk_with_keepalive__25382$fn__25383$fn__25384.invoke(common.clj:435)"]
```

**Comment by mazameli** [comment]
Here's what the options modal issue looks like:

options

Clicking on the buttons or outside of the modal results in this JS error:

```
Warning: performUpdateIfNecessary: Unexpected batch number (current 679, pending 498)
printWarning @ warning.js:33
warning @ warning.js:57
performUpdateIfNecessary @ ReactReconciler.js:146
runBatchedUpdates @ ReactUpdates.js:148
perform @ Transaction.js:141
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
close @ ReactUpdates.js:45
closeAll @ Transaction.js:207
perform @ Transaction.js:154
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:65
onStateChange @ connectAdvanced.js:202
(anonymous) @ makeAssimilatePrototype.js:15
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:65
onStateChange @ connectAdvanced.js:202
(anonymous) @ makeAssimilatePrototype.js:15
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:17
(anonymous) @ bindActionCreators.js:3
VisualizationSettings._this.close @ VisualizationSettings.jsx:17
handleDismissal @ Modal.jsx:63
(anonymous) @ makeAssimilatePrototype.js:15
OnClickOutsideWrapper._this._handleDismissal @ OnClickOutsideWrapper.jsx:72
setTimeout (async)
OnClickOutsideWrapper._this._handleClick @ OnClickOutsideWrapper.jsx:63
```

```
ReactReconciler.js:60 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:60)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:381)
    at Object.getHostNode (ReactReconciler.js:60)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:381)
    at Object.getHostNode (ReactReconciler.js:60)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:381)
    at Object.getHostNode (ReactReconciler.js:60)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:381)
    at Object.getHostNode (ReactReconciler.js:60)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:342)
```

**Comment by mazameli** [comment]
@r-kot Ah, okay, I figured out what's going on: my `Orders` table was using the foreign-key values remapping feature to display the entity name of each Product instead of the foreign-key ID value, and that was causing the Orders table to not render as a Summary Table for some reason when using raw data. The other tables in the sample dataset render just fine.

Here's where you turn that remapping on/off:

screen shot 2018-10-10 at 11 39 28 am

**Comment by sbelak** [comment]
All the aggregates we support aside from distinct count have a single pass formulation where you aggregate simpler statististics and derive the one you actually want from those. Eg. to calculate average you track the sum and count, and divide them in the last step. It turns out that all can also be merged in straightforwad way, which is exctly what we need for summaries (continuing the avg example, you sum the sums and sum the counts of constituent groups and have components of the avg for the total). 

This approach would necessitate only a single relatively straightforward and performant query and no changes on the BE, at the cost of some additional fiddling on the FE. The other downside is, that we wouldn't be able to support distinct counts.

To get a better feel for the idea, have a look how these summary statstics are implemented in kixi https://github.com/MastodonC/kixi.stats/blob/v0.4.3/src/kixi/stats/core.cljc

**Comment by mazameli** [comment]
Someone asked in our meeting yesterday if this currently works with SQL queries. I tried it out and yes, it does:

screen shot 2018-10-23 at 1 57 02 pm

**Comment by tlrobinson** [comment]
@r-kot First of all, this is an impressive PR, thanks for working on it.

@mazameli I was surprised it worked for SQL queries, but I noticed it's not actually doing the right thing for the summary of any aggregations besides count/sum such as average... it's doing a sum of the averages rather than the average of all the values in the grouping. This is true for both SQL and GUI queries (it looks like super queries are just doing nested queries rather than doing the same query with different breakouts, which is why it sort of works for native queries)

**Comment by r-kot** [comment]
I really like the idea of calculations in clojure, but i'm not sure what should be returned by endpoints (eg /api/card/:id/query). I prefer to get a list of DatasetData, somenthing similar to:
DatasetData = {
	rows: Row[],
	cols: Column[],
	columns: ColumnName[];
	additionalResults?: DatasetData[] 
}

I implemented (in js) simple calculator for totals. It has bugs, but after some work we can use it instead of additional queries.
Calculations, unfortunately, are made on js primitives instead of decimals (sometimes precision of calculations matters).

**Comment by r-kot** [comment]
Hi @metabase/core-developers,
I fixed an error regarding "avg" queries.
What is the next step?
Do you have any conclusions on how we should solve the problem with a heavy load on the backend?

**Comment by dannyeuu** [comment]
There are no labels here for when is planned to release this feature? =)

**Comment by jornh** [comment]
@dannyeuu correctly observed 🙂 

Given concerns raised in the above discussion starting in https://github.com/metabase/metabase/pull/8427#issuecomment-432250705 I think that’s only appropriate. Even though the PR includes a lot of nice stuff (that I would also like to put my fingers on) if proper solutions/answers are not found to those concerns I’d rather wait.

Putting a milestone estimate on a PR like this as this stage is probably like answering the question _“How long time does it take to catch a fish?”_. I’d rather have the core developers judge by their gut feeling + facts/testing WHEN this is ready than risk introducing (too much) quality debt.

**Comment by rijnhardtkotze** [comment]
Do we have an update on this?

**Comment by r-kot** [comment]
Hi @rijnhardtkotze,
I will try to fix the performance problem by the end of next week.

**Comment by agoud1993** [comment]
subtot
subtot2
@mazameli  how did you do that. It's not working for me either in custom query oir SQL editor. The option for using summary or pivot table is not even showing up for me. 
My current version of Metabase is 0.31.2
and I'm using Firefox browser  version 52.6.0.0

**Comment by FallenChromium** [comment]
@r-kot any things we could help about this PR? It seems really awesome and apart from performance concerns it feels like finished part of Metabase. If you will describe goals you're trying to achieve probably community here can help you!

**Comment by dannyeuu** [comment]
It's stopped this PR @mazameli ? It will be really nice to have this!

**Comment by FallenChromium** [comment]
@dannyeuu I suppose that asking Maz about this is not the best idea. Probably it would be better to reach @r-kot first, or ask core-developers if they can finish this PR

**Comment by rijnhardtkotze** [comment]
Leaving another bump here. 

Any update?

**Comment by rijnhardtkotze** [comment]
Just following up again. 

Any updates here? Super keen on getting this!

**Comment by dannyeuu** [comment]
Just following up again. Any updates here @tlrobinson ?

**Comment by skaboy007** [comment]
It is unfortunate that this feature is no longer being developed looks like a must for Metabase. a natural representation of a drill-down 
@r-kot Cheers what do you think what will it take to complete this

**Comment by walterl** [comment]
This is a great feature, but, after some more discussion, this solution seems like it could have detrimental effects. Especially for users with big data sets.

That, and given how outdated this PR has become, I'm going to close it. If anyone else is willing to take a stab at it, feel free to take up the baton.

**Comment by aaronscifo** [comment]
A must-have feature, I hope that it might get considered in future releases

**Pull request closed without merging**
