### PR TITLE
Improvement of csv export

### PR DESCRIPTION
**Pull request by r-kot**
This pr improves the memory usage for csv export (for large amount of data). I tested it on Oracle and h2 databases.

###### Before submitting the PR, please make sure you do the following
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && lein check-namespace-decls && ./bin/reflection-linter`

-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by flamber** [comment]
Hi @r-kot 
My clojure-fu is close to zero, but from looking at your code, would this fix #5187 (not the XLSX)?

**Comment by r-kot** [comment]
Hi @flamber 
Yes, this pr should fix "Java heap space" error.
What version do you use?
On my private repo I have a branch for version 29.4. If you want I can share It.

**Comment by flamber** [comment]
@r-kot 
I haven't had the issue myself, I'm was just trying to link things together - in the hope it get's easier to find.
And then I like to look at PRs, so I can learn a little clojure :smile:

**Review by mazameli — CHANGES_REQUESTED** [review]
This PR appears to make changes to the query processor code, but to my eyes it doesn't appear to include corresponding tests, which we would need in order to merge this. There now unfortunately also appear to be some merge conflicts.

**Review by camsaul — CHANGES_REQUESTED** [review]
I don't think we necessarily need new tests, since this changes the implementation of existing functionality rather than fixing specific bugs or adding features. But we do need:

*  Fix merge conflicts
*  Fix style issues -- please familiarize yourself with Clojure style https://guide.clojure.style/

**Comment by walterl** [comment]
Superseded by #11554.

**Pull request closed without merging**
