### PR TITLE
ClickHouse Driver Module

### PR DESCRIPTION
**Pull request by enqueue**
Sorry to create yet another PR for ClickHouse driver (#3332). I tried to contribute to #8722 but the branch seems to have stalled.

### CODE REVIEW

**Comment by tlrobinson** [comment]
Hey all,

Thank you for this PR and apologies for the long delay responding. We've recently done some work to support drivers as plugins in Metabase and as of the next release (v0.32) we will be asking driver developers to first publish new drivers in their own repositories (typically named `metabase-*-driver`). If the driver fully passes the driver tests we will link to it from our documentation, and if a driver gains significant usage we will consider merging it into Metabase itself.

Here is some documentation about publishing a driver as a plugin in a separate repository: https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#drivers-shipped-as-3rd-party-plugins

Here are two example drivers: https://github.com/metabase/sudoku-driver https://github.com/metabase/crate-driver

We still have some work to do on the documentation. You can follow progress and provide feedback on that here: https://github.com/metabase/metabase/issues/9348

Thank you.

**Comment by tlrobinson** [comment]
By the way, I noticed there's another Clickhouse driver: #8491 You all may want to consider consolidating efforts.

**Comment by enqueue** [comment]
@tlrobinson thank you for your feedback. I will try and create a new repository for the plug-in. This PR is actually based on the work of others in #8491 but that PR was never closed.

**Comment by nicokruger** [comment]
Hi @enqueue did you ever get around to creating a seperate repository for this?

**Comment by flamber** [comment]
@nicokruger https://github.com/enqueue/metabase-clickhouse-driver

**Comment by dannyeuu** [comment]
@tlrobinson How working with plugins will work for now on?

**Pull request closed without merging**
