### PR TITLE
[MS1] Better Onboarding UX

### LINKED ISSUE #48335: [MS1] Better Onboarding: Educational Section in the Main Sidebar
## Links
- [Product doc](https://www.notion.so/metabase/Better-Onboarding-via-first-time-UX-7c76eef94d414bb0a864d7cc786229f2)
- [Figma designs](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6290-2701&node-type=canvas&m=dev)
    - [Main navigation updates](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6297-33793&m=dev)
    - [Add data section](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6290-2723&m=dev)
- Feature branch: `better-onboarding-ux-ms1`

### Implementation Plan
Introduce the new onboarding (footer) section in the main navigation sidebar. To goal is to help admins set up their instances faster by prompting them to (1) add their own database and/or (2) upload CSV. We're also making the link to Metabase Learn content more prominent.

> [!Important]
> In this phase we're making the "Add data" section available to **admins only**!

```[tasklist]
## Checklist
- [x] MS 1.1: Add visual elements
- [x] MS 1.2: Logic (Business and Permissions)
- [x] MS 1.3: Simple event schema analytics
- [x] MS 1.4: Tests
- [ ] MS 1.5: Final design polish (optional)
```

```[tasklist]
### Add database
- [x] Allow only admins to see this button
- [x] Remove the existing "Add your own data button"
```

```[tasklist]
### Upload CSV Button
- [x] Allow only admins to see and use this
- [x] Upload to "Our analytics" only
- [x] Trigger the upload modal
- [x] Upload types: create, append, replace
- [x] Remove the existing "Upload CSV" (for DWH) button
```

### LINKED ISSUE #48380: [MS1] Better Onboarding: Testing Plan
# Testing plan for [MS1](https://github.com/metabase/metabase/issues/48335)

### Dimensions
- User action
    - Add a database
    - Upload a spreadsheet
- CSV upload action type
    - create
    - append
    - replace
- Admin Settings
    - Did user already add database
    - Is upload enabled
- Permissions
    - admin
    - non-admin
- Visual real estate on screen
    - Very narrow screen (mobile)
    - Small height or a very busy sidebar
    - Interaction with other UI elements, such as "What's new" status
- "How to use Metabase" link
- Metabase plan/features
    - DWH enabled
    - Enterprise (whitelabelling - e.g. custom Metabase name)

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### What does this PR accomplish?
- Resolves #48335
- Resolves #48380

> [!TIP]
> All of the information you need to review this PR is in the previously linked _Milestone_ and _Testing plan_ issues. But the tl;dr is:
>
> **We're adding an educational section fixed at the very bottom of the main navigation sidebar.**

It has two parts:
1. _How to use Metabase_ link to the external Metabase learn content (shown to everyone always) [^1]
2. _Add data_ section (shown only to admins)

Add data's function is to facilitate faster data upload, which gives Metabase admin more value out of Metabase sooner.
They can either (1) Add a database, or (2) Upload a spreadsheet.

> [!IMPORTANT]
> Since this button can be accessed from **any** page, all CSV uploads are hooked up to go to the root collection!

---
### How it interacts with the existing UI elements with similar functionality?
- Completely replaces "Add your own data" button from the sidebar
- Completely replaces "Upload CSVs" button from the sidebar [^2]
- Doesn't interfere with the existing upload buttons present in collections

### Design system / component library considerations
We're adding a new (`learn`) icon. No other changes have been made.

### Documentation implication
@metabase/writers might have to update the documentation after this PR gets merged to `master`. Since we're backporting it to the current 50.x release, some changes might be needed in that branch as well.

---
### Analytics
Two new simple events are being sent to Snowplow. [^3]
End-to-end tests are put in place to ensure this functionality.

### Testing
- The majority of these changes were possible to cover with Jest integration tests.
- There are also some end-to-end tests in the newly added `add-initial-data.cy.spec.ts`

The PR is touching a lot of completely unrelated tests because they had unscoped `cy.icon("add_data")` selector. We're adding the same icon to the sidebar now. The solution was to use more semantic `cy.findByLabelText("Custom column")` selector.

Adding `uploadFile` action to the sidebar affected some related unit/integration tests. Fixed by 9f2bad1f21ebdcbfb1dfd3998ce6900c0318b9a3.

[^1]: This link will be transformed to an in-app link to the new route that contains the onboarding checklist. That is the scope of the future milestone of this project.
[^2]: Added specifically for the DWH instances during [this project](https://github.com/metabase/metabase/issues/42381).
[^3]: We're removing the obsolete `csv_upload_clicked` simple event.

### CODE REVIEW

**Review by Somtom — APPROVED** [review]
Only looked at the new events and they look valid to me 👍 . Maybe @npretto or @ranquild want to have another sanity check as well on those.

**Comment by nemanjaglumac** [comment]
> Only looked at the new events and they look valid to me 👍 . Maybe @npretto or @ranquild want to have another sanity check as well on those.

Thanks.
Yes, I tagged you specifically because of those new analytic events since this is the first time I'm working with them (since the overhaul).

**Review by romnitt — APPROVED** [review]

**Review by trinya — APPROVED** [review]

**Review by sloansparger — APPROVED** [review]
Code looks clean and the feature works! Ship it!

**Comment by nemanjaglumac** [comment]
@metabase-bot backport release-x.50.x

**Pull request merged**
