### PR TITLE
Whitespace linting

### PR DESCRIPTION
**Pull request by camsaul**
Add [my "Next-Level Whitespace Linter"](https://github.com/camsaul/whitespace-linter) that I slapped together in a couple hours to our project (as a GH action). Fix some errors it found

```
Found 1 errors
./deps.edn:328:57 Found Unicode character \u217f 'ⅿ' that looks way too similar to ASCII 'm' (:character/confusing-unicode-character)
```

demo

See the GH repo for more info.

### CODE REVIEW

**Comment by robdaemon** [comment]
I have to comment, this linter nitpicky, and subjective, and not something I would enable.

I don't mind style linters, as long as they have automatic "fix this for me" modes like JS prettier. I already have a tough enough time with the check-namespace-decl one because how it thinks things should be sorted is different than Calva does, which makes for manual work.

This all reminds me of my absolute favorite thing about Go - it forces a style at the compiler level, and tooling like `goimports` manages it all for you (hook it to on-save). Sure, it means that not everyone gets the code style they want, but it eliminates an entire class of code review feedback.

**Comment by camsaul** [comment]
@robdaemon this absolutely isn't something you should have to do manually -- your editor should be able to do it for you. I know from personal experience that Emacs and Xcode can do the whitespace stuff... [here's how to enable it in IntelliJ](https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file) (you're using IntelliJ, right?). I would be surprised if anyone was using an editor that didn't have the ability to do this stuff automatically. The fact that I only had to fix ~10 files out of ~2600 that the linter checked is a testament to the fact that most editors come configured to enforce the newline/whitespace rules like these out of the box.

So in that sense this linter is mainly to check that people have their editors set up correctly.

In terms of being subjective, I think these rules are pretty common ones in the wider programming world. These are in the Clojure Style Guide for example:

https://guide.clojure.style/#terminate-files-with-a-newline
https://guide.clojure.style/#no-trailing-whitespace
https://guide.clojure.style/#spaces

The main reason for having rules like these is that _not_ having them leads to unnecessary diffs when someone touches a file when _their_ editor is configured to clean the file according to those sorts of standard rules. If some random person submits a PR that adds a bunch of Windows-style `\r\n` newline endings or hard tabs or trailing spaces or whatever and then someone else touches that file to edit one line with an editor that fixes that stuff on save, they're potentially ending up with a 100-line diff when it should have been a 1-line diff. That alone is worth the price of entry for me

**Comment by camsaul** [comment]
RE the namespace linter:

How does it differ from how Calva thinks it should be sorted? It literally just sorts namespaces with a simple text sort... you could run your namespaces thru `sort` or `M-x sort-lines` or something like that and it would give you the same results (other than complaining about unused ones). [Clj-Kondo checks for this now too](https://github.com/clj-kondo/clj-kondo#features) and it doesn't differ from the namespace linter. (It doesn't enforce either prefix or flat declarations yet tho.)

If the namespace linter is really making things hard I can add a command to fix things automatically. I don't think it would be that hard

**Review by dpsutton — APPROVED** [review]

**Comment by robdaemon** [comment]
For the namespace linter, Calva says:

`[compojure.core :refer [DELETE GET POST PUT context defroutes]]`

and the linter says

`[compojure.core :refer [context defroutes DELETE GET POST PUT]]`

Any linter capable of failing a build for purely stylistic reasons should also be capable of automatically fixing said issues.

**Comment by camsaul** [comment]
@robdaemon fixing stuff automatically is definitely nice but would be a little tricky. I'm not 100% sure how to do it and preserve any comments in the `ns` form. Besides that it would be pretty easy tho.

I can also make lowercase vs. uppercase sorting an option

**Pull request merged**
