### PR TITLE
Remove icons from download menu

### PR DESCRIPTION
**Pull request by mazameli**
We only used these icons in one place, and they're a bit goofy looking. 

# Before

image

# After
image

### CODE REVIEW

**Review by kdoh — APPROVED** [review]
👍 💯

**Comment by mazameli** [comment]
Looks like I'll need to fix at least `e2e/support/helpers/e2e-downloads-helpers.js`, which has this in it:

```
const downloadClassName = `.Icon-${fileType}`;
  const endpoint = getEndpoint(
    fileType,
    questionId,
    publicUid,
    dashcardId,
    dashboardId,
  );
```

Any guidance, @iethree, or maybe @nemanjaglumac?

**Comment by iethree** [comment]
> Looks like I'll need to fix at least `e2e/support/helpers/e2e-downloads-helpers.js`, which has this in it:
> 
> ```
> const downloadClassName = `.Icon-${fileType}`;
>   const endpoint = getEndpoint(
>     fileType,
>     questionId,
>     publicUid,
>     dashcardId,
>     dashboardId,
>   );
> ```
> 
> Any guidance, @iethree, or maybe @nemanjaglumac?

I can update the tests to check icons instead of text 👍

**Comment by mazameli** [comment]
@iethree thank you!!

**Pull request merged**
