### PR TITLE
Filter pin map by drawing rectangle

### PR DESCRIPTION
**Pull request by tlrobinson**
Draw a rectangle on a pin map to filter by lat/lon

http://recordit.co/uITjEw9DOQ

### CODE REVIEW

**Comment by salsakran** [comment]
This is really sweet. 

What help do you need to get merged? The UX is reasonable for me, though perhaps @kdoh or @mazameli have thoughts on the matter.

**Comment by tlrobinson** [comment]
I'm not sure... I barely remember writing this at 1 AM, but the code looks reasonable to me. 

@mazameli and @kdoh UX feedback would be good.

A couple other things come to mind:

1. Currently we zoom to the level that fully contains all the points, however if the rect you draw doesn't exactly match a zoom level there will be a "margin" with no points. Unfortunately I don't think Leaflet supports non-integer zoom levels, except possibly with vector layers. Should we:
  a. just live with the "margin" of empty space?
  b. zoom in one additional level so the pins fill the screen?
2. Do we also want to auto-filter when zooming every N levels (mentioned in 4622), or maybe have a button to "filter by this viewport" or something?

**Comment by mazameli** [comment]
I agree that this is very cool. A couple things that could be smoothed out:
- Not in love with "Filter by rectangle" but I don't yet have something better
- I feel like it might be nice to have a `reset` button if you've filtered in this way to remove the filters and zoom you back out. It felt a little awkward to get back to the original state.
- I think we could polish the visual design of the floating helper text when in drawing mode. It's too narrow, and it's a little hard to see. And there maybe remains a question of whether or not we need it.
- The experience of drawing a bounding box around an area with no pins and getting the "no results!" screen feels weird. I would've expected to just be zoomed in to that area and not see any pins.
- If I hit `esc` while in drawing mode, it cancels me out of drawing mode (good), but then the filter button state remains `cancel filter`. It should change back to the default state.

Re: Tom's questions:
1. I think I'd take option B 'cause the margin feels a little weird. Is there a disadvantage to zooming in an additional level that I'm not thinking of?
2. I'm more inclined to auto-filter than to add another button.

**Comment by tlrobinson** [comment]
@mazameli regarding "Is there a disadvantage to zooming in an additional level that I'm not thinking of?" the disadvantage is some of the points may not be visible.

I've updated the PR with a couple small things:

1. removed the tooltip text, I think it's pretty self explanator
2. changed the button copy to "Draw box to filter"
3. zoom an extra level in so there's no empty space surrounding the filtered area

**Review by attekei — CHANGES_REQUESTED** [review]
I like how this works & code looks good. Could the buttons have a little bigger text / better font formatting? This is how they look like for me:
screen shot 2017-05-04 at 10 13 36

**Review by mazameli — COMMENTED** [review]
Overall seems solid enough and mergeable to me. In a future hypothetical polish PR, I'd love to see these addressed:

-The experience of drawing a bounding box around an area with no pins and getting the "no results!" screen feels weird. I would've expected to just be zoomed in to that area and not see any pins.
- If I hit esc while in drawing mode, it cancels me out of drawing mode (good), but then the filter button state remains cancel filter. It should change back to the default state.
- It would be nice to have a `reset view` button to clear all the zoom filters

**Review by attekei — APPROVED** [review]

**Comment by attekei** [comment]
yup my text rendering concerns are non-blocking too

**Review by kdoh — APPROVED** [review]

**Pull request merged**
