### PR TITLE
Manual Backport #35485

### PR DESCRIPTION
**Pull request by sansolovyov**
Backported #35485

### CODE REVIEW

**Review by calherries — APPROVED** [review]
Can you explain why this should be backported?

**Review by calherries — COMMENTED** [review]
Can you explain why this should be backported?

**Review by calherries — CHANGES_REQUESTED** [review]
Didn't mean to approve

**Comment by piranha** [comment]
I thought that the approach is "backport everything except for big features/breaking changes", ain't it?

**Comment by calherries** [comment]
I think the approach is "backport bug fixes" (unless it's really difficult). Is serialization order broken on 47, or was this just a regression on master? The issue doesn't specify

**Comment by piranha** [comment]
Makes sense, on the other hand, it's marked as a "bug". @luizarakaki what do you think?

**Comment by calherries** [comment]
I'm asking whether the bug exists on the 47 branch. The bug label doesn't tell you

**Comment by piranha** [comment]
The bug exists since e19ceeb494aaae52ab1ca1e88c7f0d42c53e60a7

**Review by calherries — APPROVED** [review]

**Comment by calherries** [comment]
Ah okay, thanks! Just being sure

**Comment by nemanjaglumac** [comment]
Keep one thing in mind.
The originally closed issue has the milestone 48.0 assigned to it! If you think this should be backported to the 47 branch, change the milestone to the appropriate upcoming 47.X milestone.

**Comment by luizarakaki** [comment]
I don't think we should backport this. It significantly changes the product behavior. We don't want to change all the Serdes yamls in minor versions.

**Pull request closed without merging**
