### PR TITLE
feat: Integrate Uffizzi - Preview Environment for PRs

### PR DESCRIPTION
**Pull request by ShrutiC-git**
Hi, this is a PR addressing https://github.com/metabase/metabase/issues/25958

### What does this PR do?
This PR is adding support for **preview environments for every PR opened against Metabase** using [Uffizzi ](https://uffizzi.com/). The PR is extending Metabase's GHA workflows to **create ephemeral preview environments so each PR and its impact can be tested easily and quickly 🚀**. The URL of the preview environment is posted as a comment on the PR for easy access. 

### Testing the PR
A demo of how these Preview Environments work:

[This is a PR on my personal fork of Metabase](https://github.com/ShrutiC-git/metabase/pull/3) from a feature branch to the main branch. A new [comment](https://github.com/ShrutiC-git/metabase/pull/3#issuecomment-1321743708) was posted on the PR which lists the [preview-environment-URL](https://app.uffizzi.com/github.com/ShrutiC-git/metabase/pull/3) where the Metabase console with code changes from the PR is available for viewing and testing. 

This PR also has an instance of a seeded Postgres DB which will allow the admins to see how adding and testing integrations can be done easily. 

### How Does This PR Help?
We believe that an open-source tool like Metabase, with significantly high rates of commits/week, can greatly benefit from preview environments for PRs to fasten delivery speed and help the maintainers/contributors in the code-review process. Uffizzi is purpose-built for the task of previewing PRs and it integrates with existing workflow to deploy preview environments in the background without any manual steps for maintainers or contributors. 

We are an open-source project and we would be delighted to be Metabase's solution for preview environments. We are very open to suggestions and feedback from the community to make Uffizzi a better product.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

cc @waveywaves

### CODE REVIEW

**Comment by ShrutiC-git** [comment]
hi @nemanjaglumac 
reaching out to you to see what your thoughts are re preview environments. I'll greatly appreciate any feedback/suggestions on how we could make this helpful for Metabase.

**Comment by jpthurman** [comment]
Hi @nemanjaglumac and @ariya - friendly ping on this PR.  Would preview environments for every PR be valuable for your project?   Here's a few [projects ](https://www.notion.so/uffizzi/bd10b5646a76470ab21e5793c3cd2ca6?v=f56d96c0fe75424fb56111aa2bfce4fb) for reference that are currently using Uffizzi environments

We'll close this out in about a week if nothing heard.

**Comment by nemanjaglumac** [comment]
Hi @ShrutiC-git and @jpthurman 
We already partially address that need internally and are not interested in pursuing 3rd party solutions for now.

Thank you for the effort.

**Comment by jpthurman** [comment]
Thanks for letting us know

**Pull request closed without merging**
