### PR TITLE
Update crate-jdbc to 2.1.1

### PR DESCRIPTION
**Pull request by memcmp**
Update crate-jdbc to 2.1.1 which uses the postgres wire protocol instead of the proprietary transport protocol.

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by salsakran** [comment]
@camsaul + @bogensberger is this ready to merge?

**Comment by camsaul** [comment]
@salsakran code looks good, I haven't manually verified the tests but if you want to do that then the only thing left is to fix the merge conflict

**Comment by salsakran** [comment]
getting an error --
```

E: Version '0.57.3-1~trusty' for 'crate' was not found
sed: can't read /etc/init/crate.conf: No such file or directory
tee: /etc/crate/crate.yml: No such file or directory
psql.port: 5200
tee: /etc/crate/crate.yml: No such file or directory
psql.enabled: true
crate: unrecognized service
========================================
status=1 time=11 command=install-crate
========================================

./bin/ci returned exit code 1
```

**Comment by bogensberger** [comment]
@salsakran Thanks for the hint. I updated the PR to use the latest stable version for the tests. This should solve the problem.

**Comment by camsaul** [comment]
@bogensberger if the version was already no longer available a week or so after you submitted the PR are we going to have to update the version number every week to keep our tests from breaking?

**Comment by bogensberger** [comment]
@camsaul as i removed the version number in my last commit, always the latest CrateDB version will be used. So there is no need to update the version number every week.

**Comment by camsaul** [comment]
Thanks @bogensberger.

@salsakran do you want to try this again :D

**Comment by camsaul** [comment]
@salsakran we should merge this now that old version has officially broken our CI 😄  do you want to try this again? :D

**Comment by salsakran** [comment]
👍

**Pull request merged**
