### PR TITLE
Unify chart axis tick and label styles

### PR DESCRIPTION
**Pull request by kdoh**

### CODE REVIEW

**Comment by mazameli** [comment]
Definitely better than before, but it feels slightly off to me to have the axis labels and the tick marks be exactly the same. I think we might've had the hierarchy backwards when the axis label was fainter than the tick marks, because it's important context to know for example _which_ time field is being used. I think this will be even more the case if and when we hide the query builder, and it's already the case with SQL questions.

What do you think of the labels if they're 14px and #727479 for the fill to match the text in the time range drop downs?

screen shot 2017-10-11 at 11 12 05 am

**Comment by salsakran** [comment]
Agree with maz re: relative weight of the axis label vs tick marks. Let's go further down that train and see what it looks like?

**Comment by salsakran** [comment]
looks good 👍 
a bit of extra padding between the y-axis label and the tick values would be good, but we should definitely merge this regardless.

**Comment by kdoh** [comment]
@salsakran Agreed. Scooting the labels around actually happens at the charting library level not CSS so we should do that separately.

**Pull request merged**
