### PR TITLE
JWT embedding for Cards & Dashboards

### LINKED ISSUE #1380: Allow embedding of cards in other websites
Right now a card can only be used in a dashboard. It would be useful to be able to embed a card in blogs, etc.

### PR DESCRIPTION
**Pull request by camsaul**
Various endpoints that use [JSON web tokens](https://jwt.io/introduction/) to fetch Cards and Dashboards. The endpoints are basically the same as the ones in `api/public`, and differ only in the way they are authorized.

To use these endpoints:

1.  Set the `embedding-secret-key` Setting to a hexadecimal-encoded 256-bit key (i.e., a 64-character string) via the normal channels (`PUT /api/setting/embedding-secret-key`).
     You can use `/api/util/random_token` to get a cryptographically-secure value for this.
2.  Sign/base-64 encode a JSON Web Token using the secret key and pass it along in the appropriate place in the URLs.

Tokens have some combination of the following fields:

```clojure
{:resource {:card      <card-id>
            :dashboard <dashboard-id>}
 :params   <params>}
```

Refer to documentation for various endpoints for which fields to use.

Not sure how this looks in JavaScript but in Clojure it looks like

```clojure
(jwt/sign {:resource {:card 1}}
  "f381aa4c582d8524444ea86d7e2f6738fad0d0f2ad0e736dffe64f6e446b16a2")
;; -> "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJjYXJkIjoxfX0.QZrKG48NgP81ewEi1ZFkEoetaw2GuYTD07OzFTi3Bx8"
```

Then a request looks like

```
http://localhost:3000/api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJjYXJkIjoxfX0.QZrKG48NgP81ewEi1ZFkEoetaw2GuYTD07OzFTi3Bx8
```

Calling that gives you the publically-viewable info for Card 1.

Implements/resolves #1380, #3366, #4291, #4300

### TODO Frontend:

* [ ] improve sample code + add other languages

### TODO UX:
* [ ] more embeddable styles

### CODE REVIEW

**Comment by camsaul** [comment]
Tests and things like that are still pending

**Comment by camsaul** [comment]
The API endpoints support setting the `embedding_params` for Cards and Dashboards now.

The entire thing should be a map of `param-name` -> `true`/`false`/`value`, e.g.

```clojure
{:param true}           ; param that can be used and changed
{:param false}          ; param that cannot be used
{:param {:value "abc"}} ; param locked to a certain value
```

These can be set via the endpoints now (admin-only) but wiring up the embedding code to check them is still pending.

**Comment by camsaul** [comment]
Ok, I changed the format to

```clojure
{:param "disabled"|"enabled"|"locked"}
```

**Comment by salsakran** [comment]
getting a token error when I :
1. go to a card, click share (result show correctly)
2. click to code, click “publish”
3. go back to “preview” and it errors out with that message
this results in an invalid `iat` parameter in the jwt token somehow. error message as follows:
```
{:type :validation,
 :cause :iat,
 :message "Token is from the future (1487385029)",
 :stacktrace
 ["util.embed$unsign.invokeStatic(embed.clj:64)"
  "util.embed$unsign.invoke(embed.clj:58)"
  "api.preview_embed$fn__40650$fn__40651.invoke(preview_embed.clj:23)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:222)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:219)"
  "api.preview_embed$fn__40650.invokeStatic(preview_embed.clj:20)"
  "api.preview_embed$fn__40650.invoke(preview_embed.clj:20)"
  "middleware$enforce_authentication$fn__36745.invoke(middleware.clj:117)"
  "api.routes$fn__41415.invokeStatic(routes.clj:61)"
  "api.routes$fn__41415.invoke(routes.clj:61)"
  "routes$fn__41469.invokeStatic(routes.clj:43)"
  "routes$fn__41469.invoke(routes.clj:43)"
  "middleware$log_api_call$fn__36851$fn__36853.invoke(middleware.clj:312)"
  "middleware$log_api_call$fn__36851.invoke(middleware.clj:311)"
  "middleware$add_security_headers$fn__36794.invoke(middleware.clj:244)"
  "middleware$bind_current_user$fn__36749.invoke(middleware.clj:137)"]}
```
if I then go to "code" and back to "preview" it works.

**Comment by tlrobinson** [comment]
A couple security related things we should do:

1. Whitelist known good `alg`s, unless we're confident our JWT library does so and will continue to do so in he future (also ensure all the common JWT libraries use one of the whitelisted ones by default) https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid
2. Include default `exp` (and `nbf`?) in the code samples and docs. 1 hour default?
3. Require `exp`  (and `nbf`?) be present in the token?

**Comment by salsakran** [comment]
following up on (5), have we instrumented any of this?

**Comment by neoecos** [comment]
Hi, How this works ? How can I embed cards and dashboards in other site.

**Comment by mazameli** [comment]
@neoecos, documentation for [simple embedding is here](http://www.metabase.com/docs/v0.23.0/operations-guide/running-metabase-on-elastic-beanstalk.html#deploying-new-versions-of-metabase), and [advanced application embedding here](http://www.metabase.com/docs/latest/administration-guide/13-embedding.html).

If you need further help, please feel free to start a new thread on our [discussion board](http://discourse.metabase.com/).

**Pull request merged**
