### PR TITLE
Add container build for metabase-enterprise-head

### PR DESCRIPTION
**Pull request by dragonsahead**
This PR should be adding the enterprise-head container to our dockerhub, so I'll need @camsaul to create the public repository.

Is there something I might be missing?

Solves https://github.com/metabase/metabase/issues/14893

### CODE REVIEW

**Comment by camsaul** [comment]
I don't know if this `build_image.sh` script is actually used anywhere anymore -- we might be able to remove it entirely. The DockerHub builds are triggered whenever there's a commit to `master` or a release branch (IIRC) and then use the multi-stage `Dockerfile` in the root of the project repo to build the image.

**Comment by paoliniluis** [comment]
Oops, sorry then, I thought that the process was commanded by that script. I'm lost in this case :(

**Comment by camsaul** [comment]
I've looked thru things and this script is definitely just orphaned from the old build scripts. So we can go ahead and delete it.

DockerHub is just set up to build using the multi-stage Docker file at `./Dockerfile`. If you want to tweak that Dockerfile to build EE if you pass it an appropriate environment variable, I can add a hook to DockerHub for it

**Review by camsaul — CHANGES_REQUESTED** [review]
`./bin/docker/build_image.sh` is actually not used anymore -- you can delete it. We need to tweak `./Dockerfile` to build EE by passing an env var, and then we can set DockerHub up to do automated EE builds

**Comment by paoliniluis** [comment]
Done @camsaul, thanks for the tip. Give a try to the new Dockerfile by doing `DOCKER_BUILDKIT=1 docker build . --build-arg MB_VERSION=ee`.

If you don't pass args it will default to oss :dancers: 

BTW, I included the same cert changes that I did in https://github.com/metabase/metabase/pull/15025. For some reason we were including fixed certs in this one by copying them from a previous container

**Review by camsaul — APPROVED** [review]
LGTM. I don't know what's going on with CircleCI but it looks like it passed earlier so I'll go ahead and merge. I'll set up DockerHub to do a head build in a bit

**Pull request merged**
