### PR TITLE
Remove `redux-form` from setup

### PR DESCRIPTION
**Pull request by kulyk**
Part of #22372

Removes explicit `redux-form` usage from the setup flow's database step. It uses `getValues` selector to get the `engine` value for `DatabaseHelpCard` component

### CODE REVIEW

**Comment by ranquild** [comment]
@kulyk it is draft, should we review it?

**Comment by kulyk** [comment]
> it is draft, should we review it?

@ranquild not yet, I want to fix the failing tests first and then reopen it once the CI is green. Thanks for checking!

**Comment by kulyk** [comment]
@ranquild it's fixed now, would appreciate it if you can take a look! Had to move the engine value to the setup's Redux state: realized we need to keep it out of the `DatabaseStep`, so the help card can animate nicely

**Review by ranquild — APPROVED** [review]
Works great!

**Pull request merged**
