### PR TITLE
Repro for #12872: `Between Dates` filter (in)consistency

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
READY

### What does this PR accomplish?
- reproduces #12872 

### How to test this manually?
- `yarn test-cypress-open`
- `frontend/test/metabase/scenarios/question/filter.cy.spec.js`
- replace `it.skip()` with `it.only()` to test it in isolation
- the test should fail until the related issue is fixed

### Additional notes:
- once the issue is fixed, please remove the `.skip` part (unskip the test completely)
- make sure test is passing and
- merge it together with the fix

### CODE REVIEW

**Review by flamber — CHANGES_REQUESTED** [review]
This will always fail, since the query generated is wrong, which is the issue.

**Comment by nemanjaglumac** [comment]
> This will always fail, since the query generated is wrong, which is the issue.

In that case I completely misunderstood. I thought you included SQL as an alternative way to reproduce this issue. Ouch!
I'll rewrite it ASAP.

**Comment by nemanjaglumac** [comment]
I'll rebase this once #13632 is merged.

**Review by flamber — APPROVED** [review]
That should work. I don't like the id references, since I don't know if those can be guaranteed or if they might change if the sync process has a minor change or race-condition, and because it makes it a bit harder to read the test. But if the id is static, then I don't see a problem.

**Review by nemanjaglumac — COMMENTED** [review]
> That should work. I don't like the id references, since I don't know if those can be guaranteed or if they might change if the sync process has a minor change or race-condition, and because it makes it a bit harder to read the test. But if the id is static, then I don't see a problem.

IDs as in `questionId` or field IDs?

**Review by flamber — COMMENTED** [review]
So now `PRODUCTS.CREATED_AT` will translate into an number automatically?
I generally find MBQL difficult to read.
If you test with `2019-04-15`-`2019-04-16` you should get 1 row in current version.

**Comment by nemanjaglumac** [comment]
> So now `PRODUCTS.CREATED_AT` will translate into an number automatically?

It was translated into a number automatically even before. For some reason, it was working with the wrong syntax for non-joined table. I was using simply `[PRODUCTS.CREATED_AT]` instead of `["field-id", PRODUCTS.CREATED_AT]`. That didn't work for joined table, but with the correct syntax it works as it should for both joined and non-joined.

> If you test with `2019-04-15`-`2019-04-16` you should get 1 row in current version.

Yes. I confirm.

**Pull request merged**
