### PR TITLE
Handle long names better

### LINKED ISSUE #9161: UI - Group By for datetime with long names, can't change period
- Your browser and the version: Chrome v70.0.3538.110 (Official Build) (64-bit) (but also Firefox)
- Your operating system: Windows 7
- Your databases: SQL Server
- Metabase version: v0.30.3
- Metabase hosting environment: jar file, Windows server
- Metabase internal database: Postgres

*Repeatable steps to reproduce the issue*
- Create a datetime column with a long name, for me about 36 chars the trick
- Start a new question with that field
- Add a "Group By" for that field
- Try to change it to "by month" but the entire "by ..." button on the far right is not visible so not possible
image

Would probably be sufficient if the "by ..." button simply right aligned to the end of the field name, even if it obscures the field name itself. I see the "by ..." button gets "squashed" as the field name grows, maybe it could be fixed and the field name could get squashed?

Instead of this:
image

Maybe do this:
image

I assume it's the same with the binning on number too but have not verified.

Thanks

### LINKED ISSUE #9616: Filter button option (is, contains, equal to..) hidden by a "Data" name too long
The filter button in the "Filtered by" UI does not appear if the "Data" name is too long :
image

## Possible CSS adjustements
I have tested out some CSS adjustments which seem to work :
```
.AdminSelect {
    background-color: #FFF;
}

FilterPopover div {
    max-width: none;
}

h3.ml1 {
    max-width: 150px;
    overflow: hidden;
}
```

## Environment

- Chrome 72.0
- Mac OS 10
- Metabase version: 0.30.3
- Metabase hosting environment: (Docker)

## Related issues
https://github.com/metabase/metabase/issues/6011 Not exactly the same though

### PR DESCRIPTION
**Pull request by flamber**
Fixes #9161 
Fixes #9616
~~Not currently #10286~~
Also fixes various other places, where I couldn't find an open issue.

Screencast

### CODE REVIEW

**Comment by RMMSecurity** [comment]
YES! I kept meaning to file an issue for this. It's particularly a problem as you start nesting saved questions with them. Not even a tooltip could tell you which one you were looking at so you had to start selecting them at random to actually see the full name.

**Comment by mazameli** [comment]
@kdoh wdyt about this? It definitely fixes cases where you can't get at filter operators or granularity/binning options for breakout fields when the column name is super long, like this:

image

The fixes in this PR just lend themselves to some funny looking popovers, like this:

image

**Comment by flamber** [comment]
Would it be better if I changed the entire PR to use ellipsis with a hover tooltip similar to Collection list?
And fix the tooltip problem too of course - just noticed it now.
Screenshot_00000
There's a couple of downsides with ellipsis too. It would only be visible using a mouse and would probably be a little distracting on the QB dropdown, since it's already packed with information.

**Comment by mazameli** [comment]
I don't think we want to go the ellipses route if we can avoid it (causes problems for mobile and can make the UI feel twitchy with too many on-hover effects). I think we just might need to have a more thought-through approach for how/when exactly to wrap these kinds of labels, so that e.g. we don't cause inputs in popovers to get crazy long.

Appreciate you starting this fix, @flamber, and let's see if we can get it over the finish line. Just give me and @kdoh a little bit to see if we can offer some suggestions.

**Review by kdoh — CHANGES_REQUESTED** [review]
Regarding the popover situation I think for the filter header example above (or other similar situations in popovers) adding the `flex-wrap` class on the parent flex element to make the table and field name stack vertically when they get crazy long should prevent them from getting too crazy and squishing oddly. For filters I think you'd want to [add that here](https://github.com/metabase/metabase/pull/9711/files#diff-53c55aaf7a8273268bb6a50cfb9feac2R346) I think.

**Comment by flamber** [comment]
Added `flex-wrap` as @kdoh pointed out - it looks better:
image
And fixed a few other places too (start, x-ray, data model), alignment, wrong text and missing i18n.

I can see CI is failing on some network issue, so I'll ignore that, but can someone help me understand the conflicts? Is it because my checkout is fairly old, so I need to rebase with master? (not a Git champ :face_with_head_bandage:)

Current outstanding, which I don't know if it should be part of this PR or a new?

- [ ] Objects in QB with very long name (or multiple objects, there's a couple of issues open on this), but this PR was started before I knew about Notebook-mode.
- [ ] Tooltip doesn't wrap (also an issue in QB when hovering :information_source: icon of Metric/Segment)
- [ ] Several of the modals (like Move question) will trigger h-scroll, but is blank if scroll and focused
- [ ] Table Visualization > Column Formatting > select dropdown options
- [ ] Custom Fields/Expressions > select dropdown options
- [ ] Admin > Data Model > database select dropdown options
- [ ] Admin > Data Model > long breadcumb path triggers h-scroll (on sub pages :gear:)
- [ ] Admin > Permissions > having difficult with fixing it because of positioning
- [ ] Pulses (doing this on local dev, so haven't tested any pulses)
- [ ] Reference (haven't checked any of `/reference`)

**Comment by kdoh** [comment]
@flamber From my perspective I'd lean towards getting the merge conflicts fixed up and this initial set of changes merged in and then follow up with other spots in chunks as it makes sense. Making sure we do a good job with dynamic text length is always going to be an ongoing battle. I think you should be able to just merge or rebase on top of master and be good, none of the conflicting files seem to have anything more than some formatting differences going on.

I also wouldn't sweat worrying about the upcoming notebook mode changes since most of your changes here will still be relevant in terms of dealing with long names at least in the near term.

**Comment by flamber** [comment]
@kdoh Thanks for the inputs Kyle!
I will open a new PR for the outstanding issues, once this gets merged.

**Review by kdoh — APPROVED** [review]

**Comment by mazameli** [comment]
Sorry we haven't yet merged this, @flamber! I was just giving it a final review when I noticed two things.

Looks like these column selector dropdowns in the chart settings modal aren't behaving correctly (or maybe they were missed?):
image

The bottom border of these inputs on number filters don't seem to extend the full width of the popover. (This might not be an issue because I think in a conversation with @kdoh we'd talked about swapping that style of input out for traditional inputs in `notebook-mode`, but I'd need him to confirm.)

Screen Shot 2019-07-15 at 4 18 05 PM

Screen Shot 2019-07-15 at 4 18 10 PM

**Comment by flamber** [comment]
@mazameli No worries, I know you're busy :-)
About the column settings dropdown - I'm pretty sure I already fixed that, but I think it's actually the commit that I reverted (https://github.com/metabase/metabase/pull/9711/commits/224ce016817679ef31bde2a2f5c46902cfedefb1), since I didn't understand the [test fail](https://circleci.com/gh/metabase/metabase/77954) (at that point in time).
Should I have that fixed before this is merged? Currently means #10286 will not be fixed.

**Comment by mazameli** [comment]
@flamber Got it. Since that dropdown thing is not a regression, and since this PR fixes a lot of other cases, I'm okay merging this without that one item being brought into scope. I'll make a note on #10286 about why this PR couldn't/didn't fix it. Thanks so much!

**Pull request merged**
