### PR TITLE
Update iframeResizer.js

### PR DESCRIPTION
**Pull request by alxnddr**
https://github.com/metabase/metabase/pull/16929 within Metabase organization in order to run CI checks

### CODE REVIEW

**Comment by rlotun** [comment]
apparently we're also using it here: https://github.com/metabase/metabase/blob/master/resources/frontend_client/app/iframeResizer.js

**Comment by rlotun** [comment]
ah, that's updated- will merge as both @alxnddr and @paoliniluis tested this

**Review by rlotun — APPROVED** [review]

**Comment by mariovalney** [comment]
Hi! Would you mind to explain what means "within Metabase organization"?
Did I forget to do something in last PR?

Thank you for merging. We already using the new version 😃

**Comment by paoliniluis** [comment]
@mariovalney thanks for your PR, as we need to run changes through our CI, we need to wrap external PR's as it would have been done by both internal Metabase devs and external contributors, as the CI's won't run any tests if it comes from people outside the Metabase github organization

**Comment by mariovalney** [comment]
Oooh. Interesting.
Thanks for taking time to anwer.

**Comment by paoliniluis** [comment]
> Oooh. Interesting.
> Thanks for taking time to anwer.

Thank you for contributing to the project

**Pull request merged**
