### PR TITLE
Only show object detail for single rows

### LINKED ISSUE #11162: Filter Equal with multiple IDs of Entity Key only shows Object Details of single ID
**Describe the bug**
When filtering an Entity Key (PK) using "Equal to" and comma separating to select multiple IDs, the result only shows Object Details of a single ID.
Works fine for numbers (like Orders.Quantity).
Also works fine when filtering Foreign Key (FK), but filter selection is different - it's called "Is".

**Logs**
I don't see any logs or console errors. The request params and response includes all the IDs, so this must be some frontend code not doing it's thing.

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Filter by "ID" with "Equal to"
3. Type `5` comma `8` comma `15`, click "Add filter"
4. Only shows Object Details for ID `5`

**Expected behavior**
Show table result with filtered IDs. I would expect similar behavior as filtering Foreign Keys.

**Information about your Metabase Installation:**
Metabase 0.33.4 and `release-33.x` on Firefox 69

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #11162

The issue was that we displayed object details whenever using a PK filter. I refined that to PK filters that use the "=" operator and have one argument.

Separate from that main fix, I updated the primary key filter options so that they match foreign keys. Does that make sense to do?

### CODE REVIEW

**Comment by salsakran** [comment]
I dunno if this is the place to have this conversation, but I think an object detail page should be a separate route + component and not a special case of the query builder having specific filters. I think this sort of over-loading is making the QB more complicated than it needs to be. 

Also, most of the chrome of the QB actively detracts from the UX of the object detail page. Eg, why should I see a notebook mode button?

**Comment by paulrosenzweig** [comment]
> I think an object detail page should be a separate route + component

Would that mean a separate visualization? e.g. table vs object view?

**Comment by flamber** [comment]
This partially fixes #9447 too.

**Review by kdoh — APPROVED** [review]
> I updated the primary key filter options so that they match foreign keys. Does that make sense to do?
👍 I think this makes sense. 

To @salsakran's point I do think we need to revisit how we show one record and how that interacts with the rest of the UI, but since this primarily addresses a bug we should ship this regardless of where that conversation takes us.

**Pull request merged**
