### PR TITLE
beanstalk instructions for the new UI

### LINKED ISSUE #5588: Update elastic beanstalk installation instructions
The UI has been redesigned, and we should update the list of steps.

### PR DESCRIPTION
**Pull request by salsakran**
fixes #5588

### CODE REVIEW

**Review by senior — APPROVED** [review]
👍

**Review by mazameli — COMMENTED** [review]
Seems good. The only thing that struck me as funny were the screenshots with error messages or red highlighting. Not sure if that's avoidable, but it makes it look like things are going wrong in those two screenshots.

**Comment by salsakran** [comment]
that's actually the way it looks out of the box. we can't pre-fill the db user and password, and the form validation complains.

**Comment by salsakran** [comment]
maybe we should call that out?

**Pull request merged**
