### PR TITLE
Change funnel and pie charts to be a sensible visualization type if data has at least two columns

### LINKED ISSUE #33113: Pie and funnel charts switch to a table if a new column is added to the query
### Describe the bug

Pie charts and Funnel charts both are “sensible” if and only if the number of columns in the data is exactly 2. If there are more than two columns, the charts types are no longer “sensible”. This means that if the display type is pie chart and there are two columns in the data, and then later the query changes so the data has more than 2 columns, the pie chart no longer is "sensible" and the chart will switch back to a table chart, even if the chart is perfectly fine.

### To Reproduce

1. Create a new query with two columns, and make a pie or funnel chart. Save the question
2. Add a third column to the query and visualize the results. The chart type will have switched to a table.

Demo here:
https://www.loom.com/share/881d0e85bb0d442eb4b97ec2e06e167f?sid=b203a356-dcfc-4e43-bf71-b13e0f795107

### Expected behavior

Pie and funnel charts shouldn't switch to a different chart type automatically when data changes from 2 columns to more than 2 columns. They should only switch when the data changes from 2+ columns to 1 column.

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

low

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calherries**
Resolves #33113

### CODE REVIEW

**Comment by calherries** [comment]
@metabase/core-frontend-42 I'm putting this up for review knowing there are no tests, because I'm hoping you can tell me what tests there should be.

**Comment by calherries** [comment]
@metabase/core-frontend-pixel-police I'm putting this up for review knowing there are no tests, because I'm hoping you can tell me what kind of tests to write for this.

**Comment by ranquild** [comment]
@calherries I'd write a e2e repro

**Comment by JesseSDevaney** [comment]
I mentioned the below quote in the issue related to this fix, but wanted to include it here for clarity as well.
- https://github.com/metabase/metabase/issues/33113

> Also, I think this fix requires more than allowing data with 2 or more columns to be plotted. As the data is not automatically aggregated like other charts, it can lead to some non-sensible charts - multiple slices represent the same category (e.g.if data is `grouped by`).
> 
> **No Aggregation in Pie Charts**
> 
> does-not-aggregate-in-pie-charts

**Review by alxnddr — APPROVED** [review]
I think it makes sense, let's just confirm with the design if this behavior is desired.

@mazameli what do you think about making funnels and pie charts sensible even on large number of column tabels?

**Comment by mazameli** [comment]
Yeah, I think this feels friendlier, though can we take this one step further, and if you pick Pie or Funnel, can we go ahead and just pick a measure and a dimension/step column for you instead of being passive aggressive and displaying this sad unselected state? Sure, we might get it wrong, but then the user can just change it, which is no worse than the current behavior, and has the upside of possibly being right, as well as giving you the immediate gratification of showing you a real visualization.

image

**Pull request closed without merging**
