### PR TITLE
SQL Server Driver [WIP]

### PR DESCRIPTION
**Pull request by camsaul**
Supersedes #1396

### CODE REVIEW

**Comment by camsaul** [comment]
why did you merge this into master????? It's labeled [WIP] and it's not passing tests???

**Comment by agilliland** [comment]
i didn't.  i merged the other one.

**Comment by camsaul** [comment]
screen shot 2015-11-03 at 1 44 50 pm

**Comment by agilliland** [comment]
i think this somehow got linked to the PR about schema support.  that's the one i merged.  in any case, lets back it out.

**Comment by camsaul** [comment]
Weird. It looks like the relevant files didn't actually get merged, GitHub is just tripping. I don't think we need to do anything

**Comment by camsaul** [comment]
I'll just submit a new PR

**Comment by agilliland** [comment]
Cool.  That was definitely weird.

**Pull request merged**
