### PR TITLE
Add new executors in CircleCI

### LINKED ISSUE #15709: Dependency caching no longer works on CI
After we switched to the new CI docker images in #15201, the backend and frontend dep caches no longer work. Our CI config attempts to cache things assuming `~/` is `/home/circleci` (it looks like it's actually `/root` in the new CI image. We can change the paths in the CircleCI config, but this doesn't work if we use a mix of CircleCI Docker images for Java 8/16 and Metabase CI images.

We should change the Metabase CI images to use `/home/circleci`, or create versions of the Metabase CI images for Java 8 and Java 16 

cc @paoliniluis

### PR DESCRIPTION
**Pull request by dragonsahead**
Let me tell you the story of trying to use a 100% alpine based CI which finished with this PR:
1) we had our alpine based builder which was using a pinned down docker image, this ended up persisting BE and FE cache into a /root/ folder and CircleCI based images could not get this cache as these images work on the /home/circleci folder, and it even returned errors since you can't persist in the root folder in a container where you're not root.
2) also, you can't make alpine based containers for cypress, since you need packages that are glib-based and not musl based (https://docs.cypress.io/guides/getting-started/installing-cypress), so the only option was to build our container from scratch (debian based + node + browsers) or use the one that is cypress based (which we will have to add layers as they don't have java installed)
3) at this point I ended up adding a circleci user to our own containers so everything can be cached to that folder and then the circleci based containers that use cypress can pull this cache, but this ended up in permission errors which I couldn't debug (java permission errors that never happen locally but happen in CircleCI for unknown reasons)
4) I ended up rebuilding a debian buster circleci based image with latest leinengen + latest LTS node + clojure cli tools, which is a sub-optimal solution but this should accelerate everything because of caching.

The final solution should be to fix the permission errors in our custom builder so we used that image along all building process + try to build a debian based cypress image as well to be agnostic of the CI

### CODE REVIEW

**Comment by ariya** [comment]
@paoliniluis It wasn't clear to me, which version of Node.js is being used here?

**Comment by paoliniluis** [comment]
> @paoliniluis It wasn't clear to me, which version of Node.js is being used here?

14

**Review by camsaul — APPROVED** [review]
WFM

**Comment by paoliniluis** [comment]
I'm going to close this as it's moving towards new executors in https://github.com/metabase/metabase/pull/16749

**Pull request closed without merging**
