### PR TITLE
xrays: Add smart-row visualization option

### PR DESCRIPTION
**Pull request by sbelak**
Adds `smart-row` as a visualiziation option with the following semantics: if cardinality of breakout field is <= `smart-row-table-threshold`, display as row, else as table. This removes a hugely unneeded coupling where if you wanted to display a category as a row chart you had to do 2 bindings and 2 cards to work around cardinality cap of our row visualization. Result -100 loc of heuristics. 

Open questions:
* is smart-row a good name?
* should this be the default behaviour for all row-charts defined in xrays?

TODO:
* [x] Add mini barcharts to table
Screenshot 2019-03-29 18 38 08

### CODE REVIEW

**Comment by sbelak** [comment]
I'm more and more convinced this is how all row charts defined in xrays should behave

**Comment by RobertLowe** [comment]
Nice work. 

Yea, presently the row-chart just feels like a sideways bar chart, perhaps it should of just been an option there?

**Comment by mazameli** [comment]
I'm a 👍 on using these for high cardinality results. But I also wanted to call out this question you asked:

> Should this be the default behaviour for all row-charts defined in xrays?

My hunch is yes. I.e., your screenshot example would look cleaner if they all were tables I think. One other idea: if we use a `smart-row-chart` for _one_ of the results in a given section, could the x-ray know that and use that style for any other row charts in that section as well?

**Comment by sbelak** [comment]
I meant default as is: there should only be `rows` value in the heuristic, so you'd never have to explicitly pick between using `rows` or `smart-rows` (ie. `rows` implies/always is `smart-rows`)

It shouldn't be too hard to downgrade all the charts in a group to table if one has to be.

**Review by mazameli — APPROVED** [review]

**Pull request merged**
