### PR TITLE
Create metabase-h2-backup.sh

### PR DESCRIPTION
**Pull request by lwqcz**
I have found no possibility to do online H2 database backups so I have done this primitive script to do offline backup to SQL, compress it and upload to backup-server. This script is ment to be run by CRON and it has requirements of correctly configured /etc/ssh/ssh_config Host part, /etc/hosts file.
And as lat but not least - this script works for me, but for others can be OK or some kind of inspiration ONLY.

### CODE REVIEW

**Comment by salsakran** [comment]
hello @lwqcz ! Thank you for your contribution. It seems like you're running metabase as a service but we don't provide a standard way to do that in our distribution. Could you bundle that into this PR?

There will be other style comments as well, but as-is we can't accept a PR that presumes a means of deployment we don't provide. Also, have you signed the CLA? If not, we can't accept this.

**Review by salsakran — CHANGES_REQUESTED** [review]
Needs CLA + service setup at a minimum

**Comment by lwqcz** [comment]
Hi @salsakran ! I've signed your CLA and yes I can provide scripts to run Metabase *.jar file as a service. Did you mean that? Can you send me a link where can I find documentation how Metabase is run as part of Docker and other solution? I have no time and hardware to test it however. (I mean another approaches than *.jar service way). Therefore, would you accept my scripts as part of that approach only?

BTW: I hoped that this my primitive script will be useful for some one or maybe some kind of inspiration for some others, therefore it can be a part of documentation or extra script or so... Or am I wrong?

**Comment by jornh** [comment]
@lwqcz the Operations Guide has a section with a few ways to run including on Debian as a service (but I guess it quite easily adapts to other Linux flavors), so maybe add to that - to limit variations that need to be maintained? Plus there’s Docker and a bunch of clouds: 
https://metabase.com/docs/latest/operations-guide/start.html#installing-and-running-metabase

The Debian instructions btw has an open PR: https://github.com/metabase/metabase/pull/7858

**Comment by salsakran** [comment]
closing since this is a little too bare-bones to include, and too specific to a given (unsupported) means of running MB.

**Pull request closed without merging**
