### PR TITLE
Optimize changed files check for the backend.yml workflow

### PR DESCRIPTION
**Pull request by nemanjaglumac**
New static viz check is GREAT!
But to get the output is expensive, as it requires to prepare both FE and BE, **and** to build static-viz bundle.

I think we can slightly improve this check.

### Before
1. prepare-frontend
2. prepare-backend
3. build-static-viz
4. files-changed-check
5. static-viz-files-changed-check

So, we're doing all these expensive operations before the step 4, even though they might not even be necessary.
If files changed already outputs `backend_all`, this means we have to run these tests whether or not there were static-viz changes.

### After
1. test which files changed
    - if `backend_all` output -> skip static-viz-bundle and start running tests straight away
    - else if there are no direct backend changes, have an additional check for static-viz
2. static-viz-files-changed
    - if true -> run tests
    - else -> skip tests

### CODE REVIEW

**Review by npfitz — APPROVED** [review]
I like it! good idea to split the 2 checks

**Review by alxnddr — APPROVED** [review]
Totally makes sense 👏

**Comment by iethree** [comment]
Idea makes sense, I think some of the backend workflows are still relying on the static viz artifact, thus they are failing.

Screen Shot 2023-09-28 at 2 47 24 PM

**Comment by nemanjaglumac** [comment]
Idea **made** sense before I saw that we'd have to build static-viz anyway.
Let me sleep on it to see whether or not it's worth adding another conditional to solve it, or should I abandon it.

**Comment by alxnddr** [comment]
If we had **download or build artifact** step later instead of just downloading it would work and in some cases eliminate excessive FE/BE preparation

**Comment by nemanjaglumac** [comment]
> If we had download or build artifact step later instead of just downloading it would work and in some cases eliminate excessive FE/BE preparation

@alxnddr Did you mean this?
https://github.com/metabase/metabase/pull/34209/commits/e3ddd3aa9834afd4b38f56ef58cee53102c1c4e8

**Review by alxnddr — APPROVED** [review]
@nemanjaglumac yep 👍

**Pull request merged**
