### PR TITLE
No need to use the abstracted `backend.js` to launch Cypress tests

### PR DESCRIPTION
**Pull request by ariya**
The general purpose `backend.js` is overkill for running Metabase before launching Cypress and the tests. Instead of the abstracted logic, just do the starting and stopping of Metabase Uberjar directly.

How to test: build the Uberjar first (e.g. `./bin/build`) and then launch Cypress tests (e.g. `yarn test-cypress-open`).

Before and after this PR, there should not be any behavior changes, i.e. everything should continue to work as is.

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
While I absolutely love the simplified logic, I am not so sure we should put everything together in a Cypress runner. I'm [in the middle of cleaning `backend.js` up](https://github.com/metabase/metabase/issues/24023) (mostly for the sake of history/documentation). Do you mind if we wait with this step a bit?

**Comment by nemanjaglumac** [comment]
Unless I missed it, this approach doesn't account for `yarn test-cypress-open-no-backend`, or it doesn't account for `E2E_HOST` in other words.

But it is extremely helpful as a guide in the right direction and thank you so much for that.

**Comment by ariya** [comment]
> Do you mind if we wait with this step a bit?

Definitely, this PR serves more as an illustration, rather than set-in-stone approach!

**Comment by ariya** [comment]
> Unless I missed it, this approach doesn't account for `yarn test-cypress-open-no-backend`, or it doesn't account for `E2E_HOST` in other words.

Yup, just to let us focus on the first step first. I reckon it's easier to add a (better) logic for launching tests with the currently running backend, once everything is sorted out a little bit.

**Comment by ariya** [comment]
Looks good! Closing this one since the proposed improvements were in.

**Pull request closed without merging**
