### PR TITLE
Make temporal fields selectable for max/min summary

### LINKED ISSUE #4482: Can not get the minimum or maximum of datetime
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome

- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X 10.12.2

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Redshift

- Metabase version: (e.x. 0.19.3)
0.22.2

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
docker

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
h2

Hi, guys, I can only find the numeric fields in the builder when I chose minimum of, however min(datetime typed fields) is supported in sql editor. Why does this happend?

Finnaly, thanks for your great job and product.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by ariya**
This is achieved by having a new type of field called `LIMIT` (if anyone has a better name, I'm all ears), which includes `NUMBER` and `TEMPORAL` and changing the function `min` and `max` to operate on `LIMIT`, instead of `SUMMABLE` (which is more suitable for e.g. `avg`).

New Cypress tests were added.

**To verify manually**

1. Ask a question, Custom question.
2. Sample Dataset, Products table.
3. Summarize: Pick the metric and choose _Minimum of..._.

**Before this PR**

The choices are _only_ Price and Rating.

image

**After this PR**

The choices are Price, Rating, and Created At.

image

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
Possibly use `restraint` (or `scope`) instead of `limit`, since `limit` might be confused with the SQL clause?

This is great, but seems like it automatically selects granularity. It likely requires fixing issue 13098, before this issue can be addressed.

At least it's possible to use Custom Expression now directly without Custom Column hack.
image

But I have to know the field name and type it manually in the Custom Expression editor:
image

It also does not allow strings (example in bottom part of https://github.com/metabase/metabase/issues/4482#issuecomment-927821792), but the Custom Column can still be used here.

**Review by ranquild — APPROVED** [review]
Code-wise look great. WDYT about changing cypress tests or adding a new one that would validate that the query result is the correct one?

**Comment by ranquild** [comment]
@flamber As for the granularity issue, I'd say that this PR can be merged before fixing it, WDYT?

**Comment by flamber** [comment]
@ranquild Yes, but then the issue cannot be closed before a PR would address that (and probably some of my other points).
That's why I neither approved or blocked the PR, since it's great progress, but needs some extra stuff that could come in other PRs.

**Comment by ariya** [comment]
> Possibly use `restraint` (or `scope`) instead of `limit`, since `limit` might be confused with the SQL clause?

Good point on the conflict, I've changed it to `scope` for now.

> This is great, but seems like it automatically selects granularity. It likely requires fixing issue 13098, before this issue can be addressed.

Thanks for the pointer on 13098! I'll take a look.

> It also does not allow strings (example in bottom part of [#4482 (comment)](https://github.com/metabase/metabase/issues/4482#issuecomment-927821792)), but the Custom Column can still be used here.

Just to make sure I don't misunderstand: should `min` and `max` be allowed for strings as well?

**Comment by ariya** [comment]
> Code-wise look great. WDYT about changing cypress tests or adding a new one that would validate that the query result is the correct one?

Thanks @ranquild, I've added the query result verification to the tests.

**Comment by flamber** [comment]
@ariya 
> Just to make sure I don't misunderstand: should min and max be allowed for strings as well?

Perhaps not visually, just allow it via Custom Expressions, since it's not a super common use-case, though it was something I have used often in legacy systems, like when your IDs are stored as strings (ex. `C01-000231`) or you want to return the last Title from Categories in Products.

**Comment by ariya** [comment]
> Perhaps not visually, just allow it via Custom Expressions, since it's not a super common use-case, though it was something I have used often in legacy systems, like when your IDs are stored as strings (ex. `C01-000231`) or you want to return the last Title from Categories in Products.

This behavior is filed as #18207.

**Pull request merged**
