### PR TITLE
Rewrite sources in all joined-fields

### LINKED ISSUE #12129: Cannot filter on joined/linked table when question has Custom Column
**Describe the bug**
When creating a question with a Custom Column, it's not possible to filter on linked/joined tables.

**To Reproduce**
Linked table:
1. Notebook question > Sample Dataset > Orders
2. Create Custom Column `[Discount] * 2` called "Mega Discount"
3. Filter by Product.Category=Doohickey
4. Errors with `Column "PRODUCTS__via__PRODUCT_ID.CATEGORY" not found`

Joined table:
1. Notebook question > Sample Dataset > Orders
2. Join table Products on Orders.ProductID=Products.ID
3. Create Custom Column `[Discount] * 2` called "Mega Discount"
4. Filter by Product.Category=Doohickey
5. Errors with `Column "Product.CATEGORY" not found;`

**Information about your Metabase Installation:**
`master` on several platforms with different datasources - it used to work on 0.34.3

### PR DESCRIPTION
**Pull request by sbelak**
Fixes #12129

### CODE REVIEW

**Review by walterl — APPROVED** [review]
As I understand it this change hoists up the `mbql.u/replace` call to include all `:joined-field`s, and not just those in the root query's fields. Clever!

**Comment by mazameli** [comment]
I'm giving this a quick manual test right now.

**Review by mazameli — APPROVED** [review]
Fixes the repro cases that @flamber outlined in #12129.

**Comment by Xlagrap** [comment]
Hello,

Is this fix : 

> Fixes the repro cases that @flamber outlined in #12129.

integrated in the 0.35 RC2 ? Because I have the same problem in RC2 : 

Thanks

**Comment by flamber** [comment]
@Xlagrap Yes, this is in RC2. Can you provide steps to reproduce?

**Comment by Xlagrap** [comment]
Hello,

This sample question works in 0.34.3 but has the "column not found" error in 0.35 RC2 : 

Annotation 2020-03-31 154047
Annotation 2020-03-31 154059

Thanks

**Comment by flamber** [comment]
@Xlagrap Can you please provide full steps to reproduce? Do I need to generate the query in 0.34.3 with French interface, save it, then upgrade to 0.35.0 (released now) for it to fail.
Otherwise open a new issue with steps to reproduce.

**Comment by Xlagrap** [comment]
@flamber  you just have to create a query in 0.35.0 like this one to reproduce the problem : 

Annotation 2020-04-01 180329

Annotation 2020-04-01 180323

I have tried in English and the problem is here also.

Thanks

**Comment by flamber** [comment]
@Xlagrap That's an aggregated question, so you're likely seeing #11007 - upvote by clicking :+1:

**Comment by sbelak** [comment]
I think it's a separate bug. In the generated query the the name of the aggregation is wrong, it tries to reference `expression` instead of `sum`.

**Comment by Xlagrap** [comment]
Ok so I'll open a new issue.

Thanks

**Pull request merged**
