### PR TITLE
expand chart colors [WIP]

### PR DESCRIPTION
**Pull request by kdoh**

### CODE REVIEW

**Comment by kdoh** [comment]
Here's where I'm at with this so far. 

Bar / Line / Area charts were previously just limited to the 5 "Metabase Colors" we had. Now using some more forgiving color magic we use the expanded color set like we were using for pie charts.

This expanded set is now generated in a smarter way as well, and in order to give us better contrast we grab values of differing saturations throughout the generated range for every color.

This results in a situation with a bunch o' series looking something like this:
screen shot 2017-01-11 at 4 37 16 pm

The system is a bit more forgiving, but one downside is in favor of contrast it's blown out the colors a bit and everything feels very "neon." Ideally I'd like to find a way to tweak the color generation to favor a slightly more muted palette so the generated colors are a bit more like the one I initially created for MB.

Comments welcome.

**Comment by anki-code** [comment]
@kdoh Just for your information. Colors used in QlikView BI:

image

**Comment by tlrobinson** [comment]
Will the original ~5 colors remain the same? Definitely shouldn't optimize for the zillion series case too much.

**Comment by kdoh** [comment]
@tlrobinson Ideally yes. My comment above shows what you get if you go "fully generative". I made a note that ideally I'd like to find a way to be able to use the same idea, but have the initial values be as close as possible to what I hand picked originally. I'm currently looking into how best to do that.

**Comment by anki-code** [comment]
JFYI: the chart data with many stacked segments looks less "random" if it was sorted by size (#3970).

**Comment by kdoh** [comment]
closing this in favor of #4270 so we can fix the problem of series having repeated colors. Eventually I'd like to look into a more generative solution for colors as a whole but I don't want to block fixing this issue on that.

**Pull request closed without merging**
