### PR TITLE
Hide custom GeoJson settings when they are set by the env var

### LINKED ISSUE #18862: Admin Settings > Maps breaks when `custom-geojson` is set via env var `MB_CUSTOM_GEOJSON`
**Describe the bug**
When setting `MB_CUSTOM_GEOJSON`, then the frontend returns blank screen.

Workaround: Set it directly in the application database table `setting` or set it via the API with key `custom-geojson`, with value, eg. `{}`
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#put-apisettingkey

**To Reproduce**
1. Start Metabase:
`java -DMB_CUSTOM_GEOJSON='{"864d0660-2e03-ba4e-f23c-7d31eb6ac7b8":{"name":"Custom States","url":"https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/us-states.json","region_key":"STATE","region_name":"NAME"}}' -jar metabase.jar`
2. Go to Admin > Settings > Maps - blank screen
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at i.value (app-main.bundle.js:2)
    at Wa (vendor.bundle.js:2)
    at Ba (vendor.bundle.js:2)
    at xs (vendor.bundle.js:2)
    at vu (vendor.bundle.js:2)
    at gu (vendor.bundle.js:2)
    at uu (vendor.bundle.js:2)
    at vendor.bundle.js:2
    at t.unstable_runWithPriority (vendor.bundle.js:2)
```

**Information about your Metabase Installation:**
Tested 0.41.1 (versions pre-0.40.0 would not error, but would not apply the envvar, when there was keys in `setting` table)

**Additional context**
Related to #13166 and #14790

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/18862

How to test:
- `MB_CUSTOM_GEOJSON='{"864d0660-2e03-ba4e-f23c-7d31eb6ac7b8":{"name":"Custom States","url":"https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/us-states.json","region_key":"STATE","region_name":"NAME"}}' yarn dev`
- Go to Admin > Maps. The page should open and it shouldn't be possible to view/edit custom GeoJson settings.

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
Tested manually and seeing a blank page when I go to `/admin/settings/maps`.

These are the errors:
<details>
  <summary> Click to expand</summary>

```
react_devtools_backend.js:4045 The above error occurred in the <CustomGeoJSONWidget> component:
    in CustomGeoJSONWidget (created by SettingsSetting)
    in div (created by SettingsSetting)
    in li (created by SettingsSetting)
    in SettingsSetting (created by SettingsEditorApp)
    in ul (created by SettingsEditorApp)
    in div (created by AdminLayout)
    in div (created by AdminLayout)
    in div (created by AdminLayout)
    in AdminLayout (created by SettingsEditorApp)
    in SettingsEditorApp (created by Title[SettingsEditorApp])
    in Title[SettingsEditorApp] (created by Connect(Title[SettingsEditorApp]))
    in Connect(Title[SettingsEditorApp]) (created by RouterContext)
    in Unknown (created by Title[])
    in Title[] (created by RouterContext)
    in div (created by AdminApp)
    in AdminApp (created by Title[AdminApp])
    in Title[AdminApp] (created by RouterContext)
    in Unknown (created by UserIsAdmin(Component))
    in UserIsAdmin(Component) (created by Connect(UserIsAdmin(Component)))
    in Connect(UserIsAdmin(Component)) (created by UserIsAuthenticated(Connect(UserIsAdmin(Component))))
    in UserIsAuthenticated(Connect(UserIsAdmin(Component))) (created by Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))
    in Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component))))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component))))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))) (created by BackgroundApplicator)
    in BackgroundApplicator (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, App.
overrideMethod @ react_devtools_backend.js:4045
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
callback @ react-dom.development.js:20744
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19858
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
(anonymous) @ index.js:25
Promise.then (async)
(anonymous) @ index.js:24
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
_callee$ @ settings.js:12
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ selectors.js:469
_next @ selectors.js:469
(anonymous) @ selectors.js:469
(anonymous) @ selectors.js:469
(anonymous) @ settings.js:12
(anonymous) @ store.js:23
dispatch @ applyMiddleware.js:35
_callee3$ @ settings.js:35
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ selectors.js:469
_next @ selectors.js:469
(anonymous) @ selectors.js:469
(anonymous) @ selectors.js:469
(anonymous) @ settings.js:35
_callee3$ @ redux.js:200
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ redux.js:200
(anonymous) @ store.js:23
(anonymous) @ bindActionCreators.js:3
componentDidMount @ SettingsEditorApp.jsx:66
commitLifeCycles @ react-dom.development.js:19814
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
Component.setState @ react.development.js:471
(anonymous) @ Router.js:109
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
done @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
getComponentsForRoute @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
mapAsync @ AsyncUtils.js:78
getComponents @ getComponents.js:29
finishEnterHooks @ createTransitionManager.js:77
next @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
wrappedNext @ TransitionUtils.js:110
_callee$ @ routes.jsx:165
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ SegmentSidebar.jsx:72
_next @ SegmentSidebar.jsx:72
Promise.then (async)
asyncGeneratorStep @ SegmentSidebar.jsx:72
_next @ SegmentSidebar.jsx:72
(anonymous) @ SegmentSidebar.jsx:72
(anonymous) @ SegmentSidebar.jsx:72
(anonymous) @ routes.jsx:162
transitionHook @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
next @ AsyncUtils.js:34
loopAsync @ AsyncUtils.js:51
runTransitionHooks @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
runTransitionHooks @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
finishMatch @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
next @ AsyncUtils.js:41
loopAsync @ AsyncUtils.js:51
matchRoutes @ matchRoutes.js:231
match @ createTransitionManager.js:41
historyListener @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
callComponentWillMount @ react-dom.development.js:12953
mountClassInstance @ react-dom.development.js:13048
updateClassComponent @ react-dom.development.js:17101
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
scheduleUpdateOnFiber @ react-dom.development.js:21188
updateContainer @ react-dom.development.js:24373
(anonymous) @ react-dom.development.js:24758
unbatchedUpdates @ react-dom.development.js:21903
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24757
render @ react-dom.development.js:24840
_init @ app.js:76
(anonymous) @ app.js:118
Show 119 more frames
CustomGeoJSONWidget.jsx:169 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at CustomGeoJSONWidget.render (CustomGeoJSONWidget.jsx:169:1)
    at finishClassComponent (react-dom.development.js:17160:1)
    at updateClassComponent (react-dom.development.js:17110:1)
    at beginWork (react-dom.development.js:18620:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22154:1)
render @ CustomGeoJSONWidget.jsx:169
finishClassComponent @ react-dom.development.js:17160
updateClassComponent @ react-dom.development.js:17110
beginWork @ react-dom.development.js:18620
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
(anonymous) @ index.js:25
Promise.then (async)
(anonymous) @ index.js:24
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
_callee$ @ settings.js:12
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ selectors.js:469
_next @ selectors.js:469
(anonymous) @ selectors.js:469
(anonymous) @ selectors.js:469
(anonymous) @ settings.js:12
(anonymous) @ store.js:23
dispatch @ applyMiddleware.js:35
_callee3$ @ settings.js:35
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ selectors.js:469
_next @ selectors.js:469
(anonymous) @ selectors.js:469
(anonymous) @ selectors.js:469
(anonymous) @ settings.js:35
_callee3$ @ redux.js:200
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ redux.js:200
(anonymous) @ store.js:23
(anonymous) @ bindActionCreators.js:3
componentDidMount @ SettingsEditorApp.jsx:66
commitLifeCycles @ react-dom.development.js:19814
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
Component.setState @ react.development.js:471
(anonymous) @ Router.js:109
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
done @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
getComponentsForRoute @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
mapAsync @ AsyncUtils.js:78
getComponents @ getComponents.js:29
finishEnterHooks @ createTransitionManager.js:77
next @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
wrappedNext @ TransitionUtils.js:110
_callee$ @ routes.jsx:165
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ SegmentSidebar.jsx:72
_next @ SegmentSidebar.jsx:72
Promise.then (async)
asyncGeneratorStep @ SegmentSidebar.jsx:72
_next @ SegmentSidebar.jsx:72
(anonymous) @ SegmentSidebar.jsx:72
(anonymous) @ SegmentSidebar.jsx:72
(anonymous) @ routes.jsx:162
transitionHook @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
next @ AsyncUtils.js:34
loopAsync @ AsyncUtils.js:51
runTransitionHooks @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
runTransitionHooks @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
finishMatch @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
next @ AsyncUtils.js:41
loopAsync @ AsyncUtils.js:51
matchRoutes @ matchRoutes.js:231
match @ createTransitionManager.js:41
historyListener @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
callComponentWillMount @ react-dom.development.js:12953
mountClassInstance @ react-dom.development.js:13048
updateClassComponent @ react-dom.development.js:17101
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
scheduleUpdateOnFiber @ react-dom.development.js:21188
updateContainer @ react-dom.development.js:24373
(anonymous) @ react-dom.development.js:24758
unbatchedUpdates @ react-dom.development.js:21903
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24757
render @ react-dom.development.js:24840
_init @ app.js:76
(anonymous) @ app.js:118
Show 113 more frames
react_devtools_backend.js:4045 The above error occurred in the <CustomGeoJSONWidget> component:
    in CustomGeoJSONWidget (created by SettingsSetting)
    in div (created by SettingsSetting)
    in li (created by SettingsSetting)
    in SettingsSetting (created by SettingsEditorApp)
    in ul (created by SettingsEditorApp)
    in div (created by AdminLayout)
    in div (created by AdminLayout)
    in div (created by AdminLayout)
    in AdminLayout (created by SettingsEditorApp)
    in SettingsEditorApp (created by Title[SettingsEditorApp])
    in Title[SettingsEditorApp] (created by Connect(Title[SettingsEditorApp]))
    in Connect(Title[SettingsEditorApp]) (created by RouterContext)
    in Unknown (created by Title[])
    in Title[] (created by RouterContext)
    in div (created by AdminApp)
    in AdminApp (created by Title[AdminApp])
    in Title[AdminApp] (created by RouterContext)
    in Unknown (created by UserIsAdmin(Component))
    in UserIsAdmin(Component) (created by Connect(UserIsAdmin(Component)))
    in Connect(UserIsAdmin(Component)) (created by UserIsAuthenticated(Connect(UserIsAdmin(Component))))
    in UserIsAuthenticated(Connect(UserIsAdmin(Component))) (created by Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))
    in Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component))))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component))))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))) (created by BackgroundApplicator)
    in BackgroundApplicator (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

</details>

**Comment by nemanjaglumac** [comment]
Also, this:
```
CustomGeoJSONWidget.jsx:169 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at CustomGeoJSONWidget.render (CustomGeoJSONWidget.jsx:169:1)
    at finishClassComponent (react-dom.development.js:17160:1)
    at updateClassComponent (react-dom.development.js:17110:1)
    at beginWork (react-dom.development.js:18620:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22154:1)
    ```

**Comment by ranquild** [comment]
@nemanjaglumac I've double-checked and I wasn't able to reproduce the issue you mentioned. Have you tried removing the frontend cache folder (`node_modules/.cache`)?

**Comment by nemanjaglumac** [comment]
No, I haven't. Will do that and try again. Thanks for the suggestion.

**Comment by nemanjaglumac** [comment]
@ranquild still the same, even after nuking fe cache. Let's see if someone else can reproduce.

**Comment by ranquild** [comment]
> @ranquild still the same, even after nuking fe cache. Let's see if someone else can reproduce.

Do you follow the steps from the description, or something else?

**Comment by nemanjaglumac** [comment]
> Do you follow the steps from the description, or something else?

Of course. I run it with:
```
MB_CUSTOM_GEOJSON='{"864d0660-2e03-ba4e-f23c-7d31eb6ac7b8":{"name":"Custom States","url":"https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/us-states.json","region_key":"STATE","region_name":"NAME"}}' yarn dev
```

**Comment by alxnddr** [comment]
@ranquild I'm getting the same error as @nemanjaglumac 
Screenshot 2022-01-12 at 22 16 36

**Comment by ranquild** [comment]
@alxnddr Could you check the fix one more time? It should be working now

**Review by flamber — APPROVED** [review]
While this works, could we perhaps write something like this, since just displaying a blank section can be a little difficult to understand unless you know it's controlled by envvar.
> Custom maps is defined by MB_CUSTOM_GEOJSON

image

**Comment by ranquild** [comment]
@mazameli Could you please have a look?

**Comment by ranquild** [comment]
Given that it's no longer possible to change translation strings, I'll merge it as it is.

**Comment by flamber** [comment]
Then you could just leave the section title "Custom maps" and add `Using value of env var {0}` or `Using {0}`, which already exists in translations.

**Pull request merged**
