### PR TITLE
Replace npm with yarn

### PR DESCRIPTION
**Pull request by tlrobinson**
[Yarn](https://yarnpkg.com/) is an npm compatible package manager from Facebook which appears to solve a number of pain points we've had with npm.

It's significantly faster and has a lockfile/shrinkwrap system that's might actually work and doesn't produce insane diffs.

Yarn doesn't respect `npm-shrinkwrap.json` (it has `yarn.lock`) so use it at your own risk until we start committing `yarn.lock`.

### CODE REVIEW

**Comment by kdoh** [comment]
I'm excited about this. 👍

**Comment by tlrobinson** [comment]
Just waiting for them to release 0.15.2 which fixes an issue with `yarn run` (#809) then I think we should go for it.

**Comment by tlrobinson** [comment]
@metabase/core-developers  yarn released 0.16.0 which fixed the issue that was blocking this. If you guys are up for giving this a shot I most certainly am.

**Comment by kdoh** [comment]
Let's do it. Can't say there's anything specific about the way NPM manages dependencies that I'm going to miss.

**Comment by camsaul** [comment]
Can't be any worse than `npm`

**Comment by salsakran** [comment]
I share @camsaul's enthusiasm.

**Pull request merged**
