### PR TITLE
Consider schema for Snowflake DB in sync

### LINKED ISSUE #13126: Configuration property 'Schema' doesn't work for Snowflake
We've upgraded our Metabase version from v0.35.4 to v0.36.3 and looks like the logic for Snowflake connection was changed.

v0.35.4:
by specifying 'Shema' in database connection details we were able to have tables only from this schema in database and 
all others haven't been shown to users. 

v0.36.3 
Metabase shows all schemes regardless of whether 'Shema'  was specified or not.

It's confusing for users and don't allow us not to share sensitive information. 

Diagnostic info:
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.9.0-11-amd64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.5.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-04",
      "tag": "v0.36.3",
      "branch": "release-0.36.x",
      "hash": "a792f14"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by jeff303**
Consider schema for Snowflake DB in sync

If :schema is specified in Snowflake db-details, then only sync that schema

Adding test

### CODE REVIEW

**Comment by jeff303** [comment]
Fixes #13126.

**Comment by dpsutton** [comment]
I am not familiar with what schemas are supposed to be in snowflake. But if they are similar to schemas in other databases, shouldn't we enumerate all schemas that the connection user has permissions to see? It sounds like perhaps restricting to just a schema in details might have been a bug that they came to rely on, rather than a feature that we broke. It's not clear to me that that is the correct way forward.

My gut says that the connection's credentials should not allow access to those schemas and then sync just works as normal as it does on other databases. But I don't know how schemas are intended to be used on snowflake so maybe they aren't exactly analogous.

**Comment by dpsutton** [comment]
We describe the snowflake database like so:

```clojure
(defmethod driver/describe-database :snowflake
  [driver database]
  ;; using the JDBC `.getTables` method seems to be pretty buggy -- it works sometimes but other times randomly
  ;; returns nothing
  (let [db-name          (db-name database)
        excluded-schemas (set (sql-jdbc.sync/excluded-schemas driver))]
    (qp.store/with-store
      (qp.store/fetch-and-store-database! (u/the-id database))
      (let [spec (sql-jdbc.conn/db->pooled-connection-spec database)
            sql  (format "SHOW OBJECTS IN DATABASE \"%s\"" db-name)]
        (with-open [conn (jdbc/get-connection spec)]
          {:tables (into
                    #{}
                    (comp (filter (fn [{schema :schema_name, table-name :name}]
                                    (and (not (contains? excluded-schemas schema))
                                         (sql-jdbc.sync/have-select-privilege? driver conn schema table-name))))
                          (map (fn [{schema :schema_name, table-name :name, remark :comment}]
                                 {:name        table-name
                                  :schema      schema
                                  :description (not-empty remark)})))
                    (try
                      (jdbc/reducible-query {:connection conn} sql)
                      (catch Throwable e
                        (throw (ex-info (trs "Error executing query") {:sql sql} e)))))})))))
```

which is just a lot of noise for `(format "SHOW OBJECTS IN DATABASE \"%s\"" db-name)` 
```clojure
(and (not (contains? excluded-schemas schema))
     (sql-jdbc.sync/have-select-privilege? driver conn schema table-name))
```

Which seems pretty reasonable to me. The documentation for [show objects](https://docs.snowflake.com/en/sql-reference/sql/show-objects.html) states

> Lists the tables and views for which you have access privileges. This command can be used to list the tables and views for a specified database or schema (or the current database/schema for the session), or your entire account.

But if we make this change, there would be no way to allow access to only 2 of N schemas. We presumably can't handle some comma delimited string of schemas so this seems like just a workaround that doesn't actually solve the issue. It would seem far better to [grant privileges](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege.html) to whatever schemas through the user account rather than this change.

Would love to hear thoughts though.

**Comment by jeff303** [comment]
> I am not familiar with what schemas are supposed to be in snowflake. But if they are similar to schemas in other databases, shouldn't we enumerate all schemas that the connection user has permissions to see? It sounds like perhaps restricting to just a schema in details might have been a bug that they came to rely on, rather than a feature that we broke. It's not clear to me that that is the correct way forward.
> 
> My gut says that the connection's credentials should not allow access to those schemas and then sync just works as normal as it does on other databases. But I don't know how schemas are intended to be used on snowflake so maybe they aren't exactly analogous.

Yeah, there is actually a larger epic (can't find right at this moment, but I can probably dig it up tomorrow) pertaining to finer grained control over sync behavior/large instances/etc.  The idea is that users should be able to select or deselect certain schemas from the UI, without having to go into the DB server itself and muck with permissions (which they sometimes don't have the ability to do anyway).

Let's leave this for now until I can figure out how this fits into the larger context.

**Pull request closed without merging**
