### PR TITLE
Check for and ignore broken `table-columns` when determining export column order

### LINKED ISSUE #19465: Specific visualization_settings can cause empty export
**Describe the bug**
Specific visualization_settings can cause blank export

Regression since 0.41.0

I've spend too long trying to figure out how to end up like this, but cannot figure it out, so here's the steps to reproduce the problem, not how to end up here. And it seems to only happen with saved questions, not dirty, which just makes this even more frustrating (#17753).

**To Reproduce**
1. Custom question > Sample Dataset > Products - summarize Count grouped by Category and CreatedAt:Year - save question
2. Change report_card.visualization_settings to this:
<details><summary>JSON</summary>

```
{
  "table.columns": [
    {
      "name": "RANDOM_OLD_NONEXISTENT_COLUMN1",
      "fieldRef": [
        "field",
        1,
        null
      ],
      "enabled": true
    },
    {
      "name": "RANDOM_OLD_NONEXISTENT_COLUMN2",
      "field_ref": [
        "field",
        2,
        null
      ],
      "enabled": true
    }
  ],
  "graph.metrics": [
    "count"
  ],
  "graph.dimensions": [
    "CREATED_AT",
    "CATEGORY"
  ]
}
```

</details>

3. Refresh the question and try to export - all files are empty, just with newlines matching the amount of results there should have been.
image

**Information about your Metabase Installation:**
Tested 0.40.5 thru 0.41.5 and master - regression since 0.41.0

### PR DESCRIPTION
**Pull request by noahmoss**
The core issue in #19465 is that we use `table-columns` (from a card's viz settings) as the source of truth for the order of columns in the export, if it exists. If `table-columns` is corrupted and only contains references to columns that don't actually exist in the query results, the export ends up blank. `table-columns`, as far as I know, should only contain references to actual columns in the query, so there must be an upstream bug somewhere (maybe in the past) that can lead to this state.

My proposed solution is to check whether any column refs in `table-columns` are _not_ present in `cols` (the column metadata from the query). If this is the case, we can assume that `table-columns` is corrupted and fallback to using the order of columns in `cols` directly for the export.

Resolves #19465

### CODE REVIEW

**Review by dpsutton — APPROVED** [review]
Couple questions:
- why `remove nil?` on the field_refs seq? Can we have columns without field_refs?
- why do we handle an empty column list? `(empty? col-field-refs)` What scenario would this be? I think field_ref will be present for all columns so empty field_refs means no columns as I understand it.

Looks fine just wanted to understand the subtleties of these two points.

**Comment by noahmoss** [comment]
@dpsutton Good questions, should have made this clearer in the PR description. Native queries don't actually have field_refs defined in `cols` so we should always consider `table-columns` as valid. These are to handle that case. I'll add a comment to make it clear.

**Comment by dpsutton** [comment]
On stats i did `select * from orders` against the sample dataset and I see in the dataset response:
image

Copy that json blob and 

```javascript
cat /tmp/metadata.json| jq '.data.cols | map(.field_ref)'
[
  [
    "field",
    "ID",
    {
      "base-type": "type/BigInteger"
    }
  ],
  [
    "field",
    "USER_ID",
    {
      "base-type": "type/Integer"
    }
  ],
  [
    "field",
    "PRODUCT_ID",
    {
      "base-type": "type/Integer"
    }
  ],
  [
    "field",
    "SUBTOTAL",
    {
      "base-type": "type/Float"
    }
  ],
  [
    "field",
    "TAX",
    {
      "base-type": "type/Float"
    }
  ],
  [
    "field",
    "TOTAL",
    {
      "base-type": "type/Float"
    }
  ],
  [
    "field",
    "DISCOUNT",
    {
      "base-type": "type/Float"
    }
  ],
  [
    "field",
    "CREATED_AT",
    {
      "base-type": "type/DateTime"
    }
  ],
  [
    "field",
    "QUANTITY",
    {
      "base-type": "type/Integer"
    }
  ]
]
```

Which demonstrates that native queries will have field_refs I believe. From the annotate middleware, we put a field ref on native columns if they have a non-empty name: https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/annotate.clj#L74-L92

**Comment by rlotun** [comment]
shall we backport this, since I think we'll do one last maintenance release for 41?

**Comment by noahmoss** [comment]
@dpsutton Interesting... in the streaming code, when I try to export a native query of `select * from orders;` I see this in `cols`:

```
({:display_name "ID", :source :native, :name "ID", :base_type :type/BigInteger}
 {:display_name "USER_ID", :source :native, :name "USER_ID", :base_type :type/Integer}
 {:display_name "PRODUCT_ID", :source :native, :name "PRODUCT_ID", :base_type :type/Integer}
 {:display_name "SUBTOTAL", :source :native, :name "SUBTOTAL", :base_type :type/Float}
 {:display_name "TAX", :source :native, :name "TAX", :base_type :type/Float}
 {:display_name "TOTAL", :source :native, :name "TOTAL", :base_type :type/Float}
 {:display_name "DISCOUNT", :source :native, :name "DISCOUNT", :base_type :type/Float}
 {:display_name "CREATED_AT", :source :native, :name "CREATED_AT", :base_type :type/DateTime}
 {:display_name "QUANTITY", :source :native, :name "QUANTITY", :base_type :type/Integer})
```

**Comment by dpsutton** [comment]
@noahmoss weird. The query metadata is an accumulated mess I think. It has the column information in the metadata twice and they are subtly different. It really needs some thoughtful cleanup. I guess the streaming stuff has a subtly different middleware stack for some reason.

**Pull request merged**
