### PR TITLE
Add visual smoke test for notebook editor

### PR DESCRIPTION
**Pull request by kulyk**
This PR adds a visual smoke test for the notebook editor. The test constructs a question using different notebook features, so we can test the overall look of the page

### Demo

Screenshot 2021-08-12 at 15 58 43

### CODE REVIEW

**Comment by kulyk** [comment]
@metabase-bot run visual tests

**Comment by alxnddr** [comment]
There is no new screenshot here https://percy.io/6a8dd5c9/metabase/builds/12052609/unchanged/678701115?browser=chrome&browser_ids=20&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1280&widths=1280 🤔

**Comment by kulyk** [comment]
> There is no new screenshot here https://percy.io/6a8dd5c9/metabase/builds/12052609/unchanged/678701115?browser=chrome&browser_ids=20&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1280&widths=1280 🤔

Ouch, I guess the test name could be a problem, forgot to rename it

**Comment by kulyk** [comment]
@metabase-bot run visual tests

**Comment by kulyk** [comment]
@metabase-bot run visual tests

**Comment by kulyk** [comment]
@alxnddr it's here now, please take a look: https://percy.io/6a8dd5c9/metabase/builds/12054773/changed/678812197?browser=chrome&browser_ids=20&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=1280

Thanks for pointing that out in the first place 🙏

**Review by alxnddr — APPROVED** [review]
Fantastic 👍 Thanks for adding the test

**Comment by kulyk** [comment]
Thank you for setting up Percy! 🏆

**Pull request merged**
