### PR TITLE
Switch from Korma to HoneySQL [WIP]

### PR DESCRIPTION
**Pull request by camsaul**
This PR isn't done but I'll open it so we can have a place to discuss this proposal.

If I had a dollar for every time Korma made something harder than it needed to be I'd have at least $20. I've considered the switch for at least a year now but put it off because Korma was "good enough" and we could "make it work" with enough hacks. 

At this point, we're running into cases were no amount of hacks can make it work the way we want without forking the project and fixing it ourselves. There's not much hope for that changing in the near future, either: Korma development is happening very slowly these days; we've reached the point that we can't even update `clojure.java.jdbc` because it breaks Korma.

Korma was never really meant to be used for what we're doing with it. Korma is macro-based and meant to write **and execute** queries in a concise syntax. To programmatically build a form that can be compiled to SQL, we have to dive deep into the Korma internals. In effect, this means hacking the Metabase SQL drivers requires an intimate knowledge of the undocumented internals of Korma; I've only acquired this through picking apart the korma source code. [HoneySQL](https://github.com/jkk/honeysql) on the other hand is specifically designed for building queries the way we do.

Korma's also Is tied to the C3P0 library. @agilliland has resolved most of our connection pool issues but we're still tied to one specific connection library as long as we use Korma. We don't necessarily need to stop using it but with HoneySQL at least we'd have the option to switch it out if we wanted.

There are no real risks involved beyond the time it takes to refactor the code. HoneySQL syntax is broadly similar to Korma in most cases, but substantially simpler when trying to do complicated things. The biggest risk might be making the driver code easier to write and attracting rando PRs.

### CODE REVIEW

**Comment by agilliland** [comment]
why are there 107 files changed as part of this PR?  honeysql couldn't possibly require that much of a change

**Comment by agilliland** [comment]
also, after a quick glance at this it looks like you are trying to use honeysql not only for the MBQL driver sql but also for the entire app persistence layer, which seems like biting off way too much at one time.

**Comment by salsakran** [comment]
As a point of process, this is too big a PR to reasonably review. Given that it touches pretty much the entire app, can we split this up into at least two smaller bite sized PRs to review and verify? 

There's a LOT of room for bugs to hid in 1k+ changed LoC. 

👎

**Comment by salsakran** [comment]
Naively I'd propose breaking this up into

1. a PR to move the crud accesses over to honeysql (with no semantic changes)
2. a PR to move the drivers over to honey sql (with no semantic changes)
3. a PR to cover any changes in semantics.

The expectation is that tests would be unchanged between in 1+2, with any deviation being very closely checked. Tests could reasonably change in 3, but at least it'd be easy to inspect any changes in semantics without having to also wade through 100s of lines of other code.

**Pull request closed without merging**
