### PR TITLE
Add new flag for BigQuery to use JVM timezone [ci drivers]

### PR DESCRIPTION
**Pull request by senior**
This commit adds a flag to allow dates parsed from BigQuery to be
parsed in the JVM's timezone rather than UTC. By default all BigQuery
dates are in UTC but it's possible to modify the timezone via a
function invocation. This flag allows installs that have all of their
queries modifying the timezone in that way to match the actual and
expected timezones via setting the JVM's timezone.

### CODE REVIEW

**Comment by senior** [comment]
@mazameli I think we'll need some design work on this new setting. It needs some description for the setting and maybe something to minimize it? I think for most BigQuery users the default (turned off) is good and would probably just be confusing to see it.

**Comment by mazameli** [comment]
Hmm, I wonder which of these settings is the one @senior added… ;)

I think we could have this follow the same pattern of the "this is a large database" setting below it. I.e., have it use the `toggle` component, have the label appear to the right of the toggle, and add some explanatory text to it. The toggle's default state should be whatever we think will be right for most of our users most of the time.

The explanatory text below the label could say something like, "Most users should leave this on [or off; I don't which is the right default]. Turn this off if [some pithy way of explaining why you might turn this off, like 'if you want to manually format time fields in your queries' or whatever]."

screen shot 2018-08-31 at 3 59 53 pm

**Comment by senior** [comment]
@mazameli The slider seems fine. FWIW, the database connection settings (called details on the backend) and the UI widgets around it are all derived from their types. On the backend we add a new "detail" with a name and a type (boolean in this case) and I think the frontend handles that generically. I think in some cases we have special handling on the FE for specific connection settings, along with special verbiage that relies on the name of that setting. Sounds like we'd need to setup something similar/specialized as opposed to the generic handling that is being used now.

**Comment by mazameli** [comment]
@senior Gotcha. Looks like the toggle for choosing when metabase syncs and scans is rendered in this file, starting on line 229: `/frontend/src/metabase/components/DatabaseDetailsForm.jsx`

**Pull request merged**
