### PR TITLE
Translate datetime UI

### PR DESCRIPTION
**Pull request by tlrobinson**
Updated version of @mshen7310's #9050

### CODE REVIEW

**Comment by mazameli** [comment]
Do you need a review on this, Tom?

**Comment by tlrobinson** [comment]
@mazameli Yes that would be nice. There may be some new strings which haven't been translated though. You could use the `window.localStorage["metabase-i18n-debug"] = true` thing at least.

**Comment by mazameli** [comment]
Looks like the names of months as well as "AM" and "PM" didn't get tagged:

screen shot 2018-12-17 at 10 40 26 am

screen shot 2018-12-17 at 10 40 48 am


This might be a separate issue, but dashboard datetime filters also still have a few untagged strings:

screen shot 2018-12-17 at 10 41 38 am

screen shot 2018-12-17 at 10 41 50 am

screen shot 2018-12-17 at 10 42 38 am

**Comment by mazameli** [comment]
@tlrobinson Just a ping to see if you saw the untranslated/untagged strings I found in the above screenshots.

**Comment by tlrobinson** [comment]
I've fixed those and a couple others I've found.

BTW some of those were actually not issues because they use `moment`'s formatting rather than `c-3po` tagged strings which isn't affected by the `metabase-i18n-debug` setting. This PR enabled setting the `moment` locale based on the Metabase locale, so in the future when looking for untranslated strings we should both set `metabase-i18n-debug` and change your browser language to something else (Japanese or another language with non-Roman alphabet makes it obvious)

**Pull request merged**
