### PR TITLE
bugfix: browse data sorted using display name

### LINKED ISSUE #17513: Tables in "Browse data" is sorted by `name` instead of `display_name`
**Describe the bug**
Tables in "Browse data" is sorted by `name` instead of `display_name`

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Products > change table name to something different
2. Browse data > Sample Dataset - it's now in a slightly confusion order instead of alphabetically
image

**Information about your Metabase Installation:**
Tested 0.40.2

### PR DESCRIPTION
**Pull request by rubiagatra**
closes #17513 

###### Before submitting the PR, please make sure you do the following

- ~[ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.~

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

###  Result

Screen Shot 2021-08-21 at 18 36 58

### CODE REVIEW

**Comment by rubiagatra** [comment]
It works @flamber on my attached image sorted by display_name. But, I have trouble when running test on M1 chip.

`yarn lint && yarn test`:
```
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
```

`clojure -X:dev:test`:
```
FAIL in metabase.sync.analyze.fingerprint.insights-test/timeseries-insight-test (insights_test.clj:93)
expected: [{:best-fit [:*
                       1.5672560913548484E227
                       [:exp [:* -0.02899533549378612 :x]]],
            :col nil,
            :last-change -0.19553072625698323,
            :last-value 144,
            :offset 137234.92983406168,
            :previous-value 179,
            :slope -7.671473413418271,
            :unit :day}
           {:best-fit [:+ 8915371.843617931 [:* -498.764272733624 :x]],
            :col nil,
            :last-change -0.2373905164602839,
            :last-value 2525,
            :offset 8915371.843617931,
            :previous-value 3311,
            :slope -498.764272733624,
            :unit :day}]
  actual: ([{:best-fit [:*
                        1.5672560913548482E227
                        [:exp [:* -0.02899533549378612 :x]]],
             :col nil,
             :last-change -0.19553072625698323,
             :last-value 144,
             :offset 137234.92983406168,
             :previous-value 179,
             :slope -7.671473413418271,
             :unit :day}
            {:best-fit [:+ 8915371.843617931 [:* -498.764272733624 :x]],
             :col nil,
             :last-change -0.2373905164602839,
             :last-value 2525,
             :offset 8915371.843617931,
             :previous-value 3311,
             :slope -498.764272733624,
             :unit :day}])
```

**Comment by flamber** [comment]
@rubiagatra Thank you for the PR.
We're working on M1 compatibility. It has been problematic and still some areas that isn't supported yet.

**Comment by rubiagatra** [comment]
Anything I can do after this @flamber? Or just waiting for the review?

**Comment by flamber** [comment]
@rubiagatra You could add a test, just to ensure that this wasn't changed back by accident in the future, but likely not needed.
And then wait for review.

**Review by camsaul — APPROVED** [review]

**Comment by pawit-metabase** [comment]
Thank you for your contribution! This will be included in the 0.41 release.

**Pull request merged**
