### PR TITLE
move timezone selection to localization

### PR DESCRIPTION
**Pull request by salsakran**
This is a straggler. Makes way more sense to have timezone under "localization" rather than "general" settings.

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]
🎉

**Comment by nemanjaglumac** [comment]
It's really weird that mysql test failed, because the error I see in the logs seems to be old (and fixed around last week). o.O

**Comment by paulrosenzweig** [comment]
@nemanjaglumac It looks like Sameer hadn't pulled since last week. The parent commit is from 11/23.

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac It looks like Sameer hadn't pulled since last week. The parent commit is from 11/23.

Yup. Just edited my previous message :)

**Pull request merged**
