### PR TITLE
Leaflet pin maps

### PR DESCRIPTION
**Pull request by tlrobinson**
This is a simple port of our pin maps to Leaflet, and fixes a few other issues.

PRs #3133 (and #2737) are similar but add clustering.

Open questions:
1. which pin map types should we support? Currently we show clickable client-side markers for < 2000 rows, and server-rendered tiles for >2000 rows. Do we also want clustering and/or heat maps?
   - clustering: need a new endpoint to efficiently fetch large number of points?
   - heat map: based on raw lat/lon points or an aggregation grouped by binned lat/lons? (dependent on #798?)
2. which map tile server should we use? OSM frowns upon people distributing software with their tile server hard-coded. At a minimum we should have a way to configure the tile server URL template so people can use nicer maps like MapBox, which are free but require an API key. Is it ok to use OSM by default? https://wiki.openstreetmap.org/wiki/Tile_usage_policy

Related issues:
- Switch to using Leaflet for all maps visualizations (pin map, heat) #3496 
- Request for Google Maps API heat maps #3206
- Pin Map keeps zooming on San Francisco #3152
- Completely remove Google Maps from an installation #3617
- Provide better error message for Google Maps failure #3164
- Pin + Heat maps should have the appropriate zoom + center set #3166

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers I believe this is ready for review. It's up on metabase-leaflet-maps.herokuapp.com too

**Comment by salsakran** [comment]
I'm not a fan of splitting up the two sets of map settings. 

I think they should both be under the same sub-section. @mazameli thoughts?

**Comment by salsakran** [comment]
overall, seems pretty sane 👍

**Comment by salsakran** [comment]
Hey @tlrobinson can we fix the settings confusion while we're in this as well?

**Pull request merged**
