### PR TITLE
Center chart with legend

### LINKED ISSUE #10201: Pie charts should be centered on the screen
With a wide-ish viewport, pie charts are aligned very oddly. I'd expect the chart itself to be centered vertically with the center of the page (i.e. with the refresh button).

image

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10201 

Through some flexbox hackery, I centered chart with the legend to the side. I think this looks good for questions, but I'm iffy on it for cards on dashboards.

Some options:
1. Just keep the prior behavior on dashboards
2. Have some width cutoff where we switch the layout
3. A more clever flexbox solution that gradually moves the chart to the center as the width increases

Another question I had: What's `flexChart` used for? I couldn't seem to find a layout that used it. I haven't tested how it works with this.

Here are the before/after screenshots:

### Before
question-before

### After
question-after

### Before
dashboard-before

### After
dashboard-after

### CODE REVIEW

**Comment by mazameli** [comment]
Hmm, I think I'd expect the legend to be positioned more like this, with equal space on the left and right of it:

image

**Comment by paulrosenzweig** [comment]
@mazameli good call. I just updated that.

**Comment by mazameli** [comment]
This looks good to me generally speaking. I did find one regression, where if your dashboard card is ~7 units wide and ~10 units tall such that the legend goes to the bottom, it gets clipped:

image

**Review by tlrobinson — CHANGES_REQUESTED** [review]
@paulrosenzweig Looks like Maz found one issue.

Also, I made some related changes in `notebook-mode` but I'll handle merging those.

**Comment by mazameli** [comment]
Any luck figuring out the cause of the [regression](https://github.com/metabase/metabase/pull/10406#issuecomment-514839089) I found in this branch, @paulrosenzweig? Would be cool to get this merged since it's so close.

**Comment by paulrosenzweig** [comment]
The fix ended up being simpler than I thought! 

Before the last commit:


After the last commit:

**Comment by mazameli** [comment]
Nice, yeah, looks like that regression is fixed.

I'm seeing another regression, though: if you start with a wide browser window and then resize it to be narrower, the pie charts aren't sizing down correctly.

## This branch

Screen Shot 2019-08-15 at 10 17 35 AM

## `release-0.33.x`

Screen Shot 2019-08-15 at 10 20 25 AM

**Review by mazameli — CHANGES_REQUESTED** [review]
There appears to be [another regression](https://github.com/metabase/metabase/pull/10406#issuecomment-521724176) when resizing down your browser's window.

**Comment by paulrosenzweig** [comment]
@mazameli I think that was an issue that was separately fixed in work for 33. I just rebased these changes on top of `release-0.33.x` and the issue went away.

**Comment by mazameli** [comment]
Dope. I'll take another look.

**Comment by mazameli** [comment]
@paulrosenzweig I'm still seeing some goofy dashboard card states as you can see in this video. Are you seeing things like this when testing it out locally, or is my instance haunted?

[weird-pie-charts.mov.zip](https://github.com/metabase/metabase/files/3511365/weird-pie-charts.mov.zip)

**Comment by paulrosenzweig** [comment]
> Are you seeing things like this when testing it out locally, or is my instance haunted?
Not haunted! There were some new issues introduced when I rebased on 33.x. Sorry for bouncing it over too early.

I tested it pretty thoroughly and fixed more bugs. One of those required double inserting the legend to have an accurate `flex-basis` for the spacer. @tlrobinson does that feel too gross to use?

**Review by mazameli — APPROVED** [review]
This looks good to me on the UI side! 👍 
@tlrobinson There's one thing Paul asked if you were okay with in the code.

**Review by tlrobinson — APPROVED** [review]
Works for me

**Pull request merged**
