### PR TITLE
View SQL of Structured Queries and convert them if desired

### LINKED ISSUE #607: Enable the ability to switch from gui to sql after running a question
once you start down building a card and run it, there's no way to change to sql without starting over. This is most problematic if you just need to do something more advanced on a card and it's already properly placed on a dash. Makes more sense to be able to write sql for the same card.

### LINKED ISSUE #2387: Add option to view the raw SQL created by the query builder
It would be great if there was an option to view the built SQL so we can hand it off to our DBAs for performance tuning. It would also make the query builder more portable & useful in supporting other tools & use cases.

### LINKED ISSUE #2542: New Question actions should have tooltips like dashboard actions
Dashboards actions have great tooltips, and we should add those to New Question actions, too, both for consistency as well as clarity.

Something like this:

screen shot 2016-05-04 at 5 24 51 pm

screen shot 2016-05-04 at 5 24 33 pm

screen shot 2016-05-04 at 5 23 01 pm

screen shot 2016-05-04 at 5 24 03 pm

### PR DESCRIPTION
**Pull request by agilliland**
Resolves #2387
Resolves #607
Resolves #2542

Builds upon the work in #2564 and provides an actual UI for seeing the SQL generated from a structured query and optionally converting the card over to a SQL based card if desired.  Works for other native forms as well (mongo, druid, etc).

screen shot 2016-05-16 at 5 54 31 pm

TODO:
- [x] updated icon
- [x] formatting for SQL

### CODE REVIEW

**Comment by salsakran** [comment]
Are there any quick + dirty ways to format the SQL in question?

The fully qualified names are kinda annoying but I realistically see them being un-munged. It would be nice however to have some formatting to make it readable.

**Comment by salsakran** [comment]
eg 
```
SELECT COUNT(*) AS "count", "PUBLIC"."PEOPLE"."NAME" AS "NAME" 
FROM "PUBLIC"."ORDERS" LEFT JOIN "PUBLIC"."PEOPLE" ON "PUBLIC"."ORDERS"."USER_ID" = "PUBLIC"."PEOPLE"."ID" 
GROUP BY "PUBLIC"."PEOPLE"."NAME" 
ORDER BY "count" DESC, "PUBLIC"."PEOPLE"."NAME" ASC 
LIMIT 10
```

vs 
```
SELECT COUNT(*) AS "count", "PUBLIC"."PEOPLE"."NAME" AS "NAME" FROM "PUBLIC"."ORDERS" LEFT JOIN "PUBLIC"."PEOPLE" ON "PUBLIC"."ORDERS"."USER_ID" = "PUBLIC"."PEOPLE"."ID" GROUP BY "PUBLIC"."PEOPLE"."NAME" ORDER BY "count" DESC, "PUBLIC"."PEOPLE"."NAME" ASC LIMIT 10
```

**Comment by camsaul** [comment]
ya it would be nice if we nicely formatted the SQL queries the way we do in the app logs

**Comment by agilliland** [comment]
Yeah, I did a quick check for a JS lib that would do that but didn't come up with anything obvious.  I was going to tackle that as a separate thing.  Maz had also had some syntax highlighting in his mocks that would be nice to include as well.

I can definitely apply the logic from the formatting code that we have where we are just adding in some newlines.  That's a simple first step.

**Comment by dapaishan** [comment]
We hope to increase the functionality of formatting sql, which will bring great convenience to the work of data analysts.

**Pull request merged**
