### PR TITLE
fix waterfall timezone issues and incorrect bar widths when total is enabled

### LINKED ISSUE #41551: [dc.js migration] waterfall chart with unaggregated time-series data is broken
https://github.com/metabase/metabase/assets/22608765/e309de82-27f5-4e11-8107-37e6f2a97872

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/41551

### Description

Waterfall bar width did not account for the Total bar on time series and numeric scales which led to thick overlapping bars.

During the review Emmad found that bars look weirdly shifted and bars are overlapping. The issue was that we did not apply x-axis date time transformations which I also implemented in this PR.

### How to verify

```sql
SELECT '2022-01-01' x, 10 y
union all SELECT '2022-01-02', 10
```

#### Bar widths

Before
Screenshot 2024-04-21 at 4 36 51 PM

After
Screenshot 2024-05-27 at 10 09 50 PM

#### Correct timezone

Dc.js
Screenshot 2024-05-27 at 10 09 20 PM

This branch
Screenshot 2024-05-27 at 10 08 47 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by EmmadUsmani — CHANGES_REQUESTED** [review]
On my machine I'm seeing the second bar overlap with the total, and when the total is disabled the bars are positioned strangely and the second tick label is gone

**Comment by alxnddr** [comment]
@EmmadUsmani can you please try once again on the rebased branch? There is a high chance it got fixed by https://github.com/metabase/metabase/pull/41456

**Comment by EmmadUsmani** [comment]
@alxnddr It's still not fixed, looks exactly the same as in my previous screenshots

**Review by EmmadUsmani — CHANGES_REQUESTED** [review]
@alxnddr It's still not fixed, looks exactly the same as in my previous screenshots

**Review by EmmadUsmani — APPROVED** [review]
Looks much better than before! I wonder if we can also address the un-centered labels by applying a padding offset when needed, similar to what we do for histograms? Regardless IMO this is worth merging even with the un-centered labels, we can maybe fix that later.

**Comment by alxnddr** [comment]
@EmmadUsmani un-centered labels look correct: the instance timezone is GMT-3 so we use it for ticks but the data does not include this timezone hence it is treated as UTC so that data points are a few hours ahead of ticks

**Pull request merged**
