### PR TITLE
🤖 backported "Add default value to report_card.last_used_at"

### PR DESCRIPTION
**Pull request by github-automation-metabase**
#45323
  > [!IMPORTANT]
  > Manual conflict resolution is required.
  Checkout the branch and run `./backport.sh` script. Force push your changes after cherry-picking.

### CODE REVIEW

**Comment by johnswanson** [comment]
@calherries I'm actually not sure we want to back port this. I'm on my phone so can't look in detail right now but if we reset the column but then don't update it when a card is used, we still can't trust the column. I'm thinking about the case where someone runs this version for 7 months and then they upgrade to v51. Wdyt?

**Comment by calherries** [comment]
That's true, this backport should not land until the https://github.com/metabase/metabase/pull/45007 backport is landed.

**Comment by qnkhuat** [comment]
we decided not to backport #45384 as none of these metadata are used in 50, and we still want to experiment with grouper. As this PR won't make any difference if we don't re-enable last-used-at tracking, I'm canceling this backport.

**Comment by calherries** [comment]
Opened this again because the backport #45629 landed. I need to wait for #45448 though to be cherry-picked into this PR though

**Review by calherries — APPROVED** [review]

**Pull request merged**
