### PR TITLE
WIP: Cassandra driver

### PR DESCRIPTION
**Pull request by mariusz-jachimowicz-83**
Implement #2049

###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

- [x] connection test
- [ ] cassandra installation script for CI

### CODE REVIEW

**Comment by kthakore** [comment]
hey does this work yet?

**Comment by kthakore** [comment]
What needs to be done to make this work? I wouldn't mind finishing it off.

**Comment by mariusz-jachimowicz-83** [comment]
I can't say what needs to be done to make this work. I wanted to start learning Metabase and Cassandra generally so I have started this. I can't go any further for now because I have a lot of work with my client now.
Feel free for use this if you want or you can create your own PR for this feature.

For now this PR doesn't do anything valuable.

**Comment by tlrobinson** [comment]
Hey @mariusz-jachimowicz-83 

Thank you for this PR and apologies for the long delay responding. We've recently done some work to support drivers as plugins in Metabase and as of the next release (v0.32) we will be asking driver developers to first publish new drivers in their own repositories (typically named `metabase-*-driver`). If the driver fully passes the driver tests we will link to it from our documentation, and if a driver gains significant usage we will consider merging it into Metabase itself.

Here is some documentation about publishing a driver as a plugin in a separate repository: https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#drivers-shipped-as-3rd-party-plugins

Here are two example drivers: https://github.com/metabase/sudoku-driver https://github.com/metabase/crate-driver

We still have some work to do on the documentation. You can follow progress and provide feedback on that here: https://github.com/metabase/metabase/issues/9348

Thank you.

**Comment by faerics** [comment]
@tlrobinson, did you manage to release Cassandra metabase driver as a plugin?

**Comment by flamber** [comment]
@faerics Tom closed this PR, since drivers was changed in 0.32 to a modular architecture, so that would be the way to create third-party drivers going forward. There's currently no Cassandra driver available (publicly at least), but upvote #2049.

**Pull request closed without merging**
