### PR TITLE
Fix issues with schema-less db permissions

### LINKED ISSUE #12372: Cannot view/edit table-level permissions for databases that are not schema-based
**Describe the bug**
This is another round of #12269, which fixed so it's possible to click "View tables" on the left, but clicking the squares and selecting "Limit access" in the dropdown breaks the interface.

EDIT: But when accessing via "View tables", then clicking the table squares and selecting "Grant unrestricted access" (and OK), then nothing happens.

**To Reproduce**
1. Go to Admin > Permissions
2. Click on the squares for a non-schema-based database (like MySQL) and select "Limit access"
3. The URL is changed to `/admin/permissions/databases/11/schemas/null/tables`, but the interface freezes and needs a browser refresh to make it work again.

Cannot change table permissions:
1. Go to Admin > Permissions
2. Click "View tables" for a non-schema-based database (like MySQL)
3. Clicking a table-square to "Grant unrestricted access", and OK, nothing happens, but the "Save changes" becomes active, but is also empty.

**Screenshots**
image

**Information about your Metabase Installation:**
Metabase 0.35.3

Currently the only workaround is to downgrade to 0.34.3 (remember to backup first!)

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #12372

More of what #12299 did. I hadn't done enough QA and missed some other places where `""` rather than `null` was breaking stuff.

### CODE REVIEW

**Comment by flamber** [comment]
@paulrosenzweig This fixes some of it, but it seems like the actual permission part isn't done correctly.
When I disable database for group, and then grant access to specific tables, when going to `/browse/:id` with a user, then I get the error `This database doesn't have any tables.`
If I grant unrestricted access to the entire database, then the user can see all the tables.

**Comment by paulrosenzweig** [comment]
@flamber good catch!

Ugh it looks like I'll need to keep using `""` within the permissions graph. `null` is ambiguous in that.

**Comment by paulrosenzweig** [comment]
I updated lib/permissions to expect `null` as a schema name but to convert it to `""`. It's pretty awkward, but it wasn't much of a code change and avoids reorganizing the permissions object's structure.

**Comment by flamber** [comment]
@paulrosenzweig :+1: 
It's working as it should now, but I have only tested H2 and MariaDB - would be nice if there was an extra pair of eyes on this, so we're sure we didn't overlook something (and because it's permissions)

**Comment by tlrobinson** [comment]
It seems like there's a lot of confusion around `null` vs `""` schemas. Would it be simplified by saying something like "all tables in Metabase have a schema, and if the underlying table in the database doesn't have a schema we set it to the empty string"?

**Review by tlrobinson — APPROVED** [review]

**Comment by paulrosenzweig** [comment]
@tlrobinson yeah maybe that's best. I had preferred using `null` everywhere, but if the permissions object requires `""` it might be simplest to go with that.

**Pull request merged**
