### PR TITLE
Sync latest version of `pulse.cy.spec.js` from `master`

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING CI

### What does this PR accomplish?
- Syncs the latest version of `pulse.cy.spec.js` (after [this fix](https://github.com/metabase/metabase/pull/14394/commits/e0f1a0ff18270d1951e5e0da900d398387425a39)) from `master` to keep branches in sync.

### CODE REVIEW

**Comment by ariya** [comment]
Hmm, seems that Cypress still fails on `scenarios > pulse should create a new pulse - should create a new pulse`. What could it be the reason?

**Comment by nemanjaglumac** [comment]
Not "still". The reason is that release and master diverged. So the version that was working on a release branch ahd to be updated.
It was a mistake trying to bring the updates back to the release branch so I'll close this PR.

Didn't have a chance to take a proper look - just glanced from my phone but for whatever reason the placeholder text changed on master :)

**Comment by nemanjaglumac** [comment]
Sanity check - [revert the changes](https://github.com/metabase/metabase/pull/14434/commits/ad36e8950840acc8bae6645d6edf262876d76f94) to see if the version of this test that is [already in this branch](https://github.com/metabase/metabase/commit/3c5071c1ca488a2e4f006a45e2ce439c8f95a362) works or did we have a false positive in https://github.com/metabase/metabase/pull/14372. 

All checks passing - all seems good without the need to _sync_ or _fix_ it.

**Comment by nemanjaglumac** [comment]
### Conclusion:
- Closing this PR because test didn't need fixing on a release branch and is working as expected
- It needed to be updated for `master` because branches diverged
- It's probably important to note that on a `release` branch it was possible to create a pulse without a recipient and that's why the test is passing. Is this correct/expected behavior @tsmacdonald? I can address this in a separate PR, if needed.

**Comment by tsmacdonald** [comment]
@nemanjaglumac 

> It's probably important to note that on a release branch it was possible to create/edit a pulse without a recipient and that's why the test is passing. Is this correct/expected behavior @tsmacdonald? I can address this in a separate PR, if needed.

I'm not sure which branch you're talking about, but the expected behavior for both pulses and dashboard subs is that the "Create Pulse" (or "Done") button is disabled until an email address is put in. That's the current behavior on `master` (and I just double-checked on stats)

**Comment by tsmacdonald** [comment]
Ah. Yeah, manual testing shows the bug on `release-x.37.x` but not `master` :/

**Comment by tsmacdonald** [comment]
Also an issue where clicking the email toggle can reset the form state :thinking:

**Comment by nemanjaglumac** [comment]
> Ah. Yeah, manual testing shows the bug on `release-x.37.x` but not `master` :/

Should we address this on a `release-.x.37.x` branch? I can open an issue and make a repro (basically, reopen this PR - sync changes from the `master`).

**Pull request closed without merging**
