### PR TITLE
Fix drill through to question user doesn't have all data permissions for

### LINKED ISSUE #7928: Drill-through is broken when user doesn't have access permissions to all FKs in a table
Seeing the below error
screen shot 2018-06-22 at 12 56 32 pm

when I try to click into a state on a dashboard generated for the orders sample table under a user with only access to that table (and no others) in the sample dataset.

### LINKED ISSUE #10656: Can't view a dashboard without data access permission for fields connected to filters
**Describe the bug**
A user with collection permissions to a dashboard _also_ needs data access permission 

**Logs**
```
08-20 18:06:11 WARN middleware.log :: GET /api/field/21 403 1.9 ms (4 DB calls) 
"You don't have permissions to do that."

08-20 18:06:11 WARN middleware.log :: GET /api/field/21/values 403 1.2 ms (3 DB calls) 
"You don't have permissions to do that."
```

**To Reproduce**
1. Create a dashboard
2. Create a "count of rows" card for the orders dataset
3. Add this card to a dashboard
4. Add an ID parameter and link it to the User ID field
3. Create a user X 
4. Remove Data access permissions from All Users for Sample Dataset's  People table.
5. Login as user X and go to the dashboard you created 

**Expected behavior**
I should be able to use a dashboard I have collections access to even if I have no self-service data access permissions 

**Information about your Metabase Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome
- Your operating system: (e.x. OS X 10, Windows XP, etc)
Mac OS X
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Sample dataset
- Metabase version: (e.x. 0.19.3)
```
You're on version v0.34.0-snapshot
Built on 2019-08-20
Hash: 3d5bd0a
```

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Macbook

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
H2

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #7928 
Resolves #10656

Basically just porting the crashing code to newer `metabase-lib` which is more robust.

@salsakran I *think* I reproduced what you were describing in #7928 but if you can verify, or at least clarify exactly what you did that would be good.

TODO:

- [ ] fix flow types

### CODE REVIEW

**Comment by tlrobinson** [comment]
@salsakran can you verify this resolves #7928 and #10656?

**Comment by salsakran** [comment]
@tlrobinson this fixes both of those for me.

**Comment by salsakran** [comment]
can we add tests for this?

**Review by salsakran — CHANGES_REQUESTED** [review]
fixes the issues linked.

needs tests.

**Review by camsaul — APPROVED** [review]

**Pull request merged**
