### PR TITLE
Save all x-ray questions into the same collection

### PR DESCRIPTION
**Pull request by sbelak**
Saves all x-ray questions into the same collection. 

Not sure what the correct behaviour is. Should we:
1) create the collection upfront as admin; or
2) create the collection on the first usage of xrays as current user at that time?

Should we i18n the collection name? If so, what happens if different users have different language set?

### CODE REVIEW

**Comment by salsakran** [comment]
@mazameli @kdoh 
How's the below logic?
1. Admins save dashboards into an "autogenerated" collection in the root folder
2. Normal users save them into their personal folder

**Comment by kdoh** [comment]
@salsakran That seems coherent to me.

**Comment by mazameli** [comment]
You're thinking for admins we'd put them in that autogenerated collection in the root vs. their personal collection so that other admins would be able to see each other's explorations more easily? Just trying to think through a justification for the difference in behavior between types of users.

**Comment by salsakran** [comment]
the rationale is - admins are probably saving them for use by other people, normal users aren't.

**Comment by mazameli** [comment]
Sure. I'm like 95% fine with it, I was just thinking that in either scenario, admins would have to move those auto dashboards somewhere else in order for non-admins to view them (presuming we keep the `autogenerated` collection locked down to admins-only), and if we teach admins that that's where those auto dashboards get saved, they might incorrectly assume that that's where non-admin auto dashboards will get saved as well.

**Comment by salsakran** [comment]
alternatively -- should we just have a "where do you want to save this dashboard" picker ?

**Comment by mazameli** [comment]
Yeah. I think the benefit of the peace of mind of knowing exactly where something is going to be saved might very well be worth the slight trade off in browsing friction.

**Comment by sbelak** [comment]
Closed in favour of #8118

**Pull request closed without merging**
