### PR TITLE
Fix recent Cypress flakes

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING CI

### What does this PR accomplish?
- Attempts to fix the most recent Cypress flakes appearing in CI

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
FYI, I'm manually cancelling CI run as soon as I see that the test I fixed passed. The goal is to have at least 3 successful passes in CI before reintroducing it into master.

**Comment by ariya** [comment]
> The goal is to have at least 3 successful passes in CI before reintroducing it into master.

In that case, for the sake of this testing branch, may I suggest to tweak `cypress.json` to run only `editor.cy.spec.js`? That way, the tests will finish faster. Also, you can freely re-run the job from CircleCI couple of times to ensure that subsequent runs will not fail.

**Comment by nemanjaglumac** [comment]
> In that case, for the sake of this testing branch, may I suggest to tweak `cypress.json` to run only `editor.cy.spec.js`? 

@ariya Great idea! I can certainly try to see how it works. Btw, I wanted to fix a couple of flakes. I guess I could simply edit `cypress.json` when switching to another file.

**Comment by nemanjaglumac** [comment]
@ariya - this is not going to work for Mongo and Postgres, but I am happy with that trade-off. What are your thought regarding this?

**Comment by ariya** [comment]
I think this is as good as we can make it for now. Good job @nemanjaglumac 👍

**Review by ariya — APPROVED** [review]

**Pull request merged**
