### PR TITLE
Fix 19630

### LINKED ISSUE #19630: Nit: dataset actions (move, archive, duplicate) still reference it as a "question" in modals
This is really a nitpicking, more than a "bug". Let's call it correctness.

As the title says, when you want to move, copy, archive or add dataset to a dashboard, it's still referenced as a question in each of the modals. Maybe this is even a desired behavior? cc @mazameli 

popover
image

edit modal
image

add to dashboard
image

archiving dataset
image

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Fixes #19630

### How to test and verify manually?
___
### Duplicate model tooltip
1. Open an existing model
2. Click on a chevron down icon to open the sidebar
3. Hover over the copy/duplicate icon
4. The tooltip should say "Duplicate this model"
image

### Verification Badge (requires EE)
1. Open an existing unverified model
2. Click on a chevron down icon to open the sidebar
3. The badge should say "Verify this model"
image

### Archive action
1. Open an existing model
2. Click on a chevron down icon to open the sidebar
3. Click on the archive icon
4. Modal that appears should have the title "Archive this model?" and should give warning "This model will be removed from any dashboards or pulses using it."
image
5. Confirm by clicking on the "Archive" button
6. The popup bubble in the lower left corner should say "Archived model" instead of "Archived question"
7. Similarly, when you unarchive model, that same bubble should say "Unarchived model"

@kulyk I will need your help with 6 and 7. Btw, note that those strings were never translated :/

### Edit model
1. Open an existing model
2. Click on a chevron down icon to open the sidebar
3. Click on the pencil icon
4. The modal should have the title "Edit model"
image

### Add model to dashboard
1. Open an existing model
2. Click on a chevron down icon to open the sidebar
3. Click on the "add to dashboard" icon
4. Modal that appears should have the tile "Add this model to a dashboard"
image

### CODE REVIEW

**Review by mazameli — APPROVED** [review]
Thanks for doing this!

**Comment by nemanjaglumac** [comment]
@mazameli a fix for the "Archived question" and "Unarchived question" bubbles in the lower left corner are probably going to be a bit harder. Is it ok if we leave it for the separate PR?

**Comment by mazameli** [comment]
@nemanjaglumac where do you mean exactly? Regardless, I think it would be fine if it's in a separate PR. I'm just wondering if it's worth doing at all, so a screenshot would help me.

**Comment by nemanjaglumac** [comment]
@mazameli here is the gif:
https://share.getcloudapp.com/X6u8d78P

This is the only place that's left if I'm not mistaken.

**Comment by mazameli** [comment]
Thanks! I think we could go the simpler route and actually _remove_ the existing word "question" in the "Archived question" toast notification, so it would just say "Archived". I don't think it's adding much clarity right now. But yeah, sounds like a separate and less urgent PR.

**Comment by nemanjaglumac** [comment]
Or even "Archived item" and "Unarchived item". The context menu in collections is saying "Archive this item", anyway.
image

**Pull request merged**
