### PR TITLE
Copy over sqlite fix from master to release-0.34.x

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Copies over #11662

### CODE REVIEW

**Comment by tlrobinson** [comment]
@paulrosenzweig @camsaul I know this was already merged to `master`, but does this fix really belong in the frontend or should the SQLite driver be fixed to be consistent with other drivers?

**Comment by paulrosenzweig** [comment]
@tlrobinson yeah I figured that this was a sensible change either way, but called that out in a comment on the issue.

I looked at the SQLite driver a bit and the datetime/date logic looked like it was working around some quirks, so I figured this was the easier change.

**Comment by camsaul** [comment]
I agree with @tlrobinson, it would make more sense to tweak the SQLite driver to return consistent result

**Comment by paulrosenzweig** [comment]
Here's an issue to track that SQLite driver change: #11703

**Pull request merged**
