### PR TITLE
Add checksum for migration

### PR DESCRIPTION
**Pull request by dpsutton**
I don't understand why this is an issue but it blew up for me so
rather safe than sorry

### CODE REVIEW

**Comment by dpsutton** [comment]
Really doesn't make sense to me. I don't believe this has changed at all as far as i know.

**Comment by camsaul** [comment]
Are you sure you didn't run a different version of that migration locally at some point? I don't think I've ever seen Liquibase randomly change a checksum on us for no reason. If you look in the databasechangelog table does it give you more info about the version it thinks it ran?

**Comment by dpsutton** [comment]
closing as i think this was from a prior version of this migration.

liquibase doesn't allow for `renameSequence` operations on mysql and/or h2 even if you have preconditions on the dbms type preventing it from running; it will always blow up with an unsupported operation.

**Comment by dpsutton** [comment]
good catch @camsaul

**Pull request closed without merging**
