### PR TITLE
Sync table.columns to query's fields clause + additional fields

### PR DESCRIPTION
**Pull request by tlrobinson**
* [x] sync `table.columns` setting to dataset query's `fields` clause
  * [x] only for raw data queries (not aggregation or breakout)?
* [x] UI for adding removed (or additional) fields back in

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers Please give this a try and let me know if you run into any issues.

1. When you hide a table column the visible columns will be synced to `query.fields`.
2. You can also add additional fields (either fields that were previously removed, or new fields connected by a foreign key, e.g. #3043).

**Comment by salsakran** [comment]
seems to work locally for me.

One of the big things that's odd is that the name of an FK field doesn't indicate where it came from. Would it make sense to have it be labeled <FK Name>.<FieldName>? Thoughts @mazameli @kdoh ?

**Comment by tlrobinson** [comment]
For columns that are in the query I think it's using the result column name, so that it matches the column headers in the table.

**Comment by mazameli** [comment]
Seeing it again, it does feel like we should do something like `Product: Category` for FK-linked fields, especially for cases where you have fields with the same name. In fact, it looks like right now I can't add `Product: Created At` to the Orders table because it already has a `Created At` field. 

Tom's right that we don't do that when you break out by a linked field, but you could argue that we should, or that it's less necessary in that case because the query builder shows the breakout fields.

**Comment by tlrobinson** [comment]
@mazameli do you think we should change the column headers to include the FK name, or only in the chart settings?

**Pull request merged**
