### PR TITLE
Give all groups root collection r/w perms

### PR DESCRIPTION
**Pull request by camsaul**
thoughts and concerns?

### CODE REVIEW

**Review by salsakran — APPROVED** [review]
looks reasonable. @mazameli  did you still have an application db from 0.29.3 you could use to verify this works as advertised?

**Comment by mazameli** [comment]
Yep. I'll test it out right now.

**Comment by mazameli** [comment]
Everything looks right except that non-admins are being given access to the _migrated_ collections. Expected behavior is that only admins should have access to those.

The goal is to give everyone access to the root collection, leave existing collections unchanged, and lock down the new "migrated" collections to admins only.

screen shot 2018-08-01 at 2 47 23 pm

**Comment by camsaul** [comment]
Oops. Give me one second

**Comment by camsaul** [comment]
@mazameli ok, try again pls

**Comment by mazameli** [comment]
Looks correct now. Thanks, Cam. 👍

**Pull request merged**
