### PR TITLE
update postcss deps

### PR DESCRIPTION
**Pull request by daltojohnso**
This PR updates our postcss dependencies as they were all _old_, like 5 years old. We skipped this back when updating webpack and babel, but updating postcss ended up being simpler than anticipated... at least the build works 🙂 

Please play around with this branch to see if any styles are messed up.

Here's all the things I changed:

- Upgraded all postcss-related deps to latest
- Removed webpack-postcss-tools as it is no longer used in `postcss.config.js`
- Replaced deprecated package `postcss-cssnext` with its replacement `postcss-preset-env`
- Rewrote `postcss.config.js` to conform to what `postcss-preset-env` expects
- Rename `color` function found in css to `color-mod`, which is what the latest from `postcss-color-mod-function` expects
- Explicitly list `postcss-custom-media` in the postcss config, as it stopped worked for whatever reason.

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot run visual tests

**Comment by alxnddr** [comment]
@daltojohnso it appears there are tiny [visual changes](https://percy.io/6a8dd5c9/metabase/builds/13782468/changed/780218080?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=1280) in the question view header:
- increased padding 
- collection name vertical alignment

**Comment by flamber** [comment]
I don't have access to Percy, but breadcrumbs are being updated in PR 18903, so perhaps that would address (some) of this?

**Comment by alxnddr** [comment]
@flamber I've sent you an invitation to Percy. Yes, 18903 may address the issues. However, having them here is a sign that something has changed with CSS, and we can regress in other areas — just worth checking

**Comment by daltojohnso** [comment]
@metabase-bot run visual tests

**Comment by daltojohnso** [comment]
https://github.com/metabase/metabase/pull/18860/commits/3dd86fef1b43365eb6818bc2e4da1be37e496aee and https://github.com/metabase/metabase/pull/18860/commits/f78ea87323b2ddd5bc4592b88db0d9af3c64a0f2 seem to fix things -- the postcss config was slightly wrong, and doing `-var(--foo)` no longer works so I had to replace it with `calc(-1 * var(--foo))`.

Seems like the rest of the failed percy tests are from time differences

**Review by alxnddr — APPROVED** [review]
Great job 👏

**Pull request merged**
