### PR TITLE
Feature/copy to clipboard

### PR DESCRIPTION
**Pull request by viuts**
Added a new options in download widget to able to copy result directly into clipboard

format is compatible with google sheet / excel, can directly copy & paste without download the csv and import.

Screenshot 2019-12-30 at 7 29 30 PM

### CODE REVIEW

**Comment by mazameli** [comment]
Thanks for the contribution. Before we consider merging this, can you elaborate on your use case? I'm not certain this would be a universally applicable or desirable addition.

**Comment by viuts** [comment]
> Thanks for the contribution. Before we consider merging this, can you elaborate on your use case? I'm not certain this would be a universally applicable or desirable addition.

Yeah sure, our company is using metabase as BI tool.

As an operation associate, they are performing query very in a short interval, and usually they will some external dependencies which require copying out the result and paste to google sheet / excel to furture compute the result. (e.g. calculate the price based on price table in excel). They usually need to perform this action 60-100 times per day, which downloading as csv & open & copy is very painful.

As a business analyst, also will have a lot of predefined figures which only require data to pipe in, and usually those are in excel format as well (e.g. monthly report), which may have up to 10 sheets and again need to download 10 times is quite painful as well.

The initiative is from [This issue](https://github.com/metabase/metabase/issues/4425)

**Comment by kdoh** [comment]
Hi @viuts. I think for right now after considering this a bit further I'm going to have to decline this PR as is. I understand the use case for your team, but I'm not sure I'm a fan of mixing the other file formats and copy / paste in that download popover for most MB users.

From a product design standpoint I'd probably want the copy / paste to be more closely associated with the table itself (hitting download to copy feels semantically weird). Thanks for doing this to raise your copy / paste needs, I do think copying and pasting from MB could / should be better.

If I can come up with something that feels a bit more natural I'll reopen this PR and reply with it, but I can't give you a current timeframe on when that would be.

**Comment by keewi** [comment]
I'd be very interested in this feature. I use Metabase for product analytics and BI and often copy+paste results for investigative queries into a Google sheet to share or further analyze (looking at 10-30 queries over one sitting). I currently have to download as a CSV, open it, and then copy+paste which feels tedious after running a few in a short period of time.

What are your thoughts on having the copy-to-clipboard icon next to the download button (see the bottom-right of the attached image)? It seems that all of those buttons currently interact with the results somehow, and it would make my workflow significantly more seamless. The icons can be further ordered by how often people use them (ie. right of the download button if it's not used as frequently).
Screen Shot 2020-01-21 at 11 50 04 AM

**Comment by keewi** [comment]
@kdoh what are your thoughts on this?

cc @viuts

**Comment by brettdavies** [comment]
This functionality would be very helpful. For my use cases, being able to copy the result set to the clipboard while retaining col/row formatting is crucial. Not being able to do this is an unexpectant deficiency compared to google sheets, excel, and other BI tools that I've used throughout the years.

**Comment by tomas-kucera** [comment]
Adding my vote for this ... it is helpful, when doing some quick data analysis and want to copy / paste some data into excel / google sheets. Not always export to xlsx is the best.

**Comment by flamber** [comment]
Please go and upvote #4425

**Pull request closed without merging**
