### PR TITLE
Add legends to bar chart 

### PR DESCRIPTION
**Pull request by suhastech**
We are using metabase at @signeasy. We think it's amazing.

We thought of adding legends to the bar and line charts as stated it #1454

After this, we can also use it add it in the annotation using this commit https://github.com/signeasy/metabase/commit/6c7e18a3a4ba9dbeb6f39a2980ed0809a615caa5

It will now look like 

screen shot 2015-11-19 at 3 13 40 pm

I'm not sure about the design goals you have. I thought I'd drop it here.

### CODE REVIEW

**Comment by agilliland** [comment]
Hi @suhastech , thanks for submitting this.  We appreciate the contribution.  We'll pull this down and test it out in the next couple days.

Just a heads up that we have a pretty rigid design process that we follow and so part of the PR review will involve a design and UX approval on top of actual code review.

**Comment by pygeek** [comment]
Some code can be simplified: see https://github.com/signeasy/metabase/pull/7

**Comment by MartinArens** [comment]
+1

**Comment by GSeva** [comment]
+1

**Comment by R-Campbell** [comment]
+1

**Comment by pygeek** [comment]
Was this tested? Has this gone through the UI/UX process?

**Comment by agilliland** [comment]
Hi @suhastech , sorry for not being more engaged here.  We are still working on getting a good process in place for more impactful contributions like this one.

I'm going to go ahead and close this specific PR now because it has become outdated and Metabase has made lots of charting improvements over the past couple releases both at the code level as well as on the charting UI.  We've got a lot more improvements coming in v0.16.0 as well.

**Pull request closed without merging**
