### PR TITLE
Reposition convert to SQL trigger in header

### PR DESCRIPTION
**Pull request by kdoh**
Screen Shot 2019-08-13 at 3 57 57 PM

### CODE REVIEW

**Comment by flamber** [comment]
@kdoh Took me a little time to actually find the new location. Fixed doesn't like scroll:
image

**Comment by RMMSecurity** [comment]
@kdoh @flamber I've noticed weird things with scrolling as well. 

Switch to notebook mode and create a join with anything at all. Click the fields on the first table and scroll down to uncheck a few at the bottom. The first works, but used to cause your screen to scroll back up. Now if you uncheck another it'll uncheck it at the mouse position if you scrolled all the way back up and clicked.

**Comment by flamber** [comment]
@RMMSecurity It sounds like you're using RC1. Since `Fields` is now called `Columns`. But fairly sure the issue you're talking about was fixed by PR #10497. I'm not seeing the issue on latest `release-0.33.x`. You might upvote #10460 too.

**Comment by RMMSecurity** [comment]
@flamber I'm actually on the "release-0.33.x" branch. Using the latest commit as of eb70656

I'll check master, but it was actually working as intended so it's probably recently been broken somewhere along the way.

**Review by mazameli — CHANGES_REQUESTED** [review]
As others have mentioned, the positioning of this icon gets weird once the notebook starts needing to scroll. I guess it would either need to move down as you scroll so that it's in the bottom-right; or would need to be horizontally aligned with the Visualize button, in which case it wouldn't always be at the very bottom of the screen.

image

**Review by mazameli — APPROVED** [review]
image

Yeah, I think this is an improvement over what we currently have in place.

**Pull request merged**
