### PR TITLE
Data stories [WIP]

### PR DESCRIPTION
**Pull request by sbelak**
I've added a couple of mock data stories to a number field xray and time series xray to kickstart the discussion. 

```clojure
:data-stories {:noisy {:noise {:value 0.3
                                                 :description "Noisy data is highly variable jumping all over the place with changes carrying relatively little information."
                                                 :link "https://en.wikipedia.org/wiki/Noisy_data"}
                                             :quality "very"
                                             :recommended-resolution "month"
                                             :direction "up"}      
                         :gaps {:quality "some"
                                     :mode "missing"
                                     :filter [= ["field-id" 14] null]}                    
                          :regime-change {:breaks [{:from "beginning"
                                                          :to (t/date-time 2015)
                                                         :shape "linear"
                                                         :mode "increasing"}
                                                         {:from (t/date-time 2015)
                                                          :to (t/date-time 2017)
                                                         :shape "exponential"
                                                          :mode "increasing"}
                                                         {:to "now"
                                                          :from (t/date-time 2017)
                                                         :shape "linear"
                                                         :mode "decreasing"}]}
                               }
```

~~Each story comes in 2 formats: parametrized and as a string. For the sake of iteration speed it would be great if we wouldn't have to special case each data story on the frontend, however the more I think about it, the less I think that's plausible. If we take for example timeseries/smoothness, it would be very smooth (pardon the pun) to have "try smoothing it" and "month resolutions" be links that do that for you; number/gaps could have a link to rows in the table where value is nil, ... It would also be nice to have tooltips over words which require a definition (in the present examples "normal value", "smoothness" are good candidates), like we already do with feature definitions now, but here one story can intertwine multiple concepts/kpis.  If we go for pre-written option, it still makes sense to pass parameters along so that we can for example annotate charts (timeseries/regime-change is a good candidate for that).~~ [settled on parametrized responses]

### CODE REVIEW

**Comment by salsakran** [comment]
I think we should use "insights" or "magic-genie" or something similar to differentiate it from our stories concept (ask @mazameli if you're curious).

I think the format makes sense. Random aside are dashes being converted to underscores in serialization? If not, we should standardize on something that's parsable in js land without having to quote map keyes.

I like the idea of automatically tagging concepts with wikipedia entries. Let me think about a way to do that ...

**Comment by sbelak** [comment]
Sure, the name was the first thing that sprang to mind during the discussion. 

With the format you mean the parametrized version (there are 2 versions for each case to illustrate the 2 approaches).

We already do the wikipeda linking that for proper features (see metabase/src/metabase/feature_extraction/descriptions.clj), we can adopt the same mechanism. In the example above is :smoothness would have an entry in descriptions it would get changed to
```
{:value 0.3
 :label "smoothness"
 :description "Measure of how smooth a dataseries is. Calculated as normalized standard deviation of differences"
 :link "https://link.springer.com/chapter/10.1007%2F3-7643-7582-5_1"}
```

We don't translate dashes. Will change in a separate PR if needed (Clojure Baby Jesus will cry though).

**Comment by salsakran** [comment]
is there a url I can hit to see the results working?

**Comment by sbelak** [comment]
If you hit an x-ray for any numerical field you'll see the 2 (hardcoded atm) examples.

**Comment by sbelak** [comment]
Added tooltip data (same protocol/format as tooltips for other xray features) and filter for "view these X" to examples.

**Comment by attekei** [comment]
The insights frontend proto looks now like this:

screen shot 2017-10-23 at 14 24 26

screen shot 2017-10-23 at 14 24 15

We should definitely improve the copys, these are still example insights on mock data

**Comment by sbelak** [comment]
Merged into #6266

**Pull request closed without merging**
