### PR TITLE
Fix issue with joins in BigQuery driver #4218

### PR DESCRIPTION
**Pull request by jvdweerthof**
Simple fix for issue  #4218

##### Disclaimer
My goal was to quickly fix something we ran into in production, without diving too deep into code. This is my first attempt at Clojure and Metabase... Open to any tips that will help get the pull request merged.

### CODE REVIEW

**Comment by salsakran** [comment]
Hello @jvdweerthof -

Thanks for the help!

It would be great if you could add a test that shows the specific bug in #4218 that passes with this PR.

**Review by camsaul — CHANGES_REQUESTED** [review]
we should add a test for this

**Comment by hden** [comment]
Suggestion: perhaps uncouple database feature `:foreign-keys` into
1. `infer-foreign-rels`
2. `join-foreign-rels`

where most RDBMS support both.

Then we can reuse tests defined in `metabase.query-processor-test.joins-test` by `(engines-that-support :join-foreign-rels)`

**Comment by vbronsky** [comment]
@camsaul What kind of test?

**Comment by camsaul** [comment]
a test demonstrates #4218; one that would fail before the fix was in place and would pass after. To verify that the issue is fixed and to prevent regressions

**Comment by vbronsky** [comment]
@camsaul  
So when that issue could be solve? Any chance to add this fix to release?

I'm still have an error and our company cant' work with metabase:
Field 'METABASE_DATA.SKU__via__SKU_code.Trade_group_in_price_model' not found on either side of the JOIN

We tried to patch this byself but we had a lof of erorrs after compilation.

**Comment by camsaul** [comment]
@jvdweerthof I went ahead and added a test to this and opened a new PR #6610. Thanks for your contribution!

@vbronsky We should be shipping this as part of our upcoming release 0.28.0

**Pull request closed without merging**
