### PR TITLE
Trendlines multiseries [WIP]

### PR DESCRIPTION
**Pull request by tlrobinson**

### CODE REVIEW

**Comment by mazameli** [comment]
Looks like this doesn't work for time series with a second breakout? I'm getting `Cannot read property 'Symbol(Symbol.iterator)' of object`

screen shot 2018-10-16 at 5 39 07 pm

**Comment by mazameli** [comment]
This icy blue color's trend line is pretty rough to see:

screen shot 2018-10-16 at 5 42 47 pm

**Comment by mazameli** [comment]
Is it an expected/known limitation of this PR that you can't do trend lines for a single aggregation with two breakouts? Example:

screen shot 2018-10-17 at 11 34 18 am

**Comment by mazameli** [comment]
Turning stack-100% on with trend lines causes this error: `Cannot read property 'Symbol(Symbol.iterator)' of undefined`. Seems like those are probably mutually exclusive settings.

screen shot 2018-10-17 at 11 38 39 am

**Comment by tlrobinson** [comment]
> Is it an expected/known limitation of this PR that you can't do trend lines for a single aggregation with two breakouts?

Yes. The backend doesn't return insights in that case.

**Comment by tlrobinson** [comment]
Moved to #8709

**Pull request closed without merging**
