### PR TITLE
if request comes with an API key, it is CORS-safe

### PR DESCRIPTION
**Pull request by sansolovyov**

### CODE REVIEW

**Comment by npretto** [comment]
I think this could collide with a project we're working on in the embedding team, let me ask on our team channel

**Comment by escherize** [comment]
Is there a product doc or similar for this bit of work? I'd like to review it to make sure it'll work when we land https://github.com/metabase/metabase/issues/46970.

**Comment by npretto** [comment]
> Is there a product doc or similar for this bit of work? I'd like to review it to make sure it'll work when we land #46970.
@escherize  sorry I didn't link the slack discussion here before, it's currently being discussed here: https://metaboat.slack.com/archives/C063Q3F1HPF/p1726735292342709

**Comment by romeovs** [comment]
I haven't tested it, but I'm not sure this will actually work for the use case we wanted to use this for (the Google Sheets hackaton project).

To test whether or not a request is allowed for CORS the browser sends a preflight request to probe the server. The preflight request does _not_ contain the actual `X-API-Key` header.

This means that Metabase will not see the `X-API-Key` header and will this deny the CORS request (ie. not return the current origin as being allowed).

**Comment by piranha** [comment]
Doesn't make sense in the current form then :(

**Pull request closed without merging**
