### PR TITLE
How loading up huge app-dbs should work

### PR DESCRIPTION
**Pull request by escherize**
Adresses: #44922

This PR introduces a new namespace `src.dev.add-load` that provides a utility for generating and loading test data in the app-db for Metabase. It works similarly to `with-temp`, but uses a data oriented api, and is not limited to ~400 inserts at a time, because it does not use the program stack to track every single insertion.

Checkout [the docstring](https://github.com/metabase/metabase/pull/46214/files#diff-815d2335d3813ebce8b35fa057fbdb9cf5c9f3d34f06ba4c7df5ed5f262160b0R31-R105) for the rationale.

### CODE REVIEW

**Comment by qnkhuat** [comment]
nice stuff, have you looked at https://github.com/metabase/metabase/blob/a792ca29d934b4f813b68b826f72552ab34999b8/enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj#L115 ?

**Comment by piranha** [comment]
That's a cool idea! I think it would be cool to use this as a`with-temp` backend, so for one-off cases you won't need to write destructuring.

Also, in lieu of Ngoc's remark, have you seen [datapotato](https://github.com/donut-party/datapotato)? It's what (archived) specmonstah repo recommends now, and I wonder if it would make sense to employ this to generate more random data in our tests.

**Comment by escherize** [comment]
I think making it easy to write bigger, more complex scenarios is a win, whether we end up using datapotato or however it happens. 

This approach can be the foundation for the [kitchen-sink instance]() too, because in this world, the kitchen sink is simply a longer list of 3-tuples, similar to how `mt/with-temp` takes them.

For load-testing we can focus on adding e.g. 10000 users, or permissions, and link them together quite simply doing it in a data-oriented way makes that extremely easy. Examples are in the docstring for [from-script](https://github.com/metabase/metabase/pull/46214/files#diff-815d2335d3813ebce8b35fa057fbdb9cf5c9f3d34f06ba4c7df5ed5f262160b0R30).

**Comment by escherize** [comment]
I don't want to see this in the github "needs review" posting, but still think it's good.

**Pull request closed without merging**
