### PR TITLE
Adding Model to Cypress Snapshot

### PR DESCRIPTION
**Pull request by npfitz**
This PR adds a model to the Cypress Sample Dataset, something done in preparation for the Audit V2 feature (which will seed models of instance data). An unfortunate side effect of this is that the Data Selector will act much differently with a model in the sample dataset. This PR attempted to make as many tests agnostic to the environment as possible, using the `openTable` function rather than `startNewQuestion` and navigating the data selector.

### CODE REVIEW

**Comment by iethree** [comment]
I have some theoretical misgivings here. This leaves the model-less instance behavior mostly untested, right? do we maybe just want to remove that behavior altogether?

**Comment by npfitz** [comment]
That is true, and OSS will still have the ability to be model-less. I could try to add some tests around the dataselector that test that scenario, though you could say the same about a question-less scenario too :/

**Review by iethree — CHANGES_REQUESTED** [review]
We discussed this, and decided that we need to add some model-less tests to make sure we maintain coverage on the model-less version of the data picker.

**Comment by iethree** [comment]
Added a new snapshot to the setup process: `without-models` and add a few tests against that snapshot to make sure we have coverage on a model-less instance.

**Review by iethree — APPROVED** [review]
👍

**Pull request merged**
