### PR TITLE
Add query_hash column and indexes, use for /api/dataset/duration endp…

### LINKED ISSUE #2793: Optimize query for /api/dataset/duration endpoint
We query for the 10 most recent (`started_at`) query executions filtered by the JSON query dictionary (`json_query`), which can take a long time on instances with many query executions, which in turn causes "slow card" warnings to take longer to appear than they should.

Possible solution:

Instead of querying by the full JSON object we should store a hash of the query dictionary in a separate column, and put indexes on both that column and `started_at`.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #2793

### CODE REVIEW

**Comment by agilliland** [comment]
This looks sensible to me.  Do we know what the maximum value is that is returned by `(hash)`?  If that value is big enough then you might want to use a larger column type here than `int`.  Seems safer to use `bigint`.

Otherwise lgtm 👍

**Comment by tlrobinson** [comment]
I think @camsaul looked into it and said it should map fine to `int`.

I've got a couple other fixes I'm about push.

**Comment by camsaul** [comment]
`hash` returns a `java.lang.Integer` which is 32-bit just like SQL `INTEGER` type

**Comment by agilliland** [comment]
looks fine to me

**Pull request merged**
