### PR TITLE
Proposal: no more prefix namespaces

### PR DESCRIPTION
**Pull request by camsaul**
T H O U G H T S?

### CODE REVIEW

**Comment by sbelak** [comment]
Why? I like prefixes, way less line noise.

**Comment by camsaul** [comment]
@sbelak I agree about the line noise. I think non-prefix ns declarations have a few benefits:

*  It's a lot easier to grep the codebase to see where a namespace is used -- this is my main motivation (I was trying to move some namespaces around in #14279, and kept missing places
* it leads to smaller git diffs/less merge conflicts
* it's easier to understand, and to do by hand. I feel bad for anyone not using `clj-refactor` to do it automatically
* Namespaces have no hierarchical relationship in reality, so a flat list better reflects how things actually work (Stuart Sierra mentioned that [here](https://stuartsierra.com/2016/clojure-how-to-ns.html#prefix-lists))
* It seems like the vast majority of the Clojure community is on the side of side of not using prefix lists. So it would make the Metabase codebase a bit more "normal" or "boring" if we went this route.
 
I think there are pros and cons to both prefix and non-prefix styles but I think the non-prefix benefits outweigh the prefix ones.

Interested in hearing more thoughts

**Comment by camsaul** [comment]
I was under the impression no one really liked prefixy namespace declarations that much, so a PR like this was on my TODO list for a while. It only took me maybe 10 minutes to do tho in Emacs so if we decide we prefer prefixes we can toss this PR

**Comment by camsaul** [comment]
Here's another added benefit: this PR removes almost 1200 LoC which in its own way is a bit less noise.

```clj
[metabase
  [db :as mdb]
  [u :as u]]
```

is more lines than

```clj
[metabase.db :as mdb]
[metabase.u :as u]
```

**Comment by dpsutton** [comment]
I'm a big fan of the flat style imports. Far easier to sort. I hate when adding a new namespace changes a flat import to a nested one and it can change the order in the ns list as well. Much easier to find usages just using grep or ag.

**Comment by tsmacdonald** [comment]
I'm in favor of this PR (but would be fine either way). Having a less-nested data structure to deal with is nice, and I second the points Dan raised.

**Comment by tsmacdonald** [comment]
image
Yeah, saving 1200 LOC isn't bad…

**Comment by sbelak** [comment]
Fair. I'm not a strong no to begin with

**Comment by camsaul** [comment]
Cool. If we decide to merge this it's going to be a cause a little bit of disruption for any in-flight PRs. But I guess there won't ever be a time where that's not the case

**Comment by sbelak** [comment]
Perhaps do it after we ship 38

**Comment by camsaul** [comment]
I want it to make it to the `release-x.38.x` branch so we don't end up dealing with two different namespace declarations styles for 2 or three months

I could do that after we cut the release tho

**Comment by camsaul** [comment]
GitHub gist for the code I used to do this is here https://gist.github.com/camsaul/c9036017d499e347c654636e279883af

(this is mostly a note to self so I don't lose it)

The whole thing in Emacs took maybe 5 minutes to run

**Review by robdaemon — APPROVED** [review]

**Review by tsmacdonald — APPROVED** [review]
:confetti_ball:

**Review by sbelak — APPROVED** [review]

**Pull request merged**
