### PR TITLE
Externalize backend strings

### PR DESCRIPTION
**Pull request by senior**

### CODE REVIEW

**Comment by mazameli** [comment]
Ryan, I'm not sure how to translate the strings in this file, starting at line 78: /Users/maz/workspace/metabase/src/metabase/api/table.clj

That has the datetime granularity option strings and the binning strings.

**Comment by senior** [comment]
@mazameli I've externalized all of the dimension options strings. Looks like there's a bunch of reflection warnings from the i18n library that is causing CI to fail. I'll get those fixed up along with the merge conflict.

**Review by mazameli — COMMENTED** [review]
This generally looks right to me, but there are a few lines of clojure that I'd be more comfortable with @camsaul looking at, e.g.:

(log/warn (trs "Warning: endpoint {0}/{1} does not have a docstring." (ns-name *ns*) fn-name)))

**Review by camsaul — APPROVED** [review]
Looks fine to me

**Pull request merged**
