### PR TITLE
Support all timezones

### PR DESCRIPTION
**Pull request by qqshfox**
Use the available timezone ids from system instead of hardcoded ones.

### CODE REVIEW

**Comment by camsaul** [comment]
This makes sense let me try this locally

**Review by camsaul — CHANGES_REQUESTED** [review]
If we're fetching the results from a function I'm not sure if it makes sense to keep them in memory collecting dust when we could fetch them again whenever we need them. The call to `(t/available-ids)` takes let than 10 microseconds on my system.

On my system I have about 600 timezones which based on my calculations (see this [SO post](https://stackoverflow.com/questions/31206851/how-much-memory-does-a-string-use-in-java-8)) would use something like 41 KB of memory, which isn't huge but not something I would want to commit to permanently tying up for no reason (these sorts of things add up).

I think we should delete the namespace entirely and replace the lone reference to `metabase.models.common/timezones` with a call to `t/available-ids`. 

WRT to there being 600 timezones -- how would this affect the UX? @mazameli @tlrobinson I don't think we have search in the timezone drop down, right? We'd definitely want to add it if we were giving people 600 options

**Comment by camsaul** [comment]
Bump @mazameli @tlrobinson

**Comment by camsaul** [comment]
@kdoh @tlrobinson any thoughts on how we should display 600 timezones? Is that something we'd even want?

I like the idea of letting people choose whatever timezone they want as opposed to the ones we have in that list but we need to tweak the widgets and add a search box or something I think

**Comment by kdoh** [comment]
If we think allowing the system timezone set of options is the right call here (and I think it is but I'm not at all a timezone expert), but we can't be relatively certain about the length or the format of the things the system will return I think our `Select` with search populated by the system options is our only sane way to surface this. That will at least allow you to find what you need quickly by typing, but also browse the list if the format is weird or unexpected.

**Comment by tlrobinson** [comment]
FYI our `Select` component has a search option built-in (although i think the settings component uses the old version without search)

**Comment by kdoh** [comment]
@tlrobinson Yup that's the one I was referring to / we should use.

**Comment by mazameli** [comment]
@qqshfox Do you think you'll be able to make the [requested changes](https://github.com/metabase/metabase/pull/8943#pullrequestreview-186346988)?

**Comment by camsaul** [comment]
@qqshfox ?

**Comment by mazameli** [comment]
In order for this PR to be merged, [these changes](https://github.com/metabase/metabase/pull/8943#pullrequestreview-186346988) need to be made:

>If we're fetching the results from a function I'm not sure if it makes sense to keep them in memory collecting dust when we could fetch them again whenever we need them. The call to (t/available-ids) takes let than 10 microseconds on my system.
>
>I think we should delete the namespace entirely and replace the lone reference to metabase.models.common/timezones with a call to t/available-ids.

It's been a long time since any changes have been made to this PR, so I'm closing it for now, but we'll happily reopen it if the requested changes and merge conflicts are resolved. Thanks!

**Pull request closed without merging**
