### PR TITLE
Nested collection item pickers [WIP]

### PR DESCRIPTION
**Pull request by tlrobinson**
This implements an "item picker" component that supports nested collections, and uses it everywhere we need to pick a collection, question, dashboard, etc.

picker component:
* [x] basic nested picker implementation
* [x] fix scrolling
* [x] search
* [x] nest personal collections
* [x] inherit select button width

collection contents listing:
* [x] move: pick collection

collection
* [x] create/edit: pick (parent) collection

dashboard:
* [x] create modal: pick collection
* [x] move button: pick collection
* [x] add question button: pick question
  * [x] make non-full modal

question:
* [x] save modal: pick collection
* [x] move button: pick collection
* [x] add to dashboard button: pick dashboard

pulse 
* [x] create/edit: pick collection
* [x] create/edit: pick question
  * [ ] reimplement raw data warnings etc

### CODE REVIEW

**Comment by tlrobinson** [comment]
@kdoh I could use some help figuring out scrolling (both in the "select" components and modals, they both use `ItemPicker` internally)

@mazameli @kdoh I think i've found all the places this should be used but let me know if you find any I've missed or notice any strange behaviors. It ended up being a fairly big change for various reasons.

Also I still need to implement search. @kdoh mentioned just putting a search icon to the left of the breadcrumbs which swaps the crumbs for a search box. Does that still sound reasonable? Should it be a typeahead or just when you hit enter?

**Comment by kdoh** [comment]
@tlrobinson This is looking really good. 

Biggest thing I'm noticing aside from scrolling (which I'm been poking at this morning) is just a couple contexts like pulses and selecting parent collections from new ones the size jumps around so we'll want to standardize that to a single width. In both cases I think it inheriting the width of the element that triggered it is the right call.

We should also make sure the add to dashboard modal is no longer full width so it's a similar experience to the other non select modals.

Search wise that's still my best idea, I'd go with on enter since it can reuse the search endpoint and be similar to what we have in the global nav and there are fewer questions around statefulness there. I do want to get typeahead going for all our search contexts eventually but let's bite off one piece at a time.

**Comment by mazameli** [comment]
When trying to save a new question and picking its destination collection, I can't scroll this popover:

screen shot 2018-07-06 at 10 21 33 am

**Comment by tlrobinson** [comment]
It would have been nice if the API returned personal collections in "Personal Collections" pseudo-collection (just a collection that no one has curate permissions for seems sufficient) so we didn't have to put that logic in the frontend, but oh well.

**Comment by tlrobinson** [comment]
I've implemented basic searching, cleaned up the personal collections, made the ItemSelect content match the button width, and made the add question to dash modal non-full page.

@kdoh I could still use some help with the scrolling issue.

@mazameli @kdoh let me know what you think of the search experience. it could probably use some polish

**Comment by mazameli** [comment]
Seeing this when trying to change where a collection is saved:

screen shot 2018-07-11 at 4 21 07 pm

**Comment by mazameli** [comment]
One thing that feels tricky about moving a dashboard is that the Move modal doesn't start out by highlighting the collection where the dashboard is currently saved so it's hard to get oriented. (This is exacerbated by the fact that the dashboard doesn't have a badge on its detail view to show where it's saved.)

**Comment by mazameli** [comment]
Pulse edit form:

screen shot 2018-07-11 at 4 33 18 pm

**Comment by mazameli** [comment]
As Tom mentioned, we need to dial in the color and size of search result icons:

screen shot 2018-07-11 at 4 29 47 pm

screen shot 2018-07-11 at 4 34 55 pm

**Pull request merged**
