### PR TITLE
Translate the UI of datetime picker

### PR DESCRIPTION
**Pull request by mshen7310**
The UI of date time picker contains English text under non-English locale setting, due to the default locale setting of moment js. To fix this,
1. Call moment.locale to set the correct locale before calling moment.format
2. Add tagged text to clojure and js code
3. Update po file

### CODE REVIEW

**Review by tlrobinson — CHANGES_REQUESTED** [review]
@mshen7310 Thanks for working on this. It's a good start but I left a few suggestions for things to fix/improve.

**Comment by tlrobinson** [comment]
I went ahead and made these changes in #9071

**Comment by mshen7310** [comment]
Thanks for you quick response. I will go back and merge you latest changes.

**Comment by mshen7310** [comment]
The pull request is closed, as #9071 has implemented the feature already.

**Pull request closed without merging**
