### PR TITLE
i18n(App) syntax errors found while translating

### PR DESCRIPTION
**Pull request by joebordes**

### CODE REVIEW

**Review by camsaul — APPROVED** [review]

**Comment by camsaul** [comment]
we need to update `metabase.api.session-test/google-auth-token-info-tests`

**Review by camsaul — CHANGES_REQUESTED** [review]
Need to update tests (See my past comment for the specific tests to update)

**Comment by joebordes** [comment]
I'm not sure if those comments are for me but, just in case, I will not be looking into the tests code.

**Comment by rlotun** [comment]
Thanks for the contribution and apologies for the delay in circling back to it! I've included this in an updated PR since it's been so long: https://github.com/metabase/metabase/pull/19481 - closing this one in favor of that. 🙏🏽

**Comment by joebordes** [comment]
:-)  Merry Christmas

**Pull request closed without merging**
