### PR TITLE
Fix segments in case custom expressions

### LINKED ISSUE #24922: Can't use segments in case function for custom columns value
**Describe the bug**
Hi there, 

I have a custom column created with an older version of Metabase using a case function. After upgrading it seems like if I try to edit it normalizes the value to some invalid format and I can no longer query the data. 

This is the value that it works -> https://vertis.d.pr/ouisBv

Once I edit something, it gets transformed into https://vertis.d.pr/lnwzfe which is invalid, giving this error https://vertis.d.pr/6uox2m

I have to mention that all values are Segment names, not columns.

**Logs**
```
Input to resolve-card-id-source-tables* does not match schema: [0;33m [(named {:query {:expressions {"Revenue Category" (named [nil (named [[(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil] [(named (named [nil (named [(named (not (= :value :segment)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "pred") nil]] "clauses") nil] "Must be a valid instance of one of these clauses: :+, :-, :/, :*, :coalesce, :length, :floor, :ceil, :round, :abs, :power, :sqrt, :exp, :log, :case")}}} arg0)] [0m
```
**To Reproduce**
1. Go and create one segment
2. Start a question and add a custom column
3. use a case switch for that column values, i.e = `case([Segment name],'Segment','Others')`
4. There is some normalization which is happening it gets turned into `case([Segment name] = True,'Segment','Others')` which breaks the query.

**Expected behavior**
The normalization should not break the query.

**Screenshots**
- Working format  https://vertis.d.pr/ouisBv
- Invalid format  https://vertis.d.pr/lnwzfe
- Error https://vertis.d.pr/6uox2m

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: https://www.whatsmybrowser.org/b/EABJ3
- Your operating system: https://www.whatsmybrowser.org/b/EABJ3
- Your databases: MongoDB
- Metabase version: 0.44.1
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
The bug is blocking me from editing any query which uses segments in custom columns.

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/24922
Caused by https://github.com/metabase/metabase/pull/21342
Reproduces https://github.com/metabase/metabase/issues/24922

How to test:
- Follow the steps from the linked issue
- Or run the cypress test as it has the same steps

### CODE REVIEW

**Review by WiNloSt — APPROVED** [review]
The test passed, but I'm not entirely sure if this will cause other complications or not since, I'm not really familiar with that part of the code.

**Comment by nemanjaglumac** [comment]
@ranquild @flamber this issue doesn't have a milestone set, but it was backported. 
I've [approved the backport](https://github.com/metabase/metabase/pull/24976) but want to double check before merging it.

**Comment by ranquild** [comment]
@nemanjaglumac I thought that it was enough to set the milestone on the issue itself https://github.com/metabase/metabase/issues/24922

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac I thought that it was enough to set the milestone on the issue itself #24922

It is.
I was commenting from a phone earlier today and have most likely confused the issue with the PR. Sorry for the confusion.

**Pull request merged**
