### PR TITLE
CSV uploading [Experimental]

### PR DESCRIPTION
**Pull request by tlrobinson**
Drag a CSV file into Metabase to upload it and add it as a table which you can then query like any other table.
- [ ] Currently stores uploaded data in a SQLite database, since that was easiest. We should probably store them in the Metabase application database so they are persisted even on Heroku etc, however we can't just add the application database as a database in Metabase without filtering out the Metabase tables.
- [ ] Modal where you can specify whether the first row is column names, or name them yourself.
- [ ] Detect column types, parse numbers, etc (currently uses strings for everything)
- [ ] Currently we sync the whole "Uploads" database when adding a new file. Can we just sync a specific table?
- [ ] Only allow drag/drop if you're logged in
- [ ] Delete tables?
- [ ] Other formats?

### CODE REVIEW

**Comment by pygeek** [comment]
+1

**Comment by Germanaz0** [comment]
Where is that option ? I cannot see on master

**Comment by pygeek** [comment]
@germanaz0 this branch wasn't merged into master, the uplid_file branch was just fast-forwarded.

**Comment by Germanaz0** [comment]
I tested it a bit, uploaded a small csv and worked fine, but in the moment that I uploaded a big csv it did not work, I'm getting the following error:

```
03-22 15:38:28 ERROR metabase.driver :: Query failure: Assert failed: engine
03-22 15:38:28 DEBUG metabase.middleware :: GET /api/database/NaN/tables 404 (205 µs)
"GET /api/database/NaN/tables is not yet implemented."
```

This zip includes the csv file that I'm trying to upload.

[us-500.zip](https://github.com/metabase/metabase/files/184743/us-500.zip)

**Comment by tlrobinson** [comment]
@Germanaz0 we hadn't merged master into this branch in a few months. but I just did. Could you build the latest from this branch and try again?

I also haven't tested with large CSVs (this was really meant to be a prototype/experiment)

**Comment by Germanaz0** [comment]
Yes, I merged it into a master in a fork that I've but had that previous error, large csv does not work, but I love the prototype

**Comment by salsakran** [comment]
@tlrobinson + @agilliland 
Wanted to re-open conversation about this PR as I still think it's super interesting


**Open Questions**

_Where to store the files?_
Separate H2 Database - called “Uploads"

_Who can upload?_
Only Admins

_Is there a size limit to the CSVs?_
Yes - Admin defined, default to 10mb? Goal is to keep people from trying to upload a petabyte and killing the server

_Where should this feature live?_
In the "Uploads" database detail page. This keeps it from polluting the query builder
Alternative idea: A dedicated tab in the admin. 

**Additional features**

- Give the uploaded CSV/table a name - YES
- Is the first row column headers? - YES
- Detect types? - YES
- Delete tables - YES
- Other formats? - No


Thoughts?

**Comment by tlrobinson** [comment]
+1 I'd really like to see this happen.

_Where to store the files?_

Using H2 would be incompatible with PaaSs with read-only or non-persistent file systems such as Heroku. Could we just use a schema within the same database we use for Metabase's application database, or perhaps allow the admin to mark a database in `/admin/databases` as the "uploads" database? (any of the ones we support for the Metabase application database? Postgres, MySQL, H2?)

_Where should this feature live?_

I really like the idea of being able to drag and drop a CSV file on the query builder, especially for Mac app users (would also be nice to have a `File : Import` menu item in the Mac app).

**Comment by tlrobinson** [comment]
On second thought, I'm not sure we should allow an admin to mark a database in `/admin/databases` to be used for uploads, as it breaks the current (implicit? explicit?) "read-only" contract we have.

**Comment by salsakran** [comment]
Re: a separate db vs the main db, the thing I'd want to avoid there is a situation where someone can fill up the metabase db with csv's and break things. If it's a separate db, any errors will present themselves as query errors vs outright app errors.

I really like the mac file upload option.

The main reason I'm leaning towards having it be an admin action is that if a person keeps uploading working csvs, eventually the disk space used would grow out of control.

**Comment by agilliland** [comment]
_Where to store the files?_

This is the biggest issue for me, so I'd like to come to some consensus on this first because I think it generally shapes the feeling of the feature for the most part.  IMO this feature will be confusing and difficult to reconcile for users if you only allow them to upload files into a separate and stand-alone place.  So as a user I'd want to just pick one of my existing databases to upload it to.  In the case where I really just want something stand alone (or I don't have any databases) then I'd want Metabase to have a way where I can create a custom "Uploads" database, probably using H2, that can fulfill the need.

Obviously this approach contradicts Metabase's goal and general operating pattern of only using read-only connections to databases, but this operation is clearly a WRITE operation, so I don't really see any way to get around that.

I'm most opposed to the idea of putting this data in the Metabase application database because doing that has other implications which could negatively impact the app execution and it doesn't solve any of the other UX issues above.  So at this point I'm pretty strongly against this path.

So if I was proposing what I think is the most desirable user approach, it would be 1) a way to mark a database as writable, 2) when you upload you just pick one of your writable databases, and 3) we allow you to create a single H2 database for uploads if needed.

**Comment by kdoh** [comment]
I still would really love to do this, but given how much time has passed without activity on this I'm going to close this PR for now to reflect we're not actively working on it.

**Pull request closed without merging**
