### PR TITLE
Add `is-hosted?` setting based on metastore token

### LINKED ISSUE #17252: Expose the `hosting` setting and use it to identify if Metabase is running in Cloud
We have a few UI components that are shown only for self-hosted instances (e.g. an “Upgrade to Cloud” CTA banner) or for cloud customers only (the most recent one is [“Cloud” settings section](https://github.com/metabase/metabase/pull/17134) for admins).

Metabase FE has a function for that called [`isHosted`](https://github.com/metabase/metabase/blob/cadd71015baf2ebfcf21a37b9945c74d8a52f712/frontend/src/metabase/lib/settings.js#L93). We don't have a clear way to know if Metabase is self-hosted or is running in the Cloud. So currently, `isHosted` just checks if the `site-url` setting contains `metabaseapp.com`, which is pretty fragile.

The idea is to expose the `hosting` setting from metastore [the same way we do for e.g. `sso` or `whitelabel`](https://github.com/metabase/metabase/blob/master/src/metabase/public_settings/metastore.clj) and refactor `isHosted` to use this setting instead of checking a URL

### PR DESCRIPTION
**Pull request by noahmoss**
Exposes `is-hosted?` as a public setting on the backend that just checks whether the `hosting` feature is enabled for the instance's token. Changes the corresponding helper function on the frontend to return the value of this setting.

I've also removed the `ssoEnabled` setting since I noticed it's not being used anywhere, and it's semantically incorrect since it's just checking whether the Google Sign-in client ID is set.

### CODE REVIEW

**Comment by noahmoss** [comment]
This PR got stalled because of a weird behavior I can't figure out:

I've defined an `is-hosted?` setting in `metabase.public-settings.metastore`, and when I activate a token with the `hosting` setting, the value of the setting is `true` when I try to fetch it in a REPL.

But when I call `/api/setting` the value is `null`. I think this is why the e2e tests are failing.

Any ideas ass to why the value of the setting isn't being reflected in the API call?

**Comment by camsaul** [comment]
@noahmoss not sure why it would return different values... are you running a separate server process from your REPL? I think we cache the token features. Try restarting the server if it's a separate process?

**Review by camsaul — APPROVED** [review]

**Review by kulyk — APPROVED** [review]
🏆 ☁️

**Comment by kulyk** [comment]
The `cloud.cy.spec` tests fail because they still mock the `site-url` setting for the previous `isHosted` implementation, so we now need to mock the `is-hosted?` property. I tried to do that locally using `mockSessionProperty` tests but had no luck :(

The test looked like that:

```js
beforeEach(() => {
    restore();
    cy.signInAsAdmin();
});

it("should be visible when running Metabase Cloud", () => {
   mockSessionProperty("is-hosted?", true);
   cy.visit("/admin");
   // the rest of the assertions
});
```

`is-hosted?` setting is set to `true` eventually, but the first few `/api/session/properties` responses still return `false` for `is-hosted?` and the UI doesn't respond to the change. We can tweak the frontend, so it refreshes the setting sections in this case, but it would only help to workaround the behavior in Cypress without any benefit for a real environment (for cloud, it would always be `true`, I guess)

Hey @nemanjaglumac, we had the same problem while mocking `site-url`. Maybe you now have a better idea of how can we achieve that? I can't come out with a good solution here. I wonder if we should maybe disable these tests until we have a better solution? 🤔 At least we would be able to test Cloud-only now

**Comment by nemanjaglumac** [comment]
@noahmoss I am receiving this warning when building your branch:
`babel-loader@7.1.5" has incorrect peer dependency "webpack@2 || 3 || 4".`

Seems like you opened it before we upgraded babel? WDYT of rebasing it to the latest `master` just in case? We want to see if everything's working with the upgraded tooling.

**Comment by nemanjaglumac** [comment]
@kulyk We can't use that approach here. There is no endpoint to send the `PUT` request to, and mocking the session properties **or** the settings doesn't seem to work.

**Comment by noahmoss** [comment]
Updated with the fix for the bug I was experiencing in https://github.com/metabase/metabase/pull/17256#issuecomment-897076682

Also some automatic whitespace fixes in `metabase.models.setting`

**Comment by noahmoss** [comment]
@nemanjaglumac I've now merged Cam's PR into this one, so the backend bug in the settings code should be fully fixed. Do we still not have a good solution for mocking the setting in Cypress?

**Comment by kulyk** [comment]
Hey @noahmoss @nemanjaglumac,

I've tried using `mockSessionProperty("is-hosted?", true)` to emulate the Cloud environment, but had no luck this time too.

What I noticed, is that even with a recent backend fix, `MetabaseSettings.isHosted()` still returns `false` the first couple of times. I thought the settings are always relying on the`/api/session/properties`, but they don't. The initial settings are populated with `window.MetabaseBootstrap` (see [here](https://github.com/metabase/metabase/blob/6f8324debe17cd130adc30a23ba009f251b033fe/frontend/src/metabase/lib/settings.js#L297)) and it's `false` for `is-hosted?`.

`MetabaseBootstrap` value is retrieved from a `<script id="_metabaseBootstrap">` element on the page. Try to open browser developer tools when Metabase is opened and put `document.getElementById("_metabaseBootstrap")` in the console. You'll notice there is a `<script>` element on the page. It contains a JSON with initial setting values. It's generated by the backend [here](https://github.com/metabase/metabase/blob/6f8324debe17cd130adc30a23ba009f251b033fe/src/metabase/server/routes/index.clj#L78) and gets included into the `index.html` template [here](https://github.com/metabase/metabase/blob/6f8324debe17cd130adc30a23ba009f251b033fe/resources/frontend_client/index_template.html#L27). Then latest the frontend parses it and puts the JSON in `MetabaseBootstrap` variable [here](https://github.com/metabase/metabase/blob/6f8324debe17cd130adc30a23ba009f251b033fe/resources/frontend_client/inline_js/index_bootstrap.js#L2)

That explains why we can't easily emulate the cloud environment using just the `mockSessionProperty` helper. Ideally, we also want the `MetabaseBootstrap` JSON to contain expected values from the very beginning. That's probably possible if we can run Metabase with a token containing the `hosting` feature. Or maybe we can somehow tweak the backend in Cypress (maybe with some new endpoint like `/testing/restore`)

**Comment by nemanjaglumac** [comment]
@kulyk thank you sooooo much for such a detailed explanation. I might come up with something now that I know this. Very useful.

@noahmoss sorry for the late reply.

**Pull request merged**
