### PR TITLE
Dockerfile 

### PR DESCRIPTION
**Pull request by agilliland**
intended to produce an image that runs the app from source.

### CODE REVIEW

**Comment by agilliland** [comment]
@michaelshobbs let me know if you have any thoughts on this

**Comment by michaelshobbs** [comment]
Is there perhaps already a clojure base image that has openjdk and leiningen? That could make the build process faster.

**Comment by agilliland** [comment]
yeah, i tried out the clojure image but ran into a couple issues.  overall the difference felt pretty minimal since all it removed from the current Dockerfile is adding openjdk and leiningen.

**Comment by agilliland** [comment]
Planning to move forward with this and we can optimize over time.  Just want to get something going for now.

**Pull request merged**
