### PR TITLE
Fix "saved questions" database behavior in notebook mode + joins

### LINKED ISSUE #10440: Improve UX when attempting to join data from a different DB
Currently in the notebook you can select a saved question based on data from a database different from the currently selected one, but it results in an error if you attempt to preview the results:

image

Ideally we should filter out the selectable saved questions to only include ones that are based on the same database.

Falling short of that, we should provide a nicer-looking warning message.

### LINKED ISSUE #10491: Add ability to use joins when starting data is a saved question
0.33 will add the ability to join _to_ a saved question, but currently there's a limitation where you can't use joins if your _starting data_ is a saved question. 

This won't be a 0.33 feature, but maybe 0.34 or 0.35?

### PR DESCRIPTION
**Pull request by tlrobinson**
This fixes two problems with the "Saved Questions" database in notebook mode, by switching the `db_id` from the fake `-1337` to the actual underlying database ID:

1. When starting a notebook question based on a "Saved Question" table, we now show the correct actions based on the underlying database capabilities, like join and custom columns. Previously we didn't show anything except the very basics that were supported by all databases (filter, summarize, etc)
2. When joining either to or from a "Saved Question" table we only show the questions (or tables) based on the same underlying database.

Resolves #10440
Resolves #10491

### CODE REVIEW

**Review by mazameli — APPROVED** [review]
Awesome! I think this resolves https://github.com/metabase/metabase/issues/10491, too. (Though @salsakran pointed out some relevant areas for improving the UX that I should spin out as separate issues.)

**Comment by tlrobinson** [comment]
Correct, that's what I was referring to in item 1, I'll update the description.

Also @salsakran's item 1 in #10491 is referring to what I fixed in my item 2.

I agree the "Saved Questions" database is not longer good UX (for one we flatten hierarchical collections into a flat list of schemas) and should be addressed separately

**Comment by tlrobinson** [comment]
@camsaul can you review the backend portion of this?

**Comment by camsaul** [comment]
We can probably actually remove the saved question mark virtual ID entirely. But that can be done later

**Review by camsaul — APPROVED** [review]

**Comment by tlrobinson** [comment]
@camsaul `saved-questions-virtual-database-id` is still used for the saved question "database" itself, just not the tables belonging to it.

**Pull request merged**
