### PR TITLE
Slow dashboard card warnings

### LINKED ISSUE #1749: Make default dashboard query timeout of 60 seconds configurable
I'm using Metabase to query a read replica of our production db, but some queries take longer than 60 seconds. The default hard coded 60 second timeout kills these queries. It would be useful to configure this timeout value to suit our needs... ideally with an environment variable (AWS Environment Property). 

I'm certain there are other scenarios where reducing/increasing the timeout might prove helpful.

See also issue: #576

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #1749 
- [x] Logic for "average" query execution probably needs tweaking.
- [x] Tweak `DATASET_SLOW_TIMEOUT` and `DATASET_USUALLY_FAST_THRESHOLD`

### CODE REVIEW

**Comment by tlrobinson** [comment]
@agilliland @salsakran @kdoh Do you have any thoughts on how to compute the "average" execution time of a query? Currently I'm essentially just doing `SELECT AVG(running_time) FROM QueryExecution WHERE json_query = ?` (https://github.com/metabase/metabase/pull/2570/files#diff-a7a97dd572784f1f0a7c10ad75ba2e6bR43)

I think at a minimum we should limit it to "recent" executions (by time or count?), or it could be more complex like a moving average (preferably expressible in SQL)

@kdoh Also need the final value for the delay before showing the warning message.

**Comment by agilliland** [comment]
Yeah, I think that's about all you can do right now.  Eventually when we add the card_id to the query execution tracking we'll be able to make this a little better.

**Comment by tlrobinson** [comment]
Well, I think looking up executions by `json_query` is actually better than card id since if the query changes it's somewhat likely the execution time will change. I'm just asking if we should limit to the `$N` most recent executions, or executions since `now() - $SOME_INTERVAL`, or something more complex.

I'm not sure how to express this in SQL, but I think a combination of the two would be best, like "executions in the last week, or the last 5 executions, whichever there are more of". A busy dashboard could trigger 5 executions in minutes, skewing the result if the DB happens to be slow, while an infrequently visited dashboard may not have any executions in the last week.

**Comment by agilliland** [comment]
Yeah, lets limit it somehow and I think limiting it to the last 10 executions makes sense.

**Comment by tlrobinson** [comment]
@kdoh Are you happy with this now or is there anything else that needs to be done?

**Pull request merged**
