### PR TITLE
Alternate upgrade strategy using Heroku Pipelines

### PR DESCRIPTION
**Pull request by jaxn**
This is an upgrade strategy that can be done completely from a web browser and without using Git.

If the metabase team approves of this addition, I can add screenshots to help clarify the instructions.

###### TODO 
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by salsakran** [comment]
Thanks! I personally don't know enough to determine whether this is a good or bad idea. Anyone on  @metabase/core-developers feels like they do?

**Comment by wvengen** [comment]
Nice idea! Someone will need to keep [metabase-deploy](https://github.com/metabase/metabase-deploy) up-to-date (current version is from May 2017, while the latest Metabase release is from September 2017).

**Comment by camsaul** [comment]
Generally we don't update `metabase-deploy`, we update [`metabase-buildpack`](https://github.com/metabase/metabase-buildpack) which `metabase-deploy` uses

**Comment by mazameli** [comment]
Hey, @jaxn. Sorry this PR never got reviewed. We'd need you to sign our CLA if we were to merge this. Thanks.

**Comment by jaxn** [comment]
@mazameli the CLA is submitted. Thanks!

**Comment by mazameli** [comment]
@tlrobinson, Sameer had said "I personally don't know enough to determine whether this is a good or bad idea." WDYT?

**Comment by mazameli** [comment]
Thanks @jaxn. Mind also resolving the merge conflict please?

**Comment by tlrobinson** [comment]
I think our Heroku instructions are actually out of date since we started using https://github.com/metabase/metabase-buildpack

https://github.com/metabase/metabase-deploy hasn't been updated in a long time.

**Review by tlrobinson — COMMENTED** [review]
I think our Heroku instructions are actually out of date since we started using https://github.com/metabase/metabase-buildpack

https://github.com/metabase/metabase-deploy hasn't been updated in a long time.

**Comment by dacort** [comment]
I like this in concept, but I think this approach is misusing the concept of pipelines a little bit.

_I am not a Heroku expert_ but it seems like  Pipelines are more useful for testing new versions of code in different environments and then pushing those new versions to production. Which, don't get me wrong, would be a great approach to use for deploying a production-ready version of Metabase in Heroku. 

As such, I would rather see the documentation updated to reflect *that* workflow, than one where you temporarily deploy an app as part of a pipeline, promote it, and then delete it.

**Comment by kdoh** [comment]
Closing per @dacort's comment about updating the docs vs using pipelines in this way.

**Pull request closed without merging**
