### PR TITLE
Split repro for #13641 in two versions: "remapped" and "default"

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
MERGED

### What does this PR accomplish?
- Splits repro for #13641 into 2 versions
    - "Remapped" (display values remapped to the FK) - which is now passing (changes introduced in #14695)
    - "Default" version without remapping - still failing at cc348c8c9f3e6bcd0f3780bdbed814fafd5c47cb

See @flamber's [comment](https://github.com/metabase/metabase/pull/14695#pullrequestreview-584885256) for an additional context.

### How to test this manually?
- `yarn test-cypress-open --testFiles enterprise/frontend/test/metabase-enterprise`
- `enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js`
- You can isolate this test by adding.only() to the test
```javascript
it.only(`${test.toUpperCase()} version:\n drill-through should work on implicit joined tables with sandboxes (metabase#13641)`, () => {...})
```
- Then comment out or temporarily unskip the `cy.runnable().skip()` part to let the test run for both scenarios
```javascript
test === "remapped"
  ? (cy.log("**-- Remap Product ID's display value to `title` --**"),
    remapDisplayValueToFK(ORDERS.PRODUCT_ID, PRODUCTS.TITLE))
  : cy.state("runnable").skip();
```
- The "default" version of the test should fail until the related issue is fixed (please see the screenshot below)

### Additional notes:
- Once the issue is fixed, please enable both test cases
- Make sure both are passing and
- Merge them together with the fix

### Screenshots:
1. Local testing only with both tests enabled
image

2. "Default" version of the test skipped
image

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
### Stress-testing with GitHub actions
With repro for 13642 unskipped (I branched off of @camsaul `fix-10474` branch) where this test was unskipped:
[12 passing, 1 failing (13642), 3 skipped](https://github.com/nemanjaglumac/metabase-tests/actions/runs/549483978)
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  sandboxes.cy.spec.js                     01:05       16       12        1        3        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     01:05       16       12        1        3        - 
```

With repro for 13642 skipped (I branched off of @camsaul `fix-10474` branch) where this test was unskipped:
[12 passing, 4 skipped](https://github.com/nemanjaglumac/metabase-tests/actions/runs/549483978)
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  sandboxes.cy.spec.js                     00:47       16       12        -        4        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:47       16       12        -        4        -  
    ```

**Review by flamber — APPROVED** [review]
The function `remapDisplayValueToFK` seems like something we can use elsewhere than just sandboxing.

**Comment by nemanjaglumac** [comment]
> The function `remapDisplayValueToFK` seems like something we can use elsewhere than just sandboxing.

Most definitely. I was thinking about it, but I usually wait until I see the need to use it elsewhere before i move it as a **global** helper function. I can extract it now if you'd like?

**Comment by flamber** [comment]
It's up to you - I'm okay with you leaving it for now and restructure after release.

**Review by camsaul — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
It turned out repro for #13642 needs to be updated as well.
I'll update both tests in their respective branches/PRs. Closing this PR.

**Pull request closed without merging**
