### PR TITLE
License: fix Metabase Commercial License url

### PR DESCRIPTION
**Pull request by anarute**
Minor documentation change, the current url is returning 404.

Not sure if it's better to fix in the server to redirect `https://www.metabase.com/license/commercial/` to `https://www.metabase.com/license/commercial`. If not, this commit fixes the Licenses.

### CODE REVIEW

**Review by jeff-bruemmer — APPROVED** [review]
Thanks, @anarute!

**Comment by jeff-bruemmer** [comment]
@anarute. To get these failing tests to pass, you may need to [sync your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).

**Comment by anarute** [comment]
> @anarute. To get these failing tests to pass, you may need to [sync your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).

done :)

**Comment by nemanjaglumac** [comment]
Seems to have been fixed already in https://github.com/metabase/metabase/pull/25642

**Pull request closed without merging**
