### PR TITLE
Query results metadata should include field refs

### LINKED ISSUE #10474: Cannot use Saved Question, when original question uses "Display values"="Use foreign key"
**Describe the bug**
When a field in Admin > Data Model has "Display values"="Use foreign key", then the question cannot be used as Saved Question.
It will just return an error that the foreign table column was not found (depending on database, the error might be different):
`Invalid column name "TITLE"`
`Column "source.TITLE" not found`

**To Reproduce**
Steps to reproduce with Sample Dataset:
1. Go to Admin > Data Model > Sample Dataset > Orders > Product ID :gear: 
2. Change "Display values"="Use foreign key", connected to "Title"
3. Create a QB/Simple question of Orders and save it as "Q1"
4. Create a new question and use the "Q1" in Saved Questions, and run it.
5. Fails with the error: `Column "source.TITLE" not found`

**Information about your Metabase Installation:**
Metabase 0.32.10 (prod) and 0.33.0-RC1 (test)
This used to work in 0.32.9

### PR DESCRIPTION
**Pull request by camsaul**
#10474 stopped working because results metadata, which is used when we use an existing question as a saved question, didn't include `field_ref` info, so we weren't able to propertly refer to fields that were from other Tables (e.g. FK columns)

This fixes #10474 and probably lots of other bugs related to saved questions not working properly.

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
Tested commit `edbc6c8`.

I can now create a question from Saved Questions with FK remapping (#10474) :tada: 

But I cannot save any questions (QB, nested, SQL) - getting "An error occurred" in the Save-dialog, and nothing in the log. The `POST /api/card` returns this:
```
result_metadata: "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."
```

---

Drill on implicit join only works if there's *is* FK remapping #13641 - without remapping it fails:
```
Column "source.CATEGORY" not found; SQL statement: -- Metabase:: userID: 2 queryType: MBQL queryHash: de3ef305d79ab6fc5c1895ec02868d0d80e6cec86a96ac11ab09ca6c8797703e SELECT "source"."ID" AS "ID", "source"."USER_ID" AS "USER_ID", "source"."PRODUCT_ID" AS "PRODUCT_ID", "source"."SUBTOTAL" AS "SUBTOTAL", "source"."TAX" AS "TAX", "source"."TOTAL" AS "TOTAL", "source"."DISCOUNT" AS "DISCOUNT", "source"."CREATED_AT" AS "CREATED_AT", "source"."QUANTITY" AS "QUANTITY" FROM (SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY" FROM "PUBLIC"."ORDERS" WHERE "PUBLIC"."ORDERS"."USER_ID" = 1) "source" WHERE "source"."CATEGORY" = ? LIMIT 2000 [42122-197]
```

---

And #13642 seems unchanged. Cannot drill or filter the joined table.
```
Column "source.Products__CATEGORY" not found; SQL statement: -- Metabase:: userID: 2 queryType: MBQL queryHash: 00cc4ca78b223deae8ec307f20159c0b723630b6fb3dd6c2f43a520452d3b8ae SELECT "source"."ID" AS "ID", "source"."USER_ID" AS "USER_ID", "source"."PRODUCT_ID" AS "PRODUCT_ID", "source"."SUBTOTAL" AS "SUBTOTAL", "source"."TAX" AS "TAX", "source"."TOTAL" AS "TOTAL", "source"."DISCOUNT" AS "DISCOUNT", "source"."CREATED_AT" AS "CREATED_AT", "source"."QUANTITY" AS "QUANTITY", "Products"."ID" AS "Products__ID", "Products"."EAN" AS "Products__EAN", "Products"."TITLE" AS "Products__TITLE", "Products"."CATEGORY" AS "Products__CATEGORY", "Products"."VENDOR" AS "Products__VENDOR", "Products"."PRICE" AS "Products__PRICE", "Products"."RATING" AS "Products__RATING", "Products"."CREATED_AT" AS "Products__CREATED_AT" FROM (SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY" FROM "PUBLIC"."ORDERS" WHERE "PUBLIC"."ORDERS"."USER_ID" = 1) "source" LEFT JOIN (SELECT "PUBLIC"."PRODUCTS"."ID" AS "ID", "PUBLIC"."PRODUCTS"."EAN" AS "EAN", "PUBLIC"."PRODUCTS"."TITLE" AS "TITLE", "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", "PUBLIC"."PRODUCTS"."VENDOR" AS "VENDOR", "PUBLIC"."PRODUCTS"."PRICE" AS "PRICE", "PUBLIC"."PRODUCTS"."RATING" AS "RATING", "PUBLIC"."PRODUCTS"."CREATED_AT" AS "CREATED_AT" FROM "PUBLIC"."PRODUCTS" WHERE "PUBLIC"."PRODUCTS"."CATEGORY" = ?) "Products" ON "source"."PRODUCT_ID" = "Products"."ID" WHERE "source"."Products__CATEGORY" = ? LIMIT 2000 [42122-197]
```
Though if FK remapping is enabled, then the error looks slightly different:
```
Column "PRODUCTS__via__PRODUCT_ID.ID" not found; SQL statement: CREATE FORCE VIEW PUBLIC._3 AS SELECT "PRODUCTS__via__PRODUCT_ID".ID AS "PRODUCTS__via__PRODUCT_ID__ID", "PRODUCTS__via__PRODUCT_ID".EAN AS "PRODUCTS__via__PRODUCT_ID__EAN", "PRODUCTS__via__PRODUCT_ID".TITLE AS "PRODUCTS__via__PRODUCT_ID__TITLE", "PRODUCTS__via__PRODUCT_ID".CATEGORY AS "PRODUCTS__via__PRODUCT_ID__CATEGORY", "PRODUCTS__via__PRODUCT_ID".VENDOR AS "PRODUCTS__via__PRODUCT_ID__VENDOR", "PRODUCTS__via__PRODUCT_ID".PRICE AS "PRODUCTS__via__PRODUCT_ID__PRICE", "PRODUCTS__via__PRODUCT_ID".RATING AS "PRODUCTS__via__PRODUCT_ID__RATING", "PRODUCTS__via__PRODUCT_ID".CREATED_AT AS "PRODUCTS__via__PRODUCT_ID__CREATED_AT" FROM PUBLIC.PRODUCTS WHERE "PRODUCTS__via__PRODUCT_ID".CATEGORY = ?2 [42122-197]
```
^ notice the missing `LIMIT 2000` ?

**Comment by nemanjaglumac** [comment]
Tested locally with Cypress and 10474 is indeed passing:
image

**Comment by camsaul** [comment]
@flamber did you restart the backend server when you ran this branch? Some of those schema validation errors will show up if you don't restart the server

**Comment by camsaul** [comment]
@flamber I never said this PR fixed #13641 and #13642 -- and reason you can't 👍 ? I'm not trying to fix every single bug in a single PR. I'll fix one bug in a PR and then open a new PR to fix another

**Comment by flamber** [comment]
@camsaul It was breaking every question save, that's why I didn't approve.
> But I cannot save any questions (QB, nested, SQL) - getting "An error occurred" in the Save-dialog, and nothing in the log. The POST /api/card returns this:
> `result_metadata: "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."`

I just tested the other issues, since you commented on those issues that this PR might fix it.

**Comment by camsaul** [comment]
The result metadata issue is fixed now

**Review by flamber — APPROVED** [review]
Tested `64e5dd6`
This fixes #10474 :+1: and I can save questions :tada: 
Didn't test anything else.

**Comment by nemanjaglumac** [comment]
> Tested `64e5dd6`
> This fixes #10474 👍 and I can save questions 🎉
> Didn't test anything else.

👆 What he said :)

**Review by nemanjaglumac — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
@camsaul you don't have to wait for https://github.com/metabase/metabase/pull/14710. I'll rebase and merge it into #14719

**Pull request merged**
