### PR TITLE
Fix dnd clause composition

### PR DESCRIPTION
**Pull request by ranquild**
Context https://metaboat.slack.com/archives/C0645JP1W81/p1710769889848229

Trying to select text in the expression popover for an existing clause won't start a drag-n-drop interaction.

### CODE REVIEW

**Review by kamilmielnik — CHANGES_REQUESTED** [review]

**Comment by kamilmielnik** [comment]
Please also add tests :pray:

**Comment by ranquild** [comment]
@kamilmielnik how do you expect this to be tested?

**Comment by kamilmielnik** [comment]
> @kamilmielnik how do you expect this to be tested?

An e2e test simulating text selection with `mousedown` + `mousemove` + `mouseup` in a way that would reorder the clauses (like in the loom video) and asserting that clauses have the same order afterwards.

**Comment by ranquild** [comment]
@kamilmielnik 
before
Screenshot 2024-03-19 at 09 31 46

after
Screenshot 2024-03-19 at 09 32 06

**Review by kamilmielnik — APPROVED** [review]
:+1:

**Pull request merged**
