### PR TITLE
Fixing Table isValid check

### LINKED ISSUE #28304: Table Columns showing [Unknown]
Tables that used to display correctly now show many columns that were not present before with a name of [Unknown]

1. Go to New Question -> Orders -> Visualize;
2. Move any column up or down (so that we write the `table.columns` prop);
3. Return to the notebook view and add `Count by Created At: Year`, click Visualize
4. Change back to a table view, you'll notice that there are now many columns that say [Unknown]

**Expected behavior**
Should only show columns that make sense

**Screenshots**
image

### PR DESCRIPTION
**Pull request by npfitz**
Fixes #28304 

How to test:
- New -> Question -> Orders -> Visualize
- Go to table settings and move a column to a new place
- Go back to notebook editor, and summartize by count, group by Created At: Year -> Visualize
- Switch viz back to table (it is likely showing up as a line chart)
- You should see both the Created At and Count columns there to re-order. Previously, you would have only seen Created At.

The original e2e test has been updated to check for the presence of the Count field, as well as check that the column formatting has been applied.

### CODE REVIEW

**Comment by alxnddr** [comment]
For some reason, it does not show an aggregate:

<video src="https://user-images.githubusercontent.com/14301985/219726047-f3bf266d-6b69-46bf-85ff-e712827b7840.mov" />

**Comment by alxnddr** [comment]
Also when you convert a structured question to native one, it shows an invalid state which leads to column duplication:
<video src="https://user-images.githubusercontent.com/14301985/219729551-cf9a7676-f8f4-48bb-93eb-7863b0b64f33.mov" />

**Comment by alxnddr** [comment]
Also, the toggle columns widget incorrectly shows columns from joined tables. They lack their table name like "Product  -> ..." and they are placed under the source table:
<video src="https://user-images.githubusercontent.com/14301985/219731638-2f0b27a0-9cb9-4d67-a4cf-706d4f86af82.mov" />

**Review by alxnddr — COMMENTED** [review]
Can you please add an explanationatory comment describing in which cases we need to ignore column names?

Wdyt about adding a bit more specs to cover the scenarios I initially found?

**Comment by npfitz** [comment]
Will do! And yeah, I'm currently adding tests for your use cases 👍

**Review by alxnddr — APPROVED** [review]

**Pull request merged**
