### PR TITLE
MLv2 — Migrate notebook's join step to MLv2

### LINKED ISSUE #31070: [MLv2] Migrate notebook join step component to MLv2

### PR DESCRIPTION
**Pull request by kulyk**
Closes #31070, epic #30514

A feature branch for notebook's join step migration to MLv2

**Pull requests**

- #32903
- #32904
- #32905
- #32906
- #32907
- #32908
- #32911
- #32912
- #33526

### CODE REVIEW

**Review by bshepherdson — APPROVED** [review]
MLv2 integration looks good to me.

**Review by ranquild — CHANGES_REQUESTED** [review]
I spent a bit of time on testing this and these are the first issues I've found. Pretty sure there is more. Please take a look:

1. When data source is changed, the join is not cleared 

Screenshot 2023-09-06 at 12 22 23
Screenshot 2023-09-06 at 12 29 02

2. Doesn't work correctly when self-joining models. E.g. it cannot be "previous results" on the right:

Screenshot 2023-09-06 at 12 30 39

3. Allows incompatible column selection which breaks the query

Screenshot 2023-09-06 at 12 32 13
Screenshot 2023-09-06 at 12 32 22

**Comment by kulyk** [comment]
@ranquild thanks for trying it out:

1. Reproduced, will look into it
2. Can't reproduce, could you please share the steps? I'm getting the model name above both the LHS and RHS columns
3. It used to work that way before the migration too. I can see why we'd want to filter out columns, we can open an issue about it or ask product/design if that makes sense and address that separately

**Review by alxnddr — COMMENTED** [review]
Hey @kulyk @bshepherdson 👋  I found a couple of regressions compared to the `master` branch, could you please have a look? It would be great to slightly increase test coverage to handle these and other cases 

1) Removing joins creates an invalid state

https://github.com/metabase/metabase/assets/14301985/5c7e3d73-3ad8-402a-a122-c3a95d60f931

2) Second stage join crashes the query builder

https://github.com/metabase/metabase/assets/14301985/219a9428-c094-4322-ada6-d60a499568de

3) Minor: when selecting a model as a source and creating a join, it immediately shows "Previous results" inside the join section. However, on `master` it shows the name of the model:

Screen Shot 2023-09-19 at 12 22 20 PM

**Review by alxnddr — APPROVED** [review]
Tremendous work 👍 
Worked as expected for me

**Pull request merged**
