### PR TITLE
Wrap long question titles to prevent overflows

### LINKED ISSUE #17750: master: Question list overflows instead of wrapping names
**Describe the bug**
A clear and concise description of what the bug is. Regression on master compared to latest release 0.40.3.1

**To Reproduce**
1. Save a question with a medium-long name
2. Go to a dashboard > :pencil2: > :heavy_plus_sign: 
image

**Expected behavior**
Wrap names - including words without spaces (languages like Danish has some ridiculous long words, 30+)

**Information about your Metabase Installation:**
master `f9a649d`

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #17750 

## How to Test

For all tests:

1. Save a question with a long name

<hr/>

### 1. In a dashboard’s add question sidebar

1. Go to a dashboard › :pencil2: › :heavy_plus_sign: 

#### Before

<hr/>

### 2. In a new question’s saved questions picker

1. Create question
2. Simple Question
3. Saved Questions

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
Thanks for fixing it! Is there a way to use `Ellipsified` component there? I think it might be helpful in some cases

**Comment by flamber** [comment]
I would pay good money if we didn't ellipse, but wrapped, just like it currently does on 0.40.5:
image

**Comment by gusaiani** [comment]
@alxnddr @flamber 

Gotcha, I'll see about wrapping the titles.

**Comment by gusaiani** [comment]
@flamber, updated, is that the idea?

**Review by alxnddr — APPROVED** [review]
Thanks 👍

**Review by flamber — APPROVED** [review]
You're getting a :kissing_heart: :kissing_heart: :kissing_heart: because this also fixed the annoying horizontal scroll
image

**Comment by gusaiani** [comment]
@flamber You had mentioned money but 😘 😘 😘 is better :****

**Pull request merged**
