### PR TITLE
Upgrade Toucan to 1.1.2 [ci drivers]

### PR DESCRIPTION
**Pull request by senior**

### CODE REVIEW

**Comment by senior** [comment]
@camsaul found that our toucan was out of date. If the tests all pass, any reason not to merge it?

**Comment by camsaul** [comment]
yeah I merged a few external PRs to it over the last month or two which is why the version was bumped. Nothing that should affect Metabase so feel free to update.

For all of our dependencies we can generally update them whenever someone feels like opening a PR to do it unless there's a comment next to them with reasons not to do so (e.g. MySQL driver dropping Java 7 support).

**Review by camsaul — APPROVED** [review]
:bird:

**Comment by camsaul** [comment]
image

**Pull request merged**
