### PR TITLE
Fixed doc for running the docker image

### PR DESCRIPTION
**Pull request by Malte-D**
the current docker image uses `JAVA_OPTS` instead of `JAVA_TOOL_OPTIONS`

###### Before submitting the PR, please make sure you do the following
- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.
### Tests
-  [ ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by mazameli** [comment]
@tlrobinson Do you mind taking a quick look at this PR? I'm no expert at Docker image options.

**Comment by tlrobinson** [comment]
I'm not that familiar with the difference between these. It looks like we do pass `JAVA_OPTS` through to `java`, whereas `JAVA_TOOL_OPTIONS` is for when that's not possible https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#tooloptions

But @salsakran wrote that original documentation and @camsaul probably knows so I'd like to confirm with them.

**Comment by camsaul** [comment]
`JAVA_TOOL_OPTIONS` will get passed directly to `JAVA` whereas `JAVA_OPTS` is something we use internally. I'm 90% sure the reason we tell you to use `JAVA_TOOL_OPTIONS` is so it adding a single flag like in the example doesn't override all the other stuff we set in `JAVA_OPTS` (or imply that it does)

**Review by camsaul — CHANGES_REQUESTED** [review]
👎 on changing the documentation for reasons stated 

If you want to change the `JAVA_OPTS` variable name in our Docker scripts to something that won't cause confusion in the future (perhaps something like `metabase_java_options`) we can merge that

**Comment by tlrobinson** [comment]
@camsaul `JAVA_OPTS` is a semi-standard way of passing options to Java, not just an internal thing. Our scripts append to `JAVA_OPTS` so it won't override the ones we set in ours scripts.

**Comment by camsaul** [comment]
Don't think we should encourage people to use a "semi-standard" env var for setting Java options vs the actual real standard env var for setting them. And that is if you could even call it semi-standard. 

Tomcat and JBoss are the only projects I can think of off the top of my head that support it.

We don't want to go around confusing people into thinking that something like

```
JAVA_OPTS='-Xmx2g' java -jar metabase.jar
```

is going to work, because it won't. We shouldn't be documenting the name of an internal variable and telling people to use it when there's an actual standard way of doing the same thing.

**Pull request closed without merging**
