### PR TITLE
Change max_series to 100

### PR DESCRIPTION
**Pull request by mazameli**
This is a reincarnation of https://github.com/metabase/metabase/pull/5592 for the purpose of discussion. It might be a while before we get the bandwidth to implement [a more elegant solution](https://github.com/metabase/metabase/issues/3656#issuecomment-512610895) for the problem of line/area/bar chars with more than 20 series, so I started playing around to see how much of a performance hit users would experience when trying to interact with or modify a chart with lots more series on it.

The short answer is: it depends on how many total points there are on the chart.

## How this felt in practice when I tried it out

I played around with a time series chart with a series breakout — count of orders by time and by user state, all-time (our sample data has about 3 or 4 years represented). This only resulted in **48 series** (for each of the lower 48 states in the USA). I then tried opening up the sidebars of the UI and hovering over points on the lines to see how the chart performed.

- At the **month** granularity (our default), things felt pretty darn good actually.
- At the **week** granularity, things were pretty usable, but with some noticeable slowdown.
- At the **day** granularity, things felt _technically_ usable, in that it didn't grind things to a halt, but if I started clicking around too fast or hovering on lots of points, things got slow. This didn't feel like a fun state to be in at all until I filtered down the time range.

[Here's a 4-minute screen capture](https://drive.google.com/file/d/1InctoBLUGyCg0ZGhXV4FdNmj6htDyHdU/view?usp=sharing) (Metabase email address required)

For other situations, like seeing orders per state by day-of-the-week, this felt pretty great:

image

## Items for discussion
CC @salsakran @kdoh @paulrosenzweig 
- Should we do this as a way to relieve pressure in the short-term? I think the trade-off of allowing the potential for users to run into a chart with way too many data points might be acceptable for the benefit of having fewer situations where a line/area/bar chart just refuses to work _at all_.
- Is `100` the right limit for now? I'm not sure since in my tests I was using 48 series because I didn't have a column with cardinality `> 48 <= 100` at hand.
- The main problem here is line/area/bar chart performance. Improving its performance so that it re-renders faster would also make the GUI experience better in general, but I'm sure this is a large project. Is it time to tackle this?
- This wouldn't fix the problem of too many items in our legends, but it also doesn't make that situation notably worse IMO.

### CODE REVIEW

**Comment by vitorbaptista** [comment]
Hello. Any ETA on this? This is a big blocker for us...

**Comment by kdoh** [comment]
> Should we do this as a way to relieve pressure in the short-term?
Yup. We've punted on this for far too long.
> Is 100 the right limit for now?
Seems reasonable enough as an escape valve for now. I'm still partial to the idea of no specific hard cap where we wouldn't render things and just warning the user that things will be slow if it's above a threshold (which I think 100 would be fine for) but let's not get too cute.
> The main problem here is line/area/bar chart performance.
Yeah we're definitely not being smart enough about downsampling and generally handling large datasets in visualizations well. It still feels like we should be able to handle more than we're doing now though without too drastic an overhaul. I wouldn't link the two though as this is affecting folks today.
> This wouldn't fix the problem of too many items in our legends, but it also doesn't make that situation notably worse IMO.
They do look pretty heinous and this will let people have pretty gross stoplights in their questions but I don't think that's worse than not being able to look at 30 series so I'm not happy with it but ok to fix the limit and then follow up with something more considered.

**Comment by mazameli** [comment]
Played around with this some more, and I'm of the mind that we should merge it and play with it on our stats instance a bit.

**Comment by salsakran** [comment]
Can we have some kind of safety valve where we multiple the # of series by the number of x-axis values and short circuit it if we suspect it'll lock up the browser?

**Comment by mazameli** [comment]
@salsakran Not exactly sure what you had in mind re: "short circuit," but one thought I had is if we do suspect the result would be crazy slow as a line/area/bar chart, we could propose visualizing it as a table instead. 

E.g. if I have Count by Month, and then go to add Vendor as a series breakout:

add-grouping

I would see this modal to choose between chart or table:

warning

And then if I choose table I'd land here:

pivot-table-result

**Comment by flamber** [comment]
@mazameli Try selecting Count by CreatedAt:Minute and Product->Vendor. On my computer with Firefox (a few addons), it takes about 12 seconds to render the line graph, 10 seconds to render table:pivot, and about 1 second to render table:simple.
I know the selection is grotesque, and the line graph is useless, but it's just to see what happens if someone is showing detailed data with a filter CreatedAt:CurrentMonth, and someone changes the filter to Previous (which then defaults to 30 months) and just clicks okay, without adjusting the 30.

**Comment by henrytran026** [comment]
Is there any ETA on this PR? We have been waiting for this.

**Comment by keshav0129** [comment]
Which release can we expect to have increased series limit?

**Review by tlrobinson — APPROVED** [review]
Works for me.

**Comment by mazameli** [comment]
@paulrosenzweig or @tlrobinson one question on this before we merge it is how feasible/challenging would it be to guess at the expected size of the result and show a modal if we think it would render really slowly as a chart like I commented above? https://github.com/metabase/metabase/pull/11305#issuecomment-565185435

**Comment by paulrosenzweig** [comment]
@mazameli I don't think it'd be too hard to pause on that confirm modal before displaying the chart. I probably can't fit it in this week. Maybe it make sense to merge this PR as-is and make an issue to polish that in a follow-on?

**Comment by mazameli** [comment]
Thanks for fixing that test, guys.

**Pull request merged**
