### PR TITLE
Revert the ports of number and date formatting to CLJC

### PR DESCRIPTION
**Pull request by bshepherdson**
Large dashboards, and especially tables, cause a lot of recomputation
of number and date formats. There's enough overhead in converting to
CLJS data that it causes noticable lag on large dashboards, especially
in the editor view.

There are paths to avoiding the recomputation, which is pretty wasteful
in either language. To be investigated after the 46 cut.

---
For better context: This PR reverts #27114, #27616, and #27551.

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
Without even testing this locally, one of the potential signs that this has indeed fixed the issue is CI timing:

|| cljc | revert |
|---|---|---|
| e2e-tests-dashboard-ee | 43m 3s | 36m 6s |
| e2e-tests-dashboard-filters-ee | 27m 47s | 24m 53s |

**Comment by bshepherdson** [comment]
> Without even testing this locally, one of the potential signs that this has indeed fixed the issue is CI timing:
> 
> cljc	revert
> e2e-tests-dashboard-ee	43m 3s	36m 6s
> e2e-tests-dashboard-filters-ee	27m 47s	24m 53s

I have a hard time believing this could make that much of a difference! Even with a huge table-filled dashboard, this shouldn't be adding more than perhaps a couple of seconds in aggregate to any test.

**Review by ranquild — APPROVED** [review]

**Comment by iethree** [comment]
> I have a hard time believing this could make that much of a difference! Even with a huge table-filled dashboard, this shouldn't be adding more than perhaps a couple of seconds in aggregate to any test.

one factor here is that the github runners, especially lately have been very slow, so are likely to magnify any performance-related changes.

**Comment by bshepherdson** [comment]
Perhaps, but I think it's a lot more likely that since this PR was pushed late in the NA evening, with global "working hours" over the Pacific, it got access to the good runners.

**Comment by iethree** [comment]
> Perhaps, but I think it's a lot more likely that since this PR was pushed late in the NA evening, with global "working hours" over the Pacific, it got access to the good runners.

@nemanjaglumac and I have a conspiracy theory that since github introduced its premium runners, all open source projects get 💩 runners all the time

**Pull request merged**
