### PR TITLE
Renaming funnel order settings names

### PR DESCRIPTION
**Pull request by npfitz**
PR to change the names of the viz settings used for computing series order in funnel visualizations to match what we use for Line/Area/Bar charts.

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
I think this can be misleading because on the funnel chart we actually reorder rows(steps), not series. I'd vote not to follow consistency when it is not correct logically

**Comment by WiNloSt** [comment]
Agree with @alxnddr on that we're reordering rows not series. But I still think we should make the combo chart and funnel chart settings look more similar.

How about:
combo
- `graph.series_order_dimension`
- `graph.series_order`
Funnel
- `funnel.rows_order_dimension`
- `funnel.rows_order`

At least it's better than just `graph.series_order` and `funnel.rows` which doesn't look even close

**Review by alxnddr — APPROVED** [review]
Probably, https://github.com/metabase/metabase/pull/26797 will get merged earlier so please rebase and update the names in the code added by this PR

**Comment by npfitz** [comment]
Closing this PR as we already released RC1-3 and don't really have a migration strategy in place. This can be picked up again if needed.

**Pull request closed without merging**
