### PR TITLE
HoneySQL Part 1 Part 3

### PR DESCRIPTION
**Pull request by camsaul**
Supercedes #2613. This finishes the transition of the CRUD layer to HoneySQL.

### CODE REVIEW

**Comment by agilliland** [comment]
let me know when this is done and i'll take a look

**Comment by camsaul** [comment]
This has been done since Monday

**Comment by agilliland** [comment]
I've looked through about a third of this at this point and the couple thoughts I have at this point are ...

why do we have so many select-* variations?  it seems over the top to have 13 ways to call select.  my preference would be to keep the actual `select` fn very simple and let the other modifiers exist as separate functions which can be applied ...
```
select, select-one, select-one-field, select-one-id, 
select-one-count, select-field, select-ids, select-field->objects, 
select-field->object, select-field->field, select-field->id, 
select-id->object, select-id->field
```

related, why do we need `insert!`, `simple-insert!`, `insert-many!`, and `simple-insert-many!`?  again, seems like we are overworking that.

overall i'm a little concerned that we are just making another SQL dsl and it's unclear why.  is there any reason a query like this shouldn't have been honeysql directly inside a well defined app function like `(get-session <session-id>)`?

```
(db/select-one [Session :created_at :user_id]
 (db/join [Session :user_id] [User :id])
 (db/qualify User :is_active) true
 (db/qualify Session :id) metabase-session-id)
```

**Comment by camsaul** [comment]
We used to have the same number of select variations, they were all part of the crazy-giant `sel` macro. This made things harder to debug and work with and the documentation more complicated. It's much easier to understand a dozen tiny functions than one giant multi-hundred line function.

Read the docstrings for the `insert!` functions. The simplest ones are just tiny wrappers around `jdbc/insert!` which replaced places where we were calling `korma/insert` directly. The more complicated ones built on and replace the old `ins` macro.

We're not making another DSL so much as we're greatly simplifying the one that we already had and breaking it down into understandable chunks.

As always, things can always be put inside "well-defined app functions", but this PR is about refactoring DB access patterns without changing anything else so that's really outside the scope of this PR.

**Comment by agilliland** [comment]
For the select-* variations I am still of the belief that those should not be coupled with the notion of a db/select.  There is no reason for that when most of those are just conveniences for reorganizing a list of maps.  So instead I believe they should be independent functions and if you want to use them then do `(field->object :id (db/select ...))`.

I also think that we should avoid creating them where they are not accomplishing any meaningful code such as select-field->objects which is just `(group-by field (apply select entity options))`.  This is superfluous and IMO should just be written as `(group-by :id (db/select ...))`.

**Comment by camsaul** [comment]
The db functions have several benefits, like automatically modifying the query to get only the fields needed, resulting in more efficient queries.

In addition, it makes sense to have utility functions that abstract away common patterns that are used over and over again in the codebase. Just like we have `u/pprint-to-string`:

```clojure
(u/pprint-to-str 'red object)
```

of course, everywhere we use that we *could* have just wrote:
```clojure
(colorize.core/red (with-out-str (clojure.pprint/pprint object)))
```

`u/pprint-to-str` is more concise and is used all over the place. The same goes for these DB functions. 

Any time we repeat the same pattern a dozen times in the codebase it's worth abstracting it a bit ([DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)). That's why older versions of these functions have been in the codebase for well over a year when I introduced them as options to the `sel` macro. They're widely used all over the codebase; these *new* DB functions are just one-for-one replacements for them. 

Removing existing convenience functions is outside the scope of this PR. Rewriting the functions to be simpler was only something I tackled in the first place so they could co-exist alongside the older korma-based versions for a short period. Rewriting existing code to do things in a more complicated way can be addressed in a future refactor if there's ever any evidence that it's a good idea, but it has nothing to do with this PR.

**Comment by agilliland** [comment]
The fact that something exists in the codebase now is not any form of defense for it's continuing existence.  I've never been in support of having the multitude of select macro variations that you introduced.  You are coupling 2 concepts together which I believe are better defined separately and composed when needed.

Also, as far as I'm concerned everything to do with the app persistence layer is in the scope of this PR.  If you are going to take on the task of completely rewriting the persistence layer for the app then you should be prepared for that.

Your argument for abstraction and DRY is too open and I do not agree with it.  It's certainly not "any time", it's "some times" when there is clear value.  It's a judgement, not a rule.

**Comment by camsaul** [comment]
For me, the new syntax like:

```clojure
(select-id->field :name Database)
```

is a clear win over old syntax like:
```clojure
(sel :many :id->field [Database :name])
```

and especially over what you're proposing:
```clojure
(into {} (for [{:keys [id name]} (select [Database :id :name])]
           {id name}))
```

We do things like this several dozen places in the codebase. Personally, I don't want to have to write the 3rd form over and over again dozens of places. Are you saying you do?

**Comment by agilliland** [comment]
For the syntax of your specific example I'm saying that instead of 
```clojure
(db/select-id->field :name Database)
``` 

it should be written as 
```clojure
(id->field (db/select :name Database))
```

which is one pair of parentheses longer, but it separates the functions into more natural divisions and promotes composition of functions.  and in the event a function like `field->objects` is of no meaningful improvement over the code it wraps then we should skip having it completely and just write the code directly.  for example:

```clojure
(field->objects :name (db/select Database))

  ... is not an improvement on ...

(group-by :name (db/select Database))
```

separately, but since we are on the topic, i'm not a fan of this syntax

```clojure
(db/select :name Database, :id database-id)
```

which i consider ambiguous and inconsistent in a misleading way because it's not obvious at a glance that `:name Database` is doing something entirely different than `:id database-id`.  I would instead prefer that we favor consistency in the way we limit the fields returned from an entity and stick with

```clojure
(db/select [Database :name] :id database-id)
(db/select Database :id database-id)
```

i think it's fine to omit the braces if you are just going to get the default of all fields from an Entity, but it doesn't make sense to support a duplicate notation where keyword(s) before the entity name are used as an alternate way to specify that you only want specific fields from the entity.

**Comment by camsaul** [comment]
You realize this wouldn't work, right?
```clojure
(id->field (db/select [Database :name] :id database-id))
```

Why not? Because we're only fetching the `:name` of the database. We don't have the `:id` at all. 

So I'm going to say your examples reinforce my point: they save you from making mistakes in using them.

**Comment by camsaul** [comment]
```clojure
(field->objects :name (db/select Database))
```
might not be any simpler than

```clojure
(group-by :name (db/select Database))
```

but 
```clojure
(db/select-field->objects :name Database)
```

certainly is.

**Comment by salsakran** [comment]
is that the only outstanding issue on this PR?

**Comment by agilliland** [comment]
You have saved nothing, I was simply reusing your example.  You can't create a mapping of id->name without fetching both of those attributes, so no matter what you say you are indeed fetching both of them!  If anything, your own response validates that you have obscured what's actually happening in the code to the point you've confused yourself.

separating the logic of what fields are being selected from the database and what post-select modifications are being made is absolutely worthwhile.

and regarding your second comment, I completely disagree.  of the 3 examples you gave i believe the below is the most concise and easily readable.

```clojure
(group-by :name (db/select Database))
```

not to mention that it reuses existing clojure.core functions and avoids us having to define extra code.

**Comment by MrMauricioLeite** [comment]
... really? That's the discussion? C'mon @agilliland and @camsaul.
Someone have to step back.

@agiland, the code is ready the way it is. It really is not too far from what you want. You really need to be coded your way? I mean, it's ready... Opinions should have came earlier. Or you can code it yourself and stop asking to be done one way or another just because you think it's better.

@camsaul is there anything you can change to make it closer to @agilliland ideas? Will it take too much effort or affect other parts of the main code? 

Lets try to solve it like good coders.
Sorry for barging in. See you guys around.

**Comment by camsaul** [comment]
@agilliland `group-by :name` wouldn't give us what we want.

Suppose we have a list of objects like:
```clojure
(def objects [{:name "A", :id 1}
              {:name "B", :id 2}
              {:name "C", :id 3}
              {:name "D", :id 4}])
```

`(group-by :name objects)` gives us:

```clojure
{"A" [{:name "A", :id 1}]
 "B" [{:name "B", :id 2}]
 "C" [{:name "C", :id 3}]
 "D" [{:name "D", :id 4}]}
```

Which is different from what we want with `select-field->object`.

To get the desired output, which looks like:
```clojure
{"A" {:name "A", :id 1}
 "B" {:name "B", :id 2}
 "C" {:name "C", :id 3}
 "D" {:name "D", :id 4}}
```

The code would have to look something like:

```clojure
(into {} (for [[k [v]] (group-by :name objects)]
           {k v}))
```

Does that make sense? Can I go ahead and merge this now so I can wrap up the refactor?

**Comment by camsaul** [comment]
I've eliminated the most "controversial" of our existing `select` variations by introducing a new util function that should be reusable in other places as well.

So 
```clojure
(db/select-field->object :name Table, :db_id 1)
```

becomes
```clojure
(u/key-by :name (db/select Table, :db_id 1))
```

**Pull request merged**
