### PR TITLE
New question flow, first iteration

### PR DESCRIPTION
**Pull request by attekei**
Clicking "New Question" now shows you two options: Custom and SQL. This is the result of first iteration of new question flow, not a real MVP yet (and definitely not a Minimum Loveable Product!). But I think that this is still mergeable after fixing tests.

- [x] Fix tests and linters
- [x] Add trivial tests for both Custom and SQL options

### CODE REVIEW

**Comment by salsakran** [comment]
SQL image is broken for me, and there doesn't seem to be enough vertical padding.

screen shot 2017-08-15 at 11 13 04 am

**Comment by salsakran** [comment]
also, I think the copy should be tweaked .. directional suggestions would be:

Custom: Use the simple query builder to see trends, lists of things or your own metrics.

SQL: For more complicated questions, use SQL directly.

**Comment by mazameli** [comment]
I pushed a commit to fix up the spacing and text a little, and fixed the SQL image. I don't know enough about how to use our flex grid stuff to move the row of cards so that it's vertically justified (centered), but that's probably wasted effort anyway since we'll be adding the other two cards soon enough.

This should be good to merge now I think.

screen shot 2017-08-16 at 1 51 09 pm

**Review by kdoh — APPROVED** [review]
Seems ok. I think there are some visual improvement's we'll want to make in the next pass (like more contrast between the page and the cards, and obviously the spacing) but this seems like a reasonable starting place.

**Pull request merged**
