### PR TITLE
Fully deprecate alert deletion, and rename some alert/subscription endpoints

### PR DESCRIPTION
**Pull request by noahmoss**
Updates the alert API for the subscription management project, based on recent discussions w/product.

Major functional changes:
* Alert deletion is fully deprecated. Alerts should be archived instead of deleted (needs to be updated on the FE).
* Alerts are now archived automatically when the last recipient unsubscribes, if there are no Slack channels. This is true regardless of who the last recipient is.
* The email to an alert creator when the alert is deleted has been removed (recipients will still get unsubscribe emails when an alert is archived).
* The endpoint `/api/alert/:id/unsubscribe` is changed from a `PUT` to a `DELETE` method, and it is no longer restricted to non-admins
* I added some extra permission checks in the alert updates endpoints, since non-admins should not be allowed to archive or add recipients to an alert that they created, and should not be able to edit an alert they didn't create at all.

TODO (by @ranquild, cannot merge this PR without these)
- [x] Update frontend to call `DELETE /api/alert/:id/subscription` for all unsubscribe requests
- [x] Update frontend to call `PUT /api/alert/:id` to archive alerts where they would currently be deleted

### CODE REVIEW

**Comment by noahmoss** [comment]
Putting this back into draft since I'm out this week but it's no longer ready for review -- need to fix merge conflicts, debug failing tests, and remove some code that's not needed anymore

**Review by camsaul — APPROVED** [review]

**Comment by noahmoss** [comment]
@ranquild I've now revised the backend part of this PR and done some manual testing. The only issue I can find is that when a user unsubscribes from a dashboard subscription from the `Notifications` page, the subscription doesn't disappear until you refresh the page. Could this be a quick fix to bundle into this PR or should I open a separate issue to fix it separately?

**Comment by ranquild** [comment]
> @ranquild I've now revised the backend part of this PR and done some manual testing. The only issue I can find is that when a user unsubscribes from a dashboard subscription from the `Notifications` page, the subscription doesn't disappear until you refresh the page. Could this be a quick fix to bundle into this PR or should I open a separate issue to fix it separately?

Good find! I've fixed the issue in this PR and added a e2e test for this case.

**Comment by ranquild** [comment]
@noahmoss Please merge this PR when you are ready

**Pull request merged**
