### PR TITLE
Open links in new tab if command/'meta' key is pressed

### LINKED ISSUE #2647: Object details links don't respond to command-clicks to open in a new window
I've been using MB a fair bit to manage ListOfInboundThings and have been drilling into individual entries a lot. 

Going from a list to an item is a bit of a pain for two reasons. Once is that "back" doesn't return me to the scroll position in the list, and the 2k rows makes this more annoying with time. Second, is that I can't open up individual details in other tabs. 

Common tricks like cmd-click or right clicking don't work. I'm guessing this is due to the QuickFilter.

### LINKED ISSUE #5168: Dashboard card title links can't be opened in new tab/window on Windows or Linux
Command/ctrl+clicking or right-clicking on question titles for cards on dashboards no longer allows you to open that question in a new window or tab. I tested this on Chrome on master, but [another user reported it on Windows](http://discourse.metabase.com/t/can-i-know-why-its-not-posible-to-open-the-questions-on-a-new-tab-like-it-was-before/1538) (unsure which browser).

**No `new tab` or `new window` options in the context menu:**

screen shot 2017-05-22 at 2 21 37 pm

**But those options are present on question links in the rest of the app, like the Questions list:**

screen shot 2017-05-22 at 2 21 51 pm

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #8840: Clicking on a primary key link in a table should take me straight to the detail view
It's annoying that you have to click on the `View details` link to go to the detail view instead of just going straight there when clicking on a PK cell. 

I'm pretty sure the current behavior is a consequence of my dumb idea that this should be consistent with other cell actions, but it's a case of consistency for consistency's sake instead of ideal UX/IX.

screen shot 2018-11-01 at 9 54 06 am

### PR DESCRIPTION
**Pull request by tlrobinson**
* Object details links don't respond to command-clicks to open in a new window. Resolves #2647
* Dashboard card title links can't be opened in new tab/window. Resolves #5168
* Clicking on a primary key link in a table should take me straight to the detail view. Resolves #8840

### CODE REVIEW

**Review by kdoh — APPROVED** [review]
Seems to work as expected. I still feel a little funny about having to recreate built in browser behavior like this but I'm happy to get the functionality back.

**Review by mazameli — CHANGES_REQUESTED** [review]
The command+click behavior doesn't work for me in Firefox, either for object detail links in tables, or dashboard card titles. Works in Safari and Chrome, but another funny thing I noticed was that in Chrome, a command+click opens the link in a new tab _and gives it focus_, whereas in Safari in behaved as expected (opens link in new tab but keeps focus in current tab).

`Clicking on a primary key link in a table should take me straight to the detail view` does work for me in all 3 browsers. 🎉

**Comment by tlrobinson** [comment]
Apparently this doesn't workin in Firefox:

```javascript
      const a = document.createElement("a");
      a.href = url;
      a.target = "_blank";
      a.click();
```

**Comment by mazameli** [comment]
Any chance we can get this into 0.31.1 @tlrobinson? The holdup was that it doesn't work for Firefox. It would be great if it did, but if there's no regression introduced and we can't find a fix that works for Firefox maybe we merge this and get things working better for Safari and Chrome?

**Comment by tlrobinson** [comment]
@mazameli this should be working in FF now too

**Review by mazameli — APPROVED** [review]

**Comment by flamber** [comment]
@tlrobinson I've tested 0.31.2 with Firefox and Chromium on Ubuntu, but when I hold `Ctrl` and click any of the card titles or object links, then it doesn't open in new tab. Does this feature only work on Mac?

**Comment by tlrobinson** [comment]
@flamber It uses the `metaKey` which I guess doesn't match the built in link behavior on Windows? https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

**Comment by flamber** [comment]
@tlrobinson 
Okay, I would have expected it was `Ctrl`, since that's how you open links in tabs on any other system than Mac. I think I can count on one hand how many times I use the `OS/Meta` key in a day :-)
Pressing the `OS/Meta` key works in Chrome, but Firefox seems to be a known issue on Linux:
https://stackoverflow.com/questions/39292111/can-firefox-detect-metakey

**Comment by flamber** [comment]
@tlrobinson Github didn't automatically close the 3 issues, even though you marked as `Resolves #....`

**Pull request merged**
