### PR TITLE
Fixes #8562 by escaping '{login}' in zh.po as in the original string

### LINKED ISSUE #8562: Metabase fails to launch in Chinese
```
java -jar metabase.jar 
```

and i get the error
```
09-20 11:00:40 INFO metabase.util :: 正在加载Metabase……
09-20 11:00:42 INFO util.encryption :: 已存储的证书加密方式已经为这个Metabase事例启用 🔐 
For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
Exception in thread "main" java.lang.ExceptionInInitializerError
....
Caused by: java.lang.IllegalArgumentException: can't parse argument number: Login
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at java.text.MessageFormat.<init>(MessageFormat.java:380)
	at puppetlabs.i18n.core$fmt.invoke(core.clj:250)
	at puppetlabs.i18n.core$translate.doInvoke(core.clj:257)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.integrations.ldap$fn__48754.invokeStatic(ldap.clj:48)
	at metabase.integrations.ldap$fn__48754.invoke(ldap.clj:47)
	at metabase.integrations.ldap__init.load(Unknown Source)
	at metabase.integrations.ldap__init.<clinit>(Unknown Source)
	... 126 more
Caused by: java.lang.NumberFormatException: For input string: "Login"
```

what should i do?

### PR DESCRIPTION
**Pull request by jornh**
Steps to reproduce the bug this PR fixes:

    wget http://downloads.metabase.com/v0.30.3/metabase.jar
    java -Duser.language=zh -jar metabase.jar

=> 💣 

###### Before submitting the PR, please make sure you do the following 
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [ ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by senior** [comment]
This error occurs on startup for the `release-0.30.3` branch. On `master` right now, we have shifted to formatting these strings at runtime, so it won't crash, but still could cause problems. I just opened https://github.com/metabase/metabase/pull/8569 which attempts to parse the message and if it can't, write the exception to the log and return the original string.

We still need to fix the broken string like did in this PR (thanks! :+1:) but we should also not allow a typo in a translated string to cause us so many issues.

**Review by senior — APPROVED** [review]
:+1: Looks good to me, the only thing I'm not sure about is if we need to update the translation site as well. Maybe @tlrobinson knows?

**Comment by jornh** [comment]
I’m pretty sure it eventually needs to be sourced from POeditor. I merely put this PR out there to document my findings so others didn’t have to do duplicate work. Feel free to do whatever makes the most sense. 

The isolation from translation bugs being able to break stuff sounds super-nice!

**Comment by senior** [comment]
:+1: I've updated it in POEditor

**Pull request merged**
