### PR TITLE
Document titles HOC and Route wrapper

### LINKED ISSUE #1484: Set more descriptive document titles to make history more useful
Currently we never change the document title from "Metabase", resulting in pretty useless history listings like this:

screenshot 2015-11-16 11 03 25

It might be nice to change the title to reflect the state of the application with titles such as:
- Metabase - Home
- Metabase - New Question
- Metabase - New Question (Orders raw data)
- Metabase - New Question (Orders count, grouped by Product Id Rating)
- Metabase - Question - Order count by rating
- Metabase - Dashboard - My Key Metrics
- Metabase - Admin - Settings
- Metabase - Pulses
- Metabase - Pulse - Weekly Key Metrics

etc.

We may or may not want detailed automatically generated descriptions of the query builder state, I'm not sure.

### PR DESCRIPTION
**Pull request by tlrobinson**
Alternative to #3826
Resolves #1484

For static titles you can do any of the following:

```javascript
<Route path="/foo" title="Foo" component={Foo} />

<Route path="/foo" component={title("Foo")(Foo)} />

@title("Foo")
class Foo extends Component {...
```

For dynamic titles based on props you would typically do:

```javascript
@title((props) => props.whatever)
class Foo extends Component {...
```

Commonly you'd use something in the Redux store to build the page title (make sure `@connect` is before `@title`):

```javascript
@connect((state) => ({ card: state.card }))
@title((props) => props.card ? props.card.title : "")
class Foo extends Component {...
```

Possible improvements:
* maybe something like `@titleFromRedux` that takes a selector and automagically connects to the store
* maybe a way of using the route hierarchy to build up titles by joining all titles in the heirarchy, e.x.

```
<Route path="/" title="Metabase">
  <Route path="admin" title="Admin">
    <Route path="settings" title="Settings">
    <Route path="datamodel" title="Data Model">
```

Then when you're on `/admin/settings` you automatically get `Settings | Admin | Metabase`

### CODE REVIEW

**Comment by tlrobinson** [comment]
@kdoh thoughts on this approach?

If we're cool with it we should map out the titles we'd like to use.

If they're "hierarchical" enough I might add a mode that builds up route titles from parent routes (see end of previous comment)

**Comment by kdoh** [comment]
Seems nice! We should definitely move forward with it. I'm thinking the primary nesting will be in the admin routes so I'll leave it up to you whether the nesting logic is worth it for that.

**Comment by tlrobinson** [comment]
@salsakran @mazameli @kdoh if you have any input on naming schemes I'm happy to implement them, otherwise I can just come up with something.

**Comment by salsakran** [comment]
Off the top -- 

For dashboards
Metabase - <Dashboard Name>

For Pulses
Metabase - Pulses
Metabase - <Pulse Name>

For saved questions
Metabase -<Card Name>
Metabase - <Collection Name> (if viewing a collection)
Metabase - Search: <Search term>

For unsaved cards
Metabase - Question

Admin Panel
Metabase - <Tab Name> - [Subtab] | [Database if looking at a detail]

**Comment by tlrobinson** [comment]
@kdoh @salsakran ^

**Comment by tlrobinson** [comment]
@kdoh @salsakran ping

**Comment by kdoh** [comment]
@tlrobinson Works for me!

**Review by salsakran — APPROVED** [review]
titles look good to me

**Pull request merged**
