### PR TITLE
Verification in search

### PR DESCRIPTION
**Pull request by dpsutton**
###### Search
The verification is always present in search results but only boosts scores when enterprise features are present and enabled.

###### API
This is easily moved into enterprise only. This means that no one can verify questions unless the enterprise classes are on the classpath. However, I don't believe there are any checks that these features are enabled. This is work to be done.

###### Model

The model is NOT behind an enterprise check. This is for a few reasons:
- the model is used in quite a few places and it is better if we don't conditionally add this in: for instance in dashboard responses, search results (ie, just the results, not how they are ranked). If there are no moderation reviews all of these parts work fine with no interruption, and without an API, they cannot be modified.
- the dump to h2 feature has no idea about any enterprise models. not a huge dealbreaker, but just another thing have to make sure works correctly, add tests, etc
- we have some batched hydration functions that must be loaded for this to work correctly. If the model is moved to ee, these should be moved to ee as well (pertains to multiple models so can't live in a particular model). Not clear where this should be required. Presumably as a side effect in `metabase.core`? server? Unclear if others are done so.
- I just haven't gotten to it yet :)

### CODE REVIEW

**Comment by daltojohnso** [comment]
The FE code in this PR adds a verification icon next to verified saved questions in search results:

Screen Shot 2021-08-05 at 9 04 16 AM
Screen Shot 2021-08-05 at 9 04 23 AM

**Review by mazameli — APPROVED** [review]
Looking good, product-wise.

**Review by alxnddr — APPROVED** [review]
Front-end looks good

**Review by jeff303 — APPROVED** [review]
Backend LGTM

**Pull request merged**
