### PR TITLE
Show series title in tooltip

### LINKED ISSUE #9407: Chart axis and series label settings not reflected in tooltips
This is on our stats instance. If I modify the title of a series or e.g. my y-axis label, these changes don't appear to take effect in tooltips:

labels-in-tooltips

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #9407

### CODE REVIEW

**Comment by tlrobinson** [comment]
@mazameli I'll probably add a test for this but in the meantime feel free to try it out.

**Comment by mazameli** [comment]
This seems to be working for multi-series titles:

screen shot 2019-02-14 at 9 54 49 am

But it doesn't seem to work for single series:

image


image

**Review by kdoh — COMMENTED** [review]
Looks good to go once there are tests.

**Review by mazameli — CHANGES_REQUESTED** [review]
Doesn't seem to be working for single series.

**Review by kdoh — APPROVED** [review]

**Review by mazameli — APPROVED** [review]

**Pull request merged**
