### PR TITLE
[49 Backport] Catch exceptions from driver/database-supports? outside driver code and Memoize driver.u/supports? (#44719) (#44804)

### PR DESCRIPTION
**Pull request by calherries**
This PR backports changes from two PRs to 49. 
1. https://github.com/metabase/metabase/pull/43429
2. https://github.com/metabase/metabase/pull/44719

I'm unsure how I missed backporting the first PR, because I definitely intended to and I even changed the milestone. It landed in master around the time of the 50 RC so I probably just forgot to backport it twice.

### CODE REVIEW

**Comment by crisptrutski** [comment]
LGTM but there's a single test failing: `metabase.upload-test/create-csv-upload!-schema-test`

Perhaps it need some cache busting?

**Review by crisptrutski — DISMISSED** [review]
Pre-emptive approval as it seems like just a test that needs updating.

**Comment by calherries** [comment]
Yeah, I spent about 15 minutes trying to figure out how this failure could have happened and then realised it was nuts. The fact that test behaviour is this dependent on global state like this is worth solving by itself. I'll merge this first and attempt this backport again afterwards: https://github.com/metabase/metabase/pull/44938

**Comment by calherries** [comment]
@crisptrutski I've cherry-picked https://github.com/metabase/metabase/pull/44938 and fixed that test by just removing the part that tests that `future` was called. It wasn't very strong or useful IMO anyway and I've already removed it in master.

**Review by crisptrutski — APPROVED** [review]

**Pull request merged**
