### PR TITLE
Show newly created model as option in new question

### LINKED ISSUE #24878: Newly created Model not an option when creating a new question
Probably related to #25144
 
tl;dr: We currently can't create a question from a freshly created model unless we reload the app.

Likewise when moving a model from one collection to another, the changes are not reflected in the model picker when creating a new question.

### To reproduce

1. Create a model
2. Reload the page
3. Create another model
2. Without refreshing the browser, create a question and choose Models as the source.

You will not see the newly created model.

If you reload the page and retry a new question, you will see the model.

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #24878

### How to Test

1. Create a model
2. Reload the page
3. Create a question and turn it into a model
4. Without refreshing the browser, create a question and choose Models as the source.

Last created Model should be displayed as an option for the new question.

### CODE REVIEW

**Comment by WiNloSt** [comment]
@gusaiani Thanks for the PR, but I don't think this PR solves anything yet. I'm sorry I didn't summarize my finding in a written form but here's the demonstration of why this PR still doesn't solve the issue.
https://www.loom.com/share/e8202f59e6fd43b9a78abbc755759a61

Here's the line that I added [in another PR](https://github.com/metabase/metabase/pull/21178) that refetch the list, so you see in the video after I've moved a model to another collection, suddenly there is a new model that I've moved in the step prior shown up in the Temp collection.

https://github.com/metabase/metabase/blob/358cdb5cd6cd0fa7af4182065557ffdd4706f713/frontend/src/metabase/entities/questions.js#L48

**Comment by kulyk** [comment]
Any chance we can fix that by extending some reducer instead of reloading everything? It's always nice to avoid redundant HTTP requests

**Comment by gusaiani** [comment]
@WiNloSt thank you.
Funny because the PR did fix what I was reproing against here, but yeah, not enough.

@kulyk, yup. This is way deeper than it seemed.
Back to draft and to the debugger.

**Comment by WiNloSt** [comment]
@gusaiani What might help is that, based on your repro, I think it should even work with `master`.

The bug occurred when you first try to create a new question then click on the model, Metabase will then load and cache the result. After that, if you create a new model then try to create a new question again, after clicking on the model (in the question creation page). You should see cached result instead of the newly created model.

Doe that makes sense.

**Pull request closed without merging**
