### PR TITLE
Only show 'qb_newb' modal first time user visits a card

### LINKED ISSUE #3078: The "it's okay to play around with saved questions" message is appearing when it shouldn't
This is on `release-0.19.0`.

The behavior of the message should be that you only ever see it the **very first time** you ever go to a saved question detail page. What's happening instead is that during the initial session after you log in to a new account (or maybe when you first initialize an instance?) you see this message every time you go to _any_ saved question. It stops happening if you close the window and relaunch the app.

screen shot 2016-07-29 at 3 07 48 pm

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3078

### CODE REVIEW

**Comment by salsakran** [comment]
@mazameli can you verify that this fixes the behaviour you saw?

**Comment by mazameli** [comment]
I'll give it a look now

**Comment by mazameli** [comment]
This does not appear to solve the problem in #3078. Screen capture:

[saved-questions.zip](https://github.com/metabase/metabase/files/402806/saved-questions.zip)

**Comment by mazameli** [comment]
Steps to reproduce: create a new user, log in with that new user, click around on saved questions.

**Comment by salsakran** [comment]
frowntown.

**Comment by tlrobinson** [comment]
Updated for master, should be working now.

**Pull request closed without merging**
