### PR TITLE
Fix wrongly used `Database` and `Table` types from `metabase-types/api`

### PR DESCRIPTION
**Pull request by ranquild**
Epic https://github.com/metabase/metabase/issues/30763

`Database` and `Table` entity loaders always return `metabase-lib` entities (because they have `getObject` selector overridden). This PR fixes where we use `Database` and `Table` types from `metabase-types/api` and uses ones from `metabase-lib/metadata`. No app code changes, only types + tests.

How to verify:
- type check, unit tests are green on CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30661)

### CODE REVIEW

**Review by uladzimirdev — APPROVED** [review]

**Comment by ranquild** [comment]
@uladzimirdev sure:
1. In app code always use `Database` and `Table` from `metabase-lib` since there is no way to get the raw api table
2. In tests when we setup mocks use api types

**Comment by ranquild** [comment]
@uladzimirdev new entity loader hooks use correct types, if people start to use them if would be clear

**Comment by uladzimirdev** [comment]
@ranquild to which entities should we apply same rules?

**Comment by ranquild** [comment]
> @ranquild to which entities should we apply same rules?

@uladzimirdev currently `Database`, `Table`, and `Field`. I'll create a PR that would make sure we get `Schema` from `metabase-lib` in the app as well, but it's not currently the case.

**Pull request merged**
