### PR TITLE
Select no columns in the custom question mode

### PR DESCRIPTION
**Pull request by alxnddr**
Screen Shot 2021-12-07 at 22 58 51

Allow unticking all columns except the first one by clicking on "Select None" in the custom question query builder.

### How to verify
- New question -> Custom question
- Select any table, open column picker
- Click "Select none"
- Ensure it unselected all the columns except the first one which has become disabled
- Select any other column
- Ensure you can untick the first column
- Ensure clicking on "Visualize" shows the correct set of columns

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
It doesn't seem to handle if unselecting all. Note that should definitely not block this PR, since it's otherwise working great, so that's a small problem compared to currently.
image

**Comment by alxnddr** [comment]
@flamber, we've decided to make "select none" actually keeping one column selected to avoid bugs such as you found. So that it does not require significant refactoring and we can safely include it into the upcoming release even though it is not perfect. Wdyt?

**Review by mazameli — DISMISSED** [review]
Love it!

**Review by flamber — COMMENTED** [review]
Wow that's a frustrating solution. Preferred how it worked on previous commit, if this is only going to be a quick-bug-fix instead of trying to make it easier to filter through many fields on large tables.

This is trying to address a P1 issue, which has been addressed with several patches (including some by me). The current approach just seems like another patch.

**Comment by mazameli** [comment]
Hrmm, okay, let's pause on merging this then until I can understand @flamber's perspective on this.

**Comment by mazameli** [comment]
So, @flamber, the thing that always used to drive me crazy about that popover was that you couldn't do a deselect-all on the original table. This PR in its current state solves that for me in that it deselects everything but one column, ensuring there's always at least one column selected (it doesn't force you to pick the first column -- you can re-select another column and then deselect that other one).

The reason I advocated for that was that in the previous commit, you could get some really unexpected behavior like what you found -- if you select nothing, then do a preview, or do a filter step, or save the question, it very unexpectedly (and dangerously?) shows _all_ columns instead.

My understanding of what @alxnddr told me is that this is due to some ugly and complicated parts of the FE codebase. So my take was that we could take this incremental victory (make it way easier to deselect all columns but one) now, and defer on solving the more pernicious underlying FE problem separately/next. 

Can you elaborate on what you think we should do here?

**Comment by flamber** [comment]
@mazameli Okay, so it's only meant to be a patch. Wonder if we should just merge it as so - not closing the issue, just like we've done with other issues, where we don't have the final solution yet.

----

If you make a join, then it doesn't mark as disabled:
image

**Review by mazameli — APPROVED** [review]

**Review by kulyk — APPROVED** [review]

**Pull request merged**
