### PR TITLE
Remove emacs specific deps

### PR DESCRIPTION
**Pull request by agilliland**
remove dev dependencies that are specific to Emacs because they cause issues with the REPL on Intellij.

### CODE REVIEW

**Comment by agilliland** [comment]
@camsaul I know you use these and honestly I don't care if they are in the project, but they cause a problem with my REPL in IntelliJ and every time I want to launch my repl i need to remove these deps first, which is really annoying.  Do you mind putting these in your personal .lein profile?

```
{ :user {:plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]
                      [refactor-nrepl "2.0.0-SNAPSHOT"]]}}
```

**Comment by camsaul** [comment]
why do they cause a problem in your REPL?

**Comment by agilliland** [comment]
I don't know.  Right now I get this printing in the REPL constantly ...

```DEBUG: unknown status state
DEBUG: unknown response keys :changed-namespaces, :repl-type
DEBUG: unknown status state
DEBUG: unknown response keys :changed-namespaces, :repl-type
DEBUG: unknown status state
DEBUG: unknown response keys :changed-namespaces, :repl-type```

**Comment by camsaul** [comment]
Ok. Go ahead and remove them. Sounds like your REPL is broken...  

Or maybe now is the perfect chance to give CIDER a shot instead :wink:

It has all the best things like paredit, auto-complete, and pop-up dox:

screenshot1

[I have this repo hanging around](https://github.com/camsaul/minimal-emacs-clojure-repl-setup) with a barebones `init.el` to try if you were so inclined.

**Comment by agilliland** [comment]
Yeah, it was working fine for quite a while, but at some point it broke :/

**Pull request merged**
