### PR TITLE
Exclude internal content when populating :has_question_and_dashboard for current user.

### LINKED ISSUE #45289: x-rays on the home screen are disappearing too quickly
### Describe the bug

Even in a new instance, x-rays disappear on the home screen as soon as there are any recent items

### To Reproduce

1. Create a fresh instance
2. note the x-rays on the home page
3. go to examples -> E-commerce insights
4. Now go back to the homepage. The x-rays are gone, and now you have recents

### Expected behavior

I believe the expected result is that users should see the x-rays until there is at least 1 user generated question and dashboard on the instance. However, looking at the code (`user.clj#298`), it appears that we only do this until the user *has access* to 1 question and 1 dashboard (and there are no recent items). 

### Logs

N/A

### Information about your Metabase installation

```JSON
Current Master
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#45317** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45317?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by escherize — APPROVED** [review]
🚀

**Comment by noahmoss** [comment]
@iethree are you saying I should always use closing keywords? In this case I forgot and added the link to the issue after it was closed via the mobile UI

**Comment by iethree** [comment]
> @iethree are you saying I should always use closing keywords? In this case I forgot and added the link to the issue after it was closed via the mobile UI

not a catastrophe, but yeah, better to always use the closing keywords, even after merge, so our automation can parse the links.

**Pull request merged**
