### PR TITLE
Fix time granularity ordering

### LINKED ISSUE #5849: Order of time granularity options is wrong
I think this might've happened due to the binning PR(s), but the time granularity options are in some wacky order now:

screen shot 2017-08-30 at 11 38 03 am

I think the ordering used to be something like:
- Minute
- Hour
- Day
- Week
- Month
- Quarter
- Year
- [ _then some padding/spacing_ ]
- Minute of hour
- Hour of day
- Day of week
- Day of month
- Day of year
- Week of year
- Month of year
- Quarter of year

### PR DESCRIPTION
**Pull request by kdoh**
Fixes #5849

### CODE REVIEW

**Comment by mazameli** [comment]
UI looks good, though I wish there was a bit of padding after `Year` before all the more esoteric options. I think that's how it used to look? Thanks for fixing this!

**Comment by kdoh** [comment]
@mazameli. I believe so. Only thing is this list is now supplied by the backend so being able to split the list won't be trivial.

**Review by senior — APPROVED** [review]
👍

**Comment by mazameli** [comment]
Gotcha. No worries.

**Pull request merged**
