### PR TITLE
Pin map filter nulls

### LINKED ISSUE #7361: Cannot read property 'lat' of null - Allow filter empty/not empty (like for dates)
### Feature requests and proposals

It would be nice to be able to filter latitude and longitude fields to only select those with an actual value. I'm currently trying to generate a map chart based on lat/long fields but some of the rows have empty data and it fails with `Cannot read property 'lat' of null`

I believe something similar was done for the Date fields.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by morganhankins**
Fixes #7361
* Filter out points that don't have numeric latitude, longitude and metric (if present).

Discussion:

* Not sure if `typeof == 'number'` is the preferred way to test for is-a-number.

* Are there existing tests like 'Does PinMap load correctly'?

### Tests
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)

### CODE REVIEW

**Comment by paulrosenzweig** [comment]
@morganhankins thank you for submitting this!

* The approach of filtering invalid rows by default makes sense to me. However, It might lead to some confusion if a user sees that ten rows are returned but only nine appear on the map. It'd be nice (but not strictly necessary if it's a hassle) to add a warning. We do this in `lineAreaBarRenderer` a few times.

* I don't think you need to check `typeof x === number`. We separately check that the column type is numeric, so checking for nullness is probably enough here. I expect all missing values would be `null`, but you could do `x != null` which would also fail if an undefined crept in. Maybe something like this?
```
const points = allPoints.filter(([lat, lng, metric]) => lat != null && lng != null && metric != null)
```

* It doesn't look like we have unit tests for pin maps already. Sorry about that! I think for this logic could just test `_getPoints` rather than confirming everything loads correctly. Would you be willing to create a new test file with just a test or two for this new behavior? That will help pave the way for more tests in the future.

**Review by paulrosenzweig — CHANGES_REQUESTED** [review]
Thanks for jumping in to fix this! I added a comment with some suggested tweaks.

**Review by tlrobinson — CHANGES_REQUESTED** [review]
Thanks Morgan! I agree with @paulrosenzweig's suggestions

**Comment by paulrosenzweig** [comment]
I added the changes I suggested in a new PR: #12159

**Pull request closed without merging**
