### PR TITLE
Formatting date/times by granularity

### LINKED ISSUE #1066: Time grouping by granularities other than day should use human readable names
when grouping by a different granularity, we should have the response be in that granularity, eg, when I group orders by quarter, I'd like to see something like "Q1 2015" instead of a timestamp like in the attached screenshot
screen shot 2015-09-30 at 12 01 30 pm

### PR DESCRIPTION
**Pull request by tlrobinson**
I made my best guess at reasonable formats but I expect we'll want to tweak them. Take a look at the comments next to each case in the switch statements for examples of each.

Not sure about "week".

Also only included the ones we're presently displaying in the UI but can add the rest. Here's the complete list:

```
"minute",
"hour",
"day",
"week",
"month",
"quarter",
"year",
"minute-of-hour",
"hour-of-day",
"day-of-week",
"day-of-month",
"day-of-year",
"week-of-year",
"month-of-year",
"quarter-of-year",
```

Fixes #1066 #1067 #1261

### CODE REVIEW

**Comment by salsakran** [comment]
Kent would really like this to hit their instance. What's ETA on this being ready?

**Comment by tlrobinson** [comment]
It's ready as far as I know. Not sure if anyone has reviewed/tried it, but it's up on https://metabase-proto.herokuapp.com/

**Comment by salsakran** [comment]
Looked good last time I checked.

**Comment by agilliland** [comment]
@tlrobinson just playing with now and noticed a couple things that we should handle

1. it looks like the legends on pie charts aren't taking into account this formatting

screen shot 2015-10-22 at 4 31 29 pm

2. i'm getting days of the week being out of order.  are we possibly misinterpreting something there?

screen shot 2015-10-22 at 4 32 01 pm

**Comment by tlrobinson** [comment]
@agilliland 

1. Yeah, still waiting on this feature in dc.js: https://github.com/dc-js/dc.js/pull/916 Might be possible to work around but I didn't find one.
2. It looks like you're sorting by count in that query. Is that no the case?

**Comment by agilliland** [comment]
re #1, got it.  for #2 that was my bad, i was sorting the results by count.  this lgtm now.

**Pull request merged**
