### PR TITLE
AS400 DB2 Driver

### PR DESCRIPTION
**Pull request by dludwig-jrt**
###### TODO 
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

### CODE REVIEW

**Comment by rcronin** [comment]
Nice work on getting this up and running. Are you still actively developing this?

**Comment by dludwig-jrt** [comment]
Just testing and any bug fixes.

**Comment by rcronin** [comment]
Doug,

Have you seen this error when refreshing the schema?

`Error syncing fields for Table 647 'LTL400TST3.FRL00139': [SQL7049] An internal object limit has been exceeded.
("driver.generic_sql$describe_table_fields.invokeStatic(generic_sql.clj:330)"
 "driver.generic_sql$describe_table_fields.invoke(generic_sql.clj:328)"
 "driver.generic_sql$describe_table.invokeStatic(generic_sql.clj:363)"
 "driver.generic_sql$describe_table.invoke(generic_sql.clj:361)"
 "driver$fn__24454$G__24297__24463.invoke(driver.clj:45)"
 "sync.fetch_metadata$fn__34801$table_metadata__34806$fn__34807.invoke(fetch_metadata.clj:18)"
 "sync.fetch_metadata$fn__34801$table_metadata__34806.invoke(fetch_metadata.clj:15)"
 "sync.sync_metadata.fields$fn__35234$db_metadata__35239$fn__35240.invoke(fields.clj:212)"
 "sync.sync_metadata.fields$fn__35234$db_metadata__35239.invoke(fields.clj:208)"
 "sync.sync_metadata.fields$fn__35262$sync_fields_for_table_BANG___35271$fn__35274$fn__35275.invoke(fields.clj:225)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:115)"
 "sync.util$do_with_error_handling.invoke(util.clj:110)"
 "sync.sync_metadata.fields$fn__35262$sync_fields_for_table_BANG___35271$fn__35274.invoke(fields.clj:224)"
 "sync.sync_metadata.fields$fn__35262$sync_fields_for_table_BANG___35271.invoke(fields.clj:219)"
 "sync.sync_metadata.fields$fn__35300$sync_fields_BANG___35305$fn__35306.invoke(fields.clj:236)"
 "sync.sync_metadata.fields$fn__35300$sync_fields_BANG___35305.invoke(fields.clj:232)"
 "sync.sync_metadata$fn__35869$sync_db_metadata_BANG___35874$fn__35875$fn__35876.invoke(sync_metadata.clj:28)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:115)"
 "sync.util$do_with_error_handling.invoke(util.clj:110)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:113)"
 "sync.util$do_with_error_handling.invoke(util.clj:110)"
 "driver$fn__24532.invokeStatic(driver.clj:220)"
 "driver$fn__24532.invoke(driver.clj:220)"
 "driver$fn__24506$G__24287__24515.invoke(driver.clj:45)"
 "sync.util$sync_in_context$fn__33515.invoke(util.clj:106)"
 "sync.util$with_db_logging_disabled$fn__33512.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_logging$fn__33507.invoke(util.clj:87)"
 "sync.util$with_sync_events$fn__33504.invoke(util.clj:70)"
 "sync.util$with_duplicate_ops_prevented$fn__33495.invoke(util.clj:49)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:133)"
 "sync.util$do_sync_operation.invoke(util.clj:130)"
 "sync.sync_metadata$fn__35869$sync_db_metadata_BANG___35874$fn__35875.invoke(sync_metadata.clj:23)"
 "sync.sync_metadata$fn__35869$sync_db_metadata_BANG___35874.invoke(sync_metadata.clj:20)"
 "api.database$fn__38444$fn__38445$fn__38446.invoke(database.clj:495)")`

**Review by samant-rags — APPROVED** [review]

**Comment by dludwig-jrt** [comment]
No I haven't been able to reproduce this error.

**Comment by dludwig-jrt** [comment]
What is the approximate timeframe when this pull request gets merged into master?  And into a release?

**Comment by rcronin** [comment]
I can confirm that I've had to make several modifications to this code to get it to work efficiently with our version of AS400. Also, AS400 dashboard queries completely lock up the browser so there's a LOT of testing that needs to be done with this to get it anywhere near production grade IMO.

**Comment by viniciuscr** [comment]
Someone can please merge it?

**Comment by tlrobinson** [comment]
Hey all,

Thank you for this PR and apologies for the long delay responding. We've recently done some work to support drivers as plugins in Metabase and as of the next release (v0.32) we will be asking driver developers to first publish new drivers in their own repositories (typically named `metabase-*-driver`). If the driver fully passes the driver tests we will link to it from our documentation, and if a driver gains significant usage we will consider merging it into Metabase itself.

Here is some documentation about publishing a driver as a plugin in a separate repository: https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#drivers-shipped-as-3rd-party-plugins

Here are two example drivers: https://github.com/metabase/sudoku-driver https://github.com/metabase/crate-driver

We still have some work to do on the documentation. You can follow progress and provide feedback on that here: https://github.com/metabase/metabase/issues/9348

Thank you.

**Pull request closed without merging**
