### PR TITLE
[E2E] Remove type delay to avoid lose of focus

### PR DESCRIPTION
**Pull request by diogormendes**
### Status
PENDING REVIEW 

### What does this PR accomplish?
- This PR is to remove a flaky we were having when the typing was being interrupted by the autocomplete. To accomplish that the typing delay was removed.

Screen Shot 2022-04-04 at 12 11 17

Screen Shot 2022-04-04 at 12 09 13

### How to test this manually?
- `yarn test-cypress-open`
- `frontend/test/metabase/scenarios/native-filters/sql-field-filter-string.cy.spec.js`
- All tests should pass

### Screenshots:

Screen Shot 2022-04-04 at 12 10 53

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
I'm not sure this flake has anything to do with the delay, and I am not aware that we have any "autocomplete" functionality here.

In my local tests even setting the delay to the full `1000ms` didn't trigger the problem. On the contrary. We're much more likely to avoid the flake if we increase the delay.

The flake happens because the input field loses focus. It might be a Cypress `type` flake, or it could be something in our FE app. @kulyk would you be able to take a look at this and please tell us if there's something in FE that could make this behavior worse?

**Comment by ariya** [comment]
Could this be a negative side-effect of my "workaround" in PR #20970?

**Comment by diogormendes** [comment]
> I'm not sure this flake has anything to do with the delay, and I am not aware that we have any "autocomplete" functionality here.
> 
> In my local tests even setting the delay to the full `1000ms` didn't trigger the problem. On the contrary. We're much more likely to avoid the flake if we increase the delay.
> 
> The flake happens because the input field loses focus (and then Cypress continues to type in the other focused element, which is the native ace editor). It might be a Cypress `type` flake, or it could be something in our FE app. @kulyk would you be able to take a look at this and please tell us if there's something in FE that could make this behavior worse?

Make a lot of sense to check this further with @kulyk .

I've attached the autocomplete I've mentioned.

Screen Shot 2022-04-04 at 15 36 49

**Comment by nemanjaglumac** [comment]
> I've attached the autocomplete I've mentioned.

@diogormendes what you're seeing is a suggestion query, which loads a list of suggested values after a specific time in ms set in the debounce function. That will NOT finish and apply the filter value instead of you.

**Pull request closed without merging**
