### PR TITLE
[WIP] Enable transparent background for embedded questions

### PR DESCRIPTION
**Pull request by gusaiani**
This is a naive implementation for us to list potential visual design decisions to make.

### How to test

1. http://localhost:3000/admin/settings/public-sharing → enable sharing
2. Create an embeddable question, dashboard etc.
3. Get the embed URL.
4. In `frontend/src/metabase/home/homepage/components/HomeRecentSection/HomeRecentSection.tsx`, line 37, replace src with your embed URL.
5. In `frontend/src/metabase/home/homepage/components/HomeLayout/HomeLayout.styled.tsx`, around line 13, play with a background color or image. This will be the imaginary website on which you embed the iframe.

In localhost:3000 or your local base_url, on the right side, scroll down to see the embedded iframe.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27586)

### CODE REVIEW

**Comment by gusaiani** [comment]
To think about

Will the header and footer backgrounds be:

always transparent?
always white?
configurable?

image

**Comment by gusaiani** [comment]
To think about

The background may be of similar color to text.
In this case, `TOTAL` underneath 69.540.

image

**Comment by gusaiani** [comment]
To think about

in dashboards, do we make cards transparent by default?
If so, any exception?

If the headers and footers are transparent, how do we handle filter dropdowns?

image

**Comment by gusaiani** [comment]
To think about

Backwards compatibility.

If we just remove the white background, at least that of the main section of a question/dashboard, will currently embedded questions/dashboards suffer in enough quantities?
Could we do anything to mitigate this?

Do we invest in any new configurations and user control for this?

**Comment by cdeweyx** [comment]
@gusaiani Great questions all around. On each of them:

> Should the header and footer be transparent as well? ([link](https://github.com/metabase/metabase/pull/27586#issuecomment-1376191671))

Yeah, that's my expectation

> What is the background is similar color to text? ([link](https://github.com/metabase/metabase/pull/27586#issuecomment-1376193491))

Agreed that the text blending into the background could be an issue, but I don't think it's entirely unexpected. If we hear from customers, then we can add a config option for text color in the future.

> In dashboards, do we make cards transparent by default? What about filter dropdowns? ([link](https://github.com/metabase/metabase/pull/27586#issuecomment-1376213022))

Yeah, on dashboards I would expect exactly what you have here, expect the cards are also transparent by default. Filter dropdowns feel like the trickiest thing to handle. I think we’ll have to leave any dropdown as is-in product. Unless there's a better solution I'm not thinking of.

> Will currently embedded questions/dashboards suffer in enough quantities? ([link](https://github.com/metabase/metabase/pull/27586#issuecomment-1376237919))

It will impact those signed embeds that have “transparent” set as a URL parameter atm. Customers can always remove that parameter and revert to default behavior, but the idea is that this better matches expected behavior, so it's not a blocker in my eyes.

**Comment by gusaiani** [comment]
Thanks for the above @cdeweyx.

I'll get to this one.

**Pull request closed without merging**
