### PR TITLE
Use built-in `tools.build` manifest functionality

### PR DESCRIPTION
**Pull request by nemanjaglumac**
According to this answer, it was added back in `v0.14`.
https://ask.clojure.org/index.php/10827/ability-customize-manifest-created-clojure-tools-build-uber?show=10840#a10840

### MANIFEST.MF

**Before**
```
Manifest-Version: 1.0
Multi-Release: true
Created-By: Metabase build.clj
Build-Jdk-Spec: 11
Main-Class: metabase.bootstrap
```

**After**
```
Manifest-Version: 1.0
Created-By: depstar
Built-By: metabase
Build-Jdk: 11.0.20.1
Multi-Release: true
Main-Class: clojure.main
Manifest-Version: 1.0
Multi-Release: true
Created-By: Metabase build.clj
Build-Jdk-Spec: 11
Main-Class: metabase.bootstrap
```

### CODE REVIEW

**Comment by camsaul** [comment]
Having two `Main-Class` entries does not seem like a good idea, any way to prevent it from including the first (wrong) one?

**Review by metamben — CHANGES_REQUESTED** [review]
Running the jar file with such a manifest would always print a warning and (most likely) run the first declared `Main-Class`, so it's not good.

**Review by camsaul — CHANGES_REQUESTED** [review]
Seconding Tamas' request for changes, if you figure out how to get this to output just one Main-Class then please request a rereview

**Comment by nemanjaglumac** [comment]
> Seconding Tamas' request for changes, if you figure out how to get this to output just one Main-Class then please request a rereview

Will do.
Thank you both.

This completely got lost on my radar. I'll try to get back to it.

**Pull request closed without merging**
