### PR TITLE
Fix drag-to-filter and Safari clip-path issue

### LINKED ISSUE #5272: Drag-to-filter chart doesn't seem to work on master
JS error:

screen shot 2017-06-05 at 10 14 31 am

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #5272

### CODE REVIEW

**Review by attekei — COMMENTED** [review]
LGTM but tests (maybe Mocha in this case?) would be a nice way to ensure we don't accidentally break drag-to-filter in future.

Tested both on Chrome and Safari.

**Review by mazameli — COMMENTED** [review]
Everything seems good except I'm having trouble getting it to work with a nested query (which has a `between` filter as part of its definition). I'm getting this error when trying to use a draggable filter on it: "Must be an OrderableValue or OrderableValuePlaceholder"

Also, this never worked with SQL-based questions right?

**Comment by camsaul** [comment]
@mazameli that's probably a nested queries issue. can you post steps to repro in #nested-queries? I will fix

**Comment by tlrobinson** [comment]
@attekei I think this is the kind of thing that should be caught by flow, but the types were too lenient (we should try to avoid types like `Object` and `any`, as well as `@flow weak`)

**Pull request merged**
