### PR TITLE
add FAQ section for supported browsers

### LINKED ISSUE #10310: Document which browsers we support
We should have an authoritative list of browsers + version we intend to support going forward.

### PR DESCRIPTION
**Pull request by kdoh**
Resolves #10310

### CODE REVIEW

**Comment by flamber** [comment]
@kdoh Can we add it to `/docs/faq/supported-browsers.md` instead and a link in `/docs/faq/start.md`, since `/docs/faq.md` is outdated https://github.com/metabase/metabase/pull/11117#discussion_r353435162

**Comment by flamber** [comment]
Is IE11 going to continue the support? #11444
And I think you mean Edge version 44 (https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history), but the question is if only Edge Chromium should be supported.

**Comment by kdoh** [comment]
@flamber Yeah I'll move it to a new spot, missed that part of the conversation in #11117

**Review by paulrosenzweig — APPROVED** [review]

**Comment by paulrosenzweig** [comment]
Maybe we should decide on a threshold to drop IE11 support? It looks like we're at 0.7% of users currently. Honestly, that might be low enough to drop it now, but if not, maybe 0.5%?

**Comment by kdoh** [comment]
@paulrosenzweig (and @flamber too). Yeah in the data we do have from people IE 11 is certainly on its way out. I'm just concerned that there might be folks in an enterprise or government context who might be stuck on it that don't share usage data with us. If there's a solid technical reason to drop it (possibly #11444) then I could certainly be convinced about not signing us up to continue support.

**Comment by paulrosenzweig** [comment]
Ah good point, I hadn't thought that IE 11 would likely be most prevalent among those who don't share data.

I didn't verify this, but I think that IE 11 would be the last roadblock in turning off some of our transpiling rules. Though, with source maps, I don't really mind having them.

**Comment by flamber** [comment]
Yeah, most enterprise-size environments (including governments, hospitals, etc) don't enable statistics, and are the biggest users of legacy systems. I can see that in the municipal here, mostly Win7 with a sprinkle of WinXP :man_facepalming:
But given that Edge Chromium (likely due January 2020) will include [IE Mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode), which will be available on Win7+, then I think it's fair enough to plan on facing out support for IE11 in a near future - like from Metabase 0.35? That doesn't mean we'll break it on purpose, just that it will not be tested.

Perhaps instead of writing version numbers for some of the browsers, it should just say "Current supported official releases", since both Chrome and Firefox changes version every 4/6 weeks. Same will probably happen for Edge Chromium (version 78?).
By the way, isn't Safari v11 [outdated](https://en.wikipedia.org/wiki/Safari_version_history#Safari_11), and v12 by the end of 2019?

**Comment by kdoh** [comment]
@flamber
>  I think it's fair enough to plan on facing out support for IE11 in a near future - like from Metabase 0.35? That doesn't mean we'll break it on purpose, just that it will not be tested.

Yeah that's where my head's at as well. I think we'll re-evaluate every so often and decide what makes sense at the time given the user base. Overall this is mostly meant to be a reference for folks so they know what the minimum threshold of browsers Metabase will run on and to reach as many folks as possible I think we should keep things as broad as makes sense. (for example you can't run it on a browser that doesn't support flex box or ES5). I still think we'll evaluate rendering bugs or on a case by case basis in terms of severity and browser usage.

> By the way, isn't Safari v11 outdated, and v12 by the end of 2019?
I think since v11 was released ~2 years ago we should still try to make sure things don't completely break on it.

**Review by mazameli — APPROVED** [review]
WFM. Thanks for doing this, Kyle.

**Pull request merged**
